### ISSUE TITLE
Implementation of metered connections on Android

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#10035]
## Expected behavior

For v0.16, there are new settings for Android device that allow limiting the synced data if the device is on a Metered connection.
[Notion project page](https://www.notion.so/learningequality/Updates-to-Device-Settings-45529cbcc4f74aeb9b19559228c97579)
[Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773)
[Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#1959b753421648308fb467e21bdaa125)

A [new capability ](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/app/utils.py#L12) should be added and [this Android API](https://developer.android.com/training/monitoring-device-state/connectivity-status-type#DetermineType) will be used to determine if the device is using a metered connection.

This must be done in coordination with the work on the [automatic resource syncing issue](https://github.com/learningequality/kolibri/issues/10019)

**Comment by marcellamaki** [comment]
Superseded by https://github.com/learningequality/kolibri/issues/10662
