### ISSUE TITLE
emphasize message when content renderer is not available

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1003]
Current behavior is confusing because the error is styled the same as the description:

![image](https://cloud.githubusercontent.com/assets/2367265/23562570/d50525d4-fff7-11e6-8644-98c28b9a6c7d.png)

> Kolibri is unable to render this content

This string should be rendered as an error message so it doesn't look like part of the content description. Recommend that we use a [non-dismissible alert](https://josephuspaye.github.io/Keen-UI/#/ui-alert) error:

![image](https://cloud.githubusercontent.com/assets/2367265/23562703/6ddf6a26-fff8-11e6-9b4c-45d2f3d7bcec.png)

**Comment by indirectlylit** [comment]
might also be helpful (at least in the console) to report what renderer it's looking for

**Comment by rtibbles** [comment]
Can put some `logging.debug` statements back in.
