### ISSUE TITLE
Tweaks to skip logic navigation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10060]
For the first issue, the experiences in tension are consistency in label names in the side panel/breadcrumb and quicker navigation. Giving this some thought again, seems it'd be best to change the left folder side panel so that the options there align with the breadcrumb - so, changing it to be as it was before. While it will make navigation "slower" if the user chooses to use that panel, it seems it will create more consistency in expected behavior and there is still always the option for faster navigation through the main card section.

On the second issue, there's a solution here to use a divider, extra space, and placing resources in the order as set on Studio, highlighted in "1a" in the mockup https://github.com/learningequality/kolibri/issues/9043#issuecomment-1022561028

_Originally posted by @jtamiace in https://github.com/learningequality/kolibri/issues/9915#issuecomment-1382594880_

**Comment by marcellamaki** [comment]
Closed with #12737
