### ISSUE TITLE
0.16 - Cannot open Kolibri in Internet Explorer 11

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10086]
## Observed behavior
It's not possible to open Kolibri 0.16 in Internet Explorer 11. There are multiple errors in the console

## Expected behavior
It should be possible to open Kolibri using Internet Explorer 11

## Steps to reproduce the issue
1. Install the the latest [0. 16 build ](https://buildkite.com/learningequality/kolibri-windows/builds/5278) 
2. Attempt to open Kolibri using Internet Explorer 11

## Screenshot

![2023-02-06_17-29-38](https://user-images.githubusercontent.com/79847249/217015755-e1c84028-2298-4af4-bde9-7a8fe99b9717.png)

## Console errors

`HTML1300: Navigation occurred.
auth
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
auth (128,11)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
auth (129,11)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
auth (130,11)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
auth (131,11)
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
auth (132,11)
SCRIPT1002: Syntax error
kolibri.core.default_frontend-0.16.0.dev0+git.20230203234314.js (2,2400867)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (351,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.user_profile.user_profile_side_nav-0.16.0.dev0+git.20230203234314.js (1,684)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.user_auth.login_side_nav-0.16.0.dev0+git.20230203234314.js (1,693)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (357,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.device.side_nav-0.16.0.dev0+git.20230203234314.js (1,682)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (362,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.learn.side_nav-0.16.0.dev0+git.20230203234314.js (1,693)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.facility.side_nav-0.16.0.dev0+git.20230203234314.js (1,698)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.coach.side_nav-0.16.0.dev0+git.20230203234314.js (1,692)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (371,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (373,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (376,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (378,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (381,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (383,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (386,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (388,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (391,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (393,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (396,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (398,9)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
auth (411,29)
SCRIPT5009: 'kolibriCoreAppGlobal' is undefined
kolibri.plugins.user_auth.app-0.16.0.dev0+git.20230203234314.js (2,73263)
`

## Usage Details
Windows 7, 10 - Internet Explorer 11

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Flagging for anyone investigating this that the issue seems to be a syntax error in the default frontend bundle - this suggests that either a dependency we are bundling is not being properly transpiled, or some of our code is not.

**Comment by abhishekd358** [comment]
I just search on internet explore 11 the site perfectly working . no issue at all
