### ISSUE TITLE
0.16 Coach Reports - A previously previewed document is being displayed when using the 'Back' button

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10085]
## Observed behavior
A previously previewed document is being displayed when using the 'Back' button while previewing documents at Coach > Reports > Lesson > Report

## Expected behavior
The correct document should be displayed, not the previously viewed one.

## Steps to reproduce the issue
1. Install the the latest [0. 16 build ](https://buildkite.com/learningequality/kolibri-debian/builds/5894#018619bc-722e-47ff-890f-17600e5df75d) 
2. Go to Coach > Reports > Lesson > Report
3. Click on a document
4. Click the Preview button
5. Click the 'Back' link
6. Select the next document of the same type to preview it

## Video

https://user-images.githubusercontent.com/79847249/217006007-294b2038-3d40-404f-9055-46708cdcb58f.mp4

## Usage Details
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by hyprsyd** [comment]
I'm sorry I'll fix it as soon as possible

**Comment by hyprsyd** [comment]
Hey sorry for the delay I'm starting on this now as I was out of station for a few days.As of now I can see the prop currentContentNode in views>plan>LessonContentPriviewPage>Index.vue is getting updated twice first with the previous content.id and and second the the current one so a page refresh fixes it but thats not how it should be. @rtibbles where should I look ahead to fix this ?

**Comment by hyprsyd** [comment]
@pcenov @rtibbles I think the the problem resides [here](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/plan/LessonContentPreviewPage/index.vue#L227-229) please guide me how and what I can do to solve this issue it's probably some backroute issue

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this in 0.16.0b10

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
