### ISSUE TITLE
Kolibri Resource Sidebar View Update

### ISSUE THREAD

**Issue by tomiwaoLE** [learningequality/kolibri#10092]
## Observed behavior
Currently, users cannot see the currently viewed resource in the sidebar view. 

![image](https://user-images.githubusercontent.com/110987933/217064487-6a0a06c7-98e1-437e-9172-cc4ff353197e.png)

…

## User-facing consequences
Makes it difficult for the user to ascertain which resource is being viewed especially if the user steps away from the platform briefly.

## Fix
Created two possible fixes - with the currently viewed resource included and highlighted in the sidebar view [HERE](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fix?node-id=784%3A14768) .

**Comment by rtibbles** [comment]
Let's go with the second option. If the additional text is too much, we can always simplify it to option 1 later.

![image](https://user-images.githubusercontent.com/1680573/217329120-352e4022-8cc3-44f8-ac7f-c6abc522eae2.png)

![image](https://user-images.githubusercontent.com/1680573/217329170-36763cc8-bba7-4320-a270-4e8d912eda5d.png)

**Comment by tomiwaoLE** [comment]
My preferred solution @rtibbles . Thanks!

**Comment by marcellamaki** [comment]
For 0.16.0, this issue is just to add the string itself to the code so it will be available in the content renderer sidebar display. No implementation of the feature needed at this time.
