### ISSUE TITLE
Clean up previously generated CSV files

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10123]
## Observed behavior
When a new CSV file is generated for session and summary logs, the previously generated files that are stored in the user's database are no longer accessible for download in the UI. A record of the new CSV file request is saved to the logger model `GenerateCSVLogRequest` which contains the facility id, log type (session or summary), the selected start date, the selected end date, and the date that the request was made. There should only ever be one record for each facility and log type combination. The information in this modal is used to scan the database folder `log_exports` and retrieve the previously generated file for download.

Note: For session and summary log files, the file naming convention has been updated to include a date-range selection, with the dates formatted as `YYYY-MM-DD`.
Previous naming convention:
- `{facility_name}_{last 4 digits of facility ID}_{log export type}.csv`

Current naming convention:
- `{facility_name}_{last 4 digits of facility ID}_{log export type}_from_{start date}_to_{end date}.csv`

## Expected behavior
We should remove any files that do not have a record in the database. One way to achieve this is by scanning the folder `log_export`, which contains all exported log files, using the predictable file naming convention, and cross-referencing them with the file records stored in the database. Any session or summary files that do not have a corresponding record in the database should be deleted.

With a 1:1 correlation with the `GenerateCSVLogRequest` record, the database should only contain one exported file for each session and summary log type. A new async task should be created for performing this cleanup, and can be queued whenever a new log export is generated. If the task has a predictable id, it can be ensured that there is only one cleanup task going at once.

More details on the task system can be found [here](https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/tasks.html).

## User-facing consequences
Ensures the database is free from redundant files and optimizes the user's database storage.

## Acceptance Criteria

- [ ] All previously generated session and summary log file exports that lack a corresponding record in the database have been deleted.
- [ ] The previously generated CSV file should be automatically removed from the database upon generating a new one.
- [ ] New python code should be covered by unit tests.

**Comment by Jaspreet-singh-1032** [comment]
Hi @LianaHarris360, I would like to give this issue a try. Can you share some more details or screenshots about how to reproduce and test this issue?

Thanks.

**Comment by LianaHarris360** [comment]
Hi @Jaspreet-singh-1032 Thank you for your interest in working on this. At the moment this issue needs some more details to be clarified before it is ready to be tackled. Once it is fully prepared and ready for contributions, I will follow up with you.

**Comment by Jaspreet-singh-1032** [comment]
Sure @LianaHarris360 , thanks.

**Comment by LianaHarris360** [comment]
@Jaspreet-singh-1032 More context has been added and this issue is ready for contributions. This [PR](https://github.com/learningequality/kolibri/pull/10106) contains more details for reproducing/testing this flow. Feel free to ask any clarifying questions that you may have.

**Comment by Jaspreet-singh-1032** [comment]
Thanks @LianaHarris360, Will check this one.

**Comment by GeekGawd** [comment]
Hi! @LianaHarris360 Could I work on this issue alongside with you and @Jaspreet-singh-1032...

**Comment by LianaHarris360** [comment]
Hi @GeekGawd, @Jaspreet-singh-1032 is actively working on this. If they are open to collaboration, they can respond here to let you know, but it may be easier to explore another issue that you could potentially contribute to.

**Comment by Jaspreet-singh-1032** [comment]
Hi @GeekGawd, I will check if it's possible to divide this into any sub-task and then let you know.
thanks.
