### ISSUE TITLE
Do not use SQLAlchemy Session for Task reads

### ISSUE THREAD

**Issue by vkWeb** [learningequality/kolibri#10120]
Right now, the tasks backend is using SQLAlchemy's session for reading task data from the database. Richard and I think that we should not be using sessions for reading job data because its simply unnecessary for reads in our opinion. 

Addressing this issue requires completion of two tasks:-

- [x] Currently, the tasks API uses `get_orm_job` and `get_job` to get `orm_job` and the Job object. We should use just one function `get_orm_job` to get the `orm_job`, and from that we should deserialize the Job object.
- [x] Do not use `Session` for database reads.

**Comment by Jaspreet-singh-1032** [comment]
Hi @vkWeb. I would like to contribute to this issue. Just wanted to confirm if this issue is currently in progress.
Thanks.

**Comment by vkWeb** [comment]
@Jaspreet-singh-1032 Welcome to our community! 

This issue is currently open for contribution. I've assigned the issue to you, feel free to ask for doubts / clarification if get stuck. All the very best @Jaspreet-singh-1032!

**Comment by Jaspreet-singh-1032** [comment]
Thanks @vkWeb for assigning this issue to me. I was going through the code. wants to confirm do we need to use connection instead of session for the task reads as used here?
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/tasks/storage.py#L311

**Comment by vkWeb** [comment]
Yes @Jaspreet-singh-1032 that's the right code.

**Comment by vkWeb** [comment]
Resolved by https://github.com/learningequality/kolibri/pull/10202
