### ISSUE TITLE
Complete backend integration for metered connection notification

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10142]
## Summary

Follow up to https://github.com/learningequality/kolibri/issues/9845

## Expected behavior
Currently, only the front end was covered for string freeze. The follow up work ensures the modal displays at the point of download, to confirm the user choice. See original issue for full details, and [slack thread for finalized expected behavior](https://learningequality.slack.com/archives/C0LKG14NL/p1676066655721309)

**Comment by bjester** [comment]
This is somewhat related, as it adds behavior for handling network locations where `is_local is False` https://github.com/learningequality/kolibri/issues/10431

**Comment by marcellamaki** [comment]
Superseded by https://github.com/learningequality/kolibri/issues/10662
