### ISSUE TITLE
Linting rules on `console.log` are missing

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10208]
## Observed behavior

It appears, through code review, that linting isn't capturing `console.*` statements. 'We have the core logging library setup to allow deliberate logs to be left in.'

## Errors and logs

Observed https://github.com/learningequality/kolibri/pull/10206/files#r1128608156

## Expected behavior

Linting rules should test against the existence of `console.*` statements.

## User-facing consequences

Potential increased memory usage if logging objects(?)

**Comment by GeekGawd** [comment]
Hi! @bjester I would like to work on this issue, could you give me some more details, how I should approach this issue and if I am not wrong you want to warn the user against console.* statements when the user runs `yarn run lint-frontend` command right and or remove it with `yarn run lint-frontend:format`?

**Comment by bjester** [comment]
Hi @GeekGawd, we should only warn them against using `console.*` statements, that way the dev can then explicitly choose whether it's important to keep or otherwise remove it.

It seems `eslint` has removed `no-console` from their recommended rules, which I'm looking into, but for now I think it would be good to explicitly add it to [Kolibri's rules](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-tools/.eslintrc.js). There may be some `console` statements that have made it into the codebase and they'll also need to be resolved by removal or making an exception. Please let us know if you have questions. Thanks!

**Comment by bjester** [comment]
Following up, it seems eslint wasn't very clear on its removal of `no-console` from the `recommended` rules, refraining to put it in the changelog nor making the change in a way could be easily traced. They did put it in [the migration guide](https://eslint.org/docs/latest/use/migrating-to-6.0.0#-eslintrecommended-has-been-updated), but such a significant change should have made it into the changelog.

For reference https://github.com/eslint/eslint/issues/11267

**Comment by thesujai** [comment]
Hey @bjester, I want to take this up.
