### ISSUE TITLE
Quizzes - No values are being displayed for 'Time spent', 'Best score time' and 'Attempted' 

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10219]
## Observed behavior
When as learner I complete a quiz or a practice quiz I am not seeing any values for 'Time spent', 'Best score time' and 'Attempted'. This is also valid if I attempt to view the reports for the quizzes as a Coach.

## Expected behavior
The values for 'Time spent', 'Best score time' and 'Attempted'  should be displayed correctly.

## Steps to reproduce the issue
1. Install the the latest [0. 16 build ](https://buildkite.com/learningequality/kolibri-python-package/builds/7597) 
2. As a Coash assign quizzes to a Learner and complete them as a Learner
3. Check the quiz reports as a Learner/Coach

## Screenshot

![2023-03-09_16-55-51](https://user-images.githubusercontent.com/79847249/224097771-6a8d806e-5549-48e2-95f7-a7832547d165.png)

## Usage Details
Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
@pcenov I just tried to replicate this on the latest `develop` branch and I'm not able to with either a practice or regular quiz.

Can you double check on your end with the [latest build?](https://buildkite.com/learningequality/kolibri-python-package/builds/7747).

If you still see the issue on your end, I can check it out and see if I can replicate it.

**Comment by pcenov** [comment]
Hi @nucleogenesis - I confirm that this is now not replicable on the latest `develop` branch.

**Comment by radinamatic** [comment]
Closing as not extant anymore. If the 👻  reappears, we'll investigate further 😈
