### ISSUE TITLE
 Improve Coach tabs accessibility - "Report-Learners" tabs on a Reports lesson page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#10254]
In #10212, we embarked on the journey toward improved accessibility of the coach plugin. Part of it is refactoring tabs logic to use new KDS tabs components that are implemented in an accessible manner. This issue is a continuation of that work.

The goal is to use the KDS tabs components for _Report-Learners_ tabs on a lesson page in the coach reports ( _Coach → Reports → Lessons_ → select a lesson → lesson page)

![report-learners](https://user-images.githubusercontent.com/13509191/225319889-01cf2c6f-11ac-4414-84f1-686d2f461377.png)

## Acceptance criteria

- [ ] The current implementation is refactored to use KDS tabs components (`KTabs` or the combination of `KTabsList` + `KTabsPanel`)
- [ ] The new implementation satisfies [these](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) and [these](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/) W3C guidelines (this is already provided by KDS tabs components, however in some cases, a bit of additional Kolibri logic may be needed as well - see comments below)
- [ ] The focus ring shows when navigating with a keyboard and stays on the selected tab after pressing enter

## Comments

- KDS tabs components documentation
  - [Tabs page](https://deploy-preview-426--kolibri-design-system.netlify.app/tabs/)
  - [KTabs component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabs/)
  - [KTabsList component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabslist/)
  - [KTabsPanel component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabspanel)
- You can play around with the _Lessons-Quizzes-Groups-Learners_ tabs that are already implemented with KDS components  to experience the expected behavior
![example](https://user-images.githubusercontent.com/13509191/225308774-6663d3db-680f-4211-ac98-6a550a8f94d6.png)
- In some cases, due to the routing architecture, some additional Kolibri logic may be needed to ensure seamless focus behavior. If you run into issues with the focus ring disappearing after pressing enter on a tab or similar, [useCoachTabs composable](https://github.com/learningequality/kolibri/blob/5806f4ad50db3d96fdd0030d0659861b52a63e67/kolibri/plugins/coach/assets/src/composables/useCoachTabs.js) may help

**Comment by muditchoudhary** [comment]
Hello @MisRob Could you assign it to me? I can work on this. Thanks!

**Comment by MisRob** [comment]
Hi @muditchoudhary, yes, thank you! Even though I haven't finished the second round of my review on your first PR from this category, I am already sure that it's implemented very well overall. Here, you can apply the same approach.

These are great improvements to a11y which matters to us.

**Comment by muditchoudhary** [comment]
> Hi @muditchoudhary, yes, thank you! Even though I haven't finished the second round of my review on your first PR from this category, I am already sure that it's implemented very well overall. Here, you can apply the same approach.
> 
> These are great improvements to a11y which matters to us.

Thanks!!
