### ISSUE TITLE
Improve Coach tabs accessibility - "Report-Difficult questions" tabs on a Reports quiz page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#10253]
In #10212, we embarked on the journey toward improved accessibility of the coach plugin. Part of it is refactoring tabs logic to use new KDS tabs components that are implemented in an accessible manner. This issue is a continuation of that work.

The goal is to use the KDS tabs components for _Report-Difficult questions_ tabs on a quiz page in the coach reports ( _Coach → Reports → Quizzes_ → select a quiz → quiz page)

![report-difficultquestions](https://user-images.githubusercontent.com/13509191/225306457-81f4b1e4-6011-4836-83e1-99e80374bed2.png)

## Acceptance criteria

- [ ] The current implementation is refactored to use KDS tabs components (`KTabs` or the combination of `KTabsList` + `KTabsPanel`)
- [ ] The new implementation satisfies [these](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) and [these](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/) W3C guidelines (this is already provided by KDS tabs components, however in some cases, a bit of additional Kolibri logic may be needed as well - see comments below)
- [ ] The focus ring shows when navigating with a keyboard and stays on the selected tab after pressing enter

## Comments

- KDS tabs components documentation
  - [Tabs page](https://deploy-preview-426--kolibri-design-system.netlify.app/tabs/)
  - [KTabs component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabs/)
  - [KTabsList component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabslist/)
  - [KTabsPanel component](https://deploy-preview-426--kolibri-design-system.netlify.app/ktabspanel)
- You can play around with the _Lessons-Quizzes-Groups-Learners_ tabs that are already implemented with KDS components  to experience the expected behavior
![example](https://user-images.githubusercontent.com/13509191/225308774-6663d3db-680f-4211-ac98-6a550a8f94d6.png)
- In some cases, due to the routing architecture, some additional Kolibri logic may be needed to ensure seamless focus behavior. If you run into issues with the focus ring disappearing after pressing enter on a tab or similar, [useCoachTabs composable](https://github.com/learningequality/kolibri/blob/5806f4ad50db3d96fdd0030d0659861b52a63e67/kolibri/plugins/coach/assets/src/composables/useCoachTabs.js) may help

**Comment by KshitijThareja** [comment]
Hi @MisRob. I'd like to work on this issue. Could you please assign it to me, if possible?
Thanks :)

**Comment by KshitijThareja** [comment]
@MisRob I was just playing around with the application. I tried to make a new quiz while on the `develop` branch but when I click on New quiz option, the screen seems to be loading forever. So, I switched to the `release-v0.16.x` branch and things were working well. I added a quiz from there and then again switched to the develop branch. But again I wasn't able to access the Reports and Plan pages.
I don't know if it's just me or it's the same for everyone, might possibly be a bug somewhere.

Here's the screenshot.

![error](https://github.com/learningequality/kolibri/assets/116485536/81c32e20-5a3f-4809-96c6-e0dc291f886f)

And this is the screenshot of the New quiz page while it's stuck at loading screen.

![loading](https://github.com/learningequality/kolibri/assets/116485536/78b58b54-b817-4b9a-8fb7-ddd9d22e34f2)

Should I base my code off the `release-v0.16.x` branch then?

**Comment by MisRob** [comment]
Hi @KshitijThareja, you're welcome to work on this, thanks for volunteering. This issue is an important a11y improvement. I'd recommend checking all links and the first PR that you can use as a template. Recently, we received a really good pull request from @muditchoudhary who resolved this for another tabs, so you could study their pull request and our feedback https://github.com/learningequality/kolibri/pull/11501. The approach here will be the same.

I'm sorry you experienced troubles on `develop`. I think we have a fix for this in progress but it probably isn't merged yet. You're welcome to work from the 0.16 branch if you don't mind that later on we will need to rebase your work to develop. It shouldn't be complicated since there shouldn't be many conflicts in this particular area. We can also help with the rebase.

**Comment by KshitijThareja** [comment]
Sure 👍
And thanks! I'll go through the resources and will try to make a pr soon.
