### ISSUE TITLE
User is not appropriately alerted to failures of the merge workflow when connection to the remote server is lost

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10268]
Thanks @jredrejo, as always we are dealing with complex flows... I just tried again with the latest build assets and it's still not fully functioning correctly as the user is left guessing what is going on unless the console is being opened. Here are the main scenarios the way I see them:

Scenario 1: The target server is stopped before pressing the Continue button. In that case there's no message displayed to the user and only a `410 Gone` error in the console:

https://user-images.githubusercontent.com/79847249/225590784-529d6945-721e-4808-aaac-9051d82bd13c.mp4

Scenario 2: The target server is stopped after pressing the Continue button. In that case I do see the `Remotely preparing data: MorangoError` however nothing happens after restarting the target server and clicking the RETRY button - I have to manually refresh the page and start over in order to complete the process.

https://user-images.githubusercontent.com/79847249/225592996-1cfcd6d1-b930-4e50-8524-07861e23c7d3.mp4

Scenario 3: The target server is not being stopped but there are network interruptions before or after pressing the Continue button. In that case it's somewhat clearer to the learner what is going on however it also involves starting over the process.

https://user-images.githubusercontent.com/79847249/225603372-21de70cd-c9ca-45bb-88dc-50d4a4d59f2b.mp4

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/10247#issuecomment-1471786755_

**Comment by bjester** [comment]
We can potentially handle some of the disconnection edge cases and provide UI feedback once the `DeviceConnectingModal` is complete
