### ISSUE TITLE
Device management PIN - Consider masking the input on the Learn-only device

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10275]
## Observed behavior
When I input the PIN on a Learn-only it is fully visible and could be seen by a bystander. 

## Expected behavior
The PIN input value should be masked in the same way a password is.

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/6331/jobs/0186ea8c-f487-468c-b52d-856b7f05e1b7/artifacts/0186eeb5-7c32-43b9-bc8b-bea11c9d2234) 
2. Setup a full facility and add a Device management PIN at Facility > Settings
3. Attempt to input the PIN value as a learner on a Learn-only device

## Screenshot

![2023-03-17_13-20-13](https://user-images.githubusercontent.com/79847249/225891287-29bee411-fb23-448f-87fd-b8ff289ae95d.png)

## Usage Details
Windows 10, Ubuntu 22  - Chrome

**Comment by radinamatic** [comment]
Fair point, and would also suggest we consider implementing one of those _eye_ icons to reveal and hide the password/pin that is being inputted:

![Selection_129](https://user-images.githubusercontent.com/1457929/225894081-83bf3e9b-b8b5-4da9-a02e-7f71034d16f5.png)

**Comment by akolson** [comment]
@radinamatic I agree, we should enhance the `KTextbox` component for type password to contain a password reveal.

**Comment by akolson** [comment]
@pcenov the password masking issue has been resolved in https://github.com/learningequality/kolibri/pull/10264 and PR has been updated accordingly.
