### ISSUE TITLE
Device management PIN - Missing modal indicating that the PIN will not be affected

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10274]
## Observed behavior
An incorrect modal is displayed when there is a PIN and the user has clicked the 'Reset to defaults' button.

## Expected behavior
As specified in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=969-16669) when there is a PIN and the user clicks the 'Reset to defaults' button then there should be displayed a modal explaining that the PIN value will not be affected.

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/6331/jobs/0186ea8c-f487-468c-b52d-856b7f05e1b7/artifacts/0186eeb5-7c32-43b9-bc8b-bea11c9d2234) 
2. Setup a full facility and add a Device management PIN at Facility > Settings
3. While at Facility > Settings click the 'Reset to defaults' button

## Screenshot
![2023-03-17_13-08-43](https://user-images.githubusercontent.com/79847249/225889825-2022580d-a33a-4541-a0a1-793d51e61718.png)

## Usage Details
Windows 10, Ubuntu 22  - Chrome

**Comment by akolson** [comment]
This seems a little odd. From the latest `develop`, the modal was already updated with the string in [this pr](https://github.com/learningequality/kolibri/pull/10074); Also, some tweaks were made to the initial design based on this [comment](https://github.com/learningequality/kolibri/issues/9789#issuecomment-1400983669)

Current UI from develop:
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/5203639/226019520-0c50a343-0232-4a4e-8c01-95db7b944c72.png">

**Comment by marcellamaki** [comment]
I do see this on the alpha8 pex (for reasons that are honestly a bit mysterious to me, because it looks like the strings were added before that release was tagged, but... that is besides the point) but it is fixed on the latest develop. I will close as resolved and we can reopen if for any reason there is a problem again in the future.
