### ISSUE TITLE
Username and icon not center-aligned in the app bar

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10288]
## Observed behavior

The username and icon are off-center, rather than correctly aligned on the app bar.

## Errors and logs

<img width="1000" alt="image (18)" src="https://user-images.githubusercontent.com/17235236/226720476-438d3ab5-3ac0-432f-b3dd-6c4434ac8f76.png">

…

## Expected behavior
The username and icon should be center aligned across all screen sizes - xs, sm, med, lg. 

## User-facing consequences
Not to spec

## Context
Alpha 7 bug bash

**Comment by sivangbagri** [comment]
Hii I would like to work on this issue , please assign me this issue .
@marcellamaki

**Comment by MisRob** [comment]
Hello @sivangbagri , thank you for your interest. You're welcome to take this issue on. If you haven't done so already, please have a look [at our developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html) and start your working branch from the `develop` branch where your pull request will be targeted into. As part of your pull request, you're welcome to add yourself to the list of contributors in _AUTHORS.md_ file.

**Comment by xauravww** [comment]
I would like to contribute to this issue. I can help resolve this issue. Please let me know .

**Comment by sivangbagri** [comment]
Hii @MisRob , I have figured out the solution through inspect but I am unable to find the particular html file of this page in the project directory , can you please help me in this??

**Comment by MisRob** [comment]
Hello @sivangbagri, I'd recommend installing Vue Devtools (https://devtools.vuejs.org/) which will allow you to inspect what components are on a page. Then you can locate files in the codebase by searching by component names.

**Comment by Pursottam6003** [comment]
Hello @MisRob . I would like to work on this issue please allow me to assign in this issue I will be extremely happy to  contribute in these issue

**Comment by rtibbles** [comment]
Fixed in #10366
