### ISSUE TITLE
Finalize Studio remote browsing integration

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10280]
## Observed behavior
https://github.com/learningequality/kolibri/pull/10227 was merged with some fairly involved special case logic for Studio that uses the existing RemoteChannelsEndpoint.

Now that the implementation of the public APIs on Studio have been finalized and merged to unstable, we can now do further testing of this flow using unstable as our upstream Studio, and remove most of th

## Expected behavior
With the new API endpoints in place, we should be able to check Studio's info endpoint, and confirm that it is indeed upgraded to a version equivalent to Kolibri 0.16.0 (using the minVersion composable logic), and then display it if so.

We should then be able to browse the device exactly like any other, with current device info that sets the `baseurl` to the set Studio URL in Kolibri configuration.

To test with unstable we can override this configuration by setting this environment variable:
```
KOLIBRI_CENTRAL_CONTENT_BASE_URL=https://unstable.studio.learningequality.org/
```

**Comment by bjester** [comment]
Added https://github.com/learningequality/kolibri/issues/10431
