### ISSUE TITLE
Import from Kolibri Studio - Missing 'Language' label

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10284]
## Observed behavior
The 'Language' label is not displayed above the 'All languages' drop-down, instead I see: CommonCoreStrings.languageFilterLabel

## Expected behavior
The  'Language' label should be displayed.

## Steps to reproduce the issue
1. Install the the latest develop build.
2.  Navigate to Channels > Import from Kolibri Studio

## Screenshot

![2023-03-21_16-37-37](https://user-images.githubusercontent.com/79847249/226653763-0f5d573b-27c7-4c61-bc22-ae56f047f1aa.png)

## Usage Details
Windows 10, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
Seems like a victim of string consolidation and deduplication. Pretty sure the string exists though!

**Comment by radinamatic** [comment]
Yep, I checked, it's there on Crowdin... 😌 
``CommonCoreStrings.languageLabel``

**Comment by radinamatic** [comment]
Closing as it's tracked in #10328.
