### ISSUE TITLE
Double focus online on the password for the sign-in page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10281]
## Observed behavior
Sometimes, there is a double focus online on the password for the sign-in page

## Errors and logs
![Screenshot 2023-03-20 at 3 30 36 PM](https://user-images.githubusercontent.com/17235236/226446284-3b63eeff-9322-48e5-b21c-67eb7431ef88.png)

## Expected behavior
Should only be one focus outline

## User-facing consequences
It doesn't look very nice, and might be confusing to those navigating by focus outline (and possible screen reader, if two different elements are indeed focused).

## Steps to reproduce
Sign in, and then use the TAB key to navigate. Does not reproduce _all_ of the time so it might take some wrangling. 

Does seem to also happen on hover

## Context
`develop`, Mac 13, Chrome 

This might need to be fixed in KDS

**Comment by rtibbles** [comment]
When I have observed this it seems to trigger much more frequently if the Enter key has been used to finalize input of the username field on the previous screen.

**Comment by radinamatic** [comment]
Interesting, no issues in Firefox, and I almost always use the full keyboard navigation in this flow (Enter key included).

**Comment by MAYANKpandey14** [comment]
Hey, I have been trying reproducing this bug , no issues for me in Chrome , MacOS catalina . 
Using keyboard navigation and Enter in the previous screen.

**Comment by MisRob** [comment]
I too observed this from time to time recently, and like @rtibbles I had an impression it may be related to hitting Enter on the previous screen
