### ISSUE TITLE
Facility plugin - The navigation defaults to the main facility

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10294]
## Observed behavior
As noted by @radinamatic if I have imported an additional facility and I go to the Facility plugin I am being prompted to select a facility. When I select the imported facility I am correctly redirected to the Classes tab, however if I navigate to any of the other tabs then I am seeing the data for the main facility. The facility id value is also no longer displayed in the URL.

Note that the navigation in the Coach plugin is functioning correctly.

## Expected behavior
The data for each selected facility should be displayed correctly when navigating within the Facility plugin.

## Steps to reproduce the issue
1. Install the the latest `develop` build.
2.  Setup a full facility and import an additional facility.
3. Navigate to the Facility plugin and select the imported facility.
4. Attempt to view any of the other tabs such as Users, Settings or Data

## Video

https://user-images.githubusercontent.com/79847249/226886910-e1674124-3015-4acd-9ed2-150b53fcb4be.mp4

## Usage Details
Windows 10, Ubuntu 22  - Chrome, Firefox

**Comment by rtibbles** [comment]
This definitely seems like a regression from the changes to the app bar. To fix this we would need to make sure that the top tabs are encoding any current facility id from the route into their routes.

It is worth checking the coach plugin for the same behaviour as that can also select a facility.
