### ISSUE TITLE
SetupWizard: Select facility should redirect if it doesn't have what it needs

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#10292]
## Observed behavior

Users can find themselves on the Select Facility page without having a device selected as reported by @akolson on [Notion](https://www.notion.so/learningequality/A-user-should-not-be-able-to-proceed-past-the-Select-facility-page-if-an-import-address-has-not-be-93ffa32011374777b5e49171c5791b35).

I don't know how to replicate exactly but suspect that going back and forth between that page and it's previous/next pages is liable to cause the issue. 

Additionally, until #10240 is merged, this will be blocked as decisions there will impact whether this bug even remains a problem. Perhaps that PR will also resolve this issue.

**Comment by akolson** [comment]
@nucleogenesis after looking around for quite a bit, this is not an issue anymore.
