### ISSUE TITLE
No error message shown when entering a user name that already exists on the LOD

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10306]
## Observed behavior
Reported by: @akolson and @jtamiace in the alpha-10 bug bash.
When going through the `Group learning → Device Name → Learn only Device → Create Account` workflow and creating an account for an existing facility, if the entered username already exists on the Learn Only Device, no error message is returned.

![Mar-23-2023 13-07-35](https://user-images.githubusercontent.com/46411498/227550281-ff76b6d1-d299-488f-9ef1-ee90c3e856d3.gif)

## Expected behavior
An error message should be returned specifying what exactly went wrong.

## User-facing consequences
Users will not understand why an account fails to be created, if they have entered a username that already exists, when joining an existing facility.

## Context
0.16.0-alpha10

**Comment by marcellamaki** [comment]
Fixed with https://github.com/learningequality/kolibri/pull/10295
