### ISSUE TITLE
When a LOD has joined a facility without the PIN setting enabled on the facility, they should not access the Device Tab

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10302]
## Observed behavior
When preparing for alpha-10 bug bash, I set up a LOD account on @rtibbles's  test facility, which at that state, did not have the device PIN setting enabled on the facility settings. 

I was able to see the device plugin in the menu, and when I clicked it, I got a blank screen. 
…

## Errors and logs
No errors in console or network tab

https://user-images.githubusercontent.com/17235236/227366442-29b55e1f-d228-4b6a-8a3f-9a31900adf68.mp4

## Expected behavior
For LODs where the PIN setting is not enabled on the facility, the learner should still be able to access the Device tab. The PIN setting can be seen as a way of _restricting_ access, rather than granting access that otherwise wouldn't exist.. i.e. the PIN setting version is more restricted, and the non-PIN LOD has access to the tab. 

## User-facing consequences
LODs will not be able to access the device tab.

## Steps to reproduce
- Create an LOD account on an existing facility, where the facility _has not_ enabled the PIN in the facility settings 
- Access the device tab 

## Context
0.16.0 alpha10

**Comment by akolson** [comment]
Hi @marcellamaki. I have been trying to replicate this, but unsuccessful so far. @rtibbles is it possible to revert the test facility to the state before the setting up the pin or even momentarily disable the PIN?

**Comment by pcenov** [comment]
@marcellamaki and @akolson I am also not able to replicate this in 0.16.0 alpha10 - my user is able to access the Device tab if a PIN has not been enabled.

**Comment by rtibbles** [comment]
The testing server has had the PIN removed now, @akolson.

**Comment by akolson** [comment]
I was able to replicate this with @rtibbles and pointers regarding a potential fix shared. We should be having a fix for this pretty soon. :)
