### ISSUE TITLE
When upgrading or updating a channel, if they have previously been ordered, the ordering of the channel will be lost

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10309]
## Observed behavior
Running an upgrade on a channel deletes the ChannelMetadata object, so any previously explicitly set ordering relative to other channels is lost.

It's possible that this ordering is also lost just when adding more resources to an already existing channel without an upgrade, but this needs to be confirmed.

Looking at the code, however, it seems unlikely: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/utils/annotation.py#L782 - so this is probably only happening for upgrades.

## Expected behavior
The order of the channel should be preserved across upgrades and updates.

## User-facing consequences
Careful planning of the order of channels is lost.

## Steps to reproduce
1. Import 2 channels.
2. Order the channels so that the currently second one is first.
3. Upgrade the now first channel.
4. See it move to second.

Do a similar procedure, but only import additional resources this time, and see if that bug occurs there.

## Context
 * Kolibri version: 0.15+

## Hints for resolution

To resolve this, we would need to persist any explicitly set ordering across upgrades. This is probably best done in the channel import logic.

In this method: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/utils/channel_import.py#L952 the current channel order can be read before the import runs, and then it can be set again on the channel object if the import did indeed run.

Creating a test to ensure this is preserved would also be helpful. This could be added to the channel upgrade tests here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/test/test_channel_upgrade.py

**Comment by im-NL** [comment]
I'm having trouble trying to figure out how to upgrade the channel. I read the docs and thought maybe I could upload my own resource into kolibri and then update _that_ to reproduce this bug but decided to ask first instead 
![image](https://github.com/learningequality/kolibri/assets/75334285/7e05c6a5-cf5b-4104-a70c-312d4780421a)

**Comment by radinamatic** [comment]
@im-NL You are on the right track: the easiest way to try to replicate this is to have your own channel(s) on [Kolibri Studio](https://studio.learningequality.org/) (register a new account if you don't have one), update or add some new resources, and publish them to be able to (re)import & update (use the channel token) in your Kolibri installation.
