### ISSUE TITLE
‘Select device’ — device flickers

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10329]
## Observed behavior
Reported by @bjester in the alpha9 bug bash 

The RPi @ richard’s home was returning a 500 on the info endpoint, but it was flicking as available / unavailable

## Expected behavior
If unavailable, it should have been unavailable the whole time

**Comment by marcellamaki** [comment]
@radinamatic - just bumping this as needs re-review from you or @pcenov for confirmation that this is still occurring. 

For a bit more context, this would be in a place where you can select a device from the pop up modal (you could look at the sync facility flow or import facility flow, perhaps) and have this "flickering" or rapid switching back and forth between being available to select and a disabled option. 

Probably worth trying on a variety of different network speeds/throttling, and perhaps checking local network vs. zerotier in case the zerotier testing was a factor.

Thank you!

**Comment by radinamatic** [comment]
I remember trying to replicate this initially, and then it fell through the cracks, my apologies...

We might even have commented on that in the dev meeting and/or iteration planning, that since I was never able replicate the flicker in the local network, it might be a Zerotier issue? Or am I confusing it with another problem...?

**Comment by pcenov** [comment]
Hmmm I'm always keeping at least one additional device in my local network and have never observed any flickering in Select device' so I would also point a finger at Zerotier.

**Comment by rtibbles** [comment]
It does specifically only seem to happen when the info endpoint on the remote Kolibri returns a 500, so it might be harder to replicate, especially now that @akolson has resolved the issues that seemed to cause the 500s most regularly!

**Comment by marcellamaki** [comment]
We will close this as resolved for now, as QA team has been unable to replicate. We can reopen, or open a more specific issue, if the problem comes up again during the critical workflows and integration testing
