### ISSUE TITLE
After changing facility, promped to sign into the original facility

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10334]
Reported by @jamalex during the alpha9 bug bash

## Observed behavior
After migrating user, it says “you were automatically signed out due to inactivity”, and then asks me to sign into the original facility, not the new facility I’ve been migrated into.

## Errors and logs
<img width="685" alt="Untitled (6)" src="https://user-images.githubusercontent.com/17235236/228268585-1cd07d23-d6f6-4344-9129-609537de4133.png">

## Expected behavior
I would have expected:
- If it’s not going to auto-log me into the new facility, a more meaningful message (than “due to inactivity”) would be nice.
- It should show the new facility I migrated to, otherwise I’m likely to put my username in here and fail.

**Comment by LianaHarris360** [comment]
I am unable to reproduce this issue, it might be OS specific. It happened to @jamalex on Windows 11 in the Chrome browser, using the windows installer.

**Comment by bjester** [comment]
I'm unable to reproduce either on Linux.

**Comment by radinamatic** [comment]
@LianaHarris360 and I were also not able to reproduce this issue: after merging accounts and joining her facility, I did not have any other to sign in on my device.
