### ISSUE TITLE
Ensure Vuex loading state is properly managed in all pages post CoreBase Refactor

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10336]
## Observed behavior
Since the `CoreBase` refactor, loading state has been inconsistently managed across all plugins, resulting in "jumpy" or flashing pages and an overall non-smooth user experience.

## Expected behavior
As the "loading" state in Vuex was not changed by the refactor, this should still be available for tracking the loading state, and should be used to properly display the page linear loader.

Tasks: 
- [ ] #10455 
- [x] #10729 

## User-facing consequences
Glitchy or flashing UI. Loading status is not clearly communicated and can be confusing.

## Context
`develop`

**Comment by bjester** [comment]
One of the high level parent components should be handling the loading state.
