### ISSUE TITLE
No clear way to proceed to join a facility when there is no new admin account to "take over"

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10332]
Reported by both @rtibbles and @jamalex in the alpha9 bug bash

## Observed behavior
I tried to join a facility when I had the same username as the superadmin on the other device. When I tried to do the merge, it asked me to enter a password, and then it asked me to choose a new superadmin for my device, but there’s no one else to choose, so I am stuck.

**Comment by jredrejo** [comment]
This seems to be a duplicated of #10333
