### ISSUE TITLE
Text overlap on coach > plan: manage resources section

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10340]
## Observed behavior
For resources with longer channel titles or resource titles, text overlaps

## Errors and logs

<img width="725" alt="Screenshot 2023-03-29 at 9 34 42 AM" src="https://user-images.githubusercontent.com/17235236/228555363-99beaae6-1fa4-453a-9304-43563480365f.png">

## Expected behavior
Items should either expand to account for all text, or be truncated

## User-facing consequences
Text becomes illegible 

## Steps to reproduce
Import "African storybook library (multiple languages)" or another channel with a long name, and select some resources with long titles.

## Context
`develop`

**Comment by Pursottam6003** [comment]
Hey, I am interested in working on this issue. Could you please assign it to me so we can get started? @MisRob

**Comment by MisRob** [comment]
Hi @Pursottam6003 , thank you for your interest. You're welcome to take this issue on. If you haven't done so already, please have a look at [our developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html). This issue is to be resolved on the `develop` branch so please open a pull request into `develop`. If you have any problems running Kolibri locally or have questions about this issue, you can use the comments section on this page. As part of your pull request, you're welcome to add yourself to the list of contributors in _AUTHORS.md_ file.

**Comment by Pursottam6003** [comment]
thank you @MisRob

**Comment by Pursottam6003** [comment]
Hello @MisRob  and @marcellamaki  
As per the guidelines i had set up the project and make some changes into the code 

![image](https://user-images.githubusercontent.com/81693090/229258279-182ad8f0-4309-4dcc-8950-0e76033593fc.png)


inside the **kolibri/plugins/coach/assets/src/views/plan/LessonSummaryPage/ResourceListTable.vue**  

For now i have used "white-space:nowrap" and Overflow: hidden to deal with the overlapping text 
But i am facing the difficulty in mobile view 

Here the **Remove** button is getting over the text

![image](https://user-images.githubusercontent.com/81693090/229258613-bcda1311-5719-44a1-b752-437648d56535.png)

Could you please guide me

**Comment by Pursottam6003** [comment]
@marcellamaki  could you please review the pull request currently it passes all the tests

Thank You

**Comment by MisRob** [comment]
Hello @Pursottam6003, regarding your questions above, I'd recommend waiting for a reply before submitting a solution if some clarification is needed. We've received several contributions lately and are gradually working on answering clarification questions and reviewing pull requests. Please have patience with us, it may take us a couple of days. Do you still need us to reply to https://github.com/learningequality/kolibri/issues/10340#issuecomment-1492776608?

**Comment by Pursottam6003** [comment]
I am really sorry🙇🏻‍♂️  for the inconvenience. Sure I will wait 😊

**Comment by MisRob** [comment]
No need to apologize. I can see that @thanksameeelian has already posted initial feedback. If you have some questions about the next steps, please post them in the pull request.

**Comment by rtibbles** [comment]
Fixed in #10369
