### ISSUE TITLE
Change facility - The 'Change' option disappears for all users after having changed my facility as a learner

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10346]
## Observed behavior
The 'Change' option disappears for all users after having changed my facility as a learner.

## Expected behavior
Unless otherwise specified the 'Change' option should still be available for the rest of the users.

## Steps to reproduce the issue
1. Install the latest Kolibri 0.16.0a10 build
2. Go through the 'On my own' setup flow and create a facility with different type of users
3. Sign in as a learner and change your facility
4. Attempt to do the same with another user

## Video
https://user-images.githubusercontent.com/79847249/228603933-116b38f8-8461-46e1-994f-cfe8431be5ba.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by photon0205** [comment]
I would like to work on this issue @radinamatic

**Comment by pcenov** [comment]
@radinamatic This issue is no longer extant in kolibri-0.16.0a13 and can be closed.
