### ISSUE TITLE
Missing string on snack bar when saving user edits

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#10353]
## Observed behavior
When editing a user and clicking on the "save" button, a snack bar appears to be missing the correct string.

## Errors and logs
[screen-capture.webm](https://user-images.githubusercontent.com/103313919/228831553-57fe4a54-a721-41a1-804b-2c83609c493b.webm)

## Expected behavior
The snack bar message should clearly indicate whether the changes have been successfully saved 
## Steps to reproduce
Log in as a superadminor 
Navigate to the user profile you want to edit.
Make some changes to the user details.
Click on the "save" button.
Observe the snack bar message that appears at the bottom of the screen.

## Context
 * Kolibri version: devlope

**Comment by photon0205** [comment]
I want to work on this issue @AllanOXDi

**Comment by AllanOXDi** [comment]
@photon0205 Sure! Please take it on. Do let me know if you need any assistance or if there's any specific information that would be helpful for you to have.

**Comment by Pursottam6003** [comment]
Hii @AllanOXDi , @MisRob I would like to work on it please assign this issue to work

**Comment by rtibbles** [comment]
Fixed in #10359
