### ISSUE TITLE
hide search bar when there are no users?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1036]
Currently, seems a bit broken to have nothing happen when you type in here: 

![image](https://cloud.githubusercontent.com/assets/2367265/23730798/56c241b8-041e-11e7-9ecf-dc5903cd4f67.png)

**Comment by indirectlylit** [comment]
not critical - removing milestone

However, flaging this as question about global patterns in the Filter section of the style guide (cc @khangmach @jtamiace)

**Comment by MauHernandez** [comment]
Hello everyone. 

I was developing a fix for this issue nevertheless seems somewhat impossible to have 0 users since actually there has to be always an admin, therefore I saw as an option to create a new "function" for when there's more than 1 user:
```
otherThanAdmin(){
    return this.users.length > 1;
}
```
but I don't know if that would be a solution or if this one is presently still an issue. 

Cheers.

**Comment by rtibbles** [comment]
Since the device owner was removed and the first created user is also a facility user, it means that this situation can never arise.

So, should we hide the search when there are only admins? When there is only one user?

@khangmach @jtamiace?

**Comment by khangmach** [comment]
I don't like hiding the search when there is only one user/one admin for two reasons:

- Instantiates an inconsistent pattern for tables (especially in the future)
- I think there is a huge benefit in showing a a user what functions (filtering in this case) are available even if there's no immediate benefit or anything actionable at that moment (currently only one user). 

There was a similar issue where we were debating whether to remove the "Exam visibility" column if there weren't any groups, but we decided that it was beneficial to show the column at all times to show the functionality was available.

**Comment by rtibbles** [comment]
Sounds good. I guess the only possibility here is in the multi-facility scenario, where a superuser is looking at another facility that is empty? But that seems like a very edge case, and the desire for UI consistency might override that.

Let's close this then!

**Comment by indirectlylit** [comment]
So the reason it felt 'broken' was that when you type in the search box, there's no user feedback. I agree with @khangmach's points but we haven't addressed the original issue.

This is something we should standardize, but perhaps the text

> No users exist

should update to be

> No users match 'QUERY'

and that will give feedback to the user that things are working?

**Comment by indirectlylit** [comment]
oh I'm sorry, I missed that the situation can no longer arise
