### ISSUE TITLE
Remove vendored ipaddress module when we drop Python 2.7 support

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#10363]
## Summary

In order to better handle functionalities associated with ip addresses, there is need to implement a utility library that can be used across the platform.  [`ipaddress`](https://github.com/python/cpython/blob/main/Lib/ipaddress.py) has been vendored however, it only supports python 3+. 

As such,  this task is to remove the vendored `ipaddress`, which we added to provide support for `python 2.7`.

**Comment by rtibbles** [comment]
I think we can probably let this lie, and just focus on unvendoring it when we drop Python 2.7 support.

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/11654
