### ISSUE TITLE
Clear button not visible  properly in Learn > Library > Channels selection box 

### ISSUE THREAD

**Issue by Pursottam6003** [learningequality/kolibri#10370]
## Observed behavior

I was just  going through the learn > Library section  where I found that the **cancel button** is n**ot visible especially for long channel names** 

![image](https://user-images.githubusercontent.com/81693090/229312086-dbb855c1-f316-4b29-ac66-68bcc9a1dd91.png)

Even the channel name  text is overlapping the  section so I think it needs some improvements 
## Errors and logs

…

## Expected behavior

It should either wraps the text or hides the text or  append the with ...

Eg channel_name = kolibri_education_foundation_chapter13

can be change as : kolibri.....chapter13            or            kolibri_education_foundation....

## User-facing consequences

Make sure you have at least some resources locally

## Steps to reproduce

1. Download any resources channels pick longer  resources channels  names
2. Navigate towards the learn > library 
3. On the left side there is a sidebar 
4. Inside the sidebar we have the option to select channels 
5. If you selected longer channel you will unable to see the cancel icon its overlaps with the sidebar

## Context

I would like to solve this issue  so if its possible kindly assigned me 

thank you

**Comment by Pursottam6003** [comment]
Hello @MisRob  @marcellamaki I have solved this issue please assign me this issue 

![image](https://user-images.githubusercontent.com/81693090/229361327-e8dabdf6-dc09-40b8-bdef-95b6a48ec3ac.png)

It would be very helpful to me 

Thank You

**Comment by MisRob** [comment]
Thank you, @Pursottam6003, I'm assigning you then. Using `TextTruncatorCss` here would be good if possible.
