### ISSUE TITLE
Update developer documentation to remove 0.15 provisioning recommendation

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10376]
## Summary

While the new setup wizard was in progress, we updated the developer documentation to recommend starting with the `release-v0.15.x` branch. Now that the setup wizard has been integrated, we can now remove this special circumstance:
https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#checkout-release-v0-15-x

**Comment by jose-hy** [comment]
Hello, I would like to work on this issue!

**Comment by bjester** [comment]
Hi @jose-hy,

Thank you for your interest. These two sections in the docs can be removed:
- https://github.com/learningequality/kolibri/pull/9592/files#diff-8694be4b82420c24034980d33221b4966598eb15bfa1baf64e09880695072863R60-R69
- https://github.com/learningequality/kolibri/pull/9592/files#diff-8694be4b82420c24034980d33221b4966598eb15bfa1baf64e09880695072863R252-R257

If you would read it through after removing them, to make sure the setup instructions make sense and I didn't miss anything, that would be great!

**Comment by rtibbles** [comment]
Fixed in #10424
