### ISSUE TITLE
Content Length mismatch when fetching thumbnails from another device

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10394]
## Observed behavior
During Remote Content Dev bug bash, reported by @rtibbles 

## Errors and logs
net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)   

## Context
`develop`
Source device was windows, viewing device Ubuntu

**Comment by rtibbles** [comment]
This was resolved by #10562 , it seems.
