### ISSUE TITLE
Kolibri 0.16 - Missing translation for the Language label

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10397]
## Observed behavior
The label~s~ for ~CommonCoreStrings.langagueFilterLabel and~ `CommonCoreStrings.language` are not displayed. See the attached screenshots. 

## Expected behavior
The labels/translations should be displayed correctly.

## Steps to reproduce the issue
1. Install the latest Kolibri 0.16.0 build
2. View the details for a resource or attempt to import resources.
.
## Screenshot~s~

**First issue has been fixed** | **This is still extant**
--|--
![2023-04-06_12-41-44](https://user-images.githubusercontent.com/79847249/230423962-2c7f39e0-1b10-45ca-8f3b-1caaa35ed55e.png) | ![2023-04-06_16-58-55](https://user-images.githubusercontent.com/79847249/230423984-2568a0fa-77c4-4597-9134-03d535e3167e.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Point of clarification, the asset @pcenov was using was from this PR: https://github.com/learningequality/kolibri/pull/10389, that may not have been up-to-date with the latest `develop`.

We'll re-check to confirm tomorrow, when #10389 has been rebased.

**Comment by pcenov** [comment]
@radinamatic the CommonCoreStrings.langagueFilterLabel issue is fixed in https://github.com/learningequality/kolibri/pull/10412 while the second one for CommonCoreStrings.language is still extant.

**Comment by radinamatic** [comment]
Thank you for re-testing, @pcenov !

Will keep this open for the extant instance then 👍🏽
