### ISSUE TITLE
Kolibri 0.16 - Missing translation for the 'Copy to clipboard' button

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10399]
## Observed behavior
See the attached screenshot.

## Expected behavior
The translation should be displayed correctly.

## Steps to reproduce the issue
1. Install the latest Kolibri 0.16.0 build
2. Go to Device > Info and click the Show button.

## Screenshots

![2023-04-06_16-43-03](https://user-images.githubusercontent.com/79847249/230424688-a40a5712-8110-402d-8054-058f150fd0d4.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
String is translated on Crowdin, and I see in the code here:

https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-common/components/AppError/TechnicalTextBlock.vue#L89

**Comment by AllanOXDi** [comment]
I was not able to reproduce this. It must have been fix by @marcellamaki recent  PR for the string updates.
<img width="1451" alt="Screenshot 2023-04-13 at 22 54 23" src="https://user-images.githubusercontent.com/103313919/231869183-eaf6bf46-8447-4449-a851-1535c42d4a8e.png">

**Comment by pcenov** [comment]
Hi @AllanOXDi both me and @radinamatic are still seeing that button as not being localized when testing with the following build assets: https://buildkite.com/learningequality/kolibri-python-package/builds/8047 (latest develop) and the build artefacts from this PR: https://github.com/learningequality/kolibri/pull/10487 so I am a bit puzzled why is this the case and how can we be sure that we are testing the latest translations. Could you please have a look at what could be the reason for the discrepancy?

**Comment by AllanOXDi** [comment]
Thanks @pcenov, I will be taking a look at it gain today.
