### ISSUE TITLE
Kolibri 0.16 - Missing translation for the 'Add new address' modal

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10396]
## Observed behavior
The label for CommonCoreStrings.newAddressTitle is not displayed. See the attached screenshots. 

## Expected behavior
The label/translation should be displayed correctly.

## Steps to reproduce the issue
1. Install the latest Kolibri 0.16.0 build
2. Either attempt to import a facility in the Setup Wizard or changing the facility if you have a user created through the 'On my own' flow.

## Screenshots
![2023-04-06_18-07-45](https://user-images.githubusercontent.com/79847249/230422205-796e6989-18cc-481d-8c31-1ca2d45b5da4.png)

![2023-04-06_12-07-39](https://user-images.githubusercontent.com/79847249/230422231-881ad8d9-f166-4126-9b76-6b0b23df7b34.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
This looks like a typo `newAddresTitle` instead if the `newAddressTitle`, but I can't seem to find the former in the code 🤔 

String is there, translated: `CommonSyncString.newAddressTitle`

**Comment by radinamatic** [comment]
Point of clarification, the asset @pcenov was using was from this PR: https://github.com/learningequality/kolibri/pull/10389, that may not have been up-to-date with the latest `develop`.

We'll re-check to confirm tomorrow, when #10389 has been rebased.

**Comment by pcenov** [comment]
@radinamatic this is fixed in the latest build from https://github.com/learningequality/kolibri/pull/10412

![2023-04-07_13-26-06](https://user-images.githubusercontent.com/79847249/230593179-ce4e66cb-5078-4de7-a1b6-0405c4a6e638.png)

**Comment by radinamatic** [comment]
Excellent, thank you @pcenov!

Closing as fixed!
