### ISSUE TITLE
Kolibri 0.16 - Missing translations for the PIN options / incorrect English label of the drop-down

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10400]
## Observed behavior
See the attached screenshots. Note that even the English label of the drop-down 'Option' should be corrected to 'Options'

## Expected behavior
The translations should be displayed correctly.

## Steps to reproduce the issue
1. Install the latest Kolibri 0.16.0 build
2. Go to Facility > Settings and add a PIN number.
3. Click the 'Options' drop-down

## Screenshots

![2023-04-06_16-49-56](https://user-images.githubusercontent.com/79847249/230425541-7a8cd00f-09bf-4c02-a7de-c9d81bd217c4.png)

![2023-04-06_18-29-11](https://user-images.githubusercontent.com/79847249/230426614-06b2aaf0-2eff-4812-b995-e117c4566295.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
This is going to require some weird patching, because we apparently missed to include both the `View PIN` and `Change PIN` strings in the freeze 😞 . `Remove PIN` was included and is translated, can be found in `CommonCoreStrings.removePinPlacholder`, needs investigating why it is not displaying.

**Comment by akolson** [comment]
So it turns out that the reason this section isn't being translated is because the strings are currently hardcoded.
```
dropdownOption() {
  return [
    { label: 'View PIN', value: 'VIEW' },
    { label: 'Change PIN', value: 'CHANGE' },
    { label: 'Remove PIN', value: 'REMOVE' },
  ];
},
```
Using `removePinPlaceholder` should be a relatively easy task. Any recommendations on the two missing translations @radinamatic ?

**Comment by radinamatic** [comment]
> because the strings are currently hardcoded

I suspected that much 😞 

We discussed this with @marcellamaki, and I don't see other option but to try to concatenate, since we have all three words as separate strings:

Change: `DeviceSettingsPage.changeLocation`
View: `CommonCoreStrings.viewAction`
PIN: `PinAuthenticationModal.pinPlaceholder`

It may not sound ideal in some languages, but better than leaving it in English 🤷🏽‍♀️

**Comment by marcellamaki** [comment]
Yes - it's definitely not ideal and will be strange in some languages, but I think it is the best option we have for now. Thanks @radinamatic and @akolson

**Comment by akolson** [comment]
Okay. PR will be amended to include concatenation shortly. Thanks Radina & Marcella
