### ISSUE TITLE
Change Language button is unresponsive

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10407]
## Observed behavior
Reported by: @LianaHarris360 and @AllanOXDi  in the alpha-12 bug bash

Selecting `Change Language` menu option has no effect when pressed.

https://user-images.githubusercontent.com/46411498/230498037-a0eb039c-26cc-45d3-805c-e40f9e35b9a3.mp4

## Expected behavior
Pressing `Change Language` should open modal that displays the supported language options.

## User-facing consequences

User is unable to change the language.

## Steps to reproduce
1. Install the latest Kolibri 0.16.0 build
2. Open menu and Select `Change Language` 

## Context
0.16.0-alpha12
Using mac app download kolibri-0.16.0a12-0.3.0.dmg

**Comment by varunsh17** [comment]
Hi @LianaHarris360 . I want to get started with this issue as I think it falls under my skillset..
The issue I encountered also in my WSL , I am not able to click "change Language button".
![image](https://user-images.githubusercontent.com/81704366/230595381-13b23767-9a1d-4139-83a2-4ae0e3077fac.png)

**Comment by LianaHarris360** [comment]
Hi @varunsh17, thank you for your interest in working on this, I will assign it to you. Just to note, this regression is not limited to occurring in the Mac app, that is just where it was found. That information was added in case it could be of any use because sometimes there are operating system specific bugs/regressions.

**Comment by varunsh17** [comment]
`<LanguageSwitcherModal v-if="languageModalShown" ref="languageSwitcherModal" :style="{ color: $themeTokens.text }"
      @cancel="languageModalShown = false" />`
The above code is responsible for showing "Change Language" option in SideNav
But in methods the
`handleShowLanguageModal() {
      this.languageModalShown = true;
    },`
handleShowLanguageModal function is not triggering.The event is not not taking place as I also did console.log() but nothing could be seen, that mean on clicking, the function is not taking place..

Also the Privacy Link is somewhat same and have same functionality, but it is working fine !
This is the File wher above code is linked -> [kolibri/kolibri/core/assets/src/views/SideNav.vue](https://github.com/learningequality/kolibri/blob/a3309f3e207ba13bf5d309403e9c30f96e271b19/kolibri/core/assets/src/views/SideNav.vue#L210)

Any thoughts on this @LianaHarris360 ?

**Comment by marcellamaki** [comment]
Hi @varunsh17 - 

I recently did some work that refactored some code here, and you are right - the event that had been there before was (unintentionally) lost along the way, so now the expected event isn't triggering. 

The `ChangeLanguage` option uses `CoreMenuOption.vue` and you can see that [there used to be a `conditionalEmit` event ](https://github.com/learningequality/kolibri/blob/92819f1f026d17bbc3fe6c0232fac9eb2af4a65a/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L10). You can see how the component used to be set up for some ideas. I think adding a method to handle an event back into `CoreMenuOption` would be a good thing to try.

The goal here would be to ensure that: 
1. Menu options where there are links continue to navigate correctly to the new page
2. Menu options without a link (such as the Change Language, with a popup) emits an event which can be heard by the sidenav or other parent container.

**Comment by varunsh17** [comment]
Looking into it, I added the conditionalEmit event in methods, with `@click="conditionalEmit" @keydown.enter="conditionalEmit"`
Doing this fixed the issue and all the other links are redirected ideally with the ChangeLanguage button now being responsive.
I would like your input on this, please state for any inconsistency I also looked into v15.x codebase of Kolibri.
Thank you
[ Related file ](https://github.com/learningequality/kolibri/blob/d2ea094bf9532ed1d7eec5ee1e16203c67a74b6d/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L26)
```
<li v-else>
      <a ref="menuItem" :href="link" class="core-menu-option" role="menuitem" :class="$computedClass(optionStyle)"
        tabindex="0" @click="conditionalEmit" @keydown.enter="conditionalEmit">
        <slot>
          <KLabeledIcon>
            <template v-if="icon" #icon>
              <KIcon :icon="icon" :color="optionIconColor" />
            </template>
            <div v-if="label">{{ label }}</div>
          </KLabeledIcon>
          <div v-if="secondaryText">{{ secondaryText }}</div>
        </slot>
      </a>
    </li>
```

And into the methods, I have added

```
conditionalEmit() {
      if (!this.link) {
        this.$emit('select');
      }
    }
```
@marcellamaki @LianaHarris360

**Comment by varunsh17** [comment]
@marcellamaki and @LianaHarris360 
Should I make a pull request so you can review the changes I have made?

**Comment by LianaHarris360** [comment]
@varunsh17 Yes, that would be best. We will add any feedback directly on the pull request.
