### ISSUE TITLE
Grammar inconsistency within new learning facility setup

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10409]
## Observed behavior
Reported by: @laurenlichtman in the alpha-12 bug bash

When setting up a new learning facility, step 2 reads: “You can change this in your device settings later.” and step 3 reads: “You can change this in your learning facility settings later” — the former has a period, and the latter doesn’t (step 4 doesn’t either).

## Expected behavior
Consistent grammar within device setup.

## Context
0.16.0-alpha12

**Comment by marcellamaki** [comment]
Please refer to [KDS punctuation guidelines](https://kolibri-design-system.netlify.app/writing/#punctuation)
