### ISSUE TITLE
Facility sidebar's sub-links don't work as intended.

### ISSUE THREAD

**Issue by Wck-iipi** [learningequality/kolibri#10423]
## Observed behavior

The links under facility just go to "/en/facility/#/classes" and not to desired location.

## Errors and logs

…

## Expected behavior

Clicking a link under facilities should take me to required facility link.

## User-facing consequences

It causes a little confusion.

## Steps to reproduce

1) Go to any other link except facility.
2) Now click any sublink and you will reach en/facility/#/classes.

https://user-images.githubusercontent.com/110763795/230741851-1ce58ac0-4fdf-4b7e-8278-18a50740d627.mp4

## Context

…

**Comment by thanksameeelian** [comment]
this is a duplicate issue of #10430, which is fixed by PR #10550
