### ISSUE TITLE
Vertical order of elements below Flexbox and PLIX on iPhone 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1042]
## Summary

Something is amiss in vertical order of elements on `iPhone`: those below the Flexbox and PLIX exercises (like the `Download content` button or `Recommended`) end up overlaying them.  

On Android phone order seems correct.

## System information

 - Version: 0.2.0alpha5.dev35
 - Operating system:  iPhone 5S
 - Browser: all (Safari, Chrome, Firefox)

## Screenshots

**Firefox**
![download-button](https://cloud.githubusercontent.com/assets/1457929/23763911/6c656e18-04b0-11e7-9968-c70ceea643ab.JPG)

**Chrome** 
![download-button3](https://cloud.githubusercontent.com/assets/1457929/23764012/c39bcae2-04b0-11e7-822d-80f69b2e5317.JPG)

**Comment by christianmemije** [comment]
This is an issue with Safari on iOS http://stackoverflow.com/questions/23083462/how-to-get-an-iframe-to-be-responsive-in-ios-safari

**Comment by christianmemije** [comment]
Accidentally closed. I remembered I was never able to find a solution to this.

**Comment by christianmemije** [comment]
Addressed in https://github.com/learningequality/kolibri/pull/1137

**Comment by rtibbles** [comment]
Fixed in #1137
