### ISSUE TITLE
Reserved network locations for Studio and KDP

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10431]
##  Summary
As a developer, in support of remote content browsing and pursuit of leveraging existing functionality, I would like to use the `NetworkLocation` models and associated architecture to interact with Studio and KDP. We can also leverage functionality added with the `is_local` attribute to generalize interacting with devices on the internet.

Note: KDP doesn't currently respond to the info endpoint, so we should prevent requests to KDP until we update KDP.

### The task helper [`_enqueue_network_location_update_with_backoff`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/discovery/tasks.py#L169)
- It should prevent enqueuing new tasks when `is_local is False`

### The model [`NetworkLocation`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/discovery/models.py#L38)
- A new `type` field should be added with choices of `static`, `dynamic`, and `reserved`
- A django migration should migrate all models with `dynamic = False` to have `type` of `static` (all `dynamic = True` can be deleted)
- The field `dynamic` should be removed from the model once `type` has been set
- The `type` field should be `NOT NULL` once migrated
- The existing `DynamicNetworkLocation` and `StaticNetworkLocation` models should be migrated to use the new `type` field

### The task [`reset_connection_states`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/discovery/tasks.py#L284)
- It should update or create `reserved` network locations for Studio and KDP,  using the URLs defined in Kolibri's `options.ini`
- The `reserved` network locations should use hardcoded IDs 
- The connection state for the locations should be reset like `static` locations
- It should not enqueue a `perform_network_location_update` task for KDP, but should set its `application` to `Kolibri Data Portal`

### The viewsets for [`NetworkLocations`](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/discovery/api.py#L26-L51)
- ~~It should annotate a `dynamic` attribute on the response which is true when `type` is `dynamic`~~
- Only `static` models should be allowed to be created and it should set the `type` to `static` when creating them
- It should have a new `syncable` filter, which should include KDP's `reserved` location when `1` and Studio when `0`
- If `syncable` filter is not provided, always exclude both KDP and Studio
- Its method `update_connection_status` should prevent making requests to KDP's location for the time being

**Comment by bjester** [comment]
Removed the following in favor of always excluding KDP and Studio from the response for the time being:

### The composable [`useDevicesWithChannel`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js#L139)
- It should send `syncable=false` to the viewset API

### The composable [`useDevicesWithFacility`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js#L139) and [`useDevicesForLearnOnlyDevice`](https://github.com/learningequality/kolibri/blob/9bf713bf1563e5dd8efbf6e5631ca0f19a2a3a9b/kolibri/core/assets/src/views/sync/SelectDeviceModalGroup/useDevices.js#L174)
- It should send `syncable=true` to the viewset API

**Comment by akolson** [comment]
Tagging https://github.com/learningequality/kolibri/pull/10765 as a reminder to implement a KDP availability check once implementation of this issue complete. It should be implemented independently.

**Comment by rtibbles** [comment]
This has been implemented for Studio: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/discovery/well_known.py

KDP does now respond to `info` requests.
