### ISSUE TITLE
Missing strings when attempting to change facility

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#10437]
## Observed behavior
Reported by:  @AllanOXDi in the alpha-12 bug bash

When you  attempt to change the facility , some strings are missing from the interface

## Errors and logs
![image](https://user-images.githubusercontent.com/103313919/231119712-43cd1c60-f8dd-40a9-b803-2690f5a0b9e4.png)

## Expected behavior
Correct strings should show.
## User-facing consequences
This could cause confusion to a user.

## Steps to reproduce

Navigate to profile
change learning facility > click change  and select the learning facility

## Context
0.16.0-alpha12
Mac app download kolibri-0.16.0a12-0.3.0.dmg

…

**Comment by Pursottam6003** [comment]
Hii @AllanOXDi  

I was actually trying to reproduce the issue on my local computer but I was unable to get change` learning facility  `  option in my profile could you please let me know 

Does it requires student user account ?
![image](https://user-images.githubusercontent.com/81693090/231827942-d128caa6-d1a9-4690-9d7b-96c58963e2dc.png)

**Comment by AllanOXDi** [comment]
Hi @Pursottam6003 , I am not sure why you are not able to. Maybe @marcellamaki  has a better context. Because I seem to change a learning facility even with my supper admin account.
<img width="680" alt="Screenshot 2023-04-14 at 20 00 57" src="https://user-images.githubusercontent.com/103313919/232110531-66b34119-bfa3-4496-bd17-b2ce53c7c58a.png">
