### ISSUE TITLE
 Filters not working on "My Downloads" page

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#10436]
## Observed behavior

Reported by:  @AllanOXDi and @akolson  in the alpha-12 bug bash

When attempting to filter by  activity type or sorting by file size, the page does not refresh and display the filtered results

## Errors and logs

[fb0b870b-b1da-455e-b483-02a4d6c474b6.webm](https://user-images.githubusercontent.com/103313919/231115435-cc788ac4-ae19-43c1-a3e7-7dfa25f8f1f3.webm)

## Expected behavior
The "My Downloads" page should display filtered results based on the selected filter criteria.

## User-facing consequences
A user is not not able  access the correct filtered result.
## Steps to reproduce

1. Install the latest Kolibri 0.16.0 build
2. Open menu and  select my download
3. Try to filter the sample files available in my download

## Context
0.16.0-alpha12

**Comment by marcellamaki** [comment]
Note that this is still an in-progress feature and the filter implementation has not been fully built yet. This should be resolved once the rest of the download functionality is added, but we should leave the issue open so it's not forgotten.

**Comment by AllanOXDi** [comment]
Thanks! closing it
