### ISSUE TITLE
Channel selector opens missaligned

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1044]
## Summary

Tapping the channel selector on mobiles opens the partially visible menu - it seems right aligned with the edge of the channel selector icon instead of the left edge of the mobile view itself. 

## System information

 - Version: 0.2.0alpha5.dev35
 - Operating system:  iPhone 5S & Android 4.2.2
 - Browser: all (Safari, Chrome, Firefox)

## How to reproduce

I'm unable to pinpoint exactly when, because sometimes it does open correctly... :disappointed: 

## Screenshots

![menu](https://cloud.githubusercontent.com/assets/1457929/23765633/a7200576-04b6-11e7-8be6-5b174f436f96.JPG)

This is reproducible even on responsive view in Chrome dev tools:

![instantschools learningequality org-learn- iphone 5](https://cloud.githubusercontent.com/assets/1457929/23765674/c1dd61c4-04b6-11e7-9c05-34ffdfc810b8.png)

**Comment by indirectlylit** [comment]
should be addressed by https://github.com/learningequality/kolibri/pull/1087
