### ISSUE TITLE
Regression: not being able to sync to KDP if not (known to be) registered

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10446]
## Observed behavior
Noted by @jamalex in the alpha-12 bug bash

> we need to allow syncing to KDP even when the local device’s facility is not in a “registered” state. Sometimes the facility is registered already on the KDP side, but the local device doesn’t know it is until… it syncs. 

Related: https://github.com/learningequality/kolibri/issues/7672

## Expected behavior
Device should have the option of syncing to KDP even if it doesn't know that it can. 

## User-facing consequences
If the device never syncs to KDP, it will never know it can sync to KDP!

## Context
0.16.0-alpha11

**Comment by bjester** [comment]
This doesn't appear to be a regression. We never fixed it in 0.15
