### ISSUE TITLE
Rounding error difference between "Best Score" and attempts

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10443]
## Observed behavior
Noted by @lauradanforth in Alpha-8 bug bash 
Best score says 67%, Attempts says 66%

## Errors and logs
<img width="450" alt="Screen Shot 2023-03-02 at 1 01 04 PM" src="https://user-images.githubusercontent.com/17235236/231182787-7bb4922a-20df-4af2-885d-463cab87eda8.png">

## Expected behavior
Rounding is okay, but is should match

## User-facing consequences
Confusion about scores

## Steps to reproduce
Take a practice quiz with a number of questions that would result in rounding (i.e. "Test on the Big Picture" which has 3 questions)

## Context
0.16.0-alpha8

**Comment by thanksameeelian** [comment]
fixed in #10451
