### ISSUE TITLE
Bookmark option for remote resources should be disabled

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10444]
## Observed behavior
Noted by @LianaHarris360 in 0.16.0alpha9 bug bash - bookmark icon/option is appearing on remote browsing resources. It is not the expected behavior to be able to bookmark a remote resource, so it appears "broken"

## Expected behavior
User should not have the option to bookmark a remote resource 

## Steps to reproduce
Bookmark a remote resource within the content renderer 

## Context
0.16.0-alpha9

Note that this be resolved in the course of @MisRob's updates to the content rendered, and in this case, should just be confirmed and then closed.

**Comment by MisRob** [comment]
> Note that this be resolved in the course of @MisRob's updates to the content rendered, and in this case, should just be confirmed and then closed.

Yes, I can confirm. Assigning myself here.

**Comment by MisRob** [comment]
Will besolved in https://github.com/learningequality/kolibri/pull/10558

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/10558
