### ISSUE TITLE
"Try Again" for practice quiz is cut off in some languages

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10442]
## Observed behavior
Noted by @LianaHarris360 in the alpha 8 bug bash: 

"Try again" button is cut off in some languages

## Errors and logs
<img width="1439" alt="Screenshot 2023-03-02 at 2 55 14 PM" src="https://user-images.githubusercontent.com/17235236/231182147-478f3175-078e-4584-9fd1-b60b2aaf6b80.png">
<img width="1439" alt="Screenshot 2023-03-02 at 2 53 21 PM" src="https://user-images.githubusercontent.com/17235236/231182154-20d5c28a-0dcc-4850-9460-dc4eb2ea85e8.png">

## Expected behavior
Complete text should be visible

## Steps to reproduce
Complete a practice quiz (see Kolibri QA channel for examples) in a language other than English (Spanish, German might be good starting places)

## Context
0.16.0-alpha8

**Comment by Pursottam6003** [comment]
Hii @marcellamaki I have done my previous assigned issues  

If possible could you please assign me to this issue I would be happy to work on it

thank you

**Comment by MisRob** [comment]
Hi @Pursottam6003, I just assigned you another issue you asked for that I noticed earlier than this one, so I will leave this unassigned in case someone else would want to help. Please remind yourself again here as soon as you finished all other issues and if it's still unassigned, we will assign you.

**Comment by Wck-iipi** [comment]
@marcellamaki @MisRob Can I work on this issue?

**Comment by MisRob** [comment]
Hi @Wck-iipi. yes you can, thank you
