### ISSUE TITLE
Alignment of content on small mobile layout

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1045]
## Summary

Content container is aligned to the right edge of the view which makes impossible to interact with exercises and videos on smaller mobile layouts.

## System information

 - Version: 0.2.0alpha5.dev35
 - Operating system:  iPhone 5S & Android 4.2.2
 - Browser: all (Safari, Chrome, Firefox)

## Screenshots

**Chrome**
![align3](https://cloud.githubusercontent.com/assets/1457929/23766130/751935aa-04b8-11e7-9f98-fdd126054ddc.JPG)

**Firefox**
![align4](https://cloud.githubusercontent.com/assets/1457929/23766143/7cc00d88-04b8-11e7-9407-7c6ed982f019.JPG)

**Comment by radinamatic** [comment]
Reproducible on responsive view in Chrome dev tools, so you don't have to test on "real" mobile phone... :stuck_out_tongue: 

![instantschools learningequality org-learn- iphone 5 1](https://cloud.githubusercontent.com/assets/1457929/23766328/31d0cc26-04b9-11e7-8952-2d84dc26cd8d.png)

**Comment by radinamatic** [comment]
Hint: if I deactivate the `right: 0` for `content-container` it aligns left and at least is horizontally scrollable, which could be an interim solution:

![count with small numbers - instant schools math - kolibri - google chrome_085](https://cloud.githubusercontent.com/assets/1457929/23766542/1bf50a88-04ba-11e7-8e92-2753b9933a1e.png)

**Comment by radinamatic** [comment]
@indirectlylit I did not test in browserstack, but I can reproduce this issue in responsive layout view in both Chrome and Firefox. It seems the width of video player (and its upper containers) gets stuck at 840px even on smallest screen sizes:

https://instantschools.learningequality.org/learn/#/recommended/1d8f6d84618153c18c695d85074952a7/content/82661ee52b345fbf9e82182e3f3ad3fa
![overview of addition sums to 10 - ck-12 - kolibri - google chrome_091](https://cloud.githubusercontent.com/assets/1457929/23955561/81dbfc98-0957-11e7-8802-9308dd07810d.png)

![overview of addition sums to 10 - ck-12 - kolibri - google chrome_092](https://cloud.githubusercontent.com/assets/1457929/23955660/c8cce2f2-0957-11e7-9990-1ed108334b87.png)

https://instantschools.learningequality.org/learn/#/recommended/1d8f6d84618153c18c695d85074952a7/content/82661ee52b345fbf9e82182e3f3ad3fa
![counting with small numbers - instant schools math - kolibri - mozilla firefox_093](https://cloud.githubusercontent.com/assets/1457929/23955684/e04d0574-0957-11e7-9a5e-01be50643c57.png)

**Comment by jamalex** [comment]
I get this when I load the online demo server (as you're using, @radinamatic), but not when I test locally with the latest version. It seems someone may have inadvertently fixed it along the way? I'm going to relaunch the demo server soon, after hearing back from VF about when a brief downtime is best to happen, but in the meantime, could we set you up for testing locally?

**Comment by jamalex** [comment]
Ok, demo server has been updated! Seems to work for me now.

**Comment by radinamatic** [comment]
Ha, half an hour later, magic happens! :+1:  :tada: 

![getting to 10 by filling boxes - instant schools math - kolibri - google chrome_094](https://cloud.githubusercontent.com/assets/1457929/23958190/814de2e4-095e-11e7-82af-c38cb206918e.png)

Player control bar is still too wide, not sure if we can do something about it... :thinking:

**Comment by jamalex** [comment]
_Literally_ magic, we don't know who fixed it.

**Comment by jamalex** [comment]
Oh, yeah -- I wasn't getting that on "iPhone 6", but I do see it on "iPhone 5" -- I think it's because there's no room for all the buttons in the bar, so it has an effective min-width; can we have it hide some of the controls below a certain width, @christianmemije?

**Comment by radinamatic** [comment]
Forward and Rewind buttons would be my choices if we're hiding controls button at this width...

**Comment by jamalex** [comment]
Most exercises are now better, but some still have subtler issues, where they have components with bigger min-widths, e.g. https://instantschools.learningequality.org/learn/#/recommended/11d9de56da744f98877cc9fe710bb78d/content/9cefc3c618da41c79861df2a29ad8c9f

May be no easy & general-purpose fix for this particular kind of issue.

**Comment by radinamatic** [comment]
True, we may have to take them one-by-one at some point.

**Comment by indirectlylit** [comment]
thanks guys

made a new issue for the one referenced above: #1074
