### ISSUE TITLE
Remove debugger from the setup wizard

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10458]
## Observed behavior
It's still here :) 

## Expected behavior
Should not be present, as soon as there is no dev need for it

## Context
Latest develop (last noted in 0.16.0-alpha12)

**Comment by Pursottam6003** [comment]
Hii @marcellamaki  could you please briefly explain the issue I am not getting how to reproduce it

**Comment by marcellamaki** [comment]
Hi @Pursottam6003 - this is an issue that is functioning as a reminder for the team to come back to a particular workflow and remove a debugging state that is currently in the UI, before we release. I am not sure that it's something we should proceed with just yet - it's so we don't forget. 

I think it would make more sense for you to work on a different issue - but thank you for your interest!
