### ISSUE TITLE
Add deprecation warnings for python 2.7 and IE 11

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10482]
**Not ready for dev work**

Work with design team to determine where to place deprecation warnings 
- only show to super admins on devices that are running python 2.7 
- super admin if they are running IE11 or if we have a recorded client device version is using IE11

**Comment by jtamiace** [comment]
Could use a non-dismissible warning alert component that appears above the first page container across all pages in the app. For cases where more than one condition is active, all messages should display within the alert, separated by a line break

<img width="1558" alt="Screenshot 2023-04-27 at 3 08 14 PM" src="https://user-images.githubusercontent.com/6668144/235001837-b7f3298c-6e6e-4df3-a1c6-f202c49060e6.png">

**Comment by rtibbles** [comment]
Checking the IE11 status will require doing some aggregation over logs in the backend to check for usage of IE11 in those logs as well - so may need an additional API endpoint for doing this check.

**Comment by nucleogenesis** [comment]
@jtamiace should I borrow the structure of what was added [here](https://github.com/learningequality/kolibri/pull/10128) re: the banner styling? I could probably just borrow the component, update the icon to use the "warning" icon, and use the color yellow above?

**Comment by nucleogenesis** [comment]
@rtibbles What logs would we be looking to in this case? I'm thinking about this and I'm at a loss of where to start looking to do this.

**Comment by rtibbles** [comment]
Can probably just look for `IE,11` being in the `device_info` property here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/logger/models.py#L180

(see the method below to see how this info is encoded)

So can probably just do:

```
UserSessionLog.objects.filter(device_info__contains="IE,11").exists()
```

to do the check?

**Comment by jtamiace** [comment]
> @jtamiace should I borrow the structure of what was added https://github.com/learningequality/kolibri/pull/10128 re: the banner styling? I could probably just borrow the component, update the icon to use the "warning" icon, and use the color yellow above?

@nucleogenesis yes I think that would work!
