### ISSUE TITLE
Windows installation process error

### ISSUE THREAD

**Issue by zrg228** [learningequality/kolibri#10489]
## Observed behavior

When trying `pip install -e` command on a Windows machine the following error comes up:
![image](https://user-images.githubusercontent.com/99768066/230952115-6a7b1b26-1e46-42ba-9c6b-cbceb61c3fdb.png)

We were able to solve the issue by changing some of the code from the env file. Specifically the `py33combat.py` file and made the following change in code to that file:

![image](https://user-images.githubusercontent.com/99768066/230956635-9ee0f2dd-ea69-4287-82b1-4ba3c2cbca8d.png).

## Context
Python version:
`Python 3.9.9`

This error occurred on a Windows 11 PC and on another PC with the same OS. The env that is being used in this process was venv (the built in env of Python) due to the complexities of using Pyenv-virtualenv on a Windows PC. Some file systems may have a slightly different file path based on the installation of the env.

**Comment by rtibbles** [comment]
Hi @zrg228 - could you copy paste the full traceback of the error as text? Will make it more useful to be able to see the whole traceback without the file paths cut off by the screenshot.

Also, could you note what version of Python you were using when this error occurred?

**Comment by rtibbles** [comment]
The full traceback of this error has been logged here: #10502 closing in favour of that issue - please follow there for more updates @zrg228

**Comment by rtibbles** [comment]
Fixed in #10609
