### ISSUE TITLE
Windows Installation Process Pyenv Issues

### ISSUE THREAD

**Issue by jose-hy** [learningequality/kolibri#10492]
## Observed behavior

Hello, I wanted to create this issue to know if anyone else who uses Windows and is contributing to Kolibri has experienced the same issues regarding the virtual environment setup.

## Errors and logs

First Error: The documentation of [pyenv-win](https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html#installation-of-pyenv-on-windows) for windows has the same command to download it from the pyenv-win's [github](https://github.com/pyenv-win/pyenv-win#quick-start). I've followed the instructions correctly and restarted my shell. When trying to install and set a python version to the shell, this is said after doing the previous 2 steps: 
 
![pyenv-win_shellError](https://user-images.githubusercontent.com/84255480/232557614-d452c813-6f64-43a5-9515-e0ea347ff280.jpg)

## Expected behavior

The behavior should say 
`pyenv 3.9.9`

## Steps to reproduce

Follow the getting started instructions up until the [Python Virtual Environment](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#python-virtual-environment) section. 
Then, follow the [Install pyenv-win](https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html#installation-of-pyenv-on-windows) instructions and check the version of Python after setting the shell version to 3.9.9

## Context

This should only occur on Windows, as I'm using the pyenv-win version to start my virtual environment. 
To go around this issue for the time-being (which may be permanent), I used the Python 3 venv tool already installed in recent Python versions as a workaround, and that seems to work but comes with its own issues (such as #10489). I haven't tried any other virtual environment since the Python 3 venv went over this problem. 

## Errors and logs

Second Error: When creating and setting up pyenv-win and moving on to creating the virtual environment, pyenv-win does not recognize the command "virtualenv"
 
![pyenv-win_kolibri-nosuchcommand](https://user-images.githubusercontent.com/84255480/232561540-c9691729-0f93-4142-b8df-f858670effea.png)

When checking out what commands are available from the pyenv-win version, this is what I got from typing "pyenv":
```
Usage: pyenv <command> [<args>]

Some useful pyenv commands are:
   commands     List all available pyenv commands
   duplicate    Creates a duplicate python environment
   local        Set or show the local application-specific Python version
   global       Set or show the global Python version
   shell        Set or show the shell-specific Python version
   install      Install a Python version using python-build
   uninstall    Uninstall a specific Python version
   update       Update the cached version DB
   rehash       Rehash pyenv shims (run this after installing executables)
   vname        Show the current Python version
   version      Show the current Python version and its origin
   version-name Show the current Python version
   versions     List all Python versions available to pyenv
   exec         Runs an executable by first preparing PATH so that the selected Python
   which        Display the full path to an executable
   whence       List all Python versions that contain the given executable

See `pyenv help <command>' for information on a specific command.
```

## Expected behavior

The command should create a new virtual environment with the name I gave along with the version that I specified. 

## Steps to reproduce

Download and install pyenv-win through the [documentation](https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html#installation-of-pyenv-on-windows) and continue on to setting up the [virtual environment](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#python-virtual-environment) with the command "pyenv virtualenv 3.9.9 kolibri-py3.9"
Should receive an error that says something along the lines of "no such command 'virtualenv' "

## Context

This should only occur on Windows, since the commands given from the pyenv-win is compatible for Windows OS. Like the previous issue above, I've gone around this by using an entirely different virtual environment setup with Python 3 venv.

**Comment by rtibbles** [comment]
You are asking for the version of pyenv by typing `pyenv --version` but you seem to be expecting it to output the version of python that you have installed with pyenv.

This might make sense if you were entering `python --version` and you were seeing this, but I am struggling to understand what the issue being reported here is.

For the second issue, there are specific instructions in the documentation to install the pyenv virtualenv plugin https://kolibri-dev.readthedocs.io/en/develop/howtos/pyenv_virtualenv.html#using-pyenv-virtualenv-with-pyenv

If you experienced an issue installing that on Windows, please let us know, so that we can update the documentation accordingly, but you haven't mentioned this above.

**Comment by jose-hy** [comment]
Thank you for replying and sorry for the late response! I've already installed and worked with the Python venv, so I didn't get a chance to test the pyenv virtualenv plugin on Windows. I can work with the plugin in the next days to see if this can provide a way to use venv on Windows, but I didn't see if this is compatible with Windows in the setup and installation process. 

Like I said in the beginning of the issue, I wanted to get other opinions from contributors who use Windows as well. Thanks again for helping me out!

**Comment by rtibbles** [comment]
Closing as stale, we can reopen if additional information is added.
