### ISSUE TITLE
Import Error Running Devserver on Develop Branch

### ISSUE THREAD

**Issue by estelacruz** [learningequality/kolibri#10497]
## Observed behavior | Error logs 

I am attempting to run the devserver while on develop branch, and although I can install all required and option python dependencies, I am unable to run the server.

Below is the screenshot of the observed error: 

<img width="1007" alt="Screen Shot 2023-04-17 at 6 06 56 PM" src="https://user-images.githubusercontent.com/79770461/232621104-ead257ad-46b6-46b0-9950-213a746ea932.png">

<img width="862" alt="Screen Shot 2023-04-17 at 6 07 36 PM" src="https://user-images.githubusercontent.com/79770461/232621374-90a35d83-aa63-4655-8cd0-c786412aee48.png">

Since traceback indicates that the "DeviceStatus class should be defined in the file kolibri/core/device/models.py" I went to check both the models.py and api.py in kolibri/core/device/ and observed the following in the API file: 

<img width="574" alt="Screen Shot 2023-04-17 at 6 14 01 PM" src="https://user-images.githubusercontent.com/79770461/232622124-966a0c0c-fb3a-4f0e-9f8e-55e6f4bc7003.png">

I was curious to know if the import error is because DeviceStatus is relatively imported versus absolutely imported. I created my own branch to see if that would help, but I am still getting the same import error:
```
Exception Value: cannot import name 'DeviceStatus' from 'kolibri.core.device.models' 
```

Environment:
 * Kolibri version: develop branch (16x)
 * Operating system: MacOS
 * Browser: Chrome

**Comment by rtibbles** [comment]
We have quite a few developers using MacOS, but no one has previously reported this issue. What command are you using to run the development server?

Could you try running `make clean-pyc` and running again to see if stale pyc files might be causing the import issue?

**Comment by estelacruz** [comment]
Hello,

Thank you for getting back so soon! 

I initiated the server:
```
kolibri manage migrate
```
and then to run the server:
```
yarn run devserver
```

I followed the documentation but did encounter some issues along the way. I recorded what commands did not work for me, as well as my workaround, and am looking to share this to contribute to the developer documentation once it is all complete. I wonder if my workarounds are the reason why I am having issues running the server--perhaps updating dependency versions by default or anything along those lines

**Comment by rtibbles** [comment]
Could you detail the issues and workarounds you have done? It does seem like something is rather different with your setup that you are encountering something completely novel.

**Comment by estelacruz** [comment]
Hello,

I have documented my issues/workaround in [google docs](https://docs.google.com/document/d/1zw1PZY5abRcXtVgslohB0djZTTr_zqMW-8FxHQH2SBw/edit?usp=sharing)
Let me know if this helps explain what is going on.

**Comment by rtibbles** [comment]
This seems to have been related to installing the build requirements, hopefully is resolved by the updates to documentation.
