### ISSUE TITLE
Top Nav items shift when switching from non-bold to bold text

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10526]
## Observed behavior
Noted in the alpha12 bug bash by @jamalex:

In the navigation, when the styles change from non-bold to bold (active) styles for the top navigation items, the tabs themselves shift slightly, due to the difference in spacing. 

## Expected behavior
Text/layout should not shift 

## Steps to reproduce
Use the top navigation items and notice that there are slight shifts in alignment

## Context
0.16.0-alpha12
Windows

**Comment by Wck-iipi** [comment]
@marcellamaki Can I work on this issue?

**Comment by MisRob** [comment]
Hi @Wck-iipi, yes, thank you
