### ISSUE TITLE
While performing device setup, the form doesn’t remember the previously selected options

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10528]
## Observed behavior
Noted by @akolson in the alpha-12 bug bash

While performing device setup, the form doesn’t remember the previously selected options. As such a user needs to reselect the set up options. It looks like they are persisted in state however these are not reflected on the UI especially on click back button

## Expected behavior
The UI should persist the previously selected state

## Steps to reproduce
Move back and forth within the setup wizard

## Context
0.16.0-alpha12

**Comment by rtibbles** [comment]
Fixed in #10672
