### ISSUE TITLE
Manually adding inaccessible network device hangs

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10529]
## Observed behavior
Noted by @jamalex in the alpha12 bug bash 

## Errors and logs
Adding the address causes the UI to hang

<img width="222" alt="Untitled (8)" src="https://user-images.githubusercontent.com/17235236/233401124-113684da-6da2-4199-94ae-1b54a1886d21.png">

## Expected behavior
A user should be able to add KDP as a syncing destination

## User-facing consequences
Unable to connect/sync with KDP

## Steps to reproduce
Add KDP as a syncing destination by inputting manually

## Context
0.16.0-alpha12

**Comment by bjester** [comment]
The hanging UI should be resolved by https://github.com/learningequality/kolibri/issues/10267 -- bumped to P1

**Comment by bjester** [comment]
Can confirm that it doesn't hang:
![Screenshot from 2023-04-25 09-34-05](https://user-images.githubusercontent.com/819838/234343693-d802adc4-e620-4f74-8df4-ffb119a3dbd6.png)
