### ISSUE TITLE
Syncing on "Facility > Data" page does nothing

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10532]
## Observed behavior
Noted by @bjester during the alpha12 bug bash 

Possibly related, this comment from @jamalex that: 

> Clicking “SYNC” pops up a modal that first shows a red error message and maybe something else before immediately collapsing down

## Errors and logs
![Screenshot from 2023-04-06 13-24-00](https://user-images.githubusercontent.com/17235236/233403507-964bc5bc-c8e7-42ea-b85e-7b54e43147a8.png)

## Expected behavior
Syncing should work from this page

## Steps to reproduce
Go to Facility > Data and try to sync

## Context
0.16.0-alpha12

**Comment by AllanOXDi** [comment]
I am unable to replicate this Issue
[screen-capture (3).webm](https://user-images.githubusercontent.com/103313919/234964532-3a582fd8-8eb0-4d97-a9a4-fd548db5e883.webm)

**Comment by bjester** [comment]
@AllanOXDi I think you're right, it is working now with 0.16.0a13. Better close it out! :)
