### ISSUE TITLE
Double "Data" Tab on the "Facility Page" 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10533]
## Observed behavior
Noted by @bjester during the alpha12 bug bash 

Pixel 5 dimensions — 393px — if it doesn’t appear immediately, select different tabs and the double data will appear

## Errors and logs
![Screenshot from 2023-04-06 13-22-20](https://user-images.githubusercontent.com/17235236/233404132-4e137c59-8f8b-48f5-a89a-695b6a873008.png)

## Expected behavior
Each menu item should only appear once

## Steps to reproduce
Pixel 5 dimensions — 393px — if it doesn’t appear immediately, select different tabs and the double data will appear

## Context
0.16.0-alpha12

**Comment by marcellamaki** [comment]
Hi @radinamatic and @pcenov - could one of you take a look at seeing if you can reproduce this? So far, I have been unable to, either with previewing as Pixel 5 in the browser following the tips from Blaine I included in the issue, or using a different sized dev tools preview, or using a responsive screen. I do see another problem with the menu button overlapping text at very specific breakpoints which I will fix (see below -- it's possibly related), but additional confirmation or tips about this would be helpful. Thanks!

This is not urgent - definitely a lower priority than anything studio related or testing any remaining Kolibri features

![Image](https://github.com/learningequality/kolibri/assets/17235236/f92e5758-ad1f-4a05-bf31-5537d7cfe7f6)

**Comment by pcenov** [comment]
Hi @marcellamaki - I confirm your observations, the issue is not replicable in Kolibri 0.16.0a15. I also noticed the menu button overlapping text or being too close to the text. Tested on an actual Android device plus Chrome's responsive dimensions.
