### ISSUE TITLE
Export usage data card is horizontally scrollable

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10534]
## Observed behavior
On the Facility > Data page, the Export usage data card can be scrolled horizontally when it should not be 

## Errors and logs

[Screencast from 04-06-2023 01_28_11 PM.webm](https://user-images.githubusercontent.com/17235236/233404720-4a5b00f6-37e1-4c0b-9037-8b52b840dc71.webm)

## Context
0.16.0-alpha12

**Comment by Wck-iipi** [comment]
@marcellamaki Can I work on this issue?

**Comment by marcellamaki** [comment]
Hi @Wck-iipi - yes, you are welcome to work on this issue.  Thanks for your interest. Let me know if you have any questions as you get working.

**Comment by Shivanshu-09** [comment]
@marcellamaki I want to contribute to this project but I am facing some issues while setting up this project on MacOS. Is there any discord group where I could get some starting help so I can get started with the issues?

**Comment by MisRob** [comment]
Hi @Shivanshu-09, thank you for your interest. Please use [GH discussions](https://github.com/learningequality/kolibri/discussions) to report issues with the development server - that's a place where we will notice it most easily or other contributors may help. Recently some contributors reported and attempted to debug problems occurring on MacOS - you may find #10497 and also the comments section of #10335 helpful.
