### ISSUE TITLE
Sidebar - Missing translation for 'learner'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10541]
## Observed behavior
See the attached screenshot.

## Expected behavior
The translation should be displayed correctly. Note that in Figma the type of user is capitalized: Learner so this might need to be corrected as well.

## Steps to reproduce the issue
1. Install the build asset from https://github.com/learningequality/kolibri/pull/10487
2. Sign in as a Learner user and change the language to a language different from English
4. Expand the sidebar and look under the username

## Screenshots
![2023-04-21_15-26-11](https://user-images.githubusercontent.com/79847249/233635881-3ef3a4fa-2043-446a-82dc-696c64ea3a3c.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #10543
