### ISSUE TITLE
Learn-only device's sidebar - Unnecessary links and missing indication that this is a learn-only device

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10542]
## Observed behavior
See the attached screenshot.

## Expected behavior
This could be a known issue but I couldn't find it so reporting that currently for a LOD we are showing the Permissions, Facilitates, Info and Settings links in the sidebar while for a LOD there should be only the Channels link. Also the text indicating that this is a learn-only device is missing.

## Steps to reproduce the issue
1. Install the latest develop build.
2. Setup a Learn-only device
4. Expand the sidebar and open the Device plugin

## Screenshots

![2023-04-21_17-21-13](https://user-images.githubusercontent.com/79847249/233661817-ee8e8751-1e20-4ac6-be5a-2b62994d8a3d.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
@pcenov could you see if these issues are resolved by this PR? https://github.com/learningequality/kolibri/pull/10481

**Comment by pcenov** [comment]
Hi @rtibbles - https://github.com/learningequality/kolibri/pull/10481 fixes the issue with the Permissions, Facilitates, Info and Settings links in the sidebar as these are now hidden. However, the info text about the learn-only device is still missing:

![2023-04-25_11-19-35](https://user-images.githubusercontent.com/79847249/234217991-63fb6e51-52cb-4b97-a0be-42cbef5302f0.png)
