### ISSUE TITLE
Halt Kolibri startup if Redis is unavailable when configured

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10551]
This needs reproduced on 0.16 before proceeding. There is likely benefit to adding a dedicated connection test though.

## Observed behavior

If Kolibri is configured to use Redis as its cache backend, when it's unavailable we should properly halt Kolibri startup. This has been observed in BCK environments where the Redis service may not be ready when Kolibri starts, specifically when running the `kolibri services` command. The result is that Kolibri reaches a state where it's stuck still running, outputting messages like those below. Note: this was observed on 0.15, so some improvements may have 

## Errors and logs

```
Got an exception running <bound method Worker.check_jobs of <kolibri.core.tasks.worker.Worker object at 0x7fd6f475d2b0>>: cannot schedule new futures after interpreter shutdown
```

## Expected behavior

In an [existing location](https://github.com/learningequality/kolibri/blob/2ff89f2df90f0b9db3757c38b93b5ea12cbc5ac7/kolibri/core/apps.py#L105) where we test Redis settings, we should raise a proper exception if the connection to Redis fails. Since we already have a dedicated check for Redis settings, adding this should be a small but dedicated improvement to stop Kolibri startup when this occurs.

## User-facing consequences

Kolibri could get stuck in a running state

## Steps to reproduce

Run `kolibri services` with it configured to use Redis as its cache backend, but without redis running.

## Context

0.15

**Comment by rtibbles** [comment]
Fixed in #11296
