### ISSUE TITLE
Add new Kolibri option to disable Zeroconf

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10552]
## Observed behavior

In cloud deployments like BCK, we do not need Zeroconf running.

## Expected behavior

A new `options.ini` configuration should exist to disable Zeroconf, which should prevent [subscribing the plugin](https://github.com/learningequality/kolibri/blob/2ff89f2df90f0b9db3757c38b93b5ea12cbc5ac7/kolibri/utils/server.py#L688)

## User-facing consequences

Unexpected issues when an unneeded capability, like Zeroconf, is utilized

## Context

0.15+

**Comment by jredrejo** [comment]
This would be nice to have for KDP. In this environment zeroconf is just a waste of resources. Moving it to the backlog.

**Comment by rtibbles** [comment]
Fixed in #12620
