### ISSUE TITLE
Tab title string is broken

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10568]
On the profile page, the string associated with the title/name on the browser tab is a broken string 

![image](https://user-images.githubusercontent.com/17235236/234662448-f8debb11-c886-4059-91e7-49933eae10f7.png)

This probably broke during string refactoring, and the reference should be updated.

**Comment by Pursottam6003** [comment]
Hii @marcellamaki  what should be the expected behavior, does it would display the name of the user or display current page title could you please clarify

**Comment by rtibbles** [comment]
Fixed in #10677
