### ISSUE TITLE
Remote Content Browsing: Improve the downloading string on a content page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#10575]
A follow-up to #10558 (couldn't be incorporated due to the 0.16 string freeze)

When downloading remote content, we currently display the "Download requested" string as the downloading loader tooltip
![strings](https://user-images.githubusercontent.com/13509191/234798487-c89ed341-0f41-462b-8289-45d32929a390.png)

This should be replaced by a better string, e.g. "Downloading".

**Comment by MisRob** [comment]
I assume there won't be objections against using the "Downloading" string, but marking this issue as "needs decisions" until it's confirmed by the strings team

**Comment by marcellamaki** [comment]
@MisRob - I actually think this used to be "downloading" and was changed to "download requested" although I cannot totally recall why - whether it was grammatical (I think we have guidance around using verbs with -ing in English), or if it was a technical nuance to indicate that... well... the download had been "requested", but not necessarily that the download was actively happening. Perhaps it was a combination. 

This isn't a conclusion or recommendation of how to proceed, just a little background insight. Regardless, we can revisit this the next time around if it proves to be confusing to our users, or there is a better word or phrase for it :)

**Comment by MisRob** [comment]
Ah okay, I didn't know this was discussed already at some point. I think it makes sense to return to it in case learners find it confusing. For now, I'm making our TODOs list a bit smaller ;)
