### ISSUE TITLE
Remote Content Browsing: Make sure that bookmarking a resource after downloading works

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#10577]
A follow-up to https://github.com/learningequality/kolibri/pull/10558

## Blocked by

#10391
#10564 

## Summary

After downloading remote content on a content page, it's not possible to bookmark it (`Request failed with status code 400'`). This is actually correct because the download action is currently mocked and it is expected that a resource that hasn't been downloaded yet can't be bookmarked. So this issue may not require any additional work except just making sure that bookmarking works after the blocking issues referenced above are resolved.

![bookmark](https://user-images.githubusercontent.com/13509191/234809131-32398f8b-38b5-4f65-890d-70800d2ec82c.gif)

**Comment by marcellamaki** [comment]
Confirming that after manual QA including the team session on Friday, the download icon is replaced by the bookmark icon/interaction, once the download has completed!
