### ISSUE TITLE
Allow users without any content on their device to browse network devices

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10599]
## Observed behavior
Noted by @marcellamaki in the alpha13 bug bash 

> We might need to update the “no content on device” landing page to be able to browse other kolibris?

When a device installs kolibri and joins a network with other kolibris, they should be able to see that content right away, in addition to having the option for adding their own content. 

## User-facing consequences
Users will not be able to fully benefit from the remote browsing content feature. 

## Context
0.16.0-a13

**Comment by AllanOXDi** [comment]
fixed in https://github.com/learningequality/kolibri/pull/10687.
