### ISSUE TITLE
plugins cannot be disabled when they don't exist

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#106]
steps to reproduce:
1. create a new plugin (e.g. `hello`)
2. enable it: `kolibri plugin kolibri.plugins.hello enable`
3. delete the plugin. Now running kolibri throws an error: `ImportError: No module named hello`
4. try to disable the plugin: `kolibri plugin kolibri.plugins.hello disable` - thows an error: `kolibri.utils.cli.PluginDoesNotExist: Plugin does not exist`

At this point, `~/.kolibri/kolibri_settings.json` must be manually edited to remove the offending plugin

I'm not sure what the correct behavior is, but we probably don't want people to need to edit the settings file directly. Also, we may be able to log warnings with helpful information rather than raising exceptions.

**Comment by benjaoming** [comment]
Also, don't get too caught up on the JSON settings file, we might not use JSON because it isn't human friendly :) See: #17

**Comment by indirectlylit** [comment]
JSON actually doesn't bother me :) I've always found it to be a reasonably human friendly config language. At least it's not XML!

**Comment by benjaoming** [comment]
Heh, developer-friendly maybe is a better notion for it... but .ini files are better for end-users, that was the concern regarding #17.

**Comment by benjaoming** [comment]
Test of plugin disabling was oddly removed a few weeks before this issue... fe3e900840e59dac58b12dafbf4c2bae6d793342

**Comment by rtibbles** [comment]
Fixed in #1770
