### ISSUE TITLE
Make SideNav sub menu items have font size 14 px

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10608]
Items look a bit small at 12px, but looking slightly better at 14px

Current:
![image](https://user-images.githubusercontent.com/1680573/235491918-c54aa63a-23d5-4be8-b2d1-e49be98d131b.png)

With 14px:
![image](https://user-images.githubusercontent.com/1680573/235491949-83c12151-0bfe-4169-859a-e172a6751be4.png)

[Slack Message](https://learningequality.slack.com/archives/C0LKG14NL/p1680905065984949?thread_ts=1680905065.984949&cid=C0LKG14NL)

**Comment by AllanOXDi** [comment]
This seems to be fixed [here](https://github.com/learningequality/kolibri/blob/ad4a735302ba392c138f91c0dea2443e913fcbc0/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L222). Closing it
