### ISSUE TITLE
Can't navigate to the library until I import some resources 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10600]
## Observed behavior
[Reported by @MisRob and replicated by @radinamatic in the alpha 13 bug bash ](https://www.notion.so/learningequality/I-can-t-navigate-to-library-until-I-import-some-resources-3ac82561cb794a3fa91a6b0e79514171?pvs=4)

## Errors and logs

![error1](https://user-images.githubusercontent.com/17235236/235466301-cf58943a-b41b-4815-9c12-3350441b5f80.gif)

## Expected behavior
Should be resolve at least partially in connection with https://github.com/learningequality/kolibri/issues/10599 which will allow users who are on a local network to browse other kolibris. 

We might need some clarification of expected behavior in other scenarios @jtamiace @rtibbles 

## User-facing consequences
User is unable to navigate 

## Context
v0.16.0-a13

**Comment by rtibbles** [comment]
I think just not displaying the Home and bookmarks tabs when there are no resources available locally would be important as well.

**Comment by thanksameeelian** [comment]
this also occurs outside of remote browsing in the case of importing a user from an existing facility onto a fresh device, when attempting to navigate with the top nav or side nav 
![image](https://github.com/learningequality/kolibri/assets/43046460/f2b6a273-4895-4b2b-ad81-e8f356e79bfb)
![image](https://github.com/learningequality/kolibri/assets/43046460/5ea01040-2899-4c98-aa26-5132d0a6b6a3)

**Comment by akolson** [comment]
So I managed to fix the issues raised here. Just wondering what would be the preferred behavior for the `Home` and `Bookmark` options that stay visible and provide an access route to the the `resources-unavailable` page. It doesn't look like there is a direct way to hide side menu options presently, though I could be mistaken. Any thoughts @rtibbles @marcellamaki ?

**Comment by rtibbles** [comment]
We can toggle whether the menu options are shown by doing a conditional check inside the routes specified in https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/LearnSideNavEntry.js#L12 

However - while I think this would be the ideal solution, the tricky thing is making this responsive once new resources have been imported - as soon as a resource is imported, we would need these routes to update, but we are not proactively monitoring this state. With that in mind, I'd argue counter to my past self, and say we should just leave them there for now.

**Comment by akolson** [comment]
Okay. I did try adding the conditionals on to the `LearbSideNavEntry.js` but experience the same pitfall you describe above. I will now open a pr for the changes I was able to make regarding this task, also reverting the previous hiding of tabs for now
