### ISSUE TITLE
Progress on content is still being tracked when the resource does not load

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10603]
## Observed behavior
Reported by @nucleogenesis[ in the alpha 13 bug bash ](https://www.notion.so/learningequality/Progress-on-content-is-still-being-tracked-when-the-resource-does-not-load-42291a7d67b74f308a54e8686d75ef9d?pvs=4)

> Related to the[ “resource not available” bug ](https://github.com/learningequality/kolibri/issues/10602)I noted above — despite the content not loading, I can see that I have 25% of progress because I was writing up my bug with the content renderer still open

## Expected behavior
Resource should load, and progress should only occur for a resource that the user is actively interacting with

## User-facing consequences
Could incorrectly reflect progress - which would be confusing to coaches and learners

## Steps to reproduce
Access a remote zip content resource, and allow the browser 

## Context
v0.16.0-a13

**Comment by rtibbles** [comment]
Note that I think this will be resolved by proper handling of resource loading errors, as tracked in #10393
