### ISSUE TITLE
Should be able to unpin a channel from the library page 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10605]
## Observed behavior
[Reported by @nucleogenesis in the alpha 13 bug bash ](https://www.notion.so/learningequality/Should-be-able-to-unpin-a-channel-from-the-library-page-4c528d3930f64dd4a9b2763d1de69b14?pvs=4)

You cannot unpin a channel from the library page once you have pinned it

## Context
0.16.0-a13

**Comment by AllanOXDi** [comment]
I was able to pin and unpin devices successfully. And basing on our slack conversation it appears that title here is inaccurate too. It was just an incorrect expected behavior reported in the bug bash.
