### ISSUE TITLE
Toggle button not working properly with its props 

### ISSUE THREAD

**Issue by Pursottam6003** [learningequality/kolibri#10617]
## Observed behavior

There are toggle buttons to help the user to switch  between two different states but here in some parts, the toggle button is not working properly and it's not able to change its state 

Moreover, even its able to change its state but unable to display those changes in the frontend 

## Errors and logs

[Screencast from 02-05-23 06:15:09 PM IST.webm](https://user-images.githubusercontent.com/81693090/235673299-e3d75c21-fa6d-4f95-8bc5-75713e0fc29c.webm)

## Expected behavior

It should be able to toggle between visible to non-visible with the correct active display 

## User-facing consequences

Its quite difficult for the admin to identify whether it is visible to learners

## Steps to reproduce

1. Navigate towards Coach 
2. Navigate towards your class
3. Click on any particular lesson 
4. Toggle the button visible to learners

## Context

…

**Comment by rtibbles** [comment]
I believe this should be resolved by #10720

**Comment by pcenov** [comment]
Hi @rtibbles I confirm that this has been resolved by https://github.com/learningequality/kolibri/pull/10720:

https://github.com/learningequality/kolibri/assets/79847249/ca851ec7-9442-4c5b-a1eb-f782c6023d57
