### ISSUE TITLE
Issue Running Development Server

### ISSUE THREAD

**Issue by estelacruz** [learningequality/kolibri#10654]
## Observed behavior

After successfully installing the required and optional dependencies, I still cannot run the dev server. Below is a screenshot of my terminal output:

## Errors and logs

<img width="1096" alt="Screen Shot 2023-05-07 at 4 01 59 PM" src="https://user-images.githubusercontent.com/79770461/236700886-fd9b0448-19a2-466b-b68e-8c388248dda4.png">

<img width="1088" alt="Screen Shot 2023-05-07 at 4 02 21 PM" src="https://user-images.githubusercontent.com/79770461/236700918-5a3a2e41-4c14-4056-919d-005de549debc.png">

<img width="1063" alt="Screen Shot 2023-05-07 at 4 02 41 PM" src="https://user-images.githubusercontent.com/79770461/236700921-d8ac565b-f5ef-42ca-9167-d3af9803f708.png">

<img width="1079" alt="Screen Shot 2023-05-07 at 4 02 54 PM" src="https://user-images.githubusercontent.com/79770461/236700925-beef0bbc-7edd-4cb1-beb9-e0ccf23c7cfa.png">

<img width="1070" alt="Screen Shot 2023-05-07 at 4 03 23 PM" src="https://user-images.githubusercontent.com/79770461/236700927-144b3d3e-70ef-4110-a361-b256c29b29df.png">

## Context
As suggested, I ran the"kolibri stop" command and tried to run the dev server after, but I still got the same error message. This has been an ongoing error even after uninstalling and reinstalling Kolibri as well as its dependencies -- I would appreciate any advice on how to troubleshoot!

- I am running on M1 MacOS.

**Comment by estelacruz** [comment]
I also tried to limit the specific frontend bundles that are built and watched by running 
"yarn run devserver-hot learn" 

This is a screenshot of the server's traceback error:

<img width="679" alt="Screen Shot 2023-05-07 at 4 34 34 PM" src="https://user-images.githubusercontent.com/79770461/236701464-0b104423-3955-4fee-9793-439a636c39f9.png">

This is the same error I have been getting in the past regardless of my attempted workarounds. Any advice from the community is appreciated!

**Comment by estelacruz** [comment]
Hello, I uninstalled (and reinstalled) Kolibri one more time and I finally got the dev server to run! I am unsure of another work around other than uninstalling but if anyone happens to see this and has tips for others who might encounter this issue, I think it would be a great contribution.

**Comment by MisRob** [comment]
Thank you, @estelacruz, happy to hear that it's running finally on your machine
