### ISSUE TITLE
Add a "Tip" on Developer Documentation 

### ISSUE THREAD

**Issue by estelacruz** [learningequality/kolibri#10655]
## Observed behavior

I have had issues installing project dependencies in the past, and want to suggest that we add a "tip" section to the "Install Python dependencies" section on the developer documentation so that if other users experience similar issues, they try this workaround.

Suggested Tip Section:

<img width="684" alt="Screen Shot 2023-05-07 at 5 10 49 PM" src="https://user-images.githubusercontent.com/79770461/236702761-2f55864a-acd8-4f5a-98d1-3b7c67de3060.png">

## Issue Context 

Under another Github issue, @Wck-iipi provided me with this tip after being unable to run "pip install -e ." and it worked for me. As seen below, @Wck-iipi experienced a similar issue (shoutout to them for the resolution), so I think this can definitely benefit the developer community!

<img width="686" alt="Screen Shot 2023-05-07 at 5 00 57 PM" src="https://user-images.githubusercontent.com/79770461/236702570-c961fa8d-cf52-42d6-9197-cc1bb0999472.png">

## Errors and logs

Below is my terminal output after following the developer documentation step by step: 

<img width="564" alt="Screen Shot 2023-05-07 at 5 01 38 PM" src="https://user-images.githubusercontent.com/79770461/236702591-2679aa36-79f9-4447-a4fb-9417978ad9f9.png">

After upgrading setuptools, I was able to run the command "pip install e ."

<img width="876" alt="Screen Shot 2023-05-07 at 5 02 11 PM" src="https://user-images.githubusercontent.com/79770461/236702635-9c37329c-56a4-4d58-8707-b35e00200a95.png">

If you would like to include this on the developer documentation, I would be happy to be assigned this issue. Thank you for your time.

## Computer Context
I am running on M1 MacOS.

**Comment by Wck-iipi** [comment]
If this issue does get noticed, please add node installation of develop and main branches as 2 separate code blocks and not in one with comment. This is extremely confusing for beginners(personal experience).

**Comment by rtibbles** [comment]
This should have been resolved by removing the installation of build requirements from the suggested developer setup, so we will leave that as the resolution here.
