### ISSUE TITLE
Change learning facility - No facilities displayed when attempting to merge a second learner

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10661]
## Observed behavior
After having successfully merged one of the learners on the facility if I sign in as another learner then I am not able to merge that learner because no facilities get displayed at 'Select learning facility'. I tried restarting both servers but that changes nothing. Also tried manually adding the Server URL but that doesn't help either.

I'm seeing the following error in the console:
`[{"id":"PERMISSION_DENIED","metadata":{"view":"Network Location List"}}]`

## Expected behavior
Unless otherwise specified it should be able to merge learners consecutively.

## Steps to reproduce the issue
1. On device 1 setup a full facility
2. On device 2 setup a On my own facility and add learners
3. On device 2 sign in as one of the learners and go through the 'Change learning facility' flow
4. Sign out the merged user and sign in as another learner
5. Attempt to go through the 'Change learning facility' flow - no facilities get displayed.

## Video

https://github.com/learningequality/kolibri/assets/79847249/7e543787-bec1-4341-9d46-73ff7c1cbf56

## Usage Details
Kolibri 0.16alfa13
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
cc @jredrejo
