### ISSUE TITLE
Ensure metered connection notification appears at point of bandwidth usage

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10662]
## Overview

The `MeteredConnectionNotificationModal` determines if the criteria are met based on settings to decide whether it should be shown or not. Because of this, we can "trigger" it's appearance by way of a `v-if`whenever the user takes an action that would warrant showing it.

Here we just need to polish things, put the new component where it belongs and show it when it needs to be shown. 

Follow-up from #10624 

## Acceptance criteria

- [x] Remove `MeteredConnectionNotificationModal` from the `core...AppBarPage.vue` file as this was used for QA testing.
- [x] Clean up any debugging and `console.log` from https://github.com/learningequality/kolibri/pull/10624
- [x] Ensure the modal shows up at the point of first potential bandwidth usage - when a logged in user goes to the Library Page, we need to:
  * Check if the metered connection setting is set - if allowed, carry on
  * If unset, or set to disallow, check whether we are on a metered connection
  * If we are not on a metered connection, carry on
  * If we are on a metered connection and it is set to disallow, do not display of the Other Libraries section (if it is hidden via v-if the bandwidth incurring loading within it should not occur)
  * If we are on a metered connection and the setting is currently unset, display the modal
  * Depending on how the user sets the setting do the appropriate from the above!

Out of scope/needs decisions - what to do if a user has disabled download, but tries to download content. 

<img width="557" alt="Screenshot 2023-05-09 at 9 21 59 AM" src="https://github.com/learningequality/kolibri/assets/17235236/3ccc494a-d786-4d3b-8bd3-45150e3ffdd0">
<img width="559" alt="Screenshot 2023-05-09 at 9 22 18 AM" src="https://github.com/learningequality/kolibri/assets/17235236/45dee5a4-407a-4c57-9b9d-a6d54aea5e4e">

## Additional guidance

You will need to configure your Kolibri such that:
  
* The device setting for allowing downloads on a metered connection is set to do so
* The `integration_testing/scripts/run_kolibri_app_mode.py` script should be returning `True` in the `check_is_metered` function defined there -- (or `False` if you're testing that it doesn't show, although that passed QA in #10624)
* You are signed in as a `superuser`
* You have cleared your browser session storage - namely the `METERED_NETWORK_MODAL_DISMISSED` entry, in case you've dismissed it previously

Now, by using the `yarn run app-devserver`command, you can run Kolibri "in App mode" -- so with the aforementioned in place you should be working in what is basically the Android app.

**Comment by rtibbles** [comment]
Once this has been finalized, [this commit](https://github.com/learningequality/kolibri-installer-android/commit/3de3514b2bd256a75d70c46f18f6c7cac97c7a79) in the Android installer repo should be reverted to finalize integration there.
