### ISSUE TITLE
Alignment differences between Chrome and Firefox on smaller mobile screens

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1067]
## Summary

1. Seems as if the left margin is missing on both FF and Chrome but only on Andorid phones, the one on iPhone is decent enough.

Another thing I noticed is that it seems to start loading with the margin correctly in place, but once everything is fully loaded, content jumps left and goes outside.  

## System information

 - Version: 0.2.0alpha5.dev35
 - Operating system:  iPhone 5S & Andorid 4.2.2
 - Browser: all (Chrome, Firefox)

### Chrome (Android left, iPhone right)
![exercise2](https://cloud.githubusercontent.com/assets/1457929/23866514/4ff0fb5c-07d6-11e7-8d34-475ff9b770bf.JPG)

2. Missing image on iPhone is reported in #1049, so I can't confidently test the issue of the answer field being "glued" on it on iPhone is the same as in Android. 

![exercise3](https://cloud.githubusercontent.com/assets/1457929/23867492/4da233ea-07d9-11e7-8798-525ca18829e5.JPG)

### Firefox (Android left, iPhone right)
![exercise5](https://cloud.githubusercontent.com/assets/1457929/23866550/6a273c7a-07d6-11e7-9b2d-ceb28889a9c4.JPG)

**Comment by christianmemije** [comment]
@radinamatic Can you confirm this still exists on Develop?

**Comment by radinamatic** [comment]
Nope, not extant anymore on latest develop! :+1:
