### ISSUE TITLE
[Setup Wizard] canceling individual user import prior to syncing still imports user

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#10675]
related to issue #9495 

## Observed behavior
When setting up a fresh learn-only device and importing a user from a remote full-facility device, if you cancel the import and choose to import a different user, both users will be imported and the canceled user will register as the first imported user and therefore be made superadmin.

https://github.com/learningequality/kolibri/assets/43046460/a1f782e8-9e85-4dab-a102-6095c9589691

## Errors and logs
**current understanding is that this is likely related to the process in which we initially get a certificate corresponding to the selected user from the remote server and store it locally, but this certificate is not locally removed upon "cancel"**

- no unexpected errors - initial errors upon `Continue` are expected until/unless user selects `Import`
- payload in successful POST to `/api/tasks/tasks` endpoint after `Import` includes only the intended user (and not the canceled user)

## Expected behavior
only accounts which have been selected for import by the user should be imported. if the user cancels importing an account once the "Device limitations" modal appears, that account should not be imported.

## User-facing consequences
user may believe they have imported 1 account which will be a superadmin, but those privileges will be assigned to the wrong account if the user initially selects but cancels import of a different account. 

## Steps to reproduce
- create/have credentials for 2 users on a full-facility device, each with admin or coach permissions
- on a fresh learn-only device, step through SetupWizard:
   `Group Learning` > `Learn-only device` > `Import one or more existing users...` > Enter credentials for first user > `Continue` > `Cancel` in "device limitations" modal > Enter credentials for second user > `Import` in "device limitations" modal > `Finish` > once new device loads, `Device` > `Permissions` --> instead of only second user, the list of users will include both the first & second user, with the first user having superadmin permissions on the device

**Comment by bjester** [comment]
Is the 'first user' an admin of the facility?

**Comment by thanksameeelian** [comment]
> Is the 'first user' an admin of the facility?

i tried this with the first user being a coach (entered credentials, hit `continue`, got the "device limitations" modal, hit `cancel`) & the second one being an admin (re-entered credentials, hit `continue`, got the "device limitations" modal, hit `import`) => first user comes across as superadmin on new device. i also tried it with the order reversed, `cancel`ing an admin and then `import`ing a coach. in both cases, the user that was attempted first became the superadmin on the new device, regardless if they were originally an admin or a coach in the facility they were imported from. 

if this is answering the wrong question, please just let me know! 🙂

**Comment by bjester** [comment]
Hmm okay I don't suspect the Morango certificates to cause any of this behavior, especially if the first user wasn't a facility admin. I suspect there must be some state management issue where the reference to the first user is persisting
