### ISSUE TITLE
Internet Explorer 11 - 'Kolibri is unable to render this resource' error when viewing PDF resources

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10707]
## Observed behavior
It's not possible to view PDF resources in Internet Explorer 11 both while working on an assigned lesson or viewing the resource in the Library page.

## Expected behavior
It should be possible to view PDF resource when using Internet Explorer 11

## Steps to reproduce the issue
1. Install the the following [0. 16 build](https://github.com/learningequality/kolibri/pull/10701) 
2. Attempt to to view PDF resources using Internet Explorer 11

## Screenshot
![2023-05-15_15-52-34](https://github.com/learningequality/kolibri/assets/79847249/151be212-b646-4903-b60c-d02ec45f1734)

## Usage Details
Windows 10 - Internet Explorer 11

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
@pcenov - do you recall the last time we checked this (specifically on ie11)? @radinamatic I'm wondering if we tested Alex's work on ie 11? I imagine yes, but if it's specific to PDFs I am curious if it's related to those updates

**Comment by radinamatic** [comment]
I don't recall testing Alex's work on IE11... Since I was concentrated on testing with the screen reader, that was not a likely combination.

**Comment by pcenov** [comment]
@marcellamaki yes it's quite possible that this was introduced by Alex's updates there and somehow slipped through the cracks. I've also just confirmed that it's extant in Kolibri 0.15.12.

**Comment by marcellamaki** [comment]
Thank you! That makes sense with the testing focus, @radinamatic. And thanks for the helpful context @pcenov

**Comment by rtibbles** [comment]
I suspect that the fix in #10701 simply may not have gone far enough and that we do need to be transpiling all sources unless absolutely necessary not to.
