### ISSUE TITLE
Inconsistent naming in api-resources for MasteryLog and AttemptLog

### ISSUE THREAD

**Issue by 66eli77** [learningequality/kolibri#1070]
In [`kolibri/core/assets/src/api-resources/index.js`](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/api-resources/index.js#L15):

```javascript
  MasteryLog: require('./masteryLog'),
  AttemptLog: require('./attemptLog'),
```

should be renamed:

```javascript
  MasteryLogResource: require('./masteryLog'),
  AttemptLogResource: require('./attemptLog'),
```

**Comment by indirectlylit** [comment]
In [that file](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/api-resources/index.js#L15):

```javascript
  MasteryLog: require('./masteryLog'),
  AttemptLog: require('./attemptLog'),
```

What's the inconsistency?

**Comment by indirectlylit** [comment]
oh - I adding `Resource` - got it.

**Comment by rtibbles** [comment]
Fixed.
