### ISSUE TITLE
coach: multi-facility user briefly sees 1st facility's class list when navigating to a class in 2nd facility

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#10714]
## Observed behavior

As a multi-facility admin user, when I navigate to the `Coach` > `Class home` page and am redirected to the list of my facilities, select the second facility in the list, and select any class, there is a split-second flash of the _other_ facility's (my default facility) class list, which renders in the view before I am successfully navigated to the class initially selected. 

No matter the order in which I select them, when I click on _Class2A_ in **_Mr. Tibbles' House of Phun_**, the brief flash of my other facility's classes is (usually) visible to the naked eye, and clicking on _Class1B_ leads to the same experience but also an error in the console. I don't experience this when selecting classes from my default facility.

https://github.com/learningequality/kolibri/assets/43046460/aa82810d-b9c3-4dec-b62f-be0972fd88dc

now in slow motion!
![slo-mo](https://github.com/learningequality/kolibri/assets/43046460/ad36e906-a8ef-4308-8907-38abe99de20e)

## Errors and logs
![image](https://github.com/learningequality/kolibri/assets/43046460/1c649a14-fa2e-4194-aacc-60055b231354)

## Expected behavior
Clicking on a link to a class within a specific facility will navigate straight to that class, without any other views rendering

## User-facing consequences
currently appears cosmetic, as user is ultimately navigated to the correct place.

a potential scenario: a user's machine & browser are running slowly and the short flash of the other facility's classes is visible for longer than in the screen recording, and during the interim the user clicks in the same spot their cursor already is, but since the link below their cursor had changed they'll potentially be redirected to the page for a class they didn't intend to select.

## Steps to reproduce
- user must be a multi-facility admin
-  it may be useful to record your screen, as the unexpected view of the other facility's classes may be visible only very briefly
- navigate to `Coach` > `Class home` and select user's _non-default_ facility upon redirect to the `Facilities` page
- select a class from that facility
- during navigation to that class's page, the view will momentarily change to reflect the list of classes from user's default facility before the intended view renders and user has been navigated to the initially-selected class's page. 

**_Note:_** reported console error may be specific to facility & class selected in screen recording (_**Mr. Tibbles' House of Phun**_ - _Class1B_), but the overall behavior described was seen for all classes in non-default facility, and not observed when intentionally navigating to classes within default facility.

## Context
Chrome - `develop` branch of Kolibri

**Comment by marcellamaki** [comment]
@thanksameeelian - just curious if you tried this out with a throttled browser speed to see if the scenario you describe 

> a user's machine & browser are running slowly and the short flash of the other facility's classes is visible for longer than in the screen recording,

might be happening for users who are on a slower system? If so, we might want to bump up the priority here a little bit 


If you haven't used throttling for testing performance before, you can update it here in Chrome.
<img width="615" alt="Screenshot 2023-05-22 at 3 30 59 PM" src="https://github.com/learningequality/kolibri/assets/17235236/78419fb3-fcfa-4919-aa62-371ded622ec8">
<img width="627" alt="Screenshot 2023-05-22 at 3 31 06 PM" src="https://github.com/learningequality/kolibri/assets/17235236/6fb22394-9e19-4c63-bcba-242240201189">

**Comment by thanksameeelian** [comment]
@marcellamaki thanks for this!! the problem is much more evident when i intentionally throttle the browser speed. in all these cases i'm a multi-facility user.

navigating from a link on my imported facility's "All classes" page, i was shown my default facility's "all classes" page for long enough that i could click on a class there and cause a little bit of additional chaos:

https://github.com/learningequality/kolibri/assets/43046460/6bb2424f-6d5a-4a6d-9f7d-68c3af5c8298




other things that throttling revealed in the same area (but may be solved by already-ongoing work on loading state?):

when i try to navigate to my default facility, which only has one class, on slow 3G i actually see two different views before the one we intend, as we should be navigating directly to the class home if there is only one class. both an empty "no classes" page & an "all classes" page containing 1 class are visible for long enough periods of time that i could click something on the temporarily-rendered page

https://github.com/learningequality/kolibri/assets/43046460/768ec029-55f1-45c4-bc1a-a2f827decce2

in my imported facility, i have multiple classes, and am shown "no classes" before reaching the intended "All classes" page.

https://github.com/learningequality/kolibri/assets/43046460/6848951a-17aa-4884-9fb6-113bdc6f7858

**Comment by thanksameeelian** [comment]
> just curious if you tried this out with a throttled browser speed to see if the scenario you describe might be happening for users who are on a slower system? If so, we might want to bump up the priority here a little bit

so the short answer is yes! :)

**Comment by nucleogenesis** [comment]
@radinamatic if this issue replicates please assign it to me and I'll resolve it directly - but I am pretty sure I fixed this in f5153e9e55c058b4b6d9921968b580bf594aace7 in #10455 🤞🏻

**Comment by pcenov** [comment]
@radinamatic I confirm that this is fixed now:

https://github.com/learningequality/kolibri/assets/79847249/020f3fa8-ad7f-4ee3-92c3-74d31563a4af

**Comment by radinamatic** [comment]
Excellent, thank you! 💯 

Closing as fixed! 💥
