### ISSUE TITLE
Add 0,75 as playback speed

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10717]
## Observed behavior

Many of my students thinks they are speaking to quickly in the videoes as English is their 2nd language. 0,5 is too slow for the video speed, but 0,75 will probably be a good speed for slowing down the speed a bit.

<img width="918" alt="msedge_iOCHmzZbmK" src="https://github.com/learningequality/kolibri/assets/148026/aafb75d1-c4a7-4766-b2f6-8a32e1fd003d">

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

…

**Comment by marcellamaki** [comment]
Thank you for sharing this feedback, @lsolesen! We will look into the possibility of adding this in an upcoming release.

**Comment by GarvitSinghal47** [comment]
@marcellamaki i would like to work on this , can you assign it to me .

**Comment by marcellamaki** [comment]
Thanks @GarvitSinghal47 - I have assigned you. (I've also added myself, to keep track and check in with you)

**Comment by rtibbles** [comment]
Fixed in #11164 - @lsolesen this change will be released as part of the upcoming 0.16.0 release.
