### ISSUE TITLE
Update loading state in Coach

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10729]
## Observed behavior
Plugin specific follow up to https://github.com/learningequality/kolibri/issues/10336

## Expected behavior
When navigating through the coach plugin, users should see proper loading states. If an entire page is loading, the "linear loader" should be displayed at the top of the page. If a section of the page is loading (i.e. the contents of a table, a list of resources) then the circular spinner loader should be used. 

## User-facing consequences
User should have a consistent, smooth experience that properly indicates when there is a transition is happening and/or when data is being loaded.

## Steps to reproduce
Using the "throttle" function on Google chrome with Slow 3G is a helpful way to find problem areas. 

```[tasklist]
### Tasks
- [ ] Investigate and fix https://github.com/learningequality/kolibri/issues/10797
```

**Comment by thanksameeelian** [comment]
potentially related to #10714

**Comment by thanksameeelian** [comment]
potentially related to #10797

**Comment by nucleogenesis** [comment]
Noting that #10731 adds an `isPageLoading` getter that can be used to conditionalize cleanly on whether the page is being loaded. 

Generally, my approach there was to ensure we call `store.dispatch('loading')` and `store.dispatch('notLoading')` in the handlers that show the pages and to be sure that the `*?AppBarPage` component has the `isPageLoading` passed to it. When data is being loaded dynamically (ie, a part of an already-loaded page is loading data), then a local-to-that-context piece of data should be used to conditionally show a `KCircularLoader` in place of where the content will be shown.
