### ISSUE TITLE
App Bar navigation items don't have tab focus

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10726]
> One thing I noticed is that we aren't able to focus the AppBar -- is that to be expected since it's basically reflected in the SideNav as well?

_Originally posted by @nucleogenesis in https://github.com/learningequality/kolibri/pull/9922#pullrequestreview-1427276416_

**Comment by radinamatic** [comment]
Keyboard-navigating through the AppBar options could be improved (for example keeping the focus on the selected/current tab after the page reload, so the user does not need to Tab-navigate from the very beginning each time), but I don't see any other blocker here... 🤔 


https://github.com/learningequality/kolibri/assets/1457929/b0611160-3c51-4075-a46f-e0fc311404af



Going to close as not extant.
