### ISSUE TITLE
Disconnected status always shown when browsing the Kolibri [Studio] library

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#10721]
## Observed behavior

A disconnected icon/status is displayed when a user browses the studio library.
<img width="1798" alt="Screenshot 2023-05-18 at 22 58 37" src="https://github.com/learningequality/kolibri/assets/5203639/ae6ff500-dc6f-40d0-8afe-377f21215559">

## Expected behavior

The disconnected icon/status should only be displayed when the studio library is unavailable/goes offline in the process of browsing its resources

## User-facing consequences

The status is misleading to the user at that any point in time.

## Steps to reproduce

- Remember to run Zerotier. This should already be set up from earlier sessions, but you may need to reopen the application. Incase you need a refresher on setup, please visit [ZeroTier](https://www.notion.so/ZeroTier-3e508bf09b7e4c72a1713b8374a43cac)
- To view the Kolibri Library when exploring libraries, set the environment variable below before you run the app file
   - `KOLIBRI_CENTRAL_CONTENT_BASE_URL=https://unstable.studio.learningequality.org`
- Go to `/learn/#/library`
- Click on the `Explore` card under the Kolibri library section

## Context

`0.16.0-alpha13`

**Comment by radinamatic** [comment]
Tested the asset on 2 different VMs, in one as an admin on the group learning setup, and on the other as 'on-my-own' user setup. In both cases the disconnected status from the Kolibri Studio was not extant anymore.


https://github.com/learningequality/kolibri/assets/1457929/1f2577b9-1e85-410b-8f0a-0017784cf700

The only thing that would be good to clarify is the exact name of the environment variable, as when I initially set `KOLIBRI_CENTRAL_CONTENT_BASE_URL=https://unstable.studio.learningequality.org` I was unable to see the Kolibri Library in both VMs. 

Only after I changed it to `CENTRAL_CONTENT_BASE_URL=https://unstable.studio.learningequality.org`, that is without the initial `KOLIBRI_` (see the recording above), it did appear in the Library tab.
