### ISSUE TITLE
InsufficientStorage error raised after running a full sync with KDP

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10732]
## Observed behavior

After running a full sync with KDP, the InsufficientStorage error was raised from the function `_process_content_requests`. The message `Content download requests need 0B of free space` was received which suggests that the user does not have enough storage, despite free_space being `15061171584`

Possibly caused by this [while statement](https://github.com/learningequality/kolibri/blob/4cf6a66db0714f76735d2b695d4291276b7b2d4b/kolibri/core/content/utils/content_request.py#LL404C2-L404C2) or [download_request assignment](https://github.com/learningequality/kolibri/blob/4cf6a66db0714f76735d2b695d4291276b7b2d4b/kolibri/core/content/utils/content_request.py#L419) within `content_request.py`

Relevant:
- It was the first time this facility had synced to KDP
- Registration was skipped
- Lessons and quizzes were in the local facility data (the lessons & quizzes were created, and the resources used were then deleted from the device)
## Errors and logs

```
[python-devserver] DEBUG    2023-05-21 17:07:53,388 Did not find suitable download request for free space 15061171584
[python-devserver] WARNING  2023-05-21 17:07:53,392 Content download requests need 0B of free space
[python-devserver] ERROR    2023-05-21 17:07:53,393 Job ca69893aff45483e8bc769daf078c825 raised an exception: Traceback (most recent call last):
[python-devserver]   File "/home/richard/github/kolibri/kolibri/core/content/utils/content_request.py", line 266, in process_content_requests
[python-devserver]     _process_content_requests(incomplete_downloads)
[python-devserver]   File "/home/richard/github/kolibri/kolibri/core/content/utils/content_request.py", line 445, in _process_content_requests
[python-devserver]     raise InsufficientStorage(
[python-devserver] kolibri.core.content.utils.content_request.InsufficientStorage: Content download requests need 0B of free space
```

## Expected behavior

If there is enough free space, the `download_request` should be able to be processed.
## User-facing consequences

User devices unable to process download requests despite having enough space to do so.

**Comment by bjester** [comment]
I believe I fixed this in this PR https://github.com/learningequality/kolibri/pull/11083. There were several issues with the annotation queries
