### ISSUE TITLE
Adding a custom text color picker for Kolibri EPUB renderer : GSoC '23

### ISSUE THREAD

**Issue by akila-i** [learningequality/kolibri#10741]
## Observed behavior

- Kolibri EPUB renderer currently has 6 fixed built in themes, which are not allowed to be edited by users
- Kolibri does not allow adding new color themes to the EPUB renderer with the colors of user's preference

## Errors and logs

No errors or logs with unexpected behaviour on Kolibri EPUB renderer.

## Expected behavior

- Users will be able to add custom color themes to the EPUB renderer with their preferred text color, background color, and links color.
- Users will be able to edit (change the colors)  and delete the custom themes as they wish.

## User-facing consequences

- Custom color themes will increase the accessibility of Kolibri EPUB renderer for visually impaired users and users overall.

## Steps to reproduce

No errors or logs with unexpected behaviour on Kolibri EPUB renderer.

## Checklist for tasks to be done
 - [ ] Add a separate section to accommodate custom themes in EPUB renderer UI
  -  - [x] Grid Element
  -  - [x] Grid items for themes
  -  - [x] Tick Icon for selected theme
 - [ ] Add functionality to apply the custom theme to EPUB renderer when clicked
  -  - [x]  Set_Theme function for custom themes
  -  - [x] Make the set_theme function to support both fixed and custom themes interchangably
 - [ ] Add a color picker for themes
  -  - [x] Modal with text color, background color, link color, and a preview of the theme
  -  - [x] Color picker modal which will pop when text color, bg color or link color is clicked
  -  - [x] Handle states of selected colors
 - [ ] Save the color themes in local storage
  -  - [x] Save to the storage when a new theme is added
  -  - [x] Delete from storage when a custom theme is removed
  - [x] Modify epub.js usage to change the link color in EPUB
  - [ ] Fix focus management in modal
  - [x] Add warnings for unsigned users when saving a theme
  - [ ] Add context labels for screen readers

**Comment by marcellamaki** [comment]
Completed with Akila's GSoC Project in #11041
