### ISSUE TITLE
let exercise content scroll horizontally when necessary

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1074]
Some content may have a minimum width that is wider than the viewport:

![image](https://cloud.githubusercontent.com/assets/2367265/23971370/ef683942-098a-11e7-97a1-c472663e4a2b.png)

In these instances, the content should scroll horizontally. The white background should extend the full width of the content.

**Comment by christianmemije** [comment]
`overflow-x: auto` ??

**Comment by indirectlylit** [comment]
that should be the plan! but where does it go... :)

**Comment by christianmemije** [comment]
Right here https://github.com/learningequality/kolibri-exercise-perseus-plugin/blob/master/kolibri_exercise_perseus_plugin/assets/src/vue/perseus.vue#L386

**Comment by christianmemije** [comment]
https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/50

**Comment by indirectlylit** [comment]
nice
