### ISSUE TITLE
Scheduled sync - The 'Last synced' value won't auto-update

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10759]
## Observed behavior
Reporting this as a follow-up issue noticed in https://github.com/learningequality/kolibri/pull/10748
When a sync is happening while one is at the Facilities page, the 'Last synced' value doesn't update unless I manually refresh the page.

## Expected behavior
The 'Last synced' value should get updated immediately.

## Steps to reproduce the issue
1. Install the latest build asset from https://github.com/learningequality/kolibri/pull/10748
2. Create a scheduled sync either for a device or KDP
3. Observe the behavior of the 'Last synced' value immediately after the sync has occurred.

## Video

https://github.com/learningequality/kolibri/assets/79847249/ae9bcd27-a85a-48f1-a5b4-4c97fcba223a

## Usage Details
Kolibri 0.16alfa14
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #12158
