### ISSUE TITLE
Managing a Kolibri long distance

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10756]
## Observed behavior

I am leaving a small organization in Zambia, where we have implemented Kolibri. I live in Europe myself and will not be able to come back often. However, we are planning on training the volunteers from the organization in Europe also using the same facility, so they have access to the same content in Denmark and in Zambia.

We can train them to make updates from the computers in Denmark, when they come to the project. But is it possible to have a computer in Zambia that is updated with potential changes in Denmark. Or should this be done locally always? 
…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

 * Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Chrome
…

**Comment by bjester** [comment]
@lsolesen please submit your question to [our community forum](https://community.learningequality.org/)
