### ISSUE TITLE
Update device provisioning so that first user is given superadmin permissions

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10769]
## Observed behavior
Currently, our device provisioning grants the first of a provisioned device 'content management' permissions. Because this user is not granted 'super admin' permissions, the device never has a superadmin. 

## Desired behavior
The provisioning should be updated so that the first user has 'device superuser permissions'. 

## User-facing consequences
This update will allow for much better management of provisioned devices. Related problems have been reported by S2S regarding the difficulty of re-provisioning devices, or otherwise managing provisioned devices. This update will be a first step to alleviating some of these concerns, and by creating the superuser, it will allow for more work to build on top of this, to further improve the workflows around device provisioning.

In 0.15, we avoided doing this, as there was concern about granting full superuser permissions to the learner imported onto the device. However, in 0.16, we are mitigating against this with the PIN functionality, to allow some restrictions on access. This means that the downsides of not having a super admin outweight these risks.

**Comment by nucleogenesis** [comment]
@akolson do you recall if the PIN prompt checks the user type (ie, if the user is a SuperAdmin, don't show the PIN prompt)?

**Comment by akolson** [comment]
Yes, we do check for the user type. More precisely we check for
```
if (get(isLearnerOnlyImport) && !isFacilityAdmin && (isSuperuser || userCanManageContent)) {...}
```
