### ISSUE TITLE
Allow importing all content thumbnails in a channel

### ISSUE THREAD

**Issue by dbnicholson** [learningequality/kolibri#10770]
## Observed behavior

Currently when importing content via the API or CLI, you can specify content nodes to include or exclude. That's very useful for limiting the desired content. However, we'd like to be able to get the thumbnails for excluded nodes so that they can be displayed as available to download. We've found that without the content thumbnail the node is uninteresting to users.

## Errors and logs

There are no errors, just the lack of the desired content.

## Expected behavior

Currently working as expected.

## User-facing consequences

With the content thumbnail available on locally, users with the ability to download content to the device are given a better visual cue for what might interest them.

## Steps to reproduce

Import a subset of a channel's content nodes:
```
kolibri manage importcontent <somechannel> --node-ids <somenodeids>
```

Go to the Device page, Manage the channel and click Import More. Note that there are only generic icons next to the node titles.

## Context

0.16.0a14, any OS or browser

**Comment by rtibbles** [comment]
The remaining frontend pieces of this are wontfix - as Kolibri will instead rely on remote preview functionality to provide the user experience here.
