### ISSUE TITLE
Scheduled sync - The 'Frequency' drop-down is labeled incorrectly

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10778]
## Observed behavior
This as a follow-up issue noticed in https://github.com/learningequality/kolibri/pull/10748
The 'Frequency' drop-down is labeled incorrectly as 'Frequence'

## Expected behavior
The label should be corrected.

## Steps to reproduce the issue
1. Install the latest build asset from https://github.com/learningequality/kolibri/pull/10748
2. Go to Device > Facility
3. Click the 'Create sync schedule' link
4. Click 'Add device' and select either KDP or Local network

## Screenshot
![2023-06-02_18-32-38](https://github.com/learningequality/kolibri/assets/79847249/014913c3-ff21-4ea1-94e9-f8e970f6ab1d)

## Usage Details
Kolibri 0.16alfa14
Windows 10, Ubuntu - Chrome

**Comment by Shashank245** [comment]
Hello, I have made the changes in the files and corrected the Label "Frequency" and created the PR for the same. Thank you!
