### ISSUE TITLE
Channel looses spot in channel order after being updated

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10790]
## Observed behavior

First, I order my channels.

<img width="898" alt="msedge_JHAq09bCMx" src="https://github.com/learningequality/kolibri/assets/148026/61c720d5-d59f-4e79-ba33-a56344ccdc62">

I see that the desired channel is in top.

<img width="898" alt="msedge_M5sjRGv9jH" src="https://github.com/learningequality/kolibri/assets/148026/249e9fec-c74f-42aa-bd74-584cfeae77d9">

Then I update the channel to a new version.

Then it looses it's place in the channel order.

<img width="899" alt="msedge_QWncd5kU0D" src="https://github.com/learningequality/kolibri/assets/148026/f9524d88-ee24-45cb-a1a9-7831915390ae">

<img width="905" alt="msedge_0SWEx9sMxF" src="https://github.com/learningequality/kolibri/assets/148026/74191f78-aa3a-4b88-b9d7-5b0855d46f7a">

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

 * Kolibri version: 0.15.12
 * Operating system: windows
 * Browser: chrome

…

**Comment by rtibbles** [comment]
Thanks for the report @lsolesen - we have an existing report for this bug here: https://github.com/learningequality/kolibri/issues/10309 so I'm closing this one as a duplicate.
