### ISSUE TITLE
"NaN B" displayed in coach when toggling lesson visibility

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#10797]
## Observed behavior
in `Coach`, there is sometimes noticeable shaky behavior when toggling lesson visibility in the `Reports` & `Plan` tabs. if you throttle your network to "Slow 3G," it becomes clear this is related to `NaN B` being temporarily displayed during some transitions in lesson visibility. 

## Screen recording
https://github.com/learningequality/kolibri/assets/43046460/d5ba879a-d571-42a4-bd41-b2360aa2ce47

## Expected behavior
it would be preferable for UI to display `0B` or `-` over `NaN B`, which looks buggy and does not convey any useful information to the user. notably, the value of "Total size of lessons visible to learners" is `0` while size in the table is displayed as `NaN B` - maybe the implementation of the former could be smoothly adapted for the latter.

it would be ideal for the table columns to have fixed widths in this specific case, as the current responsiveness of the column widths leads to a jittery UI when `NaN B` flashes into view (though this may not mesh with other usages of the table component)

## User-facing consequences
![it's weird man](https://github.com/learningequality/kolibri/assets/43046460/b7604dfe-255f-4a46-b200-73dbb0458202)

## Steps to reproduce
in a facility that contains at least 1 class, visit that class's `Report` & `Plan` tabs and toggle "Visible to learners" several times (they behavior does not occur on every on/off toggle)

**Comment by nucleogenesis** [comment]
I'll dive into this within the scope of #10729

**Comment by rtibbles** [comment]
I thought I'd caught all these in this PR: https://github.com/learningequality/kolibri/pull/10720 - seems like we need to make sure that the lesson save action should only resolve once the size fetch has also resolved.
