### ISSUE TITLE
Implement a universal template tag for rendering all children of an abstract asset hook

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#108]
From the presentation of plugins by @indirectlylit, we identified the need of a template tag that can render all registered hooks of an asset type abstract hook.

We need:
1. An identifier / slug for abstract hooks
2. Expand the existing template tags to receive slugs: `{% webpack_base_assets %}` and `{% webpack_base_async_assets %}`
3. Some documentation

**Comment by rtibbles** [comment]
I believe this is done, if not, I am misunderstanding.
