### ISSUE TITLE
Make it possible to create a new facility on existing Kolibri

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10826]
## Observed behavior

On my existing Kolibri installation I want to be able to create a new facility. However, it seems that this option is not available.

![msedge_t7ZbSSUTkH](https://github.com/learningequality/kolibri/assets/148026/ff3778a5-1d06-422d-8677-65f6c8f8fc3a)

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context
* Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Chrome

…

**Comment by rtibbles** [comment]
Hi @lsolesen - thanks for this report, we have definitely had this feedback before. There are workarounds for now, the easiest being setting up Kolibri on another device and then importing that facility from there.

I am fairly sure we had designed this flow, so I will see if we can find those designs to add to this issue. It's possible that we could do this without adding any new strings, therefore it's possible we might be able to address this is in the scope of a patch release, but I'll have to investigate further.

**Comment by jtamiace** [comment]
Here's a design that will allow someone to create a new facility. There may be new strings in the buttons and snackbar in the mockup, but hopefully there are some existing ones to replace what's there.

![newfacility](https://github.com/learningequality/kolibri/assets/6668144/0417b915-0262-46f3-9290-4e2d7376db14)

**Comment by Jaspreet-singh-1032** [comment]
Hello @rtibbles, Please assign me this issue.

**Comment by rtibbles** [comment]
Thanks @Jaspreet-singh-1032 - hopefully the design by @jtamiace above is sufficient for implementation here, but feel free to ask any follow up questions as needed!

**Comment by rtibbles** [comment]
Fixed in #11197! Thanks to @Jaspreet-singh-1032!

@lsolesen - this will be released in the 0.17 release, which we anticipate being released before the end of the year.
