### ISSUE TITLE
Khan Exercise is failing

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10827]
## Observed behavior

I am not aware where to file issues for problems with channels. If this is not the correct place, then please advice.

One of the Khan Exercises is not working.

"Represent multiplication on the number line"

![msedge_aLMRT0Se3R](https://github.com/learningequality/kolibri/assets/148026/88504b36-887b-4563-980f-1aa27ab297f4)

When you input a number in the input field, it complains that you did not input the number:

![msedge_biSvDPKNmI](https://github.com/learningequality/kolibri/assets/148026/b00aa376-b299-477e-80a8-a96b0e521907)

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

1. Go to the Exercise.
2. Fill in the input fields (does not apply to the single and multiple choice).
…

## Context

 * Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Tried Edge and Chrome
…

**Comment by rtibbles** [comment]
Hi @lsolesen - it is very likely that this is an issue with our integration of the Khan exercise rendering framework 'Perseus' into Kolibri, so this is the right place to flag this, thank you!

I have some ongoing work to update our version of Perseus, so I will make sure to address this issue while finalizing that, but it will be sometime later in the year.

**Comment by pcenov** [comment]
Hi @rtibbles - I'm not able to replicate this issue in Kolibri 0.17.

**Comment by rtibbles** [comment]
Hi @lsolesen - we think this issue has been fixed with our latest updates to question rendering in 0.17.0. I am closing this issue, but please feel free to post here if you do see this again with the latest version!
