### ISSUE TITLE
Make device available when logged in on 2nd facility

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10829]
## Observed behavior

I have created two facilities. When I am logged in on the 2nd facility, however, the Device tab is not present - and it is not possible to make a user Super Admin.

Then you need to login to the other facility to do any admin work, but I want different super admins on the facilities.

![msedge_vP9yslLD9P](https://github.com/learningequality/kolibri/assets/148026/4a6ab2c8-87ae-4d9e-b8cb-64c49518920d)

When logged into the other facility, I have the possibility to create classes etc. 

![msedge_0BhXfElWhH](https://github.com/learningequality/kolibri/assets/148026/2d6a1833-9fc2-4235-bd81-5f7564d32afc)
…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

 * Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Edge
…

**Comment by rtibbles** [comment]
Hi @lsolesen, this is possible, you would need to grant the user on the second facility with super admin permissions. See the documentation for details https://kolibri.readthedocs.io/en/latest/manage/permissions.html#super-admin-permissions

**Comment by lsolesen** [comment]
Thanks. I could give myself super admin permissions logging into the other facility. However, it is a little counterintuitive that you need to login to one facility to give yourself access in another facility :)

**Comment by radinamatic** [comment]
Valid point @lsolesen, will be adding pointers to this in our user documentation, thank you! 🙏🏽
