### ISSUE TITLE
Imported facility - Can't access the pages in the Coach plugin

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10835]
## Observed behavior
While regression testing for https://github.com/learningequality/kolibri/pull/10812 I noticed that after importing a facility I can't access any of the pages in the Coach plugin. This happens after I sign out from my main facility and then sign in to the imported facility as a super admin. Seems that this is a side effect from the changes made in https://github.com/learningequality/kolibri/pull/10768.
The following error is shown in the console: `Error: Missing required 'facilityId' argument`

## Expected behavior
It should be possible to access the Coach plugin of an imported facility as a super admin.

## Steps to reproduce the issue
1. Install the latest develop build
2. Setup a multifacility device
3. Sign in to an imported facility and attempt to access any of the pages in the Coach plugin.

## Video

https://github.com/learningequality/kolibri/assets/79847249/1bbf8a6e-dd68-478c-b7c7-de313b5d4fed

## Usage Details
Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@thanksameeelian @radinamatic

**Comment by rtibbles** [comment]
This seems to be a duplicate of #10811?

**Comment by thanksameeelian** [comment]
agree with @rtibbles - there is potentially already [an existing fix for this (if it is a duplicate) here](https://github.com/learningequality/kolibri/pull/10813), it's just waiting for the changes in #10812 to be approved by QA & merged before we apply it, in an attempt to avoid further merge conflicts for that contributor.

**Comment by pcenov** [comment]
No probs, closing this one - seemed like a different case to me as https://github.com/learningequality/kolibri/issues/10811 was reported only for a Coach user. :)

**Comment by thanksameeelian** [comment]
@pcenov i do think it's worth double-checking that this specific case is covered by the fix mentioned above once it comes up for review (hopefully today), but i believe the case you reported should be covered by the code change that PR is introducing.
