### ISSUE TITLE
Link KDS to Kolibri via webpack aliases rather than using yarn link

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#10847]
Add commands to Kolibri's package.json (e.g. `yarn run devserver-with-kds` and `yarn run devserver-hot-with-kds`) that will run Kolibri's development server but with a local `kolibri-design-system` repository (KDS) instead of _node_modules_ KDS. Using these commands removes the need to use `yarn link` completely for developing with a local version of KDS in Kolibri.

This would also close #10809 since if a new approach works well for developers, we won't need to use `yarn link` anymore.

## Motivation

There's currently a problem with using `yarn link` to link KDS to Kolibri (#10809). Also, `yarn link` is inefficient, especially when there's a need to switch between KDS version defined in Kolibri's package.json and local KDS frequently. I believe this would also help us to encourage contributors to work on KDS, since you'd need one simple command to run Kolibri with local KDS instead of several steps needed to `yarn link`. 

## Implementation

- The new commands will utilize a webpack alias for `kolibri-design-system` that will resolve to a local location of the KDS repository (this should override _node_modules_ KDS). You can see [A better alternative to npm/yarn link for front-end web development](https://teselagen.com/blog/a-better-alternative-to-npm-yarn-link-for-front-end/).
- By default, the alias could be resolved to _kolibri-design-system_ directory that's at the same level as _kolibri_ directory, but ideally it would be configurable.
- @rtibbles suggests we _"add an option to the kolibri tools build command that lets you set aliases, and then have a standard yarn command that just takes a path for KDS"_
- I don't expect any troubles but may be good to experiment with a quick draft implementation before polishing all details at first just to find out if this approach works in our webpack environment.
- One more note from @rtibbles: _"I think the main complexity will just be working out how to format an alias as a command line argument, the rest should just be passing it through to the webpack configuration."_

**Comment by Jaspreet-singh-1032** [comment]
Hello @MisRob, please assign this issue to me.

**Comment by MisRob** [comment]
Hi @Jaspreet-singh-1032, great, this would be so helpful for everyone working on KDS. Thanks once again for volunteering your time and energy.

**Comment by MisRob** [comment]
@Jaspreet-singh-1032 Let us know how it goes. Feel free to open a draft PR with work in progress if there will be anything it'd be good to chat about. This may need a bit of research and playing around. Hopefully it'll be doable. There are some good pointers by @rtibbles in the issue description.
