### ISSUE TITLE
Frontend translations only get applied the moment one starts typing

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#1085]
Branch: latest 0.3.x

![bug](https://cloud.githubusercontent.com/assets/191955/24059711/4852a44c-0b0d-11e7-9f6c-335a855c0348.gif)

Text intially starts in English, even with another language set. Typing then switches it to the said language.

**Comment by rtibbles** [comment]
Does this only happen on the login page?

**Comment by aronasorman** [comment]
Yup!
