### ISSUE TITLE
Unable to submit surveys

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10860]
## Observed behavior
When testing surveys, @radinamatic noticed that there are significant errors in the console during the interaction of the survey, but most critically, that the survey does not submit at the end. I was able to reproduce this and I think it's related to the changes of the `finish` event in https://github.com/learningequality/kolibri/pull/10747/

## Errors and logs

<img width="1434" alt="Screenshot 2023-06-16 at 9 16 38 AM" src="https://github.com/learningequality/kolibri/assets/17235236/e5636f3d-d26c-469b-bfd7-8963d0e590e2">

## Expected behavior
User should be able to submit surveys, even if they are a feature currently only used in certain scenarios.

## Steps to reproduce
Choose a survey from the QA channel. Complete it. Note the errors in the console while filling out your answers. When you get to the "submit" step, note that the survey does not submit but stays on the screen with the modal open. 

## Context
latest develop

**Comment by radinamatic** [comment]
Just noting that the survey does get submitted at some point, it's just not communicated to the front-end correctly: if page is reloaded at that point (loader still spinning behind the modal), user will see the survey report.

**Comment by rtibbles** [comment]
I assume the same is true for practice quizzes?

**Comment by radinamatic** [comment]
Yep, apparently it does...


https://github.com/learningequality/kolibri/assets/1457929/6707386f-8309-40d1-9090-454a89928590
