### ISSUE TITLE
create Github Action to automatically update AUTHORS.md

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#10885]
## goal
create a new github action to incorporate into our workflow which would add a new contributor's name to [AUTHORS.md](https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md) as part of their first pull request. 

## why?
currently, this element of the PR/contribution process is very often missed, requiring contributors' names to be added manually & separately from their contribution, which has led to some contributors not getting added to the file at all.

## potential resources
there are existing github actions available on github marketplace like [auto-add-contributors](https://github.com/marketplace/actions/auto-add-contributors) which could provide a helpful reference point for what we want to accomplish, but for our action we also need to assess the current content of `AUTHORS.md` to avoid repeat mentions of the same contributor, and ideally would also scrape a contributor's full name from their gh profile, in order to record that in addition to their username.

**Comment by GarvitSinghal47** [comment]
i would like to work on this issue , can you assigned it to me .

**Comment by thanksameeelian** [comment]
awesome - thanks for volunteering! i went ahead & assigned you 🙂

**Comment by GarvitSinghal47** [comment]
#10902

**Comment by GarvitSinghal47** [comment]
#10902
