### ISSUE TITLE
Kolibri Module routing & plugin conventions

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/kolibri#109]
Based on discussion we decided:
- Django should inject both the portion of the url it captured for routing and the remaining portion which should be routed by the js app.
- We will remove the `urls` module from plugins -- plugins should only define _one_ url, and we can entirely construct it from the existing plugin attributes for urls.

**Comment by benjaoming** [comment]
@indirectlylit hope it's okay to assign you this one since you were very active in the discussion from which the decision formed :)

**Comment by indirectlylit** [comment]
Still unresolved because it turned out to me more subtle than just lists of names and URLs. 

Migrating to trello because it needs design & planning: https://trello.com/c/qIy4GgTa/318-core-api-pluggable-routing-nav-bar-items
