### ISSUE TITLE
No user feedback during content channel download?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1091]
## Summary

Not sure if this is already being handled elsewhere? But I think it's important for early UX, especially anyone trying to test Kolibri to get an early impression.

Before downloading a content channel, users should be presented with data about the channel:

1. Some description
1. Figures, like available video count
1. Total data needed to be transferred
1. Total drive space required

During the download:

1. Total size MB
1. Currently downloaded MB
1. Transfer speed avg (past 10 minutes?)
1. ETA

We should of course handle application crashes (device reboots), and connection outages.

**Comment by indirectlylit** [comment]
Thanks for the report! Similar to #463 adding this to https://trello.com/c/zGD8iLpq/691-add-size-and-time-estimates-to-content-transfers-during-import-export
