### ISSUE TITLE
Remote browsing - Search and filters are not working

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10926]
## Observed behavior
Both search and filters are not working while remote browsing.

## Expected behavior
Fully functional search and fitlers.

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries > Browse channel > Folder 
3. Attempt to search by a keyword or apply a filter

## Video

https://github.com/learningequality/kolibri/assets/79847249/93e5d096-4b98-4748-93c5-015009b3b368

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Confirming that the search and filtering is not getting any results on both remote browsing the Kolibri Library on Studio, as well when browsing other peer libraries.


https://github.com/learningequality/kolibri/assets/1457929/da1f489a-285d-49c0-a2d3-1698d1a23bd7

**Comment by rtibbles** [comment]
Thanks @radinamatic - at least that means it's an issue on the Kolibri side, and we don't have to fix anything on Studio! I'll take it from here.

**Comment by radinamatic** [comment]
Some additional testing confirms that not only the keyword search, but also none of the filters work during remote browsing, both on Kolibri Library (Studio), or on peer libraries. Basically, none of them are active/actionable... 


https://github.com/learningequality/kolibri/assets/1457929/b8bb3575-cd0c-436f-97b1-582f2753205d


Recording is from browsing Studio, but it's absolutely the same on peer library
