### ISSUE TITLE
Remote browsing - Several UX issues

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10931]
## Observed behavior
Noticed several UX issues while comparing the current implementation to what we have in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=194-2922&mode=design).

## Expected behavior
Should be further discussed /changes made.

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries

## More information

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| RESOLVED in https://github.com/learningequality/kolibri/pull/11090 ~Library > Other libraries - Design differences~ | ![2023-06-23_15-09-30](https://github.com/learningequality/kolibri/assets/79847249/239f74bd-ed25-4ba6-a829-0f4385950630)
| (WIP in https://github.com/learningequality/kolibri/pull/11097) Library > Other libraries - Design differences | ![2023-06-23_15-21-47](https://github.com/learningequality/kolibri/assets/79847249/e9e855ca-941a-4f38-a9af-452431deab72)|
| RESOLVED in https://github.com/learningequality/kolibri/pull/11100 ~Library > View all libraries - Missing number of available channels~ |  ![2023-06-23_15-27-07](https://github.com/learningequality/kolibri/assets/79847249/cb61c1f3-31fd-44d3-9a15-0f6a06b249cb) |
| RESOLVED in https://github.com/learningequality/kolibri/pull/10974 ~Library > Explore libraries - Missing Search pane, Language filter displayed to the right and ‘All libraries’ link to go back~ | ![2023-06-23_15-32-21](https://github.com/learningequality/kolibri/assets/79847249/d49c9456-5dec-4353-90c4-33bcba60cf86) |

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@marcellamaki these are tagged P2, leaving it to you to decide whether to include in the upcoming release or in a future patch.

**Comment by GarvitSinghal47** [comment]
Hey @radinamatic and @marcellamaki if no one is working on these UX issue then i would like to take these issue , so can you assign this issue to me .

**Comment by MisRob** [comment]
Hi @GarvitSinghal47, you're welcome to work on this.

I'd recommend resolving issues one by one in separate pull requests. 

Some look pretty straightforward ard and others may be a bit more complex. Let us know how it's going and if you need some support.

**Comment by rtibbles** [comment]
Note that I have resolved the final issue with the display of the search panel in some other work to do with remote browsing search.

**Comment by MisRob** [comment]
First issue is resolved by https://github.com/learningequality/kolibri/pull/11090

**Comment by MisRob** [comment]
The other two remaining issues are in in progress/review (linked them in the description)

**Comment by MisRob** [comment]
Third issue resolved by https://github.com/learningequality/kolibri/pull/11100

**Comment by MisRob** [comment]
The only emaining issue resolved by https://github.com/learningequality/kolibri/pull/11097. Thank you, @GarvitSinghal47!
