### ISSUE TITLE
Remote browsing - Missing connection error message

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10930]
## Observed behavior
Clicking on a resource or a channel from Kolibri Library when internet connection is lost or the server is stopped results in a ‘Sorry! Something went wrong! error

## Expected behavior
Connection errors should be handled gracefully

## Steps to reproduce the issue
1. Install the latest develop build
2. Navigate to Library > Explore libraries
3. Stop the device's internet connection or stop the server of the device that you are exploring and click on a resource in the channel

## More information

![2023-07-05_17-31-46](https://github.com/learningequality/kolibri/assets/79847249/3a2c0ff6-4e4a-4e26-a8ad-0bd7e3c3e02c)

## Usage Details
Kolibri 0.16alfa17
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
The first dev task here should be to determine in slack discussion the proper error handling that we want to use in this scenario

**Comment by pcenov** [comment]
@radinamatic I confirm that this issue is still extant in [v0.16.0-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta1). Tried both with the Network throttling option in Chrome and on a real device. A similar scenario in the Device plugin is handled by immediately dimming the screen when the connection has been lost and showing the "Disconnected from server..." message.

https://github.com/learningequality/kolibri/assets/79847249/dc1ed561-efbc-41ef-bbf5-9c02230c823c
