### ISSUE TITLE
Version number visible on the login page

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1095]
## Summary

As long as we're doing lots of prereleases and involving lots of testers, we should make people very aware of what they are running, ourselves included.

This will mean that no one has to click to get the version number.

If there was an "easy pickings" or "beginner friendly" label, I would have added that :)

**Comment by indirectlylit** [comment]
good ideas, thanks!

**Comment by christianmemije** [comment]
Adressed in #1221
