### ISSUE TITLE
Product issue: A coach can replace questions

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10951]
## Overview

Once a coach has selected any number of resources they can then select to replace them with other questions from the section's question pool.

### Description and outcomes

The **question replacement side panel** presents a list of questions in the question pool (which are not already in the quiz section's questions list). The coach may now click each question to expand it and show a preview similarly to how they could in the questions list. Each question has a checkbox that will allow the coach to select it.

At the bottom the coach is shown how many replacements they've selected vs how many questions they've selected to replace.

The coach may not click the "Replace" button until they've selected as many replacements as questions they've selected to replace.

Ideally, the coach's selections on this screen should be cleared only in two circumstances. This will allow the coach to maintain their work while going back and forth between the replacement screen and the questions list underneath it.

- They click replace and successfully replace the questions
- They change which section they're focusing on

### Accessibility requirements

Please review the [W3C Aria Authoring Practices Guide's a11y guidance for the Accordion pattern](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/). This should serve as a general guideline for the a11y expectations for this component. *There are items marked as `(Optional)` in that spec and we will treat them as such here as well.*  Additionally, Heyden Pickering's "Inclusive components" has an excellent chapter on **Collapsable Sections** that can give additional insight.

### Resources

[Epic](https://github.com/learningequality/kolibri/issues/10802)

[Relevant Figmas](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2110-61552&mode=design&t=HHb6uOjOH68o9mju-0)

**Comment by rtibbles** [comment]
Note that resolving this should also resolve this deep cut #4708
