### ISSUE TITLE
Product issue: A coach can add a new section to the quiz from within the question preview page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10952]
## Overview

In order to streamline the coach's experience during quiz creation, we will also allow coaches to add a new section on the fly from the **Question preview** page by way of a side bar. This will provide everything the coach needs to select content and configure a new section.

### Description and outcomes

The **add section side panel** will present the same form as #10949 does for each section in a `SidePanel` component.

The user will be able to open and use the same user flow as defined by #10967 in order to select the resources they want for this section they are creating.

The user will be given a way to back and forth between the workflow in #10967 and the "Add section" form.

Finally, when the form is submitted, a new section is added to the quiz and this change should be made such that it will reflect immediately in the **Question preview** page.

### Resources

[Epic](https://github.com/learningequality/kolibri/issues/10802)

[Relevant Figmas](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=1800-54292&mode=design&t=DcHOASPJReWd3xRw-0)

### Accessibility requirements

Here we will be largely using existing components which ought to handle much of the a11y out of the box - that is, the form elements, buttons, side panel, etc. Aside from ensuring that keyboard navigation works as expected, there shouldn't be much additional to consider on this front in this case.

**Comment by nucleogenesis** [comment]
Design decisions void this issue.
