### ISSUE TITLE
Current develop branch not working on IE10

### ISSUE THREAD

**Issue by 66eli77** [learningequality/kolibri#1097]
<img width="1164" alt="screen shot 2017-03-20 at 11 15 13 am" src="https://cloud.githubusercontent.com/assets/5577205/24114840/caed6c22-0d5e-11e7-9d81-b0a704d84631.png">

**Comment by DXCanas** [comment]
I have a strong feeling this has to do with https://github.com/babel/babel/issues/116

It seems to be a common thing amongst ES6 compilers because IE10 lacks `__proto__`

**Comment by rtibbles** [comment]
Yes, almost certainly.

**Comment by DXCanas** [comment]
What do you think of some of the fixes cited?

**Comment by rtibbles** [comment]
Well none of them are actually fixes, just workarounds that don't quite work - so, my temptation would be to drop IE10 too.

Another thing to check would be if this is a problem in Android 4.

**Comment by rtibbles** [comment]
Can't support IE10.

**Comment by indirectlylit** [comment]
added new issue to more elegantly handle unsupported browsers: #2035
