### ISSUE TITLE
Kolibri Library - It's possible to filter by more than one activity type

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10975]
## Observed behavior
If I am exploring the Kolibri Library and I try filtering by Activity I am able to select several activities.

## Expected behavior
It should be possible to filter only by one Activity at a time.

## Steps to reproduce the issue
1. Install the build asset from the following [PR](https://github.com/learningequality/kolibri/pull/10974)
2. Navigate to Library > Other libraries > Explore
3. Attempt to apply several filters by Activity

## Video

https://github.com/learningequality/kolibri/assets/79847249/a7c56e46-5ffe-4179-90c8-c4b4c308d8a3

## Usage Details
Kolibri 0.16alfa19
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Related to https://github.com/learningequality/kolibri/issues/10926, as while testing it yesterday @rtibbles discovered that while filtering Kolibri is still trying to search its own local library, rather than the remote library (it is a regression, used to work well before).

**Comment by rtibbles** [comment]
I am confused - this is intended behaviour.

**Comment by pcenov** [comment]
Now I am confused - why would it be intentional? :) It's inconsistent with the behaviour of the Activities filter at the Library page and it also looks weird from UX point of view...

**Comment by rtibbles** [comment]
You can filter further by Learning Activities, if the already filtered set has those Learning Activities available. So, if you filter by Read, and it is also tagged as "Listen" (perhaps because it's a read-aloud book), then you will be able to select Listen as well.

I will dig in a bit further to confirm it is working as intended, but the reason you don't see this on the Library page is just because of resources you have imported that do not have multiple Learning Activities labelled on a single resource.

**Comment by pcenov** [comment]
Hmmm, so in the case you are describing if I keep filtering by adding more activities then it should return only resources matching all specified activity types e.g. 'books with audio' and that could be indeed helpful. But now it returns both books and books with audio.
Also I just imported a channel with resources with several activities assigned to them and can confirm that the filter at the Library page filters them only by the default activity type, for example for a PDF file that is Read and for a video file that is Watch.

**Comment by radinamatic** [comment]
Confirming what @pcenov mentions above: filtering the Kolibri Library is able to return results with resources that are tagged with multiple activity types, but when filtering the local library or a peer library, the additional activity types on resources do not seem to be _visible_ to the filter. In the below video I have the asset from https://github.com/learningequality/kolibri/pull/10974 installed with the latest version of the QA channel (120) where several resources have been tagged as multiple activity types. Trying to filter both the local library copy of QA channel, as the one in the peer library (DistrictKolibriHub, which also has QA channel on version 120), will always present the results with the _original_ activity type (videos for **Watch**, PDFs & ePUBs for **Read**, etc), even though other resources have been tagged with **Watch** and **Read** activity.

https://github.com/learningequality/kolibri/assets/1457929/34d4ef0b-d2a1-43c8-9c28-bf82d11eb2da
