### ISSUE TITLE
Catch and redirect 401 errors on Kolibri when browsing remotely

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10996]
If a user is automatically logged out while remote browsing (such as if they step away from the computer or do different work), there are unhandled `401` errors in the console as the endpoint is being polled. Response is `Authentication credentials were not provided.`

![image](https://github.com/learningequality/kolibri/assets/17235236/b3e50485-ebdc-429a-a21e-c665c61172e4)

Since you cannot browse as a guest, these `401` errors should be caught and the user should be redirected to login

[Slack Message](https://learningequality.slack.com/archives/CB37UM23A/p1689778374053269?thread_ts=1689778374.053269&cid=CB37UM23A)

**Comment by vkWeb** [comment]
Assigned myself @marcellamaki.

**Comment by rtibbles** [comment]
Fixed in #11119
