### ISSUE TITLE
Add custom user-agent to `NetworkClient` and external API calls

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10995]
## Observed behavior

The user agent for API calls made with python `requests` do not clearly identify the device as Kolibri

## Errors and logs

Perhaps connected with errors like the following although these are not the primary reason to customize the user-agent:
```
http.client.RemoteDisconnected: Remote end closed connection without response
```

## Expected behavior

It's recommended that we clearly identify the application making API calls, to differentiate it from potential scripting. According to MDN, it should have the format:
```
User-Agent: <product> / <product-version> <comment>
```
So for Kolibri 0.16.0:
```
User-Agent: kolibri/0.16.0 python-requests/2.28.2
```

## User-facing consequences

Web application firewalls may take more aggressive action against clients making many requests if it appears to be purely something scripted.

## Context

Kolibri 0.15+

**Comment by bjester** [comment]
@mhasbini could you comment on the issue here so I can assign you?

**Comment by mhasbini** [comment]
👋
