### ISSUE TITLE
Add and handle V3 schema for `Exam#question_sources` JSONField

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11002]
## Overview

The `kolibri.core.exams.models.Exam` class's `question_sources` property is a `JSONField` where we store the structure of a quiz and where it gets its exercises from.

The latest version is a list of objects as follows:

```
  # V2
  [
  	{
      	exercise_id: ...,
          question_id: ...,
          title: ...,
          counter_in_exercise: ...,
      },
  ]
```

We will update this data structure and its schema in the `Exam` model and then we will update the Javascript that handles converting older `question_sources`' data versions so that we can reliably retrieve the data we need in the shape we need it in.

## Acceptance criteria

- [x] Update the `kolibri.core.exams.models` `Exam` class's comment defining the schema for `question_sources` with something like the following, being sure to keep previous definitions.

```
  """
  V3:
  	V3 represents a list of questions of V2 objects each of which are now a "Exam/Quiz Section"
      and extends it with an additional description field
      
      # Exam
        [
        	# Section 1
            {
              "title": <section title>,
              "description": <section description>,
              "questions": [
                {
                    "exercise_id": <exercise_pk>,
                    "question_id": <item_id_within_exercise>,
                    "title": <title of question>
                },
                ...
              ]
            },
            
            # Section 2
            {...}
        ]
  """
```

- [x] Update `kolibri/core/assets/src/exams/utils.js` so that there is a way to reliably get any Quiz's `question_sources` in the new `V3` format. Ultimately, this will result in taking `V2` data and creating a new object out of it to populate the `question_sources` list

- [ ] The **Practice Quiz** creation and **Coach > Quiz Reports** should be able to also still get any Exam using the `V2` schema so that we don't flat out break those features. For example - whenever any part of Coach **other than quiz creation/editing** wants the `question_sources` data, they should just be getting the first section of the quiz as it would just be the `V2` schema they are already using. This may result that `utils.js` having its exports extended to differentiate between V3 and previous versions.

- [x] Tests should be updated to accommodate the new data structure. See `kolibri/core/assets/test/exams/utils.spec.js` and `kolibri.core.exams.test.test_exam_api` as a start.

**Comment by rtibbles** [comment]
Fixed in #11025
