### ISSUE TITLE
Build flexible and accessible accordion component

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11011]
## Overview

Two areas ([Example 1](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2176-81165&mode=design&t=Kuek0fECRyAw6GoE-0) [Example 2](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2176-80756&mode=design&t=Kuek0fECRyAw6GoE-0)) of the new quiz creation flow make use of a very similar yet unique accordion patterns which can easily be displayed using one well defined purpose-driven component.

To accomplish this, we will have a handful of new components that will make use of the VueJS slots feature.

A wrapping component will be provided which will maintain the knowledge of what items have been opened and closed. This component will expose some of its functionality by way of [scoped slots](https://v2.vuejs.org/v2/guide/components-slots.html#Scoped-Slots) so that the wrapping component can react to interactions with its children within its own scope.

#### Architecture Notes

By using Scoped Slots we will be able to implement a structure which allows the consumer of these components we make to both manage what is shown local to their own scope (in our case, that would be the "root" quiz creation component). For example:

```vue
  <!-- AccordionContainer.vue -->
  <!-- In this file's template where we define the slot, any attribute we pass to it will be exposed 
         in the parent component that is using `AccordionContainer` in its own template -->
  <slot name="content" :setActiveItem="setActiveItem" :toggleItemState="toggleItemState"></slot>
  
  <!-- So any method or computed property or other function imported from elsewhere can be
          passed as values into the attributes of the slot and, along with their binding to `this` (aka the instance of
          AccordionContainer).  -->
  import { isItemExpanded } from "kolibri.some.place";

  /* in component definition */
  computed: { isItemExpanded },
  methods: {
      setActiveItem(id) { 
          this.activeItemId = id 
      },
     /* ... and so on ... */
  }
  
  <!-- Wherever AccordionContainer is used -->
  <AccordionContainer>
    <!-- These slot props are defined in `AccordionContainer` and passed to the 'content' slot -->
    <template #content v-slot="{ setActiveItem, toggleItemState, isItemExpanded }">
  	<div v-for="item in items" :key="item.id">
        <!-- Now we can call the functions provided by the AccordionContainer
  		   so that we can tell it when an item is toggled -->
        <AccordionItem 
          :expanded="isItemExpanded(item.id)"
          @click="setActiveItem(item.id); toggleItemState(item.id)"
        >
          <template #heading>
            <!-- The clickable and always shown section of the item -->
            <!-- Where drag handlers, checkboxes and/or a title would go -->
    	  </template>
    
    	  <template #panel>
  	     <!-- What is shown when the item is expanded -->
    	  </template>
    	</AccordionItem>      
      </div>
    </template>
  
  </AccordionContainer>
```

The above is only a suggestion - but note how we are able to pass functions from within `AccordionContainer` so that the dev using the component can call something within the scope of the `AccordionContainer`. This is in the Overview and not the Acceptance Criteria, so focus primarily on meeting the defined needs below.

#### General

- [ ] Implement Figma designs to the visual specification

#### AccordionContainer

- [ ] This will maintain the state of which elements are currently expanded and which are not expanded

- [ ] This will expose a means by which it will expand or collapse all of the items

- [ ] Use of this component should not rely on managing any state re: what items are open or closed - that should all be handled within this component

- [ ] Provides a slot where a heading can be put [Example 1](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2176-81165&mode=design&t=Kuek0fECRyAw6GoE-0) [Example 2](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2176-80756&mode=design&t=Kuek0fECRyAw6GoE-0)

- [ ] Does not handle or consider "draggability" in its own definition -- however, whatever `AccordionItem` components are passed in should be able to be wrapped also by a `DragContainer`.

#### AccordionItem

- [ ] Provide two slots - one for the always-visible row which will be clickable to toggle whether or not the content in the second slot is visible.

- [ ] Monopolizes space on the far right of the content where the toggling chevron icons will live.

- [ ] Emits a `@click` event whenever the toggling chevron icon or the clickable slot content is clicked

#### Accessibility

Review the [w3 WAI-ARIA guidance on the Accordion pattern](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/) with particular consideration for keyboard navigation expectations as well as some of the simpler and most helpful ARIA attributes such as `aria-expanded` which can be helpful for users of assistive technologies. Some items are listed as (Optional) - I believe that ensuring that the `Home` and `End` keys work as indicated there would help us ensure a smooth UX.

Related to the last note: the UX of navigating a list of checkboxes to select multiple items only to have to return to the beginning in order to access the actions should be considered. Use of the `Home` and `End` keys may or may not be widespread, but perhaps we can manage focus to ensure that a user has a reliable way to get to the actions section of the interface.

**Comment by MisRob** [comment]
@nucleogenesis Have you considered making this a KDS issue rather than Kolibri one?

**Comment by nucleogenesis** [comment]
I thought about that but building a new component into KDS bears a much larger burden of documentation, complicates the development process, and can just be done after the fact if we find that we want to make the component more universally available. I figured all of that would be an unnecessary delay to the tight timeline we're aiming for on the feature.

I also think that this might be better suited for `kolibri-common` as `CoreAccordion` or something like that if we did find that Kolibri could make use of the component across the application but if we find that Studio & KDP could make good use of the pattern then we can plan to migration to KDS alongside the necessary pattern guidance documentation for the KDS website and such

**Comment by MisRob** [comment]
@nucleogenesis

Alright, thank you, I can understand.

In regards to possible future `CoreAcordion`, in my view, documentation is not necessarily a burden even though it takes time, especially for typical components like this that follow common UX and a11y patterns for which having guidelines is useful, even when using it in one product. And it can help with building it in a way that's pretty clear and flexible. So I don't think that we have to necessarily use a component in all products for it to be categorized as a KDS component. For that reason, I'd suggest we consider `KAccordion` too when the time comes.

That's a general note for consideration, I'm not familiar with the details of this component and see there are more things to balance and that's okay. Starting a component in Kolibri and moving it at some point higher in the structure or alternatively to KDS is something that we do quite commonly and seems to work well.

**Comment by nucleogenesis** [comment]
Completed in #11087
