### ISSUE TITLE
"Select All" checkbox in MyDownloadsPage can be checked with no selectable items

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11026]
## Observed behavior
Reported by @nucleogenesis during the beta0 bug bash

> when all items in the table are disabled, the “Select all” checkbox is not disabled, so I can still manage to select everything using that checkbox — noting it, but if the rows weren’t disabled, then this is behaving as intended beside the fact that clicking “Remove Selected” does nothing 

https://www.notion.so/learningequality/Cannot-remove-item-I-selected-to-download-on-My-Downloads-page-7e87f388f8a74df4a6263f0bfd6f884a?pvs=4

## Errors and logs
<img width="1426" alt="Screenshot 2023-07-27 at 4 28 17 PM" src="https://github.com/learningequality/kolibri/assets/17235236/52c55397-6fa7-48f7-acb1-bd4f2b3a5f0d">

## Expected behavior
"Select all" should only be enabled if one or more items are selectable

## User-facing consequences
Confusion, mis-selecting items

## Steps to reproduce
Initiate a download and navigate to the "My Downloads" page

## Context
beta0

**Comment by nucleogenesis** [comment]
Fair chance that the issue causing this is the same as #11029
