### ISSUE TITLE
User initiated content download needs remote browsing context (for Studio)

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11022]
## Observed behavior

When browsing Studio content remotely through Kolibri, if I initiate a download of one of the resources, it fails to 'find a peer' for importing the content.

## Errors and logs
```
INFO     2023-07-27 10:22:17,150 No acceptable peer network device for importing content metadata
WARNING  2023-07-27 10:22:17,160 Could not find available peer for content import
```

## Expected behavior

When a user initiates a download of a resource through remote browsing, it should store the device on which the user was browsing, so that the automatic import processing can choose the best device. This will be primarily useful for the use case of browsing Studio, but is valuable information to have in any case for optimizing the import processing.

## User-facing consequences

Content fails to download and remains in 'Waiting to download' state

## Steps to reproduce

1) Provision Kolibri
2) Browse local libraries, navigating to Studio
3) Find a resource and click the download button to initiate the download
4) Observe the download never completes

## Context

Kolibri 0.16.0b0
https://www.notion.so/learningequality/Initiating-a-content-download-from-Studio-runs-into-No-acceptable-peer-network-device-for-importing-306e6139324145e18d78057e2683ad35?pvs=4
https://www.notion.so/learningequality/Initiating-a-content-download-from-a-peer-that-has-the-content-failed-8ddc95fe6742464da9e4ff26b3049694?pvs=4

**Comment by marcellamaki** [comment]
After doing some manual QA, this appears to be a problem with local network connections too. 

Scenario: 
1. latest release branch, clean kolibri home folder 
2. create a new admin account and sign in
3. browse "local" content (Mr. Tibbles' Classroom Server) 
4. request content download 

No errors/400s, but 
```
No acceptable peer network device for importing content metadata
```
appears in the terminal, and the status never moves beyond pending, just as described above

**Comment by bjester** [comment]
Thanks @marcellamaki, my plan is to handle both studio and local connections, with local also benefiting from the same contextual information as is needed for Studio.
