### ISSUE TITLE
Ensure loading state on "Explore Libraries" immersive pages is correctly implemented

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11028]
## Observed behavior
Reported by @nucleogenesis in the beta0 bug bash

> Wonky loading state for the Explore libraries immersive content navigation page - it just looks frozen with no page loader or spinners where content is going to appear

https://www.notion.so/learningequality/Wonky-loading-state-for-the-Explore-libraries-immersive-content-navigation-page-it-just-looks-froz-41da053c6e8547ac84bcbfe067fb436b?pvs=4

## Expected behavior
Loading states should be fully handled to properly manage title/base page loading, data loading, etc. with KDS loaders used according to the pattern that has been updated in recent loading state work post-0.15

## User-facing consequences
Looks frozen/glitchy

## Context
beta0

**Comment by thanksameeelian** [comment]
may have same root cause as #11033 - potentially could combine if so?

**Comment by bjester** [comment]
Recorded this when remotely browsing Studio. There was significant lag, without a loading state

https://github.com/learningequality/kolibri/assets/819838/ed33bd4d-ec7c-4873-a59c-94b05c4e020a
