### ISSUE TITLE
Responsive mixins issue.

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1103]
## Summary

* Rapid change in content items in the all-content section of Learn causes flashing.
* https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/vue/learn-page/allcontent.vue#L45
* A change in `this.elSize.width` causes a change in `contentToShow` size.

## System information

 - Version: Current Develop
 - Operating system: Ubuntu
 - Browser: Chrome

## How to reproduce

1. Go to http://127.0.0.1:8000/learn/#/recommended/
2. Close drawer.
3. Resize the window to have a width between 867 - 882 px.

## Screenshots

![seizure](https://cloud.githubusercontent.com/assets/7193975/24160039/16de8ac0-0e1e-11e7-8c80-2bf90ed4f2a7.gif)

## Real-life consequences 
* This rapid flashing could be dangerous.

**Comment by indirectlylit** [comment]
It looks like part of the issue might be that the scrollbar is hiding/showing.

The simple solution here might be to set `overflow-y` to `scroll` instead of `auto`

**Comment by christianmemije** [comment]
@indirectlylit That's it. Will submit a PR shortly.
