### ISSUE TITLE
Requeuing a LOD sync job fails updating keys ‘repeat’ and ‘interval’

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11046]
## Observed behavior
Observed by @bjester during the 0.16.0beta0 bug bash 
> Requeuing a LOD sync job fails updating keys ‘repeat’ and ‘interval’

## Errors and logs

```
ERROR 2023-07-27 10:49:46,365 Tried to update job with id 6d2be9fa9c5a0874c5053b11abfd8233 with non-updateable key repeat
ERROR 2023-07-27 10:49:46,370 Tried to update job with id 6d2be9fa9c5a0874c5053b11abfd8233 with non-updateable key interval
```

## Expected behavior
Sync jobs should requeue successfully

## User-facing consequences
Syncs do not update automatically currently, and the user must restart their Kolibri

## Context
0.16.0-beta0

**Comment by bjester** [comment]
Should be resolved by https://github.com/learningequality/kolibri/pull/11023
