### ISSUE TITLE
A mechanism to avoid starting pollUserSyncStatusTask is needed

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#11069]
## Observed behavior

In kolibri 0.16, automatic polling to sync user status is always started whenever a registered user is login.
This is causing unneeded network traffic and server load in two cases:

- when there's no need to sync an user
- when kolibri is used with plugins that don't require user syncing (KDP as an example)

## Expected behavior
Have a chance to avoid this continuous polling caused by this code https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/views/SideNav.vue#L294

## User-facing consequences
Continuous network traffic and server load when not needed.

## Context
kolibri 0.16 beta 0
KDP plugin

**Comment by rtibbles** [comment]
We should only do this for learner only imported users, I believe.
