### ISSUE TITLE
Mac app - Cannot save the changes made at Device > Settings

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11076]
## Observed behavior
Nothing happens when I click the 'Save changes' button at Device > Settings

## Expected behavior
All changes made should be saved.

## Steps to reproduce the issue
1. Install the [v0.16.0-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta1) 
2. Go to Device > Settings
3. Click the 'Save changes' button

## Video

https://github.com/learningequality/kolibri/assets/79847249/4c695726-8a5a-4250-b9ca-25583e5762ac

## Logs

[logs.zip](https://github.com/learningequality/kolibri/files/12309862/logs.zip)

## Usage Details
Kolibri 0.16.0b1
MacOS Catalina version 10.15.7

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
@pcenov can you attach the log files for this?

**Comment by pcenov** [comment]
@rtibbles - yes, I've attached them now.
