### ISSUE TITLE
Long content titles cause issues with learning activity bar buttons

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11086]
## Observed behavior

When a resource title is very long, it causes the top bar activity buttons to wrap and stack awkwardly.

![Screenshot from 2023-08-10 08-09-19](https://github.com/learningequality/kolibri/assets/819838/8f1863eb-b732-4e5f-8c9e-78bea3514f7b)

## Expected behavior

The buttons container does not try to shrink, but remains a consistent size and forces the title to be further truncated in order for everything to fit. It should possibly turn into the meatball menu earlier with a long title.
## User-facing consequences

Buttons may not be easily actionable and could cause confusion

## Steps to reproduce

1) Download a resource with a long title
2) View the resource in Kolibri
3) Shrink the viewport until the condition occurs

## Context

Kolibri 0.16

**Comment by GarvitSinghal47** [comment]
@bjester i would like to resolve this issue , can you assign it to me.

**Comment by bjester** [comment]
Hi @GarvitSinghal47, thank you for your interest. I've assigned you this issue, but this one might be a little tricky. Please be sure to checkout the `release-v0.16.x` branch to start off from, and let us know if you have questions so we can find the appropriate solutions.
