### ISSUE TITLE
Lack of spacing between folder thumbnail and description

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11080]
## Observed behavior

The folder description starts colliding with the thumbnail at some screen sizes

![Screenshot from 2023-08-09 10-41-02](https://github.com/learningequality/kolibri/assets/819838/a6ae879b-76a0-457f-ba30-5b8249815609)

## Expected behavior

To maintain some spacing between the thumbnail and description

## User-facing consequences

Could affect readability

## Steps to reproduce

1) Remotely browse a channel
2) Open a topic which has a thumbnail and description
3) Decrease the viewport width until the above condition occurs

## Context

Kolibri 0.16.0

**Comment by GarvitSinghal47** [comment]
@bjester i would like to work on this issue , can yo assign it to me.

**Comment by bjester** [comment]
Hi @GarvitSinghal47, thank you for your interest. I've assigned you this issue. Please be sure to checkout the `release-v0.16.x` branch to start off from.
