### ISSUE TITLE
User bulk import does not prevent case insensitive username matches

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11081]
## Observed behavior
Case insensitive username matching during user creation is enforced in the FacilityUserManager class create_user function: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/models.py#L616

However, the bulk import code only checks if there is a username clash if a UUID has been specified for the user, and the user UUID already exists - otherwise, it is not checked. https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/management/commands/bulkimportusers.py#L559

Also, when the duplicate username check is made, it is not done using a case insensitive check: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/management/commands/bulkimportusers.py#L567

Lastly, it might be useful to validate that the CSV itself does not contain case insensitive username duplicates.

**Comment by nick2432** [comment]
can i work on this?

**Comment by nick2432** [comment]
can i work on this?

**Comment by bjester** [comment]
@nick2432 Yes, you may take this on. I will assign you.

**Comment by nick2432** [comment]
Case insensitive username matching during user creation is enforced in the FacilityUserManager class create_user function: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/models.py#L616

Should I implement sensitive username matching?

**Comment by nick2432** [comment]
hey @rtibbles review my PR

**Comment by rtibbles** [comment]
Fixed in #11779
