### ISSUE TITLE
App Navigation Bar updates

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11115]
There are some UI tweaks that would improve the user experience and overall layout, ensuring the new nav bar is fully to spec

| Item | Reference image |
|---|---|
| Nav bar spacing | ![image](https://github.com/learningequality/kolibri/assets/17235236/977c0196-e537-4386-9a79-0cde69217762) |

```[tasklist]
### Tasks
```

**Comment by nikkuAg** [comment]
Is this issue open?

**Comment by MisRob** [comment]
Hello @nikkuAg, yes it is, thank you for your interest. At first, if you haven't done so already, please check out [our contributing guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md).

Meanwhile, @marcellamaki, what are the problems here? And by the reference image you mean that that's the design we should follow?

**Comment by marcellamaki** [comment]
Hi @nikkuAg - thanks for your interest in working on this issue! It needs a bit more detail and a few other to-dos added to it. If you are looking to get started on something right away, another issue might be more suitable. Otherwise, I will finish writing up this issue this week, and let you know when it is ready to begin.

**Comment by nikkuAg** [comment]
Okay, I will look for another issue for the time being.
