### ISSUE TITLE
Can't set task priority via the API

### ISSUE THREAD

**Issue by dbnicholson** [learningequality/kolibri#11114]
## Observed behavior

If you enqueue a task from the backend, you can specify its priority. However, if you enqueue a task via the tasks API you can't. It would be nice to be able to do this so that the frontend can prioritize the tasks it's scheduling.

## Errors and logs

There are no errors. Tasks scheduled via the API use the priority declared in the `register_task` decorator.

## Expected behavior

The priority of each task can be specified in the list sent to the tasks API.

## User-facing consequences

The way most users schedule tasks is via the API as called by the frontend. User scheduled tasks are likely of higher importance than other non-user scheduled tasks, so it would be nice for the frontend to specify a higher priority. Alternatively, the user may know that the task they're scheduling isn't that important to them and can be run at some later time. The frontend would specify a lower priority in that case.

## Steps to reproduce

Start Kolibri with 0 regular priority workers and 1 high priority worker. Go to the device content management page and start several tasks of different types. Then go the device task panel and note that the order that they start is not the same as the order they were scheduled.

## Context

0.16.0-beta1, Linux

**Comment by rtibbles** [comment]
Happy to receive a PR for this.

**Comment by im-NL** [comment]
Hello! 
Tasks can either have a regular priority of 10 or a high priority of 5.
Here, would we just have to make it so that all tasks enqueued by the user have a priority of 5 (high)?

**Comment by rtibbles** [comment]
No, that's not quite what is desirable here, rather that tasks initated via the API should default to the priority set on the task itself, but that the payload sent to the API endpoint _can_ specify the priority if so desired. 

This would be best achieved by adding an optional `priority` field to the EnqueueArgs serializer: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/tasks/validation.py#L6

and then ensuring that the priority field is passed in if set during job queueing: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/tasks/api.py#L144

This will need to be done a little bit carefully to ensure that the default priority of tasks does not get overridden when no priority is passed in the API payload.

**Comment by im-NL** [comment]
Just to confirm, the priority can only be either 5 or 10? And the default priority of the task will be used but an option must be added to have a `priority` argument in the payload of the request to the tasks api.

thank you in advance

**Comment by rtibbles** [comment]
The possible priorities are enumerated here, the definition of the serializer field should reference this, so that if new priorities are added it will get updated in step.

https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/tasks/job.py#L92

Yes, the priority field would be added to the enqueue args, but it would be optional, so if it isn't specified the priority is the default for the task.
