### ISSUE TITLE
Maintain PDF viewer zoom setting within browser

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11110]
## Observed behavior

1) Open a PDF in Kolibri
2) Observe the default zoom
2) Zoom out
3) Close or navigate away from the PDF
3) Reopen the PDF
4) Observe the zoom is back to the default, not the last setting

## Desired behavior

It could be really helpful to maintain the zoom setting across multiple PDF views of any PDF resource so the user doesn't have to repeatedly adjust it when opening new PDFs. The PDF documents in actually use probably have a fairly consistent page size and orientation, so maintaining the zoom setting, in a user's browser, would make sense and keep the rendering the most ideal for their viewport size.

## User-facing consequences

Possibly more helpful, a fit-to-width feature that also persists across views: https://github.com/learningequality/kolibri/issues/1971

## Context

Kolibri 0.15

**Comment by nikkuAg** [comment]
Is this issue still open?

**Comment by bjester** [comment]
@nikkuAg Yep it's still open and you may tackle this if you'd like. The desired approach is to use the browser's local storage for persisting the setting. I can assign you if you're interested in working on it?

**Comment by nikkuAg** [comment]
Yes I would like to solve this

**Comment by nikkuAg** [comment]
How to open a PDF in Kolibri?

**Comment by nikkuAg** [comment]
@bjester I have opened a PR. Please review it

**Comment by rtibbles** [comment]
Fixed in #11110 - thank you @nikkuAg!
