### ISSUE TITLE
Don't let people import a facility from a learn only device

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11121]
LODs are currently listed as facilities that people can import from when doing the import flow. They should not be!

**Comment by nikkuAg** [comment]
Is this issue still pending, I would like to work on it?

**Comment by marcellamaki** [comment]
Hi @nikkuAg - thanks for your interest in contributing to Kolibri! One of the members of our team is actually getting started on this issue, I apologize that I had not updated it yet to assign him. It is now accurately reflected.

You can take a look at some of the other [issues in Kolibri tagged with "good first issue"](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) for other options of where to get started with open source contributions.

We also have [Github Discussions for Kolibri](https://github.com/learningequality/kolibri/discussions), where you can learn more about contributing and ask any questions. Let me know if you have any further questions!
