### ISSUE TITLE
Add guidelines for running another Kolibri instance alongside the development server to Kolibri Developer Documentation

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11142]
## Summary

Add a new page into [How To Guides](https://kolibri-dev.readthedocs.io/en/develop/howtos/index.html) of the Kolibri Developer Documentation. The page would contain guidance on running another Kolibri instance as pex alongside the development server.

## Value Add

As more of Kolibri features are built about remote content browsing, in our development workflows we often need to try things out with another Kolibri instance running alongside the development server. Using pex is one of the ways to do so. This workflow is simple and can be easily used independently of ZeroTier (and even internet network access). I believe having a few steps documented that we could just reference would be handy for new team members as well as contributors.

## Guidance
- [Documentation files location](https://github.com/learningequality/kolibri/tree/develop/docs)
- [Documentation about updating documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#updating-documentation) 🙃
- I recently summed all the steps up for a contributor in https://github.com/learningequality/kolibri/pull/11100#issuecomment-1687998251 so it could be used after some polish and organization

**Comment by GarvitSinghal47** [comment]
@MisRob I would like to work on this , can you assign it to me.

**Comment by MisRob** [comment]
@GarvitSinghal47 Yes sure, you know how to do this setup already, so feels like a great fit

**Comment by MisRob** [comment]
@GarvitSinghal47 Just a note that we currently have some troubles with the documentation website build (styles are off). You can work on this issue for sure, just wanted to mention it so you know it won't be nothing related to your new changes. We're investigating.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11163
