### ISSUE TITLE
Device > Settings - Incorrect default value for the storage limit slider

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11176]
## Observed behavior
Currently when I select the option "Set storage limit for auto-download and learner-initiated downloads" then the default value is displayed as "0". 

## Expected behavior
Unless otherwise specified somewhere the expected behavior of the Slider state should be as described in [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?type=design&node-id=969-16669&mode=design).

## Steps to reproduce the issue
1. Install the latest [Beta 4 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta4).
2. Go to Device > Settings and enable the option "Set storage limit for auto-download and learner-initiated downloads"

## More information

![2023-08-29_16-30-14](https://github.com/learningequality/kolibri/assets/79847249/7b352f9e-e0c4-4bb7-8995-d8fde6f477e3)

## Usage Details
Kolibri 0.16beta4
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
The expected behavior is that the slider (and corresponding value) should default to 80% of the remaining storage on the device. 
![Screenshot 2023-08-29 at 10 10 04 AM](https://github.com/learningequality/kolibri/assets/17235236/34390b4f-fc52-43fe-a1ff-edbf2b858617)

**Comment by nikkuAg** [comment]
Is this issue still open?

**Comment by marcellamaki** [comment]
Hi @nikkuAg - yes it is! Let me know if you would like to work on it and I will assign you.

**Comment by nikkuAg** [comment]
Hi @marcellamaki - please assign me this issue

**Comment by nikkuAg** [comment]
@MisRob @marcellamaki I have added a PR, please review it.

**Comment by MisRob** [comment]
Thanks @nikkuAg, we will have a look

**Comment by rtibbles** [comment]
Fixed in #11191
