### ISSUE TITLE
'Select device' modal - Disabled radio-buttons for the available devices

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11175]
## Observed behavior
The available devices are displayed as disabled while the Continue button is active. So if there is only one available device the user can proceed with the import but if there are multiple devices the user is not able to select the desired one. This issue is observed both in the setup wizard and at Device > Facilities.

## Expected behavior
All valid available devices should be selectable and displayed correctly.

## Steps to reproduce the issue
1. Install the latest [Beta 4 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta4).
2. Attempt to import a device.

## More information

![2023-08-29_16-13-02](https://github.com/learningequality/kolibri/assets/79847249/52b00562-e703-4582-ac98-41955fdaf908)

Manually added device:

![2023-08-29_16-15-03](https://github.com/learningequality/kolibri/assets/79847249/e92ad988-01dc-42b0-a49f-2466db8e1d01)

## Usage Details
Kolibri 0.16beta4
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by bjester** [comment]
At the very least, we should disable the `Continue` button when there are no selectable devices

**Comment by jredrejo** [comment]
@pcenov I'm trying to reproduce this without success, this is what I have:
1. kolibri 0.16b2 in another computer in my network
2. one kolibri 0.16b4 in tcp port 8000 in my laptop
3. a second kolibri 0.16.b4 started in my laptop in a tcp port 9000 and try to import a facility:

![image](https://github.com/learningequality/kolibri/assets/1008178/77fc8dce-b243-46a3-8f7c-a6f36571945c)

Everything is enabled, can you lend me a hand to reproduce the problem?

**Comment by pcenov** [comment]
Hi @jredrejo, this issue was happening consistently on my end so I thought that it was not difficult to replicate however currently I am also not able to replicate it in normal network conditions...
My guess is that the speed of my network connection was really low for prolonged periods of time but not constantly.
When I try to replicate this by throttling the network connection I do see a behavior which is very similar to the one described in the issue (if I wait long enough I do see the devices displayed correctly while previously this was not the case):

https://github.com/learningequality/kolibri/assets/79847249/3c34feed-e1e4-42a0-ba62-8fc37723346a

So in such cases the Continue button should not actually be active.

**Comment by jredrejo** [comment]
> Hi @jredrejo, this issue was happening consistently on my end so I thought that it was not difficult to replicate however currently I am also not able to replicate it in normal network conditions... My guess is that the speed of my network connection was really low for prolonged periods of time but not constantly. When I try to replicate this by throttling the network connection I do see a behavior which is very similar to the one described in the issue (if I wait long enough I do see the devices displayed correctly while previously this was not the case):

Yes, that's normal: if the network is slow, fetching the information from the facilities to know if they are importable or not takes some time.


> 
>  2023-09-05_10-18-22.mp4 
> So in such cases the Continue button should not actually be active.

That should be fixed in #11196
