### ISSUE TITLE
Device > Channels - Navigation issue while importing from an attached drive/local network

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11187]
## Observed behavior
If I click the Back arrow while importing a channel from an attached drive or device on the local network I am brought back to the 'Import from Kolibri Studio' modal.

## Expected behavior
The user should be brought back to Device > Channels instead

## Steps to reproduce the issue
1. Install the latest [Beta 4 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta4).
2. Go to Device > Channels and click the Import button
3. At 'Select a source' select the 'Attached drive or memory card' option
4. Select a drive and click Continue
5. Click the Select resources button next to an available channel
6. While at 'Importing from drive 'Removable Disk' click the back arrow and observe that the user is at 'Import from Kolibri Studio'

## More information

https://github.com/learningequality/kolibri/assets/79847249/c4a5ba32-94b4-421f-95ea-3392a6c63363

## Usage Details
Kolibri 0.16beta4
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by ShivangRawat30** [comment]
I would like to work on this issue

**Comment by rtibbles** [comment]
Hi @ShivangRawat30 - great, I'll assign you.

This seems like an issue specifically with the back arrow linking to the wrong place, so this should be fairly easy to pin down in the frontend of the device plugin. Feel free to ask any questions here if you're unsure of where it is happening!

**Comment by ShivangRawat30** [comment]
@rtibbles can you please help me with the docker development of the project ?

**Comment by rtibbles** [comment]
I see you're already in discussion here about this: https://github.com/learningequality/kolibri/discussions/11213 - unfortunately, I am not sure I have much to add, as I have never used the Docker development flow, and have relied on Python virtual environments usually.

**Comment by ShivangRawat30** [comment]
hey @rtibbles can you please provide the url of the 'Import from Kolibri Studio' page, it would be really helpful.

**Comment by radinamatic** [comment]
@ShivangRawat30 You can read the relevant topics from the Kolibri user documentation:
https://kolibri.readthedocs.io/en/latest/manage/resources.html#import-channels-and-resources-into-kolibri

**Comment by rtibbles** [comment]
Fixed in #11272
