### ISSUE TITLE
Learn-only device - The 'Full name' value entered in the setup wizard is missing

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11188]
## Observed behavior
If I create a new learner user through the 'LOD>Create a new user account for an existing facility' user flow then the 'Full name' value is missing from both the learner's profile page and the user details in Facility > Users

![2023-09-01_15-24-40](https://github.com/learningequality/kolibri/assets/79847249/23ba6915-2ab3-45a4-a62b-4665115a8c9f)

## Expected behavior
The 'Full name' value should be stored and displayed correctly as it is a required field.

## Steps to reproduce the issue
1. Install the latest [Beta 4 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta4).
2. On one VM create a Full facility
3. On another VM go through the 'LOD>Create a new user account for an existing facility' user flow

## More information

https://github.com/learningequality/kolibri/assets/79847249/0a5e978b-ee99-481b-8ce3-d5c4d166eef2

## Usage Details
Kolibri 0.16beta4
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by GarvitSinghal47** [comment]
hey @radinamatic i would like to give a try to resolve the above mentioned issue , can you assign it to me .

**Comment by MisRob** [comment]
Hi @GarvitSinghal47, we think it'd be best to leave this issue for one of the core team members. I recently assigned you another issue which is a pretty big one, so it'd suggest we focus on that for now.
