### ISSUE TITLE
Learn-only device syncing: concurrency issues joining a network with multiple servers of the same facility

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11209]
## Observed behavior

When a learn-only device joins a network, it receives notifications of what servers are on the network and requests to sync with each server via their learn-only device sync queue. If there are multiple servers with the same facility on the network, it's possible that the learn-only device gets queued to sync with each server at the same time. Our facility data syncing mechanism isn't built to handle concurrency, which could cause it to fail through `Database is locked` errors or other errors related to sync hooks or automatic content import.

## Expected behavior

A learn-only device requests to sync with each server one by one, notifying the server of their estimated time to sync with other servers, such that the devices can coordinate to avoid concurrent syncs.

## User-facing consequences

Constant failure of learn-only device syncs because of consistent timing on re-attempting syncs.

## Context

Kolibri 0.15+

**Comment by marcellamaki** [comment]
Resolved with https://github.com/learningequality/kolibri/pull/11390
