### ISSUE TITLE
Cosmetic UI cleanup of resource duration in Content Renderer side panel

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11206]
## Observed behavior
Some of the elements on the "Also in this lesson"/"Also in this folder" side panel of the Content Renderer are misaligned: 

![image (22)](https://github.com/learningequality/kolibri/assets/17235236/b53df362-292a-46db-8f7c-21b39187c521)

## Expected behavior
Per the spec, items should be aligned as follows, with the duration under the title of the content: 

<img width="337" alt="Screenshot 2023-09-07 at 10 40 08 AM" src="https://github.com/learningequality/kolibri/assets/17235236/fdbe0345-ef47-477b-9af2-a9600cbb0939">

## Steps to reproduce
When viewing a piece of content, use the menu bar to open the "Also in this [lesson/folder]" side panel. Observe that some of the items are misaligned.

## Context
0.16.0-beta5

**Comment by ShivangRawat30** [comment]
I would like to work on this issue

**Comment by marcellamaki** [comment]
Thanks @ShivangRawat30 - I'll assign you :)

**Comment by ShivangRawat30** [comment]
@marcellamaki Is there a Slack channel available? I'm encountering difficulties while trying to set up the project, and I'm looking for assistance.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, we have a section dedicated to troubleshooting development server in GitHub Discussions https://github.com/learningequality/kolibri/discussions/categories/q-a, please send us as much information about your device and setup steps you can. Especially logs from the beginning of the setup to the point you encounter problems would help.

**Comment by ShivangRawat30** [comment]
@MisRob thanks I've created a new discussion for the error /discussions/11213

**Comment by rtibbles** [comment]
Fixed in #11262
