### ISSUE TITLE
Depreciation warning for Koibri build due to 'set-output' command.

### ISSUE THREAD

**Issue by GarvitSinghal47** [learningequality/kolibri#11200]
## Observed behavior
Depreciation warning for Kolibri build due to 'set-output' command on assets building on exe and deb build which need to be updated to the latest command .
…
![Syncing-fixes-for-automatic-content-syncing-and-regressions-·-learningequality-kolibri-ebb1c62](https://github.com/learningequality/kolibri/assets/82756460/7a6d8f40-d347-405b-9452-bc19dcf4a1f4)

…

## Expected behavior
Just keeping that in mind as it is Depreciated it needs to be remove and would need to be change to latest command due to any issue that may can arise in future due to this depriciation.
…

**Comment by rtibbles** [comment]
These warnings are coming from the kolibri-installer-windows and the kolibri-installer-debian repos, the update that needs to be made is detailed in this blog post here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by rtibbles** [comment]
This has been fixed in https://github.com/learningequality/kolibri-installer-debian/commit/1899239ff68f365223b0063186ee65a47fc86d93 and https://github.com/learningequality/kolibri-installer-windows/commit/633db21911f984aaeb3d001c09ad190e5cbe4010
