### ISSUE TITLE
Library page - The filter defaults to being open

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11212]
## Observed behavior
Using Chrome browser if I quickly resize the fully expanded browser window to about one third of the page width or less the filter defaults to being open and in some cases doesn't close on clicking the x icon.

## Expected behavior
The filter should not be displayed expanded.

## Steps to reproduce the issue
1. Install the latest Beta 5 build.
2. Import at least a single channel.
3. Go to the Library page
4. Quickly resize the fully expanded browser window to about one third of the page width or less

## More information

https://github.com/learningequality/kolibri/assets/79847249/0b63d243-e140-4830-b9b9-0a915bddfd61

## Usage Details
Kolibri 0.16beta5
Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by marcellamaki** [comment]
Hi @ShivangRawat30 - thank you for your interest, but this issue has already been assigned. Our QA team does regularly open issues where we seek open source contributions, so you can be sure to check back in the coming days for more opportunities and issues tagged as help wanted.
