### ISSUE TITLE
Automatically synced content should have `admin_imported=False`

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11225]
## Observed behavior

Blaine forgot to follow up on this-- we need to ensure that metadata for automatically synced content has the `admin_imported=False` if the metadata doesn't already exist or the files are not available at time of syncing. The flag, when `True`, prevents resources from being garbage collected and removed the device's disk.

## Expected behavior

1) When metadata is imported for content that will be automatically downloaded, if the metadata didn't already exist, the `admin_imported` flag should be set to `False`
2) If the admin later decides to import the same content, meaning the metadata already exists, the `admin_imported` flag should be set to `True`
3) If the admin 'removes' content that has automated syncing requests, it should set the `admin_imported=False`

## User-facing consequences

File resources are not automatically removed from a device to make room for new content.

…

**Comment by rtibbles** [comment]
> If the admin later decides to import the same content, meaning the metadata already exists, the admin_imported flag should be set to True

I think there are two things that we need to do here - firstly update the admin_imported flag to default to True when the metadata is imported, and then also set it properly for the admin imported flow.
