### ISSUE TITLE
Deletion size appears to be improperly reported - and task takes a very long time to remove one resource

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11241]
## Observed behavior
I selected a single resource to delete from the Kolibri QA channel, and it reported it was deleting 106GB of data. This seems high. The deletion task then spent a very long time doing seemingly nothing, even though in the terminal, it had already run annotation for removing the offending resource. Seems that something is amiss following recent updates.

![image](https://github.com/learningequality/kolibri/assets/1680573/1da183f0-e427-49a2-b1d3-6370ea557367)

## Errors and logs
Saw this in the temrinal, then the task stalled:

```
INFO     2023-09-14 09:36:51,372 Removing availability of non-topic ContentNode objects in 1 batches of 10000
INFO     2023-09-14 09:36:51,382 Annotating ContentNode objects with children for 5 levels
INFO     2023-09-14 09:36:51,385 Annotating ContentNode objects with children for level 5
INFO     2023-09-14 09:36:51,388 Annotating ContentNode objects with children for level 4
INFO     2023-09-14 09:36:51,389 Annotating ContentNode objects with children for level 3
INFO     2023-09-14 09:36:51,392 Annotating ContentNode objects with children for level 2
INFO     2023-09-14 09:36:51,393 Annotating ContentNode objects with children for level 1
DEBUG    2023-09-14 09:36:51,395 Recursive topic tree annotation took 0 seconds
```

## Expected behavior
It should properly report a sensible amount for deletion of a single resource. The deletion task should finish very quickly for deleting a single resource.

## User-facing consequences
Confusion, inability to delete resources.

## Steps to reproduce
Import the entire Kolibri QA channel.
Attempt to delete a single document from the root of the channel from the device.

**Comment by jredrejo** [comment]
@rtibbles I've tried to reproduce this several times without success, could you confirm if it's still happening for you  in the current release-v0.16.x  branch?

Tested using `kolibri start` & `yarn python-devserver` and it worked fine with both methods.

**Comment by marcellamaki** [comment]
@radinamatic and @pcenov - can we see if this can be reproduced by the QA team? Thank you!

**Comment by pcenov** [comment]
Hi @jredrejo I couldn't replicate the first part of the issue with the incorrect size of the resources selected for deletion. However when deleting a folder with multiple subfolders from 'Khan Academy (English - US curriculum)' (317MB) it remained stuck in progress for quite some time at the 'Preparing to delete resources..' step:

https://github.com/learningequality/kolibri/assets/79847249/7840a3cf-2ea8-414f-a496-2bd82d8edf39

Logs: [logs.zip](https://github.com/learningequality/kolibri/files/12749393/logs.zip)

**Comment by jredrejo** [comment]
> Hi @jredrejo I couldn't replicate the first part of the issue with the incorrect size of the resources selected for deletion. However when deleting a folder with multiple subfolders from 'Khan Academy (English - US curriculum)' (317MB) it remained stuck in progress for quite some time at the 'Preparing to delete resources..' step:
> 
>  channel.mp4 
> Logs: [logs.zip](https://github.com/learningequality/kolibri/files/12749393/logs.zip)

Hi @pcenov I don't see any issue with that. Looking at your video it looks normal to me. Your server is in a syncing process while calculating the nodes to be deleted in a quite deep and extense tree of nodes. And I see how the deletion works properly. Do you see it slower than in the past? I.e. If you do the same while not syncing the server, do you appreciate a regression?

**Comment by pcenov** [comment]
Hi @jredrejo, no I was just mentioning that the issue as described by @rtibbles can be partially replicated, but other than taking some time in cases such as the one described above the deletion is working correctly.

**Comment by rtibbles** [comment]
I have now reconfirmed that this was an issue with my local dev setup - apologies for the noise here. This happens if LocalFiles have been annotated as `available` and it is in fact correctly cleaning these up.
