### ISSUE TITLE
enforce NPM package license compatibility

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1124]
Our software needs to use only libraries with compatible licenses. We [already do this](https://github.com/learningequality/kolibri/blob/develop/test/conditional/test_licenses.sh) for PyPi packages, and we should do it for NPM as well.

We can probably just use `yarn licenses ls` and search for instances of GPL code: https://yarnpkg.com/en/docs/cli/licenses

This should be run as a pre-commit or linting check, though we need to be careful about performance impacts.

**Comment by indirectlylit** [comment]
removing milestone. not critical

**Comment by rtibbles** [comment]
This was fixed in #8355
