### ISSUE TITLE
interpolate variables into translation strings

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1125]
Translation strings must not be concatenated with variables - the variables need to be interpolated using [ICU message syntax](https://formatjs.io/guides/message-syntax/)

[example 1](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/class-edit-page/user-remove-modal.vue):

```javascript
      deleteConfirmation: 'Are you sure you want to remove ',
      from: ' from ',
      still: 'You can still access this account from ',
```

[example 2](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/manage-class-page/class-delete-modal.vue):

```javascript
      deleteConfirmation: 'Are you sure you want to delete ',
```

**Comment by DXCanas** [comment]
@indirectlylit Is there a list I can reference to tackle some of these?

**Comment by indirectlylit** [comment]
nope, but searching vue files for these two regexes find some strings with leading and trailing space:

* `: ' .+',`
* `: '.+ ',`

results:

```
Searching 126 files for ": ' .+'," (regex)

/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/coach/assets/src/views/attempt-log-list/index.vue:
   50        today: 'Today',
   51        yesterday: 'Yesterday',
   52:       daysAgo: ' { daysElapsed } days ago',
   53        question: 'Question { questionNumber, number }',
   54      },

/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/management/assets/src/views/class-edit-page/user-remove-modal.vue:
   47        // confirmation messages
   48        deleteConfirmation: 'Are you sure you want to remove ',
   49:       from: ' from ',
   50        still: 'You can still access this account from ',
   51        users: 'Users',

2 matches across 2 files


Searching 126 files for ": '.+ '," (regex)

/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/management/assets/src/views/class-edit-page/user-remove-modal.vue:
   46        cancel: 'Cancel',
   47        // confirmation messages
   48:       deleteConfirmation: 'Are you sure you want to remove ',
   49:       from: ' from ',
   50:       still: 'You can still access this account from ',
   51        users: 'Users',
   52      },

/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/management/assets/src/views/manage-class-page/class-delete-modal.vue:
   47        description: 'Users will only be removed from the class and are still accessible from the "Users" tab.',
   48        // confirmation messages
   49:       deleteConfirmation: 'Are you sure you want to delete ',
   50      },
   51      components: {

4 matches across 2 files
```

I'd say fixing those is good enough for this task. We could potentially do a deeper audit of all translated strings but I think that'd be overkill at the moment.

**Comment by DXCanas** [comment]
I'm not finding a way to get this done on most of these strings while also including HTML (making string bold)

Should I interpolate and forget about HTML formatting, or leave them be? @indirectlylit

**Comment by indirectlylit** [comment]
There is a `$trHtml` function for this purpose - however it's potentially risky and I think we should avoid using it when possible. (https://trello.com/c/gHONGfCU/795-question-is-trhtml-a-potential-source-of-bugs-or-security-holes)

**Comment by DXCanas** [comment]
@indirectlylit $trHtml doesn't do anything differently from `$tr`, at least not as far as I could tell. I have a bug filed for it here https://github.com/learningequality/vue-intl/issues/8.

But yeah. After some debugging, it looks like it just parses the HTML out into strings and then spits it back out as a regular `$tr` string? I even went into the source code, and couldn't find it doing anything differently.

**Comment by DXCanas** [comment]
@indirectlylit I had said that it doesn't do anything differently. That was wrong.

I avoided its use though! And the way I used it, the translator never sees any of the HTML. Let me know what you think; I was kind of iffy on it.

**Comment by rtibbles** [comment]
Good to avoid it if possible, definitely,at least until we can come up with some better sanitisation on string import.

**Comment by DXCanas** [comment]
Can't find anything else with provided regex's. Will assume this is good for now.
