### ISSUE TITLE
improve messaging for users about to delete themselves

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1126]
User should be warned more strongly about the consequences of losing their account.

[Migrated from Trello](https://trello.com/c/ast2vrct/493-add-a-different-more-personal-warning-message-for-an-admin-who-is-trying-to-delete-themselves-or-downgrade-to-a-learner-role)

**Comment by radinamatic** [comment]
Trell card has been archived, and admin user cannot delete themselves, so I'm guessing this could be closed...? @indirectlylit 

![manage users - kolibri - google chrome_337](https://user-images.githubusercontent.com/1457929/28007355-6119e882-6553-11e7-956f-107eec7235b3.png)

**Comment by rtibbles** [comment]
Indeed, this issue has been closed in favour of disallowing it.
