### ISSUE TITLE
Quiz root page with questions available w/ Accordion

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11276]
## Overview

Here we will wrap up the work on #11013 by integrating the work in #11087 

This will require that we create a way to bootstrap some selected questions into the data architecture for testing purposes, but once #11015 is completed, there will be a way in the UI to do this per the specifications.

#### Acceptance Criteria

- [ ] Add a temporary button to "automatically add selected questions" which can just use mock data if needed (see `quizCreationSpecs.js` for the expected data structures - you may be able to use the objectSpec `objectWithDefaults` function to generate usable test data with the specs defined there as well
- [ ] Implement the new Accordion component fully with the data architecture so that sorting the questions, selecting the questions' checkbox, etc keeps things up-to-date
- [ ] Implement removal of questions
- [ ] Implement buttons which will open question replacement side panel (noting that the list of the user's selected questions should be stored in the `quizForge` so no need to pass that along at all to the side panel component)

**Accordion specific**

As the actual proper data gets plugged into the accordion component(s), you should identify ways in which it might differ from the [Figma](https://www.figma.com/file/1tQQ0Sw1yDjzO66hyjLVPM/Kolibri-UX-Fixes?type=design&node-id=2159-67878&mode=design&t=hbBUBwPIC80aL3qo-0) by the nature of previously using placeholder data.

**Comment by shivam-jainn** [comment]
Hey can you please assign me this issue :) I would love to work on it
