### ISSUE TITLE
Rename KContentRenderer to ContentRenderer

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11282]
In https://github.com/learningequality/kolibri-design-system/pull/436, we moved `KContentRenderer` from Kolibri Design System (KDS) repository to Kolibri repository.

As we only use `K` to prepend KDS components, it'd be good to rename `KContentRenderer` to `ContentRenderer` to indicate that it's a Kolibri component rather than coming from KDS.

## User-facing consequences

None. It just doesn't follow our convention and can therefore be slightly confusing for developers.

## Acceptance criteria

- [x] The component is renamed
- [x] All places using the component are updated accordingly

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, alright, thank you

**Comment by 0xV0YD** [comment]
@MisRob   can i work on this issue?

**Comment by MisRob** [comment]
Hi @yash1378, this has already been assigned to @ShivangRawat30

**Comment by rtibbles** [comment]
Fixed in #11289
