### ISSUE TITLE
user mgmt modals close before response from server is known

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1128]
Currently, the user-edit modal will preemptively close, even before the response from the server is returned.

Instead, it should go into a 'busy' state while the asynchronous work is pending. On success, the modal should close. On failure, appropriate messaging should be displayed in the modal.
 
migrated from: https://trello.com/c/VOJvBYTn/718-user-edit-modal-error-handling

**Comment by 66eli77** [comment]
The management plugin implemented a solution for this issue. Control the modal display from vuex state, so that one can close the modal inside an action after server responded.

**Comment by DXCanas** [comment]
@christianmemije Seems like you have this in mind in #2154?

**Comment by christianmemije** [comment]
@DXCanas Yes, that PR should take care of this!
