### ISSUE TITLE
Remove TextTruncator component

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11287]
## Summary

We recently stopped using [`TextTruncator` component](https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/views/TextTruncator.vue) completely in favor of using `TextTruncatorCss`. Let's remove `TextTruncator` from the codebase.

##  Acceptance Criteria

- [ ] `TextTruncator` exists no more
- [ ] Please double-check that `TextTruncator` is really not used anywhere

**Comment by MisRob** [comment]
This is already reserved for contribution for [yash1378](https://github.com/yash1378)

**Comment by MisRob** [comment]
Note that you need to target `release-v0.16.x` branch since that's the branch where we recently stopped using `TextTruncator` everywhere

**Comment by 0xV0YD** [comment]
hi @MisRob   please assign me this issue  and where can i connect with you for the guidance

**Comment by MisRob** [comment]
Great, you're assigned @yash1378. For questions about this particular issue, you can use this comments section. Please study CONTRIBUTING.md for guidance on development server where you will also find out where to report dev server problems if you experience any. Note there may be other team members jumping in and generally it might take us few days to reply.

**Comment by 0xV0YD** [comment]
> Great, you're assigned @yash1378. For questions about this particular issue, you can use this comments section. Please study CONTRIBUTING.md for guidance on development server where you will also find out where to report dev server problems if you experience any. Note there may be other team members jumping in and generally it might take us few days to reply.

done mam i guess i have resolved this issue and also made pr and thank you very much mam for helping me out i t was getting messed up in head as how to contribute and where to  thanx once again for helping me out  and no issues for the time , i just want to become a part of open source community

**Comment by MisRob** [comment]
Great @yash1378, welcome to the open-source community!

**Comment by 0xV0YD** [comment]
> Great @yash1378, welcome to the open-source community!

thank you mam is there any other issue in your known on which i can work i have worked with js,reactjs,nodejs,nextjs and also with sockets and mongo

**Comment by MisRob** [comment]
Hi @yash1378, I will soon be opening some more issues for Kolibri, so you can check on "good first issue"s again from time to time. We also have other products where we welcome contributions. One of my colleagues recommends this one https://github.com/learningequality/studio/issues/4272. We'll add a bit more information on where to find the place to fix soon. If you'd be interested, please send us a message there and meanwhile you can try to setup Studio development server.

**Comment by 0xV0YD** [comment]
> Hi @yash1378, I will soon be opening some more issues for Kolibri, so you can check on "good first issue"s again from time to time. We also have other products where we welcome contributions. One of my colleagues recommends this one [learningequality/studio#4272](https://github.com/learningequality/studio/issues/4272). We'll add a bit more information on where to find the place to fix soon. If you'd be interested, please send us a message there and meanwhile you can try to setup Studio development server.

Sure Mam , I will keep checking the good first issues time to time
