### ISSUE TITLE
Upgrade to Django 1.11 (once released)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1129]
## Summary

**Django 1.11 is designated as a long-term support release. It will receive security updates for at least three years after its release. Support for the previous LTS, Django 1.8, will end in April 2018.**

https://docs.djangoproject.com/en/dev/releases/1.11/

**Comment by rtibbles** [comment]
Should we upgrade to 1.10 as an interim measure in the meanwhile?

**Comment by benjaoming** [comment]
Certainly if one is upgrading from 1.9 -> 1.11, that means reading through the release notes of 1.10, so somewhat inevitable :) But we can skip actually having 1.10 released and in master, but only as a commit that's CI tested in a PR?

**Comment by benjaoming** [comment]
1.11 is out

**Comment by indirectlylit** [comment]
Might want to do this ASAP to catch any potential issues early

**Comment by benjaoming** [comment]
Thanks for adding a reminder to this.

Step 1 could be to open up a WIP PR to make test failures evident and so we can grasp the scope. But might be good if someone can clear a bit of schedule to get this done..

**Comment by rtibbles** [comment]
I think we should target this for 0.7 - I will open the PR as soon as we branch release-v0.6.x

**Comment by rtibbles** [comment]
Before this can be implemented, the hard requirement of morango on something in Django 1.9.7's internal API needs to be removed.

cc @ralphiee22 @jamalex

**Comment by indirectlylit** [comment]
removing milestone because of the morango dependency
