### ISSUE TITLE
Coach>Plan - Missing 'No results' string (CommonCoreStrings.noResults)

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11310]
## Observed behavior
When I go to Coach>Plan>Quizzes and I filter by Status returning no results I see `CommonCoreStrings.noResults` instead of 'No results'.
Also if I go to Coach>Plan>Lessons and filter by 'Not visible' (given I don't have any lessons set to Not visible) then there's no 'No results' text at all.

## Expected behavior
The 'No results' text should be displayed in all cases where the filter by status is returning no results.

## Steps to reproduce the issue
1. Install the latest Beta 6 build.
2. Go to Coach>Plan>Quizzes or Coach>Plan>Lessons
3. Filter by status

## More information

https://github.com/learningequality/kolibri/assets/79847249/e87b79f4-ad9a-4dcc-87f9-033cfe6820cc

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Note that the issue here seems to be that it should be referencing commonCoreStrings, not commonCoachStrings - the noResults string is in the former.
