### ISSUE TITLE
Coach>Plan/Reports - Missing scrollbar when previewing a resource of type PDF

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11311]
## Observed behavior
There's no scroll bar while previewing a resource of type PDF. A scrollbar is displayed for the rest of the available resource types.

## Expected behavior
A scrollbar should be displayed when previewing a PDF resource.

## Steps to reproduce the issue
1. Install the latest Beta 6 build.
2. Go to Coach>Reports>Lessons>Lesson>PDF resource>Preview or Coach>Plan>Lessons > Lesson > PDF resource

## More information

https://github.com/learningequality/kolibri/assets/79847249/eecea9cc-281b-41f3-b71c-d978f82b1aca

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by ShivangRawat30** [comment]
Can I work on this issue ?

**Comment by MisRob** [comment]
Hi @ShivangRawat30, I just assigned you a few other issues you volunteered for. I think the core team will be addressing this soon.
