### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Perseus Viewer plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11329]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Perseus Viewer plugin plugin (kolibri/plugins/perseus_viewer)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by ShivangRawat30** [comment]
I've opened a PR related to the other assigned issues, can I work on this issue ?

**Comment by MisRob** [comment]
Sure @ShivangRawat30, thank you!
