### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Learn plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11324]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Learn plugin (/kolibri/plugins/learn)**

**Comment by thesujai** [comment]
@MisRob Please, assign this to me

**Comment by MisRob** [comment]
Hi @thesujai, thank you. I already assigned you some other issues. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left you).

**Comment by thesujai** [comment]
Hey @MisRob, as I finished my other assigned issue, I will be working on this

**Comment by MisRob** [comment]
Okay, @thesujai, thanks

**Comment by rtibbles** [comment]
Fixed in #11366
