### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - E-pub Viewer plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11326]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the E-pub Viewer plugin (/kolibri/plugins/epub_viewer)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by thesujai** [comment]
I am working on this

**Comment by rtibbles** [comment]
Fixed in #11369
