### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Pdf Viewer plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11328]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Pdf Viewer plugin (/kolibri/plugins/pdf_viewer)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by ShivangRawat30** [comment]
I've opened a PR related to the other assigned issues, can I work on this issue ?

**Comment by MisRob** [comment]
Yes, thank you @ShivangRawat30

**Comment by mhdsalih2000** [comment]
is this closed or not? if not I would like to work on it

**Comment by MisRob** [comment]
Hi, @mhdsalih2000, thanks for volunteering! We have already received a pull request for this issue which will be merged soon. You're welcome to choose another issue.

We currently have contributing opportunities in three repositories. You can see the contributing guidelines (including links to issues suitable for contribution) for each of them here:

Kolibri: https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md
Kolibri Design System: https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md
Studio: https://github.com/learningequality/studio (the contributing guidelines are not ready yet here, but you could find issues in the same manner like for the other two repositories)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11529
