### ISSUE TITLE
 Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Media Player plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11327]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Media Player plugin (/kolibri/plugins/media_player)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by FireSuperior482** [comment]
please, assign this to me

**Comment by MisRob** [comment]
Hi @FireSuperior482, thank you for volunteering, I'm assigning you.

Here are our [contributing guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) if you haven't seen it yet.

We have some good pull requests already from this category of issues so it might be helpful to study one of them, for example https://github.com/learningequality/kolibri/pull/11346 as an example. It already has notes from reviewers.

Also please check out the acceptance criteria in the parent issue and include a list of affected pages in your pull request (you can just note them down as you're testing your updates), e.g. their URLs. That will help our QA team to test for regressions and smooth review process.

**Comment by FireSuperior482** [comment]
I have submitted the pull request with the necessary changes. This was my first pull request, so if there are any mistakes, please let me know

**Comment by MisRob** [comment]
Thanks @FireSuperior482, great work
