### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Coach plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11325]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Coach plugin (/kolibri/plugins/coach)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
Hello @ShivangRawat30, alright, assigning you. Thank you.

Note that even though we will review your pull request, it might take some time to merge it because we have some important fixes in progress for useKResponsiveWindow (https://github.com/learningequality/kolibri-design-system/pull/453) that we might need to finish at first before we use the composable more widely. It's not a blocker for working on this though.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11355
