### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Slideshow Viewer plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11331]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Slideshow Viewer plugin (kolibri/plugins/slideshow_viewer)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by Suraj-kumar00** [comment]
Hi @MisRob MisRob, I saw here no one is working and I really want to contribute to this issue, can you please assign this issue to me, please?

**Comment by MisRob** [comment]
Hi @Suraj-kumar00 , thanks for volunteering. You're welcome to tackle it. Please see [the contributing guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) if you haven't seen them yet. I'd also recommend studying changes and review of [this pull request](https://github.com/learningequality/kolibri/pull/11346) which resolves the same thing in a different plugin and already has some notes from reviewers so you can use it as a guidance.

**Comment by Suraj-kumar00** [comment]
Hi, @MisRob thank you for assigning this issue to me, can I know like how much time I have to solve this issue? And if I face any problem can ask you?

**Comment by MisRob** [comment]
This issue isn't pressing so you have as much time as you need, @Suraj-kumar00, thank you for asking.

If you experience problems with running the development server, it's best to contact us at GitHub Discussions linked in the contributing guidelines. For questions about this issue specifically, you can post here.

**Comment by Suraj-kumar00** [comment]
> This issue isn't pressing so you have as much time as you need, @Suraj-kumar00, thank you for asking.
> 
> If you experience problems with running the development server, it's best to contact us at GitHub Discussions linked in the contributing guidelines. For questions about this issue specifically, you can post here.

Yeah, thanks @MisRob

**Comment by MisRob** [comment]
Hi @Suraj-kumar00, just checking in if you're working on this or should we unassign you? I know you asked about the timeline beforehand so if you're still planning to give it a try, no problem.

**Comment by Suraj-kumar00** [comment]
Yes, I'm working on this @MisRob, pardon me for not updating you about this, I'll try to finish it either today or by the end of this week.

**Comment by MisRob** [comment]
No worries, and no need to hurry. Thanks! I am only checking which issues are in progress and which aren't every few weeks.

**Comment by moweiss** [comment]
Hey @Suraj-kumar00 are you still working on this? I'm interested in contributing and can take it over if you aren't finished with it.

**Comment by MisRob** [comment]
Hi @moweiss, thanks for volunteering. Since we haven't heard back from the previous volunteer, I will re-assign this to you. Please check the comments above for useful links.

**Comment by moweiss** [comment]
Hey @MisRob! I just took a look at the only .vue file in the kolibri/plugins/slideshow_viewer directory, called SlideshowRendereComponent.vue.

It doesn't seem to be using the KResponsiveWindow mixin.  On lines 83/84, I see import statements for coreVue components called responsiveElementMixin and responsiveWindowMixin, but nothing else. Should this task be closed, and marked as not needing a change?

**Comment by moweiss** [comment]
Hello! Opened a PR here: https://github.com/learningequality/kolibri/pull/11534

**Comment by MisRob** [comment]
Wonderful, thanks @moweiss!
