### ISSUE TITLE
Re-enable multiple-learner-import to a single LOD in the setup wizard

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#11336]
## Observed behavior
During QA ,It was discovered that the multiple-learner on a single device experience is not working well and has syncing problems. And we had to disable it temporary in #11242 

## Expected behavior
It would be good if these changes are reverted back to its original state once the syncing problems is addressed that still exists since 0.15

**Comment by marcellamaki** [comment]
Should be resolved by https://github.com/learningequality/kolibri/pull/11470 following @bjester's changes in #11390

**Comment by rtibbles** [comment]
Fixed in #11470
