### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Core

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11335]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Core (/kolibri/core)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by a6ar55** [comment]
hey @MisRob ,I would like to work on it.

**Comment by MisRob** [comment]
Hi @a6ar55, thanks for volunteering. You're welcome to tackle it. Please see [the contributing guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) if you haven't seen them yet. I'd also recommend studying changes and review of [this pull request](https://github.com/learningequality/kolibri/pull/11346) which resolves the same thing in a different plugin and already have some notes from reviewers so you can use it as a guidance.

**Comment by a6ar55** [comment]
Okey, sure I will look into it 👍

**Comment by Suraj-kumar00** [comment]
Hi @MisRob, I saw here no one is working and i really want to contribute to this issue , can you please assign this issue to me please!

**Comment by MisRob** [comment]
Hi @Suraj-kumar00, thanks! This is already taken by @a6ar55, I only forgot to make the assignment. I just assigned you the other issue from the group you asked for though.

**Comment by Suraj-kumar00** [comment]
> Member

yeah thanks !

**Comment by a6ar55** [comment]
Hi @MisRob, I've submitted a pull request. I carefully reviewed the documentation and implemented the required changes. This was my first experience working with composables in Vue. Could you please take a look and provide feedback?

**Comment by MisRob** [comment]
Hi @a6ar55, thank you! Overall it's looking good to me. I will review in detail in the upcoming days.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11427
