### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - User Auth plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11332]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the User Auth plugin (kolibri/plugins/user_auth)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, great, thanks. Assigning you.

I can also see you volunteered for other issues from this group. Kindly request, please ask for an assignment of a reasonable amount of issues. Each one of these will take some time as you will need to find places to test etc. As soon as you complete your assigned issues, you're welcome to ask for more. If you decide not to work on some of them, but rather worked on something else, please let us know and we can re-assign you. Thank you.

**Comment by MisRob** [comment]
@ShivangRawat30 Note that even though we will review your pull request, it might take some time to merge it because we have some important fixes in progress for useKResponsiveWindow (https://github.com/learningequality/kolibri-design-system/pull/453) that we might need to finish at first before we use the composable more widely. It's not a blocker for working on this though.

**Comment by ShivangRawat30** [comment]
@MisRob I didn't find any `KResponsiveWindowMixins` in `kolibri/plugins/user_auth`, is that the correct directory ?

**Comment by MisRob** [comment]
Hi @ShivangRawat30, can you try to search for `responsiveWindowMixin`? See the note in the parent issue https://github.com/learningequality/kolibri/issues/11321 about imports.

**Comment by MisRob** [comment]
I think I included only plugins that use it in the issues, but it's possible I made mistake and included some that don't. Let us know if you've found anything.

**Comment by ShivangRawat30** [comment]
@MisRob My apologies for the misunderstanding. I've now realized the details of the `responsiveWindowMixin` in issue #11321, and I'm ready to begin working on it.

**Comment by MisRob** [comment]
@ShivangRawat30 No problem at all :)!

**Comment by ShivangRawat30** [comment]
@MisRob I attempted to replace `KResponsiveWindow` with `useKResponsiveWindow`, but upon closer inspection, I discovered that `KResponsiveWindow` was imported in the file even though it wasn't being used.

**Comment by MisRob** [comment]
@ShivangRawat30 I see, in that case, you can just remove the obsolete import and then, if there are no more occurrences of the mixin in the user auth plugin, that would close this issue.

**Comment by rtibbles** [comment]
Fixed in #11354 (note, this was a low risk change, so I merged this to release-v0.16.x, rather than retarget to develop).
