### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - Setup Wizard plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11330]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the Setup Wizard plugin (kolibri/plugins/setup_wizard)**

**Comment by ShivangRawat30** [comment]
I would like to work on it.

**Comment by MisRob** [comment]
@ShivangRawat30 I already assigned you some other issues so I'll leave this open for other contributors. You're welcome to remind yourself here again as soon as you've finished them (explained more in one of the comments I left for you).

**Comment by TacticalPrice** [comment]
please assign this to me i would like to work on it

**Comment by MisRob** [comment]
Hi @uraj323, thank you for volunteering, I'm assigning you.

Here are our [contributing guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) if you haven't seen it yet.

We have some good pull requests already from this category of issues so it might be helpful to study one of them, for example https://github.com/learningequality/kolibri/pull/11346 as an example. It already has notes from reviewers.

Also please check out the acceptance criteria in the parent issue and include a list of affected pages in your pull request (you can just note them down as you're testing your updates), e.g. their URLs. That will help our QA team to test for regressions and smooth review process.

**Comment by MisRob** [comment]
Hi @uraj323, just checking in if you're working on this or if we should unassign you?

**Comment by KshitijThareja** [comment]
Hi @MisRob 
I believe this issue has not been resolved yet. If possible, can you assign me to this issue as I would like to work on it.

**Comment by KshitijThareja** [comment]
@MisRob  I have made the required changes and tested them locally. Should I make a PR for this issue?

**Comment by KshitijThareja** [comment]
@MisRob @marcellamaki Can you please review the PR I made in reference to this issue? Thanks again :)

**Comment by marcellamaki** [comment]
Hi @KshitijThareja - thank you for your contribution! I've assigned the PR to myself and one other team member for review. We will plan to look it over this week and get back to you with feedback, if any.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11474
