### ISSUE TITLE
Replace KResponsiveWindow mixin by useKResponsiveWindow composable - User Profile plugin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11333]
This is one of the issues whose common goal is to gradually replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable.

First, see https://github.com/learningequality/kolibri/issues/11321 for detailed instructions and acceptance criteria common to all issues.

Then, replace `KResponsiveWindow` mixin by `useKResponsiveWindow` composable in all .vue files of **the User Profile plugin (kolibri/plugins/user_profile)**

**Comment by thesujai** [comment]
@MisRob Please, assign this to me

**Comment by MisRob** [comment]
Hi @thesujai, assigning you, thank you. Note that even though we will review your pull request, it might take some time to merge it because we have some important fixes in progress for `useKResponsiveWindow` (https://github.com/learningequality/kolibri-design-system/pull/453) that we might need to finish at first before we use the composable more widely. It's not a blocker for working on this though.

**Comment by MisRob** [comment]
Note that even though we will review your pull request, it might take some time to merge it because we have some important fixes in progress for `useKResponsiveWindow` that we might need to finish at first before we use the composable more widely. It's not a blocker for working on this though.

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11358
