### ISSUE TITLE
Docker Installation stuck at python-typing

### ISSUE THREAD

**Issue by aarishshahmohsin** [learningequality/kolibri#11368]
### Discussed in https://github.com/learningequality/kolibri/discussions/11367

<div type='discussions-op-text'>

<sup>Originally posted by **aarishshahmohsin** October  7, 2023</sup>
I am trying to locally setup kolibri using docker. I've tried multiple times and every time the installation gets stuck at
 `=> => # Setting up python-typing (3.6.2-1) ... ` .
 Command : ` make docker-build-base`.  
OS: Fedora 38

![Screenshot from 2023-10-07 20-24-47](https://github.com/learningequality/kolibri/assets/49566965/dae538e5-febb-4381-8caf-83351b6fcec4)
</div>

**Comment by aarishshahmohsin** [comment]
I have found a way to fix the problem. Should I ask for a pull request?
![Screenshot from 2023-10-08 13-40-52](https://github.com/learningequality/kolibri/assets/49566965/de56d9ed-ceae-41d4-9689-1f4c9c307b66)

**Comment by aarishshahmohsin** [comment]
@pcenov please look into the issue.

**Comment by MisRob** [comment]
@bjester replied here https://github.com/learningequality/kolibri/discussions/11367
