### ISSUE TITLE
Add guidelines for rebasing `develop` branch to `release-v*` to Kolibri Developer Documentation

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11361]
## Summary

Especially before a new release, we sometimes guide contributors to rebase their pull request from `develop` to `release-v*` branch. There's a helpful guidance by @rtibbles in https://github.com/learningequality/kolibri/pull/11337#issuecomment-1741462959:

> * Make sure you have local versions of the Learning Equality develop branch and the Learning Equality release-v0.16.x branch and that they are both up to date - for the sake of the following, I will assume they are called `develop` and `release-v0.16.x` respectively.
> * Locally, checkout your feature branch
> * Run this rebase command: `git rebase --onto release-v0.16.x develop` this will rebase your current branch (your feature branch) onto `release-v0.16.x`, removing any commits that are already present in `develop` - so, if everything works as expected, it should keep your commit [bugfix- birth year selction](https://github.com/learningequality/kolibri/pull/11337/commits/15ce825f871d5361cfd5e4b2a79a7c8feec4879c)
> * Once you have done that, you will need to force push to update your remote branch `git push --force` - if the remote branch is not set, then git should give you hints about how to push to the correct remote branch.

It'd be great to move it to Kolibri Developer Documentation as a new page in [How To Guides](https://kolibri-dev.readthedocs.io/en/develop/howtos/index.html).

**`release-v*` should be used instead of `release-v0.16.x`** so that the guidelines are applicable for any future releases.
 
## Value Add

Efficiency

## Guidance
- [Documentation files location](https://github.com/learningequality/kolibri/tree/develop/docs)
- [Documentation about updating documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#updating-documentation) 🙃

**Comment by RISHIKESHk07** [comment]
hey @MisRob could i contribute to this

**Comment by MisRob** [comment]
Hi @RISHIKESHk07, yes, thank you

**Comment by Tweniee** [comment]
@MisRob i made the changes and created a PR, if any change needed please let me know
PR:#11509

**Comment by MisRob** [comment]
Thanks @Tweniee, I will have a look some time this week

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11512
