### ISSUE TITLE
App - The bottom bar navigation disappears in landscape mode

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11363]
## Observed behavior
In an Android tablet, but also in the Mac app, the bottom bar navigation disappears when in landscape mode and the app can be used with the normal desktop navigation.

## Expected behavior
Should be further discussed as this could be viewed as inconsistent behavior.

## Steps to reproduce the issue
1. Install the latest Beta 6 build on an Android tablet.
2. View Kolibri in landscape mode.

## More information

![2023_10_05_23 30 31](https://github.com/learningequality/kolibri/assets/79847249/47a95d89-10ef-4a2c-9554-a686f683240e)

## Usage Details
Kolibri 0.16beta6, Android tablet

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
[Design team](https://learningequality.slack.com/archives/C0LKG14NL/p1696541873539769) confirms it's not _by design_ 🙂

**Comment by rtibbles** [comment]
Requires updating the condition from breakpoint based to whether it's a touch device.
