### ISSUE TITLE
My downloads - The 'Available storage' value is not calculated when I am signed in as a Learner

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11377]
## Observed behavior
The 'Available storage' value is not calculated when I am signed in as a Learner and is always displayed as 0.
The following error is displayed in the console: `GET http://127.0.0.1:8080/api/device/freespace/?path=Content 403 (Forbidden)`

## Expected behavior
The 'Available storage' value should be displayed correctly.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11177
2. Create a Learner user and sign in with that user
3. Go to the Library and download a resource
4. Go to 'My downloads' and observe the value for 'Available storage'

## More information

https://github.com/learningequality/kolibri/assets/79847249/ba7f130b-79ce-4c38-b35b-5db7b823d06c

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
The simplest fix here would seem to be just loosening the permissions on the API endpoint.

**Comment by rtibbles** [comment]
One thing to note is that we should be using the 'device settings size limit' here as well, and then reporting the lower of the two numbers (so no more than the download size limit).
