### ISSUE TITLE
Explore libraries - The option 'Remove from my library' is not positioned correctly and not working

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11378]
## Observed behavior
The option 'Remove from my library' is not displayed correctly and not working

## Expected behavior
Correctly displayed and fully functioning 'Remove from my library' option

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11177
2. Go to Explore libraries and click the download icon on a card.
3. Observe the position of 'Remove from my library'
4. Click 'Remove from my library' and go to 'My downloads' to confirm that the resource is actually removed.

## More information

https://github.com/learningequality/kolibri/assets/79847249/e9627a35-ee46-4e46-bd7a-8e6874af66fc

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
First problem is clearly with the z-index of the dropdown menu falling behind the cards.

The second problem has two possibilities:
* The removal isn't actually happening when accessed from the remote library browsing page
* It is actually happening but the API endpoint is still returning contentdownload requests that have a current removal

**Comment by rtibbles** [comment]
Reopening until #11397 is confirmed to fix the issue completely and is merged.
