### ISSUE TITLE
MediaPlayer transcript display is incorrectly positioned in portrait displays

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11375]
## Observed behavior
When activating the transcript in portrait mode in the media player, the transcript completely overlays the video, and cannot be dismissed - in addition, only the lower part of the transcript display is visible. This seems to happen regardless of screen breakpoint.

The styling that is being applied seems to work for the other scenario that it is made for, when the screen is small and the video is shown in full screen mode, so it might be better not to change the styling, but rather to create a separate case for this scenario.

![image](https://github.com/learningequality/kolibri/assets/1680573/8372bab0-ce55-4c65-987f-7f0bbcd6d62c)

## Expected behavior
The transcript should be displayed below the video player.

## User-facing consequences
A very poor user experience, especially as it is impossible to dismiss the transcript once activated, because it is covered - the only way a user can remove it is to turn their device into landscape mode.

## Steps to reproduce
Open a video with subtitles in a device or screen size that is portrait.
Open the transcript option

## Context
0.16.0 beta

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by MisRob** [comment]
Hello @ShivangRawat30, this is being address by a core team member already
