### ISSUE TITLE
Login page remains in English even though portal is set to French

### ISSUE THREAD

**Issue by Kevsy** [learningequality/kolibri#1138]
## Summary

The portal has been set to French language, and once you are logged in everything is indeed in French. However the login page remains in English, which is a barrier to DRC users.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Vodafone 0.3 pex
 - Operating system: Ubuntu 14.04
 - Browser: Firefox and IE

## How to reproduce

1. ./kolibri language setdefault fr-fr
1. kolibri start
1. access Kolibri  via browser

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Barrier to DRC launch

**Comment by aronasorman** [comment]
Hi @Kevsy, can you attach your pex file here so we can try it out on our side?

**Comment by aronasorman** [comment]
@Kevsy never mind, we can replicate this with the production server! https://fr.instantschools.learningequality.org/user#/signin

**Comment by Kevsy** [comment]
Cheers @aronasorman , much appreciated

**Comment by aronasorman** [comment]
@rtibbles I see why. The locale folders for the external paths aren't added to `LOCALE_PATHS`:

```
>>> settings.LOCALE_PATHS
[u'/Users/aron/.pex/install/kolibri-0.3.0-py2.py3-none-any.whl.cb9c5d381ba3b0738cc8fe7f8af91e21708a8552/kolibri-0.3.0-py2.py3-none-any.whl/kolibri/locale']
```

**Comment by aronasorman** [comment]
@rtibbles are those supposed to get added automatically during run time?

**Comment by aronasorman** [comment]
There's this function in `hooks.py`:

```
    @property
    def locale_data_folder(self):
        if self._module_path.startswith('kolibri.'):
            return os.path.join(getattr(django_settings, 'LOCALE_PATHS')[0], 'en', 'LC_FRONTEND_MESSAGES')
        # Is an external plugin, do otherwise!
        else:
            return os.path.join(
                os.path.dirname(self._build_path),
                getattr(self, 'locale_path', 'locale'), 'en', 'LC_FRONTEND_MESSAGES')
```

**Comment by aronasorman** [comment]
Looks like it's used by `webpack_bundle_data`. I'll try to see how this function is used.

**Comment by aronasorman** [comment]
@rtibbles ah, so Django does automatically add catalog files for external apps. But it looks for mo or po files specifically:

https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#how-django-discovers-translations

So we have to roll our own solution for frontend catalog files.

**Comment by aronasorman** [comment]
i.e. they're not added to `LOCALE_PATHS`. So we'll need another function to add those manually.

**Comment by aronasorman** [comment]
A quick function to derive the locale folders from external plugins, and:
![screen shot 2017-03-27 at 17 14 43](https://cloud.githubusercontent.com/assets/191955/24383295/f2c6803c-1310-11e7-90a4-a9b9ee4175f3.png)

I'll make a PR with my changes.

**Comment by Kevsy** [comment]
From my local test this seems to have been fixed, but we will install in DRC before closing. Cheers :)

**Comment by Kevsy** [comment]
All good, many thanks :)
