### ISSUE TITLE
Add more padding below the 'View More' button to  enhance its visibility

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#11387]
## Observed behavior

Some padding should be applied to the bottom of the `View More` button that is displayed when browsing a remote device.
![image](https://github.com/learningequality/kolibri/assets/5203639/29982792-d999-44a6-a102-2aac08264f4d)

## Errors and logs

NA

## Expected behavior

- There should be some padding below the `View More` button to enhance visibility of the button.

## User-facing consequences

- A user could easily miss the view more button

## Steps to reproduce

- Browse a remote library that have many resources. The button should appear at the very bottom flashing with the end of the browser window.

## Context

- release-0.16.x
- Chrome Version 117.0.5938.149 (Official Build) (arm64)
- MacOs Sonoma 14.0

**Comment by thesujai** [comment]
@rtibbles I am working on this
