### ISSUE TITLE
Library - Limit the number of cards displayed in the 'Recent' section

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11438]
## Observed behavior

The 'Recent' section can get quite long - a 'View more' link is shown in Figma when there are more than 3 cards.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11419 and setup a full facility.
2. Go to the Library page and view multiple resources.
3. Observe the 'Recent' section.

## More information

https://github.com/learningequality/kolibri/assets/79847249/fc799e16-3115-412c-a621-607094da736e

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
When fixing this issue, I would recommend using this composable to enforce a limit of one row of card display (or a minimum of three cards), and also to help make the cards smaller (they often display significantly larger than the channel card on the same page).

https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/composables/useCardLayoutSpan.js
