### ISSUE TITLE
Library - No clear indication of a lost internet connection

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11437]
## Observed behavior

There's no clear indication that I've lost my connection - the Kolibri Library appears available but clicking on a resource just brings me back to the Library page.

## Expected behavior
To be further discussed.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11419 and setup a full facility.
2. Go to the Library page.
3. Turn off your wi-fi.
4. Keep attempting to explore the 'Kolibri Library' section under 'Other libraries'

## More information

https://github.com/learningequality/kolibri/assets/79847249/94a34eb1-1d7d-4e32-9a2a-435560d2a183

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Disconnected icon in the top immersive page bar as shown in the figma is not appearing. It's possible that the polling/wifi disconnection status is not working as expected.

needs investigation - is there a distinction between the local browsing vs. the studio/kolibri library browsing? is this only causing an issue with studio.

**Comment by akolson** [comment]
This seems to happen for the `Kolibri Library` only. The network libraries are disappear when wifi has been disconnected.
