### ISSUE TITLE
The 'Welcome to Kolibri' modal is displayed regardless of the fact that I have imported channels

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11456]
## Observed behavior

This is a follow-up issue to https://github.com/learningequality/kolibri/pull/11449 - since we are not tracking the dismissal in anything other than browser state the 'Welcome to Kolibri!' modal will show on the Library page and on Device > Channels regardless of whether the user has already imported channels or not.

## Expected behavior
The 'Welcome to Kolibri!' should only be displayed to actual first time users.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11449 and setup a full facility.
3. Sign in and go to the Library page and/or Device > Channels - observe the welcome modal
4. Import channels
5. Clear all the browser cookies and sign in again, or sign in using a different browser - observe that the Welcome modal is displayed regardless of the fact that the user has already downloaded channels to the device.

## More information

Library:

https://github.com/learningequality/kolibri/assets/79847249/270a830b-d6e5-4e10-be37-735a89c8c4cc

Device > Channels:

![2023-10-24_10-08-29](https://github.com/learningequality/kolibri/assets/79847249/0ee242fb-3fd1-4224-a5d3-42ee157107e7)

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@marcellamaki @radinamatic

**Comment by ozer550** [comment]
I can take this one!

**Comment by marcellamaki** [comment]
Thank you @ozer550! I'll assign you. Let me and @rtibbles know if we can support or clarify anything

**Comment by radinamatic** [comment]
Welcome modal still appears, on LoD devices even, upon each app restart.

And even more, @pcenov discovered that the strings appear in English when the language is switched in the UI. Strings are translated in Crowdin, so there must be some reference mismatch.

UI in Arabic | UI in French
-- | --
![welcome-arabic](https://github.com/learningequality/kolibri/assets/1457929/2dca22bd-22f3-4efb-b9d7-adeb6a8bd6c6) | ![welcome-french](https://github.com/learningequality/kolibri/assets/1457929/0d631e66-2a6c-4bed-86de-39da40b71287)

All the [DBs and logs from testing on Windows 10](https://drive.google.com/drive/folders/1jXHg1lF1gpjD-fDT3JMp8hgdVkGzDVnv?usp=sharing).

**Comment by radinamatic** [comment]
Changed to P0, since we cannot have LoDs displaying this message.
