### ISSUE TITLE
Quizzes - The 'missing resource' alert is not displayed at the Home page

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11453]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/11426 - quizzes with missing resources are not showing an alert on the home page.

## Expected behavior
To be further discussed.

## Steps to reproduce the issue
1. Install the latest build from https://github.com/learningequality/kolibri/pull/11426 and setup a full facility and a learn-only device.
2. Assign a quiz to the learner on the LOD.
3. Sign in as the learner and delete some of the quiz resources by going to Device > Channel
4. Go to the quiz an observe that it correctly alerts for missing resources.
5. Go to the learner's home page and observe that there the alert 'Some resources are missing or not supported..' is missing.

## More information

Video with replications steps - the original was more than 10 minutes long, so I had to shorten it:

https://github.com/learningequality/kolibri/assets/79847249/8fb9dcb4-8419-4e01-8f8f-180d39a3ad91

## Usage Details
Kolibri 0.16beta6
Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by marcellamaki** [comment]
@pcenov just to clarify, the behavior of the missing alert on the home page is seen only with quizzes when following these steps, not if you do the same with lesson resources? I realize the quiz format is different, but if you
1. Assign a lesson to the learner on the LOD.
2. Sign in as the learner and delete some of the quiz resources by going to Device > Channel
If you go to the home page, is the alert 'Some resources are missing or not supported..' missing? Thank you!

**Comment by pcenov** [comment]
Hi @marcellamaki - yes, the issue I've described here is specifically about the assigned quizzes with missing resources and not about assigned lessons containing missing quiz resources.

**Comment by pcenov** [comment]
@radinamatic we've discussed this and it's still valid.

**Comment by pcenov** [comment]
@radinamatic - I confirm that this is still extant in the official 0.16 build. 

Quiz with missing resources (in which case we have to open the quiz to see that there are missing resources):

https://github.com/learningequality/kolibri/assets/79847249/f2426f8c-03a6-4b89-9ccf-d37e8a3b9047

Lesson with missing quiz resources (in which case the 'missing resource' alert is clearly displayed):

https://github.com/learningequality/kolibri/assets/79847249/e8037376-9d42-4e08-a606-d16085cbf420

**Comment by radinamatic** [comment]
Thank you for confirming, @pcenov! 🙏🏽 

@marcellamaki I believe with the recordings provided the inconsistent experience is now clear, and the priority to be fixed in the upcoming patch should remain P1.

**Comment by rtibbles** [comment]
Fixed in #12008
