### ISSUE TITLE
When syncing job fails it's not scheduled again

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#11469]
## Observed behavior

A LOD tried to sync and the process didn't finish because the sqlite db was locked by another process (in this case it was sqlitebrowser). That's fine with sqlite.

However when the job failed, kolibri didn't schedule it again, so this LOD stopped syncing until it was restarted.
After restarting it the `kolibri.core.auth.tasks.soud_sync_processing` job was scheduled again and everything was fine.

## Errors and logs
It can be seen beginning on line 550 of this log file
[kolibri.txt](https://github.com/learningequality/kolibri/files/13191404/kolibri.txt)

## Expected behavior
In case a syncing job fails, it should be scheduled again

## User-facing consequences
Syncing stop until the kolibri instance of the user is restarted

## Steps to reproduce
It happened when the `networklocation.sqlite3` file was open in sqlitebrowser but it'll likely happen if `db.sqlite3` or` job_storage.sqlite3` are open too or kolibri is doing the `vacuum` task

## Context
kolibri 0.16 installed on this PR code https://github.com/learningequality/kolibri/pull/11390

**Comment by rtibbles** [comment]
Looking at this again - I don't think the database locked error is the issue here, as it is being caught and reported. I think this is actually another instance of https://github.com/learningequality/kolibri/issues/11485, as I am seeing elsewhere in the logs a 404 from the transfersession endpoint.
