### ISSUE TITLE
Update phrasing explaining LOD option in onboarding flow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11461]
Reported by Laura:

During the onboarding flow, the *Learn-only device* phrasing of "This device will have one or more learner accounts imported from a full device that already exists" isn't _always_ true because the next step gives an option to either import _or_ *Create a new user account for an existing facility*. But if I saw that explanation I would be confused and think that it was necessary to already have an account created.

Maybe better phrasing would be "This device will have one or more learner accounts *syncing with* a full device that already exists" or "This device will auto-sync with a full device that already exists. Learn-only devices have Kolibri features for learners, but not those for coaches and admins"

**Comment by hustlernik** [comment]
Is this open to solve? @marcellamaki

**Comment by marcellamaki** [comment]
Hi @hustlernik - thanks for your interest in contributing to Kolibri! This issue is open, but it still needs some decisions from our team before it can be assigned to anyone to pick up. To find issues that welcome community contributions, look for unassigned issues with the "help wanted" tag. You can also visit our [Github discussions page](https://github.com/learningequality/kolibri/discussions) for more information about open source contributions.

**Comment by hustlernik** [comment]
@marcellamaki Thanks for guidance, mam.
