### ISSUE TITLE
Pressing enter to submit the Super Admin creation form in the Setup Wizard does not make form validation warnings visible

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11465]
## Observed behavior
When entering super admin details into the form for the setup wizard, if you type in passwords that do not match, and then on the second password box press 'enter' to submit, the submission will not happen because the passwords do not match, but no warning text is displayed to the user to explain why this is the case.

## Expected behavior
Any attempt to submit should trigger form validation and display warning text to the user, in this case "passwords do not match"

## User-facing consequences
Confusion, especially when passwords do not match due to a typo.

## Steps to reproduce
* Start the setup wizard from scratch
* Use the 'on my own workflow'
* Type in account details, using tab to move from one text box to the next
* Type in differing passwords in each password box
* Press enter to submit

## Context
Kolibri 0.16.0-betas

Observed in Chrome, but probably not browser dependent.

**Comment by a6ar55** [comment]
I would like to work on this.

**Comment by MisRob** [comment]
Hi @a6ar55, alright I'm assigning you.

**Comment by thesujai** [comment]
There is a similar problem in login for home facility, for invalid username no warning is shown
Refer to the video below(only users with username `thesujai` and `ram` exists in my db):

[Screencast from 03-11-23 08:02:40 AM IST.webm](https://github.com/learningequality/kolibri/assets/120925871/14940642-c89f-4298-9b25-13e88acfae48)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11500
