### ISSUE TITLE
Update top bar and bottom navigation appear and hide according to spec

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11471]
## Observed behavior
According to the design spec for the app version of Kolibri, the top bar and the bottom navigation should hide as the user scrolls down, and show again as they scroll up.

<img width="534" alt="Screenshot 2023-10-27 at 12 43 59 PM" src="https://github.com/learningequality/kolibri/assets/17235236/2442cbac-0f76-4d19-a02d-cd47541e5dac">

Currently, this is not implemented.

## Expected behavior
This implementation should be applied when both of the following conditions are true:
- on a touch device
- in the app

Because the bottom bar does not appear in other settings, changes to the appearance are not relevant in other contexts (desktop, browser mobile device, etc.)

These changes should not impact the desktop app or the browser version of Kolibri. Meaning, if viewing Kolibri in the browser on a mobile/touch device, there is no change.

## User-facing consequences
On small screens, much of the space could be taken up by navigation when it is not needed. 

## Steps to reproduce
Test the latest 0.16.x version on a touch/mobile device. Alternatively, you could mock the state being a touch device for testing on a desktop setup while making the fix, and then later confirm with the QA team that the fix is working as intended on a physical device.

**Comment by 0xV0YD** [comment]
@marcellamaki  is this issue open or closed ?

**Comment by rtibbles** [comment]
It is open and assigned to @akolson, who has an open PR for its resolution, as can be seen linked above.
