### ISSUE TITLE
'All content' and 'Most popular' remains in English even though portal is set to French

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1147]
## Summary

The portal has been set to French language, but the 'All content' and 'Most popular' strings in the Recommended content page remain in English

## System information

Version: Vodafone 0.3 pex
Operating system: Ubuntu 14.04
Browser: Firefox and IE

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

./kolibri language setdefault fr-fr
kolibri start
access Kolibri via browser

## Screenshots

![image](https://cloud.githubusercontent.com/assets/5150483/24383615/d2b08f8e-1312-11e7-8d31-70edb1f7a632.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Needed for French DRC users

**Comment by rtibbles** [comment]
This is due to an unwrapped string here: https://github.com/learningequality/kolibri/blob/release-v0.3.x/kolibri/plugins/learn/assets/src/vue/learn-page/allcontent.vue#L3

and here: https://github.com/learningequality/kolibri/blob/release-v0.3.x/kolibri/plugins/learn/assets/src/vue/learn-page/index.vue#L10

Will fix.

**Comment by jeepurs** [comment]
@rtibbles Are these strings also unwrapped? Should I open a new issue for these?

![image](https://cloud.githubusercontent.com/assets/5150483/24427497/f9a49d08-13bf-11e7-9313-53427a94af5f.png)

![image](https://cloud.githubusercontent.com/assets/5150483/24427540/1cce59b8-13c0-11e7-9ba7-a602c7e7c5a7.png)

**Comment by jeepurs** [comment]
@rtibbles @aronasorman I made a separate issue for these strings: https://github.com/learningequality/kolibri/issues/1157

**Comment by indirectlylit** [comment]
two more found - 'Log In' and 'Finish':

![image](https://cloud.githubusercontent.com/assets/2367265/24439993/6d8d3a86-1406-11e7-9740-8cbe7cc2eca5.png)

**Comment by christianmemije** [comment]
PR to address those 2 ^ :
https://github.com/fle-internal/kolibri-instant-schools-plugin/pull/38

**Comment by indirectlylit** [comment]
thank you!

Note that to fully fix this issue, we'll also need to commit translations and update kolibri to reference the new VF commit.

I'm going to create an 0.3.1 tag with the current state of things so we can at least get that to them, and then we can do an 0.3.2 with these two strings translated when that's ready.

**Comment by rtibbles** [comment]
Fixed in #1152.
