### ISSUE TITLE
KRadioButton 'value' prop deprecation

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#11481]
## Overview
Before updating KDS, it should be noted that the `KRadioButton` `value` prop is soon to be deprecated. The `buttonValue` prop should be used instead.

#### Description and outcomes
`KRadioButton` has been configured to use the prop `buttonValue` rather than `value` to fix redundancy and avoid confusion regarding the API.

#### Resources
- [ ] Relevant KDS [issue](https://github.com/learningequality/kolibri-design-system/issues/379)
- [ ]  Relevant KDS [pull request](https://github.com/learningequality/kolibri-design-system/pull/485)

**Comment by moweiss** [comment]
Hello! I'm interested in contributing and was wondering if I could have this assigned to me?

**Comment by LianaHarris360** [comment]
Hi @moweiss thank you for your interest in contributing! At the moment this issue is blocked and isn't suitable for immediate work. I would suggest taking a look at issues that are labeled as "help wanted" instead, as they are likely to be the best ones to contribute to.
