### ISSUE TITLE
Setup Wizard - The 'Learning facility name' field can be left empty

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11486]
## Observed behavior
Currently it's possible to leave empty the 'Learning facility name' field at the 'What kind of learning environment is your facility' page (for both Formal and Non-formal facility).

## Expected behavior
The 'Learning facility name' field should be required and the user should be prompted to enter a value before being able to continue.

## Steps to reproduce the issue
1. Install the [Beta 7 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta7).
2. Start setting up a device through the 'Full device' flow 
3. Attempt to leave empty the 'Learning facility name' field at the 'What kind of learning environment is your facility' page.

## Video

https://github.com/learningequality/kolibri/assets/79847249/0b331ecc-89ad-4b2b-a37f-166892e45927

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta7
Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by KshitijThareja** [comment]
@rtibbles Can you please assign this issue to me? I have already  worked on the solution and will be linking a PR to this issue soon. 
Thanks :)

**Comment by rtibbles** [comment]
Yes - please make sure to base your code off the release-v0.16.x branch!

**Comment by KshitijThareja** [comment]
@rtibbles I have made a PR for this issue. Can you please review it once and suggest changes, if any?

**Comment by MisRob** [comment]
Hi @KshitijThareja, thank you, we will review it
