### ISSUE TITLE
[DOC] Add license information in README

### ISSUE THREAD

**Issue by adityadeshpande09** [learningequality/kolibri#11493]
Add License information in README file

**Comment by rtibbles** [comment]
We follow Github's recommended best practices of putting our license in a LICENCE file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

It states that some projects include their license in the README, but does not suggest or recommend redundantly making it.

Closing as a wontfix.
