### ISSUE TITLE
Adding resources to lesson can interfere with LoD syncing?

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11498]
## Observed behavior
Encountered while testing #11489: after 3 successful resumed syncing upon re-connection of LoD to WiFi, I decided to add resources to lessons that the learner previously completed, and test if they are reaching the LoD. Something did reach the learner device as they could now see the lesson cards marked with *In progress* instead of *Completed*, but  when the learner opens the lesson, there was no sign of the newly added resource, nor any notification that a resource is incoming. While waiting for something to appear, I made and started a quiz, which was eventually synced to the LoD, but still there was no sign of the newly added resources to each lesson.

LoD | Coach
-- | --
![Screenshot_2023-11-03-22-30-27-848_org learningequality Kolibri](https://github.com/learningequality/kolibri/assets/1457929/e049244c-e464-427b-8651-1451846945a7) | <img width="960" alt="2023-11-03_23-02-50" src="https://github.com/learningequality/kolibri/assets/1457929/8680f67b-81e8-4e12-b5bc-48529f802f25">

Syncing seems to have been interrupted, I waited close to 20 minutes and no change on either LoD or Coach side. Afterwards I restarted the app, and finally the new resources appeared, one in each lesson. However the syncing did not resume after the app restart, and neither after the LoD reboot or the server `kolibri service` restart. 

## Errors and logs
[Ubuntu20-server-db-logs.zip](https://github.com/learningequality/kolibri/files/13255058/Ubuntu20-server-db-logs.zip)
[Android13-LoD-logs.zip](https://github.com/learningequality/kolibri/files/13255059/Android13-LoD-logs.zip)
[db-Android13.zip](https://github.com/learningequality/kolibri/files/13255090/db-Android13.zip)

## Expected behavior
Adding resources to the lesson should not interrupt syncing.

## User-facing consequences
...

## Steps to reproduce
…

## Context

 * Kolibri version: DEB and APK assets from #11489 
 * Operating system: Ubuntu 20.04 server and Android 13 LoD
 * Browser: Firefox

**Comment by bjester** [comment]
I've confirmed that adding resources to a lesson does not interfere with syncing. I believe the issue was that a 'database is locked' error occurred, which syncing will be made more robust with fixes from https://github.com/learningequality/kolibri/issues/11469 and https://github.com/learningequality/kolibri/issues/11485
