### ISSUE TITLE
Allow character input for sign-in username field on mobile devices

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1150]
## Summary
From Panwar's email:

> ​I tried to access the Kolibri on two androids phones which have android version 6.0.1 and 5.0.2 On both phones I do not get the keyboard to enter the alphabetic characters for the user name as you can see in the screenshot. I get only the numeric keyboard.

Username input field on login page is setup to `type="tel"` which forces both iOS and Android to display a dialer keypad instead of the standard one. Maybe we should change it to `type="text"` since alphanumeric keyboard allows both?  

## System information

 - Version: 0.3.0
 - Browser: all on mobile devices

## Screenshots

![screenshot_keyboard for user name](https://cloud.githubusercontent.com/assets/1457929/24391208/95109702-1342-11e7-8591-fc1a492f5517.png)

![screenshot_keyboard for user name2](https://cloud.githubusercontent.com/assets/1457929/24391369/89d9388e-1343-11e7-9de6-ce23e28b90d3.png)

**Comment by indirectlylit** [comment]
thanks - looks like this was somehow included from the VF plugin
