### ISSUE TITLE
Add  option to change current tasks queue by a tasks stack

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#11506]
## Overview

There are some particular cases where jobs should be picked beginning by the last added to the queue, following a LIFO behaviour instead of the current FIFO.
Having the possibility to chose between a queue and a stack, or having an option to determine how jobs are picked from the queue would be really helpful.

#### Description and outcomes
Theoretically this would be doable changing the ordering of `time_created` from default ascending to descending [here](https://github.com/learningequality/kolibri/blob/2351bb29daf6da86eae439199e0372bd1e4ace97/kolibri/core/tasks/storage.py#L235) -- 
Passing an argument to this function and passing that to the engine specific [function can do the job](https://github.com/learningequality/kolibri/blob/2351bb29daf6da86eae439199e0372bd1e4ace97/kolibri/core/tasks/storage.py#L273C9-L273C28)

This would be helpful in situations where some of the data to be shown to the user is being calculated in a task in the background. If the user moves between pages in the web site, it's better to do the calculations of the last page where the user moved first.

**Comment by moweiss** [comment]
Hello I am interested in contributing! Can you assign this to me?

**Comment by MisRob** [comment]
@jredrejo Do you think this is suitable for contribution?

**Comment by MisRob** [comment]
Hi @moweiss, I already assigned you another issue so it'd be good if you could focus on that one at first.

Regarding this one, we discussed it with @jredrejo. Originally, we didn't seek contributions on this one as it requires a good knowledge of Python and it may be helpful to have some previous experience with Kolibri since this is its core part. However, we appreciate any help and are definitely open to volunteers here. 

So after you resolve your first issue, feel free to come back here. Then, I'd recommend to study relevant parts of the codebase and perhaps make a brief proposal of next steps here in the comments before diving into the full implementation, just to make sure we're all on the same page.

**Comment by moweiss** [comment]
Hello! Checking back here to see if I can proceed with working on this? I've uploaded (and I think wrapped up) a PR for my first issue.

**Comment by GarvitSinghal47** [comment]
@MisRob i would like to work on this issue if it is still open for contribution

**Comment by MisRob** [comment]
Hi @GarvitSinghal47, thank you! @moweiss was here a bit sooner so I will leave it for them. You're welcome to find another issue to work on. 

We currently have contributing opportunities in three repositories. You can see the contributing guidelines including links to issues suitable for contribution for each repository here:

Kolibri: https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md
Kolibri Design System: https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md
Studio: https://github.com/learningequality/studio (the contributing guidelines are not ready yet here, but you could find issues in the same manner like for the other two repositories)

**Comment by MisRob** [comment]
@moweiss feel free to have a look, I'd recommend following guidance I posted here https://github.com/learningequality/kolibri/issues/11506#issuecomment-1805606130. If you have any questions or when your proposal is ready, please mention @jredrejo.

**Comment by nick2432** [comment]
The current assignee has been inactive for one week. Could you please assign this task to me?

**Comment by AlexVelezLl** [comment]
Hi @moweiss! Are you still working on this issue? If there is anything we can help you with, let us know.

**Comment by nick2432** [comment]
@AlexVelezLl  can i work on this?

**Comment by AlexVelezLl** [comment]
Hi @nick2432. Sure! I have assigned the issue to you. Thank you!

**Comment by nick2432** [comment]
@AlexVelezLl  @MisRob  Proposed Solution:

Introduce a new parameter, use_lifo, to the _filter_next_query method, allowing developers to toggle between FIFO (default) and LIFO behaviors. Additionally, extend the get_next_queued_job method to accept this parameter and pass it to the _filter_next_query method accordingly.

**Comment by vkWeb** [comment]
@nick2432 your proposed solution look correct to me, just keep in mind that priority should be respected, you only need to change the ordering of `time_created`.

@jredrejo will we need to define a configuration sort of thing for changing from FIFO to LIFO..?

**Comment by jredrejo** [comment]
> @jredrejo will we need to define a configuration sort of thing for changing from FIFO to LIFO..?

I think it would be good to have a `DEFAULT_STACK` defined, similar to the `DEFAULT_QUEUE` that's defined in `kolibri/core/tasks/constants.py`. Using the `enqueue` functions in storage with `DEFAULT_STACK` would behave in `LIFO` mode. Studing ways to implement this would be make devs life easier later because there would not be any need to be calling the different jobs functions in a different manner, just selecting the right _queue_ for the job would make it.

If that approach is too complex or hard to implement,  the best alternative is what @vkWeb proposes, adding a new optional argument to the `enqueue_job` and `enqueue_job_if_not_enqueued`  to pass from FIFO to LIFO.

**Comment by vkWeb** [comment]
@nick2432 please wait until me and @jredrejo decide the right approach to solve this. Then we will let you know on how exactly to proceed with coding this.

**Comment by nick2432** [comment]
> @nick2432 please wait until me and @jredrejo decide the right approach to solve this. Then we will let you know on how exactly to proceed with coding this.

OK thank you

**Comment by vkWeb** [comment]
@nick2432 Hello! We have decided the right approach for this.

So, we will enqueue LIFO jobs before all the QUEUED jobs, it means that LIFO jobs will run first and then FIFO jobs will be run.

Imagine a initial queue as: `[  [FIFO_Job]  ]` when a new LIFO job is enqueued, the new queue will look like 
`[ [LIFO_Job] [FIFO_Job]  ]`. When another new LIFO job is enqueued, queue will be 
`[ [LIFO_Job] [LIFO_Job] [FIFO_Job]  ]`.

#### 1. You will need to implement a `enqueue_lifo_job` function in [storage class](https://github.com/learningequality/kolibri/blob/8f00a2e2b068d393e50ade59eb091e67dc34460a/kolibri/core/tasks/storage.py#L95), it should look much like below -- 

> **Below code implementation credits to @rtibbles**
```python

def enqueue_lifo(
        self, job, queue=DEFAULT_QUEUE, priority=Priority.REGULAR, retry_interval=None
    ):
        """
        Add the job given by j to the job queue.

        Note: Does not actually run the job.
        """
        naive_utc_now = datetime.utcnow()
        soonest_job = query.filter(ORMJob.state == State.QUEUED)
            .filter(ORMJob.scheduled_time <= naive_utc_now)
            .order_by(ORMJob.scheduled_time).first()
        dt = timezone.make_aware(soonest_job.scheduled_time, pytz.utc) - timedelta(microsecond=1) if soonest_job else self._now()
        try:
            return self.schedule(
                dt,
                job,
                queue,
                priority=priority,
                interval=0,
                repeat=0,
                retry_interval=retry_interval,
            )
        except JobRunning:
            logger.debug(
                "Attempted to enqueue a running job {job_id}, ignoring.".format(
                    job_id=job.job_id
                )
            )
            return job.job_id
```

#### 2. Add a new method to [`RegisteredTask`](https://github.com/learningequality/kolibri/blob/8f00a2e2b068d393e50ade59eb091e67dc34460a/kolibri/core/tasks/registry.py#L133), the new method can be named `enqueue_lifo_job`, that calls the `JobStorage.enqueue_lifo` method that we implemented above. 
#### 3. Add unit tests for testing this behavior. Your unit test should make sure that when enqueuing multiple LIFO jobs, the latest enqueued LIFO job is run first.

**Comment by nick2432** [comment]
Hey @vkWeb  , I've implemented the necessary changes and added unit test, but I'm encountering errors in every test file when I run the pytest command. Any insights on why this might be happening?
![image](https://github.com/learningequality/kolibri/assets/77477551/253b6d4e-89b3-459e-81ef-0f85153776cc)

**Comment by jredrejo** [comment]
> Hey @vkWeb , I've implemented the necessary changes and added unit test, but I'm encountering errors in every test file when I run the pytest command. Any insights on why this might be happening? ![image](https://private-user-images.githubusercontent.com/77477551/293914059-253b6d4e-89b3-459e-81ef-0f85153776cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODU3ODgsIm5iZiI6MTcwNDI4NTQ4OCwicGF0aCI6Ii83NzQ3NzU1MS8yOTM5MTQwNTktMjUzYjZkNGUtODliMy00NTllLTgxZWYtMGY4NTE1Mzc3NmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEyMzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NGQ3ODJhYWM3OGJhNTZiZDVjYTFlMDM5ZTk1MTYxNWFlZWNkYWQ1NDI1NGE4MjdiZDRkMjZmZmZiYzcwY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-JFLlObHSAVDRPEduDWs0GQWIRAbgKIo4JXk41jmbg)

hi @nick2432 , how are you running the tests? Also, you don't provide any traceback from the errors so it's hard to know what's happening to you. My only guess could be that you have not installed kolibri in the environment where you are working, i.e. it seems you haven't done 
`pip install -e .`
Also, before anything else, ensure you've installed all the needed dependencies, specially those from the ` test.txt` file, as explained in https://kolibri-dev.readthedocs.io/en/latest/getting_started.html#install-python-dependencies

**Comment by nick2432** [comment]
The test is now working; I hadn't installed the dependencies. Thank you, @jredrejo  !
