### ISSUE TITLE
Beta 8 Android syncing issues

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11524]
## Observed behavior

After setting up a LOD on an Android device the syncing is working correctly for some time and then it completely stops regardless of how many times I restart the server and the app on the device. I'm providing the logs of 2 separate testing sessions on Android using the same learner and the server logs. Also tested syncing with a Mac and Windows LODs which were syncing correctly.

It seems that the issue described in https://github.com/learningequality/kolibri/issues/11485 is still valid as well.

## Expected behavior

Fully functioning sync with an Android LOD.

## Steps to reproduce the issue
1. Install the [Beta 8 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta8).
2. Setup a server and an Android LOD device connected to the server.
3. Start assigning lessons/quizzes to the LOD and observe the sync status.

## Logs

https://drive.google.com/drive/folders/1TFxMYrFIj0BpjD3KdpdFHwlHsy9DnfUp?usp=drive_link

## Usage Details
Ubuntu 22  - Chrome, Android 13

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
On my side the results are similar, 3 Android LoDs start syncing Ok with the server on Windows 10, no issue with importing/creating/merging accounts, but eventually , after I leave Kolibri app running on them, but without much interaction, the syncing stops. Only one LoD managed to sync for 3-4 hours, but also ended up in the 'Not recently synced' state.

1 | 2
-- | --
<img width="840" alt="1-of-3" src="https://github.com/learningequality/kolibri/assets/1457929/6297f3f7-7a3d-4c0c-ac6a-991910adfedb"> | <img width="840" alt="0-of-3" src="https://github.com/learningequality/kolibri/assets/1457929/305b5aa8-dd27-46d6-bc65-001ff3cf62ae">

[Win10-db-and-logs.zip](https://github.com/learningequality/kolibri/files/13339364/Win10-db-and-logs.zip)
[Android11-marcg-db-and-logs.zip](https://github.com/learningequality/kolibri/files/13339366/Android11-marcg-db-and-logs.zip)
[Android11-michc-db-and-logs.zip](https://github.com/learningequality/kolibri/files/13339367/Android11-michc-db-and-logs.zip)
[Android13-neelar-db-and-logs.zip](https://github.com/learningequality/kolibri/files/13339368/Android13-neelar-db-and-logs.zip)
