### ISSUE TITLE
Missing form validation on facility creation on Setup Wizard

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri#11536]
## Observed behavior

The facility creation form doesn't validate the required fields before continuing to the next step.

https://github.com/learningequality/kolibri/assets/51239030/a178913e-6496-4505-8afc-7499d6c4c8d3

## Expected behavior

The form shouldn't continue to the next step if the facility name input is empty.

## User-facing consequences

Creating facilities with a empty string as names.

## Steps to reproduce

1. In the setup wizard, select use Kolibri as Group Learning.
2. Select full device setup.
3. Create a new learning facility.
4. Let empty the learning facility name.
5. Click on continue.

## Context

Kolibri version: Last version in develop
Operating system: Windows 10
Browser: Opera GX

**Comment by pcenov** [comment]
Hi @AlexVelezLl this is a known issue that should have been fixed by this PR: https://github.com/learningequality/kolibri/pull/11499

**Comment by AlexVelezLl** [comment]
Oh thanks @pcenov I hadn't seen it among the open issues, but it makes sense if it had just merged.
