### ISSUE TITLE
Initial channel on user homepage may not match the default language

### ISSUE THREAD

**Issue by Kevsy** [learningequality/kolibri#1153]
## Summary

The initial content selection shown to a user (in the main pane) may be in a different language to the portal default. In DRC the problem is that the language default is set to French, and the portal itself does indeed show French section headings, links etc - but the content selection displayed on login is all in Swahili. The user can change this using the top-right dropdown, but to avoid user confusion we need to be able to set the initial content selection offered to the user.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Vodafone 0.3 pex
 - Operating system: Ubuntu 14.04
 - Browser: Android, Chrome for Mobile

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. import KA Swahili and KA French channels
1. set the language default to fr-fr
1. login as a user, and the portal is in French, but the initial selected channel is in Swahili
![kolibri_langauge_issue](https://cloud.githubusercontent.com/assets/7903978/24411546/0e00ceee-13ce-11e7-814e-9619a4e129f7.png)

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Poor user experience, priority for DRC

*If applicable*

**Comment by indirectlylit** [comment]
requires some design. migrating to https://trello.com/c/NQtUUZPm/809-add-support-for-setting-default-channel
