### ISSUE TITLE
Facilites task manager not displaying task details

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11543]
## Observed behavior
Task data is not displayed, just the green checkmark 🙂 

Facility with a lot of tasks | Facility with less tasks
-- | --
![2023-11-17_13-25-09(1)](https://github.com/learningequality/kolibri/assets/1457929/812193d3-c6e3-4ab8-86cd-92eddf3e3875) | ![Selection_226](https://github.com/learningequality/kolibri/assets/1457929/ebf8db59-0881-441b-85cd-6ca797a84816)

The first image is from the facility that had a lot of syncing with LoDs, while the second is from another device where I imported the first facility in full.
 
## Errors and logs
None that I could see in the console

## Expected behavior
Proper detail about the past tasks should be available to the user.

## User-facing consequences
Inability to check the history of the facilities syncing tasks. UI seems broken.

## Steps to reproduce
Wait for some syncing tasks to be completed and check the Facilities task manager page.

## Context

 * Kolibri version: EXE asset from #11525 
 * Operating system: Windows 10
 * Browser: Firefox & Chrome

**Comment by GarvitSinghal47** [comment]
@radinamatic  I would like to work on this issue, can you assign it to me.

**Comment by MisRob** [comment]
Hi @GarvitSinghal47, this is very time sensitive as it's one of the last bugs blocking a new release. Generally, I'd rather recommend issues that are marked as suitable for contribution and aren't time sensitive. However, we're open to contributions to other issues as well, especially from experienced contributors.

If you already have an idea what's wrong and think you can have a pull request soon, I won't be preventing you from looking at this. However, you should know that it's possible that a core team member will need to tackle it and we won't be able to notify you when that happens exactly. You are generously volunteering your time an energy, and I don't want you to work under pressure or your work ending up in vain.

**Comment by MisRob** [comment]
@GarvitSinghal47 So this will be addressed by @bjester, but we figured out you can have a look at https://github.com/learningequality/kolibri/issues/11540 instead if you're interested

**Comment by MisRob** [comment]
@GarvitSinghal47 We assigned @thanksameeelian to the issue I recommended you (https://github.com/learningequality/kolibri/issues/11540) instead of this one. We will wait for a few days to see if you're interested in it and if yes, she won't work on it herself but rather support you if you needed anything.
