### ISSUE TITLE
Migrate Vuex exercise family tree counting to compisition API module

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11548]
## Overview

We need to enumerate resources that are descendants of topic nodes. For example, given 3 channels each which have 4 exercise resources, we need to say ["12 resources selected from 3 channels".](https://www.figma.com/file/wRlClsHgcVqIwgUrntRN1a/Kolibri-Enhanced-Quiz-Management?type=design&node-id=28-8895&mode=design&t=TF2JxLnbZ7LKj4kh-0)

The function in `kolibri/plugins/coach/assets/src/modules/examCreation/handlers.js` `showExamCreationTopicPage` is where this was done before. This fetches a topic and its children and then calls `filterAndAnnotateContentList` - which seems to be where the magic happens.

Note that the Vuex architecture largely relies on functions that return promises that return promises that return promises and so on. This is not really an approach suitable for use with the composition API so don't feel compelled to keep the structure of the old code that you encounter but focus instead on the functionality.

## Acceptance Criteria

- [x] Create a new `useExercises` module in the `coach` plugin to provide the following functionality

- [x] Expose a function that will provide the list of all exercise descendants for the given `topic_id`

- [x] Identify the ideal way for a composition API module to represent this state or to update this state. At this point, we need to be able to update the values whenever the topic_id changes elsewhere in the system -- so being able to update the new `useExercises` module's `topic_id` and then being able to rely on computed (or other) properties of that module's internal workings to reactively update some kind of state will be ideal.

**Comment by nandini584** [comment]
Heyy, I would like to work on this issue, would you please assign it to me?

**Comment by hustlernik** [comment]
@nucleogenesis, Can I work on this issue?

**Comment by nucleogenesis** [comment]
@nandini584 @hustlernik thank you for your interest! Unfortunately this issue is one that is dependent on some other ongoing work.

That said, we'd certainly appreciate your help on any of the issues listed with our [Help Wanted](https://github.com/learningequality/kolibri/labels/TAG%3A%20help%20wanted) or [Beginner Friendly](https://github.com/learningequality/kolibri/labels/TAG%3A%20beginner%20friendly) labels and will be glad to answer any questions you have for any of those which are currently unassigned.

**Comment by nandini584** [comment]
Sure.

**Comment by nucleogenesis** [comment]
Closed in #11682
