### ISSUE TITLE
Android LOD - A device with insufficient storage keeps downloading resources up to its limit and above

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11555]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/11552 - even though now the status of the Android device changes correctly to 'Not enough storage' initially the device keeps downloading more resources than the set limit of 1GB after which it proceeds with removing previously downloaded resources.

![2023-11-22_17-26-49](https://github.com/learningequality/kolibri/assets/79847249/35f106c6-f18e-4411-af82-1652ce50e0f3)

## Expected behavior

The current behavior is a bit confusing. No resources should be downloaded to the Android device if their size exceeds the set download limit.

## Steps to reproduce the issue
1. Install the [latest Beta 9 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9).
2. Setup a server device with learners and assigned lessons.
3. Setup an Android LOD and set the storage limit to 1GB.
4. Assign some lessons to the LOD to confirm it's syncing correctly.
5. Assign a large lesson with 1GB of resources to the LOD.
6. Observe that on the server side at Coach > Class home > View learners we are correctly indicating that the there is not enough storage on the device
7. On the Android device observe that it keeps downloading resources regardless of the fact that it's supposedly out of storage.

## Logs

https://drive.google.com/drive/folders/1yD0a_0ZrnGSlQ2cu_DBa3OcB7Na8ZHbw

## Usage Details
Ubuntu 22  - Chrome, Samsung phone Android 13

**Comment by pcenov** [comment]
@radinamatic @bjester

**Comment by bjester** [comment]
@pcenov If the storage status tracking is functioning properly, this is the expected behavior. It should predict that it doesn't have enough storage, sync that back but download as much content it can. So what was your indication that it `keeps downloading more resources than the set limit of 1GB`?

**Comment by pcenov** [comment]
@bjester If I remember correctly, on my device I had already downloaded resources and then it proceeded to fully download the entire lesson with assigned 1GB of resources so when looking at Device > Channels I could see that the total size of the channels was greater than 1GB. Let me know if there's a better way of knowing what exactly is the size of the downloaded content on the LOD and I can try to replicate with more details.

**Comment by bjester** [comment]
@pcenov So prior to the lesson, were the resources already downloaded via the learner download function? or were they downloaded via Device > Channels import?

**Comment by pcenov** [comment]
Hi @bjester yes, I had resources already auto-downloaded as part of some assigned lessons. Nevertheless, after additional testing today I can confirm that I was misled by a miscalculated actual size of one of the assigned lessons which was actually less than 1GB and therefore the total was less than 1GB. Closing this one and sorry for the false alarm!

**Comment by bjester** [comment]
@pcenov No worries! Glad we figured it out. Thank you for re-testing
