### ISSUE TITLE
 Device > Channels - Channel update process keeps failing

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11557]
## Observed behavior

Not sure whether this is on Studio's side or on Kolibri's but currently each time I attempt to update a channel I am getting 'Failed' in the task manager. I'm still able to manually import the new resources though.

https://github.com/learningequality/kolibri/assets/79847249/0edf83e5-1b76-451d-a369-4e3269cdea37

## Expected behavior

It should be possible to update a channel.

## Steps to reproduce the issue
1.  Install the [latest Beta 9 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9).
2. Create a new channel in Studio and import it in Kolibri.
3. In Studio add additional resources the the channel and publish it.
4. In Kolibri go to Device > Channels and attempt to update the channel so that the new resources will be downloaded as well.

## Logs

[UbuntuServerLogs.zip](https://github.com/learningequality/kolibri/files/13460303/UbuntuServerLogs.zip)

## Usage Details
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
@pcenov - is this something that seems to be newly broken with this most recent beta? (I am guessing yes or else there would have been an issue before, but asking just in case)

**Comment by pcenov** [comment]
Hi @marcellamaki - sorry but I can't say when this issue was introduced and I noticed it only as part of the integration testing on Beta 9.
