### ISSUE TITLE
Text for USB content import ('Local Drives') cut off

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1156]
## Summary

The text for importing content from a USB ('Local Drives') is cut off for French and Portuguese versions of Instant Schools installer.

## System information

*Please specify the Kolibri version you were using and your operating system!*

Version: Vodafone 0.3 pex
Operating system: Ubuntu 14.04
Browser: Android, Chrome for Mobile

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

Admin function --> Manage --> Content

## Screenshots

<img width="382" alt="screen_shot_2017-03-27_at_8 32 29_am" src="https://cloud.githubusercontent.com/assets/5150483/24427217/04c08482-13bf-11e7-8040-94a19dbf650b.png">

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

International deployments affected

**Comment by indirectlylit** [comment]
It's not actually cut off - the text actually has the "..." in it :)

```
"wizard-import-network.title":"Escolha uma fonte..."
```

**Comment by indirectlylit** [comment]
oops! missed the button

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri/commit/81efb1f6c0190590817c1420f47370c98c03283d
