### ISSUE TITLE
Use consistent KDS imports across the whole Kolibri

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11561]
There are currently two ways we import KDS (Kolibri Design System) logic (e.g. a component, a mixin, a composable) to Kolibri:

**(1) Via `kolibri.coreVue`**

First, a piece of KDS logic, in this example `UiIconButton`, is imported from `kolibri-design-system` and registered in [apiSpec.js
](https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js)

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js#L22

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js#L192

This makes it available in the whole Kolibri for import from `kolibri.coreVue`:

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/plugins/learn/assets/src/views/QuizRenderer/index.vue#L160

**(2) Directly**

The other approach imports a piece of KDS logic, in this example `UiAlert`, to a Kolibri component directly from the `kolibri-design-system` package:

https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/plugins/learn/assets/src/views/QuizRenderer/index.vue#L159

## Goal

The goal of this issue is to use approach (2) everywhere. Using direct imports from KDS will ensure consistency and make it clear where code is being imported from.

## Acceptance criteria

- [ ] All JavaScript `coreVue` imports for KDS are replaced by direct imports in all Kolibri files
- [ ] All related KDS logic is removed from `apiSpec.js`

## Out of scope

Note that we also use direct KDS styles imports, for example `@import '~kolibri-design-system/lib/styles/definitions';`. Dealing with these Sass imports is not in the scope of this issue and they can stay as are.

## Guidance

1. Search the codebase for [api spec `kolibri.coreVue` imports](https://github.com/search?q=repo%3Alearningequality%2Fkolibri+from+%27kolibri.coreVue&type=code)
2. If an imported piece of KDS logic is registered in `apiSpec.js`, remove it.
3. Replace the `coreVue` import with the direct import

**Comment by MisRob** [comment]
This issues is to target the `develop` branch

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.

**Comment by MisRob** [comment]
Hi @ShivangRawat30, thank you, I'm assigning you. Good luck and let us know if you needed anything.

**Comment by nucleogenesis** [comment]
I think maybe we should consider strongly replacing all uses of vendored code with KDS components directly. This would be a substantial amount of work, however, so could be created as a separate issue to be dealt with down the road as it would involve updating many places in Kolibri to import/use a new component.

**Comment by MisRob** [comment]
@nucleogenesis Yes, definitely. Even though I used vendored components as an example, this issue is more general and includes imports of regular KDS components as well. You can find cases where the same logic is imported in two different ways.

**Comment by MisRob** [comment]
@nucleogenesis And we'll be most likely tweaking location of composables one way or another too and those are regular KDS paths. So this will help in that case as well.

**Comment by MisRob** [comment]
@nucleogenesis I'm more than up to to not be reaching to vendored files directly eventually. Not sure what was the motivation for that.

**Comment by PR4NJ41** [comment]
@MisRob If No One is working on this issue anymore can i work on it ?? Please assign it to me and let me know. Thank You

**Comment by AlexVelezLl** [comment]
Hi @ShivangRawat30  are you still working on this issue? If there is anything we can help you with, let us know.

**Comment by PR4NJ41** [comment]
@AlexVelezLl @MisRob Could you please provide Slack Channel link where i can discuss GSOC related queries ?

**Comment by AlexVelezLl** [comment]
Hi @PR4NJ41! Sorry, we don't have a slack channel for GSoC 2024 yet, but please stay tuned for when we have everything ready =).

In the meantime, you can open new GH Discussions or use [this discussion](https://github.com/learningequality/kolibri/discussions/10691) for anything related to Kolibri.

**Comment by ShivangRawat30** [comment]
@AlexVelezLl I am currently working on an other issue, you can assign the issue to someone else in the mean time.

**Comment by AlexVelezLl** [comment]
Thanks @ShivangRawat30! @PR4NJ41 I just assigned it to you :raised_hands:

**Comment by PR4NJ41** [comment]
@AlexVelezLl Thanks for assigning me the issue. Just to confirm, i have to work on the `develop` branch, am i right?

**Comment by AlexVelezLl** [comment]
Hi @PR4NJ41! yes, you should work on they develop branch.

**Comment by PR4NJ41** [comment]
Hi @AlexVelezLl, I found 2 components named UiToolbar 

1. `import UiToolbar from '../views/KeenUiToolbar.vue';`
2. `import UiToolbar from 'kolibri-design-system/lib/keen/UiToolbar';`

The 1st one was already present in `apiSpec.js`

what should i do with the 2nd one?

**Comment by PR4NJ41** [comment]
This is in `apiSpec.js` file
https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/core-app/apiSpec.js#L127

This is the other file.
https://github.com/learningequality/kolibri/blob/4de6c2fbd8924b1ec82f9c8555ed9aedb772bb61/kolibri/core/assets/src/views/KeenUiToolbar.vue#L3

**Comment by AlexVelezLl** [comment]
Hi @PR4NJ41. Could you try replacing the places where the UiToolbar from `views/KeenUiToolbar.vue` is used to using the one from `kolibri-design-system/lib/keen/UiToolbar`? You can see if they have the same props and if they work the same, then you can replace them, and prefer to use the one from `kolibri-design-system/lib/keen/UiToolbar`.

If they are incompatible, let's leave the `views/KeenUiToolbar.vue` in the apiSpec for the moment, and we can later open a follow up issue to unify both of them.

**Comment by PR4NJ41** [comment]
Hi @AlexVelezLl, I replaced it. 

@MisRob @AlexVelezLl  I raised a PR please review it. Thank you

**Comment by rtibbles** [comment]
Sorry, I totally missed the content of this issue. This is entirely the wrong direction of travel, and we should be removing references to KDS in the core API spec, not adding them.

If import paths update in KDS that is a breaking change that should be documented, and then can quickly be addressed in the upgrade in Kolibri with a global find replace.

Apologies for the delay here, but I think I had seen the title and assumed it was about switching to direct imports from KDS and not this away around.

**Comment by PR4NJ41** [comment]
@rtibbles So do i have to remove Kolibri.coreVue.. used in files ?

**Comment by PR4NJ41** [comment]
Also, I ran `yarn run build` and `yarn run test` they were running fine.

**Comment by rtibbles** [comment]
Hi @PR4NJ41 - I think @MisRob and I need to discuss this further before I suggest next steps, and we are both out of the office until January. We will follow up then.

**Comment by PR4NJ41** [comment]
Ok, Thank You. I will try to fix other issues.

**Comment by indiansamaltman** [comment]
please notify when you create a slack channel @AlexVelezLl

**Comment by MisRob** [comment]
@rtibbles My main concern is consistency and am not very opinionated which direction we choose. This issue is a result of discussion with @AlexVelezLl during one of the reviews, where he mentioned that using core can prevent from replacing many imports in case we change them in KDS. I though that was a good argument and therefore leaned towards that direction.

However at that time, I didn't know of https://github.com/learningequality/kolibri/issues/5488 and the current organization seemed to indicate that it's a common practice to put KDS components to core. I assume that https://github.com/learningequality/kolibri/issues/5488 is the main reason you suggest taking the opposite approach? If that's so, I think it makes sense.

**Comment by rtibbles** [comment]
Yes, when I saw the title of the issue I had assumed it was just consistently not using the core imports, rather than the other way around!

#5488 is a response to the tendency towards extreme bloating of the core API that we have seen - KDS imports are a little bit different, inasmuch as we do bundle all of the KComponents into the core through the use of the plugin and global registration, but just importing directly from KDS means that we don't have to maintain as much in the core API, and can be easily updated with a find and replace, even if import paths change.

**Comment by rtibbles** [comment]
I have updated the issue to reflect the opposite direction here. @PR4NJ41, please feel free to resume this work if you are able!

**Comment by MisRob** [comment]
Okay, thanks for taking care to update the issue, @rtibbles.

@PR4NJ41 apologies for confusion and thanks for all your work.

**Comment by PR4NJ41** [comment]
@MisRob @rtibbles 
Please can you confirm which approach i have to follow now (Please refer to the Topmost part):

(1) Via kolibri.coreVue
(2) Directly

**Comment by PR4NJ41** [comment]
If we are using the 2nd approach then do i have to remove all imports which are using "kolibri.coreVue" or only certain ones.

**Comment by rtibbles** [comment]
Directly, so any imports for modules that we could import directly from KDS should be imported directly from KDS. Note that there are lots of other "kolibri.coreVue" imports that are not for KDS imports, so you can leave these as they are.

**Comment by vaibhav-rm** [comment]
I would like to help with this issue.

**Comment by PR4NJ41** [comment]
@vaibhav-rm I am already working on this

**Comment by vaibhav-rm** [comment]
> @vaibhav-rm I am already working on this

Okie, Let me know If I could be of any help.  Good luck.

**Comment by PR4NJ41** [comment]
@MisRob @rtibbles I've just raised another PR. I used `yarn run build` and `yarn run test` for testing.

Please review the changes.  I'm open to make further improvements if needed. 

Thank you!

**Comment by MisRob** [comment]
Thank you @PR4NJ41, we appreciate your flexibility and patience

**Comment by Abhinav1148** [comment]
@rtibbles, @MisRob, I've raised a PR for this issue. Please review it and please let me know if any changes are needed.
Thank you!!

**Comment by MisRob** [comment]
I'm sorry @Abhinav1148, but this has been already resolved here https://github.com/learningequality/kolibri/pull/11742 and will soon be merged. Please always check if there's already an asignee in an issue. If yes, than it's already taken. If no, send us a message a first and wait until we assign you.

**Comment by Abhinav1148** [comment]
I'm sorry @MisRob for this mistake, I'll take care of that from now onwards.

**Comment by MisRob** [comment]
No problem, I feel sorry this was your first experience! I just posted more information to your pull request :)

**Comment by rtibbles** [comment]
Fixed in #11742
