### ISSUE TITLE
Unwrapped strings on Vodafone Instant Schools 0.3.x

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1157]
## Summary

Unwrapped strings found and need translating.

## Screenshots
![image](https://cloud.githubusercontent.com/assets/5150483/24430484/a95b6ac8-13cb-11e7-81dc-e1ba35fda051.png)

![image](https://cloud.githubusercontent.com/assets/5150483/24430439/80970124-13cb-11e7-8b58-502b2170662e.png)

![image](https://cloud.githubusercontent.com/assets/5150483/24430381/19e7aba4-13cb-11e7-8d2b-91fa375b2280.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Urgent need for DRC rollouts

**Comment by indirectlylit** [comment]
These strings are all in the coach reports sections of the app. My understanding was that coach reports are not relevant to the VF roll-out?

**Comment by jeepurs** [comment]
@indirectlylit the third screenshot shows strings which are needed for administrators in general (i.e. the data export descriptions), but not critical for rollout.

**Comment by jeepurs** [comment]
Text for progress on exercises are not translated:
![image](https://cloud.githubusercontent.com/assets/5150483/24471882/6c701606-1478-11e7-9766-30c774f2925b.png)

**Comment by jeepurs** [comment]
Sections of the sign up page still in English: https://fr.instantschools.learningequality.org/user#/signup

**Comment by rtibbles** [comment]
Wrong repo.
