### ISSUE TITLE
Improve error management and allow the user to retry and report errors during "Setting Up Kolibri"

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11574]
## Observed behavior
When the user is on the "Setting Up Kolibri" page of the setup wizard, we do not have a good error management experience. 

In some instances, content syncing tasks begin running in the background once the user is imported from the facility, and this can create a lock on the database. 

In other cases, errors with the import itself (such as the issue Radina reported with the "on my own flow" on Android) do not have a clear step of what to do next. 

Finally, when there is an error screen on android, much of the text is cut off, making troubleshooting difficult.

## Errors and logs
UI example: 

<img src="https://github.com/learningequality/kolibri/assets/17235236/74bb169a-3154-4acc-8f29-9998d4851609" width="350">

## Expected behavior

- [ ] If we get an error back from the provision device endpoint, we should be able to retry, rather than the user getting stuck at the end of the setup wizard. 
- [ ] Other errors should also be better managed
- [ ] We should enhance our middleware to catch the 503 error, and manage that case, so that the user is able to retry.
- [ ] We should repurpose the generic "something went wrong" error message, which would allow the user to report the error, and would pop up the modal that properly displays the error text
- [ ] We should add a retry button 
- [ ] If the retry is unsuccessful, the user should be able to start over at the beginning of the setup wizard

**Comment by nucleogenesis** [comment]
@marcellamaki @rtibbles should this be in our backlog and targeted/prioritized for 0.16?

In any case I'd love to tackle this / clean up the mess I've made here and/or cohack w/ someone on it!

**Comment by pcenov** [comment]
Hi @marcellamaki while testing https://github.com/learningequality/kolibri/pull/11655 I was able to identify the following steps to reliably replicate the error mentioned here - it's caused by leftover data from the previous installation. 

Steps to replicate:

1. Install the Android app.
2. Go through the `On my own` flow.
3. Stop the app and uninstall it without clearing any of the app data or cache.
4. Install again the app and go through the `On my own` flow.

**Comment by marcellamaki** [comment]
Thank you @pcenov!
