### ISSUE TITLE
Setup Wizard - importing user from facility that doesn't require learner passwords

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#11605]
## Observed behavior
if progressing through the setup wizard: `Group-learning` > `LOD` > `Import one or more existing user accounts...` & the user selects a facility where learners are not required to have a password, the following `Import individual user accounts` page does not display a password field due to its conditional rendering. 

if user enters a username that **does not exist** within the selected facility, currently an error occurs that is not visible to users and keeps them from progressing further in the wizard. the error appears only in the console and doesn't seem to accurately reflect to the scenario that occurred, as the error details are `Password is required`, despite the password field not being available to the user.

## Errors and logs

![image](https://github.com/learningequality/kolibri/assets/43046460/105d4148-db8a-4cc4-b353-203446263d65)
![image](https://github.com/learningequality/kolibri/assets/43046460/93cb0fa6-c49d-4921-8470-4959a06a84c9)
![image](https://github.com/learningequality/kolibri/assets/43046460/024a81a1-96a3-45a6-946d-19e0bc1034cf)

[code for errors arising in this case was updated recently](https://github.com/learningequality/kolibri/pull/11541/files#diff-ba32c1a203321831f941bab48eb678f5b592af398c724fa48415375da15eacd1R52) in https://github.com/learningequality/kolibri/pull/11541

## Expected behavior

- **surfacing error to user**: currently if the user attempts to enter a non-existent username, a console error occurs but no error surfaced to the user and they remain on the page, inexplicably unable to progress. the user should be made aware of what problems are keeping them from progressing through setup. 

- **raising accurate error**:  currently the error that is raised if user enters a non-existent username, when investigated, has the detail `Password is required` - this message does not seem to accurately represent the scenario that has occurred, which is expected to be the detail that accompanies `error_constants.AUTHENTICATION_FAILED` (`"401 Client Error: Unauthorized for url:..."`)

- **handling legitimate non-learner cases**: if an extant **coach** or **admin** username is entered into the username field on the `Import individual user accounts` page, user should be prompted for that username's password as well - even if a facility does not require learner passwords, it still does require passwords for coach or admin users. in this case, raising the `Password is required` error could be appropriate but users also need guidance/a next step nudging them towards the `Use an admin account` link if the password text field is still not made available on the page.

## User-facing consequences
user gets "stuck" on `Import individual user accounts` page without any indication of what is wrong

## Steps to reproduce
- on/based off of release-v0.16.x branch
- fresh kolibri instance to trigger setup wizard
- `Group-learning` > `LOD` > `Import one or more existing user accounts...`
- connect to a facility in which **learner passwords are _not_ required**
- enter a non-existent username into the provided field & attempt to progress through the wizard
- see console for error details

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by bjester** [comment]
Hi @aarishshahmohsin, thank you for your interest. I don't think this one is suitable for development at the moment. I think we might need new user facing string to better inform the user on what they should do in this situation, which means we need to reprioritize this as well.

We currently have contributing opportunities in three repositories. You can see the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)

- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)

- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

**Comment by bjester** [comment]
For posterity:
In the setup wizard, we already know whether the facility requires a password for learners. We won't be able to provide information through the originating API on whether the learner exists or simply isn't a learner and needs to provide a password. So I think in this scenario we should inform the user to `Check the username or provide admin credentials instead`.

**Comment by nick2432** [comment]
can i work on this ?

**Comment by akolson** [comment]
Hi @nick2432! Based on @bjester's [above comment](https://github.com/learningequality/kolibri/issues/11605#issuecomment-1856709996), I don't think so, but @bjester should be able to respond if otherwise. 
Thanks again!
