### ISSUE TITLE
Account sign-up non-functional for online demo in non-english languages

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1161]
## Summary

Creating accounts is not possible for French and Portuguese VF online demos, e.g. https://fr.instantschools.learningequality.org/user#/signup 

## System information

*Please specify the Kolibri version you were using and your operating system!*

Version: Vodafone 0.3 pex
Operating system: Ubuntu 14.04
Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```

default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.enterName" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
2default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.name" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.enterPhoneNumber" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
2default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.phoneNumber" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.enterPassword" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
2default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.password" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.confirmPasswordPlaceholder" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
2default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.confirmPassword" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
default_frontend-0.3.0.js:194 [Vue Intl] Missing message: "signUpPage.termsAgreement" for locale: "fr-fr", using default message as fallback.
L @ default_frontend-0.3.0.js:194
instant_schools_user_module-0.3.0.js:4 Uncaught (in promise) TypeError: e.resource.collectionUrl is not a function
    at instant_schools_user_module-0.3.0.js:4
```
and in case I can't properly format text:

![image](https://cloud.githubusercontent.com/assets/5150483/24433532/49718ca6-13de-11e7-8e7e-c73e405da84a.png)

## How to reproduce

1. From main page, click on ''Create Account'
2. Enter in details for a new account
3. Click Finish

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Critical for DRC rollout!

**Comment by jeepurs** [comment]
@indirectlylit Let me know if you need screenshots for the Portuguese console.  They report the same messages.

**Comment by indirectlylit** [comment]
so far, not able to reproduce locally

**Comment by indirectlylit** [comment]
URL where this is happening: https://fr.instantschools.learningequality.org/user#/signup (also at all other languages except English)

Still cannot reproduce locally on either the `master` branch (which should be what's running there) or the latest `0.3.x`.

the resource name in question is `kolibri:user:phonesignup` and the collectionUrl attribute is `undefined`:

![image](https://cloud.githubusercontent.com/assets/2367265/24439272/11ba454a-1402-11e7-9955-9b676b152bcd.png)

cc @aronasorman @rtibbles

**Comment by indirectlylit** [comment]
It looks like `kolibri:user:phonesignup` exists in the django reversal URLs list when I run locally, but it does not exist on the current demo server.

**Comment by jonboiser** [comment]
The TypeError in the screenshot is saying that `e.resource.collectionUrl` is not a function, which is true. It's a getter, so should be accessed without the `parens`

http://github.com/jonboiser/kolibri/blob/aac88844081355c7b36e66f4e5162908ca03ac28/kolibri/core/assets/src/api-resource.js#L567

```diff
- a = e.resource.collectionUrl()
+ a = e.resource.collectionUrl // => still undefined
```

I don't know if it being undefined is a problem, but the type mismatch is the main cause of the crash. Does the code not enter this branch normally (when `this.id` is falsy) at this line:

http://github.com/jonboiser/kolibri/blob/aac88844081355c7b36e66f4e5162908ca03ac28/kolibri/core/assets/src/api-resource.js#L114

**Comment by indirectlylit** [comment]
cc @rtibbles - could possibly use your eyes on this one

**Comment by rtibbles** [comment]
@jonboiser It is a getter, but the getter returns a function that then is immediately invoked. So, it's the fact that it is undefined that is the issue.

This is almost certainly happening because the URL is not being properly defined somehow - it is not matching whatever is recorded in the Django JS Reverse URLs object that we are using to access the collectionUrl.

**Comment by rtibbles** [comment]
For the instant schools demo servers that have a default language set, the URL for `phonesignup` API endpoint is not put into the frontend by Django JS reverse. When I tested it, it seems that the URL is present in the Django urlconf for the server, but is not being put into the frontend.

Possible reasons:

something about the URL is making it not get put into the frontend by Django JS Reverse (it has an assigned `basename` https://github.com/fle-internal/kolibri-instant-schools-plugin/blob/master/kolibri_instant_schools_plugin/api_urls.py#L7 - which is one case where this can not happen, I don't know of any others).

something to do with caching - this is currently cached, so if there is any shared cache between the different instances of the demo server running, then the cached reversejs block from the vanilla Kolibri could be affecting the language specific ones (seems unlikely, as why wouldn't the English instant schools be affected).

Something to do with the language setting - this seems to be the common factor.

Something to do with the way the servers are invoked - the English instant schools demo server is invoked with a slightly different script (although, on the surface, they seem to have identical function) from the language specific ones.

**Comment by aronasorman** [comment]
Immediately managed to replicate this by:

- creating a fresh Ubuntu 16.04 Vagrant VM, copying `run_kolibri_fr.sh` and `/var/www/kolibri-v0.3.1-beta3-instantschools.pex` to my local machine, then adding those to the VM.
- forwarded the VM's port `9090` to the host port `9090`.
- added both those files to `/var/www`, then ran `run_kolibri_fr.sh` as `www-data`.

No Nginx proxy in front.

This for me discounts a caching issue -- there's only one kolibri running on my VM right now, and it showed up on the very first testing, meaning no server-side caching has happened in the first place.

I'll try to start the English server using a similar script to `run_kolibri_fr.sh`, and see if we can replicate it in that language as well.

**Comment by aronasorman** [comment]
Can also replicate it on the english demo server -- so it might be how we start it, or something inherent to our pex file assets.

**Comment by rtibbles** [comment]
But I wasn't getting it on the remote English server, which was using the same pex file, I think? It just had a different startup script (which seemed identical in function, but different in precise implementation).

**Comment by aronasorman** [comment]
Heh. Actually, it looks like they are different versions:

```
# kolibri.pex is run by the english server
aron@kolibridemo:/var/www$ python kolibri.pex --version
0.3.0

# kolibri-beta3 is run by the non-english servers
aron@kolibridemo:/var/www$ python kolibri-v0.3.1-beta3-instantschools.pex --version
0.3.1beta3
```

**Comment by rtibbles** [comment]
Ruh roh.

**Comment by aronasorman** [comment]
Since I'm guessing people haven't managed to replicate this using the exact same pex file, it might be an issue that shows up in the specific production environment. Do you think that's the case @rtibbles?

If that's so, then then it might be the difference between Ubuntu's server version and Ubuntu's desktop version (which some Kolibri devs have been looking at).

**Comment by rtibbles** [comment]
Might just be this particular pex file in the production environment then?

**Comment by rtibbles** [comment]
I can double check locally with the pex file that is problematic also.

**Comment by aronasorman** [comment]
For reference: here's the pex file that's in production servers right now: https://slack-files.com/T0KT5DC58-F59SLLQ2D-b4b6659f84

**Comment by rtibbles** [comment]
Replicated locally, even with the phone hashing settings activated. I think there is something fishy with this pex file.

**Comment by aronasorman** [comment]
It turns out that we forgot to turn off the `user` plugin when we activated the `kolibri_instant_schools` plugin. Made the fix on the production server.
