### ISSUE TITLE
Share open-source community Slack notifications action to Studio and KDS

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11619]
As soon as we confirm that https://github.com/learningequality/kolibri/issues/9521 works as expected for Kolibri repository, it needs to be shared for Studio and Kolibri Design System repositories as well. I believe this can be achieved by utilizing [learningequality/.github](https://github.com/learningequality/.github) repository.

**Comment by MisRob** [comment]
> I believe this can be achieved by utilizing [learningequality/.github](https://github.com/learningequality/.github) repository

@rtibbles is that right?

**Comment by rtibbles** [comment]
We can create shared actions in that repository - we might still need to do some work in each repo to setup the action specifically.

**Comment by testingslacknotif** [comment]
testing slack notif with this comment, will delete.

- vkweb sending this.

**Comment by testingslacknotif** [comment]
testing slack notif with this comment, will delete.

- vkweb sending this.

**Comment by testingslacknotif** [comment]
testing slack notif with this comment, will delete.

- vkweb sending this.

**Comment by testingslacknotif** [comment]
testing slack notif with this comment, will delete.
00123.
- vkweb sending this.

**Comment by vkWeb** [comment]
This is done. Hence, closing.
