### ISSUE TITLE
Class activity loading inconsistencies

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11613]
## Observed behavior
Two issues are observed:
* <kbd>VIEW ALL</kbd> button often seems unresponsive, and only the page reload actually manages to open the ``/home/activity`` page
* Once the full activity page is opened, it sort of _flickers_ displaying past states for short bursts before the current one, and if the coach user returns to Class home, the panel with Class activity is again displaying the different state than what they saw on the **all** activity page. Gives a very inconsistent experience which does not inspire confidence.

1 | 2 | 3
-- | -- | --
https://github.com/learningequality/kolibri/assets/1457929/7eb6cb4b-d8ca-4d85-9a4b-b9e97009a73e | https://github.com/learningequality/kolibri/assets/1457929/5df65923-dbd5-4d5b-a8e5-ee24404a5994 | https://github.com/learningequality/kolibri/assets/1457929/ed0e802c-6c3e-4896-80ae-c246787df728

## Errors and logs
None observed in the network tab or the console.

## Expected behavior
The activity state (list) should be consistent between what is displayed in the **Class activity** panel on the Class home, and the full **Activity** page.

## User-facing consequences
Coach frustration and the lack of confidence in the learners' activity Kolibri is supposed to display to support tracking of their progress. 

## Steps to reproduce
* You'll need to observe the progress of ideally 2 LoDs as they sync with the server.
* Pay attention on the list in the **Class activity** panel.
* Try to open the **Activity** page and observe the difference in the list displayed there.

## Context

 * Kolibri version: 0.16b9
 * Operating system: Windows 11
 * Browser: both Firefox & Chrome

**Comment by KshitijThareja** [comment]
Hi @radinamatic. I'd like to give this issue a try. Could you please assign it to me?

**Comment by KshitijThareja** [comment]
@radinamatic I tried to replicate this issue in my system. But the `VIEW ALL` button click action and the loading of information in the `class activity` page seemed to be pretty much consistent to me. Is the error OS specific? I am running a linux distro.

**Comment by radinamatic** [comment]
@KshitijThareja - thanks for your interest in contributing to Kolibri! 

This issue is probably best suited for someone from our team who has the dev environment configured with more than one learn-only device already syncing.

To find issues that welcome community contributions, look for unassigned issues with the "help wanted" tag. You can also visit our [Github discussions page](https://github.com/learningequality/kolibri/discussions) for more information about open source contributions.

**Comment by KshitijThareja** [comment]
Sure @radinamatic, I'll look for some other issues.
Thanks  :)
