### ISSUE TITLE
The 'Welcome' modal is still being shown in LODs and normal devices if there are no imported channels

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11644]
## Observed behavior
While regression testing https://github.com/learningequality/kolibri/pull/11587 I noticed that the 'Welcome' modal is still being shown in LODs and normal devices if there are no imported channels.

https://github.com/learningequality/kolibri/assets/79847249/db7d58c8-0e2e-4075-8405-b16354e60b41

## Expected behavior

The 'Welcome modal' should never be displayed in LODs. For normal devices it should only be displayed once to the user and not be displayed in subsequent sign-ins with the same or a different browser. 

## Steps to reproduce the issue

1. Install the [latest Beta 9 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9).
2. Create a full facility and sign in.
3. Observe that the 'Welcome modal' is displayed correctly at the Library page or at Device > Channels.
4. Open a new browser window and sign in. Going to the Library page or at Device > Channels results in the modal being shown.
5. If you install the Android app and sign in as a LOD user the modal will also be displayed when there are no imported channels.

## Usage Details
[Beta 9](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9)
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by ThEditor** [comment]
I looked into it a bit and it seems like `welcomeDismissalKey` is stored in session storage of the browser and hence, when using a new browser (or clearing site data) the welcome modal comes up again. This might just be expected behaviour? I'm not sure.

Though if the welcome modal needs to stay hidden across devices (or browsers), it'll require storing this key to the account instead.

**Comment by ozer550** [comment]
Hi @ThEditor, Thanks for looking into this, we have already made some progress with this issue, to refer [pr-11449 ](https://github.com/learningequality/kolibri/pull/11449), [pr-11492](https://github.com/learningequality/kolibri/pull/11492), [pr-11587](https://github.com/learningequality/kolibri/pull/11587). We indeed are now using the local storage!

**Comment by rtibbles** [comment]
> For normal devices it should only be displayed once to the user and not be displayed in subsequent sign-ins with the same or a different browser.

Flagging that persisting this information across browsers would require a large technical investment for little pay off, so we should instead be aiming for:

> For normal devices it should only be displayed once to the user and not be displayed in subsequent sign-ins with the same browser.
