### ISSUE TITLE
Device > Channels - The 'Enter channel token' modal doesn't disappear when importing a channel collection

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11647]
## Observed behavior

The 'Enter channel token' doesn't disappear when importing a channel collection. If I manually refresh the page I am able to proceed with the import of the channel collection.

https://github.com/learningequality/kolibri/assets/79847249/f0162f70-6948-434d-9d02-7f570e572b78

## Expected behavior

The 'Enter channel token' modal should disappear so that the user can proceed with the import. This is working correctly in Kolibri 0.15.12 and is a regression in 0.16.

## Steps to reproduce the issue

1. Install the [latest Beta 10 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta10).
2. Create a full facility and sign in.
3. Go to Device > Channels and attempt to import a channel collection, for example by using the following token: `latuk-noriz`

## Usage Details
[Beta 10](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta10)
Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Just for clarification, it is a regression from 0.15.12, but not introduced in Beta10, probably much earlier. I was testing a collection this morning after a long time, bumped into this and asked @pcenov to confirm on his end.
