### ISSUE TITLE
Ensure that card grid on the Library, Explore Libraries, and Topics pages is the right max size

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11653]
## Observed behavior
There are some inconsistencies between the card grid widths on the Library, Explore Libraries, and Topics pages. 

## Expected behavior
On ultrawide screens, card grids across pages should extend up to, but not past, `1700px`.

## Steps to reproduce
1. Use an ultrawide screen, or stretch your browser window to reach ~ 2000px 
2. Observe the card layout
3. Is there a max-width set of `1700px`? 

We have _many_ child grid components, and to minimize confusion and maximize efficiency, this bug should be resolved at the page level whenever possible, by setting a max-width on the child grid components in the page, rather than on each of the grid components themselves. 

## Acceptance Criteria

The card grids go up to, but not past `1700px` in each of the following scenarios

### Library page 
_Fixed in #11665 thanks @iskipu_
- [x] Channels
- [x] Recent
- [x] Explore Libraries Section Preview (requires being signed in as an admin) 
- [x] Search results

### Topic/Channel View 
(Library > [click on a channel card for a **locally imported channel** at the top of the page])
_Fixed in #11515_
- [x] Main view 
- [x] search results

### Explore Libraries main view 
(requires being signed in as an admin; navigate via Library > Explore Button in the "Explore Libraries" section)
_Fixed in #11665 thanks @iskipu_
- [x] Main Page
- [x] Individual Library (i.e. click on one card) 
- [x] Search results

**Comment by nikkuAg** [comment]
Hey is this issue still open? I would like to work on this

**Comment by iskipu** [comment]
> Hey is this issue still open? I would like to work on this

Hi @nikkuAg 

i don't find any issue with Topic/Channel View and Explore Libraries main view ( [refer the comment](https://github.com/learningequality/kolibri/pull/11665#issuecomment-1867905056) ) let me know if i am missing something

**Comment by AlexVelezLl** [comment]
Hi @iskipu. I can see that the issue has been solved for the library and explore pages, but I found that when we go to a Topic/Channel View, the grid does not have a maximum width of 1700.

![image](https://github.com/learningequality/kolibri/assets/51239030/70ff4e22-8981-4399-a676-1d4ccbfc2397)

I have updated the issue with the completed tasks.

Would you like to take a look at it @iskipu? :smiley:. Or can I assign the issue to @nikkuAg :open_hands:.

**Comment by iskipu** [comment]
Hi @AlexVelezLl i dont have my laptop with me as i am out of station, but as far as i remember the grid (div which is flexbox i.e the div containing the cards) has max width of 1700 i believe the screen shot which u shared is the parent div of the flexbox div i was talking about.

If i am wrong u can assign this to @nikkuAg as i will not be having access to my laptop till jan 2nd.

**Comment by AlexVelezLl** [comment]
Oh, no rush! Enjoy the holidays! :open_hands: I'll leave the issue unassigned for whoever can review it first. Hope you have a happy new year!

**Comment by iskipu** [comment]
> the grid does not have a maximum width of 1700

Hi @AlexVelezLl,

![image](https://github.com/learningequality/kolibri/assets/143542192/f37316cf-ab31-46c0-bc76-7935c5988fe2)

the grid does have a maximum width of 1700px in Topic/Channel View.

**Comment by AlexVelezLl** [comment]
Oh thanks @iskipu, it was my bad, I wasnt selecting the grid div but its parent. I just checked it again and yes, it already has the max-width set :smiley:. Thank you!

**Comment by iskipu** [comment]
Hi @marcellamaki, i think all the issues mentioned are resolved is there any specific reason why this issue is still open ?

**Comment by marcellamaki** [comment]
@iskipu - no, it's just open because I forgot to close it out. Thanks for checking!
