### ISSUE TITLE
PDF Pages height are not rendering dynamically

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri#11663]
## Observed behavior

Issue observed while testing #11145.

When a PDF is rendered, the height of the first page to be rendered is used, and this height is used for all other pages. The problem is if there are PDFs that have pages with different heights, for example, if there are some pages in landscape and others in portrait.

When a landscape page is the first page to be rendered, the portrait pages overflows its height and renders on top of the following page:
![image](https://github.com/learningequality/kolibri/assets/51239030/fa02d1da-ddb9-4053-8a60-66170632d49e)

When a portrait page is the the first page to be rendered, the landscape pages present a big gap between them and the following pages:
![image](https://github.com/learningequality/kolibri/assets/51239030/d26af3d1-89a6-4aa0-9dcf-5515d73a5d57)

This issue is because we use a [virtual list for rendering the pages list](https://github.com/learningequality/kolibri/blob/2722f72b6b2758fb0e4721f84551ec08a90b925f/kolibri/plugins/pdf_viewer/assets/src/views/PdfRendererIndex.vue#L87) and render the pdf pages on demand. But this component renders a fixed-size list, which takes the same height for every list item.
 

## Expected behavior

The PDF Renderer list should render a dynamic-size virtual list. We can do this by keeping the `vue-virtual-scroller` library or installing a new library that allows dynamic-size virtual lists. 

## Steps to reproduce

Import the Kolibri QA channel (import token nakav-mafak), and open the "PDF page orientation" resource.

**Comment by marcellamaki** [comment]
Completing the upgrade to Vue virtual scroller 1.1.2 and using the DynamicList and DynamicListItem components that support dynamic sizing would probably be the best approach for resolving this

**Comment by AlexVelezLl** [comment]
I had completely forgotten that I had a PR draft to update vue-virtual-scroller :sweat_smile:, I'll take a look at that!

**Comment by marcellamaki** [comment]
I had forgotten too!! 😄 Great. No rush on this though :) if you'd like something to work on through the end of the year and this seems fun - it would be great for you to work on. But if you have other things to do that you'd rather focus on, that's okay too. We might be able to get this into one of our planned patches for 0.16.x though, which would be great. Thanks, @AlexVelezLl !

**Comment by ThEditor** [comment]
I've looked into this a bit and noticed that the migration from `RecycleList` (v0.12.0) to `RecycleScroller` (v1.1.2) has not been completed yet. I've got `RecycleScroller` to work locally and might be able to get `DynamicScroller` to work too.
I was wondering if I should look into it further and maybe draft a PR? @AlexVelezLl @marcellamaki

**Comment by AlexVelezLl** [comment]
Hi @ThEditor! Sure, you can! I remember that the migration to vue-scroller 1.1.2 had some minor issues that needed to be resolved. But if you already tried it and were able to run it locally, then cool! You're welcome to pen a PR :open_hands:

**Comment by ThEditor** [comment]
Alright, thanks! I've drafted a PR #11671 . Currently I've done some code changes to upgrade to vue-virtual-scroller `v1.1.2` using `RecycleScroller`. I'll try to look into implementing `DynamicScroller`.

**Comment by ThEditor** [comment]
I think I might've found a solution for `DynamicScroller`, however, I don't have a pdf to test these against. I tried visiting the ones mentioned in #11145 , however, I'm encountering "resource not found". Is there any other pdf content I can use for testing?

**Comment by AlexVelezLl** [comment]
Yes @ThEditor , you can import our QA channel as explained in [this comment](https://github.com/learningequality/kolibri/issues/11145#issuecomment-1803740986). Let me know if you have any issue!

**Comment by ThEditor** [comment]
So, I imported the pdfs and the height issue seems to be fixed. Though there are two issues that still need to be addressed
- Fit to width: I'm not sure how we're planning to do this, a fit to width button might just be the solution? Is that what we will be going with?
- ~Loaded pages: From what I can understand, the latest commit in my PR isn't pre-loading pages before and after the current page. I think I might have to look at the `buffer` property provided by vue-virtual-scroller for this.~

**Comment by AlexVelezLl** [comment]
Oh, no, that is out of scope. This issue was just to render dynamic sizing virtual list for PDF Renderer :smile:

**Comment by ThEditor** [comment]
alright then, I've opened the PR #11671 for review, thanks!

**Comment by AlexVelezLl** [comment]
Perfect! Ill take a look in the afternoon. For now, can you please add some preview images?

**Comment by ThEditor** [comment]
I wasn't active when you mentioned me, apologies. I've added a preview video to PR. That should be alright I suppose?

**Comment by AlexVelezLl** [comment]
Oh, there's nothing to apologize for, take your time. We all have our things to do and you are taking a little of your time to help us! So thank you for that! :open_hands:  No rush =)


> That should be alright I suppose?

Yes! That's it.

**Comment by AlexVelezLl** [comment]
Solved in #11671
