### ISSUE TITLE
Replace all uses of isEmbeddedWebView with isAppContext

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11689]
## Observed behavior
Our embedded webview sniffing is susceptible to failure if we have not preconfigured the webview from within Kolibri. Instead, we should use isAppContext to flag whether we are in an app context or not.

## Completion criteria

- [x] Add an isAppContext computed property to the core useUser composable
- [x] Replace every instance of isEmbeddedWebView with the isAppContext computed prop (when this is used in a component, this should be consumed and exposed via the component setup method, otherwise it can be called in module scope).
- [x] Delete unused isEmbeddedWebView and the constituent values from browserInfo.js

Will resolve any future issues similar to: https://github.com/learningequality/kolibri/issues/7767

**Comment by ThEditor** [comment]
I looked into this a bit and I wasn't very sure of what changes I needed to make (and how). Hence, I am not opening a PR yet, however, you can check the code changes I made [here](https://github.com/learningequality/kolibri/compare/develop...ThEditor:kolibri:appcontext?expand=1). Please let me know if this is right.

**Comment by rtibbles** [comment]
Hi @ThEditor - looks like this has already been assigned to @AllanOXDi, I'll remove the help wanted label.

**Comment by rtibbles** [comment]
That said - your addition of the composable is correct, but then you are still using the getter rather than the composable to access the value.

**Comment by rtibbles** [comment]
@AllanOXDi will take it from here!

**Comment by rtibbles** [comment]
Fixed in #11715
