### ISSUE TITLE
Remove unnecessary use of the core Kolibri store in tests

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11725]
When custom theming was first introduced to Kolibri, the theming state was made reactive by adding it to the core Vuex state.

This necessitated many component oriented frontend tests to inject the store into their tests in order to have the Vuex state available and prevent errors.

Since this happened, the reactive theming state has been extracted from Vuex and now lives independently. Therefore, injecting the store into these component tests is no longer needed.

```[tasklist]
### Acceptance Criteria
- [ ] Find all instances of `kolibri.coreVue.vuex.store` imports in Javascript test files
- [ ] In cases where the store is just injected as is into the component, and nothing in the component relies on any vuex state, remove the import and the injection, and ensure the test still passes.
```

For a starting point, many of the affected spec files were originally edited in this commit: https://github.com/learningequality/kolibri/pull/4587/commits/69856a15e321b0c977b29fc0474703d2521bdb13 but there may be others, or those files may have moved since!

**Comment by vaibhav-rm** [comment]
Can I work on this?

**Comment by LianaHarris360** [comment]
Hi @vaibhav-rm yes, I will assign you to this issue. Please reach out if you have any questions!

**Comment by adadgarg** [comment]
Hi @vaibhav-rm I have almost solved this issue,if you don't mind can i raise a PR.

**Comment by vaibhav-rm** [comment]
>  Hi @vaibhav-rm I have almost solved this issue,if you don't mind can i raise a PR.

Sure

**Comment by MisRob** [comment]
@adityagarg06 and @vaibhav-rm Thanks both. @adityagarg06 kindly request you ask for an assignment of an issue and wait to be assigned next time, especially when someone has been assigned previously. Please have a look [at the contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md).

**Comment by nick2432** [comment]
can i work on this?

**Comment by MisRob** [comment]
It seems no one is working on it now, so I think it's good to go @nick2432. Thank you.

**Comment by nick2432** [comment]
Hey @rtibbles , I'm raising a PR. Am I on the correct path?

**Comment by rtibbles** [comment]
I will take a look, thanks!
