### ISSUE TITLE
Create equivalent of getters for all accessed session state and all getters in useUser composable

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11723]
We currently have multiple getters and even some state in the [session.js Vuex module](https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/state/modules/session.js) that is accessed throughout Kolibri. 

We have started migrating these references to instead use the [useUser core composable](https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/assets/src/composables/useUser.js), but the composable still does not expose all the needed getters and state that are referenced across Kolibri.

To remedy this, all the getters that are defined in the session.js module should be exposed through the useUser composable in a similar way to those that have already been wrapped.

In addition, all state in the session module should be exposed for consumption via the composable as well.

**Comment by dhruvpal05** [comment]
Hey @rtibbles, I can work on this issue, please assign me this issue

**Comment by rtibbles** [comment]
Sure thing!

**Comment by dhruvpal05** [comment]
Hey @rtibbles, just created a PR for this #11738 , do review

**Comment by rtibbles** [comment]
I have reviewed, @dhruvpal05 - thanks for your efforts, but you seem to have misunderstood the issue. Please feel free to ask further clarifying questions on my review.

**Comment by Wck-iipi** [comment]
I would like to work on this issue @rtibbles

**Comment by rtibbles** [comment]
Hi @Wck-iipi, I assigned you to another issue recently, please finish the fix for that, and then we can revisit this.

**Comment by rtibbles** [comment]
Ah, apologies, I see you've submitted a PR for that issue already! I'll assign you here.
