### ISSUE TITLE
Make the AppBarPage self populate the top nav, based on registered navigation items in in navComponents.js

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11731]
We currently duplicate our specification of navigation items within Kolibri Single Page Apps. Firstly, they are specified in a top nav bar component on a per app basis, which is used to populate the top navigation.

Addtionally, the side navigation specifies not just the top level navigation item, but also all the side navigation items, which are identical to the top navigation items.

To resolve this, we should update the AppBarPage component, or potentially the HorizontalNavBarWithOverflow component, to populate the navigation automatically based on registered items in the navComponents.js

```[tasklist]
### Acceptance Criteria
- [ ] Merge the NavBar component into the HorizontalNavBarWithOverflow component, as it is used nowhere else.
- [ ] Retain the simpler 'NavBar' name - add code comments to describe the amazing overflow behaviour
- [ ] Autopopulate nav bar items in this component based on items that are registered in navComponent.js
- [ ] To accomplish this, refactor the nav-components.js mixin, into a composable that can be reused as needed.
- [ ] This will probably involve moving some computed props from SideNav into the new composable to reuse them - these may be defined in the module scope, as they can be global state, and do not need to be independent
- [ ] Remove all explicitly defined nav bars in each of the SPAs
- [ ] Remove the NavBar and NavBarItem components from the core API
```

**Comment by dhruvpal05** [comment]
I can work on this issue , please assign me this

**Comment by rtibbles** [comment]
Hi @dhruvpal05 - this has some intersections with other work, so I didn't want this to be worked on just yet. Please have a look for issues with the `help wanted` label, which are more amenable for contribution!
