### ISSUE TITLE
Coach routing: Flash of white on every route navigation in Quiz Creation

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11732]
## Overview

There are some known issues in Coach (see: #11219 #11422 and issues referenced therein) with the routing handlers. This is resulting in the entire page flashing every time a user changes the route within the new quiz creation application.

This is an undesirable user experience as the process of creating a quiz should feel like a cohesive and immersive process but the screen flashing white when opening the side panel to select/replace content or to edit the current section or to change which section is being edited results in a disjointed UX.

## Guidance & notes

[This](https://github.com/learningequality/kolibri/blob/878d2461809636a8f1dbdc7e88ad3acf6bbaf73a/kolibri/plugins/coach/assets/src/app.js#L32) `beforeEach` call in the coach `app.js` is almost certainly the cause of the issue.

In order to avoid regressions, it would probably be best to conditionalize the call to set the loading state there to only do so if/when we're not using any of the routes that include [these page names](https://github.com/learningequality/kolibri/blob/7033034cdeefde45ef9ccdc47e566c104a46ec0d/kolibri/plugins/coach/assets/src/constants/index.js#L15-L21). This is similar to the conditionalized dispatch of `coachNotifications/stopPolling` defined [here](https://github.com/learningequality/kolibri/blob/878d2461809636a8f1dbdc7e88ad3acf6bbaf73a/kolibri/plugins/coach/assets/src/app.js#L43)

## Acceptance criteria

- [ ] When the user opens a side panel, changes sections, etc, the screen does not flash.

- [ ] The changes made here do not affect any page except for the quiz creation page (**Note for QA: This means there should be no regressions in Coach Reports or Lessons, but this is not going to resolve or close the issues linked above)

**Comment by akolson** [comment]
I agree with @nucleogenesis about. This is a major culprit. 
> [This](https://github.com/learningequality/kolibri/blob/878d2461809636a8f1dbdc7e88ad3acf6bbaf73a/kolibri/plugins/coach/assets/src/app.js#L32) beforeEach call in the coach app.js is almost certainly the cause of the issue.
