### ISSUE TITLE
progress values returned from API are sometimes null

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1175]
A work-around was committed here: https://github.com/learningequality/kolibri/pull/1163/commits/a54306beb334ab28c38497c6684871c78f45c060

We should identify the root cause and remove the work-around such that `progress` always has a defined value.

**Comment by rtibbles** [comment]
This is the only place where a null value can still potentially be returned: https://github.com/learningequality/kolibri/blob/develop/kolibri/content/serializers.py#L74

**Comment by rtibbles** [comment]
Sorry, misread this issue. Having trouble understanding how progress values on the session and summary logs ever returned null, as they default to zero.
