### ISSUE TITLE
Setup Wizard - Broken facility/LOD import

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11763]
## Observed behavior

Currently both the import of a facility or the import/creation of LOD are not working (getting a `http://127.0.0.1:8080/api/device/deviceprovision/ 400 (Bad Request)` error in the console). 
This issue was initially observed by @radinamatic while regression testing https://github.com/learningequality/kolibri/pull/11756 and the [latest Beta 11](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta11).

https://github.com/learningequality/kolibri/assets/79847249/7c93f1b7-f11a-4ac4-92db-45a5bb1e07d5

## Expected behavior

Fully functional full facility import and import/creation of a LOD.

## Steps to reproduce the issue

1. Install the [latest Beta 11 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta11).
2. Setup a server device with created users.
3. On a different device start the Setup Wizard and go through the workflows for importing a full facility or importing/creating a learn-only device.

## Logs

[UbuntuDevice.zip](https://github.com/learningequality/kolibri/files/14010143/UbuntuDevice.zip)
[WindowsServer.zip](https://github.com/learningequality/kolibri/files/14010144/WindowsServer.zip)
[Error details.txt](https://github.com/learningequality/kolibri/files/14010159/Error.details.txt)

## Usage Details
[Beta 11](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta11)
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nick2432** [comment]
Can i work on this?

**Comment by bjester** [comment]
@nick2432 As this is a high priority, critical issue with regards to our Kolibri 0.16 release, it isn't suitable for contributors. Thank you for interest though!
