### ISSUE TITLE
On os_user sign-in, unnecessary password field can temporarily appear

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11777]
## Observed behavior
There are two possible sign in flows - one is the regular username and password flow, and one is where the operating system user is used to create a Kolibri account within setup. 

If multiple accounts are created on the same device and kolibri installation, with different setup options, there is a scenario where a user signing in using the operating system user can briefly see a password field which is not required for them to sign in. This is a frontend state management/loading state issue (~1 second of intermediate state), and the sign in works as expected following https://github.com/learningequality/kolibri/pull/11754

## Errors and logs

https://github.com/learningequality/kolibri/assets/17235236/dfd36144-974f-48a3-a9b3-65ed220f6b56

## Expected behavior
For an optimal user experience, this would be properly managed in the front end, and the `os_user` workflow would not see the password field.

## User-facing consequences
Users may think they need to enter a password, or try to enter one, which could result in confusion or further errors. 

## Steps to reproduce
1. Running Kolibri locally *[*not** in app_mode](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode), create a user with a password (let's call this "pw_user")
2. Stop your Kolibri server, but maintain the same `KOLIBRI_HOME` folder
3. Run Kolibri locally using (https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode). (let's call this "os_user")
4. Sign out. You should now see both "pw_user" and "os_user" available to select in the sign in page
7. Select "pw_user". You should be directed to the next step, where you enter your password. Do not sign in. Go back via "Change User"
8. Select "os_user". You should briefly see the password field appear (the same as before) but then be properly logged in and redirected into Kolibri after ~1 second, without needing to enter a password.

## Context
0.16.x
Mac ventura 13

**Comment by shivansh-bhatnagar18** [comment]
Dear Authors, Please Assign me this issue. I would love to work

**Comment by ThEditor** [comment]
The solution was a one-liner change to `clearUser`, hence I created a pull request directly. Please review it and let me know, thanks!

**Comment by marcellamaki** [comment]
Closed with #11814
