### ISSUE TITLE
add linting to ensure that all `$tr` are present in the translation .json files

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1177]
This will help ensure that when new strings are added, the updated json is also checked in so that it can be uploaded to crowdin.

**Comment by christianmemije** [comment]
Fixed in #1178

**Comment by DXCanas** [comment]
So I've been digging through the code that seems to be responsible for this. It seems like the `.json` files are directly created as a result of the `$tr`  -- If it's not in the `JSON`, it wasn't found by the program. 

Not sure how we'd go about linting this, then. I might be misunderstanding the purpose of the linter, though. Please advise! @indirectlylit

**Comment by indirectlylit** [comment]
Hm, trying to remember what my intent was here.

I opened this at the same time as #1176 after a particularly rough sequence of VF releases where each one was missing some translations - it was a slow and delicate process getting things to 100% of all languages.

Maybe my intent with this issue was to compare the various locales with english and warn of missing strings? That would be useful, but also isn't what I wrote in the description...

@christianmemije @rtibbles I don't suppose you remember?

**Comment by rtibbles** [comment]
I think it was probably stemming from the fact that the `extract_$trs` was failing to extract strings that were not simply values in the esprima parse of the AST.

This meant that expressions were not being properly extracted (like when we were adding two strings together).

Hopefully the existing linting in there is sufficient to warn if something is not being properly parsed.

**Comment by indirectlylit** [comment]
I would have thought that also, except that I filed the other issue for that

**Comment by rtibbles** [comment]
I guess it's doing an extra verification of the downloaded json files from Crowdin? So it would be a matter of comparing the generated `json` files for `en` against the ones that are in the other locale folders, and then showing warnings? I don't know why a key would go missing, except when we had outdated files, but then it's a lot of warnings that devs can do little about until translation has happened.

**Comment by indirectlylit** [comment]
okay, closing this issue. If we run into more i18n pain in the future, we can open a more actionable issue
