### ISSUE TITLE
Update "insufficient storage" conditon

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11774]
The banner that displays on a LOD when a user sync status is "Insufficient Storage" should only appear on Learn. Currently, it displaying also in the Device plugin, as seen below.

![image](https://github.com/learningequality/kolibri/assets/17235236/2e755719-9623-4aca-83a7-b5504a1e4cd1)

~Because the StorageNotificationBanner is widely used and exists in `core`, this should not be moved (i.e. moving the component itself only to Learn), but rather, the condition should be updated.~
(After further discussion, updated) 
We should remove the banner from the AppBarPage, and instead put it into the relevant place in the Learn page

The banner: 
- [ ] should appear in Learn when the status is `INSUFFICIENT_STORAGE`
- [ ] should be dismissed after a user clicks "manage channels" and is redirected
- [ ] the banner should _not_ ever appear in the Device plugin, even if the user's status changes to `INSUFFICIENT_STORAGE` while they are in the Device Plugin

_(While not a release blocker, this is an important change that we are prioritizing. This is open for community contribution, but contributors interested in this issue should only volunteer if they will be available to work on it promptly.)_

**Comment by FidalMathew** [comment]
@marcellamaki can I work on this issue?

**Comment by shivansh-bhatnagar18** [comment]
@marcellamaki Please Assign me this issue. I would love to work on this

**Comment by MisRob** [comment]
Thanks @FidalMathew and @shivansh-bhatnagar18 for volunteering. It seems @iskipu already has a PR for that. Thanks @iskipu, and also would you mind asking for an assignment before working on something next time? Please have a look [at contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md). It will always take us some time to respond to all comments we're receiving on issues, and it'd help us to distribute work.

**Comment by iskipu** [comment]
> Thanks @iskipu, and also would you mind asking for an assignment before working on something next time?

I am so sorry i started working on this and i havent noticed that people already requested for an assignment which caused the problem sorry @FidalMathew & @shivansh-bhatnagar18  i will make sure i ask for an assignment before working.

**Comment by MisRob** [comment]
No problem @iskipu, thank you for your understanding.

**Comment by Yogeshlodhi** [comment]
@marcellamaki Please assign this task to me if it is still open

**Comment by MisRob** [comment]
Hi @Yogeshlodhi, thank you for volunteering, this is already being addressed in https://github.com/learningequality/kolibri/pull/11809

**Comment by marcellamaki** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/11809
