### ISSUE TITLE
`LessonResourceSelectionPage/ContentCardList.vue` component improvements

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11771]
## Overview

During content creation we borrowed from previous Lesson resource selection components, namely the `ContentCardList` component. 

This component was last updated 3 years ago, so there are a few rough edges that we'd like to smooth out for a more consistent developer interface to the component.

The `viewMoreButtonState` [prop](https://github.com/learningequality/kolibri/blob/66589c69dd0c59c443acf33e54a062ff89af99d7/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSel
ectionPage/ContentCardList.vue#L81-L84) currently expects a string. This should instead make use of a constant. 

### View More Button State

- [ ] Create and export a new object from the [coach/.../constants/index.js](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/constants/index.js) file called `ViewMoreButtonStates`. This should be formatted similarly to how the others are in that file.

The object should handle the following states:
- Loading (previously waiting)
- Has more (previously indicated by not passing the specific strings for loading / not having more)
- No more 
- Error

- [ ] Update `ContentCardList` so that the `viewMoreButtonStates` props validates against those constants to ensure that we always pass only those constants in to that prop

- [ ] Update `ContentCardList` so that it no longer depends on there not being errors to show the button, but rather that it will show the button when the `ViewMoreButtonStates.hasMore` state is passed in.

- [ ] Update all components using the `ContentCardList` to leverage those new constants when passing as a prop to `ContentCardList` (looks like only the `LessonResourceSelectionPage/index.vue`, `CreateExamPage/index.vue`, and `CreateExamPage/CreatePracticeQuiz.vue` components will need to be updated.

**Comment by GarvitSinghal47** [comment]
@nucleogenesis @MisRob i would like to work on this , if its up for contribution.

**Comment by nucleogenesis** [comment]
@GarvitSinghal47 apologies for my delay replying here - let us know if you're still interested and we'll assign you.

**Comment by GarvitSinghal47** [comment]
Yes @nucleogenesis  I am still interested in working on it .

**Comment by MisRob** [comment]
Thank you, @GarvitSinghal47.
