### ISSUE TITLE
Validate QuizSectionSerializer.resource_pool against actually-used information

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11798]
## Overview

We fetch a whole tree of data which includes a lot of data that we don't use and will not use for the purposes of QuizCreation.

This results in a lot of extra data ending up in the database.

Currently, it is using a HexUUIDField as the child validator. It doesn't seem like saving the IDs only will be helpful as we need things like the `ancestors` and `assessmentids` to be included there, likely including a few other things.

## Acceptance criteria

- [ ] Bring parity between the `QuizExercise` type defined in `quizCreationSpecs.js` and the actual results we're saving in the `resource_pool` that are fetched by way of `ContentNode.fetchTree` - basically, update the fields to match the names in the API response, then only keep the ones that are being used during QuizCreation
- [ ] During `useQuizCreation#addToWorkingResourcePool` (merged in #11783) massage the fetchTree-fetched data to map to the newly updated `QuizExercise` typedef
- [ ] There needs to be a better validator on the [QuizSectionSerializer.resource_pool](https://github.com/learningequality/kolibri/blob/d05c5ee39868630fadaa8b96c12f9173941fc5e3/kolibri/core/exams/serializers.py#L43) which ensures that only the required fields are listed there - basically, make a Django serializer which matches the newly updated `QuizExercise` type.

**Comment by rtibbles** [comment]
I am a bit confused by the requirements here - listing anything more than the ids for the ContentNodes will mean that we are creating an implicit cache of the content node metadata, with no real mechanism for invalidating it. Surely the point of only storing the ids is so that we can fetch the most up to date metadata from the content node API?

**Comment by nucleogenesis** [comment]
Thanks @rtibbles -- I'll close this and update #11783 to pass the IDs only to the API
