### ISSUE TITLE
Models that we intend to sync across devices should inherit from AbstractFacilityDataModel

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1180]
We will be linking Kolibri into Morango by making AbstractFacilityDataModel into the base "syncable model". If new models are being added that we want to be syncable via Morango, they should inherit from this class.

Specific example:
https://github.com/learningequality/kolibri/blame/dd689859c9a2a60cb9953e799d0441e9ffabf266/kolibri/content/models.py#L308

**Comment by rtibbles** [comment]
Yeah, I hadn't done it with the exams, as we had explicitly said we were not going to sync them. But then I went and added them as FKs on the ExamLogs, so.... they do need to.

**Comment by rtibbles** [comment]
Fixed in #1193.
