### ISSUE TITLE
Superfluous mastery label covers the thumbnail on the exercise card in the lesson on Android LoDs

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11804]
## Observed behavior

Since the mastery level is already included below the activity label, maybe we can remove the one over the thumbnail...?
1 | 2
-- | --
![2024_01_26_02 03 38](https://github.com/learningequality/kolibri/assets/1457929/1742a20a-0e9e-479f-95a0-0a8f762e7970) | ![mastery-overlay](https://github.com/learningequality/kolibri/assets/1457929/a09adbbd-0625-4f55-892e-2e0bdc5e90e0)

## Errors and logs
...

## Expected behavior
...

## User-facing consequences
...

## Steps to reproduce

Open a lesson that has an exercise resource on Android LoD

## Context

 * Kolibri version:  Windows 7 (0.16b13)

**Comment by FidalMathew** [comment]
@radinamatic can I work on this issue?

**Comment by rtibbles** [comment]
Hi @FidalMathew - thanks for your enthusiasm, but as this is a critical bug for our upcoming and imminent 0.16.0 release, we will be handling this internally to expedite its completion.

**Comment by FidalMathew** [comment]
> Hi @FidalMathew - thanks for your enthusiasm, but as this is a critical bug for our upcoming and imminent 0.16.0 release, we will be handling this internally to expedite its completion.

Sure! Thank you.
