### ISSUE TITLE
Quiz Creation Select Resources- Accessibility Improvement 

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#11806]
### Overview 
The current keyboard navigation in the Resource Selection does not select the resources. When the checkbox is in focus, pressing the Enter key does nothing while navigating through topic cards and exercises.

https://github.com/learningequality/kolibri/assets/103313919/5faf62ec-b35f-417d-b482-62b6b8160f8e

**Comment by kafukoM** [comment]
Hello. I am interested in any updates in regards to this issue and whether any contribution would be welcomed

**Comment by MisRob** [comment]
Hello @kafukoM, thanks for volunteering. This issue is already assigned. Please ask for an assignment on issues that have no assignee and are labeled as "help wanted".

**Comment by nucleogenesis** [comment]
This issue has been resolved -- not sure exactly where but I've tested again and checkboxes work and focus moves as expected.
