### ISSUE TITLE
Logging module ('kolibri.lib.logging') not working as expected

### ISSUE THREAD

**Issue by iskipu** [learningequality/kolibri#11819]
## Observed behavior

There are two issues i found with **`kolibri.lib.logging`** module

1. logging module doesnt support .log function which i saw being used in some places in the codebase

https://github.com/learningequality/kolibri/blob/11233954b3ef17b56d3c23645fbd82540a6ef9c7/packages/kolibri-common/components/MeteredConnectionNotificationModal.vue#L93-L94

2.  Setlevel function of logging not working as expected (Refer Image2 attached below)

## Errors and logs

**Image 1**
![image](https://github.com/learningequality/kolibri/assets/143542192/d95bcf91-d6a2-4302-9f0c-8fbbd34516f9)

**Image 2 (Debug statement not getting printed even after setting level to 0)**
![image](https://github.com/learningequality/kolibri/assets/143542192/6b56b8cd-bc03-4bb5-bfb4-c348ceac59f3)

## Steps to reproduce

 import the kolibri.lib.logging module and try using .log method and .setlevel methods

**Comment by rtibbles** [comment]
Fixed in #11820
