### ISSUE TITLE
Users should not be able to create a second account created on a LoD

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11817]
## Observed behavior
Since setting up multiple learner accounts on LoD seems to have been re-enabled, I decided to go that road on the same setup from #11816. After signing out with the first user, I successfully created another on the same server facility. I was able to see it in Facility-Users, and to enroll it in the same class as the first user. However, it's is unclear what is supposed to happen with syncing this user/account, as its status on both the server and the LoD remained 'Not connected to server', even though the device continued to sync under the first user.

LoD | server
-- | --
https://github.com/learningequality/kolibri/assets/1457929/fbd34f3d-dd6f-4a00-8200-52e8a6a6a38a | <img width="840" alt="2024-01-30_04-09-40" src="https://github.com/learningequality/kolibri/assets/1457929/6060b1a2-8b4e-4406-a1f9-51f87a66ccfb">

## Errors and logs
[Huawei-MediapadT5-AndroidStudio-second-user-created.log](https://github.com/learningequality/kolibri/files/14092368/Huawei-MediapadT5-AndroidStudio-second-user-created.log)

## Expected behavior
Some decisions needed here.

## User-facing consequences
Confusion...? Can I create a second user on an LoD and expect it to sync my progress with the facility that I created it in?

## Steps to reproduce
…

## Context

 * Kolibri version: 0.16b13
 * Operating system: Windows 7 (server) and Android 8 LoD

**Comment by rtibbles** [comment]
I am not completely clear on what happened here.

When you say you "created" a second user on the LOD, what exact steps did you take to do that?

**Comment by radinamatic** [comment]
Apologies for not being clearer about the steps:

1. Sign out from the first LoD user (created in #11816)
2. 'Create an account' button was available on the sign in page (see the recording), so I decided to test it.
3. The new account was successfully created and I could see it on the VM in the server's Facility - Users, and could even enroll it to a class.
4. However, the status remained as 'Not connected to server' for a while, and eventually changed to 'Not recently synced', and no class assignments appeared on this user's Home, just 'Explore channels' that were already on the device.

@pcenov also replicated this, and we were both unsure what are actually the expectations here, as we do not seem to have the Gherkin scenarios for this workflow in 0.16. If the creation of the second user account on one LoD is allowed for the same server facility, is this account having the same _treatment_ as the first one (enrolled in the class and receiving assignments), is it supposed to sync 'independently' from the first user...?

**Comment by rtibbles** [comment]
OK, so the bug here is that create account should not be appearing there. Users on an LOD cannot currently create a new account except during the setup wizard.

**Comment by rtibbles** [comment]
Fixed in #11827
