### ISSUE TITLE
Not able to access the webpage in kolibri app_mode

### ISSUE THREAD

**Issue by iskipu** [learningequality/kolibri#11821]
## Observed behavior

On running kolibri server in [app_mode]( https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-in-app-mode) and opening

The meter modal doesnt go away 

## Errors and logs

https://github.com/learningequality/kolibri/assets/143542192/05bce599-5696-4287-b35f-a13011455269

## Replicate

In order to replicate run the kolibri server in app mode and try opening the webpage.

## Expected behavior

To start accessing the web page after choosing the desired option.

**Comment by rtibbles** [comment]
Fixed in #11819
