### ISSUE TITLE
Enhance Quiz- Side panel doesn't show on mobile

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#11826]
## Overview

When I was explaining a certain piece of behavior in the  select resource component  to  @akolson .  I discovered that  when you  want to add resource while on mobile the side panel does not appear at all.  or  when it's loaded and the page change to mobile view everything get's distorted.

Uploading Screen Recording 2024-02-01 at 16.37.15.mov…

**Comment by ProgrammingPirates** [comment]
Hello sir @AllanOXDi  can you assign me this issue ?

**Comment by rtibbles** [comment]
Hi @ProgrammingPirates - this will be worked on by our core development team, for issues you could help take on, please look for unassigned issues with the help wanted label. For a complete list of such issues across our repos, you can look at this link:

https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues
