### ISSUE TITLE
Android app - Screen flickering at the Library page while scrolling down

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11838]
## Observed behavior
This issue was initially reported as a comment to https://github.com/learningequality/kolibri/pull/11551 and was thought of as fixed, but I've found some other cases where it's not. Specifically it can be replicated when you are signed in as a Learner and there are some channels in your Library but there are no other libraries around you:

https://github.com/learningequality/kolibri/assets/79847249/8b07c1a1-798b-4b86-bcd9-1ba46cede163

Also happens when I am signed in as a Learner, there are no channels in my Library and there are some other libraries around me.

https://github.com/learningequality/kolibri/assets/79847249/3f6da8d6-fb41-4e5d-aeb2-96a8cbf8efc4

## Expected behavior

No flickering while exploring the Library

## Steps to reproduce the issue

1. Install the [latest Beta 13 Android app](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13).
2. Follow the above mentioned scenarios.

## Usage Details
[Beta 13](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13)
Ubuntu 22  - Chrome
Samsung Note 10 Lite, Android 13

**Comment by pcenov** [comment]
@radinamatic

**Comment by iskipu** [comment]
Can you assign this to me plz

**Comment by akolson** [comment]
@pcenov, noting that I picked up flickering on the same screen(yesterday during 0.16 "test drive") when viewing a particular remote content(I was able to replicate this consistently with Jacob's device that I was testing remote content browsing on). So I think this is not just specific to android devices only. Please see the video below; cc @marcellamaki @radinamatic 

https://github.com/learningequality/kolibri/assets/5203639/cb73fd38-c14c-4383-8b82-4244c0f740b8

**Comment by MisRob** [comment]
Hi @iskipu, thank you for volunteering, yes.

**Comment by bjester** [comment]
@iskipu Please be sure to base your work off the [`release-v0.16.x` branch](https://github.com/learningequality/kolibri/tree/release-v0.16.x)

**Comment by iskipu** [comment]
Hi @pcenov  i was able to successfully replicate the problem in my andriod device by downloading the apk. But can you explain me how did you replicate android screen in web browser.

in my chrome browser i am not able to replicate like you did in the video you shared : 

![image](https://github.com/learningequality/kolibri/assets/143542192/72af96cd-571a-40e1-8b5d-14cbe7dfdd32)

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11853
