### ISSUE TITLE
Mobile view - Library - The filter or the folders sidebar is opened by default when exploring folders

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11842]
## Observed behavior
Observed in mobile browsers or using Chrome's mobile device emulator. When exploring folders then the filter or the folders sidebar is opened by default while the user should first be able to see the content.

https://github.com/learningequality/kolibri/assets/79847249/43c29148-b1de-4062-8bd2-3499c9bf2765

## Expected behavior
The user should be able to first see the content and then decide whether to use the filters.

## Steps to reproduce the issue

1. Install the [latest Beta 13 Android app](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13).
2. Go to the Library page in mobile view and attempt to explore a channel with folders.

## Usage Details
[Beta 13](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13)
Ubuntu 22  - Chrome
Samsung Note 10 Lite, Android 13

**Comment by pcenov** [comment]
@radinamatic

**Comment by Moscode** [comment]
Hello @radinamatic, I will like to be assigned to this issue.

**Comment by MisRob** [comment]
Welcome @Moscode, thank you for volunteering. I will assign you.

**Comment by bjester** [comment]
@Moscode Please be sure to base your work off the [`release-v0.16.x` branch](https://github.com/learningequality/kolibri/tree/release-v0.16.x)

**Comment by MisRob** [comment]
Hello @Moscode. is this issue work in progress or should we unassign?

**Comment by MisRob** [comment]
Unassagning due to inactivity. If you'd like to return to it @moscode, let us know.

**Comment by Wck-iipi** [comment]
@radinamatic I would like to work on this issue

**Comment by bjester** [comment]
@Wck-iipi I have assigned you
