### ISSUE TITLE
Loading issues while viewing reports (part 2 & 3)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11856]
## Observed behavior
Follow-up from  #11824 (part 1 with `Resource not found` notification was fixed in  https://github.com/learningequality/kolibri/pull/11843)

1. When trying to open the ``need help`` resource in the second lesson, there is a brief flash of the title of the ``need help`` resource from the first lesson (see the recording below). 

2. Size of the lesson (before the resource itself is opened) has a flash of ``NaN B``.

Dual Core 8GBs | Quad Core 16GB
-- | --
https://github.com/learningequality/kolibri/assets/1457929/a6c850c1-6fcb-413f-bdc7-4b01bae3deaa | https://github.com/learningequality/kolibri/assets/1457929/eaad3f2b-5812-4943-b908-519e94e99b6c

## Errors and logs
No errors in the Network tab or the console. Use any of the following to debug:

* [full home folder (280MB)](https://drive.google.com/file/d/14fdx8ynheoCajPBeVyTlOzAffv7sqXnr/view?usp=drive_link)
* [everything but the content (38MB)](https://drive.google.com/file/d/1wQcgFKFxmUiPUkaeDy1LDhiI8ognXcSQ/view?usp=drive_link) 
* [just logs](https://drive.google.com/file/d/1YSi_ymrlXTQnUB0joZe-6hP1lGXXPYvz/view?usp=drive_link)

## Expected behavior
Clear and seamless navigation through coach reports without loading issues. 

## User-facing consequences
Bad coach experience. 

## Steps to reproduce
Load the home folder provided above, try to navigate the **Lek3** and **Lek4** lessons to open and review the resources that learners ``need help`` with.

## Context

 * Kolibri version: 0.16b13
 * Operating system: Windows 7

**Comment by himanshuc3** [comment]
I don't have access to the resources mentioned in the issue. If this something that will be handled internally, I could look for other issues @radinamatic

**Comment by MisRob** [comment]
Thanks @himanshuc3, yes I think it'd be better to find "help wanted" issue

**Comment by rtibbles** [comment]
Fixed in #12178
