### ISSUE TITLE
Insufficient storage banner - The 'Go to my downloads' button is not working / no space between the buttons

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11866]
## Observed behavior

While regression testing https://github.com/learningequality/kolibri/pull/11809 I noticed that the 'Go to my downloads' button is not working and there is no space between the 'Go to my downloads' and 'Mange channels' buttons. 
The 'Go to my downloads' is also not working if the LOD user is with no super admin permissions.

https://github.com/learningequality/kolibri/assets/79847249/d63dee0c-2cff-46ff-9ab5-d3831d82bf45

## Expected behavior

Clicking on 'Go to my downloads' should bring the user to 'My downloads'. All the buttons should be displayed with enough space between them and displayed nicely in mobile view.

## Steps to reproduce the issue

1. Install the [latest Beta 13 Android app](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13).
2. Setup a learn-only device by importing at least 2 learners.
3. Sign in as the super admin learner, go to Device > Settings and enable both 'Allow learners to download resources' and 'Set storage limit for auto-download...'. Select 0 as the value.
4. Go to the Library page and download a resource from a device in the 'Other libraries' section..
5. Observe the insufficient storage banner and click the 'Go to my downloads' button.

## Usage Details
[Beta 13](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta13)
Ubuntu 22  - Chrome
Samsung Note 10 Lite, Android 13

**Comment by pcenov** [comment]
@radinamatic

**Comment by iskipu** [comment]
Can i work on this

**Comment by MisRob** [comment]
Hi @iskipu, yes, I will assign you. Thanks!

**Comment by himanshuc3** [comment]
@iskipu The last commit if a month old by you. Can you acknowledge if this being worked on.
Further @MisRob can you confirm if this issue still persists.

**Comment by iskipu** [comment]
Hi @himanshuc3,

I fixed the issue in the latter commits of https://github.com/learningequality/kolibri/pull/11809

Refer:https://github.com/learningequality/kolibri/pull/11809#issuecomment-1979114826

@MisRob i think this issue can be closed now. Looks like i haven't refered the issue in my latter commits so it caused the confusion sorry 😅.

**Comment by MisRob** [comment]
Thanks @iskipu :)
