### ISSUE TITLE
Audit and fix theme token updates against KDS

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11867]
## Overview

In support of planned patch 1, we need to ensure that our token mapping is properly upgraded, in particular where there are changes to the components token map (i.e. previously a `primary` token, but now needs to be the color of the `secondary` token).

## To Do
Review Kolibri against KDS token updates (pending). Some updates may need to be made in KDS, and some may need to be made in Kolibri. 
General areas of consideration: 
- App bar updates 
- learning activity icons
- icons generally
- hover states and active states

Search Kolibri codebase for:  
- references to  tokens that are added in to custom components. Particularly `primary` and `secondary`tokens. Ask if there are any questions about which is the appropriate token going forward
- Hex codes that do not belong

Manually review (you can ask for support from designers and Radina once you have a PR with assets):
- Links and/or text with insufficient contrast (this would be edge cases)

@marcellamaki @jtamiace @tomiwaoLE and @radinamatic are available for support

**Comment by rtibbles** [comment]
Fixed in #11867
