### ISSUE TITLE
Loading spinner misalignment

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11884]
## Observed behavior
There are a couple of places where the `KCircularLoader` spinner is misaligned to the text that it should be next to

## Incorrect display

Sync status display
![statusdisplay2](https://github.com/learningequality/kolibri/assets/17235236/475eb080-3187-4cf9-b3ef-cf048e7d9423)

On the downloads page:
![image (24)](https://github.com/learningequality/kolibri/assets/17235236/288c89d8-0f3e-4809-b417-7693284fefee)

## Expected behavior
- The `KCircularLoader` should be sized proportionally to the text 
- The loader should be in line with the text, and the items should be alined horizontally

Example of proper scale and alignment:
<img width="128" alt="Screenshot 2024-02-15 at 12 58 10 PM" src="https://github.com/learningequality/kolibri/assets/17235236/0fa894d8-de82-49e9-9fca-d86d6ca3876d">

## Steps to reproduce

1. Set up two Kolibris - one as a Learn Only Device (LOD) and one as a full facility. The LOD should be set up to sync back the main facility
2. Assign some resources to the Learner
3. Observe the sync status 

Part 2:
1. Set up Kolibri as an "on my own" setup
2. download some content from the Kolibri Content Library via your internet connection by browsing the library page
3. go to "my downloads" and observe the syncing display and spinner 

Note: modifying your connection speed to "Slow 3G" in the browser may help with replicating a slower download so the loading/waiting state can be properly observed

## Context
Kolibri v0.16.x

**Comment by MisRob** [comment]
Here's a tutorial for setting up two Kolibri apps https://kolibri-dev.readthedocs.io/en/develop/howtos/another_kolibri_instance.html

**Comment by iskipu** [comment]
Hi @MisRob Can i work on this plz

**Comment by Abhishekzod007** [comment]
Hey @MisRob I wanna contribute on this issue. Can you assign me this?
Although most of the issues are assigned on "Studio" to someone so and I tried to work on that but people are working already working on these. So please assign me this atleast.

**Comment by MisRob** [comment]
Hi @iskipu and @Abhishekzod007, thank you! I will assing @iskipu since they asked first here and @Abhishekzod007 I just assigned you another issue.

**Comment by MisRob** [comment]
@Abhishekzod007 Have you seen our contributing guidelines? There are links to all unassigned "help wanted" issues and there's plenty.
