### ISSUE TITLE
Mac App: Opening the side navigation and scrolling activates scrolling for main page as well

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11881]
Observed by @LianaHarris360 during the 0.16 sync sessino on Feb 14 2024

## Observed behavior
When running Kolibri on the mac app, if you open the side navigation, the main page behind the overlay also scrolls 

## Expected behavior
Only the side navigation should scroll

## Steps to reproduce

1. Run the Kolibri Mac app **on the browser**
2. Open the main side navigation 
3. Scroll, and observe the main page content also scrolling

## Context
Mac app - 0.16.x

**Comment by poju3185** [comment]
Hi @marcellamaki, I would like to work on this issue. First, I'd like to confirm if this is the bug you mentioned:
User shouldn't be able to scroll the main page while the side navigation is open.

https://github.com/learningequality/kolibri/assets/81625625/1ef2f070-c98d-4be1-b632-c9edfef0f1c2

By the way, this also happens in devserver.

**Comment by LianaHarris360** [comment]
Hello @poju3185 the issue occurs when scrolling on the side navigation, the main page will scroll at the same time.

https://github.com/learningequality/kolibri/assets/46411498/ae3d3894-3366-4097-b476-4ca04a3b64b5

**Comment by poju3185** [comment]
@LianaHarris360 thanks for your reply. Could you please tell me how you run the app server?
I used `yarn run app-devserver` and open the url showed in the teminal.
However, I was stuck at the **Using mobile data?** window.
It doesn't react when I click either of the option. In terminal, the error message is `django.core.exceptions.ValidationError: {'extra_settings': ["{'allow_download_on_metered_connection': False} does not have property 'enable_automatic_download'"]}`
Should I open another issues for this?
![image](https://github.com/learningequality/kolibri/assets/81625625/62379746-369f-49ca-b142-959f1c8ee311)

**Comment by poju3185** [comment]
I fix the scrolling issue. Please kindly review, thanks!

**Comment by LianaHarris360** [comment]
@poju3185 To run the app server, I followed all of the same instructions [here](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#running-the-server:~:text=Running%20in%20App,%C2%B6). But I am unable to recreate the error you described, I can select either option when running the Kolibri Mac app in the browser, with a Mac operating system as well.

The Kolibri dev documentation also mentions the file [integration_testing/scripts/run_kolibri_app_mode.py](https://github.com/learningequality/kolibri/blob/4959560f6384d9168b66c15d4a24a28472dccf09/integration_testing/scripts/run_kolibri_app_mode.py#L52), where you can edit line 52 to return `False` within the function `check_is_metered()`. 

I see your opened pull request to fix this issue, thank you for taking the time to work on this, I will assign this issue to you. Moving forward, could you please wait to be assigned to an issue before opening a pull request? This helps maintain transparency within the team's workflow and provides the team time to make any necessary decisions! :)

**Comment by poju3185** [comment]
@LianaHarris360 thanks for the reply. Sorry I'll make sure to open a PR after being assigned. Should I create another PR and cloase the old one?
Regarding the **Use mobile data** issue, I actually found a bug in the frontend file, which I solved with this [PR](https://github.com/learningequality/kolibri/pull/11988). Please also check it out if possible. Thank you.

**Comment by LianaHarris360** [comment]
No worries! You can keep the current PR for this issue open and I will assign myself and possibly another to review. Apologies if it does not get reviewed straight away. 

In regards to the second issue you identified, we will work with our QA team to try and replicate the issue before addressing it with a PR. From here, it would be ideal if you could close the PR you opened for it and add notes about the bug you found to the issue description. Once the issue can be recreated and confirmed, we will assign the issue. Thank you.

**Comment by poju3185** [comment]
Thank you for the update! I've closed the PR for the second issue.

**Comment by LianaHarris360** [comment]
Fixed in #11992
