### ISSUE TITLE
Facility > Data - It's possible to import users with duplicate usernames

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11890]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/11779: if there are several duplicate usernames in the CSV file (with different letter case like Peter, PETER) and I am importing them for the first time it's still possible to import all of them.

https://github.com/learningequality/kolibri/assets/79847249/5d249098-56fe-47db-a369-c3753d749877

## Expected behavior

It shouldn't be possible to import duplicate usernames.

## Steps to reproduce the issue

1. Install the [the build asset from here](https://github.com/learningequality/kolibri/pull/11779).
2. As a super admin go to Facility > Data and attempt to import the following list of users: 
[users.csv](https://github.com/learningequality/kolibri/files/14309067/users.csv)

## Usage Details
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nick2432** [comment]
can i work on this?

**Comment by radinamatic** [comment]
As @rtibbles commented, you're welcome to pick this one too, @nick2432 🙂 
Thank you for your continued contributions!

**Comment by nick2432** [comment]
@radinamatic  Thank you so much for your kind words, I'm glad to be a part of this community and appreciate the support.

**Comment by nick2432** [comment]
@pcenov , I've raised the PR. Could you please check it?

**Comment by marcellamaki** [comment]
Closed with #11899
