### ISSUE TITLE
get_learner_count returns all users, not just learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1190]
The `ClassroomSerializer` currently returns the total number of users in a class for the `learner_count`.

Instead, it should return only those users that are not coaches or admins.

In _serializers.py_:

```python
class ClassroomSerializer(serializers.ModelSerializer):
    learner_count = serializers.SerializerMethodField()
    coach_count = serializers.SerializerMethodField()
    admin_count = serializers.SerializerMethodField()

    def get_learner_count(self, target_node):
        return target_node.get_members().count()

    def get_coach_count(self, target_node):
        return Role.objects.filter(collection=target_node, kind=role_kinds.COACH).count()

    def get_admin_count(self, target_node):
        return Role.objects.filter(collection=target_node, kind=role_kinds.ADMIN).count()

    class Meta:
        model = Classroom
        fields = ('id', 'name', 'parent', 'learner_count', 'coach_count', 'admin_count')
```

**Comment by rtibbles** [comment]
Note: While the fix submitted by #1321 will fix the UI problem, I think, in the long run, this is the wrong fix.

The problem is again the conflation of roles and membership that is endemic in the management app.

Being a member of a class means you are a learner *in that class* - otherwise, you should not be a member of it.

**Comment by jonboiser** [comment]
What were these user-type counts used for in the UI? I don't see them displayed anywhere.

So should the 'role' of a user simply be hidden in the context of a classroom? Then the original Serializer would be partly correct in counting all FacilityUsers attached to the Classroom, but there would be no need to count admins and coaches.

**Comment by indirectlylit** [comment]
they were previously, but no longer. sorry for the confusion and wasted effort!

**Comment by jonboiser** [comment]
Should we delete the counting-related code, then?

**Comment by indirectlylit** [comment]
I think we may still need in the not-to-distant future for when we allow class coaches and admins
