### ISSUE TITLE
Fix release workflow automatic upload GCS to not upload to folders

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11908]
## Observed behavior
In our new release automatic workflow, when the assets are uploaded to the GCS bucket, there is currently an extra folder level, with the name of the asset.

For example: 
── `0.16.0/kolibri-0.16.0-0.4.0.dmg/kolibri-0.16.0-0.4.0.dmg`

The correct structure should be 
`0.16.0/kolibri-0.16.0-0.4.0.dmg`

Noting that even with the folder change, the Pi Image will need to be renamed to:
e.g. `kolibri-pi-image-0.16.0.zip`

and the windows installer will need to be renamed to:
e.g. `kolibri-v0.16.0-windows-setup.exe`

**Comment by emdneto** [comment]
Hi:
Can I help with this one? 😄 

Found this in the logs: Uploading ~/work/kolibri/kolibri/dist/kolibri-0.16.0-0.4.0.dmg to gs://***/downloads/kolibri/v0.16.0/kolibri-0.16.0-0.4.0.dmg/kolibri-0.16.0-0.4.0.dmg. 

I think we can fix by changing here https://github.com/learningequality/kolibri/blob/develop/.github/workflows/release_kolibri.yml#L188.

**Comment by marcellamaki** [comment]
Hi @emdneto - thanks for your interest in contributing! This issue is already assigned to a member of our team, but you are welcome to look for another unassigned issue, particular one labeled "help wanted" to find another way to contribute.

**Comment by rtibbles** [comment]
This is assumed to have been fixed by #12050.

If it is not fixed, we can reopen.

**Comment by rtibbles** [comment]
Hopefully fixed in #12069
