### ISSUE TITLE
Setup wizard: Responsive language list

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri#11923]
## Observed behavior
We want the list of languages shown in the [LanguageSwitcherList](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/language-switcher/LanguageSwitcherList.vue) to fit on a single line.

Currently the list of languages in the LanguageSwitcherList is not fully responsive as it relies on window breakpoints to choose the number of languages to be displayed in the list before the "see more". The problem is that this number is fixed and does not depend on the width of the text, and in languages where the text takes up more space, the list items end on a second line. See https://github.com/learningequality/kolibri/pull/11847#issuecomment-1945997358.

## Expected behavior
The list of languages along with the "see more" fits on a single line in the setup wizard

## Steps to reproduce

See https://github.com/learningequality/kolibri/pull/11847#issuecomment-1945997358

## Notes

We will need to use here the new KDS component that handles horizontal lists with overflow https://github.com/learningequality/kolibri-design-system/issues/556, so this issue is blocked until that component is implemented.

**Comment by nikkuAg** [comment]
Is this issue still open? I would like to work on this

**Comment by AlexVelezLl** [comment]
Hi @nikkuAg! Unfortunately this issue is still blocked until https://github.com/learningequality/kolibri-design-system/pull/552 is merged.
