### ISSUE TITLE
Update `kolibri` command usage in `kolibri_sentry_plugin` documentation

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#11936]
## Observed behavior

> Issue originally reported by @thesujai while setting up kolibri sentry plugin on his local

The current documentation on enabling the Kolibri sentry plugin don't seen to work as it doesn't match the usage description of the `kolibri` command.

## Errors and logs

Running ` kolibri plugin kolibri_sentry_plugin enable` returns the error below;
```
Usage: kolibri plugin [OPTIONS] COMMAND [ARGS]...
Try "kolibri plugin --help" for help.

Error: No such command "kolibri_sentry_plugin".

```

## Expected behavior

The usage documented in https://github.com/learningequality/kolibri-sentry-plugin needs to be updated to match the command usage(`kolibri plugin [OPTIONS] COMMAND [ARGS]...`). i.e the commend should be 
`kolibri plugin enable <plugin name>`

## User-facing consequences

Following the current documenting results into errors while setting up the sentry plugin

## Steps to reproduce

Set up the Kolibri Sentry plugin with the current documentation.

## Context

Kolibri v0.16.0

**Comment by poju3185** [comment]
Hi @akolson, could I work on this issue?

**Comment by poju3185** [comment]
I opened a [PR](https://github.com/learningequality/kolibri-sentry-plugin/pull/2) in the [kolibri-sentry-plugin repo](https://github.com/learningequality/kolibri-sentry-plugin). Please give it a look, thank you!

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri-sentry-plugin/pull/2
