### ISSUE TITLE
`TypeError: this.items is null` on Windows

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1199]
## Summary

Appears on all the non-PLIX and non-Flexbox exercises in CK-12 channel.
@rtibbles tried one approach in #1197, but the error is still there. 

## System information

 - Version: 0.3.1b2.dev4
 - Operating system: Windows 7
 - Browser: FF & Chrome

## Traceback or relevant snippet from server.log or browser console

```
TypeError: Cannot read property 'length' of undefined
    at qt.loadItemData (exercise_perseus_render_module-0.3.1beta1.dev2.js:42)
    at qt.n [as loadItemData] (default_frontend-0.3.1beta2.dev4.js:13)
    at qt.<anonymous> (exercise_perseus_render_module-0.3.1beta1.dev2.js:42)
    at nr.run (default_frontend-0.3.1beta2.dev4.js:14)
    at B (default_frontend-0.3.1beta2.dev4.js:13)
    at Array.<anonymous> (default_frontend-0.3.1beta2.dev4.js:14)
    at t (default_frontend-0.3.1beta2.dev4.js:14)
```

## How to reproduce

Try any non-PLIX and non-Flexbox exercise.

### Firefox
![virtualbox_windows 7_07_04_2017_14_21_39](https://cloud.githubusercontent.com/assets/1457929/24800093/e2111a2c-1b9e-11e7-88c1-22f628ab743d.png)

### Chrome
![virtualbox_windows 7_07_04_2017_14_24_47](https://cloud.githubusercontent.com/assets/1457929/24800040/9dffe868-1b9e-11e7-9b33-e3c3597a224a.png)

**Comment by rtibbles** [comment]
Looks like the mime type is still octet stream, so I think our diagnosis of the issue is still valid, just our solution is not working.

**Comment by radinamatic** [comment]
Maybe worth noting that this issue appeared right after the #1189 `zipcontent` issue was fixed, if it helps...

**Comment by rtibbles** [comment]
This issue can only appear with the zip content fix. I will need to debug on a Windows machine in order to see how to set the mimetype properly.

**Comment by radinamatic** [comment]
`this.items` is null no more! :boom:
