### ISSUE TITLE
Pre-commit hooks not looking out for print statements

### ISSUE THREAD

**Issue by thesujai** [learningequality/kolibri#11990]
## Observed behavior

Reference: https://github.com/learningequality/kolibri/pull/11978#discussion_r1523044240
Currently the precommit hooks are not detecting print statements in our code base, and there are many of them that have made into our codebase.

## Expected behavior

- Pre-commit hooks should fail if any print statements(without `noqa` comments) are there in the code.(Introduce [flake8-print](https://pypi.org/project/flake8-print/ ))
- Wherever there are print statements in codebase, they must be either replaced by `logger` or `noqa` comments should be added to them

## User-facing consequences

**Developers** using print statements for testing and debugging miss out some print statements while commiting. So the pre-commit will stop them from doing so.

## Steps to reproduce

Run the pre-commit on all files, you can see everything pass, but there are many print statements throughout codebase
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/management/utils.py#L52

## Context

Observed on develop but same for elsewhere

**Comment by thesujai** [comment]
I would be happy to raise a PR for this.
Just a confusion where to use `noqa` and where to use `logger`

**Comment by bjester** [comment]
@thesujai I'll assign you. I think most existing usages of `print` would have to be migrated to use logging, unless it seems clear it was accidentally added for debugging
