### ISSUE TITLE
Import channel from local drive not working (Windows)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1200]
## Summary

I am testing this from VM, but we had it working correctly in VMs back in November, so it shouldn't be an issue...

## System information

 - Version: 0.3.1b2.dev4
 - Operating system: Windows 7
 - Browser: FF & Chrome

## Traceback or relevant snippet from server.log or browser console

```
{ "request": { "path": "/api/tasks/localdrive/", "params": { "1491573636624": 1491573636624 }, "headers": { "X-CSRFToken": "l2CgsGjXdAWu0vIFAfGBzLXOahxm3Kme", "Content-Type": "application/json", "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2" }, "method": "GET", "canceled": false }, "url": "/api/tasks/localdrive/?1491573636624=1491573636624", "raw": {}, "status": { "code": 500, "text": "Internal Server Error" }, "headers": { "Date": "Fri, 07 Apr 2017 14:00:37 GMT", "Vary": "Cookie", "Server": "0.0.0.0", "X-Frame-Options": "SAMEORIGIN", "Transfer-Encoding": "chunked", "Content-Type": "text/html" }, "entity": "<h1>Server Error (500)</h1>" }
```

## How to reproduce

1. Log in as Admin
1. Go to `Manage > Content`
1. Try to import from the local drive

## Screenshots

![virtualbox_windows 7_07_04_2017_16_00_54](https://cloud.githubusercontent.com/assets/1457929/24803471/a393fb4a-1bab-11e7-969d-ef875e93ff51.png)

![virtualbox_windows 7_07_04_2017_16_02_15](https://cloud.githubusercontent.com/assets/1457929/24803481/ac682228-1bab-11e7-8bd8-072e7969eb5e.png)

![virtualbox_windows 7_07_04_2017_14_14_15](https://cloud.githubusercontent.com/assets/1457929/24802022/af1f6d46-1ba6-11e7-850d-f62c743a472f.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

UNICEF Uganda will need this (or a workaround) asap.

**Comment by indirectlylit** [comment]
cc @aronasorman maybe you have some ideas on this?

**Comment by radinamatic** [comment]
Installing on VM with the same guest OS but a different host machine (both hosts were OSX) did not result in the same error, and I was able to import without issues, though... :thinking: 

![fullscreen_08_04_17_01_55](https://cloud.githubusercontent.com/assets/1457929/24873766/6cc2f822-1e22-11e7-84f1-65c3ed4b1f33.png)

![fullscreen_08_04_17_02_04](https://cloud.githubusercontent.com/assets/1457929/24873775/743e8ddc-1e22-11e7-8a2e-9bfae6c67674.png)

Maybe leave open for now, in case the I manage to replicate.

**Comment by indirectlylit** [comment]
is this something they encountered in uganda on real machines?

**Comment by radinamatic** [comment]
Nope, happened to me while testing on a VM in one host, but not on a second VM with the same guest OS.

**Comment by indirectlylit** [comment]
closing as possibly a fluke of the VM? please re-open if you encounter it again

**Comment by radinamatic** [comment]
Ok to close this, since it only appeares on one VM, and not even consistently on others with the same host OS.
