### ISSUE TITLE
Quiz Creation: Replace TabsWithOverflow with KListWithOverflow 

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12011]
## Overview
Late in the development on the updates to quiz creation, a component was added to KDS that should improve the UX of the section tabs overall. Here we will update the quiz creation to instead use that [KListWithOverflow](https://design-system.learningequality.org/klistwithoverflow/) component.

While I suspect that this will be relatively straightforward, there are a few differences to how things are done. Ideally, you should have everything you need in `KListWithOverflow` to list the section titles as intended.

## Acceptance criteria

- [ ] Migrate use of `TabsWithOverflow` to the `KListWithOverflow` component to be released in KDS 
- [ ] Mark the "currently selected section" w/ a `$themeTokens.primary` underline if it is in the drop-down menu.
- [ ] **NOTE:** If there are features you _need_ from `KListWithOverflow` that aren't there, then make them and test them in KDS and make a corresponding PR in KDS.

**Comment by MisRob** [comment]
Note that `KTabs` and `KTabsList` should be updated to use `KListWithOverflow`. Is there something major in `TabsWithOverflow` that `KTabs` with `KListWithOverflow` can't provide?

**Comment by MisRob** [comment]
Blocked by https://github.com/learningequality/kolibri-design-system/issues/623

**Comment by AlexVelezLl** [comment]
Closing since another approach will be implemented to handle overflow in tabs. See https://github.com/learningequality/kolibri/pull/12146#issuecomment-2127951322
