### ISSUE TITLE
Quiz Creation: Move `handleReplacements` logic from `ReplaceQuestions` to `useQuizCreation`

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12012]
## Overview

This is some tech debt we identified during reviews. Basically, the `ReplaceQuestions#handleReplacements` method doesn't need to live there and is better placed in `useQuizCreation` -- this will clean-up `ReplaceQuestions` a bit and house the logic where it belongs.

## Acceptance criteria

- [ ] Move `handleReplacements` logic from `ReplaceQuestions` to `useQuizCreation` and clean up after yourself

**Comment by ghost** [comment]
@nucleogenesis  
 I am open to work on it. May I go ahead ?

**Comment by MisRob** [comment]
Thank you for volunteering @rd-sharma7, I will assign you

**Comment by ghost** [comment]
@nucleogenesis , @MisRob , I have start working on this , and simultaneously setting up the kolibri environment in my W11 machine . I have done the steps till [_Development_ server](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#development-server) & get stucked in cmd **yarn run devserver** ,shows this :

(running in win-Administrator)

![Screenshot 2024-03-23 192327](https://github.com/learningequality/kolibri/assets/129971777/de90965e-6a14-4c20-81cc-cfe40a967bec)

my yarn pkg is on path _C:\Program Files (x86)\Yarn_

@nucleogenesis  I checked out the DB , found that there are three files seems to assoicated with this issue .if you don't mind , can you illustrate the issue little bit more!
- [ReplaceQuestion.vue]( https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue)
- [useQuizCreation.js]( https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/composables/useQuizCreation.js)
- [useQuizCreation.spec.js]( https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/test/useQuizCreation.spec.js)

**Comment by nucleogenesis** [comment]
I'm sorry @rd-sharma7 I think that you'll need to wait just a day or two to start on this as it is depending on #11937 being merged (which I'm working on to start this week). 

`ReplaceQuestions.vue` is expanded significantly in that PR and this issue is meant to be a follow-up to that so I was too eager last week in setting this as ready to be worked on.

In any case, those files are correct. Overall, the `useQuizCreation` module is used for managing UI and overall state for the quiz creation tool in Kolibri. I initially wrote that `replaceQuestions` method in the `ReplaceQuestions` component but in review it was suggested that it'd be better suited in the `useQuizCreation` module.

You can see the soon-to-be-merged version of the `ReplaceQuestions.vue` file in #11937 which may make the goal of this issue more clear.

If you'll be able to start on this later this week, then I will ping you here again when it is ready.

---

**re: your dev environment & running Kolibri's devserver**

I'm not familiar with development on a Windows machine so there may be some issues w/ the configuration there -- however, you'll need to be sure that the directory at `C:\Users\ASUS\kolibriSSH` is where you cloned the Kolibri Github repo. If you run `dir` in that directory, what files are listed?

When you run `yarn run devserver` you'll need to be in the directory where the Kolibri repo lives, so when you `dir` you should see a `package.json` and folders like `kolibri` and `requirements` and so forth.

**Comment by ghost** [comment]
@nucleogenesis  thankyou for your kind response , I am feeling disappointing that the issue seems me more critical now ,as it wasn't before , and I start feeling like that i am not able solve this at now .I will looks further to solve others when I get command on languages. 
thankyou (-_-)

**Comment by KshitijThareja** [comment]
Hi @nucleogenesis @MisRob :)
I'd like to work on this issue once the mentioned PR is merged. Feel free to assign it to me.

**Comment by MisRob** [comment]
Alright @KshitijThareja, thank you
