### ISSUE TITLE
Getting "Username is duplicated" message when importing a user on my second facility and the user is already extant in the first facility

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12031]
## Observed behavior
Observed while integration testing the [v0.16.1-beta0 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta0) release.
When I have multiple facilities and I try to import a user or several users to Facility 2 but they are already existing in Facility 1 I am seeing the validation message that they are duplicate. 

https://github.com/learningequality/kolibri/assets/79847249/a6d88ef3-55ef-4d7e-891d-3571954fb6d9

## Expected behavior

This validation should be performed only for users from the same facility.

## Steps to reproduce the issue

1. Install  [v0.16.1-beta0 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta0).
2. Setup a full device with several facilities.
3. In Facility 1 import or create several users.
4. In Facility 2 go to Facility > Data and attempt to import the same users.

## Logs

[win-0.16.1-logs.zip](https://github.com/learningequality/kolibri/files/14789382/win-0.16.1-logs.zip)

## Usage Details
[v0.16.1-beta0 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta0)
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Good catch! Guessing this happened in the course of our work to tighten up the duplication checking!

**Comment by rtibbles** [comment]
Fixed in #12040
