### ISSUE TITLE
'On my own' device - Merging a user is not working

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12048]
## Observed behavior
Observed while integration testing the [v0.16.1-beta1 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta1) release.
When I try to merge a user created through 'On my own' I am getting an "Invalid URL" error in the console. Note that creating a new account through the same flow is working correctly. This issue is caused by the changes made in https://github.com/learningequality/kolibri/pull/12028 and is not extant in [v0.16.1-beta0](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta0).

https://github.com/learningequality/kolibri/assets/79847249/30daa3ca-918c-4c15-901b-c74c08b96466

## Expected behavior

Fully functional 'Merge accounts' user flow. 

## Steps to reproduce the issue

1. Install [v0.16.1-beta1 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta1).
2. Setup a full device as a server and another device by going through the 'On my own' setup flow.
3. Attempt to merge the user from the 'On my own' device' to the server facility.

## Logs

[logs.zip](https://github.com/learningequality/kolibri/files/14850735/logs.zip)

## Usage Details
[v0.16.1-beta1 ](https://github.com/learningequality/kolibri/releases/tag/v0.16.1-beta1)
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic @rtibbles

**Comment by rtibbles** [comment]
Thanks @pcenov - this probably indicates that the frontend is doing something wrong, can update!

**Comment by rtibbles** [comment]
Fixed in #12049
