### ISSUE TITLE
User menu cut on wider resolutions

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1206]
## Summary

User menu gets cut off on some wider resolutions.

## System information

 - Version: 0.4.0alpha1.dev352
 - Operating system: Linux
 - Browser: Chrome & FF

## Screenshots

![kolibri - mozilla firefox_149](https://cloud.githubusercontent.com/assets/1457929/24876552/698e0aac-1e2c-11e7-87ee-13b43c05d4fb.png)

![kolibri - google chrome_145](https://cloud.githubusercontent.com/assets/1457929/24876565/76f10a3c-1e2c-11e7-9a75-e4218d7b0de4.png)

![manage users - kolibri - google chrome_144](https://cloud.githubusercontent.com/assets/1457929/24876578/822d320e-1e2c-11e7-8b7d-6f37d8c663e1.png)

![manage users - kolibri - google chrome_143](https://cloud.githubusercontent.com/assets/1457929/24876590/8a19223e-1e2c-11e7-8700-3d6866723811.png)

OK here:

![kolibri - google chrome_146](https://cloud.githubusercontent.com/assets/1457929/24876604/97d8a3cc-1e2c-11e7-9be6-a098430de1ed.png)

**Comment by christianmemije** [comment]
@radinamatic I cannot reproduce this. Can you reproduce this on Develop?

**Comment by radinamatic** [comment]
@christianmemije Latest `develop`, Chrome on Linux:

![classes - kolibri - google chrome_174](https://cloud.githubusercontent.com/assets/1457929/25398159/3d11ccc8-29eb-11e7-8c83-e2fa38aa37b5.png)

**Comment by radinamatic** [comment]
Firefox
![classes - kolibri - mozilla firefox_175](https://cloud.githubusercontent.com/assets/1457929/25398486/975a5c3a-29ec-11e7-9a14-a85bf7f458fe.png)

**Comment by DXCanas** [comment]
@radinamatic I am trying pretty hard to reproduce this, and I can't seem to get the behavior. Tried putting in the resolution manually and setting the presets to everything that starts with the word "laptop" too. 

@christianmemije did you say you were able to reproduce?

**Comment by christianmemije** [comment]
I was able to reproduce once, but never again...

**Comment by radinamatic** [comment]
Sorry people, I see this very often on my dev repo, but not necessarily in the responsive view (I keep resizing window a lot while making screenshots for docs). Latest develop, 2 minutes ago:

![learn - ck-12 - kolibri - google chrome_237](https://cloud.githubusercontent.com/assets/1457929/25877054/5a157518-3521-11e7-8742-096e52188b05.png)

I'll try it on a dev repo on my uni machine tomorrow, and see what happens...

**Comment by radinamatic** [comment]
For consolation, I don't remember seeing it in any of the versions I installed & tested on VMs... :wink:

**Comment by DXCanas** [comment]
This is using the pex file, correct? Have you tried it from a dev environment?

**Comment by radinamatic** [comment]
No, the above screenshot is from my dev environment, I don't recall seeing this in a PEX, at least not recently.

**Comment by DXCanas** [comment]
Hm. And this is latest, from Kolibri's `develop` branch?

**Comment by radinamatic** [comment]
Sorry, I had to fetch the latest, but the error persists:

![learn - ck-12 - kolibri - google chrome_242](https://cloud.githubusercontent.com/assets/1457929/25878017/ea34ab72-3527-11e7-9dc5-9945fd009529.png)
 
The menu does jumps back and forth as I resize the window, ducks under the edge and then comes back where it's supposed to be...

I'm running server in production, fyi.

**Comment by christianmemije** [comment]
Was able to reproduce. Seems to be an issue related to [Tether](https://github.com/HubSpot/tether)

Possibly https://github.com/HubSpot/tether/issues/248?

![cut](https://cloud.githubusercontent.com/assets/7193975/25907547/9803f9ae-355c-11e7-90aa-b4192ec1b662.gif)

**Comment by DXCanas** [comment]
Interesting - I was able to reproduce this, but only on the the `learn` plugin. It works everywhere else just fine

**Comment by DXCanas** [comment]
Alright. Dug deeper. Pretty sure @christianmemije is right. The calculations are off, one big reason is the mixed up `position` tag you see above (and mentioned inside of https://github.com/HubSpot/tether/issues/248).

**Comment by rtibbles** [comment]
Looks like this requires an upstream fix in tether, then a PR to Keen to update the dependency. Punting to 0.7, as seems unlikely to get fixed soon.

**Comment by christianmemije** [comment]
Since tether is no longer being actively maintained, this might require replacing tether with [Popper.js](https://github.com/FezVrasta/popper.js#installation) in keen-ui.

**Comment by indirectlylit** [comment]
this affects a small number of users and the cost of fixing it sounds high. removing 0.7 milestone

**Comment by radinamatic** [comment]
Annoying is what it is. 
I was trying to get the screenshot for the docs, and gave up at the end... :unamused: 

![cropped](https://user-images.githubusercontent.com/1457929/31962055-c468613c-b8fc-11e7-84a6-fd0e2153afde.png)

**Comment by indirectlylit** [comment]
oh for some reason I thought it only happened at specific resolutions for specific browsers

**Comment by christianmemije** [comment]
It's random, even when there is plenty of space in the app bar.

**Comment by radinamatic** [comment]
Now that I think of it, if I put a long enough username, it should probably work for a screenshot, but the bug remains...

**Comment by radinamatic** [comment]
And I can see it in [VF mocks](https://github.com/fle-internal/kolibri-instant-schools-plugin/pull/61#issuecomment-339039458) too, are we sure we want to leave it in 0.7?

**Comment by indirectlylit** [comment]
I'm just worried about it becoming a time sink. I'll add the milestone back, but let's be careful to pull the plug again if it looks like a big effort

**Comment by christianmemije** [comment]
Okay I managed to track down the issue. It stems from this line https://github.com/JosephusPaye/Keen-UI/blob/next/src/UiPopover.vue#L119

`window.innerWidth` appears to sometimes* give a larger width

![image](https://user-images.githubusercontent.com/7193975/32400542-d2128b7c-c0be-11e7-8f12-0a9157e5f607.png)

So simply moving the `window.innerWidth` to the end of these or statements should do the trick.

Result
![localhost_8000_learn_](https://user-images.githubusercontent.com/7193975/32400582-18fc0a40-c0bf-11e7-9b28-16d103e26067.png)

**Comment by indirectlylit** [comment]
As a work-around for the external library, we'll implement a fixed-position drop-down (relative to the button). Basically, since we know it's always at the top-right of the screen, we don't need any fancy tethering.
