### ISSUE TITLE
Improve loading state on learner quiz report page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12062]
## Observed behavior
In Kolibri, the loading state of the learner quiz report updates with each time you click from one question to another. It is _"too much loading state"_, and you lose your scroll position on the page as well as the focus. 

## Errors and logs
[Screencast from 04-08-2024 09_38_04 AM.webm](https://github.com/learningequality/kolibri/assets/17235236/7d982dca-2def-4bfe-a7ab-c5385cec817d)

## Expected behavior
While a loading state might still be useful for while the question data is fetched, it should be updated so that most of the page remains the same, and the loading spinner is only displayed within the question/attempt preview portion of the container.

## User-facing consequences
Jumpy, annoying user experience.

## Steps to reproduce
1. Assign a quiz to a learner, and have the learner user account complete and submit the quiz.
2. Reopen the completed quiz to see the quiz report 
3. Click among the questions - you will see that page state updates to "too broad" of a way, as demonstrated in the video above

## Context
0.16.x

**Comment by tanouh** [comment]
Hello, Can I be assigned to this issue ?

**Comment by LianaHarris360** [comment]
Hi @tanouh, thanks for showing interest in fixing this issue! The issues open for contributors have a `help wanted` label, you can check out some of those unassigned issues [here](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues).

**Comment by tanouh** [comment]
@LianaHarris360 Sure thanks for your reply !

**Comment by AlexVelezLl** [comment]
Closed by #12082
