### ISSUE TITLE
Fix loading state at Coach > Reports

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12126]
_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12082#issuecomment-2072372525_

> While regression testing I noticed that this is not fixed at Coach > Reports

https://github.com/learningequality/kolibri/assets/79847249/790c7c74-74f9-4fe5-9bad-38cfb161bddf

**Comment by rtibbles** [comment]
Fixed in #12178
