### ISSUE TITLE
Update Quiz creation to reference unique questions by way of the `item` property

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12127]
## Overview

Quiz questions use a composite ID joining the question's `exercise_id` (the Exercise it came from) and it's `question_id`, an ID for the question within that particular Exercise. This is to avoid collisions if two Exercises have the same `question_id` in them.

Elsewhere in the codebase, we use the same type and shape of ID -- for example, in logging.

In those cases, each question-shaped object has a property `item` to reference this unique ID.  We should do this everywhere!

## Acceptance criteria

- [ ] Update [quizCreationSpecs.js](https://github.com/learningequality/kolibri/blob/7368f265756eed7295267cf484b3fe9581881eaf/kolibri/plugins/coach/assets/src/composables/quizCreationSpecs.js#L58-L59) definition of `id` and change it to `item`. 
- [ ] Reviewing `useQuizCreation` `selectQuestions` and the components in `<coach>/../plan/CreateExamPage/*` - revise naming throughout to no longer reference "Question IDs" as a concept when, in fact, it is referencing the `Question Item`. The changes here should distinguish between a question's `question_id` -- in which case the naming convention referencing "Question ID" would make sense.

> For example, in `selectQuestions.js` the 4th parameter  `questionIdArrays`  is actually referencing a question's "item", so perhaps `questionItemArrays` would make more sense.

Similar instances can be found throughout ([ex1](https://github.com/learningequality/kolibri/blob/7368f265756eed7295267cf484b3fe9581881eaf/kolibri/plugins/coach/assets/src/composables/useQuizCreation.js#L103), [ex2](https://github.com/learningequality/kolibri/blob/7368f265756eed7295267cf484b3fe9581881eaf/kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ResourceSelection.vue#L580), [ex3](https://github.com/learningequality/kolibri/blob/7368f265756eed7295267cf484b3fe9581881eaf/kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue#L86)

**Comment by rtibbles** [comment]
This has been fixed in various places, but the last replacement happened in [#12353](https://github.com/learningequality/kolibri/pull/12353)
