### ISSUE TITLE
Handle Integrity Error in Django 3.2 Upgrade

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#12138]
## Observed behavior
Encountering integrity errors post-upgrade to Django 3.2 due to invalid data in the local database. Not sure how we got here but worth looking into.

## Errors and logs

```
[python-devserver] django.db.utils.IntegrityError: 
The row in table 'logger_usersessionlog' with primary key '905c3e6ef149e1b4bacddfe782ff906f' 
has an invalid foreign key: logger_usersessionlog.user_id 
contains a value '2f4536317ea71e134e84f0fb39698c02' 
that does not have a corresponding value in kolibriauth_facilityuser.id.
```

## Steps to reproduce
Upgrade to Django 3.2 
Reinstall  Python dependencies

## Context
develop

…

**Comment by rtibbles** [comment]
I took a look at the database where @AllanOXDi saw this issue, and it did seem contained to this single row. Still at a bit of a loss as to how this happened, but we could probably handle this during upgrade before the Django machinery is initialized by doing a `PRAGMA foreign_key_check;` statement and dealing with the results, probably just by deleting the offending rows.

**Comment by rtibbles** [comment]
I have flagged this as P0 for now, as although I think it is a highly unlikely scenario, it _has_ happened and if it happened to an end user, it would be unrecoverable without losing all data.
