### ISSUE TITLE
EQM: When deleting "quizzes" some do not get deleted 

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#12159]
## Observed behavior
when deleting  quizzes at once, some don't get deleted

## Errors a

https://github.com/learningequality/kolibri/assets/103313919/c95645fd-31a9-4b8a-802a-7b2be218dd91

## Expected behavior
When a user select all and click delete everything  should be deleted

## Steps to reproduce
go to add questions > select quizzes and click apply changes.
click select all > delete

## Context

Develop

**Comment by AlexVelezLl** [comment]
It seems that this is the intended behaviour 🤔 

![Image](https://github.com/learningequality/kolibri/assets/51239030/42203f17-bfa8-4c9e-a67f-3ce60856393a)
