### ISSUE TITLE
TypeError: Cannot read property '0' of null on CK-12 exercises

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1216]
## Summary

Might have something to do with the megamerge that happened yesterday, 'cause I tested these exercises on `0.3.1b2.dev4` last week, and were working fine.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: `0.4.0alpha1.dev495`
 - Operating system: Windows 7
 - Browser: all

## Traceback or relevant snippet from server.log or browser console

```
TypeError: Cannot read property '0' of null
    at a.setItemId (learn_module-0.4.0alpha1.dev495.js:9)
    at a.n [as setItemId] (default_frontend-0.4.0alpha1.dev495.js:formatted:3499)
    at a.nextQuestion (learn_module-0.4.0alpha1.dev495.js:9)
    at a.n [as nextQuestion] (default_frontend-0.4.0alpha1.dev495.js:formatted:3499)
    at a.sessionInitialized (learn_module-0.4.0alpha1.dev495.js:9)
    at n (default_frontend-0.4.0alpha1.dev495.js:formatted:3499)
    at a.<anonymous> (default_frontend-0.4.0alpha1.dev495.js:formatted:4267)
    at a.St.t.$emit (default_frontend-0.4.0alpha1.dev495.js:formatted:4527)
    at default_frontend-0.4.0alpha1.dev495.js:formatted:13586
```

### Chrome
![virtualbox_windows 7_12_04_2017_13_36_19](https://cloud.githubusercontent.com/assets/1457929/24956173/bc130a60-1f86-11e7-8d4f-3fcbdab2f69c.png)

### IE11
![virtualbox_windows 7_12_04_2017_13_47_57](https://cloud.githubusercontent.com/assets/1457929/24956286/3de2a65e-1f87-11e7-8ea5-8d9d2ee40ec7.png)

### Firefox just reports unspecific network error 🙄 
![virtualbox_windows 7_12_04_2017_13_46_37](https://cloud.githubusercontent.com/assets/1457929/24956303/5290adf8-1f87-11e7-9e84-67bb492c6998.png)

**Comment by rtibbles** [comment]
None of the fixes that we have made in v0.3.x have been propagated to latest develop as yet. Closing until we can confirm that this is independent of these issues.

**Comment by rtibbles** [comment]
Windows changes are now live in develop, please confirm, and reopen this if necessary.

**Comment by radinamatic** [comment]
Whatever that was it's not there anymore in [`0.4.0alpha1.dev511`](https://buildkite.com/learningequality/kolibri/builds/434#dc894453-b207-42c2-8dfa-337687a826cc)! :+1: 

![virtualbox_ie11 - win7_13_04_2017_17_49_41](https://cloud.githubusercontent.com/assets/1457929/25012963/527fa968-2072-11e7-9671-dc7479f77acd.png)
