### ISSUE TITLE
EQM - < 0.17 quizzes not showing "File size for download" value properly

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12163]
> Missing value for 'File size to download' when starting a quiz which was created on 0.15.2 but not started until after the upgrade:

Per @pcenov https://github.com/learningequality/kolibri/pull/12111#issuecomment-2102844230

This may take a bit of investigation but I suspect that it will be to do with something related to the Vuex route handlers. 

https://private-user-images.githubusercontent.com/79847249/329287611-19e6b35b-a305-4b37-92a5-c113d93713a6.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MzU1MjYsIm5iZiI6MTcxNTYzNTIyNiwicGF0aCI6Ii83OTg0NzI0OS8zMjkyODc2MTEtMTllNmIzNWItYTMwNS00YjM3LTkyYTUtYzExM2Q5MzcxM2E2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDIxMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNzgyNDdiYjc0ZDNiZjdmZDUwM2E0Yzg5NWI2N2QwZjRiYzQ4NmFjMGRiZmY0MWFkMTBmZGNiYTE0NTk5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Op3DvbH3ie3u36hEWSJbLDZSr7ak3Cm16MxtqmjMQE4

**Comment by AllanOXDi** [comment]
I will take a look.
