### ISSUE TITLE
Update eslint rules to use rules from eslint/vue where possible

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12199]
## Observed behavior
@MisRob created multiple custom eslint rules for Vue components, which she also contributed upstream to eslint/vue. Many of these rules are now in the main eslint/vue package.

## Expected behavior
We should use these rules from upstream (e.g. https://eslint.vuejs.org/rules/no-unused-properties.html#vue-no-unused-properties) where possible, and remove the code and tests for unused rules in this repository.

**Comment by shubh1007** [comment]
May I work on this issue?

**Comment by rtibbles** [comment]
Hi @shubh1007 - that would be great! Before work can begin fully on this, this PR https://github.com/learningequality/kolibri/pull/9698 must be merged, but we are hoping to do that this coming week.

In the meantime, looking at the existing custom rules we have for vue components, which you can find in here: https://github.com/learningequality/kolibri/tree/develop/packages/eslint-plugin-kolibri/lib/rules and then seeing which ones will be redundant once we upgrade our vue eslint plugin version (see here for the complete list: https://eslint.vuejs.org/rules/) would be a great start!

I'll assign you, and if you can make a note of which rules you think you'll need to switch over in this issue, that would be super!

**Comment by shubh1007** [comment]
Since the PR #9698 has been merged, I want to work upon this issue. Please describe the problem briefly so that I can understand the problem properly and resolve the issue. 
Thank you.

**Comment by rtibbles** [comment]
We have some rules in our custom rules https://github.com/learningequality/kolibri/tree/develop/packages/eslint-plugin-kolibri/lib/rules that have equivalents in https://eslint.vuejs.org/rules/

Find the ones that we can remove from our custom rules and use the eslint/vuejs rules instead.

**Comment by MisRob** [comment]
Hi @shubh1007, are you working on planning to work on this, or would it be better to unassign?

**Comment by shubh1007** [comment]
You can unassign the task.

**Comment by MisRob** [comment]
Alright, thanks for letting us know @shubh1007. Best wishes
