### ISSUE TITLE
Change learning facility - Getting a 400 error "Invalid_username" while changing the facility

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12191]
## Observed behavior

When the `Require password for learners` option at `Facility > Settings` is left unchecked and I attempt to change my facility from an 'On my own' device, then I am getting into an infinite loop:

https://github.com/learningequality/kolibri/assets/79847249/d538e64b-f730-4339-81a3-5b12dc1daa9c

I checked the 0.16.1 version of Kolibri and it's extant there as well.

## Expected behavior

It should be possible to change the learning facility.

## Steps to reproduce the issue

1. Install Kolibri 0.16.2b2 on two devices one of which is of type 'Formal facility' and the other one is an 'On my own'
2. On the 'On my own' device go to the Profile page and click the 'Change' button
3. Keep clicking the 'Continue' button and observe that clicking 'Continue' at 'Confirm account username' brings the user back to 'Change learning facility'.

##Logs

[on-my-own-logs.zip](https://github.com/learningequality/kolibri/files/15405325/on-my-own-logs.zip)

[server-logs.zip](https://github.com/learningequality/kolibri/files/15405338/server-logs.zip)

## Usage Details
Kolibri 0.16.2b2
Windows 11, Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@marcellamaki This is not a regression but looks serious... 🤔

**Comment by marcellamaki** [comment]
yes, we will fix this for the patch. Thank you @pcenov !

**Comment by rtibbles** [comment]
Fixed in #12193
