### ISSUE TITLE
Create composable for connection monitoring and replace existing logic with it

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12205]
Currently, connection monitoring is handled by [vuex state](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/connection.js), this can be replaced by an internal facing (not exposed in the core API) composable module that defines state at the module level in order to provide a global record of connection monitoring.

**Comment by nathanaelg16** [comment]
Hi @rtibbles, can I try this issue?

**Comment by AlexVelezLl** [comment]
Hi @nathanaelg16. For sure! Thanks for your interest in taking this. I will assign you this issue! Please let us know if you have any questions.
