### ISSUE TITLE
Create composable for snackbar state and replace existing logic with it

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12206]
Currently the snackbar state is handled by [vuex state](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/snackbar.js).

This should be replaced by a composable module exposed on the core API that provides access to the state and methods for manipulating the snackbar. All state should be stored in the module to provide a global store.

**Comment by nathanaelg16** [comment]
Hi @rtibbles, I'd like to try this issue.

**Comment by rtibbles** [comment]
Sure, you'll be an expert at this soon!

**Comment by nathanaelg16** [comment]
Quick question @rtibbles, should the [legacy snackbar module](https://github.com/learningequality/kolibri/blob/22063f96d8264070f4679bd6371f02fb45acc0a5/kolibri/core/assets/src/state/modules/snackbar.js) be removed as part of this issue or should we keep it in for now?

**Comment by rtibbles** [comment]
Yes, let's also delete the legacy code as part of the cleanup - that will help us see if we've missed anything in the switchover too!
