### ISSUE TITLE
Migrate all existing references to session getters and state to the useUser composable

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12203]
The useUser composable now encapsulates all the vuex getters and state for the session, we should migrate all references to these to instead import the useUser composable and read from there.

See the composable for the full list of getters and state that will need to be remapped: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/composables/useUser.js#L36

Note, this will not involve removing the session vuex module.

**Comment by nathanaelg16** [comment]
Hi @rtibbles, can I try this issue?

**Comment by rtibbles** [comment]
Hi @nathanaelg16 - yes, please do!

When you make a pull request, I'd suggest making a commit 'per plugin' (learn, coach, etc. and one for the core references).

**Comment by rtibbles** [comment]
Fixed in #12438 and #12611
