### ISSUE TITLE
Mac app's Sign-in page - The footer section is not displayed correctly

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12212]
## Observed behavior

After the changes made in https://github.com/learningequality/kolibri/pull/12208 the footer section at the Sign-in page when viewed in the Mac app is not displayed correctly - it's entirely covered by the background image and the part with "Kolibri 0.16.2b3 Usage and privacy • Photo credit: Lewa Wildlife Conservancy" is missing.

![2024-05-27_11-58-04](https://github.com/learningequality/kolibri/assets/79847249/a5a3f889-679d-47cd-93d5-1e36b575275a)

## Expected behavior

The footer section should be displayed correctly.

## Steps to reproduce the issue

1. Install Kolibri 0.16.2b3 on a Mac device.
2. Open the app and after setting up Kolibri sign out to go to the Sign-in page.
3. Observe the footer.

## Usage Details
Kolibri 0.16.2b3
MacOS Sonoma 14.4.1

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Hrm, guessing this is a Safari specific bug.

**Comment by pcenov** [comment]
Yes, this is the same in Safari 17.4.1

**Comment by rtibbles** [comment]
Yeah, I've just replicated in Safari 15.6 as well.

**Comment by rtibbles** [comment]
Fixed in #12213
