### ISSUE TITLE
Unable to stop the server: kolibri-stop.bat in the wrong Python folder

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1222]
## Summary

_Are the installer issues now to be filed here? Move if necessary..._

My guess is that this is because there was the switch from Python 3 to Python 2, and the `kolibri-stop.bat` script was left behind. 

Tried and failed to stop the server form the task tray. Opened the `Python27/Scripts` folder to stop it from the command prompt and noticed there was a `Python34/Scripts` folder even though not Python 3 was installed on the system. Run the `kolibri-stop.bat` script thatwas inside and the server stopped.

## System information

 - Version: `0.4.0alpha1.dev511`
 - Operating system: Windows 7
 - Browser: all

## Screenshots

![virtualbox_ie11 - win7_13_04_2017_17_35_12](https://cloud.githubusercontent.com/assets/1457929/25013680/dedf4182-2074-11e7-93b6-452cfd8e0f62.png)

**Comment by mrpau-richard** [comment]
@radinamatic moving this at kolibri Installers issue.
