### ISSUE TITLE
Some state-management strangeness in EQM creation workflow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12233]
## Observed behavior

When exploring some of the routing behavior in EQM during 0.18 planning, I noticed that there were some inconsistent behaviors when navigating through the resource tree. Although there are a few variations that appear in the UI, the main problem seems to be when a user begins adding resources without saving them, and navigates away from the side panel.

## Errors and logs

If I start selecting resources and click out, sometimes when I reopen the exercise panel I see various "mismatched" states:

|   |   |
|---|---|
| Resource indicated as selected in the bottom count, but not checked; can't save | <img width="700" alt="Screenshot 2024-05-30 at 4 48 53 PM" src="https://github.com/learningequality/kolibri/assets/17235236/6280503b-0318-427b-98df-2d9a4fb9a581"> |
| Resource properly selected, but can't save changes | <img width="1433" alt="Screenshot 2024-05-30 at 4 49 08 PM" src="https://github.com/learningequality/kolibri/assets/17235236/94f3d39d-d594-4616-b311-8251d771f937"> |
| UI is very confusing. Maybe UX writing/indeterminate state would help  | <img width="700" alt="Screenshot 2024-05-30 at 4 48 53 PM" src="https://github.com/learningequality/kolibri/assets/17235236/c1452109-1dd7-4558-9af8-2eb215946123"> |

## Expected behavior
There should be consistency within the UI (and within the frontend data structures) of what the current state is. If resources are new and selected, the user should be able to save. Alternatively, the state should not persist when the user navigates away from the side panel (i.e. by exiting or clicking on the backdrop). 

## User-facing consequences
Confusiong, 

## Steps to reproduce
1. Begin adding resources to a new section of a quiz
2. Select at least a few questions within a resource 
3. Do not save. Navigate away from the page by clicking the backdrop or hitting `esc`
4. Reopen the side panel and resume
5. Observe mismatched state

## Context
`develop` / Chrome

**Comment by rtibbles** [comment]
It seems like per my and @marcellamaki's investigations, these issues have been resolved. Will file more specific follow up issues if needed.
