### ISSUE TITLE
Character encoding in CK-12 exercise

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1223]
## Summary

So far found on this one exercise, but there could be more... Not sure if it has anything to do with the `fontdata.js` not loading.

## System information

 - Version: `0.3.1beta3.dev2`
 - Operating system: Windows 7
 - Browser: Firefox and Chrome 

## Screenshots

![virtualbox_ie11 - win7_13_04_2017_18_57_35](https://cloud.githubusercontent.com/assets/1457929/25016975/4fe493a2-2082-11e7-9d2f-fd5ece9f0c86.png)

![virtualbox_ie11 - win7_13_04_2017_18_57_35](https://cloud.githubusercontent.com/assets/1457929/25016791/a524b1cc-2081-11e7-93f6-54d284ea8324.png)

**Comment by indirectlylit** [comment]
I believe this may be addressed? cc @jamalex

**Comment by jamalex** [comment]
I couldn't replicate it when re-running the pipeline locally. Let me test on the demo server and republish if necessary.

**Comment by radinamatic** [comment]
I've seen it this morning in the latest `develop`, sorry.

**Comment by jamalex** [comment]
It's not actually a Kolibri issue, it's a content pipeline issue, so republishing and reimporting may fix it -- checking

**Comment by radinamatic** [comment]
If I recall well, it appeared when previewing exercises while creating Exam.

**Comment by jamalex** [comment]
It'll appear everywhere the exercise appears in Kolibri, until the source content is fixed

**Comment by radinamatic** [comment]
Ok, waiting for re-publish to do the re-import!

**Comment by jamalex** [comment]
It's got 3798 exercises to rebuild, which will take a while -- leaving it running for a while!

**Comment by jamalex** [comment]
Had to make some additional fixes (https://github.com/fle-internal/sushi-chef-ck12/pull/2); running again now.

**Comment by radinamatic** [comment]
I'm guessing it did not finish building all - I just re-imported the CK-12 channel on my dev repo, but those strings are still visible:

<img width="1779" alt="ck12-encoding" src="https://cloud.githubusercontent.com/assets/1457929/25902060/bfebcca8-3598-11e7-8483-3b326cbb9d1c.png">

**Comment by jamalex** [comment]
Woohoo! Seems to be fixed: https://kolibridemo.learningequality.org/learn/#/recommended/1d8f6d84618153c18c695d85074952a7/content/3e9dc5679ce55f34beed7e1e2aea97a9
