### ISSUE TITLE
Implement backend sorting of users data for Facility -> Users table

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#12234]
## Overview

To be able to add sorting for Facility -> Users table as designed here

![table](https://github.com/learningequality/kolibri/assets/13509191/e0d697ac-85c6-4bc6-8f86-651a6a5d0ec0)

backend needs to be able to return sorted data.

Backend sorting is expected to work for:
- Full name
- User name
- Identifier
- Gender
- Birth year
- Date created

Note that sorting in this case can't be done on frontend as here we use paginated data that is loaded lazily.

### Outcomes

- Backend can optionally return sorted (ascending/descending) data mentioned above

### Out of scope

- Implementing the whole sorting feature (to be possibly done as part of a GSOC project)
- There's currently no information on 'Date added` on backend so this won't be returned
- Note that 'Date created' is not yet visible in the current table UI but are planned to be added. Even though making the columns visible on frontend is not in the scope of this issue, sorting is expected to work for them as these two fields are the main motivation for the sorting feature in this table.

**Comment by MisRob** [comment]
This is related place in code https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/facility/assets/src/views/UserPage/index.vue#L38-L45

**Comment by rtibbles** [comment]
This would need to be done using the OrderingFilter defined here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/api.py#L58

Which is a reimplementation of the DRF OrderingFilter documented here: https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter

It should work fairly easily out of the box.

**Comment by MisRob** [comment]
Also note that I think that as part of this work, "date_created" and "date_added" will need to be added to the facility users response (endpoint `api/auth/facilityuser/?member_of=37b644ecd03062f21a54452f84cfadb6&page=1&page_size=30`). I originally assumed we may have it available already, but is not the case:

![Screenshot from 2024-06-13 10-13-38](https://github.com/learningequality/kolibri/assets/13509191/4f04a924-7a26-4dab-a429-29d5a6c62906)

**Comment by MisRob** [comment]
As agreed with @ozer550 and @rtibbles, I removed "Date added" requirements since that is currently not available on backend
