### ISSUE TITLE
When creating/editing a quiz, clicking the Save button results in immediately closing the modal

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12245]
When creating/editing a quiz, clicking the Save button results in immediately closing the modal:

https://github.com/learningequality/kolibri/assets/79847249/cf2727b2-bdee-45db-9bb2-92feaa915cc6

seems like either the button should be 'Save & Close' with another 'Save' button for saving without closing, or there should be a confirmation modal.

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12232#issuecomment-2149416020_

**Comment by nucleogenesis** [comment]
Closed by #12182 adding a "Save and close" button next to the "Save" button -- that said, #12263 is tracking a follow-up issue.
