### ISSUE TITLE
When editing a quiz I cannot replace a questions

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12246]
When editing a quiz I cannot replace a question because clicking the checkbox of a question results in selecting all the questions:

https://github.com/learningequality/kolibri/assets/79847249/d5219dc0-0636-4126-96eb-75ef65528075

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12232#issuecomment-2149416020_

**Comment by pcenov** [comment]
Hi @nucleogenesis, while testing with the [latest build](https://github.com/learningequality/kolibri/suites/24783179278/artifacts/1590673777) in https://github.com/learningequality/kolibri/pull/12182 I noticed that it's still not possible to replace the questions when editing a quiz. I'm seeing a `TypeError: Cannot read properties of undefined (reading 'length')` error in the console:

https://github.com/learningequality/kolibri/assets/79847249/6a34772b-54d0-4d70-8c60-b7e027520889

**Comment by nucleogenesis** [comment]
Seems to have been finally closed by #12274
