### ISSUE TITLE
Setup the database that stores all the errors raised during runtime

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12244]
## Overview
This issues involves setting up the database that stores all the errors raised from the frontend and backend during runtime.

## Description and outcomes
- Add a new sqlite database in [sqlite_db_names.py](https://github.com/learningequality/kolibri/blob/80939fe789ed169504862415c4441d0ba37e932f/kolibri/deployment/default/sqlite_db_names.py#L14), with the name `errors`, to store all the errors that are traced from the frontend and the backend.
- Create an app called `errorsreports` to handle all error reporting related logic in `kolibri/core/`. Remember to add the new app to the list of `INSTALLED_APPS`.
- Add a [database router](https://github.com/learningequality/kolibri/blob/09297be74fa5239a1e0a5da218e13d2281a8ad18/kolibri/deployment/default/settings/base.py#L161-L165) for the `errors` database, and implement the database's routing behavior in `kolibri.core.errors.models.ErrorsRouter`.
- All error related reads and writes, regardless of the application they originate from, should be routed to the `errorsreports` app database.
- Run a migration to create the new sqlite database.

## Acceptance Criteria
- An app called `errorsreports` has been created in `kolibri/core/`
- Database migration has been executed and a new database `errors.sqlite3` has been created in `KOLIBRI_HOME`, in the default or specified location.
- All error related reads and writes, regardless of the application they originate from, are routed to the `errorsreports` app database.

## Assumptions and Dependencies
NA

## Scope
This shall cover:
- Creating the errors app
- Implementing the routing behavior for the errors database
- Running the migration to create the new database

It doesn’t include;
- Implementing the model that will store the reported errors

## Accessibility Requirements
NA

## Resources
- [ Multiple databases in Django](https://docs.djangoproject.com/en/3.2/topics/db/multi-db/)

**Comment by akolson** [comment]
@thesujai First task is ready for you to take on! 🎉

**Comment by thesujai** [comment]
Thank You!
Feel free to assign me 😄

**Comment by akolson** [comment]
implemented with https://github.com/learningequality/kolibri/pull/12250
