### ISSUE TITLE
When editing a quiz the 'Question order' value is always displayed as 'Randomized'

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12248]
When editing a quiz the 'Question order' value is always displayed as 'Randomized'. Note that it's not clear what should happen if I have both sections with randomized and fixed order:

https://github.com/learningequality/kolibri/assets/79847249/7d130fd4-fe55-41df-8a96-aeab91553626

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/12232#issuecomment-2149416020_

**Comment by Tweniee** [comment]
more info

**Comment by LianaHarris360** [comment]
Hi @Tweniee, there are still some decisions that need to be made before work on this issue can begin. The issues open for contributors have a help wanted label, you can take a look at some of those unassigned issues [here](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues).

**Comment by rtibbles** [comment]
In discussion with @nucleogenesis - it seems that this top level randomize property should now actually be for the order of the sections, so the copy needs to be updated to reflect that at a minimum.
