### ISSUE TITLE
Implement the ErrorReport model

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12257]
## Overview
This issue implements a model that stores error reports

## Description and outcomes
- Create  a new model named `ErrorReports` in the `errorreports` app with the following attributes:
    - `error_from`: To know if the error is from frontend or the backend
        - Type: `CharField`, `Enum`
        - Length: 10, either frontend or backend
    - `error_message`: The actual error message, like ‘Operational Error’
        - Type: `CharField`
        - Length: 255
    - `traceback`, containing meaningful stack traces
        - `Type`: `TextField`
    - `first_occured`: The time the error first occurred in UTC
        - Type: `DateTimeField`
        - Default: `timezone.now`
    - `last_occured`: If the same error reoccurs, this will be set to the time of recurrence, otherwise the `first_occured` time is set
        - Type: `DateTimeField`
        - Default: `timezone.now`
    - `sent`: Send the status of the error.
        - Type: `BooleanField`
        - Default: `False`
    - `no_of_errors`: Number of occurrences of a specific error. This will help with the prioritization of errors
        - Type: `IntegerField`
        - Default: 1.
- Run the migrations for the model
- Create the following methods to manipulate the `ErrorReports`. These methods shall be `classmethods`, defined inside `ErrorReports` class.
    - `insert_or_update_error`: This shall create a new error object, and also update an existing error if `error_message` and `traceback` match with an existing object. Even if `sent` is `true`, update `last_occured` and `no_of_errors`
    - `get_unsent_errors`: This shall return the tuple of errors that have `sent` field as `false`(unreported errors)
    - `delete_error`: A little out-of-scope for now, as the deletion logic of reported errors is not yet finalized(Might be implemented with cronJob or something similar later on)
    - `mark_as_sent`: It should set the sent field of the object. So need not be a class method
- For each of the methods above, If `DEVELOPER_MODE` is `true`, then skip updating the model and just log the error else update the model

## Acceptance Criteria
- Model is migrated
- `insert_or_update_error()' and `get_unsent_errors()` are implemented as mentioned. `delete_error()` can just do nothing for now(add ellipsis)
- Test are written to verify correctness of the created model, ensure that the methods below work correctly and that errors are only logged into the database in `DEVELOPER_MODE`. The methods include;
    - `insert_or_update_error()`
    - `get_unsent_errors()`
    - `mark_as_sent()`
 
## Assumptions and Dependencies
- Django will handle the table updating

## Scope
- Creating new model
- Running migration
- Defining the `db_utils` functions
- Writing tests to ensure the functions work properly

## Accessibility Requirements
NA

## Resources
- [Django Models](https://docs.djangoproject.com/en/3.2/topics/db/models/)
- [Class Methods](https://docs.djangoproject.com/en/3.2/topics/db/models/)

**Comment by akolson** [comment]
Hi @thesujai, please comment so we can assign you this!

**Comment by thesujai** [comment]
Yes ready to go!

**Comment by akolson** [comment]
Closed by https://github.com/learningequality/kolibri/pull/12255
