### ISSUE TITLE
Create a middleware to catch backend exceptions

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12258]
## Overview
This issue creates a middleware that will catch the exceptions in the backend

## Description and outcomes
- Create a middleware in `errorreports` app that catches all the runtime exceptions. This middleware uses [process_exception](https://docs.djangoproject.com/en/3.2/topics/http/middleware/#process-exception) middleware hook of Django to insert error entries into the `ErrorReports` model, using `insert_or_update_error()` 
- Don't forget to add middleware to this

## Acceptance Criteria
- Middleware catches all the runtime errors and logs them. 
- Middleware is added to https://github.com/learningequality/kolibri/blob/develop/kolibri/deployment/default/settings/base.py#L92 
- Tests are written to ensure that the middleware works correctly.
 
## Assumptions and Dependencies
- `process_exception` catches exceptions raised by view functions, and other middleware components that dont handle exceptions themselves. There are edge case errors that could be raised in the context of the backend. As such a follow-up issue is necessary to cater for the edge case.

## Scope
- Implementing the middleware that catches all the backend error

Out-of-Scope:
- Catching frontend errors

## Accessibility Requirements
NA

## Resources
- [process-exception](https://docs.djangoproject.com/en/3.2/topics/http/middleware/#process-exception)
- [Example middleware](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/middleware.py)

**Comment by akolson** [comment]
@thesujai another one here!

**Comment by thesujai** [comment]
Yes ready to go!

**Comment by akolson** [comment]
Closed by https://github.com/learningequality/kolibri/pull/12260
