### ISSUE TITLE
Implement the /api/errorreports/report endpoint

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12259]
## Overview
This issue creates an API endpoint `/api/errorreports/report ` to capture and store reports from the frontend

## Description and outcomes
- Create a new API that will store all the errors from frontend to the database.
- The API should consist of:
    - Endpoint: `/api/errorreports/report`
    - Method: `POST`
    - Request Body: 
    ```json
    {
        "error_message": "OperationalError",
        "traceback": "Traceback (most recent call last): File \"main.py\", line 9, in <module> do_stuff() File \"main.py\", line 5, in do_stuff raise Exception(\"test exception\") Exception: test exception"
    }
    ```
    - Return: `HTTP 200` 
    ```json
    {
        "error_id": "9030c6ff1e43400496bbf50506a84d4f"
    }
    ```
    - View: `report()` view that validates the data and calls `insert_or_update_error()` and returns HTTP 200.  `error_from` is defaulted to `frontend` for this view.
- Create a serializer `ErrorReportsSerializer` that validates data in the `report()` view
- Route the new API endpoint correctly

## Acceptance Criteria
- New API that captures and stores errors from frontend 
- API routed from `core/api_urls.py` to `core/errorreports/api_urls.py` to final core/errorreports/api.py:report()
- Test case are written to ensure:
    - Errors are saved into `ErrorReports` when not in developer mode
    - Errors are not saved into `ErrorReports` when in developer mode
    - API validates data properly.
 
## Assumptions and Dependencies
NA

## Scope
- Creating a new API endpoint
- Routing new API endpoint
- Test cases for new API

Out-of-Scope
- Calling the endpoint from frontend

## Accessibility Requirements
NA

## Resources
- [Function based views](https://www.django-rest-framework.org/api-guide/views/#function-based-views)

**Comment by akolson** [comment]
@thesujai!

**Comment by thesujai** [comment]
All set to start this!

**Comment by akolson** [comment]
Closed by https://github.com/learningequality/kolibri/pull/12261
