### ISSUE TITLE
EQM: Section form validation improvements

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12262]
## Overview

Follow-up to comments [here](https://github.com/learningequality/kolibri/pull/12182#issuecomment-2154983044).

Overall, this issue is to address the issues reported by Peter. The changes in that PR which introduced these issues are in [this commit](https://github.com/learningequality/kolibri/pull/12182/commits/599460b7aa124ec41534cfbfeb3a5470491c0474) 

At a high level, we need to be sure that the form's validation flags are being set appropriately as things happen. It feels to me like there are a lot more moving parts than should be necessary, but refactoring the whole thing proprly be more work than it's worth at this point, so some key things to consider:

- `KTextbox` props - `showInvalidText` is a sort of override saying "show errors no matter what when true", whereas `invalidText` is the text and `invalid` is just telling `KTextbox` "this is invalid, do with it what you will" (_I'm sorry... I added that prop but now I regret it lol_
- The error messages should show when the user needs to know it -- for example, when they're currently typing into the title box, if their title is a dupe, we show the error, but if they're not focusing it, then we hide it -- but if they click to submit, we focus the title and show the error.

- [ ] Cannot make sections with duplicate titles
- [ ] Improved validations UX (consider reaching out in #kolibri-dev for guidance if you have questions about the best UX for a particular item)

**Comment by nucleogenesis** [comment]
Be sure that we focus & scrollTo the topmost error validation.

Also include a "Are you sure?" message for top-most quiz.

**Comment by marcellamaki** [comment]
Example of focus/scroll to on mobile being particularly helpful. Also router navigation guards so that when a user can't accidentally (or unthinkingly) just close out of the modal and lose the quiz



https://github.com/learningequality/kolibri/assets/17235236/a5827708-f1b0-451e-9c50-0cc8f8caf94c
