### ISSUE TITLE
Add the runtime error tracking mechanism for frontend

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12284]
## Overview
This task implements the runtime error tracking mechanism for the frontend.

## Description and outcomes
- Track all unexpected runtime errors that may occur in the frontend.
- The errors should be traced by using three mechanisms:
    - [Vue Error Handler](https://vuejs.org/api/application.html#app-config-errorhandler)
    - [Window: error event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#examples)
    - [Window: Window: unhandledrejection event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#examples)
- The configuration should be added in `kolibri/core/assets/src/core-app/index.js`.
- Create a function `report()` inside `kolibri/core/assets/src/utils` that is called from the error handlers. The `report()` function posts the error to the [api/errorreports/report](https://github.com/learningequality/kolibri/pull/12261) endpoint. For example:
```bash
curl -X POST http://localhost:8000/api/errorreports/report   
       -H "Content-Type: application/json"   
       -d '{
       	    "error_message": "An example error occurred",
       	    "traceback": "Traceback (most recent call last): ..."
     	}' 
```

## Acceptance Criteria
- All possible runtime exceptions in the frontend are caught.
- `report()` is called whenever the error is reported and makes a post request to `api/errorreports/report`.
- Appropriate tests are written to verify correctness of implementation.
 
## Assumptions and Dependencies
- Implementing [Vue Error Handler](https://vuejs.org/api/application.html#app-config-errorhandler), [Window: error event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#examples), and [Window: Window: unhandledrejection event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#examples) should catch all frontend errors to a satisfactory degree.

## Scope
- Implementing `report()` to make post request.
- Tracking frontend unhandled errors and calling `report()`.

## Accessibility Requirements
NA

## Resources
- [Vue Error Handler](https://vuejs.org/api/application.html#app-config-errorhandler)
- [Window: error event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event#examples)
- [Window: unhandledrejection event](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event#examples)
- [Example: Handling errors in Vue.js](https://www.raymondcamden.com/2019/05/01/handling-errors-in-vuejs#error-handling-technique-one%3A-errorhandler)

**Comment by akolson** [comment]
@thesujai 🙂

**Comment by thesujai** [comment]
All set to go!

**Comment by akolson** [comment]
Closed by https://github.com/learningequality/kolibri/pull/12291
