### ISSUE TITLE
Cannot edit the section order of a started quiz

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12289]
## Observed behavior

Observed while regression testing the changes made in https://github.com/learningequality/kolibri/pull/12278:

If I have created and started a quiz, when I go to edit it and change the section order then the quiz can no longer be saved and there is a 400 error in the console: `Cannot update learners_see_fixed_order on an Exam object`

![cannotupdate](https://github.com/learningequality/kolibri/assets/79847249/61edf7e1-50f1-4a43-977b-f3feeb1271f2)

Logs:

[logs.zip](https://github.com/user-attachments/files/15872595/logs.zip)

Video:

https://github.com/learningequality/kolibri/assets/79847249/3eb6a6ad-75aa-4df4-ba5e-08967bc95f24

## Expected behavior

To be further discussed whether it should be possible to update the section order of a started quiz.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12278
2. Import the exercises from the QA channel.
3. Create a quiz, save it and start it.
4. Attempt to change the section order of the quiz by editing it.

## Usage Details
Kolibri [kolibri_0.16.2a0.dev0+git.1258.g6ca0dd28-0ubuntu1_all.deb](https://github.com/learningequality/kolibri/suites/24928253877/artifacts/1603675275)
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Hrm, good point - I had disallowed this from the backend, but as it doesn't change the content of the quiz, I think this is actually safe.

And at the very least, the UI should only allow what the API allows!
