### ISSUE TITLE
devserver: ctrl+c does not always kill subprocesses

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#123]
running 

``` bash
kolibri manage --debug devserver -- --webpack
```

and then Ctrl-c to quit.

Occasionally the `node` watch process remains running in the background, and changes to files will cause a re-build.

**Comment by benjaoming** [comment]
I think we've established that there is a certain Django thing that causes this behaviour and we need to revert to  `runserver`.

@rtibbles :
> @benjaoming: Hrm, seems like there mightbe a good reason to overload the runserver command: https://github.com/django/django/blob/master/django/core/management/__init__.py#L328 hardcoded in the source!

**Comment by rtibbles** [comment]
I am not *completely* certain that this is the cause, as all this does is allow the autoreloader to start even if there is an error in the Django source code.

**Comment by indirectlylit** [comment]
this is still an issue - `node` processes tend to build up over time and must be manually killed

**Comment by indirectlylit** [comment]
I haven't seen this in a while

**Comment by rtibbles** [comment]
I have, on occasion, but I think `killall node` is the only surefire recourse.

**Comment by rtibbles** [comment]
I think should have finally been resolved by #3360
