### ISSUE TITLE
EQM: Delete section bugs

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12303]
## Overview

Reported by @MisRob on [Notion](https://www.notion.so/learningequality/Getting-an-are-you-sure-you-want-to-leave-on-Save-and-Close-button-82d0a84e15ef40dc82f7e8be236cff90)

> Using TAB in the delete section modal takes me to CANCEL button, then to the DELETE button and then outside the modal, instead of being trapped within it and returning to CANCEL

[Also here ](https://www.notion.so/learningequality/Clicking-the-CANCEL-button-on-the-section-deletion-confirmation-modal-does-nothing-553307b27d424d2281af9c8a2996402c)

![bug-3](https://github.com/learningequality/kolibri/assets/6356129/4e6217ce-6a6a-441a-bf76-fc1183d63462)

**Comment by MisRob** [comment]
I also reported that ESC key doesn't close the modal so it's potentially larger a11y ussye

**Comment by MisRob** [comment]
I also reported that ESC key doesn't close the modal so it's potentially larger a11y issue. Also note I haven't tested other modals in the new feature (if there are any) so would be good to check on it.
