### ISSUE TITLE
EQM Bug: Cannot navigate to channel in resource selection if it's the only one?

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12302]
## Overview

Reported by @LianaHarris360 in [Notion](https://www.notion.so/learningequality/Getting-an-are-you-sure-you-want-to-leave-on-Save-and-Close-button-82d0a84e15ef40dc82f7e8be236cff90) (see video there as well)

Kolibri Home folder linked [here](https://learningequality.slack.com/archives/C05FSV4BEJ1/p1718656475097349?thread_ts=1718654878.969419&cid=C05FSV4BEJ1) can be used to replicate.

### My experience

- Go to make a quiz, open the resource selection, you cannot click into CK-12
- Go to Library, see that there _are_ some exercises available there in CK-12
- Import `nakav-mafak` from Studio, only the "Exercises" folder
- Go to make a quiz, now you can go into both CK-12 to find the resources you should have seen before and you can go into the QA channel just fine

No errors in console... so this is kind of a weird one so hopefully diving into wherever channels are being fetched and transformed will make it obvious where the issue is here.

**Comment by rtibbles** [comment]
~Note, this issue is specific to CK-12, and does not replicate with other channels.~

Sorry, this is actually due to having channels that do not have practice quizzes in them - the simple button was not linking correctly.
