### ISSUE TITLE
Errors in perseus renderer from possibly mismatched answer state

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12322]
when answering the questions in a quiz it seems that the focus is not in the input field so that the selected value from the keyboard is not entered in the field. But even if I manually input it sometimes it just disappears when I revisit the question:

https://github.com/learningequality/kolibri/assets/79847249/55dc7acf-d412-4bfd-accf-34de915cf470

Here's the error in the console:
[browser-console-error.log](https://github.com/user-attachments/files/15903277/browser-console-error.log)

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/9759#issuecomment-2179033123_

**Comment by pcenov** [comment]
Hi @rtibbles - here's the DB as requested: [logs_DB.zip](https://github.com/user-attachments/files/15910480/logs_DB.zip)
