### ISSUE TITLE
Select a quiz - Possible confusion caused by the 'Changes saved successfully' message

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12333]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/12312 - When I select a quiz I see the 'Changes saved successfully' message. If I decide to close the modal, then I see a confirmation modal informing me that "You will lose any unsaved edits to your work". Since I don't think that I have unsaved edits I go ahead and click 'Continue' which results in actually losing the entire quiz. 

A similar confusion can occur even when creating a quiz from scratch as I might have entered the title of the quiz and just added some questions in which case I will also see the 'Changes saved successfully' message prior to exiting the quiz. 

Video:

https://github.com/learningequality/kolibri/assets/79847249/34432cb0-8450-443d-bf57-a0a6684ff4ce

## Expected behavior

It should be further discussed how to convey to the user clearly whether the entire quiz is saved or just some modifications made to the sections.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12312
2. Observe the steps in the provided video.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
I think the simplest solution here is simply to only show this snackbar when changes have actually been saved - i.e. when the 'save' button has been clicked.
