### ISSUE TITLE
Issues when creating a quiz without having imported resources or users enrolled in the class

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12330]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/12312 - if there are no imported channels and/or no imported users then we are not showing appropriate messages to the coach:

Videos:

https://github.com/learningequality/kolibri/assets/79847249/6aa47f65-773c-4a32-86f1-20ded1c5d6f2

https://github.com/learningequality/kolibri/assets/79847249/454e450d-3ebe-4285-962b-7644f0549bd8

## Expected behavior

1. If there are no imported channels, when attempting to add questions users should see a modal informing them that there are no imported resources.
2. If there are no learners enrolled in the class that should also be explicitly stated.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12312
2. Attempt to add questions to a quiz without having imported any channels with exercises before that.
3. Attempt to assign the quiz to a learner without having enrolled learners in the class.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Strings have been added separately, UI updates will happen post-string-freeze
