### ISSUE TITLE
Quiz - Deleting an unsaved section brings the user to a collapsed previous section

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12332]
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/12312 - Deleting an unsaved section brings the user to a collapsed previous section which is confusing. There's a `TypeError: Cannot read properties of undefined (reading 'questions')` in the console.

Video:

https://github.com/learningequality/kolibri/assets/79847249/7ddc6a7b-6cc4-4f52-8dc1-41aeb30cbdd7

## Expected behavior

All the questions of the previous section should be visible.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12312
2. Observe the steps in the provided video.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Seems like we need to make sure to navigate to the previous section when this happens - I thought I had added logic for this, but perhaps it's not being properly triggered.
