### ISSUE TITLE
Coaches should not be required to be members of the classes for which they are the coach

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1236]
Currently, coaches can only be assigned to classes that they are members of - this leads to odd reports behaviour, where coaches are included in reports on their classes, unless they are specifically filtered out.

**Comment by DXCanas** [comment]
@christianmemije?

**Comment by rtibbles** [comment]
This should be reconsidered when we introduce `class coach` capability.

**Comment by indirectlylit** [comment]
this is no longer the case
