### ISSUE TITLE
Coach is not able to create exam

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1238]
## Summary
Coach user is not able to create exam for learners.

## System information

 - Version: kolibri 0.4.0alpha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome Browser and Firefox

## How to reproduce

1. Login with Coach user.
2. Click on coach and then class name.
3. Nothing will appear on screen.
## Screenshots
![screenshot from 2017-04-18 10_52_12](https://cloud.githubusercontent.com/assets/12776071/25115671/808d8800-2425-11e7-86e7-899e0dd9996e.png)

**Comment by rtibbles** [comment]
@indirectlylit this is a result of the `facility` scoping issue that we discussed previously on slack.

**Comment by yogeshmhaskule** [comment]
@rtibbles @aronasorman 
### System information
Version: kolibri 0.4.0alpha4
Operating system: Ubuntu 14.04 LTS
Browser: Chrome Browser and Firefox

We retested in new release of kolibri. Coach and admin is not able to create the exam

![coach_failed_exam](https://cloud.githubusercontent.com/assets/7850420/25331960/8e17196e-2902-11e7-9d01-1b988952f3a2.png)

**Comment by rtibbles** [comment]
Thanks for the additional console log.

Have reopened and we will look into this.

**Comment by rtibbles** [comment]
This appears to be due to some malformed database data, whereby some exercises are missing the additional data required for rendering assessments.

I would recommend reimporting your database with the following command:
`./kolibri-v0.4.0-alpha4.pex manage importchannel -- network <channel_id>`

We will also make an additional bug fix to make the exam creation robust against this kind of error in data.

**Comment by rtibbles** [comment]
To confirm, this was on the same channel that #1305, #1303, and #1301? I am fairly certain they are being caused by the same underlying database issue. Will be submitting fixes to make sure these kind of errors don't prevent accessing features.

**Comment by indirectlylit** [comment]
new task for handling missing metadata: #1309

**Comment by harishbalachandran** [comment]
We retested today here are the Observations:
1. Retested with Channel ID that Richard shared Khan Academy (en) Fractions.  78eed5c0b59b30c0a40c94c17c849af6, we are able to create the exam.
![login4](https://cloud.githubusercontent.com/assets/13453618/25380558/41056244-29ce-11e7-9368-5ebc541044f2.png)
![login5](https://cloud.githubusercontent.com/assets/13453618/25380560/424efe9e-29ce-11e7-935c-fb17ba5631f2.png)

2. Retested with the channel ID  Test Channel Harish (7769d932b2cc49efb18c5e665cda64ff) on which we opened this bug on, and found that the issue still persists. 

![login2](https://cloud.githubusercontent.com/assets/13453618/25380565/44fb1790-29ce-11e7-992e-6139ac51d4c9.png)
![login3](https://cloud.githubusercontent.com/assets/13453618/25380569/4691dfee-29ce-11e7-8538-54d233c273c0.png)

**Comment by rtibbles** [comment]
Thanks for the update, @swapnil106111 - we have a fix for the issue currently open, it should be in the next alpha.

**Comment by swapnil106111** [comment]
@rtibbles  Retested with channel Test Channel Harish (7769d932b2cc49efb18c5e665cda64ff). Now, it is working.

![1238_1](https://cloud.githubusercontent.com/assets/12776071/25421637/705f2a54-2a7b-11e7-83dd-3195166f74ca.png)
![1238_2](https://cloud.githubusercontent.com/assets/12776071/25421638/705f3fc6-2a7b-11e7-88ed-a6944fa1f632.png)
