### ISSUE TITLE
"GET A HINT" button not working in KA channel.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1239]
## Summary
In Kolibri for KA channel, GET A HINT button is not working. Nothing will happen after clicking on "GET A HINT" button.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0alpha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Select Khan Academy channel.
2 . Click on any exercise then click on GET A HINT button.

## Screenshots
![get hint](https://cloud.githubusercontent.com/assets/12776071/25116128/6ba3f386-2428-11e7-82cf-0f6263e6dbbd.png)

**Comment by rtibbles** [comment]
Thanks for reporting - will fix.

**Comment by yogeshmhaskule** [comment]
@rtibbles We have tested. It's works.
![get_a_hint_reolved](https://cloud.githubusercontent.com/assets/7850420/25332712/200c1566-2905-11e7-84fa-86044cb8fb07.png)
