### ISSUE TITLE
Audit and replace unwrapped "up" and "down" strings used for aria labeling

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12392]
## Observed behavior
There are some places where the strings that are passed to draggable items, for aria labels, are regular strings (i.e. "up" "down" and are not translated strings). We may want to consider using a commonCoreString translation for these? and translating and replacing all with 0.18. There might also be a case for not using a common string. 

## User-facing consequences
Non-translated aria labels

## To Dos 
- Audit all "up" "down" or other ariaLabel strings that are untranslated and share a list in #kolibri-dev tagging @marcellamaki and @radinamatic 
- After follow up decision about whether or not we should create commonCore strings for the existing use cases, update all relevant strings with their proper translated reference.

**Comment by AllanOXDi** [comment]
fixed in [#12817](https://github.com/learningequality/kolibri/pull/12817)
