### ISSUE TITLE
Need to refresh the page to load exercise.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1240]
## Summary
When open the exercise in Kolibri, it doesn't load exercise. But after refreshing the page, it loads exercise.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0alpha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login into system.
2. Select Exercise if it doesn't gets load into system, refresh the page.

## Screenshots
![screenshot from 2017-04-18 11_36_07](https://cloud.githubusercontent.com/assets/12776071/25116593/5fbecf48-242b-11e7-80d8-c49f0d928b74.png)

**Comment by rtibbles** [comment]
This seems to be a replication of the issues you were facing @DXCanas - seems like a race condition on loading the exercise.

**Comment by indirectlylit** [comment]
this should be addressed in the next alpha

**Comment by yogeshmhaskule** [comment]
@rtibbles We tested it in new release of kolibri. it's work.
