### ISSUE TITLE
Need to refresh the page to see the changes from Admin to Learner 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1241]
## Summary
Need to refresh the page when we switch admin to learner.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login with Device Owner.
2. Click on Manage then Users.
3. And Select Edit button of Admin user to make it learner. This time need to refresh the page.
## Screenshots

![1](https://cloud.githubusercontent.com/assets/12776071/25117584/613348fe-2430-11e7-9eee-8c6841d4389e.png)
![2](https://cloud.githubusercontent.com/assets/12776071/25117585/61355f7c-2430-11e7-812e-319582fc4aed.png)
![3](https://cloud.githubusercontent.com/assets/12776071/25117587/6139b98c-2430-11e7-814f-da8c9883b46d.png)

**Comment by rtibbles** [comment]
I think you had looked at this previously, @DXCanas? Perhaps your change got regressed somewhere?

**Comment by DXCanas** [comment]
iirc, this was a race condition. Will look at this after reports stuff is taken care of

**Comment by yogeshmhaskule** [comment]
@rtibbles @aronasorman on creation of new user in kolibri 0.4.0aplha4, user kind not shown until refresh the page.

Before refresh page(check user **test_coach1**):

![user_coach_not_showing_kind](https://cloud.githubusercontent.com/assets/7850420/25335809/44ea3e96-2912-11e7-9fe8-9774a53fa239.png)

After refresh page(check user **test_coach1**): 
![showing_user_kind](https://cloud.githubusercontent.com/assets/7850420/25335828/5052c532-2912-11e7-8761-28e11386d4ad.png)

**Comment by DXCanas** [comment]
Bug likely caused by a double-mapping of API to State data, the second one being incompatible with the state mapper (because it's already mapped to a state). See:

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/state/actions.js#L365

Going to be submitting a fix soon

**Comment by DXCanas** [comment]
This issue describes 2 separate problems. The above fix only addresses admin creation. Looking into the first issue now

**Comment by DXCanas** [comment]
Admin -> Learner was the result of a promise being fired and not waited for. Fix in this commit of the same PR:
https://github.com/learningequality/kolibri/pull/1312/commits/97f2a9c56dbb350bff9c915731ac43d06681b3b8

**Comment by swapnil106111** [comment]
@rtibbles Retested. It is working fine.

![1241_1](https://cloud.githubusercontent.com/assets/12776071/25421448/979e1428-2a7a-11e7-9476-c67f2ceb1b0a.png)
![1241_2](https://cloud.githubusercontent.com/assets/12776071/25421449/979ff2a2-2a7a-11e7-989a-0561bf6a92b6.png)
![1241_3](https://cloud.githubusercontent.com/assets/12776071/25421451/97a092c0-2a7a-11e7-8ead-9f1279e15d40.png)
![1241_4](https://cloud.githubusercontent.com/assets/12776071/25421452/97b31940-2a7a-11e7-88a2-679618561583.png)
![1241_5](https://cloud.githubusercontent.com/assets/12776071/25421450/97a09a68-2a7a-11e7-947f-30b2b298e400.png)
