### ISSUE TITLE
EQM - There shouldn't be a confirmation prompt after reordering the sections

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12419]
## Observed behavior

When I click the 'Apply settings' button after having reordered the sections of a quiz I am seeing the 'Are you sure you want to leave this page?' modal.

Video:

https://github.com/learningequality/kolibri/assets/79847249/24d9deb8-6217-493e-91fd-61ce35d4f40c

## Expected behavior

As per the latest changes - in that case the changes should be applied and the user should go directly to the quiz screen.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta0
2. Create a quiz with several sections
3. Attempt to reorder the sections

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
Closed by #12432
