### ISSUE TITLE
As a learner on submitting the exam we get an Error page.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1242]
## Summary
As a learner on submitting the exam we get an Error page.

## System information

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome and Firefox

## How to reproduce

1. Give an exam logged in as a learner.
2. Input answers for all the questions. 
3. Submit the exam.
4. Ideally the completed exam status should be displayed.
4. But presently we have to refresh the page and we get an error page.

## Screenshots
![error on submiting the exam](https://cloud.githubusercontent.com/assets/13453618/25117623/837626ca-2430-11e7-853a-182d667dedb9.png)
![submit exam](https://cloud.githubusercontent.com/assets/13453618/25117624/837b05aa-2430-11e7-882f-c237790794b3.png)

**Comment by swapnil106111** [comment]
When we logged in as a Coach or Admin user and give the exam. After submitting exam, It shows the results for Coach or Admin User.
Admin User
![admin user](https://cloud.githubusercontent.com/assets/12776071/25125847/e814f54e-244d-11e7-98ca-22cf54fc60f3.png)

Coach User
![coach user](https://cloud.githubusercontent.com/assets/12776071/25125848/e817cfe4-244d-11e7-8caf-5e38413661a8.png)

**Comment by rtibbles** [comment]
Looks like it needs a small tweak on the userexam endpoint. Will fix.

**Comment by rtibbles** [comment]
I was able to replicate #1246, but could not replicate this. Could you reproduce and then attach here the `kolibri.log` file inside the `.kolibri` folder in the home directory of the user running the pex? This should give us more logging information to see what is causing the error. Thanks!

**Comment by harishbalachandran** [comment]
This is can be reproduced by:
	1	Give an exam logged in as a learner.
	2	Input answers for all the questions. (Enter the answer for the last question, then move to some other question, so that the response is saved for the last question)
	3	Submit the exam.
	4	Ideally the completed exam status should be displayed.
	5	But presently we have to refresh the page and we get an error page.

Attaching the ScreenPrint and Log file as per request.
[1242_kolibri.txt](https://github.com/learningequality/kolibri/files/933448/1242_kolibri.txt)

![back to exm screen](https://cloud.githubusercontent.com/assets/13453618/25175507/a7acd4c4-2518-11e7-90da-6811773192ee.png)
![end exam](https://cloud.githubusercontent.com/assets/13453618/25175510/a8ec1a52-2518-11e7-95f8-d77643b6e466.png)
![error screen](https://cloud.githubusercontent.com/assets/13453618/25175511/a8f1ffee-2518-11e7-8668-dc3084c949ef.png)
![page refresh](https://cloud.githubusercontent.com/assets/13453618/25175509/a8cde88e-2518-11e7-9f74-e377f6a78744.png)

**Comment by rtibbles** [comment]
Thanks for the log file, I know what is happening here and will make an update to prevent it from happening!

**Comment by rtibbles** [comment]
This should no longer occur. Please reopen if it recurs!

**Comment by yogeshmhaskule** [comment]
@rtibbles not able to test #1301
