### ISSUE TITLE
EQM - The Section settings modal closes after clicking 'Add more questions'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12422]
## Observed behavior

Clicking the  'Add more questions' button after having changed the section title or description results in closing the modal.

Video:

https://github.com/learningequality/kolibri/assets/79847249/2c7c3030-a43e-44da-88af-7ecb8b1d7535

## Expected behavior

It should be possible to modify the section settings and add new questions at the same time.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta0
2. Create a new quiz with section.
3. Attempt to add questions to a sections while modifying it in some way.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
Closed by #12432
