### ISSUE TITLE
Hover and Click effect on Demo & Download button for better user interface and experience

### ISSUE THREAD

**Issue by KARANSINGH34951** [learningequality/kolibri#12423]
## Observed behavior
For now, both buttons look static and plan 

https://github.com/learningequality/kolibri/assets/137412876/03cd503a-e1a2-4b84-a02b-062cafe82521

## Expected behavior
A hover and click effect are the expected behavior when button clicked user get a confirmation that its actually got clicked.

## Steps to reproduce
It is visible in the Hero section Right side

**Comment by nucleogenesis** [comment]
Hey @KARANSINGH34951 thank you for the report. We have already begun addressing many issues on our website so this particular button design is no longer relevant due to ongoing work we'll be releasing soon.
