### ISSUE TITLE
EQM - Preview quiz - The selection effect is reversed

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12425]
## Observed behavior

See the screenshot.

Screenshot:

![selection](https://github.com/learningequality/kolibri/assets/79847249/7dea72a2-e8a8-4724-9c97-fdfadf5e0d97)

## Expected behavior

Only the currently selected question should be highlighted in light gray.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta0
2. Create a new quiz with sections and save it.
3. While at Coach > Quizzes click on the title of the quiz.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
For any dev who takes this -- the background is currently falling back to or is transparent so that the underlying elements are shown _except_  for the active one, which is made white. So it seems like perhaps this is as simple as flipping those two values 🤞

**Comment by MisRob** [comment]
Re-opening since it seems we somehow lost the fix https://github.com/learningequality/kolibri/pull/12427 as reported by @pcenov [here](https://github.com/learningequality/kolibri/pull/12427#issuecomment-2507807829)
