### ISSUE TITLE
EQM - Select a quiz - Missing 'Are you sure you want to leave this page?' modal when I click the browser's Back button

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12421]
## Observed behavior

There's no 'Are you sure you want to leave this page?' modal when I click the browser's Back button after having selected a quiz to import.

Video:

https://github.com/learningequality/kolibri/assets/79847249/6f537ca3-d8ec-411c-9c14-629f5172947d

## Expected behavior

Unless otherwise specified somewhere the newly created quizzes should appear on top of the table in Plan > Quizzes so that it's easier for the Coach to keep track of them.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta0
2. Create a new quiz and save it. Repeat several times and observe the position of the newly created quizzes in the table.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
Closed by #12441
