### ISSUE TITLE
EQM - All question cards are disabled when there's just 1 question to add

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12443]
## Observed behavior

All question cards are disabled when there's just 1 question to add. This is not happening always so a bit hard to replicate, but has happened to me several times already with different channels.

Video:

https://github.com/user-attachments/assets/76aa8923-cccc-4e61-a8a3-25ac6703fa54

## Expected behavior

It should be possible to add a single question.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta2
2. Import the Khan Academy channel (not the QA channel)
3. Create a new quiz with sections.
4. Attempt to add a single question to a section.

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #12444
