### ISSUE TITLE
Some videos are not loading

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1244]
## Summary
Some videos are not loading in chrome and Firefox browser.

## System information

*Please specify the Kolibri version you were using and your operating system!*
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login with learner.
2. Open video in chrome browser or in Firefox.

## Screenshots
![video](https://cloud.githubusercontent.com/assets/12776071/25118572/7db3911a-2434-11e7-82fd-2a4abffe6da0.png)

**Comment by rtibbles** [comment]
@christianmemije can you look at this channel/content node and see if there is something strange about these video files?

**Comment by christianmemije** [comment]
@swapnil106111 What version of Firefox is that?

**Comment by swapnil106111** [comment]
Probably, It comes when large-sized content channel is there in system.
Firefox Version 48.0
Chrome Browser Version 53.0.2785.101 (64-bit)

**Comment by indirectlylit** [comment]
@swapnil106111 - how pervasive is this issue? is it still occurring?

**Comment by rtibbles** [comment]
Not able to replicate. Closing. Will reopen if further reports.
