### ISSUE TITLE
EQM - The 'Add section' button is not fully visible in some languages

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12449]
## Observed behavior

The 'Add section' button is not fully visible in some languages where the text is longer such as German. It's displayed correctly in mobile view but as I start expanding the window horizontally (more than 600x) it's no longer fully visible.

Video:

https://github.com/user-attachments/assets/982b2d67-9f14-4c6d-b1c4-2d68cecad218

## Expected behavior

The button should either be fully visible or the text should be abbreviated.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta3
2. Create a new quiz with sections.
3. Observe the display of the 'Add section' button in German.

## Usage Details
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #12465
