### ISSUE TITLE
EQM - Replace questions in RTL language - The checkboxes and arrows are overlapping

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12450]
## Observed behavior

See the video. The checkboxes and arrows are overlapping but it's still possible to select them.

Video:

https://github.com/user-attachments/assets/55c0a90f-cb8e-4a1f-86b9-750a54029a78

## Expected behavior

The checkboxes and arrows should not be overlapping.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta3
2. Create a new quiz with sections.
3. Attempt to replace questions while viewing in Arabic.

## Usage Details
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
I suspect this is related to [here](https://github.com/nucleogenesis/kolibri/blob/49b9044770beadc7c1ce3061c822e15762e74952/kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/ReplaceQuestions.vue#L69) - maybe should just try to put the styles into a class in the style tag (particularly the `right: 1em;`)

Perhaps it's worth my revisiting how our automatic rtl<>ltr style stuff works

**Comment by Sahil-Dash** [comment]
can i work on this , or is there someone already working ?

**Comment by nucleogenesis** [comment]
Hey @Sahil-Dash - this issue is already assigned. If you're interested, we have an issue label [Help wanted](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee). Thanks for your interest in helping, I hope there is something there that sparks your interest!

**Comment by rtibbles** [comment]
Fixed in #12470
