### ISSUE TITLE
EQM - Answer history in mobile view - Incorrect question numbers when viewing the sections

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12464]
## Observed behavior

When I go to check the 'Answer history' after having completed a quiz with several sections then for each new section I select I see the question numbers starting from 1 in the drop-down list.

Video:

https://github.com/user-attachments/assets/8c5dd25d-a168-4e95-bcdd-aab9fd4e9e70

## Expected behavior

Consistent behavior with the desktop version of the 'Answer history' report.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-beta3
2. Create a new quiz with several sections.
3. Complete the quiz as a learner in mobile view and observe the 'Answer history'

## Usage Details
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #12467
