### ISSUE TITLE
Shows you have 1 question is unanswered.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1247]
## Summary
After giving answer of all the question in exam,still it shows you have 1 question is unanswered.

## System information
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce
1. Login as a learner.
2. Click on exam section.
3. On last question, it shows this error.

## Screenshots
![e1](https://cloud.githubusercontent.com/assets/12776071/25124930/d4187a50-244a-11e7-85c7-e2a9218a0a44.png)
![e2](https://cloud.githubusercontent.com/assets/12776071/25124929/d4154dc6-244a-11e7-9276-80d552567e22.png)

**Comment by rtibbles** [comment]
Yes, this is a pain because the Perseus renderer doesn't actually tell us when an answer has been submitted, so we will just have to keep checking, but can work around for a good user experience. Thanks!

**Comment by indirectlylit** [comment]
should be addressed

**Comment by yogeshmhaskule** [comment]
@rtibbles Not able to test this because of #1301

**Comment by harishbalachandran** [comment]
The answer entered is saved for the last questions and hence this specific issue is closed.

![1](https://cloud.githubusercontent.com/assets/13453618/25381109/2b3ee460-29d0-11e7-944d-afed498449ed.png)
![2](https://cloud.githubusercontent.com/assets/13453618/25381111/2bf0d120-29d0-11e7-85ed-2eb27c387060.png)
