### ISSUE TITLE
KSelect with section questions is trapped behind/by Perseus container

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#12476]
## Observed behavior
On smaller screens (tested on Android 13 phone), when a Perseus question container is small, it _traps_ the dropdown selector of the questions in the section, cuts off the bottom and makes the swipe/scroll challenging. Issue is not noticeable when the question has more content/images and the container becomes longer.

https://github.com/user-attachments/assets/456c2027-44aa-46da-9afa-f37f523692b7

## Errors and logs
Nothing in the console.

## Expected behavior
KSelect should be visible in full regardless of the question length on screen. 

## User-facing consequences
Challenging scroll and navigation through questions.

## Steps to reproduce
Add 50 questions to a quiz section, try navigating through questions as a learner on a mobile screen.

## Context

Tell us about your environment, including:
 * Kolibri version: 0.17b3
 * Operating system: Android 13, but the cutoff is also visible in responsive mode emulator in the browser.
 * Browser: -

**Comment by rtibbles** [comment]
Fixed in #12484
