### ISSUE TITLE
On-my-own learner who joins a facility cannot open class assignements

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#12486]
## Observed behavior
Issue was first observed on a RPi server with Motorola phone, and replicated on Ubuntu 24.04 server with Xiaomi phone.

- Android device was set up as `On my own` 
- Learner account was then _transferred_ to the server using the *Change facility* workflow
- On the server facility the Learner account was enrolled into an already existing class with 1 quiz and 1 lesson
- On the device's Home screen, *Learner* is able to see the class they have been assigned to, and both assignments, but each time they try to open them, they are redirected to the Library page instead.
- Syncing has completed successfully, and  *Learner* can open and view each of the resources that are in the quiz and lesson, they just cannot view them _within_ the quiz and/or lesson.

https://github.com/user-attachments/assets/e52a3fb7-478f-4057-8635-1a8fc9281ae1

## Errors and logs
[Xiaomi-Android-13-logcat.txt](https://github.com/user-attachments/files/16375247/Xiaomi-Android-13-logcat.txt)

[db-and-logs.zip](https://github.com/user-attachments/files/16375578/db-and-logs.zip)

## Expected behavior
Learner who joins a facility and is enrolled in a class must be able to see and open the class assignments.

## User-facing consequences
Inability to open and complete the class assignments after changing the facility.

## Steps to reproduce
…

## Context

 * Kolibri version: 0.17b3
 * Operating system: RPi and Ubuntu 24.04 servers, Motorola G51 (Android 12) and Xiaomi 10C (Android 13) LoDs

**Comment by rtibbles** [comment]
Fixed in #12500
