### ISSUE TITLE
 It's impossible to exit Coach plan tab using a browser's back icon.

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#12490]
## Observed behavior
When  a user navigates to coach plugin and then plan -  a user can  then not navigate out of couch plan tab useing browser's back icon 

https://github.com/user-attachments/assets/7ffd06db-e225-4976-90b4-97e53e54de96

## Expected behavior
Should be able to navigate out  of plan tab using browser's icon

## Context
Kolibri version: 0.17b3
chrome

**Comment by rtibbles** [comment]
Noting that this is likely a problem with the redirect behaviour that is happening, where we are pushing to the browser history for the redirect rather than replacing, so when we press back we hit the redirect again and can't escape!

**Comment by itzharshit99** [comment]
hi i would like to work on this issue.

**Comment by AllanOXDi** [comment]
Hi @itzharshit99  I will assign this to you

**Comment by AllanOXDi** [comment]
Hey @itzharshit99! 👋
Just wanted to check in and see how you're doing. How's everything going with this work? I hope it's not too overwhelming!
Remember, we're all here to support you. If you're stuck on anything or just want to bounce some ideas around, don't hesitate to give a shout! 😊
No pressure for an immediate response, but when you get a chance, it'd be great to hear how you're getting on

**Comment by AllanOXDi** [comment]
Hey @itzharshit99,
 We haven't heard back from you, and I completely understand if you've been busy😊. I wanted to let you know that if we don't hear from you within the next 1-2 weeks, we'll need to reassign this issue to one of our internal team members  to  take it.

**Comment by LianaHarris360** [comment]
It seems that this problem has been fixed. I can't replicate it in the `release-v0.17.x` branch or the `develop` branch. The video below shows the behavior working as it should. Could you confirm @AllanOXDi?

https://github.com/user-attachments/assets/7d1b0c1b-7d78-437d-b039-a5179f6b346b

**Comment by pcenov** [comment]
Hi @radinamatic - I confirm that this issue is no longer extant in the latest version of Kolibri and can be closed.

**Comment by radinamatic** [comment]
Closing as not extant anymore! 💥
