### ISSUE TITLE
Profile section for each user

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1250]
## Summary
Not showing Profile section for Device owner user and Facility admin user.

## System information
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login with different type of users.

## Screenshots
Learner user
![learner](https://cloud.githubusercontent.com/assets/12776071/25173145/bc1069c4-2510-11e7-81e9-86be5401521f.png)

Coach user
![coach](https://cloud.githubusercontent.com/assets/12776071/25173144/bc0b0754-2510-11e7-8af4-f0a1877eea00.png)

Facility admin
![facility admin](https://cloud.githubusercontent.com/assets/12776071/25173147/bc250848-2510-11e7-9db8-cc0b5e20b7cd.png)

Device owner
![super admin](https://cloud.githubusercontent.com/assets/12776071/25173146/bc10ed40-2510-11e7-931a-101cb94e3523.png)

**Comment by rtibbles** [comment]
This is deliberate, as:
a) Device Owners do not have a profile per se (as they are not Facility Users like all other user types)
b) Admins can make all relevant changes to themselves from the Manage tab.

@khangmach @jtamiace can you think of any advantages to letting the Facility Admin access the Profile tab for themselves?

**Comment by indirectlylit** [comment]
My recollection is that we _did_ intend for facility admins to have a profile self-edit tab.

**Comment by rtibbles** [comment]
OK, we can make that update then, but it will never appear for Device Owners, as they do not have profiles to edit.

**Comment by jtamiace** [comment]
Device Owner users can edit their passwords through the terminal right? I can see a use of having a profile, or some space through the UI dedicated for that. 

But it's a good point that admins are able to do that through the Manage UI... if there's a good case for Device Owners to have the capability to change their passwords through a less tech-savvy means then I would think that Facility Admins to also have a profile page for that.

**Comment by rtibbles** [comment]
For now, we will make the fix for FacilityAdmins - there would be more technical work for Device Owners to have the same functionality (for now they should be changing their passwords through the command line).

**Comment by yogeshmhaskule** [comment]
@rtibbles Please, could you provide more details to set password through the command line. So it's easy to check for us into latest release.

**Comment by yogeshmhaskule** [comment]
@rtibbles @aronasorman  For facility admin profile section is showing. As Device owner "Profile" section is showing on UI. If we click on it. It gets signout. Does the update profile facility available to the device owner.
