### ISSUE TITLE
Importing content from local drives

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1251]
## Summary
Not able to import a specific channel while importing using local drives.

## System information
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Device Owner user.
2. Goto manage then content tab.
3. Click on IMPORT and Select LOCAL DRIVES.
4. Then, select local drive.
## Screenshots
According to Design Document:
![screen shot 2017-04-19 at 4 10 50 pm](https://cloud.githubusercontent.com/assets/12776071/25176158/df761b98-251a-11e7-8a52-b813a48c7d6c.png)

In Kolibri
![111](https://cloud.githubusercontent.com/assets/12776071/25175950/32c95b4e-251a-11e7-81fb-c07117912ee1.png)
![112](https://cloud.githubusercontent.com/assets/12776071/25175949/32b839e0-251a-11e7-92fe-ce46dd4ee3d9.png)

**Comment by rtibbles** [comment]
This will be fixed, but I don't think in time for the Nalanda release.

Is this urgent, or can it be worked around for now by only having the desired channels on the external drive?

**Comment by rtibbles** [comment]
@jonboiser assigning to you as you are working on the next steps of the content import-export feature.

**Comment by rtibbles** [comment]
@swapnil106111 note that the mockup you are referencing here is targeted for public release in July, so the functionality will be created, but not within our current timelines for 0.4.x

**Comment by indirectlylit** [comment]
this will be addressed during the granular import/export work in 0.7

**Comment by indirectlylit** [comment]
closing in favor of #2273
