### ISSUE TITLE
Replace KResponsiveElementMixin by useKResponsiveElement composable

### ISSUE THREAD

**Issue by AlexVelezLl** [learningequality/kolibri#12523]
This issue is blocked by https://github.com/learningequality/kolibri-design-system/issues/711.

## Summary

This issue involves replacing all [occurrences of KResponsiveElementMixin](https://github.com/search?q=repo%3Alearningequality%2Fkolibri+KResponsiveElementMixin+language%3AVue&type=code&l=Vue) with the new [useKResponsiveElement](https://github.com/learningequality/kolibri-design-system/blob/6a6865f1060e1da160b77b7b851f82f340f453a1/lib/composables/_useKResponsiveElement.js) composable throughout the Kolibri codebase.

This includes updating imports for properties like `elementWidth` and `elementHeight`, and ensuring all affected components are manually tested to confirm they work correctly with the new composable. 

### Acceptance criteria

- [ ] `useKResponsiveElement` composable is used instead of `KResponsiveElementMixin` in all Kolibri codebase.
- [ ] All occurences of properties provided by `KResponsiveElementMixin` (`elementWidth`, `elementHeight`) are imported from `useKResponsiveElement` composable in the component where `KResponsiveElementMixin` mixin is being removed.
- [ ] All components where KResponsiveElementMixin is replaced are manually tested and still work as expected with `useKResponsiveElement` composable.
- [ ] There is a list of affected pages the a pull request description (e.g. their URLs).

**Comment by AlexVelezLl** [comment]
Closed by #12717

**Comment by marciatorresg** [comment]
Hi @AlexVelezLl, I am a GSOC applicant for 2026, and I would like to work on this issue. Could you please assign it to me?

**Comment by rtibbles** [comment]
Hi @marciatorresg - this issue is closed as it has already been resolved. Please look out for open help wanted issues!

**Comment by marciatorresg** [comment]
[like]  Marcia Stephanie Torres Garces reacted to your message:
________________________________
