### ISSUE TITLE
option to delete a specific channel from kolibri server(Enhancement)

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1252]
## Summary
Option to delete a specific channel from kolibri server(Enhancement).

## System information

 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

**Comment by rtibbles** [comment]
Again, assigning to @jonboiser for after upcoming import export work, but this will not be done for 0.4.x release.

**Comment by jonboiser** [comment]
This should be available in 0.5.

1. As a Device Owner, go to 'Management -> Content'
2. Next to the channel, there will be a 'Delete' button
3. Click the 'Delete' button, and then confirm.
4. The channel should disappear from the list, and from the 'channel select dropdown' on the Learn pages.
