### ISSUE TITLE
Write helper function(s) to manage display of metadata tags following prioritization criteria

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12525]
When designing the card display, different user needs were balanced. 

- Coaches want to have relevant information available at a glance, so they can make a quick decision about the relevance of a particular resources 
- Coaches can be overwhelmed by too much information, and due to overwhelm and limited time, select things at the top of the list or randomly, and then end up with resources that are not necessarily the most relevant 

To balance these two needs, Jessica has designed a prioritization system for metadata tags on channels and resources, with inputs from the implementations team.

The amount of metadata available will vary widely across channels and resources. The prioritization system ranks the type of metadata and the order. If that metadata exists for the contentNode, it will be displayed, otherwise, the next available piece of metadata in the ranking order will be displayed. 

<img width="904" alt="Screenshot 2024-08-27 at 9 27 05 AM" src="https://github.com/user-attachments/assets/561d6357-8954-4a76-a336-806994fe3621">
<img width="811" alt="Screenshot 2024-08-27 at 9 26 59 AM" src="https://github.com/user-attachments/assets/60b87815-aceb-48b8-820e-5a5a4f5a9e22">

**Acceptance criteria**
- [x] create a composable in `kolibri-common` that accepts a contentNode
- [x] If the contentNode is a **channel** or a **folder**, it returns up to 7 tags at one time according to the priority list of usefulness while browsing:
     - Max 3 from Category
     - Max 3 from Level
     - Max 1 from language
     - If there is more than 1 language, display “Multiple languages"
- [x] If the contentNode is a **resource**, it returns up to 3 tags at one time according to the priority list of usefulness while browsing:
     - Activity 
          - If more than 1 activity, display "multiple learning activities"
     - Duration
     - Level
          - If more than 1, display each 
     - Category
          - If more than 1, display each. Display the most specific category available (i.e. "Chemistry", not "Science") 
     - Language
     - Show resources / What you need
- [x] the composable returns an array of **translated** metadata strings, which can be consumed by the relevant card easily to render each tag

**Comment by AllanOXDi** [comment]
completed in [12686](https://github.com/learningequality/kolibri/pull/12686)
