### ISSUE TITLE
While enrolling in the class, there should be an option to select all the learners.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1253]
## Summary
While enrolling in the class, there should be an option to select all the learners.
Presently, We have to select each user seperately. This would be a problem if there are many learners.

## System information 
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Facility Admin.
2. Select manage then select class name.
3. Click on ENROLL USERS.

## Screenshots
![select all enroll user](https://cloud.githubusercontent.com/assets/12776071/25176679/a34ad094-251c-11e7-889b-b20069c09183.png)

**Comment by rtibbles** [comment]
@jtamiace any compelling reason this was omitted?

**Comment by jtamiace** [comment]
No reason I can think of. It seems to be valuable, but should select all select all users in the facility, or just those showing on the current page?

**Comment by rtibbles** [comment]
Ah, a UX question as old as time!

Whichever way we do it, we should indicate how many users are selected at any one time, in order to give feedback about which has happened, do we do that already?

**Comment by jtamiace** [comment]
_summons_ @khangmach 

I _feel_ like should select just the users on the current page... drawing experience from things like gmail:
![screen shot 2017-04-19 at 10 29 22 am](https://cloud.githubusercontent.com/assets/6668144/25193202/1f4cfdb6-24eb-11e7-80d2-347ca3c2d076.png)

Both the mockups and implementation do not show how many users were selected until "review&save" is clicked. could be a bit of meta text next to the review&save button

**Comment by rtibbles** [comment]
I think the way Gmail does it is a nice model, by default only select those shown, but show the additional option of really selecting everyone.

**Comment by indirectlylit** [comment]
(another option is to get rid of paging and use a scrolling window instead)

**Comment by jtamiace** [comment]
where the "users selected" counter could go?

<img width="893" alt="screen shot 2017-04-19 at 10 36 25 am" src="https://cloud.githubusercontent.com/assets/6668144/25193515/3e448332-24ec-11e7-99fa-b2cb60d00946.png">

**Comment by khangmach** [comment]
yeah if we incorporate a "select all" checkbox, it should check the users that are currently visible and indicate how many were selected.

**Comment by indirectlylit** [comment]
are selections remembered:

* as you page through
* as you modify the search filter

(e.g. can hidden items remain selected)

**Comment by jtamiace** [comment]
yes to both

**Comment by khangmach** [comment]
as you page through: yes
as you modify search filter: yes
 - searching for a user and then selecting them will select the user and clear the search filter anyways

**Comment by jtamiace** [comment]
i don't know it should clear the search filter... i can see there being a case where there are several users that an admin wants to add from a single search filter entry

**Comment by khangmach** [comment]
ah yeah, then they're just selected and to go back the main list you just clear the search. got it

**Comment by rtibbles** [comment]
@jtamiace @khangmach could you update the design mock accordingly, and we can assign someone to fix this issue?

**Comment by jtamiace** [comment]
yep. one of us will post here when that happens

**Comment by khangmach** [comment]
@rtibbles @indirectlylit @jtamiace 

See changes here: https://invis.io/RD9VC27CG#/212352902_Class_Adding_Learners

So in the above mock...there is a selection filter switch for showing all selected users. However, I haven't made a text indicator for showing the amount of users when you "select all". I think showing "show selected users (total #)" next to the switch is enough of an indicator for the total amount of users you have selected on all the available pages. 

Reasoning: showing text such as "showing 9 users" when checking "select all" conflicts with the switch that shows the total selected and it's better for "select all" to obviously serve as more of a shortcut function so you don't have to select everything manually on that specific page. In the case that you have user selections on, say, page 1, 2, and 3, the words "showing 9 users" on one page will be a bit misleading, as you obviously have more people selected on different pages.

**Comment by swapnil106111** [comment]
@rtibbles  Retested with select all users option. Working fine.

![1253_1](https://cloud.githubusercontent.com/assets/12776071/25422000/e8d0f5f2-2a7c-11e7-9269-33eb53c26149.png)
