### ISSUE TITLE
EQM - Add new section/Edit Section - The 'Section settings' modal remains open after clicking 'Delete section'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12532]
## Observed behavior

When adding a new section or editing it if I click the 'Delete section' button, then the 'Section settings' remains open and cannot be closed by the user so that the user is forced to reload the page resulting in loss of any unsaved changes.

Video:

https://github.com/user-attachments/assets/0da1924f-3698-4744-8a67-8ac069c76663

## Expected behavior

The 'Section settings' modal should disappear.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/releases/tag/v0.17.0-rc2
2. Create a new quiz.
3. Click the 'Add section' button and then click the 'Delete section' button.
4. Alternatively after having already added a section click the 'Options' button, select 'Edit section' and click 'Delete section'.

## Usage Details
Ubuntu 22  - Chrome
Windows 11 - Edge

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
This is the same error I encountered in https://github.com/learningequality/kolibri/pull/12462#issuecomment-2247833246, which we decided to postpone to patch 1 to do a more thorough testing. Can we cherry-pick the fix you implemented there, @nucleogenesis? Thank you!

**Comment by radinamatic** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/12536
