### ISSUE TITLE
Move `avg_request_time_to_error` to the backend `context`

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12556]
## Overview
The `avg_request_time_to_error ` property is more suited for the backend `context` and should be move there instead. Its currently part of `errorreport`.

## Description and outcomes
- Move `avg_request_time_to_error ` to the backend `context`

## Acceptance Criteria
 - `avg_request_time_to_error` is part of the backend `context`

## Assumptions and Dependencies
- NA

## Scope
- Moving the `avg_request_time_to_error`

## Accessibility Requirements
NA

**Comment by thesujai** [comment]
I can pick this up @akolson

**Comment by rtibbles** [comment]
Fixed in #12660
