### ISSUE TITLE
Prevent sensitive information like user passwords from being logged/captured

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#12555]
## Overview
We should not capture sensitive information like passwords during error reporting 

## Description and outcomes
- Check request headers for any sensitive information and remove it before capturing the eror.

## Acceptance Criteria
 - No sensitive information exists in captured erors

## Assumptions and Dependencies
- NA

## Scope
- Prevent capture and transmission of sensitive information in errors

## Accessibility Requirements
NA

**Comment by rtibbles** [comment]
Fixed in #12660
