### ISSUE TITLE
standardize on strings as type returned for all IDs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1255]
Some IDs are returned from the API as integers (like users and facilities), and others are strings (like channels and content nodes).

We should probably standardize on strings everywhere. This may be happening anyway as part of the Morango upgrade? We'll likely need to do some client-side work to remove any assumptions about integer-based ID types.

cc @ralphiee22 @jamalex @rtibbles

**Comment by rtibbles** [comment]
More confusingly, I have come across places where the id is an integer but is serialised as a string, and in other places the id is an integer and serialised as such.

**Comment by DXCanas** [comment]
@rtibbles could it be that the int strings are JSON?

**Comment by rtibbles** [comment]
If I recall correctly, the difference seems to be whether the id is the primary key, or a reference to a primary key of a related model, which means directly comparing the two is difficult.

Either way, I agree with having one way of sending them to the front end.

**Comment by rtibbles** [comment]
Note that this is now somewhat mitigated, due to the introduction of Morango, where all syncable model ids are now strings.
