### ISSUE TITLE
Remove FocusTrap in favor of KFocusTrap

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#12588]
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri/blob/develop/CONTRIBUTING.md).**

### Blocked by

- https://github.com/learningequality/kolibri-design-system/issues/746

### Summary

As soon as Kolibri Design System contains https://github.com/learningequality/kolibri-design-system/issues/746, here in Kolibri we need to

**(1) Remove all `FocusTrap`s that are wrapping `KModal` s**

```jsx
<FocusTrap>
  <KModal>
```

(because `KModal` will contain the focus trapping logic within itself)

**(2) Rename all remaining instances of `FocusTrap` to `KFocusTrap`**

**(3) Finally remove *kolibri/core/assets/src/views/FocusTrap.vue*** 

### Comments

This may slightly conflict with https://github.com/learningequality/kolibri/issues/5488. Nothing really blocking, let’s just inform  @rtibbles about progress on this issue.

### Acceptance criteria

- [ ]  Implemented as specified above
- [ ]  There are no regressions at all updated places

**Comment by DakshArora1004** [comment]
Hi @MisRob, I'm interested in working on this issue after [kolibri-design-system#746](https://github.com/learningequality/kolibri-design-system/issues/746#issue-2481366763) is resolved. Could you assign it to me? I'll start preparing and will be ready to implement once the blocker is cleared.

**Comment by MisRob** [comment]
Hi @DakshArora1004, thanks for volunteering. I will assign you. After https://github.com/learningequality/kolibri-design-system/pull/764 is merged, you can [use devserver-with-kds command](https://kolibri-dev.readthedocs.io/en/develop/howtos/development_with_kds.html) to run Kolibri with your local Kolibri Design System. Feel free to ask any questions here.

**Comment by MisRob** [comment]
@DakshArora1004 I wanted to flag there's a possibility that this work will be addressed in the scope of https://github.com/learningequality/kolibri-design-system/pull/764#issuecomment-2326064319. Better to wait before working on what's the decision in the linked pull request.

**Comment by MisRob** [comment]
@DakshArora1004 I'm sorry for confusion but we will assign this to the same volunteer who has just resolved https://github.com/learningequality/kolibri-design-system/pull/764 since they will use this issue to ensure everything works as expected in Kolibri. Otherwise both of you would work on the same task.

There are other contributing opportunities in three repositories you're very welcome to explore. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.

**Comment by lokesh-sagi125** [comment]
hey @MisRob .

**Comment by MisRob** [comment]
Hi, thanks @lokesh-sagi125, assigning as agreed

**Comment by MisRob** [comment]
@lokesh-sagi125 may be handy https://kolibri-dev.readthedocs.io/en/develop/howtos/development_with_kds.html ;) cc @akolson

**Comment by MisRob** [comment]
Hi @lokesh-sagi125, are you working on this or planning to? Just to know if we should keep the assignment or not.

**Comment by lokesh-sagi125** [comment]
YES @MisRob  i am still working on this issue, i was learning going through the codebase to avoid making errors while creating the component, i will raise a PR in 3 days

**Comment by MisRob** [comment]
Thanks for update @lokesh-sagi125. No problem and no pressure at all, just my regular rounds checking on possibly stale assignments.

**Comment by rtibbles** [comment]
Fixed in #12718 

Thanks for your work here @lokesh-sagi125, very much appreciated!

**Comment by lokesh-sagi125** [comment]
@rtibbles  thank you for helping me with the rebasing issues .  i hope to produce PR's with lesser problems in the future :).
