### ISSUE TITLE
Create a composable for total progress fetching and points calculation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12619]
Currently total points fetching is handled in vuex state and with an action:

State: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/index.js#L13
Action: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/actions.js#L270
Mutations: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/actions.js#L270 https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/mutations.js#L21
Getter: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/getters.js#L21

These should all be replaced by a composable that has a global progress state, and all references for fetching, mutations, and state should go through the composable.

This composable should be added to the core API spec to facilitate import across plugins.

**Comment by nathanaelg16** [comment]
Hi @rtibbles, I'd like to be assigned this issue.

**Comment by rtibbles** [comment]
Thank you @nathanaelg16 - you have been assigned!
