### ISSUE TITLE
Unintended Horizontal Scrolling on Main Kolibri Website

### ISSUE THREAD

**Issue by Suraj-kumar00** [learningequality/kolibri#12629]
## Observed behavior

Horizontal scrolling occurs unintentionally across multiple pages, affecting user experience.

`https://learningequality.org/kolibri/about-kolibri/`

Video:
[Screencast from 2024-09-03 15-04-30.webm](https://github.com/user-attachments/assets/823876b9-97e0-47bb-97f6-e46d4d5a9c1b)

## Errors and logs

No specific errors or logs; issue related to front-end UI/UX.

## Expected behavior

The website should have no horizontal scrolling unless explicitly needed.

## User-facing consequences

Users may miss content or find the site difficult to navigate, this issue is only on laptop/desktop screens.

## Steps to reproduce

Visit the Kolibri website, scroll horizontally, and observe the unintended side-scrolling.

## Context

**Kolibri Version:** v0.17.0
**Operating System:** Ubuntu 24.04 LTS
**Browser:** Chrome, Brave

**Comment by krishna-shrivastav232702** [comment]
Hey @Suraj-kumar00,

I’ve worked on this issue and made changes in my forked repository. Could you guide me on how to verify that the issue has been resolved

**Comment by Suraj-kumar00** [comment]
Hi @krishna-shrivastav232702 , actually I'm not the maintainer but one the contributor, I just saw the issue and raise the issue. I have LinkedIn the video of the issue if the changes that you have made doesn't show the horizontal scrolling than the issue is resolved.

**Comment by MisRob** [comment]
Thanks for reporting @Suraj-kumar00. The main Kolibri website is a different repository, I will transfer this issue to https://github.com/learningequality/website later on.

**Comment by MisRob** [comment]
Thanks for reporting @Suraj-kumar00. The main website is a different repository, I will transfer this issue to https://github.com/learningequality/website later on.

**Comment by MisRob** [comment]
cc @krishna-shrivastav232702 above is one of the reasons why I closed your PR. I left some links there on how to approach opening a pull request including guidance on running the development server, and related.

**Comment by MisRob** [comment]
cc @krishna-shrivastav232702 above is one of the reasons why I closed your PR. I left some links there on how to approach opening a pull request including guidance on running the development server, and related. That should help with "Could you guide me on how to verify that the issue has been resolved" :)

**Comment by MisRob** [comment]
cc @krishna-shrivastav232702 above is one of the reasons why I closed your PR. I left some links there on how to approach opening a pull request including guidance on running the development server, and related. That should help with

> Could you guide me on how to verify that the issue has been resolved

Also note that generally it can take us a day or two to reply on GitHub.

**Comment by Suraj-kumar00** [comment]
> Thanks for reporting @Suraj-kumar00. The main website is a different repository, I will transfer this issue to https://github.com/learningequality/website later on.

I meant this issue is related to this repository, the website link have mentioned in the issue.

**Comment by MisRob** [comment]
> I meant this issue is related to this repository, the website link have mentioned in the issue.

Ah I see. The website is about LE in general and the app Kolibri and this is the repo for the actual app :)

**Comment by MisRob** [comment]
No problem @Suraj-kumar00 at all.

I will close this now in favor of https://github.com/learningequality/website/issues/66
