### ISSUE TITLE
errors when trying to do khan academy exercises

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1263]
trying to do exercises in the small add/sub khan academy math channel as a Learner

----

* URL: http://localhost:8000/learn/#/f6d2f857af2e304093648daf2d8cacec/topics/c/37666e5422735d1ba711ca2d4dd88e27
* Name: Subtract within 100

gives:

![image](https://cloud.githubusercontent.com/assets/2367265/25216214/68a0bb04-2556-11e7-88f0-212179cbd4ca.png)

![image](https://cloud.githubusercontent.com/assets/2367265/25216206/63364bf2-2556-11e7-8fc6-dfa8ee6a756d.png)

----

URL: http://localhost:8000/learn/#/f6d2f857af2e304093648daf2d8cacec/topics/c/7bdb45614975517c93e94c09bf82c05a
Name: Add and subtract on a number line 

Gives: 

![image](https://cloud.githubusercontent.com/assets/2367265/25216253/9858362e-2556-11e7-866f-f70bc2398d53.png)

![image](https://cloud.githubusercontent.com/assets/2367265/25216263/a4269a9a-2556-11e7-9143-e78dda047125.png)

----

This one in a different channel seems to almost work, but throws 400 errors:

URL: http://localhost:8000/learn/#/78eed5c0b59b30c0a40c94c17c849af6/topics/c/2a9dc24c4f494b5cb6e871a8c8e57c8f
Name: Compare fractions and mixed numbers 

Gives:

![image](https://cloud.githubusercontent.com/assets/2367265/25216446/8bb99646-2557-11e7-9173-a8368225ad42.png)

![image](https://cloud.githubusercontent.com/assets/2367265/25216453/9816cd3c-2557-11e7-9aad-934c1e92f8d7.png)

**Comment by rtibbles** [comment]
First one seems to be a content issue, the second one should have been solved by my recent PR (was this on latest develop?) and the third is due to an issue with the attempt log saving introduced by my learner exam PR, that is solved in the detail reports PR.

**Comment by indirectlylit** [comment]
most of these issues are addressed. Migrated the remaining zip content issue to #1272
