### ISSUE TITLE
After Practice Quiz and clicking back button, user does not see latest score

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#12663]
## Observed behavior

This is a follow-up from https://github.com/learningequality/kolibri/pull/12564 which added the latest Practice Quiz's score to the content's card's "Progress" section.

I suspect that the `TopicsPage` is not calling this again. I tried adding `force: true` in the params to no effect. This might take a bit of digging, but we just need to be sure that we're fetching the progress again whenever the page loads.

This is where it is called (the _loadTopicsTopic calls the API for progress):

https://github.com/learningequality/kolibri/blob/443b2f06936db2f29a5552d1b4fcd9a03c9388da/kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue#L509-L512

## Expected behavior

When a user's progress for any content has been updated, the user interface should reflect their latest progress.

## User-facing consequences

User does not see their progress reflected in the UI.

## Steps to reproduce

- Take a practice quiz
- Click the "Back" arrow
- No score there
- Refresh page, see your score now
- Take the practice quiz again - score differently on purpose
- Click the "Back" arrow
- See first attempt's score
- Refresh page
- See latest score

## Context

`develop`

**Comment by rtibbles** [comment]
For non-practice quiz content types, we do some special frontend cache manipulation to do this update, we would need to add the equivalent here for the practice quiz extra progress data.
