### ISSUE TITLE
Upgrade places utilizing `KCard` from beta to its final API

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#12688]
## Dependencies

KDS `v5.0.0-rc7`

## Summary

KDS `v5.0.0-rc7` will introduce breaking changes to `KCard`, such as renaming some props (see release notes as soon as available). In Kolibri, we need to update the following components accordingly:

- [kolibri-common/components/Cards/AccessibleFolderCard.vue](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-common/components/Cards/AccessibleFolderCard.vue)
- [kolibri-common/components/Cards/AccessibleResourceCard.vue](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-common/components/Cards/AccessibleResourceCard.vue)
- [kolibri-common/components/Cards/AccessibleChannelCard.vue](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-common/components/Cards/AccessibleChannelCard.vue)

Furthemore, KDS `v5.0.0-rc7` introduces many new guidelines to [the `KCard` documentation page](https://develop--kolibri-design-system.netlify.app/kcard/). The components above should be reviewed against it and updated to follow them whenever relevant.

As of Oct 1, 2024, `KCardGrid` isn't yet used in Kolibri, however if its beta version find its way to Kolibri codebase before this issue is resolved, it should too be updated to its final version and revisited against guidelines - simply follow [the `KCardGrid` documentation page](https://develop--kolibri-design-system.netlify.app/kcardgrid/).

**Comment by marcellamaki** [comment]
This has been resolved between Allan's updates/rebasing of his open PRs for the accessible cards, plus other work making use of these cards with the card grid, and no longer needs to be tracked as a separate issue
