### ISSUE TITLE
Expose  the content node API to show resources / What you need

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#12687]
## Overview

We will  need to expose Content Node API to  return  "What you need metadata/requirements " section. To allow our  to frontend cards component  fetch and display this metadata.

**Comment by rtibbles** [comment]
Noting here, so that I don't forget - that we will also add this to the public content node endpoints (and should do so on Studio too) - but we will need to add in an empty value when fetching this from Kolibri versions that do not return this data.
