### ISSUE TITLE
exam creation: possible for the same question to be selected multiple times?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1271]
While previewing an exam, one exercises had two rows that both said "Question 5". Is it possible that we're allowing the same questions to be selected multiple times?

**Comment by DXCanas** [comment]
Hmm. If you selected various sources, and those sources happen to share exercises, I think there's a chance that item id's could be repeated?

**Comment by DXCanas** [comment]
@indirectlylit I can start looking into this if you can send me the channel / exercises you selected.

Basically this page + the channel name
![image](https://cloud.githubusercontent.com/assets/9877852/25413584/452188f0-29e0-11e7-92ad-4d5df88b32ae.png)

**Comment by rtibbles** [comment]
My intution is that this may be cause if we are accidentally allowing an exercise with only 5 questions to be selected to give 6 questions, but needs investigation.

**Comment by christianmemije** [comment]
> we are accidentally allowing an exercise with only 5 questions to be selected to give 6 questions
That should not be possible.

**Comment by indirectlylit** [comment]
So far no one else has reported/reproduced this, and I didn't provide steps to reproduce, so I'll close the issue.
