### ISSUE TITLE
When comparing a bloompub file with the corresponding epub file sometimes the images or parts of the text are missing

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12726]
When comparing a bloompub file with the corresponding epub file sometimes the images or parts of the text are missing

_Originally posted by @rtibbles in https://github.com/learningequality/kolibri/issues/12586#issuecomment-2380239850_

**Comment by pcenov** [comment]
Adding a video for this:

https://github.com/user-attachments/assets/3f4ad91a-1778-43f0-9ebf-fa63752dd141

Files used for the comparison with direct links to the bloom library site:

1. [Chola'j Ub'ee Ch'a'teem Achi](https://bloomlibrary.org/book/mJICLgjsTI)
2.  [God Gives Solomon Wisdom](https://bloomlibrary.org/book/a8sYMIXDlC)
