### ISSUE TITLE
Remove "Activity" tab from learner view

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12733]
## Overview 

As part of the information architecture refactor, we need to do a little bit more follow up on the new learner overview/report page -  `ReportsLearnerReportPage`.

Please review https://github.com/learningequality/kolibri/issues/12679 and https://github.com/learningequality/kolibri/pull/12711 for context of the past changes. 

Current state of develop:
![Image](https://github.com/user-attachments/assets/2b4eb948-2598-40b7-80e7-bc42bf8743c3)

Figma:
![Image](https://github.com/user-attachments/assets/d1e6406c-8eb0-4fa4-b5a0-0281bdfa2f8f)
![Image](https://github.com/user-attachments/assets/2aa7b407-32b2-44cd-b88d-aecea63bdfdf)

In addition to the code cleanup, add "pagination". 
- [x] For both Lessons and quizzes display the first 10 items of the array
- [x] If there are >10 Items, display a view more button
- [x] On click, render another 10 items
- [x] If still more items, on click, view the rest, no matter how many)
- [x] If there are no more items to be shown (the user is viewing all), hide the "view more" button

### Acceptance Criteria
**Code cleanup:** 
- [x] Remove the use of Tabs and clean up related code
- [x] Remove the rendering of the `ActivityList` on this page (do not delete the file, it's in `kolibri-common`)
**Layout/styling:**
- [x] Retain the use of grids so the containers stack properly on mobile 
- [x] Ensure everything matches the [figma](https://www.figma.com/design/lVJt5ukOrxS9qay0rXy7GC/0.18-Coach-updates?node-id=116-21582&node-type=frame&m=dev) in terms of spacing and layout (using the dev mode if needed)
- [x] Everything looks okay on tablet and mobile
**New features:** 
- [x] Pagination is implemented according to the spec
**What else?**
- [x] No regressions

**Comment by apoorvapendse** [comment]
![Image](https://github.com/user-attachments/assets/b24fe056-9331-4100-841c-fdfeec9efdca)
Do you mean this one? @marcellamaki

**Comment by marcellamaki** [comment]
Hi @apoorvapendse - nope, this issue actually isn't about that. This issue is not ready for assignment, as you can see it hasn't been written yet and there are no details or tags on the issue. 

If you're interested in contributing to Learning Equality projects, please look at the Kolibri [contribution guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) to get a better sense of our open source process. Choosing from ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) would be the best place for you to find ways to contribute and engage with the team.

**Comment by apoorvapendse** [comment]
Thanks @marcellamaki, will look into it!
