### ISSUE TITLE
Always logging into Super admin

### ISSUE THREAD

**Issue by jlh-create** [learningequality/kolibri#12741]
Our account always signs into our super admin regardless of device, facility settings and even if you log out of all accounts before closing app.  We have tested every scenario we can think of.  When I sign out, the app glitches, flashes indefinitely and I have to close the tab.  Below is out troubleshooting json info.  I notice the do_automatic_login is set to true.  Is that the problem?  I've been looking for the config.jsn file where this setting may exist, no luch so far...

[kolibri-gnome-debug-info.json](https://github.com/user-attachments/files/17507055/kolibri-gnome-debug-info.json)

**Comment by rtibbles** [comment]
I assume this issue is related to the support forum post? https://community.learningequality.org/t/super-admin-remains-logged-in/3385/1

As detailed there, for the GNOME app, the Kolibri user is tied to the system user.

Hopefully the solution detailed there will resolve this. Thank you for reporting!

**Comment by jlh-create** [comment]
Hello Richard,
We still have the issue described below for some of our older machines...
The above fix worked for our newer laptops (Lenovo P53).  But we also have
older desktops, Optiplex 3020 that the fix did not work for.
When I set the environment variable Kolibri flashes/glitches when it loads
and it does not stop, I have to close the app. The glitch disappears when I
unset the variable.
Thanks, Jen

**Comment by rtibbles** [comment]
Hi Jen - I've flagged your question on the forum again to Dylan to see if he can provide some insight!
