### ISSUE TITLE
On my own - Merge accounts - The checkmark for the 'I understand the consequences...' checkbox is not displayed

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12758]
## Observed behavior
While merging my account the checkmark for the 'I understand the consequences of merging accounts' checkbox is not being displayed. The user is still able to enable the 'Continue' button by clicking on the checkbox. Here's a video of that:

https://github.com/user-attachments/assets/5ea42d8d-e3c4-4c23-8a2d-e777663f7c4c

## Expected behavior

The checkmark should be displayed.

## Steps to reproduce the issue

1. Install the [latest 0.17.3-beta0 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.17.3-beta0).
2. Go through the 'On my own' setup flow.
3. Go to Profile > Change > Merge accounts

## Usage Details
[0.17.3-beta0](https://github.com/learningequality/kolibri/releases/tag/v0.17.3-beta0)
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
Fixed in #12761
