### ISSUE TITLE
Facilities Configuration: loading settings error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1275]
## Summary

Fresh install of so no users or classes yet...

## System information

 - Version: 0.4.0alpha3
 - Operating system: both Windows 7 and Ubuntu 16.10
 - Browser: FF & Chrome

## How to reproduce

1. Install
1. Go to Manage > Facilities

## Screenshots

![virtualbox_ubuntu 16 10_21_04_2017_14_52_21](https://cloud.githubusercontent.com/assets/1457929/25278246/673d1922-26a2-11e7-9458-af704c1dd7b4.png)

![virtualbox_windows 7_21_04_2017_14_52_39](https://cloud.githubusercontent.com/assets/1457929/25278209/438a1700-26a2-11e7-8b21-1ddf95e01957.png)

**Comment by indirectlylit** [comment]
this may be due to being logged in as a superuser?

**Comment by indirectlylit** [comment]
working on some some work-arounds here: https://github.com/learningequality/kolibri/pull/1274

**Comment by radinamatic** [comment]
Could very well be, looking forward to testing the `artificial facility ID` from #1274. :+1:

**Comment by indirectlylit** [comment]
this should be fixed in the `detail-reports` branch

**Comment by radinamatic** [comment]
Looks nice :+1: 

![configure facility - kolibri - google chrome_179](https://cloud.githubusercontent.com/assets/1457929/25398927/fa2aa0bc-29ed-11e7-9ad1-4a97f97b3ad7.png)

...but if I simply reload the page, the error comes back! :disappointed: 

![configure facility - kolibri - google chrome_180](https://cloud.githubusercontent.com/assets/1457929/25398988/2c010f9a-29ee-11e7-82bf-4993536345c6.png)

![configure facility - kolibri - google chrome_181](https://cloud.githubusercontent.com/assets/1457929/25399000/31ed4f72-29ee-11e7-8167-45b80bba88c7.png)

**Comment by DXCanas** [comment]
@radinamatic I'm not seeing this behavior, even when logged in as a device owner. Are you running the latest?

**Comment by indirectlylit** [comment]
as far as I can tell this is fixed, but I'm "happy" to be proved wrong :)

**Comment by radinamatic** [comment]
@DXCanas it was extant on the latest develop at the time when screenshots were created. 

I just had a fresh dev repo running and at first pass (with basically no content and no users) I cannot replicate it, but will try again later on the old one where it was extant.

**Comment by radinamatic** [comment]
Gone indeed on `0.4.0alpha6.dev19` :+1:
No "happy" to you this time @indirectlylit... :stuck_out_tongue:
