### ISSUE TITLE
Two modal sizes for adding a new user

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#1277]
## Summary

Under the "users" tab, clicking on "add new" and then entering a username with a space (e.g. Khang Mach) prompts an input error message which makes the modal wide. Would suggest just adopting the wide modal width instead or line breaking the input error message.

The error shown is also wrapped in square brackets and quotes, indicating that it's likely incorrectly formatted javascript.

## How to reproduce

1. Navigate to users tab
2. Hit "add new"
3. Enter name, enter a username with a space in between (john doe)
4. confirm the rest of the details
5. hit create account
6. modal changes size which seems to be based on the error. 

## Screenshots

![image](https://cloud.githubusercontent.com/assets/2367265/25413646/b2e13e62-29e0-11e7-90ee-f7f9e1270962.png)

**Comment by christianmemije** [comment]
Passing `width="300px"` as prop to the core-modal should do the trick.
