### ISSUE TITLE
0.18 - Cannot create a new lesson

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12801]
## Observed behavior
This could be known issue but we are reporting it for tracking purposes - when I go to Coach > Plan > Lessons and attempt to create a new lesson I see an empty modal and it seems impossible to create a lesson. As a workaround one can create a lesson by typing the lesson name and navigating using the keyboard:

https://github.com/user-attachments/assets/a13cfbc2-62a7-4baa-961c-9945b9454c43

## Expected behavior
It should be possible to create a new lesson.

## Steps to reproduce the issue

1. Install the latest `develop` build
2. Go to Coach > Plan > Lessons and attempt to create a new lesson

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by Arunima22** [comment]
Hey, has this issue been assigned? If not, I would like to work on this! I have read through the frontend documentation and currently going through the backend documentation.  Any guidance will be appreciated.

**Comment by AlexVelezLl** [comment]
Hi @Arunima22! This issue has actually been fixed 😅, but forgot to close it. But You’re welcome to find [a "help wanted" issue with no assignee](<https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues>)

**Comment by AlexVelezLl** [comment]
Closed by #12775

**Comment by Arunima22** [comment]
Alright :)
