### ISSUE TITLE
Give hover effect for "Donate" button like that "Get Started" button

### ISSUE THREAD

**Issue by Ajaykumar724** [learningequality/kolibri#12810]
I also attach image 

![Image](https://github.com/user-attachments/assets/13f4451d-ea3b-43c7-b7b3-b4dfca34c6aa)

this is not good user experience so that we must update them. 

Thank you.

**Comment by Ajaykumar724** [comment]
> I also attach video
> 
> this is not good user experience so that we must update them.
> 
> Thank you.

**Comment by emily-dominguez** [comment]
hi, can i get this issues assigned to me pls!

**Comment by rtibbles** [comment]
Hi @emily-dominguez - unfortunately, this appears to be an issue for our website, which is not an open source project. Thanks for your interest, but I'll be closing this issue!

**Comment by Ajaykumar724** [comment]
but this issue is valid so how can i contribute please guide me @rtibbles

**Comment by MisRob** [comment]
Hi @emily-dominguez and @Ajaykumar724, 

There are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.
