### ISSUE TITLE
The ergonomics of KA Lite

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1282]
_From @jamalex on February 23, 2014 14:41_

One of the somewhat concerning observations that came out of recent feedback from the Nalanda classrooms was that some students were getting _so_ engaged and focused on their learning with the KA Lite tablets that they may have neglected to move, leading to ergonomic issues.  One student “didn’t want to get up from the tablet, [...] focusing on that only”, and ended up with a crick in her neck that she noticed in the dance class that followed. Another student learned her own ergonomic lesson after spending a class period answering math exercises so intently that it took a moment to be able to extend her arm fully again afterwards, so the next class period with the tablets, she made sure to stretch her arms from time to time.

Considering these observations, it may be worth looking into including ergonomic reminders interspersed with the videos and exercises, encouraging stretching, breaks, and good posture.

_Copied from original issue: learningequality/ka-lite#1611_

**Comment by benjaoming** [comment]
_From @jamalex on February 23, 2014 14:43_

(If anyone could write a Google Docs plugin so I could use this for my dissertation, that would be a bonus! ;) Would need to be sometime in the next 24 hours, though. :P )

**Comment by benjaoming** [comment]
_From @jamalex on February 23, 2014 14:56_

It would be nice to build this into KA Lite itself (as described above), but in the meantime, perhaps it would be good to include some ergonomic suggestions and exercises in the teacher's manual, so teachers in the new classrooms can start kids off on a healthy path.

**Comment by benjaoming** [comment]
_From @66eli77 on March 23, 2015 22:31_

really like this idea, won't close it during this issue triaging.

**Comment by benjaoming** [comment]
I really like this idea, too :)

**Comment by indirectlylit** [comment]
migrating to trello instead because it's not an immediately actionable issue: https://trello.com/c/WukThURt/802-ergonomic-reminders-interspersed-with-the-videos-and-exercises-encouraging-stretching-breaks-and-good-posture
