### ISSUE TITLE
0.17.3 - Setup wizard - Cannot import a learner on a LOD from a device with multiple facilities

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12872]
## Observed behavior
It's not possible to import a learner on a LOD from a device with multiple facilities because at the 'Select learning facility' page there is only a 'Go back' button:

https://github.com/user-attachments/assets/ef3df01a-b4e8-4a70-aeb1-2fb057d949c7

The issue is extant in both 0.17.3 and 0.18 and is probably caused by changes made in https://github.com/learningequality/kolibri/pull/12397

## Expected behavior

It should be possible to import a learner on a LOD from a device with multiple facilities

## Steps to reproduce the issue

1. Install Kolibri 0.17.3 and create a server device with at least 2 facilities.
2. Install Kolibri 0.17.3 on another device.
3. Go through the setup wizard by selecting Group learning > Learn-only device > Import one or more existing user accounts from an existing facility

## Logs

[LoD-logs.zip](https://github.com/user-attachments/files/17847060/LoD-logs.zip)
[server-logs.zip](https://github.com/user-attachments/files/17847059/server-logs.zip)

## Usage Details
Kolibri 0.17.3 and 0.18
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Just to reiterate that this was discovered while testing 0.18 assets, and confirmed as replicable on 0.17 branch too, so the fix needs to be applied to both branches.

**Comment by rtibbles** [comment]
Note that this bug _also_ affects importing facilities from a device with multiple facilities.

**Comment by rtibbles** [comment]
Fixed in #12893
