### ISSUE TITLE
0.18 - Coach > Lessons - The 'Recipients' drop-down is not working

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12898]
## Observed behavior
There are no values in the 'Recipients' drop-down at Coach > Lessons while it's working at Coach > Quizzes.
Also at Coach > Quizzes when I select a value from the 'Recipients' drop-down then either I see a scroll-bar or the contents of the drop-down are not fully visible.

https://github.com/user-attachments/assets/8f0ff814-42e3-475c-b9b9-ce41232a5040

## Expected behavior

Fully functional "Recipients" drop-down both at Lessons and Quizzes

## Steps to reproduce the issue

1. Install the build asset from https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
2. Go to Coach > Lessons and Coach > Quizzes and interact with the 'Recipients' drop-down

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by Jeevansm25** [comment]
Can I take this issue?

**Comment by AlexVelezLl** [comment]
Hi @Jeevansm25! Unfortunately this issue is not meant for open source contribution. But you’re welcome to find [a "help wanted" issue with no assignee](<https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues>) :)

**Comment by pcenov** [comment]
A note that the 'Recipients' drop-down is not working at Coach > Learners too:

https://github.com/user-attachments/assets/002956db-3106-49be-b39d-9e4acdd7ba40

**Comment by Jeevansm25** [comment]
> ## Observed behavior
> There are no values in the 'Recipients' drop-down at Coach > Lessons while it's working at Coach > Quizzes. Also at Coach > Quizzes when I select a value from the 'Recipients' drop-down then either I see a scroll-bar or the contents of the drop-down are not fully visible.


The issue you're encountering is likely due to the fact that the :options prop is an empty array ([]), meaning there are no items to display in the dropdown.

**Comment by Jeevansm25** [comment]
> A note that the 'Recipients' drop-down is not working at Coach > Learners too:

The filterOptions array is only populated with a default value (allLabel), this could be why the dropdown is not functioning as expected or not updating correctly.
