### ISSUE TITLE
0.18 - Coach > Learners - Export to CSV is not implemented

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12897]
## Observed behavior
The export to CSV is not implemented yet at Coach > Learners, reporting the issue as a reminder.

![Image](https://github.com/user-attachments/assets/97575027-c67c-402b-92ef-eaf1ff55ce76)

## Expected behavior

Clicking on the 'Export as CSV' button should result in generating a CSV file. The CSV contents are to be further specified.

## Steps to reproduce the issue

1. Install the build asset from https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
2. Coach > Learners >Learner and attempt to export the CSV.

## Usage Details
https://github.com/learningequality/kolibri/releases/tag/v0.18.0-alpha0
Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Closing this as a duplicate, it is covered by the tracking issue #12734 assigned to @ozer550 (as discussed with @AllanOXDi yesterday)
