### ISSUE TITLE
Create a FilterSet that allows Collection endpoints to be filtered based on current user's roles

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1291]
Idea: Create a `CurrentUserRoleFilterBackend` which adds `?user_has_role=admin,coach` etc to `FacilityViewSet`, `ClassroomViewSet`, and `LearnerGroupViewSet`. It would allow filtering one of those endpoints based on whether the current user has one of the specified roles for that collection (either directly, or indirectly). So, for example, something like `/api/classroom/?user_has_role=admin` would return all classrooms for which the current user has the admin role, or, if the user is a facility admin, then it would return all classrooms in the facility. It could also return all classrooms if the current user is a device owner, if desired.

Conceptual context: http://kolibri.readthedocs.io/en/master/dev/uap/concepts_and_definitions.html
Implementation context: http://kolibri.readthedocs.io/en/master/dev/uap/implementation.html

Example of use case: https://github.com/learningequality/kolibri/pull/1287

Starter code (untested):

```python
from kolibri.auth.constants.role_kinds import choices

class CurrentUserRoleFilterBackend(filters.BaseFilterBackend):
    """
    Filters a Collection endpoint to only those collections for which the current user has one of a specified set of roles.
    """

    def filter_queryset(self, request, queryset, view):
        roles = self.request.query_params.get("user_has_role", "").split(",")
        if not roles:
            return queryset
        for role in roles:
            assert role in [c[0] for c in choices], "'%s' is not a valid role kind" % role
        if request.user.is_superuser:
            return queryset
        return HierarchyRelationsFilter(queryset).filter_by_hierarchy(
            source_user=request.user,
            role_kind=roles,
            descendant_collection=F("id"),
        )
```

**Comment by indirectlylit** [comment]
ref #1281

**Comment by jonboiser** [comment]
Added to the list of [backburner issues](https://github.com/learningequality/kolibri/discussions/7806)
