### ISSUE TITLE
displayed mastery model doesn't correspond to actual behavior

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1293]
channel: `1ceff53605e55bef987d88e0908658c5`
content: `b9444e7d11395946b2e14edb5dc4670f`

![image](https://cloud.githubusercontent.com/assets/2367265/25320452/10098530-285c-11e7-8826-5d241d23c565.png)

It wanted me to get 5 check marks to show up, but let me continue after only 3.

**Comment by rtibbles** [comment]
Hrm, this is what I thought I had fixed with the points PR.

**Comment by indirectlylit** [comment]
let me make sure I'm fully updated with the perseus renderer

**Comment by rtibbles** [comment]
That's all happening internally to Kolibri, so shouldn't matter.

**Comment by rtibbles** [comment]
Replicated. It seems I solved the issue I was seeing of *never* getting to mastery by making it a *little* too easy! Will fix.

**Comment by rtibbles** [comment]
Should be fixed on detail-reports now.
