### ISSUE TITLE
trying to take a test, getting error

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1294]
Clicking 'start' results in an error in _utils.js_ and I can't continue:

```
Uncaught (in promise) TypeError: Cannot read property 'assessmentmetadata' of undefined
    at selectQuestionFromExercise (eval at <anonymous>
```

**Comment by indirectlylit** [comment]
it appears that this call is returning an empty list:

```
          const contentPromise = ContentNodeResource.getCollection(
            { channel_id: channelId },
            { ids: questionSources.map(item => item.exercise_id) }).fetch();
```

The value of `questionSources` is:

![image](https://cloud.githubusercontent.com/assets/2367265/25321899/04d98be6-2867-11e7-9a03-0ec01af52b44.png)

**Comment by rtibbles** [comment]
Not understanding why this would return empty if the exercise_id maps to a content item.

**Comment by rtibbles** [comment]
Not replicating this locally.

**Comment by indirectlylit** [comment]
also reported here - #1301. closing this one as a duplicate
