### ISSUE TITLE
After taking the hint and entering the right answer, not able to proceed to the next question.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1298]
## Summary
After taking the hint and entering the right answer, not able to proceed to the next question.

## System information
 - Version: Kolibri 0.4.0aplha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Open an exercise. 
2. Hit on get hint. 
3. Enter the correct answer.
4. Click on next question.

**Expected result:** 
Should go to next question.

**Actual result:**
Stays in the same question.

## Screenshots
![not able to proce](https://cloud.githubusercontent.com/assets/13453618/25333365/83b66b8c-2907-11e7-8eca-935874bf1edf.png)

**Comment by rtibbles** [comment]
Will investigate - seems like the data being sent back is malformed.

**Comment by swapnil106111** [comment]
@rtibbles  Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Still facing same problem.

**Comment by rtibbles** [comment]
Thanks @swapnil106111 - I did not anticipate that this issue would be solved by the channel switch, there are fixes for this that will be in the next alpha.

**Comment by swapnil106111** [comment]
@rtibbles  Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Now, It is working.

![1298_1](https://cloud.githubusercontent.com/assets/12776071/25422757/8ad65c6e-2a7f-11e7-974e-cb412bd4df98.png)
![1298_2](https://cloud.githubusercontent.com/assets/12776071/25422756/8ad6818a-2a7f-11e7-9b63-77527b9486a7.png)
