### ISSUE TITLE
After taking the hint and refreshing the page the hint is not getting recorded in the progress bar.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1299]
## Summary

After taking the hint and refreshing the page the hint is not getting recorded in the progress bar.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Start an exercise 
2. Take a hint.
3. Refresh the page.
4. Observe the exercise progress bar.

**Expected result:**
The hint taken should be present in the exercise progress bar.

**Actual result:**
The question reappears without the hint taken status.

## Screenshots
![refresh 1](https://cloud.githubusercontent.com/assets/13453618/25333856/a4564b30-2909-11e7-8c03-157a9bc3c1e0.png)
![refresh 2](https://cloud.githubusercontent.com/assets/13453618/25333858/a52b1536-2909-11e7-8aa1-b87a6a8de753.png)

**Comment by rtibbles** [comment]
Will fix.

**Comment by swapnil106111** [comment]
@rtibbles Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Still facing same problem.

**Comment by rtibbles** [comment]
Thanks @swapnil106111 - I did not anticipate that this issue would be solved by the channel switch, there are fixes for this that will be in the next alpha.

**Comment by swapnil106111** [comment]
@rtibbles Retested kolibri 0.4.alpha5 with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you.Working fine.

![1299_1](https://cloud.githubusercontent.com/assets/12776071/25425375/657dc2ae-2a89-11e7-8f87-0139294f841b.png)
![1299_2](https://cloud.githubusercontent.com/assets/12776071/25425374/657d1ac0-2a89-11e7-9767-90d74204df88.png)
![1299_3](https://cloud.githubusercontent.com/assets/12776071/25425376/657fb668-2a89-11e7-87a2-54f29f626993.png)
