### ISSUE TITLE
The hint option is always opened up on subsequent questions.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1300]
## Summary

The hint option is always opened up on every questions. This happens after the learner opens hint after entering the correct answer for the present question. 

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Start and exercise 
2. Enter the correct answer.
3. Click on "check answer" button.
4. Do not click on next question.
5. Instead click on "get hint"
6. Now click on next question.

**Expected result:**
Next question should be displayed with no hint or hiden.

**Actual Result:**
The next question appears with the hint readily available.  

## Screenshots
![refresh 3](https://cloud.githubusercontent.com/assets/13453618/25334228/5d5dd6ec-290b-11e7-8b10-0c25067533c1.png)
![refresh 4](https://cloud.githubusercontent.com/assets/13453618/25334230/5ec17e3a-290b-11e7-95c1-d9031714cdc4.png)
![refresh 5](https://cloud.githubusercontent.com/assets/13453618/25334234/63fed370-290b-11e7-82e2-6980fef114de.png)

**Comment by rtibbles** [comment]
Yes, that could be a problem. Will fix.

**Comment by swapnil106111** [comment]
@rtibbles Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Still facing same problem.

**Comment by rtibbles** [comment]
Thanks @swapnil106111 - I did not anticipate that this issue would be solved by the channel switch, there are fixes for this that will be in the next alpha.

**Comment by swapnil106111** [comment]
@rtibbles Retested kolibri 0.4.0alpha5 with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you.Working fine.

![1300_1](https://cloud.githubusercontent.com/assets/12776071/25425591/0546bf8e-2a8a-11e7-9133-0e06fc1fd463.png)
![1399_2](https://cloud.githubusercontent.com/assets/12776071/25425590/05339fee-2a8a-11e7-8236-11c51e7dbdf6.png)
