### ISSUE TITLE
Coach report Exercise Detail View is not working.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1303]
## Summary
Coach report Exercise Detail View is not working.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Master an exercise as a learner.
2. Login as a coach.
3. Drill down on to see the detailed view of the exercise.

## Screenshots
![coach report recent](https://cloud.githubusercontent.com/assets/13453618/25337095/06135d50-2918-11e7-86cd-e79db25fec60.png)
![coach report 1](https://cloud.githubusercontent.com/assets/13453618/25337100/1003886c-2918-11e7-9070-bbd79e5cda95.png)
![coach report 2](https://cloud.githubusercontent.com/assets/13453618/25337109/15a3cbd8-2918-11e7-928c-f3f75d8177e1.png)

**Comment by indirectlylit** [comment]
new task for handling missing metadata: #1309

**Comment by harishbalachandran** [comment]
Re-tested using the channel you had shared, The coach report seams to open up, will test in detail tomorrow and share the results. 
![master3](https://cloud.githubusercontent.com/assets/13453618/25387965/1c547fa4-29ea-11e7-823e-44eb9ae3a9fb.png)

**Comment by rtibbles** [comment]
Thanks for the update @harishbalachandran - hopefully the fixes in the next alpha should make this robust on the testing channel also while we track down why the exercises in question are missing necessary data.

**Comment by indirectlylit** [comment]
This is looking good. Not entirely related, but I'm still seeing "Question NaN attempts":

![image](https://cloud.githubusercontent.com/assets/2367265/25408936/c823b9e2-29c4-11e7-93fa-d274de127e45.png)

**Comment by indirectlylit** [comment]
made a new issue for the above: #1330

**Comment by swapnil106111** [comment]
@rtibbles Retested for channel ID Test Channel Harish(7769d932b2cc49efb18c5e665cda64ff). Now,It is working.

![1303_1](https://cloud.githubusercontent.com/assets/12776071/25422227/d92b3526-2a7d-11e7-8b67-3720e91ec7e1.png)
