### ISSUE TITLE
Question content not showing

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/kolibri#1305]
## Summary

After importing magogenie test channel. Question content of existing topic(not newly updated topic) of same channel is not shown.

## System information

 - Version: kolibri 0.4.0aplha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox
- Channel ID : 7769d932b2cc49efb18c5e665cda64ff

## How to reproduce

1. Login as device owner . 
2. Import channel "7769d932b2cc49efb18c5e665cda64ff"
3. Click on topic->MG Copied->Rupees and Paise - > Notes and Coins ->level1

## Screenshots
![content_not_showing](https://cloud.githubusercontent.com/assets/7850420/25337759/b63f6b18-291a-11e7-8730-03e8667b41a9.png)

**Comment by rtibbles** [comment]
I have replicated this, it is an issue with the assessmentmetadata being generated on the content curation server @jayoshih - could you look into this? The assessment meta data for this content node is missing from the database.

Note: there are some entries in the database table, just not this one.

**Comment by indirectlylit** [comment]
new task for handling missing metadata: #1309

**Comment by swapnil106111** [comment]
@rtibbles Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Showing questions content.

**Comment by rtibbles** [comment]
Thanks for the update @swapnil106111 - hopefully the fixes in the next alpha should make this robust on the testing channel also while we track down why the exercises in question are missing necessary data.
