### ISSUE TITLE
add handling for missing assessment meta data

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1309]
Sometimes assessment metadata is missing from content nodes, and the front-end makes the assumption that it's always there. We should add handling to either gracefully fail when it's missing or insert some empty metadata so the attribute is at least defined.

cc @rtibbles @jayoshih

**Comment by rtibbles** [comment]
Already started on a PR to address this @indirectlylit.

**Comment by indirectlylit** [comment]
okay - do we have a separate issue for the root cause? (e.g. that metadata is missing)

**Comment by rtibbles** [comment]
No, could you open one on content curation?

**Comment by rtibbles** [comment]
Note that it is a specific, not systemic absence of metadata, the table exists, and has some rows, but then some content nodes that are flagged as exercises do not have an associated assessmentmetadata row.
