### ISSUE TITLE
Create a "make assets" target + remove previous webpack assets before building new

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#131]
Current implementation of the npm build command leaves a lot of unused files with random names as noted by @indirectlylit. Possibly the best approach is to clear out previous assets before building new ones.

I would suggest implementing an `assets` target in the Makefile, dependent on a `clean-assets` target.

This also means consolidating README.rst...

**Comment by indirectlylit** [comment]
clean added in #585
