### ISSUE TITLE
<Observation> The Channel import through internet stops at 99%.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1319]
## Summary
Channel ID: 78eed5c0b59b30c0a40c94c17c849af6
Using the above channel ID while we import through internet, the import got stuck at 99% at the back end and its not showing "Finished!" at the front end.

**Note:**
1. Faced the same problem on 2 laptops while doing the import.
2. But on cancelling and reimporting the same channel it was successful!
![reimport_2](https://cloud.githubusercontent.com/assets/13453618/25372642/d1321a76-29b3-11e7-81d8-5b02aac0fea3.png)
![reimport](https://cloud.githubusercontent.com/assets/13453618/25372645/d2097458-29b3-11e7-96a6-74ceafafa904.png)

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Login to Device admin
2. Import channel 78eed5c0b59b30c0a40c94c17c849af6
3. Wait for the Finished status in front end.
4. Look at the status in the terminal too

**Expected Result:**
The status should be Finished in Front end an Terminal

**Actual Result:** 
(Even after waiting for 60mins after 99% complete status)
Terminal: 99%
Front end: Please wait 

## Screenshots
![channel import 99](https://cloud.githubusercontent.com/assets/13453618/25372404/e316be32-29b2-11e7-906c-7bbdff714bca.png)
![frontend import channel](https://cloud.githubusercontent.com/assets/13453618/25372407/e3c1be68-29b2-11e7-9c69-12b63fed4e01.png)

**Comment by harishbalachandran** [comment]
Tested on channel: a21f3dd08adb407ba6c5c0e95ba5515a
Observation:
1. On the fist import the front end does not get updated to Finished! status, even though the back end this time got updated. 
2. Again on re-importing the same channel we got the Finished message this time!

**Comment by rtibbles** [comment]
@aronasorman @jonboiser could you investigate this or assign others to do so?

**Comment by indirectlylit** [comment]
Rest assured the channel did import.

This is a known issue with the current import/export system: https://github.com/learningequality/kolibri/issues/614

(One of many: https://trello.com/c/2nCLWsj2/721-import-export-bugs)
