### ISSUE TITLE
Changes are not reflected on clicking the Finished/Cancel button during content import.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1320]
## Summary
Changes are not reflected on clicking the Finished/Cancel button during content import. On refreshing the page the user is logged out and has to login again to see the changes in channel.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Import a new channel through internet
2. Observe the status bar.
3. Click the close or 

## Screenshots

![finihed page](https://cloud.githubusercontent.com/assets/13453618/25373470/6cff68a2-29b7-11e7-933e-e6721d9a1e6f.png)
![finhed](https://cloud.githubusercontent.com/assets/13453618/25373476/7074bd7a-29b7-11e7-9d6c-bbea853923f9.png)
**Page refreshed**
![refresh content](https://cloud.githubusercontent.com/assets/13453618/25373488/7a750802-29b7-11e7-9f67-6fc1f7e281b4.png)
![logged out](https://cloud.githubusercontent.com/assets/13453618/25373495/85c44088-29b7-11e7-965b-adff6c7c48f1.png)

**Comment by rtibbles** [comment]
@jonboiser could you look into this in parallel to the other issue I assigned?

**Comment by jonboiser** [comment]
In my recent experience, new channels should appear mid-import, but I'll confirm that.

I reproduced the 'getting logged out on refresh' behavior, which happens even if you are not importing anything, which seems like a bug. I'll take a look into that first.

**Comment by harishbalachandran** [comment]
@indirectlylit Retested today on Kolibri 0.4.0alpha5 and the user is not logged out anymore from content page. Thanks!
