### ISSUE TITLE
enrollment pagination text needs to be a single phrase

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1322]
Currently encoded as:

```
{{ visibleStartRange }} - {{ visibleEndRange }} {{ $tr('of') }} {{ numFilteredUsers }}
```

These variables all need to be interpolated into the translation string.

---

@here rule of thumb: every string should be meaningful on its own. If you have an `$tr` string that looks like a fragment, there's a chance we're constructing phrases programmatically.

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/1311
