### ISSUE TITLE
class groups are sorted by order of creation, not alphabetically

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1323]
recommend they be sorted alphabetically

**Comment by rtibbles** [comment]
@christianmemije perhaps look at other endpoints too, like classes and facilityusers?

Can either do this on the client side, add an OrderingFilter to the endpoint: http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter or just change the default ordering of the returned queryset.
