### ISSUE TITLE
signup is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1327]
![image](https://cloud.githubusercontent.com/assets/2367265/25405836/72f27bb2-29b9-11e7-8e34-976f97536c94.png)

**Comment by jonboiser** [comment]
I was looking at this code recently, so I can take this one. But how do you 'signup' in 'learn'? I thought you signup from the login page. Could you provide a URL where this happens?

**Comment by indirectlylit** [comment]
whoops - wrong title! changed.

**Comment by DXCanas** [comment]
@jonboiser I made some changes to this page a while back that don't seem to be here. Mind if I take this one?

**Comment by DXCanas** [comment]
PR for fix open, but the `id` error shown in the screencap comes from a core action. It comes up on sign in as well (any time there isn't a session, I think). We don't need it to sign up, though.

**Comment by indirectlylit** [comment]
is there still an error reported? If so, maybe @jonboiser has an idea how to address it?
