### ISSUE TITLE
Mismatch between Learner's last_active and item's last_active

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1336]
![datemismatch](https://cloud.githubusercontent.com/assets/9877852/25413935/09397958-29e3-11e7-931e-759465fe8876.gif)

**Comment by DXCanas** [comment]
Should this be part of the milestone? @indirectlylit

**Comment by rtibbles** [comment]
@DXCanas which one is correct?

**Comment by DXCanas** [comment]
the one in the exercise detail page

**Comment by DXCanas** [comment]
@rtibbles

**Comment by DXCanas** [comment]
Times are diverging a significant amount on my setup.

On detail page: 
![on_detail_page](https://cloud.githubusercontent.com/assets/9877852/25466466/aebb31d4-2abd-11e7-9bd8-b7eed16d367a.png)

Also note: `end_timestamp` is set to a day later than today.

On Learner List:
![on_user_list](https://cloud.githubusercontent.com/assets/9877852/25466472/b4286786-2abd-11e7-82c4-7c6e21f8f5a6.png)

Learner List after Refresh:
![after_refresh](https://cloud.githubusercontent.com/assets/9877852/25466476/bba5aaf0-2abd-11e7-878a-cdc48761a104.png)

**Comment by rtibbles** [comment]
@DXCanas when I was updating this time rendering on exercise detail reports, I noticed that the way you were parsing the string was causing a 20 hour time differential also - passing in the date in the same way that I did may fix this.

**Comment by indirectlylit** [comment]
just a heads-up that all inputs to the `elapsed-time` component are passed through [`date-fns/parse`](https://date-fns.org/docs/parse)

In theory at least, no pre-processing is necessary. In practice, maybe this is causing issues?

**Comment by rtibbles** [comment]
I think it may be this preprocessing on the date object that is causing the issue: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/reports/learner-exercise-detail-page/attempt-summary.vue#L92
