### ISSUE TITLE
'exams' should be hidden for anonymous users

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1338]
Currently, 'exams' is accessible, and clicking ain't pretty:

![image](https://cloud.githubusercontent.com/assets/2367265/25415023/fe78634c-29e9-11e7-83f6-7ff11add15a2.png)

**Comment by jonboiser** [comment]
So is the fix two parts?

1. Don't show the 'Exam' button if logged in as guest.
2. If anonymous user goes directly to URL, there should be a nicer message.

**Comment by rtibbles** [comment]
That should do it!
