### ISSUE TITLE
coach exam report doesn't handle unstarted users

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1339]
![image](https://cloud.githubusercontent.com/assets/2367265/25415820/0404f618-29ef-11e7-91b7-64e17f651094.png)

...batman!

**Comment by jonboiser** [comment]
Is the 'NaN' the only issue? What should the 'score' column read?

**Comment by indirectlylit** [comment]
My inclination is to replace NaNs with m-dashes in the column, and compute the average score based on only real scores (or a dash if no one has taken the exam)
