### ISSUE TITLE
in Learn, all exams are listed regardless of channel, but links are broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1341]
Currently, all exams are shown to a learner regardless of the target channel. 

Is this intended behavior? (cc @jtamiace @khangmach @rtibbles )
    
 * If so, let's fix the links so they don't rely on the global "current channel"
 * If not, let's filter exams down to just those in the current channel.

**Comment by rtibbles** [comment]
I think for consistency, we should filter.

**Comment by indirectlylit** [comment]
I'm a little torn. I agree that it's more consistent, but on the other hand:

1) in Coach all exams are shown and namespaced in a single list after creation
2) learners don't care about channel consistency - they just want to take the exam

**Comment by rtibbles** [comment]
Fair enough, have a quick fix if you can review?

**Comment by indirectlylit** [comment]
Looks good. We might still want to follow-up on the UX here but the update looks good

**Comment by khangmach** [comment]
Yep, I believe that was the intended behavior. 
"learners don't care about channel consistency - they just want (or need, rather) to take the exam"
^ Would agree with that.
