### ISSUE TITLE
On reviewing the previous questions after entering the answers, the answers disappear for exam.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1343]
## Summary
On reviewing the previous questions after entering their answers, the answers disappears for those questions that a user is reviewing.

## System information
 - Version: Kolibri 0.4.0alpha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as learner.
2. Click on Exams tab and select any exam.
3. Attempt all questions.
4. Go back and start reviewing each questions.

**Actual results:**
 The answers starts disappearing and the question highlighter on the left also disappears as you continue to review.

**Expected results:**
The previous recorded answers should be present and the question highlighter should be purple.

## Screenshots
Attempted all the questions:
![attempted all question answer_1](https://cloud.githubusercontent.com/assets/12776071/25427620/ca72f632-2a90-11e7-842b-443911f3b4e3.png)

Start reviewing the questions from the beginning:
(The answers starts disappearing with the question highlighter) 
![attempted all question answer_2](https://cloud.githubusercontent.com/assets/12776071/25427711/047c24f2-2a91-11e7-919c-c2fcee139ed0.png)

**Comment by rtibbles** [comment]
Seems like an empty answer is somehow getting set back on the attemptlog - we should prevent that from happening.

**Comment by swapnil106111** [comment]
@rtibbles Retested on Kolibri 0.4.0alpha6. Still facing same problem.

![1343_1](https://cloud.githubusercontent.com/assets/12776071/25515828/a31fe534-2c04-11e7-96d6-9f820fff0ad5.png)
![1343_2](https://cloud.githubusercontent.com/assets/12776071/25515827/a31df77e-2c04-11e7-94e4-8e2c5e27fb5c.png)
![1343_3](https://cloud.githubusercontent.com/assets/12776071/25515829/a3242a68-2c04-11e7-93d6-470518fa3598.png)

**Comment by rtibbles** [comment]
Will reinvestigate.

**Comment by rtibbles** [comment]
Replicated, submitting a fix shortly.

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.0alpha7. Now, on reviewing the previous questions after entering the answers are not disappearing.

![screen shot 2017-05-02 at 6 42 32 pm](https://cloud.githubusercontent.com/assets/12776071/25619151/76c8ccd8-2f67-11e7-9c08-b4dd76850deb.png)
![screen shot 2017-05-02 at 6 42 36 pm](https://cloud.githubusercontent.com/assets/12776071/25619150/76c6c866-2f67-11e7-8a40-4ba662da0ccb.png)
