### ISSUE TITLE
Close button is not working

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1344]
## Summary
While submitting the exam, close button is not working.

## System information

 - Version: Kolibri 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Learner.
2. Select Exams tab.
3. Select any exam.
4. Answers all the questions
5. Click on Submit Exam button.
6. close button is not working.

## Screenshots

![cross button is not working](https://cloud.githubusercontent.com/assets/12776071/25432520/66483b9c-2aa2-11e7-81c6-9d3ee26b06e5.png)

**Comment by rtibbles** [comment]
Could you do a quick fix for this @christianmemije? It is probably an oversight by me, just not hooking up the core modal close method.

**Comment by harishbalachandran** [comment]
Tested and working fine. 
![exam submit button](https://cloud.githubusercontent.com/assets/13453618/25528388/396d1378-2c3b-11e7-866d-757f6298cf9b.png)
![exam submit](https://cloud.githubusercontent.com/assets/13453618/25528389/3a4bab74-2c3b-11e7-8dba-0b2f481561fd.png)
