### ISSUE TITLE
Not showing timestamp in coach detailed exercise report 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1346]
## Summary
Not showing timestamp in coach exercise report.It must shows it in minutes, hours, days or months.

## System information

 - Version: Kolibri 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Admin.
2. Click on Coach tab.
3. Select Class name.
4. In Recent tab, Select channel.
5. Select any content.
6. Select User which has progress.

## Screenshots
![mastered](https://cloud.githubusercontent.com/assets/12776071/25434790/596adf8e-2aab-11e7-8aae-ecc0fefc1a85.png)

**Comment by DXCanas** [comment]
Might be related to #1336

**Comment by DXCanas** [comment]
I'm not seeing this behavior, but I am getting some pretty unpredictable times. See #1336

**Comment by rtibbles** [comment]
I am also not replicating this behaviour locally. Hopefully this will be fixed by #1397.

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.0alpha7. Now, it is showing timestamp in coach exercise report.

![1346](https://cloud.githubusercontent.com/assets/12776071/25611702/b1603bc8-2f45-11e7-8284-c8fd5f1e56ec.png)
