### ISSUE TITLE
<Enhancement> Username on the top right corner for logged in users will be great.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1347]
## Summary

<Enhancement> Username on the top right corner will be great. Like in **KA-lite** the username is displayed on the top right corner and this will make a child know at all times he/she is using their respective ID. 

## System information

 - Version: 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Login as a user.
2. Observe the top right corner.

## Screenshots
In KA lite:
![screen shot 2017-04-26 at 6 15 23 pm](https://cloud.githubusercontent.com/assets/13453618/25435048/609637b2-2aac-11e7-81be-ee7509d8fa1a.png)

On kolibri, not really great 👎 :)
![login](https://cloud.githubusercontent.com/assets/13453618/25435122/a940236a-2aac-11e7-94f0-7896436d16a3.png)

**Comment by rtibbles** [comment]
@khangmach @christianmemije this is a priority for Nalanda, so if we could fix this for 0.4.0, that would be great.
