### ISSUE TITLE
Some exercises do not become mastered after last question completed

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1355]
## Summary

Shows that mastery status has been reached, but quickly reverts back to in progress status and erases the last saved answer that would have given mastery status of an exercise.

This has been repeatable, but it's unpredictable on what exercises it happens on. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0alpha5 http://192.237.248.135:8088/
 - Operating system: Mac OS Sierra 10.12.4
 - Browser: Chrome

## How to reproduce

1. Log in as a Learner
2. Reach mastery of any exercise

## Screenshots

Example 1:
![reverting back](https://cloud.githubusercontent.com/assets/6668144/25461219/8455698a-2a9c-11e7-99e6-5e2422192bf9.gif)
Example 2:
![apr-26-2017 16-34-05](https://cloud.githubusercontent.com/assets/6668144/25461545/718d3d12-2a9e-11e7-8191-641bb7b3c65f.gif)

Screenshot of console after mastery is reached and it reverts
<img width="1207" alt="screen shot 2017-04-26 at 4 25 40 pm" src="https://cloud.githubusercontent.com/assets/6668144/25461303/0ef0de12-2a9d-11e7-9154-00a4aa0043c9.png">

**Comment by rtibbles** [comment]
Trying to reproduce this bug on the linked demo server, and no exercises are actually loading. The perseus renderer registers, but then nothing displays.

**Comment by rtibbles** [comment]
@jtamiace to further debug this, it would be useful to see the pattern of requests - to do this, you can either record the issue with the network tab open, or right click on your console and select 'Log XMLHttpRequests'.

I thought it might be a timing issue, but have not been able to replicate locally using Network Throttling.

**Comment by rtibbles** [comment]
Seems like it's a problem with the publishing of the testing channel - no assessmentmetadata is in the published channel.

Not been able to replicate this locally on other channels, would be great if you can get others to replicate!

**Comment by rtibbles** [comment]
I think this is happening because when we save the masterylog it returns pastattempts that include the final two incorrect ones you are seeing in your example.

A couple of questions - did any questions repeat during this session? How many incorrect/hinted answers did you submit before achieving mastery?

It's also possible that our start timestamps are messed up, and so when we return them reverse sorted by start timestamp, the pastattempts is not in the order we would expect.

**Comment by jtamiace** [comment]
The content channel on this server was updated after I had made this issue -- I can no longer replicate it either and content is not showing up for me

**Comment by jtamiace** [comment]
> did any questions repeat during this session? How many incorrect/hinted answers did you submit before achieving mastery?

Sometimes questions repeated, and this was happening with and without incorrect/hinted answers. I will try to reproduce locally as well.

**Comment by rtibbles** [comment]
Thanks - I was wondering if there might be a network issue, with saves taking a long time over the network (couldn't think why else the MasteryLog save would return an incorrect attempt log history), which was why I was trying to do network throttling to reproduce.

**Comment by jtamiace** [comment]
@rtibbles Exercises are working nicely locally on Kolibri 0.4.0alpha1.dev895, cannot reproduce this issue. 

There are still issues in the console, unrelated to this issue?
![screen shot 2017-04-27 at 9 54 34 am](https://cloud.githubusercontent.com/assets/6668144/25494783/aa93cfb8-2b2f-11e7-96e4-985d22e0aad3.png)

**Comment by rtibbles** [comment]
These remaining issues are covered by #1272. I am still a little concerned that this is not resolved, but if not replicable, there is not much we can do. I wonder if it was a result of some very weird content export run?
