### ISSUE TITLE
exam report 'status' column text is red

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1356]
Its should be normal text color:

![image](https://cloud.githubusercontent.com/assets/2367265/25461685/35f17a9c-2a9f-11e7-901c-fcc62cedbe29.png)

**Comment by DXCanas** [comment]
Looks like it was done intentionally, incoming PR

**Comment by indirectlylit** [comment]
i thought maybe it was copy/pasted from a delete button column in another table :)
