### ISSUE TITLE
Reset your password which is on main screen is not working.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1361]
## Summary
Reset Your Password which is on main screen is not working.

## System information

 - Version: Kolibri 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Hit URL in browser localhost:8080
2. Reset your password is not working.

## Screenshots
![reset_your_password](https://cloud.githubusercontent.com/assets/12776071/25470832/b40dc000-2b41-11e7-8380-124fd6c4544b.png)

**Comment by indirectlylit** [comment]
thanks. this needs to be hidden because only an admin can reset an account password

**Comment by jonboiser** [comment]
So is the fix to just remove this link?

How do admins reset their password? I don't see it on the 'profile' section, where I assumed it would be.

**Comment by indirectlylit** [comment]
> So is the fix to just remove this "link"?

Correct. This was a hold-over from the Vodafone version, where we showed instructions for calling the admin.

> How do admins reset their password?

This is under Manage Users -> Edit user -> Reset Password

**Comment by swapnil106111** [comment]
@rtibbles Retested. Now, it is not showing reset your password on main screen.

![1361](https://cloud.githubusercontent.com/assets/12776071/25515186/886867d8-2c00-11e7-8075-c29fa9ff7ef2.png)
