### ISSUE TITLE
Timestamp in tablet and in laptop.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1363]
## Summary
When I logged in as a Coach user in laptop and in tablet with same user, it shows channel and Last active time in Recent tab. In tablet, Last time shows in only seconds and in laptop, it is in minutes and hours.

## System information

 - Version: Kolibri 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Log in as learner.
2. Click on Coach and Select Recent tab.
3. You will see Channels name with Last active.

## Screenshots
Laptop screenshot:
![screen shot 2017-04-27 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/12776071/25476346/88d8f092-2b57-11e7-92fc-e6e79d28a21d.png)

Tablet screenshot:
![screenshot_2010-01-18-02-39-40](https://cloud.githubusercontent.com/assets/12776071/25476388/ac5d2844-2b57-11e7-8019-aa5a02e36a55.png)

**Comment by rtibbles** [comment]
To confirm, the tablet is Android 4, in Chrome?

**Comment by jonboiser** [comment]
I was able to reproduce this on desktop mac by setting my computer time to the past, which also messes up a lot of other things on the computer! I guess the formatter needs to be able to handle negative values of 'last active'.

**Comment by rtibbles** [comment]
I think this is related to broader time issues in #1278 - where relative times could be problematic when comparing times set across different devices.

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.0aplha7. Now, it is showing same timestamp in tablet and in laptop.

![screenshot_2010-01-01-07-03-30](https://cloud.githubusercontent.com/assets/12776071/25611230/eaf57738-2f43-11e7-9f7f-37742bd67278.png)
