### ISSUE TITLE
installing node-sass with yarn does not guarantee that the binary gets installed

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1367]
## Summary

Setting up a fresh dev repo on Linux, going though steps in our `Getting Started` dev documentation, and ending up with the `webpack: Failed to compile` error.

## System information

 - Version: dev repo
 - Operating system: Ubuntu Linux

## Traceback or relevant snippet from server.log or browser console

Original error - [Terminal output](https://slack-files.com/T0KT5DC58-F5599FWKV-8f23e75e07)

After `npm install node-sass` - [Terminal output](https://slack-files.com/T0KT5DC58-F55G3PN77-b84b647924)

After `npm rebuild node-sass` - [Terminal output](https://slack-files.com/T0KT5DC58-F568EC8NB-e32a118fb8)

## Real-life consequences

Unable to start server in development

**Comment by indirectlylit** [comment]
Some googling implicates an issue with yarn - [according to one poster](https://github.com/sass/node-sass/issues/1804#issuecomment-265972823) you might try:

```bash
yarn install --force
```

**Comment by radinamatic** [comment]
🙏 💥 👯 

@indirectlylit `--force` flag did the trick 👍, thanks for googling that for me... :woman_facepalming:

**Comment by radinamatic** [comment]
I'll update the `Getting Started` dos with the tip, and some small corrections!

**Comment by djholmes** [comment]
yarn install and yarn install --force is not working for me i am getting webpack compilation is still in progress or not able to load default frontend please help. below is the error i am getting


Request Method: | GET
-- | --
http://127.0.0.1:8000/setup_wizard/
1.11.10
WebpackError
Webpack compilation still in progress
kolibri/core/webpack/hooks.py in _stats_file_content, line 124
/home/pratham/.venvs/kolibri/bin/python
2.7.6
['/home/pratham/kolibri/kolibri/dist',  '',  '/home/pratham/.venvs/kolibri/lib/python2.7',  '/home/pratham/.venvs/kolibri/lib/python2.7/plat-x86_64-linux-gnu',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-tk',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-old',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/pratham/.venvs/kolibri/local/lib/python2.7/site-packages',  '/home/pratham/kolibri',  '/home/pratham/.venvs/kolibri/lib/python2.7/site-packages',  '/home/pratham/kolibri/kolibri/dist/py2only']
Thu, 15 Mar 2018 11:58:30 +0530

**Comment by rtibbles** [comment]
Hi @djholmes, if you receive this error, it means that the webpack build process has not completed yet. If you then wait and it completes and you still experience an error, please let us know!
