### ISSUE TITLE
Session is not updated after editing profile

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1371]
## Summary

The session object within store is not updated after edits to profile are made. Prevents the following case:

1. Bob has a username of `bobby`
2. Changes username to `bobthebo$$`
3. Without navigating away, decides to change username back to `bobby`. Fails.

Due to checks within `editProfile` that compare edits with those in the store session object.

**Comment by DXCanas** [comment]
Will pick up after .4x stuff is finished

**Comment by christianmemije** [comment]
Addressed in #1372
