### ISSUE TITLE
Broken exercise loading 

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#1374]
## Summary

Exercises are unable to load. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Latest Develop
 - Operating system: OSX Yosemite
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
[Vue warn]: Invalid prop: type check failed for prop "itemId". Expected String, got Null. 
(found in component <exercise-perseus-renderer>)
```

## How to reproduce

Go this channel fb51dae6df7545af8455aa3a0c32048d (Portion Control) and click on an exercise. Seems is only broken for some channels.

## Screenshots

![screen shot 2017-04-27 at 4 00 11 pm](https://cloud.githubusercontent.com/assets/6361732/25507711/a44482f0-2b62-11e7-9e08-6d7e090f0b42.png)

**Comment by indirectlylit** [comment]
sounds like this was fixed by a CC server update?

**Comment by ralphiee22** [comment]
yes, that is correct.
