### ISSUE TITLE
On Coach Reports, change "X/Y mastered" into "X/Y completed"

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1375]
## Summary

May be an ongoing UX issue, but the word "mastered" introduced confusion to all Implementations team members who tested coach reports.

Conclusion from testing is that "completed" sounds more appropriate given the formative nature of exercises.

![screen shot 2017-04-27 at 4 04 29 pm](https://cloud.githubusercontent.com/assets/6668144/25507848/39167730-2b63-11e7-9dd9-d19fe5dcb3ae.png)

**Comment by rtibbles** [comment]
Closed by #1380
