### ISSUE TITLE
Add tooltips to data in Coach tables

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1378]
## Summary

Metadata such as "X resources / X exercises" aren't immediately understandable. Short-term solution: tooltips?

Even in context with other things on the page, it is not intuitive. 

Something that can help is tooltips, although ultimately, we may need to brainstorm better names for the two columns, or consider combining them given the discussion around #1375 . 

Tooltip examples here in a prototype: https://projects.invisionapp.com/share/7D8ZDY4EN#/screens/220191549
![apr-27-2017 17-21-14](https://cloud.githubusercontent.com/assets/6668144/25509452/ffa62c38-2b6d-11e7-84eb-755527d00a5a.gif)

**Comment by indirectlylit** [comment]
@jtamiace this should be straightforward if we can enumerate the exact locations and content of the tooltips

**Comment by indirectlylit** [comment]
no longer relevant
