### ISSUE TITLE
Coach Report: exercise & resource counter are not counting contents within topics

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1379]
## Summary

It is only counting what is displaying on the current page 

![screen shot 2017-04-27 at 5 23 37 pm](https://cloud.githubusercontent.com/assets/6668144/25509524/92349b2a-2b6e-11e7-88a5-005145b4b05e.png)

**Comment by rtibbles** [comment]
Note: This only happens at the top level (for a channel), within a topic, the counts are accurate.
