### ISSUE TITLE
Windows Installer for Instant Schools not showing Instant Schools UI

### ISSUE THREAD

**Issue by Kevsy** [learningequality/kolibri#1386]
## Summary

Windows Installer for Instant Schools shows the regular Kolibri UI, not the Instant Schools UI.

@aronasorman  could this be caused if the environment variables that enable the Instant Schools plugins are missing in the Windows installer?

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: KolibriSetup-0.3.1b3-instant-schools.exe from https://drive.google.com/file/d/0BziX9-4A2RIIdmQzcExzZkFZdlU/view?usp=sharing 
 - Operating system: Windows 10, Windows Server
 - Browser: all

## How to reproduce

1. Run the Windows installer
1. Start Kolibri
1. Load in browser

## Screenshots

![capture](https://cloud.githubusercontent.com/assets/7903978/25519496/f245cd32-2bef-11e7-93b5-d51c2811f3bf.PNG)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Critical for launch

**Comment by rtibbles** [comment]
Hi @Kevsy this is a result of the current pipeline for the Kolibri windows installer, which does not pull in the instant schools plugin early enough for the frontend assets to be built in the correct way. A new pipeline is being created to allow this to happen, and there is an open issue for it here: https://github.com/learningequality/kolibri-installer-windows/issues/9

**Comment by rtibbles** [comment]
I think this has been fixed.
