### ISSUE TITLE
Exam report is not showing what the learner has attempted.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1387]
## Summary

Learner attempted all the questions in exam but showing most of the questions not attempted and some attempted in exam report when logged in as a Coach.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach.
2. Click on Coach.
3. Select the class.
4. Click on Exams tab.
5. Select the View report in down arrow of Exam which learner has given.
6. Click on User.

## Screenshots

![111](https://cloud.githubusercontent.com/assets/12776071/25522185/9f51d352-2c1f-11e7-9dc2-939bb82583aa.png)
![112](https://cloud.githubusercontent.com/assets/12776071/25522186/9f52e530-2c1f-11e7-8bd3-2b8c26c7b43c.png)
![113](https://cloud.githubusercontent.com/assets/12776071/25522187/9f53fc86-2c1f-11e7-9927-f651816145ad.png)
![114](https://cloud.githubusercontent.com/assets/12776071/25522190/9f56dadc-2c1f-11e7-9593-fe3b24808c26.png)

Coach user Exam report:

![115](https://cloud.githubusercontent.com/assets/12776071/25522188/9f542e68-2c1f-11e7-816f-90a64586eb2f.png)
![116](https://cloud.githubusercontent.com/assets/12776071/25522189/9f56c394-2c1f-11e7-9427-cf4cc66d0d19.png)

**Comment by rtibbles** [comment]
Will attempt to replicate.

**Comment by rtibbles** [comment]
This actually has the same underlying cause as #1343 - the fix I submit should fix this too!

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.0alpha7. Now, exam report is showing what learner has attempted in exam.

![screen shot 2017-05-02 at 12 15 11 pm](https://cloud.githubusercontent.com/assets/12776071/25607031/3b4f9fb8-2f32-11e7-9f6e-79bd0d339c27.png)
![screen shot 2017-05-02 at 12 15 13 pm](https://cloud.githubusercontent.com/assets/12776071/25607030/3b49e924-2f32-11e7-8df8-bf141a86c2a8.png)
