### ISSUE TITLE
Learner should able to view question wise report after submitting the exam(Enhancement).

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1388]
## Summary
Learner is able to view result only but not able to view report question wise.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Learner.
2. Click on Exams tab.
3. Start the exam.
4. Submit the exam.

## Screenshots
![screen shot 2017-04-28 at 2 11 16 pm](https://cloud.githubusercontent.com/assets/12776071/25522582/16f175c4-2c21-11e7-86ca-64aa25aab8de.png)

**Comment by rtibbles** [comment]
Not part of current spec, but we can look at implementing in the future.

**Comment by indirectlylit** [comment]
migrating to https://trello.com/c/YV5Z6qkS/810-learner-exam-report

needs design and triaging. @swapnil106111  we'd be interested to know how critical this feature is for you
