### ISSUE TITLE
when coach user views not started learners exam report page hangs.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1389]
## Summary
When Coach user is viewing report of exam of user who do not started exam yet, then page hangs.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach.
2. Click on Coach.
3. Select the class.
4. Click on Exams tab.
5. Select the View report in down arrow of Exam which learner has given.
6. Click on User who has not attempted the exam yet.

## Screenshots
![1234](https://cloud.githubusercontent.com/assets/12776071/25526790/d93c2db6-2c32-11e7-8a11-ed3659b95387.png)
![12345](https://cloud.githubusercontent.com/assets/12776071/25526789/d9395ba4-2c32-11e7-9e69-9bebc1d96a7c.png)

**Comment by rtibbles** [comment]
Need a little more error checking, will fix.

**Comment by swapnil106111** [comment]
@rtibbles Tested Kolibri 0.4.0alpha7. Now, coach user not able to click on learner who is not attempted the exam.

![screen shot 2017-05-02 at 12 41 32 pm](https://cloud.githubusercontent.com/assets/12776071/25607594/e4127ccc-2f34-11e7-9084-3c9916e82d76.png)
