### ISSUE TITLE
`kolibri -h` is out-of-date

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#139]
Running `kolibri -h` does not mention the `--webpack` and `--karma` flags.

It also says that everything following the `--` are "passed on to the django manage command", but this isn't true for those flags.

**Comment by benjaoming** [comment]
The CLI usage string had a revisit in #1562 and #1598, removing the `--watch` flag. The correct way to see these flags is: `kolibri manage help devserver`
