### ISSUE TITLE
Sorting functionalities on Coach reports

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1390]
## Summary
Sorting on functionalities on recents tab,Topics tab and Exams tab.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Coach user.
2. Click on class name.
3. then you will see Recent, Topics and Exams tab.
4. In those tabs, sort the data according to Name or progress.

## Screenshots
![sort in recet](https://cloud.githubusercontent.com/assets/12776071/25529182/a66db196-2c3e-11e7-8763-80556e4ae308.png)
![sort in topic area](https://cloud.githubusercontent.com/assets/12776071/25529181/a66be596-2c3e-11e7-9325-0433f149c31e.png)
![sort n exam](https://cloud.githubusercontent.com/assets/12776071/25529183/a66e1b4a-2c3e-11e7-997e-f57bb58fd86c.png)

**Comment by harishbalachandran** [comment]
@indirectlylit @rtibbles Thank you the sorting works well on Recent activity and Topics pages.

Can the same be implemented on the Exam reports section like mentioned above in the issue? It would be really helpful.
