### ISSUE TITLE
<Design Change> Can we please move the question attempt pane to the bottom of the exam screen.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1394]
## Summary

<Design Change> Can we please move the question attempt pane to the bottom of the exam screen.

**Reason for this request:**
1. The question area on the tab for displaying the question will increase and this will aid in accommodating images more easily.
2. Learners need to put a little more effort to skip a question and the learners get to focus on the question that is in front and not get diverted to the left side to skip quickly. 

## How to reproduce

1. View and learners completed exam report.

## Screenshots
**Presently:**

![exam mode](https://cloud.githubusercontent.com/assets/13453618/25530058/6a11681a-2c42-11e7-802b-59b554f7dafb.png)

**Possible design change: (Excuse for a really bad hand-writing)**
![img_20170428_182206](https://cloud.githubusercontent.com/assets/13453618/25530041/5554d3b2-2c42-11e7-867b-a9666ba2fa71.jpg)

**Comment by rtibbles** [comment]
@jtamiace @khangmach please assess.

**Comment by indirectlylit** [comment]
I'd also left a comment on exam layout here: https://github.com/learningequality/kolibri/issues/1357#issuecomment-297576588

**Comment by khangmach** [comment]
@indirectlylit @rtibbles

Per request, here's a short term re-appropriation of the submit button/previous/next buttons

https://cloud.githubusercontent.com/assets/25045166/25542331/ebd73e60-2c06-11e7-9814-4b4a8017c71c.png

**Comment by khangmach** [comment]
Hi @harishbalachandran, here's an example of an alternative layout for learner exams. Let us know your thoughts on the question layout and if there are any discrepancies we can go over them in more detail on thursday!

![slice](https://user-images.githubusercontent.com/25045166/28296772-11b86a30-6b1f-11e7-8d70-70c76108cd94.png)

**Comment by harishbalachandran** [comment]
@khangmach Looks great! Thanks.

**Comment by indirectlylit** [comment]
closing - this is now being tracked internally and the feedback will be incorporated in a future iteration of the exam screen
