### ISSUE TITLE
Exams, learner view - Showing that exams are assigned but none were actually created

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1398]
## Summary

Maybe just a typo?

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0alpha1.dev917
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Have no exams created
2. Create a Learner either from sign up or as an Admin
3. Log in as Learner and navigate to Exams

## Screenshots

![screen shot 2017-04-28 at 10 47 48 am](https://cloud.githubusercontent.com/assets/6668144/25540678/d99bc8ca-2c00-11e7-9a29-65a2033dfa04.png)

**Comment by rtibbles** [comment]
What a highly uninformative message!
