### ISSUE TITLE
Logging out: Drawer and Action Bar state change

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1408]
## Summary

* Drawer and Action Bar changes state after clicking log out for a brief second before navigating to the login page.
* Not too high priority but definitely not ideal. 

## How to reproduce

1. Log out.

## Demo

![jump](https://cloud.githubusercontent.com/assets/7193975/25586920/7dfd4914-2e56-11e7-8871-baa1a73b40d8.gif)

**Comment by jonboiser** [comment]
"Fixed" this bug by not prematurely logging the user out and just letting the browser refresh.
