### ISSUE TITLE
Hide "Exams" tab from Learner accounts that are not members of a class

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1411]
## Summary

Reason: Exams are a class-specific feature.
cc @khangmach 

## System information

 - Version: Kolibri 0.4.0alpha1.dev952
 - Operating system: MacOS Sierra
 - Browser: Chrome

![screen shot 2017-05-01 at 3 13 22 pm](https://cloud.githubusercontent.com/assets/6668144/25596937/be55045a-2e80-11e7-90a0-aa4dfb5ff09e.png)

**Comment by indirectlylit** [comment]
That makes sense to me

**Comment by khangmach** [comment]
yup. they should be hidden

**Comment by rtibbles** [comment]
Ditto - this also means that we don't have to worry so much about showing it in non-formal school contexts.

**Comment by rtibbles** [comment]
Fixed in #1436
