### ISSUE TITLE
Attempts made by learner is not reflected in the exercise report of the coach.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1413]
## Summary
When a learner solved exercise in learn, the same solved exercise is not reflected correctly in exercise report of a coach.

Channel ID:  78eed5c0b59b30c0a40c94c17c849af6

## System information

 - Version: Kolibri 0.4.0alpha7
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Attempts exercise in learn by log in as a Learner.
2. then login as a Coach user.
3. Click on Coach then select Class name.
4. In Recent tab, select channel.
5. Select the exercise on which learner attempted.
6. Select the learner.
7. Observe the question attempts. 

## Screenshots
attempts made by the learner:
![screen shot 2017-05-02 at 3 07 45 pm](https://cloud.githubusercontent.com/assets/12776071/25613287/51d205d2-2f4b-11e7-9d82-af0a1390f688.png)

viewing the report as a coach for the same exercise:
![coach reprot off](https://cloud.githubusercontent.com/assets/12776071/25613309/63265978-2f4b-11e7-81c7-a7d1062a22b3.png)

![student 12 report off](https://cloud.githubusercontent.com/assets/12776071/25613310/632dfa8e-2f4b-11e7-868d-62ebedd40aac.png)

**Comment by swapnil106111** [comment]
@rtibbles Retested on Channel ID 3991aadbea9c5b489f14099cdcc35d2d. Working fine with this channel ID.

![1](https://cloud.githubusercontent.com/assets/12776071/25615006/65fef23e-2f52-11e7-98b1-b5decd31b701.png)
![2](https://cloud.githubusercontent.com/assets/12776071/25615005/65f916a2-2f52-11e7-92c4-bd9f6e772904.png)

**Comment by rtibbles** [comment]
I am unable to use any exercises on `78eed5c0b59b30c0a40c94c17c849af6`, so am unable to replicate this. As suggested in the follow up, this is working fine on other channels.

**Comment by rtibbles** [comment]
Please follow up if it continues to be problematic.
