### ISSUE TITLE
<Critical> Mastery of one exercise masters other exercises due to duplicated content IDs

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1414]
## Summary

Mastered 3 exercise (within Reading,writing, and drawing fractions) only and got 1500 (500 points for each exercise) points, but found that all the exercise within the channel are completed and mastered, without the learner attempting any. 

On the coach report: when we see the progress of the exercises that the learner had not attempted, it redirects to the ones that learner had attempted.

Channel ID used: 3991aadbea9c5b489f14099cdcc35d2d

## System information
 - Version: Kolibri 0.4.0.alpha7
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce

1. Login as a learner 
2. Master all the exercise inside a folder.
3. Observe all other exercises.
4. It shows all of them as mastered inspite of the learner has not attempted others.

## Screenshots
**Logged in as a learner: Shows all the exercises mastered .**

![learner](https://cloud.githubusercontent.com/assets/13453618/25615954/beaf49b0-2f57-11e7-96d9-e52ef53f0fb1.gif)

**The coach report of the same learner:**
Look at the Exercise names carefully it changes:
![coach report 1](https://cloud.githubusercontent.com/assets/13453618/25615567/974639a8-2f55-11e7-9c2d-c7d06c493153.gif)
![coach reprot 2](https://cloud.githubusercontent.com/assets/13453618/25615566/9745df9e-2f55-11e7-98f6-8b1cb79e6c35.gif)

**Comment by harishbalachandran** [comment]
When the learner mastered **Level 1 : Proper, Improper and Mixed fractions**, all the exercise that says **Level 1** gets mastered automatically.

![2](https://cloud.githubusercontent.com/assets/13453618/25617303/447ea1ba-2f5f-11e7-9dd3-267f36903707.png)
![3](https://cloud.githubusercontent.com/assets/13453618/25617302/4434a16e-2f5f-11e7-94db-a35d9903f913.png)

**All the exercise with Level 1 is getting mastered automatically:**
![4](https://cloud.githubusercontent.com/assets/13453618/25617530/59cbdb2c-2f60-11e7-9142-4612be29b8b3.png)

**Comment by harishbalachandran** [comment]
Mastered **Level 2 : Reading, writing and Drawing fractions** and found all the Level 2 to be mastered.

![level 2](https://cloud.githubusercontent.com/assets/13453618/25618078/0e492e86-2f63-11e7-9faa-8293ec155e76.png)
![level2 2](https://cloud.githubusercontent.com/assets/13453618/25618107/33607440-2f63-11e7-8976-29c08b5f3845.png)
![level 3 3](https://cloud.githubusercontent.com/assets/13453618/25618090/1bd03a18-2f63-11e7-972d-5fce264bad03.png)
![all level 2 are done](https://cloud.githubusercontent.com/assets/13453618/25618125/476fc5f8-2f63-11e7-8f1c-04f15afa12d7.png)

**Comment by rtibbles** [comment]
Good catch - I think I know why this is happening. Will fix.

**Comment by rtibbles** [comment]
Not able to directly replicate in another channel. Will look at your channel in particular next.

**Comment by rtibbles** [comment]
Have replicated this in the channel that you found this bug in. The issue seems to be that there are distinct content items in the channel that share a `content_id` @aronasorman @ralphiee22 @jayoshih please investigate where these duplicate `content_id`s are occurring!

**Comment by jayoshih** [comment]
This sounds like it could be a result of using the same source_id for multiple nodes. @yogeshmhaskule do you know how the source_ids are determined in the Magogenie sushi chef? Also, could you upgrade your Ricecooker to v0.5.6 as it adds a fix that will allow us to debug more of what's causing this issue? Thanks

Explanation from README:
`IMPORTANT: nodes representing distinct pieces of content MUST have distinct source_ids. Each node has a content_id (computed as a function of the source_domain and the node's source_id) that uniquely identifies a piece of content within Kolibri for tracking purposes. For example, if the same video occurs in multiple places in the tree, you would use the same source_id for those nodes -- but content nodes that aren't for that video need to have different source_ids.`
