### ISSUE TITLE
Some of the facility configurations are not working.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1415]
## Summary
Allow user to change their password and allow user to delete their account is not working.

## System information
 - Version: Kolibri 0.4.0alpha7
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Device owner.
2. Click on manage and then select Facility tab.

## Screenshots

![screen shot 2017-05-02 at 6 13 47 pm](https://cloud.githubusercontent.com/assets/12776071/25618210/a7883baa-2f63-11e7-9f78-00b03449ad51.png)

**Comment by rtibbles** [comment]
Fixed in #1425

**Comment by harishbalachandran** [comment]
@rtibbles Retested looks okey. The ones available are working.

![1415_1](https://cloud.githubusercontent.com/assets/13453618/25698019/dda7658a-30da-11e7-9bb0-bbb6c7ab954c.png)
![1415_2](https://cloud.githubusercontent.com/assets/13453618/25698020/de7a4f7c-30da-11e7-87bb-f8c9a6412c0e.png)
