### ISSUE TITLE
On removing the previously recorded answer from a question in exam, It still stores the previous data.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1416]
## Summary
On removing the previously recorded answer from a question in exam, It still stores the previous answer.

## System information
 - Version: Kolibri 0.4.0aplha7
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Attempted a question in exam.
2. Click on next question.
2. Go back to the question and clear the option.

**Expected result**
The cleared/deleted answer should go away from the question.

**Actual Result**
The answer entered is saved and does not delete, and the Question indicator also shows attempted only.

## Screenshots
1. First attempted answer:
![img-20170502-wa0004](https://cloud.githubusercontent.com/assets/13453618/25622481/2a622fd2-2f72-11e7-97ed-638b0158868f.jpg)

2. Deleting the attempted answer:
![img-20170502-wa0003](https://cloud.githubusercontent.com/assets/13453618/25622520/47f1ca76-2f72-11e7-93f5-5134e22b4666.jpg)

3. navigating to the some other question:
![img-20170502-wa0002](https://cloud.githubusercontent.com/assets/13453618/25622535/55cb8592-2f72-11e7-8e8e-5264fb6c7d69.jpg)

4. Navigate back to the same question to observe that the answer is not deleted.
![img-20170502-wa0001](https://cloud.githubusercontent.com/assets/13453618/25622566/6ba5c4f4-2f72-11e7-879d-8b825f80bf48.jpg)

**Comment by rtibbles** [comment]
Interesting - I had not thought that letting a student delete their answer without replacing it is desirable, so had not implemented for this eventuality.

Is this something that we want students to do? Isn't it always better exam practice to put an answer instead of no answer?

**Comment by indirectlylit** [comment]
> Is this something that we want students to do? Isn't it always better exam practice to put an answer instead of no answer?

Seems to me like there are two independent dimennsions to this:

* Are all answers required? This seems like something the teacher will eventually want to choose for themselves when designing the exam (alongside things like assigning point weight). If answers are required but left empty, the student should be notified.
* Does answer editing behave as expected? If the student has intentionally cleared an answer, they will expect that to be persisted. This is independent of whether they're allowed to submit the exam with empty answers.

**Comment by rtibbles** [comment]
Fair enough - I'll fix the second issue for now (which seems to be the concern here).

**Comment by harishbalachandran** [comment]
Tested works fine.
![1416_1](https://cloud.githubusercontent.com/assets/13453618/25698049/f96325ac-30da-11e7-8c1f-d10ca8cc4bab.png)
![1416_2](https://cloud.githubusercontent.com/assets/13453618/25698048/f9608554-30da-11e7-9682-10f2d10c86d4.png)
