### ISSUE TITLE
Exercise points snackbar doesn't disappear

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#1417]
## Summary

Upon completing any kind of exercise or watching a video, I am awarded points but the snackbar indicator that appears doesn't disappear after waiting a certain amount of time, as desired.

## How to reproduce

1. Navigate to Learn
2. Complete any exercise
3. Watch for indicated problem

## Screenshots
https://cloud.githubusercontent.com/assets/25045166/25634969/5fd95d84-2f31-11e7-9755-e50a3219584e.png

**Comment by rtibbles** [comment]
Ah, this was no clear from the mockup.
