### ISSUE TITLE
Display the icon and title of 

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1418]
## Summary

*Briefly describe the issue and please DELETE the non applicable headings below. *

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: ?
 - Operating system: ?
 - Browser: ?

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Steps
1. To
1. Reproduce

## Screenshots

*If applicable*

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by indirectlylit** [comment]
I'm gonna, um, close this as 'fixed'

:)

**Comment by jtamiace** [comment]
WOOPS
