### ISSUE TITLE
Short term enhancements to learner view of exercise mastered

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1419]
## Summary

A few suggestions:

* Float the "NEXT ITEM" button to the right side
* Place arrow within the next item button on the right side
* Display the icon and title of the next item near the "NEXT ITEM" button

## System information

 - Version: Kolibri 0.4.0alpha1.dev977
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Master any exercise

## Screenshots
![screen shot 2017-05-02 at 11 47 46 am](https://cloud.githubusercontent.com/assets/6668144/25635114/daf75570-2f31-11e7-9024-dcc18106d1cc.png)

**Comment by rtibbles** [comment]
This is fixed on 0.4.x
