### ISSUE TITLE
show progress indicators on topics cards in learner view

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1420]
Currently we only show progress indicators on content items. We should also show them on topics.

This will involve some cache clearing of parent topic progress data after interacting with child content.

**Comment by jtamiace** [comment]
cc @khangmach 

We had some previous designs where we displayed things like percentages, "X / Y completed", etc on topic cards

I have no idea where those designs are now

**Comment by jtamiace** [comment]
It's the one that got away

**Comment by indirectlylit** [comment]
For a first pass, would it be reasonable to use the exact same icons as for content items?

**Comment by khangmach** [comment]
I sea little reason reason to give topics not complete/in progress/complete icons. Seems redundant and makes them look like content items, which they shouldn't be looking like, because they're navigational items. Given that a class has had a lot of time to work through kolibri and is a good portion through their school time, these topics will always have in progress icons assigned to them. 

Using progress bars instead would be more useful, I think.

**Comment by rtibbles** [comment]
There is a slightly orthogonal concern, which is that you could be **done** with a topic, without actually having exhaustively completed every content item inside it. I think that supports @khangmach's proposed differentiation of content and topics - which leaves us open to flag **topics** as complete in the future, if we tie that to a group of assessment outcomes, for example.

**Comment by indirectlylit** [comment]
valid points, just trying to think of the quickest possible solution

> reason to give topics not complete/in progress/complete icons

The main use-case is almost like how HTML links have a 'visited' state: having a basic "In progress" vs "Not started" distinction would help people navigate the tree based on scanning for stuff they've touched or not touched.

**Comment by khangmach** [comment]
Addressed and incorporated the icons here : https://invis.io/ZTA3FH2S2#/226351535_Topics_1

**Comment by rtibbles** [comment]
Worth noting that we have currently disabled the annotation on the backend that would allow this due to performance considerations.

**Comment by khangmach** [comment]
@rtibbles what annotation? does this merit a redesign of how progress should look like on topic cards?

**Comment by indirectlylit** [comment]
I think in the current design, you have a little progress bar running along the bottom? That seemed good.

The open question is whether it's feasible to re-introduce the annotations and maintain reasonable performance @rtibbles ?

**Comment by rtibbles** [comment]
Right - I think we can do it, but we may want to think of it as a progressive enhancement to the interface, rather than something that is present at page load.

**Comment by rtibbles** [comment]
In fact, I would like to think about this in general as part of an optimization push - what things are *needed* before the user interface is meaningful, and what things can we load more asynchronously to add in additional details.

PWA 4 lyf.
