### ISSUE TITLE
When creating a new user in "Users", autofocus on the 'Full name' field

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1422]
## Summary

Something noticed during the user testing with Implementations folks.

It could make the user account creation experience faster to have the Full name field auto focused after "ADD NEW" is clicked in Users, so that extra time isn't taken to click the field. 
With potentially hundreds of accounts being created on one device, it'd be nice to streamline where we can.

While it is nicely keyboard accessible with just two "tabs", that kind of interaction is not always apparent.

## System information

 - Version: Kolibri 0.4.0alpha1.dev977
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Log in as Admin or Device Owner
2. Navigate to Manage
3. Navigate to Users
4. Click "ADD NEW"

## Screenshots

![screen shot 2017-05-02 at 3 00 43 pm](https://cloud.githubusercontent.com/assets/6668144/25641452/f9d3c980-2f48-11e7-803b-50695cac1292.png)

**Comment by christianmemije** [comment]
This occurs for all forms within a modal. The autofocus conflicts with the `core-modal`'s focus. cc @DXCanas

**Comment by DXCanas** [comment]
@christianmemije This seems like a feature request. What are you saying happens with all forms within a modal?

**Comment by christianmemije** [comment]
https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/user-page/user-create-modal.vue#L13

We are already setting the textbox to autofocus, but it is not actually working.

**Comment by indirectlylit** [comment]
can update to this:

```javascript
    mounted() {
      this.lastFocus = document.activeElement;
      this.$nextTick(() => {
        if (!this.$refs.modal.contains(document.activeElement)) {
          this.focusModal();
        }
      });
```
