### ISSUE TITLE
<Query> If the exercise is shared across two channels then the learners progress on one channel is recorded across both the channels.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1426]
## Summary
<Query> If the exercise is shared across two channels then the learners progress on one channel is also recorded across all the channels. This seams to be fair use case, please confirm if this is how its been built. 

The channel ID: 45acc22384394eeeb9d9a33d74eec574
The channel ID: 3991aadbea9c5b489f14099cdcc35d2d

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0aplha7
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## Screenshots
![exercise same shared across 2 channel](https://cloud.githubusercontent.com/assets/13453618/25656457/b248ac38-3016-11e7-9c88-9a92b552b660.png)

**Comment by rtibbles** [comment]
Yes, this is by design!
