### ISSUE TITLE
Error message is incorrect, when a coach tries to create an exam with not enough question in the exercise he/she has selected.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1427]
## Summary

Error message is incorrect, when a coach tries to create an exam with not enough question in the exercise he/she has selected.

Please refer the screenshot for the error message looks a bit off. 

It could read: **Not enough questions on the selected exercise or Reduce the number of questions to create an exam**

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Try creating an exam with total number of question exceeding the number of questions present in the exercise.

## Screenshots
![error message during exam creation](https://cloud.githubusercontent.com/assets/13453618/25656916/eb158b1a-3018-11e7-9dee-36d63daeb33b.png)

**Comment by rtibbles** [comment]
Should be closed by #1439

**Comment by harishbalachandran** [comment]
Retested the error message makes a lot of sense. Thanks.
![1427](https://cloud.githubusercontent.com/assets/13453618/25698119/3d68bf78-30db-11e7-8dc3-935e1e57bd9f.png)
