### ISSUE TITLE
<Enhancement> Student exam report can be showed which is very similar to the Coach exam report for self tracking.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1428]
## Summary

Presently, The kids themselves cannot access their performance on an exam because ,they cannot see their attempts or the report.

It would be great if the same report that a coach can see be made accessible to the learner.  

**Reason for this request:**
1. The kids once they finish will look at which questions they went wrong.
2. The kids can work with others kids/coach to rectify their mistakes, without teacher taking the pains to go through and then rectify or help learner.

 
## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## Screenshots

If the below report can be made available to kids too then it would be good.
![attempts 1](https://cloud.githubusercontent.com/assets/13453618/25662025/965e8fe6-3030-11e7-9ed0-2aaa12ba8a42.png)
![attempts 2](https://cloud.githubusercontent.com/assets/13453618/25662027/97b8bbe6-3030-11e7-8b03-a931e57f7342.png)

**Comment by rtibbles** [comment]
This would require some significant changes, so we cannot bring this in before the release, but we will look at it for 0.5.x.

**Comment by indirectlylit** [comment]
this task requires design and prioritization - migrating to trello: https://trello.com/c/3o66mWhV/808-student-focused-exam-reports

**Comment by indirectlylit** [comment]
similar issue filed here: #1388

**Comment by indirectlylit** [comment]
closing - this is now being tracked internally as a new feature on our roadmap
