### ISSUE TITLE
<Enhancement> The over all score displayed within the exam report for a learner shows in decimal

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1430]
## Summary

<Enhancement> The over all score displayed within the exam report for a learner shows in decimal.

Instead the score could be in percentages.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Give an exam.
2. Open up the exam report. 
3. Observe the top left corner which reads "Overall score"

## Screenshots
![over all score](https://cloud.githubusercontent.com/assets/13453618/25662682/fe1de71a-3032-11e7-9b35-72a16f24bb39.png)

**Comment by rtibbles** [comment]
Should be percentage

**Comment by harishbalachandran** [comment]
Looks great Thanks!
![1430](https://cloud.githubusercontent.com/assets/13453618/25698247/bbdf1a14-30db-11e7-946f-fc30181c14a5.png)
