### ISSUE TITLE
Exam status on the coach exam report is confusing.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1431]
## Summary
The status column on the view report section is not clear and is confusing.

1. For a learner who has completed an exam it shows the status as 9 out 10, it should be completed or submitted.
2. For a learner who has not completed an exam and is in progress also shows status 3 out 10. This is fine but a note like **"In progress, 3 out 10"**  will be more clear.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Submit and exam as a learner
2. Attempt only few questions for another learner and let it stay in inprogress
3. Login as a coach and observe the exam status.

## Screenshots
**Exam status:**
![unclear about the status](https://cloud.githubusercontent.com/assets/13453618/25663275/d21eb818-3034-11e7-92aa-18dde3b2467f.png)

Completed exam:
![completed exam](https://cloud.githubusercontent.com/assets/13453618/25663289/e214ee40-3034-11e7-9138-7c90c1b85f85.png)

In progress exam:
![in progress](https://cloud.githubusercontent.com/assets/13453618/25663305/ec859d02-3034-11e7-8357-26d34ed834e9.png)

**Comment by khangmach** [comment]
@christianmemije 

for case 1: student completes an exam. Let's keep the score column intact, but instead of showing "3 out of 10", we'll just say "Complete"

for case 2: an exam in progress, let's say "X questions remaining", that way, the teacher will know the exam is still in progress + how many questions the learner still has to answer.

**Comment by rtibbles** [comment]
Fixed in #1438

**Comment by harishbalachandran** [comment]
Now it looks good. Thanks!
![1431](https://cloud.githubusercontent.com/assets/13453618/25698284/e1b5249a-30db-11e7-8502-dff27cc01d05.png)
