### ISSUE TITLE
Exercises questions and answers not randomized

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1445]
## Summary

The question order and answer options order aren't randomized on Kolibri, despite selecting for the feature in the exercise editor on the CC server.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: VF version 0.3 beta2
 - Operating system: online demo - instantschools.learningequality.org
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Create exercise and questions via the exercise editor on the CC server (Be Strong Online channel)
1. Check the box where it says 'Randomize question order for learner' and 'Randomize answer order for learner'
1. Publish channel
1. Import channel to Kolibri
1. Select exercise and start answering questions

## Screenshots

Not sure the best way to visualize this - best to give you the Channel name as an example: BeStrong Online.  There's a quiz per Module.

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by rtibbles** [comment]
@jayoshih - can you investigate this from the CC side, to ensure that the data is being published correctly, and I'll look at it from the Kolibri end?

**Comment by rtibbles** [comment]
Actually, don't worry @jayoshih - files seem to be formatted correctly: https://instantschools.learningequality.org/zipcontent/9fd8c8c8b87174b448a1ffc670bbc553.perseus/128efab2d181459899a2f958f8c7047f.json

https://instantschools.learningequality.org/zipcontent/9fd8c8c8b87174b448a1ffc670bbc553.perseus/exercise.json

**Comment by rtibbles** [comment]
Seems like question randomization was not implemented prior to 0.4.x.

**Comment by rtibbles** [comment]
@jeepurs seems like the answer randomization is incorrectly implemented in 0.3.x and 0.4.x.

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/76 for 0.4.x.
