### ISSUE TITLE
Exercise mastery criteria doesn't match the selection chosen on CC workshop

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1446]
## Summary

The mastery model for exercises created using the exercise editor on CC server does not match the option selected.  E.g. 100% correct selected doesn't allow for the right number of 'check marks
## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: VF 0.3
 - Operating system: Online demo instantschool.learningequality.org
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Create an exercise using the editor on CC server.
1. Select '100% correct' under 'Master criteria'
1. Publish channel
1. Import channel to Kolibri
1. Start the exercise - the sections which shows the number of check marks needed for mastery (below the body of the question) doesn't reflect the selected criteria.  I tried this for different types of criteria - 3 in a row, 5 in a row.  None were showing correctly on Kolibri learner view.
1. In some cases, the green check mark for mastery shows up prematurely

## Screenshots

![screenshot from 2017-05-04 18 43 51](https://cloud.githubusercontent.com/assets/5150483/25757291/c3d3a534-317e-11e7-96b6-8900adb9a2a4.png)
![screenshot from 2017-05-04 18 47 15](https://cloud.githubusercontent.com/assets/5150483/25757309/d1063da2-317e-11e7-8147-82d8f29068f1.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by rtibbles** [comment]
This is due to the fact that non-`m_of_n` mastery models were not implemented in Kolibri before 0.4.x.

@jayoshih for things to be backwards compatible, we would have to make sure that the `exercise.json` file being generated only uses `m_of_n` mastery models, while the assessmentmetadata in the database can use all of them. Does this sound like a reasonable fix?

**Comment by rtibbles** [comment]
Fixed in https://github.com/fle-internal/content-curation/pull/269
