### ISSUE TITLE
Change button text on "Get a hint" if learner takes a hint

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1447]
## Summary

During the bug bash, there was confusion as to whether or not there were more hints available.
Solution open to discussion.

I think there was a PR where the hint button moved to the left side but the suggestions below would still apply.

## System information

 - Version: Kolibri 0.4.0beta1.dev7
 - Operating system: MacOS Sierra
 - Browser: Chrome

## Screenshots

Possible solution: change the hint button text after the first hint is taken and add a hint counter next to the button.

![hints](https://cloud.githubusercontent.com/assets/6668144/25757802/d8292912-3180-11e7-936c-b11b0095134e.png)

**Comment by rtibbles** [comment]
I guess I had always assumed that the `1/4` `2/4` etc. above each hint was sufficient for this.

**Comment by jtamiace** [comment]
Shivi brought up a point that it might be uninformative for learners who haven't learned fractions yet

**Comment by rtibbles** [comment]
True - perhaps we should make an upstream suggestion to KA on that front too - as those are Perseus rendered annotations.

**Comment by khangmach** [comment]
Could also place the counter within the button. 
[ Use a hint (3 left) ]
[ Use a hint (2 left) ]
[ Use a hint (0 left) ]

**Comment by jtamiace** [comment]
much better

![hints2](https://cloud.githubusercontent.com/assets/6668144/25758933/43ccd368-3185-11e7-9240-1721b46b1807.png)

**Comment by christianmemije** [comment]
> [ Use a hint (3 left) ]
   [ Use a hint (2 left) ]
   [ Use a hint (0 left) ]

For the last state, `No more hints` makes more sense than `Use a hint (0 left)`.

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/75
