### ISSUE TITLE
Add tooltip to progress icons on Learn?

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1448]
## Summary

Very minor initial confusion during the bash, but adding a tooltip to progress icons could add complete clarity as to what they mean. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0beta1.dev7
 - Operating system: MacOS Sierra
 - Browser: Chrome

## Screenshots

![tooltip](https://cloud.githubusercontent.com/assets/6668144/25759265/8267f5e8-3186-11e7-810f-d32185080f26.png)

**Comment by christianmemije** [comment]
Addressed in #1449
