### ISSUE TITLE
License field should say what the license is, not show the primary key

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1451]
Below content items, we show some metadata. For "license", we just show a numeric primary key, which means nothing to the user:

![image](https://cloud.githubusercontent.com/assets/618416/25861540/ebfbbae2-3499-11e7-8f81-ede791d07a2d.png)

We should prioritize this fix:
- Show the short name of the license (e.g. "CC-BY-NC-SA")

If it's easy, otherwise for a future release, also:
- Either a) Have the license name be clickable, or b) Have a "?" circle next to it that can be clicked, to pop up a model with the license description.
- Side note, while we're at it: if there is no Author, or no Copyright holder, perhaps we can just leave those out rather than showing "--"?

For context, here's what we have on the CC server:

![image](https://cloud.githubusercontent.com/assets/618416/25861756/770424d0-349a-11e7-93f0-561458ad98a4.png)

and then when you click the info bubble:

![image](https://cloud.githubusercontent.com/assets/618416/25861774/8b6299a2-349a-11e7-8a3d-5222121e0364.png)

**Comment by christianmemije** [comment]
@jamalex Currently the license model does not have a description. Where should the descriptions of the licenses come from?

**Comment by rtibbles** [comment]
Note @jamalex, unlike on the CC server, the license description is not distributed into the built content database, only the license name.

**Comment by indirectlylit** [comment]
Does the license integer correspond to an element in the `choices` tuple here?
https://github.com/learningequality/le-utils/blob/master/le_utils/constants/licenses.py#L13

**Comment by rtibbles** [comment]
Kind of - via this fixture, I believe: https://github.com/fle-internal/content-curation/blob/develop/contentcuration/contentcuration/fixtures/initial_data.json

**Comment by rtibbles** [comment]
@aronasorman @jayoshih it would be good if the descriptions data in this fixture was either exported to the Kolibri content DB, or part of le-utils, so it could be used alongside the standardized descriptions in our Kolibri frontend interface - however, it would also need to be made amenable to i18n.

**Comment by rtibbles** [comment]
Fixed in #1457

**Comment by rtibbles** [comment]
(but needs additional export in CC server to be fully functional)
