### ISSUE TITLE
viewing an exercise detail report logs activity for the exercise

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1461]
Steps to reproduce:

* create a coach or admin account
* add yourself to a class
* interact with an exercise
* wait a bit
* look at your detail report for that exercise
* go up a level - note that the 'last activity' is incorrect

![image](https://cloud.githubusercontent.com/assets/2367265/25881351/4fa89680-34f1-11e7-9f59-7313af245d8e.png)

**Comment by rtibbles** [comment]
I am almost certain that the same may well apply to exercises used in exams too. I should probably fix this in 0.4.x.

**Comment by rtibbles** [comment]
Should have been fixed in #1499.
