### ISSUE TITLE
Use links rather than click events

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1468]
## Summary

Sort of a tech debt piece. Used click events due to the structure of the template, but would make more sense to use links.

Initially meant for just report page components, going to start a list of places:
- [ ] Main sidebar nav
- [ ] Reports page attempts

**Comment by DXCanas** [comment]
Here, we're listening to a `select` event in a component that listens to click events to fire `select`. Might be better to have `interaction-list`be made up of `router-link`s instead of `div`s.

**Comment by indirectlylit** [comment]
low priority - removing milestone

**Comment by indirectlylit** [comment]
sidenav is being addressed here: #3559

many other instances have been fixed. Let's open individual issues for any others we find
