### ISSUE TITLE
<Enhancement> A pop up on the screen when a learner masters an exercise would be great.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1471]
## Summary

<Enhancement> A pop up on the screen when a learner masters an exercise would be great.

Presently the learner is not aware if he/she has mastered the topic, since the point addition happens very subtly.
Hence a Pop up on screen that would read "You have Mastered the Exercise and earned 500 points, Keep Going"  would be great. Anything even shorter would be great. 

Its just an on screen pop up would be great.

## System information

 - Version: 0.4.0Beta1
 - Operating system: Linus LTS 14.04
 - Browser: Chrome

## How to reproduce

1. Master an exercise on a tablet.
2. You not know if you have mastered the topic clearly .

## Screenshots

![img-20170511-wa0002](https://cloud.githubusercontent.com/assets/13453618/25945726/a11480a4-3665-11e7-9621-52a26a8be9c2.jpg)

![img-20170511-wa0001](https://cloud.githubusercontent.com/assets/13453618/25945727/a2af45b6-3665-11e7-87db-d9d6003a41f0.jpg)

**Comment by rtibbles** [comment]
Would it help if the points pop up appeared regardless of where you are scrolled to on the screen? (the issue seems to be that on the tablet, the points pop up is 'under the fold' at the top part of the screen).

**Comment by harishbalachandran** [comment]
@rtibbles That should do the trick, just increase the fade time of the pop up by few more seconds, presently it fades off quickly.

**Comment by rtibbles** [comment]
@khangmach ^ note will increase the fade time to 10 seconds from 5.

**Comment by khangmach** [comment]
https://cloud.githubusercontent.com/assets/25045166/25976223/62000868-3668-11e7-88ab-85ddfba9f9b6.png

thoughts on this popup?Perhaps it can fade in upon completion. I could make an animation for this if it's of some interest.

**Comment by rtibbles** [comment]
Note that it already does fade in and out!

**Comment by harishbalachandran** [comment]
This looks good! Thanks. In fact I would prefer the learner had to click on close to proceed further instead of fade out in 10s.

I kinda keeps the momentum and focus.

**Comment by khangmach** [comment]
The pop-up is re-addressed here:
https://cloud.githubusercontent.com/assets/25045166/26118317/4fdd576c-3a1e-11e7-9e5f-1d519045ea6e.png

already looked at by @christianmemije

**Comment by harishbalachandran** [comment]
@rtibbles the pop up pops perfectly :) 
But the pop up shows up with the background text and the alignment within the pop up is not perfect. 
![img-20170518-wa0002](https://cloud.githubusercontent.com/assets/13453618/26189885/762e3a9c-3bc4-11e7-8da2-c8dbfa4ebf6f.jpg)

**Comment by rtibbles** [comment]
Should be fixed completely in #1531

**Comment by harishbalachandran** [comment]
@rtibbles Looks good great now, but alignment at the centre of the screen would be great, presently its a bit left aligned like you see.
