### ISSUE TITLE
user and class management tables broken on smaller monitors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1476]
what ever media query code we're using causes the tables to be truncated and the layout to be broken:

![image](https://cloud.githubusercontent.com/assets/2367265/25972795/518a46f4-3656-11e7-988a-80511021c294.png)

Recommend stripping out any media queries and other responsive code, and adding 

```css
overflow-x: auto
```

to a wrapper around the tables. This has been an effective alternative to designing mobile views in report tables.

**Comment by radinamatic** [comment]
Still visible on [`0.5.0-beta1-dev22`](https://buildkite.com/learningequality/kolibri/builds/1673).

![win10 start running - oracle vm virtualbox_317](https://user-images.githubusercontent.com/1457929/28022371-450841ec-658b-11e7-9654-9a58e50dd7b1.png)
