### ISSUE TITLE
"Oh, cool, I've already earned 500 points, and haven't even started watching!"

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1478]
When I saw the greyed out points box, my initial (and post-initial) reaction was that I had already earned those points, and since nothing changed when I started watching, that assumption was reinforced.

![image](https://cloud.githubusercontent.com/assets/618416/25973804/88b2b66c-365a-11e7-88e9-645ae8535a9a.png)

Is it necessary to show "potential points" before they've been earned? If so, is there some way we can indicate more clearly that they're unearned? E.g. "0 / 500" or something?

**Comment by khangmach** [comment]
@jamalex i noticed that on many games, rewards that were already gained are greyed out/not clickable/not placed in focus because they're gone, you've got them. Therefore the user focus on something else on the page and have a feeling like they've already snagged that shiny attainable jewel. 

I feel like greyed out should == already attained reward
shiny leaf == leaf available and up for grabs

thoughts @jtamiace @rtibbles @indirectlylit?

**Comment by jtamiace** [comment]
I think that would still introduce the same problem, of the user thinking that they already earned the points because the number is there. I think either way, beginning greyed out or filled in, is okay and the state change after mastery/completion is learnable as long as the state change is consistent. 

For either case, filled in or greyed out, maybe the number shouldn't be showing if they hadn't yet completed/mastered the content. Could just show the leaf without anything next to it, or even a "?" next to the leaf?

**Comment by khangmach** [comment]
the thing is, different games present different rewards, which manifest themselves in different mediums. Points, pears, peaches, titles, all these mediums of currency have to be learnable by all users when they first encounter them. The quicker we can make our currency learnable, the better. I think the number has to show to provide context. Our currency is points, so we show points. 

Even if we put a "?" next to the leaf, would that still induce an air of mystery and juiciness once they realize they'll only get 500 points every time? My guess is not likely. Also question marks aren't universal. I'll look at other ways apps convey "you've unlocked it/you haven't", but generally games and apps follow the notion I introduced above.

**Comment by christianmemije** [comment]
Currently, that does not _not_ look clickable. Especially with the square/shadow, it kind of looks like a button.

**Comment by khangmach** [comment]
@christianmemije it's not meant to look or be clickable. 
proposed styling change here: 
https://cloud.githubusercontent.com/assets/25045166/25975740/f7728398-3664-11e7-9617-39144ce15787.png

**Comment by indirectlylit** [comment]
We have a transient pop-up which indicates when points are achieved. After engaging with a couple content items, most users will learn to expect this.

How about: remove the inline points indicator. Keep just the global points score and the transient "new points achieved" pop-ups.

**Comment by jtamiace** [comment]
> How about: remove the inline points indicator. Keep just the global points score and the transient "new points achieved" pop-ups.

I am actually a fan of this idea. Would lessen the number of indicators that lets a user know that a content was completed. 

I think the point indicator would be valuable only if there was a difference in number of points achieved per content.

**Comment by jtamiace** [comment]
Could reintroduce @rtibbles gambling algorithm that he used for KA Lite?

**Comment by rtibbles** [comment]
READ MY MIND!

**Comment by rtibbles** [comment]
(but no, because that would require tracking separately, unfortunately)

**Comment by rtibbles** [comment]
Unless... we just stored it as > 1 progress on an item.

**Comment by khangmach** [comment]
Wasn't the point of in-line point count to distinguish whether or not you've received points yet? You'd take away the visual incentive and would have no way of anticipating whether or not a new piece of content offers points or not. You'd have to infer that the gold mastery star next to the content card == you already got the points there, which isn't the purpose of the gold mastery star

**Comment by jtamiace** [comment]
You could argue that the user would make that association regardless of whether or not the points are there. The concurrent appearance of points (although transient) with the gold star implies that they are related. 

I'm wondering now if there even is visual incentive anymore, with the fact that the points are the same every time?

**Comment by indirectlylit** [comment]
We could make the pop-up not automatically disappear until the user navigates to a new page or manually dismisses it.

![image](https://cloud.githubusercontent.com/assets/2367265/25976148/cca09526-3667-11e7-9570-4836bfc6ac12.png)

> Would lessen the number of indicators

Agree that there's a lot of information here, and we're risking distracting from the content itself.

**Comment by khangmach** [comment]
well, then it sounds like we'll be assuming the in progress/mastery indicator is enough of an association to whether or not they'll get points. Which i think will also be learnable over time. 

thoughts on something like this then? 
https://cloud.githubusercontent.com/assets/25045166/25976595/e9e7d8ee-366a-11e7-8a94-4a1d8e9e536e.png

addressed somewhat here: #1471

**Comment by rtibbles** [comment]
Fixed in #1529
