### ISSUE TITLE
Wide screen is wide: whiplash caused by asking "Where are my points?"

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1479]
![image](https://cloud.githubusercontent.com/assets/618416/25973942/2b91f83e-365b-11e7-86c5-648722795fc8.png)

Should we have a max-width on the content area? Or have the points stay above the actual width of the content block?

**Comment by jamalex** [comment]
Related: When title is long and screen is narrow, points box goes behind video:

![image](https://cloud.githubusercontent.com/assets/618416/25974430/d7a5c036-365d-11e7-9e71-36fd5dcd4bfe.png)

**Comment by rtibbles** [comment]
Fixed in #1529
