### ISSUE TITLE
TypeError at /api/masterylog/

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1480]
## Summary

Was about to start interacting with an exercise on the new morango demo server: http://192.237.248.135:8808/learn/#/fb51dae6df7545af8455aa3a0c32048d/recommended/b9b1d066de3d4dad8ab78afc7d0fb4e7

Got this error:

* Request Method:	POST
* Request URL:	http://192.237.248.135:8808/api/masterylog/?1494540093775=1494540093775
* Django Version:	1.9.7
* Exception Type:	TypeError
* Exception Location:	/var/www/.pex/install/kolibri-0.4.0b1.dev45-py2.py3-none-any.whl.28cf6b61d36eb3b41a78d8dd3b958d0241da3c5d/kolibri-0.4.0b1.dev45-py2.py3-none-any.whl/kolibri/dist/rest_framework/serializers.py in create, line 862

* Exception Value:	Got a `TypeError` when calling `MasteryLog.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `MasteryLog.objects.create()`. You may need to make the field read-only, or override the MasteryLogSerializer.create() method to handle this correctly.
Original exception text was: coercing to Unicode: need string or buffer, int found.

## System information

http://192.237.248.135:8808/

**Comment by rtibbles** [comment]
This is fixed, but I can't find the change that @jamalex made to do so.
