### ISSUE TITLE
group 'move' button is enabled with nothing selected

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1481]
When moving users, the 'move' button is enabled regardless of whether anything is selected.

![image](https://cloud.githubusercontent.com/assets/2367265/25974447/f1e5dd0a-365d-11e7-827f-082a59d3cdf6.png)

Clicking move in this state results in general brokeness:

![image](https://cloud.githubusercontent.com/assets/2367265/25974461/10c9576a-365e-11e7-9029-ee2f74afe4ce.png)

We should disable the button when nothing is selected.

**Comment by christianmemije** [comment]
Fixed in #1483
