### ISSUE TITLE
error and freeze in exam report: multiple timers

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1482]
was browsing an exam detail report: http://192.237.248.135:8808/coach/#/448c7d75d493342a81edc36df4f34f35/fb51dae6df7545af8455aa3a0c32048d/exams/495eb64ef60a69b955ce8ae4769be9b2

Clicked two question two and then tried to click back to question 1, but can't:

![image](https://cloud.githubusercontent.com/assets/2367265/25974602/d5ac37f0-365e-11e7-9ffc-e406099bbfe5.png)

![image](https://cloud.githubusercontent.com/assets/2367265/25974606/dc81930e-365e-11e7-9a8f-2291e3459846.png)

**Comment by rtibbles** [comment]
This is due to the still extant tracking on the content renderer, fixing this.

**Comment by rtibbles** [comment]
Should have been fixed in #1499.
