### ISSUE TITLE
parent topic is not correctly linked from exercise report

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1484]
Exercise reports are currently parameterized by content ID rather than primary key, and don't include the parent topic in the URL. This means that the real parent becomes ambiguous, and one is chosen arbitrarily to be the 'return' link:

![img](https://cloud.githubusercontent.com/assets/2367265/25985780/4774039e-36a1-11e7-8587-fb7f3b885ae2.gif)

The two options are probably:

1. Retrieve just a single exercise by primary key instead of content ID. This is how we do it in the 'Learn' app, so presumably it would work here also? @rtibbles mentioned there might be a problem with this strategy, but I forget what it is.
2. Encode the parent topic in the URL. Use that to select the appropriate copy of the exercise here: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/state/actions/reports.js#L299

**Comment by rtibbles** [comment]
This should now be fixed.
