### ISSUE TITLE
Mathml not rendering onto kolibri(shown properly on perseus)

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/kolibri#1485]
## Summary

Mathml conversion of latex code not rendering properly onto kolibri. But I have checked same latex data on `http://khan.github.io/perseus/` where it shows properly.

Mathml Data: `<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>F</mi><mi>i</mi><mi>l</mi><mi>l</mi><mo>&#160;</mo><mi>i</mi><mi>n</mi><mo>&#160;</mo><mi>t</mi><mi>h</mi><mi>e</mi><mo>&#160;</mo><mi>b</mi><mi>l</mi><mi>a</mi><mi>n</mi><mi>k</mi><mo>.</mo><mspace linebreak="newline"/><mn>888</mn><mo>&#160;</mo><mo>&#215;</mo><mo>&#160;</mo><mn>0</mn><mo>&#160;</mo><mo>=</mo><mo>&#160;</mo><mi>_</mi><mi>_</mi><mi>_</mi><mi>_</mi><mi>_</mi></math>`

Latex Data: `Fill in the blank.$\phantom{\rule{0ex}{0ex}}888 \times 0 = \_\_\_\_\_$`

## System information

 - Version: kolibri 0.4.0beta1
 - Operating system: OS X EI Capitan
 - Browser: Chrome and Firefox
 - Channel Id: 8f64961a91274c35945459f846c9f2cb (Level2 -> Multiplication facts ->45261(question_id))

## Screenshots
1. Latex code onto perseus
![before_rendering](https://cloud.githubusercontent.com/assets/7850420/25996412/c7d17010-3734-11e7-8bef-c5d4113512c3.png)

![after_rendering](https://cloud.githubusercontent.com/assets/7850420/25996296/50133ed2-3734-11e7-80aa-a4808eb33e75.png)

2. Latex code onto kolibri

![screenshot_chrome](https://cloud.githubusercontent.com/assets/7850420/25996325/70e437f6-3734-11e7-8d30-2098816aaea5.png)
![screenshot_firefox](https://cloud.githubusercontent.com/assets/7850420/25996324/70e30bf6-3734-11e7-9093-52c9d6390190.png)

**Comment by harishbalachandran** [comment]
@rtibbles @jamalex @aronasorman can you please look at this issue. We are facing while importing the MG content.

**Comment by yogeshmhaskule** [comment]
@harishbalachandran @jamalex @rtibbles We have fixed in Sushi chef.
