### ISSUE TITLE
Unable to create username with "." in the name on device owner page.

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1488]
## Summary

When creating an account on the device owner page with a username containing a ".", the system is unresponsive.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.3.1b2-6
 - Operating system: Windows?
 - Browser: [Can update as I have more information next week]

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

Create a new device account with a username containing a "." (period)

## Screenshots

This issue took place during the UNICEF training in Greece. I don't have screenshots at this time but can work to reproduce if useful.

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

It would be helpful to have a meaningful warning or provide guidance on what characters cannot be included in a username.

**Comment by rtibbles** [comment]
We should either do client side validation, or produce a meaningful warning when the attempt to create a non-permissible user name is made.

**Comment by DXCanas** [comment]
Sorry I got so sidetracked about this. @christianmemije it's all yours, if you want it.

**Comment by indirectlylit** [comment]
> We should either do client side validation, or produce a meaningful warning when the attempt to create a non-permissible user name is made.

should probably do both, but the client-side validation would be sufficient and really help
