### ISSUE TITLE
"Recent" filter might be too recent on coach reports

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1489]
## Summary

Something I forgot to make an issue for during the last bug bash with Imps members. When they tried to view the coach report data that Khang and I made 1 week before that session on [http://192.237.248.135:8088/](http://192.237.248.135:8088/), they found they could no longer easily access it from Recent.

Navya only then observed that it is set at a hard "7 days". She noted that even though she might have her students work on content, she might still want to see performance on that content some time after 7 days. 

I remember that we decided to limit what shows by date in order to avoid overflowing the recent tab with content that goes on and on from the beginning of time, which I think is a good call. 

But maybe we can increase the time filter? "Showing recent activity in the past **30 days** maybe? Not sure what the best approach is, or how long teachers would want to reference a "recent" activity, for grading purposes.

## System information

 - Version: Kolibri 0.4.0beta1.dev7
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Get learner data
2. Open coach reports after 8 days

**Comment by rtibbles** [comment]
This is, in theory, dynamically changeable, so we could add a slider or somesuch to allow the value to be altered.

**Comment by rtibbles** [comment]
The slider could be on a log scale, so you start with 7 days, then 14 days, then 30 days, 2 months, 4 months, all time.

**Comment by indirectlylit** [comment]
added a note to trello so that we can triage this: https://trello.com/c/0hylFDUV/251-adjustable-time-range-for-recent-reports

**Comment by indirectlylit** [comment]
closing as this is now tracked in clearinghouse
