### ISSUE TITLE
intl polyfill is not loading - affects at least Safari and IE9

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#149]
**Branch** vue-hacking
**Browser** Safari 9.1.1

Followed the document at https://docs.google.com/document/d/1OrMHqOscjPHpbjx0eeEylzuS6A94nC2_tgwdBiJkH5E/edit# using Safari but it doesn't load the learn page, with this error

> ReferenceError: Can't find variable: Intl.  

Here's a screenshot:
![screenshot 2016-06-10 05 38 10](https://cloud.githubusercontent.com/assets/175580/15948871/e2300092-2ed5-11e6-8813-520f634dc6c0.png)

We tried to re-create our virtualenvs, removed the `node_modules` directory, and re-did the steps but got the same error.

**Workaround**: use Google Chrome.

**Comment by indirectlylit** [comment]
thanks for reporting this!

**Comment by indirectlylit** [comment]
updated title - this issue exists in master also

**Comment by rtibbles** [comment]
Seems our polyfill is not loading, @indirectlylit.

**Comment by rtibbles** [comment]
This is also an issue in IE9.
