### ISSUE TITLE
'NoneType' object has no attribute 'license_description'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1490]
## Summary

Deleted and re-imported portion control channel (`fb51dae6df7545af8455aa3a0c32048d`)

```
AttributeError at /learn/
'NoneType' object has no attribute 'license_description'
Request Method:    GET
Request URL:    http://localhost:8000/learn/
Django Version:    1.9.7
Exception Type:    AttributeError
Exception Value:    
'NoneType' object has no attribute 'license_description'
Exception Location:    kolibri/content/serializers.py in get_license_description, line 133
```

## System information

[learner reports working branch](https://github.com/learningequality/kolibri/pull/1464) (synced with latest 0.4.x)

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/commit/4d6254563898eb54b633fe1b1f3aaeb4f9c71a88
