### ISSUE TITLE
updating content db schema in Kolibri breaks app

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1491]
When the content db schema is updated, the `migrate` command doesn't affected downloaded databases. However, the app still assumes that that all databases are compatible.

This results in DB errors when simply trying to browse the app. For example, after upgrading kolibri, the learn app would not load and simply returned

```
no such column: content_license.license_description
```

Even if the goal was to somehow instruct users that they need to re-import content, the current behavior makes that difficult because the UI becomes ostensibly unavailable. (Technically, you can manually enter the 'management' URL but most users will not do that)

Things we could do:

* add schema version checking during content DB loading, and skip any that don't conform to the current schema
* load DB meta-data for out-of-date DBs, but surface user-feedback that they are no longer available because they're not compatible, and provide a quick link to re-import them
* add the ability to migrate content DB schemas after kolibri is updated

**Comment by rtibbles** [comment]
Fixed in #1947
