### ISSUE TITLE
API endpoint that exposes file size estimate for  imported channels

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1493]
In these designs for the 'import channel' workflow, the user sees an estimate of how large the data they are about to download:

Remote import:
https://projects.invisionapp.com/share/KDB49AZTW#/screens/226789628

Local import:
https://projects.invisionapp.com/share/KDB49AZTW#/screens/226789631

Like #1492, this requires a way to access the file size statistics for content sources, but the difference is that they are not stored on the device yet.

**Comment by lyw07** [comment]
The endpoint to get the file size of each contentnode is merged: https://github.com/learningequality/kolibri/pull/2573

**Comment by aronasorman** [comment]
Fixed with #2573
