### ISSUE TITLE
Return total time remaining for a Task

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1494]
Currently, the payload for a `Task` provides a progress as a percentage, but these designs would like to know how that translates to 'time remaining':

https://projects.invisionapp.com/share/KDB49AZTW#/screens/226789626

Doing this estimate on the client using the rate of change of percentage leads to unstable and/or inaccurate estimates because the client always has fewer data points than the server on which to base these estimates.

It would be preferable if this time estimate were provided as part of the `Task` payload.

**Comment by aronasorman** [comment]
Punting for 0.8.

**Comment by rtibbles** [comment]
5 years later, we've yet to come up with a good way of estimating the time remaining - and I am not confident that the backend has significantly more information to inform this than the frontend.
