### ISSUE TITLE
Ability to record when a channel was last updated (on the device)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1496]
Per this design, there is a 'last updated' column, which indicates the last time the channel was updated or downloaded for the first time.

https://projects.invisionapp.com/share/KDB49AZTW#/screens/226789607

This feature requires a place to store this data that can be cross-referenced with the channelId.

**Comment by jonboiser** [comment]
One path to implementation would be to extend `ChannelMetadataCache` with a date field like `datetime_last_updated`.

* When a channel is import from the internet or local drive, then `datetime_last_updated` is equal to the time when the download is completed.
* When a channel is "imported" from `.kolibri` folder and does not already exist in the cache, then `datetime_last_updated` is equal to the current datetime.
* When a channel is "imported" from `.kolibri` folder and already exists in the cache, then its `datetime_last_updated` is left alone.

**Comment by rtibbles** [comment]
Fixed in #1592
