### ISSUE TITLE
KA exercises are not loading on Kolibri 0.4.0beta2.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1504]
## Summary
The Channel ID: abb42df1203f4043a7b6e430de257d90, has both KA english and MG contents.

But we see that the only KA exercise are not loading in the front end.

## System information

 - Version: Kolibri 0.4.0beta2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Import the channel and check the KA exercises. 

## Screenshots
![questions not loading](https://cloud.githubusercontent.com/assets/13453618/26050970/527666c6-397e-11e7-949d-e0c852973151.png)

**Comment by rtibbles** [comment]
Fixed in #1523
