### ISSUE TITLE
The points on the top right corner shows 0, were as in Profile the learner has a lot of points.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1505]
## Summary

Mismatch between the points on the top right corner to the points on the profile.
 When a learner logs in every time he is shown 0, though he has more than 0 on his profile section.

## System information
 - Version: Kolibri 0.4.0beta2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Make sure the learner has some points under the profile section.
2. Login in with the same learner again.
3. Observe the points on the top right corner it shows 0, instead of the points in the profile section.

## Screenshots
![points shown as 0](https://cloud.githubusercontent.com/assets/13453618/26051802/f707fb3a-3980-11e7-8561-ee47ecb2932a.png)

![points shown as 1500](https://cloud.githubusercontent.com/assets/13453618/26051804/fa3b81f0-3980-11e7-98e0-32ff8dbd27b4.png)

**Comment by rtibbles** [comment]
@christianmemije can you attempt to replicate this locally?

**Comment by christianmemije** [comment]
@rtibbles Can reproduce. I thought this had been fixed by #1458, but I guess it wasn't... :thinking: Will look into it.

**Comment by rtibbles** [comment]
Should be fixed in #1507.
