### ISSUE TITLE
Not able to enter answers and proceed to next question for the polynomial topics of KA.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1512]
## Summary

Not able to enter answers and proceed to next question for the polynomial topics of KA on Kolibri.

Any answer entered cannot be removed or the learner cannot use the Math Input that pops up on the answer field. 

On Khan-academy side it works smoothly. 

## System information
 - Version: Kolibri 0.4.0beta2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Solve any KA exercise with Polynomial.
2. Try to enter the answer and proceed to the next question. 

## Screenshots
![whatsapp image 2017-05-16 at 3 35 02 pm](https://cloud.githubusercontent.com/assets/13453618/26102068/15b95972-3a51-11e7-95fe-0b41975659b1.jpeg)

![whatsapp image 2017-05-16 at 3 35 02 pm 6](https://cloud.githubusercontent.com/assets/13453618/26102197/a2b68f34-3a51-11e7-8912-88369b99717c.jpeg)

On Khan Academy it works perfectly:
![screen shot 2017-05-16 at 4 08 20 pm](https://cloud.githubusercontent.com/assets/13453618/26102273/f771bddc-3a51-11e7-982b-7dc7d2018fa9.png)

**Comment by DXCanas** [comment]
@rtibbles Looks like this is more than a styling issue. There are some weird things going out with the JS libraries. I have a feeling some race conditions might be involved? Going to look at it with some more depth tomorrow morning.

**Comment by harishbalachandran** [comment]
@rtibbles  On the laptops the Mathquill works perfect, very similar to KA.org.
**But on a tablet, it does not** 
1. The backspace does not work and cannot remove the entered values.
2. Once I select any of the operations such as exponent of a number, I cannot come out of it and continue writing the equation, since exponent selection stays ON.
![img_20170518_124852](https://cloud.githubusercontent.com/assets/13453618/26191010/c7804ce6-3bc9-11e7-80aa-bf5ede1f30f7.jpg)

**Comment by DXCanas** [comment]
@rtibbles work is going very slowly, but it seems like the question's validator isn't being defined properly on the tablet for some reason. Still debugging.

**Comment by harishbalachandran** [comment]
@jamalex, @rtibbles  and @DXCanas Sorry guys still unable to use in Tablets and Mobile phones.

![img_20170522_163601](https://cloud.githubusercontent.com/assets/13453618/26309013/08da0c66-3f19-11e7-87ab-d9c1bb47e14d.jpg)
![screenshot_20170522-174910](https://cloud.githubusercontent.com/assets/13453618/26309042/1ffd0ee8-3f19-11e7-9ee1-2c87d7811d1e.png)

**Comment by jamalex** [comment]
Hmm, when I tested on an old Nalanda tablet yesterday (Android 4.0.4) it worked fine, in practice (non-exam) mode. Is it perhaps specific to the exam mode?

When I tried in exam mode just now even on my laptop, I saw some JS errors popping up, in case that's related:
![image](https://cloud.githubusercontent.com/assets/618416/26312857/e5eb5576-3ebd-11e7-9b1e-ce795b7bfc90.png)

**Comment by DXCanas** [comment]
...hm.

That's the error, but I'd never seen it on a laptop.

**Comment by DXCanas** [comment]
Regarding the input/backspace issues. Likely has a lot to do with some stylesheets we're not including. As far as I can tell, we weren't including them because they're written in less and the perseus team decided to include the less compiler globally as well. Looking into options, along with the JS errors in console

**Comment by rtibbles** [comment]
@DXCanas are they not being included via the built perseus.css file though? What other ones are missing?

**Comment by DXCanas** [comment]
These are the lines I'm seeing @rtibbles 
https://github.com/Khan/perseus/blob/master/index.html#L14-L18

**Comment by DXCanas** [comment]
It also looks like the input element that's being used for polynomials has some issues with touch system's on-screen keyboards. The KA site mitigates it by using a keyboard they've included so that a user doesn't use the built in one. Looks like they're using this: https://github.com/Khan/math-input

Looking into workarounds

**Comment by DXCanas** [comment]
Also, these seems to match some of behavior being described. Seems that mathquill is the origin of these issues
https://github.com/mathquill/mathquill/issues/643
https://github.com/mathquill/mathquill/issues/65

@rtibbles Looks like the integrated keyboard is the way to go

**Comment by harishbalachandran** [comment]
@DXCanas @jamalex @rtibbles , Boys sorry to say and I know you guys have been working hard to fix this. But the new keypad seams to appear on a mobile device, but for a tablet that we are going to use there is no change there, still unable to enter valid answer and proceed. 
![whatsapp image 2017-05-24 at 4 23 39 pm](https://cloud.githubusercontent.com/assets/13453618/26401559/2d477048-40a4-11e7-9480-c0ed34f7bde3.jpeg)
![whatsapp image 2017-05-24 at 5 09 22 pm](https://cloud.githubusercontent.com/assets/13453618/26401561/2fa96daa-40a4-11e7-9f70-acde09242703.jpeg)

This is the default keyboard setting on Android 5.1:
![whatsapp image 2017-05-24 at 5 09 48 pm](https://cloud.githubusercontent.com/assets/13453618/26401571/3603530a-40a4-11e7-85a5-a18783ae9b72.jpeg)

**Comment by DXCanas** [comment]
Huh. Tested on some of our tablets in office. Will look in to if chrome ever changes the User Agent.

@harishbalachandran By any chance, do you have "Request Desktop Site" enabled in Chrome's settings?

**Comment by DXCanas** [comment]
@harishbalachandran It's now set to use the keypad on all android devices!

**Comment by harishbalachandran** [comment]
@DXCanas @rtibbles @jamalex Sweet! this is fixed now look to believe 💯 

![whatsapp image 2017-05-25 at 10 36 40 pm 1](https://cloud.githubusercontent.com/assets/13453618/26462063/f6fc0270-419c-11e7-99e3-57231ec1c1fb.jpeg)
![whatsapp image 2017-05-25 at 10 36 40 pm](https://cloud.githubusercontent.com/assets/13453618/26462064/f735d720-419c-11e7-9db9-4015383bcd38.jpeg)
