### ISSUE TITLE
<Enhancement> Need a keypad to input answers on tablet.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1513]
## Summary
The input keypad that pop ups on a tablet completely blocks the screen and the kids are unable to enter the answers. 

## System information
 - Version: Kolibri 0.4.0beta2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Try to enter answers for the exercise.
2. The learners screen is completely blocked to input the answer.

## Screenshots
![whatsapp image 2017-05-16 at 3 35 02 pm](https://cloud.githubusercontent.com/assets/13453618/26102767/295718b8-3a54-11e7-95a8-c43f6456f9b1.jpeg)

![whatsapp image 2017-05-16 at 3 35 02 pm 6](https://cloud.githubusercontent.com/assets/13453618/26102777/30960e0e-3a54-11e7-8072-95d02e73cda1.jpeg)

**Comment by DXCanas** [comment]
Implemented as a fix to another issue: https://github.com/learningequality/kolibri/issues/1512#event-1094651940
