### ISSUE TITLE
both tabs get selected

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1518]
Started a fresh server with no content on `develop`:

![image](https://cloud.githubusercontent.com/assets/2367265/26131753/c723464c-3a50-11e7-9f2a-c37885236793.png)

cc @christianmemije

**Comment by christianmemije** [comment]
Whats the url?

**Comment by indirectlylit** [comment]
it's `/learn` forwarding to `/learn/#/content-unavailable`

(I guess part of the issue might be that forward. Since we first implemented this, I've regretted that decision)

**Comment by christianmemije** [comment]
Notice the links that the tabs are given. Hence both match.

![image](https://cloud.githubusercontent.com/assets/7193975/26178390/a6b1c4f2-3b12-11e7-90a6-fc2a70907ef2.png)

**Comment by christianmemije** [comment]
`missing param for named route "LEARN_CHANNEL": Expected "channel_id" to be defined`

**Comment by jonboiser** [comment]
"Fixed" this bug by getting rid of the tabs on the content-unavailable page.

**Comment by rtibbles** [comment]
Sneaky.
