### ISSUE TITLE
Don't earn points when viewing HTML5 apps

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1525]
## Summary

When viewing a HTML5 app, no matter how long I stick around or interact, I don't get any points

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.x
 - Operating system: Ubuntu
 - Browser: Chrome

## How to reproduce

1. Log in as a learner
1. Go to an HTML5 app page
1. Click around or sit there and stare at it intently
1. Observe that no matter how much you long for them, your points do not appear

## Screenshots

At first:

![image](https://cloud.githubusercontent.com/assets/618416/26139885/72267de8-3a88-11e7-9b26-6edab64efb76.png)

A while later:

![image](https://cloud.githubusercontent.com/assets/618416/26139894/74b1a600-3a88-11e7-98b6-35a385550c29.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Hair loss

**Comment by jonboiser** [comment]
@jamalex What's the expectation when interacting with this content? Is it like if you spend enough time reading it, or hit the bottom of the page, you should get credit for the exercise?

**Comment by jamalex** [comment]
For now, we were going to do the same thing as PDFs (which may also not be
working currently?) and just flag as complete if they spend, I think it was
15s, on the page.
ᐧ
