### ISSUE TITLE
The Learners tab under the coach report is not working.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1526]
## Summary

The Learners tab under the coach report is not working while trying to see the progress made by the learner.

## System information
 - Version: Kolibri 0.4.0beta3
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Login as a coach 
2. Navigate to learners tab.
3. Try see the progress of a learner by clicking on any of the resource.

## Screenshots
![learner tab nav](https://cloud.githubusercontent.com/assets/13453618/26158673/22b7bc6a-3b3a-11e7-92a7-b01f4fe7fe1a.png)

![page not loading](https://cloud.githubusercontent.com/assets/13453618/26158687/2762df92-3b3a-11e7-8a2b-e1512b9cbb92.png)

**Comment by rtibbles** [comment]
Have replicated, will fix.

**Comment by harishbalachandran** [comment]
@rtibbles Thanks seams to work fine now in Beta4.
