### ISSUE TITLE
Learn's Search is broken

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1534]
## Summary

* Search within Learn is currently broken on Develop.
* See [triggerSearch()](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/state/actions.js#L377)

## Exception

`Exception Value: 'list' object has no attribute 'values_list'`

## How to reproduce

1. Search for something within Learn

## Real-life consequences

:rage4:

**Comment by rtibbles** [comment]
Also broken on release-v0.4.x

**Comment by rtibbles** [comment]
Fixed in #1535
