### ISSUE TITLE
Classes broken

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1537]
## Summary

Classes page within Coach is broken on 0.4 & Develop

## Traceback or relevant snippet from server.log or browser console

`'SyncableModelQuerySet' object has no attribute 'filter_by_topic'`

## How to reproduce

1. Create a class as admin. 
2.  Sign in as coach and try to access the class within Coach.

## Real-life consequences

:rage4:

**Comment by rtibbles** [comment]
Replicated - this needs fixing urgently!

**Comment by rtibbles** [comment]
Seems like the log manager change is the issue here, @ralphiee22 - can you look to see how this affected inheritance of managers?

**Comment by christianmemije** [comment]
Fix: Advised by @ralphiee22  to restart the server. Worked. Closing.

**Comment by ralphiee22** [comment]
I think it also had to do with upgrading morango per the requirements, as the hash we used changed between versions.

**Comment by rtibbles** [comment]
I am still getting this issue with the latest version of morango installed.

**Comment by rtibbles** [comment]
I am able to access the `filter_by_topic` method on the `ContentSummaryLog.objects` manager in Django shell - but for some reason it does not find the method when it is loaded through the REST framework serializer.

**Comment by rtibbles** [comment]
Hrm, scratch that, it seems to lazily evaluate these methods, so it lets me access it and say it is a bound method, but once I invoke it, it does not find it.

**Comment by rtibbles** [comment]
Seems like my venv got into a weird state - works fine with fresh environment.
