### ISSUE TITLE
Hindi (hi-in) UI switch not successful. 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1538]
## Summary

Ran the script ./kolibri-v0.4.0-beta5.pex language setdefault hi-in, but not successful.

But we tried the other ones available es-es and sw-tz, seams to work fine.

## System information
 - Version: Kolibri 0.4.0beta5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Run the script for UI switch 

## Screenshots

![language switch](https://cloud.githubusercontent.com/assets/13453618/26254962/dd7c3b10-3cd5-11e7-91f9-30e79043ac09.png)

**Comment by jamalex** [comment]
Should be fixed in Beta 7: https://github.com/learningequality/kolibri/releases/download/v0.4.0-beta7/kolibri-v0.4.0-beta7.pex

**Comment by harishbalachandran** [comment]
@jamalex Was able to switch the platform to Hindi. Thanks
