### ISSUE TITLE
Auto page alignment while switching from landscape to portrait mode is a bit off.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1539]
## Summary

Auto page alignment while turning from landscape to portrait mode is a bit off.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.0beta5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## Screenshots

![whatsapp image 2017-05-19 at 9 00 02 pm 1](https://cloud.githubusercontent.com/assets/13453618/26255592/b5b7258e-3cd7-11e7-9f8a-0c4f62ea34f1.jpeg)
![whatsapp image 2017-05-19 at 9 00 02 pm](https://cloud.githubusercontent.com/assets/13453618/26255593/b600f8a8-3cd7-11e7-8b2f-3c5570b7aede.jpeg)

**Comment by christianmemije** [comment]
Fixed in #1540

**Comment by harishbalachandran** [comment]
@christianmemije seams to work good now. Thanks!
