### ISSUE TITLE
Getting error message while upgrading from Beta7 to Beta8 using the pex file on few Ubuntu systems 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1552]
## Summary
Getting error message while upgrading from Beta7 to Beta8 using the pex file on few Ubuntu systems.

Note:
This is not for all the systems but for few. 

## System information
 - Version: Kolibri 0.4.0beta8
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Run command "sudo ./kolibri-v0.4.0.-beta8.pex start"

## Screenshots
![platform upgrade](https://cloud.githubusercontent.com/assets/13453618/26401824/4ccc6ca6-40a5-11e7-9bad-17640aea6793.png)
![platformupdate](https://cloud.githubusercontent.com/assets/13453618/26401826/4d90239e-40a5-11e7-8ffb-1afef00e23c3.png)

**Comment by rtibbles** [comment]
@harishbalachandran I assume this is not critical for rollout, because you will be installing fresh, but we will look into it in case it affects any future upgrades.

**Comment by jamalex** [comment]
This was from an edge case where the MAC address changed between two runs of the server. Will be fixed in Morango once commit 8c597d9a84f6ad5d6f4dc72ae9f6a74b2a3a0687 is merged in the next release.
