### ISSUE TITLE
Questions of Khan Academy exercise are not rendering properly onto Kolibri.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1553]
## Summary

Questions of Khan Academy exercise are not rendering properly on Kolibri.

KA Topic name: Negative numbers on the number line

**Important note:**
We haven't been able to check various content types of KA content on Kolibri till date, so hopefully we don't have too many alignment issues. 

## System information
 - Version: Kolibri 0.4.0beta8
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Check the question alignment of the topic mentioned above on Kolibri.

## Screenshots

![whatsapp image 2017-05-24 at 5 09 48 pm 1](https://cloud.githubusercontent.com/assets/13453618/26403493/28d83b3e-40ac-11e7-924a-6a82f062e923.jpeg)
![whatsapp image 2017-05-24 at 5 09 48 pm 2](https://cloud.githubusercontent.com/assets/13453618/26403495/293bd982-40ac-11e7-8a12-442e5e94d757.jpeg)
![whatsapp image 2017-05-24 at 5 09 48 pm 3](https://cloud.githubusercontent.com/assets/13453618/26403498/29799fce-40ac-11e7-8c2a-bb1e7bbc5312.jpeg)
![whatsapp image 2017-05-24 at 5 09 48 pm 4](https://cloud.githubusercontent.com/assets/13453618/26403496/293c05ce-40ac-11e7-8cb8-5bfbd7ac2d6a.jpeg)
![whatsapp image 2017-05-24 at 5 09 48 pm 5](https://cloud.githubusercontent.com/assets/13453618/26403497/293e97da-40ac-11e7-8057-18106e1b0d3b.jpeg)

**Comment by rtibbles** [comment]
@DXCanas looks like we have some more styling issues, maybe?

**Comment by DXCanas** [comment]
@rtibbles Looks like it. There's some funky stuff going on with the solution area, but I'll hack at it a bit longer. You happen to know of a channel I can see this stuff on? Preferably a small one?

**Comment by rtibbles** [comment]
Looks like @harishbalachandran is still using his testing channel: `abb42df1203f4043a7b6e430de257d90`

**Comment by DXCanas** [comment]
@rtibbles I can't seem to import that channel. Is it still live?

**Comment by DXCanas** [comment]
`khan-site.css` doesn't help with the issue. Just seems to break things :no_mouth:. Gonna sniff around the KA implementation to see what we're missing

**Comment by DXCanas** [comment]
@rtibbles 

Update: there's a class name that a ton of the KA style definitions rely on. Adding it and removing our custom styles fixed the problem with this exercise completely. Iteratively adding in styles till it looks good, then testing on different exercises. Potential for lots of red.

**Comment by DXCanas** [comment]
> ... `mobile`, `framework-perseus`, `bibliotron-exercise`, `perseus-mobile`. These are hard-coded in the apps' exercise templates and stylesheets. (See here for an approximate list of the relevant classes.)

(the "here" link is dead, but I found [this file](https://github.com/Khan/khan-mobile-exercises/blob/master/prototype-core/public/mobile-exercise-content-7.css), which seems to be right)

https://sites.google.com/a/khanacademy.org/forge/for-developers/perseus-versioning

**Comment by harishbalachandran** [comment]
@rtibbles @DXCanas This is fixed too. 
But we will keep testing all the other question types of KA exercise and will report separate issues, if found.

**Comment by DXCanas** [comment]
:beers:
