### ISSUE TITLE
kolibri manage <command> <args>

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1556]
## Summary

Something is wrong passing arguments to Django manage commands (see below)

## System information

 - ~Version: 0.4.x~
 - Version: 0.5.x (develop)

## Traceback or relevant snippet from server.log or browser console

As you can see, when I ask for help for the `changepassword` command, the response is as if I just ran `kolibri manage help` w/o the name of the `<subcommand>`

```
$ kolibri manage help changepassword

Type 'kolibri manage help <subcommand>' for help on a specific subcommand.

Available subcommands:

...
```

**Comment by rtibbles** [comment]
This is by design - any args to a django management command have to be separated from the command by `--`. This was implemented to allow unambiguous parsing of Kolibri arguments and django management commands, implemented, I think, by you.

**Comment by benjaoming** [comment]
\*facepalm\* that's not how rigid I remembered it :D

```
➜  kolibri git:(release-v0.4.x) kolibri manage help -- changepassword
usage: kolibri manage changepassword [-h] [--version] [-v {0,1,2,3}]
                                     [--settings SETTINGS]
                                     [--pythonpath PYTHONPATH] [--traceback]
                                     [--no-color] [--database DATABASE]
                                     [username]
```

So I guess the problem is then that it's accepting (throwing away) an unknown argument as it is.

**Comment by benjaoming** [comment]
Fixed, documented and merged
