### ISSUE TITLE
manage createsuperuser allows for creation of same login multiple times

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#1557]
## Summary

Calling manage createsuperuser allows for creation of a login that was previously made (e.g. 'admin').  Existence of multiple accounts doesn't allow user to log in.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: version 0.3
 - Operating system: Linux
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Use cmd line manage create superuser
2. Follow prompts to create a new login and password
3. Run kolibri start
4. Open in browser
5. Log in with freshly created login
6. Pressing on 'Log in" doesn't take you to main page

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

There's no validation step which prevents an admin from creating the same login/password combo.  Will lead to confusion upon trying to log in.

**Comment by rtibbles** [comment]
Fixed in #2287
