### ISSUE TITLE
Be able to compare version of channel on device w/ latest available version

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1569]
As a user, I would like to know whether the version of a channel on my device is up-to-date or behind on its version relative to the latest available on a peer device or the content curation server.

## Scenario

WHEN Channel X is at version 1 on the my device
AND Channel X is at version > 1 on the CC server
THEN the App tells me that Channel X is 'out of date'

WHEN Channel X is at version 1 on the my device
AND Channel X is at version 1 on the CC server
THEN the App tells me that Channel X is 'up to date'

**Comment by rtibbles** [comment]
This should be part of the content sync redesign that is happening for 0.7, so punting this to there for now.

**Comment by indirectlylit** [comment]
top-level issue: #2273

**Comment by lyw07** [comment]
I think the backend implementation regarding this issue has been merged: https://github.com/learningequality/kolibri/pull/2566

**Comment by aronasorman** [comment]
There is now backend logic for getting the latest version on studio, and from there the frontend can do comparisons to determine if we should upgrade our version.
