### ISSUE TITLE
Use cards for exams

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1578]
## Summary

* Use cards for exams
* Mockups need to be created @jtamiace @khangmach 

This should also include adding filters as described here: https://github.com/learningequality/kolibri/issues/2053

**Comment by khangmach** [comment]
@christianmemije exam cards preliminary design here. See design channel discussion for justifications of design choices

![exam cards](https://user-images.githubusercontent.com/25045166/28286037-ad87bdd2-6aeb-11e7-99e4-033794541089.png)

**Comment by indirectlylit** [comment]
Noted in review: if lessons and exams do not have thumbnails, it might be more appropriate to show them in table form than card form.

**Comment by christianmemije** [comment]
Addressed in #3288
