### ISSUE TITLE
Docs on develop

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1588]
## Summary

 - [ ] Solve ~66~ 130 warnings
 - [ ] `/index.rst` is called "Getting Started", so is `/dev/index.rst` - let's call the main page something else
 - [ ] Find all syntax errors in docstrings (made by @benjaoming) - stuff like `:param: name` instead of `:param name:`

Will collect a couple of TODOs here do them all at once..

**Comment by indirectlylit** [comment]
old issue, and docs have changed a lot. Let's file individual issues for items that are still relevant
