### ISSUE TITLE
Use translator-friendlier names on CrowdIn

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#1590]
Right now we name our frontend and backend strings as `LC_FRONTEND_MESSAGES` and `LC_MESSAGES` in CrowdIn, respectively. These names look intimidating, and there's really no reason for translators to know this specific implementation detail.

We should rename these folders to `frontend` and `backend`, respectively. It should be easy to change it here: https://github.com/learningequality/kolibri/blob/develop/crowdin.yaml#L6-L13

By just changing the `translation` key in that file, we can change the way these folders appear on CrowdIn, while allowing us to still be compatible with what Django and our build system expects.

**Comment by indirectlylit** [comment]
cc @rtibbles if this change is as trivial as it sounds, maybe we should do it?

**Comment by rtibbles** [comment]
This seems to be impossible. But simply not preserving the hierarchy might be the easiest way. Let's punt to 0.8.

**Comment by indirectlylit** [comment]
this has been improved by #3176
