### ISSUE TITLE
No form validation on "Create an account"

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1594]
## Summary

Form not yet updated with max character counter

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev78
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Have Facility settings to allow users to create their own account
2. Sign out
3. Click "Create account" from sign up page

## Screenshots

<img width="697" alt="screen shot 2017-06-05 at 6 00 37 pm" src="https://cloud.githubusercontent.com/assets/6668144/26809379/2c3b2644-4a19-11e7-9073-be5966290bec.png">

**Comment by christianmemije** [comment]
Fixed in #1791
