### ISSUE TITLE
upgrade to latest compatible versions of python dependencies

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1597]
## Summary

NB! We might wanna have a service like https://pyup.io/ as mentioned in #526 

In lack thereof, let's just step through dependencies...

1. If a new patch release is available, the dependency should be updated
1. If a new minor release is available and release notes show significant benefits and no deprecations, it should be updated

 - [ ] django-filter==0.13.0
 - [ ] django-js-reverse==0.7.2
 - [ ] six==1.10.0
 - [ ] djangorestframework==3.3.3
 - [ ] django==1.9.7
 - [ ] colorlog==2.6.0
 - [ ] docopt==0.6.2
 - [ ] django-mptt==0.8.5
 - [ ] djangorestframework-csv==1.4.1
 - [ ] tqdm==4.8.3                     # progress bars
 - [ ] requests==2.10.0
 - [ ] https://github.com/cherrypy/cherrypy/archive/v6.2.0.zip#egg=cherrypy
 - [ ] https://github.com/fle-internal/django-q/archive/934d557d77ded18c4a73a702905a6f8fe932f97b.zip#egg=django-q
 - [ ] porter2stemmer==1.0
 - [ ] unicodecsv==0.14.1
 - [ ] metafone==0.5
 - [ ] le-utils==0.0.9rc14
 - [ ] kolibri_exercise_perseus_plugin==0.6.11
 - [ ] jsonfield==2.0.1
 - [ ] https://github.com/learningequality/morango/archive/e964c9e3d8225fddd5fe086ec3fb0cf124fdd52c.zip#egg=morango
 - [ ] requests-toolbelt==0.7.1
 - [ ] clint==0.5.1
 - [ ] tzlocal==1.4

**Comment by benjaoming** [comment]
We have to remove HTTP URLs from the requirements entirely since they aren't allowed for anything by `pip install -r file.txt`

Example:

```
 pip install -e .
Obtaining file:///media/archive/code/kolibri
Requirement already satisfied: django-filter==0.13.0 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Collecting django-js-reverse==0.7.3 (from kolibri==0.5.0b1)
  Using cached django_js_reverse-0.7.3-py2.py3-none-any.whl
Requirement already satisfied: six==1.10.0 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: djangorestframework==3.3.3 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: django==1.9.7 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: colorlog==2.6.0 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: docopt==0.6.2 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: django-mptt==0.8.5 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: djangorestframework-csv==1.4.1 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: tqdm==4.8.3 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: requests==2.10.0 in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Requirement already satisfied: cherrypy in /home/benjamin/.virtualenvs/kolibri/lib/python2.7/site-packages (from kolibri==0.5.0b1)
Collecting barbequeue (from kolibri==0.5.0b1)
  Could not find a version that satisfies the requirement barbequeue (from kolibri==0.5.0b1) (from versions: )
No matching distribution found for barbequeue (from kolibri==0.5.0b1)
```

**Comment by indirectlylit** [comment]
could we be more specific about the outcome here?

Are we auditing for dependencies that have known security issues and upgrading those?

**Comment by benjaoming** [comment]
@indirectlylit 

The outcome? I don't know quite what kind of outcome? If someone felt the need to update a dependency, the outcome is in its release notes. "Our software works fine as far as we know" is great, but if something is fixed in a dependency, there might be a need to update.

Security issues are great to fix, but also just normal bugs.

Maybe we could make the patch release decide.. so we don't have to read some ~23 dependencies' release notes.

1. If a new patch release is available, the dependency should be updated
1. If a new minor release is available and release notes show significant benefits and no deprecations, it should be updated

In all other cases, updates have to follow an individual decision.

**Comment by indirectlylit** [comment]
> I don't know quite what kind of outcome?

Sorry, I meant the outcome for this specific issue. Right now it's it's worded broadly, without a specific result: "check up on latest versions". It makes it hard to determine when the task is done.

Maybe the outcome is one of:

* Check Python dependencies for known security issues, and upgrade any that have them
* Upgrade all dependencies that have patch and minor release updates

For the latter, I'd much prefer to do it early in dev release cycle because there's a chance of regressions even for minor/patch updates. I think we should only upgrade for security reasons in 0.7, and do a broader upgrade in 0.8.

**Comment by indirectlylit** [comment]
I think the process you outlined above for deciding whether to upgrade a dependency is perfect - we should use that

**Comment by benjaoming** [comment]
Sounds good, changed the description! I agree that it's wiser to allocate these changes in early stages of a release cycle.

**Comment by rtibbles** [comment]
A good chunk of this has been done in #2882. Everything that starts with `django` except the patch release bump for `django-js-reverse`.

**Comment by rtibbles** [comment]
Oh, I tell a lie, this upgrade had already happened.

**Comment by benjaoming** [comment]
With our current use of issues and lack of automation for dependency management, I think we should consider to close this issue once #2882 is in, but re-open a new issue to track further needs for dependency upgrades :) To keep the dependency soup simmering :)

**Comment by rtibbles** [comment]
Or maybe we should use pyup and close it 5ever?

**Comment by benjaoming** [comment]
Right, let's give it a shot :) #2883

**Comment by indirectlylit** [comment]
nice job - this has been addressed!
