### ISSUE TITLE
DateTimeTzFields are serialized with incorrect times

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1602]
Example saved this time in a `ChannelMetaDataCache` object (at around 14:00 local time)

`2017-06-06 14:44:12.582879(America/Los_Angeles)`

But it gets serialized as

`2017-06-06T07:44:12.582-07:00`

Expected is

`2017-06-06T14:44:12.582-07:00`

**Comment by rtibbles** [comment]
This is due to the time being saved in the local time, not UTC.
