### ISSUE TITLE
Login ID and Password fields for a learner/user should not be case sensitive.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1605]
## Summary

Login ID and Password fields for a learner/user should not be case sensitive, this is especially for young learners and they struggle a lot to login itself.

Please consider this change for Nalanda branch.

## System information
 - Version: Kolibri 0.4.0beta9
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

**Comment by rtibbles** [comment]
Fixed in #1633

**Comment by harishbalachandran** [comment]
@rtibbles The functionality works smooth and helps a lot.
But the usernames are still case sensitive:
The user name created is _Harish_ and a kid if enters _Hari_ only then he is suggested the full name Harish in dropdown, instead if case-insensitve _hari_ should also show Harish in the dropdown. This would be a great flow where any young learners will have total benefit of login in quickly.

1. In this I have to enter _har_ in small case to enable me to login to _harry_ quickly.
![case1](https://user-images.githubusercontent.com/13453618/27506671-0909d1d6-58db-11e7-9bc0-40d2ef1baf1d.png)
2. In this I have to enter _Har_ to enable me to login to _Harish_ quickly 
![case2](https://user-images.githubusercontent.com/13453618/27506672-09b39df6-58db-11e7-9560-953cf62670ab.png)

**Comment by rtibbles** [comment]
I can make the username search case insensitive, will update and build a new release by the end of Sunday.

**Comment by harishbalachandran** [comment]
@rtibbles Thanks this is so much cooler for our little learners 👍
