### ISSUE TITLE
In `channel-grid` Improve transition when getting file sizes/counts

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1612]
Using the KeenUI spinner widget in the `channel-grid` table, the transition abruptly resizes the table rows once the data is loaded in.

![kapture 2017-06-07 at 14 42 27](https://user-images.githubusercontent.com/10248067/26902820-90a8d55a-4b8f-11e7-8c3b-823e1aa36c1b.gif)

**Comment by christianmemije** [comment]
Fixed in #1826
