### ISSUE TITLE
carousel button review

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1621]
![image](https://user-images.githubusercontent.com/2367265/26952186-2c753216-4c59-11e7-84d8-09ab0019c8da.png)

![image](https://user-images.githubusercontent.com/2367265/26952970-aada864e-4c5c-11e7-9744-556e8c1c0891.png)

Some more granular notes:
* The button has no elevation (drop shadow) even though it's over cards which do have elevation.
* Currently, only the circle itself is active, but I would expect the "hit area" to be much larger
* Keyboard focus states seem to behave oddly
* The button is a variable distance away from the cards depending on browser width - I would expect it to remain a fixed distance (e.g. either overlapping or not)

cc @DXCanas

**Comment by DXCanas** [comment]
Can you describe some of the expected tab behavior? I can take care of this pretty easily.

Also, I'm unsure about what to do with the size / hit size. 

All in all, I think we should sync up on this when you get a chance

**Comment by indirectlylit** [comment]
Hey - sorry, just saw this!

> Can you describe some of the expected tab behavior? I can take care of this pretty easily.

I would expect the keyboard focus state to be more consistent with other buttons. (@khangmach can help)

Currently seeing weird flickering behavior on keyboard focus:

![gifmakerproject8_1](https://user-images.githubusercontent.com/2367265/27192522-87307de4-51b0-11e7-9f52-5f1b41930bae.gif)

> Also, I'm unsure about what to do with the size / hit size.

I would first ask: do you want the button to overlap the cards or not?

* If so, I would make the hit area a bit larger like this:  ![hit](https://user-images.githubusercontent.com/2367265/27192655-04774ad0-51b1-11e7-818c-3eeda741606b.png)
* If not, it doesn't matter as much because there's less chance of clicking the wrong thing. However, even here a larger click area would be helpful for users: 
![image](https://user-images.githubusercontent.com/2367265/27192689-1f5db992-51b1-11e7-9f0b-cea994cfc0c5.png)

**Comment by khangmach** [comment]
https://user-images.githubusercontent.com/25045166/27194633-1f700e42-51b8-11e7-9fe3-2624ed49055c.png

Heres the keyboard onfocus state of one arrow toggle we currently have (the only one i can find in my pex file). I think the color change indicated on the buttons in that screenshot are fine to have as a first pass. Just missing the drop shadow. Agree with Devon regarding the bigger hit area

**Comment by DXCanas** [comment]
Something about keenUI's button implementation doesn't allow me to attach shadows using straight CSS. Punting for later.
