### ISSUE TITLE
tooltips and A11Y for progress and content type indicators?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1622]
![image](https://user-images.githubusercontent.com/2367265/26953110-5e749fbe-4c5d-11e7-8cd4-84460e314f56.png)

The colored icon banners look great, but:
* it's not completely obvious what they mean. Perhaps add a tooltip like "Completed video" or "In progress app"?
* Should probably have some kind of label for screen readers
* there's also still an empty icon div:

![image](https://user-images.githubusercontent.com/2367265/26953178-c2be89e4-4c5d-11e7-80db-91366e60fbc7.png)

**Comment by christianmemije** [comment]
> it's not completely obvious what they mean. Perhaps add a tooltip like "Completed video" or "In progress app"?

The content icon banners are meant to only symbolize content type, not progress.

**Comment by christianmemije** [comment]
But I agree our, icons need to be A11Y-ified

**Comment by indirectlylit** [comment]
> The content icon banners are meant to only symbolize content type, not progress.

I assumed the progress was encoded in banner color

**Comment by christianmemije** [comment]
The colors are just to associate content types.

**Comment by indirectlylit** [comment]
hm that's potentially confusing:

 * the icon already shows type - I'd expect color to be used to show new information or not at all
 * do we choose a random color for every type? What happens when we add new types?

**Comment by christianmemije** [comment]
I think it helps quickly scan a page for different content types. 

## Without color
![127 0 0 1-8000-learn- 10](https://user-images.githubusercontent.com/7193975/27237430-ebba08ac-527d-11e7-9d19-15350dbefff8.png)

## With Color
![127 0 0 1-8000-learn- 8](https://user-images.githubusercontent.com/7193975/27237429-ebb7132c-527d-11e7-9efe-50af5478ab29.png)


https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/styles/core-theme.styl#L27

>  What happens when we add new types?
@jtamiace @khangmach

**Comment by khangmach** [comment]
@christianmemije new types require the addition of new colors

**Comment by indirectlylit** [comment]
> new types require the addition of new colors

We need to be more specific because we can't keep choosing arbitrary colors as new content types are added. If we want to associate a unique color with each content type we need a way to define all the possible colors.

For example, there are [categorical color scales](https://github.com/d3/d3-scale-chromatic) which do this.

**Comment by indirectlylit** [comment]
The conversation got a bit off-track - migrating simpler version to https://github.com/learningequality/kolibri/issues/1979
