### ISSUE TITLE
hover state on cards is slightly jarring

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1623]
The cards currently transition from a small drop-shadow to a large one on hover:

![image](https://user-images.githubusercontent.com/2367265/26953519-a481ca34-4c5f-11e7-9d19-208abdd88e36.png) ![image](https://user-images.githubusercontent.com/2367265/26953508-984260c6-4c5f-11e7-9c45-f35e0e87aba3.png)

The instantaneous transition is a bit jarring, because drop-shadows imply a physical elevation and it's impossible for something to instantaneously move from one elevation to another. Recommend applying an eased transition.

**Comment by jonboiser** [comment]
When I was playing with these new topic cards, it brought to mind the effect on the Stripe Increment journal, which gives the cards a levitating effect.

https://increment.com/on-call/

**Comment by christianmemije** [comment]
Definitely needs a transition.
