### ISSUE TITLE
inconsistent spacing on learn page sections

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1624]
"All items" is a bit too cozy with "Resume"

![image](https://user-images.githubusercontent.com/2367265/26954376-6bcdea9c-4c64-11e7-8013-e3542e0984f9.png)

**Comment by DXCanas** [comment]
this is because the controls take up a little space in a div below. Will take care of it

**Comment by DXCanas** [comment]
NVM. Looks like this issue was solved in https://github.com/learningequality/kolibri/commit/5b805f5fe43d6ea9e43af84acfcd483bb753b4a3, since the hitboxes are always there and create a consistent margin
