### ISSUE TITLE
underline gets thicker by expanding up instead of down

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1626]
Keyboard focus on text boxes causes the underline the expand going up, which shifts the textbox itself up by a pixel.

Not exactly a critical issue - but would be nicer if the input box stayed fixed.

![image](https://user-images.githubusercontent.com/2367265/26954986-73398756-4c68-11e7-9948-9a96666bc4ef.png)

**Comment by christianmemije** [comment]
Fixed in #2337
