### ISSUE TITLE
Error while adding groups under coach tab.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1641]
## Summary
Getting error screen while adding new groups in the coach tab. 

Note: This is specifically faced on server wherein we updated the version from Beta9 to Beta10.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Update the server form beta9 to beta10
2. Try to add groups under coach tab.

## Screenshots
![screen shot 2017-06-12 at 1 45 13 pm](https://user-images.githubusercontent.com/13453618/27079844-f0a5634e-5056-11e7-9689-27d762384173.png)

**Comment by rtibbles** [comment]
There are breaking database changes in beta10, which was the reason we were so keen on having you use the beta10 for the Rajasthan training in case of any need for data persistence. An upgrade from beta9 to beta10 is not expected to work properly.

**Comment by harishbalachandran** [comment]
@rtibbles An observation, when we deleted the .kolibri of beta9 and installed beta10 afresh we faced the same problem. But we had to delete all the flies from the .pex directory and re-install beta10 then it was working fine. Is there a specific reason for this?

**Comment by rtibbles** [comment]
I think that the .pex directory stores some cached versions of Python files from inside the pex file itself, so if that is not cleared then you may get inconsistent behaviour, but I am not completely sure!

**Comment by rtibbles** [comment]
@aronasorman any clues?
