### ISSUE TITLE
Groups created does not get updated on real time on Learner group section and under exams section.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1642]
## Summary

Groups created does not get updated on real time on Learner group section and under exams section.

Instead we have to refresh the page to see the changes.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Add groups move learners.
2. Navigate to Learners tab and check the groups column, the changes will not be seen.
3. Navigate to Exam tab and try to allocate to the group, the drop down will not have the group you crated.
4. But on refreshing the page once we are able to see these changes on both Learners tab and Exam allocation.

## Screenshots
Adding Group
![group1](https://user-images.githubusercontent.com/13453618/27081818-cbb83422-505f-11e7-84db-3bf28f33963c.png)
Move learners
![group2](https://user-images.githubusercontent.com/13453618/27081828-da32b18a-505f-11e7-8d05-ff4810b24729.png)
Moved learners
![group3](https://user-images.githubusercontent.com/13453618/27081834-e2f554bc-505f-11e7-9673-a1495ff4d224.png)
Navigate to the learners tab and check the groups section, Its is not updated.
![group4](https://user-images.githubusercontent.com/13453618/27081866-0579c4d2-5060-11e7-8001-a00b9f883b65.png)
Navigate to exam and try to allocate the exam that was created earlier, no groups on drop down:
![group5](https://user-images.githubusercontent.com/13453618/27081881-1fd6a200-5060-11e7-87c0-71d777deb195.png)
Refresh page:
![group6](https://user-images.githubusercontent.com/13453618/27081889-2cb4fe5e-5060-11e7-93f2-1f011fe532c7.png)
The changes are reflected:
![group7](https://user-images.githubusercontent.com/13453618/27081905-361a7424-5060-11e7-8d9f-5c133d629b12.png)
![group8](https://user-images.githubusercontent.com/13453618/27081906-369de49e-5060-11e7-9e30-b49a3e6e9bb6.png)

**Comment by rtibbles** [comment]
Fixed in #1648

**Comment by swapnil106111** [comment]
@rtibbles  Tested on Kolibri 0.4.0beta11.Now, it is working fine. 

![screen shot 2017-06-22 at 2 55 10 pm](https://user-images.githubusercontent.com/12776071/27427824-eb086810-575d-11e7-8b41-2934c8bae325.png)

![screen shot 2017-06-22 at 2 55 40 pm](https://user-images.githubusercontent.com/12776071/27427840-f72f5612-575d-11e7-9411-1ac90e628a66.png)

![screen shot 2017-06-22 at 2 55 59 pm](https://user-images.githubusercontent.com/12776071/27427842-f776ee28-575d-11e7-8479-18bb8585e587.png)

group name is updated without refreshing the page:
![screen shot 2017-06-22 at 2 56 26 pm](https://user-images.githubusercontent.com/12776071/27427841-f72fee06-575d-11e7-9670-3326e9822eb4.png)

![screen shot 2017-06-22 at 2 58 33 pm](https://user-
images.githubusercontent.com/12776071/27427839-f72eb022-575d-11e7-9e09-925e883f33d7.png)
