### ISSUE TITLE
Facility admin is able to delete his/her own user ID while logged in using the same ID.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1643]
## Summary
Facility admin is able to delete his/her own user ID while logged in using the same ID

## How to reproduce
1. Add a Facility admin.
2. Login with the same facility admin.
3. Click on edit and delete the ID.
4. It gets deleted.

**Comment by rtibbles** [comment]
Title does not match issue description?

**Comment by harishbalachandran** [comment]
Oops ya editing the description :0

**Comment by swapnil106111** [comment]
@rtibbles I have tested this issue in Kolibri 0.4.0beta11. Facility admin is not able to delete itself. Fixed.
![1643](https://user-images.githubusercontent.com/12776071/27422630-8aef36f4-574c-11e7-8013-9ed3e3841b6a.png)
