### ISSUE TITLE
UI Style Inconsistency - Indeterminate checkbox is not using Material Design

### ISSUE THREAD

**Issue by chaowentan** [learningequality/kolibri#1645]
## Summary

The KeenUI checkbox doesn't support indeterminate checkbox, so the native HTML indeterminate checkbox has been used (e.g. the "create exam" page), and it's not Material Design.

## Screenshots

![image](https://user-images.githubusercontent.com/1924154/27095859-0608dc80-5024-11e7-9c3b-182b51561635.png)

**Comment by indirectlylit** [comment]
resolved!
