### ISSUE TITLE
UI Style Inconsistency - Restyle the core-modal to make it conform to the design spec

### ISSUE THREAD

**Issue by chaowentan** [learningequality/kolibri#1652]
The core modal should look like this:

https://drive.google.com/file/d/0B3sjMmpdLvk4Tzk4ZnJpUV9nSkE/view

**Comment by jonboiser** [comment]
@chaowentan The current `core-modal` also provides a '<-' back arrow button when `back` prop is provided. This is to support multi-step workflows inside a modal.

Does the new spec have any recommendations for placing this back control? I don't think I see any in the screenshots.

**Comment by chaowentan** [comment]
@jonboiser We would have to ask the design team for recommendation on that.

**Comment by indirectlylit** [comment]
#3311
