### ISSUE TITLE
In Chrome, different video time controls restart video

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1655]
Example: math video
http://localhost:8000/learn/#/fb51dae6df7545af8455aa3a0c32048d/topics/c/47c32ca2832441a7ba668828ff1f49e1

As a side effect of this, the Mastery modal appears prematurely when I actually sit and watch the video all the way through.

![video keeps resetting](https://user-images.githubusercontent.com/10248067/27110541-e934e12c-505e-11e7-8da4-18b5b0a201c4.gif)

## Events

1. Try to jump to a certain point
2. Click the +15
3. Click the -15 (which is probably correct behavior, but probably same result if more than 15 sec out).

**Comment by rtibbles** [comment]
@christianmemije can you investigate this? It may be extant on 0.4.x also, in which case it would be good to fix there.

**Comment by harishbalachandran** [comment]
@rtibbles @jonboiser This is a behaviour that people using 0.4.x also observed few times.

**Comment by christianmemije** [comment]
Looks like the typical issue of the server not handling byte range requests.

**Comment by christianmemije** [comment]
See https://github.com/videojs/video.js/blob/master/docs/guides/troubleshooting.md#problems-with-playback

**Comment by christianmemije** [comment]
See https://github.com/videojs/video.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20byte%20range%20

**Comment by christianmemije** [comment]
@harishbalachandran This issue appears when a server is not properly configured to accept byte-range requests. The NGINX config must have the following server setting:
`proxy_http_version 1.1;`

**Comment by rtibbles** [comment]
Closing this as resolved externally to Kolibri.
