### ISSUE TITLE
The keypad on screen does not work for a specific type of question in MG Content.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1657]
## Summary

The keypad on screen does not work for a specific type of question in MG Content.

The '-' negative sign, '.'  decimal point, Back space 'x' buttons are not functional.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Import he channel.
2. Access the topic Garde 6 --> Integers --> Natural number, Whole.... --> Challenge set on a tablet.

## Screenshots
![whatsapp image 2017-06-14 at 7 42 55 pm 1](https://user-images.githubusercontent.com/13453618/27138039-34e8cc30-513d-11e7-9913-7a309f031303.jpeg)

![whatsapp image 2017-06-14 at 7 42 55 pm](https://user-images.githubusercontent.com/13453618/27138061-4160aa96-513d-11e7-8a2b-d3bfb436a282.jpeg)

Channel ID 6996f85e5a1f508e8757cf9a4ce1085a
![screen shot 2017-06-14 at 7 58 26 pm](https://user-images.githubusercontent.com/13453618/27138004-180eddfc-513d-11e7-8d7a-0323961efad5.png)

**Comment by rtibbles** [comment]
The root of this issue should be being fixed in https://github.com/fle-internal/content-curation/pull/339

**Comment by harishbalachandran** [comment]
@rtibbles haven't faced it yet will reopen if encountered.
