### ISSUE TITLE
Dashboard response time is too much when the learners are engaging with the content.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1658]
## Summary

Dashboard response time is too much when the learners are engaging with the content.

Takes more than 10 seconds to load the page while refreshing and while moving from recent to topics to learners tabs.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. The 15 learners engage with the content 
2. Observe the dashboard by refreshing and move from Recent to topics and to learners 

## Screenshots
![whatsapp image 2017-06-14 at 7 42 54 pm 1](https://user-images.githubusercontent.com/13453618/27139988-0fe42be6-5142-11e7-9a90-a045661c97ff.jpeg)
![whatsapp image 2017-06-14 at 7 42 54 pm 2](https://user-images.githubusercontent.com/13453618/27139989-101d443a-5142-11e7-8507-9ad1eb39cd74.jpeg)
![whatsapp image 2017-06-14 at 7 42 54 pm](https://user-images.githubusercontent.com/13453618/27139998-151758cc-5142-11e7-9827-9697f8eb8b46.jpeg)

**Comment by rtibbles** [comment]
Looks like we could do with some query optimization on the coach reports too.

**Comment by rtibbles** [comment]
Half reduced the response time by more than half so far. Will continue to work on this.
