### ISSUE TITLE
content import is very slow

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1662]
## Summary

Testing out content import using the new iceqube system currently in PR #1610.

I tried importing the portion control channel `fb51dae6df7545af8455aa3a0c32048d`. It was already imported, so the system only needed to download the database - not the content.

The process took about 5 minutes and eventually succeeded. During that time, there was very little network, CPU, or disk activity:

![image](https://user-images.githubusercontent.com/2367265/27162106-25f853b6-5134-11e7-8f25-46e680d5f80d.png)

![image](https://user-images.githubusercontent.com/2367265/27162097-1921fdd6-5134-11e7-9462-e14845ee7aba.png)

![image](https://user-images.githubusercontent.com/2367265/27162103-216caaf4-5134-11e7-9ac3-a64e484dff0d.png)

## System Info:

* `icecold` branch merged into current `develop`
* OSX

**Comment by aronasorman** [comment]
My hunch is that this is a limitation of the current thread-based system, which maximizes compatibility across all platforms (Android and Windows in particular), in exchange for being slow, due to Python's GIL.

It shouldn't be too hard to switch to a process-based system (it's one flag during client initialization), but that's currently untested and will not work for Android at least.

**Comment by indirectlylit** [comment]
> My hunch is that this is a limitation of the current thread-based system, which maximizes compatibility across all platforms (Android and Windows in particular), in exchange for being slow, due to Python's GIL.

If that were true, I'd expect to see my CPU pegged to 50% (I have a two-core processor). However that's not the case - the CPU is mostly idle.

**Comment by rtibbles** [comment]
I believe this was a display issue, not an import issue, please confirm the fix @indirectlylit.

**Comment by indirectlylit** [comment]
confirmed as fixed.

I believe @aronasorman mentioned there was an artificial delay introduced between actions or something like that?
