### ISSUE TITLE
channel management phrasing: "# Contents"

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1663]
![image](https://user-images.githubusercontent.com/2367265/27162427-02b76098-5136-11e7-9197-ff709e049f23.png)

"Content" is an uncountable word (you wouldn't say "3 contents"), and "Contents" has a different meaning than intended here.

https://english.stackexchange.com/a/13598
http://dictionary.cambridge.org/grammar/british-grammar/content-or-contents

**Comment by jonboiser** [comment]
That's the header used in the mockup. It may be more understandable and accurate to simply use "files", as that's what's actually being counted.

**Comment by indirectlylit** [comment]
cc @jtamiace 

Is it a raw file count, or more like the number of "content items"/"resources" in the topic tree?

**Comment by jtamiace** [comment]
Hesitant to say raw files because several files may comprise one content item (subtitles, different resolutions for one video for example)

It represents content items/resources. Might provide more clarity to say "content items?"

**Comment by indirectlylit** [comment]
I think we had started to consolidate definitions of user-facing terms across the system (docs, CC server, kolibri)

e.g. channels, topics, exercises, resources, content items

Perhaps this glossary can be documented somewhere.

**Comment by radinamatic** [comment]
Is there a draft doc with those consolidated definitions...?
@indirectlylit @christianmemije @jtamiace

**Comment by jtamiace** [comment]
Not a doc of definitions, but I made a slide deck that has all the terms being use to refer to content items...?

https://docs.google.com/presentation/d/1YFu6tSgxk_uq7V-yDeLCEvauoMT0MOlEtmJYe4iWMtM/edit

**Comment by radinamatic** [comment]
Thanks, @jtamiace, I'll dig into that!

**Comment by jtamiace** [comment]
After some brief discussions, got approval from Shivi and @khangmach to suggest universally using "Resource(s)" when referring to one or more...... resource.

Seems to be a commonly used and understood term in the OER space.

**Comment by jonboiser** [comment]
We could change the header from "# Contents" to "# Resources", but is that accurate, given that the number below that column is literally the number of files (html, movs, pdfs, etc.) in the channel?

Or does a resource comprise multiple files? So we would need to figure out, say, that this channel with 100 files actually only has 33 resources.

**Comment by indirectlylit** [comment]
I think it's fine to define a "resource" as the leaf nodes of a topic tree, and to say that a resource can have multiple files. In fact, I'd argue that the number of files is an unimportant implementation detail from a user's perspective and should generally be hidden.

One other consideration:

![image](https://user-images.githubusercontent.com/2367265/30353700-87bb0a96-97dc-11e7-8ed4-2ff56297aa2e.png)

We could change those columns to be:

* Avg. progress - Exercises
* Avg. progress - Other resources

**Comment by indirectlylit** [comment]
Also for channel management:

![image](https://user-images.githubusercontent.com/2367265/30353951-4a1ae9de-97de-11e7-83f9-8701eb48112c.png)

Recommend calling the column simply "Resources", not "# Resources".

The [number sign](https://en.wikipedia.org/wiki/Number_sign) is not universally a stand-in for the word "number" - and even when it is, it refers to [ordinal numbers](https://en.wikipedia.org/wiki/Ordinal_number_(linguistics)), not [cardinal numbers](https://en.wikipedia.org/wiki/Cardinal_number_(linguistics)).

**Comment by jtamiace** [comment]
+1 on user's caring less about the actual number of files that comprises a resource, and also just "Resources"

Don't know yet how we can best label those two columns though... those suggestions work but I'd like to see if there are ways to make the framing more concise.

Are tooltips or "info icons" out of the question? To help us use shorter terms for the column label and rely on the popup for more info?

**Comment by jtamiace** [comment]
Never mind, info icons go against the rule to use icons as buttons

**Comment by indirectlylit** [comment]
> Are tooltips or "info icons" out of the question? To help us use shorter terms for the column label and rely on the popup for more info?

> Never mind, info icons go against the rule to use icons as buttons

Certainly seems like a reasonable component to introduce into the style guide and across the application - a `( ? )` icon with a tooltip. Maybe use the long columns for now, and introduce that inline help / "more info" component holistically in the future?

**Comment by jtamiace** [comment]
Ok. I want to document this as a TODO in the style guide tracker, but unsure whether it fits in with an existing component or whether "tooltips"/"(?) icon" should be made it's own thing or fits into another broader component.  

https://docs.google.com/spreadsheets/d/1W9vV6IufYLlFJ3iir0uQnztqFRWy0QalMcBa35zK2dc/edit#gid=0

Although material makes tooltips its own thing 
https://material.io/guidelines/components/tooltips.html

**Comment by rtibbles** [comment]
Fixed in #2194
