### ISSUE TITLE
inconsistent user login password validation

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1666]
During login, there are two different validation strategies depending on whether learners need a password or not.

With a password, we use the built-in browser feature, and the message doesn't pop up until after hitting "sign in":

![image](https://user-images.githubusercontent.com/2367265/27187216-773e5246-519f-11e7-99f9-812226cf1b5b.png)

Logging in as an admin when learners do not need passwords, the password field shows red validation text as soon as the password field appears:

![image](https://user-images.githubusercontent.com/2367265/27187309-b542ec8c-519f-11e7-8c8a-c7caf9ce740a.png)

**Comment by christianmemije** [comment]
Fixed in #2005! :fireworks:
