### ISSUE TITLE
Inconsistency with name on "Manage" tab

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1669]
## Summary

The "Manage" tab says "Manage" and the header at the top of the window says "Management." This inconsistency may or may not be intentional, but after speaking with the team, we think they should both be "Manage" for consistency across the platform.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244
 - Operating system: Android 6.0.1 (on Samsung S5)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App
2. Be directed automatically to the "Manage" tab after logging in
3. View the inconsistency

## Screenshots

Unable to see both at the same time to take a screenshot, but I observed the same on the non-app version of Kolibri on the demo site. 
![manage](https://user-images.githubusercontent.com/25990164/27204493-81dcad38-51f9-11e7-8ecc-b4fa510a47a4.JPG)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Super super minor....

**Comment by christianmemije** [comment]
@rtibbles Should the url remain as `/management`?

**Comment by rtibbles** [comment]
Yes, we can leave the url for now.

**Comment by christianmemije** [comment]
What should the target branch be?

**Comment by rtibbles** [comment]
Can target 0.5.x.

**Comment by christianmemije** [comment]
Fixed in #1788
