### ISSUE TITLE
Progress bar to import content never finished loading when import was complete

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1674]
## Summary

I imported a large channel into Kolibri from the Internet on the Android App. I left the phone alone for a while (almost an hour, checking it periodically) and t didn't look like the import progressed much. Then I received an error message saying to "please try again." I closed the message but noticed that the channel was imported (looking below and checking in Learn). 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 6.0.1 (on Samsung S5)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App
2. Import Channel ID (I was using 93a5bfcfa2a74962be843288aefcfc0e)
3. Wait a while for it to finish loading. See if you ultimately get the error screen.
4. Close out of the app and re-enter the app. See if the content was successfully loaded.

## Screenshots

![screenshot_2017-06-15-19-46-36](https://user-images.githubusercontent.com/25990164/27206774-8d1c3a52-5207-11e7-8e25-a3eeb229a207.png)
![screenshot_2017-06-15-19-51-39](https://user-images.githubusercontent.com/25990164/27206772-874729e8-5207-11e7-94f8-0fc7997deed2.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

It's useful to know when the content has finished being imported. I could see many partners being troubled by this.

**Comment by laurenlichtman** [comment]
When I imported a smaller channel (ID: 8e06f21efdf23ffab4b026f674a8c442) on a Pixel (Android 7.1.2), the import bar was still in progress when the channel had already been published, but in this instance, ultimately the screen saying the channel was imported did appear (unable to screenshot).

**Comment by rtibbles** [comment]
This should have been fixed.
