### ISSUE TITLE
Unable to see all of the video options on Android App on Android 6.0.1 device

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1675]
## Summary

I'm unable to see all of the video options on the bar at the bottom of the viewer on Android 6.0.1 device (I can on Android 7.1.2.).

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 6.0.1 (on Samsung S5)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App, import channel ID 93a5bfcfa2a74962be843288aefcfc0e from the Internet.
2. Click on video content and view. 

## Screenshots

Android 6.0.1
![screenshot_2017-06-15-20-48-49](https://user-images.githubusercontent.com/25990164/27207529-6e08f122-520d-11e7-9f9c-24c4f7724a9d.png)

Android 7.1.2 (for comparison)
![screenshot_20170615-205610](https://user-images.githubusercontent.com/25990164/27207545-852ec962-520d-11e7-847a-8ba15f8adbf2.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

It's critical to be able to see the full-screen button. and for the viewer to render properly to be able to see subtitles.

**Comment by jonboiser** [comment]
@laurenlichtman This looks like the controls might be getting cut off because of the different screen size, just based on the comparative scales of the rest of the app. Is the Android 6 device less wide than the Android 7 one?

**Comment by laurenlichtman** [comment]
@jonboiser Sorry for not putting the devices above. They're essentially the same size. The Android 7 was on a Pixel (5.0 inches (~69.0% screen-to-body ratio)) and the Android 6 was on a Samsung Galaxy S7 (5.1 inches).

**Comment by christianmemije** [comment]
Should have been fixed in #1708 :champagne:
