### ISSUE TITLE
Warn users when they attempt to re-import an already-installed channel

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1676]
As a user, I would like to be informed that a channel that I intend to importing from a remote or local source is already installed on my device before starting any data transfer.

### Remote source
Given that channel 'foo' with channel id `f00` is installed on my device
When I go through the 'import remote channel' workflow and attempt to download `f00`
Then I am notified that the channel is already there
Then I can continue with the download or choose to cancel.

### Local source
Given that channel 'foo' with channel id `f00` is installed on my device
Given that channel 'foo' (and potentially other channels) is installed on my USB drive
When I go through the 'import local channel(s)' workflow and attempt to import the USB drive contents
Then I am notified that 'foo' channel is already there
Then I can continue with the download or choose to cancel.

## Summary

I tried to import a channel with the same ID as a channel already loaded and did not receive an error or warning message. I'm not sure if the channel ever re-imported. I assume that the new content from the ID will replace the old content but: 
(1) You should receive a warning message confirming that this is what you want to do (especially in a context where it is a large file and the internet connection isn't strong); or
(2) You should be prompted to delete the old ID first (which may not be necessary if it will just replace it anyway; in case there's a problem importing the new content, at least the old will be there?)

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 6.0.1 (on Samsung S5)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App, log in, and go to Manage tab.
2. Import Channel ID (I was using 93a5bfcfa2a74962be843288aefcfc0e)
3. Once content has been loaded, try reimporting the same channel ID and observe.

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

I could see this being problematic if you are in a low-bandwidth context and the filesize is large and this is accidental. It would be helpful for Kolibri to acknowledge that you're trying to do this. In my opinion from a user experience perspective, this wouldn't interrupt my experience, but rather reassure me that it's the correct path forward.

**Comment by jonboiser** [comment]
@laurenlichtman In my experience, if you already have, say KA English, and you attempt to download it again, it will not re-download all of the files. But I think it would be an improvement to point out that the channel is already on the device. If the intention is to update a channel, I've written up a user story #1569 to notify a user when a channel is updatable; the user could then initiate an update through a simpler process like clicking an "update" button.

@jamalex Could you explain in this thread for my benefit what does happen when one attempts to re-download a channel? Does the ContentMetadata database get overwritten? If the DB has jumped a version, will kolibri download the new stuff?

**Comment by laurenlichtman** [comment]
@jonboiser I didn't check to see if it redownloaded all of the files in part because #1673 would occur. My intention is around knowing whether it's on the device and confirming that you want to reimport (in case overriding it was accidental).

**Comment by jonboiser** [comment]
Ok, this sounds like a desirable enhancement for users. I will add a basic user story to the original issue and edit the title a bit. Maybe we'll target it for 0.6 release.
