### ISSUE TITLE
Full screen video button isn't working on Android App

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1677]
## Summary

The full-screen video button isn't working. I'm also unable to rotate but that may be a separate issue (see #1678).

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 7.1.2 (Pixel)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App, import channel ID 93a5bfcfa2a74962be843288aefcfc0e from the Internet.
2. Click on video content and try clicking on the full-screen button. 

## Screenshots

https://drive.google.com/open?id=0B9HRyCgn-ZQZbXBXS3NEOFQtaWM 
https://drive.google.com/open?id=0B9HRyCgn-ZQZeFBDM2NlNF8xa3M
(let me know if you're unable to see this video and I can reshare)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

It's critical to be able to view videos in full-screen mode, especially on smaller screen devices.

**Comment by DXCanas** [comment]
Potentially resolved (at least temporarily) by https://github.com/learningequality/kolibri/pull/1823

**Comment by rtibbles** [comment]
Marking this as closed.
