### ISSUE TITLE
Screen rotation isn't working periodically in Android App

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1678]
## Summary

Screen rotation isn't working periodically, especially in Learn.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 7.1.2 (Pixel)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App, import channel ID 93a5bfcfa2a74962be843288aefcfc0e from the Internet.
2. View content in Learn and try to rotate. I found this to be the case with videos and exercises (wasn't able to test other types of content).

## Screenshots

See video from here: https://github.com/learningequality/kolibri/issues/1677

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

This was problematic, especially on an older version of Android where the screen dimensions made it so that I couldn't see many of the buttons on the screen.

**Comment by christianmemije** [comment]
No longer exists.
