### ISSUE TITLE
Error message popped up when going back to main learn page on Android App

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1679]
## Summary

Honestly, I'm not entirely sure how this happened but I believe I was pressing on an arrow to from a piece of content back to the main Learn page (what the imps team has referred to as the "Netflix" view).

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 7.1.2 (Pixel)
 - Browser: n/a (Android App)

## Screenshots
![random error](https://user-images.githubusercontent.com/25990164/27208168-17abe384-5212-11e7-9137-f13a5d5aecb8.png)

**Comment by indirectlylit** [comment]
Without steps to reproduce, we might want to remove the 0.5 target and wait for more information?

**Comment by indirectlylit** [comment]
closing - no way to repro
