### ISSUE TITLE
UI Style Inconsistency - Implement a generic and standardized breadcrumb component

### ISSUE THREAD

**Issue by chaowentan** [learningequality/kolibri#1682]
So far, there's only a learner-specific breadcrumb in Kolibri. But it should be generalized and implement the style described in the spec: 

https://docs.google.com/document/d/1ul2xQLcOEtC2Hy_Div4-qnED5zyqqNDrWG-oPuMBAcg/edit

**Comment by christianmemije** [comment]
IN PR: https://github.com/learningequality/kolibri/pull/1632

**Comment by christianmemije** [comment]
Implemented in #1632 :100:
