### ISSUE TITLE
Style Guide - Styles are leaking from vuep

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1685]
For example, in simple modal section (screenshot is WIP of adjusting core-modal), the font family is defaulting to Helvetica Sans, which it is picking up from `.vuep` class.

<img width="605" alt="screen shot 2017-06-19 at 2 30 32 pm" src="https://user-images.githubusercontent.com/10248067/27306838-1796ee60-54fc-11e7-8a18-ea54651b4300.png">

**Comment by indirectlylit** [comment]
thanks - cc @chaowentan in case you have thoughts

**Comment by chaowentan** [comment]
Ah, good catch! Yeah, it's leaking from the Vuep stylesheet (see below). And it seems font style is the only one conflicting with the Kolibri style, so we can try to override that (or more accurately speaking, restore its style) in the Style Guide stylesheet.

Is the new typography style being defined yet?

https://github.com/QingWei-Li/vuep/blob/master/dist/vuep.css

**Comment by jtamiace** [comment]
Typography is done on the design side, ready for dev review https://docs.google.com/document/d/1YWRImTl7ocWpCxcePHyf_3Fo07zWneb8_NUnTI_9xoc/edit#
