### ISSUE TITLE
Style guide - API table camelCase props are being converted to snake-case

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1686]
e.g. in simple-modal section

<img width="874" alt="screen shot 2017-06-19 at 2 57 07 pm" src="https://user-images.githubusercontent.com/10248067/27307656-9b45d94e-54ff-11e7-8437-2aa7086178d9.png">

**Comment by jonboiser** [comment]
I think it's actually okay in vue to use the `snake-case` name of a prop even if it's defined in camelCase. But the convention in the code is to use the prop name as originally named.

**Comment by indirectlylit** [comment]
Good catch - we should in general try to match internal code conventions in the style guide

cc @magali-br in case you have thoughts

**Comment by jonboiser** [comment]
It might be enough to delete this line, which seems to "uncamelCase" the prop name.

https://github.com/learningequality/vuedoc-parser/blob/master/lib/parser.js#L231
