### ISSUE TITLE
(Style guide) Create custom styles for indeterminate checkboxes

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1692]
## Summary

<img width="555" alt="screen shot 2017-06-20 at 11 47 30 am" src="https://user-images.githubusercontent.com/6668144/27350103-42a759f2-55ae-11e7-96c2-b1f8b5383057.png">

I believe Keen UI does not provide style guidelines for indeterminate checkboxes, so I would like to propose that we follow material guidelines for them: 

<img width="445" alt="screen shot 2017-06-20 at 11 50 30 am" src="https://user-images.githubusercontent.com/6668144/27350247-af546aa4-55ae-11e7-9679-ed74903608b5.png">

Which would be similar to the material icon for indeterminate checkboxes and be filled with the primary purple.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta10.dev351 /style_guide
 - Operating system: MacOS Sierra
 - Browser: Chrome

**Comment by christianmemije** [comment]
Closed in #1903
