### ISSUE TITLE
(Style guide) Style the text fields to match the guideline

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1693]
## Summary

Text fields in the style guide should not span the full width of the page, but at a max width of 400px as indicated in the guidelines

<img width="1208" alt="screen shot 2017-06-20 at 11 53 18 am" src="https://user-images.githubusercontent.com/6668144/27350635-b7139c1e-55af-11e7-864c-afaae45da522.png">

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta10.dev351 /style_guide
 - Operating system: MacOS Sierra
 - Browser: Chrome

**Comment by christianmemije** [comment]
FIxed in #2098
