### ISSUE TITLE
(Style guide) Do we want to have description fields filled out for props, slots, and event tables?

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1695]
## Summary

<img width="823" alt="screen shot 2017-06-20 at 12 18 07 pm" src="https://user-images.githubusercontent.com/6668144/27351566-ab030b00-55b2-11e7-9e48-9a6724ef87b9.png">

I notice that some are auto-populated (or done manually), and others are not (probably because a lot of them are self-explanatory). These are pretty useful for both devs and designers to indicate what a component is capable of doing, and so this may be useful to fill out, especially for terms that are a little less obvious from the name.

Not picking any specific ones out now, but might be good to have description-writing as a TODO as we continue to fill out pages

**Comment by jtamiace** [comment]
Maybe I should file a separate issue, but this might be a bug

<img width="1039" alt="screen shot 2017-06-20 at 1 34 41 pm" src="https://user-images.githubusercontent.com/6668144/27354710-5223999a-55bd-11e7-9277-c6ac74b109ec.png">

**Comment by christianmemije** [comment]
Descriptions should be mandatory for each item in these tables even if redundant.

**Comment by indirectlylit** [comment]
closing - this is an ongoing activity
