### ISSUE TITLE
Kolibri stop command not working

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1697]
## Summary

* The command `kolibri stop` does not seem to always work.

## System information

 * Develop

```
ERROR    During graceful shutdown, server says: KA Lite server configuration error (9)
ERROR    Not responding, killing with force
INFO     Server stopped
```

## How to reproduce

1. `kolibri start`
2. `kolibri stop`

**Comment by rtibbles** [comment]
Have replicated by deleting the webpack build json from the user plugin.

**Comment by rtibbles** [comment]
This causes it to produce a 500 - unfortunately, the subsequent force stop that it tries to do does not stop the server.

**Comment by rtibbles** [comment]
Oh no, I tell a lie - it does still stop it from running when I do that.

**Comment by rtibbles** [comment]
@benjaoming this appears to be related to an error we are getting in Travis, whereby sometimes we get a bad shutdown, and after that the Kolibri Home dir cannot be deleted. c.f.:
https://travis-ci.org/learningequality/kolibri/jobs/244984849
```
ERROR    During graceful shutdown, server says: KA Lite server configuration error (9)
ERROR    Not responding, killing with force
INFO     Server stopped
```

```
py2.7 runtests: commands[5] | rm -r /home/travis/build/learningequality/kolibri/kolibrihome_test
/bin/rm: cannot remove ‘/home/travis/build/learningequality/kolibri/kolibrihome_test’: Directory not empty
ERROR: InvocationError: '/bin/rm -r /home/travis/build/learningequality/kolibri/kolibrihome_test'
```

**Comment by benjaoming** [comment]
Ah, thanks for the heads up - should find a reliable way of stopping it.

Meanwhile, #1689 has isolated the environments so they don't actually need to be deleted. This mitigates the test failures.

**Comment by benjaoming** [comment]
@rtibbles are you working on this? Otherwise, do feel free to assign me.

**Comment by rtibbles** [comment]
I was not, no, just investigating.

**Comment by benjaoming** [comment]
I still encounter this in newer versions, likely because I switch around between different versions of Kolibri. So calling `stop` in order to stop another instance of kolibri is something I would suspect to typically cause this. Which is not a major issue.

As long as we can guarantee that Kolibri stops... updates to this issue should pertain when **kolibri does not stop when asked to**.

**Comment by radinamatic** [comment]
Not sure if it's relevant, but often when calling `kolibri status` after `kolibri stop`, the response is `Unclean shutdown (7)`.

**Comment by benjaoming** [comment]
@radinamatic - it's especially relevant when the same installation (version) gives this error, that's not the intention. A clean start should give a clean shutdown in all cases.

**Comment by indirectlylit** [comment]
haven't seen this in a while - re-open if it's still an issue
