### ISSUE TITLE
card hover drop-shadow effect is clipped in new carousel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1698]
![image](https://user-images.githubusercontent.com/2367265/27357497-4708033e-55c7-11e7-88e2-bc58d6757289.png)

**Comment by indirectlylit** [comment]
cc @DXCanas looks like this can be fixed by removing the `overflow-x: hidden` prop. Not sure why that also helps in the `y` direction

![image](https://user-images.githubusercontent.com/2367265/27360885-b72eadf0-55d8-11e7-950f-4ce11e803082.png)

**Comment by DXCanas** [comment]
@indirectlylit the `overflow-x:hidden` was there to block the incoming/outgoing cards from being visible outside of the context of the carousel. This was a request from @christianmemije and @khangmach

**Comment by DXCanas** [comment]
Should have been taken care of in #1586
