### ISSUE TITLE
Move installed plugins to options.ini and deprecate kolibri_settings.json

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#17]
Currently, we use JSON, which isn't human friendly. This was under the assumption that ConfigParser (Python 2) and configparser (Python 3) would be terrible to try and unify. However, it turns out there's a backport of Python 3's configparser for Python 2:

https://pypi.python.org/pypi/configparser

@rtibbles you asked about .ini files, thanks for reminding me about this :)

 - [x] New ini-based configuration - introduced in #3607
 - [ ] Option for well-known + auto-enabled plugins
 - [ ] Do not store values directly for appending to `INSTALLED_APPS`, instead rename configuration option to `PLUGINS` and use module names. This avoids problems with application configs and can minimize the work done when checking if a plugin exists #1902

**Comment by indirectlylit** [comment]
Note - this refers to the `~/.kolibri/kolibri_settings.json` file

**Comment by indirectlylit** [comment]
The main issue here was that the settings file is hard for a developer to manually edit.

As an easier alternative to switching formats, I submitted a quick PR to simply format the JSON in a more developer-friendly way. I think this should suffice to close this issue? (Most devs are familiar with editing JSON)

**Comment by benjaoming** [comment]
Can we re-open this?

I actually liked the unreadable JSON because it avoided people messing around in it with manual edits and writing instructions with references to this file :)

It's nice that the JSON file is readable but there's still no semantic verification or documentation. This means that we're half-encouraging deployments to base things off a configuration file that we don't really support, it's an internal file still.

Being backwards compatible on an interface we didn't intend, can have serious negative consequences.

Ideally, the configuration file is a public, human interface, or it's an un-readable mess that discourages any kind of interaction.

**Comment by indirectlylit** [comment]
Until #106 is fixed, manually editing the config file is a fairly common activity

**Comment by benjaoming** [comment]
True that! So you're suggesting to fix #106 - I'm stepping up to that!

**Comment by indirectlylit** [comment]
see also #2019

**Comment by benjaoming** [comment]
#3607

**Comment by rtibbles** [comment]
Shall we close this now, or maybe migrate kolibri_settings.json to an ini file?

**Comment by benjaoming** [comment]
@rtibbles for non-human readable settings it still serves a purpose.. but I guess we don't have any of such? :tada: 

I have changed the title of the issue, reduce, reuse, recycle :green_heart:

**Comment by rtibbles** [comment]
Alas poor kolibri_settings.json, I knew him, Horatio!

**Comment by indirectlylit** [comment]
* this issue seems to be covered in #2019 and #2510
* added note about switching from json to ini in #2019
* also, options.ini now exists

closing to consolidate. let me know if anything wasn't captured

**Comment by radinamatic** [comment]
@indirectlylit 

> also, options.ini now exists

"Exists" as in _is created by default with Kolibri installation_, or as in _you can create one yourself, if needed_? I hope the latter, or I need to amend the documentation.

**Comment by indirectlylit** [comment]
yup - you can create one yourself, if needed :)
