### ISSUE TITLE
keyboard focus tab order on carousel is unexpected

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1700]
![image](https://user-images.githubusercontent.com/2367265/27360528-775f5f82-55d6-11e7-867a-68f24b9f4934.png)

Current:

* previous page
* next page
* card
* card
* card

Expected:

* previous page
* card
* card
* card
* next page

**Comment by DXCanas** [comment]
Had some talks about behavior with @christianmemije too. @radinamatic might be able to contribute some insight here once she's done with her thesis. I'll be doing a comparitive analysis today
