### ISSUE TITLE
Unable to create new accounts

### ISSUE THREAD

**Issue by pkpetit** [learningequality/kolibri#1701]
## Summary

New users are unable to create account on the SIGN UP page. This is because the Terms of Service and Privacy Policy checkbox isn't visible. Therefore cannot be checked.

## System information

 - Version: 0.3.3.dev27
 - Operating system: Windows
 - Browser: Chrome/ IE/Mozilla

## Screenshots

<img width="951" alt="chrome" src="https://user-images.githubusercontent.com/26124514/27379938-c0995180-566c-11e7-86af-3889897e3852.png">
<img width="959" alt="ie" src="https://user-images.githubusercontent.com/26124514/27379939-c09a78bc-566c-11e7-953d-1adb01308592.png">
<img width="959" alt="mozilla" src="https://user-images.githubusercontent.com/26124514/27379937-c09909dc-566c-11e7-857e-4db1dd3379ef.png">

**Comment by jeepurs** [comment]
The version you report (0.3.2) is not the most current version (which is 0.3.3).  I suggest you upgrade to the most current version.

Once you do, you can check your kolibri_settings.json file to make sure that: 
`kolibri.plugins.user` is disabled and
`kolibri_instant_schools_plugin` is enabled

**Comment by pkpetit** [comment]
@jeepurs After enabling the kolibri_instant_schools_plugin, the Terms of Service and Privacy Policy checkbox is visible. This test was carried out on my laptop. Will test on the Server and feedback.
<img width="960" alt="after_plugin_enabled" src="https://user-images.githubusercontent.com/26124514/27401835-2dc20116-56b4-11e7-8ba2-ccca3072a130.png">

**Comment by pkpetit** [comment]
Issue has been resolved. It works perfectly on the server. Thank you @jeepurs
