### ISSUE TITLE
detect and warn of misconfigured server

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1707]
Admins occasionally run into issues where people can't interact with streaming content and spend time trying to debug the cause. This can occur because either the user is running the devserver, or because of misconfigured nginx front-ends.

For example:
* https://github.com/learningequality/kolibri/issues/676
* https://github.com/learningequality/kolibri/issues/1165
* https://github.com/learningequality/kolibri/issues/1655

If possible, it would be great to detect a misconfigured server and show a warning to the user.

**Comment by rtibbles** [comment]
Yeah, we could attempt a byte range request and see if it works, if it doesn't, we can display a warning to the user, and also disable the seeking functionality.

**Comment by indirectlylit** [comment]
this could be a good place to display more technical info resulting from this warning: https://github.com/learningequality/kolibri/issues/1910

**Comment by indirectlylit** [comment]
this has been mostly addressed. Let's open issues for specific things if we need more warnings
