### ISSUE TITLE
popup can be intrusive in certain content types

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1709]
The popup makes sense when we have a definitive signal that the item is "finished" - e.g. for exercises

However for content like documents or interacting with HTML applications, the popup occurs at an arbitrary time and is very intrusive:

![image](https://user-images.githubusercontent.com/2367265/27410027-9319bf60-5699-11e7-9cd9-8001aecd769c.png)

This might also happen for videos and audio if the user has repeated sections rather than playing straight through.

**Comment by khangmach** [comment]
I believe this is a place where moving away from the point snackbar did us a disservice. It would be perfect here instead of a point pop up. Can we assign the usage of either of the two to different content types? 100% agree with the problem here.

**Comment by khangmach** [comment]
Updated mockup with behavior specifics here:

![points popup](https://user-images.githubusercontent.com/25045166/28843274-68844bf8-76b5-11e7-9e9f-1966b2cc3df3.png)

**Comment by rtibbles** [comment]
Fixed in #1964.
