### ISSUE TITLE
Pex on clean Ubuntu 17.04: TypeError: '_NamespacePath' object does not support indexing

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1710]
## Summary

Tried on a fresh Ubuntu 17.04 with Python 3.5, and Python 2.7

 - Works on 2.7
 - Fails on 3.5

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: (latest builds from develop)
 - Operating system: Ubuntu 17.04
 - Browser: N/A

## Traceback or relevant snippet from server.log or browser console

```
python3 kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex
Traceback (most recent call last):
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 310, in execute
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 243, in patch_sys
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 202, in minimum_sys
  File "/home/test/Downloads/kolibri_buildkite_build-1672_1405_kolibri-v0.4.0-beta10-348-g15069d7.pex/.bootstrap/_pex/pex.py", line 139, in minimum_sys_modules
TypeError: '_NamespacePath' object does not support indexing

```

## How to reproduce

1. Dowload a pex
1. `python3 name_of.pex`

**Comment by benjaoming** [comment]
Been trying around with installing extra python3 libraries like `python3-pip` with no luck. Started debugging directly using code snippets from pex and found:

```
>>> for module_name, module in sys.modules.items():
...     if not hasattr(module, '__path__'):
...         continue
...     for k in reversed(range(len(module.__path__))):
...         module.__path__[k]
... 
'/usr/lib/python3.5/xml/dom'
'/usr/lib/python3/dist-packages/apport'
'/usr/lib/python3/dist-packages/apt/progress'
'/usr/lib/python3.5/urllib'
'/usr/lib/python3.5/http'
'/usr/lib/python3.5/xml/parsers'
'/usr/lib/python3/dist-packages/apt'
'/usr/lib/python3.5/json'
'/usr/lib/python3.5/xml'
'/usr/lib/python3.5/collections'
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
TypeError: '_NamespacePath' object does not support indexing
```

Going a bit deeper, we can find:

```
>>> for module_name, module in sys.modules.items():
...     if not hasattr(module, '__path__'):
...         continue
...     print(module.__name__)
...     for k in reversed(range(len(module.__path__))):
...         module.__path__[k]
... 
xml.dom
'/usr/lib/python3.5/xml/dom'
apport
'/usr/lib/python3/dist-packages/apport'
apt.progress
'/usr/lib/python3/dist-packages/apt/progress'
urllib
'/usr/lib/python3.5/urllib'
http
'/usr/lib/python3.5/http'
xml.parsers
'/usr/lib/python3.5/xml/parsers'
apt
'/usr/lib/python3/dist-packages/apt'
json
'/usr/lib/python3.5/json'
xml
'/usr/lib/python3.5/xml'
collections
'/usr/lib/python3.5/collections'
keyrings
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
TypeError: '_NamespacePath' object does not support indexing
```

What seems to be happening is that while pex is introspecting available sys modules, it starts addressing properties of namespaced packages in the wrong way.

```
>>> keyrings.__name__
'keyrings'
>>> keyrings.__path__
_NamespacePath(['/usr/lib/python3/dist-packages/keyrings'])
```

Looking at the `keyrings` package, we find that it indeed doesn't have an `__init__.py` which is allowed

```
ls  -l /usr/lib/python3/dist-packages/keyrings
total 4
drwxr-xr-x 3 root root 4096 Apr 12 05:14 alt
```

The concept of namespaced packages is described here: https://packaging.python.org/guides/packaging-namespace-packages/

I'm opening up an issue on in the Pex repo.

**Comment by benjaoming** [comment]
Issue already open: https://github.com/pantsbuild/pex/issues/331

**Comment by aronasorman** [comment]
I got this error as well, when I upgraded to the latest setuptools.

**Comment by benjaoming** [comment]
Thinking about solving this by:

1) Contributing a fix for the issue in Pex
2) Documenting as a know issue and wait for a new release of Pex.

**Comment by benjaoming** [comment]
https://github.com/pantsbuild/pex/issues/393 is closed saying that Pex 1.2.8 fixes the issue - will have to verify.

**Comment by indirectlylit** [comment]
any updates?

**Comment by benjaoming** [comment]
It's been reported in the upstream issue that they're now "silently ignored", so that sounds promising :) Will re-check...

**Comment by benjaoming** [comment]
Can confirm that this now works, tested on the same 17.04 VM that previously crashed the pex.
