### ISSUE TITLE
To reflect group name change in learner tab,need to refresh the page after deleting group 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1711]
## Summary
In learner tab, it shows learner name with group name. After deleting the group,still showing group name. To reflect the group name changes need to refresh the page.

## System information

Version: Kolibri 0.4.0beta11
Operating system: Ubuntu 14.04 LTS
Browser: Chrome

## How to reproduce

1. Login with Facility admin.
2. Go to Coach.
3. Click on Groups.
4. Add the learners in the group.
5. Click on learner tab.
6. it shows learner name with group name.
7. Go to groups tab.
8. Delete the group.
9. Go to Learner tab.
10. Still shows learner name with deleted group name.

## Screenshots
![screen shot 2017-06-22 at 3 44 12 pm](https://user-images.githubusercontent.com/12776071/27432310-4a8f019a-576d-11e7-9426-cba07d0ec973.png)
![screen shot 2017-06-22 at 3 44 38 pm](https://user-images.githubusercontent.com/12776071/27432311-4a8fd796-576d-11e7-8b39-2242548a756d.png)
![screen shot 2017-06-22 at 3 44 44 pm](https://user-images.githubusercontent.com/12776071/27432308-4a8cdd34-576d-11e7-8092-9d6b6db8b693.png)
![screen shot 2017-06-22 at 3 44 53 pm](https://user-images.githubusercontent.com/12776071/27432309-4a8f028a-576d-11e7-850e-3817723543b0.png)

Still shows group name
![screen shot 2017-06-22 at 3 44 58 pm](https://user-images.githubusercontent.com/12776071/27432312-4a93199c-576d-11e7-8c28-41c862e0aa18.png)

After refreshing the page
![screen shot 2017-06-22 at 3 45 09 pm](https://user-images.githubusercontent.com/12776071/27432313-4a942706-576d-11e7-830b-c0cc73d46472.png)

**Comment by christianmemije** [comment]
Fixed in #1749

**Comment by swapnil106111** [comment]
@rtibbles  Retested. Now, its working fine.
![1](https://user-images.githubusercontent.com/12776071/27673466-87d6bea2-5cbe-11e7-9443-523c57f264e7.png)
![2](https://user-images.githubusercontent.com/12776071/27673465-87ab9b6e-5cbe-11e7-90ff-93a7a1810fed.png)
![3](https://user-images.githubusercontent.com/12776071/27673464-87189c9c-5cbe-11e7-8364-6bb1c4370df7.png)
![4](https://user-images.githubusercontent.com/12776071/27673462-865421dc-5cbe-11e7-954e-1fbd3f6396fc.png)
![6](https://user-images.githubusercontent.com/12776071/27673461-85dcbc8c-5cbe-11e7-958b-5d83b00269d2.png)
