### ISSUE TITLE
(Style guide) Whole screen disappears when testing out breadcrumbs

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1715]
## Summary

![breadcrumb bug](https://user-images.githubusercontent.com/6668144/27449658-02279ea0-573e-11e7-8dd0-cc30ca1fd49c.gif)

## System information

 - Version: 0.4.0beta10.dev484
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Nav to style guide
2. Click breadcrumbs page
3. Click on one of the example breadcrumbs

**Comment by jonboiser** [comment]
@jtamiace does the URL change when you click the breadcrumb?

**Comment by jtamiace** [comment]
Yes, it just adds an underscore:

http://localhost:8000/style_guide/components/breadcrumbs

to

http://localhost:8000/style_guide/components/breadcrumbs_

**Comment by jonboiser** [comment]
@jtamiace That might be the cause. After clicking the breadcrumb "link", the router might be attempting to resolve the `components/breadcrumbs_` route, which is probably not defined.
