### ISSUE TITLE
Invoke cli.update() every time plugins are updated or changed

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1717]
## Summary

As per #1615, there is an issue about .pex files with identical version files. Since we haven't pin-pointed the source of the issue, we can only guarantee consistency in migrations and static assets by running `cli.update()` every time kolibri starts.

So this is not an issue, until we revert this behaviour in #1498 

I think the necessary change would be to make the version file contain BOTH kolibri version and a list of everything in INSTALLED_APPS, moreover adding their version numbers. I'm not sure if loading `application.__init__` is safe for all apps, but since `django.setup()` is already called, I would assume it is.

## System information

Future kolibri :)

## How to reproduce

1. Install Kolibri + plugins
1. Upgrade a plugin or change plugin configuration

**Comment by indirectlylit** [comment]
It sounds like until end-users are manually installing plugins, this isn't a user-facing issue. Let me know if that's incorrect.

**Comment by benjaoming** [comment]
Ah yes @indirectlylit - and I will get the description updated so it doesn't revolve around things that have changed - but it should still be relevant, though not high priority.

**Comment by rtibbles** [comment]
This was fixed in #5957
