### ISSUE TITLE
imports get stuck when server is restarted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1720]
* begin importing channel
* stop server
* start server

Transfer is stuck partway. It does not continue, and due to #1673 cannot be canceled:

![image](https://user-images.githubusercontent.com/2367265/27461544-370a8796-576f-11e7-8e64-86fb3562d304.png)

**Comment by jonboiser** [comment]
Expected behavior is that there would be no in-progress Tasks, as Tasks are not restarted when the server is restarted.

**Comment by aronasorman** [comment]
When there's no import running, then clicking cancel should now clear the job from the job queue. Fixed by this PR: https://github.com/learningequality/kolibri/pull/1734

**Comment by indirectlylit** [comment]
would it be possible to always clear the queue on startup?

**Comment by aronasorman** [comment]
Yup! Should be in a PR coming in either later or tomorrow morning (along with some other optimizations)

**Comment by aronasorman** [comment]
@indirectlylit can you test this with the latest 5.x? We should be processing messages faster now.

**Comment by aronasorman** [comment]
Oh no wait, we now clear the queue on startup. Fixed.

**Comment by indirectlylit** [comment]
yup, works for me in 0.5.x - thanks!
