### ISSUE TITLE
poor user-facing handling of incomplete channel imports

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1721]
For typical scenarios, a user sees the following chain of events on channel import:

* Manage
  * initiate channel import
  * see progress indicator
  * channel appears in channel list
* Learn
  * channel appears in switcher
  * content is available to be browsed

However, it is possible to deviate from this flow in a couple ways:

 * User refreshes or opens Manage in a new tab. They will see the new channel in the list, with no indication that it's only partially imported.
 * Another user browses Learn while import is in progress. They will see the new channel, but fail to load content with 404s

We need to better handle "partially imported" channels for both learners and admins.

**Comment by rtibbles** [comment]
This is fixed in #1947, any residual poor user experience is tracked in #2078
