### ISSUE TITLE
The exercise got mastered before the learner reached the actual state of mastery.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1725]
## Summary

The mastery set for the exercise is 4 out of 5, but when the learner got correct 3 out of 4 the exercise got mastered.

**Note:** This happens pretty sporadically and not always consistent across all the exercises.

## System information
 - Version: kolibri 0.4.0 
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## Screenshots
Dashboard:
![dashboard1](https://user-images.githubusercontent.com/13453618/27506847-17455e32-58e0-11e7-85fe-b0bda7d75f17.png)
Learner's view of the exercise:
![whatsapp image 2017-06-24 at 1 15 00 pm](https://user-images.githubusercontent.com/13453618/27506850-387a94fa-58e0-11e7-8ba6-74b9f7107b4d.jpeg)
![whatsapp image 2017-06-24 at 1 14 59 pm](https://user-images.githubusercontent.com/13453618/27506851-39dfb83e-58e0-11e7-8224-7d69e94c95a7.jpeg)

**Comment by rtibbles** [comment]
This looks like a race condition in how the exercise progress is calculated. Will look into it today.

**Comment by harishbalachandran** [comment]
@rtibbles Havent faced till now, will re-open if found. You can close for now.
