### ISSUE TITLE
Device Admin should be able to edit the Facility name

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1728]
## Summary
<Imp Enhancement> Device Admin should be able to edit the Facility name.

At present the we cannot edit the facility name once its created at the device owner sign up.

This is an important feature to have since we at Nalanda implementation would be cloning the servers from the single server (Master server) which will have a particular Facility name and a specific channel across all the  servers. 
To differentiate the servers deployed at different schools and classrooms, we would need to change the Facility name to that specific school when giving it to the teachers. This feature if implemented will in-turn help us to track the progress when synced to the cloud with a unique Facility name.

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Login as a device admin.
2.  Navigate to facility.
3. Allow the device admin to edit the facility name.

## Screenshots
![facilityname](https://user-images.githubusercontent.com/13453618/27527959-bb22763e-5a6b-11e7-8fb8-88fbc35e0415.png)

**Comment by jonboiser** [comment]
@harishbalachandran I believe that the product roadmap includes a feature where a single device could manage multiple facilities, which would probably need names that can be edited. It seems like a reasonable enhancement in the single-facility scenario to make names editable.

**Comment by jamalex** [comment]
> This is an important feature to have since we at Nalanda implementation would be cloning the servers from the single server (Master server) which will have a particular Facility name and a specific channel across all the servers.

I agree that being able to edit the Facility name could be useful in itself, but we need to be very careful with the deployment process here, as the described method would lead to syncing issues down the road.

Let me first describe some background information to help clarify how things work and why this is important.

- When a new Facility is created, it creates an entry in the database with a unique ID for that Facility. This ID is used to identify that particular Facility, and all user accounts and data in that facility are then also associated with that ID.
- When syncing happens, that Facility record and associated data will be synced, and merged with all the other data associated with the same Facility ID.
- Changing the name of a Facility does not change that ID, so it is still the same Facility. When synced, the name change would sync also, and affect other servers with that same Facility ID. All classes and user accounts associated with the Facility ID would also be merged, and show up under the one big Facility after syncing.

To avoid these issues, please use the following procedure:

- Before creating a clone image of the master server, stop the server, and delete `~/.kolibri/db.sqlite3`. Then create the cloned image.
- Copy this cloned image (with no `db.sqlite3` user database) onto each of the servers.
- On the first server per school, start up the server and create the Facility, using the correct name for that school as the Facility Name.
- Copy `~/.kolibri/db.sqlite3` from that server onto any other servers for the same school. (Do *not* create new facilities manually on these additional servers for the same school, as they need to have the same Facility ID, in order for us to keep them in sync later.)
- Repeat the last two steps for each school.

You won't have to touch the content folder or other pieces (they can just be cloned verbatim). The only thing that matters is `~/.kolibri/db.sqlite3`. All servers for the same school should have a copy of the same `~/.kolibri/db.sqlite3` file, after the Facility for that school was created on one of the servers.

**Comment by jamalex** [comment]
Given the above ^^, I think it would be safest *not* to make the Facility name editable for now, and once we do add this, we'll have to put in a big warning explaining that changing the name doesn't make it a new Facility, and that these changes may affect other servers after syncing happens.

Another thing this highlights for me is that it could be useful to show the FacilityDataset UUID itself somewhere in the admin UI, for the current facility, in an unobtrusive but discoverable location/format.

**Comment by jredrejo** [comment]
@jonboiser  shouldn't we close this after #6755 was merged? or is there any difference I am missing?
