### ISSUE TITLE
Grid layout issue

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1732]
## Summary

* Grid layout issue.
## System information

- Develop

## How to reproduce

1. Filter topic items.

## Screenshots
![issues](https://user-images.githubusercontent.com/7193975/27562716-b0dda0ba-5a82-11e7-8c9b-6c5d860d56b5.gif)

**Comment by DXCanas** [comment]
@christianmemije Not seeing this issue with the tab filters. Seems to be an issue exclusive to https://github.com/learningequality/kolibri/pull/1793? Looking into it

**Comment by DXCanas** [comment]
Not seeing it inside #1793 either. Mind sending me the channnel you're using? Might have something to do with them being mixed content types

**Comment by christianmemije** [comment]
@DXCanas As @jonboiser pointed out, the issue is that there is a margin on the [span that wraps the content-card](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/content-card-grid/index.vue#L9) that appears even if the content-card does not.

**Comment by christianmemije** [comment]
Can no longer reproduce, closing.
