### ISSUE TITLE
After using the hint button cannot proceed to the next question.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1738]
## Summary

After using the hint button cannot proceed to the next question, on few of the KhanAcademy exercises.  

This is faced on across both English and Hindi channels. And hope a single fix would fix the problem across all the exercises. 

Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5

Exercise:
Class 6 (India) --> Playing with numbers --> Prime factorization --> Prime factorization
Class 6 (India) --> Playing with numbers -->  Lowest common multiple --> Exercise in it
गणितकक्षा 6 (India) --> भिन्न  विषम और मिश्रित भिन्न --> भिन्नों को विघटित करें
गणितकक्षा 6 (India)-->भिन्न  एक भिन्न का सरलीकृत रूप ---> भिन्नों को सरलीकृत करें 
गणितकक्षा 8 (भारत )-->अध्याय 7: घन और घनमूल-->  घनमूल-->घनमूल

Note:
If there are 4 hints few hints gets wrapped and not displayed, please refer the hints in the screenshot below. Raising a separate defect for this issue, to track it separately. 

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1.  Use hint in that exercise
2. Enter the correct answer.
3. Click on Check Answer.
4. Does not proceed to next question.

## Screenshots
English Channel:
![a1](https://user-images.githubusercontent.com/13453618/27575008-087a346a-5b36-11e7-9c3e-6973812e08e2.png)
![a2](https://user-images.githubusercontent.com/13453618/27575012-0970e09e-5b36-11e7-9799-4453912f2588.png)
![a3](https://user-images.githubusercontent.com/13453618/27575009-09668cca-5b36-11e7-8570-df851b3bf1c9.png)
![a4](https://user-images.githubusercontent.com/13453618/27575011-096f6c1e-5b36-11e7-9d6f-ba12632f0cc2.png)
![a5](https://user-images.githubusercontent.com/13453618/27575010-09687e86-5b36-11e7-8560-3e3a0f1a2d5e.png)

Hindi Channel:
![a6](https://user-images.githubusercontent.com/13453618/27574789-53d447d0-5b35-11e7-96f5-4cf07ae12d1e.png)
![a1](https://user-images.githubusercontent.com/13453618/27574788-52f17ffe-5b35-11e7-9012-b543cdfafa88.png)
![a2](https://user-images.githubusercontent.com/13453618/27574791-53d727c0-5b35-11e7-9446-b28098a9bbfc.png)
![a3](https://user-images.githubusercontent.com/13453618/27574793-53ddab22-5b35-11e7-9997-2972f485a807.png)
![a4](https://user-images.githubusercontent.com/13453618/27574790-53d566c4-5b35-11e7-969e-5e034c4f396a.png)
![a5](https://user-images.githubusercontent.com/13453618/27574792-53d82d46-5b35-11e7-9a00-65f1799eca0b.png)

More Exercises: 
![hindi1](https://user-images.githubusercontent.com/13453618/27576430-98835254-5b3a-11e7-9197-882eed9187c5.png)
![hindi2](https://user-images.githubusercontent.com/13453618/27576432-99631466-5b3a-11e7-9667-2875847a5b8e.png)

![g1](https://user-images.githubusercontent.com/13453618/27576929-632e3c0c-5b3c-11e7-8d46-8964819eb079.png)

**Comment by harishbalachandran** [comment]
@rtibbles Seams to have been fixed.

**Comment by harishbalachandran** [comment]
@rtibbles Retested and works fine now.

**Comment by harishbalachandran** [comment]
@rtibbles, this problem did not get fixed on these topics:
Channel ID: 
eb99f209f9c34ba192f6e695aeb37e4f
Path: Class 7 (India) --> Fractions and decimals --> Multiplication of decimal numbers.
Exercise:
Multiplying decimals 1 (standard algorithm)
Multiplying decimals 1 (standard algorithm)

Path: Class 8(India) --> Cubes and Cubes roots --> Cube roots.
Exercise:
 Cube roots
 
![3](https://user-images.githubusercontent.com/13453618/27788307-b9b03d32-6005-11e7-8edd-82e73b0da50c.png)
![1](https://user-images.githubusercontent.com/13453618/27788312-c03dadec-6005-11e7-9e52-8fe4be756f7c.png)
![2](https://user-images.githubusercontent.com/13453618/27788429-34be2214-6006-11e7-915a-fdc6cb337da3.png)

![1_1](https://user-images.githubusercontent.com/13453618/27788566-d0c723a4-6006-11e7-97f1-da61205bef40.png)
![1_2](https://user-images.githubusercontent.com/13453618/27788569-d1a430b4-6006-11e7-93d8-33bf73610818.png)

**Note**
The same exercise are not working on Hindi channel too, e890b1acbcad44939688dbb1b7dde2e5

**Comment by rtibbles** [comment]
Hi @harishbalachandran I am unable to replicate this issue on either of the exercises you mention here. Also, I would note that you are testing with a device owner account, this account acts differently to other user accounts, so the learner experience is best tested with a non-device owner account.
