### ISSUE TITLE
Not all the hints are displayed and some gets hidden as we open more hints.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1739]
## Summary

Not all the hints are displayed and some gets hidden as we open more hints.

**Note:
The same behaviour is seen at KA.org hence don't know if this can be sorted at Kolibri specifically. 
If it cannot be handled then please close this issue.**

Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5

Exercise:
Class 6 (India) --> Playing with numbers --> Prime factorization --> Prime factorization

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Use the hints.
2. Observe that the hints gets hidden.

## Screenshots
Hint 2/4 is hidden
![a5](https://user-images.githubusercontent.com/13453618/27575752-5b5f8912-5b38-11e7-9c50-d82587c90186.png)

Hints 4 to 9 are hidden.

![c6](https://user-images.githubusercontent.com/13453618/27575797-87267c40-5b38-11e7-8583-04f115e6080f.png)

**Comment by rtibbles** [comment]
@harishbalachandran this is intended behaviour from Khan Academy, some hints have a specific key of 'replace' to show that they should overwrite the previous hint.
