### ISSUE TITLE
Questions not getting displayed for few of the exercise in Hindi KA Exercise

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1740]
## Summary

Questions not getting displayed for few of the exercise in Hindi KA Exercise

Note:
The same question are working fine in English channel exercise. 

Channel ID:
e890b1acbcad44939688dbb1b7dde2e5

Exercise Path:
 गणितकक्षा 6 (India) --> भिन्न  तुल्य भिन्न ---> तुल्य भिन्न (भिन्न मॉडल)
गणितकक्षा 6 (India) --> अनुपात और समानुपात -->  अनुपात शब्द समस्याएँ ---> अनुपात शब्द समस्याएँ 
गणितकक्षा 7 (India) --> पूर्णांक -->  पूर्णांकों की आधारभूत संकल्पनाएँ
गणितकक्षा 7 (India)--> भिन्न एवं दशमलव  --> भिन्नों का गुणन --> भिन्नों और पूर्ण संख्याओं को गुणा करना 1
गणितकक्षा 7 (India)--->परिमेय संख्या--->  संख्या रेखा पर परिमेय संख्या-->संख्या रेखा पर परिमेय संख्याएँ
गणितकक्षा 7 (India)-->रेखा और कोण-->  रेखाओं के युग्म-->Angle relationships with parallel lines.
गणितकक्षा 7 (India)-->त्रिभुजों की सर्वांगसमता-->  त्रिभुजों की सर्वांगसमता की कसौटियां-->सर्वांगसम त्रिभुजों के कोणों का माप ज्ञात करें

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Access the exercise.
2. You will find that the problem will pop up.

## Screenshots

![d1](https://user-images.githubusercontent.com/13453618/27576852-1783b57a-5b3c-11e7-836d-11552a2b3af3.png)
![d2](https://user-images.githubusercontent.com/13453618/27576853-18568d24-5b3c-11e7-81bb-bcd0f3d7acb1.png)
![f1](https://user-images.githubusercontent.com/13453618/27576854-185a52d8-5b3c-11e7-9f59-6854ece15498.png)
![h1](https://user-images.githubusercontent.com/13453618/27577350-00b5b09e-5b3e-11e7-88b9-53e17027c291.png)
![i1](https://user-images.githubusercontent.com/13453618/27580764-52c64d48-5b49-11e7-90b5-b0eea669f450.png)
![i2](https://user-images.githubusercontent.com/13453618/27580765-539a9a62-5b49-11e7-8d53-6551cb000cff.png)

**Comment by harishbalachandran** [comment]
@rtibbles seams to work fine.

**Comment by harishbalachandran** [comment]
@rtibbles, reimported and validated all the exercise and found that the issue persists for the following exercise.
Channel ID's:
e890b1acbcad44939688dbb1b7dde2e5
eb99f209f9c34ba192f6e695aeb37e4f

Path:

कक्षा 7 (India)प्रायोगिक ज्यामिति --> एक त्रिभुज की रचना जब उसकी तीनों भुजाओं की लंबाइयाँ दी गयी हो (SSS कसौटी) --> त्रिकोणों का निर्माण

Topics Class 7 (India)Practical geometry  Construction of triangles when the lengths of its three sides are known (SSS Criterion)

![4](https://user-images.githubusercontent.com/13453618/27790475-29c43878-600e-11e7-8439-c1571817bbf1.png)
![5](https://user-images.githubusercontent.com/13453618/27790477-2a6b0324-600e-11e7-9854-fb91637e12bc.png)

**Comment by rtibbles** [comment]
Ah, this war a different error to the rest, had not seen the difference until now.

**Comment by rtibbles** [comment]
Replicated - appears to be malformed exercise data.

**Comment by rtibbles** [comment]
Doubt this will be fixed prior to roll out, unfortunately.
