### ISSUE TITLE
Answers for the fractions questions on Hindi KA Exercise are not accepted even after entering the correct answer.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1741]
x`## Summary
Answers for the fractions questions on Hindi KA Exercise are not accepted even after entering the correct answer.

**Note:** 
The same questions are working fine on English KA exercises. 

Channel ID:
e890b1acbcad44939688dbb1b7dde2e5

Path:
 गणितकक्षा 7 (India) -- > भिन्न एवं दशमलव --> भिन्नों का गुणन --> दृष्टिगत रूप से भिन्नों और पूर्ण संख्याओं को गुणा करना
 गणितकक्षा 7 (India)-->भिन्न एवं दशमलव --> भिन्नों का गुणन --> भिन्नों का गुणन
गणितकक्षा 7 (India)-->भिन्न एवं दशमलव  भिन्नों का गुणन --> भिन्नात्मक भुजा की लम्बाई वाले आयतों का क्षेत्रफल
गणितकक्षा 7 (India)-->भिन्न एवं दशमलव--->  भिन्नों का गुणन-->मिश्रित संख्याओं को गुणा करना
 गणितकक्षा 7 (India)--->भिन्न एवं दशमलव---->  भिन्नों का गुणन---> भिन्नों संबंधित शाब्दिक समस्याओं का गुणन
गणितकक्षा 7 (India)--->भिन्न एवं दशमलव---->  पूर्ण संख्याओं और भिन्नों का विभाजन--->भिन्नो और पूर्ण संख्याओं के विभाजन से संबंधित शाब्दिक समस्याएँ 
गणितकक्षा 7 (India)-->भिन्न एवं दशमलव-->  भिन्नों का भिन्नों से विभाजन ---> भिन्नों का विभाजन
गणितकक्षा 7 (India)--->परिमेय संख्या ---> परिमय संख्याओं को जोड़ना और घटाना--->सार्व हर वाले भिन्नों को जोडें
 गणितकक्षा 7 (India)-->परिमेय संख्या--->  परिमय संख्याओं को जोड़ना और घटाना-->सार्व हर वाले भिन्नों को घटाएँ
गणितकक्षा 7 (India)--->परिमेय संख्या-->  परिमय संख्याओं को जोड़ना और घटाना-->असमान हर वाले भिन्नों को जोडें
 गणितकक्षा 7 (India)-->परिमेय संख्या-->  परिमय संख्याओं को जोड़ना और घटाना-->असमान हर वाले भिन्नों को घटाना 
 गणितकक्षा 7 (India)-->परिमेय संख्या--->  परिमय संख्याओं को जोड़ना और घटाना-->मिश्रित संख्याओं को जोड़ना और घटाना 2

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Reach the exercise.
2. Try to enter the correct answer and proceed to the next question.

## Screenshots
![j1](https://user-images.githubusercontent.com/13453618/27588093-8f705692-5b64-11e7-97cc-b25bbbeea697.png)
![j2](https://user-images.githubusercontent.com/13453618/27588094-8fcce2e0-5b64-11e7-8b6e-47c29af87550.png)
![j3](https://user-images.githubusercontent.com/13453618/27588096-8fd386cc-5b64-11e7-830a-d7665fda5ee9.png)
![j4](https://user-images.githubusercontent.com/13453618/27588097-8fd503f8-5b64-11e7-8b09-72d1e520b279.png)
![k1](https://user-images.githubusercontent.com/13453618/27588095-8fd1038e-5b64-11e7-9644-6ad76f7bfeea.png)
![k2](https://user-images.githubusercontent.com/13453618/27588098-8fd4fc96-5b64-11e7-9fe9-6727d0a751c2.png)
![k4](https://user-images.githubusercontent.com/13453618/27589335-b53d4cbe-5b68-11e7-969f-76350900e9dd.png)
![k5](https://user-images.githubusercontent.com/13453618/27589337-b576bc10-5b68-11e7-90e0-44ac1fc0a841.png)
![k6](https://user-images.githubusercontent.com/13453618/27589336-b572bee4-5b68-11e7-8044-1e6ad342fe98.png)

**Comment by rtibbles** [comment]
We have just republished the Hindi Rajasthan channel, and I am now unable to replicate this issue.
