### ISSUE TITLE
Cannot move geometrical figures on a co-ordinate plane to proceed to the next question.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1744]
## Summary
Cannot move geometrical figures on a co-ordinate plane to proceed to the next question.

This is faced across both English and Hindi channels for the geometrical concepts.

Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5 - Hindi

Path:
Class 7 (India)-->Congruence of triangles-->  What makes two shapes congruent?-->Congruence & transformations

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Reach the exercise mentioned above.
2. Try to solve and proceed to the next question.

## Screenshots
![m1](https://user-images.githubusercontent.com/13453618/27590933-da28ef60-5b6d-11e7-95f1-9c571d71819a.png)
![m2](https://user-images.githubusercontent.com/13453618/27590934-da726050-5b6d-11e7-81e8-e69f4b51daf3.png)
![m3](https://user-images.githubusercontent.com/13453618/27590935-da755a6c-5b6d-11e7-91b9-d021b1e389db.png)
![m4](https://user-images.githubusercontent.com/13453618/27590936-da780294-5b6d-11e7-8f28-cc0a9f112465.png)

**Comment by rtibbles** [comment]
@ralphiee22 there are images with invalid paths in this exercise: `Not allowed to load local resource: file:///data/ka-sushi-chef-en/build/15d/15dd019cb26fdde772fb82a33fa0874374c9e96e.png`

**Comment by rtibbles** [comment]
This seems to be due to missing images, is being fixed.

**Comment by rtibbles** [comment]
Hrm, there are some additional issues, potentially, over and above the missing images. Investigating further.

**Comment by rtibbles** [comment]
Have found the cause of this issue, beyond the missing images, submitting a fix.

**Comment by rtibbles** [comment]
Due to missing `$_` global in the perseus renderer plugin.

**Comment by harishbalachandran** [comment]
@rtibbles seams to work now.

**Comment by harishbalachandran** [comment]
@rtibbles , this exercise does not work on a tablet.

**Channel ID's:**
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5 - Hindi
**Path:**
Class 7 (India)-->Congruence of triangles--> What makes two shapes congruent-->Congruence & transformations
Class 5(India) --> Shapes and Angles --> Angles and unit measurement for angles --> Measure angles.
After using the hint and trying to solve the question the subsequent questions I m getting the error shown below:
![whatsapp image 2017-07-03 at 4 53 28 pm 1](https://user-images.githubusercontent.com/13453618/27791127-34d4169a-6011-11e7-979a-6c685d6ecbae.jpeg)
![whatsapp image 2017-07-03 at 4 53 28 pm 4](https://user-images.githubusercontent.com/13453618/27791138-3c8aa08e-6011-11e7-96d9-8351917b13e7.jpeg)

Protractor is not seen:
![whatsapp image 2017-07-03 at 4 53 28 pm 3](https://user-images.githubusercontent.com/13453618/27791143-448cf4ee-6011-11e7-8243-01de84665bd5.jpeg)
![Uploading WhatsApp Image 2017-07-03 at 4.53.28 PM (5).jpeg…]()

**Comment by rtibbles** [comment]
@DXCanas can you investigate this issue on a tablet?

**Comment by DXCanas** [comment]
Can't seem to be able to duplicate this on the android tablets in office using the same content channel + item on release 0.5x.
