### ISSUE TITLE
Figures from the question are missing in both KA En and Hi exercises.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1745]
## Summary

Figures from the question are missing in both KA En and Hi exercises.

Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5

Path:
Class 7 (India)-->Visualizing solid shapes--->  Nets for building 3D shapes-->Surface area
Class 7 (India)-->Data handling-->  Arithmetic mean, mode, and median-->Calculating the mean: data displays
Class 7 (India)--->Data handling--->  Arithmetic mean, mode, and median-->Calculating the median: data displays

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Navigate to the exercise.
2. Notice that the figures are not displayed

## Screenshots
![n1](https://user-images.githubusercontent.com/13453618/27591630-e5780872-5b6f-11e7-8ed6-d72fa915b719.png)
![n2](https://user-images.githubusercontent.com/13453618/27591633-e5cafaa0-5b6f-11e7-9fc1-a4a36df8b996.png)
![n3](https://user-images.githubusercontent.com/13453618/27591631-e5bc944c-5b6f-11e7-9ac1-269474da356a.png)
![n4](https://user-images.githubusercontent.com/13453618/27591632-e5bdefa4-5b6f-11e7-98f9-8bddded80d05.png)

**Comment by rtibbles** [comment]
@ralphiee22 this is due to incorrect `backgroundImage` `url` properties.
`Not allowed to load local resource: file:///data/ka-sushi-chef-en/build/0af/0af8aac45ffa4eff210e2fc77c6b4bfa176b4f29.svg`
