### ISSUE TITLE
Figures are missing and the letters runner reach other and the hints button is not working for a particular Hi KA exercise

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1746]
## Summary

Figures are missing and the letters runner reach other and the hints button is not working for a particular Hi KA exercise

Note:
This exercise works properly in en KA channel.

Channel ID's:
e890b1acbcad44939688dbb1b7dde2e5

Path:
गणितकक्षा 7 (India)-->परिमाप और क्षेत्रफल-->  एक समांतर चतुर्भुज का क्षेत्रफल -->समांतर चतुर्भुजों का क्षेत्रफल

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Go to the exercise mentioned above.
2. Notice the question, figure is missing and the hint does not work.

## Screenshots
![n7](https://user-images.githubusercontent.com/13453618/27592043-1e429a2c-5b71-11e7-8b9e-237e3ab938f7.png)

**Comment by rtibbles** [comment]
Unable to replicate following most recent content publish.
