### ISSUE TITLE
The entire question is not displayed for a specific khan academy hi and en exercise.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1747]
## Summary

The entire question is not displayed for a specific khan academy **hi** and **en** exercise.

Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5 - Hindi

Path:
Class 8 (India)--> Exponents and powers-->  Laws of exponents-->Properties of exponents challenge(integer exponents)

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Access the exercise mentioned above.
2. The entire exercise will not be displayed.

## Screenshots
![n8](https://user-images.githubusercontent.com/13453618/27593719-82a5915a-5b75-11e7-8882-abaae2051e28.png)

**Comment by rtibbles** [comment]
This is due to the mastery model `type` being set to `do-all`, rather than `do_all`.

**Comment by harishbalachandran** [comment]
@rtibbles seams to work fine now.

**Comment by harishbalachandran** [comment]
@rtibbles re-imported the channels and this issue stills exists.
Channel ID's:
eb99f209f9c34ba192f6e695aeb37e4f - English
e890b1acbcad44939688dbb1b7dde2e5 - Hindi
Path:
Class 8 (India)--> Exponents and powers--> Laws of exponents-->Properties of exponents challenge(integer exponents)
Class 9(India) --> Number system --> Properties of exponents (Rational exponents) -->  Properties of exponents (Rational exponents)
Class 9(India) --> Number system --> Properties of exponents (Rational exponents) --> Properties on exponents challenge (Rational exponents) **The hints and the expression is not seen**


![2_1](https://user-images.githubusercontent.com/13453618/27788949-221fee56-6008-11e7-84df-eae8e40686c3.png)
![2_2](https://user-images.githubusercontent.com/13453618/27788950-2222b23a-6008-11e7-8b9e-2974cbb76749.png)

**Comment by rtibbles** [comment]
Again, I am not replicating these on the latest content. Are you sure you are using the latest installer to test this, as this fix was made in Kolibri 0.4.1?
