### ISSUE TITLE
The Pictographs and Frequency tables are not completely visible to work on the question in KA English Channel.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1755]
## Summary
The Pictographs and Frequency tables are not completely visible to determine the answers in KA English Channel.

Channel ID:
eb99f209f9c34ba192f6e695aeb37e4f

Path:
Class 6 (India)-->Data handling-->  Pictographs--> Read picture graphs
Class 6 (India)-->Data handling-->  Bar graphs--> Solve problems with bar graphs 1
Class 6 (India)-->Data handling-->  Bar graphs--> Solve problems with bar graphs 2

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Navigate to the exercises above
2. Check the pictographs and frequency tables.

## Screenshots
![q1](https://user-images.githubusercontent.com/13453618/27625068-e54efa90-5c00-11e7-97c1-d0feb004dafc.png)
![q2](https://user-images.githubusercontent.com/13453618/27625076-e640c4f6-5c00-11e7-99b0-30fbb21ea7cb.png)
![q3](https://user-images.githubusercontent.com/13453618/27625075-e639ac66-5c00-11e7-80fd-5796eccec192.png)
![q5](https://user-images.githubusercontent.com/13453618/27625074-e6399c62-5c00-11e7-95c3-9a5595b340cc.png)

**Comment by rtibbles** [comment]
I have not been able to replicate the issue on picture graphs, but the bar graphs seem to be missing a data json file.

@ralphiee22 this seems to be a result of the extant `file:///.....` paths in url keys, so should be fixed by the same work you are already doing.
