### ISSUE TITLE
The questions that has number line get cutoff when viewed on a tablet on Portrait mode.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1756]
## Summary
The questions that has number line get cut-off when viewed on a tablet on a Portrait mode.

KA English channel:
eb99f209f9c34ba192f6e695aeb37e4f

Path:
Grade 7 --> Fractions and Decimals-->Multiplication of fractions --> Multiplying fractions and whole numbers 1

Grade 7 --> Rational numbers-->Multiplication of rational numbers --> Multiplying fractions and whole numbers 1

Grade 7 --> Symmetry-->Lines of symmetry for regular polygons --> Draw lines of symmetry and symmetrical figures

## System information
 - Version: Kolibri 0.4.0
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Navigate to the path
2. Observer the number lines on a tablet/phone in portrait mode.

## Screenshots
![whatsapp image 2017-06-28 at 2 36 51 pm 1](https://user-images.githubusercontent.com/13453618/27629301-87316286-5c0f-11e7-9e65-644776261697.jpeg)
![whatsapp image 2017-06-28 at 2 36 51 pm](https://user-images.githubusercontent.com/13453618/27629302-87973c0a-5c0f-11e7-85e8-378cd46e3a92.jpeg)

**Comment by rtibbles** [comment]
Did this happen after navigating to the page in portrait mode, or after navigation and switching to portrait mode? I have a made a fix that should help the former case, but a fix for the latter case will not be possible in this time frame.

**Comment by harishbalachandran** [comment]
@rtibbles its the former case, hope the fix fixes the issue 👍
