### ISSUE TITLE
bbq explosion

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1765]
On 0.5.x I was running an import, and then...

![image](https://user-images.githubusercontent.com/2367265/27664166-e80116f0-5c1a-11e7-9f90-117c4a3c2074.png)

**Comment by indirectlylit** [comment]
possibly due to not having upgraded bbq?

**Comment by indirectlylit** [comment]
closing - I think I didn't have BBQ updated

**Comment by indirectlylit** [comment]
actually, just reproduced it again

**Comment by aronasorman** [comment]
Leave this to me.

**Comment by aronasorman** [comment]
Fixed in some bbq version.
