### ISSUE TITLE
ENHANCEMENT: Support markdown on descriptions

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri#1782]
## Summary

It might be nice to handle markdown content in descriptions.

## Screenshots

Example: TRANSCRIPT should be on its own line to separate it from the summary of the video

![image](https://user-images.githubusercontent.com/7447496/27757980-230cb83a-5dbf-11e7-9be9-66b9c81f9bd4.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

 Some content sources might have text that needs to be separated using a linebreak, which currently is not supported in Kolibri

**Comment by rtibbles** [comment]
Might be a good starting point http://miaolz123.github.io/vue-markdown/

**Comment by christianmemije** [comment]
Addressed in #1804
