### ISSUE TITLE
Thumbnails show under "Recommended" but not under "Topics"

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1783]
## Summary

For the same content nodes, graphic thumbnails show up on recommended page, but in topic tree, just show the generic icons.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.5.0-beta1
 - Operating system: Android
 - Browser: Chrome or webview

## How to reproduce

1. Load channel fb51dae6df7545af8455aa3a0c32048d
1. Go to /learn/#/fb51dae6df7545af8455aa3a0c32048d/recommended
1. Compare with /learn/#/fb51dae6df7545af8455aa3a0c32048d/topics/t/6e1f847e1f6441328f1519939af5b842

## Screenshots

![image](https://user-images.githubusercontent.com/618416/27759266-02b2371e-5de1-11e7-85b5-cef7065057b0.png)

![image](https://user-images.githubusercontent.com/618416/27759273-6716f6ea-5de1-11e7-91b0-058012819d4c.png)

**Comment by laurenlichtman** [comment]
I had the same experience on Kolibri 0.4.0.dev446 in Windows 10.

**Comment by jonboiser** [comment]
Should have been fixed in #1821
