### ISSUE TITLE
Database is locked.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1794]
## Summary
While importing a channel(9e5305326ed742d0892479dea825a514) showing database is locked.

## System information

 - Version: kolibri 0.4.2
 - Operating system: ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1.Login as Device owner
2. import channel 9e5305326ed742d0892479dea825a514

## Screenshots
![screenshot from 2017-07-04 19_26_10](https://user-images.githubusercontent.com/12776071/27833479-ae2407e6-60f0-11e7-959b-ee78b7986615.png)

Log file 

[log.txt](https://github.com/learningequality/kolibri/files/1122322/log.txt)

**Comment by benjaoming** [comment]
Assuming this is possible because multiple threads are accessing the same database. Or multiple processes (for instance an unterminated "zombie" worker from an old kolibri instance).

The error happens for specific reasons, though. @swapnil106111 if you do a reboot in order to guarantee that there are no other kolibri processes running, and you just start kolibri once - will it continue with this error?

See also: https://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked

**Comment by jamalex** [comment]
This looks like an issue in https://github.com/learningequality/barbequeue, and hence in @aronasorman's wheelhouse.

However, it doesn't seem to be interfering with the actual download progress -- I think it's just the task status tracking DB that's being competed over by multiple threads. Should be fixed, but seems as if it may not be a blocker to use here, unless you're seeing other issues as a result, @swapnil106111?

If you _are_ seeing problems as a result: an alternative method to updating a channel is to shut down the Kolibri server (`kolibri stop`), and then run the following 2 commands on the terminal:
```
kolibri manage importchannel -- network CHANNELID
kolibri manage importcontent -- network CHANNELID
```
(where CHANNELID is the ID of the channel you want)

**Comment by benjaoming** [comment]
@jamalex `kolibri stop` was introduced in 0.5. Same for barbequeue.

But I think it's still possible to start and CTRL+C kill kolibri and end up with a dangling worker process.

**Comment by jamalex** [comment]
Ahh, right -- I saw it was being thrown by a "loop over task object" query, so I was thinking barbequeue. Seems like a django-q issue, then -- which makes it even less of a concern, since it won't show up in 0.5+

**Comment by jamalex** [comment]
(So we can probably safely close this issue, but I'll leave that to @aronasorman )

**Comment by aronasorman** [comment]
Yeah, this is 4.x and django-q, which makes optimizations harder (the problem here is one of the threads is holding on to the write lock too long and timing out other threads).

The easiest fix here is to increase the SQLite timeout and hope for the best:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': '/home/tomi/djangotest.sqlite',
        'USER': '',              # Not used with sqlite3.
        'PASSWORD': '',          # Not used with sqlite3.
        'HOST': '',              # Not used with sqlite3.
        'PORT': '',              # Not used with sqlite3.
        # for sqlite write lock timeout
        'OPTIONS': {
            'timeout': 5,
        }
    }
}
```
