### ISSUE TITLE
<Critical>A learner when accumulates a lot of points by mastering the videos and Exercises stops working.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1795]
## Summary

<Critical>A learner when accumulates a lot of points by mastering the videos and Exercises, the account stops working and when we try to login we get 504 error.

This has been found at multiple locations where the entire Nalanda team is validating the content by solving the exercise on Kolibri.

This is not channel dependent since we have noticed this on all the channels, but here are the channel ID's where we face this problem quite often.
9e5305326ed742d0892479dea825a514
8fc515793aad4e52b490b03c48ad21de

**Note: All the other accounts with lesser points work fine in the same server, its just the problem with the learner who has too a lot of points.**

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Latest Kolibri 0.4.2
 - Operating system: Ubuntu 14.04
 - Browser: Chrome and Firefox.

## How to reproduce

1. Make a learner ID
2. Solve many exercise to get points more than 10,000
3. Suddenly we get Error page.
4. And on refreshing and try t login we get 504 error for that specific account.

## Screenshots
Kolibri.log
[kolibri_new.txt](https://github.com/learningequality/kolibri/files/1123469/kolibri_new.txt)

We get the error page first:
![img-20170704-wa0023](https://user-images.githubusercontent.com/13453618/27836411-fd5bafba-60fc-11e7-86c1-11f498671972.jpeg)
And on refreshing:
![img-20170704-wa0025](https://user-images.githubusercontent.com/13453618/27836483-379ce428-60fd-11e7-9dd0-594e015d776f.jpeg)

Trying to login Again with the same account:
![screen shot 2017-07-04 at 7 43 56 pm](https://user-images.githubusercontent.com/13453618/27836437-10027cde-60fd-11e7-8ca5-40df4951d076.png)
![screen shot 2017-07-04 at 7 46 03 pm](https://user-images.githubusercontent.com/13453618/27836451-1aef2818-60fd-11e7-95c6-b7560ea60698.png)

This page is accessible but when we try to click on learn tab then we get the same 504 error page:
![screen shot 2017-07-04 at 7 50 33 pm](https://user-images.githubusercontent.com/13453618/27836524-5efc5a9e-60fd-11e7-8ee1-7c50da49dae8.png)

**Comment by jamalex** [comment]
Big improvements seen with https://github.com/learningequality/kolibri/pull/1798 -- will be in a release shortly.

**Comment by jamalex** [comment]
Should be improved in https://github.com/learningequality/kolibri/releases/tag/v0.4.3 -- please test and confirm, and close this issue if it's resolved for you.

**Comment by harishbalachandran** [comment]
@jamalex  Validated with 2 learners, they have accumulated 6500 and 10,000 points respectively and did not face any issues. 

Thanks! Closing for now. 
![img_20170705_150827](https://user-images.githubusercontent.com/13453618/27873778-e88446be-61ca-11e7-9a60-3b14719dd20b.jpg)
![img_20170705_150902](https://user-images.githubusercontent.com/13453618/27873780-e8e7948a-61ca-11e7-80c9-8c7b249b1ece.jpg)
