### ISSUE TITLE
<Major> 0 being the correct answer for a question is not accepted by the platform.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1796]
## Summary

<Major> 0 being the correct answer for a question is not accepted by the platform.

The right answer for the question is 0 and the platform does not consider it as correct and does not allow to proceed. 

Sample Channel:
9e5305326ed742d0892479dea825a514
Path:
CBSE-->3 --> 5 Shapes and Design --> Edges and corners, curved and Straight.

## System information
 - Version: Kolibri 0.4.2
 - Operating system: Ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1. Follow the path 
2. Solve the question till you get the question that correct answer is 0.
3. Cannot proceed to the next question.

## Screenshots
![screen shot 2017-07-04 at 8 11 55 pm](https://user-images.githubusercontent.com/13453618/27836864-eaf88116-60fe-11e7-963a-2682ba485420.png)
![screen shot 2017-07-04 at 8 11 21 pm](https://user-images.githubusercontent.com/13453618/27836872-f3d6eb9c-60fe-11e7-8a04-c488fdcc18b1.png)
![screen shot 2017-07-04 at 8 12 37 pm](https://user-images.githubusercontent.com/13453618/27836875-fd7faff8-60fe-11e7-9e4e-dd8ee9e5f877.png)

**Comment by navakk9** [comment]
@rtibbles

**Comment by jamalex** [comment]
Looking at the JSON for the question, it seems there are no answers listed:
http://contentworkshop.learningequality.org/zipcontent/f43c2b9101c2c5f31bf3cc4c040034ab.perseus/6ecf1f1fce115ea4983cf47d4e047d04.json

I'll take a look at the sushi chef to see whether I see any reasons in there why this might be. But this doesn't look to be an issue with Kolibri itself.

**Comment by jamalex** [comment]
Should be fixed by https://github.com/fle-internal/content-curation/pull/377 -- will deploy that and re-export channels shortly.

**Comment by jamalex** [comment]
Channels have been re-published; re-opening this issue (it was auto-closed) until you've tested.

**Comment by harishbalachandran** [comment]
@jamalex , These are the base MG channels:
6996f85e5a1f508e8757cf9a4ce1085a
2ce8480105415643888efe9aadc3e497

These are the curated and the channels that will be used in actual deployment:
9e5305326ed742d0892479dea825a514 - This is the ID that logged this issue with, Reimporting the channel to verify.
**8fc515793aad4e52b490b03c48ad21de - IS this also fixed and republish so that I can reimport and validate?**

**Comment by harishbalachandran** [comment]
@jamalex @navakk9 @rtibbles Quick update!

Tested on 9e5305326ed742d0892479dea825a514 after reimporting, Issue resolved. 

8fc515793aad4e52b490b03c48ad21de - Getting reimported will let you know the results of this in an hour.

**Comment by harishbalachandran** [comment]
@jamalex @navakk9 8fc515793aad4e52b490b03c48ad21de  - Validated works fine. Thanks!

**Comment by jamalex** [comment]
Excellent!

**Comment by harishbalachandran** [comment]
@aronasorman @rtibbles 8fc515793aad4e52b490b03c48ad21de - This issue has re-appeared on the latest pex file (kolibri-v0.4.4-4-gc23b072.pex) sent to us, it would be great if you could you could put fix this issue on a updated pex, since many of the questions ave 0 as answer and the kids are not able to proceed to the next question or master the exercise.
![whatsapp image 2017-07-24 at 10 40 14 pm](https://user-images.githubusercontent.com/13453618/28535564-794becfa-70c2-11e7-8a46-b27f754bbd26.jpeg)
![whatsapp image 2017-07-24 at 10 49 21 pm](https://user-images.githubusercontent.com/13453618/28535565-79ca4a5a-70c2-11e7-9458-bddb2c125ccc.jpeg)

**Comment by rtibbles** [comment]
@harishbalachandran this is a content issue, so if it has recurred, it must be that some content has not been updated properly, so it is independent of the pex file.

**Comment by jamalex** [comment]
This is coming from the following perseus file:
https://contentworkshop.learningequality.org/content/storage/c/4/c4be971349d2301e6c5337f80ca7bdd5.perseus

Within that zip, it's coming from `3e540487c1895bb1b446ff939edb638d.json`, which correctly identifies 0 as a correct answer:

```
{
    "question": {
        "content": "![](${☣ LOCALPATH}/images/2c9a6c064bf96fab5fc580d14bb741c9.png)\n\nNumber of rays you can see in this figure are \\_\\_\\_\\_\\_\\_ .\n\n\n\n[[☃ numeric-input 1]]",
        "images": {},
        "widgets":  {
            "numeric-input 1": {
                "type":"numeric-input",
                "alignment":"default",
                "static":false,
                "graded":true,
                "options": {
                    "static":false,
                    "answers":[
                        {
                            "value": 0.0,
                            "status": "correct",
                            "message": "",
                            "strict": false,
                            "simplify":true,
                            "maxError": 0,
                            "answerForms": [
                                "proper",
                                "mixed",
                                "integer",
                                "decimal",
                                "improper"
                            ]
                        }
                    ],
                    "size":"normal",
                    "coefficient":false,
                    "labelText":""
                },
                "version": {
                    "major":0,
                    "minor":0
                }
            }
        }
    },
    "answerArea":{
        "calculator":false,
        "chi2Table":false,
        "periodicTable":false,
        "tTable":false,
        "zTable":false
    },
    "itemDataVersion": {
        "major": 0,
        "minor": 1
    },
    "hints": [
        {
            "widgets":{},
            "images":{},
            "content":"0\n\n",
            "replace":false
        }
    ]
}
```

It seems as if that server may not have been updated with the latest content? That Perseus file was created (and last updated) on July 5.
