### ISSUE TITLE
PDF reader with a more graceful message?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1803]
## Summary

During testing with UNICEF, the following has come up:

> I tried to see the content of the lessons. When I choose one of them then a message came up, that the inline browser of the app cannot open pdf file (see attached photo). If I understood correctly that means that the app cannot open pdf file.

![image](https://user-images.githubusercontent.com/374612/27934424-fc9bbd40-62a5-11e7-8f4c-0485921e568e.png)

Since it's a tablet, it won't be optimal to have the student navigate to a separate application to view the PDF.

Does a solution exist to guide the user to enable inline PDF viewing?

If not, please feel free to close this issue. I actually think the text is pretty okay as it is tbh.

Otherwise the text could say "please download the PDF and open it with an external application for displaying PDFs. In case you have one installed already, it may open up when you click this link:"

**Comment by christianmemije** [comment]
We currently use [PDFObject](https://pdfobject.com/) to embed PDFs. The api does allow us to change the fallback text that is displayed via the `fallbackLink` option. 

Another solution would be to make use of [PDFJS](https://github.com/mozilla/pdf.js/)

**Comment by benjaoming** [comment]
@christianmemije nice that the fallback text can be specified, I think that's better than adding such a heavy dependency, possibly carrying a load of new issues.
