### ISSUE TITLE
Appbar search field breaks when zooming out

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#1806]
## Summary

Appbar search field breaks when zooming out to certain percentages

## System information

Kolibri 

 - Version: 0.5.3
 - Operating system: MacOS
 - Browser: Chrome

## How to reproduce

1. Run Kolibri
1. Locate an exercise or any page within Learn
1. Zoom out of browser to 33%, 67%, 80% or 90% zoom percentage

## Screenshots

<img width="1168" alt="screen shot 2017-07-07 at 12 58 11 pm" src="https://user-images.githubusercontent.com/25045166/27977377-4ef7a3f0-631f-11e7-8cfe-ed27f50ed949.png">

**Comment by christianmemije** [comment]
Fixed in #1825
