### ISSUE TITLE
Wrong string for local export

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1809]
## Summary

When exporting to local drive, the message `Importing from curation server` is displayed, instead of what should correctly say `Exporting to local drive`. Operation seems to finishes correctly, just displays the wrong message.

## System information

 - Version: [`0.4.0-446-gd1737c5`](https://github.com/learningequality/kolibri/pull/1805)
 - Operating system: Windows 7
 - Browser: Chrome

## How to reproduce

1. Import channel
1. Try to export to local drive
1. Observe the message above the progress bar

## Screenshots

![win7 start running - oracle vm virtualbox_327](https://user-images.githubusercontent.com/1457929/27994333-059a3300-64bc-11e7-832a-3f1af1618db5.png)

**Comment by jonboiser** [comment]
@radinamatic The PR in #1805 targets version 0.5, but the artifact versions are labeled 0.4. Is that just a convention for artifacts?

In any case, the Task API is returning the value "localimport", when it used to be "localexport". When the task API returns that value, the UI shows the "Importing from Curation Server" message.

Here's the line with a comment from @aronasorman 

https://github.com/learningequality/kolibri/blob/release-v0.5.x/kolibri/tasks/api.py#L34

@aronasorman Are there any plans to change this. As it stands, there's no way to distinguish between the different kinds of task to inform the UI.

**Comment by radinamatic** [comment]
@jonboiser 

> The PR in #1805 targets version 0.5, but the artifact versions are labeled 0.4. Is that just a convention for artifacts?

As per @rtibbles 's words, there's an issue with the naming, untagged build artifacts get named wrong

Thanks for investigating this, it does seem that we need to introduce the correct tasks for the [strings](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/manage-content-page/task-status.vue#L36) to display correctly.
 
@aronasorman ^^

**Comment by indirectlylit** [comment]
I'm seeing the inverse issue while testing #1840: performed a web-based import, but seeing:

![image](https://user-images.githubusercontent.com/2367265/28759478-d2ecb246-7552-11e7-895b-6316dc09ab0d.png)

**Comment by ivanistheone** [comment]
Not sure if this is directly related, but might be good to fix at the same time.
All Task progress reporting is use `TASKTYPE = "remoteimport"`: 
https://github.com/learningequality/kolibri/blob/develop/kolibri/tasks/api.py#L31

**Comment by rtibbles** [comment]
Fixed in #2003
