### ISSUE TITLE
Content recommendation sub-section reordering

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1817]
## Summary

A long-needed change. Thanks to @laurenlichtman for bringing it up.

**Current order of the content recommendation subsections:**

1. Most popular
2. Next steps
3. Resume
4. Overview (to be renamed)

**Proposed reordering:**

1. Resume
2. Next steps
3. Most popular
4. Overview (to be renamed)

**Justification:**
Presenting "Resume" followed by "Next steps" is more in line with supporting a personalized learning experience. The Learner would see content that is most related to what they were most recently engaging with first, without needing to scroll or click through a labyrinth of topics.

Please write comments providing further justifications for either ordering, as there is not consensus in the team for the proposed reordering.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.5.0beta1.dev33
 - Operating system: MacOS Sierra
 - Browser: Chrome

**Comment by navakk9** [comment]
I am on board with the proposed reordering.

**Comment by lauradanforth** [comment]
Same. I hesitate to bring up the word 'Explore' again but I think it might be fitting for that Overview section?

**Comment by jtamiace** [comment]
_explore flashback intensifies_

**Comment by khangmach** [comment]
+1 for the proposed ordering
I think right now, the word overview is super ambiguous. Overview of what exactly? "Explore" is also ambiguous, but I like that is has a more random context: "explore some of this content we have lying around for you". 

I think I wouldn't be hesitant to expand overview into..."overview of _[channel name]_"

**Comment by jtamiace** [comment]
^ Ah yes, would also like to flag the following context for imps team:

On the dev side, it will now be possible to mix content from different channels onto the same "Recommended" page, eliminating the need for the Channel switcher in the app bar. 

"Overview or [Channel]" or "Featured in [Channel]" or something is a nice start of doing away with the ambiguity.

**Comment by lauradanforth** [comment]
I'm imagining it from the perspective of what a student might be used to seeing in a textbook, which is that the overview would typically come first. It's like a preview of everything you're going to learn about...so putting this section last (which I like) doesn't fit with the word Overview in my head. 

I like 'featured in' as an option though.

**Comment by rtibbles** [comment]
I support @jtamiace's proposed ordering, as it prioritises the sections in order of our best guess about what a student should or might want to engage with next. 

"Overview" is a fallback of last resort when we have no other information and say @#*& it, maybe this will do. 

That said, "Featured in..." is a good name. 

A big no to explore and any other verb based names that by their existence imply their opposition to or distinctiveness from the primary Learn.

**Comment by jtamiace** [comment]
Cool, so in the direction of:

1. Resume
2. Next steps
3. Most popular
4. Featured in Channel X
5. Featured in Channel Y
6. (Until all channels are featured??)

@navakk9 could you elaborate on reasoning for putting popular before "featured/overview?" With the possibility of there being many Channels on a device, I would suggest putting "Most popular" before these "Featured in." 

Also, if we do decide to break out these new sections by Channel, we need to think about navigation and where the "View more" leads to. To me, it does not make sense for it to go to the "View more" page as it is currently implemented, but instead to the first level of topics in that Channel in "Topics." Thoughts?

**Comment by rtibbles** [comment]
Sounds like it will be 'view channel' rather than 'view more' in that case.

**Comment by indirectlylit** [comment]
> Sounds like it will be 'view channel' rather than 'view more' in that case.

Note that in the current design, each of these sub-pages is a vignette or glimpse into the sections. There is no pagination or organization as occurs in the topic tree.

**Comment by navakk9** [comment]
@jtamiace - I am ok with the proposed reordering if most popular is always from an in classroom context with all students in the same grade in one classroom. Otherwise,  I think that it depends on the learning context. If the context is a multigrade classroom, I would not want most popular to be before overview because every student is not in the same grade in the same classroom. If it is in a community center context, again most popular might not reflect what is needed for the learner, because there will be varying age levels and learning pathways.

**Comment by rtibbles** [comment]
How about 'Most popular (with users like you)'?

**Comment by DXCanas** [comment]
> most popular is always from an in classroom context with all students in the same grade in one classroom
@rtibbles Is this currently the case? Should i stick with the current naming scheme or update it?

It looks like we want: 
1. "Most Popular" -> "'Most popular (with users like you)"
2. "Overview" -> "Featured in Channel X"

Does that sounds right?

Also, I know that a lot of the talks above were targeting multi-channel recommendations, but I don't think that exists yet. 

Going to move forward with the order described [here](https://github.com/learningequality/kolibri/issues/1817#issuecomment-314506550), wher "Featured in Channel X" will only say "Featured in `Curren Channel Name`. Objections?

**Comment by rtibbles** [comment]
Most popular is currently aggregated across all users, so we would have to do some algorithmic improvements in order to have the update to 'like you'.

**Comment by jtamiace** [comment]
"Most popular (with users like you)" also seems a little verbose... is the case that @navakk9 described enough justification to reorder "Featured in [Channelname]" to display before "Most popular" then, but without the (with users like you) add on?

Given the MVP state of the algorithms, I'm not too partial on either ordering, just as long as "Resume "and "Next Steps" are placed above the two.

**Comment by rtibbles** [comment]
An initial modification to this has been made in #1866 - leaving open because it appears there may be further iteration required.

**Comment by indirectlylit** [comment]
closing this issue - let's file additional specific issues for specific iterations if necessary
