### ISSUE TITLE
On recommended tab: arrow icon placement is correct, but they're pointing at the wrong place

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#1849]
![img_1101](https://user-images.githubusercontent.com/191955/28186126-d0ae069c-67ce-11e7-8ee2-d03716449b83.jpg)

Clicking the left arrow goes forward, which is what I expected. Ditto for the right arrow. However, they're pointing on opposite sides, which is wrong as per RTL guidelines.

**Comment by rtibbles** [comment]
Superseded by #1875
