### ISSUE TITLE
RTL: Exercise progress moves right, should move left

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#1850]
## Summary

Checks and X's are still moving right on exercise performance

## System information

RTL Demo Server

 - Operating system: Mac OSX
 - Browser: Chrome

## How to reproduce

Complete an exercise question and click next question

## Screenshots

![image](https://user-images.githubusercontent.com/22602993/28187002-f90bf0d8-67d1-11e7-80a1-e8acf898c4f5.png)

**Comment by christianmemije** [comment]
Fixed in #2746
