### ISSUE TITLE
Responsive Element RTL issue

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1851]
## Summary

* The Responsive Element mixin does not appear to be updating width when RTL.

![resize](https://user-images.githubusercontent.com/7193975/28187943-403afc30-67d5-11e7-9c21-3a155664c276.gif)

**Comment by indirectlylit** [comment]
I wonder if this might be related to https://github.com/marcj/css-element-queries/issues/171

**Comment by christianmemije** [comment]
I was looking into this and I think it might be due to the `scrollLeft` values when in RTL mode 

> Note that if the element's direction of the element is rtl (right-to-left) then scrollLeft is 0 when the scrollbar is at its rightmost position (at start of the scrolled content) and then increasingly negative as you scroll towards the end of the content.

https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft

**Comment by rtibbles** [comment]
Fixed in #2733
