### ISSUE TITLE
Adding space between "[#]Learner(s)" and "[#] Selected" on Groups page

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1853]
## Summary

The fields for "[#]Learner(s)" and "[#] Selected" need an additional space between them - they're too close together. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version:  0.5.0beta2.dev1
 - Operating system: Windows 10
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. View groups page and add a learner to a group.

## Screenshots

![screencapture-127-0-0-1-8080-coach-1499838135636](https://user-images.githubusercontent.com/25990164/28188361-e5456a70-67ef-11e7-98cf-96bf7721f157.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Visually unappealing and potentially confusing. Not critical.

**Comment by rtibbles** [comment]
Fixed in #1864
