### ISSUE TITLE
add RTL helper for inline SVGs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1855]
Many of our inline SVGs need to be flipped based on the `isRtl` status.

For example, sign in: 
![image](https://user-images.githubusercontent.com/2367265/28189221-f7dea036-67d9-11e7-8084-8ca0985ce3c7.png)

Note that [not all icons get flipped](https://material.io/guidelines/usability/bidirectionality.html). For example, Search does not: 
![image](https://user-images.githubusercontent.com/2367265/28189197-dbcd51d0-67d9-11e7-9aa1-be36ec00ef7e.png)

This could possibly be implemented using CSS: https://codepen.io/MarcoCP/pen/zowbMa

**Comment by indirectlylit** [comment]
Fairly low priority. removing milestone

**Comment by christianmemije** [comment]
Fixed in  #2702
