### ISSUE TITLE
Broken checkboxes under groups

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#1856]
## Summary

Checkboxes for moving learners between groups are not working. Inconsistent behavior. Sometimes they check, sometimes they don't. Check all box always works.

## System information

 - Version: 0.5.0beta3
 - Operating system: OSX
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

No output from console.

## How to reproduce

1. Create learners and put in class.
2. Log into coach and go to groups.
3. Try to use checkboxes to move learners.

## Screenshots

![jul-13-2017 15-00-34](https://user-images.githubusercontent.com/6361732/28189758-385ae532-67dc-11e7-96ae-a8b201180295.gif)

**Comment by rtibbles** [comment]
Fixed in #1864
