### ISSUE TITLE
In class list, names are misaligned with "Full name" column header

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1857]
## Screenshots

![image](https://user-images.githubusercontent.com/618416/28189915-2c394680-67dd-11e7-8c8a-13fa1c4f9c88.png)

## System information

*Please specify the Kolibri version you were using*

 - Version: develop (0.6?)

## Real-life consequences

OCD-triggered seizures.

**Comment by jamalex** [comment]
Also happens in RTL (it's from the padding in the row cell):

![image](https://user-images.githubusercontent.com/618416/28190609-9afc5b0e-67e0-11e7-87ec-c6df1346ff3e.png)

**Comment by rtibbles** [comment]
Fixed in #1871
