### ISSUE TITLE
Cropped Login Page

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1868]
## Summary

After some updates to core-base, login page crops horizontally: 
![corebasecropped](https://user-images.githubusercontent.com/9877852/28390005-299e701c-6c8d-11e7-8e7c-4059818cf7b3.png)

Narrowed down to `a1d8d47ad9646e9a0b99b8e88cc796bc9c08549e`

Reason it happened, from Richard
> It's because the handling of the document title switching is handled in core-base
￼￼￼So, previously, the login page had no proper page title

**Comment by rtibbles** [comment]
This was fixed in #1973.
