### ISSUE TITLE
Carousel needs to be RTL compatible

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1875]
## Summary

Carousel still goes from left to right, carousel navigation buttons point right for more, rather than left.

**Comment by indirectlylit** [comment]
@DXCanas you're actively working on this, correct?

**Comment by DXCanas** [comment]
yup! ^ Been writing tests, currently working on the implementation

**Comment by indirectlylit** [comment]
see follow-up issue: #2785
