### ISSUE TITLE
At onboarding, non-latin usernames fail validation 

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1876]
## Summary

When creating a user account, non-western usernames will fail validation.

**Comment by jonboiser** [comment]
The regex `/^\w+$/g` that validates user name relies on the `\w` character class, which is `[A-Za-z0-9_]`.

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/setup_wizard/assets/src/views/index.vue#L157

If Unicode were supported, one could use language classes to rewrite like `/^[\p{L}0-9_]$/g`

https://regex101.com/r/dM0kM5/5

But it's not, so probably need to provide a regex that blacklists certain characters. Ostensibly, the original regex was intended to blacklist whitespace and all punctuation. If so, could write something like `/[^\s{punctuation}$]/g`

**Comment by rtibbles** [comment]
Yeah, unfortunately that property of unicode regex can't be transpiled either (at least by this transpiler: https://mothereff.in/regexpu).

Agree with using a black list, rather than a whitelist. Could you tackle this @jonboiser?

**Comment by rtibbles** [comment]
Fixed in #2071 and #2154
