### ISSUE TITLE
Cannot log in with simplified log in for usernames over 3 characters

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1881]
## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.5.0beta4.dev22
 - Operating system: MacOS Sierra
 - Browser: Chrome

## How to reproduce

1. Activate simplified login 
2. Log out
3. Log in with a username that is more than 3 characters long

## Screenshots

<img width="1037" alt="screen shot 2017-07-20 at 3 01 43 pm" src="https://user-images.githubusercontent.com/6668144/28440927-349ed332-6d5d-11e7-9187-212bb0888c06.png">

**Comment by jtamiace** [comment]
```
default_frontend-0.5.0beta4.dev22.js:13 TypeError: Cannot read property 'length' of undefined
    at a.setSuggestionTerm (user_module-0.5.0beta4.dev22.js:formatted:2669)
    at a.n [as setSuggestionTerm] (default_frontend-0.5.0beta4.dev22.js:13)
    at ro.run (default_frontend-0.5.0beta4.dev22.js:14)
    at Tt (default_frontend-0.5.0beta4.dev22.js:13)
    at Array.<anonymous> (default_frontend-0.5.0beta4.dev22.js:14)
    at t (default_frontend-0.5.0beta4.dev22.js:14)
    at <anonymous>
```

**Comment by radinamatic** [comment]
No errors on fist pass @rtibbles, just following @jtamiace 's steps: Learner with 5 digits username logs in successfully without password, console doesn't complain.

Any other condition to test here?

**Comment by rtibbles** [comment]
That's it - wanted to specifically replicate on @jtamiace's machine as well, because I was never able to replicate on my local machine.
