### ISSUE TITLE
In content cards, and content pages, content titles and descriptions in LTR text are set as RTL direction

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1886]
## Summary

Text is right aligned and displayed as English text in an RTL context on content cards, breadcrumbs, and also descriptions in content pages:

![image](https://user-images.githubusercontent.com/1680573/28480726-dd04d3be-6e16-11e7-99da-a8ddab51b26f.png)

Should look more like this (have only changed "Adding and Subtracting Fractions" on the content cards):

![image](https://user-images.githubusercontent.com/1680573/28480826-53a38b6e-6e17-11e7-85aa-4606c44d8578.png)

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Develop
 - Operating system: Linux
 - Browser: Chrome

**Comment by christianmemije** [comment]
@rtibbles This would also apply to content page titles? And descriptions?

**Comment by rtibbles** [comment]
Yes - any text that is language specific for the content item itself.

**Comment by rtibbles** [comment]
(note, that we may still want the overall alignment of the divs to be RTL - so the title might still be to the right, but the internal, container element that has the text in it should have its `dir` attribute set by the language of the content item).
