### ISSUE TITLE
wording on facility settings is incorrect

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1890]
phrasing "Allow users to edit ...":

![image](https://user-images.githubusercontent.com/2367265/28535457-5a251fc2-7059-11e7-92e8-433c6aa0d2f9.png)

Incorrect for admins, who can always edit this info (including their own):

![image](https://user-images.githubusercontent.com/2367265/28535515-82be53ea-7059-11e7-9939-5e296e1bac44.png)

We should clarify the facility settings, as e.g. "Allow learners and coaches to edit ..."

**Comment by rtibbles** [comment]
Punting to 0.6.0 because strings.

**Comment by indirectlylit** [comment]
This should be addressed during some of the device & facility permissions re-work (cc @jtamiace)
