### ISSUE TITLE
videos in fullscreen on Android app don't switch device orientation 

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1893]
Noticed on Android 7

When viewing fullscreen of a video in portrait setting, it doesn't automatically turn to landscape. It's only a smaller video at the top.

1. Login as Learner
2. View piece of video content in profile
3. Press full screen
4. Switch to landscape

**Comment by indirectlylit** [comment]
Not a blocker for 0.5

**Comment by DXCanas** [comment]
Are we talking about Kolibri in an android browser, or the android app?

**Comment by indirectlylit** [comment]
good question! I don't actually recall where I got this information from; my guess it was reported during a hack session.

would you mind testing both?

**Comment by DXCanas** [comment]
well, for the android app, the current implementation for fullscreen on Android is a workaround - currently, we have no means of accessing information about the device within the app, including accelerometer info. 

We can apply this change globally, so that the entire app listens to the orientation of the device. This would mean that any page of the app would respond to orientation, which I think a lot of the team was opposed to?

Resolving this issue would involve a lot more work.

On an android browser, I'm having a hard time even loading a video, which is odd. Looking into that right now.

**Comment by DXCanas** [comment]
Tested on browser, works as expected, device orientation and all. I think the issue may have been written for the android app, in which case I think it'd take a while to get taken care of. Thoughts, @indirectlylit?

**Comment by indirectlylit** [comment]
> We can apply this change globally, so that the entire app listens to the orientation of the device. This would mean that any page of the app would respond to orientation, which I think a lot of the team was opposed to?

Could you elaborate? Not sure I understand the implications

**Comment by DXCanas** [comment]
> Could you elaborate?

essentially, it'll behave just like the browser does on the web version - the entire thing will rotate. This would break the current implementation of fullscreen, as it simply puts the player on `width/height:100%` and rotates the player 90 degrees. Rotating would then put the video in fullscreen "portrait mode" -- essentially, in no case would the video ever be in the correct orientation.

Assuming we fix this, I think enabling rotation also means removing "fullscreen", so the status bar on top would also be visible. This would have another benefit of enabling the keyboard to "squish" the display up to prevent the scroll/keyboard behaviour we see now.

**Comment by DXCanas** [comment]
Not seeing this in browser or in app. See app screenshots below: 
![screenshot_20170920-170855](https://user-images.githubusercontent.com/9877852/30673300-df47a27e-9e26-11e7-84b0-361dbe1ae73a.png)
![screenshot_20170920-170849](https://user-images.githubusercontent.com/9877852/30673299-df478762-9e26-11e7-9679-44aa740d7a82.png)

**Comment by DXCanas** [comment]
Might've been a system-level orientation lock? I'd like to close for now and reopen if anyone else sees this issue?
