### ISSUE TITLE
downloading usage data doesn't work on android

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1894]
Reported during 0.5.x bug bash, on Android 7:

Unable to export usage data (detail or summary logs) as Device Owner or Facility Admin.

1. Have learner generate data
2. Login as facility admin/device owner
3. Try to download logs

Nothing happens when clicking the button.

**Comment by indirectlylit** [comment]
Looks like this might be the same issue as https://github.com/learningequality/kolibri/issues/1894

**Comment by indirectlylit** [comment]
> Looks like this might be the same issue as #1894

That is of course true. What I meant though was: looks the same as #1974

**Comment by jonboiser** [comment]
@christianmemije can you see if #2179 (fixing noop callback for submit button) fixes this?

**Comment by DXCanas** [comment]
Works alright in the android browser, testing on android app

**Comment by DXCanas** [comment]
Confirmed broken on android app, for the same reason Jamie mentioned in https://github.com/learningequality/kolibri/issues/1974#issue-249419523

We can sniff, as @christianmemije mentioned to hide the button, the same way we did in #1974? @indirectlylit

**Comment by indirectlylit** [comment]
@DXCanas yes that's what I was trying to do in #2068

**Comment by DXCanas** [comment]
@indirectlylit :man_facepalming: on it
