### ISSUE TITLE
Audio player just looks like a broken video when there's no thumbnail

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1905]
## Summary

e.g. https://kolibridemo.learningequality.org/learn/#/a9b25ac9814742c883ce1b0579448337/recommended/1af3cc273f8344aab44e7a793df34cfd

Perhaps we can put a placeholder image in there, with an audio/speaker on it, to make it clearer, when there's no thumbnail?

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.5.0beta4
 - Operating system: all
 - Browser: all

## Screenshots

![image](https://user-images.githubusercontent.com/618416/28644476-9860c2bc-720e-11e7-8853-5ab7b05e9119.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Learner thinking the video is broken, when it's really just an audio file.

**Comment by khangmach** [comment]
![audio placeholders](https://user-images.githubusercontent.com/25045166/29098990-2a796a94-7c57-11e7-85e9-e0af1834ee71.png)

Here are some quick placeholder options:

**Comment by rtibbles** [comment]
Fixed in #2103
