### ISSUE TITLE
Unwrapped string

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1906]
## Summary

* Unwrapped `ungrouped` string
* https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/groups-page/move-learners-modal.vue#L20

**Comment by jonboiser** [comment]
This has been fixed 
```
    <div v-if="!isUngrouped">
      <hr>
      <k-radio-button
        radiovalue="ungrouped"
        :label="$tr('ungrouped')"
        v-model="groupSelected"
      />
    </div>
```
