### ISSUE TITLE
show Kolibri IP and port in the web UI

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1910]
During a discussion about native desktop apps and installers, it came up that administrators can often use an easy way to get the current IP and port through the web UI (e.g. Manage -> Device?). 

This would be particularly helpful for users that don't use the terminal, e.g. windows users running the tray application.

see related issue #1595

cc @jtamiace would need design

**Comment by jtamiace** [comment]
Approved in the design room on Slack.

Solution is to add another "Info" tab in Device with the IP, port, and other useful metadata about the device. 

Note for the implementor: if any items are difficult to access through python, skip for now. Priority is getting the URL to show correctly

![device info tab](https://user-images.githubusercontent.com/6668144/31973754-8310217c-b8dc-11e7-8a2e-3452386685a6.png)

**Comment by indirectlylit** [comment]
note from @jamalex:

> We can get all of that from Python except device name/id (unless we use the "instance id" from Morango, which might actually be good, noting however that it can sometimes change), and probably memory usage. In the disk space section, I guess we would just show the free space in the content folder, specifically. Perhaps put that in a section next to the path to the content folder.

**Comment by rtibbles** [comment]
Taking on the backend portion of this. Will create an API endpoint that exposes the information listed in the mockup above.

**Comment by rtibbles** [comment]
Note that we can only display a database path if the server is using SQLite (which will normally be the case, but we do support other DB backends).

**Comment by rtibbles** [comment]
Note to @jamalex: `platform.node()` seems to work to return a device name.

**Comment by rtibbles** [comment]
We could get free memory, but it would require us to add the `psutil` library which we have had significant issues with previously.
