### ISSUE TITLE
Unable to install apk on Android 4.2.2 - Python error

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1912]
## Summary

Trying to install the latest apk on Android 4.2.2, and getting a Python error. 

## System information

 - Version: v0.5.0-beta4
 - Operating system: Samsung GT-S7580; Android version 4.2.2

## Screenshots

![android4 2 2-img_20170727_174453336](https://user-images.githubusercontent.com/1457929/28680053-72151828-72f5-11e7-9871-af48a3f43532.jpg)

**Comment by indirectlylit** [comment]
closing given all the recent changes to the android apk. let's re-open new issues as necessary

cc @DXCanas
