### ISSUE TITLE
<Tabs> component currently hides some items on mobile

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1914]
# Summary

Currently, narrow displays obscure items on the <Tabs> Component. This has been pointed out by @laurenlichtman, @jamalex, and UNICEF.

Currently, overflow allows scroll, which isn't ideal. Apart from that, the affordance isn't clear - the scroll bar is invisible on most mobile devices.

@laurenlichtman made mentions of an indicator to show that there's more to see. Maybe even a button that would scroll the nav.

## Screenshots (Photocreds to @laurenlichtman) 

![starting to scroll](https://user-images.githubusercontent.com/9877852/28682666-969a46d4-72b2-11e7-8107-9e00a98bc3f0.png)
![still and unclear that there are more items](https://user-images.githubusercontent.com/9877852/28682675-9d23c91c-72b2-11e7-9580-a77e273302d3.png)
![landscape](https://user-images.githubusercontent.com/9877852/28682676-a433aa38-72b2-11e7-837a-65d3afc51166.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Users don't know all the options available to them in management, and other potentially long subnavs

**Comment by DXCanas** [comment]
@rtibbles Any idea what milestone this should fall under?

**Comment by DXCanas** [comment]
@laurenlichtman Feel free to add anything! I'll change anything in the description too, if you think it's necessary.

**Comment by rtibbles** [comment]
0.5.0 would be preferable, as we are trying to have an Android version for it. But could triage for later if it is a big ask.

**Comment by DXCanas** [comment]
Setting to 0.5.0 for now, @christianmemije update if you think this is out of scope?

**Comment by laurenlichtman** [comment]
As @DXCanas mentioned, without changing to landscape, it's not clear that you can see all of the icons when uploading content on a smaller screen device.

**Comment by christianmemije** [comment]
Yes, ideally there would be some pagination as seen here: https://material.angularjs.org/latest/demo/tabs#dynamic-tabs

@khangmach @jtamiace

**Comment by jtamiace** [comment]
I think that pagination is a nice solution if we really want to preserve the tab design on mobile. If we go this route, I'd suggest that the tab container span 100% width of the browser window instead of maintaining the same margins as the body container.

An alternative redesign could be to have a dropdown that contains a list of the tab options.

**Comment by indirectlylit** [comment]
Another possibility I'd mentioned in #1892 is to have sub-sections shown under the main nav bar for the currently top-level section:

![image](https://user-images.githubusercontent.com/2367265/28684067-e4536414-72b7-11e7-8982-89600852c5de.png)

**Comment by rtibbles** [comment]
I think this is probably a better long term solution. It increases the available space on the page, as the sub nav is hidden in the nav, and would also help to address the issue we have of Titleception (#1838). May not be possible as a short term fix as would require adding an API for the nav bar, but I think this is the better and Material solution.

**Comment by jtamiace** [comment]
Having subnav appear in the drawer works too, maybe the best solution for **mobile**. 

I would still suggest having tabs for tablet/desktop, especially for learn and coach. Easier to toggle between, as the subnav tabs in learn and coach are a little more related/intertwined in functionality than manage.

**Comment by rtibbles** [comment]
Punting to 0.6.0, as management on phones is not a high priority.
