### ISSUE TITLE
import/export modal briefly closes between steps 

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1924]
seen while testing #1840

The delay is inconsistent, and is sometimes much longer. I believe that turning on network throttling sometimes helps see the issue.

![gifmakerproject15](https://user-images.githubusercontent.com/2367265/28759603-35ac062e-7554-11e7-8514-e00ff3c619ae.gif)

**Comment by jonboiser** [comment]
One solution might be to refactor how the modal works on this screen. Currently, modals are interpolated via `component`

```
<component is="currentModal">
```

Where `someModal` is a function of `pageName`.

To have more control over transitions, invert the hierarchy

```
# <ManageContentModal />
<core-modal>
     <component is="currentMenu" />
</core-modal>
```

And provide some transition state for the `currentMenu` variable.

**Comment by indirectlylit** [comment]
Let's take a look at this during work on granular import/export
