### ISSUE TITLE
Make "make dist" more robust

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1931]
## Summary

These are issues and suggestions from building and releasing 0.4.4 on PyPi:

Since the build environment is going to invoke a runtime kolibri environment (which is not really ideal, but at this point hard to fix), we should ensure that we don't build on unclean environments. This has the potential to mess up static assets (mixing in things from from different versions).

 - [ ] Ensure running in a virtualenv?
 - [ ] Create and activate a new virtualenv?
 - [ ] Use a unique, temp KOLIBRI_HOME
 - [x] Uploads should happen with twine
 - [ ] Consolidate Make routines across all branches, so we don't slip up if we do releases in old branches
 - [x] Remove the zipped sdist, new PyPi says `HTTPError: 400 Client Error: Only one sdist may be uploaded per release.`

Notice that it's **NOT** an advantage to have completely clean build systems if they are very slow.

**Comment by rtibbles** [comment]
@benjaoming I am wondering if it might be possible/desirable to decouple our build from the runtime environment - this would involve no longer using enabled plugins as the basis for which assets we build, but rather have an explicit list of which plugins we build (in development mode, we could default back to the old behaviour).

**Comment by benjaoming** [comment]
@rtibbles - you are right, we do enable a couple of external things while building, we could perhaps create some minimal settings file `kolibri.deployment.buildchain`

**Comment by rtibbles** [comment]
Yeah, that might be a good way to approach it. I think it probably also ties into the other conversation that is ongoing about how we configure the currently enabled plugins (i.e. not adding them to `INSTALLED_APPS` but listing them elsewhere).

**Comment by rtibbles** [comment]
Most of these issues have now been addressed. Any extant concerns with our package building should open new issues.
