### ISSUE TITLE
alternate 'exam visibility' handling for classes with no groups?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1935]
For classes with no groups, the 'visible to' UI is a bit confusing:

----

![image](https://user-images.githubusercontent.com/2367265/28894083-8c0305f0-7788-11e7-9e12-5411ec7d8ed6.png)

----

![image](https://user-images.githubusercontent.com/2367265/28894074-859f723e-7788-11e7-9427-376cfd14f446.png)

----

The user is presented with an empty dropdown and a single radio button. It might be good to add some special-case informational text for users that are unfamiliar with groups.

**Comment by khangmach** [comment]
For first pass, if there are no groups in that class, I would opt to remove that change button completely or place it in a disabled state. Activatable when a group is created

**Comment by indirectlylit** [comment]
If there are no groups, maybe the entire 'Visible to' column should be hidden then? Otherwise they're all just going to say 'Entire class'.

**Comment by rtibbles** [comment]
I think maintaining the visibility of the column highlights that the potential to assign it to something other than the entire class is available.

**Comment by khangmach** [comment]
Yeah, agreed with Richard. I don't think the entire column saying "entire class" is that huge of an issue. It would still look like a standard table column data type and I think the benefits of having that text displayed and acknowledged, even when there aren't groups, outweighs hiding it completely.

**Comment by indirectlylit** [comment]
I'm kind of torn.

I would definitely agree with this if groups were a more important feature. However for all we know, most coaches may never use or want to use groups, in which case "visible to" just adds noise.

**Comment by khangmach** [comment]
that's true. Perhaps we can nest a "change visibility" option within the actions dropdown, and have the default visibility state be "entire class" once the exam is created?

**Comment by rtibbles** [comment]
I am not sure on what basis we are downgrading the status of groups though - from the feedback from Nalanda, they use groups very frequently to subdivide classes. Granted, we may hear in the future that this is not universally the case, but I think we should not assume groups are not used frequently until we hear or see that is the case.

**Comment by khangmach** [comment]
agreeing with what Richard said above..I would disable until groups are created
