### ISSUE TITLE
Implement simple Selenium tests built using Selenium Builder

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1951]
## Summary

Create integration tests only using Selenium builder to improve maintainability.

Only run on a time trigger, not every PR to prevent flakiness from impacting dev progress.

**Comment by jonboiser** [comment]
To help this process, it might be good to look at buttons and links and assess how easy it is to select them (e.g. using CSS). Using Selenium Builder, the Hamburger icon could only be targeted using xpath.

On the login page, the two inputs are indistinguishable, so it gets the username input using CSS, and then the password input using xpath to go from `#password` down to the input.

**Comment by jonboiser** [comment]
Added to the list of [backburner issues](https://github.com/learningequality/kolibri/discussions/7806)
