### ISSUE TITLE
Improve robustness of current frontend unit test setup

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1952]
## Summary

- [ ] Running full suite on watch mode throws errors after first run
- [ ] In watch mode, tests seem to be run twice after refresh. (the report shows up twice, where the first repeats the previous state, and the second run is the state when file was saved).
- [x] vue-intl throws warnings, and does not translate complex strings in a useful way
- [ ] some async tests are swallowing errors. are these test failures or intentional?
- [ ] stack traces have weird line/col numbers
- [ ] test coverage report
- [ ] snapshot testing support
- [ ] Use an assertion library that supports diffs

**Comment by jonboiser** [comment]
Here are some benchmarks on different Vue test set-ups.

https://github.com/eddyerburgh/vue-unit-test-perf-comparison (Karma-Mocha is on the slower end)

It might be possible to simplify the test runner to only Mocha+JSDOM instead of using Karma+Headless Chrome.

**Comment by rtibbles** [comment]
Yeah, for unit tests, using Headless Chrome is probably unnecessary.

The choice of karma + mocha was made by me, based purely on familiarity.

**Comment by rtibbles** [comment]
Have done some preliminary implementation of this. My impression so far is that it doesn't *seem* much faster, but haven't done any proper testing. Also it will only be a fair test when I get all of the tests passing!

**Comment by rtibbles** [comment]
Haven't got all of the tests passing with mocha-webpack+jsdom here, but at the moment (with 23 failing) it is taking about 4 minutes to run a full test suite on my machine, compared with 40s using our current setup.

**Comment by rtibbles** [comment]
I think this has been handled with the switch to jest.
