### ISSUE TITLE
Move kolibri/ to src/

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1953]
## Summary

Be like the cool kids?

@benjaoming please elucidate more clearly the motivations for doing this here.

**Comment by benjaoming** [comment]
The rationale is here:

https://blog.ionelmc.ro/2014/05/25/python-packaging/

But it comes with another big suggestion: To move all tests to their own `tests/` hierarchy.

I could write a lot of stuff here, but I rather agree with the blog, and I think it says it quite well. I've had good experiences with this structure.

But but but... I feel a bit like this is very disruptive and quite a lot of work. So we have to figure out a way to schedule it if it's ever going to happen.

**Comment by rtibbles** [comment]
We still haven't done this, so I'm going to say we're not going to. Django appears to have stuck with the same sort of project structure for us up to version 4, so I'm going to say what's OK for Django is OK for us.
