### ISSUE TITLE
Edit/delete/reset user modals do not wait for positive or negative response from server

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1960]
## Summary

User management modals do not wait for the request to complete before closing

**Comment by rtibbles** [comment]
@DXCanas @indirectlylit can you confirm if this is still the case? If not, please close.

**Comment by DXCanas** [comment]
Looks like it's happening on user create: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/user-page/user-create-modal.vue#L169

[But I'm not seeing it in any of the edit functions.](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/user-page/user-edit-modal.vue)

I'm thinking we have add some data to the pageState and have the action edit that. Then the view  listens to the pageState property and updates accordingly. Thoughts, @indirectlylit @rtibbles ?

**Comment by rtibbles** [comment]
Seems reasonable.

**Comment by indirectlylit** [comment]
I don't think this is a high priority - certainly not for 0.5

**Comment by christianmemije** [comment]
Should have been fixed in #2154
