### ISSUE TITLE
Hide download button in Android app WebView

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1974]
In the Android app, downloading files from the content page isn't currently supported, as webviews don't have built-in filepicker functionality. There are ways we could add that eventually, but it's also not a critical function for the standalone Android app, so at least for now, just hiding the button when we detect it's inside a webview would be best.

**Comment by jamalex** [comment]
@christianmemije Do you think this might be easy to do, in a similar vein to the fullscreen hack?

**Comment by christianmemije** [comment]
An option is to sniff the user agent to see whether it is currently in a webview. Self-assigning this issue.

**Comment by christianmemije** [comment]
https://developer.chrome.com/multidevice/user-agent#webview_user_agent

**Comment by christianmemije** [comment]
RIght idea https://github.com/uupaa/UserAgent.js/blob/master/lib/UserAgent.js#L345

**Comment by rtibbles** [comment]
Fixed in #1975
