### ISSUE TITLE
making a link look like a button and button look like a link

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1987]
![image](https://user-images.githubusercontent.com/2367265/29235129-0fe4d52c-7eb1-11e7-89a9-f4eebe42d7a0.png)

Currently on the sign-in page, we wrap `<k-button>` in `<router-link>`:

```html
<router-link v-if="canSignUp" class="group-btn" :to="signUp">
  <k-button :text="$tr('createAccount')" :primary="false"/>
</router-link>
```

resulting in a link containing a button:

```html
<a data-v-2598daee="" href="#/create_account" class="group-btn">
  <button data-v-2e2b028a="" data-v-2598daee="" type="button" class="k-button k-button-secondary-raised">
    Create account
  </button>
</a>
```

One of the effects is that as you tab through with the keyboard, both the link and the button get focus in turn.

----

Note that in the [original style guide doc](https://docs.google.com/document/d/1HqbqIUxU0DriHXtKZag0AzeN8URDbDZzsSbc3zbdmag/edit?), we'd decided that from a user's perspective "links" and "buttons" can be used interchangeably. The difference is mainly an implementation detail.

![image](https://user-images.githubusercontent.com/2367265/29235174-7f7bc8f0-7eb1-11e7-8056-6fca3c0021f6.png)

I believe the best long-term change might involve:

* Change the `raised` prop on buttons to be `style`, and take a string that is one of `"raised"`, `"flat"`, or `"link"`. This will allow `<k-button>`s to be styled as links.
* Rename the style guide page "Buttons" to "Buttons and Links"
* Create a new component `<k-link>` which would be a wrapper around `<router-link>`. It would take similar props to `<k-button>`, in particular `text`, `primary`, ~`raised`~ `style`, and `disabled`. It would also include a new prop, `to`, which would be a proxy to the `<router-link>`. It would  _not_ include `type`, which is button-specific. Open question of whether it would emit a `click` event?

After this, we would look for instances of `<router-link>` and update them to use `<k-link style="link">`

Of course, an alternative strategy is to stick with a single `<k-button>` component which will render as a `<a>` instead of `<button>` if a `to` prop is passed. This might be elegant also too - I don't have a strong lean one way or the other.

------

cc @christianmemije

**Comment by DXCanas** [comment]
> Of course, an alternative strategy is to stick with a single <k-button> component which will render as a <a> instead of <button> if a to prop is passed. This might be elegant also too - I don't have a strong lean one way or the other.

This approach sounds really clean to me

**Comment by indirectlylit** [comment]
@DXCanas I tried the API both ways, and decided to create three independent components. It became apparent that three small sets of required props is a simpler API than one large group of optional props.

Under the hood they all share styling logic of course.
