### ISSUE TITLE
app bar zoomed view improvements

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1989]
## Summary

Implement the variable height app bar depending on screen breakpoints (this should be a part of the Material Spec), in order to mitigate some of issues when Kolibri is viewed on high zoom (200%)

## Context

[Trello Card](https://trello.com/c/fRJMlKPm/171-a11y-zoom-up-to-200)

## Screenshots

![intro to addition - khan academy en - kolibri - google chrome_454](https://user-images.githubusercontent.com/1457929/29284258-3b8cc86c-812a-11e7-8bd7-6b9909b0eb86.png)

![create new exam - kolibri - google chrome_466](https://user-images.githubusercontent.com/1457929/29284272-46834976-812a-11e7-8a01-4d29935b7f83.png)

**Comment by indirectlylit** [comment]
thanks for the report

We already implement some dynamic sizing of the app bar per Material spec, but we are missing the smallest height (48px).

@radinamatic would you mind filing an independent issue for the exam preview feedback? Seems unrelated to app bars and zoom.

**Comment by indirectlylit** [comment]
this is ameliorated to a degree because the app bar scrolls off-screen now
