### ISSUE TITLE
worker-loader has unmet peer dependency

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#1990]
## Summary
* On Develop.
* run `yarn`
* `warning "worker-loader@0.8.1" has unmet peer dependency "webpack@>=0.9 <2 || ^2.1.0-beta || ^2.2.0".`

**Comment by jonboiser** [comment]
This is happening in the context of the 'document_pdf_render' plugin, since there's no webpack in that folder's package.json

Adding webpack@^2.2.0 to that plugin's package.json gets rid of the warning.

**Comment by rtibbles** [comment]
Hrm, would rather not do that though, because then we end up installing webpack unnecessarily. I'll add this issue to the build system project.

**Comment by rtibbles** [comment]
(note that the warning here is artifactual, and a result of how we nest our dependencies, and not something that is indicative of an issue that will affect the build)
