### ISSUE TITLE
Optimize Travis and Tox build matrix

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#1999]
## Summary

Currently the `licence` tox env is failing often because of a Google Chrome download that stalls (perhaps Google is blocking it during parallel builds?). But we don't need this in our build, so should investigate if the Travis addon can be cached or downloaded+installed only once.

**Comment by rtibbles** [comment]
One possibility here would be to deprecate our use of tox by shifting from Travis to Circle, where we could use a matrix of different docker files instead of a tox driven matrix. Lots of possibilities to explore.

**Comment by benjaoming** [comment]
> use a matrix of different docker files instead of a tox driven matrix

Tox is really quick and supports caching of downloaded packages between environments. We can really optimize this part in a way that I would just assume knocks Docker out of the competition. Or did you have other benefits in mind?

As for Travis vs. Circle, that's a different discussion - we could see if the Travis slowness continues, but I really love their UI.

**Comment by benjaoming** [comment]
Closing this, I haven't seen Chrome failing for a while, and I'll open another tox-related issue now :)
