### ISSUE TITLE
<High>The videos are not loading on a server updated from 0.4.5 to 0.5.0beta8.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2008]
## Summary
The videos are not loading and we ar getting the error "Kolibri is unable to render this content"
Note:
This sever is being used at the Learning centre here in Pune. We will be testing/using the latest and stable pex file. We would be raising issues and and when we find it.
Also I reimported one of the channels and fund the issue not resolved.  

**Following are the Channels in the server and videos don't load on all theses channels:**
8fc515793aad4e52b490b03c48ad21de
797ff4dfe6fd473e91b68cfb8ec3a44e
095baa553e1547c19be273e96f591ff9
3f6e54734f45445bb3e597a408e95202
197934f144305350b5820c7c4dd8e194

## System information
 - Version: Kolibri 0.5.0beta8
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chome

## How to reproduce
1. Upgrade the server from 0.4.5 to 0.5.0beta8
2. The videos that were working will not load anymore.

## Screenshots
![screenshot from 2017-08-22 18_14_04](https://user-images.githubusercontent.com/13453618/29575340-c96dfda6-8781-11e7-9c5e-fd7ec52f4907.png)
![screenshot from 2017-08-22 21_27_00](https://user-images.githubusercontent.com/13453618/29575342-c9c93216-8781-11e7-8832-9fc75e421823.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)
For Nalanda's context the updation from 0.4.5 to any future releases will be a biggest challenge.

**Comment by rtibbles** [comment]
Hi @harishbalachandran a little surprised that this is happening, as we had explicitly included a fix to prevent this from happening, but we can investigate further.

Can you detail exactly how you did the update process?

**Comment by harishbalachandran** [comment]
We always run the platform using the command sudo ./Kolibri-version.pex start. 

In this case I deleted the older version 0.4.5 and used the latest pex file and ran sudo ./Kolibri-0.5.0beta8.pex start

**Comment by rtibbles** [comment]
OK, we'll test and try to replicate. Thanks!

**Comment by lyw07** [comment]
Here is the kolibri_settings.json file after replicating this issue:

`{
  "AUTO_SEARCH_PLUGINS": [], 
  "FIRST_RUN": false, 
  "INSTALLED_APPS": [
    "kolibri.plugins.management", 
    "kolibri.plugins.learn", 
    "kolibri.plugins.document_pdf_render", 
    "kolibri.plugins.html5_app_renderer", 
    "kolibri.plugins.setup_wizard", 
    "kolibri.plugins.coach", 
    "kolibri.plugins.user", 
    "kolibri_exercise_perseus_plugin"
  ]
}`

**Comment by rtibbles** [comment]
@benjaoming after investigation by @lyw07, it looks like while we are getting rid of the old video and audio renderer plugins, we are not adding the new content renderer plugin to upgrading installations.

Would you have time to make a quick PR to tackle this on 0.5.x?

**Comment by rtibbles** [comment]
Fixed in #2013
