### ISSUE TITLE
The coach report shows incorrect data on version 0.5.0beta8

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2009]
## Summary
The class progress shows 6/24 completed, but on navigating to check the students who have completed , I notice that fewer kids have only completed under the recent tab.

Note:
This is the same server that was updated from 0.4.5 to 0.5.x. This is across all the channels and not specific to any channel.

## System information
 - Version: 0.5.0beta8
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. As few users master an exercise.
2. Look for the class progress from recent tabs.

## Screenshots
![coach reprot_1](https://user-images.githubusercontent.com/13453618/29614177-dc706cfe-8826-11e7-9e40-adb89a4cf587.png)
![caoch report 2](https://user-images.githubusercontent.com/13453618/29614202-f501dece-8826-11e7-9c84-e8dff816d364.png)
![coach report_3](https://user-images.githubusercontent.com/13453618/29614211-fd03eedc-8826-11e7-8d0a-64a314eefda4.png)
![coach report_4](https://user-images.githubusercontent.com/13453618/29614216-feab0ac2-8826-11e7-804b-7b491e5d1106.png)

**Comment by rtibbles** [comment]
Thanks for doing these checks, @harishbalachandran! Seems like perhaps our recency filter is not filtering properly on the aggregate page, but is doing so when generating reports for individuals?

How does the report for pieces of content (6/24 watch) compare to looking at the same piece of content under 'Topics'? If it is the same, then I think it confirms my supposition.

**Comment by rtibbles** [comment]
Woops, did not mean to close!

**Comment by rtibbles** [comment]
Replicated locally. Investigating.

**Comment by rtibbles** [comment]
Fixed in #2014
