### ISSUE TITLE
Last update date is incorrectly populated and shows same time stamp for all the available channels.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2011]
## Summary
Last update date is incorrectly populated and shows same time stamp for all the available channels.
I had updated only one of the channel and the same time stamp is populated across all other channels on the same server.

## System information
 - Version: 0.5.0beta8
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. Update one of the channel.
2. Notice the same time stamp is populate for the channels that are not updated.

## Screenshots
I had updated the Maharashtra State English channel only in the below screen shot:
![channel update](https://user-images.githubusercontent.com/13453618/29614697-cdd9be00-8828-11e7-9df1-ffacc9cd7911.png)

**Comment by rtibbles** [comment]
This seems related to #1664 - will punt to 0.6.x for similar reasons.

**Comment by rtibbles** [comment]
Fixed in #1947
