### ISSUE TITLE
Enable explicit disabling of default plugins

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2019]
## Summary

In latest changes in #2013, we re-enable default plugins at a version change.

This could be annoying for users who have explicitly disabled a plugin for a reason, so it would be helpful to explicitly blacklist a default plugin to protect against this behaviour.

Additionally, as suggested in #17 let's migrate from `json` to `ini`

**Comment by indirectlylit** [comment]
related conversations in #2510 and #2626

**Comment by rtibbles** [comment]
Not sure this is critical, as the default plugin list for custom builds will be set specifically for those custom builds.

**Comment by indirectlylit** [comment]
fixed in https://github.com/learningequality/kolibri/pull/5637
