### ISSUE TITLE
Upgrade to Vuex3

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2022]
## Summary

Vuex3 will allow better and more modular Vuex state management.

**Comment by jonboiser** [comment]
One thing we can start doing now that won't break anything is move functions in `options.vuex.getters` to `options.computed` and `options.vuex.actions` to `options.methods`, like in this [diff](https://github.com/jonboiser/kolibri/commit/9206d77f789dbae23e517b7fbee605f915b6c8d8)

**Comment by rtibbles** [comment]
Do we want to have mapGetters as a universal helper function that we can then swap out for the vuex mapGetters function?

**Comment by jonboiser** [comment]
Yeah, that's why I named them so similarly. It wouldn't be an exact swap though.

pre vuex3
```js
      ...mapGetters({
        isAdmin,
        isCoach,
        classCoaches,
        isSuperuser,
        className,
      }),

```

vuex 3 (assuming these getters are defined on your store/module
```js
      ...mapGetters([
        'isAdmin',
        'isCoach',
        'classCoaches',
        'isSuperuser',
        'className',
      ]),

```
```

**Comment by indirectlylit** [comment]
@jonboiser please close this issue once your final introduction of modules for page state has been merged
