### ISSUE TITLE
Device owner can sign in without password?

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2038]
## Summary

* Device owner can sign in without password?

## System information

 - Version: Develop

## How to reproduce

1. Enable `Allow users to sign in with no password"
2. Sign out.
3. Sign in using device owner username.
4. Magic

## Example

![wut](https://user-images.githubusercontent.com/7193975/29793665-97d3f648-8bf9-11e7-9452-c82842bd0a48.gif)

## Real-life consequences

* Deadly

**Comment by rtibbles** [comment]
Looks like I forgot the part where the DeviceOwner becomes a facility admin. Whoops!
