### ISSUE TITLE
Make Content Metadata Import process happen within a transaction

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2041]
## Summary

Following the merge of #1947, content metadata is imported into the main database, for now, this involves deleting all existing content metadata for a channel, which, if done during active classroom use would result in a disjointed user experience for active learners.

In order to avoid this, it would be better for the deletion and import to happen within a single transaction, so that it is committed all at once, can be cancelled/rolled back without issue, and just generally doesn't mess things about!

**Comment by indirectlylit** [comment]
done

**Comment by rtibbles** [comment]
Wait, where was this done?

**Comment by indirectlylit** [comment]
whoops - thought it was done in 1947

**Comment by rtibbles** [comment]
No, this was made because of #1947!
