### ISSUE TITLE
Broken js navigation in 0.5.0beta10

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#2044]
## Summary

Something strange is going on with the js router. It get stuck the first content item navigated to and subsequently shows that item even if you click on something else.

## How to reproduce

  - Go to http://35.185.88.71/learn/#/053653a2a7fa436a8b3991115db18d25/recommended
  - Click on first item (Henna for me)
  - Press browser back button
  - Click on second item (Map for me)

I expected the Map content item to be loaded, but I see the Henna content loading again, so it seems like the js routing logic is "stuck" on the first item clicked on after page load.

Command+clicking navigates fine (opens in new tab).

## System information

This is latest beta (`0.5.0beta10`) and I can reproduce in FF and Chrome.

**Comment by rtibbles** [comment]
@indirectlylit I think we just found your winning argument.

**Comment by harishbalachandran** [comment]
@ivanistheone , Thanks for already catching this! Very strange.

@rtibbles impacts quite a lot. 

Adding a recording of this issue, no way i could have taken screen prints to explain this issue :) 
[Navigation error.zip](https://github.com/learningequality/kolibri/files/1260850/Navigation.error.zip)

**Comment by christianmemije** [comment]
Fixed in #2045
