### ISSUE TITLE
Groups page without any groups

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2046]
## Summary

* Currently, if there are no groups created, ungrouped users can still be selected but no action can be performed. Looking for a mockup for this scenario.

![whattodo](https://user-images.githubusercontent.com/7193975/29833922-f2fa758a-8ca1-11e7-9b42-8d60131fb9f7.gif)

**Comment by jtamiace** [comment]
I don't think the mocks specify anything about this scenario... 
A few options:

1. Add a "move learners" button in a disabled state, checkboxes enabled
2. Add a "move learners" button in a disabled state, checkboxes disabled
3. Add a "move learners" button in active state, checkboxes enabled, prompt "new group" modal with appropriate supporting text 

I think having everything disabled would make more sense though

**Comment by khangmach** [comment]
I would go with option 2 as a quick fix, so that we present moving users around as a supported function here.

**Comment by indirectlylit** [comment]
see related issue: https://github.com/learningequality/kolibri/issues/1935
