### ISSUE TITLE
Add filters to learner exam page

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2053]
## Summary

By status, by class.

https://projects.invisionapp.com/share/ZTA3FH2S2#/screens/244157121

**Comment by MauHernandez** [comment]
@rtibbles I have a doubt, which status should exams have here? for learners the unactive exams are not visible unless they are finished which only shows the final score, so... status by:
- Active
- Inactive
- All

Doesn't have much sense here. Which status should we be looking for? Maybe "In progress", "not started" ???

**Comment by MauHernandez** [comment]
Also, "By Class" I think doesn't make much sense either, since according to "http://kolibri.readthedocs.io/en/develop/learn.html" the learners don't add themselves to any class so they are not aware of to which class they belong.

**Comment by indirectlylit** [comment]
cc @khangmach would you mind helping resolve design questions on this issue?

Is there any chance some of this work is outdated after recent work in Lessons and new Exam designs?

**Comment by khangmach** [comment]
@indirectlylit 
All issues are resolved in the latest prototype found here: https://invis.io/5VE5OYB8N
Apologies for the confusion, I'll look to update design wiki with the latest prototypes..

To reiterate @MauHernandez 's points above, some of the latest thoughts:
- Scoping exams and assignments by class is addressed in the prototype. No filter needed
- No need for an exam status filter, as the only two options would be "all" and "active". I'm also not convinced learners need the status filter at the moment -- the amount of exams teacher curate don't merit this.

**Comment by indirectlylit** [comment]
thanks. Closing this issue
