### ISSUE TITLE
error: Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2057]
Devs often get this error after running `yarn install`:

```
        Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x
        
        Found bindings for the following environments:
          - OS X 64-bit with Node.js 7.x
```

It is addressed by running:

```
npm rebuild node-sass
```

However, it's time-consuming for devs:
* it can take some time between starting the devserver and the error to show up
* it's not obvious what the solution is (though it's now [documented](https://github.com/learningequality/kolibri/pull/2054/files))

One interesting clue: I only started encountering this issue since downgrading from Node 7 to Node 6. (We're using Node 6 because it's the LTS version, and there might be some issues in Node 7 with webpack dependencies?)

**Comment by christianmemije** [comment]
New version of node-sass with node 9 support: https://github.com/sass/node-sass/releases. Plus Node 8.9 just became a LTS version

**Comment by EmanekaT** [comment]
I found the explanation [here ](https://github.com/sass/node-sass/issues/1585)
This seems only happen when you switch Node version, and there should have already been an error message saying "npm rebuild node-sass".

**Comment by rtibbles** [comment]
I think this should be prevented by our aggressive node version restriction.
