### ISSUE TITLE
can no longer sign in using a pre-existing superuser account after upgrade

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2061]
It appears that my superuser account is no longer available since upgrading to the latest develop. 

I would have expected it to get migrated to an admin account with superuser flags enabled.

It actually looks like the user might still be there:

![image](https://user-images.githubusercontent.com/2367265/29852726-81f2b1b4-8cf0-11e7-9b0a-adb9fb0cb264.png)

**Comment by rtibbles** [comment]
Yeah, replicated this issue. Guessing the password setting during migration is not working as expected.

**Comment by rtibbles** [comment]
Actually - that doesn't seem to be the issue, as I can still login through the Django admin login with this user without problems. Will investigate further.

**Comment by rtibbles** [comment]
It seems like the wrong facility id is being assigned to the superuser. Not happy, not happy at all.

**Comment by rtibbles** [comment]
Can confirm that this happens if there are any other collections with a 'lower' id than the facility. It seems that inside the Django data migration the differences between Proxy Models are not recognized, and so it just grabs the first Collection, rather than the first Facility.

**Comment by indirectlylit** [comment]
fixed!
