### ISSUE TITLE
locked-up server with excess logging during import

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2066]
Starting from a fresh checkout of current `develop` and no `.kolibri` folder, I followed these steps:

* create admin super user
* start importing KA English (`913efe9f14c65cb1b23402f21f056e99`)
* clicked 'Learn'

At this point, the browser just hanged, as though the server was not responding. Looking at the server console, it seemed to be logging an exorbitant amount of SQL Alchemy debug info of various kinds. A lot looked like this:

```
FROM content_localfile 
WHERE content_localfile.id = ?
INFO:sqlalchemy.engine.base.Engine:SELECT content_localfile.id AS content_localfile_id, content_localfile.extension AS content_localfile_extension, content_localfile.available AS content_localfile_available, content_localfile.file_size AS content_localfile_file_size 
FROM content_localfile 
WHERE content_localfile.id = ?
2017-08-30 13:03:12,712 INFO sqlalchemy.engine.base.Engine (u'309fe0bc3aa9588f34125a572c45cd6e',)
INFO:sqlalchemy.engine.base.Engine:(u'309fe0bc3aa9588f34125a572c45cd6e',)
2017-08-30 13:03:12,713 INFO sqlalchemy.engine.base.Engine SELECT content_localfile.id AS content_localfile_id, content_localfile.extension AS content_localfile_extension, content_localfile.available AS content_localfile_available, content_localfile.file_size AS content_localfile_file_size 
FROM content_localfile 
WHERE content_localfile.id = ?
INFO:sqlalchemy.engine.base.Engine:SELECT content_localfile.id AS content_localfile_id, content_localfile.extension AS content_localfile_extension, content_localfile.available AS content_localfile_available, content_localfile.file_size AS content_localfile_file_size 
FROM content_localfile 
WHERE content_localfile.id = ?
2017-08-30 13:03:12,713 INFO sqlalchemy.engine.base.Engine (u'6014477c88ae234d13c541a1fe4109d0',)
INFO:sqlalchemy.engine.base.Engine:(u'6014477c88ae234d13c541a1fe4109d0',)
2017-08-30 13:03:12,715 INFO sqlalchemy.engine.base.Engine SELECT content_localfile.id AS content_localfile_id, content_localfile.extension AS content_localfile_extension, content_localfile.available AS content_localfile_available, content_localfile.file_size AS content_localfile_file_size 
FROM content_localfile 
WHERE content_localfile.id = ?
INFO:sqlalchemy.engine.base.Engine:SELECT content_localfile.id AS content_localfile_id, content_localfile.extension AS content_localfile_extension, content_localfile.available AS content_localfile_available, content_localfile.file_size AS content_localfile_file_size 
FROM content_localfile 
WHERE content_localfile.id = ?
2017-08-30 13:03:12,715 INFO sqlalchemy.engine.base.Engine (u'3b2019a157dcd6b49239ae78eadeea6b',)
```

This went on for a couple minutes, during which time things felt broken from a user perspective even though it was clearly working very hard.

Eventually it stopped, the content started downloading, and I was able to interact with web UI again.

**Comment by rtibbles** [comment]
Yeah, this is where some progress tracking during content database import would be helpful. At the moment it is treated as a monolithic operation.

**Comment by indirectlylit** [comment]
The amount of logging may also have exacerbated the issue, at least on a dev server where Terminal needed to handle it.

**Comment by rtibbles** [comment]
Yeah, this level of logging also only happens with DEBUG=True.

That said, I can probably tone it down a little more :)

**Comment by indirectlylit** [comment]
The behavior seems to have improved slightly (no more locked-up browser).

Now however I see this state while the server is doing stuff related to 'Setting availability of ContentNode objects':

![image](https://user-images.githubusercontent.com/2367265/30298604-db3e7270-9700-11e7-954b-d972d78e4805.png)

It currently feels broken because the progress bar gets to 100% very quickly, and then it's in this state for at least 90% of the time it's working.

**Comment by rtibbles** [comment]
Yeah, this is where the progress tracking would be helpful.

Was the content already downloaded?

**Comment by indirectlylit** [comment]
yes I think it was downloaded at that point and just processing

**Comment by rtibbles** [comment]
But the majority of the content was not already downloaded, also?

**Comment by indirectlylit** [comment]
I'm not sure actually - had been deleting/redownloading a few times. I can try to do some more testing and get concrete steps to repro.

**Comment by rtibbles** [comment]
Yeah, mostly just interested in a rule of thumb ratio of time to download vs time to mark ContentNode availability.

**Comment by rtibbles** [comment]
(obviously, this will vary a lot, but just trying to come up with sensible heuristics)

**Comment by indirectlylit** [comment]
I'm no longer reproducing this issue as originally described
