### ISSUE TITLE
Unable to enroll users in a class

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#2073]
## Summary

Selected users to move, clicked 'Review & Save', then confirmation box appeared. Nothing happened after clicking 'Yes, Enroll Users'.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.5.0
 - Operating system: OSX
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

![image](https://user-images.githubusercontent.com/22602993/29900148-aad82c08-8da4-11e7-97d4-e48184b910c7.png)

## How to reproduce

Create a class and move users into it

## Screenshots

![image](https://user-images.githubusercontent.com/22602993/29900093-47f73606-8da4-11e7-99d8-37457072ee1f.png)

**Comment by rtibbles** [comment]
Interestingly, I failed to replicate this locally on Python3.

**Comment by rtibbles** [comment]
Nor on Python2.

**Comment by jonboiser** [comment]
@rtibbles @lauradanforth Could be related to #2163. I'll see if the same factors could be in play.

**Comment by jonboiser** [comment]
So, just to clarify, does "move" mean "enroll"? When I saw "move" I was thinking of something similar to the "move" feature for groups.

Anyway, I just confirmed that the same 'deleting stuff then trying to add them back breaks things' issue is at play here:

1. Add a user A to a class
2. Delete user A from class
3. Add user A to class
4. Attempt to delete user A from class
5. Get run time error stemming from `removeClassUser` action

As with the groups issue, I'm not sure when/how an associated API error comes up (e.g. the 400s in the screenshot), but I think that the server can be put in a bad state as a side effect of the above phenomenon.

**Comment by indirectlylit** [comment]
updated title - thanks

**Comment by christianmemije** [comment]
Currently. adding/removing users is done one at a time. That might be causing the database lock? Might be helpful to create an endpoint for bulk adding/removal?

**Comment by jonboiser** [comment]
Yeah enrolling multiple users in one request is probably how it should be done. Another hacky thing one can do is throttle the requests, so there's a brief pause between each request.

**Comment by jonboiser** [comment]
The fix in #2317 most likely fixes @lauradanforth 's original problem. Will create a new, more specific, issue about the batch enrollments.
