### ISSUE TITLE
exercise progress is not persisted in 0.6

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2075]
* make progress
* refresh
* lose progress

![gifmakerproject16_1](https://user-images.githubusercontent.com/2367265/29900645-ffe6a988-8da7-11e7-97b7-b4a20423946a.gif)

**Comment by indirectlylit** [comment]
I'm a guest

**Comment by rtibbles** [comment]
Maybe we should put it in local storage for guests, and then ask them to create an account later?

**Comment by indirectlylit** [comment]
That would be nice. Possibly a more critical scenario: I _do_ have an account and forget to log in. I make a bunch of progress because things "seem to work", but all is lost.
