### ISSUE TITLE
improve validation in wizard-import-network & user-edit-modal

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2076]
Validation needs to be improved.

**Comment by indirectlylit** [comment]
@christianmemije - could you elaborate on this issue?

I removed the 'form' part - addressed in #2118

**Comment by christianmemije** [comment]
These forms just needed improved validation. The wizard-import-network modal was addressed in #2118. The user-edit-modal is being addressed in #2154

**Comment by rtibbles** [comment]
Assuming this was fixed in #2154 - if not, please reopen @christianmemije
