### ISSUE TITLE
0.5 -> 0.6 causes breakage in Learn Topics

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2078]
## Summary

* 0.5 -> 0.6 causes breakage in Learn Topics
* Performed migrations 
```
http://127.0.0.1:8000/api/contentnode/bcd99d8aeef04ce6b9e25a88d87eedb7/ancestors/?1504215141699=1504215141699
http://127.0.0.1:8000/api/contentnode/bcd99d8aeef04ce6b9e25a88d87eedb7/?1504215141714=1504215141714
```
both return `{detail: "Not found."}`

**Comment by rtibbles** [comment]
Note: this happens if you just do importchannel, and not also importcontent.

Will update to prevent loading a channel for which there is zero availability.

**Comment by rtibbles** [comment]
Also, it will happen on upgrade, as I think the upgrade path is effectively just doing import channel, and not the necessary annotation.
