### ISSUE TITLE
Exams can be edited after being submitted

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2085]
## Summary
In Exam, after submitting the student can go back to the paper and make changes and submit again. His score changes by doing this.

## System information

Kolibri Version: Kolibri 0.4.5
Operating System : Ubuntu 14.04
Browser : Chrome

## How to reproduce

1. Assign exam to student
2. login with learner and start giving exam.
3. submit the exam and go to back to exam again by back button.
4. and start giving exam.
5. then submit the exam again now score will be changed.

## Screenshots

![1](https://user-images.githubusercontent.com/12776071/29963231-bb96fba2-8f23-11e7-9ef3-8a3515f30bdd.png)
![2](https://user-images.githubusercontent.com/12776071/29963271-db853136-8f23-11e7-906c-05bca98b02b9.png)
![3](https://user-images.githubusercontent.com/12776071/29963270-db84527a-8f23-11e7-9466-40cfaa3e5c2f.png)
![4](https://user-images.githubusercontent.com/12776071/29963273-db8bfef8-8f23-11e7-9266-62ea17f77c3d.png)
![5](https://user-images.githubusercontent.com/12776071/29963272-db856dcc-8f23-11e7-9736-10a36d82df99.png)
![6](https://user-images.githubusercontent.com/12776071/29963274-db915de4-8f23-11e7-8eaf-dd4b9ad2dcfa.png)

**Comment by navakk9** [comment]
@indirectlylit @rtibbles

**Comment by navakk9** [comment]
@rtibbles 
![screen shot 2017-09-26 at 3 13 15 pm](https://user-images.githubusercontent.com/26124065/30886858-9fd9ba9a-a2cd-11e7-81eb-38452f298e17.png)

**Comment by christianmemije** [comment]
Learners can revisit the exam URL and modify the answers to the questions they originally submitted. They cannot change the answers that were unanswered. 

So we need to prevent this on the back end api. For the front end, we can either prevent routing to the url of an already completed exam, show a `exam already submitted` text, or disable the submit exam button.

**Comment by rtibbles** [comment]
If you want to handle the frontend rerouting, @christianmemije, I can modify permissions on the backend.

**Comment by christianmemije** [comment]
Sounds :100: @rtibbles

**Comment by christianmemije** [comment]
Routing addressed in #2318

**Comment by rtibbles** [comment]
Fixed in #2318 and #2349

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.6beta1. Working fine.

![2085_1](https://user-images.githubusercontent.com/12776071/31373461-c2524368-adb7-11e7-8c2a-4b1bbf23b604.png)

![2085_2](https://user-images.githubusercontent.com/12776071/31373462-c2960670-adb7-11e7-9f70-2de3d6dcaf54.png)
![2085_3](https://user-images.githubusercontent.com/12776071/31373463-c2f45cd4-adb7-11e7-8ecf-e4faac8cfbab.png)

After pressing Back button:
![2085_4](https://user-images.githubusercontent.com/12776071/31373464-c3317754-adb7-11e7-8f11-58e0a56d2d01.png)
