### ISSUE TITLE
In Exam feature, instead of the Folders, stars are also coming with the same name as folders.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2086]
## Summary
In Exam feature, instead of the Folders, stars are also coming with the same name as folders. 

Detailed Description

- While creating exam there is a list of stars and folders with the name of Balbharati, Grades, Chapter Names, topics, etc. 
- The folder part seems good, but the star part is some bug which is showing up. Selecting the star part instead of the folder part shows an error that you have not selected exercises.
- See the video for further understanding.

## System information

Kolibri Version: Kolibri 0.4.5
Operating System : Ubuntu 14.04
Browser : Chrome

## Video
[VID-20170901-WA0004.mp4.zip](https://github.com/learningequality/kolibri/files/1269330/VID-20170901-WA0004.mp4.zip)

**Comment by christianmemije** [comment]
@swapnil106111 Can you please provide the channel id.

**Comment by swapnil106111** [comment]
@christianmemije star appears across channels. Channel Id 8fc515793aad4e52b490b03c48ad21de( Maharashtra state english channel). Above Channel used in schools.

**Comment by christianmemije** [comment]
@swapnil106111 Thank you. Issue was reproduced. Will look into it.

**Comment by christianmemije** [comment]
Replicated. But then the issue went away.

It appears that the api endpoint was not taking the `kind` param into account.
Sample url:

`http://127.0.0.1:8000/api/content/8b4d3e6d3d4842ba8ea658335b5dd252/contentnode/?parent=8e39cb56309745199ffb6b3e7a482d26&kind=exercise&fields=pk%2Ctitle%2Cassessmentmetadata&1506716496983=1506716496983`

Then it randomly started working. Any ideas @rtibbles ?

**Comment by christianmemije** [comment]
Can be fixed by restarting the python server.

**Comment by swapnil106111** [comment]
@rtibbles  Tested on Kolibri0.4.6beta1. Working fine.


![2086_1](https://user-images.githubusercontent.com/12776071/31373657-907e8738-adb8-11e7-8204-1fdb445bdeb0.png)
![2086_2](https://user-images.githubusercontent.com/12776071/31373658-90f1bc26-adb8-11e7-9cea-938be6f55b2e.png)
![2086_3](https://user-images.githubusercontent.com/12776071/31373659-915d1944-adb8-11e7-97d1-12507d9e54f0.png)
