### ISSUE TITLE
exercise is not completed even after solving enough questions correctly in a row

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2087]
## Summary

Level is not completed even after solving 4-5 questions correctly in a row.

## Detailed Description

- Level is not completed even after solving 4-5 questions correctly in a row.
- After a certain question, once you click on check answer tick comes ,Post that if you click  on next question same question and tick appear in a loop. The exercise shows still in progress.
- The problem is solved only when you refresh the page. It shows a green tick and next item after this.
- Not everyone but most of the learners facing this problem.

## System information

- Kolibri Version: Kolibri 0.4.5
- Operating System : Ubuntu 14.04
- Browser : Chrome

## How to reproduce

1. start giving exercise with learner login

## Video
[VID-20170809-WA0007.mp4.zip](https://github.com/learningequality/kolibri/files/1269360/VID-20170809-WA0007.mp4.zip)
[Error_Grade4.mp4.zip](https://github.com/learningequality/kolibri/files/1270056/Error_Grade4.mp4.zip)
[Error_Grade5.mp4.zip](https://github.com/learningequality/kolibri/files/1270055/Error_Grade5.mp4.zip)

**Comment by rtibbles** [comment]
Is this only on some exercises, or does this happen across many exercises?

**Comment by harishbalachandran** [comment]
@rtibbles this is across few exercises, and not across all.

**Comment by navakk9** [comment]
@indirectlylit - critical, and seems to tie in with other issues filed.  cc @rtibbles

**Comment by navakk9** [comment]
@rtibbles - this ties in with the pop up not showing up
