### ISSUE TITLE
The progress shown is 0 % completed, but when we click the name it shows the student has done all questions correct.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2088]
## Summary

In the Recent Coach Report feature, the progress shown is 0 % completed, but when we click the name it shows the student has done all questions correctly.

## Detailed Description

- In the recent coach report, we saw student named Shubham Yadav has 0% progress.
- After clicking on the name and looking at the tab of the student, both showed the student has solved all questions correctly and also moved to the next level.
- found above scenario in one class with two learner.

## System information

Kolibri Version: Kolibri 0.4.5
Browser: Chrome
Operating System : ubuntu 14.04

## How to reproduce

1. Create class scenario.
2. Start giving exercise and see the progress of each student in class 

## Screenshots

![img_20170823_130211](https://user-images.githubusercontent.com/12776071/29959005-0184e68a-8f13-11e7-8de2-3faf7f5ac6ec.jpg)

![img_20170823_130219](https://user-images.githubusercontent.com/12776071/29959006-0187de30-8f13-11e7-9fcc-01067cb560d9.jpg)

![img_20170823_130456](https://user-images.githubusercontent.com/12776071/29959007-018d7bf6-8f13-11e7-9a53-81a27f8e411f.jpg)

**Comment by rtibbles** [comment]
This is intended - because it is the 'recent' tab. Indicating that this progress was not completed in the last 7 days.

However, the UX of this could be improved. @jtamiace

**Comment by jtamiace** [comment]
Even more misleading is that Shubham's "Last activity" for the exercise is marked as 32 minutes ago

**Comment by harishbalachandran** [comment]
@jtamiace @rtibbles Thats right it seams to be a bug wherein it does not capture the progress at the topic level.

**Comment by indirectlylit** [comment]
possibly need to cherry-pick changes from https://github.com/learningequality/kolibri/pull/2014 ?

**Comment by benjaoming** [comment]
Supposing that #2370 was the fix for this - right?
