### ISSUE TITLE
detailed progress is sometimes missing under the 'Recent' coach report

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2089]
## Summary

In the Recent Coach Report feature, the progress of some students is shown in percentage but a detailed question wise report does not appear.

## Detailed Description

- In the recent coach report, we saw students named Akash Shah have progress reported as 100 percent complete.
- After clicking on the name and looking at the report of the student, a detailed report was not being displayed. (Look at the Video).

## System information

Kolibri Version: Kolibri 0.4.5
Operating System : Ubuntu 14.04
Browser : Chrome

## How to reproduce

1. Create class scanario.
2. Start giving exercise through learner login.

## Video
[VID-20170901-WA0001.mp4.zip](https://github.com/learningequality/kolibri/files/1269460/VID-20170901-WA0001.mp4.zip)

**Comment by rtibbles** [comment]
What had the student actually done with this exercise?

My guess would be that this is a logging error, where progress is being misattributed to the wrong content item.

**Comment by harishbalachandran** [comment]
@rtibbles , the child has mastered the exercise like always. And this occurs across few other classrooms.

**Comment by harishbalachandran** [comment]
@rtibbles todays observation, this again seams to be a major issue across classrooms thats needs attention.
[No Report.mp4.zip](https://github.com/learningequality/kolibri/files/1317689/No.Report.mp4.zip)

**Comment by navakk9** [comment]
@indirectlylit @rtibbles

**Comment by navakk9** [comment]
![coacherror1](https://user-images.githubusercontent.com/26124065/30886471-f502494e-a2cb-11e7-9b32-d6b329ad1389.png)
![coacherror2](https://user-images.githubusercontent.com/26124065/30886473-f5460b16-a2cb-11e7-9129-05edfc0f3b6d.png)
![coacherror3](https://user-images.githubusercontent.com/26124065/30886470-f4faaa0e-a2cb-11e7-8839-28bed72a9477.png)
![coacherror4](https://user-images.githubusercontent.com/26124065/30886469-f4faa428-a2cb-11e7-8df2-d1bc807b4ee4.png)
[Error.txt](https://github.com/learningequality/kolibri/files/1335141/Error.txt)

**Comment by rtibbles** [comment]
Now that's what I call traceback! This is only on tablets, right? Not on a laptop?

**Comment by navakk9** [comment]
I haven't been able to replicate it on the laptop.

**Comment by harishbalachandran** [comment]
@rtibbles, @navakk9 , The screen shot provided by Navya is not exactly the same issue reported here.
On the above the attempts are at-least shown but the real issue is that it does not show even the attempts.

Here is the screen shot of the actual issue:
![1](https://user-images.githubusercontent.com/13453618/30899828-30ada322-a37f-11e7-8333-1fb45cc6b857.jpeg)
![2](https://user-images.githubusercontent.com/13453618/30899829-3114f4d2-a37f-11e7-9b18-bb1767cc394e.jpeg)
![3](https://user-images.githubusercontent.com/13453618/30899831-31259e54-a37f-11e7-90be-ead319c7b5a3.jpeg)
![4](https://user-images.githubusercontent.com/13453618/30899830-311aefc2-a37f-11e7-96cd-21524627e7a7.jpeg)
![5](https://user-images.githubusercontent.com/13453618/30899832-3126d58a-a37f-11e7-9339-b469b67b842f.jpg)

**Comment by DXCanas** [comment]
Replicating. Seems like a logging error! @rtibbles I'm getting a `UNIQUE constraint failed: logger_masterylog.id` when on load, leading some some weird behaviour. Successful submissions appear to be reported, and I'll get the "checked" symbol, but there aren't any attempts or interactions for the user recorded. Happens on `http://localhost:8000/api/masterylog/?1506991954092=1506991954092`

Interestingly, if I paste that URL straight to the browser, i don't get the integrity error. That being the case, I'll message an HTML file with the error page I get as a response.

**Comment by DXCanas** [comment]
@harishbalachandran

I've been able to consistently duplicate this in only one scenario:

A student was logged into one tab of a browser session, working on an exercise. In a separate tab, the student is logged out, and a deviceowner signs in. If I switched back to the student tab and submitted an answer, logging information starts falling apart for this student.

Do you think it likely that there is any case where a deviceowner and a student might be signed into the same browser session?

I'll continue trying to reproduce, but this is the only way I've been able to replicate the issue so far.

**Comment by harishbalachandran** [comment]
@DXCanas Nope this use case is not possible, since the device owner/teacher have their own server laptop and the kids access through tablets specifically.

**Comment by DXCanas** [comment]
@harishbalachandran we were able to replicate in a few other ways, and the fix should have been pushed through in #2354!
