### ISSUE TITLE
unable to view questions in coach report

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2090]
## Summary
In the coach report, the teacher is unable to view the question itself.

After performing exercises by learner user, when coach user wants to see the progress of learner that time coach report does not show questions or  answer history is not shown in the coach report.

## System information
 - Version: kolibri 0.4.5
 - Operating system: Ubuntu 14.04 
 - Browser: Chrome

## How to reproduce

1. Login with admin.
2. Go to coach
3. Select class.
4. Goto Learner tab.
5. select student name.
6. select channel.
7. Go to topic.

## Screenshots

![whatsapp_image_2017-08-09_at_8 06 32_pm](https://user-images.githubusercontent.com/12776071/29962971-c71fc7a2-8f22-11e7-8935-5bc4b3483b66.jpeg)

**Comment by rtibbles** [comment]
Could you navigate to these questions again, and bring up the Developer Console, and copy any output there to here? It's possible these questions are erroring out.

**Comment by swapnil106111** [comment]
@rtibbles  this error does not occur always but still we told our team to take developer console screenshot whenever the error comes.

**Comment by harishbalachandran** [comment]
@rtibbles this seams to be same errors as #2089

**Comment by navakk9** [comment]
@rtibbles - this issue came up yesterday during the hack session too, but only on the mobiles and tablets.

**Comment by navakk9** [comment]
@indirectlylit

**Comment by rtibbles** [comment]
@navakk9 thanks - that's useful extra info, seems likely it is a browser compatibility issue that is getting hidden.

**Comment by navakk9** [comment]
@rtibbles - same as #2089 

![coacherror1](https://user-images.githubusercontent.com/26124065/30886507-201729ce-a2cc-11e7-8252-f7a6b2b65125.png)
![coacherror2](https://user-images.githubusercontent.com/26124065/30886509-202916ca-a2cc-11e7-8f79-81f5065402f3.png)
![coacherror3](https://user-images.githubusercontent.com/26124065/30886508-201d17bc-a2cc-11e7-8161-61f44fa7c502.png)
![coacherror4](https://user-images.githubusercontent.com/26124065/30886510-202e71c4-a2cc-11e7-94b3-a84cd85df6e3.png)
[Error.txt](https://github.com/learningequality/kolibri/files/1335143/Error.txt)

**Comment by harishbalachandran** [comment]
In this issue @swapnil106111 has removed other screenshot and kept the one that is specific to this, I will try to get more screenshot with console, because this issue should pop some kind of error on console.

**Comment by DXCanas** [comment]
I've only been able to replicate this screen while the content was loading, which sometimes takes a while :confused:. Never get an error, and the screen usually pops up. I haven't been able to replicate @navakk9's error at all, though

**Comment by harishbalachandran** [comment]
Will try to find the reason for this occurrence, which will help you to replicate it.

**Comment by rtibbles** [comment]
@harishbalachandran since posting, we have found another way to replicate this.

**Comment by rtibbles** [comment]
I think we have a fix lined up!

**Comment by rtibbles** [comment]
Oh, sorry, this was the wrong issue. Ignore my comments above...

**Comment by rtibbles** [comment]
Unable to replicate.
