### ISSUE TITLE
Content import from local drive shows error in windows system

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2091]
## Summary
Showing error while importing content from local drives in windows operating system. Showing same error when external drive  is connected and when external drive is not connected.

## System information

 - Version: Kolibri 0.5.0
 - Operating system: Windows 7 
 - Browser: Chrome

## How to reproduce

1. Login with device owner.
2. Go to manage tab.
3. Click on content.
4. Click on Import.
5. Click on local drive.

## Screenshots
![error - kolibri](https://user-images.githubusercontent.com/12776071/29966471-afdba6d0-8f2f-11e7-8c7b-e7d49f76fc2b.png)
![kolibri windows import error](https://user-images.githubusercontent.com/12776071/29966472-afe5802e-8f2f-11e7-8f8b-31d5318273b9.png)

**Comment by radinamatic** [comment]
Thank you for the report @swapnil106111!

We weren't able to reproduce this during our testing in virtual machines, and we'll have to investigate iton a physical Windows machine.

**Comment by indirectlylit** [comment]
import has changed a lot in 0.7. Let's re-open a new issue if it arises
