### ISSUE TITLE
Minimum browser support

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#21]
I'd like to concretize the browsers we're willing to support for Kolibri to the following:
- Internet Explorer 10+
- Firefox 35+
- Chrome 40+
- Android browser 4.2+
- iOS 6.0+
- Safari 5+
- ~~Opera~~ (latest ones use the same rendering engine as Chrome)

The versions given above are meant to be negotiated. But we need to commit to supporting certain versions soon as that will determine what external dependencies we'll be bundling in (see [Kolibri Frontend Architecture doc](https://trello.com/c/wlRWKYUe/13-front-end-architecture-high-level-concepts)).

To answer this realistically, we'll need to look at our most important partners and deployments, and see what technologies they're using. Here's a list of people we need to contact:
- FUNSEPA
- Nalanda
- WCH
- UNICEF
- Aflatoun
- ~~World Bank~~ (Premature to contact, according to Liz)
- {{ add more here @jamalex and @jeepurs }}

**Comment by MCGallaspy** [comment]
How difficult is it to support IE9?

**Comment by MCGallaspy** [comment]
Just to be clear, IE8 is the *latest* version available on Windows XP (and presumably Server 2003). But Windows 7 users *may* be running IE9. IE10 was released with Windows 8 and is available for Windows 7, but that's contingent on the user having upgraded.

**Comment by rtibbles** [comment]
I believe we settled on the above modified to include IE9?

**Comment by indirectlylit** [comment]
closing this issue - not quite the right forum. For posterity:

* we're currently supporting down to IE9, but we're looking at distributing a lightweight browser and discontinuing support
* other browsers we haven't been following concrete minimum version requirements, but it seems that we'll likely need to support Android browsers 4+
