### ISSUE TITLE
Media player is broken :crying-jordan:

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2101]
## Summary

* Language computed props need to be updated.
* Layout messed up somehow. 

## System information

 - Version: 0.6

## Screenshots

![127 0 0 1-8000-learn-](https://user-images.githubusercontent.com/7193975/29986266-86c9755a-8f17-11e7-93f8-3771ea27b7b9.png)

Why is everything broken?

**Comment by rtibbles** [comment]
Fixed in #2103 and #2105
