### ISSUE TITLE
Setup_wizard page failed to load on IE 11 for v0.6.x, showing 'kolibriGlobal' is undefined 

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2107]
## Summary

When using v0.6.0-alpha1 windows installer on win7 (32bit) with IE 11, the kolibri setup_wizard page only shows the kolibri logo. Using the IE 11 built-in debugger gives me two errors (posted below in screenshots section). 

**However, v0.5.0 release works fine on this IE 11.** 

I assume this is the same as the situation happened on Raspberry Pi 3's 3.8.2 epiphany browser, where v0.5.0 loads fine but v0.6.x doesn't work either. 

## System information

 - Version: v0.6.0-alpha1
 - Operating system: Win 7
 - Browser: IE 11

## How to reproduce

1. Use Win7 VM with IE 11
2. Download v0.6.0-alpha1's windows installer and install kolibri
3. Start and load the server
4. Use IE's built-in debugger

## Screenshots

![image](https://user-images.githubusercontent.com/19424916/29988971-14035820-8f25-11e7-9510-ff68cab6a18e.png)
![image](https://user-images.githubusercontent.com/19424916/29988980-1d421aac-8f25-11e7-86fd-f114ad762039.png)

**Comment by rtibbles** [comment]
Looks like we had duplicated properties in object definitions which threw IE11 off. Fixing.

**Comment by rtibbles** [comment]
Fixed in #2108 and https://github.com/learningequality/kolibri/commit/09b03bf3d02f57d2aa0701a2200d3a9012b34525#diff-9640266a0a98c13fcc415b64ecc7d7a4
