### ISSUE TITLE
0.4.x - capital letters trigger username validation error

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2110]
## Summary
I have "coach" named coach user in server but when I logins with small "coach" it logins without showing any error. When I login with capital "COACH" as a username it shows error "Incorrect username or password", but still i am able to login with capital "COACH" by putting correct password.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.5.0beta11
 - Operating system: Ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1. Create username with small case.
2. And login same username with capital case.

## Screenshots
![1](https://user-images.githubusercontent.com/12776071/30013054-cfc4c614-9161-11e7-9184-1f87e858bfb1.png)
![2](https://user-images.githubusercontent.com/12776071/30013053-cfc494c8-9161-11e7-8a00-fcdc341314ec.png)

**Comment by rtibbles** [comment]
This is intentional.

**Comment by rtibbles** [comment]
I assume the flagged issue here is that you can login with the username, regardless of whether it is in lower or upper case. This is intentional.

If there is another issue here, please explain further, and we can reopen!

**Comment by swapnil106111** [comment]
@rtibbles It is fine for small "coach" to get "Enter password" message. But when we enter capital "COACH" we get "Incorrect username or password", in this case the user will get confused whether he is writing correct username or incorrect username.

Hence, when a user is logging in with small "coach" or capital "COACH", the message should be "Enter password".

**Comment by rtibbles** [comment]
OK, understood! According to @indirectlylit this does not seem to be extant on 0.5.0, and I don't think this is sufficiently urgent for us to fix this on 0.4.

@indirectlylit please close if this is no longer extant on newer versions.

**Comment by indirectlylit** [comment]
* Confirmed that on 0.4.x a capitalized username will trigger an incorrect validation error:
* Confirmed that on 0.6.x this is no longer the case.

![image](https://user-images.githubusercontent.com/2367265/30934404-5bc24a1a-a382-11e7-8630-101197f40781.png)

Agreed that this is not critical for an 0.4 patch. Will update the title for posterity and close.

**Comment by indirectlylit** [comment]
fixed in 0.6

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri 0.9.0. It is working fine.
