### ISSUE TITLE
Don't let non-superusers reset passwords for superusers

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2115]
## Summary

We now have a special flag on users to indicate if they are superusers, however, they are also still facility users. This means that currently, a facility admin could reset the password of a superuser in order to gain access to the superuser privileges of this account.

**Comment by DXCanas** [comment]
It seems like the existing `isSuperuser` checks are still using `kind` - where's the flag you mentioned?

**Comment by rtibbles** [comment]
This flag is in the backend on the FacilityUser model, which has an `is_superuser` property.

**Comment by DXCanas** [comment]
Do you think hiding the "Edit" button sufficient?

**Comment by rtibbles** [comment]
Yeah, probably good to not let them edit anything about superusers. We should also change this on the backend to restrict the permission.

**Comment by indirectlylit** [comment]
I don't think this issue is quite accurate - it's conflating device permissions with facility permissions.

I agree that the whole thing is confusing, but password resets follow the admin/coach/learner permission hierarchy (which is distributed across devices)

**Comment by indirectlylit** [comment]
(I could well be wrong - this was just my first reaction)

**Comment by rtibbles** [comment]
Yes, although it has the unfortunate consequence of meaning that making someone a superuser then, in principle, gives superuser access to anyone who has admin access to this user. A facility admin who is super user can have their password edited by another, non superuser facility admin, which I think is undesirable. 

The fix I suggest does not fix a multiple device sync credential subversion scenario, but does stop this more elementary attack.

**Comment by christianmemije** [comment]
@rtibbles Can you edit the table below.

Edit = edit username, name, password, and delete.

Can edit -> ? | super admin | super coach | super learner | admin | coach | learner
--- | :---: | :---: | :---: | :---: | :---: | :---: 
super admin |   |   |   |  yes |  yes | yes
super coach |   |   |   |   |   | 
super learner |   |   |   |   |   |

**Comment by rtibbles** [comment]
It will be 'yesses' everywhere, I think, because superusers can edit anyone.

The issue is the other way table, that admins should not be able to change the password of super admin, super coach, or super learner.

**Comment by christianmemije** [comment]
So much power... Okay I added a new row for admins.

**Comment by rtibbles** [comment]
Yes - but restricted to this device! And I think the super-coach/learner use case is rare. Most of those use cases can be achieved with the more granular device permissions.

**Comment by christianmemije** [comment]
Addressed in https://github.com/learningequality/kolibri/pull/2288/commits/33c7be7cca14823107913f1b4acb4bbc19fd2ef1

**Comment by christianmemije** [comment]
Addressed in #2288
