### ISSUE TITLE
Channels that are deleted once remain 'deleted' as Model

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2128]
If, in a single session, you delete a Channel from the Content Management Page, that Channel and the Model associated with that GUID (which is static) is flagged as 'deleted' for the remainder of the session.

One consequence is that if you delete a channel on the content management UI, and then try to re-import it, it will not appear on the channel list after dismissing the 'success' notification.

## Steps
0. Delete all channels and restart server
1. Import channel(s) via any method
2. Delete those channels
3. Re-import the channels via any method
4. On dismissing success notification, expect to see channels appear below, but see no channels.
5. Channels will reappear if one refreshes browser.

## Analysis

The reason for this is that after the first time deleting the channels, the ChannelResource Model associated with that id is flagged as 'deleted'. 

So the next time `Collection.getCollection().fetch()` is called, it returns `Collection.data`, which filters on that `deleted` flag (i.e. the previously deleted, but re-imported Channels are filtered out).

(From log at http://github.com/jonboiser/kolibri/blob/ea1931c325926e3ff089e71791764eedb2b3a571/kolibri/core/assets/src/api-resource.js#L382)
**Before Delete**
![screen shot 2017-09-06 at 12 47 43 pm](https://user-images.githubusercontent.com/10248067/30131437-a57e7e3a-9301-11e7-97b1-6c212e13442c.png)

**After Delete**
![screen shot 2017-09-06 at 12 42 14 pm](https://user-images.githubusercontent.com/10248067/30131271-0286e8d4-9301-11e7-8477-aed491a19a08.png)

**Comment by rtibbles** [comment]
Hrm, should have the flag toggled off if you do a save, I suppose!

**Comment by jonboiser** [comment]
Technically, this still happens, but is a non-issue for Channels after #2153
