### ISSUE TITLE
Lower the likelyhood of accidentally clicking the Hint button

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2132]
## Summary
In the current scenario, the Hint Feature is just below the Space to enter the answer and space to fill answers appears very light in color. 
-Sometimes the students by mistake press the hint instead of the answer space.

**Some more actual user stories:**
As of now when students try to punch answer in the box, they inadvertently click on hint option, with somehow students don't get the point. In light of the fact if a student uses a hint option they will not get the point or consider it as a wrong answer, though students know the right answer. If this happened each time they would not go to the next exercise. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.5
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. Observe hint button and answer box.

## Screenshots
![hint1](https://user-images.githubusercontent.com/13453618/30149866-e647d4be-93c6-11e7-8407-bed6caf8991a.JPG)
![hint2](https://user-images.githubusercontent.com/13453618/30149867-e65bd964-93c6-11e7-9355-dfc35249ddb7.jpg)

**Comment by khangmach** [comment]
@christianmemije can we change the hint text to "Stuck? Use a hint (4 left)", make it a hyperlink instead of a button, and increase its top margin from the input box?

**Comment by christianmemije** [comment]
> make it a hyperlink

Why a hyperlink?

**Comment by indirectlylit** [comment]
My guess is to lower it in the visual hierarchy?

related: https://github.com/learningequality/kolibri/issues/1987

**Comment by christianmemije** [comment]
But link to what? @khangmach

**Comment by indirectlylit** [comment]
Sorry to keep jumping in - correct me if I'm wrong @khangmach  :)

But I think the intent is to keep the functionality the same as the current button. Clicking the "thing that looks like a link but is actually implemented as a button" will show the hint.

**Comment by khangmach** [comment]
@christianmemije to lower the hierarchy. Having it be a big button invites the problems Harish mentioned above. It wouldn't link to anything, would just reveal the hint.

**Comment by indirectlylit** [comment]
made a task for the short-term fix above --^

we can implement the full solution using this work: #2255

**Comment by harishbalachandran** [comment]
The space between the Hint and Input box seams to be reasonable.
