### ISSUE TITLE
selection dropdown component does not respond to standard keyboard input

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2134]
When it has keyboard focus, native selection dropdowns allow you to do things like:

* type the first character of an item to select it (whether or not the menu is open)
* use the arrow keys to change selection (whether or not the menu is open)
* press 'escape' to dismiss the menu

none of these work with our current selection box widget

![image](https://user-images.githubusercontent.com/2367265/30185994-99e5bde0-93d8-11e7-80a4-3339063e32ee.png)

**Comment by christianmemije** [comment]
Will be fixed in #2337

**Comment by christianmemije** [comment]
Fixed in #2337
