### ISSUE TITLE
Backup database before upgrades with migrations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2137]
## Summary

This issue is for further investigation and findings will be consolidated here, even if it's a *wontfix*.

Problem:

- Some of our migrations only have `forward()`, not `backward()`
- If there is an unknown bug in a release, we risk that installations are stuck in some new broken version.

Example: #2078

**Comment by benjaoming** [comment]
Point from @jamalex 
 * Counters from Morango could get messed up if backing up one database but not another?
 * Databases can accumulate a lot of user data, reports from KA Lite that databases are > 1 GB

**Comment by benjaoming** [comment]
While I don't like that we end up building our own structures for handling too much database stuff outside of frameworks (Kolibri is supposed to be database-agnostic, so there are few assumptions to be made), I think we can let us guide by solving problems for the general use case when it makes sense.

This is my conclusion of who we should target:

1. Users who run `kolibri start` from command line
1. Especially early releases of Kolibri where the kinds of problems that prompt a downgrade are essential.
1. Releases that contain data migrations: But let's try to avoid that?
1. Releases that contain other types migrations that are irreversible: We should totally prohibit that. Please let me know if there are any problems with this as a policy?

Some additional use case will remain uncovered:

1. Users of installers who have no command line interaction
1. Automated installers that upgrade Kolibri in the background (PPA distribution for instance) and then restart the service automatically

In case 1), we can argue that this user would not be able to install the database backup from command line anyways. In case 2) we can argue that the intention (extreme caution!) of the database upgrade isn't relevant, we cannot ship upgrades that need this level of caution.

Paradox of db-tracked migrations:

 * We have to run a database backup *before* initializing a database connection
 * We have to connect to the database to know if there are un-applied migrations
 * The database configuration is stored in `django.settings`

Here is a draft of what I think could be the design.

Objectives for UX:

 * Automatically prompt user during **upgrades** if database should be backed up
 * Connect to the database first, if there are migrations, recommend the user to do an upgrade and show the command for the upgrade, i.e. `kolibri backup --dest=/path/` (see mockup below)
 * Store database in a location sub-folder with timestamp in name. Do not rename files, this will make instructions for restoring more complicated.
 * Make target directory user-changable, default: `~/.kolibri/backups/` (satisfied by the command line option)
 * Do not prompt:
    * During downgrades, no migrations will be run. If someone is downgrading and they want to un-apply migrations, we need a mapping from their old installation environment to see everything that has changed. This is beyond the scope.
    * If we are on a dev environment: The upgrade target to+from are both non-stable versions.
    * When not prompting, output something like "Skipping backup process".

UX mock-up:

```
$ pip install kolibri --upgrade
$ kolibri start
INFO     Version was 0.6.dev020170830184305-git, new version: 0.6.1

Upgrade detected!

Migrations were detected for your upgrade.

We recommend that you quit now and run the following command to save your database files (size: 10 MB)

kolibri backup --dest=/home/aron/.kolibri/backups

Quit now and stop the upgrade? [Y/n]
```

Kolibri backup:

```
$ kolibri backup --dest=/home/aron/.kolibri/backups
Starting kolibri backup...

Detected database, size: 10 MB
Destination: /home/aron/.kolibri/backups

Continue with backup? [Y/n]

Files backed up in:

Destination: /home/aron/.kolibri/backups/2017-09-18-110023/

To restore, copy the files to /home/aron/.kolibri/
```

----

Re: Being database agnostic: There are huge performance improvements to be gained from running Postgres, which should be at the hands of most larger deployments shipping/maintaining their own devices.

**Comment by rtibbles** [comment]
+1 for database agnosticity, and we have taken a big step in that direction with the content db importing work.

We do currently have irreversible migrations in Kolibri, for the DateTimeTzField - I couldn't make the reverse migrations work, unfortunately.

**Comment by benjaoming** [comment]
> We do currently have irreversible migrations in Kolibri, for the DateTimeTzField - I couldn't make the reverse migrations work, unfortunately.

That's okay, no looking back, no regretting not being able to regret things! I think we are solving this issue in case we have more of these glitches - but we would do wise in implementing a policy of not allowing anything non-reversible in the future as I mentioned above.

**Comment by indirectlylit** [comment]
Hi @benjaoming thanks for your work so far on this.

For 0.6 (need to do it this week) I think we need a much simpler strategy with zero user interaction - something that works for our non-command-line users also.

The goal at this point should be to _not_ expose any of this backup functionality to the end-user. The only time they'd need to know it's happening is if something goes horribly wrong - we'll quickly learn about it, and then we work with them closely to show them how to downgrade.

For now, can we simply do a backup without any user interaction whenever the Kolibri version changes, and only keep the most recent backup? This will give us an emergency escape hatch for all users (including those using Windows, Android, etc) but in all likelihood it will be one we'll never need to exercise.

**Comment by benjaoming** [comment]
@indirectlylit :
> For 0.6 (need to do it this week) I think we need a much simpler strategy with zero user interaction - something that works for our non-command-line users also.

Would not work because of what @jamalex pointed out:
> Databases can accumulate a lot of user data, reports from KA Lite that databases are > 1 GB

Although we might not see deployments with `>1 GB` size, I think it's slightly a waste of time to implement a design that we know will break, especially since the bulk of this issue is to design something that'll work.

**Comment by benjaoming** [comment]
But hey, if it can't make it for 0.6, that's alright, then let's move it to 0.7 and fix it the best way pragmatically possible!! :)

**Comment by indirectlylit** [comment]
closing as wontfix since it's been back-burnered for so long and might not actually be necessary.

let me know if you see this as problematic

**Comment by benjaoming** [comment]
Yeah, agreed.

Current behavior is: If we are using SQLite and the version changes, a dump of the database is automatically created. _**Before running migrations.**_

Likely, the issues here are more about cleaning up automatically created backups since they can occupy a lot of disk space.
