### ISSUE TITLE
newly imported channel is not shown until refresh

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2145]
### importing:

![image](https://user-images.githubusercontent.com/2367265/30303016-069693da-971a-11e7-953e-b9de7f57fe1c.png)

### finished:

![image](https://user-images.githubusercontent.com/2367265/30303022-11857afe-971a-11e7-8d1d-eec6875a7c4c.png)

## close:

![image](https://user-images.githubusercontent.com/2367265/30303030-1d9f0814-971a-11e7-8fcc-eb7785240c9b.png)

### dismiss green pop-up:

![image](https://user-images.githubusercontent.com/2367265/30303049-2ee4a674-971a-11e7-903c-ffcaff2046df.png)

### refresh:

![image](https://user-images.githubusercontent.com/2367265/30303052-3463843a-971a-11e7-9e09-19572f600e0d.png)

**Comment by jonboiser** [comment]
@indirectlylit Did you delete Portion Control before this sequence? If so, there's an issue #2128 that goes into why this happens.

**Comment by indirectlylit** [comment]
that is probably what happened, thanks
