### ISSUE TITLE
'in progress' icon should be animated (or removed) so it doesn't look like a refresh button

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2146]
Currently the blue arrows [look like a refresh button](https://www.google.com/search?q=refresh+button&tbm=isch):

![image](https://user-images.githubusercontent.com/2367265/30303104-8603a838-971a-11e7-9130-86ca5e5078f1.png)

I believe the intent was that they'd be animated, is that correct @khangmach?

**Comment by khangmach** [comment]
yes, animated if possible. When we were running through this design Jessica and I liked the icon ic_autorenew: https://material.io/icons/#ic_autorenew over ic_refresh

**Comment by indirectlylit** [comment]
okay we can look at animating

one other option in case you're interested is the material "loading" spinner: https://codepen.io/indlt/pen/EwxZWx

**Comment by khangmach** [comment]
That looks good. I believe there's also a little animation delay/lag towards the end of the animation on the official spinner: https://material.io/guidelines/components/progress-activity.html#progress-activity-types-of-indicators

**Comment by christianmemije** [comment]
We can just use the [ui-progress-circular](https://josephuspaye.github.io/Keen-UI/#/ui-progress-circular).

**Comment by khangmach** [comment]
Cool, UI-progress-circular should be exactly what we're looking for.

**Comment by christianmemije** [comment]
Fixed #3238
