### ISSUE TITLE
Update from 0.5.0 to 0.6.0alpha2 does not load the content of the channels. 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2147]
## Summary
I updated the version 0.5.0 to 0.6.0-alpha2 the platforms works but cannot engage with any of the content and any of the features in Coach section.

Updation process:
1. Removed the 0.5.0pex file.
2. Used the kolibri-0.6.dev020170907122712-git.pex file.
3. ran `sudo ./kolibri-0.6.dev020170907122712-git.pex start`
4. Platform ran after a lot of migrations.
5. But the content does not load up on learn tab.
6. Cannot create exams, see the progress from recent, learner and topic tabs under coach section.

## System information
 - Version: kolibri-0.6.dev020170907122712-git.pex
 - Operating system: ubuntu 14.04LTS
 - Browser: Chrome

## Screenshots
![update1](https://user-images.githubusercontent.com/13453618/30323292-3a9c24c2-97da-11e7-846b-6f21c759cbf9.png)
![update2](https://user-images.githubusercontent.com/13453618/30323293-3af4eabc-97da-11e7-98a6-799bc7419dc0.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

The impact would be huge if we cannot update from one version to another smoothly.

**Comment by rtibbles** [comment]
Hi @harishbalachandran - this alpha is fairly old and was created as a code reference point. Current 0.6.x code does not suffer from all of these problems (and there are specific issues for those that do still exist).

I will be sure to flag you when there is a 0.6.0-beta to test out!

**Comment by harishbalachandran** [comment]
@rtibbles , thats totally fine will wait for the update! But the issue is that I am not able to revert back to 0.5.0, the platform is not working at all when I run `sudo ./kolibri-0.5.0.pex start`. Is there a way to revert it back? that would be really helpful.
