### ISSUE TITLE
'selected' counter in groups editor is inaccurate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2152]
Weird behavior with checkboxes in Groups page and the "N selected" message:

![gifmakerproject21](https://user-images.githubusercontent.com/2367265/30348024-cbdf7d02-97c2-11e7-88ac-76783f3594f3.gif)

This was found during the 0.6 hack session at this URL: http://104.196.144.58/coach/#/6e54aec31b1a5672ec663c5e11b354c3/groups

**Comment by christianmemije** [comment]
Fixed in #2181
