### ISSUE TITLE
server 400 response and uncaught JS errors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2156]
note: this issue does not seem to have a user-facing impact.

-----

Server is set up to allow password-less login:

http://104.196.144.58/user

![image](https://user-images.githubusercontent.com/2367265/30350245-c4dd445a-97ca-11e7-9c5d-4944bb7e1e6d.png)

After entering super user password `devowner` the server returns a 400:

```{"missing_field":"password","message":"Please provide password for user"}```

and the client has an unhandled error:

![image](https://user-images.githubusercontent.com/2367265/30350350-26f1b81a-97cb-11e7-8825-c71c1e462ac1.png)

**Comment by rtibbles** [comment]
Reopening as the fix has been reverted. Retargeting for 0.8
