### ISSUE TITLE
can't scroll PDFs on mobile safari (iOS)

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2158]
Go to page, try to scroll PDF. Doesn't work in embedded or full-screen mode.

Reproducible in Browserstack:

![image](https://user-images.githubusercontent.com/2367265/30351642-40c4d8c0-97d1-11e7-9ed5-c4e97792da37.png)

**Comment by kollivier** [comment]
Unable to reproduce in iOS 9+ on device or simulator in the general case, and iOS v7 was notably buggy after the huge UI rework, so I am going to close this issue.
