### ISSUE TITLE
duplicate labels in Profile page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2160]
Now that we're using text input fields with a built-in label, we should remove the extra headers:

![image](https://user-images.githubusercontent.com/2367265/30353128-0389fac8-97d9-11e7-9060-692b6d16f2e5.png)

**Comment by jonboiser** [comment]
This is a duplicate of #2149. ALso, the headers will probably still be necessary if the fields are in read-only mode.

**Comment by indirectlylit** [comment]
thanks
