### ISSUE TITLE
moving learners between groups is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2163]
Noted during hack session, and reproducible:

> Moving users between groups crashes (sometimes 500 error from /memberships plus JS error, sometimes no HTTP error, only JS error)

* Location: http://104.196.144.58/coach/#/6e54aec31b1a5672ec663c5e11b354c3/groups
* Request URL: `http://104.196.144.58/api/membership/?1505265732878=1505265732878`
* Request payload: `{collection: "10e72fed209853809b3583699113bc82", user: true}`
* Server error: `<h1>Server Error (500)</h1>`

Javascript console:

![image](https://user-images.githubusercontent.com/2367265/30355532-d8bff9fe-97e8-11e7-909b-36f7132cee56.png)

**Comment by jonboiser** [comment]
After doing some debugging, I'm suspecting something similar to #2128 is going on: The MembershipCollection has models that are flagged as deleted, so are not returned as `memberships` in

```javascript
const collection = MembershipResource.getCollection(blah)
collection.fetch().then(function onSuccess(memberships) {
   console.log(collection.models) // has stuff but is deleted
   console.log(collection.data) // === memberships and is empty, hence crash
})
```

Why is it that these Membership models are being reused? Unlike the channels, they should have unique UUIDs when they are created.

**Comment by indirectlylit** [comment]
cc @aronasorman could use your help with this

**Comment by jonboiser** [comment]
I don't think this is back-end related. See the analysis in #2128: If a Model is deleted, there seems to be a cached version that stays deleted, even if a new Model (with the same ID) is brought back into the system. This is why it happens when deleting and re-creating things like Memberships and Channels whose IDs are not random.

**Comment by rtibbles** [comment]
This bug is extant back to 0.4, so I will be submitting the fix there and then cascade merging.

**Comment by jonboiser** [comment]
#2317
