### ISSUE TITLE
replace exercise renderer with kolibri loader until content is ready

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2167]
Currently,content slowly appears, shifting the rest of the page down. This is a bit confusing because there's no clear indication that the page is still loading, or affirmation when it's done loading:

![gifmakerproject22](https://user-images.githubusercontent.com/2367265/30356356-6dd5704c-97ed-11e7-9ac7-6d12f2855973.gif)

Recommend swapping out the exercise renderer for the kolibri flappy bird until the content is completely ready.

**Comment by rtibbles** [comment]
Probably two layers here - one is a loading animation for loading content renderers, the other would be a loading animation for the perseus renderer in particular.

The latter of these is more like the issue described, however.

**Comment by christianmemije** [comment]
The specific renderer could emit a ready/loading event up to the content-renderer component .

**Comment by christianmemije** [comment]
Waiting on https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/116

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/121
