### ISSUE TITLE
hide thumbnails from downloadable files

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2169]
We should filter thumbnails out of the downloadable file list for all content types.

![image](https://user-images.githubusercontent.com/2367265/30356823-03b04702-97f0-11e7-96fe-d9a98daaf328.png)

![image](https://user-images.githubusercontent.com/2367265/30356837-1013b88a-97f0-11e7-8e69-6a6d814f1c80.png)

**Comment by rtibbles** [comment]
Fixed in #2174
