### ISSUE TITLE
Extra bullet points appear on the answer options when the question is accessed through a tablet.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2177]
## Summary

Extra bullet points appear on the answer options when the question is accessed through a tablet.

Channel: e7092f51089243aaa8542bf2519bb548

## System information
 - Version: 0.4.5 and 0.5.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. Import the channel and access the question through tablet.

## Screenshots
Screen shot from a Tablet:
![screenshot_2017-09-13-19-17-22](https://user-images.githubusercontent.com/13453618/30381084-05beb424-98b9-11e7-8794-53329be37ca5.png)
![screenshot_2017-09-13-19-17-45](https://user-images.githubusercontent.com/13453618/30381088-0699d40a-98b9-11e7-8563-7bbdc238e1b0.png)
![screenshot_2017-09-13-19-17-52](https://user-images.githubusercontent.com/13453618/30381089-069e251e-98b9-11e7-923c-bd2b388341cf.png)

Screen shot of the same question on a Laptop: 
**Note**: The same bullets appear behind the radio button if we take a closer look.
![image5](https://user-images.githubusercontent.com/13453618/30381110-1b4db59c-98b9-11e7-92e0-6ac39d32b5f4.png)
![image 6](https://user-images.githubusercontent.com/13453618/30381122-1e8673a2-98b9-11e7-80f2-a8d8dd99417c.png)

**Comment by rtibbles** [comment]
I think this was fixed by #1869

**Comment by indirectlylit** [comment]
Fixed in 0.6

unsure if it's necessary (or straightforward) to fix in 0.4 because I assume that would require multiple released versions of the perseus renderer?

**Comment by rtibbles** [comment]
I can see how the change might happen, but I thought it was too risky to port to 0.4 yeah.
