### ISSUE TITLE
style guide update: form validation pattern

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2184]
Currently the logic for textboxes in a form is:

> show validation on blur

This leads to a situation where just tabbing through the form or clicking another link or button will display a validation message, which seems [a little bit off-putting](https://github.com/learningequality/kolibri/pull/2183#issuecomment-329248568).

recommend updating the pattern to be:

> show validation on blur _if_ the value has changed

This should allow people to interact with other parts of the page without inadvertently showing irrelevant validation messages

The one downside here might be that fields which are required won't display "required" text as you tab through them. However, this will be identified when they submit the form.

Feedback is welcome. (cc @jtamiace @christianmemije)

**Comment by christianmemije** [comment]
> The one downside here might be that fields which are required won't display "required" text as you tab through them.

Hmm. Not a fan of this. 

Another option is that validation only occurs on submit...

**Comment by indirectlylit** [comment]
> Not a fan of this

Can you elaborate?

Basically I'm thinking:

* It's good to show validation as soon as possible so they can correct mistakes sooner
* It's good to avoid showing validation when the user did not actually make a mistake

Those two forces are often in opposition, so any behavior will need to compromise between them

**Comment by christianmemije** [comment]
I guess the fact that only a subset of the validation occurs if the value has changed. But `It's good to avoid showing validation when the user did not actually make a mistake` is good point.

**Comment by indirectlylit** [comment]
well let's sit on this for a bit and maybe revisit with @jtamiace later

**Comment by indirectlylit** [comment]
This was reported again during today's hack session by @jeepurs:

* Description: Error for username validation shows up every time a language is switched
* Page: Sign in
* Steps to reproduce: Click on language that is not English

**Comment by indirectlylit** [comment]
@jtamiace  says

> maybe we can see if there are indicators we can add to make required vs optional fields more salient without form submission being the way to find out

@indirectlylit  responds

>  yeah - could just add a dot to the label or something
