### ISSUE TITLE
Content# counts in Kolibri are inaccurate

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2185]
## Summary

We appear to be counting `File` objects rather than `ContentNode` objects in returning content/resource counts on the content import page. This is different (and less useful) from what is reported on the Studio side.

The correct code for counting would be something like:
`ContentNode.objects.get(id=root_node_id).get_descendants().exclude(kind=content_kinds.TOPIC).count()`

## System information

 - Version: 0.5.0

## How to reproduce

1. Download content
1. Go to content page and look at count
1. Cry

## Screenshots

![image](https://user-images.githubusercontent.com/618416/30395216-4a3cd49e-987a-11e7-872b-0ff78654aeb3.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Users have reported in confusion on the mismatches between the Studio counts and the counts in Kolibri.

**Comment by rtibbles** [comment]
Fixed in #2194
