### ISSUE TITLE
content cards should handle long titles better

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2193]
See for example this card:

![image](https://user-images.githubusercontent.com/2367265/30400942-62c9f1c8-988d-11e7-948b-435732946196.png)

It should have the title

> I am the very model of a modern Major General, I've information vegetable, animal, and mineral

The title is truncated and there's no indication to the user that the title is truncated.

Some options:

* add an ellipsis character (…) when the title is truncated
* add a tooltip showing the full title on hover
* updated spacing so that 3 lines of text can be shown

**Comment by jtamiace** [comment]
I've always thought ellipses were a good solution for this. I think a combo of ellipsis and tooltips are a good workaround.

**Comment by indirectlylit** [comment]
https://github.com/quantity-digital/vue-shave

**Comment by mrpau-eugene** [comment]
Hi @indirectlylit, is it alright to use the `title` attribute for the tooltip and some css for the ellipsis part? Or should we use the `vue-shave` for doing the ellipsis part?

**Comment by indirectlylit** [comment]
Hey @mrpau-eugene -

As far as I know it's not possible to use CSS for the ellipsis because it's a multi-line text region, so I think `vue-shave` is our best bet.

For the tooltip, let's use the `ui-tooltip` component that we use elsewhere in the app. Note: it should _only_ be shown when the text is elided by `vue-shave`.

Thanks for working on this - it will be a big improvement!

**Comment by mrpau-eugene** [comment]
@indirectlylit Thanks! Btw, can you give me a walkthrough on how can I import `vue-shave`?

After doing `yarn add vue-shave`, I'm not quite sure what to do next

I think I need to do something similar to this:

https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/core-app/constructor.js#L53

so I can use it inside components. But I'm just not quite sure what is the correct process when adding a new dependency...

**Comment by indirectlylit** [comment]
> I think the only sure-fired way to get vue-shave in is to bind it to the global Vue instance within every plugin, located here:
> https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/core-app/constructor.js#L51-L52
> 
> Though I'm not sure this is ideal, since I don't think we use it in every instance.

That sounds okay to me. If it works well, there will likely be other place we'll want to re-use it in the future.

**Comment by rtibbles** [comment]
You can definitely do it on a per plugin basis, as @DXCanas suggests.

Given that this is an issue we are going to confront a lot, I don't see an issue with adding it globally as @indirectlylit suggests and @DXCanas describes.

**Comment by christianmemije** [comment]
Fixed in #3278
