### ISSUE TITLE
create 'kolibri setup' command

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2196]
Migrated from [Trello card](https://trello.com/c/7HyYiYNO/577-create-kolibri-setup-cli-command-to-allow-currently-start-specific-setup-to-be-done-independently)

Create Kolibri 'setup' CLI command to allow currently 'start'-specific setup to be done independently.

@aronasorman or @rtibbles feel free to elaborate or close this as wontfix if desired.

**Comment by benjaoming** [comment]
This is very nice for purposes of bootstrapping/templating deployments.

The only thing I don't like is adding yet another command that starts with an 's' :) But this might be fixed by not ordering commands alphabetically, but by their relevance:

```
Usage:
  kolibri start [--foreground] [--port=<port>] [options]
  kolibri stop [options]
  kolibri restart [options]
  kolibri status [options]
  kolibri shell [options]
  kolibri manage COMMAND [DJANGO_OPTIONS ...]
  kolibri manage COMMAND [options] [-- DJANGO_OPTIONS ...]
  kolibri diagnose [options]
  kolibri plugin [options] PLUGIN (enable | disable)
  kolibri language setdefault <langcode>
  kolibri plugin --list
  kolibri -h | --help
  kolibri --version
```

**Comment by jonboiser** [comment]
I'm not sure, because it's not clear to me what "'start'-specific setup" means, but I think some of this feature might already exist in commands like `provisiondevice`. Users can use that CLI command to create a new Kolibri server without having to go through the Setup Wizard.
