### ISSUE TITLE
core API - pluggable routing / nav bar items

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2197]
We need a flexible and forward-looking way for application-level plugins (e.g. manage, learn, coach) to register themselves as wanting to add a widget to the nav bar.

This is might not be as simple as just a list of names and URLs:

* Needs to take into account ordering, user permissions, icons, etc
* potentially support more complex widgets than just text + link (e.g. we at one point discussed displaying learner points in the nav bar)
* Might also need to support sub-section links

**Comment by rtibbles** [comment]
I believe this is fixed, except for the sub-section piece, which would come more under the 'plugins for plugins'?

**Comment by indirectlylit** [comment]
yes, thanks
