### ISSUE TITLE
automated upgrade path testing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2200]
Implement automated tests to help us prepare for upgrades

**Comment by indirectlylit** [comment]
notes: 

* simple db backup approach is still targeted for 0.6 here: https://github.com/learningequality/kolibri/issues/2266
* we'll be doing manual upgrade testing during a hack session tomorrow: https://docs.google.com/document/d/1dD1z_cgVkA1lqD7Cbngkiwm7qCuvrp2B8IaR-TwjxXQ/edit#
* will need to do additional manual testing of installers.

With all that in mind, I'm switching the milestone and focusing this ticket on just automated upgrade testing

**Comment by jredrejo** [comment]
> With all that in mind, I'm switching the milestone and focusing this ticket on just automated upgrade testing

@indirectlylit  could you give me some details on the kind of tool you have in mind to do the testing? travis? or some other tool?

**Comment by indirectlylit** [comment]
I don't have strong opinions - it would depend in part on how long the tests take and what kind of sample data is necessary to get realistic assurances.

This task may also be a lower priority now that we have upgrade paths as part of our manual integration testing.

Originally I'd been worried that our data migrations and other related upgrade code might be a risky part of the code base in the presence of real-world databases, and I'd envisioned collecting a large, representative set of representative data in order to ensure that no data loss or corruption occurs on upgrade. However in practice we haven't seen many issues, so I'm not sure this concern was entirely justified.

Before diving in, we should try to identify what kind of test coverage we already have, what kinds of tests we do manually, and where the main risk areas are. @rtibbles and @radinamatic might have thoughts...

**Comment by jonboiser** [comment]
Added to the list of [backburner issues](https://github.com/learningequality/kolibri/discussions/7806)

**Comment by indirectlylit** [comment]
If we're closing the issue, is 'backburner' the right list? Maybe won't-fix?

**Comment by jonboiser** [comment]
Yeah, most likely "backburner" is equal to wont-fix in practice, esp. if the issue hasn't moved forward in a couple years. I'm just trying to get the issue list down to a more manageable size.
