### ISSUE TITLE
Superuser permissions follow-up

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2201]
* Grep for `isSuperuser` (case-sensitive) and `device owner` (case-insensitive)
* Primary design questions: language and iconography

**Comment by khangmach** [comment]
Advocating for the usage of ic_vpn_key to replace the permission stars. Stars are associated with mastery and since we're using a lock for the permissions "tab", it would perhaps make more sense to introduce "keys" for certain "locked" permissions. See icon here: https://material.io/icons/#ic_vpn_key

**Superuser permission color:** #FBC02D
**Regular permission(s) color:** #212121
**No permissions:** do not use any icon. Remove the current superuser icon. Icons should be in their own column and not placed left of the full name column.

**Comment by khangmach** [comment]
**CHANGES TO USER DROPDOWN**

- Removal of (role label) that is appended to the username.
- Removal of "superuser" as a role label option
- Include role label in user dropdown menu as first item
- Saves screen estate and emphasizes username as primary info, role as secondary information
- Roles only include: learner/coach/admin. "Superuser" should not be a role (it is currently displayed in Kolibri) and is only a label for that should be conveyed in the permissions tab. 

![user dropdown menu](https://user-images.githubusercontent.com/25045166/30668498-cf5f10f2-9e0f-11e7-9aca-3edfe8c99ce2.png)

**Comment by khangmach** [comment]
**CHANGES TO PROFILE**

- Rearrange form elements to de-clutter the form, specifically letting points have a bit of breathing space, not squashed between Role and full name. 
- Add list of device permissions available to the specific user. 
![profile changes](https://user-images.githubusercontent.com/25045166/30670282-94cdc45e-9e16-11e7-9386-5b444dbc3a1a.png)

**Comment by christianmemije** [comment]
So if a user is a Superuser, would we just say Superuser, or say superuser and list all permissions? @khangmach

**Comment by khangmach** [comment]
If superuser is now an official user type (has make superuser checkbox checked), we need to swap out "device owner" with "Superuser". Facility admin still stands if a user has some permissions checked OR all permissions excluding "make superuser" checked. 

If a user doesn't have any permissions, there is no "device permissions" profile section to show here.

**Comment by indirectlylit** [comment]
reported during hack session by @jtamiace:

If a Superuser makes a Learner a Superuser, and then that Learner logs in, the Role of that former Learner does not have an "Admin" tag in the Users list

* Have a Superuser elevate a Learner to a Superuser
* Log out
* Log in with that former-learner account
* Navigate to Users and find your former-learner account

**Comment by christianmemije** [comment]
@khangmach What should the text be updated to? 

![127 0 0 1-8000-learn- 1](https://user-images.githubusercontent.com/7193975/30874040-10b9c536-a2a4-11e7-9ae2-e89f018be99b.png)

**Comment by khangmach** [comment]
@christianmemije 

**No content available**
You can download content by navigating to the "Device" tab in the main menu

No need to mention signing in as a device owner or account created in the setup wizard. The primary use case for this text: We want this text to help those who just setup their devices (who are already logged in as a superuser) who happened to navigate to "Learn" immediately before exploring the Device tab. 

Learners and coaches that are created shouldn't see this text, as they'll have their devices and channels configured by the facility admin beforehand.

**Comment by christianmemije** [comment]
> If a Superuser makes a Learner a Superuser, and then that Learner logs in, the Role of that former Learner does not have an "Admin" tag in the Users list

That sounds like correct behavior. They are not an Admin. Their role is still learner, but with superuser permissions. In the users page we only display role details, not permission details. Unless I'm misunderstanding this. @indirectlylit

**Comment by indirectlylit** [comment]
I'm honestly not sure anymore - it turns out that a superuser learner actually has all the facility role permissions of an admin. Previously the thinking was that superuser permission was just device related but that's actually not true.

**Comment by khangmach** [comment]
My initial understanding was that the superuser was also just device related, but it seems the discussion within design room last week frames superuser as another role. 
Discussion: https://learningequality.slack.com/archives/C0LKG14NL/p1505950420000036
Permission roles doc for reference: https://docs.google.com/document/d/1mD2NwW-JE8_NuVo110us2DGnZ6l2AKE3__3fIwvTjIs/edit#heading=h.7siqjgdhfv5i

**Comment by christianmemije** [comment]
Addressed in #2288
