### ISSUE TITLE
login-page language switcher is always hidden

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2203]
Regardless of screen size, the language switcher is always "below the fold".

I believe the intent was that - when space is available, it would be visible by default?

![image](https://user-images.githubusercontent.com/2367265/30503190-31b6dd02-9a1e-11e7-8b9c-d0db5a5e941f.png)

cc @khangmach

**Comment by rtibbles** [comment]
Odd, I don't remember it being like this when originally implemented, spent a lot of time ensuring it always displayed.

**Comment by khangmach** [comment]
Yeah, the language footer was intended to be displayed at all times, whenever space is available
