### ISSUE TITLE
Unable to import channel from Kolibri Studio.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2205]
## Summary
Unable to import channel from Kolibri Studio. 
Channel ID: e7092f51089243aaa8542bf2519bb548

We tested few other channel and are still not able to import.

## System information
 - Version: 0.5.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
1. The channel import fails 

## Screenshots
![screen1](https://user-images.githubusercontent.com/13453618/30553989-977b796e-9cc0-11e7-8f72-bca3bb1515e4.png)
![screen2](https://user-images.githubusercontent.com/13453618/30553990-97c1e354-9cc0-11e7-9b83-e47d52ec89eb.png)

**Comment by jonboiser** [comment]
@harishbalachandran Did the transfer fail immediately, or did it progress a little bit before failing?

A few days ago we were making changes to the server that might have caused channel import requests to fail immediately.

**Comment by harishbalachandran** [comment]
@jonboiser! yes you are right, I tired to import when the server was down, now I can import. Hence closing this issue. Thanks!
