### ISSUE TITLE
Class Page - Rough transition when applying 'selected users' filter

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2208]
![kapture 2017-09-18 at 11 02 43](https://user-images.githubusercontent.com/10248067/30556783-e6770a02-9c60-11e7-9b10-40a58d17713e.gif)

@christianmemije Do you think a `transition` could help here?

**Comment by christianmemije** [comment]
I think we need to figure out why the column is changing widths and prevent that. While we are here, we should also replace the switch with a checkbox.

**Comment by indirectlylit** [comment]
note - some behavior might be affected by https://github.com/learningequality/kolibri/pull/2215

Let's get that merged in before further work because they impact the same files
