### ISSUE TITLE
Correctly use fullscreen modals & action bars

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2210]
The style guide specs out a fullscreen modal and action bar components. To summarize, fullscreen modals should be overlays without a unique url. If there is a unique url, then action bars should be used. This does not call for an overlay, just a change in action bar, from the default app bar to the appropriate action bar.

Currently there are some places, such as the permissions page, that use the fullscreen modal component, aka `immersive-fullscreen`, but should in fact be just using the action bars

Fullscreen modal:
https://docs.google.com/document/d/15Y1RDzsO_vpRSSEtL_L5lCzZtAtN4j3qN813_bnL4uw/edit?usp=drive_web

Action bars:
https://docs.google.com/document/d/1oqo8JbiNAWPg0qR1EUsvqG_2QRoMCxKUmGEvnFBRbLo/edit#heading=h.3hd8sb43s8bk

**Comment by indirectlylit** [comment]
fixed in https://github.com/learningequality/kolibri/pull/5653
