### ISSUE TITLE
add ESLint back to build process

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2216]
Prettier has helped make our code prettier and more consistent, but ESLint had the advantage of being able to catch bugs like missing variable definitions and imports.

Comment from one dev:

> At least three times last week code with bugs that would have been caught passed CI.

Let's add ESLint back to the build, alongside Prettier.

**Comment by rtibbles** [comment]
Yes, now that we have the simpler config, this should be simple.

**Comment by rtibbles** [comment]
One question - would we want to revert to the old 'fail on error' behaviour, or just warn? I know people had found the failing on error aggravating.

**Comment by indirectlylit** [comment]
is it possible to fail for CI and warn for devs?

**Comment by rtibbles** [comment]
Yes, all things are possible. (as long as all things = these very specific things).

**Comment by indirectlylit** [comment]
see also #1949

**Comment by christianmemije** [comment]
Fixed in #2418
