### ISSUE TITLE
Onboarding - Lose keyboard control of form at "Step 4"

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2218]
On Chrome, onboarding is keyboard accessible through Step 3.

When I start tabbing at Step 4, it cycles through browser tabs, instead of the form.

![screen shot 2017-09-19 at 4 07 50 pm](https://user-images.githubusercontent.com/10248067/30619554-dfcb539e-9d54-11e7-9cc0-fa87e14dae4c.png)

**Comment by DXCanas** [comment]
I can set up a new prop to allow autofocus on `k-radio-button`, but it seems like  the component isn't tab-able generally,

@christianmemije Do you happen to know why this is the case? See gif below:
![focusorderkradiobutton](https://user-images.githubusercontent.com/9877852/30671924-578e4a5c-9e1e-11e7-9c15-5298cd2fefb7.gif)

**Comment by jonboiser** [comment]
@DXCanas Tabbing won't take you to the other radio buttons, but using arrow keys does. Tabbing should take you to the submit button, though.

**Comment by DXCanas** [comment]
@jonboiser sweet. Sounds like the behavior in the gif is working as expected, then?

**Comment by jonboiser** [comment]
Yeah, what's in the GIF is expected, but you did have to click on to the page to get the form to focus right?

So if you could get the radio buttons to be focused on page load, I think that would fix it. Currently, for me, when you start tabbing on this page, the browser tabs are focused, and not anything on the page.

**Comment by DXCanas** [comment]
>  but you did have to click on to the page to get the form to focus right?

No actually, it was focused on enter! Sounds like this fix is good then. PR incoming.
