### ISSUE TITLE
finish initial version of style guide

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2221]
Tracker issue for ongoing style guide work.

We can close this when all of the main components have been moved to the style guide and set to 'completed'.

[See documentation on GDrive](https://drive.google.com/drive/folders/0B7bOp_NzCzXIMkljN1ZRcGNkVmM)

* [ ] Typography
* [ ] Color
* [ ] Grids
* [ ] Writing Style
* [ ] Tables
* [ ] Forms
* [ ] Table Filters
* [ ] Full-page modals
* [ ] Text fields
* [x] Checkboxes
* [ ] Search
* [ ] Simple Modals
* [x] Buttons
* [x] Breadcrumbs
* [ ] Radio buttons
* [ ] Style guide update and usage notes

**Comment by jonboiser** [comment]
Closing, as these style guide docs have been moved to the kolibri-design-system repo and might have a new table of contents.
