### ISSUE TITLE
Missing pluralization 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2222]
## Summary

Not sure where exactly is this string, but I'm suspecting that it could have a singular too, and not only plurals.

**coach_module-messages.json**
`examReportPage.remaining`

## System information

 - Version: Crowdin for 0.6 release

https://crowdin.com/translate/kolibri/247/en-es#17038

## Screenshots

![coach_module-messages json - kolibri - crowdin translation - google chrome_623](https://user-images.githubusercontent.com/1457929/30655434-2a792402-9e31-11e7-8e72-86f54e2c1d07.png)

**Comment by rtibbles** [comment]
Shifted it to 0.7.0, as this is an issue, but not big enough to violate the string freeze, methinks.

**Comment by radinamatic** [comment]
Agreed, not big enough! :+1:
