### ISSUE TITLE
Detecting if a topic is a channel

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2223]
## Summary

Currenty, we detect if a topic is a channel by checking that the `channel_id` and `pk` are equal. I ran into a channel where they are not equal. See 2nd channel in image below. Does this just need to be republished? Also, should we be just annotating channels as kind=channel in the models?

![image](https://user-images.githubusercontent.com/7193975/30656070-ab496d34-9de7-11e7-86d1-c27b27a669bb.png)

![image](https://user-images.githubusercontent.com/7193975/30656122-d5060c4a-9de7-11e7-909e-ff67890a4a5a.png)

**Comment by jonboiser** [comment]
If a node has `null` for `parent`, does that mean it's a channel?

**Comment by christianmemije** [comment]
Sounds right.

**Comment by rtibbles** [comment]
Yes, this is a better test, as we are really looking at a root node. We may also want to just use the channel data instead, which,  in the database at least, has a base64 encoded thumbnail.

**Comment by rtibbles** [comment]
I just did it this way to quickly reuse the existing grid.

**Comment by indirectlylit** [comment]
+1 on anything that helps grab the thumbnail

**Comment by christianmemije** [comment]
Implemented in #2286
