### ISSUE TITLE
Reduce page padding on mobile 

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2224]
## Summary

Currently a lot of precious space is wasted with a padding of 32px on mobile screens.

https://github.com/learningequality/kolibri/blob/a0cca5c17e8f190f0ed66fe8deb9c9e5cd436ac4/kolibri/core/assets/src/views/core-base.vue#L164

We should reduce that padding on mobile screens. Thought @indirectlylit?

![127 0 0 1-8000-management-device iphone 5](https://user-images.githubusercontent.com/7193975/30657254-bce6e554-9deb-11e7-9369-81050e102b70.png)

**Comment by indirectlylit** [comment]
reducing the padding is a good idea - maybe down to 16px for breakpoint 0.

Note that this particular page now scrolls horizontally.

**Comment by rtibbles** [comment]
Fixed in #2480
