### ISSUE TITLE
Running 'generateuserdata' command re-enrolls users to facility after first run

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2225]
To reproduce, do something like:

```
# on a clean and empty .kolibri/ folder
kolibri manage generateuserdata # generates 2 classes by default
kolibri manage generateuserdata --classes=3 # will add one more class
```

Get this in the stack trace: `django.db.utils.IntegrityError: UNIQUE constraint failed: kolibriauth_facilityuser.username, kolibriauth_facilityuser.facility_id`

It seems that even with the new random sample, there are at least some users in the first two classes being added to the third. To test this theory, I added '123' to the usernames from the CSV file and the problem went away.

**Comment by rtibbles** [comment]
To fix this, we should do `get_or_create`.
