### ISSUE TITLE
clicking label for k-checkbox does not trigger 'change' event

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2233]
Don't know if it's being used wrong in 'facilities-config-page', but expected clicking label to work the same as clicking the actual checkbox.
```
            <k-checkbox
              :label="$tr(setting)"
              :checked="settings[setting]"
              @change="toggleSetting(setting)"
            />

```
![label click](https://user-images.githubusercontent.com/10248067/30670875-0e611f4e-9e19-11e7-8c13-579ebd90af9e.gif)

**Comment by christianmemije** [comment]
:rage4: :rage4: :rage4: Caused by https://github.com/learningequality/kolibri/pull/2220, looking into it.
