### ISSUE TITLE
new channels don't show up after importing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2237]
import is completed, but the channel doesn't show up:

![gifmakerproject24](https://user-images.githubusercontent.com/2367265/30674071-5c090f46-9e2c-11e7-893a-aab1b27e6dfa.gif)

**Comment by jonboiser** [comment]
You have to click 'close' first to see the notification and see the new channel. Whether this is a good interaction should probably be focused on for the new im/ex designs.
