### ISSUE TITLE
login screen doesn't scroll

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2238]
on small windows, buttons "below the fold" are inaccessible:

![image](https://user-images.githubusercontent.com/2367265/30674291-f469336e-9e2d-11e7-90ec-e705d5c2cf34.png)

**Comment by indirectlylit** [comment]
cc @khangmach

**Comment by DXCanas** [comment]
Can confirm. Especially annoying on small screens.

**Comment by khangmach** [comment]
The entire screen should scroll on mobile screens. The language selection area was intended to follow the content the rest of the content above it, like one div after the other. The area should not overlay anything.

**Comment by rtibbles** [comment]
Again, I had made this so previously. Not sure why this is getting overridden unless the base styles got reverted somehow.

**Comment by indirectlylit** [comment]
Very possibly a regression. We could git bisect to find the root cause if that'd be helpful.

FYI - @khangmach and I have been discussing intended responsive behaviors a bit. I'd be happy to take this on.

**Comment by rtibbles** [comment]
Sure, the main thing I had done for this previously was getting rid of some of the base styles in core-styles, particularly the default hidden overflow.

**Comment by rtibbles** [comment]
This is fixed for 0.6. Punting to 0.7 for fuller work.
