### ISSUE TITLE
Recommended view more broken

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2240]
## Summary

Recommended view more page is broken

## Version

0.6

## Error

```
recommended.js:83 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
```

## Error source

https://github.com/learningequality/kolibri/blob/9ae52f66977590f59ba0c641e97b9fda9e186b7f/kolibri/plugins/learn/assets/src/state/actions/recommended.js#L83

## How to reproduce

1. Go to Learn Recommended Page
2. Click on View More

**Comment by jonboiser** [comment]
The contract for then call back in `pagePrep.then` looks off (e.g. being 2-ary and having `channels` as the second argument).

```
  const pagePrep = Promise.all([
    getContentPromise(state, channelId),
    setAndCheckChannels(store),
    // resolves to mapped content set because then resolves to its function's return value
  ]).then(([content]) => _mapContentSet(content), error => error);

  pagePrep.then(
    (recommendations, channels) => {
      if (!channels.length) {
        return;
      }
```

Possibly the intention was `pagePrep.then(([recommendations, channels]) => ...`, but the type of `pagePrep` looks like `Promise<Object>`, where `Object` is the return value of `_mapContentSet`. So maybe `pagePrep.then(({recommendations, channels}) => ...`?

**Comment by indirectlylit** [comment]
original change - https://github.com/learningequality/kolibri/commit/a5a84104f3e58fc309691c785a0714f5652ffbb8#diff-a6ca316ca9b4bd1573989c36dbd5b084
