### ISSUE TITLE
No special 'empty' state when no learners are in a class

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2243]
As a coach, go to a class that has no learners. See the headers (but no rows) for a learner table, but no special message below (unlike the other tabs in coach tools):

![image](https://user-images.githubusercontent.com/2367265/30720728-921a4c88-9edd-11e7-895d-3f8005b5cc0f.png)

reported by @jonboiser during an 0.6 QA session

**Comment by rtibbles** [comment]
Fixed in #2576
