### ISSUE TITLE
'nice work' pop-up often doesn't appear

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2253]
## Summary
The nice work keep it up pop up doesn't come in most of the learners account on version 0.4.5 and 0.5.0

## System information
 - Version: 0.4.5 and 0.5.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome

## How to reproduce
Start solving the exercise and videos the pop up does not come up.

## Screenshots
This pop up does not appear most of the time:
![popup](https://user-images.githubusercontent.com/13453618/30753079-ed1ac276-9fdb-11e7-98d8-1724e8cd0df5.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Learners are unaware that they have mastered and keep solving it continuously.

**Comment by rtibbles** [comment]
Is this after the exercise is already completed, or just in general?

Any more information about the context in which this is happening is helpful - is it only when the platform is in Hindi, for example?

**Comment by harishbalachandran** [comment]
Just in general, some of the exercises get mastered with the pop up and some doesn't.

It's not channel specific and across all cities. And we do not have Hindi UI platform, we only have English UI.

**Comment by navakk9** [comment]
I was able to replicate this locally on the 0.5 pex, even after finishing 3 questions, there is no pop up to move to the next exercise. I did like 10 questions in a row. no error showing up in the console: 
![screen shot 2017-09-26 at 10 24 22 am](https://user-images.githubusercontent.com/26124065/30874395-072fa610-a2a5-11e7-9f37-6e12a862dba3.png)
![screen shot 2017-09-26 at 10 24 36 am](https://user-images.githubusercontent.com/26124065/30874396-074e3328-a2a5-11e7-8cf5-7d1fcede76ef.png)

**Comment by rtibbles** [comment]
Had you previously completed another exercise in the same session before this happened?

**Comment by navakk9** [comment]
@rtibbles - yes!

**Comment by rtibbles** [comment]
I think I know the root of the issue - the pop up dialog has some internal state that is not getting reset (presumably, it is not getting torn down when we navigate to the next item) - this prevents the pop up from showing up again if an item has already been completed, but it is failing to take into account the change of exercise!

**Comment by navakk9** [comment]
ahaaa wonderful!

**Comment by rtibbles** [comment]
Fixed in #2354

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.6beta1. Working fine.

![img_20171010_145326](https://user-images.githubusercontent.com/12776071/31379318-81c8fc42-adcb-11e7-88a4-d19969e929cd.jpg)
