### ISSUE TITLE
add device setting for changing default language

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2258]
The default language for a device is now configurable during setup. However there is currently no UI for modifying this after the fact.

Needs design - cc @khangmach @jtamiace

**Comment by khangmach** [comment]
@indirectlylit there is a "change language" option within the user dropdown

**Comment by indirectlylit** [comment]
The user dropdown updates the language for the current user.

This issue is for the device default, which is set up during initial onboarding. This affects the default language for newly-created users.

**Comment by indirectlylit** [comment]
It also affects the language of the sign-in screen. Will probably need to be added to device settings somewhere:

![image](https://user-images.githubusercontent.com/2367265/30794590-f2f03796-a17d-11e7-9d04-98df7b1fdf2c.png)

**Comment by jtamiace** [comment]
![device setting](https://user-images.githubusercontent.com/6668144/31142351-e8acad02-a82e-11e7-9833-8b1cf828c253.png)

Putting this here so that it doesn't get lost. Still prefer the option on the left, with tab name of "Settings" to minimize the number of tabs in the future "Data" & "Facilities"

Note from @indirectlylit in Slack:

> (minor subtlety is the other language switchers change the global language immediately, whereas this one wouldn’t because the admin’s language preference still takes priority. doesn’t really affect the designs above, just an interaction detail)

**Comment by jtamiace** [comment]
![slice](https://user-images.githubusercontent.com/6668144/31144062-560641a6-a834-11e7-8b19-74754e46d61c.png)

I think we like this one better. In the words of Devon:

> "simple drop-down is simple"

**Comment by jonboiser** [comment]
This will require some new additions to the code:

1. A Viewset to be able to modify the default language in the DeviceSettings model
1. An entirely new section for Device > Settings
