### ISSUE TITLE
<Imp Enhancement> Learner username is not displayed on the top right corner of the browser on a Portrait mode in a tablet.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#2260]
## Summary
Learner username is not displayed on the top right corner of the browser on a Portrait mode in a tablet.

When the tablet is key in landscape mode the learners can see their logged in username on the top right corner, but when you switch it to portrait mode learner's login ID is not visible and on top of that he/she cannot know who's ID he is logged in, as the username is not visible on the dropdown option on the top right corner.

**Important user story**
Its always good to have the learners name displayed all times at the top right corner, so that the learner is aware that he/she is using their own account. This is a big issue since we have't implemented the #2131 and because of this at-least 50% of the leaner end up progressing on the wrong student account. Some learners prefer using Portrait mode and some prefer Landscape mode, hence is enhancement is important.

## System information
 - Version: 0.4.5 and 0.5.0
 - Operating system: Ubuntu 14.04LTS
 - Browser: Chrome.

## How to reproduce
1. Login in a tablet on Landscape mode, notice the user name is clearly visible at the top right corner.
2. Now switch to Portrait mode and notice the username is not visible and not found in the dropdown too.
3. The learner has to got to profiles to know the username.

## Screenshots
On landscape mode:
![img_20170919_162516](https://user-images.githubusercontent.com/13453618/30801189-113b35f2-a200-11e7-891e-68111c2b5ea2.jpg)

On Portrait mode:
![img_20170919_162503](https://user-images.githubusercontent.com/13453618/30801195-1a3cdd40-a200-11e7-9d88-89d5f498ecb6.jpg)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)
Learner's end up using the wrong user accounts most of the time. Consequence is  👎  :)

**Comment by christianmemije** [comment]
Addressed in #2288

**Comment by indirectlylit** [comment]
re-opening because we need to address it in 0.4.6

**Comment by christianmemije** [comment]
@indirectlylit Addressed for 0.4 in https://github.com/learningequality/kolibri/pull/2357

**Comment by rtibbles** [comment]
Fixed in #2357

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri0.4.6beta1. Working fine.

On landscape mode:
![img_20171010_124853](https://user-images.githubusercontent.com/12776071/31374209-a8953cca-adba-11e7-9295-796b87bc2a99.jpg)


On Portrait mode:
![img_20171010_124921](https://user-images.githubusercontent.com/12776071/31374177-83cab9a6-adba-11e7-9f3d-79db028d9467.jpg)

**Comment by swapnil106111** [comment]
@rtibbles  In portrait mode I have observed one thing -- when name of channel is longer, the username get shifted towards the right side and in few cases we do not see the username entirely. This enhancement is not of high priority.

![screenshot_2017-10-12-12-35-10](https://user-images.githubusercontent.com/12776071/31483644-d7b85a64-af4a-11e7-871f-b3eb77eb738a.png)
![screenshot_2017-10-12-12-35-41](https://user-images.githubusercontent.com/12776071/31483645-d825c1bc-af4a-11e7-8a37-3353c5fdb62e.png)

**Comment by harishbalachandran** [comment]
Hey @rtibbles and @christianmemije the second screen shot added by @swapnil106111 seams to be a bit of a concern and needs to be addressed in the final 0.4.6 version.

**Comment by rtibbles** [comment]
@indirectlylit raised this as a potential problem - my suggestion would be to use the collapsed channel representation that we do on mobile, does that seem reasonable?

You would no longer see the current channel title displayed in the app bar in portrait mode (there's only so much space!)

**Comment by indirectlylit** [comment]
>  collapsed channel representation that we do on mobile

That sounds fine to me if channel switching is uncommon.

(If channel switching is common, might be better to set a max width and truncate with a `...` ellipsis)

**Comment by harishbalachandran** [comment]
@indirectlylit @christianmemije @rtibbles, At present all our servers have only one channel, but in long term that will not be the case, hence the later suggested :

> (If channel switching is common, might be better to set a max width and truncate with a ... ellipsis)

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.7. Not showing username properly.

Portrait mode
![img_20171023_122714](https://user-images.githubusercontent.com/12776071/31875941-e15c0736-b7ed-11e7-841a-deb39a47062a.jpg)

**Comment by rtibbles** [comment]
@christianmemije shouldn't the channel name be collapsing here?

**Comment by rtibbles** [comment]
Fixed in #2504

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.8. Showing username properly. 

![img_20171027_113212](https://user-images.githubusercontent.com/12776071/32090044-06ca785c-bb0b-11e7-913d-7001c022643a.jpg)
