### ISSUE TITLE
Kolibri not running on windows 8.1

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2261]
## Summary

I have installed kolibri 0.5.0 on windows 8.1 but it is not working. I have set environment variable in the windows still it is not running. But when I installed Kolibri 0.4.1 in the same windows machine, it works.

Python Environment variable:
Variable name : KOLIBRI_SCRIPT_DIR
Variable value : C:\Python27\Scripts

## System information

 - Version: Kolibri 0.5.0
 - Operating system: Windows 8.1
 - Browser: Chrome
 - Python version : Python 2.7

## Screenshots

![screen shot 2017-09-25 at 5 06 40 pm](https://user-images.githubusercontent.com/12776071/30807269-bb72ccd6-a216-11e7-85aa-dde59641cefa.png)
![screen shot 2017-09-25 at 5 06 54 pm](https://user-images.githubusercontent.com/12776071/30807268-bb724388-a216-11e7-8bb6-eca30ff8b37a.png)
![screen shot 2017-09-25 at 5 07 22 pm](https://user-images.githubusercontent.com/12776071/30807267-bb71bfc6-a216-11e7-8ca0-e765c2b5808e.png)

**Comment by radinamatic** [comment]
@swapnil106111 Thanks for reporting this! :slightly_smiling_face: 

@mrpau-richard Could this be similar to other start issues reported on Windows 10?

**Comment by mrpau-richard** [comment]
@swapnil106111 I recommend you, install the latest [Pre-release](https://github.com/learningequality/kolibri/releases) of kolibri. 

During my testing I successfully ran the kolibri server, after I upgrade the Kolibri from `0.4.1` to `0.5.0`.
![screen shot 2017-11-23 at 10 43 16 am](https://user-images.githubusercontent.com/8663934/33166727-32f02cee-d076-11e7-8e43-7622cc9a762f.png)

But after I created a user account, I have this javascript error when I try to login that account.
![screen shot 2017-11-23 at 1 00 53 pm](https://user-images.githubusercontent.com/8663934/33166772-6923da40-d076-11e7-86b3-4e0551ac554d.png)

I install the [Kolibri 0.6.0](https://github.com/learningequality/kolibri/releases/download/v0.6.0/KolibriSetup-0.6.0.exe) and I didn't encounter any issue.

**Comment by mrpau-richard** [comment]
Hi @swapnil106111, Did you try to install the latest [pre-release](https://github.com/learningequality/kolibri/releases) of Kolibri windows installer? 
If you encounter the same issue, It would help if you can post here the `kolibri server log` file located at `C:\Users\YourCurrentUser\.kolibri`

**Comment by indirectlylit** [comment]
I'll close this unless we get indication that it's still a problem.

thanks all!

**Comment by radinamatic** [comment]
Not a problem for release 0.7, working a-Ok on Win 8.1! 👍 

![win8 1 start running - oracle vm virtualbox_111](https://user-images.githubusercontent.com/1457929/34094861-3fdab5e8-e3cf-11e7-9f0a-0313070fc066.png)
