### ISSUE TITLE
Classes page responsive issue

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2262]
## Summary

* 'Add a new class' button is NOT responding properly. The button was overlapping with text, in the middle of the screen. 
* Originally reported in https://docs.google.com/spreadsheets/d/1tYf6KP0t2CYMQmu7wHsfT47KPbTW0A0-8o_cPpQmUbM/edit#gid=0&range=31:31
## System information

* 0.6
* http://35.185.84.118

## How to reproduce

1. Sign in and visit the classes page under Facility.

**Comment by rtibbles** [comment]
See #2278 for screenshots.
