### ISSUE TITLE
Exercises not rendering on Android

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2263]
## Summary

* "There was an error showing this item" 
* Videos work, but all other content doesn't across phones and tablets
* Originally reported in https://docs.google.com/spreadsheets/d/1tYf6KP0t2CYMQmu7wHsfT47KPbTW0A0-8o_cPpQmUbM/edit#gid=0

## System information

 - 0.6 
 - http://35.185.84.118/learn/#/topics/c/9541b757bc234d439626a052cf7f87ca
 - Android 6
- VF tablet, LG Sunrise
- Chrome 

## How to reproduce

1. Visit http://35.185.84.118/learn/#/topics/c/9541b757bc234d439626a052cf7f87ca

**Comment by rtibbles** [comment]
Able to get any traceback from the tablet?

**Comment by rtibbles** [comment]
This was fixed in #2469
