### ISSUE TITLE
Khang was right - you *can* delete yourself as a superuser

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2272]
reported by @jonboiser 

This maroons you if you don't have another superuser to reinstate you. (refs #1985)

* go to facility > users
* select your own name (as superuser) > delete yourself
* get logged out
* try to log back in

**Comment by rtibbles** [comment]
Hrm, odd. This is specifically banned in the permissions, and has tests to check this case also.

**Comment by rtibbles** [comment]
We should add the same check for facility admins to super users also, then, just as an initial fix.

**Comment by christianmemije** [comment]
Front end fix was handled in #2298.

**Comment by rtibbles** [comment]
Backend fixed in #2316
