### ISSUE TITLE
reported local channel sizes are innaccurate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2274]
reported during 0.6 bug bashing by @jtamiace:

> Start import for a large channel, cancel process at early stage. After canceling import, it still says you have the channel and the full size of the channel, when that can't be the case (I stopped a channel import at 0.3% of a 72GB channel)

**Comment by aronasorman** [comment]
Fixed with #2573 -- the frontend now has an accurate file size based on what content has been marked as available.
