### ISSUE TITLE
UX issue previewing exam questions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2275]
reported by @khangmach during last thursday's hack session of 0.6

* Cannot preview selected exam questions IF number of exercises selected doesn't meet the number of exam questions entered
* Should be able to preview exercise questions regardless of how many I selected

To repro:

* navigate to coach exams
* create exam
* enter something like "30" for the exam question input field
* select first 1 or 2 exercises only
* try to preview exercise questions

**Comment by mrpau-eugene** [comment]
@indirectlylit should the admin still be able to continue creating the exam regardless of how many questions the admin has selected, or should it be just applicable only to the preview?

**Comment by indirectlylit** [comment]
(@khangmach correct me if I'm wrong)

The user should still be prevented from creating the exam - this change should only affect preview.

**Comment by khangmach** [comment]
Yup, the user should still be prevented from creating the exam. If the total questions I want is 40 and I've only selected exercises that give me 20 questions, I imagine the preview should still allow me to see a randomized set of 20 Q's. The main benefits of this is to allow the curator to get a bit more context about their selections. 

This is addressed in new exam creation designs, but that's still tbd on the roadmap.

**Comment by indirectlylit** [comment]
addressed in recent work
