### ISSUE TITLE
rename facility configuration -> settings

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2277]
because it's a shorter word

**Comment by DXCanas** [comment]
Mightn't this be a bit misleading, though? Account settings vs profile settings vs  account settings (there might be a distinction between the 2 soon?).

**Comment by indirectlylit** [comment]
maybe, maybe not? it's hard to speculate.

The distinction relies on the user knowing that they are in the 'facility' section

**Comment by indirectlylit** [comment]
discussion leading to this change: https://learningequality.slack.com/archives/C0LKG14NL/p1506379170000259
