### ISSUE TITLE
increase the top-margin of the hint button

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2289]
increase the top-margin of the hint button so that it's farther away from the input box

This is a short-term fix for 0.4.6 until we implement the full solution described in #2132

**Comment by christianmemije** [comment]
Addressed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/109 , waiting for a new release.

**Comment by benjaoming** [comment]
Fix has been merged to `release-v0.4.x` branch #2373
