### ISSUE TITLE
Translatable strings are not being properly updated on devserver

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2293]
## Summary

- Sometimes tr strings that are modified do not get properly updated.

## System information

 - Version: 0.6
 - Operating system: Ubuntu
 - Node 6.11.2

## How to reproduce

1. Try editing tr strings and check that they are updated in the UI. Pretty random.

## Real-life consequences 

- Development rage

**Comment by rtibbles** [comment]
Note that this is due to server side caching of the loaded JSON message files, need to make the caching conditional on DEBUG mode.
