### ISSUE TITLE
help text is unhelpful

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2294]
descriptions of two types of deployments are exactly the same

![image](https://user-images.githubusercontent.com/2367265/30944677-503aa0da-a3ae-11e7-9624-2bb625f1d881.png)

**Comment by jonboiser** [comment]
If that's the case, then why make them two separate options during onboarding?

At the last bug bash @DXCanas and I were talking about this step and how it wasn't super obvious to me how my choice at Onboarding Step 4 affected my experience with the app later on. My suggestion was that maybe this info about facility config could be shown up front instead of hidden inside the modal.

**Comment by indirectlylit** [comment]
correct text, from mockups:

![image](https://user-images.githubusercontent.com/2367265/30986501-809b0db0-a448-11e7-9850-fae971e2a0d9.png)

Also, the names are not currently internationalized

**Comment by indirectlylit** [comment]
also, the order in the modal is different from the order in the form, which is confusing: 

![image](https://user-images.githubusercontent.com/2367265/30986769-6c7943dc-a449-11e7-9f47-136b7d2c5ceb.png)

**Comment by DXCanas** [comment]
@jonboiser I agree that alternatives would be looking into. @jtamiace had some good rationale for the current design -- I think it'd be good to have a quick discussion about ways to communicate consequences!

**Comment by DXCanas** [comment]
@rtibbles @indirectlylit should I go ahead and wrap the preset names, or are we maintaining the freeze?

**Comment by rtibbles** [comment]
Wrap them - the worst that will happen is that they don't get translated (which is no change).

**Comment by DXCanas** [comment]
@indirectlylit Would changing the default also affect the order of the options?

**Comment by DXCanas** [comment]
@rtibbles should I update the default option in the JSON too?

**Comment by indirectlylit** [comment]
yes - recommend:

* [x] self-managed
* [ ] admin-managed
* [ ] informal

**Comment by rtibbles** [comment]
Yes, keep it updated in the JSON as well!
