### ISSUE TITLE
remove 'name' attribute from facility presets file make sure it's not user-facing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2296]
Currently the ['facility presets' file](https://github.com/learningequality/kolibri/blob/develop/kolibri/auth/constants/facility_configuration_presets.json) includes a 'name' string. However, this is not internationalized and might confuse developers into actually displaying it - so we should just remove it.

**Comment by indirectlylit** [comment]
This name appears to be propagated out on the python side, e.g. into the `FacilityDataset` model. Not sure what it's actually used for?

**Comment by luna215** [comment]
Should I remove the string attribute from formal, nonformal, and informal?

**Comment by indirectlylit** [comment]
yes, please!

**Comment by luna215** [comment]
@indirectlylit Should I also remove the line in `facility_presets.py` that uses the name attribute?

**Comment by indirectlylit** [comment]
good catch!

@rtibbles should confirm, but I believe we can change those lines to:

```python
choices = [(key, key) for key in presets]
```

Not quite related, but I'd recommend we update the presets file to use the user-facing strings and migrate existing data, because (my understanding is that) our presets don't actually map cleanly to the formal/nonformal/informal pedagogy concepts:

```json
{
  "admin-managed": {
    "mappings": {
      "learner_can_edit_username": false,
      "learner_can_edit_name": false,
      "learner_can_edit_password": false,
      "learner_can_sign_up": false,
      "learner_can_delete_account": false,
      "learner_can_login_with_no_password": true
    }
  },
  "self-managed": {
    "default": true,
    "mappings": {
      "learner_can_edit_username": true,
      "learner_can_edit_name": true,
      "learner_can_edit_password": true,
      "learner_can_sign_up": true,
      "learner_can_delete_account": true,
      "learner_can_login_with_no_password": false
    }
  },
  "informal": {
    "mappings": {
      "learner_can_edit_username": true,
      "learner_can_edit_name": true,
      "learner_can_edit_password": true,
      "learner_can_sign_up": false,
      "learner_can_delete_account": true,
      "learner_can_login_with_no_password": false
    }
  }
}
```

**Comment by rtibbles** [comment]
The second value is intended as a human readable label, so I would rather update it to a readable label if possible, https://docs.djangoproject.com/en/2.0/ref/models/fields/#choices - it does not get used in the frontend, unless you access the Django admin interface.

**Comment by luna215** [comment]
Should we close this issue?

**Comment by indirectlylit** [comment]
yes, thanks!
