### ISSUE TITLE
add session timeout

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2310]
We should add a session timeout so that when multiple students share a tablet, they don't share progress. Let's choose a reasonable default for now. Maybe 4 hours?

The session should also end when the browser is closed.

We can explore making it configurable by the admins in a future release.

**Comment by jonboiser** [comment]
I think this was a feature request from Harish awhile back #2131.

**Comment by indirectlylit** [comment]
exactly - thanks for the back-reference

**Comment by indirectlylit** [comment]
closing as duplicate of the above
