### ISSUE TITLE
Enrolling a large number (~10) of learners into a class causes an error

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2325]
Originally discussed in in #2073.

Batch enrolling Learners into a class creates 1 request per Learner. When enrolling multiple learners, this seems to cause a race condition where the database can be locked performing one transaction while another one is being attempted.

One proposed solution is to allow the relevant endpoint to accept many learners to add to a class, so only one request is made for the whole batch.

**Comment by rtibbles** [comment]
Simplest way to do this is probably with this: https://pypi.python.org/pypi/djangorestframework-bulk and then a relevant enhancement on the frontend to allow bulk creation.

**Comment by jonboiser** [comment]
I haven't personally tried this, but it's possible this can also happen when batch moving learners in/out of groups as a Coach. There is a similar checkbox-based UI, and it POSTs to the same `memberships` endpoint.

**Comment by rtibbles** [comment]
Seems likely, @jonboiser!

**Comment by rtibbles** [comment]
Also seems likely that a batch move would also require deleting the old memberships in bulk too, so I'll add support for bulk deletion as well.
