### ISSUE TITLE
unactivated exams are visible to learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2328]
This should probably fixed on the server-side so that learners are completely blocked from any access to unactivated exam objects.

coach view:

![image](https://user-images.githubusercontent.com/2367265/31104897-e5a33242-a794-11e7-91c7-491d1d0b6467.png)

learner view:

![image](https://user-images.githubusercontent.com/2367265/31104910-f5112edc-a794-11e7-997c-29554dc41849.png)

**Comment by rtibbles** [comment]
This is deliberate. If a user has engaged with an exam, they continue to see their score for it.

**Comment by indirectlylit** [comment]
The exam never been activated.

However, I did make a mistake: I was looking at 'Learn' with the same coach user that I created the exam with.
