### ISSUE TITLE
Erratic time is shown in 'Last Activity' tab within 'Coach' Report

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2330]
## Summary
While using the real-time coach report in class, the last activity time shown under the "Last Activity" tab comes in negative millions (-233,567,677 secs ago) instead of (12 seconds ago).

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.4.5
 - Operating system: Ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1. Login with coach user.
2. Select coach.
3. Select the class.
4. Click on Recent tab.

## Screenshots
![whatsapp_image_2017-09-30_at_5 38 53_pm](https://user-images.githubusercontent.com/12776071/31110919-f0fb3e80-a827-11e7-872f-41d56ea19c4b.jpeg)

**Comment by indirectlylit** [comment]
cc @rtibbles any chance this has been addressed by recent work?

**Comment by rtibbles** [comment]
That was only on exam timestamps, I've not heard any additional reproductions of this though.

**Comment by swapnil106111** [comment]
@rtibbles @indirectlylit We faced this issue only in one server but after that we didn't face any issue related to the erratic time in coach report. We will let you know this issue if we face such behaviour again in the future.

**Comment by indirectlylit** [comment]
thank you for the update @swapnil106111 

I've added a new issue above to try and handle these cases better. If you run into it again, please re-open
