### ISSUE TITLE
Deleting the channel after canceling import causes the server crash

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2342]
## Summary
When importing a channel, refresh the page and then cancel the import. Then without refreshing the page again, delete the channel. Since the channel content doesn't exist, it will show an error and make the server crash. However, the logging looks fine as there were no error messages in the terminal. I can only restart the server by deleting the `.kolibri` folder first.

## System information

 - Version: 0.6
 - Operating system: Mac OS
 - Browser: Chrome

## How to reproduce

1. Import a channel
2. Refresh the page
3. Cancel the import
4. Delete the channel

## Screenshots

![kolibrierror](https://user-images.githubusercontent.com/19424916/31193472-0a874c82-a8f9-11e7-9437-6112b0f250b3.gif)

**Comment by jonboiser** [comment]
@lyw07 In the latest 0.6, the Delete Button should be disabled at the point you click delete. Also, the channel should be removed from the list after clicking cancel. I'll try to reproduce what you're seeing.

The UI tries to block people from deleting DBs are not there, but it is still possible for two separate users to attempt a deletion at the same time. This will still cause an error, but in the UI this error is swallowed to not be too confusing.

**Comment by lyw07** [comment]
@jonboiser Thank you for your explanation. I'll test on the lastest 0.6 and update the issue from there.

**Comment by lyw07** [comment]
Confirmed that the latest 0.6 doesn't have this issue anymore. Closing this now.

**Comment by lyw07** [comment]
Confirmed that the latest 0.6 doesn't have this issue anymore. Closing this now.
