### ISSUE TITLE
Don't use beforeDestroy to affect tracking and progress logging logic

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2355]
Vue lifecycle hooks - particularly `beforeDestroy` - should not be used to trigger application logic.

The vue component lifecycle hooks are tied to the DOM lifecycle, not the application lifecycle. `beforeDestroy` should only be used for low-level cleanup operations like removing DOM event listeners, clearing timers, and cleaning up callbacks.

Application logic that might currently be triggered by `beforeDestroy` should instead be triggered by whatever vuex action or state change actually _caused_ the component to be destroyed.

-----

refs:

* https://github.com/learningequality/kolibri/pull/2034#issuecomment-325529393, [resulting change](https://github.com/learningequality/kolibri/pull/2045/files#diff-0ca7a9fe05f901d2fb1805decc333920L293)
* #2354
* #4018

-----

Some specific things to look for:

* `this.$emit('stopTracking');`
* `this.saveAttemptLogMasterLog(false);`
* `this.stopTracking();`

**Comment by rtibbles** [comment]
Won't fix.
