### ISSUE TITLE
migrate testing info to docs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2362]
note from @radinamatic https://github.com/learningequality/kolibri/pull/2353#discussion_r142910435

Migrate [info in google doc](https://docs.google.com/document/d/1CG4Z0hofN0ipsny9mDf1xr2C_eY5c-T2nUbhlz2eZjA/edit#heading=h.d0614gv8ru72) to the 'manual testing and qa' page

**Comment by Lewiscowles1986** [comment]
is this complete, or not? It looks like the PR merged, then #2427 happened doesn't seem to track next steps.

**Comment by indirectlylit** [comment]
Hi @Lewiscowles1986 this is not yet complete. If you'd like to tackle it, I'd recommend also doing https://github.com/learningequality/kolibri/issues/5945 at the same time.

Here are some helpful high-level links:

* [Developer docs on RTD](https://kolibri-dev.readthedocs.io/en/develop/index.html)
* [Developer docs source](https://github.com/learningequality/kolibri/tree/develop/docs)
* [Accessibility resources](https://github.com/learningequality/kolibri/wiki/Accessibility-Resources-(Tools)) (not currently in developer docs)
* [Testing with VMs](https://docs.google.com/document/d/1CG4Z0hofN0ipsny9mDf1xr2C_eY5c-T2nUbhlz2eZjA/edit) (not currently in developer docs)

Here's what I would recommend:

1. Make a new directory, _docs/manual_testing/_ and an index file _docs/manual_testing/index.rst_, similar to how _docs/contributing/_ is currently set up
2. Move _docs/manual_testing.rst_ to  _docs/manual_testing/overview.rst_ and link to it from _docs/manual_testing/index.rst_
3. Create a new file _docs/manual_testing/a11y_resources.rst_ and migrate the [Accessibility resources](https://github.com/learningequality/kolibri/wiki/Accessibility-Resources-(Tools))  to it. Link to it from _docs/manual_testing/index.rst_
3. Create a new file _docs/manual_testing/virtual_machines.rst_ and migrate the [Testing with VMs](https://docs.google.com/document/d/1CG4Z0hofN0ipsny9mDf1xr2C_eY5c-T2nUbhlz2eZjA/edit)  to it. Link to it from _docs/manual_testing/index.rst_

thanks!

**Comment by Lewiscowles1986** [comment]
Questions:

1. RE: #5945 is it just the accessibility? The rest looks like scrap paper that isn't part of docs as much as "something else".
2. I sort of went a slight different way regarding structure to try to make docs as small (parts) as possible). Happy to revise on PR if needed

**Comment by indirectlylit** [comment]
> RE: #5945 is it just the accessibility? 

Yes, for the purpose of this PR it will just be the a11y page. Once that has a new home I can take care of the rest of the wiki cleanup

> I sort of went a slight different way regarding structure to try to make docs as small (parts) as possible). Happy to revise on PR if needed

Will review next week - thanks
