### ISSUE TITLE
replace unscoped styles with 'deep' option

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2367]
The vue loader recently got a new 'deep' feature [added to scoped styles](https://vue-loader.vuejs.org/en/features/scoped-css.html):

![image](https://user-images.githubusercontent.com/2367265/31299632-47b5444a-aaa4-11e7-9774-9b22b6143581.png)

that means that unscoped styles targeting child components can be updated

**Comment by rtibbles** [comment]
Sweet!
