### ISSUE TITLE
Allow internationalization of known content licenses

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2371]
## Summary

Currently all content licenses are hard coded into the database. It would be good to be able to translate known content licenses into the interface language.

**Comment by radinamatic** [comment]
Bumping up this, as it is still extant on 0.11:

#### Learn

![ubuntu 16 04 3 0 11b1 in-context running - oracle vm virtualbox_045](https://user-images.githubusercontent.com/1457929/46926539-7afa5080-d031-11e8-92fb-f32cd3452a45.png)


#### Coach > Preview Lesson resource

![workspace 1_044](https://user-images.githubusercontent.com/1457929/46926549-86e61280-d031-11e8-98f3-67e5621e9f2b.png)

(Crowdin window behind, I was looking for the string making sure I did not miss the translation, before finding this old issue)

**Comment by indirectlylit** [comment]
unfortunately we'll probably have to wait for 0.12 on this since it requires new strings

**Comment by radinamatic** [comment]
Agreed, but there was no `0.12` milestone label yet.

**Comment by indirectlylit** [comment]
true :)

**Comment by indirectlylit** [comment]
todo: look into short-term possibilities for arabic and spanish

**Comment by indirectlylit** [comment]
removing from 0.12 in lieu of https://github.com/learningequality/kolibri/issues/5148

**Comment by indirectlylit** [comment]
refs:

* https://github.com/learningequality/kolibri/issues/5569
* https://github.com/learningequality/kolibri/pull/5205
