### ISSUE TITLE
Close/Back modal buttons do not have visual focus outline

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2380]
## Summary

Buttons are focusable, and modals can be closed with the `Enter` key once the `X` button is in focus, it's is just that there is no visual indication that focus actually grabbed it.

Modals checked:
- Welcome to Kolibri!
- Add new account
- Add new class
- Import - choose the source

## System information

 - Version: `kolibri-0.6.dev020171007224512-git.pex`
 - Operating system: Ubuntu 17.04
 - Browser: Chrome

**Comment by radinamatic** [comment]
This should be something for the styleguide, right @indirectlylit ? :slightly_smiling_face:

**Comment by indirectlylit** [comment]
Thanks - the core modal component still needs to be refactored as per the new guidelines. added a reference to this issue [in the google doc](https://docs.google.com/document/d/1102ubWXHSkWEWibHHfni9-cwc16PcQiocBWmOJrEGag/edit).

(Note that once this is fixed, it doesn't actually get documented in the style guide per se, but is instead simply baked into the core modal component.)

**Comment by radinamatic** [comment]
> Thanks - the core modal component still needs to be refactored as per the new guidelines. added a reference to this issue in the google doc.

Thanks, I made one comment in the doc!

> (Note that once this is fixed, it doesn't actually get documented in the style guide per se, but is instead simply baked into the core modal component.)

Understood, let's first fix the component to be accessible, and then update the style guide document to correctly reference the requirement.

I amended the title to reflect that both `Go back` (arrow) and `Close` (X) buttons have this issue.
