### ISSUE TITLE
Rename Buildkite assets for clarity

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2382]
## Summary

When downloading builds from `buildkite/kolibri/assets` details link, filenames are too complex and difficult to distinguish. 

![selection_655](https://user-images.githubusercontent.com/1457929/31338580-259d1370-ad00-11e7-9c8a-f890d2515631.png)

These links do save some time, but filenames are longer then those downloaded individually from Buildkite (green). Could we make them shorter? For example, get rid of the useless prefix and various `%2F` in between in order to make this:

`kolibri%2Fbuildkite%2Fbuild-2313%2F2755%2Fkolibri-0.6.dev020170929214748-git.pex` (red)

into this:

`build-2313-kolibri-0.6.dev020170929214748-git.pex` (yellow)

Or just `kolibri-0.6.dev020170929214748-git.pex` if those build details are not necessary.

![selection_653](https://user-images.githubusercontent.com/1457929/31339729-198fddf2-ad04-11e7-8b85-d1e0125600e4.png)

**Comment by benjaoming** [comment]
@radinamatic it looks like the path is translated into a filename

`kolibri%2Fbuildkite%2Fbuild-2313%2F2755%2F` means `kolibri/buildkite/build-2313/2755/`. This could just be stripped off or just put the buildkite build number at the end of the file name.

One important thing here: These builds are for testers, not end users.

Nice Ubuntu theme :)

**Comment by radinamatic** [comment]
+1 for stripping all the unnecessary! :+1: 
 

> These builds are for testers, not end users.

The issue was filed for totally selfish reasons... :smiling_imp: 

> Nice Ubuntu theme :)

GNOME dark :heart:
