### ISSUE TITLE
AJAX error when logged out because of idle session

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2390]
## Summary

Currently, the automatic logout (session idle time) kicks in after 5 minutes. Issue #2389 is addressing if this should be upped.

Regardless, we shouldn't be showing AJAX errors to users that are logged out. Case in question:

![image](https://user-images.githubusercontent.com/374612/31355230-b8d8ffb2-ad39-11e7-8fe8-7f0a6cc1da44.png)

The full error:

```
{ "request": { "path": "/api/contentsessionlog/0f60bd08465cb59a647677e631cafa41/", "method": "PATCH", "entity": "{\"channel_id\":\"8b4d3e6d3d4842ba8ea658335b5dd252\",\"content_id\":\"a973b96308c053f781bdcb51ec3563b2\",\"kind\":\"exercise\",\"start_timestamp\":\"2017-10-09T19:24:38.393Z\",\"end_timestamp\":\"2017-10-09T19:34:52.047Z\",\"time_spent\":608.3469999999996,\"progress\":0,\"extra_fields\":\"{}\",\"user\":\"7cc57c59baf63db55726b2c264766f8e\",\"pk\":\"0f60bd08465cb59a647677e631cafa41\"}", "headers": { "X-CSRFToken": "aYMYM3COfdBimconahGJyQpCp3SMG2QG", "Content-Type": "application/json", "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2" }, "canceled": false }, "url": "/api/contentsessionlog/0f60bd08465cb59a647677e631cafa41/", "raw": {}, "status": { "code": 403, "text": "Forbidden" }, "headers": { "Allow": "GET, PUT, PATCH, DELETE, HEAD, OPTIONS", "Content-Type": "application/json", "Date": "Mon, 09 Oct 2017 19:34:52 GMT", "Server": "0.0.0.0", "Transfer-Encoding": "chunked", "Vary": "Accept, Cookie", "X-Frame-Options": "SAMEORIGIN" }, "entity": { "detail": "Authentication credentials were not provided." } } 
```

Btw I'm not sure if it's kosher to dump the CSRF token in a text that you expect people to share -- okay okay this is an offline app, but I mean we might end up copying the code to use it on an online site (and it does run in online demos). In Django, there is a filter on tracebacks etc. that's sent by email and displayed when `DEBUG=True`.

I've added 0.4 as a milestone for this, question is if we can easily solve it for 0.4 or if it's easier to solve in a later version? @indirectlylit ?

**Comment by rtibbles** [comment]
We should solve this later - we can reduce the incidence of this by satisfactorily resolving #2389

**Comment by indirectlylit** [comment]
closing in favor of #1477
