### ISSUE TITLE
getting error after 5 minute of session

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2393]
## Summary
After 5 minute of accessing kolibri application, we see the error which is attached in screenshots. Even after refreshing the page it is showing same error. 

## System information

 - Version: Kolibri0.4.6Beta1
 - Operating system: Ubuntu 14.4
 - Browser: Chrome

## How to reproduce

1. Login with learner.
2. Complete a mastery by solving exercise.
3. Use kolibri on tablet for 5 minutes.

## Screenshots
![screenshot from 2017-10-10 15_10_43](https://user-images.githubusercontent.com/12776071/31387093-c38ae1f2-ade6-11e7-82ca-07c40a991abd.png)

![img_20171010_181421](https://user-images.githubusercontent.com/12776071/31387720-04d51612-ade9-11e7-97c5-6be710cee88b.jpg)

[VID_20171010_174319 - converted with Clipchamp.mp4.zip](https://github.com/learningequality/kolibri/files/1371946/VID_20171010_174319.-.converted.with.Clipchamp.mp4.zip)

[VID_20171010_144618.mp4.zip](https://github.com/learningequality/kolibri/files/1371966/VID_20171010_144618.mp4.zip)

**Comment by benjaoming** [comment]
@swapnil106111 thanks for reporting this - it's also what I just reported in #2390 - so will close this. As you can see over the other issue, we might wait to fix this until 0.7 because of priorities.. but it should definitely be fixed.
