### ISSUE TITLE
File presets are not translated

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2394]
## Summary

The presets used to describe different file formats/types is not translatable/translated - this shows in the frontend like this:

![image](https://user-images.githubusercontent.com/1680573/31397747-1d515694-ade7-11e7-8471-4c4af49d360e.png)

## System information

 - Version: Develop

**Comment by indirectlylit** [comment]
This is in LE-utils:

https://github.com/learningequality/le-utils/blob/4f8b774577b952340e66d242fd66096b7c14d123/le_utils/constants/format_presets.py
