### ISSUE TITLE
add language information to exams for proper RTL/LTR alignment

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2395]
## Summary

Currently, when creating an exam, we attach no language information to it, so we do not know the language of the title of the exam. This means when the exam is rendered, we do not know the proper way to LTR/RTL the exam title.

(by default, the RTL/LTR will be set by the language of the interface. The main possibly slightly jarring experience will be RTL aligned English text in an Arabic interface or vice versa)

**Comment by jonboiser** [comment]
I think these issues are generally handled by setting the attribute `dir=auto` in the template, so the browser can figure things out based on the font.
