### ISSUE TITLE
Video tracker and seek is not RTL compatible

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2397]
## Summary

The media player tracker gets RTL flipped (when it shouldn't be). Preventing this flip should ensure good compatibility.

## System information

 - Version: Develop

**Comment by christianmemije** [comment]
@rtibbles Is there some special markup to prevent certain css from being flipped?

**Comment by rtibbles** [comment]
Yes - the docs for it are here: http://rtlcss.com/learn/usage-guide/control-directives/

Do we import any css from videojs, or is it all internal to our code base?

**Comment by christianmemije** [comment]
Okay cool!

Yes we [import the videojs style sheet](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/media_player/assets/src/views/index.vue#L355) and then apply custom css to create a skin. Will self-assign this issue.

**Comment by rtibbles** [comment]
Fixed in #2735
