### ISSUE TITLE
Standard installer icon base

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#24]
All installers must have the following icons as the base for their GUI launcher:
1. Kolibri not started systray icon.
2. Kolibri starting up systray icon.
3. Kolibri started systray icon.
4. Kolibri application menu icon.

Installers across different platforms may make derivations of this as their platform's standard practices dictate.

@jtamiace or @66eli77  would you or someone else be able to make these icons?

Here are the platforms we've indicated that we'll support (2/4/2016):
- Android (version?)
- OS X Yosemite
- Windows XP, 7, 8, 10
- Ubuntu 14.04 and above

**Comment by benjaoming** [comment]
Not sure you'd agree but Ubuntu's programmes conform to a specific theme in the notification area:

![screenshot from 2016-02-04 17 50 03](https://cloud.githubusercontent.com/assets/374612/12822315/cd37bc88-cb67-11e5-8edb-22ea372da614.png)

**Comment by aronasorman** [comment]
Yup! Hence:

> Installers across different platforms may make derivations of this as their platform's standard practices dictate.

Same thing for OS X too. Simple colors are good. But the general shapes and style should be similar.

**Comment by benjaoming** [comment]
Ah okay, I thought you meant to create a one-size fits all.. because that most likely won't work. But simple flat stuff that's easy to adopt will :+1:

**Comment by indirectlylit** [comment]
migrating here - https://trello.com/c/4ko3tLDS/693-design-icons-for-each-platform-s-server-gui

**Comment by indirectlylit** [comment]
re-opening: this is still a to-do item, and that trello board was deprecated

**Comment by indirectlylit** [comment]
This is our new standard icon:

![kolibri](https://user-images.githubusercontent.com/2367265/82719259-c2a97b00-9c5d-11ea-9d1d-740612c2f377.png)
