### ISSUE TITLE
Don't flip checkboxes in RTL mode

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2405]
## Summary

Material spec specifies that checkboxes should not be flipped in RTL mode

![image](https://user-images.githubusercontent.com/1680573/31399481-c263f25e-adec-11e7-873f-3c29a1a09bd5.png)

**Comment by indirectlylit** [comment]
I don't think this is accurate: https://material.io/guidelines/usability/bidirectionality.html

the check icons are not flipped, but checkboxes do appear to the right of text. So the current behavior is correct.

**Comment by rtibbles** [comment]
Ah yes, my eyes deceived me!
