### ISSUE TITLE
Exercise editor allows publication of incomplete questions

### ISSUE THREAD

**Issue by niustephanie** [learningequality/kolibri#2407]
## Summary
Exercises can be published when missing a question, answer, or both. Question is marked as "Incomplete" but does not prevent publishing (is this desired behavior)?

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Develop
 - Operating system: Mac OS X
 - Browser: Chrome

## Screenshots

![image](https://user-images.githubusercontent.com/10249385/31402315-7d32d430-adaa-11e7-951d-4481332b9070.png)

**Comment by indirectlylit** [comment]
migrated to https://github.com/fle-internal/content-curation/issues/471
