### ISSUE TITLE
Race condition between setting of urls on KolibriGlobal and invocation of resource fetching

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2409]
## Summary

URLs for the API Resource layer are set in the django template by use of `django_js_reverse`. Unfortunately, until that part of the template is executed, the urls object is either undefined (0.4, 0.5) or empty (0.6+) - which makes any URLs for APIResources error or return undefined.

We should fix this by properly signalling when the URLs are loaded in order to allow the Resource layer to defer any API calls until then.

Note: this is a low risk race condition, and I only came across it will changing something in the heartbeat code that invokes during the core-app constructor.

**Comment by rtibbles** [comment]
That sounds familiar.

**Comment by indirectlylit** [comment]
https://github.com/learningequality/kolibri/issues/1161

**Comment by rtibbles** [comment]
Yeah, that one was due to something weird in the namespacing of URLs iirc.

**Comment by indirectlylit** [comment]
closing as wont-fix - there are workarounds.

at a high level: _don't call resource functionality during core app initialization_. This means specifically in `core-app/index.js` or `CoreAppConstructor`
