### ISSUE TITLE
Coach report under learner tab's answer history

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2417]
## Summary
After completing mastery of challenge set for **learner**. When I login with teacher id, I can not see all the questions in answer history. 
There is mismatch in the answer history and the questions attempted history.

## System information

 - Version: Kolibri 0.4.6beta1
 - Operating system: Ubuntu14.04
 - Browser: Chrome

## How to reproduce

1. Login with learner.
2. Solve complete exercise of any subtopic.(Reach mastery level)
3. Then, Login with coach user.
4. Click on Coach tab then go to learners.
5. Go to the topic that learner solved.

## Screenshots

Completed mastery by solving more than 4 questions but showing only 2
![img_20171011_172137](https://user-images.githubusercontent.com/12776071/31442452-22e7c188-aeb4-11e7-8d66-427156f2fe50.jpg)

In question 1, question does not change but correct option keeps changing 
![img_20171011_172144](https://user-images.githubusercontent.com/12776071/31442453-23abd000-aeb4-11e7-8f1d-cdd993d2cfbd.jpg)
![img_20171011_172147](https://user-images.githubusercontent.com/12776071/31442454-242e2b36-aeb4-11e7-8b50-aec96a8ba52c.jpg)
![img_20171011_172150](https://user-images.githubusercontent.com/12776071/31442456-24d58322-aeb4-11e7-9180-a1ac5adfa33b.jpg)
![img_20171011_172152](https://user-images.githubusercontent.com/12776071/31442461-29ef7fc0-aeb4-11e7-87aa-802ba8cf3a31.jpg)
![img_20171011_172154](https://user-images.githubusercontent.com/12776071/31442463-2a681534-aeb4-11e7-94e9-81cab0147769.jpg)

**Comment by DXCanas** [comment]
@swapnil106111 I'm having some trouble replicating this. Is this a fresh database or a continuation of the previous one? 

Also,

> In question 1, question does not change but correct option keeps changing
This is really bizarre. Can you describe exactly what it is you click on when you complete the exercise? Is this after hitting "next item" or do you go back and select another exercise manually?

**Comment by swapnil106111** [comment]
@DXCanas  I am using existing database.

Process : 
1. Completed the mastery for that topic.
2. Click on next item.
3. logout from learner user and login with coach user.
4. Went to coach report of user and I observe below behaviour:

What I observe:
1. Instead of attempting 4 questions showing only 2 in top left corner of answer history.
2. And In question 1 attempts, it must show options of question 1 only but it is keep changing.

Channel on which I saw above observation :
Channel ID : 8fc515793aad4e52b490b03c48ad21de (Maharashtra state English Medium).

Path : BalBharati - 3 - Symmetry - Symmetry about a line - Level 1

**Comment by DXCanas** [comment]
I can't replicate this at all.

This behavior is happening for newly completed exercises (not records that existed before the update)? Could you please post a shot of your console after completing an exercise, but before hitting next?

**Comment by swapnil106111** [comment]
@DXCanas  @rtibbles  Tested on Kolibri 0.4.7.  Still facing same problem. 


![111](https://user-images.githubusercontent.com/12776071/31876126-c7c45976-b7ee-11e7-990e-296e5892af0a.png)
![112](https://user-images.githubusercontent.com/12776071/31876127-c8116c3e-b7ee-11e7-92de-d1feea25334a.png)

**Comment by rtibbles** [comment]
Have reproduced locally.

**Comment by rtibbles** [comment]
Fixed in #2530

**Comment by swapnil106111** [comment]
@rtibbles  Tested on Kolibri 0.4.8.  Now, it is recording all answer history in coach report.

![2417_2](https://user-images.githubusercontent.com/12776071/32101268-2740759e-bb35-11e7-9f21-6a911dbe3355.png)

![2417_](https://user-images.githubusercontent.com/12776071/32101267-26d189a4-bb35-11e7-98c0-65f9ae27101f.png)

We will re-open this issue if we face such behaviour in future.
