### ISSUE TITLE
Z indices are being modified

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2422]
## Summary

Somewhere in our webpack build, z indices are being reduced. Not sure if this is done per vue file or plugin. This is causing issues.

Example 

![127 0 0 1-8000-learn-](https://user-images.githubusercontent.com/7193975/31468209-a75f40e4-ae91-11e7-9520-52f3100d49cd.png)

## System information

 - Version: Develop

## How to reproduce

1. Open a modal
2. Inspect the modal-overlay z-index. Should be 24, but was changed to 5

**Comment by rtibbles** [comment]
Guessing this would have to be happening in postcss? Can't think what else would be actively modifying css values.

**Comment by indirectlylit** [comment]
https://github.com/vuejs-templates/webpack/issues/614

**Comment by rtibbles** [comment]
Also possible that webpack-rtl-plugin (which depends on cssnano which uses https://www.npmjs.com/package/postcss-zindex) may be playing a role here.
