### ISSUE TITLE
Invalid exam report

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2426]
## Summary
When exam has multiple choice questions with more than 3 correct answers, it shows invalid exam report even learner gave correct answers of a question.

Channel Id : e4793bc39a884583a4e65c37fdb43e5f (Multiple select).
Create exam on above channel ID.

## System information

 - Version: Kolibri 0.4.6beta1
 - Operating system: Ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1. Assign exam(which contains multiple choice questions more than 3 correct answer) to the learner.
2. Login with learner.
3. Give the exam.
4. See the exam report of the learner.

## Screenshots
[IMG_20171012_164103715.mp4.zip](https://github.com/learningequality/kolibri/files/1379094/IMG_20171012_164103715.mp4.zip)

![12345](https://user-images.githubusercontent.com/12776071/31493750-1f945180-af6e-11e7-816d-68cbe58a16ba.png)

**Comment by rtibbles** [comment]
Is it incorrect, or does it just show unnecessary additional attempts? Is the last attempt what the student actually entered?

**Comment by swapnil106111** [comment]
@rtibbles  Same thing happened with radio button and text input answer.

For radio button:
If learner select wrong answer in exam and after 15-20 seconds learner realised that another answer is correct, next selected answer is not replicating in exam report.

![final1](https://user-images.githubusercontent.com/12776071/31544105-e084e17a-b036-11e7-9669-0f2ab183e587.png)
![final2](https://user-images.githubusercontent.com/12776071/31544106-e0c2d3ae-b036-11e7-9f08-be83244c06c5.png)
![final3](https://user-images.githubusercontent.com/12776071/31544107-e1193ab4-b036-11e7-8921-eede6cea3c3e.png)
![final4](https://user-images.githubusercontent.com/12776071/31544109-e16b2590-b036-11e7-9f68-09b67a607591.png)
![final5](https://user-images.githubusercontent.com/12776071/31544110-e1d1aafe-b036-11e7-970c-c38cf81b50aa.png)
![final6](https://user-images.githubusercontent.com/12776071/31544111-e23b37e4-b036-11e7-8bef-af4f8a735626.png)
![final7](https://user-images.githubusercontent.com/12776071/31544113-e2a2b7b6-b036-11e7-8631-6a025a5b9db9.png)
![final8](https://user-images.githubusercontent.com/12776071/31544114-e35c5234-b036-11e7-9993-1d600768daa5.png)
![final9](https://user-images.githubusercontent.com/12776071/31544115-e3c6d230-b036-11e7-9f08-b88edf9a520c.png)
![final10](https://user-images.githubusercontent.com/12776071/31544116-e45f86b0-b036-11e7-8091-1e5cf64160bc.png)


For text input answer:

Try to to give wrong text input answer in exam for more than three times and keep atleast 10 second of difference in text box answer changing and see exam report for input text answer.

![text1](https://user-images.githubusercontent.com/12776071/31544200-4ec1a290-b037-11e7-9e0c-952e17419fac.png)
![text2](https://user-images.githubusercontent.com/12776071/31544201-4f2cffe0-b037-11e7-8842-8a0cb5f2c350.png)
![text3](https://user-images.githubusercontent.com/12776071/31544202-4f95636e-b037-11e7-98b4-14a376b53d5d.png)
![text4](https://user-images.githubusercontent.com/12776071/31544203-501b5172-b037-11e7-994a-090a09d07d6f.png)
![text5](https://user-images.githubusercontent.com/12776071/31544204-5083a128-b037-11e7-9151-91e5df0e9bee.png)
![text6](https://user-images.githubusercontent.com/12776071/31544205-50f75d2a-b037-11e7-9df0-1492d19aef72.png)
![text7](https://user-images.githubusercontent.com/12776071/31544206-5165fa0a-b037-11e7-87de-b21275c5ed5f.png)
![text8](https://user-images.githubusercontent.com/12776071/31544207-52177de8-b037-11e7-9e00-220a1cc40e38.png)
![text9](https://user-images.githubusercontent.com/12776071/31544208-5291866a-b037-11e7-82db-608e67314b09.png)
![text10](https://user-images.githubusercontent.com/12776071/31544210-534e5fc4-b037-11e7-99de-e1adc37f8ffc.png)
![text11](https://user-images.githubusercontent.com/12776071/31544212-53c44572-b037-11e7-8d40-6e39a0bdc62b.png)
![text12](https://user-images.githubusercontent.com/12776071/31544213-54337816-b037-11e7-9a20-9a6f38dae22c.png)
![text13](https://user-images.githubusercontent.com/12776071/31544214-5486cd7c-b037-11e7-970b-b67fedf1d0d1.png)
![text14](https://user-images.githubusercontent.com/12776071/31544216-5501d8c8-b037-11e7-8cb9-da39c6675be7.png)
![text15](https://user-images.githubusercontent.com/12776071/31544218-55741276-b037-11e7-9032-299bf5237db9.png)
![text16](https://user-images.githubusercontent.com/12776071/31544219-563a5cc4-b037-11e7-9d3d-8952ee6e903b.png)

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.4.7. Exam report showing valid report.

![today_1](https://user-images.githubusercontent.com/12776071/31886591-98e0c03a-b812-11e7-8e03-ac2f1a7a441b.png)
![today_2](https://user-images.githubusercontent.com/12776071/31886593-9914b4bc-b812-11e7-872c-5d21591b5637.png)
![today_3](https://user-images.githubusercontent.com/12776071/31886595-99463f14-b812-11e7-9ac8-20a9d23ef87c.png)
