### ISSUE TITLE
Add Windows installer signing for releases to buildkite process

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2450]
## Summary

Automatically sign our Windows installer releases.

**Comment by indirectlylit** [comment]
@mrpau-richard we don't need to do this automatically, but do we have a mechanism for manual signing?

**Comment by mrpau-richard** [comment]
@indirectlylit Yeah, We can manually sign it, in our Windows development machine. But it would be good if you can also manually sign it own your side. 
Do I need to create`Script` and a documentation on how to mannually sign it?

**Comment by indirectlylit** [comment]
that would be great - maybe add the documentation to the other repo: https://github.com/learningequality/kolibri-installer-windows

**Comment by aronasorman** [comment]
Fixed now in https://github.com/learningequality/kolibri/pull/3702
