### ISSUE TITLE
Add Android Installer signing to our Buildkite release building

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2451]
## Summary

Automatically add a production key to releases (not prereleases) for the Android installer.

**Comment by DXCanas** [comment]
Spent a lot of time poking through some of the build files that buildozer generates (was initially trying to figure out if I could manually update the SDK it downloads), and it seems like there's some undocumented signing behaviour, but only for debug builds - might be able to take advantage of that for a short term fix.

**Comment by indirectlylit** [comment]
bumping to next release

**Comment by rtibbles** [comment]
There are security issues with doing this inside the build pipeline, so we won't do this.
