### ISSUE TITLE
Invalid exam report timestamp

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2499]
### Observed behavior
After submitting exam, when teacher go to the exam report to watch exam report. Exam report shows timestamp like "Completed 47 years ago". System time and date is as of today.

Note : Getting "Completed 47 years ago" timestamp for every exam.

### Expected behavior
It must shows correct timestamp.

### Steps to reproduce
1. Login with learner and give exam.
2. Login with teacher account and go to the coach.
3. See exam report.

### Context

* Kolibri version: Kolibri 0.4.7
* Operating system: Ubuntu 14.04
* Browser: Chrome

###Screenshots

![timestamp](https://user-images.githubusercontent.com/12776071/31876429-3472584c-b7f0-11e7-8e93-89cb761b6c9d.png)

**Comment by swapnil106111** [comment]
@rtibbles I faced same timestamp issue on another server too.

![today](https://user-images.githubusercontent.com/12776071/31943337-13ee69de-b8e6-11e7-9ec2-09d3008ac992.png)

**Comment by indirectlylit** [comment]
I see lots of places where `completion_timestamp` is set, so I'm curious whether we're using a consistent format everywhere for that. Does it always come from the `now()` function or is it ever  set directly by the server? 

Also, in the exam view's 'page status' prop we pass the value through `Date()`:

```
:completionTimestamp="new Date(completionTimestamp)"
```

maybe there's a chance that's causing unexpected behaviors, especially if we do in fact have multiple timestamp formats floating around

**Comment by swapnil106111** [comment]
@rtibbles  Tested on Kolibri 0.4.8. Showing correct timestamp in exam report.

![2499](https://user-images.githubusercontent.com/12776071/32089790-b57f18e6-bb09-11e7-8fb3-7c16ff7d8dc8.png)
