### ISSUE TITLE
Not able to see whole image on portrait mode in a tablet

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2500]
### Observed behavior
When learner solving exercises on tablet, learner is not able to see whole image of the question on portait mode.
Note: Learner is able to see same question properly on a landscape mode.

### Expected behavior
Learner must see  full image in portrait mode of tablet or atleast it must have scroll feature to view the image.

### Steps to reproduce
1. Solve the exercise.

Channel ID : 8fc515793aad4e52b490b03c48ad21de (Maharashtra state English Medium).
Path : BalBharati - 4 - Number Work Std. 4 - 3, 4, and 5-digit numbers - Level 2: 3, 4, and 5-digit numbers

### Context

* Kolibri version: Kolibri 0.4.7
* Operating system: Ubuntu 14.04
* Browser: Chrome

### Screenshots
Portrait mode:
![img_20171023_135838](https://user-images.githubusercontent.com/12776071/31879941-9d3ce28c-b7fc-11e7-865f-2ea359af543d.jpg)

Landscape mode:
![img_20171023_135844](https://user-images.githubusercontent.com/12776071/31879961-ad7bc5c8-b7fc-11e7-9edc-8219f3f4b172.jpg)

**Comment by rtibbles** [comment]
Will not be able to fix in the scope of 0.4.8 - but we will look at improving the responsive behaviour of the exercise renderer in future.

**Comment by indirectlylit** [comment]
will be addressed by https://github.com/learningequality/kolibri/issues/2628
