### ISSUE TITLE
kolibri .apk for Nigeria build couldn't run on Android 4.2.2 and 5.1

### ISSUE THREAD

**Issue by dade-ally** [learningequality/kolibri#2501]
### Observed behavior

"kolibri could not load page on Android version 4.2.2 phone"

### Expected behavior

Application launch for first time setup of kolibri on device 

### User-facing consequences

Inability to download contents channel for offline viewing

### Errors and logs

Relevant errors and tracebacks from:

Python Error

An error occurred while trying to load the application libraries. Please try again and/or reinstall

Error:Couldn't load python3.5m from loader dalvik.system.PathClassLoader[Dex PathList[[zip file"data/app/org.le.kolibri-1.apk"],nativeLobraryDirectories=[/data/app-lib/org.le.kolibri-1, /vendor/lib/system/lib, /data/datalib]]]:findLibrary returned null
* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

### Steps to reproduce

precise steps that someone else can follow in order to see this behavior

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by christianmemije** [comment]
@dade-ally This is an issue that we know exists on Android below 4.3. But you also got this error on Android 5.1?

**Comment by christianmemije** [comment]
Related: 
* #1206 
* https://github.com/learningequality/kolibri-kivy/issues/9

**Comment by indirectlylit** [comment]
closing as most work has migrated to 
https://github.com/learningequality/kolibri-installer-android/

please re-open there if necessary
