### ISSUE TITLE
Finalize the way that plugins are loaded/enabled/disabled during start

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2510]
### Observed behavior

We have seen some load errors due to module load order. We should clarify how all this works and make a nice API (based on current conventions) to support developers and make sure that plugins have a long-term life span.

This issue is taking over from #186 where we fixed a bug due to this unclear  module load order.

 * [x] Clearly describe what should happen in a plugin's enable and disable method callbacks
 * [x] Decide whether to track plugin version changes in an installation?
 * [x] Decide how and when they should be handled

### Expected behavior

re: my own post

> Following up on this: Since one may run `enable->disable->enable`, with each operation starting and exiting Kolibri, I believe that plugins should not make lots of assumptions about initial states while running `enable`. This is just a caution.

The above is about making assumptions such as "enable is an atomic action that will only be called once". This is easy to assume, however kolibri (the mother app) will not be able to give such guarantees - It maybe have been called before with a different plugin version. However, Kolibri's base plugin classes can provide the default behavior needed for common plugins. No plugin should ever have to run migrations and collectstatic.

> Anyways, because commands such as `collectstatic` and `migrate` have to be run, we also have to run `django.setup()` anyways.

Which is because while running any kind of setup command, we may detect changes in the version of kolibri or any of its plugins.

> Here's a rough vision of what enabling a plugin could look like:
> 
> ``` 
> $ kolibri plugin enable kolibri.plugins.learn
> 
> Enabling plugin: kolibri.plugins.learn
> 
> Verifying dependencies... OK!
> Collecting static assets (JS/CSS/images)........ OK!
> Running database migrations............ OK!
> 
> Plugin enabled. Please start/restart Kolibri.
> ```

### User-facing consequences

We are looking at some severe problems if plugin upgrades break, either in bundled core plugins or any other external plugin.

**Comment by indirectlylit** [comment]
Thanks for tracking this - very important to think about.

For the next few releases, upgrading and enabling/disabling plugins is not supported end-user functionality, so I'm going to remove the 0.7 milestone and priority. We currently have the 'beta plugin API' [tentatively targeted to 0.9](https://trello.com/c/BYAO7pLO/180-beta-plugin-api)

**Comment by benjaoming** [comment]
+1 on postponing the public launch of external plugins until we have stabilized API etc. around core plugins.

**Comment by indirectlylit** [comment]
see also #2019

**Comment by rtibbles** [comment]
I think this is closed by #5957 and work leading up to it.
