### ISSUE TITLE
[instant schools] Allow 'app-bar' component to use 'session.full_name' instead of 'session.username'

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2518]
### Observed behavior

With instant schools plugin, after logging in under a profile, the session's `username` will be this alphanumeric string (which is the under-the-hood username for a account/profile combination). This username will appear on the top-right corner.

![screen shot 2017-10-24 at 10 45 38 am](https://user-images.githubusercontent.com/10248067/31959149-c4df5ade-b8a8-11e7-9f63-cc73f913edc3.png)

### Expected behavior

It's not specced out as such on the mocks, but I think it might be nicer if we showed the `full_name` property in the top-right corner.

### Steps to reproduce

The 'login with a profile' flow is not ready, but you can reproduce the end result by:

1. Creating an account with a phone number (you will also provide full name, password, etc.)
1. Logging in with the randomly-generated username created by the process
1. See the randomly-generated username on the top-right corner

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by indirectlylit** [comment]
migrated to https://github.com/learningequality/kolibri/issues/2518
