### ISSUE TITLE
Total resources/size of a channel after importing from USB

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2521]
### Observed behavior

If we do a granular export to USB, say the total resource of this channel is 5000, and we only export 5 resources to USB. After that, we do an import from USB. Then at that time, will the `total resources` be shown as 5000 or 5? If we put the `total resources` as 5000, it might be confusing,  since we actually only have 5 resources to import from USB. If instead it's 5, then it somewhat feels that this channel only has 5 resources in total. Could someone clarify this please? Thank you!

The page for importing from USB is [here](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175271).

**Comment by indirectlylit** [comment]
Great question. Let's track all three values - Total, available, and on-device.

|   | Resources  | Size |
|---| ------------- | ------------- |
| Total size  | 5000  |  111 GB |
| Available  | 5  |  23 MB |
| On your device | 0  | 0 |

On the UI side, if `total == available`, we could possibly hide the second row.

cc @jonboiser

**Comment by lyw07** [comment]
Thank you! That clarifies my question.
