### ISSUE TITLE
"superuser" status does not override 'user can change...'  permissions on profile page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2526]
### Observed behavior

If a device is configured to not allow learners/coaches to change their username/full name/password on the Profile page, that does not change even if those learners/coaches become superusers.

![screen shot 2017-10-25 at 2 52 34 pm](https://user-images.githubusercontent.com/10248067/32025290-7e3f2068-b994-11e7-8e08-909a1ff65713.png)

### Expected behavior

Who knows?

**Comment by jonboiser** [comment]
This seems to be resolved for passwords:

https://github.com/learningequality/kolibri/blob/f774c6743ed72331fbf93108354f6cb1d8781763/kolibri/plugins/user/assets/src/views/ProfilePage/index.vue#L227-L230

But for user name/ full name, the issue is still there.
https://github.com/learningequality/kolibri/blob/f774c6743ed72331fbf93108354f6cb1d8781763/kolibri/plugins/user/assets/src/views/ProfilePage/index.vue#L215-L227

**Comment by indirectlylit** [comment]
@jonboiser is there still more information or a decision necessary here? Or is it as simple as adding `this.isSuperuser` to the other `canEdit*` functions?

**Comment by rtibbles** [comment]
This is not extant - superuser's roles do not include learner.
