### ISSUE TITLE
finish and use kivi 0.1.0 for android APK

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2531]
see https://github.com/learningequality/kolibri-kivy/milestone/3

**Comment by jamalex** [comment]
@christianmemije, @DXCanas and I just did a triage + planning syncup on the [Kolibri-Kivy issues](https://github.com/learningequality/kolibri-kivy/issues). We removed the 0.1.0 milestones from a couple lower-priority (or already MVP-solved) issues, and here's the status on the rest:

Have fixes in PR:

- https://github.com/learningequality/kolibri-kivy/issues/2 (should be good to go)
- https://github.com/learningequality/kolibri-kivy/issues/17 (needs additional tweak to remove `cext`)

Higher-priority and actively being worked on:

- https://github.com/learningequality/kolibri-kivy/issues/12 (@DXCanas with support from @aronasorman)
- https://github.com/learningequality/kolibri-kivy/issues/6 (@christianmemije taking over from @DXCanas)

Waiting for upstream Kolibri fixes:

- https://github.com/learningequality/kolibri-kivy/issues/18 (waiting on https://github.com/learningequality/kolibri/issues/2435)

**Comment by indirectlylit** [comment]
bumping to next release

**Comment by indirectlylit** [comment]
closing as work has migrated to 
https://github.com/learningequality/kolibri-installer-android/

please re-open there if necessary
