### ISSUE TITLE
Kolibri Load Screen Language Change Forbidden

### ISSUE THREAD

**Issue by akshaymahajans** [learningequality/kolibri#2535]
### Observed behavior

When trying to select a different language on the kolibri homepage (in the screenshot), the webpage does not respond and change the homepage's language.

![image](https://user-images.githubusercontent.com/22437378/32080789-7d633594-ba66-11e7-87bd-c612d6d01a3f.png)

### Expected behavior
I expect that the language would change to Hindi when I want it to.

### User-facing consequences
The user in different countries cannot use this application because it will only be in english.

### Errors and logs

Relevant errors and tracebacks from:

Errors are in the following screenshots:

From JS console
![image](https://user-images.githubusercontent.com/22437378/32080812-9c03f204-ba66-11e7-9282-90dfd23a6ac5.png)

From Terminal:

![image](https://user-images.githubusercontent.com/22437378/32080847-c3b3183e-ba66-11e7-957d-17d796139ddf.png)

### Steps to reproduce

1. Load kolibri via instructions on ReadTheDocs website
2. Once server loads, try changing the language.

### Context

* Kolibri version: 0.6.dev020171004191044-git
* Operating system: MacOSx
* Browser: Chrome

**Comment by rtibbles** [comment]
Not able to replicate on 0.6.x or latest develop.

**Comment by indirectlylit** [comment]
closing - unable to repro.

@akshaymahajans please re-open if you still reproduce this on the latest 0.7 build
