### ISSUE TITLE
Incentivizing registration: notification for keeping points

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#2546]
### Observed behavior

Currently, when a guest interacts with content, they receive notification of points, but they do not get to keep the points unless they are registered.  
![image](https://user-images.githubusercontent.com/5150483/32196767-f26c7f56-bd7e-11e7-9728-19adb6749877.png)

### Expected behavior

Upon getting a points notification, wording should indicate that creating an account is necessary for keeping the points.

### User-facing consequences

There is an opportunity here to promote account creation, or remind the user that they aren't yet logged in.  Suggested wording to add on modal that pops up after content completion: "Create an account to keep your earned points."

**Comment by christianmemije** [comment]
Thoughts? I went with 'Sign in' in case users already have an account. @jeepurs @jtamiace 

![localhost_8000_learn_ 2](https://user-images.githubusercontent.com/7193975/32514658-93c4b13c-c3b2-11e7-86dc-a8052e24cdb3.png)

**Comment by rtibbles** [comment]
I guess the slight nuance needed is not to give the impression that signing in now will save points they have just earned (because that would require more than just adding a string!)

**Comment by christianmemije** [comment]
'Sign in to start saving points?' @rtibbles

**Comment by christianmemije** [comment]
'Sign in to start saving points you earn'?

**Comment by jtamiace** [comment]
"Sign in to save points next time"? emphasizing the future somehow?

**Comment by jtamiace** [comment]
"You need an account to save points"...?

**Comment by christianmemije** [comment]
They might already have an account, hence 'sign in'.

**Comment by rtibbles** [comment]
@indirectlylit had suggested: "Create an account to earn points."

Perhaps: "Create an account and sign in to earn points."

**Comment by christianmemije** [comment]
`Sign in or create an account to save points you earn.`

I add save, because they are already earning points, or else they would not be seeing the points pop up.

**Comment by rtibbles** [comment]
LGTM :tm:

**Comment by jeepurs** [comment]
I am too late!   (?)

>Sign` in or create an account to save *the* points you earn.

**Comment by rtibbles** [comment]
I think "_the_" might add the implication that the current points are included, whereas the lack of a definite article reduces that implicature.

**Comment by jeepurs** [comment]
LGTMT (LGTM then)

**Comment by christianmemije** [comment]
Fixed in #2571
