### ISSUE TITLE
Publish Channel

### ISSUE THREAD

**Issue by fhenson1** [learningequality/kolibri#2549]
### Observed behavior

I am developing a Khan Academy channel. When i try to publish the channel I get the following message: 

Error with asynchronous call. Please refresh the page

I am also getting the same message when i try to save information I have added to other channels.

* the command line

contentworkshop.learningequality.org

### Errors and logs
Error with asynchronous call. Please refresh the page

Relevant errors and tracebacks from:

I don't know if the channel can be pulled up or not but this is the channel link:

66babb7951ff4bf8b09f3008c98c8520

### Context

* Kolibri version: ?
* Operating system: Windows XP or Windows 10
* Browser: ?
google Chrome or explorer

**Comment by jonboiser** [comment]
@fhenson1 Could you please report this issue on the Kolibri Studio (aka Content Curation) project?

Here's the link:

https://github.com/fle-internal/content-curation/issues

**Comment by jonboiser** [comment]
Also, @fhenson1 when you report it on the Kolibri Studio project, could you provide some details like how much content was in your published channel. Screenshots would be helpful too.

**Comment by lyw07** [comment]
@fhenson1 Sorry for the late reply. I'm publishing the channel `66babb7951ff4bf8b09f3008c98c8520` from our side. It seems to be working fine currently. I'll update the status here once it's finished.

**Comment by lyw07** [comment]
The channel `66babb7951ff4bf8b09f3008c98c8520` is published. Could you check if there are still problems? Thank you.
