### ISSUE TITLE
Not able to solve and proceed to next question in mixed fraction questions.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2587]
### Observed behavior
When learner is solving questions on fraction, kolibri always shows "your answer is close".
example:
If 4 is the whole number, and 2 is the numerator and 7 is the denominator, how can we write the number?
Answers: We are entering following correct answers but we are not able complete and proceed to the next question.

1. 4.285714285714286
2. 30/7
3. 4 2/7 

See the attached screenshots for more reference.
Channel ID : 5d132ba360b54b2ba9df169ffaa43ccb (test2)
Import above channel for replicating this issue.

### Expected behavior
Kolibri must accept all three formats of the answers.

### Steps to reproduce
1. Import the channel 5d132ba360b54b2ba9df169ffaa43ccb.
2. Try to solve questions on tablet.

### Context

* Kolibri version: Kolibri 0.4.9
* Operating system: Ubuntu 14.04
* Browser: Chrome 61.0.3163.98

### Screenshots
Kolibri studio screenshot:
![img_20171110_182255](https://user-images.githubusercontent.com/12776071/32659377-7c651b32-c644-11e7-9967-34635ae17181.jpg)

Tablet screenshots:
![img_20171110_180849](https://user-images.githubusercontent.com/12776071/32659431-bf1d4da0-c644-11e7-98dd-18094b39d06a.jpg)
![img_20171110_180917](https://user-images.githubusercontent.com/12776071/32659432-bf5df026-c644-11e7-9208-a4c75e70d39e.jpg)
![img_20171110_181153](https://user-images.githubusercontent.com/12776071/32659433-bf9987e4-c644-11e7-8961-4691489bceec.jpg)

**Comment by swapnil106111** [comment]
@indirectlylit @rtibbles Can you please take a look into this issue?

**Comment by jonboiser** [comment]
I'm wondering why the hint mentions 'you may have approximated pi' to begin with. Are the hints and expected answers grouped together somehow? Maybe this exercise is configured with the wrong answer.

**Comment by swapnil106111** [comment]
@jonboiser Tried on kolibri 0.7.0. Still facing same error on the server.
![screenshot from 2017-12-27 17_07_06](https://user-images.githubusercontent.com/12776071/34380717-955191ac-eb29-11e7-8b9e-85ce0413fa5e.png)

**Comment by jonboiser** [comment]
I'm seeing different exercises in the "Test 2" channel, but ran into the same issue with one of the problems in the "multiplying fractions" exercise. Some of them do work as expected, but not the one in the screenshot:

![screen shot 2018-01-09 at 11 45 42 am](https://user-images.githubusercontent.com/10248067/34740038-f61c72fa-f532-11e7-8cb2-a08778721418.png)

**Comment by indirectlylit** [comment]
closing - this may have been addressed by KA content updates. please re-open if it's still an issue.
