### ISSUE TITLE
Channel ID=>Token - Update docs and UI messages

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2592]
### Observed behavior

"Channel IDs" will be called "Channel Tokens" from 0.7 and onwards.

Decision needed regarding backports for documentation since Kolibri Studio will read "Channel Token" once 0.7 is released.

### Expected behavior

All docs and UI + translations should only talk about "Channel Tokens" to ensure we don't do a public release with this confusion.

**Comment by indirectlylit** [comment]
I can't find any instances of 'Channel ID' in Kolibri's user-facing text.

Migrating this to be just a 'user docs' task.

**Comment by indirectlylit** [comment]
addressed in https://github.com/learningequality/kolibri/pull/2803
