### ISSUE TITLE
Fix all Sphinx warnings (count: 163)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2598]
### Observed behavior

We keep accumulating errors in our docs, now at 163 warnings. #1588 was addressing this but got closed.

It's because no one is looking out for the warnings, and we cannot raise them to build-breakers.

### Expected behavior

We should always be at 0 warnings.

### User-facing consequences

Our docs builds contain errors that no one is aware of. Broken references, missing references etc.

**Comment by indirectlylit** [comment]
once these are resolved, might be good to have them break the build

**Comment by benjaoming** [comment]
Also lesson learned: Should not add docs in the first place and allow warnings to sneak in, I would assume what happened was that I rushed in docs, didn't mind a couple of warnings, and now they've multiplied :)

**Comment by indirectlylit** [comment]
closing in favor of the four issues above
