### ISSUE TITLE
Recommended View more UX issue

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2609]
### Observed behavior

When clicking `View more` for the Most Popular section, it is unclear that anything happened on small viewports. Also there is no clear way to go back. I would suggest moving the view more button to the bottom and/or adding breadcrumbs eg `Recommended > Most popular` to make navigation easier.

![recommended](https://user-images.githubusercontent.com/7193975/32851153-11343408-c9e9-11e7-8e79-67cd9650b518.gif)

### Expected behavior

User gets feedback that the button click actually did something. 

### User-facing consequences

Confusion

### Steps to reproduce

Use a small viewport 320 x 480

### Context

* Kolibri version: 0.6.x

**Comment by DXCanas** [comment]
I think the first designs used a full-screen modal, though I can't remember why we decided against them
