### ISSUE TITLE
Open Source math homework project interested in collaborating

### ISSUE THREAD

**Issue by jaltekruse** [learningequality/kolibri#2615]
Hello Kolibri Team!

I am the developer of Free Math, an offline web application for completing step-by-step math homework digitally, and a grading interface for quickly processing an entire classes work to find where students are misunderstanding material.

The app is deployed here: http://freemathapp.org/

While the system doesn't provide instant feedback, it does offer an opportunity for learners to convey their current understanding in a format easily sharable with their teachers. This enables teachers and coaches the unique opportunity to see what specific mistakes are made on each assignment by different groups of students on each question.

Currently the application is designed to be LMS agnostic by working with files, but it looks like Kolibri is structured around individual exercises that are linked together in the web app, and may not have a facility for collecting files right now.

I am open to changing the structure of Free Math to accommodate integrating it with Kolibri. An initial integration could simply be an optional workspace for students to use when completing their math work. This work generated by students could be saved, and incorrect work could be shown to coaches when an incorrect answer is submitted.

I do like the opportunity for teachers to provide partial credit based on the work as a benefit of Free Math, but this currently requires making feedback asynchronous, which is a drawback compared to instant fully-automated grading.

**Comment by lauradanforth** [comment]
Hi Jason,
Thanks for reaching out! Free Math sounds like a great offline platform and it would be interesting to explore how it might be used with Kolibri. We are still in the beta stage with Kolibri but our public release version will be available within the next month. Can you share more about the types of data your platform tracks through the files? This will help us better understand the use case for integration and inform continued development. As Kolibri is open source, you are welcome to play around with integration possibilities in the interim and we would love to stay in the loop on your work!

Best,
Laura

**Comment by jaltekruse** [comment]
Hi Laura,

Free Math currently just tracks a list of expressions as a response to math questions, and provides a nice multi-line editor to make answering questions fast. This is just stored as text, with latex embedded in JSON. I am looking at expanding it in the future to give space for students to graph or create diagrams for other types of problems. More generally this approach could be used as a wrapper format for other tools like geogebra, which now has a web version that can run without Java on clients. Being offline it is a bit of a challenge, balancing user power against a desire from teachers to limit access to certain tools on certain questions is difficult. For example many online math systems only allow use of calculators on some questions. There are similar issues giving geogebra or other graphing tools if the assignment is meant to teach students to graph on their own using other methods.

I'll take a look at the Kolibri code to see what might be a good place to plugin in the editor.

**Comment by lauradanforth** [comment]
Hi Jason,

Thanks for sharing more information on this and it's clear that you're thinking critically around some of the common challenges! It's difficult to create something that does _everything_, nor is that our goal so it's helpful to know which areas other platforms are tackling and find out how we can work together. Definitely let me know as you take a look at the code and I'd be happy to pick up the conversation over e-mail - feel free to reach out at laura@learningequality.org.
