### ISSUE TITLE
disable built-in browser translator

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2617]
### Observed behavior

In https://github.com/fle-internal/kolibri-instant-schools-plugin/issues/121 we observed confusion between chrome's translation widget and our own language switcher:

![image](https://user-images.githubusercontent.com/2367265/32906974-6a8eeda2-cab3-11e7-88e1-016d0695f3bc.png)

### Expected behavior

The user should hopefully only see one way to translate the site. Since we provide translations, ours should take precedence.

Longer-term we might want to revisit this for languages we don't support, but in the short-term the chrome language switcher is causing issues.

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Steps to reproduce

Open Kolibri in another language

### Context

* Kolibri version: 0.6.x
* Operating system: Android
* Browser: Chrome

**Comment by christianmemije** [comment]
Reference: https://stackoverflow.com/questions/2467454/why-does-chrome-incorrectly-determine-page-is-in-a-different-language-and-offer
