### ISSUE TITLE
change 'topics' to 'channels' in learn

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2621]
Update text and icon:

![image](https://user-images.githubusercontent.com/2367265/32921150-4b62c6aa-cae1-11e7-8fc9-ca485e138013.png)

**Comment by christianmemije** [comment]
Fixed in #2624

**Comment by jeepurs** [comment]
@christianmemije it's worth noting underneath the sub nav bar there's another instance of "Channel" displayed which I think was flagged in earlier conversations as too much.  I suggest taking that out.

**Comment by christianmemije** [comment]
@radinamatic Currently there is no h1 in Recommended, only a few h2s. And the same would happen if we remove the Channels title. Thoughts?

**Comment by radinamatic** [comment]
@christianmemije My first thought was to make a hidden H1, that is to apply the `visuallyhidden` class, but I wanted to confirm that it has no "hidden" drawbacks first. Apparently it does not, and is recommended on several occasions:

https://www.coolfields.co.uk/2016/05/text-for-screen-readers-only-updated/
https://www.drupal.org/docs/7/creating-accessible-themes/using-headings-to-improve-accessibility

So I don't see a problem for us to include a `<h1 class="visuallyhidden">Browse recommended content and channels</h1>` on the landing page, above the tabs, or similar wherever H1 might be missing! 🙂
