### ISSUE TITLE
no mastery achieved on pdf's

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#2625]
### Observed behavior

Mastery is not achieved (no complete icon, and no points earned) after spending time scrolling through the pdf.

### Expected behavior

PDF is 9 pages long. Mastery is expected after 4.5 minutes.  The 'in progress' icon appears but mastery is never achieved.

### Steps to reproduce

1. Select a pdf content, like this one: https://instantschools-v2.learningequality.org/learn/#/topics/c/2d902e00e30245799081fda4da5cabd0
2. Keep pdf open for 5+ minutes
3. No mastery achieved 
![pdfmastery](https://user-images.githubusercontent.com/5150483/32923423-5c6e00ee-caec-11e7-9e8a-3925f09f2a23.png)

### Context

* Kolibri version:  0.6.1 pex on online demo server
* Operating system: pex
* Browser: Chrome
URL: https://instantschools-v2.learningequality.org/learn/#/topics/c/2d902e00e30245799081fda4da5cabd0

**Comment by DXCanas** [comment]
@rtibbles @radinamatic @jeepurs I'm not seeing a priority tag on this, but I said I'd look into it at dev meeting today. Should we add this to a milestone? Should I be working off 0.6?

**Comment by rtibbles** [comment]
Yes, 0.6.1.
