### ISSUE TITLE
add max-width and text-overflow: ellipsis to username

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2627]
![image](https://user-images.githubusercontent.com/2367265/32929436-daae4ee4-cb0c-11e7-9dfe-ad55209c8705.png)

**Comment by jonboiser** [comment]
How did you get a username so long? On the profile page, it limits usernames to 30 characters.

**Comment by indirectlylit** [comment]
chrome dev tools? :P

even 30 can be pretty long though...

> mmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

**Comment by indirectlylit** [comment]
(we could even set the max-width conditionally based on `responsiveWindow`)
