### ISSUE TITLE
'Database is Locked' error when channel importing is running

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#2632]
We get errors in `jonboiser`'s `available-channels` branch. It's not reliably replicating (!), but the general observations are:

- It happens during `startremotechannelimport` or `diskchannelimport`
- The actual error is raised when another API or session call happens

My sense here is that it's caused by the long content import and annotation phase of channel importing.

Possible solutions:
- shorten length of transactions
- do stuff outside of transactions, before committing them

**Comment by indirectlylit** [comment]
see also https://github.com/learningequality/kolibri/issues/2271

**Comment by indirectlylit** [comment]
@aronasorman for help replicating, you might try adding long `time.sleep()`s inside suspicious sections to increase likelihood of concurrent DB access

**Comment by aronasorman** [comment]
^ That's a good suggestion, I'll try it out when I look at this on Monday!

**Comment by aronasorman** [comment]
Having a hard time replicating on my machine, so I'll fall back to either trying to slow down IO for a program, or using our designated slow laptop to try to replicate this.

**Comment by indirectlylit** [comment]
we haven't reproduced lately - seems to be mitigated

**Comment by indirectlylit** [comment]
we may be seeing this in the wild again - #3036
