### ISSUE TITLE
ui-menu keyboard navigation

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2634]
### Observed behavior

Navigation between `menuitems` seems to be working only with `Tab/Shift+Tab` keys.

### Expected behavior

According to [WAI-ARIA practices](https://www.w3.org/TR/wai-aria-practices/#menu), the navigation between `menuitems` should be possible with `Up/Down` arrow keys as well as with `Tab/Shift+Tab` keys. The latter is actually not recommended in case of the complex navigational structures and menus with deep nested levels, but since we have 3 lonely links inside this menu, it's not such a big faux-pas, yet...

### User-facing consequences

When using keyboard to navigate, user expects to be able to navigate among menu options with the arrow keys.

### Context

* Kolibri version: PEX build from #2623 
* Operating system: Ubuntu 16.10
* Browser: Firefox & Chrome

**Comment by Kalovelo** [comment]
Hello @radinamatic, could I work on this issue :leaves: ?

**Comment by marcellamaki** [comment]
Hi @Kalovelo, this is actually a duplicate issue of another in our design system that I am working on. Thanks for offering! 

Closing as [a more up to date issue in KDS](https://github.com/learningequality/kolibri-design-system/issues/178) with WIP PR addresses this issue.
