### ISSUE TITLE
add password-change functionality in 'user profile' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2645]
Users need to be able to change their password from the profile page.

**Comment by jtamiace** [comment]
Will be looking at this next week

**Comment by indirectlylit** [comment]
I think we should avoid including password updates in the same form as the rest of the profile form updates because then it looks like you need to change your password when you edit your name, username, etc:

> ### Edit profile
> Full name: _D_
> Username: _user123_
> New password: _Enter new password_
> New password: _Re-enter new password_
> <kbd>Update</kbd>

Would rather expect something like a 'change password' link

> ### Edit profile
> Full name: _D_
> Username: _user123_
> <kbd>Update</kbd>
> [Change password](#)

which opens a new modal like

> ### Change password
> Current password: _Enter current password_
> New password: _Enter new password_
> New password: _Re-enter new password_
> <kbd>Update</kbd>

**Comment by jtamiace** [comment]
![slice](https://user-images.githubusercontent.com/6668144/34220869-e6e6d4e2-e56a-11e7-80d7-5f8be2de07f0.png)

**Comment by jtamiace** [comment]
And a confirmation state after successful password change. Styling is based on current form behavior for making changes to name or username.

![desktop copy 2](https://user-images.githubusercontent.com/6668144/34231526-480fc1a4-e591-11e7-8c8c-dd2d3d0606be.png)

A remaining question is how mismatching new passwords are handled. Probably detectable on client side?

Another is how a wrongly inputted "current password" is handled? I'm guessing this can't be checked until after submission of this form. In which case, we could insert an error alert at the top of this modal form suggesting that the user input the correct password?

**Comment by indirectlylit** [comment]
> A remaining question is how mismatching new passwords are handled. Probably detectable on client side?

Yes, that sounds correct

> Another is how a wrongly inputted "current password" is handled? I'm guessing this can't be checked until after submission of this form. In which case, we could insert an error alert at the top of this modal form suggesting that the user input the correct password?

Yes, that also sounds correct

----

Mind showing the validation state for both of these two scenarios inside the modal?

![image](https://user-images.githubusercontent.com/2367265/34656757-49fa7ad6-f3d3-11e7-8eac-a1b0f1eb9966.png)

These can follow the standard [form validation patterns](https://docs.google.com/document/d/1rrq8fovV5wBtUKv65wfRqXxP4SfnV30anUZHfzCVmN4/edit) you've put together.

**Comment by jtamiace** [comment]
In the Users tab for mismatching new passwords, the error alert actually appears after the user clicks "save." Should the UI for changing password in Profile follow suit?

![screen shot 2018-01-09 at 11 48 04 am](https://user-images.githubusercontent.com/6668144/34740089-2258e57e-f533-11e7-89ec-e7abd408cd7f.png)

Following that, if a user enters a wrong current password _and_ mismatching new passwords, do all the error messages show up once the user clicks "continue," as shown here?

![slice2](https://user-images.githubusercontent.com/6668144/34741341-28a75d94-f537-11e7-9919-771f6ab8fc61.png)

cc @khangmach @indirectlylit

**Comment by khangmach** [comment]
Looking around different platforms I always see "wrong current password" error msg come up after hitting the confirm/continue/save button (the system has to check after button press that the current password is wrong). On the such forms it looks like it's also a common convention to check on the spot whether two passwords don't match.

I lean towards having the "wrong current pass" appear after because it may be annoying that the system prompts "wrong current password" too early when I'm a few characters in typing in my existing password

**Comment by indirectlylit** [comment]
@khangmach 

> it may be annoying that the system prompts "wrong current password" too early when I'm a few characters in typing in my existing password

note that would never happen because we don't do as-you-type validation anywhere anymore

**Comment by jtamiace** [comment]
Taking a closer look at the forms spec, it actually doesn't look both errors could pop up at the same time.

**Case 1: user enters mismatching new passwords**
Upon losing focus, the following error message appears. 
If we go by what's written in the forms doc, if the user tries to click "UPDATE" while there is a client-side error, the form should not submit, and instead their mouse pointer should auto-focus on the problematic input field. Should that auto-focused input field be the first or second new password field?
![desktop copy 5](https://user-images.githubusercontent.com/6668144/34890207-d99def8c-f785-11e7-9fb7-a6c67edb11ce.png)

**Case 2: user clicks update, but current password does not match server**
If the passwords match, the user can submit the form to be checked by the server.
![desktop copy 6](https://user-images.githubusercontent.com/6668144/34890377-83b2ad0a-f786-11e7-819b-a7585a8336b8.png)

**Comment by indirectlylit** [comment]
You're right!

I'd thought that we might show both in case 1, but I'd forgotten:

> If the submit button is clicked and there are visible client-side errors, set keyboard focus in the first field that contains an error instead of submitting.

**Comment by indirectlylit** [comment]
>  Should that auto-focused input field be the first or second new password field?

Second because it's the one with the error displayed, right?

**Comment by jtamiace** [comment]
>  Second because it's the one with the error displayed, right?

Sounds good to me. 

Ok, just going to post this flow here to summarize the discussion
![slice5](https://user-images.githubusercontent.com/6668144/34897008-cbee0532-f7a0-11e7-8ce8-bc74ed3e00d4.png)

**Comment by DXCanas** [comment]
Any objections to my picking this up?

**Comment by indirectlylit** [comment]
go for it!

**Comment by christianmemije** [comment]
Any alternatives to the placement of the success message of a password change, since the username/name and password change are 2 different forms. Usually if it is a modal, there is a confirmation message that lasts a second before disappearing. Or we could make use of the snackbar? @jtamiace @khangmach

**Comment by jtamiace** [comment]
I'm looking through generally at how we handle confirmation messages from modals in Kolibri, and it doesn't look like we have any message at all for changes made in modals. 

I think a snackbar sounds reasonable, and maybe that can be a pattern that we apply more broadly to confirmation for changes made in the spec for [simple modals](https://docs.google.com/document/d/1102ubWXHSkWEWibHHfni9-cwc16PcQiocBWmOJrEGag/edit)? 


> Usually if it is a modal, there is a confirmation message that lasts a second before disappearing

Need a bit more clarification. Do you mean the green bar that is currently in the mockups or another component?

**Comment by jtamiace** [comment]
Oh wait, do you mean after saving a change in a modal, a message appears inside the modal confirming that something happened, and then the modal closes?

**Comment by christianmemije** [comment]
> Oh wait, do you mean after saving a change in a modal, a message appears inside the modal confirming that something happened, and then the modal closes?

Yup, kind of like a confirmation flash.

**Comment by indirectlylit** [comment]
> after saving a change in a modal, a message appears inside the modal confirming that something happened, and then the modal closes

I dislike the idea of delaying the close of the modal because it prevents the user from moving on to their next task

> I think a snackbar sounds reasonable

that sounds better to me - something that looks a bit like the "disconnected" box

**Comment by jtamiace** [comment]
Update - includes the snackbar, same wording as the previous green confirmation bar. Should dismiss after X time (whatever the default is set to?)

![slice8](https://user-images.githubusercontent.com/6668144/35009231-d0de83bc-fab3-11e7-82f3-9a10ced29f33.png)

**Comment by DXCanas** [comment]
@jtamiace Check out PR #3709 - default dismiss time is set to 4000 ms

**Comment by DXCanas** [comment]
One obstacle: in the API's current state, there's no way to "confirm" a pw without doing a login or tweaking a session. @ralphiee22 offered to step in and help, but wanted to flag that

**Comment by DXCanas** [comment]
@jtamiace After talking to @ralphiee22 and Jamie, seems like current password isn't currently a requirement on the back end, meaning there are a few endpoints you can use to change your password without the current password check.

With this in mind, it seems like current password is an extra field. We can add it - @ralphiee22 did some of the work necessary to make it an optional requirement - but it's not any more secure at a technical level. How do you feel about removing the current password field?

**Comment by jtamiace** [comment]
:burn_it_down:

**Comment by indirectlylit** [comment]
> there are a few endpoints you can use to change your password without the current password check

mind filing an issue for this?

**Comment by indirectlylit** [comment]
fixed by @khangmach and @christianmemije in #3097
