### ISSUE TITLE
set up kolibri developer docs on RTD

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2658]
* create a new project `kolibri-dev` on RTD, giving admin permissions to the same people as the `kolibri` project
* have it track `/docs-developer/conf.py` in the advanced section:

![image](https://user-images.githubusercontent.com/2367265/33144042-a4e59f48-cf70-11e7-9c0d-21b81638e545.png)

By default, track the `develop` branch

**Comment by benjaoming** [comment]
Done! (including notifications and maintainer access)

http://kolibri-dev.readthedocs.io/en/develop/

**Comment by indirectlylit** [comment]
nice :)
