### ISSUE TITLE
add info about contributing and providing feedback to user docs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2660]
Let's provide some unintrusive but clear cross-links between the developer and user documentation.

Basically, we want advanced users who might actually wish to work on bug fixes, translations, or give feedback/bug reports should have a way of providing that.

**Comment by benjaoming** [comment]
As you will see over in https://github.com/learningequality/kolibri/pull/2985 this is solved in the developer docs slightly.

But I would like to add the following actual sections:

1. Developer docs: "Installing Kolibri" => User docs
1. User docs: "Contributing" => Develop docs
