### ISSUE TITLE
need better empty state when no channels are on the device

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2669]
re: #2610

![image](https://user-images.githubusercontent.com/2367265/33151972-2528e5de-cf8f-11e7-9942-0211196f33a2.png)

**Comment by jonboiser** [comment]
There is an empty state encoded in the `channels-grid` component, but it is based on the number of installed channels being greater than 0, and not on the number of installed-with-resources channels being greater than zero.

**Comment by christianmemije** [comment]
Fixed in #2696
