### ISSUE TITLE
translate management page titles

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2672]
### Observed behavior

currently, all pages that use `preparePage` pass in untranslated strings. For example:

```javascript
  {
    name: PageNames.USER_PERMISSIONS_PAGE,
    path: '/permissions/:userid',
    handler: ({ params, name }) => {
      preparePage(store.dispatch, {
        name,
        title: 'Manage User Permissions',
      });
      showUserPermissionsPage(store, params.userid).then(hideLoadingScreen);
    },
  },
```

### Expected behavior

page titles should be translated

### User-facing consequences

some difficulty in other languages

### Context

* Kolibri version: 0.7

**Comment by jonboiser** [comment]
This should have been fixed in #2610
