### ISSUE TITLE
"Password" placeholder in the sign-in page on Chrome

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2673]
Replaces https://github.com/fle-internal/kolibri-instant-schools-plugin/issues/145

### Context

**Update: happens on Chrome 62 on all Windows versions too**

* Operating system: Android 6.0.1, 4.2.2
* Browser: Chrome
* Phone / Device description (Make/Model/Form factor): not sure of the original reporter's make / model, but happens both on my MotoG Play (Android 6.0.1) and Samsung GT-S7580 (Android 4.2.2)
* Online demo, URL: https://instantschools-v2.learningequality.org

### Observed behavior

The password field is filled in with gray wording.  Happens only in Chrome, not on Firefox.

#### Chrome
![2017_11_22_18 52 45](https://user-images.githubusercontent.com/1457929/33143123-2297513c-cfb9-11e7-8da4-b89b5dfb5f99.png)

#### Firefox
![2017_11_22_18 52 31](https://user-images.githubusercontent.com/1457929/33143173-50f36336-cfb9-11e7-8183-1f5ced47f0a5.png)

### Expected behavior

Not use the label as a placeholder for the input field.

cc @christianmemije

**Comment by christianmemije** [comment]
As mentioned in the previously opened issue, some possible workarounds: https://github.com/mui-org/material-ui/issues/718

**Comment by radinamatic** [comment]
### Windows 7

![win7 start running - oracle vm virtualbox_071](https://user-images.githubusercontent.com/1457929/33191280-02cc7120-d0b8-11e7-933e-0ad0b1d72a94.png)

### Windows 8.1

![win8 1 start running - oracle vm virtualbox_072](https://user-images.githubusercontent.com/1457929/33191294-1c76e8d0-d0b8-11e7-8c63-2a333abb59a8.png)

### Windows 10

![win10 start running - oracle vm virtualbox_073](https://user-images.githubusercontent.com/1457929/33191298-279add84-d0b8-11e7-9f4e-7ab0e00406e0.png)

**Comment by radinamatic** [comment]
`Password` label sits as a placeholder on page load in Chrome, and returns in its proper place only after one actually taps/clicks inside the password input field:

![peek 2017-12-01 00-30](https://user-images.githubusercontent.com/1457929/33460610-41e58190-d62f-11e7-87f9-c3f76a962192.gif)

Does not happen on other browsers, just Chrome. Seems as if the label is missing, compared to `Phone Number` field.

**Comment by indirectlylit** [comment]
@mrpau-eugene would you mind taking a look at this issue? You can see I already have an initial attempt in #3232

**Comment by mrpau-eugene** [comment]
@indirectlylit I'll take a look into this. Seems like a strange bug floating for ages

**Comment by indirectlylit** [comment]
indeed. Take a look at the references I included in the PR above.

**Comment by indirectlylit** [comment]
closing - addressed as much as possible
