### ISSUE TITLE
device info page formatting cleanup

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2675]
could do some follow-up, re #2674 and #1910

current:

![image](https://user-images.githubusercontent.com/2367265/33155593-895bf052-cfa6-11e7-8717-f83fdf51e4df.png)

spec: 

![image](https://user-images.githubusercontent.com/2367265/33155597-950661ee-cfa6-11e7-97f5-3062fe35c48d.png)

**Comment by mrpau-richard** [comment]
@indirectlylit I tested this in the latest Pre-release of Kolibri  Windows installer at https://github.com/learningequality/kolibri/releases

I have this error referring to screenshot below:
![screen shot 2017-11-24 at 3 02 37 pm](https://user-images.githubusercontent.com/8663934/33203241-587d5b34-d13a-11e7-9255-b662b9861706.png)
That error can be reproduced in the fresh installation. After the user created an admin account and navigate to the `device info` page.

**Comment by indirectlylit** [comment]
thanks for testing @mrpau-richard! I've it to #2686 since it's independent of this issue.
