### ISSUE TITLE
error when viewing device details on fresh installation

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2686]
### Observed behavior

reported by @mrpau-richard:

tested this in the latest Pre-release of Kolibri  Windows installer at https://github.com/learningequality/kolibri/releases

I have this error referring to screenshot below:
![screen shot 2017-11-24 at 3 02 37 pm](https://user-images.githubusercontent.com/8663934/33203241-587d5b34-d13a-11e7-9255-b662b9861706.png)

### Expected behavior

device details page should show without error

### User-facing consequences

broken experience

### Errors and logs

...

### Steps to reproduce

That error can be reproduced in the fresh installation. After the user created an admin account and navigate to the `device info` page.

### Context

* Kolibri version: 0.7
* Operating system: Windows 7 `32 bit`.
* Browser: Google chrome `Version 62.0.3202.94 (Official Build) (32-bit)`
* Server log file:  [server.log](https://github.com/learningequality/kolibri/files/1504547/server.log)

**Comment by indirectlylit** [comment]
@mrpau-richard would you mind sharing the OS you're testing on, and any server logs?

**Comment by mrpau-richard** [comment]
@indirectlylit I added the OS and the log file I used to reproduce this issue.

**Comment by indirectlylit** [comment]
should have been addressed with #2713
