### ISSUE TITLE
Export generates "Method not allowed" error message in 0.7.0 Beta1

### ISSUE THREAD

**Issue by Rbuten** [learningequality/kolibri#2707]
### Observed behavior

description of the behavior that was observed, including screenshots or other references when applicable

### Expected behavior

description of what behavior was expected but did not occur

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

### Steps to reproduce

precise steps that someone else can follow in order to see this behavior

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by Rbuten** [comment]
Windows 10, browser Chrome

**Comment by indirectlylit** [comment]
Hi @Rbuten - feel free to re-open if you can provide steps to reproduce. thanks!
