### ISSUE TITLE
Export does not write content, only database.  Rel 0.7.0 Beta2; W10, Chrome

### ISSUE THREAD

**Issue by Rbuten** [learningequality/kolibri#2708]
### Observed behavior

description of the behavior that was observed, including screenshots or other references when applicable

### Expected behavior

description of what behavior was expected but did not occur

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

### Steps to reproduce

precise steps that someone else can follow in order to see this behavior

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by indirectlylit** [comment]
Hi @Rbuten, thanks for helping us test our beta!

If there's a problem with exporting, we definitely want to fix it. Would you mind filling in some of the details above to help us reproduce and solve the issue?

I've marked the critical elements in red:

![image](https://user-images.githubusercontent.com/2367265/33452848-63c24ac6-d5c8-11e7-86ed-2feee7490452.png)
