### ISSUE TITLE
channel resource URLs no longer include channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2710]
### Observed behavior

Our resource URLs now look like this:

* `/topics/t/:id`
* `/topics/c/:id`
* `/recommended/:id`

### Expected behavior

URLs could include the channel ID also, e.g.:

* `/topics/:channel/t/:id`
* `/topics/:channel/c/:id`
* `/recommended/:channel/c/:id`

### User-facing consequences

URLs no longer contain a channel ID, which might make it harder to report issues with content items by sharing the URL.

It's also not clear what happens in the UI if the same content resource exists in multiple channels.

### Context

* Kolibri version: 0.6.x

**Comment by jamalex** [comment]
> It's also not clear what happens in the UI if the same content resource exists in multiple channels.

Topics and resources are identified in the URL by "node id", which should be globally unique. The same resource in two places will have the same "content id", but different "node ids". So that shouldn't be a problem here.

**Comment by jamalex** [comment]
(The global uniqueness of node_id's should also mitigate the concern about issue-reporting, as we'll be able to search it and determine what channel/topic it's in)

**Comment by rtibbles** [comment]
We have heard a converse report from Nalanda, where their content partners were concerned about the channel_id being exposed in the interface (so this is actually advantageous for unlisted channels).

**Comment by rtibbles** [comment]
Going to close this for now.
