### ISSUE TITLE
"Device info" tab is visible for guests

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#2713]
### Expected behavior

Should not be there

### User-facing consequences

User gets this error:
![screen shot 2017-11-28 at 4 37 04 pm](https://user-images.githubusercontent.com/6668144/33351799-64e8249e-d45a-11e7-88ae-5799f3b21b8e.png)

### Errors and logs

User gets this after clicking still-visible `INFO` tab

![screen shot 2017-11-28 at 4 37 43 pm](https://user-images.githubusercontent.com/6668144/33351825-80135c34-d45a-11e7-9c9e-edd16218ed1c.png)

### Steps to reproduce

1. From sign in page, click `ACCESS AS GUEST`
2. Click `You can import content from the Content page if you have the proper permissions`

### Context

* Kolibri version: 0.7.0.dev020171128234418-git
* Operating system: MacOS Sierra
* Browser: Chrome

**Comment by christianmemije** [comment]
Fixed in #2737
