### ISSUE TITLE
prop validation error during exam creation

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2714]
### Observed behavior

Noticed some prop validation errors during exam creation: https://github.com/learningequality/kolibri/pull/2700#issuecomment-347645264

### Expected behavior

no errors

### User-facing consequences

none observed

### Errors and logs

```
vue.runtime.esm.js:472 [Vue warn]: Invalid prop: type check failed for prop "text". Expected String, got Null.

found in

---> <CoreSnackbar> at kolibri/core/assets/src/views/core-snackbar/index.vue
       <CreateExamPage> at kolibri/plugins/coach/assets/src/views/create-exam-page/index.vue
         <CoreBase> at kolibri/core/assets/src/views/core-base.vue
           <Root>
```

### Steps to reproduce

* I started with a fresh server
* import content
* create new class
* create new exam

### Context

* Kolibri version: 0.7

**Comment by luna215** [comment]
I was unable to reproduce the issue. Is it possible that it was fixed?

My steps for reproducing the issue: 

- Imported content: (CK-12)
- Created a new class (named it Test Class)
- Navigated to coach then to the EXAMS tab
- created exam (name it Test Exam)

**Comment by indirectlylit** [comment]
Thanks @luna215 

I've tried to reproduce but ran into trouble with the issue referenced above

**Comment by christianmemije** [comment]
Cannot reproduce.
