### ISSUE TITLE
When not logged in, and no content, clicking "You can import content" and then "Info" leads to error

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2716]
### Observed behavior

![peek 2017-11-28 17-12](https://user-images.githubusercontent.com/618416/33352805-8eaa73e0-d45f-11e7-9308-d92de1d9af58.gif)

### Expected behavior

If I'm not logged in, link to download content either shouldn't exist, or should trigger the login page.

### User-facing consequences

Frustration/confusion at a very early stage of trying to use Kolibri on a new device.

### Context

* Kolibri version: 0.7.0.dev020171127053241-git
* Operating system: Ubuntu
* Browser: Chrome

**Comment by indirectlylit** [comment]
related: #2713

**Comment by christianmemije** [comment]
#2737 Gets rid of the error displayed. Now they will just see `You must be a signed in as a Superuser or have Content Management permissions to view this page`.
