### ISSUE TITLE
import/export: content listing missing number of resources

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2717]
### Observed behavior

see e.g. "41 GB resources" below:

![image](https://user-images.githubusercontent.com/2367265/33353326-1b3aece8-d462-11e7-870c-2e14d0b5ede3.png)

### Expected behavior

I assume this is meant to display both the size and quantity?

### User-facing consequences

confusing messaging

------

cc @jonboiser

**Comment by jonboiser** [comment]
That's how the "x gb resources" message is specified in the design. There is a fix in #2699 that corrects the number to show the file sizes on the device, whereas the screenshot is a holdover from the previous version, where file sizes are totals for the channel.

**Comment by indirectlylit** [comment]
I'm almost certain that was a mistake in the mockups, and those are intended to be two different values:

![image](https://user-images.githubusercontent.com/2367265/33357384-a03a140a-d476-11e7-9d8d-ab6d0a0ebd4b.png)

**Comment by indirectlylit** [comment]
(if this requires a string change, we'll have to punt to 0.8)

**Comment by christianmemije** [comment]
Fixed in #2783
