### ISSUE TITLE
import/export: channel might show up even if nothing is imported

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2719]
### Observed behavior

We use some fancy logic to hide channels from the channel list when the user hasn't imported anything from the channel.

However, this logic is confused in situations when resources are shared across channels.

### Expected behavior

Channels should not show up in the channel list unless the user has imported something from it.

### User-facing consequences

Confusing interaction, where channels show up even when the user has not requested anything from them.

### Steps to reproduce

 * start with no content imported
 * import all the content from 'portion control' (`fb51dae6df7545af8455aa3a0c32048d`)
 * at this point, only 'portion control' is in the channel list
 * view the 'khan academy en' public channel, but don't import anything
 * go back to channel list. khan academy shows up because it happens to share content with portion control, and you happened to view it

### Context

* Kolibri version: 0.7

**Comment by lyw07** [comment]
I think currently showing available channels at page `http://localhost:8080/management/device/#/content` is handled by Jonathan on the front-end side. I checked that if we use the API call `api/channel/?available=true`, then the Khan Academy (en) channel is not shown there. @jonboiser, I remember you said there are benefits doing this on the front-end side, do you think there will be a workaround to resolve this issue? thank you!

**Comment by jonboiser** [comment]
@lyw07 Can we add an `available` property to the ChannelMetadata? Then I can use that instead of inferring it based on `on_device_resources`.

Or can we improve how `on_device_resources/files` works so that it sets these values to zero if they were not deliberately imported?

**Comment by jonboiser** [comment]
The latter approach would not involve any changes to the UI.

**Comment by indirectlylit** [comment]
is this issue resolved by the PR above?

**Comment by lyw07** [comment]
I think for this specific PR, the issue is resolved, since users won't be able to see the second channel if they go to the channel list. 
However, if they go to the channel detail page for the second channel, they can still see that it has content downloaded, although they didn't do that intentionally. But I remember we didn't come up with a solution for this case?

**Comment by indirectlylit** [comment]
I believe that we decided to leave things as-is for that situation. thanks!
