### ISSUE TITLE
import/export: unlisted channels are not persisted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2720]
### Observed behavior

users need to re-enter secret tokens or channel IDs every time they go back to import new content or update

### Expected behavior

"unlocked" channels should be persisted after unlocking them. They should [show up in the channel selection list](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175319) with a 'lock' icon:

![image](https://user-images.githubusercontent.com/2367265/33354840-a505e0d4-d469-11e7-9f7c-6552b4b8412e.png)

### User-facing consequences

user needs to unnecessarily re-enter tokens/ids

### Steps to reproduce

* start with no channels
* import from internet
* enter a channel ID
* import a subset of the channel
* go back to the beginning, and try to import more items. you need to re-enter the ID

### Context

* Kolibri version: 0.7-beta

-----

cc @jonboiser

**Comment by jonboiser** [comment]
If a channel is installed, we can append it to the channels that come back from Kolibri Studio. On the face of it, though, I'm not sure how to distinguish an installed&unlisted channel from an installed channel that was imported from a USB drive (which would not appear on the "Kolibri Central Server" page).

One idea I brought up with @khangmach was to provide a way to go directly to the "Select Content Page" from the "Manage Content Page". Currently, the only thing you can do with an installed channel on MCP is delete it.

**Comment by indirectlylit** [comment]
I wouldn't worry about making that distinction on your "channel list" page. Could be useful but I don't think it's critical.

This issue _only_ refers to the "import from central server" channel listing.

The intended behavior was roughly:

> Any unlisted channels that you've previously unlocked are shown at the top of the channel listing page with an 'unlocked' icon ![image](https://user-images.githubusercontent.com/2367265/33408904-bfcd278c-d52d-11e7-9baf-daf3aa55f6ea.png). They appear above public channels in the listing.

**Comment by indirectlylit** [comment]
> One idea I brought up with @khangmach was to provide a way to go directly to the "Select Content Page" from the "Manage Content Page". Currently, the only thing you can do with an installed channel on MCP is delete it.

I do like that idea. I find it confusing to click the top-level 'Import' button when I want to update an existing channel.

**Comment by jonboiser** [comment]
My point was that all installed channels whether from public, unlisted, or USB look the same once they are installed. To get an unlisted & installed channel to show up on the "Available Channels Page", I would need to take the public channels and add the unlisted & installed channels to that list.

The problem is that there is no simple way to tell that a channel was such an unlisted & and installed channel (again, because they all look the same once they are installed).

**Comment by indirectlylit** [comment]
My understanding is the flow would work something like this:

* user enters a token or ID, which is saved to the kolibri DB in a list
* when we query Studio for available channels, we pass that token or ID as a parameter
* Studio annotates the list of available channels with which ones are unlisted

This is all independent of whether or not the channel was previously installed.

**Comment by jonboiser** [comment]
We can query studio for all public channels via Kolibri Studio's `api/public/channels`

To determine whether a given channel is unlisted, we would need to make one request to `api/public/channels/lookup` to verify that it is an unlisted channel. So, to implement this, we would go through the difference of Installed Channels and Public Channels and do this query for each one.

I've asked some people if they could simply annotate the Channel, post-installation as a non-public channel, so it is available immediately and we don't need to query Studio.

**Comment by indirectlylit** [comment]
The main user story that I'm thinking about is:

* Day 1
  * Go to import from central server
  * Don't see my unlisted channel? Okay, I have an ID
  * There it is. But .. I'll do this later
* Day 2
  * Go to import from central server
  * Oh - there's my unlisted channel, right at the top!
  * profit
