### ISSUE TITLE
import/export: confusing behaviors during channel metadata loading

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2721]
### Observed behavior

1. When initially viewing a large channel that hasn't been viewed before, we show a message which makes it look like the import has already started ("Downloading channel contents...")

2. While this is happening, the checkboxes below are confusingly not disabled. It's possible to click around and navigate. (Weren't we going to put a semitransparent overlay on everything?)

3. Clicking '<- Select content' at the top does nothing

![image](https://user-images.githubusercontent.com/2367265/33355201-57d07bd8-d46b-11e7-99a0-eec1dd639d98.png)

4. It feels like you accidentally started a long-running operation here. But refreshing to try and get out makes things even more confusing because it goes here:

![image](https://user-images.githubusercontent.com/2367265/33355266-9f7f922a-d46b-11e7-9bc0-70b46f196749.png)

### Expected behavior

Message should indicate that we are just loading metadata _about_ the contents.

### User-facing consequences

Oh no! I didn't mean to do that. Let me refresh... Crap now what's happening????

### Steps to reproduce

* View a large channel that has _not_ been previously viewed, e.g. KA english
* Refresh

### Context

* Kolibri version: 0.7-beta

----

cc @jonboiser

**Comment by jonboiser** [comment]
A detail to note is that the content shown in the screenshot is not from KA, it's from Be Strong. So this is because the state isn't being cleaned when moving backwards in the workflow.

**Comment by indirectlylit** [comment]
ooh interesting - I didn't notice that

**Comment by indirectlylit** [comment]
much of this has been mitigated
