### ISSUE TITLE
import/export: flickering info messages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2722]
### Observed behavior

when exporting, a few messages are shown too briefly to be seen:

![gifmakerproject1](https://user-images.githubusercontent.com/2367265/33357271-06889886-d476-11e7-8aee-cf39964f2bcd.gif)

### Expected behavior

If a message is shown, it should persist long enough to be seen. Otherwise it shouldn't be shown at all.

### User-facing consequences

slight, nagging worry that something important happened

### Steps to reproduce

click 'export' without a place to export to

**Comment by christianmemije** [comment]
We could maybe replace the loading `ui-alert` with a `ui-progress-linear`. And the stacking could be avoided by moving the `drive-list` inside the transition.

**Comment by indirectlylit** [comment]
similar observation from @khangmach during hack session:

> For export flow, clicking on "export" prompts modal to come up with message "finding local drives". If drive isn't found, modal closes and another one quickly appears with another mssage "No drives that can be written to are connected to the server" showing in modal. I'm not sure if this is just the quickness of the message transition/disappearing and it's actually only just one modal. Can we have a slower transition on this or possibly just have the first message collapse a bit slower without closing out the modal/opening a new one?

**Comment by indirectlylit** [comment]
began addressing aspects of this in #4472

let's apply the same logic to the drive selectors

**Comment by indirectlylit** [comment]
this appears to be addressed
