### ISSUE TITLE
import/export: rename 'select' to 'import'?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2724]
### Observed behavior

Users click Import, then Select, then Import again:

1. ![image](https://user-images.githubusercontent.com/2367265/33357615-fddcf400-d477-11e7-9d0b-0f44bdc61233.png)
2. ![image](https://user-images.githubusercontent.com/2367265/33357621-090055c0-d478-11e7-96dd-55dd54a08248.png)
3. ![image](https://user-images.githubusercontent.com/2367265/33357631-17a9d510-d478-11e7-8e58-0de08e3c0663.png)

### Expected behavior

I would expect us to use the same verb throughout

### User-facing consequences

It's confusing to switch the name of the action partway through the flow

----

cc @jonboiser @khangmach @jtamiace

**Comment by indirectlylit** [comment]
@khangmach I think that would make sense if the first 'import' button said something else. As it is though, they've already clicked 'import' once, and that didn't start an immediate import either

**Comment by indirectlylit** [comment]
I'll close this - doesn't seem super critical - though language definitely seems weird to me

**Comment by indirectlylit** [comment]
re-opening based on recent feedback that 'select' is very confusing. cc @khangmach @jtamiace - thoughts?

**Comment by jtamiace** [comment]
I think Khang's reasoning still applies. 

A specific instance of a user misinterpreting the select button happens on page 11 of this doc https://docs.google.com/document/d/1HFLW6kkeg0EMgBb412sKc2jq3zNkeg8cAOGYbG2UsbE/edit

**Comment by indirectlylit** [comment]
okay

> Select button: User thought this would start the process of importing the channel, and was hesitant because of space constraints (Kira 1b)

sounds like both 'select' and 'import' have the same connotation?

**Comment by jessicaaceret** [comment]
Yep, that's the sense I got from it

**Comment by jtamiace** [comment]
Yep, that's the sense I got from it

**Comment by khangmach** [comment]
I can see how select could be misleading. Lets perhaps change the text to something more neutral and nonthreatening...maybe just a simple "View"?

**Comment by indirectlylit** [comment]
Let's look at this in concert with any potential updates we do to import tree navigation and content-selection. If we end up using clickable cards for those pages, we could probably use them on this page, too.

**Comment by indirectlylit** [comment]
fixed in #3717
