### ISSUE TITLE
import/export: make "Import" more prominent?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2725]
### Observed behavior

The most important button on the page gets a little lost with low contrast, sandwiched between two bits of metadata. 

![image](https://user-images.githubusercontent.com/2367265/33357718-ca94e930-d478-11e7-8fbf-70c72570930f.png)

### Expected behavior

It should be very clear what the primary action is

### User-facing consequences

The user may not immediately know what to do.

* Maybe make it primary and left-aligned, clearly associating it with the purple checkboxes?
* Can also consolidate all size metadata on the right, so they're also clearly associated with the information below

![image](https://user-images.githubusercontent.com/2367265/33357790-5b2a526e-d479-11e7-8e0d-7d88357a3155.png)

-----

cc @khangmach @jonboiser

**Comment by jonboiser** [comment]
@khangmach Is there a style guide rule for this? A common pattern for multi-part workflows is to make the "go forward" button the most prominent element. I think this is done in the modals to lead up to the above screen.

**Comment by khangmach** [comment]
> It should be very clear what the primary action is
The import button was originally the primary purple color, but was changed to secondary grey to 
1. accommodate the "update channel" button potentially being the primary action on the page
2. attempt to be consistent with a table style, even though we don't have guidelines for those yet.

I don't have any qualms with changing the import button to primary and then the "update channel" button to secondary grey. 

>Can also consolidate all size metadata on the right, so they're also clearly associated with the information below
@indirectlylit It's not clear in your mockup that the "resources selected" text is associated with the information below. Your mock does highlight the purple import button, which is good, but we immediately lose the important association between "X selected" and the import button.

**Comment by indirectlylit** [comment]
> It's not clear in your mockup that the "resources selected" text is associated with the information below

By that I just meant that it's groups similar meta-data into a column on the right so it's easier to scan:

![image](https://user-images.githubusercontent.com/2367265/33395276-dabe5338-d4f9-11e7-9b8d-3233711d72ae.png)

**Comment by khangmach** [comment]
I think this version address your point and brings back the association between import button and "X selected" text.
![1](https://user-images.githubusercontent.com/25045166/33395581-e1711f52-d4fa-11e7-904f-2a5024dd1af5.png)

**Comment by indirectlylit** [comment]
sounds good!
