### ISSUE TITLE
add a 'world' icon to 'change language' menu option

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2742]
### Observed behavior

If you switch to a language that you're unfamiliar with, the "Switch language" label is unintelligible:

![image](https://user-images.githubusercontent.com/2367265/33406838-9da2052e-d523-11e7-9b7c-025f20267011.png)

### Expected behavior

There should be some visual clue to which item is the "Switch language" function, for example a 'globe' icon:

![image](https://user-images.githubusercontent.com/2367265/33407002-37424202-d524-11e7-99c1-a8518255137e.png)

### User-facing consequences

user might have difficulty recovering from casual experimentation or a mistake

------

cc @rtibbles I recall there was some discussion about this in the past. Thoughts?

**Comment by khangmach** [comment]
sounds reasonable.
![language dropdown](https://user-images.githubusercontent.com/25045166/34232924-81774fec-e597-11e7-927f-8c9cfb9756f3.png)

**Comment by christianmemije** [comment]
There is still the issue of discover-ability. How would a user know to click on that user menu to change the language? If anything they would click on the hamburger icon to open the side nav.

And on the language switcher component, a user would also not know to click on the more languages select if they do not understand that language. Fb uses the + symbol.
![image](https://user-images.githubusercontent.com/7193975/35059240-58482c7a-fb6f-11e7-81b1-9617dd38c4fd.png)

Fb

![image](https://user-images.githubusercontent.com/7193975/35059302-83905e7a-fb6f-11e7-9550-418d19a90666.png)

**Comment by indirectlylit** [comment]
> There is still the issue of discover-ability. How would a user know to click on that user menu to change the language?

presumably because that's how they switched the language a moment before?

**Comment by christianmemije** [comment]
That's assuming that the user changed it themselves. A most probable use case for the language switcher is that a user shows up to an interface they can't understand?

**Comment by christianmemije** [comment]
![wut](https://user-images.githubusercontent.com/7193975/35069193-56f05dd8-fb8e-11e7-9e48-3256d077ef59.gif)

@khangmach  Why display the k-select when there is more room. It would make more sense to display the k-select when space is limited.

**Comment by khangmach** [comment]
@christianmemije If i can recall, I think we all decided somewhere a while ago that it matches how the onboarding language select works. For the record, I agree with you, displaying the k-select when space as limited, but I think it was a matter of reusing code.

**Comment by indirectlylit** [comment]
> A most probable use case for the language switcher is that a user shows up to an interface they can't understand?

Might be? However when I filed this issue, it was because I did this:

* Hmm, I wonder what it will look like when I switch to a language I don't know...
* Oh crap, how do I get back?

**Comment by christianmemije** [comment]
The globe would still be super helpful, but you would know that it is one of the items in the dropdown. I think language switcher in general needs to be more discoverable?

**Comment by indirectlylit** [comment]
> I think language switcher in general needs to be more discoverable?

perhaps. I know a lot of thought went into the current location .. recommend adding a clearinghouse issue if you have recommendations or complaints

**Comment by indirectlylit** [comment]
FYI, I'd like to make sure we get this in 0.8
