### ISSUE TITLE
content language filter has no options

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2743]
### Observed behavior

ain't much filterin' to do

![image](https://user-images.githubusercontent.com/2367265/33407861-2476b398-d528-11e7-9d96-dafc363006a9.png)

### Expected behavior

we should either hide the filter, or have it populate from the available languages

### User-facing consequences

currently looks like an unfinished feature

-----

cc @jonboiser

**Comment by jonboiser** [comment]
This is because the Kolibri studio channels don't have their language codes set as of now.

http://studio.learningequality.org/api/public/v1/channels

**Comment by christianmemije** [comment]
Also, we should be using our `k-select` component :cry:

**Comment by jonboiser** [comment]
@jayoshih @ralphiee22 Do we need to republish these channels to get the language codes back? It would also be nice if all the channels had nice final thumbnails to address #2744.

**Comment by jayoshih** [comment]
@jonboiser Which channels are these? Not sure if the language hasn't been set on the channels or they just need to be republished

**Comment by jonboiser** [comment]
Just checked and the public channels do have language codes now. Do need to make some UI code changes though.

**Comment by jayoshih** [comment]
Yes, republishing them now
