### ISSUE TITLE
import/export: progress bar overlaps channel thumbnail

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2744]
### Observed behavior

the channel thumbnail is partially obscured:

![image](https://user-images.githubusercontent.com/2367265/33407957-92e496c4-d528-11e7-9f90-a83ab16287b3.png)

### Expected behavior

regular page flow

### User-facing consequences

not much

**Comment by jonboiser** [comment]
The original thumbnail that's published is cut off like that

![download](https://user-images.githubusercontent.com/10248067/33410497-61f19d8e-d535-11e7-9718-8f9a0fdcf7c7.png)

**Comment by indirectlylit** [comment]
derp
