### ISSUE TITLE
import/export: hide back arrow link in '<- Select content'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2745]
### Observed behavior

When in this state, the link at the top doesn't do anything:

![image](https://user-images.githubusercontent.com/2367265/33408156-bd936872-d529-11e7-856e-f1c5ef18d403.png)

### Expected behavior

The link should be hidden

### User-facing consequences

Users will try to get out when loading metadata takes too long, and when clicking that link doesn't work they'll do something more drastic like pressing the browser 'back' button or refreshing. Both of these will have negative consequences.

### Steps to reproduce

* delete all your channels
* go to import a large channel like KA (en)
* try to get out

----

refs #2721, #2732

**Comment by jonboiser** [comment]
This is because the URL does not change to `content/wizard/topic/?pk=` URL until the DB is downloaded. Currently, the handler for this URL will break if the `pk` is empty or if the pk is filled in but DB is not downloaded. Will need to think about how to handle this.

**Comment by jtamiace** [comment]
Is it possible to put a cancel button on the progress bar?

If not, yes, agree that allowing to go back would be good, possibly with a pop up modal that says something along the lines of "exiting will cancel download. exit? y/n"

**Comment by indirectlylit** [comment]
the tricky part right now is that I don't think you _can_ cancel. The server is effectively locked up during this state

**Comment by jonboiser** [comment]
The `startremotechannelimport` task that runs when getting Metadata is a non-cancellable task. To make it cancellable, there may need to be some cleanup that needs to be implemented.

**Comment by rtibbles** [comment]
One issue is this: https://github.com/learningequality/kolibri/issues/2041 - once you've committed to importing the metadata into the database, you can't turn back.

**Comment by indirectlylit** [comment]
There's a bigger issue here around the drastic consequences of simply wanting to look at what's new in a channel.

For this specific issue, can we just hide the arrow in the action bar and make the hover cursor a normal pointer? This will make people less likely to try to click it:

![image](https://user-images.githubusercontent.com/2367265/33473864-f81cf9fa-d62c-11e7-9f96-f6c74aeb20e1.png)

When the metadata import is complete, we can show it again.
