### ISSUE TITLE
Special characters are accepted at the full name input.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2749]
### Observed behavior

I can use special characters in the full name input, when I creating a Kolibri user account. 

### Expected behavior

We must filter the special characters at `full name` input.

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Errors and logs

![screen shot 2017-11-30 at 4 11 46 pm](https://user-images.githubusercontent.com/8663934/33420357-38dcc3a6-d5e9-11e7-92e5-a48432bbcff8.png)

### Steps to reproduce

When creating a Kolibri user account, Input any special characters at `full name` section.

### Context

* Kolibri version: v0.7.0-beta3
* Operating system: Windows 7 32 bit
* Browser: Google chrome Version 62.0.3202.94 (Official Build) (32-bit)

**Comment by rtibbles** [comment]
A little wary of limiting the characters that people can use for their name.

**Comment by indirectlylit** [comment]
I think the concern is addressed by https://github.com/learningequality/kolibri/pull/2753
