### ISSUE TITLE
Browser keep refreshing at the profile page.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2750]
### Observed behavior

A user with a special character full name at the profile page will cause the browser to keep refreshing.

### Expected behavior

Fix the issue why it's keep refreshing.

### User-facing consequences

![temp](https://user-images.githubusercontent.com/8663934/33421818-4f590360-d5ee-11e7-92c0-714c023613ff.gif)

```
browser console logs
```

### Steps to reproduce

Create a Kolibri user account with a special character full name. And navigate at the profile page.

### Context

Kolibri version: v0.7.0-beta3
Operating system: Windows 7 32 bit
Browser: Google chrome Version 62.0.3202.94 (Official Build) (32-bit)

**Comment by jonboiser** [comment]
Cool @mrpau-richard! I just reproduced this. But it seems to be due to the name you used `';';';'`. Just adding a `;` for example doesn't caused this.

**Comment by jonboiser** [comment]
Just noticed that having this name also causes the 'facility management' page to refresh too.

**Comment by jonboiser** [comment]
@mrpau-richard If you're having trouble using the app, you can fix your user by going to this API UI http://localhost:8000/api/facilityuser and plugging the ID at the end of that url: e.g. `http://localhost:8000/api/facilityuser/6bcd358057d95c64c41fe89066bb6287/`

**Comment by christianmemije** [comment]
Fixes in #2753
