### ISSUE TITLE
menu items are clipped

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2765]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/33459811-408b67fa-d5e0-11e7-9a76-f92de9edc395.png)

### Expected behavior

not clipped

**Comment by jonboiser** [comment]
Looks like the same observation in #2874, where characters with descenders get cut off. My hunch in that issue is that the styles for Keen UI assume Roboto, which may not work for the font used in the app.

**Comment by indirectlylit** [comment]
fixed by #3216
