### ISSUE TITLE
Suggestion: only show channels that contain exercises, when creating exams

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2770]
### Observed behavior

When I create an exam, it asks me to choose a channel:

![image](https://user-images.githubusercontent.com/618416/33461969-c5e129b8-d5e9-11e7-9f45-403142ff97ba.png)

This list includes channels that have 0 exercises in them, which leads to the following situation:

![image](https://user-images.githubusercontent.com/618416/33461956-ad71d058-d5e9-11e7-91a0-85e917942af2.png)

### Expected behavior

This is just a UX improvement suggestion, but it might be nice to filter out channels for which we don't have any exercises, to keep the list short and avoid confusion.

### User-facing consequences

"Ooh, yes, I want to test them on the MIT Blossoms content. Wait, what's going on, why can't I create an exam?"

**Comment by jonboiser** [comment]
@lyw07 Do you think this is another use case for the "available" flag?

**Comment by rtibbles** [comment]
Probably not, because `available` would be for having any content available, rather than seeing if there are any exercises in it. I think we already return information on how many exercises are available in the channel to the frontend though.

**Comment by rtibbles** [comment]
Could probably just do with some more logic after this fetch: https://github.com/learningequality/kolibri/blob/release-v0.7.x/kolibri/plugins/coach/assets/src/state/actions/exam.js#L311

**Comment by lyw07** [comment]
I think I had this issue as well during the bug bash. But my case was that one of the resources inside the exercise topic has been imported. I guess it's because not all the resources under the exercise have been imported. So probably not a use case of the "available" flag.

**Comment by indirectlylit** [comment]
If we start hiding items from this list, we should add some indication of why the channels were hidden. For example:

"3 channels without exercises are not shown"

Additionally, it's currently possible to create an exam even when nothing is selected (e.g. if you have no channels). We need validation logic to prevent this.

**Comment by rtibbles** [comment]
Note that I fixed the descendants detail view on the ContentNode endpoint that this uses to only return available exercises, just prior to 0.7.0, so this should just be a matter of filtering channels with no returned exercises from that endpoint.

**Comment by indirectlylit** [comment]
Still a little tricky to indicate to the user that channels were hidden because they didn't contain exercises, but yes that would be a good quick improvement

**Comment by indirectlylit** [comment]
additionally, errors were observed by @mrpau-richard in #2964 when trying to make an exam with a channel that hasn't finished downloading

**Comment by khangmach** [comment]
- Agree that we should filter out channels that don't have exercises. 
- I don't think it's a priority to include information as to why the content is hidden. 

Showing something like "3 channels without exercises are not shown" gives coaches something to worry about and I wouldn't like coaches to dwell on something like that during the creation process. Through some observations of teachers I think it's already quickly learnable to them that they can only pull from exercises. 

To re-emphasize that coaches should and will choose only exercises, we should tidy up and be more clear with the verbiage we use. See fix in screenshot below:

![exam channel filter text](https://user-images.githubusercontent.com/25045166/35003857-fde84ca0-faa2-11e7-9b7d-ee1fbf746467.png)

**Comment by indirectlylit** [comment]
> To re-emphasize that coaches should and will choose only exercises, we should tidy up and be more clear with the verbiage we use. 

Agreed

![image](https://user-images.githubusercontent.com/2367265/35004132-d81ac916-faa3-11e7-9e3a-78eaf740f515.png)

Still maybe a bit confusingly worded? Also, 'create exam' is a bit misleading for the button text since that happens later.

Maybe something like this?

> ## Create a new exam
> You can select exercises from the channels below.
> 
> **Select channel:** Khan Academy
> 
> <kbd>CANCEL</kbd> <kbd>CONTINUE</kbd>

**Comment by khangmach** [comment]
@indirectlylit that sounds good too!

**Comment by rtibbles** [comment]
As an interim fix for 0.8.0 before the exams revamp in 0.9.0, @khangmach and I discussed, and suggestion is to just exclude 'exerciseless' exams from the drop down.

**Comment by indirectlylit** [comment]
yay!
