### ISSUE TITLE
Visually difficult to line up topic rows with "resources on your device" status, especially on wide screen

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2771]
### Observed behavior

![image](https://user-images.githubusercontent.com/618416/33462183-073f639c-d5eb-11e7-8a96-737f3d5f8ae5.png)

### Expected behavior

Perhaps alternating row colors or some other way to provide a visual trace across a row?

### Context

* Kolibri version: 0.7.0.dev020171130214228-git
* Operating system: Ubuntu
* Browser: Chrome

**Comment by indirectlylit** [comment]
looks like we just need to set a max width? cc @khangmach

**Comment by khangmach** [comment]
can we try a max width of a standard resolution desktop screen, 1024?

**Comment by indirectlylit** [comment]
Yes, but I think we'll need to mock up precisely what this looks like in terms of where margins would go. There's a somewhat related issue here: https://github.com/learningequality/kolibri/issues/2768

I think this max-width handling is something that should be addressed holistically across the app, not just in this one page.

**Comment by indirectlylit** [comment]
another example from lessons:

![image](https://user-images.githubusercontent.com/2367265/36874679-ac5f6314-1d61-11e8-8f2f-d73791a430c1.png)
