### ISSUE TITLE
Inconsistent alignment between resource counts and DELETE buttons on content page

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2773]
### Observed behavior

This seems to be due to variable-height thumbnails, but it might be good to change the layout such that the alignment of these pieces isn't impacted in this way, because it looks a bit messy:

![image](https://user-images.githubusercontent.com/618416/33462347-d7b17bb4-d5eb-11e7-9bde-1b967985d827.png)

### Context

* Kolibri version: 0.7.0.dev020171130214228-git
* Operating system: Ubuntu
* Browser: Chrome

**Comment by christianmemije** [comment]
Fixed in #2783
