### ISSUE TITLE
import/export: long delay before deleted channel disappears

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2787]
### Observed behavior

when deleting a channel, it takes a while to disappear. Refreshing makes it disappear sooner:

![gifmakerproject2](https://user-images.githubusercontent.com/2367265/33471156-c501ad2e-d620-11e7-851b-fc9a767de79a.gif)

### Expected behavior

Channel should disappear as soon as you dismiss the progress bar

### User-facing consequences

app looks a bit broken

**Comment by jonboiser** [comment]
This is a remnant of the old implementation of the Task-polling code, which, as a side-effect, would refresh the list of Channels. Back then, doing an optimistic removal of the Channel would just cause the Channel to come back in the next poll (and stay around in some cases!).

Maybe this isn't an issue anymore.

**Comment by indirectlylit** [comment]
note. this is still happening

**Comment by rtibbles** [comment]
This no longer appears to be extant.
