### ISSUE TITLE
many numerals are not localized

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2788]
### Observed behavior

for example...

* Percentage imported during content import
* How many users you are going to add to a class
* Choose number of questions when creating an exam
  * ![image](https://user-images.githubusercontent.com/2367265/33471547-bed28138-d622-11e7-8f93-05b7e4cae78b.png)
* Showing how many people are in a class
  * ![image](https://user-images.githubusercontent.com/2367265/33471573-e32116f8-d622-11e7-867c-44ed9d52bab4.png)
* Validating the number of characters in a text field
  * ![image](https://user-images.githubusercontent.com/2367265/33471592-fc76ad0c-d622-11e7-9942-eca738d17a93.png)

...there are likely many more and we should do a thorough audit.

### Expected behavior

All numbers should be localized.

### User-facing consequences

Unintelligible numbers in many cases

**Comment by benjaoming** [comment]
* Currently, are there any examples in the codebase of localized numbers?
 * How normal is it for Western digits to show up in Arab contexts? Can't be all that rare :)

**Comment by indirectlylit** [comment]
> Currently, are there any examples in the codebase of localized numbers?

Sure. For example in `channel-contents-summary.vue`:

![image](https://user-images.githubusercontent.com/2367265/34964130-ebcd123c-fa00-11e7-97fb-ab127003ebf7.png)


-----

The general strategy is to pass the number through a localization string:

```html
<p>{{ $tr('version', { version: versionNumber }) }}</p>
```

```javascript
$trs: {
  version: 'Version {version, number, integer}',
},
```

Anywhere we simply output the number directly in the template will be unlocalized, like if we'd tried to do this:

```html
<p>Version {{ versionNumber }}</p>
```

**Comment by benjaoming** [comment]
Thanks @indirectlylit -- would this be enough information to work out the issue @mrpau-richard ?

**Comment by indirectlylit** [comment]
open question about syntax here: https://github.com/learningequality/kolibri/pull/3084#pullrequestreview-89224343

**Comment by mrpau-richard** [comment]
Yeah those examples are enough. Thanks @indirectlylit & @benjaoming
