### ISSUE TITLE
cannot import from USB

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2790]
### Observed behavior

observed by @khangmach during hack session:

Cannot import content from USB, displays an error "transfer failed, please try again":

* Export some content from channel Be Strong Online onto a USB
* try to import that same content
* encounter transfer error

Question from @jonboiser:

>Can you go through the steps? If I download all of "Be Strong" to my computer, then export all of "Be Strong" to my USB, then I should not be able to re-import to my PC. I would have to delete "Be Strong" first.

### Expected behavior

description of what behavior was expected but did not occur

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

### Steps to reproduce

precise steps that someone else can follow in order to see this behavior

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by indirectlylit** [comment]
If this is true it's fairly critical. @khangmach could you demo it for @jonboiser tomorrow?

**Comment by jonboiser** [comment]
#2796 should prevent a subset of these scenarios from happening. @lyw07 is working on the unavoidable subset from causing the transfer to fail.
