### ISSUE TITLE
Language codes for more channels than available are visible appear in the language filter

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2791]
### Observed behavior

reported by @jonboiser: Language codes for more channels than visible appear in the language filter

(after patch https://github.com/learningequality/kolibri/pull/2760)

### Expected behavior

Only languages that are available should be shown.

### User-facing consequences

The user is mislead.

### Steps to reproduce

* View some remote channels, but don't download resources from all of them
* Language codes for the no-resource channels will show up in filter

**Comment by jonboiser** [comment]
#2760 fixes this too
