### ISSUE TITLE
Cannot read property 'connection' of undefined

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2793]
### Observed behavior

I have this `Cannot read property 'connection' of undefined` error after I fill up the Kolibri admin account.

### User-facing consequences

![screen shot 2017-12-01 at 4 15 50 pm](https://user-images.githubusercontent.com/8663934/33473823-ebcf7e80-d6b2-11e7-95b8-6b91a60d64fc.png)

The Kolibri server log file is empty.

### Steps to reproduce

Install the latest [pre-release](https://github.com/learningequality/kolibri/releases) of Kolibri windows installer. After the installation, fill up the Kolibri admin account details and submit it, then you will have this issue.

### Context

* Kolibri version: v0.7.0-beta4
* Operating system: Windows 7 32 bit.
* Browser: Google chrome Version 62.0.3202.94 (Official Build) (32-bit)

**Comment by indirectlylit** [comment]
thanks! fixed in beta5 in #2763
