### ISSUE TITLE
Can't export a Kolibri content at OS X El Capitan system storage

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2804]
### Observed behavior

The Kolibri export can't detect the system storage of OS X El Capitan.

### Expected behavior

I exported a Kolibri content at Windows 7 32 bit system storage, and it should do the same behavior at the OS X EL Capitan.

### User-facing consequences

implications and real-world consequences for learners, coaches, admins, and other users of the application

### Errors and logs

Export content at OS X EL Capitan.
![screen shot 2017-12-04 at 3 48 38 pm](https://user-images.githubusercontent.com/8663934/33541590-9dfbeab8-d90a-11e7-9ec9-e6e0424d023f.png)

Export content at Windows 7 32 bit.
![screen shot 2017-12-04 at 3 52 31 pm](https://user-images.githubusercontent.com/8663934/33541755-468f58cc-d90b-11e7-8039-be78ad6acf26.png)

### Steps to reproduce

Export a Kolibri content at the OS X El Capitan system storage.

### Context

* Kolibri version: v0.7.0-beta5
* Operating system: OS X El Capitan 10.11.6
* Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by indirectlylit** [comment]
Since exports write to the root directory, Kolibri in fact should not have permission to write to the drive running the OS. I'm actually surprised it does have permission in Windows - that seems wrong?

**Comment by indirectlylit** [comment]
closing - behaves as expected
