### ISSUE TITLE
import/export: when only one drive option is available, select it by default

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2807]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/33566736-c3907076-d8d5-11e7-8fd9-c24e2f39b7a5.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/2367265/33566745-c93ef4de-d8d5-11e7-9cdc-e8f393caa1b7.png)

### User-facing consequences

one extra click

### Steps to reproduce

* plug in a single USB drive
* start import or export process

**Comment by mrpau-richard** [comment]
I'll work in this issue @indirectlylit

**Comment by indirectlylit** [comment]
thanks!
