### ISSUE TITLE
content descriptions are unsafely rendered as raw HTML

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2810]
### Observed behavior

The [description](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/content-page/index.vue#L46) is rendered as [raw HTML](https://vuejs.org/v2/guide/syntax.html#Raw-HTML).

### Expected behavior

All user-generated content should be sanitized.

### User-facing consequences

Our users are susceptible to XSS

### Open question

Are any users relying on this bug/feature? Would removing it break existing content?

**Comment by rtibbles** [comment]
I thought this was meant to be markdown, not raw HTML??

**Comment by christianmemije** [comment]
The `zero` preset disables all options by default including the html option. https://markdown-it.github.io/markdown-it/#MarkdownIt.new

**Comment by indirectlylit** [comment]
thanks! missed that
