### ISSUE TITLE
add hidden H1 to 'recommended' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2818]
### Observed behavior

Currently, the top-level 'recommended' page does not have an H1 title.

### Expected behavior

All pages should have an H1. In this case, it should have the CSS class `visuallyhidden` and an internationalized title that says "Recommended"

### User-facing consequences

users of screen readers will not understand the content as easily

**Comment by luna215** [comment]
Hi, I'm having trouble finding the file where this issue is arising? Can someone point me in the right direction?

**Comment by luna215** [comment]
I was able to find a recommended page, however, I am not sure if this is the one that needs the bug fix. I found this recommended page in this path:
kolibri/plugins/learn/assets/src/views/recommended-subpage/index.vue

Also, how can I view the bug itself? I tried to to change the url, but it keeps redirecting me to this url: 
http://127.0.0.1:8000/learn/#/content-unavailable

**Comment by indirectlylit** [comment]
Hi @luna215 thanks for working on this

>  I found this recommended page in this path:
kolibri/plugins/learn/assets/src/views/recommended-subpage/index.vue

That corresponds to this page: http://kolibridemo.learningequality.org/learn/#/recommended/featured/2217430caf794279b83560e4b20e7f5b

It already has an `h1` so we don't need to update it.

The file that you're looking for is the (poorly-named) `learn-page`: [kolibri/plugins/learn/assets/src/views/learn-page/index.vue](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/learn-page/index.vue#L4)

You can add an `h1` tag with class `visuallyhidden` after the opening `div`.

>  it keeps redirecting me to this url:
http://127.0.0.1:8000/learn/#/content-unavailable

you'll need to [import some content](http://kolibri.readthedocs.io/en/release-v0.7.x/manage.html?highlight=import#import-content-into-kolibri)

**Comment by rtibbles** [comment]
Fixed in #3155
