### ISSUE TITLE
In content import/export, change option from "Kolibri Central Server" to "Kolibri Studio"?

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#2831]
And all other references in this feature to "Central Server" 
<img width="398" alt="screen shot 2017-12-05 at 12 02 15 pm" src="https://user-images.githubusercontent.com/6668144/33628334-44691290-d9b5-11e7-9ada-93f205e7fce2.png">

### User-facing consequences

Especially if someone had been curating on Studio, they may be expect to see "Studio" as an option, or something internet-related, and may not equate "Central Server" and "Studio." I know we know what central server means but are we expecting majority of our admin users & single-learner users to know what it means too?

### Context

* Kolibri version: 0.7.0.dev020171128234418-git
* Operating system: MacOS Sierra
* Browser: Chrome

**Comment by ivanistheone** [comment]
In a previous version of the new import wizard, there was a choice to input an alternative Kolibri Studio instance (e.g. http://develop.studio.learningequality.org/), so I guess the *Central* was necessary  to indicate it's the "offical one".

@jtamiace @jamalex @rtibbles  Do we foresee supporting multiple import sources in the future? e.g. for use case with partner organizations or testing purposes. It would be confusing to see in the above dialog, but maybe behind a "more options" small font link?

Studio is currently hardcoded in settings: https://github.com/learningequality/kolibri/blob/develop/kolibri/deployment/default/settings/base.py#L143  Might want to support an ENV variable of the same name `CENTRAL_CONTENT_DOWNLOAD_BASE_URL`

**Comment by indirectlylit** [comment]
> Do we foresee supporting multiple import sources in the future?

Earlier designs had an option to add more online sources/hosts. I believe we will still implement this eventually.
