### ISSUE TITLE
after canceling an import, the partial channel doesn't show up without refresh

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2833]
### Observed behavior

after #2778:

* begin importing a new channel
* cancel

at this point, the new channel does not show up

* refresh

now the channel shows up

Initially we thought it might be related to #2787, but it doesn't seem to be the case.

### Expected behavior

channel should show up immediately

### User-facing consequences

user might not realized that they preserved a subset of the content even after canceling

### Context

* Kolibri version: 0.7

-----

cc @rtibbles

**Comment by mrpau-richard** [comment]
I will defer on working this issue for now, And prioritise the issues that's in 0.9.0 release.

**Comment by rtibbles** [comment]
I think this should now be fixed - @jonboiser can you confirm that this is the case? (we are refreshing the channel list on completion, failure or cancellation).

**Comment by indirectlylit** [comment]
confirmed
