### ISSUE TITLE
Cheat mode for videos and audio: INSTA-COMPLETION!

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2840]
### Observed behavior

Seeking around in the video while watching allows videos (and audio) to be completed more quickly than the duration of the media file. Sometimes dramatically so:

![somuchprogresssolittletime](https://user-images.githubusercontent.com/618416/33639923-a2952f98-d9e2-11e7-865b-07ea9bb2d52a.gif)

### Expected behavior

Progress completion should at minimum take as long as `duration / play speed`. Jumping around should not speed this process up.

### User-facing consequences

Kids love to cheat. We must thwart them at every turn!

### Context

* Kolibri version: 0.7.0.dev020171205234838-git
* Operating system: Ubunty
* Browser: Chromey

**Comment by christianmemije** [comment]
Fixed in #2853
