### ISSUE TITLE
Updating a channel will cause it to be removed from the available channel list

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2841]
### Observed behavior

When a channel gets updated, it will not be found in the available channel list anymore. That is to say, the channel is marked as unavailable, although it has content already downloaded before.

### Expected behavior

The channel should still exist in the available channel page

### User-facing consequences

Users will think the channel gets removed

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
server logs
```

```
browser console logs
```

### Steps to reproduce

1. Create a test channel on studio and publish it
2. Import the channel with all of its content and go to the `content` page to see that it's listed as an available channel
3. Make some changes to the channel and publish it again
4. Go to the channel page and see that there's a new version available. Click `update` to update the channel to the latest version
5. Go back to the `content` page to see all the available channels and check that the test channel doesn't exist

### Context

* Kolibri version: 0.7
* Operating system: Mac OS X / demo server
* Browser: chrome

**Comment by indirectlylit** [comment]
cc @jonboiser I heard that you love import/export issues - any help would be appreciated :)

**Comment by rtibbles** [comment]
Fixed in #2847
