### ISSUE TITLE
fix historic migrations to be Py2/3 compatible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2842]
### Observed behavior

@benjaoming reported:

```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

### Expected behavior

@rtibbles reposponded

> we need ... fix our historic migrations to be Py2/3 compatible

### User-facing consequences

I believe this means that this blocks users on Py3?

### Steps to reproduce

originally observed by @radinamatic while testing the deb package `kolibri_0.7.0_beta5-0ubuntu1_all.deb` on Ubuntu 16.10 using `sudo dpkg` in https://github.com/learningequality/kolibri-installer-debian/issues/9

### Context

* Kolibri version: ?
* Operating system: ?
* Browser: ?

**Comment by benjaoming** [comment]
@indirectlylit should also add a step to [the release process](http://kolibri-dev.readthedocs.io/en/develop/release_process.html#squash-migrations) to ensure that there aren't any changes in models not reflected in migrations.

**Comment by jamalex** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/2860
