### ISSUE TITLE
inconsistent language ordering logic

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2843]
### Observed behavior

see front page, which gives precedence to non-western alphabets:

![image](https://user-images.githubusercontent.com/2367265/33647869-fe73203a-da0b-11e7-8e7d-c4fba0ef6410.png)

vs modal:

![image](https://user-images.githubusercontent.com/2367265/33647922-32fc78a6-da0c-11e7-9c15-fccdac895235.png)

### Expected behavior

Consistent order

### User-facing consequences

currently the home page is dominated by non-western alphabets, which is a little confusing

-----

cc @rtibbles

**Comment by indirectlylit** [comment]
Currently we use two different ordering schemes. Recommend we standardize on the one defined in the `mixin.js` file rather than using `localeCompare`.

**Comment by rtibbles** [comment]
Fixed in #2858
