### ISSUE TITLE
disable or fix 'Edit on GitHub' links

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2850]
### Observed behavior

Links are broken:

![image](https://user-images.githubusercontent.com/2367265/33650975-fc9cd17c-da18-11e7-94d1-70b36daf9154.png)

### Expected behavior

Links should be removed or fixed

### User-facing consequences

Frustration

### Steps to reproduce

See live docs:

* http://kolibri-dev.readthedocs.io/
* http://kolibri.readthedocs.io/

**Comment by benjaoming** [comment]
Displayed link:
https://github.com/learningequality/kolibri/blob/origin/release-v0.7.x/docs/index.rst

Correct link:
https://github.com/learningequality/kolibri/blob/release-v0.7.x/docs/index.rst

I suspect that `origin/` is added by mistake in `sphinx_rtd_theme`, will investigate...

**Comment by benjaoming** [comment]
Seems its an upstream regression, so I'll subscribe to the issue and re-enable the links once upstream has fixed the issue.

https://github.com/rtfd/readthedocs.org/issues/3203

**Comment by benjaoming** [comment]
I think I fixed it, but not sure because I don't :rocket: a whole local RTD deployment :)

https://github.com/rtfd/readthedocs.org/pull/3377

**Comment by indirectlylit** [comment]
confirmed: 
![image](https://user-images.githubusercontent.com/2367265/33918247-38664226-df67-11e7-86b1-729a97199ce2.png)
