### ISSUE TITLE
After updating a channel, the content doesn't get updated until refreshing the page

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2851]
### Observed behavior

After updating a channel, the content isn't updated without a refresh or going to some other page and then coming back to the channel page.

### Expected behavior

It would be better if the users can see the update result immediately

### User-facing consequences

Users might be confused about the update result if they don't refresh the page or go to other pages and then come back to the channel page

### Steps to reproduce

1. Create a test channel on Studio and publish it
2. Import the channel to Kolibri
3. Make changes on the channel and publish it again on Studio
4. Go to the channel page on Kolibri and update it

### Context

* Kolibri version: 0.7-beta7
* Operating system: Mac OS X/demo server
* Browser: chrome

**Comment by indirectlylit** [comment]
is this the same issue as https://github.com/learningequality/kolibri/issues/2939 !

**Comment by lyw07** [comment]
I think so!

**Comment by indirectlylit** [comment]
closing as dupe
