### ISSUE TITLE
Update button will not be shown without refreshing the page

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2852]
### Observed behavior

If there's an updated version of a channel from Kolibri Studio, Kolibri will not show that the channel has a newer version available until the users refresh the page

### Expected behavior

Not sure if this is expected, but I guess it could be better if the users can see there is a newer version available without refreshing the page? Or maybe we can put messages such as "Please refresh the page to see if there's a newer version available" in the channel page?

### User-facing consequences

Users  don't know if there's a newer version available if they don't refresh the page

### Steps to reproduce

1. Create a test channel on Studio and publish it
2. Import the channel to Kolibri
3. Make changes on the channel and publish it again
4. Go back to the channel page on Kolibri to check if the update button is shown to indicate that there's a newer version available. (I tried with waiting for 30 minutes but the update button was still not shown)

### Context

* Kolibri version: 0.7
* Operating system: Mac OS X/ demo server
* Browser: chrome

**Comment by jonboiser** [comment]
This may be difficult to implement, since Kolibri cannot receive push notifications, which is how some apps might implement this (e.g. after updating on Kolibri Studio, Kolibri gets a push notification regarding the update, causing the "upgrade" button to appear without a refresh).

If the goal is informing users about updates, could we achieve something similar for users by maybe sending an email from Kolibri Studio to the user?

**Comment by rtibbles** [comment]
I think this is probably fairly low priority in general, as the chances of a channel changing while a user is logged into the content management page would be low, unless they were the ones directly changing it. In which case they *know* that a change has been made, and would presumably refresh if they didn't see it?

**Comment by lyw07** [comment]
Yeah I think that could work. anyways, I think this is going to be an enhancement. Thank you for explaining the difficulties!

**Comment by lyw07** [comment]
Yeah I think that could work. anyways, I think this is going to be an enhancement. Thank you for explaining the difficulties!
