### ISSUE TITLE
Squash migrations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2868]
### Observed behavior

In our release flow, we note that migrations should be squashed before a release. This description could be improved.

However, the immediate task would be to actually squash the current migrations. Would be nice as a 0.7.1 patch release.

### Expected behavior

Migration activity is kept minimal

### User-facing consequences

Slow migration, risk of migration errors (migration in database, not on disk and vice versa)

**Comment by rtibbles** [comment]
@benjaoming I have avoided squashing migrations for now, because until we upgrade to Django 1.11 and we can mark data migrations as elidable, creating squashed migrations will give us minimal impact for now. Would rather target this to 0.8.0 (currently upgrading to django 1.11 on develop!)

**Comment by benjaoming** [comment]
Agreed, didn't take that into consideration - but always nice to have the issue opened up :)

Until then, we can offset parts of this by managing our migrations more deliberately:

 - Read through migrations manually
 - Move no-ops (changes to `verbose_name` etc) to field definitions in former migrations
 - Name the migrations in a meaningful way, not `0006_auto_20171207_1941.py` :)

(I mentioned this in a commit comment, but I can't find it)

**Comment by rtibbles** [comment]
Yes, although I am a little wary of giving license to edit previous migrations :)

**Comment by benjaoming** [comment]
It's harmless when one is sure that it's a database no-op.. adds pressure on PR reviews though :)

**Comment by indirectlylit** [comment]
de-prioritizing since performance benefits are negligible

**Comment by indirectlylit** [comment]
closing because current behavior doesn't impact users or developers
