### ISSUE TITLE
In import/export, it's possible for user to see outdated version of channel (under certain conditions)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#2869]
### Observed behavior

To view an Unlisted (i.e. not public) and unavailable (i.e. no resources downloaded on device) channel, one must enter the Channel's token in the "Enter channel token modal".

Once it's been made available (by downloading resources), then these issues do not apply.

Here are some issues

**Not force fetching**: If an unlisted channel has been updated on Studio within a single session on Kolibri, then when going to the Select Resource Page for that channel, there not be a prompt to update the channel. This is because the RemoteChannelResource is not doing a force fetch.

~**Auto-updating** The upgrade button flashes briefly after the new metadata is downloaded. This is probably due to a timing issue between when `pageState.channelList` is updated and when `pageState.wizardState.transferredChannel` is updated.~ addressed by #3243

### Expected behavior

**Updates occur in a single session**: Can be fixed by force fetching when getting Channel info through the modal.

~**Auto-updating**: The update button does not flash.~ addressed by #3243

### Context

Kolibri version: 0.7

**Comment by indirectlylit** [comment]
A lot has changed related to this functionality in 0.13. I'll close this and we can open a new issue if something similar re-occurs
