### ISSUE TITLE
HTML5 apps register 'progress' regardless of actual interaction

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2876]
### Observed behavior

When reading an html5app content, users don't need to finish viewing the whole content to get the points. Instead, if they just wait for about 15 seconds, they will get the points without doing anything.

### Expected behavior

Users get the points when they read something

### User-facing consequences

Students can pretend that they finish reading by just leaving the page open for several seconds

### Errors and logs

…

### Steps to reproduce

1. Import some content from African Storybook
2. Open an HTML5APP content
3. Don't do anything but just leave the page open
4. Wait for about 15 seconds, and you will get 500 points

### Context

Kolibri version: 0.7.0
Operating System: Mac OS X
Browser: Chrome

**Comment by indirectlylit** [comment]
migrating to clearinghouse
