### ISSUE TITLE
Add a bit of test coverage after django 1.11 upgrade

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2923]
### Observed behavior

Some lines went untested in the Django 1.11 upgrade, and it's likely easier to add automatic tests than to try them manually (they're mostly API endpoints)

https://github.com/learningequality/kolibri/pull/2882

### Expected behavior

It works

### User-facing consequences

Unexpected edge-case minor paper cuts

**Comment by indirectlylit** [comment]
closing as stale. If there are specific tests that need to exist, let's open issues for those
