### ISSUE TITLE
Downloading content: Confirm before starting

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2926]
### Observed behavior

Minor detail: There's a typo, "Downoading"

When clicking a channel's "Select" button, it should not start to download immediately. As a user, I don't even know how big a download it is.

1) "Select" button - rename to "Details & Download" ?

![image](https://user-images.githubusercontent.com/374612/33849138-ff6a96b4-deaf-11e7-99e4-1b0c95d769c3.png)

----

2) This page should have a "Download" button, also should say something about that the current version doesn't support canceling?

![image](https://user-images.githubusercontent.com/374612/33848306-9aab1a3e-dead-11e7-90bc-afd07524842a.png)

----

### Expected behavior

As a user, I would like to know more before deciding to start the download. How much will it take? How big is the file? How much storage does it take? Can I cancel the download? Resume it?

…

### User-facing consequences

Having no cancel option, I have to kill the server to stop it.

### Errors and logs

n/a

### Steps to reproduce

Go to Device > Content > Kolibri Studio Channels, click Select

**Comment by indirectlylit** [comment]
breaking out into more granular feedback above

**Comment by benjaoming** [comment]
@indirectlylit actually I thought the channel itself was being downloaded, "Downoading channel contents" would give that impression :)

Anyways, maybe we should have a high-level issue for tracking the channel import related issues? I struggled a bit to find out whether this was already reported, and how to report it.

**Comment by indirectlylit** [comment]
Yes, that's a good idea. I might also try a project board for organization.

In general, there are two kinds of issues, with some fuzzy grey area between:

1. quick changes that are really "bugs" (to be tracked as Kolibri issues)
2. feedback on the design (to be tracked as clearinghouse "user feedback" to feed into the next iteration of design)
