### ISSUE TITLE
'delete channel' modal too verbose

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2936]
### Observed behavior

reported by @khangmach during a hack session:

![image](https://user-images.githubusercontent.com/2367265/33900923-f4f6d9e8-df24-11e7-85a1-e996e0e1913c.png)

### Expected behavior

> Destroy superfluous text. Suggestion to cut channel deletion modal text to "This channel and its content will be deleted from your device. To restore, you will need to import it again from the internet or storage device." && Delete the bold text following heading. Change primary CTA text from "confirm" to "delete"

### User-facing consequences

Too much overwhelming text

### Context

Kolibri 0.7

**Comment by khangmach** [comment]
Here's a version with trimmed copy. 

![screencapture-localhost-8000-management-device-1513798330075](https://user-images.githubusercontent.com/25045166/34224817-100e0d32-e579-11e7-9946-56c24c82aee0.png)


>To restore, you will need to import it again from the internet or storage device

We can remove this text. If an admin managed to import this channel onto the device in the first place, I imagine they know to go through the same import process to get the channel back. Also, "restore" implies getting the same content back through a re-import, which is not guarenteed via a new import selection

**Comment by khangmach** [comment]
I think it wouldn't hurt. Perhaps we can replace "this channel" in the mock above with <strong>channel name</strong>

**Comment by indirectlylit** [comment]
Looks good. One potential issue with the phrase "and all of its content" [sic] is that resources _won't_ be removed if referenced by other channels.

How about simply:

> ## Delete channel
> 
> Are you sure you want to remove '[channel name]' from your device?

(also note single quotes around channel name)

**Comment by khangmach** [comment]
That's true. Looks good

**Comment by christianmemije** [comment]
Fixed in #3093 :tada:
