### ISSUE TITLE
resource counts are incorrect until refresh after updating channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2939]
### Observed behavior

After updating a channel, resource counts are incorrect. In the case below, the channel originally had 2 resources and then one was deleted in version 3. After updating, the count looked like this:

![image](https://user-images.githubusercontent.com/2367265/33904606-eb473f1c-df30-11e7-92a2-7852c1e40a2f.png)

After refreshing and going to import again, the count looked like this:

![image](https://user-images.githubusercontent.com/2367265/33904612-f35dcb6c-df30-11e7-8c8e-26686fbfabe0.png)

### Expected behavior

After updating a channel, resource counts should be accurate

### User-facing consequences

Incorrect understanding of what happened during the update

### Steps to reproduce

* create a channel with a couple items and publish
* import everything in it
* delete an item from the channel. republish it
* go to import it. click 'update'
  * channel version updates
  * 'on your device' numbers update
  * 'total' numbers do not update

### Context

Kolibri 0.7.0

**Comment by indirectlylit** [comment]
hey @mrpau-richard - are you still working on this?

**Comment by mrpau-richard** [comment]
@indirectlylit Yeah, I'm currently working on this issue.
