### ISSUE TITLE
rst warning: Bullet list ends without a blank line; unexpected unindent.

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2958]
### Observed behavior

When building the user docs, we get 

```
/Users/d/Projects/learning_equality/repos/k2/docs/learner.rst:48: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

It's not clear to me from the code what this is referring to...

### Expected behavior

No errors

### User-facing consequences

None, but it's preventing us from having error- and warning-free builds

### Steps to reproduce

Build the user docs with `sphinx-build`

### Context

* #2598

**Comment by indirectlylit** [comment]
cc @radinamatic and @benjaoming your ReStRuctUreDTexT skills would be helpful here :)

**Comment by radinamatic** [comment]
@indirectlylit I reworked a lot of stuff in #3039 and that error is no more 😉 

Once it is merged, this can be closed.

**Comment by benjaoming** [comment]
@indirectlylit I think you might have solved this yourself :tada: :heart:
