### ISSUE TITLE
make admin creation the final step of the setup wizard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2961]
### Observed behavior

Currently order:

* Name your Facility
* Create your Admin account
* Choose a Facility setup

### Expected behavior

New order:

* Name your Facility
* Choose a Facility setup
* Create your Admin account

### User-facing consequences

jump back and forth between topics

### Context

Kolibri 0.7

**Comment by jonboiser** [comment]
#2983
