### ISSUE TITLE
Channels that's not available in creating exam, are showing

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2964]
### Observed behavior
When creating an exam, some channels that's not yet downloaded, are showing in the select channel dropdown.

### Expected behavior
Those channels that is not yet downloaded, must be filtered out. 

### User-facing consequences

![gif-temp](https://user-images.githubusercontent.com/8663934/34029056-5e30607c-e1a1-11e7-9ca3-25ec3ba437dd.gif)

### Context

 * Kolibri version `0.8.0.dev020171215005858-git`
 * Operating system OS X El capitan
 * Browser Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by indirectlylit** [comment]
thanks! I added a note to #2770 referencing the additional information here
