### ISSUE TITLE
Travis' new build stages & build matrix optimizations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2975]
High-level issues:

 * [ ] Tox fetches dependencies both into its virtualenv and in `kolibri/dist` via `make staticdeps`
 * [ ] Assets and dependencies are applied to build environments that they might be irrelevant to, for instance building docs? Linting? Conditional tests, like build tests
 * [ ] Conditional tests aren't conditional enough. The whole build environment should be exited as quickly as possible if relevant files aren't changed. For instance, don't build docs, when nothing in the docs has been edited. Don't check licenses of dependencies if dependencies haven't changed etc.

I would propose that we stage our Travis builds to shorten build times, this is inspired by CherryPy's setup.

@ralphiee22 has also mentioned the new test tags introduced in Django 1.10 so we can chunk our tests into a slow and fast set.

1. Linting
1. Building assets, unifying this as 1 build for all tests
1. Upload assets to S3
   https://docs.travis-ci.com/user/build-stages/#Sharing-files-between-jobs-via-S3
1. Basic tests in 1 Python version
1. Expanded tests to all tox envs
1. Conditional tests

See: https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions

Related: #3321 

![image](https://user-images.githubusercontent.com/374612/34075348-9fc152f2-e2c4-11e7-9fb2-838928dbd29a.png)

**Comment by rtibbles** [comment]
Sounds good - at the same time, is it still important to have our build tests in Travis? Buildkite should be performing this test for us, effectively.

**Comment by rtibbles** [comment]
We should also fix this issue: https://github.com/learningequality/kolibri/issues/551 which should increase confidence across Python versions.

**Comment by benjaoming** [comment]
I'm a big fan of Travis for our test matrix stuff and now these new stages :)

I don't think Buildkite is mature for the testing and linting yet for a couple of reasons. But it seems great for building installers and deploying stuff :)

**Comment by rtibbles** [comment]
I didn't want buildkite to test anything or lint anything - simply that we do a build every time on buildkite, so our tests specifically for the Python build pipeline are duplicative.

**Comment by benjaoming** [comment]
Oooooh "build tests" sorry, kind of ambiguous :) But yes, those should be removed. Or at least used for the actual tests.

**Comment by rtibbles** [comment]
I guess another question here is: if you don't edit any python files in a PR, should we still run the Python tests, and vice versa, if you don't edit any frontend files.
