### ISSUE TITLE
12-factor app review

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#30]
Suggestion that we give our project a 12 factor review:
- [x] I. Codebase
- [ ] II. Dependencies
- [ ] III. Config
- [ ] IV. Backing Services
- [ ] V. Build, release, run
- [ ] VI. Processes
- [ ] VII. Port binding
- [ ] VIII. Concurrency
- [ ] IX. Disposability
- [ ] X. Dev/prod parity
- [ ] XI. Logs
- [ ] XII. Admin processes

**Reference:** http://12factor.net/

**Process:** For each of the 12 factors, we get some inspiration and possibly open up a single PR to resolve it. The PR is linked here. If the task requires more work, open an issue and refer it to the task list above. Once processed, mark the task as completed.

I feel like taking the lead on this, and I won't make it a long a messy process once started. But if any one wants to join in, that'd be great :)

**Comment by indirectlylit** [comment]
Let's track this in Trello since it's not an item that can be closed with a single PR

https://trello.com/c/A2YGGeAp/119-12-factor-review

**Comment by rtibbles** [comment]
Possible that we should migrate this into our release flow documents?

**Comment by indirectlylit** [comment]
Closing because performing the audit would not solve a specific unmet need for our users or our developers. We can open follow-ups for more specific issues if and when they arise.
