### ISSUE TITLE
Inconsistent naming/terminology - users vs. learners

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#3021]
### Observed behavior

Enroll users to a class: base page and modal mention `users` all over, just the button names `learners`.

![selection_172](https://user-images.githubusercontent.com/1457929/34471056-b454239e-ef3e-11e7-8300-7e3cfd87ce52.png)

### Expected behavior

Role names in one same flow of steps should be consistent. 

### User-facing consequences

Inconsistency might create confusion for both Kolibri end users and translators.

**Comment by radinamatic** [comment]
On a similar note: `user kind` or `user type`...?

![selection_175](https://user-images.githubusercontent.com/1457929/34471480-37c8c110-ef4b-11e7-8845-223b27501039.png)

`Type` sounds better to me.

**Comment by khangmach** [comment]
Sweet, let's consolidate and be more clear on verbiage. See suggestions in screenshots below:

![usertype3](https://user-images.githubusercontent.com/25045166/35005954-1834a606-faaa-11e7-90aa-3284e235ea08.png)
![usertype2](https://user-images.githubusercontent.com/25045166/35005956-184a7224-faaa-11e7-87d9-8f776d01e386.png)
![usertype1](https://user-images.githubusercontent.com/25045166/35005957-185fc854-faaa-11e7-8925-04e9e5df7a6f.png)

**Comment by indirectlylit** [comment]
@khangmach remember to wrap user-generated text in single quotes!

**Comment by indirectlylit** [comment]
> Are you sure you want to enroll these users in 'Class A'?
