### ISSUE TITLE
learner is not able to distinguish question type is multiple select or single selection 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3024]
### Observed behavior
While answering the questions, learner is not able to identify the question is of single selection or multiple selection type. Showing same symbol for multiple select and single selection. For more clarification, see attached screenshots.

### Expected behavior
It must show checkbox for multiple select question type.

### Steps to reproduce
1. Login with superuser.
2. Import channel 35173f142916466dab7ee90e1df100c3 (Mutiple Selection and Single Selection).
3. Try to solve exercise. (Exercise contains two multiple select question and two single selection question).

### Context

 * Kolibri version : Kolibri 0.7.0
 * Operating system: Ubuntu 14.04
 * Browser: Chrome

### Screenshots
Single selection:
![1](https://user-images.githubusercontent.com/12776071/34514516-ce63a9f2-f093-11e7-8273-fd6e646194c1.png)

Multiple selection:
![2](https://user-images.githubusercontent.com/12776071/34514525-d65258e8-f093-11e7-9da3-c8dd843a8908.png)

**Comment by jonboiser** [comment]
A user might be able to infer that an exercise is a "multiple selection" type based on the prompt "Chose all answers that apply" (versus "Choose 1 answers").

There is a convention in web forms, though that one uses checkboxes for fields with multiple selections, and radio buttons for fields allowing one choice.

**Comment by rtibbles** [comment]
This is entirely internal to Perseus, so this is a won't fix.
