### ISSUE TITLE
Need to refresh the page to show result of the exam

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3025]
### Observed behavior
When learner submit exam without answering any question, it is showing Start button for the same exam for learner. But after refreshing the page, it vanished and result of the exam is shown on screen. 

Note: Result is appearing correctly without refreshing the page when learner attempts questions of the exam.

### Expected behavior
After submitting exam, it must show result. No need to refresh the page.

### Steps to reproduce
1. Create the exam.
2. Login with learner.
3. Try to start the exam and submit the exam without answering any question.
4. And try to submit the exam by attempting questions. You will get to know what is actually happening.
 
### Context

 * Kolibri version: kolibri 0.7.0
 * Operating system: ubuntu 14.04
 * Browser : chrome

### Screenshots
Before starting the exam
![1](https://user-images.githubusercontent.com/12776071/34517600-af50758c-f0a1-11e7-968e-757b13f97625.png)

![2](https://user-images.githubusercontent.com/12776071/34517611-bbedbfca-f0a1-11e7-81f1-e772e7e57284.png)

Submit exam without attempting any question
![3](https://user-images.githubusercontent.com/12776071/34517622-c66ade88-f0a1-11e7-87ac-397eb996de87.png)

Still showing start button
![4](https://user-images.githubusercontent.com/12776071/34517641-d3dd4f56-f0a1-11e7-9a1d-0acf775cdb2e.png)

After refreshing the page
![5](https://user-images.githubusercontent.com/12776071/34517651-e27f7dea-f0a1-11e7-92e7-b694b38e3616.png)

**Comment by indirectlylit** [comment]
@swapnil106111 this should be addressed in 0.8

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri 0.8.0. Showing result of the submitted exam without refreshing the page.
![3025_1](https://user-images.githubusercontent.com/12776071/37964303-9f65ff7e-31de-11e8-919c-3ffb822fbe4c.png)
![3025_2](https://user-images.githubusercontent.com/12776071/37964305-9fbc388a-31de-11e8-864e-d6d172755edc.png)
![3025_3](https://user-images.githubusercontent.com/12776071/37964307-9ff0be34-31de-11e8-8c18-8e15b476f627.png)

**Comment by indirectlylit** [comment]
great, thanks for testing!
