### ISSUE TITLE
Coach Topics Reports page show Channel items that are not installed

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3029]
### Observed behavior

The Coach Topics Reports (where you can view progress on any Topic or Resource for a given Classroom) shows all of the Content for a Channel, even if only a subset is actually installed on the device.

![screen shot 2018-01-04 at 12 22 09 pm](https://user-images.githubusercontent.com/10248067/34582925-92306eb8-f14a-11e7-8700-528f8709d007.png)

### Expected behavior

Some kind of indication that the different Resources are not available for Learners to engage with.

### User-facing consequences

* Extra noise in the Coach Reports
* Inconsistency between Learner and Coach's conception of the Channel's contents

### Steps to reproduce

1. Install a subset of a channel
1. Go to the Coach's Topic Reports
…

### Context

Tell us about your environment, including:
 * Kolibri version:develop
 * Operating system
 * Browser

…

**Comment by rtibbles** [comment]
Recommended fix: all coach report backends should filter by availability, when there is no recorded activity (I think we would probably still want to show historic records for content that has since been removed).

**Comment by indirectlylit** [comment]
> all coach report backends should filter by availability, when there is no recorded activity (I think we would probably still want to show historic records for content that has since been removed).

Agree in principle, but unsure if this might break assumptions about having content metadata available. Might be safer to just filter everything by availability for now? We can introduce the more advanced version (historic records) as an upgrade in the future.

**Comment by rtibbles** [comment]
Sorry, I missed the response here. If the content is available in the database to filter, then the metadata exists, just the content itself does not.

**Comment by rtibbles** [comment]
Basic issue has been resolved, changing priority label for the more advanced approach.

**Comment by jonboiser** [comment]
As of 0.12, Coach Reports don't include the report type in the original posting.

If these reports are ever brought back into a future release, they must make sure to omit non-available nodes.
