### ISSUE TITLE
error "OperationalError: database is locked."

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#3036]
![screen shot 2018-01-06 at 20 03 08](https://user-images.githubusercontent.com/3889468/34639343-a9045162-f321-11e7-905c-680aea391134.jpg)
 
Hello,  these days I try to set Kolibri developments environment.
When I try to solve the second problem.
It keeps getting me an error "OperationalError: database is locked."

I tried to change the SQLite's timeout to 1000
but get me same errors.
```
        'OPTIONS': {
            'timeout': 100,
        }
```

**Comment by indirectlylit** [comment]
Thanks for the report.  Could you please share:

 * Steps to reproduce
 * Kolibri version
 * Operating system

Any additional details would be appreciated.

**Comment by rationality6** [comment]
Sorry for little late response.
I Installed Anacond3 and make environmental with the conda.
I was used Python2 to develop branch. After the conda virtual environments and python3. The error was gone.

Steps to reproduce was that I used python2 to develop branch.
Kolibri version was current develop branch.
Operating system was Mac osx 10.11.6.

**Comment by indirectlylit** [comment]
Thanks for the update! Glad it's working for you.

Switching environments may have been a coincidence though; let us know if the error re-appears.
