### ISSUE TITLE
Reset to defaults settings need to refresh the page to update the checkbox.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3049]
### Observed behavior
After clicking the `reset to defaults settings` the checkbox is not updating at the second time. It will only update if you refresh the page.

### Expected behavior
After clicking the `reset to defaults settings` it should update the checkbox.

### User-facing consequences
![gif-temp](https://user-images.githubusercontent.com/8663934/34711711-51d276e4-f55b-11e7-8837-eb3fe723bcbf.gif)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.8.0
 * Operating system: Mac OS X El Capitan
 * Browser: Google Chrome Version 63.0.3239.

**Comment by jonboiser** [comment]
It looks like that last option "Allow users to sign-in with no password" (`learnerCanLoginWithNoPassword`) was never given a default after it was added to this UI.

https://github.com/learningequality/kolibri/blob/6b53cd01973929e7796dd8b3da99276ae06ad2d8/kolibri/plugins/facility_management/assets/src/constants.js#L24

@mrpau-richard This should be a quick fix of adding an entry like (`learnerCanLoginWithNoPassword: false`) to the file above. I'm assuming that is the default (false).

 Would you like to submit a patch for it?

**Comment by mrpau-richard** [comment]
@jonboiser Okay, i'll work on it.
