### ISSUE TITLE
Using 'id' consistently in API responses

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3072]
`id` and `pk` are used seemingly interchangeably in responses from the REST API , which is kind of confusing.

There seems to be a preference in the JS code for `id`, as when a response uses `pk`, it is often renamed to `id`. `pk` is also hints at the underlying database, while `id` is a little more abstract.

**Comment by rtibbles** [comment]
Yeah, this seems like an appropriate refactor to undertake.

**Comment by indirectlylit** [comment]
> `pk` is also hints at the underlying database, while `id` is a little more abstract

Yes, that was the reason I'd tried to map `pk` to `id`
