### ISSUE TITLE
Making vue component names consistent with their filenames and switch to PascalCase

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3073]
Make the component `name` close to its filename (or vice-versa) so it's easier to find.

For instance, if I see "LearnerReportPage" in the Vue devtools, I first assume that it's file name is "learner-report-page.vue" (which it isn't). So I then have to grep 'learnerReportPage' and find out that it's in "learner-list-page.vue".

**Comment by indirectlylit** [comment]
I believe @christianmemije is also passionate about this, and may have started work on it at some point?

**Comment by indirectlylit** [comment]
see also: https://vuejs.org/v2/style-guide

**Comment by christianmemije** [comment]
I am also for this, but have not started any work on it. We just have to agree to go with PascalCase or kebab-case.

**Comment by indirectlylit** [comment]
my vote is for PascalCase everywhere, so that file names are valid javascript variable names

**Comment by jonboiser** [comment]
PascalCase also has the benefit of looking like the component name in vue-devtools. In some text editors, fuzzy file search is also optimal with PascalCase, so you can find LearnerReportPage with "LRP".

**Comment by jonboiser** [comment]
Here's a spreadsheet with some the components with inconsistent names

https://docs.google.com/spreadsheets/d/15zsNM9U7UDcJzPx7QLSdtrm8j0ngJVmvYbbVQIk5Ynw/edit?usp=sharing

**Comment by indirectlylit** [comment]
Can we add a prettier-type process to set component names based on filenames? That would fix this forevermore...

**Comment by indirectlylit** [comment]
fixed in #4034
