### ISSUE TITLE
Can input 'e' and '.' into "Number of questions" field during exam creation

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3081]
### Expected behavior

<img width="1248" alt="screen shot 2018-01-12 at 3 44 45 pm" src="https://user-images.githubusercontent.com/6668144/34899867-59a76468-f7b0-11e7-95f8-4024d4b4adab.png">

Should not be able to input these characters

### Steps to reproduce

1. Navigate to Exams in Coach
2. Create new exam
3. Input 'e' and '.' into the number of questions field

### Context

Version: 0.7.0 
http://kolibribeta.learningequality.org
MacOS Sierra
Chrome

**Comment by jtamiace** [comment]
Can also input '+'

**Comment by jonboiser** [comment]
Number inputs support scientific notation, so "e" and "." "+" and "-" are okay, but "eee..." would be interpreted as NaN in code.

Might need to apply some hacks to override this kind of input, as suggested in this [SO article](https://stackoverflow.com/questions/33132933/is-there-a-way-to-suppress-scientific-notation-for-input-type-number#36755620)

**Comment by jonboiser** [comment]
This probably doesn't need to be fixed, since there is a validation message when you try obviously bad numbers like "eeee...".

It's very unlikely that anybody would do this, but we might need to guard against things like "5E-3", which might fall in the allowed range, but is bad because it's a decimal 0.005.

**Comment by jonboiser** [comment]
Turns out you can also enter decimals directly, which causes an error

![screen shot 2018-01-16 at 5 02 21 pm](https://user-images.githubusercontent.com/10248067/35020092-1e1b2948-fadf-11e7-8827-d3594585e07f.png)

**Comment by rationality6** [comment]
I agree with @jonboiser, This probably doesn't need to be fixed.

**Comment by rationality6** [comment]
I added one more validation. How do you guys think?
![screen shot 2018-01-17 at 13 59 45](https://user-images.githubusercontent.com/3889468/35026513-d568a986-fb8e-11e7-84fa-20bb9d2641d1.jpg)
![screen shot 2018-01-17 at 13 59 55](https://user-images.githubusercontent.com/3889468/35026520-d7669180-fb8e-11e7-9aa8-c8668667402a.jpg)

**Comment by jonboiser** [comment]
@jtamiace @rationality6 I think we could do adjustment of the current validation message:

Now: "This exam requires a number of questions between 1 and 50"

(Removing the extra text referring to the exam)
Proposal: "This must be a whole number between 1 and 50"

**Comment by khangmach** [comment]
No need for additional validation for a super small edge case like this, and I don't think there's a need to withhold "." from being entered either.

Just "Enter a number between 1 and 50" as the same validation message for all invalid inputs, and flag any unnatural number input, e.g 4.3, to prompt that validation message as well. No one is just going to intentionally type in 4.3. It will be an accident and the user will correct their mistake.

**Comment by indirectlylit** [comment]
validation was improved in #3106
