### ISSUE TITLE
Hard-coded version numbers in docs

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3088]
### Observed behavior

Current docs have hard-coded version strings in links, we need to either bump them to 0.7.1 or have a mechanism that's automatic -- KA Lite docs have a recipe.

### Expected behavior

n/a

### User-facing consequences

Gets the wrong version

### Errors and logs
n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by benjaoming** [comment]
@mrpau-richard could you have a look at this? :)

**Comment by alanchenz** [comment]
Hi @benjaoming, 
Could you link the KA Lite file that performs this mechanism as well?

**Comment by benjaoming** [comment]
@alanchenz see: https://github.com/learningequality/ka-lite/blob/master/docs/conf.py#L73

**Comment by benjaoming** [comment]
Sorry -- also this: https://github.com/learningequality/ka-lite/blob/master/docs/conf.py#L124

**Comment by alanchenz** [comment]
It looks like the only file that needs to be updated to 0.7.1 is the android.rst file. The other ones seem to already link to 0.7.1. @benjaoming I've mainly checked in the docs/install folder in kolibri. Are there any other files that might need to be updated?

**Comment by benjaoming** [comment]
@alanchenz we are moving the user docs here: https://github.com/learningequality/kolibri-docs/

They will have a hard-coded version as well in each release branch. But it will just specify major and minor, not patch: `1.2.x`

This issue is therefore stale now since the developer docs are only for the `develop` branch.
