### ISSUE TITLE
hard-coded 'content unavailable' link is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3089]
### Observed behavior

Link here is broken: 

![image](https://user-images.githubusercontent.com/2367265/34963737-fa09edf4-f9fe-11e7-8f2f-467b9143affc.png)

observed on this page: `http://localhost:8000/learn/#/content-unavailable`

Currently it points to 

```
http://localhost:8000/management/device#/content
```

This happened after a recent refactor of the management app(s) (cc @jonboiser) and wasn't caught because we don't currently have good support for cross-app linking

### Expected behavior

should point to

```
http://localhost:8000/device/#/content
```

### User-facing consequences

![image](https://user-images.githubusercontent.com/2367265/34963773-256d2d12-f9ff-11e7-808f-e1f8a4620ce0.png)

### Steps to reproduce

* remove all content
* go to 'learn' as a superuser
* click link

### Context

kolibri develop

**Comment by christianmemije** [comment]
Fixed in #3095
