### ISSUE TITLE
Provide validation for `Exam.question_sources` JSON field when creating a new Exam model

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3094]
I noticed that the `Exam` has a JSON field for `question_sources`, and has a doc string explaining what the shape of `question_sources` should be:

https://github.com/learningequality/kolibri/blob/3b4c56f3409f1f1133eb73ebdad72729749a37b9/kolibri/core/exams/models.py#L31-L39

But the `ExamSerializer` does not seem to validate `question_sources` when POSTing a new Exam. The exercise should exist before it is attached to an exam. (in case of a race condition where a question is deleted before the exam is created).

Maybe we should validate `question_sources` and other un-typed JSON fields in the API.

What are some strategies for doing this?

**Comment by rtibbles** [comment]
This was fixed in #7866
