### ISSUE TITLE
Kolibri 'core' apps not namespaced under 'core'.

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#31]
At the moment we have an inconsistent naming scheme with the core app PRs that are being proposed (#22, #25, #26, #28).

These apps have been put into the base 'kolibri' directory, rather than inside the 'core' directory. This seems misaligned to the then separate 'plugins' directory which should store 'non-core' apps.

@benjaoming, @MCGallaspy, @aronasorman, @jamalex, @66eli77 please input below - my main concern is to be idiomatic and clear in the way we structure our core vs non-core codebase.

**Comment by MCGallaspy** [comment]
Let's move the core apps into the core directory, after they're merged.

**Comment by rtibbles** [comment]
:+1:

**Comment by indirectlylit** [comment]
this is done

**Comment by jamalex** [comment]
I don't think this is done yet -- the idea here is to move `kolibri.auth` into `kolibri.core.auth` and `kolibri.content` into `kolibri.core.content`. We were kind of waiting until things stabilized before doing so. I think we can revisit post-MMVP.

**Comment by indirectlylit** [comment]
sorry!

**Comment by jamalex** [comment]
One thing for us to try when we do this:
http://marcela-campo.blogspot.com/2015/01/django-migrations-moving-django-model.html

Oh, except it actually may not be necessary! Looks like Django just uses the final module name, not the parent module, in constructing the table names, as we have:

![image](https://user-images.githubusercontent.com/618416/33959717-3afedf98-dffd-11e7-8bb1-9d1a79d1147f.png)

even though those models are under `kolibri.core.device.models`.

So, we may be able to just leave the table names untouched.

**Comment by jamalex** [comment]
So it's probably a pretty simple refactor. We'll just need to look at what external plugins might import from these apps. Not sure there are (m)any cases of that.

@indirectlylit says: https://github.com/fle-internal/kolibri-instant-schools-plugin and https://github.com/learningequality/kolibri-exercise-perseus-plugin/ I think are the only ones to check
