### ISSUE TITLE
Clarify implications of changing Superuser’s role under manage tab

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3102]
### Observed behavior
We are able to change superuser’s role under manage tab which is not actually changing any functionality of the username superuser. Hence the EDIT button next to the superuser is of no use.

Kolibri 0.7.0, we created a Admin username as superuser and also created a learner(with superuser permission). After logging in by learner(with superuser permission). In Users tab,we are able to change superuser’s role under manage tab which is not actually changing any functionality of the username superuser. Hence the EDIT button next to the superuser is of no use.

### Expected behavior
There is not effect on superuser after changing its role. So, we want to disable EDIT option under manage tab for superuser.

### Steps to reproduce
1. Login with superuser.
2. create user whose role is learner.
3. And gives permissions of the superuser to the learner.
4. Log in with learner.
5. Select facility.
6. Click USERS tab.
7. Click on Manage drop down box of superuser. 
8. Change its role.
9. logout and login with role changed user.
10. You will observe there is no change in functionality of that user even after changing its role.
 

### Context

 * Kolibri version : kolibri 0.7.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![1](https://user-images.githubusercontent.com/12776071/35149979-64cb277e-fd3e-11e7-913a-9356bf9ab429.png)
![3](https://user-images.githubusercontent.com/12776071/35149981-6565f47a-fd3e-11e7-86d8-5b01592a0d8e.png)
![4](https://user-images.githubusercontent.com/12776071/35149982-65a978c6-fd3e-11e7-9a4d-b3fd9cc440c0.png)
 
Login with superuser whose role change

![5](https://user-images.githubusercontent.com/12776071/35149985-65ea50e4-fd3e-11e7-9ce1-072a71cf94e0.png)
![7](https://user-images.githubusercontent.com/12776071/35149987-664d617a-fd3e-11e7-9a20-c116ff1c8953.png)

**Comment by indirectlylit** [comment]
@swapnil106111 -

Is your expectation that by changing the Admin with Superuser permission to a Learner, they should also lose their Superuser permission?

**Comment by rtibbles** [comment]
I think the request is that being able to edit a user's role under the facility management seems superfluous, if they are a superuser, as it does not change their capability on this device.

However, it does have an effect on their capability on other devices in the same facility, so this is meaningful, but perhaps not so meaningful in the limited syncing circumstance most Kolibri installations are currently in.

**Comment by jtamiace** [comment]
Using this doc to explore solutions for this issue and also implications for syncing https://docs.google.com/document/d/1ruraw_a4gJ7zI9B1qaJ4lroBgo2RO3qyxYrwRkBOz4s/edit#

**Comment by jtamiace** [comment]
Sharing a first pass solution and can continue iterating on here

https://www.figma.com/file/KxjIhoBljRKy71SARf1h7dO0/superuser-clarity

**Comment by jtamiace** [comment]
Gherkin stories here 

https://docs.google.com/document/d/1xrRq0UTVn0bum5YuPRQ4ZSNkgpdy5Ny4tzdvgS7lBfg/edit

**Comment by indirectlylit** [comment]
fixed in #4238
