### ISSUE TITLE
getting mastered without listening whole audio

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3109]
### Observed behavior
Without listening whole audio in kolibri-v0.4.9, it is mastered. If learner forward a audio by 20 sec until it finished, it is going to be mastered.

See attached video for more information.

### Expected behavior
It must mastered after listening whole audio.

### Steps to reproduce
1. Import channel f22d7a17992e486081e13cc93ddc7c4d (TESSA_SAMPLE).
2. Play audio by learner login.
3. Forword the audio by 20sec until it finished and observe the behaviour.

### Context

 * Kolibri version  :  Kolibri-0.4.9
 * Operating system : Ubuntu 14.04
 * Browser  : Chrome 

### Screenshots

Chrome Info:
![img_20180123_121321](https://user-images.githubusercontent.com/12776071/35262048-e12e9d1c-0038-11e8-9ac0-4b3b2714b361.jpg)

Kolibri Issue:

![img_20180123_114836](https://user-images.githubusercontent.com/12776071/35261900-3f60b7b8-0038-11e8-9254-f4d62d0b7dbc.jpg)
![img_20180123_114843](https://user-images.githubusercontent.com/12776071/35261930-62493890-0038-11e8-916e-42ca3ed9806c.jpg)
![img_20180123_114848](https://user-images.githubusercontent.com/12776071/35261951-74e13200-0038-11e8-802b-dfa4d83ce189.jpg)
![img_20180123_114852](https://user-images.githubusercontent.com/12776071/35261955-7b0117ae-0038-11e8-8a74-5f6912237039.jpg)

Video: 
[VID_20180123_114732 - converted with Clipchamp.mp4.zip](https://github.com/learningequality/kolibri/files/1654863/VID_20180123_114732.-.converted.with.Clipchamp.mp4.zip)

**Comment by swapnil106111** [comment]
Tested on Kolibri 0.7.0. If learner is listening 50 sec of audio. After watching 30sec of audio if learner wants to listen the audio from start then after listening 20 sec of audio, it is getting mastered.

**Comment by indirectlylit** [comment]
cluster of similar issues with imprecise progress tracking: #3111 #3109 #3126

**Comment by rtibbles** [comment]
This will be fixed by work under https://github.com/learningequality/kolibri-ecosystem/issues/18 - closing this as there is no defined action, and decisions have been made!
