### ISSUE TITLE
getting mastered without reading whole document

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3111]
### Observed behavior
When learner is reading a pdf files in kolibri-v0.4.9. After scrolling the pdf files two times, it is going to be mastered. 
See attached video for more information.

### Expected behavior
It must mastered by reading pdf files not by just scrolling.

### Steps to reproduce
1. Import the channel f22d7a17992e486081e13cc93ddc7c4d (TESSA_SAMPLE).
2. Open the pdf file. 
3. And scroll the pdf files and observe the behaviour.

### Context

 * Kolibri version : kolibri 0.4.9
 * Operating system : ubuntu 14.04
 * Browser : Chrome 59.0.3071.115

### Screenshots

![img_20180123_124524](https://user-images.githubusercontent.com/12776071/35265295-bbb74b3a-0045-11e8-8625-5e888d7fce8e.jpg)

Video:

[VID_20180123_124232 - converted with Clipchamp.mp4.zip](https://github.com/learningequality/kolibri/files/1655099/VID_20180123_124232.-.converted.with.Clipchamp.mp4.zip)

**Comment by swapnil106111** [comment]
Tested on Kolibri 0.7.0. If learner is reading 8 pages of document and by spending 40-50 sec on document, it is getting mastered.

**Comment by indirectlylit** [comment]
cluster of similar issues with imprecise progress tracking: #3111 #3109 #3126

**Comment by rtibbles** [comment]
This will be fixed by work under https://github.com/learningequality/kolibri-ecosystem/issues/18 - closing this as there is no defined action, and decisions have been made!
