### ISSUE TITLE
Not able to view pdf on chrome in tablet but still able to mastered 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3112]
### Observed behavior
When learner trying to access pdf's on chrome in tablet,
1. Learner is not able to see pdf because it is showing browser does not support inline pdf's.
2. Still learner is able to mastered it.

### Expected behavior
It must show pdf's so learner can read it and If learner is not able to see the content of pdf then it must not able to mastered.

### Steps to reproduce
1. Import the channel f22d7a17992e486081e13cc93ddc7c4d (TESSA_SAMPLE).
2. Login with learner.
3. Open pdf.
4. After clicking on pdf, wait for 5-6 sec it will automatically mastered.

### Context

 * Kolibri version : kolibri 0.4.9
 * Operating system : ubuntu 14.04
 * Browser : Chrome on tablet (63.0.3239.111)

### Screenshots

Tablet:
![img_20180123_121321](https://user-images.githubusercontent.com/12776071/35267048-0ac4ad26-004b-11e8-8437-c68ed36d07a8.jpg)

![img_20180123_120411](https://user-images.githubusercontent.com/12776071/35267099-34d6e75a-004b-11e8-8f9e-5236d5626555.jpg)
![img_20180123_120414](https://user-images.githubusercontent.com/12776071/35267100-350eab04-004b-11e8-9533-ba8f5840efe2.jpg)
![img_20180123_120549](https://user-images.githubusercontent.com/12776071/35267101-35940e7a-004b-11e8-9efd-8db84a3457f2.jpg)

Video: 
[VID_20180123_143001 - converted with Clipchamp.mp4.zip](https://github.com/learningequality/kolibri/files/1655251/VID_20180123_143001.-.converted.with.Clipchamp.mp4.zip)

**Comment by indirectlylit** [comment]
No points should be awarded when the content cannot be rendered

**Comment by rtibbles** [comment]
Hrm we'll have to find a platform that PDFJS doesn't work on to confirm this fix!

**Comment by christianmemije** [comment]
PDF rendering should have been fixed in 0.5
