### ISSUE TITLE
Not able to get mastered in HTML5 content

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3119]
### Observed behavior
When learner is solving questions which are present in HTML5 content, after solving all questions correctly still not getting mastered.

See attached screenshot for more reference.

### Expected behavior
It must mastered the HTML5 content.

### Steps to reproduce
1. Import the channel a2d8baae8406499096db77f73c1984ae (SAMPLE-CK12).
2. Try to solve - The Flying Birds (PLIX).
3. Observe the behaviour.

### Context
 * Kolibri version : kolibri 0.4.9
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![1](https://user-images.githubusercontent.com/12776071/35329201-f18d71dc-0124-11e8-80ba-0e191a18d88c.png)
![2](https://user-images.githubusercontent.com/12776071/35329202-f1c93082-0124-11e8-834d-8d7fd4c45e1a.png)
![3](https://user-images.githubusercontent.com/12776071/35329203-f2077ebe-0124-11e8-925f-c4e7e4b11650.png)
![4](https://user-images.githubusercontent.com/12776071/35329204-f2417e8e-0124-11e8-89cd-81fe57cf56a9.png)
![5](https://user-images.githubusercontent.com/12776071/35329205-f27cf478-0124-11e8-921b-9e16bb001e6a.png)
![6](https://user-images.githubusercontent.com/12776071/35329206-f2babb6e-0124-11e8-89b9-23962d4cc445.png)

**Comment by jonboiser** [comment]
@swapnil106111 For HTML5 apps, a user "masters" the item by spending a short amount of time on it. In the example HTML5 app you've shared, will the mastery pop-up still show up if you interact with it for at least 30 seconds?

**Comment by swapnil106111** [comment]
@jonboiser There are five questions in The Flying Birds (PLIX) HTML content and we spent more than 40-45 seconds on each questions with right answers but still not getting mastered.

**Comment by jonboiser** [comment]
@swapnil106111 I tried this out in the latest version 0.8 and users will "master" an HTML5 app after spending about 15 seconds with it. It's possible that what you're seeing is a bug in the version you're using, 0.4.9.

**Comment by swapnil106111** [comment]
@jonboiser I tried on Kolibri 0.7.0. Now, it is mastered.

**Comment by swapnil106111** [comment]
@jonboiser Tested on kolibri 0.7.0. After spending 15 sec it is getting mastered, but without doing anything it is getting mastered.

This mastery model is not effective for teacher or learners.

**Comment by indirectlylit** [comment]
Thanks @swapnil106111 

I've made a note of your feedback. We are aware that the time-based mastery model for HTML5 apps and PDF documents is not optimal, but so far don't have a good solution. We'll continue to work on it.

I'm going to close this issue because the bug is addressed in the latest Kolibri.
