### ISSUE TITLE
'Progress' shows values outside of 0-1 range in csv export of database

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#3120]
### Observed behavior

From the analytics generated and exported from Kolibri, 'progress' is measured on a scale of 0 to 1. The csv export shows records that are above 1. It's never shown as more than 1 in the frontend of Kolibri.

![image 2](https://user-images.githubusercontent.com/5150483/35353927-881d1fbc-00fd-11e8-85ab-cc4434fd5af4.png)

### Expected behavior

The expectation is to have a min value of 0 and max value of 1.  

### User-facing consequences

Values above 1 will confuse administrators and others analyzing progress of students.  

### Context

Windows OS, Kolibri version 0.5

**Comment by jonboiser** [comment]
Similar behavior was observed in #3058, although that was for Exams showing scores higher than 100% on certain screens.

**Comment by benjaoming** [comment]
Yup, sounds right @jonboiser - are we (mis)calculating progress in two places? Might be better to only calculate it in one place.

**Comment by benjaoming** [comment]
Important:

> Note that validators will not be run automatically when you save a model, but if you are using a ModelForm, it will run your validators on any fields that are included in your form.

https://docs.djangoproject.com/en/1.11/ref/validators/

This means that the validation may not trigger if data is saved through an API call. I suspect that it doesn't... and I would like Kolibri to blow up with an exception in case the frontend tries anything funny. This is the best way to track down the origin of the issue and to ensure it doesn't happen again.

**Comment by indirectlylit** [comment]
retargeting to 0.9.1 so we don't need to rush a solution to this
