### ISSUE TITLE
Point gets increased without watching whole video

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3126]
### Observed behavior
When the video played, at the bottom of the screen it has two icons backward and forwards the video, if it presses 4-5 times backward and forward simultaneously, then the video gets over and the next item pop up open and students gets points without watching the video.

See attached video for more evidence.

### Expected behavior
Learner should get points after watching whole video.

### Steps to reproduce
1. Login with learner.
2. Watch the video.
3. Try to backward and forward the video.
4. Observe the behaviour.

### Context
 * Kolibri version : kolibri 0.4.9
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Video
[WhatsApp_Video_2018-01-15_at_20.07.45.mp4.zip](https://github.com/learningequality/kolibri/files/1663977/WhatsApp_Video_2018-01-15_at_20.07.45.mp4.zip)
[WhatsApp_Video_2018-01-15_at_20.07.46.mp4.zip](https://github.com/learningequality/kolibri/files/1663979/WhatsApp_Video_2018-01-15_at_20.07.46.mp4.zip)

**Comment by swapnil106111** [comment]
@jonboiser Tested on Kolibri 0.7.0. If learner is watching 50 sec of video. After watching 30sec of video if learner wants to re-listen the video from start then after watching 20 sec of video, it is getting mastered.

**Comment by indirectlylit** [comment]
This is unfortunately "working as designed" but agreed that the behavior is incorrect from a user's perspective.

**Comment by indirectlylit** [comment]
cluster of similar issues with imprecise progress tracking: #3111 #3109 #3126

**Comment by rtibbles** [comment]
This will be fixed by work under https://github.com/learningequality/kolibri-ecosystem/issues/18 - closing this as there is no defined action, and decisions have been made!
