### ISSUE TITLE
Make target buildconfig leaves source tree dirty

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3129]
### Observed behavior

Hmm, I just spent 2 hours debugging something that is really a harsh complexity -- I would argue that a default environment should not 1) call anything in `build_tools/customize_build.py` and 2) ship with something in `kolibri.utils.build_config.default_plugins`

We now maintain a list of plugins in:

1. The `~/.kolibri/kolibri_settings.json`
1. A `DEFAULT_PLUGINS` default variable in `kolibri.utils.conf`
1. Another `plugins` in `kolibri.utils.build_config.default_plugins`
1. Yet another default set of plugins in `build_tools/default_plugins.txt`

I couldn't build developer docs locally. This I thought had something to do with my path, and that Sphinx wasn't loading the right `kolibri`, but defaulting into some system wide path. Then I started investigating the `kolibri_settings.json` in `docs-developer/_build/kolibri_home` and found that it kept reverting to a state that didn't make any sense, until I found that it was an artifact from having previously built some stuff on an older branch.

~One thing is that the `kolibri/utils/build_config` isn't cleaned by `make clean`, but another thing is that we are really building and shipping a Python module with configuration data in it and dynamically adding it to the sdist.~

### Expected behavior

Me can run `make developer-docs` when I switch around between branches and do all the mandatory stuff with `pip install -r requirements/*` :)

### User-facing consequences

n/a

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by rtibbles** [comment]
Hrm, a little confused here because `make clean` does clear the build_config folder: https://github.com/learningequality/kolibri/blob/develop/Makefile#L35.

**Comment by benjaoming** [comment]
@rtibbles I'm sure that I recognized this problem from doing a real diagnosis, but I can see the code is there in the Makefile.

The symptom was that the build kept breaking with a plugin module that didn't exist, and none of the source tree had any evidence of where this came from.

Perhaps my mistake was to have had some other kolibri installation in the path, from which the list got extracted?

**Comment by rtibbles** [comment]
Possibly, then that 'dirty' build_config module from the other kolibri was interfering?!

**Comment by indirectlylit** [comment]
Could this have happened from conflicting edits to _~/.kolibri_settings.json_?

I've begun running all my branches & virtual environments with different values of `KOLIBRI_HOME` to make switching branches easier.

**Comment by benjaoming** [comment]
> Possibly, then that 'dirty' build_config module from the other kolibri was interfering?!

I think so

> I've begun running all my branches & virtual environments with different values of KOLIBRI_HOME to make switching branches easier.

I avoid this on purpose to be as aware/disturbed/disrupted/infuriated of upgrade conflicts as possible :D

**Comment by benjaoming** [comment]
Since we now have an improved, separate handling of plugins in `~/.kolibri/plugins.json`, I'm going to close this.

If there are future issues, I should be opening issues targeting better exception messages, _rather than_ poking around at a structure designed to be optimized for other things - not per say some developer swapping around environments and eventually building developer docs with sphinx apidocs.

Thanks for the inputs
