### ISSUE TITLE
retain previously chosen questions in unmodified exercises

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3135]
### Observed behavior

When modifying the exercises in exams, the questions that are chosen from exercises that were _not_ modified are also changed. This is probably because a new random seed is chosen every time the exercise list is updated.

### Expected behavior

When a coach is creating an exam, they may be satisfied with most of it but perhaps not a particular exercise. They should be able to:

* add new exercises
* remove existing exercises

Neither of these actions should affect the randomly-chosen questions of exercises that remain the same while editing.

### User-facing consequences

It's not possible to make exercise-level edits to the exams without re-randomizing all questions in exercises that did not change.

-----

cc @rtibbles

**Comment by khangmach** [comment]
> They should be able to add new exercises & remove existing exercises

This is already possible outside of the preview. But if we are thinking about incorporating these actions inside the preview, there's an issue with hypothetically removing too many exercises that the number of questions available from the remaining exercises no longer matches the original number input.

**Comment by indirectlylit** [comment]
For this task, I don't _think_ it's necessary to change the preview UI.

> This is already possible outside of the preview. 

It's possible to add and remove exercises, but (my understanding is that) doing so shuffles the questions in un-modified exercises, which makes the function less useful than it would otherwise be. Does that sound right?

**Comment by indirectlylit** [comment]
Need to follow-up on this later. I recall there may have been differing opinions on expected behavior

**Comment by indirectlylit** [comment]
hey @christianmemije - I think this issue may be subsumed in the work that you're doing. Should we close it?

**Comment by christianmemije** [comment]
Yes should have been addressed in https://github.com/learningequality/kolibri/commit/781c442b8f119ecc5156241880b67538cf61fd7a#diff-095c3adbe675aea16d0f85df4b2261e0
