### ISSUE TITLE
The wrong VERSION file can be read on a system with several kolibri installations

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3137]
### Observed behavior

Seems this happens with the .pex:

```
python3 code/kolibri/dist/kolibri-0.7.1b1.dev+git-2-gfd48a7a.pex --version
WARNING:root:No C Extensions available for this platform.

0.7.1b1
```

I have that version installed as a system-wide Python module from the .deb, so it seems that the VERSION file in the .pex is overruled.

```
python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkgutil
>>> pkgutil.get_data('kolibri', 'VERSION').decode('utf-8')
'0.7.1b1\n'
```

Implementation looks like this

```
def get_version_file():
    """
    Looks for a file VERSION in the package data and returns the contents in
    this. Does not check consistency.
    """
    return pkgutil.get_data('kolibri', 'VERSION').decode('utf-8')
```

### Expected behavior

Use VERSION file from Pex

### User-facing consequences

Confusion

### Errors and logs

...

### Steps to reproduce

See above

### Context

After https://github.com/learningequality/kolibri/pull/3136 is merged

**Comment by benjaoming** [comment]
I will possibly try to land a fix for 0.7.1, if not, I can live with this.

**Comment by indirectlylit** [comment]
I'd prefer not to delay 0.7.1 for this

**Comment by indirectlylit** [comment]
agreed though that it would be good especially because people will be looking at version numbers after trying to import....

**Comment by benjaoming** [comment]
When reporting this, I indeed had 0.7.1b1 installed system-wide, however this is not the source for the wrong `kolibri/VERSION` value being read in the pex.

After merging #3136 this still happens

```
python3 code/kolibri/dist/kolibri-0.7.1b1.dev_git-10-gb0f4ff4.pex --version
WARNING:root:No C Extensions available for this platform.

0.7.1b1
```

It's not the `parse_version` built into Pex, and it's not reading `kolibri/VERSION` from my system-wide installation (that returns a different value).

Example that it works:

```
python3 code/kolibri/dist/kolibri-0.7.1b1.dev_git-10-gb0f4ff4.pex shell    
WARNING:root:No C Extensions available for this platform.

INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO:kolibri.core.apps:Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from pkg_resources import parse_version
>>> parse_version("0.7.1b1.dev+git-10-gb0f4ff4")
<Version('0.7.1b1.dev0+git.10.gb0f4ff4')>
```

And it's really reading this value when invoking the pex:

```
python3 code/kolibri/dist/kolibri-0.7.1b1.dev_git-10-gb0f4ff4.pex shell    
>>> import pkgutil
>>> pkgutil.get_data('kolibri', 'VERSION').decode('utf-8')
'0.7.1b1\n'
```

...so this needs more investigation from my side, I don't suppose anyone else is running into this problem.

**Comment by benjaoming** [comment]
Cannot reproduce on a system with a system-wide Kolibri installed.

```
➜  ~ ./kolibri-0.13.2b1.dev0_git.96.g348dfbb1.pex --version
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
kolibri-0.13.2b1.dev0_git.96.g348dfbb1.pex, version 0.13.2b1.dev0+git.96.g348dfbb1
```
