### ISSUE TITLE
Coach exam reports showing multiple attempts per question

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#3139]
**Observed behavior**
Upon looking at the coach exam reports, I noticed that there were multiple attempts shown for specific exam questions. I think multiple attempts are recorded because of things like, on the student's side:

1. changing the answer and clicking out of the question input box
2. Mistyping the answer and clicking out of the question input box

**Expected behavior**
There should only be one attempt recorded, which should be based on the final input when the user presses the submit exam button.

**User-facing consequences**
Trim down on irrelevant information, as only the first attempt is necessary to a coach. A record of multiple attempts here is not strong enough evidence of struggling on particular questions or a question-solving process a student had in mind.

**Steps to reproduce**
As a coach, create an exam with fill in the blank questions
Take that exam as a learner
Input an answer into a fill in the blank question
Click out of the input box, click back in, change the answer, click to another question in the exam
Check exam report of that particular learner

**Context**
 * Kolibri version: 0.7.0.dev020171129043920-git
 * Operating system: MacOS Sierra
 * Chrome

![multiple exam question attempts](https://user-images.githubusercontent.com/25045166/35641774-f745c452-0675-11e8-9fd9-e22bd688ac2a.png)

**Comment by rtibbles** [comment]
> Trim down on irrelevant information, as only the first attempt is necessary to a coach. A record of multiple attempts here is not strong enough evidence of struggling on particular questions or a question-solving process a student had in mind.

Only the final attempt is necessary for the coach to see why the learner got it wrong, surely? While I understand wanting to trim irrelevant information, if a student does actually change their answer, this is useful diagnostic information for a coach. What might be good is to reduce the interface prominence of the non-final answers.

@navakk9 any thoughts on this, and any feedback we may have received from Nalanda that would be relevant to this concern?

**Comment by navakk9** [comment]
I have nothing substantial to report back, we would have to test how often coaches use this information across all our partner deployments.

**Comment by indirectlylit** [comment]
It sounds like the bug described is that we're recording multiple attempts when there was in fact only a single attempt

**Comment by indirectlylit** [comment]
> Expected behavior
> 
> There should only be one attempt recorded, which should be based on the final input when the user presses the submit exam button.

this sounds accurate to me. If that's not happening than this is a bug

**Comment by indirectlylit** [comment]
though I'd amend it to say 


> There should only be one attempt recorded _for each submission_, which should be based on the final input when the user presses the submit exam button.

**Comment by indirectlylit** [comment]
nevermind, forget everything I just said. deleting.

**Comment by indirectlylit** [comment]
(so starting over after deleting my previous responses...)

Intuitively I agree with @khangmach that there should be no concept of "multiple attempts" on an exam. This sounds like formative assessment information, not a summative assessment info. That would be like if a teacher could see that I erased an answer a couple times before settling on a final choice.

However from a pedagogic perspective perhaps there is value, and "student privacy" isn't important here.

**Comment by indirectlylit** [comment]
behaves as intended

let's report any additional feedback in clearinghouse
