### ISSUE TITLE
Version parsing on old setuptools platforms is broken

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3145]
### Observed behavior

Builds do not run on Launchpad. This is consistent for any older Debian + Ubuntu 14.04. Example:

```
test@test-VirtualBox:~$ python 
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pkg_resources import parse_version
>>> parse_version("1.2.3")
('00000001', '00000002', '00000003', '*final')
>>> parse_version("1.2.3.dev0")
('00000001', '00000002', '00000003', '*@', '*final')
>>> parse_version("1.2.3a1")
('00000001', '00000002', '00000003', '*a', '00000001', '*final')
>>> parse_version("1.2.3a0")
('00000001', '00000002', '00000003', '*a', '*final')
>>> parse_version("1.2.3b1")
('00000001', '00000002', '00000003', '*b', '00000001', '*final')
>>> parse_version("1.2.3b1+git-123")
('00000001', '00000002', '00000003', '*b', '00000001', '*+', '*git', '*final-', '00000123', '*final')
>>> 
```

### Expected behavior

Currently, we have an `AttributeError: 'tuple' object has no attribute 'base_version'` in the build when running on an older platform.

It doesn't happen on Buildkite or Ubuntu 16.04.

### User-facing consequences

None at the moment, but we won't have an automated release on Launchpad with the current implementation.

### Errors and logs

https://launchpadlibrarian.net/355336713/buildlog_ubuntu-trusty-i386.kolibri-source_0.7.1~b1.dev0+git.10.gb0f4ff4-0ubuntu1_BUILDING.txt.gz

### Steps to reproduce

See above

### Context

See above

**Comment by benjaoming** [comment]
Sorry nope, new error from Ubuntu 14.04. I didn't have access to directly test it locally, so had to wait for 1h for Launchpad to barf.

```
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    import kolibri
  File "/<<BUILDDIR>>/kolibri-source-0.7.1~b1.dev0+git.12.g2a8fe31/kolibri/__init__.py", line 10, in <module>
    __version__ = str(get_version(VERSION))
  File "/usr/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/<<BUILDDIR>>/kolibri-source-0.7.1~b1.dev0+git.12.g2a8fe31/kolibri/utils/version.py", line 384, in get_version
    return get_prerelease_version(version)
  File "/<<BUILDDIR>>/kolibri-source-0.7.1~b1.dev0+git.12.g2a8fe31/kolibri/utils/version.py", line 355, in get_prerelease_version
    version_file_base
AssertionError: kolibri/VERSION file inconsistent with kolibri.__version__.
__version__ is: (0, 7, 1, 'alpha', 0), file says: 0.7.1b1.dev+git-12-g2a8fe31
```

I'm going to assume mainly that there is a test missing for the above error. So am gonna try a fix that's test-based, then run it on a VM, and then try it out on Launchpad.

**Comment by indirectlylit** [comment]
fix is in above, but still needs to be tested before closing

**Comment by benjaoming** [comment]
Tested and works!

Means that our builds succeed on Ubuntu 14.04 -- but also that Ubuntu 14.04 support currently doesn't have any issues.
