### ISSUE TITLE
kolibri user docs show source code in search results

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3148]
### Observed behavior

searching for 'import' gives these results:

![image](https://user-images.githubusercontent.com/2367265/35707755-e302ef3e-075f-11e8-8797-390c75ae1018.png)

### Expected behavior

searching for 'import' should give results on importing content

### User-facing consequences

hard to find helpful info in docs

### Steps to reproduce

try searching, e.g. [like this](http://kolibri.readthedocs.io/en/release-v0.7.x/search.html?q=import&check_keywords=yes&area=default)

-----

cc @radinamatic @benjaoming

**Comment by benjaoming** [comment]
Those are the API docs? What are they doing in the user docs? :)

**Comment by indirectlylit** [comment]
¯\_(ツ)_/¯

:)

**Comment by benjaoming** [comment]
Yay, this works now after migrating to `kolibri-docs` :)
