### ISSUE TITLE
Python 2-only syntax present in source dist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3152]
### Observed behavior

As the Ubuntu package will pre-compile Python byte code upon installation, it unfortunately fails:

```
Setting up kolibri (0.7.1~b1.dev0+git.13.gf1d43ed-0ubuntu1) ...
  File "/usr/lib/python3/dist-packages/kolibri/dist/ifcfg/cli.py", line 6
    print json.dumps(ifcfg.interfaces(), indent=2)
             ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/kolibri/dist/py2only/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/kolibri/dist/kolibri_exercise_perseus_plugin/static/mathjax/kathjax.py", line 32
    print "%s exists, exiting" % mjdir
                             ^
SyntaxError: Missing parentheses in call to 'print'

Traceback (last called is first):
     main() in /var/lib/dpkg/info/kolibri.postinst:327
The command py3compile -p kolibri -V 3.4- exited with exit code 1.
dpkg: error processing package kolibri (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'll patch this up in the debian package, a temporary measure. Meanwhile, here are the tracking issues:

 * [x] https://github.com/ftao/python-ifcfg/issues/21
 * [x] https://github.com/learningequality/iceqube/issues/31
 * [x] https://github.com/learningequality/kolibri-installer-debian/issues/12
 * [ ] Get rid of `kathjax.py` in the source dist from `kolibri-exercise-perseus-plugin` https://github.com/learningequality/kolibri/pull/3265
 * [ ] Add `python3 -m compileall -q kolibri/` to test matrix and fail build if it returns errors https://github.com/learningequality/kolibri/pull/3265
 * [x] Cherrypy wrong version installed in `kolibri/dist` -- see: https://github.com/learningequality/kolibri-installer-debian/issues/15

As for the `kathjax.py`, I think this is a build file that has entered the source wrongly. But because of all the horrible git submodules, it's really hard to figure out where the issue should be raised.

### Expected behavior

Debian package can work without patches

### User-facing consequences

Need more info

### Errors and logs

...

### Steps to reproduce

You can compile all Python code recursively using Python3 like so:

    python3 -m compileall -q kolibri/

### Context

All releases that depend on `ifcfg=>0.12`, `iceqube` or the Perseus plugin... so all releases :)

**Comment by benjaoming** [comment]
This is pretty bad:

Seems that building the source distribution with Python 2 was a mistake: I'm not getting cherrypy 13.0.1 installed, but some other version containing older well-known Python 2 syntax errors. It contains a file `_cpcompat_subprocess.py` which isn't part of the new releases. I don't know which version we have, because these devs aren't putting the version number in the codebase, instead relying on that the pkgutils can access the package version from some meta data in the site-packages... which can't be done for `kolibri/dist` (note to self: That's why we store version information in the codebase).

Our .whl [released here](https://github.com/learningequality/kolibri/releases/download/v0.7.1/kolibri-0.7.1-py2.py3-none-any.whl) has the error, as well as the one uploaded to PyPi.

**Comment by benjaoming** [comment]
So actually (which is something I forgot, silly me), we are using CherryPy 6.2.0 in 0.7.1, and this means that in order to build a Python 3 friendly version, we should build the source dist with Python 2. In order to circumvent this, I'm going to simply patch up the 0.7.1 debian installers because they are for Python 3, but I don't think we should be circulating separate Python 2 and Python 3 built source dists, with the additional confusion that this will bring.

I've updated the support matrix:

Here's proof of the simple difference between Python 2 and Python 3 CherryPy... remove these two files, and you get the exact same code tree.

```
diff -r kolibri/dist/cherrypy ../kolibri-installer-debian/build/kolibri-source-0.7.0/kolibri/dist/cherrypy
Only in ../kolibri-installer-debian/build/kolibri-source-0.7.0/kolibri/dist/cherrypy: _cpcompat_subprocess.py
Only in ../kolibri-installer-debian/build/kolibri-source-0.7.0/kolibri/dist/cherrypy/wsgiserver: ssl_pyopenssl.py
```

**Comment by indirectlylit** [comment]
> ### User-facing consequences
> Need more info

Hi @benjaoming - I'm trying to prioritize the outstanding 0.8 issues, and it's not clear to me what the implications of this are. It sounds to me like 0.8 is not affected because we're using we are using `cherrypy==13.0.1`

I'll remove the 0.8 milestone for now. let me know if 0.8 is actually affected

**Comment by benjaoming** [comment]
@indirectlylit 0.6+ is affected, the thing is that I plugged it with patches in the Debian sources using [Quit](https://wiki.debian.org/UsingQuilt). I'm trying to get it fixed, that's why there is a task list further up, it's meant to keep track of this progress and chunk it into smaller pieces. It's not an immediate blocker but a serious tech debt :)

**Comment by indirectlylit** [comment]
Sounds good - I added the 'tech update' label, which we tend to use for tech-debt.
