### ISSUE TITLE
Non-semantic use of error code 400

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3158]
### Observed behavior

A couple of places, API calls will return HTTP `400`

>  A 400 means that the request was malformed. In other words, the data stream sent by the client to the server didn't follow the rules. 

If the username already exists (see: https://github.com/learningequality/kolibri/pull/3125 ) then the HTTP status code 400 is used as the sole condition.

Another example:

https://github.com/learningequality/kolibri/blob/79c6a9046b153656c61c01b9375109d3ff395ae5/kolibri/plugins/user/assets/src/views/sign-up-page/index.vue#L192

I don't think it's that bad, but I don't think we should assume anything from the HTTP status code. Some people even argue that `200` is more correct for a form processing where data doesn't validate.. because frankly, there's no exception taking place in the server, and the client is using the API correctly.

Let's find and add a standard for form validation errors? cc: @mrpau-eugene @indirectlylit @rtibbles 

### Expected behavior

Backend errors should resolve through correct error codes that do not mis-guide developers.

### User-facing consequences

None

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by mrpau-eugene** [comment]
Could it be possible to use `409` error when a user already exists?

https://stackoverflow.com/questions/25541203/http-response-code-when-resource-creation-post-fails-due-to-existing-matching-re#25541368

>  after reading on Restfull Web Apis from amundsen, Ruby and Richardson
>
> Best would be to use the 409 status code that states that there is a conflict with a resource that exists on the server. Put the url of that "conflicted" resource in the Location Header of the response and add a message of the conflict in the body

From https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10
> The request could not be completed due to a conflict with the current state of the resource. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. The response body SHOULD include enough

**Comment by benjaoming** [comment]
@rtibbles what's your suggestion for form validation errors moving forward?

I guess we might have the 409 as a special case, but there will be other validation errors that will be unrelated to a 409. Anyways, if we *only* use non-200 status messages, it would be easy for the client side to check for this and read out the error through well-known JSON response data..

**Comment by benjaoming** [comment]
Input from @jamalex : Try matching the error handling patterns in django-rest-framework

**Comment by mrpau-eugene** [comment]
> Try matching the error handling patterns in django-rest-framework

@benjaoming sorry, but could you explain this further? I don't quite understand what you meant here

**Comment by benjaoming** [comment]
It's a task to figure out exactly what they are doing, but reading from the [DSF tutorial]:

> ## Status codes
> 
> Using numeric HTTP status codes in your views doesn't always make for obvious reading, and it's easy to not notice if you get an error code wrong. REST framework provides more explicit identifiers for each status code, such as HTTP_400_BAD_REQUEST in the status module. It's a good idea to use these throughout rather than using numeric identifiers.

**Comment by indirectlylit** [comment]
Let's make this a focus of the next milestone after 0.9. I think we should take a step back and do some design work on all this together.

**Comment by indirectlylit** [comment]
This should be addressed. @ralphiee22 mind linking your error-handling PR here?
