### ISSUE TITLE
<Critical> Exercises are not loading on tablets when upgrade from 0.4.9 to 0.7.0

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#3161]
### Observed behaviour:
We a Nalanda's server from 0.4.9 to 0.7.0, post the upgrade the questions does not load up on the client devices. 

Example channel and the path: (This is across all the channels)
8fc515793aad4e52b490b03c48ad21de
Path: Balbharthi --> 3 --> 1 Introduction to Geometrical Figures --> Warm Up (Introduction to Geometrical Figures) --> Challenge Set: Warm Up (Introduction to Geometrical Figures)

**On accessing as guest** 
On server(Laptop) the questions shows up properly:
![img_20180206_154006](https://user-images.githubusercontent.com/13453618/35853851-b839e124-0b54-11e8-9e6a-01cfd4890f7e.jpg)

On a mobile connected to the server as  client:
![screenshot_20180206-153945](https://user-images.githubusercontent.com/13453618/35855234-a0890cf4-0b58-11e8-81df-2765a0cb2da1.png)

On a tablet connected to the server as  client:
There is only one question that gets mastered too on its own:
![img_20180206_154836](https://user-images.githubusercontent.com/13453618/35854111-751372e2-0b55-11e8-93f2-173fdcb58cb6.jpg)
![img_20180206_154014](https://user-images.githubusercontent.com/13453618/35855253-aa76ab9a-0b58-11e8-8b69-9a76982cac00.jpg)

**Logged in as a user:**
The topic gets mastered:
![img_20180206_155335](https://user-images.githubusercontent.com/13453618/35854369-3123c112-0b56-11e8-84cb-e35b8c1a46e4.jpg)

On Coach report we get incorrect data too:
![img_20180206_155721](https://user-images.githubusercontent.com/13453618/35854537-9a60d3d6-0b56-11e8-8407-78cdf41a5b84.jpg)

### Expected behavior
The exercise should be loading up on the tablets and all the client devices alike.

### User-facing consequences
The learners are not able to access the exercise at all.

### Errors and logs
Relevant logs from:
 * ~/.kolibri/kolibri.log
[kolibri.log](https://github.com/learningequality/kolibri/files/1698657/kolibri.log)
 * the browser console - cannot be captured on a tablet browser hence not attaching.

### Steps to reproduce
1. Upgrade the Kolibri version from 0.4.9 to 0.7.0.
2. Assess the content on a tablet.

### Context
 * Kolibri version: Upgraded from 0.4.9 to 0.7.0, so using 0.7.0.
 * Operating system: Ubuntu 14.04 LTS
 * Browser: Chrome and Firefox

**Comment by benjaoming** [comment]
Hi @harishbalachandran ! :)

Did you use any intermediate versions for the upgrade or was it straight from 0.4.9 to 0.7.0 ?

@rtibbles @indirectlylit is there an assumption about the upgrade path being in steps of one minor version? (0.4=>0.5=>0.6=>0.7) ?

**Comment by rtibbles** [comment]
I don't think there is any special logic that would differentiate the stepped upgrade from the whole leap one.

**Comment by rtibbles** [comment]
No errors in the log file after the upgrade happens as far as I can see.

**Comment by harishbalachandran** [comment]
Hey @benjaoming! Hope all is well.

I upgraded from 0.4.9 to directly 0.7.0.

I am not sure if you folks will be to reproduce this at your end, let me know how can I help to get more info on this issue. 

Seams like a important issue to tackle considering all our 198 server across India needs upgraded to latest version very soon.

**Comment by harishbalachandran** [comment]
It is very similar to #3013, but this occurs without updating the content and just after a successful upgrade from 0.4.9 to 0.7.0.

**Comment by harishbalachandran** [comment]
Hi @rtibbles please find the database [here](https://drive.google.com/drive/folders/11Z1YlyA--MLsQe08fz-DqEvhM0Ee8oFQ)
The channels used predominantly are:
8fc515793aad4e52b490b03c48ad21de
797ff4dfe6fd473e91b68cfb8ec3a44e

Following is the specific path:
Path: Balbharthi --> 3 --> 1 Introduction to Geometrical Figures --> Warm Up (Introduction to Geometrical Figures) --> Challenge Set: Warm Up (Introduction to Geometrical Figures)

Let me know if you need anything else.
