### ISSUE TITLE
Fail tests if missing migrations are detected

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3162]
### Observed behavior

We manage to merge PRs that change models without the necessary migrations. This should be blocked.

### Expected behavior

n/a

### User-facing consequences

**Best case**: Big red error messages, but the user doesn't take notice

**Worst case**: User creates migrations that later conflict with our updates!

### Errors and logs

```
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
INFO     Running 'kolibri start' as daemon (system service)
INFO     Kolibri running on:

	http://127.0.0.1:8080/
	http://192.168.1.102:8080/
	http://192.168.1.100:8080/

INFO     Going to daemon mode, logging to /home/doc_mcgoo/.kolibri/server.log
```

### Steps to reproduce

I think we should try implementing a parser for `makemigrations --dry-run` that just fails the pre-build stages on Travis if there are migrations detected.

```
kolibri manage makemigrations --dry-run
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Migrations for 'morango':
  0011_auto_20180206_1325.py:
    - Change managers on certificate
Migrations for 'kolibriauth':
  0008_auto_20180206_1325.py:
    - Alter field preset on facilitydataset
```

### Context

n/a

**Comment by indirectlylit** [comment]
me gusta

**Comment by rtibbles** [comment]
Note that this would also prevent non-Python 2/3 compatible migrations getting committed which is the majority of cases where we see this error occurring.

**Comment by rtibbles** [comment]
Interestingly, when I run `makemigrations --dry-run` on current develop, it reports two missing migrations, however, when I do the real thing, it only creates one.
