### ISSUE TITLE
Some DRF Viewsets have  typos (permission_classes vs. permissions_classes)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3166]
Some DRF Viewsets have  typos (permission_classes vs. permissions_classes). `permission_classes` is the correct property.

I fixed them in learningequality/kolibri@lessons, but reverted them [here](https://github.com/learningequality/kolibri/commit/cd92624327fcfb7609e156e637e09d02b4fa9b7b#diff-41d66ec4282b3fcf4b75a5a13946cf69) because there might be unintended consequences.

See the commit above for the files that are affected.

**Comment by rtibbles** [comment]
Odd... in the docs it says `permission_classes`: http://www.django-rest-framework.org/api-guide/permissions/

**Comment by jonboiser** [comment]
Yeah, my original post got it backwards. `permission_classes` is the correct property. In the code, there is use of `permissions_classes` (wrong name).

**Comment by rtibbles** [comment]
Ah, yep that's a typo!
