### ISSUE TITLE
`make clean` requires docs deps

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#3177]
Trying to build Kolibri in a fresh docker env. I get this error when I use just the base requirements:

```
/app $ python --version
Python 2.7.14
/app $ make clean
rm -f kolibri/VERSION
rm -fr build/
rm -fr dist/
rm -fr dist-packages-cache/
rm -fr dist-packages-temp/
rm -fr *.egg-info
rm -fr .eggs
rm -fr .cache
rm -r kolibri/dist/* || true # remove everything
git checkout -- kolibri/dist # restore __init__.py
rm -r kolibri/utils/build_config/* || true # remove everything
git checkout -- kolibri/utils/build_config # restore __init__.py
rm -r requirements.txt || true # remove requirements.txt
git checkout -- requirements.txt # restore requirements.txt
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
rm -f docs-developer/py_modules/kolibri*rst
rm -f docs-developer/py_modules/modules.rst
make -C docs clean
make[1]: Entering directory '/app/docs'
Makefile:12: *** The 'sphinx-build' command was not found. Make sure you have Sphinx installed, then set the SPHINXBUILD environment variable to point to the full path of the 'sphinx-build' executable. Alternatively you can add the directory with the executable to your PATH. If you don't have Sphinx installed, grab it from http://sphinx-doc.org/.  Stop.
```

Seems weird that we need docs dependencies when we need to just clean the repo.

**Comment by benjaoming** [comment]
I agree, should have caught that when cleaning up the Makefile in #3113 -- will `make amends` :D

**Comment by benjaoming** [comment]
We've decided to move the user docs to a separate repo, and the developer docs don't need to be cleaned because they're not part of the dist.

**Comment by benjaoming** [comment]
@indirectlylit there's an autogenerated check for Sphinx at the top of `docs/Makefile` which always fires.

**Comment by benjaoming** [comment]
@aronasorman thanks for reporting this! `clean-docs` is no longer a sub-target of `make clean`. After migrating the user docs, we don't need to consider the developer docs as part of a build, so they are okay unclean, and one can just run `make docs-clean` if desired.
