### ISSUE TITLE
translation string warning

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3181]
### Observed behavior

During startup, Kolibri warns:

```
Kolibri: $trs id "Kolibri" should be in camelCase. Found in /Users/d/Projects/learning_equality/repos/k08x/kolibri/core/assets/src/views/side-nav/index.vue
```

### Expected behavior

All string IDs should follow standard conventions

### User-facing consequences

None

### Context

Current `develop` branch (0.8)

**Comment by rtibbles** [comment]
Fixed in #3209
