### ISSUE TITLE
channel permanently out-of-date

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3184]
### Observed behavior

On a fresh Kolibri installation with no channels, I went to load the Kolibri Portion Control channel (`fb51dae6df7545af8455aa3a0c32048d`) for testing.

Before doing anything, I was presented with a message that

> New channel version available. Some of your files may be outdated or deleted.

It shows the the version I "have" (even though I have nothing) is 15, and 16 is available:

![image](https://user-images.githubusercontent.com/2367265/36107795-0e9e11e6-0fd0-11e8-9695-9190319a0412.png)

Clicking 'update' causes the new DB to be downloaded, but then the same message re-appears.

### Expected behavior

* When a user looks at a channel that they have not downloaded any content from, it should _always_ have the most recent information.
* The update button should work as expected

### User-facing consequences

Confusion and (possibly) not getting the latest channel data?

### Errors and logs

```
INFO:kolibri.content.management.commands.importchannel:Downloading data for channel id fb51dae6df7545af8455aa3a0c32048d
DEBUG    URL to fetch: http://studio.learningequality.org/content/databases/fb51dae6df7545af8455aa3a0c32048d.sqlite3
DEBUG:kolibri.content.management.commands.importchannel:URL to fetch: http://studio.learningequality.org/content/databases/fb51dae6df7545af8455aa3a0c32048d.sqlite3
DEBUG    Destination: /Users/d/kolibri/08x/content/databases/fb51dae6df7545af8455aa3a0c32048d.sqlite3
DEBUG:kolibri.content.management.commands.importchannel:Destination: /Users/d/kolibri/08x/content/databases/fb51dae6df7545af8455aa3a0c32048d.sqlite3
  0%|                                                   | 0/421888 [00:00<?, ?it/s]INFO     "GET /api/tasks/?1518453542730=1518453542730 HTTP/1.1" 200 207
INFO:django.server:"GET /api/tasks/?1518453542730=1518453542730 HTTP/1.1" 200 207
100%|█████████████████████████████████| 421888/421888 [00:00<00:00, 1857072.64it/s]INFO     Channel fb51dae6df7545af8455aa3a0c32048d already exists in database, cleaning up ContentNodes
INFO:kolibri.content.utils.channel_import:Channel fb51dae6df7545af8455aa3a0c32048d already exists in database, cleaning up ContentNodes
```

### Steps to reproduce

 * create fresh kolibri installation
 * go to import `fb51dae6df7545af8455aa3a0c32048d`

### Context

Latest Kolibri Develop (0.8)

**Comment by ivanistheone** [comment]
@indirectlylit When you say "fresh installtion" do you mean "really fresh" (as in kolibrihome was an empty dir)?

I'm guessing what's going on is you have the sqlite file in you `.kolibrihome/storage/databases/` and this is why you're promoted to update.

**Comment by indirectlylit** [comment]
> When you say "fresh installtion" do you mean "really fresh" (as in kolibrihome was an empty dir)?

Yes

**Comment by jonboiser** [comment]
@ivanistheone @jayoshih Could you republish Portion Control? I believe this behavior might be due to an older issue where the Channel on version on the sqlite3 file was permanently 1 version behind what you get when hitting /api/public/channels on Studio.

**Comment by indirectlylit** [comment]
closing - we can re-open if anyone sees this again
