### ISSUE TITLE
Creating Exam/Changing Exam assignments leads to an error

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3189]
### Observed behavior

After fixing the `permissions_classes` typo in #3169, one gets an error when trying to create or modify Visibility/assignments for an Exam.

Ran into this error using `KolibriAuthPermissions` class with a nested serializer, which is what `ExamAssignmentSerializer` is. This seems to be due to how the the KolibriUser `user_can_create/update` etc. methods tries to validate data (assumes non-nested data).
…

### Expected behavior

User can create and update Exam assignments.

### Steps to reproduce

1. Try to create an Exam, get error
1. If you already have an Exam, try to change its visibility, get an error.

**Comment by rtibbles** [comment]
This may well be related to #3186

**Comment by rtibbles** [comment]
Going to add some more tests to catch this behaviour, and try to fix.
