### ISSUE TITLE
Make Error Page Reactive to Online Status

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#3200]
### Observed behavior
Following various bugs or unknown errors, there is an appearance of a red box with json error. This format of displaying the error isn't particularly useful or informative to the user, and offers no information, it just breaks the current page the user is on. 

### Expected behavior
Some kind of friendly and informative way of conveying that an unexplainable error has occurred in Kolibri. 

### User-facing consequences
More informative and actionable error handling for unknown errors occurring in Kolibri. The more clarity we have in the design, the less put off users will be. We will also provide users with various options to report their error. 

**Design resources:**
[Spec and flow sheet](https://drive.google.com/open?id=1Dqx95ScIuVbcHWkVBzpr-jY8_bEs3UsTCDqZ3DiF3E4)
[Design of error display](https://drive.google.com/open?id=196xyQWHzGC2TbFXlNurRGvaYd8mOYhhm)
[Design of error report modal](https://drive.google.com/open?id=17HimanhkRkiGiiusLY0l4iOEUbfeI5jc)

[drive folder containing all of the above](https://drive.google.com/open?id=1Nk5B6MAYDND6rRYgCwOuZue5RSgf-emw)

**Comment by DXCanas** [comment]
Where's the asset shown in the mock located?

**Comment by indirectlylit** [comment]
These were low-fidelity mockups, so

1. Just use a placeholder image
2. Don't try to match the exact layout/spacing. In particular, stick default font sizes and spacing as much as possible.

**Comment by khangmach** [comment]
@DXCanas Updated the drive folder with image asset: https://drive.google.com/drive/folders/1Nk5B6MAYDND6rRYgCwOuZue5RSgf-emw

**Comment by DXCanas** [comment]
Do you all think it would be a good idea to consolidate this new error page and `auth-message`, making `auth-message` a specific kind of error?

I'm seeing a few instances where `auth-error` is used, not for an authentication error, but as a template for an expected error (like empty state).

**Comment by DXCanas** [comment]
@indirectlylit @khangmach 

> Don't try to match the exact layout/spacing. In particular, stick default font sizes and spacing as much as possible.

Running into an awkward styling issue on the external link to community forums:
![modal screencap](https://user-images.githubusercontent.com/9877852/43233853-467c1fee-902d-11e8-8422-585cbf746805.png)

**Comment by khangmach** [comment]
Dangit. I was working off the assumption Christian's modal refactor would be in. Umm can we wrap the link? Another alternative would be to change the link to something like www.learningequality.org/r/forum (i think Jamie did this for release blogs...)

**Comment by christianmemije** [comment]
`word-wrap: break-word;`  should do the trick @DXCanas

**Comment by DXCanas** [comment]
@khangmach, if I wrap (the way @christianmemije noted), the link will _always_ wrap since the modal is set to `medium`. That alright?

That link doesn't look live, but I'm assuming we could set up a redirect if that's something we're interested in.

**Comment by DXCanas** [comment]
Also, do we care what the `.txt` file is named? Currently it's using a random hash generated for uniqueness. On download, the can rename the file whatever they like.

**Comment by christianmemije** [comment]
Maybe `kolibri_error_${time}.txt`?

**Comment by khangmach** [comment]
@DXCanas that sounds good. I'm not too concerned about the text always wrapping at this point :)
>kolibri_error_${time}.txt

lgtm

**Comment by indirectlylit** [comment]
this should also be a `size="large"` modal I assume

**Comment by DXCanas** [comment]
@khangmach you think it's worthwhile to have a "copied!" confirmation when using the "copy to clipboard" button? Snackbar?

**Comment by DXCanas** [comment]
> this should also be a size="large" modal I assume

@indirectlylit large is very large, as it also doesn't have the max-width that `core-base` does

**Comment by indirectlylit** [comment]
> @indirectlylit large is very large, as it also doesn't have the max-width that core-base does

 maybe fix that and give it a max width?

**Comment by khangmach** [comment]
> you think it's worthwhile to have a "copied!" confirmation when using the "copy to clipboard" button? Snackbar?

Yup I included that as well in the string doc

**Comment by DXCanas** [comment]
@indirectlylit @khangmach 
![screencap](https://user-images.githubusercontent.com/9877852/43351082-c6107b0c-91c1-11e8-9af3-e90fa2b79c8f.png)

Do we want to use the kolibri image in the mocks, or the regular kolibri logo? Worried that the asset uploaded will be too low res unless we can vectorize it?

**Comment by DXCanas** [comment]
Also @indirectlylit checking if someone's "online" is a little more nuanced than expected. I could skip that part for now?

Otherwise, what do you think is a good amount of time to wait for a response to a web server? And what should I do while I wait that time out? Set `loading` to true?

**Comment by khangmach** [comment]
>Worried that the asset uploaded will be too low res unless we can vectorize it? 

I intentionally made the asset low res/pixelated haha! To kinda play on like, the broken aspect...lol

**Comment by indirectlylit** [comment]
> checking if someone's "online" is a little more nuanced than expected

I don't think you should be checking in real-time whether connectivity is enabled. We have a ping command that runs every 15 minutes or so. Recommend using the success/failure of the most recent ping as the indicator for connectivity. This value could be passed as an attribute (e.g. `internet_available`) in the new standard error response template that @ralphiee22 and @christianmemije put together.

That said, I agree that perhaps this is too much effort for a marginal UX benefit. @khangmach maybe we should drop this feature and just have a single message?

**Comment by khangmach** [comment]
@indirectlylit I'm cool with that. @DXCanas let's use one message for now (the one with internet connectivity detected). I've appended a [final] to the google drive file to indicate which one we're using.

**Comment by DXCanas** [comment]
@indirectlylit 

> Recommend using the success/failure of the most recent ping as the indicator for connectivity.

I thought our pings only checked for connectivity to the Kolibri server, not the actual web? What are we pinging?

**Comment by indirectlylit** [comment]
> I thought our pings only checked for connectivity to the Kolibri server, not the actual web? What are we pinging?

You're referring to the client heartbeat. I'm referring to the Kolibri server telemetry. See:

* https://github.com/learningequality/kolibri/blob/develop/kolibri/core/analytics/management/commands/ping.py
* https://github.com/learningequality/nutritionfacts

**Comment by indirectlylit** [comment]
this is complete, and we've decided to punt on making reactive to the 'online status'
