### ISSUE TITLE
content import: upgrade and 'unsupported' notifications

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3222]
In #3213 we disabled importing of unsupported content.

There are situations where this is not desirable, and in fact we want to allow importing supported content with the expectation that the user will upgrade Kolibri.

Let's build an MVP version of upgrade handling. This would probably at a minimum support:

* alerting superusers when an upgrade is available (assuming that we can connect to the central server)
* alerting users when they are importing a channel that has unsupported content, and suggesting an upgrade

**Comment by khangmach** [comment]
Just a quick fix:
>There are situations where this is not desirable, and in fact we want to allow importing **un**supported content with the expectation that the user will upgrade Kolibri.

**Comment by khangmach** [comment]
@indirectlylit are you expecting a design of an in-app upgrade mechanism as well? Or is this just for a notification concept? 

Also
>when an upgrade is available

a channel upgrade or for a new Kolibri version?

**Comment by indirectlylit** [comment]
This issue was specifically about channel importing, but there is a lot of overlap with ongoing work in #4571 and [this spec](https://docs.google.com/document/d/1h5hyHttxTrZpQq7j0sPCBLNlcV7PcaJ5CrtlJvVZBdM/edit).

The original intent of #4571 focused on Kolibri app upgrade notifications, but the feature is also capable of (for example) alerting users that their current version of Khan Academy has issues that have been resolved in the latest version.

Since there is so much overlap, I'll close this issue. If you have any feedback feel free to leave it in the other one.

> design of an in-app upgrade mechanism as well

at this point, that's out of scope
