### ISSUE TITLE
Content import should support "retry"

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#3226]
### Observed behavior

When downloading content on an unreliable connection (i.e. most of our user base, and me last week) it fails frequently (generally due to timeouts). Starting it up again means closing the error message, and doing a minimum of 5 clicks or so (and pageloads) to start it up again. It's even worse when you selected a granular set of items to import, because selecting them all over again is a huge pain, especially when you might be on a connection that's only loading a couple of items every 5 mins before timing out again.

### Expected behavior

When it fails, it should at the very least give you two options: Retry, and Cancel. "Cancel" is what we have now. "Retry" should restart the same import process from scratch (with the same items selected), as it will skip anything that it already has. Even better would be to have it auto-trigger the "Retry" button after a few minutes (could be initiated client-side, as long as the browser is still open) to increase chances of downloading desired content while unattended.

### User-facing consequences

On flaky connections, loading content becomes a huge headache that consumes one's entire existence (checking constantly, clicking constantly). Costs may be increased, as overnight bandwidth is often cheaper.

### Context

Kolibri 0.7.1 on Windows in Kakuma, Kenya.

**Comment by jamalex** [comment]
(We previously heard this same experience from Fabrice and others)

**Comment by indirectlylit** [comment]
let's try and tackle #3510 instead for 0.10.0

**Comment by indirectlylit** [comment]
Let's review and either implement or close as 'wontfix' in 0.13.0

started thread here: https://learningequality.slack.com/archives/C0LFYF7SA/p1564529555025700

**Comment by indirectlylit** [comment]
Have not heard of any outstanding need for this functionality. Please re-open if that's not the case
