### ISSUE TITLE
Research DB corruption + new dbrecover command

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3228]
### Observed behavior

Perhaps because of older SQLite pragma settings (which are non-reversible btw), we are running into a lot of database corruptions ATM. Other probably causes are unclean shutdowns or migrations, or concurrent access (Iceqube?).

One aspect of this issue is to research why, the other is to find a remedy that's better than to leave the user with an application crash and a traceback.

1. [x] Research if possible to create a command `dbrecover` that essentially does `dbbackup` and `dbrestore --latest`
1. [x] Catch exception at appropriate place and show suggestion to ~use `dbrecover`~ (or `sqlite3 <path> ".dump" | sqlite3 <path>`)
1. [ ] Find out why we have these somewhat frequent errors.

### Expected behavior

Yes, the database can be crashed / malformed. We can never entirely rule that out.

### User-facing consequences

A user may decide to delete their entire database to get Kolibri running. Or might have to spend time on the internet. Or doesn't have internet, so will never solve the problem. It's pretty bad.

### Errors and logs

```
File “/usr/local/lib/python3.5/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py”, line 323, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: database disk image is malformed
```

### Steps to reproduce

@radinamatic has tried it while running out of disk space, I have tried it during an upgrade from 0.7.1 to 0.7.2

Let's post some broken databases.

### Context

Well, any OS and possibly any version of Kolibri.

**Comment by rtibbles** [comment]
Icequebe uses a separate database, so the machinery itself should not be an issue. But, if there is write access to the DB while content import/annotation is going on, I can imagine that potentially causing an issue.

Possible candidates:
* the Session table (which will get written to by the heartbeat code while the user has the management page open).
* the UserSessionLog (which will get written by the heartbeat code also, when the user has been active).
* Any learner data being written to the database while this is happening.

**Comment by aronasorman** [comment]
I do see corruption as a risk item for WAL files -- basically, there's a slight sliver of chance during one of the checkpoints, that corruption might happen if there's a power loss or disk failure.

Here's a nice list of possible ways to corrupt SQLite3 files: https://www.sqlite.org/howtocorrupt.html#_corruption_following_switches_between_rollback_and_wal_modes

We can refer to this once someone actively starts investigating this.

**Comment by rtibbles** [comment]
8.2 and 8.6 seem like reasonably likely candidates. Another concern I have is that for some reason the underlying `pysqlite` is not sharing connections properly between Django and SQLAlchemy, and therefore we might be getting cross-process collision issues.

**Comment by benjaoming** [comment]
Thanks @aronasorman for the point -- however, Ubuntu 16.04 is on SQLite 3.11.0, this was how I produced corrupt db files locally and on @radinamatic 's server.

@radinamatic the corrupted database from the above server, is it okay if I share it? Does it contain anything sensitive, like a login?

**Comment by benjaoming** [comment]
Trying to implement a `dbrecover` command. Unfortunately, a call to the Python-implemented `sqlite3.dump` module, just generates the same error:

```
kolibri manage dbrecover
Traceback (most recent call last):
  File "/home/benjamin/.virtualenvs/kolibri3/bin/kolibri", line 9, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/media/archive/code/kolibri/kolibri/utils/cli.py", line 592, in main
    initialize(debug=debug)
  File "/media/archive/code/kolibri/kolibri/utils/cli.py", line 151, in initialize
    backup = dbbackup(version)
  File "/media/archive/code/kolibri/kolibri/core/deviceadmin/utils.py", line 120, in dbbackup
    for line in db.connections['default'].connection.iterdump():
  File "/usr/lib/python3.5/sqlite3/dump.py", line 30, in _iterdump
    schema_res = cu.execute(q)
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by rtibbles** [comment]
Does directly invoking sqlite dump produce an error?

**Comment by benjaoming** [comment]
It seems that there is no way to invoke the `sqlite3 <dbfile> ".dump"` mechanism from Python. I can only suggest one method for this to work with minimal user effort: To invoke the external `sqlite3` command and in case it doesn't exist, show some user guidance.

Will implement this, and then move on to figuring out how to corrupt the database..

**Comment by benjaoming** [comment]
Okay I finally implemented it and when I tested it with a corrupt database, I found that we are hitting the database unconditionally when calling management commands.

This makes it possible to create backups and recover stuff... unless the database is malformed, in which case we will not ever reach the management command... so I cannot even make one that just outputs a nice command for the user to use.

Instead, I will suggest that we make this a documentation issue for 0.8.

**Comment by indirectlylit** [comment]
see also #3437

**Comment by benjaoming** [comment]
@indirectlylit In case support questions appear from users, lets add a "known issues" chapter in the docs? Something where the work-around for a "malformed" database can appear?

Apart from that, I suggest closing this now. I will definitely recall this issue if I see a post about malformed dbs, it's a trauma :)

**Comment by indirectlylit** [comment]
okay, created an issue for that: https://github.com/learningequality/kolibri-docs/issues/29
