### ISSUE TITLE
enrollment modal doesn't respond to 'enter'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3234]
### Observed behavior

when enrolling users, the modal doesn't respond to 'enter'. you need tab down to the button:

![image](https://user-images.githubusercontent.com/2367265/36570477-1271f822-17e7-11e8-8d70-066381381da5.png)

### Expected behavior

default modal action triggered with 'enter'

### User-facing consequences

slightly slower for keyboard users

### Context

K07

**Comment by karlaeavila** [comment]
Is there an example of this in another other part of the code?

**Comment by indirectlylit** [comment]
yes, you can search for other instances of `core-modal`

**Comment by indirectlylit** [comment]
here's a representative example: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/groups-page/create-group-modal.vue

**Comment by karlaeavila** [comment]
Thanks!
