### ISSUE TITLE
The questions attempted is more than the total number of questions in an exam.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#3244]
### Observed behaviour
The actual exam created has 30 questions, but when learners attempt them we are getting 38 questions answered out of 30 questions

![whatsapp image 2018-02-23 at 9 31 54 am](https://user-images.githubusercontent.com/13453618/36582235-a8d00f8e-1896-11e8-894e-9b2a0d60e6a7.jpeg)
![whatsapp image 2018-02-23 at 9 32 09 am](https://user-images.githubusercontent.com/13453618/36582237-a9cfc3de-1896-11e8-8029-d6dae1b6d772.jpeg)
 
### Expected behaviour
The attempts should be the exact number of questions answered by the learner.

### User-facing consequences
The learners and the teachers are confused and shows incorrect data, which losses the purpose of conducting exam on Kolibri.

### Steps to reproduce
1. Create an exam.
2. Attempt as a learner.
3. Watch the attempted count to total questions count.
##Note:
This might not be easily reproducible while testing in a local server, but appears on the a classroom setting, 50-70% of the kids in a class of 38 face this issue and not all.

### Context
 * Kolibri version = 0.4.9
 * Operating system = Ubuntu 14.4 LTS
 * Browser Chrome.

**Comment by mrpau-richard** [comment]
I have this steps to reproduced this issue.
* Create and activate two or more exams in one class.
* Log in as learner.
* Start answering the first exam.
* After answering it, don't submit it just click `Back to exam list`
* Start answering the second exam and then you can reproduce this issue.
![screen shot 2018-03-09 at 4 34 59 pm](https://user-images.githubusercontent.com/8663934/37198510-81a4223c-23b9-11e8-8fc3-68934e465a2b.png)

I'm currently working on a patch for this.

**Comment by swapnil106111** [comment]
@indirectlylit Tested on kolibri 0.9.0. It is showing attempted questions correctly.

![3244_1](https://user-images.githubusercontent.com/12776071/38194204-b56c6c0e-3693-11e8-8301-f7072c1a23e6.png)

![3244_2](https://user-images.githubusercontent.com/12776071/38194205-b59f5ef2-3693-11e8-97e6-979635464ad6.png)
