### ISSUE TITLE
remove buttonAndLinkStyles from core API

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3249]
### Observed behavior

New core API module added here: https://github.com/learningequality/kolibri/pull/3223/files

This was done to support work on an external plugin to keep the code DRY

### Expected behavior

Let's copy/paste the code into the plugin rather than updating the core API spec. API maintainability and simplicity trumps DRY benefits in this case.

----

cc @christianmemije

**Comment by jonboiser** [comment]
`buttons.scss` isn't exported in api-spec.js anymore, but is imported as a SASS import by components inside the 'core' folder.
