### ISSUE TITLE
add-group button is not clickable and layout is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3268]
### Observed behavior

On the groups page, the layout is broken and the 'new group' button only seems to have a sliver which remains clickable:

![image](https://user-images.githubusercontent.com/2367265/36705502-5d0331e0-1b1a-11e8-915c-431ad8e6f2b4.png)

Looks like maybe some weird float behavior?

### Expected behavior

Button should be clickable. Let's remove floats if that's what we're using.

### User-facing consequences

Cannot create a group

### Context

0.8

**Comment by jonboiser** [comment]
Fixed in 272a44bb58f2ced9bdc7c318fc04417b77c595a5 by making the "you do not have any groups" text a span (inline) rather than paragraph (block).
