### ISSUE TITLE
Import Users and Classes - Question

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3270]
### Question:
 I've extensively checked around but I cannot find how to import users and classes from a text file.

Assuming there is no user friendly tool,  what database inserts and database operations are required to import class and user records? (Mariadb).

**Comment by indirectlylit** [comment]
Hi - you're correct that there's currently no user-facing mechanism for importing data. Longer-term, we do have plans to specify a stable public API that can be used to integrate external tools.

**Note that we cannot provide guarantees about the coherence of data if the user interface is bypassed:  there may be implicit constraints enforced by the UI but not encoded in the DB schema. We also make no guarantees about stability of internal APIs, DB schemas, etc.**

With that said, if you're interested in experimenting with this further, these two links might be helpful:

* [Documentation about the user DB models](http://kolibri-dev.readthedocs.io/en/develop/architecture/uap/index.html)
* [Example of a command that populates the DB with data](https://github.com/learningequality/kolibri/blob/develop/kolibri/logger/management/commands/generateuserdata.py)

good luck!

**Comment by nobicycle** [comment]
Much obliged. I think I'll wait. :-) Too much learning (for me) required before making a start, and as you say, the API will probably change.  Now on the other hand if there were some database procedures insert_class, insert_user; that would be different. :-)

**Comment by rtibbles** [comment]
There have been other requests to allow this, so we may see a command line management command to import from CSV at least. I will link to this issue when I have opened that one.
