### ISSUE TITLE
Removing a Learner from a Classroom does not remove them from Learner Groups

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3271]
Observed behavior

Removing a Learner from a Classroom does not remove them from Learner Groups

e.g. 

1. Enroll a Learner in Classroom C and Learner Group LG (inside of C)
1. Remove Learner from Classroom C
1. Learner still has Membership in Learner Group LG

This messes up the logic of the Learn page navbar because the Learner will technically still have 1 membership (in LG), and the "Classes" (formerly "Exams") tab will still show.

### Expected behavior

Learner loses membership in LG if they lose membership in C.

### User-facing consequences

"Classes"/Exam tab shows when it shouldn't. Maybe other undesired side-effects.

**Comment by jonboiser** [comment]
Also, the Membership API filters (?collection, ?user, etc.) don't work. Fixed them locally by adding more fields to the MembershipFilter:

```
class MembershipFilter(FilterSet):
    user_ids = CharFilter(method="filter_user_ids")

    def filter_user_ids(self, queryset, name, value):
        return queryset.filter(user_id__in=value.split(','))

    class Meta:
        model = Membership
        fields = ('user', 'collection', 'user_ids',)

```

**Comment by jonboiser** [comment]
The above comment is problematic because the logic for deleting a classroom membership relies on these filters. When I tested this, removing a single learner from a classroom wipes out all memberships everywhere.

**Comment by ralphiee22** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/3291
