### ISSUE TITLE
Logs have errors in server.log on Windows

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#3275]
### Observed behavior

In Windows, some of the logs are errors in `server.log`. 
The error is `ValueError: I/O operation on closed file`

### Expected behavior

The logs should be correct

### User-facing consequences

Users may not know what is going on in the app when they look at `server.log`

### Errors and logs

![virtualbox_windows_28_02_2018_10_03_24](https://user-images.githubusercontent.com/19424916/36804317-1649351e-1c6f-11e8-813b-4d9803096ce5.png)

### Steps to reproduce

1. Install kolibri 0.8 on a Windows machine
2. Start kolibri
3. Go to `server.log`

### Context

Kolibri version: 0.8.0-beta1
Operating system: Windows 10
Browser: Chrome

**Comment by benjaoming** [comment]
We know this issue from KA Lite! And it was fixed! :)

https://github.com/learningequality/ka-lite/issues/5057

**Comment by lyw07** [comment]
Should be fixed by #3430
