### ISSUE TITLE
'view more' and 'view less' needs padding

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3280]
### Observed behavior

There should also be a space between the link and the description text:

![image](https://user-images.githubusercontent.com/2367265/36873402-3f122bc4-1d5d-11e8-835c-fc1d51e836b3.png)

### Expected behavior

View more/less show up as expected, and have padding between it and the description text

### User-facing consequences

slight confusion

### Context

0.8

------

cc @DXCanas @jonboiser

**Comment by jonboiser** [comment]
The label mix up is Fixed in 0f5276a74224a2a79ca38572c6139d62e4c08781. We could add the padding, or maybe place it below the paragraph @DXCanas?

**Comment by indirectlylit** [comment]
updating title and clearing milestone

**Comment by jonboiser** [comment]
With the text-truncator component, the placement of view more/less is different and consistently one line below the description.

![screen shot 2018-04-26 at 11 52 16 am](https://user-images.githubusercontent.com/10248067/39325920-51ce885e-4948-11e8-84d5-d9b255ec6df8.png)

**Comment by indirectlylit** [comment]
great
