### ISSUE TITLE
in sortable lessons table, clicking column header doesn't change sort order

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3282]
### Observed behavior

1. Clicking an unsorted column causes the column to become sorted, but doesn't flip the sort order when clicked again
2. Clicking the arrow does flip the sort order, but has weird, inconsistent styling

![image](https://user-images.githubusercontent.com/2367265/36873991-24d33f4e-1d5f-11e8-9ee6-3f8e48b48461.png)

### Expected behavior

headers should look and behave and look the same as those in topic reports

### User-facing consequences

might not realize sort order can be reversed

### Context

0.8

-------

cc @DXCanas @jonboiser

**Comment by jonboiser** [comment]
@DXCanas Could we make the column sorting behavior for Lessons Reports more similar to other tables in the app?

**Comment by indirectlylit** [comment]
FYI - I think it would be reasonable to leave this update out of 0.8 and come back to it in a future release. At this point we should only be making critical changes to 0.8

**Comment by DXCanas** [comment]
Clearing milestone, will come back to it

**Comment by rtibbles** [comment]
Is this issue still extant?

**Comment by indirectlylit** [comment]
all sorting is disabled in the current version of the coach reports. I was planning on adding that in a feature release

we have a couple more related open issues so it's okay to close this

* https://github.com/learningequality/kolibri/issues/4621
* https://github.com/learningequality/kolibri/issues/4620
