### ISSUE TITLE
updates to coach top-nav

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3283]
### Observed behavior

Current tabs:

 * Topics (default)
 * Recent
 * Learners
 * Groups
 * Exams
 * Lessons

### Expected behavior

 * Learners (default)
 * Groups
 * Lessons
 * Exams
 * Recent
 * Channels

### User-facing consequences

Default page is slow, mis-named, and not the most important tab

### Context

0.8

-----

@khangmach - does the update recommended above seem right to you?

**Comment by khangmach** [comment]
LGTM

**Comment by indirectlylit** [comment]
see also #3284
