### ISSUE TITLE
updates to learn sub-nav

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3284]
### Observed behavior

Current nav:

* Recommended (default)
* Channels
* Classes (visible if enrolled)

### New behavior

* Classes (visible and default if enrolled)
* Channels (default if not enrolled)
* Recommended

### User-facing consequences

Most salient and helpful tabs should be most prominent

### Context

0.8

**Comment by indirectlylit** [comment]
see also #3283

**Comment by khangmach** [comment]
Looks good
