### ISSUE TITLE
Can’t install Kolibri 0.7.2 in Windows 10

### ISSUE THREAD

**Issue by alenguav** [learningequality/kolibri#3287]
I am trying to install Kolibri 0.7.2 from the file downloaded from this URL 

> https://learningequality.org/r/kolibri-windows-setup-latest

but I am getting this error message:

> ![image](https://user-images.githubusercontent.com/2367265/36929131-c54fbf32-1e41-11e8-916b-7be5bc880a57.png)

In other words it is suggesting me to use a different version of the software

**Comment by indirectlylit** [comment]
cc @radinamatic, @mrpau-richard - any ideas what might be happening here?

**Comment by alenguav** [comment]
It seems that the installer file was incomplete.
Downloading the file again fixed the issue.

**Comment by indirectlylit** [comment]
great, glad to hear
