### ISSUE TITLE
In the Coach -> Learners view, when you have selected a learner, it does not show you which learner you are viewing data for

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3307]
### Observed behavior
When clicking on a learner's name in the Coach -> Learners view, you can no longer see which learner you just selected.

![image](https://user-images.githubusercontent.com/1680573/37046146-75ad19e2-211c-11e8-8774-ff3301de6f3d.png)

### Expected behavior
We should see some indication of which learner's data we are currently looking at.

### User-facing consequences
Coach faces greater cognitive load by having to remember which learner they clicked on way back when.

### Steps to reproduce
* Have some learner data
* Go to Coach
* Click on 'Learners'
* Click on a Learner
* See a list of channels, but no learner name

**Comment by indirectlylit** [comment]
In believe there'd been discussion of deprecating the header-based breadcrumb switcher, and migrating to a header layout that's more consistent with the Learn views.

e.g. from

> # All classes > [ Class... v ]
> 
> TOPICS | RECENT | EXAMS | **LEARNERS** | GROUPS 
> 
> Title
> 
> ...

to something more like


> # All classes > [ Class... v ]
> 
> TOPICS | RECENT | EXAMS | **LEARNERS** | GROUPS 
> 
> Title
> 
> ...

**Comment by indirectlylit** [comment]
(not sure exactly what it would look like, but that was what @khangmach and I had briefly discussed)

**Comment by rtibbles** [comment]
Is there an open issue where this resolution can be tracked, if not, given that this is still extant, I would rather not close it!

**Comment by indirectlylit** [comment]
whoops, I didn't mean to close it

**Comment by rtibbles** [comment]
After offline discussion with @khangmach - decided on a short term fix for this for 0.8.0, where we add the name to the breadcrumb. The breadcrumb will be removed in future designs, so this is an interim fix only.

**Comment by indirectlylit** [comment]
state & api that supported this functionality was removed in #3065

**Comment by khangmach** [comment]
@DXCanas let's remove the second learner name header found in the learner's tab. Now that we have breadcrumbs indicating which learner you selected, this dup header isn't needed. It would be good to follow the same page structure as the new channels tab in coach.

Current issue:
<img width="825" alt="screen shot 2018-03-22 at 2 38 28 pm" src="https://user-images.githubusercontent.com/25045166/37799797-0a7b3176-2dde-11e8-8828-1d05112eedf7.png">
