### ISSUE TITLE
can't run Kolibri 0.8 on Ubuntu 16.04 with Python 3

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#3308]
### Observed behavior

When installing 0.8 kolibri whl file on Ubuntu 16.04 with Python 3, users can't run kolibri because it will exit with an error.

### Expected behavior

Users can run kolibri successfully

### User-facing consequences

If users install kolibri on Ubuntu using debian installers (from PPA or .deb) or through whl file with Python 3, they will not able to run Kolibri.

### Errors and logs

![virtualbox_ubuntu_06_03_2018_09_09_50](https://user-images.githubusercontent.com/19424916/37053469-1a52a4bc-2131-11e8-8926-ac00889139e3.png)

### Steps to reproduce

1. Download kolibri 0.8.0-beta1 whl file on Ubuntu 16.04
2. run pip3 install kolibri-0.8.0-beta1.whl
3. run kolibri start

### Context

Kolibri version: 0.8.0-beta1
Operating system: Ubuntu 16.04

**Comment by lyw07** [comment]
This error is introduced because we removed linux 64-bit cryptography on release-0.7, but we installs `pyopenssl` on release-0.8. Since the compatible version of cryptography isn't bundled inside kolibri anymore, the program is using the system cryptography, which is not compatible with the relatively newer version of `pyopenssl` we bundle inside kolibri.

**Comment by lyw07** [comment]
We bundle `pyopenssl` inside kolibri because we want to fix [the issue on Trusty](https://github.com/learningequality/kolibri/issues/2544). Since we still bundle cryptography for 32-bit Trusty, I'm thinking about a fix that we will dynamically add the path of OpenSSL to PYTHONPATH when we have cryptography bundled. That is to say, we will only be able to import OpenSSL on 32-bit operating systems, since now we only bundle cryptography inside kolibri for 32-bit systems. Here is the code: https://github.com/learningequality/kolibri/compare/release-v0.8.x...lyw07:test_crypto @benjaoming Do you think this fix sound plausible? I tested on different platforms, and it seems to be able to resolve both this issue and #2544

**Comment by benjaoming** [comment]
Hi @lyw07 

Nice find. I would like to spend some time figuring out how come I'm on 64 bit 16.04 with `python3-cryptography` and I've never had the problem :)

From the issue description:

> When installing 0.8 kolibri whl file on Ubuntu 16.04 with Python 3, users can't run kolibri because it will exit with an error.

This does only happens when `python3-cryptography` is installed?

I'm wondering if we can fix the latest version of `pyopenssl` to become compatible with the older version of `cryptography`? In Ubuntu 16.04, it's `1.2.3`... we could bundle our own patched version and contribute the changes upstream....

Btw: This is another issue that's connected to the need for `usedevelop=false`. I opened #3310 for this purpose now.

**Comment by lyw07** [comment]
Hi @benjaoming I think the problem exists when `python3-cryptography` is installed with `pyopenssl==17.5.0` or `pyopenssl==17.4.0` bundled inside Kolibri. Does your kolibri installation have `OpenSSL` in the dist folder?

I don't think we probably need our own patched version of `pyopenssl`. 
If I remember correctly, we bundled `pyopenssl` only to fix the Ubuntu 14.04 issue? So I guess it's not necessary for us to have `pyopenssl` in Ubuntu 16.04 if we only use `python3-cryptography`?

**Comment by benjaoming** [comment]
Mainly a note to myself: This is reproducible when a virtual environment interacts with the outside, i.e. `mkvirtualenv --system-site-packages -p python3`

**Comment by benjaoming** [comment]
Sorry about jumping in on this late, but I think the best fix for a right-around-the-corner deadline might be to re-add the 64bit Linux C extensions?

Are there any other quick options?

**Comment by lyw07** [comment]
Might be better to re-add the 64bit linux c extensions. Do we still have enough space to upload on PyPi? Thanks!

**Comment by benjaoming** [comment]
@lyw07 I think so! I have no reason to believe that we added more space-requiring dependencies since last :)

**Comment by lyw07** [comment]
@benjaoming Then I will create a pull request to add back the 64 bit Linux c extensions.
