### ISSUE TITLE
Various errors when exiting a Exercises and PDFs in a Lesson

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3309]
Getting different errors which seem to be due to quirks of the individual content renderers.

To reproduce:

1. Create, active, assign a Lesson with a PDF doc and/or Perseus Exercise
1. Go to the Lesson and view the Resource
1. Hit the "<-" button on the top bar
1. In the console, observe the Error.

This does not seem to mess with logging or affect any part of the User Experience, but does point to some code issues.

Don't see this error with HTML5 apps or videos. Couldn't find a channel with just MP3 audio.

## Exiting an exercise

Get this error
```
{request: {…}, url: "/api/attemptlog/?1520367692407=1520367692407", raw: XMLHttpRequest, status: {…}, headers: {…}, …}
entity
:
end_timestamp
:
["This field may not be null."]
__proto__
:
Object
```

## Exiting a PDF

```
[Vue warn]: Error in event handler for "updateProgress": "TypeError: Cannot read property 'channel_id' of undefined"

found in

---> <ContentRender> at kolibri/core/assets/src/views/content-renderer/index.vue
       <LearnContent> at kolibri/plugins/learn/assets/src/views/content-page/index.vue
         <LessonResourceViewer> at kolibri/plugins/learn/assets/src/views/classes/LessonResourceViewer.vue
           <AppBody> at kolibri/core/assets/src/views/app-body/index.vue
             <CoreBasePage> at kolibri/core/assets/src/views/core-base.vue
               <Root>
```

**Comment by indirectlylit** [comment]
thanks. since it doesn't seem to have an impact we can probably live with it for a bit but definitely don't want it to linger

**Comment by rtibbles** [comment]
My main concern here is that these are data logging errors, although it's possible this is happening because of our use of `beforeDestroy` handlers to try to preserve data.

**Comment by indirectlylit** [comment]
yes if this is affecting logging progress on-close we should probably aim for 0.8

(ref #2355)

**Comment by DXCanas** [comment]
> yes if this is affecting logging progress

Progress is logged in a few different places - this affects the progress that gets logged on scroll, but progress gets logged at the end of the "target" amount of time anyway - we can bypass the `onScroll` log and just have update on an interval more often?

**Comment by DXCanas** [comment]
Been finding a bunch of false positive leads on this.

Looks to me like a race condition that is a direct result of setting the `pageState` too early - `content-page` is still getting destroyed when we activate the loading state. Pulling the `state` out from under `content-page`'s feet as its getting destroyed leads to undefined getters, including `channelId`. 

If we pre-emptively set `pageState` within `topics-page`, we get the same result in other parts of learn. 

Alltogether, it's an issue with the way the Vue lifecycle interacts with Vuex state, and we haven't seen it more often because we tend not to use `beforeDestroy()`

**Comment by jonboiser** [comment]
Still seeing this on the Learn Page for PDFs. View any PDF, then exit out to a different page; will see the error in original post.

**Comment by bonidukic** [comment]
Re-flagging this as it is still an issue for Perseus Exercises.
