### ISSUE TITLE
Visible scroll bar is non-functional in content import interface

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3313]
### Observed behavior
Once you have entered the import full screen view on content import, the right hand scroll bar is no longer functional for scrolling within the page.

![image](https://user-images.githubusercontent.com/1680573/37168826-f4a5d7e4-22ba-11e8-8d0a-0358015689be.png)

### Expected behavior
Scroll bar should indicate current scroll level, and should be usable to scroll.

### User-facing consequences
Confusion, annoyance, use of arrow keys to scroll.

### Context
Extant on release-v0.8.x

**Comment by DXCanas** [comment]
I'd seen this, and then stopped seeing it as I looked for a fix. Seems like it made a comeback when merged to `release-v0.8.x`
