### ISSUE TITLE
Bake AuthMessage into AppBody/CoreBase

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#3314]
### Observed behavior

`AuthMessage` has to be explicitly imported inside of every plugin's index, and has resulted in inconsistencies in display (which have been resolved up until this point) and methods of display.

### Expected behavior

It could be a simple prop to `core-base` instead, resolving inconsistencies and extraneous checks (having to `v-if` the body of each plugin's root `index`.

**Comment by indirectlylit** [comment]
I believe this is complete
