### ISSUE TITLE
Learn top nav items should be visible even if no content exists

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3316]
### Observed behavior

Upon clicking on channels or recommended, the top nav disappears.

![localhost_8000_learn_](https://user-images.githubusercontent.com/7193975/37172282-3632369e-22c5-11e8-8ce2-347f63a661ff.png)

![localhost_8000_learn_ 1](https://user-images.githubusercontent.com/7193975/37172286-3743f3d8-22c5-11e8-8467-f23c00e040fc.png)

…

### Expected behavior

Consistent visibility of top nav.
…

### Steps to reproduce

Have no channels. 
…

Follow up of #3315

**Comment by DXCanas** [comment]
What would be in the classroom if there's no content?

**Comment by rtibbles** [comment]
Unclear if this is desireable or extant. Reopen if needed.
