### ISSUE TITLE
database corruption detection does not work on windows

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3336]
### Observed behavior

Based on [this comment](https://github.com/learningequality/kolibri/pull/3332#issuecomment-371973225) it sounds like warnings about DB corruption do not work on windows.

This might be because the warning is hidden behind the GUI?

### Expected behavior

Warnings should work on windows

### User-facing consequences

Windows users will have trouble debugging corrupted DBs

### Context

#3332

**Comment by benjaoming** [comment]
It's not the detection that doesn't work, but the suggestion for fixing it, because it uses Unix-style command pipes.

I wouldn't bother with this, we need to treat the causes, not the symptoms.
