### ISSUE TITLE
logging can happen before setup_logging is called

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3337]
### Observed behavior

It was [observed that](https://github.com/learningequality/kolibri/pull/3332#issuecomment-371971093) `setup_logging()` is called after calling `django.setup()`. This causes some error text to not appear formatted in a standard way, and may not be treated consistently as other logs.

### Expected behavior

All logging should occur after `setup_logging()`

### User-facing consequences

Some messages may be formatted inconsistently or not logged at all.

### Context

#3332

**Comment by rtibbles** [comment]
This has been addressed.
