### ISSUE TITLE
building pex throws sed error and doesn't output version

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3342]
### Observed behavior

Trying to build a pex on mac fails after running

```bash
make dist
make pex
```

generates a pex file called `kolibri-.pex`

### Expected behavior

creates a pex without error, and with a version number

### User-facing consequences

confusing error thrown and pex file is not named correctly

### Errors and logs

```
$ make pex
python -c "import kolibri; print(kolibri.__version__)" > kolibri/VERSION

Current version is now 0.8.0b2.dev+git-41-gf9a6f59cd
ls dist/*.whl | while read whlfile; do pex $whlfile --disable-cache -o dist/kolibri-`cat kolibri/VERSION | sed -s 's/+/_/g'`.pex -m kolibri --python-shebang=/usr/bin/python; done
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

### Steps to reproduce

try building a pex on mac

### Context

kolibri 0.8, macos

**Comment by mrpau-eugene** [comment]
@indirectlylit I think this answers the question why it throws that error https://unix.stackexchange.com/a/131940

> OS X's sed doesn't support -s (--separate), -u (--unbuffered), or -z (--null-data).

@benjaoming it seems that you changed this in one of your commits https://github.com/learningequality/kolibri/commit/584aad01b086d7b5dd9cd7dc635a9f0c4c3249a9

may I know why was this done?

**Comment by benjaoming** [comment]
@mrpau-eduard 

As the commit msg suggests:

>  Make filename friendlier to file systems and docker labels 

The builds would fail if file names contain `+` in the Docker label, and on Windows I think this isn't a valid character for the file name.

The `sed` expression just replaces `+` with `_`.

**Comment by indirectlylit** [comment]
@benjaoming sounds like the issue is that the version of `sed` which ships on mac has a different interface than that which ships on linux.

It would be best to do the `+` -> `_` replacement using something more cross-platform
