### ISSUE TITLE
How to get VTT changes activated in Kolibri?

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3343]
### Observed behavior

1. It seems that only only one language is available for for subtitles. 
2. Most Kolibri material is in English.
3.In many non-native English speaker countries, English is desired.

Therefore for many people, TWO subtitles should be available: one in the native language and one in English.

 
To achieve this  I was thinking of create two instances of kolibri. One for English and one for the local language.  I tried modifying a VTT file but the changes were not reflected on screen, even after restarting the server. Therefore my question is how to get VTT changes activated in Kolibri?

### Context
 * Kolibri version pex 7.1

 * Operating system
Linux manjaro
 * Browser
Vivaldi

…

**Comment by rtibbles** [comment]
Hi @nobicycle - Kolibri supports arbitrary numbers of subtitle files per video, so if available they will be there.

We generally pull in subtitles from our content providers, and do not currently have a mechanism for adding additional ones within Kolibri or Kolibri Studio, but knowing that their is demand for this functionality is helpful! 

If you are modifying the VTT files in the Kolibri content folder by hand, there is nothing that would prevent the modifications from showing up, except possibly the browser cache. 

Which content are you interested in subtitling, and in which languages?

**Comment by nobicycle** [comment]
Hi rtibbles,
Then the problem must have been browser cache. I'll check.
I am interested in all STEM-like content in languages en and id. en is there by default so I will take the en vtt and 95% automate translation with Google translate - it gives an understandable translation even if a bit turgid.

**Comment by rtibbles** [comment]
Note that I slightly misspoke above, if you have the new files you can add them to video files in your own custom channel through Kolibri Studio. If you are interested in this let me know, and one of our team can give you access via email.

**Comment by nobicycle** [comment]
Hi rtibbles,
Yes I am interested to do this through Kolibri Studio. So they would appear in the captions menu as a second language?
![screenshot_2018-03-17_10-31-43](https://user-images.githubusercontent.com/1372447/37550815-a5027ed4-29ce-11e8-9ccf-b01b81782491.jpg)

Just for completion, if I wanted to do it manually, assuming an existing file:

> .kolibri/content/storage/e/7/e7e4fcb0b20c3446478bcbe55ec63b5e.vtt

in en. How would I name the id version? Would this work (post-fixing id) 

.kolibri/content/storage/e/7/e7e4fcb0b20c3446478bcbe55ec63b5e-id.vtt

?

**Comment by rtibbles** [comment]
Yes - it would show as a second language in the list.

Unfortunately, for the manual approach, the subtitle file also needs to be registered in the database, so it starts to get a bit more complex!

Please send an email to richard *at* learningequality.org and I can help get you set up!
