### ISSUE TITLE
Some sample learners from generate-user-data appearing out of order

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3347]
On Coach Learner Reports, these two appear at top of list

Link to beta page: http://kolibribeta.learningequality.org/coach/#/fa4cbfeda32c0c0fbf1832fc1ddd10c3/learners

<img width="540" alt="screen shot 2018-03-12 at 2 11 48 pm" src="https://user-images.githubusercontent.com/10248067/37309843-64794974-25ff-11e8-88ac-8ca7f6bfe558.png">

Observations: 
1. "Jikutokuruka" and "Takitoteka" don't appear in alphabetical order (rest of list is alphabetized)

**Comment by rtibbles** [comment]
Do we alphabetize by username or fullname?

**Comment by jonboiser** [comment]
In this particular table, since fullname is in first row, we alphabetize by the fullname (this was not consistent in other User tables until recently.)

The issue here is that rows 3 and below follow that, but for some reason the first two don't. My hunch is that it has something to do with the spreadsheet these names come from (character encoding, or something).
