### ISSUE TITLE
binaries not getting installed and node-engine incompatibility module

### ISSUE THREAD

**Issue by djholmes** [learningequality/kolibri#3365]
binaries not getting installed even after yarn install --force command instead get node engine compatibility error 

### Observed behavior

only getting error regarding node compatibility

### Expected behavior
it should run and install the dependencies

### Errors and logs

```
kolibri) pratham@ubuntu:~/kolibri$ yarn install --force
yarn install v1.5.1
$ node ./frontend_build/src/npm_deprecation_warning.js
[1/5] Validating package.json...
error kolibri@0.0.1: The engine "node" is incompatible with this module. Expected version "6.x".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/pratham/kolibri/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Steps to reproduce

i have followed all the steps in the documents

### Context

 * Kolibri version - 0.6
 * Operating system - ubuntu 16.04.03 LTS
 * Browser -- Mozilla and chrome

**Comment by indirectlylit** [comment]
Looks like you solved this: https://github.com/learningequality/kolibri/issues/3366#issuecomment-373335407
