### ISSUE TITLE
WebpackError at /setup_wizard/

### ISSUE THREAD

**Issue by djholmes** [learningequality/kolibri#3366]
### Observed behavior
webpack compilation fails everytime and frontend is not able to load 
…

### Expected behavior
front page should be visible at 127.0.0.1:8000 but only error exists

…

### User-facing consequences
development server is not working therefore difficult to continue and contribute
…

### Errors and logs
error on browser
```
Request Method: | GET
-- | --
http://127.0.0.1:8000/setup_wizard/
1.11.10
WebpackError
Webpack compilation still in progress
kolibri/core/webpack/hooks.py in _stats_file_content, line 124
/home/pratham/.venvs/kolibri/bin/python
2.7.12
['/home/pratham/kolibri/kolibri/dist',  '',  '/home/pratham/.venvs/kolibri/lib/python2.7',  '/home/pratham/.venvs/kolibri/lib/python2.7/plat-x86_64-linux-gnu',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-tk',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-old',  '/home/pratham/.venvs/kolibri/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/pratham/.venvs/kolibri/local/lib/python2.7/site-packages',  '/home/pratham/kolibri',  '/home/pratham/.venvs/kolibri/lib/python2.7/site-packages',  '/home/pratham/kolibri/kolibri/dist/py2only']
Thu, 15 Mar 2018 12:41:19 +0530
```
error on terminal
t to /tmp/118215-27036-jiuykp.gnpwn.json
INFO:kolibri.core.webpack.management.commands.webpack_json:Writing webpack_json output to /tmp/118215-27036-jiuykp.gnpwn.json
ERROR    "GET /setup_wizard/ HTTP/1.1" 500 204545
ERROR:django.server:"GET /setup_wizard/ HTTP/1.1" 500 204545
Error:  Incorrect node version
`package.json` specifies `6.x`, you’re currently running `v9.8.0`.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node ./frontend_build/src/webpackdevserver.js
Directory: /home/pratham/kolibri
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/pratham/kolibri/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR    Webpack process exited unexpectedly.
ERROR:kolibri.core.webpack.management.commands.devserver:Webpack process exited unexpectedly.

…

### Steps to reproduce
followed all the guidelines for development -- 
link -- https://kolibri.readthedocs.io/en/release-v0.6.x/dev/getting_started.html
…

### Context
Tell us about your environment, including:
 * Kolibri version - 0.6
 * Operating system - ubuntu 16.04.03LTS and ubuntu 14.04.05
 * Browser -- chrome and firefox
…

**Comment by mrpau-eugene** [comment]
@djholmes have you tried using node version 6? it seems like it's coming from this one
```
Error: Incorrect node version
package.json specifies 6.x, you’re currently running v9.8.0.
```

**Comment by djholmes** [comment]
@mrpau-eugene thanks for your help but i have tried with 6.13 also, than also it was giving the same error, so please help

**Comment by mrpau-eugene** [comment]
@djholmes that's weird.. here's my node version
```
$ node --version
v6.11.2
```

**Comment by mrpau-eugene** [comment]
@djholmes You just have to wait until webpack finishes. it may take awhile

**Comment by djholmes** [comment]
@mrpau-eugene if i am using latest version it should be compatible with the 6th version, or again i install node 6 and will kolibri work  on npm version 3 because when we install node 6 we get npm 3.10 please say

**Comment by djholmes** [comment]
@mrpau-eugene thanks for your help it worked i left it for compilation for more time and then run the server

**Comment by indirectlylit** [comment]
glad it's working!
