### ISSUE TITLE
Building dist is slow because compilemessages includes kolibri/dist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3384]
### Observed behavior

Much of the build time is spent like this:

![screenshot from 2018-03-19 11-50-16](https://user-images.githubusercontent.com/374612/37591494-07ca2082-2b6c-11e8-9c40-41ec5cd26bdb.png)

### Expected behavior

Should skip `kolibri/dist` since everything there is third-party.

### User-facing consequences

n/a

### Errors and logs

n/a

### Steps to reproduce

`make dist`

### Context

n/a

**Comment by indirectlylit** [comment]
would be great to speed things up a bit

**Comment by benjaoming** [comment]
Sorry, I didn't see the new milestone, just went and fixed it immediately :)

**Comment by rtibbles** [comment]
This has been fixed already.
