### ISSUE TITLE
Exam details are overlapping at the bottom of the container 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3385]
### Observed behavior
Some details of exam are overlapping.

![screen shot 2018-03-19 at 7 21 00 pm](https://user-images.githubusercontent.com/8663934/37593470-11b00d3c-2bad-11e8-983f-abb54d831955.png)

### Context

 * Kolibri version - Kolibri 0.9.0.dev+git-20180319034928
 * Operating system - Mac
 * Browser - Google chrome Version 65.0.3325.162 (Official Build) (64-bit)

**Comment by indirectlylit** [comment]
cc @christianmemije

**Comment by christianmemije** [comment]
Cannot seem to reproduce 

![bs_macsl_chrome_49 0](https://user-images.githubusercontent.com/7193975/37622599-4f8c3ad2-2b7f-11e8-9a0f-3ebea59cecdc.jpg)

**Comment by mrpau-richard** [comment]
Closing this, My local develop is not updated.
