### ISSUE TITLE
Viewing offline video in kolibri running on Tablet with android 6.0

### ISSUE THREAD

**Issue by dade-ally** [learningequality/kolibri#3392]
### Observed behavior

Khan Academy French contents curated from studio and downloaded to 1.3Ghz 1+16GB running Android 6.0, some contents just display kolibri splash continuously but never open while quizzes just error "can't handle"

![kolibri](https://user-images.githubusercontent.com/2367265/37725640-a69dd476-2cf0-11e8-8311-ac82c6b6c264.gif)

### Expected behavior

Contents should open after the initial kolibri splash, this does not take up to 10seconds normally

### User-facing consequences

We are still at testing phase of each aspect of the application. Where can I get the error log for Android without root access?

### Errors and logs

…

### Steps to reproduce

Install kolibri_buildkite_build-2175_3143_kolibri-0.6.dev020171020180700_git-py2.py3-none-any on Tablet

Download sample contents onto the tablet using the app

Run app for viewing video contents

### Context

Kolibri version--- kolibri_buildkite_build-2175_3143_kolibri-0.6.dev020171020180700_git-py2.py3-none-any

 * Operating system- Android 6.0
 * Browser- native app

**Comment by indirectlylit** [comment]
cc @DXCanas

**Comment by DXCanas** [comment]
Hi! Just to clarify: Did you install this using a Kolibri `.apk` file? Where/when did you get this `.apk`? It's currently under active development, so the directions for getting logs are constantly changing.

**Comment by indirectlylit** [comment]
closing because most work has migrated to https://github.com/learningequality/kolibri-installer-android/

please re-open there if necessary
