### ISSUE TITLE
Content wizard for channel UPDATE view does't update properly

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#3395]
I was documenting another issue with UPDATE of exercise nodes, https://github.com/learningequality/kolibri/issues/3246#issuecomment-375073223 and in the process noticed a UI problem with the channel update wizard.

### Context
  - We have a Kolibri 0.7.2 (or 0.8) with a channel X installed, at version Y. (contains three topics)
  - Studio has version Y+1 of the channel (two topics)
  - Device owner wants to update channel through IMPORT content wizard web interface

### Observed behavior

User sees notification that there is channel update available (version 9 available):
<img width="1358" alt="step1_before_update" src="https://user-images.githubusercontent.com/163966/37734120-9fb66dc8-2d20-11e8-826d-c1cb1f36322e.png">

Clicking on UPDATE brings us to this screen:
<img width="1359" alt="step2_afrer_db_update" src="https://user-images.githubusercontent.com/163966/37734621-1fd03236-2d22-11e8-9efa-d296c59c247f.png">

Note the bottom half of the IMPORT wizard view hasn't updated, and still shows the old channel structure.

### Expected behavior
After clicking UPDATE, the bottom half of the page "Choose content to import" should get updated and show the files available for import in the new version.

### User-facing consequences

This is just a UI bug (fails to update frontend), but would be good to address as otherwise the UPDATE flow is broken (users will click UPDATE and get an updated DB, but not updated files).

Specifically, the db-only-partial update can break exercises as document here:
https://github.com/learningequality/kolibri/issues/3246#issuecomment-375073223 and in the process 
(DB contains FK --> to a perseus file that doesn't exist)

**Comment by jonboiser** [comment]
this might have been fixed in https://github.com/learningequality/kolibri/pull/3233

not sure if it was relevant to your scenario, but we also had an issue were the "total size" stats would not change after an update as well.
