### ISSUE TITLE
Font sizes and spacing of radio text on "Add new account"

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#3401]
### Observed behavior

![image](https://user-images.githubusercontent.com/618416/37796630-fbf00798-2dd4-11e8-91f0-17a45507f115.png)

### Expected behavior

- Would expect explanation text to be smaller/less prominent than the title (or that they were combined somehow, e.g. with a colon, rather than linebreak).
- The explanation for "Class coach" is closer to the "Facility coach" radio button than its own button, which feels messy/misleading.

### Context

Kolibri 0.9.0 beta demo site

**Comment by khangmach** [comment]
label text perhaps??

**Comment by indirectlylit** [comment]
we have a pattern for this in the setup wizard

**Comment by indirectlylit** [comment]
I think it would be reasonable to bake that into the core radio button component

**Comment by christianmemije** [comment]
Fixed in #3472
