### ISSUE TITLE
Users with a Facility/Class Coach Role should be redirected to the Coach page after logon

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3407]
### Observed behavior
If you are a Facility/Class Coach, you are sent to the "Learn" page after logging on. To get to the Coach pages, you need to navigate there via the side navigation.

This behavior was brought up in at least two different QA sessions.

### Expected behavior

More likely than not, if you are a Coach, you are logging into the app to view Coach tools (reports, exams, etc.). It would be nice if the Coach was sent to coach tools after logging in.

### User-facing consequences

Coach users save some extra clicking around.

**Comment by BruvaJ** [comment]
Looked into picking this up. Potentially a bug found, but not familiar enough with this project. Hope this is useful...

- Checked out latest version on dev and there is no option to create a user. Only sign-in or open as guest:
![screenshot](https://user-images.githubusercontent.com/19907551/37867320-4b8559a6-2f8e-11e8-9439-b6e4fae36c70.png)

Not familiar enough with setup. Would have run python manage.py shell then create user directly as workaround but manage.py seems hidden away then could have worked on this.

**Comment by radinamatic** [comment]
@BruvaJ You probably have the option deactivated in your Facility settings:

![manage-facility2](https://user-images.githubusercontent.com/1457929/37869156-c3d502fe-2f6f-11e8-813e-b5d2e98daa82.png)

**Comment by BruvaJ** [comment]
Thanks @radinamatic , I'll try and look into this again later today

**Comment by rtibbles** [comment]
@mrpau-eugene as this is not urgent, I've assigned @HansGam to take a look at this so you can focus on the more urgent 0.9.1 issues!

**Comment by jonboiser** [comment]
#3537
