### ISSUE TITLE
Assigned Group names missing from 'Activate exam' confirmation modal

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#3418]
### Observed behavior
When I assign an exam to a particular group, there is a blank space where the group name should appear in the confirmation window when activating it. However, does not prevent the exam from being successfully assigned to the particular group.

![image](https://user-images.githubusercontent.com/22602993/37879673-5726ad32-3074-11e8-87bf-9e0081f4573c.png)

Related: Toggling back and forth between one group and entire class produces the result of saying it's visible to 2 groups when only 1 group exists:

![image](https://user-images.githubusercontent.com/22602993/37879667-439add9c-3074-11e8-9d4f-1db6f995046f.png)

Then an error message is displayed.

### Errors and logs
```
{ "request": { "path": "/api/examassignment/", "entity": "{\"exam\":\"e704ddfbef04af1d5b020507b4557af9\",\"collection\":\"a2de8f52a93e6f16d811e2801303f0d5\"}", "params": { "1522009840885": 1522009840885 }, "headers": { "Content-Type": "application/json", "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2", "X-CSRFToken": "xGWbRMTZBB2h74gi9A2XUbRdL4NkbBIlAz3f9K0qi7hAlvc2BRnxHqfcu0tIPDPF" }, "method": "POST", "canceled": false }, "url": "/api/examassignment/?1522009840885=1522009840885", "raw": {}, "status": { "code": 500, "text": "Internal Server Error" }, "headers": { "Date": "Sun, 25 Mar 2018 20:30:41 GMT", "Vary": "Accept-Language, Cookie", "Server": "0.0.0.0", "Content-Length": "27", "X-Frame-Options": "SAMEORIGIN", "Content-Language": "en", "Content-Type": "text/html" }, "entity": "<h1>Server Error (500)</h1>" }
```

### Steps to reproduce

Create an exam, assign it to one group and then activate it. Then toggle back and forth between the 1 group and the entire class.

### Context

* 0.8.0
* Mac OS
* Chrome

**Comment by christianmemije** [comment]
That modal no longer exists in 0.9. Closing.
