### ISSUE TITLE
Refactor kolibri/dist to kolibri/vendor

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3422]
### Observed behavior

This should be a small refactor, only affecting build tools and the initial setting up of the `sys.path` environment for Kolibri

The reason is that I find that `vendor` is the most commonly used library name for bundling of someone else's project.. AKA "vendoring"

Examples:

 * pip: https://pip.pypa.io/en/stable/news/
 * https://ironboundsoftware.com/blog/2017/07/19/pip-and-private-repositories-vendoring-python/

### Expected behavior

n/a

### User-facing consequences

None

### Errors and logs

n/a
### Steps to reproduce

n/a

### Context

n/a

**Comment by rtibbles** [comment]
I think we've survived this long with dist, we can keep going with it.
