### ISSUE TITLE
Coach exams show exercise-less channels.

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#3423]
**Observed behavior**
Coach exams are showing channels (greyed out) that do not have exercises to pull questions from.
<img width="454" alt="screen shot 2018-03-26 at 2 32 32 pm" src="https://user-images.githubusercontent.com/25045166/37934403-f4ec453e-3102-11e8-8376-917bed479f27.png">

**Expected behavior**
Do not show these greyed out channels. Only show channels that have exercises. Should be filtering these channels out. See github issue that solved this problem in 0.8: https://github.com/learningequality/kolibri/issues/2770

**User-facing consequences**
No real benefit or value for the user. Pushes relevant channels downwards and is also unable to be navigated. 

**Steps to reproduce**
- Navigate to coach exams
- Create a new exam
- See list of channels

**Comment by jonboiser** [comment]
#3425
