### ISSUE TITLE
Can't change questions in exercise detail report view

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3424]
### Observed behavior
When clicking on a different question in the exercise detail report view, the URL changes, but no change occurs in the page itself.
A refresh on that URL does load the correct attempt.

### Expected behavior
Should switch without a refresh.

### User-facing consequences
Makes the detail report frustrating.

### Steps to reproduce
Look at a learner that has answered more than one question on an exercise on the coach reports.

**Comment by benjaoming** [comment]
Reported fixed in #3426
