### ISSUE TITLE
Corrupt database when upgrading debian package 0.9.0-b2 => 0.9.0-b3

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3437]
### Observed behavior

(pending investigation)

![image](https://user-images.githubusercontent.com/374612/38054178-7ec09a56-32d6-11e8-8ee5-37c9652b025c.png)

### Expected behavior

Fails when automatically upgrading

### User-facing consequences

Corrupting database upon upgrade?

### Errors and logs

Notice the nice exception message though :)

### Steps to reproduce

1. install .deb version 0.9.0b2
1. install .deb version 0.9.0b3 (on top of the other)

### Context

n/a

**Comment by jamalex** [comment]
Is this replicable? Or was it a one-time thing?

**Comment by ralphiee22** [comment]
Are migrations run during the upgrade? could be a source of the corrupt database

**Comment by benjaoming** [comment]
@ralphiee22 don't think so because this has happened in other scenarios, too... should maybe close this as a duplicate

Another thing about this is:

The database is immediately *malformed* when running Kolibri, so is likely something that happens during shutdown of the previous instance. The error is produced before running migrations, dbbackup etc.

Thought of two things that might move us forward:

1) Add more debug information to the database message (db file size + timestamp + what else?)
2) Ensure that `kolibri.cli.stop` produces as `SIGTERM` and that we are sure when sending `SIGKILL` that this isn't somehow the cause *)

*) Other examples of malformed databases happen in Tox, and have been reported through CTRL+C'ing a foreground process.

**Comment by indirectlylit** [comment]
so far, seems like this might be another instance of #3437. therefore, bumping to 0.9.1 since it's not a regression

**Comment by benjaoming** [comment]
## Tox tests proof evidence of certainty in failure

This worked every time for me:

```
git checkout release-v0.9.x
tox -e py3.5 kolibri/utils/tests  # specify a quick subset of tests, doesn't matter which
tox -e py3.5 kolibri/utils/tests  # RUN IT AGAIN
```

## This always gives a malformed database

```
git checkout release-v0.9.x
tox -e py3.5 kolibri/utils/tests  # specify a quick subset of tests, doesn't matter which
git checkout release-v0.8.x
tox -e py3.5 kolibri/utils/tests  # RUN AGAIN
```

Also running twice on 0.8.x

```
git checkout release-v0.8.x
tox -e py3.5 kolibri/utils/tests  # specify a quick subset of tests, doesn't matter which
tox -e py3.5 kolibri/utils/tests  # RUN AGAIN
```

## Narrowing it down

The above `py3.5` environment leaves behind `.tox/py3.5/tmp/.kolibri/`. After reproducing a "malformed" DB on 0.8.x, checking out 0.9.x actually works. So it seems that there is something in 0.8.x that causes the database to be malformed.

0.8.x and 0.9.x diffs:

 * Same version of Django
 * Same version of test frameworks, pytest, tox etc
 * Same `tox.ini`
 * sqlalchemy got bumped frmo 1.2.3 to 1.2.4: #3293

Investigation notes:

1. Running `tox -e ...` on 0.8.x with a clean `.tox`. It works.
1. Runing it again n 0.8.x, it breaks because of a malformed database
1. Verified that the db in `.tox/py3.5/tmp/.kolibri/` is malformed after exiting tox. It is.
1. Switching to 0.9.x and the db in `.tox/py3.5/tmp/.kolibri/` is still reported malformed with all kolibri commands running.
1. Running tests again, and it works.

**Comment by benjaoming** [comment]
## Follow up no. 1

It is not the orphaned `.pyc` migration files that a previous checkout of 0.9.x will leave behind.

Will correct the examples about, it doesn't seem like just running `kolibri manage makemigrations --check` on a 0.9.x will generate the culprit `pyc` files.

**Comment by benjaoming** [comment]
## Follow-up no. 2

I now have serious doubts about which *pyc files have been included because something triggers them to be removed as well. My experiments have become more detailed, checking at each step *if* the `pyc` files are even there.

So far, the most certain thing seems to be more related to whether or not the `.tox` directory is deleted or not, although I was also successful in producing malformed databases with an intermediate deletion of `.tox`.

I keep this issue open to track the various notes underway, will refine the comments and in the end close this issue (because I know that it's a duplicate).

**Comment by indirectlylit** [comment]
see also #3228

**Comment by benjaoming** [comment]
Update on the previous notes for reproducing a malformed db: They don't work (but using Python 3.6 this time).

Am trying to create a malformed db that isn't 19 MB like the one I have stored here, in order to implement tests for the new `kolibri manage dbrecover` command.

**Comment by benjaoming** [comment]
Have tried to follow previous recipes in an Ubuntu 16.04 VM, and have been unsuccessful with all previously documented approaches.

At this stage, I give up because I have spent far too much time trying to isolate and reproduce this.

**Comment by benjaoming** [comment]
I think we need to open up a clean issue if the problem re-occurs. We can use this information to look for OTHER reasons why the DB might be malformed :)
