### ISSUE TITLE
unlocalized text in examReport

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3441]
### Observed behavior

in learner's exam results

![image](https://user-images.githubusercontent.com/2367265/38086511-eda291bc-3354-11e8-891f-402ae73921ea.png)

and

![Uploading image.png…]()

### Expected behavior

localized

### User-facing consequences

hard to understand

### Context

0.9

https://github.com/learningequality/kolibri/blob/1c6ec061212c0f229c1d6f539daddf675e65a7bc/kolibri/core/assets/src/views/exam-report/index.vue#L25

**Comment by rtibbles** [comment]
Fixed in #3585
