### ISSUE TITLE
Lint for unused translations 

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3451]
### Observed behavior

There are some strings in the codebase that are never referenced. 

### Expected behavior

Warn about unused translations

### User-facing consequences

Wastes time for translators.

I was thinking we can search if the string is referenced inside the `registerFoundMessages` function. The typical case of `$tr('translation'...` is easy to search for but sometimes translations are not referenced like that. Sometimes there is a map of translations that is passed into a function. Or in places like the Perseus exercise renderer, the strings are never actually referenced in our codebase. Thoughts @rtibbles? 

Also handling strings that are intentionally not referenced. Also the best place in the build pipeline to lint for this.

**Comment by indirectlylit** [comment]
the flip side: https://github.com/learningequality/kolibri/issues/1958

**Comment by indirectlylit** [comment]
@nucleogenesis just noticed that this issue exists
