### ISSUE TITLE
Install docs are stale

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#3455]
following https://kolibri.readthedocs.io/en/latest/install.html#debian-ubuntu-linux

top of page:

Operating systems
Windows Vista, 7, 8.1, 10
Debian/Ubuntu: 14.04, 16.04 and up - anything that’s not end-of-life.
Linux: Any system with Python 2.7

on Debian 9 Python 2.7.13 (no python 3)

dpkg -i kolibri_0.9.0-0ubuntu1_all.deb

dpkg: dependency problems prevent configuration of kolibri:
 kolibri depends on python3 (<< 3.6); however:
  Package python3 is not installed.
 kolibri depends on python3 (>= 3.4); however:
  Package python3 is not installed.
 kolibri depends on python3-pkg-resources; however:
  Package python3-pkg-resources is not installed.

**Comment by benjaoming** [comment]
Hi @tim-moody 

The `dpkg` command doesn't install dependencies, but will only complain if they are missing. You have to install `python3` for the Debian package to work.

The reason that we sort of don't support Python 2.7 for the Debian package is that 1) it's very difficult to make a library that installs into both Python 2 and 3 paths and 2) Python 2.7 is totally outdated and you shouldn't use it :)

Debian Stretch should ship with Python 3.5, no?

**Comment by benjaoming** [comment]
This issue was moved to learningequality/kolibri-installer-debian#25
