### ISSUE TITLE
Allow learners to sign in with no password not working properly

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3459]
### Observed behavior
When "Allow learners to sign in with no password" facility is checked still it is showing password textbox. There is no effect in login page if this facility is checked or unchecked. 

### Expected behavior
It must hide password textbox if it is checked.

### Steps to reproduce
1. Login with admin account.
2. Check "Allow learners to sign in with no password".
3. Try to login.

### Context

 * Kolibri version : kolibri 0.9.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots

![before_1](https://user-images.githubusercontent.com/12776071/38195359-c8f480a2-369a-11e8-8011-d47bc7e82e8c.png)
![before_2](https://user-images.githubusercontent.com/12776071/38195360-c926f55a-369a-11e8-907b-0ba61ab1970c.png)
![after_1](https://user-images.githubusercontent.com/12776071/38195379-d71bc6c2-369a-11e8-824e-2d394a83e42c.png)
![after_](https://user-images.githubusercontent.com/12776071/38195386-de7f3bba-369a-11e8-8ba1-0f928097a502.png)

**Comment by jonboiser** [comment]
probably related to #3460 . The changes made on "Facility settings" are not being reflected at the Sign In page.

**Comment by jonboiser** [comment]
#3466

**Comment by swapnil106111** [comment]
@indirectlylit Allow learners to sign in with no password facility is working properly in Kolibri 0.9.1.
