### ISSUE TITLE
Allow learners to sign-up on this device is not working properly.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3460]
### Observed behavior
If facility "Allow learners to sign-up on this device" is unchecked still it is showing CREATE ACCOUNT  button in the kolibri login page. There is no effect on login page if it is checked or uncheked.

### Expected behavior
It must hide CREATE ACCOUNT button in kolibri login page if "Allow learners to sign-up on this device" facility is unchecked.

### Steps to reproduce
1. Check and unchecked the facility "Allow learners to sign-up on this device" and see the login page.

### Context

 * Kolibri version : Kolibri 0.9.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshots
![after2](https://user-images.githubusercontent.com/12776071/38195982-0e860ec6-369e-11e8-870b-c7d3ce14abd1.png)
![after1](https://user-images.githubusercontent.com/12776071/38195981-0e4a1344-369e-11e8-8a74-9c16f7b30503.png)

![before2](https://user-images.githubusercontent.com/12776071/38195984-0ee70afa-369e-11e8-9eee-ee2627d1bb3e.png)
![before1](https://user-images.githubusercontent.com/12776071/38195983-0eb5a5fa-369e-11e8-9e38-57d5ded4e149.png)

**Comment by jonboiser** [comment]
#3466

**Comment by swapnil106111** [comment]
@indirectlylit Allow learners to sign-up on this device facility is working properly on Kolibri 0.9.1.
