### ISSUE TITLE
Edit full name and username information using the Manage feature in the users options using Admin account.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3475]
### Observed behavior
When the admin uses manage feature in the users tab to edit the full name and username of the users and clicks on save, the first time no changes are made. After repeating the process for second time and clicking on save, there is no further movement on the screen for a long time and when you go back or press cancel, no changes are made.

### Expected behaviour

The fullname and username must have been changed instantly.

### User-facing consequences

The admins would not be able to change username and fullname if there is any issue regarding the users in the classroom.

### Errors and logs

![username_fullname edit](https://user-images.githubusercontent.com/38091824/38345755-75ee0f84-38ae-11e8-8ddf-97f00fd57b68.png)

### Steps to reproduce

1. Login as admin and go to facility--->users
2. Select any user and use the manage feature to change the fullname and username and click on save.

### Context

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot

![screenshot from 2018-04-05 08 55 19](https://user-images.githubusercontent.com/38091824/38345901-39146ef4-38af-11e8-981a-81d50a5d4e1f.png)
![screenshot from 2018-04-05 08 55 31](https://user-images.githubusercontent.com/38091824/38345903-3d7dbda6-38af-11e8-9911-039284227413.png)

**Comment by amit3107** [comment]
@mrpau-eugene

**Comment by mrpau-eugene** [comment]
@amit3107 confirmed and can reproduce this issue. will try to investigate

**Comment by amit3107** [comment]
@swapnil106111

**Comment by jonboiser** [comment]
#3478

**Comment by swapnil106111** [comment]
@rtibbles Tested in Kolibri 0.9.2. Working as expected.
