### ISSUE TITLE
Entering existing Username with different cases does not display error message.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3477]
### Observed behavior

In the add new user feature under users tab, adding user is working fine. If we add an existing username it shows an error message which is not the case if we add same username with different cases. For eg., if abc is existing username, then adding ABC as username must also show an error message, rather it does nothing and the user cant be created.

### Expected behaviour

If we add existing username with different cases the screen shows nothing and no changes can be made, rather it must display an error message For eg., if abc is existing username, then adding ABC as username must also show an error message.

### User-facing consequences

The admins who wants to add new user must understand that 2 users cant have same username with different cases and it should be displayed as message.

### Errors and logs
![3](https://user-images.githubusercontent.com/38091824/38349470-e5b113e6-38c4-11e8-876d-0978536bbb8e.png)

### Steps to reproduce

1.Login as admin and go to facility--->users
2.Use add new user and try adding existing username with different cases and click on create account.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/38091824/38349536-33129538-38c5-11e8-91b2-eef82003348c.png)
![2](https://user-images.githubusercontent.com/38091824/38349544-3c69b814-38c5-11e8-8238-8072161b4fdf.png)

**Comment by amit3107** [comment]
@mrpau-eugene

**Comment by jonboiser** [comment]
#3479 should fix this by 

1. Doing a client-side check on the UserCreateModal to see if a new user's username is already used, and normalizes new and current usernames to be all lowercase before comparing.
1. Does a similar check on the EditUserModal, but still allows a user to make changes like `user` -> `USER`

**Comment by swapnil106111** [comment]
@rtibbles Tested in Kolibri 0.9.2 but facing same issue.

For existing username case, it showing error.
![2](https://user-images.githubusercontent.com/12776071/40220972-9d611104-5a98-11e8-9126-67e12e534382.png)

For existing username with different case, it is not showing error.
![1](https://user-images.githubusercontent.com/12776071/40221005-bf70f91c-5a98-11e8-87bd-c0a60420570a.png)

**Comment by rtibbles** [comment]
Ah yes, apologies. I mislabelled this. Due to string changes, this was not added to 0.9.2.

**Comment by rtibbles** [comment]
(note that this should still be disallowed once you press the 'Create Account' button due to server side changes that were included).
