### ISSUE TITLE
Not able to go back using the back arrow key while a channel listing is being generated.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3480]
### Observed behavior

In the Import content feature once a channel is selected, a message is displayed for a long duration : Generating channel listing.This could take a few minutes.. The user is not able to move back also using the back arrow key beside select content header.

### Expected behaviour

Even if the channel listing being generated takes a lot of time, the user must be able to go back instantly. This can be done by browser back arrow key but not the back arrow on the window beside the header- select content.

### User-facing consequences

TIme consuming for the admin.

### Errors and logs
![d](https://user-images.githubusercontent.com/38091824/38359301-909581b4-38e5-11e8-8dd5-968511490d91.png)

### Steps to reproduce

1.Login as admin and go to device--content import---kolibri studio---select any channel
2.Try to go back using the back arrow beside the header select content.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![b](https://user-images.githubusercontent.com/38091824/38359514-33dc6252-38e6-11e8-8e55-a8f3ef4faeba.png)
![c](https://user-images.githubusercontent.com/38091824/38359516-34524d96-38e6-11e8-8ea2-0249259b0abd.png)

**Comment by rtibbles** [comment]
This is intentional.

**Comment by indirectlylit** [comment]
@amit3107, we understand that this behavior can be frustrating and in the long term hope to allow it
