### ISSUE TITLE
The name of Channel in Kolibri Studio is different from its name on Kolibri platform.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3481]
### Observed behavior

Name of one channel in Kolibri studio is Maharashtra state class 6 whereas its name in the Kolibri Platform is Maharashtra State Marathi Medium.

### Expected behaviour

The channel name must be the same in the Kolibri studio and in the platform. It must be Maharashtra state class 6 or Maharashtra State Marathi Medium at both places.

### User-facing consequences

Different names can be confusing.

### Steps to reproduce

1. Login as admin and go to device-->content import--->kolibri studio--->Download channel Maharashtra State class 6 (channel id- 1918d2073e8f45009adc610d896efffe)
2. Name in the Kolibri studio: Maharashtra State Grade 6 
Name after selecting the channel on the platform: Maharashtra State Marathi Medium

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![t](https://user-images.githubusercontent.com/38091824/38364530-bb50010c-38f6-11e8-897f-8ea2e2aaba8e.png)
![u](https://user-images.githubusercontent.com/38091824/38364533-bbace188-38f6-11e8-8a5a-c41cb30c1ca1.png)
![y](https://user-images.githubusercontent.com/38091824/38364534-bbee3872-38f6-11e8-877b-50053c58d8c3.png)

**Comment by jonboiser** [comment]
The channel name "Maharashtra state Marathi Medium" is being taken from the Channel Metadata DB that is download to Kolibri. Here's a screenshot of the DB:

![screen shot 2018-04-05 at 11 51 41 am](https://user-images.githubusercontent.com/10248067/38385853-dbd2cd4e-38c7-11e8-9e39-8b9e9253206e.png)

The other channel name "Maharashtra State Class 6" comes from this API:

http://contentworkshop.learningequality.org/api/public/v1/channels/lookup/1918d2073e8f45009adc610d896efffe

The two are not consistent.

**Comment by indirectlylit** [comment]
should we migrate this issue to studio?

**Comment by indirectlylit** [comment]
migrated to studio issue above
