### ISSUE TITLE
Update dev docs in light of the parallelized 'npm run devserver' script (1st time crashes)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3482]
### Observed behavior

When I am installing a local version of kolibri and follow the docs, I get a bunch of these errors

```
$ yarn run devserver
...
  File "/Users/jon/.venvs/kolibri/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "lessons_lesson" already exists
```

It may take several tries with `yarn run devserver` to get past these errors.

I don't think the dev docs have been updated with a method to get around this:

http://kolibri-dev.readthedocs.io/en/develop/start/getting_started.html#running-kolibri-server

My suspicion is this  might be because of the new `npm run devserver` script which runs webpack and django in parallel, but I'm not sure.

### Expected behavior

Dev docs have better Getting Started instructions to avoid this.

**Comment by rtibbles** [comment]
I think this was fixed by #3542, which stops the webpack process from invoking the Django stack, so this should be resolved now. Let me know if you see it recur.
