### ISSUE TITLE
User can edit Full name/Username/password even when the admin has not given permissions.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3493]
### Observed behavior

The users (learner/coach) are able to change the full name and username without permissions.

### Expected behavior

The users must not be allowed to change the username/full name without permissions.

### User-facing consequences

The coach will get confused with changing usernames and full names.

### Steps to reproduce

1. Login as admin then select and deselect the permission of user changing full name and username and save changes.
2. Login as a learner and go to profile and try changing the full name and username.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![change](https://user-images.githubusercontent.com/38091824/38457913-52f12608-3ab4-11e8-9c2a-7ff1c6686d5a.png)
![change2](https://user-images.githubusercontent.com/38091824/38457914-533123f2-3ab4-11e8-9558-d2765b899ed6.png)
![change3](https://user-images.githubusercontent.com/38091824/38457915-53799b50-3ab4-11e8-9f8a-3c29b8f2db45.png)
![change4](https://user-images.githubusercontent.com/38091824/38457917-53d5c826-3ab4-11e8-9fdc-c13283bd413a.png)
![change5](https://user-images.githubusercontent.com/38091824/38457919-54194704-3ab4-11e8-9483-5630002e1c18.png)

**Comment by mrpau-eugene** [comment]
@indirectlylit 

I just noticed that the state only gets updated on the admin side part. For example, when I disable editing their username and full name, the state `pageState.settings` gets updated accordingly.

Accessing http://localhost:8000/api/facilitydataset/ returns the right values.

But when I logout and login using a learners account, I can still update my username and full name as shown as the problem above.

However, when I try to restart the development server, everything works fine - the user can't edit their username and full name.

Do you have any idea why the state in the admin page updates while it doesn't on the profile page?

**Comment by rtibbles** [comment]
@mrpau-eugene I think this should have been fixed by #3466 - can you test on latest release-v0.9.x and verify?

**Comment by mrpau-eugene** [comment]
@rtibbles Confirmed to be working on the 0.9 release. I was on develop version so I was able to reproduce the issue.

Can close this one now 👍
