### ISSUE TITLE
Avoid using null on string-based fields such as CharField

### ISSUE THREAD

**Issue by bonidjukic** [learningequality/kolibri#3502]
### Observed behavior
There are a few model fields definitions for string-based fields using `null=True` option which is recommended to be avoided by the [Django documentation](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.Field.null):

> Avoid using null on string-based fields such as CharField and TextField. If a string-based field has null=True, that means it has two possible values for “no data”: NULL, and the empty string. In most cases, it’s redundant to have two possible values for “no data;” the Django convention is to use the empty string, not NULL. One exception is when a CharField has both unique=True and blank=True set. In this situation, null=True is required to avoid unique constraint violations when saving multiple objects with blank values.

As far as I can see, examples of the above mentioned definitions are contained within:
- `kolibri/models/models.py`
- `kolibri/models/legacy_models.py`

specifically:
- `kolibri/models/models.py`
  - `ContentNode`
    - `license_name = models.CharField(max_length=50, null=True, blank=True)`
    - `license_description = models.CharField(max_length=400, null=True, blank=True)`
    - `description = models.CharField(max_length=400, blank=True, null=True)`
  - `Language`
    - `lang_subcode = models.CharField(max_length=10, db_index=True, blank=True, null=True)`
    - `lang_name = models.CharField(max_length=100, blank=True, null=True)`

- `kolibri/models/legacy_models.py`
  - `License`
    - `license_description = models.CharField(max_length=400, null=True, blank=True)`

### Expected behavior
Remove `null=True` option from the `CharField` model field definitions.

### User-facing consequences
This is primarily a backend related issue with no real consequences to the end users. That being said, it is possible that "emptiness" of the certain field's values is not being checked correctly if they're not taking into account the two possible states for "no data": `NULL` and empty string.

### Errors and logs
There are no errors and logs related to this issue.

### Steps to reproduce
Simply take a look at the codebase, see **Observed behavior** section for the exact files.

### Context
 * Kolibri version: all versions from 0.2.0 forward (as far as I could track)

**Comment by lyw07** [comment]
We are not currently able to fix this issue, because our old databases (e.g. v0.2.0) don't have fields such as `license_name` in ContentNode. To maintain backwards compatibility, we should work on fixing this after we are sure that all of the users have upgraded their kolibri to newer versions.

However, even when kolibri users are using the newer versions, this issue is still hard to fix. We also need to change the fields to non-nullable in Studio and republish all the channels to generate new databases. The process involves modifying Studio's production database, which is risky to some extent.

**Comment by indirectlylit** [comment]
okay thanks for the analysis! closing as wont-fix

**Comment by lyw07** [comment]
yes also thanks @rtibbles for explaining this! We will have to fix this eventually, but just not at this point though.
