### ISSUE TITLE
provide a URL and direct link to import new content from an existing channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3511]
### Observed behavior

Two observations:

1. When users finish importing content, they sometimes click 'back' in their browser and expect to be able to import more content. However this doesn't currently work.
2. On the channel list page, existing channels only have a 'delete' button, but no 'import' button. In order to import more content from a channel, you need to first click 'import' at the top and then look for the channel again.

### Expected behavior

Recommended updates below. Feel free to iterate.

* The 'content selection' page for importing should have a dedicated URL that users can navigate to. This URL should include both the source (drive name or central server url) and channel ID.
* The main channel listing page should include an 'import' action along with 'delete' under an 'Actions' drop-down. Selecting import:
  * first pops up the source selection dialog
  * then navigates directly to the content selection page for that channel and source 

### User-facing consequences

Users are currently confused, and this should help alleviate that.

------

cc @christianmemije @khangmach @jtamiace let me know what you think

**Comment by jtamiace** [comment]
Both suggested updates sound great to me, but suggest the exact name of the import action on the existing channel be something like "import more" or something which alludes to that

**Comment by jonboiser** [comment]
This needs some design and analysis, since some pieces aren't in place yet:

> This URL should include both the source (drive name or central server url) and channel ID.

We don't know the origin of a Channel. When you download a ChannelMetadata DB from studio, it's indistinguishable from one downloaded from a USB drive.

**Comment by khangmach** [comment]
not knowing the origin of the channel sounds like a blocker from slapping a url on the page. 

Nesting an "import more" option under an "actions" dropdown might solve the problem of "I need a convenient and visible way of importing more of X channel", BUT I'm not sure if tacking on shortcuts here and there is the most sustainable way to go. Will think more about this issue more when we look at a v2 version of content import (look at various shopping cart models/incorporating a clearer content import UI/incorporate content management?)

**Comment by jtamiace** [comment]
> every time you go to import, you choose the original anew

I think this would be a good solution when there is an internet connection and they can pull from the central server, but wondering about any tricky situations with USB's. 

If they select the `import more` option and that source does not exist on the connected USB, will it be disabled from the source selection menu? are we able to detect it at that point?

For the back button cases, are error states like "drive has been disconnected" or "internet connection lost" specced out already?

**Comment by jonboiser** [comment]
> If they select the import more option and that source does not exist on the connected USB, will it be disabled from the source selection menu? are we able to detect it at that point?

There can be multiple connected drives, so I guess you'd only want to allow "import more" if at least one drive has the channel. It's also important that the channel be the same version, since the past behavior has been for the app to replace the server's content metadata db with the db from the remote source (Jamie might have changed this, when the version _is_ the same but I'm not sure).

As far as I know, I think only the happy path has been partly specified.
