### ISSUE TITLE
add loading indicators to all content renderers

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3514]
### Observed behavior

In many situations it will take some time for content to be rendered, and during that time the user is left confused.

### Expected behavior

All content renderers should show a loading indicator until the content is done loading

### User-facing consequences

Confusion, and potentially navigating away before content is done loading

------

cc @christianmemije

**Comment by christianmemije** [comment]
All renderers except the epub renderer, have loaders.

**Comment by indirectlylit** [comment]
@aronasorman this is a test!
