### ISSUE TITLE
add kolibri command to change the location of the content folder

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3520]
### Observed behavior

On a number of occasions, we've gotten feedback that folks want the content folder in a different location than the primary Kolibri directory. This often occurs even after a user has imported content, which means that we may need to migrate existing content to the new locations.

### Expected behavior

We should provide a new command to migrate the content directory to a new location. One possibility might be something like:

```bash
kolibri content directory  # displays current directory
kolibri content directory /media/external  # migrates the content to a new directory
```

However any command is fine if it serves the general purpose.

It would be reasonable to place some restrictions on this command if helpful, e.g. that the Kolibri server can't be running or be started while it's running.

This may also require some additional checks during Kolibri startup, since now there would be a chance that Kolibri might start without the content directory being available, or the content directory might become unavailable while Kolibri is running. These cases might require errors to get bubbled up to the end-user on the front-end.

### User-facing consequences

Users are not able to set up their systems and leverage higher-capacity hard drives as desired

**Comment by benjaoming** [comment]
Which are the user scenarios for this?

1. backup purposes
1. seeding a deployment

**Comment by indirectlylit** [comment]
My understanding was that 'moving contents to another disk' is the scenario we've heard requests for.

Would it be useful to follow-up and find specifics?

**Comment by benjaoming** [comment]
@indirectlylit thanks -no I think this clarification is sufficient. Seeding a deployment should probably follow a different pattern, but could perhaps use `kolibri manage content` as a component in that procedure.
