### ISSUE TITLE
update Windows installer to 1.2.0

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3521]
### Observed behavior

There will be upgrades to the Windows installer: https://github.com/learningequality/kolibri-installer-windows/milestone/4

### Expected behavior

Upgrade to 1.1.3

**Comment by benjaoming** [comment]
I was raising a point about keeping Kolibri 0.9.x updated (for future support), but since 1.1.3 will ship Python 3.4.x, just forget what I said :)

I would suggest in line with #56 (the example compatibility table shown) to mark this for history keeping...
