### ISSUE TITLE
FacilityUser has no facility

### ISSUE THREAD

**Issue by djholmes** [learningequality/kolibri#3522]
### Observed behavior
```
observed behaviour is this:-
user form is created but data is not posted and while posting the data below error occurs
RelatedObjectDoesNotExist at /api/registered
FacilityUser has no facility.
```

###Expected behavior
```
expected behavior :-
form data should be posted and should return the post value of user
```

### User-facing consequences
```
not able to submit the data
```

### Errors and logs
```
RelatedObjectDoesNotExist at /api/registered
FacilityUser has no facility
```
…

### Steps to reproduce
```
create your own app in kolibri environment and then create the rest api form through serializers and views and call that url 
```

### Context
```
Kolibri version - 0.10.0.dev+git-20180405000404
operating system - ubuntu 16.04.04
browser - google chrome ad firefox
```

```
code for serializers and views :-
views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from rest_framework.permissions import AllowAny
from rest_framework.generics import CreateAPIView
from django.contrib.auth import get_user_model
from .serializers import UserSerializer

class UserCreateView(CreateAPIView):
    model = get_user_model()
    permission_classes = (AllowAny,)
    serializer_class = UserSerializer

serializer.py
from rest_framework import serializers
from django.contrib.auth import get_user_model


class UserSerializer(serializers.ModelSerializer):
    password = serializers.CharField(min_length=8, write_only=True, )

    def create(self, validated_data):
        user = get_user_model().objects.create(
            username = validated_data['username']
        )
        user.set_password(validated_data['password'])
        user.ave() 
        return user

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')
```

**Comment by indirectlylit** [comment]
Hi @djholmes - 

I would caution that we do not yet have a documented, stable API for supporting third-party apps in Kolibri - though we plan to do this in the future. Therefore things are liable to break in the future if you build and integrate your own app.

I'll re-post the same thing I'd mentioned in #3270:

> **We cannot provide guarantees about the coherence of data if the user interface is bypassed:  there may be implicit constraints enforced by the UI but not encoded in the DB schema. We also make no guarantees about stability of internal APIs, DB schemas, etc.**

With that said, if you're interested in experimenting with this further, these two links might be helpful:

* [Documentation about the user DB models](http://kolibri-dev.readthedocs.io/en/develop/architecture/uap/index.html)
* [Example of a command that populates the DB with data](https://github.com/learningequality/kolibri/blob/develop/kolibri/logger/management/commands/generateuserdata.py)

To your specific question, a `FacilityUser` object (which derives from `AbstractBaseUser`) needs to be associated with a `Facility`. Take a look at `generateuserdata` for examples.

We would also be very interested in learning more about what you're trying to achieve, so we can take it into account when it is time to design the 3rd-party plugin API. Feel free to share here, or reach me directly at devon@learningequality.org to discuss your use-case further.

**Comment by djholmes** [comment]
hi @indirectlylit thanks for your time and answer, few more questions i have please answer if whenever you are free:-
1.  can i create my own plugins in kolibri environment ? 
2. does kolibri use any plugin library or they have created their own ? can you tell the name of plugin library if you used?
it would be grateful if you answer these questions.
Thanks
