### ISSUE TITLE
One group of the class with less students can view all the active lessons/exams in the class.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3530]
### Observed behavior

The lesson and exam active to one group must only be visible to that particular group. In this case while testing in the classroom, one group-Elephant, in the class had 12 students and they can view and solve all the active lessons and exams, while another group- Rest with 48 students is able to see lesson, exam only assigned to them.

### Expected behaviour

Exam, lesson only visible to the group it is assigned to.

### User-facing consequences

Students attempting wrong lesson, exam which the teacher created for other group.

### Steps to reproduce

1. Make 2 groups in the class, one with less students and other with more.
2. Assign different lessons and exams to the groups.
3. Login as student of smaller group and see whether all active the exams, lessons are visible?

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### screenshots
![g2](https://user-images.githubusercontent.com/38091824/38655605-47ba6bfa-3e33-11e8-8c69-40835900c733.png)
![g3](https://user-images.githubusercontent.com/38091824/38655608-47eb4662-3e33-11e8-84d4-0fda715ddade.png)
![g4](https://user-images.githubusercontent.com/38091824/38655609-481a095c-3e33-11e8-9332-9aa32376d540.png)
![g5](https://user-images.githubusercontent.com/38091824/38655611-484a5008-3e33-11e8-95dd-4e71a74508e7.png)
![g6](https://user-images.githubusercontent.com/38091824/38655613-487bacf2-3e33-11e8-85e5-b28311988a7c.png)
![g7](https://user-images.githubusercontent.com/38091824/38655616-48ab8184-3e33-11e8-9ae5-f465d0d998ae.png)
![g8](https://user-images.githubusercontent.com/38091824/38655617-48e30258-3e33-11e8-8f61-351fcc5b8eae.png)
![g9](https://user-images.githubusercontent.com/38091824/38655619-4945444a-3e33-11e8-91f9-d8f7e5a287af.png)
![g10](https://user-images.githubusercontent.com/38091824/38655621-49a48da6-3e33-11e8-94a4-8e2d43f3c5d4.png)
![img_20180411_150105868](https://user-images.githubusercontent.com/38091824/38655914-be639afa-3e34-11e8-9122-c4c10538e824.jpg)
![img_20180411_150428547](https://user-images.githubusercontent.com/38091824/38655915-be98586c-3e34-11e8-93c8-e9241180c7c6.jpg)

**Comment by jonboiser** [comment]
@amit3107 I'm noticing in the first two pictures, that some students are in both "Elephant" and "Rest" groups. For example, I see "Ayesha" (the user in the last tablet photo) as well as "Anjali". Were the first two photos taken at the same time?

If Ayesha is in both "Rest" and "Elephant", would it make sense for Ayesha to see the Lessons and Exams we see in the last photo?

The Kolibri interface wants Coaches to place Learners in only one group in a classroom, but it is not impossible for them to be in multiple groups under special circumstances.

**Comment by amit3107** [comment]
Yes if Ayesha is in both the groups it makes sense for her to see the exams and lessons. But how was the coach able to place them in both the groups or is it allowed by Kolibri?

**Comment by rtibbles** [comment]
Under the hood, it's allowed by Kolibri - but the interface should be preventing it.

**Comment by jonboiser** [comment]
We have had issues in the past with adding/removing large numbers of Memberships (which is how we say a User is in a Group or Classroom). e.g. #2325.

We implemented a safer way to manipulate large numbers of Memberships, but it's possible the issue lingers. Before we implemented this change, I would observe users being in two groups simultaneously, just as in the example here.

**Comment by rtibbles** [comment]
Hrm, does the interface allow this kind of error to be resolved? If a learner is in two groups, given the assumptions the interface makes about learners only being in one group, can this be undone?

**Comment by jonboiser** [comment]
I'm not sure if there's a foolproof way to resolve this on the interface. I think in the past, I would just move my learners around until the duplicate Memberships disappeared and they were in the right place...

**Comment by jonboiser** [comment]
For example, one might try moving "Ayesha in Elephant" to "Rest" and hopefully the end result is Ayesha is only in "Rest"

**Comment by jonboiser** [comment]
Here's one way to get 1 user in two different groups

1. In a class, create 3 groups, A, B, C
1. Place a User in Group A
1. Open a new browser tab for the Groups page ( User should be in group A)
1. In that second tab, move the user from group A to group B
1. In the original tab (don't refresh), move the user from group A to group C
1. User will be in groups B and C

**Comment by indirectlylit** [comment]
It seems to me that the only way to prevent this is to impose a one-group-per-class constraint on the backend
