### ISSUE TITLE
Uneven channel thumbnail view on Learn

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#3539]
### Observed behavior
On Learn in landscape view, the channel thumbnails were uneven.

### Expected behavior
Expect the alignment between the thumbnails to be even.

### User-facing consequences
The user experience is not the most pleasant but no real significant consequences. 

### Errors and logs
n/a

### Steps to reproduce

1. Open Learn in landscape
2. Observe behavior (see photos)

### Context
 * Kolibri version: v0.9
 * Operating system: iOS on iPad mini 1
 * Browser: Chrome 62.0.3202.70
-->
![img_20180413_121436](https://user-images.githubusercontent.com/25990164/38754171-c922d686-3f2e-11e8-8121-791b37374efb.jpg)
![img_20180413_121457](https://user-images.githubusercontent.com/25990164/38754172-c93a53b0-3f2e-11e8-97b1-6abc3de14669.jpg)

**Comment by jonboiser** [comment]
I'm noticing that it's the two cards that have names that take up at least two lines that are not aligned.

"Phet Interactive Simulations (en)" and "Secondary School Gamma"
