### ISSUE TITLE
add more metadata to InteractionHistory of an exercise

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3547]
### Observed behavior

In #3012 it was observed that if an question in an exercise failed to render due to an error, it counted as 'correct' to a learner.

In #3483 we switched the behavior so that an error causes the question to be marked as 'incorrect'.

### Expected behavior

Neither behavior above is optimal, because the learner has either 'correct' or 'incorrect' on their record due to something out of their control (the question having an error).

Instead, we should add more metadata to the `InteractionHistory` of the exercise which allows us to distinguish more about what happened. For example, it could be 'took a hint', 'error' occurred, etc.

See this thread: https://github.com/learningequality/kolibri/pull/3483#discussion_r179900439

### User-facing consequences

learner is penalized for something out of their control

### Context

0.9.x

**Comment by rtibbles** [comment]
Closing as already implemented as stated.
