### ISSUE TITLE
'delete class' modal doesn't respond to 'enter

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3548]
### Observed behavior

pressing 'enter' does not trigger the modal:

![image](https://user-images.githubusercontent.com/2367265/38835883-3ed73148-4181-11e8-9586-690fe54b5acd.png)

### Expected behavior

pressing 'enter' triggers the default action

### User-facing consequences

extra clicks, broken expectations

**Comment by christianmemije** [comment]
Addressed in #3560
