### ISSUE TITLE
handle empty state of coach report item list page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3554]
### Observed behavior

In #3550 we made the 'empty states' of tables more consistent.

We could not update this instance due to string freeze, so we'll do it in 0.10.0

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/reports/item-list-page.vue#L20

### Expected behavior

Same empty-state behavior as other tables

### User-facing consequences

Slight inconsistency

### Context

0.9.1

**Comment by jonboiser** [comment]
#3591
