### ISSUE TITLE
Exit Full Screen on HTML5 app renderer can cover content

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3557]
### Observed behavior
Exit Full Screen button can cover content:
![image](https://user-images.githubusercontent.com/1680573/38926621-3be93fb4-42fb-11e8-8618-354f2eefc501.png)

### Expected behavior
All content should be fully visible.

### User-facing consequences
Can't see all content!

### Steps to reproduce
Open HTML5 app.
View in full screen.

**Comment by christianmemije** [comment]
Fixed in #3924
