### ISSUE TITLE
Successful Log-in results in error

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3558]
### Observed behavior
Occasionally on a successful login, the login redirect will not occur, and instead an error is shown in the console: `Cannot read property type 'code' of undefined`. This appears to be caused by the `catch` behaviour for the login API call being trigged on a successful login.

![image](https://user-images.githubusercontent.com/1680573/38926892-0bb29074-42fc-11e8-9afe-8d4336ce5433.png)

### Expected behavior
Successful login should always trigger the `then` behaviour not the `catch` behaviour.

### User-facing consequences
Confusing experience logging in.

### Errors and logs
`Cannot read property type 'code' of undefined`

### Steps to reproduce
Try to log in.
Sometimes this error will occur.

### Context
Tell us about your environment, including:
 * Kolibri version: 0.9.0 (on demo site)
 * Browser: Chrome

**Comment by rtibbles** [comment]
This seems to be a result of logging in when you are already logged in.

**Comment by rtibbles** [comment]
Having difficulty replicating.

**Comment by jamalex** [comment]
Happened for me after upgrading DEB from 0.7.1 to 0.10.2 -- which autorestarts the server, but possibly in a funny way. The URLs /device and /facility also gave a 404. After restarting the system service, everything worked normally again.

**Comment by jamalex** [comment]
May be fixed in https://github.com/learningequality/kolibri/pull/4118

**Comment by indirectlylit** [comment]
haven't seen this in a while. please re-open if it re-appears
