### ISSUE TITLE
when viewed in an RTL language, language names with parens might display wrong

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3568]
### Observed behavior

Hindi below shows up incorrectly when viewed in an RTL language

![image](https://user-images.githubusercontent.com/2367265/39025474-188df792-43fc-11e8-9adb-9e2409768924.png)

![image](https://user-images.githubusercontent.com/2367265/39025471-109728ce-43fc-11e8-8dc4-1036ed4ed4a3.png)

### Expected behavior

Every language name should display correctly. Might need to add a `dir` language attribute to each row based on the language item?

### User-facing consequences

minor confusion

### Context

0.9

**Comment by jonboiser** [comment]
This happens in other places too, like the channels list in device management page:

![screen shot 2018-04-23 at 10 14 21 am](https://user-images.githubusercontent.com/10248067/39142300-20dc48f0-46df-11e8-8ec7-c65a40e43826.png)

**Comment by rtibbles** [comment]
Probably best to add `dir="auto"` to these places.
