### ISSUE TITLE
Import export wizard flickering

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3572]
### Observed behavior
Weird flickering of top nav from behind the import export wizard during channel import.

![flickering](https://user-images.githubusercontent.com/1680573/39055125-4ce40bda-44ab-11e8-8866-6eb8580e73e7.gif)

### Expected behavior
No flickering!

### User-facing consequences
We might need to add a seizure warning?

### Steps to reproduce
Select a channel to import, watch metadata load.

### Context
 * Kolibri version: Develop
 * Operating system: Ubuntu
 * Browser: Chrome

**Comment by jonboiser** [comment]
I've never seen this before, and the part of the page that's flickering seems kind of arbitrary (about 300 px from top of page, maybe).

The flickering is most likely do to the status-bar being re-rendered when new Tasks come down the wire.

Perhaps there is something to prevent updates like React's should-update hook? We will only re-render when there is a change.

**Comment by indirectlylit** [comment]
haven't seen this in a while. please re-open with steps to repro if it's still extant
