### ISSUE TITLE
Device tab not opening.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3579]
### Observed behavior

The device tab is not opening. The Kolibri bird wait option is being displayed for a long time. (>5 minutes). It does not open even after refreshing.

### Expected behaviour

The device tab and various features must be accessible.

### User-facing consequences

Admin won't be able to access device features like channel download etc.

### Steps to reproduce

1. Login as admin.
2. Try to open Device.

Kolibri version : kolibri 0.9.1
Operating system : ubuntu 14.04
Browser : Chrome

### screenshots
![q1](https://user-images.githubusercontent.com/38091824/39130400-9c615326-472a-11e8-8656-2817b147d5fe.png)

**Comment by rtibbles** [comment]
Should be fixed in #3583

**Comment by swapnil106111** [comment]
@rtibbles Tested this issue on Kolibri 0.9.2. Still it requires time to load the device tab. We have upto 1.5GB size content in our Kolibri Server.

**Comment by indirectlylit** [comment]
thanks @swapnil106111 - created a new issue to continue to track performance of the device tab
