### ISSUE TITLE
Incorrect username is displayed when the admin username is written in opposite cases like PM instead of pm.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3580]
### Observed behavior
When PM (Admin account) is entered as the username, an error message of incorrect username or password is displayed. After entering the password the PM (admin) can sign-in that means sign-in is not an issue.

### Expected behavior

The username is not case-sensitive. The error message must not be displayed.

### User-facing consequences
The user can think he/she has added the wrong the username.

### Steps to reproduce

1. Login as a user who is given an admin role.
2. Add username in different case. (PM or pm)
3. Error message is displayed.

### Context

Kolibri version : kolibri 0.9.1
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![o1](https://user-images.githubusercontent.com/38091824/39132602-d6f64348-472f-11e8-83cb-e61133984f3a.png)

**Comment by rtibbles** [comment]
Hi @amit3107 - I am unable to replicate this error. The only behaviour similar that I can find, is when the simplified login facility setting is activated, entering a non-learner username or password prompts this. It has nothing to do with the case insensitivity, entering 'pm' would prompt exactly the same error message.

What is perhaps undesirable in this instance is the large 'Incorrect username or password' above, which distracts from the warning that a password is required for non-learners below. However, the issue, as described does not match up to the observed problem.

**Comment by rtibbles** [comment]
Created a new issue describing the problematic behaviour here: #3582

**Comment by amit3107** [comment]
Hi @rtibbles - On entering 'pm' there is no error message (it only asks for password) but on entering 'PM' there is an error message of incorrect username or password and then after entering the password the user is allowed to sign-in.
This error is based on case-insensitivity for the non-learner account.

**Comment by rtibbles** [comment]
Thanks for the follow up!

**Comment by swapnil106111** [comment]
@rtibbles Tested in Kolibri 0.9.2. Working as expected.
![1](https://user-images.githubusercontent.com/12776071/40221285-a76ac3ce-5a99-11e8-949c-ff0b17cfd282.png)
