### ISSUE TITLE
Set page title metadata inside the components instead of indirectly through action

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3606]
Currently, we use the `CORE_SET_TITLE` mutation to manually change the browser tab title whenever the app intends to switch to a new top-level component (via `SET_PAGE_NAME`). At least once, this has lead to a situation where the title does not update, since the relevant line was missing from the switching action.

Instead, we could let the actual top-level component determine the browser tab title, using something like [vue-meta](https://github.com/declandewet/vue-meta) (inspired by react-helmet, apparently).

Using this particular library, in the component, add a `metaInfo` option:

```
metaInfo() {
  return {
    title: this.$tr('pageTitle'),
  };
}
```

**Comment by indirectlylit** [comment]
This sounds like a good idea to me, in part to help keep the `$tr` strings in vue files.

The main things I can think to be careful of are precedence and timing issues. For example:

* navigate to a top-level page with some title
* switch just out a sub-component of that page, which might set it's own more specific title
* go back to the original sub-component

I don't know if we actually have anywhere like that in the code, but I'm guessing we might?
