### ISSUE TITLE
import coach icon sizing inconsistency

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3610]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/39608181-89163ba2-4ef4-11e8-89ec-06eb824bd86d.png)

### Expected behavior

The type and coach icons should be consistently sized

### User-facing consequences

Things look a little wonky, and the more important info (type) is less visually dominant than the coach (both larger _and_ blue)

### Context

k 0.10.0

----

cc @jonboiser

**Comment by khangmach** [comment]
Can we also remove the indent between the checkbox and the content type icon?

**Comment by jonboiser** [comment]
Should be fixed in #3632
