### ISSUE TITLE
Simplify coach indicator icon for leaf ContentNodes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3611]
### Observed behavior

coach text and icon very large

![image](https://user-images.githubusercontent.com/2367265/39608321-8581bb0a-4ef5-11e8-8e43-8d5bf9dced66.png)

### Expected behavior

recommend:

* make the icon 16x16 or 12x12
* remove the 'Coach' text
* add a 'Coach' tooltip, similar to the content type icon

### User-facing consequences

cards look a little janky

### Context

k 0.10.0

-----

cc @khangmach @jonboiser @christianmemije

**Comment by khangmach** [comment]
the suggestions look great. The coach icon also looks good at 16x16. @jonboiser one of the changes Devon and I talked about last week was the removal of the "Coach" label that is next to the coach content icon and instead adding a tooltip when hovering over the icon. I don' think the text is too important to have, especially with the tooltip potentially involved.

**Comment by khangmach** [comment]
the elimination of the accompanying word "Coach" && the addition of tooltip "Coach content" will happen everywhere.

So also in:
Learn search results
Learn content cards throughout
Exercise pages
Coach recent/channels tab/learners tab
Cards in the lesson creation tool
Lists in the exam creation tool
