### ISSUE TITLE
exam preview nested scrolling issues

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3613]
### Observed behavior

nested scrollbars in the modal can sometimes make certain parts of the UI hard-to-access. I've seen some situations where parts of the UI are completely hidden, and it's not at all clear how to access them.

![scroll](https://user-images.githubusercontent.com/2367265/39608964-0ff7f552-4efa-11e8-837e-da9dc5bfdc20.gif)

see related issue: #3279

### Expected behavior

There should not be any nested scrollbars.

### User-facing consequences

Some parts of the UI are hard-to-access on smaller screens

### Steps to reproduce

* create an exam
* add a  bunch of questions
* randomize until you have a larger question
* play around with scrolling

### Context

0.10.0

----

cc @khangmach

**Comment by indirectlylit** [comment]
actually I think the original design should work here, and this is an implementation bug

**Comment by christianmemije** [comment]
Fixed in #3953

**Comment by indirectlylit** [comment]
nice
