### ISSUE TITLE
Kolibri Not Working Properly without the internet

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3620]
### Observed behavior
![kolibri-problem](https://user-images.githubusercontent.com/1372447/39672157-77792bc4-5157-11e8-8ae2-c2fbdbb57327.png)

There is an image missing in the above Khan Academy screenshot.

[kolibri-console.txt](https://github.com/learningequality/kolibri/files/1977517/kolibri-console.txt)

The browser console showed Kolibri was attempting to pull some resources from the internet.
…

### Expected behavior
Kolibri should work offline

### User-facing consequences
"Random" issues showing up during student lessons.

### Errors and logs
see attached log above

### Steps to reproduce
http://127.0.0.1:8087/learn/#/topics/c/572fab3eccfb50d0b4cfa2f95a2c3918
bread crumbs
Khan Academy (English)
Math
Early math
Counting
Numbers 0 to 120 
Numbers to 100

Use a PC, clear the browser cache, access the server without internet connection.

### Context
Browser; Vivaldi and Firefox

Kolibri version | 0.9.1

http://192.168.1.100:8087/

/opt/kolibri/db.sqlite3

Linux-4.14.36-1-MANJARO-x86_64-with-arch-Manjaro-Linux
2 GB

-->

…

**Comment by jonboiser** [comment]
Was able to produce. Here are the resources that are not available when offline:

![screen shot 2018-05-08 at 12 08 37 pm](https://user-images.githubusercontent.com/10248067/39777551-b06510e4-52b8-11e8-8485-25b429703a02.png)

**Comment by benjaoming** [comment]
This is the reason for: https://github.com/learningequality/kolibri/issues/877

**Comment by benjaoming** [comment]
@ralphiee22 while you are troubleshooting this, could you check if CSP middleware (NB! debugging ONLY) can be useful to spot such?

**Comment by nobicycle** [comment]
Another example.

Resources:
http://ka-perseus-graphie.s3.amazonaws.com/89bf5860fc0d42994c875e18dddf4f8cdc96d219-data.json

[kolibri-console.txt](https://github.com/learningequality/kolibri/files/2012079/kolibri-console.txt)
![kolibri-console2](https://user-images.githubusercontent.com/1372447/40162954-15cfc290-59e8-11e8-8796-e65ead2e3487.jpg)

**Comment by ralphiee22** [comment]
Hey @nobicycle, this issue should be fixed. 
Can you please test and verify the issue has been resolved.

**Comment by nobicycle** [comment]
I got a mailing list message:
_Can you please test and verify the issue has been resolved._
To update, can I use pip  or do I have to pull kolibri's git repo?

**Comment by ralphiee22** [comment]
Apologies, you only have to update the KA English channel on your kolibri instance. It should only update the necessary files to have the issue fixed.

**Comment by nobicycle** [comment]
Unless I am getting dementia, those two examples above have disappeared from KA V10 - so I can't test them.
Actually, I can't reproduce either of  those breadcrumb paths above. 
Math|Early math|Counting|Numbers 0 to 120 only contains videos - no exercises. Is this a bug?

If anyone else is able to find the paths then perhaps the explanation is an incomplete download. My update to KA V10 got to 99.8% and then hung, apparently due to internet outage. But on restart, Kolibri said I was at V10.

**Comment by ralphiee22** [comment]
Hello @nobicycle, apologies on the super late reply. We wanted to ensure that all issues related to content were fixed before moving forward on this issue. What I recommend is deleting the channel and then re import it. This doesn't actually delete files in `content/storage` so you won't have to re-download all the content. It will just download any new content you don't already have.

**Comment by ralphiee22** [comment]
Disregard my last comment. It WILL delete the content.

**Comment by ralphiee22** [comment]
We are planning to release kolibri 0.10 this week. What I will advise is to wait until we release, where you can then update kolibri. And then to update the KA channel from V10 to V11. 
I will post here once we release kolibri v0.10.

**Comment by nobicycle** [comment]
Understood and thanks

**Comment by nobicycle** [comment]
Hi. I noticed v0.10 was out and did a clean install, deleting the old kolibri directory.
I selected Khan Academy for import. "Generating channel listing. This could take a few minutes…" took so long I looked in the logs, attached. Seems like there are various issues.
[server.log](https://github.com/learningequality/kolibri/files/2161816/server.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/2161817/kolibri.log)

I opened a new issue:
https://github.com/learningequality/kolibri/issues/3963
Version 0.10 Server SSL Errors

**Comment by indirectlylit** [comment]
thanks for the heads-up!

**Comment by indirectlylit** [comment]
I believe the original issue (errors ) has been addressed. Please re-open if that's not the case.
