### ISSUE TITLE
Issue 3343  closed prematurely.

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3621]
Sorry to  raise an issue about an issue, but  https://github.com/learningequality/kolibri/issues/3343
 never got resolved, but was closed.  Maybe my email never got through. I'll send again

> 
> To: richard@learningequality.org
> Subject: Github issue  https://github.com/learningequality/kolibri/issues/3343
> Date: Sun, 18 Mar 2018 09:52:01 +0800
> X-Mailer: Claws Mail 3.16.0 (GTK+ 2.24.32; x86_64-pc-linux-gnu)
> 
> Hello Richard
> 
> In this issue:
> https://github.com/learningequality/kolibri/issues/3343
> 
> rtibbles commented:
> 
> "Note that I slightly misspoke above, if you have the new files you can
> add them to video files in your own custom channel through Kolibri
> Studio. If you are interested in this let me know, and one of our team
> can give you access via email."
> 
> Much obliged for your help to setup extra languages. 

> Thanks

**Comment by rtibbles** [comment]
Sorry, following up on your email shortly!
