### ISSUE TITLE
Learner full_name undefined.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3622]
### Observed behavior
I'm having `'full_name' of undefined` error at learner page. 

### Expected behavior
We should handle or catch the `user` object if it's undefined to prevent the page crash.

### Errors and logs
![screen shot 2018-05-07 at 11 47 37 am](https://user-images.githubusercontent.com/8663934/39684176-80bec488-51ec-11e8-978b-5caeef1268a9.png)

### Steps to reproduce
- Log in as coach or admin.
- Navigate at the learner profile.

### Context

Tell us about your environment, including:
 * Kolibri version: Kolibri 0.10.0.dev1.dev+git-98-gac76f36
 * Operating system: macOS 10.13.3
 * Browser: Chrome version 66.0.3359.139 (Official Build) (64-bit)

**Comment by rtibbles** [comment]
@mrpau-richard I think the issue was not our failing to handle it, but rather that the user data was being passed into the wrong variable (an additional promise had been added to the promises array that was being resolved).

See my PR above for the minimal fix.
