### ISSUE TITLE
User deletion management command with a local installation

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#3627]
To support implementing partners in any user data deletion requests, we want to provide an easy way for admins to delete a given user's data. The first pass in here is a management command `deleteuserlocaldata`, that admins can run in the command line. Running said management command with the user id will delete the user's data.

Assigned it to .11 for now, as it's not urgent, and device admins can be supported manually through the process.

**Comment by indirectlylit** [comment]
addressing this under #4303 (cc @ralphiee22)
