### ISSUE TITLE
Clicking "add resources" in lessons doesn't bring the page view to the top

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#3629]
### Observed behavior

After I create a new lesson, I click on "Add resources" which directs me to the middle of the resource selection screen. 

### Expected behavior
I should be directed to the top of the screen in order to be introduced to the context of the page. 

### User-facing consequences
Confusion over what the user just landed on. This isn't an issue on large screens, but while conducting local usability testing with small screen resolutions and browser windows, users were confused as to what they just landed on after pressing "add resources" 

### Steps to reproduce
Nav to coach lessons
Create a new lesson
Reduce the height of browser window (to maybe 500-600px)
Click on "add resources

![pageview bug](https://user-images.githubusercontent.com/25045166/39772013-ea448228-52a8-11e8-971d-eebbc6a7e110.gif)

### Context
 * Kolibri version: Kolibri demo
 * Operating system: MacOS
 * Browser: Chrome

**Comment by jonboiser** [comment]
This probably happens in a lot of places, since I don't think we manually set the scroll behavior to go back to the top, when we go from link to link.
