### ISSUE TITLE
PDFs go blank in fullscreen mode when using the 'escape' key

### ISSUE THREAD

**Issue by micahscopes** [learningequality/kolibri#3644]
### Observed behavior
I used the escape key to get out of the full screen PDF view.  When I made the PDF full screen again, it was blank.  I repeated this over and over again and found that exactly half of the time, the PDF was missing.  When I used the button to get out of full screen, the PDF showed every time.

Here's a video:
[Screencast from 05-10-2018 05:14:58 PM.zip](https://github.com/learningequality/kolibri/files/1993415/Screencast.from.05-10-2018.05.14.58.PM.zip)

### Expected behavior
I expected the PDF to show consistently when moving in and out of fullscreen mode.

### User-facing consequences
Learners would not see their homework.  They could then use that as an excuse to not finish their homework.  They could say "I clicked my homework but I couldn't see it!"  That's a dire consequence.

### Errors and logs
There was nothing relevant in the console.

### Steps to reproduce
1. Login to Kolibri.  I was logged in as a coach.
2. Go to 'Learn' mode and find some PDF content in one of the channels.
3. Click the fullscreen icon
4. Press `escape` on the keyboard
5. Click the fullscreen icon again
6. If you discovered the bug, then at this point the PDF will not show.
7+ Repeat this many times.  You will find that every second time, the PDF doesn't show.

### Context
 - Kolibri version: *Kolibri 0.10.0.dev.3*
 - Operating system: *Arch Linux*
 - Browser: *66.0.3359.139 (Official Build) Arch Linux (64-bit)*

**Comment by micahscopes** [comment]
A clue: when you exit full screen mode by clicking the button, the PDF displays consistently.  It's only when exiting with the 'escape' key that this happens.

Is there something additional happening on that button click that isn't happening when using the escape key?

**Comment by indirectlylit** [comment]
cc @christianmemije
