### ISSUE TITLE
recommended page doesn't handle duplicate items

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3645]
### Observed behavior

It's possible for duplicate items top appear. For example, below the last section has "How to Make Beurre Noisette" two times:

![image](https://user-images.githubusercontent.com/2367265/39901168-a1e0c8fa-547b-11e8-8227-f1902faaee2c.png)

This throws a 'duplicate key' error

### Expected behavior

The carousel 

### User-facing consequences

None

### Errors and logs

```
vue.runtime.esm.js:587 [Vue warn]: Duplicate keys detected: '3e464ee12f6a50a781cddf59147b48b1'. This may cause an update error.

found in

---> <RecommendedPage> at kolibri/plugins/learn/assets/src/views/recommended-page.vue
       <AppBody> at kolibri/core/assets/src/views/app-body.vue
         <CoreBase> at kolibri/core/assets/src/views/core-base.vue
           <Root>
```

### Steps to reproduce

…

### Context

0.9.0

**Comment by rtibbles** [comment]
I think we can close this as this is only happening in the 'featured in' section which has been removed.
