### ISSUE TITLE
possible for duplicate items to show up in 'recommended'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3646]
### Observed behavior

It's possible for duplicate items top appear in a single section. For example, below the last section has "How to Make Beurre Noisette" two times:

![image](https://user-images.githubusercontent.com/2367265/39901271-49e1ebd8-547c-11e8-939c-e8fc18a00648.png)

### Expected behavior

Each section should be de-duplicated

### User-facing consequences

confusion

### Errors and logs

see https://github.com/learningequality/kolibri/issues/3645 for an error 

### Steps to reproduce

…

### Context

0.9.0

**Comment by indirectlylit** [comment]
filed a separate issue to prevent duplicates from happening in this case: https://github.com/learningequality/kolibri/issues/3645

**Comment by indirectlylit** [comment]
@ralphiee22  mind taking a look at this?

**Comment by indirectlylit** [comment]
@ralphiee22 this may have been addressed?

**Comment by ralphiee22** [comment]
#3884 I believe it has been addressed here.
