### ISSUE TITLE
Lesson description field not aligned 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3649]
### Observed behavior
 New lesson description field not aligned on its bottom underline.

### Errors and logs
![screen shot 2018-05-11 at 1 15 04 pm](https://user-images.githubusercontent.com/8663934/39907814-99a86560-551d-11e8-87c6-22671ff637f4.png)

### Context

 * Kolibri version: Kolibri 0.10.0.dev3.dev+git-2-g44af734
 * Operating system: macOS High sierra 10.13.3
 * Browser: Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by jonboiser** [comment]
This is how multi-line `textarea`s are supposed to work. This allows the user to write descriptions that might be paragraph-style and span multiple lines.

**Comment by mrpau-richard** [comment]
Okay @jonboiser, Closing this.
