### ISSUE TITLE
Upgrade Node 6.x => 8.x (LTS)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3653]
### Observed behavior

The more recent Node 8 is an LTS and comes in the official Ubuntu 18.04 repos, just `apt install nodejs`.

> Note that the LTS lifespan for 8.x will end on December 31st, 2019.

### Expected behavior

Let's stay on par with an LTS

### User-facing consequences

None!

Original 8.0.0 changelog:

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#2017-05-30-version-800-current-jasnell

**Comment by indirectlylit** [comment]
I don't recall what issue we had with 8.x but it's worth a try!  (refs #2054)

**Comment by rtibbles** [comment]
Note that 6.x is also an LTS (https://github.com/nodejs/Release#release-schedule) maybe we should just leapfrog to 10.x in October?

**Comment by benjaoming** [comment]
@rtibbles leapfrogging might be a big mouthful, I mean perhaps more bite-sized to do one LTS at a time? :)

But as I mentioned, Node 8 is also in Ubuntu 18.04 official repos, which is really really nice for quickly getting started.

I was also curious about the very substantial changelog for Node 8...

:+1:  @indirectlylit it's worth a try... IIRC, we made the last Node upgrade without issues. We did the same for KA Lite.

**Comment by indirectlylit** [comment]
All I remember is that there was a specific reason we did _not_ allow 8.x (it caused issues in some cases)

**Comment by indirectlylit** [comment]
also for anyone finding this issue later: you can [use `nvm` to manage multiple node versions](https://github.com/creationix/nvm)

**Comment by jonboiser** [comment]
with node 8, we could use async functions in the test suite.

**Comment by rtibbles** [comment]
Well, we currently run the frontend tests in Chrome Headless, so we should already be able to use async functions, no?

**Comment by jonboiser** [comment]
Actually, I'm not sure anymore, since the tests files are compiled via webpack (hence buble) before sent to the browser.

I tried rewriting one of the tests with an async function and got a webpack error to that effect.

**Comment by rtibbles** [comment]
Ah, yeah - so we can't use it because buble can't transpile async, I think, so even though the browser would support it, our transpiler doesn't.

We can add:
```
transforms: {
  generator: false
}
```
to the buble config just for tests, and it seems like that might stop it from failing at least? https://gitlab.com/Rich-Harris/buble/issues/71

**Comment by rtibbles** [comment]
We can track potential integration of async into buble here too: https://github.com/Rich-Harris/buble/pull/125
