### ISSUE TITLE
make 'import by token' functionality more discoverable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3654]
### Observed behavior

Multiple instances of users reporting that the 'import by token' functionality is hard to find:

* https://github.com/learningequality/clearinghouse/issues/94
* https://github.com/learningequality/clearinghouse/issues/144
* https://github.com/learningequality/clearinghouse/issues/150

### Expected behavior

One possible solution, but suggestions welcome:

| action | mockup |
|--|--|
| Search | ![image](https://user-images.githubusercontent.com/2367265/40013701-26b7ce0e-5763-11e8-978c-055673a41f35.png) |
| Detect search for token | ![image](https://user-images.githubusercontent.com/2367265/40014508-9e12db72-5765-11e8-86ac-c78e23399762.png) |
| Direct to import |  ![image](https://user-images.githubusercontent.com/2367265/40015416-2730f392-5768-11e8-8ebd-4faaa433dfa2.png) |

### User-facing consequences

Users don't know how to import unlisted channels

### Context

0.9.x

-----

cc @khangmach @jonboiser

**Comment by khangmach** [comment]
this is a really nice improvement to tack onto the search feature here.

**Comment by khangmach** [comment]
Here's the same solution posted in issue #94
![screen shot 2018-05-14 at 11 34 40 am](https://user-images.githubusercontent.com/25045166/40025240-ce4c1eaa-5785-11e8-8d75-07375b4399e6.png)

**Comment by jamalex** [comment]
Note that this picture shows the link at the top of the content page, not the import page ^^

**Comment by khangmach** [comment]
omg my bad

**Comment by khangmach** [comment]
<img width="982" alt="screen shot 2018-05-14 at 4 10 19 pm" src="https://user-images.githubusercontent.com/25045166/40027773-629d149c-5790-11e8-868f-98aacf394826.png">

**Comment by christianmemije** [comment]
Fixed in #3717
