### ISSUE TITLE
scroll position/state is not saved when navigating

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3659]
### Observed behavior

scroll state is not saved when browsing back/forward using vue router

As [noted](https://github.com/learningequality/kolibri/pull/3636#issuecomment-388961868) by @jonboiser:

> `savedPosition` is always `{x:0, y:0}` when using back/forward button. This might have something to do with our unique usage of vue-router. Maybe if we used `router-view`, `savedPosition` would be correct

### Expected behavior

Scroll state should be preserved.

### User-facing consequences

extra scrolling and lost context

### Steps to reproduce

* going to Learn
* scrolling down on 'recommended'
* clicking something
* clicking back

I would expect it to take me to the scrolled-down location, but it goes to the top of recommended

### Context

kolibri 0.9.0

**Comment by indirectlylit** [comment]
might need to manually set `savedPosition` with our own scroll event handler?

**Comment by indirectlylit** [comment]
aspirationally putting this in 0.12 because it has a major impact on UX in reports

**Comment by ralphiee22** [comment]
It appears to be these lines causing the issue 
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreBase/index.vue#L362-L363
`window.pageXOffset` & `window.pageYOffset` are set to `0`, when using the overflow property.

**Comment by jonboiser** [comment]
I'm still seeing this in local development in various Coach Pages (screen capture is going from Coach list of classes to a home page, then back).

![scroll position](https://user-images.githubusercontent.com/10248067/56761552-7934e680-6752-11e9-8165-91965b0b4a23.gif)

**Comment by rtibbles** [comment]
I think this has now been resolved by #5426 and subsequent work.
