### ISSUE TITLE
add relevance-sorted search results

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3663]
### Observed behavior

In #3599 we greatly simplified search behaviors, and tried to make things a bit more predictable for end-users.

However, one of the consequences is that don't do any kind of ranking, and so less relevant results might get displayed instead of more-relevant results. 

### Expected behavior

relevance-ranked results

For some discussion, see https://github.com/learningequality/kolibri/pull/3599#issuecomment-385132331

### User-facing consequences

important results might be obscured

### Context

0.10.0

**Comment by rtibbles** [comment]
One important dimension of relevance: current language.
