### ISSUE TITLE
Use immersive page in content-page within Learn

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3664]
### Observed behavior

Not using immersive page in content-page within Learn

### Expected behavior

Use immersive page in content-page within Learn

### User-facing consequences

Not the best use of space.

**Comment by jonboiser** [comment]
Does this mean that when you are viewing an item in the Learn page, it looks similar to the Preview page when adding lesson resources?

If so, what should the label be for the "<-" back link?

**Comment by rtibbles** [comment]
I think more that the regular content viewing experience in Learn should be the same as the Lesson content viewing experience, which does use the immersive page, right?

**Comment by jonboiser** [comment]
Yeah, the Learn lesson resource view is almost visually the same as the lesson resource selection preview, but the "<-" back label is actually the name of the resource.

**Comment by jonboiser** [comment]
Another difference, too, is that content on the Learn page has breadcrumbs above the content title header.

**Comment by indirectlylit** [comment]
I believe @khangmach was interested in getting rid of the breadcrumbs on content pages

**Comment by khangmach** [comment]
Yes I outlined some ideas here: https://github.com/learningequality/kolibri/issues/4706
