### ISSUE TITLE
pressing 'enter' doesn't submit 'new lesson' modal from description field

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3668]
### Observed behavior

When creating a new lesson, pressing 'enter' adds a new line instead of submitting:

![image](https://user-images.githubusercontent.com/2367265/40089068-bdffcfa4-585e-11e8-89f4-f287ef048b68.png)

However, new lines are ignored anyway:

![image](https://user-images.githubusercontent.com/2367265/40088978-60535556-585e-11e8-8dcb-6fd90d1b14d8.png)

### Expected behavior

'Description' field should ignore 'Enter' keypress and allow the modal to handle it

### User-facing consequences

* more button presses necessary to create a new lesson using the keyboard
* unexpected behavior because newlines are allowed on input and ignored on output

### Steps to reproduce

Create a new lesson with newlines in the description

### Context

k0.9.0

**Comment by christianmemije** [comment]
There are 2 options.
1. Use a text area.
  * Pros:    
    * People want long descriptions? 
  * Cons: 
    * Enter would not submit the form since we do not want to prevent a textarea's default behavior or inserting a newline on enter.
    * We would have to display newlines in the lesson details page which might result in inconsistent layouts between lessons.

2. Use a textbox
  * Cons: People want long descriptions?

**Comment by indirectlylit** [comment]
Can we should use the existing text area but prevent the default behavior of inserting newlines on enter?

**Comment by christianmemije** [comment]
I'd say no because it goes against a basic textarea convention.

**Comment by indirectlylit** [comment]
I'm not entirely convinced end-users would notice or care...

here's [some discussion](https://stackoverflow.com/questions/5286663/wrapping-text-inside-input-type-text-element-html-css) on the idea of a textbox with line wrapping, though granted it doesn't touch on the UX aspects - just the technical

**Comment by christianmemije** [comment]
> I'm not entirely convinced end-users would notice or care...

If they are used to using textareas in forms/text messaging, then they might accidentally submit before they intended.

**Comment by indirectlylit** [comment]
That's certainly true. In this cases the consequences are not super high - they can easily re-edit.

Assuming we don't use a textarea with blocked newlines, seems like we need to go with regular textbox? Otherwise we need to start worrying about displaying the newlines.

**Comment by christianmemije** [comment]
A regular text input seems reasonable.
