### ISSUE TITLE
Card display is buggy on Safari

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3681]
<img width="1490" alt="screen shot 2018-05-17 at 3 12 23 pm" src="https://user-images.githubusercontent.com/6668144/40206486-1d72d1e8-59e5-11e8-9516-a039d8da833c.png">

### Steps to reproduce

CASE 1
Open Safari
Search something on http://kolibribeta.learningequality.org/user/
Cards in search results should not be aligned.

CASE 2
Open Safari
Navigate to Channels tab
Click through topic cards
Display should sometimes be buggy

### Context
 * Kolibri 0.10.0.dev3
 * MacOS Sierra
 * Safari

@christianmemije

**Comment by jonboiser** [comment]
Looks like this issue https://github.com/learningequality/kolibri/issues/3539

Where we note that it's the cards with titles spanning more than one line.

**Comment by christianmemije** [comment]
I tweaked the card sizing logic in https://github.com/learningequality/kolibri/pull/3687. So let's check if this issue still exists after that PR gets merged in.
