### ISSUE TITLE
add multi-language stop-word de-prioritization to search

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3682]
### Observed behavior

searches such as "what is an LED" can produce unhelpful results because of the commonality of some words in the phrase

### Expected behavior

common [stop words](https://en.wikipedia.org/wiki/Stop_words) should be filtered out of our searches. see for example https://github.com/6/stopwords-json

### User-facing consequences

see some [results of testing search queries](https://docs.google.com/document/d/1zIGjlNyiXbJW4cABtakkqZkdjejGV-KRIc5XgwiDy2w/edit)

### Context

0.9

**Comment by indirectlylit** [comment]
open question: filter by all languages, or adjust based on current UI language?

cc @rtibbles

**Comment by ralphiee22** [comment]
Could we do, say UI language and english? I just imagine that english content would be prevalent in several use cases. Again, I could be wrong in this assumption.

**Comment by kollivier** [comment]
I'd say restrict results to the current UI language, as I think that will be the common case, but maybe at some point add an advanced search that lets you set the language.

**Comment by indirectlylit** [comment]
As a first pass, it might be easier and nearly as effective to just filter by all words, all the time.

My guess from a quick look at the [full list](https://raw.githubusercontent.com/6/stopwords-json/master/stopwords-all.json) is that the negative consequences would be very small

(Performance is the primary concern. Could [build up a trie](https://en.wikipedia.org/wiki/Trie) for lookups)

**Comment by rtibbles** [comment]
From a cursory analysis, there is a lot of overlap between the stop words of different languages.

**Comment by indirectlylit** [comment]
Looking at [just the English](https://raw.githubusercontent.com/6/stopwords-json/master/dist/en.json), it's too aggressive to filter them out completely.

Some examples:

* `example`
* `greetings`
* `second`
*  `x`, `y`, and `z`

Instead, we can split the query up into `all_words`, `critical_words`, and `stop_words`. Then the ranked queries might look something like:

1. exact match in title
2. all words in title
3. all critical words in title
4. exact match in description
5. all words in description
6. all critical words in description
7. any critical word in title, reverse-sorted by word length
8. any critical word in description, reverse-sorted by word length
9. any stop word in title, reverse-sorted by word length
