### ISSUE TITLE
channel filter has all items disabled when it shoudn't

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3685]
### Observed behavior

reported by @jonboiser 

![image](https://user-images.githubusercontent.com/2367265/40209917-ff223910-59f6-11e8-90e2-18b9d61fcbcd.png)

might be addressed by recent changes by @christianmemije 

### Expected behavior

all filter items should be enabled

### User-facing consequences

can't filter

### Steps to reproduce

…

### Context

…

**Comment by christianmemije** [comment]
Actually if you zoom in, you can tell there is another channel below the dropdown fold. You just can't see the dropdown's scrollbar. Anyhow, in #3687, we will no longer display disabled options.
