### ISSUE TITLE
Not showing whole error message

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3690]
### Observed behavior
When we edit existing user with existing username, it is showing only 'A' message.
Refer attached screenshot for more information.

### Expected behavior
It must show user already exist.

### Steps to reproduce
1. login with admin account.
2. Click on facility.
3. Click on user tab.
4. click on manage tab of any user and try to change username with existing username. It will show you this message.

### Context

 * Kolibri version : Kolibri 0.9.2
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/40227587-89294c4c-5aac-11e8-88ae-61122164011c.png)

**Comment by mrpau-julius** [comment]
This error message is not reproduce in latest version Kolibri 0.10.0a1.

## Screenshot
![screen shot 2018-05-28 at 3 25 29 pm](https://user-images.githubusercontent.com/38421180/40602571-a5424a46-628b-11e8-8b13-f12feba65658.png)

**Comment by indirectlylit** [comment]
@mrpau-julius would you mind seeing if you can reproduce using 0.9.2?
