### ISSUE TITLE
Learner password is not masked in profile

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3691]
### Observed behavior
When learner wants to change the password, he/she is seeing the newly typed password.

### Expected behavior
It must hide the password.

### Steps to reproduce
1. Login with Learner.
2. Click on Profile.
3. Click on Change password.
4. Try to change the password.

### Context

 * Kolibri version :  Kolibri 0.9.2
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/40233051-01a80ca0-5abf-11e8-87f3-d0d8983de4b6.png)

**Comment by indirectlylit** [comment]
@christianmemije mind addressing this on the 0.9.x branch?

**Comment by christianmemije** [comment]
Fixed in #3719
