### ISSUE TITLE
Lost Channel Listings #3679 Not Fixed.

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#3696]
Hi, please delete this after reading.
3679 is not fixed on 0.9.2
I just tested - I had 3 channels with some content.
I downloaded listings for about 10 other channels.
Then logged off and restarted Kolibri.
On returning to Kolibri, I tested 3 of the newly generated channels - all of then started generating listings again.

**Comment by indirectlylit** [comment]
re-opened #3679
