### ISSUE TITLE
Content marked as visible to coaches is still visible to learners. 

### ISSUE THREAD

**Issue by JasonTame** [learningequality/kolibri#3697]
### Observed behavior
The lessons in this screenshot should only be visible to coaches and administrators:

![coach_only_lessons](https://user-images.githubusercontent.com/15672948/40306931-d6f4e106-5d00-11e8-9f59-42e27fb81149.png)

They are still visible and accessible when logged in as a learner:

![viewing_lessons_as_learner](https://user-images.githubusercontent.com/15672948/40307009-25e6835a-5d01-11e8-8c87-5931d23acafb.png)

### Expected behaviour
Learners should not be able to view content marked as visible to coaches. 

### User-facing consequences
Resources which are only meant to be viewed by coaches or administrators are visible to everyone.

### Steps to reproduce

1. Add some content in the Kolibri content studio
2. Mark content as visible to coaches
![set_visible_to_coaches](https://user-images.githubusercontent.com/15672948/40307157-a1e462b0-5d01-11e8-8d6e-429fa5355021.png)
3. Publish content
4. Import into Kolibri
5. Log on as a learner
6. Observe that learner can view content 

### Context
Kolibri version: 0.9.2
OS: Ubuntu 16.0.4

**Comment by jonboiser** [comment]
@JasonTame This feature should be available in the next release 0.10.

* Learners will not be able to see Resources visible only to Coaches
* Superuser, Admins, Class Coaches, and Facility Coaches will be able to see these Resources.
