### ISSUE TITLE
class coach column is difficult to translate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3703]
### Observed behavior

Translating the coach column is proving difficult because of the complex "N others" pluralization:

![image](https://user-images.githubusercontent.com/2367265/40440151-1093a038-5e72-11e8-8dca-2b658217a544.png)

see https://crowdin.com/translate/kolibri/452/en-ar#32837

### Expected behavior

It would be best to simplify the string to make it easier to translate. One option might be something like

> Coach A, Coach B... (+2)

### User-facing consequences

translators might make mistakes which would lead to difficulty understanding for end-users

### Context

k 090

----

cc @khangmach @jtamiace

**Comment by jtamiace** [comment]
+1 on the `+2`

If you hover on the `2 others` right now, does it show via tooltip who else is there? Feel like there's enough context that the user would know what +N is referring to, but wondering if there's value in adding a tooltip which contains the names of all who aren't showing

**Comment by khangmach** [comment]
+X sounds good. No tooltip on hover currently. Would probably be an easy add...

**Comment by radinamatic** [comment]
Agreed that `+N` sounds like a better solution. :+1:
