### ISSUE TITLE
PDF zoom gestures broken on mobile

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3710]
### Observed behavior

When trying to zoom in and out of a PDF on mobile using gestures, unexpected behaviors happen. For example, it's possible to zoom in the whole window such that the text becomes pixelated.

This behavior happens in both full-screen and embedded modes, but is more disconcerting in full-screen mode.

### Expected behavior

Zoom gestures should either work as expected (preferred) or be disabled

### User-facing consequences

User may zoom using gestures, which makes the text larger but is still hard to read due to pixelation.

We should either disable or properly handle zoom gestures

### Steps to reproduce

use pinch-zoom gestures in the PDF renderer 

### Context

K09, chrome on iphone

**Comment by indirectlylit** [comment]
(cc @christianmemije)

**Comment by christianmemije** [comment]
Does this issue exist in latest Develop?
