### ISSUE TITLE
Replace title attributes with accessible tooltips

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3723]
### Observed behavior

We use the title attribute in a various places to create a 'tooltip'. However these are not accessible. Instead we should be using something like the keen tooltip.

https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/

> tl;dr If you want to hide content from mobile and tablet users as well as assistive tech users and keyboard only users, use the title attribute.

### Expected behavior

Accessible in all devices.

### User-facing consequences

Not accessible in all devices 

### Context

0.10

**Comment by indirectlylit** [comment]
Good to know - didn't realize there were accessibility issues.

I've been using `title` whenever the length is long because `ui-tooltip` doesn't handle these strings nicely. This was true in #3715, #3713, and https://github.com/learningequality/kolibri/pull/3278#issuecomment-370037251

**Comment by indirectlylit** [comment]
fixed in #4453
