### ISSUE TITLE
Account for Varying Widths in Content Cards

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#3726]
### Observed behavior

Thumbnails, and logos in particular, aren't always a 1:1 or 16:9 ratio. Apart from this, the way we display cards (and the associated thumbnails) evolves over time. 

Thumbnails are getting stretched or distorted if they don't perfectly fit the card's thumbnail space. 

### Expected behavior

You should be able to see the thumbnail in its entirety regardless of the space allocated.

### User-facing consequences

Distorted/unrecognizable logos

![image](https://user-images.githubusercontent.com/9877852/40743480-7dea1d08-6406-11e8-9f7c-c4341b350df0.png)
![image](https://user-images.githubusercontent.com/9877852/40743539-aa944112-6406-11e8-94de-b7c49ccbee56.png)
![image](https://user-images.githubusercontent.com/9877852/40743533-a772c2f6-6406-11e8-9e67-058ec1bd7f0c.png)

Would love to hear from @ivanistheone @jayoshih @divad12 @christianmemije @indirectlylit

**Comment by indirectlylit** [comment]
At one point, we decided to standardize on 16:9 aspect ratio, and Kolibri content cards have stuck to this fairly rigidly (see e.g. [this change](https://github.com/learningequality/kolibri/pull/3713/files#diff-1fde6f0bdfefc5265e92d9904e8e960e) which fixed a slight bug there.)

It put the onus on content creators to add thumbnails which conform. It looks like some of our sushi chefs are not conforming to the convention.

When possible, it's preferable to have a human intervene and create a nicely-framed and cropped thumbnail at the correct aspect ratio. In some cases of automated chefs, this might not be possible. In those cases, we have two options:

1. Add a stage to the sushi chefs which [letterboxes](https://en.wikipedia.org/wiki/Letterboxing_(filming)) all uploaded thumbnails such that they conform
2. Do letterboxing in Kolibri

I can see pros and cons of each strategy...

**Comment by christianmemije** [comment]
We use a 1:1 ratio in some places like channel import lesson creation. We could also use `contain` instead of `cover` in the various places so the entire thumbnail is visible.

**Comment by indirectlylit** [comment]
> We use a 1:1 ratio in some places like channel import lesson creation

I wasn't aware we'd done this - recommend we reconsider that decision (cc @khangmach)

**Comment by khangmach** [comment]
So lesson thumbnails using the 16:9 dimensions found in the learn page would look something like this: 
<img width="1148" alt="screen shot 2018-05-31 at 2 50 51 pm" src="https://user-images.githubusercontent.com/25045166/40810239-180b3ea4-64e2-11e8-985b-ce8890fd079a.png">

I also adjusted the 24px to a 18px card padding 

Is merely changing the dimensions of lesson cards to 16:9 a guarantee that the thumbs won't be zoomed in/pixelated? I think steps have to be taken on the cheffing/studio side as well. 

I think given how small the height of the card would become in the example above, we might need to set a max width on the description area (we show the entire text in the preview anyways) & also a lower max character limit -- much less characters than what we allow now.

**Comment by khangmach** [comment]
Also, Jonathan just mentioned to me that he had to change the thumbnail dimensions to accommodate coach contents icon. So the cards David pasted above aren't exactly 16:9
>the thumbnail needed to be upped too, otherwise there would be extra space below the thumbnail
so maybe the thumbnail is like 16:9.5

**Comment by indirectlylit** [comment]
> the cards David pasted above aren't exactly 16:9

No they are - I fixed that here - https://github.com/learningequality/kolibri/pull/3713/files#diff-1fde6f0bdfefc5265e92d9904e8e960e

**Comment by khangmach** [comment]
Working with Jonathan on this! We're gonna try to incorporate the same 16:9 dimensions on lesson cards and see how things look.

**Comment by ivanistheone** [comment]
@khangmach  If possible please check out the content import views as well (those are the other ones that show with square aspect ratio.

**Comment by khangmach** [comment]
@ivanistheone I've checked it out and I think that even though we could implement 16:9 there, it's a bit lower priority, as we aren't using cards there, only channel thumbnails in lists. I'll discuss this with Jonathan when he gets back. (Tagging @jonboiser for convo reference)

**Comment by rtibbles** [comment]
This has been resolved by ongoing work for the 0.15 milestone, thumbnails have never looked so good!
