### ISSUE TITLE
links in new search UI are broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3728]
### Observed behavior

observed during testing of #3687

Navigating to one of the other search links results in an error:

![broken-link](https://user-images.githubusercontent.com/2367265/40755061-7e6c37ae-6431-11e8-8016-e725c37ce182.gif)

### Expected behavior

All links should work

### User-facing consequences

sadness

### Errors and logs

![image](https://user-images.githubusercontent.com/2367265/40755374-17db98c0-6433-11e8-9802-a3ffe184896d.png)

### Steps to reproduce

search for something with multiple copies and then click one of the modal links

**Comment by christianmemije** [comment]
![](http://i0.kym-cdn.com/entries/icons/facebook/000/020/001/krabs.jpg)

**Comment by rtibbles** [comment]
Should be fixed by #3737
