### ISSUE TITLE
assignment summary cannot be properly translated

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3739]
### Observed behavior

The assignment summary is not currently translatable because it concatenates a list of words into a single string separated by commas: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/assignments/AssignmentSummary.vue#L188

See [this thread](https://learningequality.slack.com/archives/C59J8FEPN/p1527708853000731) for info on why we can't do this

### Expected behavior

We need to find a translatable way to display the assignment summary

### User-facing consequences

resulting summary might not make as much sense in languages that don't use commas the same as english

### Context

0.10.0

-----

cc @khangmach @jtamiace

**Comment by khangmach** [comment]
Is this referring to the recipients section, specifically if a lesson is assigned to 1+ groups?

**Comment by jonboiser** [comment]
@khangmach Yeah, like "Group A, Group B, Group C"

**Comment by jonboiser** [comment]
RTL comma-separated lists technically do not need to be "translated", especially since the items are user-generated. E.g. for some LTR languages, you just need to change

`abc, def, ghi`

to

`ghi، def، abc`

(i.e. replace the ',')

but the decision on whether to do this would rely on knowing the locale.

Similarly for other languages that are LTR, but use a different mark than ','

**Comment by khangmach** [comment]
If we really need a comma-less strategy, maybe this could be handled by bullets or line breaks. Not the most space saving or elegant strat...but gets the job done until we can have some custom components in the future or maybe even incorporate a table into this page

Recipients:
Coach Khang
Coach Devon
Coach Jonathan

**or** 
- Coach Khang
- Coach Devon
- Coach Jonathan

**Comment by indirectlylit** [comment]
that sounds like the easiest first step

longer-term, we can consider something like the "pills" used in gmail, but I don't think we should do something like that unless we're using it holistically thoughout the app:

![image](https://user-images.githubusercontent.com/2367265/40814972-485f7f14-64f8-11e8-88fe-f95aec007cae.png)

**Comment by khangmach** [comment]
![screen shot 2018-06-11 at 2 36 23 pm](https://user-images.githubusercontent.com/25045166/41258416-e6648c92-6d84-11e8-9f4a-6ce8f7f49d41.png)
Doesn't look like the most space saving implementation, but at least a row won't expand past three lines.

**Comment by indirectlylit** [comment]
recommend vertically top-aligning cell data and adding a slightly different typographic treatment to "N other(s)" so it can't be confused with a name

**Comment by khangmach** [comment]
@indirectlylit With td top alignment & italic/smaller font size for 'n others'. Table looks wonky without vertically centering table data. Specifically, paddings look off and table ultimately would look out of place with other vertically centered tables across the app

<img width="805" alt="screen shot 2018-06-14 at 10 41 01 am" src="https://user-images.githubusercontent.com/25045166/41428609-78e1eb5a-6fbf-11e8-9187-1f1f9193e98d.png">

**Comment by indirectlylit** [comment]
part of the reason it looks wonky is the single line rows are incorrect:

![image](https://user-images.githubusercontent.com/2367265/41434497-cd65a67e-6fd0-11e8-86b1-e215faf07704.png)

(If something is vertically top-aligned, that doesn't mean a single-line row should have different top- and bottom-padding)

----

That said, I'm fine keeping it centered. If we didn't have those horizontal rules, I would be much more emphatic that they should be top-aligned so it's clear where every row begins.

Typically in data tables it's preferable for the primary information in a row to line up so you can scan across easily (LTR reading). Then for secondary information you scan down cells (top-to-bottom reading)

![image](https://user-images.githubusercontent.com/2367265/41434873-ff962794-6fd1-11e8-9df3-0108a017eb8d.png)

![image](https://user-images.githubusercontent.com/2367265/41434959-3dc95946-6fd2-11e8-9dda-3e4eb8630638.png)

**Comment by jtamiace** [comment]
https://material.io/design/components/data-tables.html#specs

At the bottom, material design put an example of a third-party table with center-aligned data in a row, but doesn't explain why it should be so

**Comment by indirectlylit** [comment]
yeah, definitely the presence or absence of divider lines I think plays a big role here

**Comment by jtamiace** [comment]
Here is a spec that can fix this issue, and locations of each UI that would need to be changed. In addition, and slightly unrelated to this issue specifically, there are updates to the appearance of pills

https://docs.google.com/document/d/1yElT9M6NkWJ04_S7uVdjnm6eZXUL-Gmdv5c3Vr-Ai-0/edit

**Comment by indirectlylit** [comment]
closing in lieu of #4523
