### ISSUE TITLE
update dev docs related to deviceowner

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3744]
### Observed behavior

developer docs currently reference a deviceowner, which no longer exists: https://kolibri-dev.readthedocs.io/en/develop/architecture/uap/concepts_and_definitions.html

### Expected behavior

docs should reflect new 'superuser' flag instead

### User-facing consequences

confused developers

### Context

0.10.0

----

cc @rtibbles @ralphiee22

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/7928
