### ISSUE TITLE
confusing message shown to admins on empty coach page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3780]
### Observed behavior

When there are no classes, an admin sees this message:

![image](https://user-images.githubusercontent.com/2367265/41182808-26a3f398-6b2c-11e8-82cf-f20d133e37b5.png)

This is confusing for two reasons:

1. admins and facility coaches can see all classes, regardless of whether or not they've been assigned
2. the message instructs admin users to contact themselves

### Expected behavior

messaging should apply to all users or be customized for different user types

### User-facing consequences

slight confusion

### Steps to reproduce

Navigate to 'coach' as an admin in a facility with no classes

### Context

0.10.0

**Comment by jtamiace** [comment]
I've started a google doc linked to this trello card that explores alternative wording according to role and whether classes exist or not in a Facility 

https://trello.com/c/q2NmPFjl/189-empty-state-empty-coach-for-coaches-and-admins

**Comment by jtamiace** [comment]
Wow the table from google docs copied over quite nicely.

After feedback from @carinediaz , here is a possible solution for the different users and scenarios

  | Classes exist in facility but coach/admin is unassigned | No classes in facility
-- | -- | --
Class coach | **You aren’t assigned to any classes** Please consult your Kolibri administrator to be assigned to a class | **You aren’t assigned to any classes** Please consult your Kolibri administrator to be assigned to a class
Facility coach | N/A | **There are no classes yet** Please consult your Kolibri administrator ~~to add classes~~
Admin | N/A | **There are no classes yet** Create classes and enroll students in Facility


^ Thinking for the admin scenario, could have `Facility` link to `Facility > Class`

**Comment by indirectlylit** [comment]
looks good. I would just recommend removing the phrase "to add classes" from Facility Coach messaging. (it's not necessarily the outcome  so better to say nothing?)

**Comment by jtamiace** [comment]
Gherkin stories here 

https://docs.google.com/document/d/17TueSXwwe3TH5-v-O9YpUZi0HnQ_rri_4TgYhQ9WMkI/edit

**Comment by indirectlylit** [comment]
have the gherkin stories been added to the repo? If not, should we make that part of the process in the future?
