### ISSUE TITLE
Disable submit buttons when busy

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3790]
### Observed behavior

In most places, we do not disable save/submit buttons, which can result in multi-submission. Ideally we would disable these buttons. This is very common in modals but also exists elsewhere.

### Expected behavior

Notify the user that the request is in progress + prevent accidental multi submission. Use a loader?

### User-facing consequences

Unsure if the request was successful.

**Comment by jonboiser** [comment]
I'm going to close this as a subset of #5320, which also prescribes disabling buttons for modals under certain conditions. I can't think of submit-like button not in a modal that should be disabled at the moment.
