### ISSUE TITLE
print 'time spent' at the end of each makefile command

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3791]
### Observed behavior

In #3776 we're trying to speed up `make dist`, but it's a little hard to measure the time the command takes.

### Expected behavior

In general, it would be nice to print out time spent in commands so we can easily check whether certain changes speed them up.

### User-facing consequences

None for users, but developers would have a better sense of how their changes affect tooling performance

### Context

0.10.0

**Comment by benjaoming** [comment]
@indirectlylit 

Use the `time` command.

For instance `time make dist`.

It's important to measure resources the right way for benchmarking. Measuring real time won't give you the right data.

**Comment by benjaoming** [comment]
Suggesting to close, tools are available on default POSIX systems, no need to beef up our code base :)

**Comment by benjaoming** [comment]
> developers would have a better sense of how their changes affect tooling performance

This is already somewhat evident from Travis and Buildkite. I think it's more about boosting the sense of importance and encouraging each other to *not* merge a PR until that "nice to have performance" issue is ironed out :)

**Comment by indirectlylit** [comment]
thanks - wasn't aware of the `time` command!
