### ISSUE TITLE
Cannot see all questions in my learner report for a particular exercise

### ISSUE THREAD

**Issue by navakk9** [learningequality/kolibri#3792]
### Observed behavior

I logged in as a learner to do an exercise. I then logged in as a coach to see the learner report view of that particular exercise, what I noticed was that only one question was showing up in the report view instead of all the questions attempted. Screenshot is attached. This was on kolibri-beta.learningequality.org because we are using that site for demo videos. 

![screen shot 2018-06-12 at 5 51 38 pm](https://user-images.githubusercontent.com/26124065/41324616-4ed48404-6e6a-11e8-9b7b-07865950b1ed.png)

### Steps to reproduce

Log in as a coach
Go to learners tab
drill down to an exercise that was attempted
look at the report view

### Context

High priority because this will stall demo videos.

**Comment by khangmach** [comment]
more specifically, the question list is missing
![missing](https://user-images.githubusercontent.com/25045166/41365477-53a56a1e-6eee-11e8-8477-00c6bd427006.png)

**Comment by khangmach** [comment]
see correct implementation on kolibridemo
<img width="642" alt="screen shot 2018-06-13 at 9 53 48 am" src="https://user-images.githubusercontent.com/25045166/41365994-be1e7bfa-6eef-11e8-91bf-bc1054e7e7e1.png">

**Comment by navakk9** [comment]
![screen shot 2018-06-13 at 11 19 38 am](https://user-images.githubusercontent.com/26124065/41370164-b7e78284-6efb-11e8-9fb9-4fffa8d41679.png)

**Comment by navakk9** [comment]
![screen shot 2018-06-13 at 11 26 37 am](https://user-images.githubusercontent.com/26124065/41370498-ac46ae22-6efc-11e8-8631-f0eb76a38ca5.png)

**Comment by rtibbles** [comment]
This should have been fixed in #3799 - @navakk9 please confirm on next beta release.

**Comment by indirectlylit** [comment]
latest is available here - http://kolibribeta.learningequality.org/

@navakk9 would you mind confirming the fix?

**Comment by khangmach** [comment]
looks good on my end
