### ISSUE TITLE
scroll bar should be on edge of screen, not within margin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3793]
### Observed behavior

regression caused by #3782 - scroll bar has margin to its right:

![screen shot 2018-06-13 at 11 09 01 am](https://user-images.githubusercontent.com/38421180/41328684-fc8d2d08-6efb-11e8-9f6c-c3c3ccef9300.png)

reported here: https://github.com/learningequality/kolibri/pull/3778#issuecomment-396801750

### Expected behavior

scroll bar should be on page edge

### User-facing consequences

layout looks broken

### Context

0.10.0-beta2

**Comment by jtamiace** [comment]
Not sure if this is an issue on other devices, but if my mouse on mac is hovered outside of the container, it doesn't scroll at all

**Comment by indirectlylit** [comment]
yeah, that's a consequence of the same issue
