### ISSUE TITLE
0.7.2 Upgrade to 0.10.0

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3805]
### Observed behavior
Login as admin at the log in page after the upgrade from 0.7.2 to 0.10.0b2 will have a javascript errors and the login page freeze. After I reload the page I logged in as admin and redirected at the profile page.

### Expected behavior
Log in page should work properly when I log in.

### Errors and logs
![screen shot 2018-06-15 at 4 07 09 pm](https://user-images.githubusercontent.com/8663934/41457822-78b75392-70b7-11e8-969e-6e4a896ecf9e.png)

### Steps to reproduce
* Install the 0.7.2
* Copy the [0.7.2 Kolibri sample data](https://drive.google.com/open?id=1HAJcFr7Yhqj2C8gE88-4gMR7sNJtQiuh) at the `.kolibri`
* Upgrade to 0.10.0b2
* Log in at the log in page

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.0b2
 * Operating system: Windows 10
 * Browser: firefox

**Comment by indirectlylit** [comment]
see also #3806, #3807

**Comment by benjaoming** [comment]
Is it because assets are cached from the previous release? (can be tested by refreshing SHIFT+F5 or similar, depending on your platform)
