### ISSUE TITLE
when modal content scrolls, make clear that content is scrollable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3813]
### Observed behavior

In the new modals from #3786, it's not obvious that they can be scrolled:

| No scroll | Scroll |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/41551737-a2a1eb50-72e1-11e8-89d8-12c81ecb0467.png) | ![image](https://user-images.githubusercontent.com/2367265/41551711-90b7b488-72e1-11e8-972e-47655f03b655.png) |

### Expected behavior

Should be clear that inner box is scrollable. Could possibly use similar shadows to the top bar and exercise progress visualization?

### User-facing consequences

might not realize that more content exists

### Context

0.11.0

-----

cc @christianmemije @jtamiace

**Comment by jtamiace** [comment]
Linking existing mocks from all the 2017 style guide work, inspired by material design's modals.

Can revisit if an alternative design is needed

https://drive.google.com/file/d/0B3sjMmpdLvk4Tzk4ZnJpUV9nSkE/view

<img width="697" alt="screen shot 2018-06-18 at 12 18 41 pm" src="https://user-images.githubusercontent.com/6668144/41557218-c9050dc6-72f1-11e8-9a0e-465eba514dca.png">

**Comment by indirectlylit** [comment]
thanks didn't know they were in the original mocks.

those lines are only shown when the content doesn't fit, right?

**Comment by jtamiace** [comment]
Yes I think so. There are various mockups and gifs on their component page 

https://material.io/design/components/dialogs.html#anatomy

**Comment by jtamiace** [comment]
I'm seeing initially more work needing to be done on defining max-heights before these lines appear on mobile vs desktop (the change language modal is the first thing that comes to mind)

**Comment by christianmemije** [comment]
Addressed in #3786
