### ISSUE TITLE
channel thumbnail doesn't update after republishing and re-importing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3821]
### Observed behavior

Reported by @bonidjukic and @laurenlichtman -

> I have updated a channel thumbnail in Studio, deleted and re-imported that channel in Kolibri, but I still see the default one - how can I actually get this to refresh / update?

I believe the channel initially had no thumbnail (or the 'default'), and then one was added.

### Expected behavior

Thumbnail should appear correctly

### User-facing consequences

Mismatch between studio channel and kolibri channel

### Steps to reproduce

* create a channel in studio with no thumbnail
* publish
* import
* add thumbnail in studio
* publish
* try to get it to show up in kolibri

### Context

0.10.0

**Comment by lyw07** [comment]
Not able to reproduce this error on 0.10.
After adding a thumbnail to the channel (originally the channel doesn't have a thumbnail), I'm not able to publish the channel directly. 
So I had to add a new file to the channel and publish it, then the database file got changed and the channel on Kolibri had the thumbnail show up after I updated the channel on Kolibri. It also works when I delete the channel and import it again after the thumbnail change.

**Comment by indirectlylit** [comment]
thanks for testing! We'll re-open if we see it again.

> After adding a thumbnail to the channel (originally the channel doesn't have a thumbnail), I'm not able to publish the channel directly.

I opened the studio issue above for this
