### ISSUE TITLE
descriptions in Learn sometimes don't appear

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3822]
### Observed behavior

reported by @bonidjukic - sometimes descriptions don't appear until the page is re-visited:

![descriptions](https://user-images.githubusercontent.com/2367265/41618393-e855ec6a-73b7-11e8-960e-36e24022fd82.gif)

### Expected behavior

descriptions should always show up

### User-facing consequences

users lose a lot of context while browsing and experience inconsistency

### Errors and logs

…

### Steps to reproduce

navigate through a content tree that contains descriptions using a combination of content cards and the breadcrumbs

### Context

k0.10.0

**Comment by bonidukic** [comment]
I would just amend this part:
>sometimes descriptions don't appear until the page is re-visited

with: descriptions are never displayed on the first node visit
