### ISSUE TITLE
No cursor appear in password field, both user's add and edit password.

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3824]
### Observed behavior

I use the <a href="https://docs.google.com/spreadsheets/d/1FhA5qIDB2DfNJW7bCPZ8lweVI-ZfDUchwY8mJwqdMWE/edit#gid=1279941688">Kolibri integration testing spreadsheet</a> as a guide to test the Kolibri 0.8.0 upgrade to 0.10.0b3 in Ubuntu 18.04. From the Superuser there's a instruction to Create a facility administrator account.

 In users tab, I click add new, then fill-up the name and username. But the password  and re-enter password field was no cursor to type in. I try to click and press tab on keyboard, but no cursor appear so that I can't enter my password. I found out, that the cursor is overlap by the label name of password and re-password. Because of that, It's hard to entered a password in user's add and even in edit password. so we think that the browser has a problem within the typing field.

### Steps to reproduce

-  Install the 0.8.0
-  Copy the 0.8.0 <a href="https://drive.google.com/drive/shared-with-me">Kolibri sample data</a>  the .kolibri
-  Upgrade to 0.10.0b3
-  Log in as admin
-  Go to facility then click users tab and add new user or edit the password.

### Context
 Kolibri version: 0.10.0b3
    Operating system: Ubuntu 18.04
    Browser: Firefox 59.0.2(64-bit)

### Screenshot
![screenshot from 2018-06-20 13-58-46](https://user-images.githubusercontent.com/38421180/41640410-54c3050e-7494-11e8-98c7-56dd49ec67f9.png)

**Comment by indirectlylit** [comment]
Hi @mrpau-julius  -

> It's hard to entered a password in user's add and edit password

Could you provide more detail on what this means? What exactly happens when you try typing?

FYI sometimes recording a short animated gif screencast is a good way to demonstrate a subtle interaction problem without needing to explain verbosely.

**Comment by mrpau-julius** [comment]
Hi @indirectlylit

sorry for short detail that I wrote. I will edit now to explain more in details.

**Comment by indirectlylit** [comment]
thank you!

**Comment by cpauya** [comment]
+1 on the .gif - @mrpau-richard knows how to do it @mrpau-julius :)

**Comment by christianmemije** [comment]
Issue has to do with with focus event listener with the core-modal.
