### ISSUE TITLE
Triple scrollbar appearing on certain content types

### ISSUE THREAD

**Issue by bonidukic** [learningequality/kolibri#3826]
### Observed behavior
Triple scrollbar appears when accessing Flexbook or PLIX content.
It seems that the first scrollbar comes from the inner `iframe`, and the second from the wrapping `div`.

- Possibly regression caused by PR #3782 - add max-width to pages and update some text-alignment
- Also might be relevant: issue #3793 - scroll bar should be on edge of screen, not within margin

### Expected behavior
There should only be two scrollbars in these situations.

### User-facing consequences
Additional scrollbar confuses people and it's generally impractical.

### Steps to reproduce
- Access any Flexbook or PLIX content (possibly not exhaustive list)
    - Make sure that the content has "enough height" (maybe you'll have to decrease browser width to make third scrollbar appear)

Performance Test - Multiple Exercises channel ID (used in my test): `1a9158aa082a460b9ea693ba329e0770`

### Context

 - Kolibri version: latest `develop` (Kolibri 0.11.0a2.dev+git-60-g55d86e5b7)
 - Operating system: Ubuntu 17.10
 - Browser:
     - Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
     - Firefox: 60.0.2 (64-bit)

#### Chrome - inner `iframe` scrollbar 

![selection_328](https://user-images.githubusercontent.com/2150991/41651200-48681722-7480-11e8-9c55-2f0dd9ee73c8.png)

#### Chrome - wrapping `div` scrollbar

![selection_329](https://user-images.githubusercontent.com/2150991/41651208-4ba2484a-7480-11e8-8991-d7337c9a1bb0.png)

#### Firefox

![selection_330](https://user-images.githubusercontent.com/2150991/41651217-50ce77c6-7480-11e8-887d-567418190f1e.png)

**Comment by mrpau-julius** [comment]
Same issue I encounter, when I change the language to Arabic and go to recommended page.
The videos' item overlap the scrollbar in bottom.

### Screenshot
Windows 10 pro
Kolibri 0.10.0b8
Firefox 61.0 (64-bit)

![arabic recommended page](https://user-images.githubusercontent.com/38421180/42015370-ab32d3ba-7ad9-11e8-9dff-0f8f2e615d58.png)

Windows 7
Kolibri 0.10.0b8
Firefox 60.0.2 (64-bit)

![maps](https://user-images.githubusercontent.com/38421180/42015672-206ceee0-7a5d-11e8-9b23-6b8740c0786f.png)

**Comment by christianmemije** [comment]
Page scrollbar fixed in #3808. :heavy_check_mark: 
HTML5 app extra scrollbar fixed in #3890  :heavy_check_mark: 
FF horizontal scrollbar should be fixed in #3977 :heavy_check_mark:

**Comment by indirectlylit** [comment]
nice
