### ISSUE TITLE
Lesson label/text margin too big

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#3828]
### Observed behavior
(in-lesson page) Margin between label text and paragraph text too far apart, making vertical readability difficult

**Current, with margin bottom = 16px:**
![screen shot 2018-06-20 at 1 12 13 pm](https://user-images.githubusercontent.com/25045166/41682238-092bd7a4-748c-11e8-9f72-2be22e9d3e9d.png)

**Proposed, with margin bottom = 8px:**
![screen shot 2018-06-20 at 1 11 56 pm](https://user-images.githubusercontent.com/25045166/41682236-0702e242-748c-11e8-9e8d-88de62ce6580.png)

…

### Expected behavior
Related information brought closer so reader can more easily visually associate fields.

…

### User-facing consequences
Readability implications

**Comment by christianmemije** [comment]
Fixed in #3957
