### ISSUE TITLE
update developer docs with info about github label conventions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3835]
### Observed behavior

Our use of github labels is not documented as pointed out here: https://github.com/learningequality/kolibri/pull/3827#issuecomment-399035053

### Expected behavior

Should add this info to this page: http://kolibri-dev.readthedocs.io/en/develop/references/development_workflow.html

We can roughly use this info:

* _changelog_ - used on PRs or issues to generate 'more details links in the [changelog](https://github.com/learningequality/kolibri/blob/develop/CHANGELOG.rst)
* _DEV: ..._ - generally used to help categorize issues by area of responsibility
* _P0_, _P1_, _P2_, _P3_ - used to prioritize issues within a specific milestone. Not used on PRs or issues not in a milestone
* _PR: ..._ - PR lifecycle flags to help coordinate code reviews
* _TAG: ..._ - general organizational labels, usually used on issues but sometimes also on PRs
* _TASK: ..._ - generally used to help categorize issues by outcome or category

### User-facing consequences

New developers don't know our conventions

### Context

See recent work here: #3795

**Comment by indirectlylit** [comment]
I'll also use this opportunity to add descriptions to the labels - cc @benjaoming

**Comment by benjaoming** [comment]
Here is a nice little extra addition to the documentation of the "beginners issue" label: https://www.firsttimersonly.com/

On top of that, we can add a friendly bot... but perhaps that's a bit of a separate issue.. https://github.com/hoodiehq/first-timers-bot
