### ISSUE TITLE
"Progress can't be null" error when navigating quickly away from content page while it's first loading

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#3836]
### Observed behavior

![image](https://user-images.githubusercontent.com/618416/41744629-39a0479e-7559-11e8-8321-dffc2fbaaf59.png)

### Expected behavior

No error? I didn't do anything wrong! :(

### User-facing consequences

Slap to the face!

### Steps to reproduce

1. Clicked down a few levels in the topic tree, and got to a content node.
1. Immediately clicked on a breadcrumb halfway up the topic tree.

Can't replicate reliably.

### Context

Kolibri 0.10.0b4, online demo server

**Comment by indirectlylit** [comment]
closing - I don't think anyone has seen this in a while
