### ISSUE TITLE
'Edit class name' icon button should be a text link

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3838]
<img width="333" alt="screen shot 2018-06-21 at 1 49 10 pm" src="https://user-images.githubusercontent.com/6668144/41745505-ff9f6662-755b-11e8-96e0-9e51344c9f38.png">

### Context

0.10 bug bash

**Comment by indirectlylit** [comment]
I think the edit button is actually a pre-style-guide hold-over: I think it's the only place in the app we use this pattern.

Maybe it would be more idiomatic to do something like 

![image](https://user-images.githubusercontent.com/2367265/41748935-d2216426-7568-11e8-92fe-f4bb93765eb3.png)

**Comment by jtamiace** [comment]
Yeah I remember we just waved it off as an outlier. I don't have any qualms with using text instead. Would suggest a capital 'E' though

**Comment by jtamiace** [comment]
It seems like we're introducing this pattern anyway especially with "change status" in lessons
