### ISSUE TITLE
incorrectly logged out due to inactivity

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3843]
### Observed behavior

reported by @carinediaz during bug bash

> Was logged in as an admin, assigning a coach to a class and got this message:

![image](https://user-images.githubusercontent.com/2367265/41747518-2081ff3c-7563-11e8-881c-ac88e81322b2.png)

> I was NOT inactive!

### Expected behavior

user's shouldn't get logged out

### User-facing consequences

annoyance

### Steps to reproduce

unknown

### Context

k0.10.0

**Comment by rtibbles** [comment]
I think this might be a performance issue, with sessions not being updated frequently enough.

**Comment by rtibbles** [comment]
Closing this as we have not seen a recent recurrence.
