### ISSUE TITLE
error and log-out after clicking completed exam

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3844]
### Observed behavior

reported by @lauradanforth during bug bash:

> When clicking on a completed exam, received the error message below (and was also ‘logged out due to inactivity’ similar to [this issue](https://github.com/learningequality/kolibri/issues/3843))

### Expected behavior

no errors and no log-out

### User-facing consequences

annoyance

### Errors and logs

```json
{
  "request": {
    "path": "\/learn\/api\/learnerclassroom\/96516155886defde0d170572c905ed73\/",
    "params": {
      "1529614360045": 1529614360045
    },
    "headers": {
      "Content-Type": "application\/json",
      "Accept": "application\/json, application\/json;q=0.8, text\/plain;q=0.5, *\/*;q=0.2",
      "X-CSRFToken": "JkgQktljYNgGVIAVqi9YOMANb4RUEgVg5nj1JYROdIEUM414EgmiprzsCFDF0HTV"
    },
    "method": "GET",
    "canceled": false
  },
  "url": "\/learn\/api\/learnerclassroom\/96516155886defde0d170572c905ed73\/?1529614360045=1529614360045",
  "raw": {
    
  },
  "status": {
    "code": 403,
    "text": "Forbidden"
  },
  "headers": {
    "Date": "Thu, 21 Jun 2018 20:29:53 GMT",
    "Vary": "Accept, Accept-Language, Cookie",
    "Server": "nginx\/1.4.6 (Ubuntu)",
    "X-Frame-Options": "SAMEORIGIN",
    "Allow": "GET, HEAD, OPTIONS",
    "Content-Language": "en",
    "Connection": "keep-alive",
    "Content-Type": "application\/json",
    "Content-Length": "58"
  },
  "entity": {
    "detail": "Authentication credentials were not provided."
  }
}
```

### Steps to reproduce

unknown

### Context

k0.10.0

**Comment by lauradanforth** [comment]
For steps to reproduce, I logged in as admin and cilcked Learn then clicked on a class and onto an Exam that had been completed.

**Comment by indirectlylit** [comment]
unfortunately I'm having trouble reproducing this

**Comment by rtibbles** [comment]
I think this might be a performance issue, with sessions not being updated frequently enough.

**Comment by rtibbles** [comment]
Closing this as we have not seen a recent recurrence.
