### ISSUE TITLE
dropdown for facility selection is confusing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3846]
### Observed behavior

reported by Azeez during the bug bash:

> When creating a new account, the box for facility is automatically filled in as facility. Doesn’t allow you to leave it blank or to put in anything else.

![image](https://user-images.githubusercontent.com/2367265/41748256-ee8ea1e4-7565-11e8-8b02-de5bda54e795.png)

### Expected behavior

If switching facility is not an option, it should be disabled or rendered as a simple text with label.

One reason for not hiding it is that if someone creates an account and then a second facility is added later, hopefully the user would remember which one they were in.

### User-facing consequences

a bit of confusion over why there's a select box with nothing to change

### Context

0.10.0

----

cc @khangmach @jtamiace

**Comment by khangmach** [comment]
During the account creation process there isn't any text really clarifying to a new user what a facility is exactly. Even if we changed the dropdown into simple label text, the information still wouldn't be relevant without a second facility added later. Would consider thinking about just dropping this component from the page until the information becomes actionable/relevant. 

As a compromise, Profile would be a good place to put the facility text imo.

**Comment by indirectlylit** [comment]
Okay - so the outcome if I understand correctly is:

1. when there is only one facility, make it a read-only label
2. add the same label to the profile page.

@khangmach is that correct?

**Comment by khangmach** [comment]
@indirectlylit sounds good!

**Comment by rtibbles** [comment]
Fixed in #5233
