### ISSUE TITLE
If a topic appears in "Next Steps," it takes the user to a content renderer page 

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3847]
<img width="1072" alt="screen shot 2018-06-21 at 3 24 05 pm" src="https://user-images.githubusercontent.com/6668144/41748545-3960b922-7567-11e8-94d9-7f7ded283015.png">
<img width="1083" alt="screen shot 2018-06-21 at 3 24 13 pm" src="https://user-images.githubusercontent.com/6668144/41748546-397feb1c-7567-11e8-814c-1296d1011d2a.png">

### Expected behavior

User should be taken to the topic and not experience infinite load state

### User-facing consequences

User will wait forever

### Steps to reproduce

1. Log in as a facility user
2. Complete/master the last item in a topic
3. Go to "Recommended"
4. Click the topic card that appears in "Next Steps"

### Context

0.10
MacOS
Chrome

**Comment by DXCanas** [comment]
@jtamiace Looking over this, one of the reasons it routes to a content page _only_ is because there's a dedicated "recommended" content page with key differentiators being the tab and breadcrumbs highlighted
![image](https://user-images.githubusercontent.com/9877852/41867101-ff5d8ac2-7866-11e8-80d3-c48cc53c3b1b.png)
Should we do anything special for "recommended" topics?

**Comment by jtamiace** [comment]
Hmm... it goes against the original design to keep content that appears in Recommended scoped to Recommended only, but feel like it would make sense to jump the user to that topic in Channels. Would there be huge issues to make that link across tabs?

**Comment by DXCanas** [comment]
>  it goes against the original design to keep content that appears in Recommended scoped to Recommended only

Huh, I didn't know that was the case. I we can probably make it so that they all go their place in the topic tree? I

**Comment by jtamiace** [comment]
> we can probably make it so that they all go their place in the topic tree?

Yeah at this point, that would make sense to me.
