### ISSUE TITLE
Progress bar on topics in Learn not reflecting actual progress

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3848]
### Observed behavior

Even if all items within a topic are completed, it will sometimes display as incomplete
<img width="1027" alt="screen shot 2018-06-21 at 3 07 55 pm" src="https://user-images.githubusercontent.com/6668144/41749211-0ac6d940-756a-11e8-942b-4232d335fb97.png">

### Expected behavior

The topic should have a full yellow bar with a complete icon

### User-facing consequences

Learner will be confused and sad or think something is missing from the topic

### Steps to reproduce

1. Log in as a facility user
2. Complete/master all items in a topic
3. Look at the parent topic

### Context

0.10.0
MacOS
Chrome

**Comment by indirectlylit** [comment]
@jonboiser mind looking at this?

**Comment by jonboiser** [comment]
I think the problem is that the percentage used on the "Early Math > Counting >Counting" topic card is 

2 (mastered resources) / 5 (total resources)

Whereas, based on this installation it should be

2 (mastered resources) / 2 (available resources)

**Comment by rtibbles** [comment]
We should probably be excluding unavailable content when getting these leaf_ids here: https://github.com/learningequality/kolibri/blob/release-v0.10.x/kolibri/content/serializers.py#L177

**Comment by rtibbles** [comment]
(this will also stop us from counting completed, but unavailable content from being included in progress calculations - the inverse of this)
