### ISSUE TITLE
language list seems randomly sorted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3851]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/41751032-02d3dca6-7574-11e8-8dbf-ce5e4cabafba.png)

### Expected behavior

Languages should be sorted "alphabetically", or whatever that means when multiple character sets are being compared.

### User-facing consequences

users might have some difficulty finding their language

### Context

0.10.0

**Comment by christianmemije** [comment]
Fixed in #3829
