### ISSUE TITLE
Can't create a superuser on windows 7 using kolibri 0.10.0beta5

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3852]
### Observed behavior
I install the Kolibri 0.10.0beta 5 in windows 7 and it was successfully install, while I 'm load in Firefox browser to setup or create a superuser and facility and fill-up all the fields. the setting was appeared and has a error messages.

### Expected behavior
The superuser must create and auto login.

### Errors and logs

```
[INFO: kolibri/core/assets/src/core-app/mediator.js] KolibriModule: setup_wizard registered
default_frontend-0.10.0b5.js:73:186152
[INFO: kolibri/core/assets/src/state/actions.js] Session set.
default_frontend-0.10.0b5.js:13:32105
[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred 
{…}
​
entity: "<h1>Server Error (500)</h1>"
​
headers: Object { "Content-Language": "en", "Content-Length": "27", "Content-Type": "text/html", … }
​
raw: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
request: Object { path: "/api/deviceprovision/", entity: "{\"language_id\":\"en\",\"facility\":{\"name\":\"jullius\"},\"superuser\":{\"full_name\":\"julius\",\"username\":\"julius\",\"password\":\"abc123*\"},\"preset\":\"nonformal\"}", method: "POST", … }
​
status: Object { code: 500, text: "Internal Server Error" }
​
url: "/api/deviceprovision/?1529635598512=1529635598512"
​
__proto__: Object { … }
default_frontend-0.10.0b5.js:1:5235
kolibriGlobal</</v.prototype.save/n</</<
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:1:5235
z
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:85:3066
$
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:85:2712
kolibriGlobal</</</o</</E.prototype.when
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:85:6940
kolibriGlobal</</</o</</x.prototype.run
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:85:5777
kolibriGlobal</</r</t.prototype._drain
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:86:537
t/this.drain
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:86:204
e
http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.0b5.js:38:533

```

### Context

Kolibri version: 0.10.0b5
Operating system: Windows 7
Browser: Firefox 60.0.2(64-bit)

### Screenshot
![error-during-set-up](https://user-images.githubusercontent.com/38421180/41755348-ad590e0a-758b-11e8-92ea-72abdd9506cb.png)

**Comment by indirectlylit** [comment]
thanks @mrpau-julius - remember to wrap your error strings in triple backticks

**Comment by indirectlylit** [comment]
Is this reproducible every time you try to install kolibri? or was this something that just happened once?

@radinamatic any idea what may have happened here?

**Comment by radinamatic** [comment]
Confusing... 😕 

On a fresh install I was able to replicate the error, as the last step of the setup wizard displayed the same:

![screenshot - 23-jun-18 2_01_47 am](https://user-images.githubusercontent.com/1457929/41803588-b7aebaf8-768a-11e8-87f6-fe52c0f6abf0.png)

![screenshot - 23-jun-18 2_03_19 am](https://user-images.githubusercontent.com/1457929/41803592-c42526be-768a-11e8-97c6-e4c7ffcc5517.png)

Missing `Language id` field here?

So I stopped the server and run it from the command prompt, but this time the setup wizard finished successfully:

![screenshot - 23-jun-18 2_08_14 am](https://user-images.githubusercontent.com/1457929/41803609-ef940f0e-768a-11e8-89a1-cb1a5957cf11.png)

**Comment by radinamatic** [comment]
Still repeating the above scenario: at first post-install run setup wizard fails, even if I reload, stop server and restart it from the desktop shortcut, or change the language. 

Only when I stop the server and start it from the command prompt, it finishes successfully.   

[kolibri.log](https://github.com/learningequality/kolibri/files/2129479/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2129480/server.log)

**Comment by indirectlylit** [comment]
strange .. lots of `sqlite3.OperationalError: database is locked` errors. Wouldn't have expected that

**Comment by benjaoming** [comment]
Can we quickly confirm that this is a Windows-only issue?

_If_ it's Windows-only, I recommend trying to install a newer Python after finishing the normal Kolibri installation, thus overwriting the bundled Python version. This is because Kolibri bundles Python and Python bundles SQLite, and we changed the Python version in this installer. So wondering if the problem could originate from there? (since I hear that it's not reproducible on other platforms)

**Comment by radinamatic** [comment]
Confirming the issue on Windows version 10:

![2018-06-25_18-25-40](https://user-images.githubusercontent.com/1457929/41863227-6c07de72-78a6-11e8-8fda-662f3489a08a.png)

[kolibri.log](https://github.com/learningequality/kolibri/files/2133919/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2133920/server.log)

The issue, from all the tests performed these last days, apparently is limited to Windows only.

Making a fresh install to test if updating Pyhton will make a difference.

**Comment by radinamatic** [comment]
Unfortunately, no change after the upgrade to Python 3.6.5:

![2018-06-25_18-45-22](https://user-images.githubusercontent.com/1457929/41863812-33f961de-78a8-11e8-9a8e-bb278d85a25c.png)


[kolibri.log](https://github.com/learningequality/kolibri/files/2133955/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2133956/server.log)

**Comment by mrpau-richard** [comment]
I reproduced this issue at the Windows 10. if I set my VM base memory into 4gb and the processor into 2. Adding more than 5gb memory and 4 processor fixes this issue in the Windows 10 VM.

**Comment by indirectlylit** [comment]
Interesting.

Would it be possible to prove that the issue is related to either the amount of ram or processing power? If that's the case, I'd imagine you should be able to run the task manager while Kolibri is throwing the error, and see either the memory or CPU maxed out.

**Comment by mrpau-richard** [comment]
@indirectlylit I think it is, the cpu maxed out. When the error came out.
![temp](https://user-images.githubusercontent.com/8663934/41893093-22ea3774-794d-11e8-8b52-7042699d4910.gif)

**Comment by radinamatic** [comment]
Just tried the 0.10 beta7 on the new Win 7 VM I built this morning, and could not replicate the error (setup wizard finished without issues). VM had 8gb of RAM and 2 CPUs, the same as the above Win 10 scenario with beta5 where the error did appear.

**Comment by mrpau-julius** [comment]
I test the 0.10 beta 7 on windows 7 VM, had 2gb RAM and 2 CPUs. In the first fill-in a superuser and click finish it has an error and I retry it again, there no error or issues. Even I change the RAM into 5gb and reinstall again, same result that I get.

**Comment by indirectlylit** [comment]
lowering priority because of the inconsistent nature of the problem. Tomorrow we can test on a resource-constrained physical computer instead of a VM to see if that affects anything

**Comment by jamalex** [comment]
>Tomorrow we can test on a resource-constrained physical computer instead of a VM to see if that affects anything

The meeting box has 4GB of RAM. But @DXCanas is doing upgrades on it, and space is limited, so check with him
