### ISSUE TITLE
Exam error message showing in all exercises.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3853]
### Observed behavior
When I input a wrong character in the exam exercise it will show the error in all exercises.

### Expected behavior
The error message should show only in the specific exercise.

### Errors and logs
![gif-temp](https://user-images.githubusercontent.com/8663934/41765417-998c3216-7636-11e8-8d54-33614a03db2c.gif)

### Context

 * Kolibri version: 0.10.0b5
 * Operating system: Ubuntu 18.04 LTS
 * Browser chrome 60.0

**Comment by jonboiser** [comment]
The warning text appears in the perseus plugin. How it appears probably is managed there?

**Comment by rtibbles** [comment]
Joy... @christianmemije fancy taking a look at this?
