### ISSUE TITLE
Answer images do not pop up in the exercise

### ISSUE THREAD

**Issue by navakk9** [learningequality/kolibri#3858]
### Observed behavior

I want to do my exercise on shapes, because it is SO MUCH FUN. But then I see that the correct answer is the only option which is showing up. The images for the other options did not show up. This is not fun anymore.

### Expected behavior

I except all the images to load on my exercise options. 

### User-facing consequences

Learners will not take this exercise seriously and coaches will not get the right feedback on the exercise. 

### Errors and logs

 the browser console - attached

### Steps to reproduce

1. Log-in as a learner using username: new, password: test
2. Click on Demo Lesson 1
3. Click on Name Shapes 3
4. Start the exercise
5. Wait for a question which asks you to choose the rectangle(this is the only question where the images are not loaded properly)
![screen shot 2018-06-22 at 3 18 00 pm](https://user-images.githubusercontent.com/26124065/41801753-3973d15e-7631-11e8-9aea-9d63623325d5.png)

…

### Context

Tell us about your environment, including:
 * Kolibri version - kolibri beta demo site - 0.10.0b4
 * Operating system - Mac OS
 * Browser - Google Chrome

…

**Comment by ralphiee22** [comment]
Hi @navakk9, would it be possible to give me the channel id and breadcrumb to reach this exercise?

**Comment by navakk9** [comment]
@ralphiee22 - Channels> Khan Academy (English)> Math> Early math> Geometry> Basic shapes>  Name shapes 3

**Comment by ralphiee22** [comment]
I think this issue has been fixed, but I will wait until KA English has been pushed to confirm.

**Comment by ralphiee22** [comment]
Confirmed that images are now showing up in exercises.
