### ISSUE TITLE
improve speed of loading the device 'channel list' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3866]
### Observed behavior

Currently, loading the 'channel list' page can take a very long time when large channels are installed. This is exacerbated on slow devices like the Pi, and is especially bad because it's the default page and shown before import begins.

### Expected behavior

Channel listing page should load more quickly.

### User-facing consequences

May think the app is broken and lose patience.

### Context

k0.10.0

**Comment by jamalex** [comment]
Let's leave this open for my upcoming caching PR?

**Comment by rtibbles** [comment]
Is this fast enough yet?

**Comment by indirectlylit** [comment]
probably - let's close this until we get further reports that it's still an issue
