### ISSUE TITLE
hide single breadcrumb in lesson resource management

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3867]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/41803423-879e85de-763d-11e8-995a-67d0845d7e2f.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/2367265/41803427-935897c0-763d-11e8-9be4-6ff28d220f04.png)

### User-facing consequences

minor UX improvement

### Context

k0.10.0

**Comment by jonboiser** [comment]
The design of this workflow as of 0.12 doesn't really match the Observed Behavior screenshot.

There is different copy and the "Channels" breadcrumb does not appear on the top-level with all the channels.
