### ISSUE TITLE
empty answer marked as 'wrong'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3870]
### Observed behavior

observed by @jeepurs 

note that the answer is empty, but the attempt is marked as 'wrong':

![image](https://user-images.githubusercontent.com/2367265/41803622-9d3ea1ba-763f-11e8-9c42-7dbeb9f8ca63.png)

### Expected behavior

empty answers should not count as an attempt by the learner

### User-facing consequences

makes students look like they're doing worse than they really are

### Steps to reproduce

…

### Context

k0.10.0

**Comment by indirectlylit** [comment]
potentially related:

* https://github.com/learningequality/kolibri/issues/3871
* https://github.com/learningequality/kolibri/issues/3869

**Comment by indirectlylit** [comment]
this may be the same behavior that @navakk9 observed here: 

![image](https://user-images.githubusercontent.com/2367265/41803722-ceb8c184-7640-11e8-8eae-e6f11ab1843f.png)

**Comment by christianmemije** [comment]
Issue:  #3871

**Comment by indirectlylit** [comment]
thanks - yes it seems like all these issues are inter-related. I think we should attempt to implement the debounce proposal in #3871

**Comment by christianmemije** [comment]
We were accidentally logging empty attempts. Should be fixed in #3904

**Comment by christianmemije** [comment]
Fixed in #3904
