### ISSUE TITLE
in-progress edits results are counted as attempts

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3871]
### Observed behavior

observed by @jeepurs 

it seems we count attempts for every blur event, which causes intermediary results to be incorrectly counted as 'attempts'

![image](https://user-images.githubusercontent.com/2367265/41803669-265590bc-7640-11e8-80db-3bd0d795cfe5.png)

### Expected behavior

Unclear. We made a decision to log intermediary edits, so it's not clear what the correct behavior is.

### User-facing consequences

students look like they're doing worse than they really are

### Steps to reproduce

…

### Context

k0.10.0

----

cc @rtibbles @khangmach @jtamiace

**Comment by rtibbles** [comment]
This is not the on blur, but on perseus registering a user interaction event. The other alternative is to add a submit button for the question.

**Comment by indirectlylit** [comment]
> registering a user interaction event

does that mean every key-press? If so, this would be a more significant issue

**Comment by rtibbles** [comment]
It depends on the perseus widget type.

**Comment by rtibbles** [comment]
Because the behaviour differs wildly between widgets is why we are not attempting to inspect it ourselves. I think the best fix would be to greatly increase the debounce interval for capturing these events.

**Comment by khangmach** [comment]
It sounds to me that increasing the debounce interval greatly wouldn't guarantee this issue would go away, but would rather make them appear far and few between. Are we able to capture the final event for every question upon exam submission?

**Comment by indirectlylit** [comment]
> I think the best fix would be to greatly increase the debounce interval for capturing these events.

Yes, agreed that increasing the debounce to something like 5 or 10 seconds would help this issue.

>  Are we able to capture the final event for every question upon exam submission?

Right it's important that when you submit the exam it should take what ever the current value is, correct, even if the debounce time has not yet elapsed

**Comment by jtamiace** [comment]
Debounce sounds good for now until we can find a better way to represent meaningful intermediary steps either now in a later version, since there still does seem to be pedagogical use for that?
