### ISSUE TITLE
'profile' link in user menu goes nowhere when viewing profile

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3876]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/41804473-f74180e0-764b-11e8-98a7-ee085d6392a5.png)

### Expected behavior

profile link should be hidden or disabled

### User-facing consequences

slight confusion

### Steps to reproduce

view profile

### Context

0.10.0

**Comment by christianmemije** [comment]
Not broken behavior.
