### ISSUE TITLE
'resource added' shown, but lesson resource list not updated

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3878]
### Observed behavior

Reported by Azeez Gupta:

> Was trying to add a resource to an existing or a new lesson, as a coach. It says ‘resource added’, but when I go back to the lesson, it doesn’t show the list with that resource

### Expected behavior

Lesson resource list should be properly updated

### User-facing consequences

Confusion/frustration

### Errors and logs

…

### Steps to reproduce

…

### Context

0.10.0

**Comment by jonboiser** [comment]
It's possible in the scenario, the "save" button was not pressed after adding the resource (the "resource added" pop up appears only when adding, not saving). The auto-saving feature in #4253 might help prevent this kind of situation.
