### ISSUE TITLE
broken layout during lesson resource preview

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3879]
### Observed behavior

Reported by @khangmach 

buggy layout:

![image](https://user-images.githubusercontent.com/2367265/41804680-a0bd8f76-764f-11e8-8678-e2c358a1c24d.png)

### Expected behavior

Layout should flow correctly

### User-facing consequences

App feels a bit broken

### Steps to reproduce

…

### Context

k0.10.0 on beta server

**Comment by christianmemije** [comment]
Fixed in #3890
