### ISSUE TITLE
clicking resources can sometimes lead to the 'content unavailable' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3880]
### Observed behavior

Reported by @jtamiace 

Clicking on the first exam leads to the “content unavailable page (logged in as admin on Learn page)

![image](https://user-images.githubusercontent.com/2367265/41804698-fe25d7a4-764f-11e8-93aa-11793eec9587.png)

![image](https://user-images.githubusercontent.com/2367265/41804699-0105fad0-7650-11e8-86c1-70161fb6ba35.png)

### Expected behavior

All displayed content should link correctly

### User-facing consequences

cannot access content that should exist

### Errors and logs

…

### Steps to reproduce

…

### Context

0.10.0 on beta server

**Comment by jonboiser** [comment]
This is because of some old logic that has never gone away.

Exams have a `channel_id` field, but if that Channel is not found on the server, the `showExam` action has the app redirect to the COntent Unavailable page.

https://github.com/learningequality/kolibri/blob/26073dda2569bb38bfe1e08ba486e96f650d10ce/kolibri/plugins/learn/assets/src/state/actions/main.js#L439-L441

**Comment by indirectlylit** [comment]
Since exams are now cross-channel, I assume they shouldn't have a channel ID field anymore?

Relatedly, I'm curious what happens when you delete a channel that has content used in a lesson or exam...?

**Comment by jtamiace** [comment]
For lessons at least, I'm seeing that if you

1. import channel 1
2. put some of channel 1 into a lesson
3. delete channel 1

The resources in the lesson from channel 1 disappear without error. When I imported channel 1 back in, they appeared in the lesson again, with progress intact (i had completed one item)

**Comment by jonboiser** [comment]
Probably will have to wait until #3991 is merged in. The solution to this particular issue will need to use some of the how-to-handle-deleted-exercises logic implemented in that PR.

**Comment by rtibbles** [comment]
This should now be fixed, as this code is no longer extant in 0.12.0+
