### ISSUE TITLE
warn when kolibri is not run as the `kolibri` user and we expect it to be

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3881]
### Observed behavior

(Kolibri repo work for https://github.com/learningequality/kolibri-installer-debian/issues/41)

When installed using the .deb package, a new `kolibri` user is created and its this user which runs the Kolibri process when the system service is started.

However we [run into problems](https://github.com/learningequality/kolibri/issues/3274) when users run kolibri commands via the command line because the local process has a different `KOLIBRI_HOME` folder than the service process.

### Expected behavior

* We should warn when the process is run as a separate user and the `kolibri` user exists. This can roughly [follow the implementation in KA Lite](https://github.com/learningequality/ka-lite/blob/master/bin/kalite#L53).
* We should update the documentation to clarify that when installed as debian, commands should be run as `sudo service kolibri [command]`, not `kolibri [command]`
* We should consider _not_ adding kolibri to the path so users can't make this mistake. (Why is it on the path?)

### User-facing consequences

Lots of confusion and sometimes broken installations

### Steps to reproduce

Install as a debian package and then run commands as a normal user.

### Context

k 0.10.0

**Comment by indirectlylit** [comment]
If there is no `~/.kolibri` folder in the current user's home dir, and the current user does not match the debconf-set user, then display a warning that:

* Kolibri was previously installed as a system service under a different user
* If you want to run kolibri commands using the system service's data, run using `sudo -u {} kolibri ...` where the user is picked up from teh `KOLIBRI_USER` environment variable
* Alternatively, if you want to continue and run using separate data & content as current user, type 'y'

**Comment by lyw07** [comment]
@benjaoming I saw the comment above, I'm wondering why do we need to check if there's a `~/.kolibri` folder in the current user's home directory. I'm thinking that whether the folder exists in the current user's home directory or not, we always need to ask the user if they want to continue to run kolibri as this current user or kolibri user. Or am I missing some cases here? Thank you!

**Comment by benjaoming** [comment]
@lyw07 - no, if the folder exists, it means that they have already been running `kolibri` as that user. We should not prompt users every time, only the first time!

**Comment by lyw07** [comment]
@benjaoming I see. Then what if the user installs kolibri through pip/pex before debian installer, so they have already had a `~/.kolibri` in current user's home directory before having the KOLIBRI_HOME directory in the KOLIBRI_USER's home directory. In this case, the prompt will not show up for the first time the user starts kolibri from the debian installer. Thanks for the explanation!

**Comment by benjaoming** [comment]
That is okay, we won't stand a chance to fix edge cases like this :) But I'm fairly confident that the .pex and the .deb won't be installed on the same system for future releases, since the .deb will be the go-to option on the Download pages for anyone on Debian systems.

We are doing changes in the .deb that _will_ in fact run the system service as the desktop user, so there won't even be a mixup :)

**Comment by lyw07** [comment]
thank you! it totally makes sense to me now
