### ISSUE TITLE
Insufficient options for correct i18n in AssignmentChangeStatusModal

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#3882]
### Observed behavior
When observed in UI language with gendered adjectives as Spanish, option labels in the status change modal for Lessons and Exams will always display incorrectly in one of those two. 

At first I thought it was my error while translating, but after digging deeper, it seems to be more than that. If I'm interpreting the code correctly, the `AssignmentChangeStatusModal.vue` component is (re)used in both cases, even though in languages other than English, Lessons and Exams might be adjectives of different genders. In Spanish *Lesson* is **Activa** but *Exam* is **Activo**.

![selection_005](https://user-images.githubusercontent.com/1457929/41815339-2101587a-7768-11e8-8d67-7d56d1ebb2f7.png)

I can appreciate the "reuse" philosophy, but in this case the result is too DRY for the correct i18n. Since we are past the string freeze, I've changed the translation on Crowdin to verbs (**Activar/Desactivar**), and my suggestion is to do the same for the next release, namely, [make the following change](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/assignments/AssignmentChangeStatusModal.vue#L79):

```
      activeOption: 'Activate',
      inactiveOption: 'Deactivate', 
```

Not much we can do in the `assignments/StatusIcon.vue` at this point, but it is probably going to need to get a bit wet in the future.

### User-facing consequences
Incorrect UI text that reduces understanding.

**Comment by indirectlylit** [comment]
Yeah the simplest change at this point would be to make two new props, `activeOptionText` and `inactiveOptionText`. Then the specific strings can be passed in the same way as `modalTitle` and `modalDescription`.

It's quite possible that the current implementation is "too DRY" because the abstract component is only used twice, violating the ["rule of three"](https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)). However given that we're trying to consolidate the exam and lesson experiences, I can see it potentially being reasonable here...

**Comment by radinamatic** [comment]
I agree with the consolidation strategy, but as long as the same components that involve noun or adjective strings are going to be used to refer to different concepts (Lessons/Exams in this case) that might require gender differentiation, I don't see an alternative to the "duplication". 

If we can consolidate on using verbs that risk is reduced, hence the interim solution I proposed.

**Comment by indirectlylit** [comment]
migrated the `StatusIcon` issue to #4288 as a lower priority

**Comment by DXCanas** [comment]
@radinamatic wouldn't the correct noun be "Activa"/"Inactiva" here? As in "Una lección activa", since the title of the modal is "Cambiar estado de lección"? I was a little thrown off by the pluralization.

**Comment by radinamatic** [comment]
@DXCanas You are right, that version of the translation is suboptimal too. That's why I suggested the verb form, and in fact in latest translation QA round I changed it to `Activar/Desactivar`, since, as you point out, we do title the modal `Cambiar el estado de lección` (Change the lesson status), that is, we demand an **action** from the user, which would indicate that the verb is more appropriate.

**Comment by indirectlylit** [comment]
the only problem is then there are two verbs in a row: 'activate' and then 'save'

![image](https://user-images.githubusercontent.com/2367265/45837249-c421e380-bcc3-11e8-86d1-4f1ceb23dbf6.png)

I think one thing that's confusing here is that the radio buttons are separated from the modal title by the description, which breaks up the flow.

Here's my recommendation:

![image](https://user-images.githubusercontent.com/2367265/45837419-28dd3e00-bcc4-11e8-9051-ff8626786030.png)

thoughts?

**Comment by indirectlylit** [comment]
(cc @jtamiace)
