### ISSUE TITLE
small layout regression

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3892]
### Observed behavior

Just going based on the screenshots in #3890 in the first row:

![image](https://user-images.githubusercontent.com/2367265/41884856-2a358932-78aa-11e8-8ec0-73b79637a77c.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/2367265/41884860-31d63b00-78aa-11e8-9e93-633be6ef80b4.png)

### Context

0.10.0

**Comment by christianmemije** [comment]
Was fixed in https://github.com/learningequality/kolibri/pull/3890/commits/14ba7333fcfc01352d6b1709723c26b79db2c2a0
