### ISSUE TITLE
User inputted text and content text should have dir attribute

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3899]
### Observed behavior

All user inputted text and content text should have dir attribute.
This includes user names, class names, etc.
Coach report columns, titles in exam cards, etc.
Related to #3864
Semi-related: https://github.com/learningequality/kolibri/issues/2395
Examples

![localhost_8000_coach_ nexus 7 19](https://user-images.githubusercontent.com/7193975/41932786-d83bc3c0-7936-11e8-96c4-59487d575dcb.png)

![localhost_8000_user_ nexus 7](https://user-images.githubusercontent.com/7193975/41932789-d94fa75e-7936-11e8-9046-6e821a6921ff.png)

### Expected behavior

Proper direction.

### User-facing consequences

Illegible text. 

### Context

0.10

**Comment by jonboiser** [comment]
Mostly fixed in #4314. Will probably need to vendor Keen-UI components to get this fixed in e.g. ui-textbox.
