### ISSUE TITLE
Best way for a plugin to define new content?

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#39]
Hi,

Kolibri looks exciting! In the future, I'm wondering how external contributors can create plugins to add new content. For a concrete example, let's say I want to bundle ipython notebooks and view them using [nbviewer](http://pvbookmarks.readthedocs.org/en/latest/devel/languages/python/tools/ipython/notebooks/tools/nb_viewer/).
1. How can I create my own channel, and upload the files necesary to view 1 content node?
2. How can a plugin declare that it now handles the new content from that channel?
3. How can I integrate with the download interface to have it retrieve the files necessary to view the content?

Thanks for the help!

**Comment by indirectlylit** [comment]
In general, this would involve implementing a new content renderer plugin. Current examples are:

* mp3 audio
* mp4 video
* pdf documents
* perseus exercises
* html5 widgets coming soon...
