### ISSUE TITLE
Learner reports table labels overlap.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3908]
### Observed behavior
Learner reports table labels overlap at the IE 11 and MSedge.
The same behavior with `Groups` and `Recent` tab, the table labels overlap.

### Errors and logs
![screen shot 2018-06-27 at 10 26 07 am](https://user-images.githubusercontent.com/8663934/41949777-734c096a-79f5-11e8-8854-dc68bdcb8b12.png)
![screen shot 2018-06-27 at 10 27 15 am](https://user-images.githubusercontent.com/8663934/41949785-7baf201a-79f5-11e8-97a7-594fa0103709.png)

### Context

 * Kolibri version: 0.10.0b7
 * Operating system: Windows 10 
 * Browsers: IE 11 and MSedge.

**Comment by christianmemije** [comment]
Only affects empty tables. It's an issue with how it handles overflow.
