### ISSUE TITLE
Exam title maximum character validation.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3909]
### Observed behavior
I'm getting an error message when I input more than 150 characters at the exam tittle.

### Expected behavior
We should add maximum character limitation at the exam title.

### Errors and logs
![screen shot 2018-06-27 at 10 52 11 am](https://user-images.githubusercontent.com/8663934/41950646-8a131068-79f9-11e8-83cb-95c8c5c5f072.png)

### Context

 * Kolibri version: 0.10.0b7
 * Operating system: Windows 10
 * Browser: firefox 60.0.2

**Comment by christianmemije** [comment]
Fixed in #3958
