### ISSUE TITLE
Can't submit a learner exam.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3910]
### Observed behavior
I'm a getting a javascript errors when I submit an exam.
I reported this issue at this [PR](https://github.com/learningequality/kolibri/pull/3890#issuecomment-400210654)

### Errors and logs
![screen shot 2018-06-26 at 3 34 19 pm](https://user-images.githubusercontent.com/8663934/41951222-55cd7b24-79fc-11e8-9c6c-c4d8edc6a906.png)

### Context

 * Kolibri version: kolibri 0.10.0b7
 * Operating system: Windows 10
 * Browser: Firefox 60.0.2

**Comment by indirectlylit** [comment]
thanks!

should be addressed by https://github.com/learningequality/kolibri/pull/3894 and will be in the next beta
