### ISSUE TITLE
card box-shadow is clipped

### ISSUE THREAD

**Issue by bonidukic** [learningequality/kolibri#3918]
### Observed behavior
Box shadows of the leftmost cards in the carousels on the _Recommended_ page are cut. As far as I can see, this happens because of the lack of left margin or padding on the carousel container element.

Screenshots:

![selection_353](https://user-images.githubusercontent.com/2150991/42049848-906c9768-7b07-11e8-8b28-ac294928f305.png)

![selection_352](https://user-images.githubusercontent.com/2150991/42049854-9349747e-7b07-11e8-984c-10401fcf6676.png)

### Expected behavior
Box shadow should be displayed in the same manner for all of the cards, regardless of their position within the carousel.

### User-facing consequences
No serious consequences, just a small visual inconsistency

### Steps to reproduce
Visit _Recommended_ page in the _Learn_ module

### Context
- Kolibri version: latest `develop` (Kolibri 0.11.0a2.dev+git.98.gbd06437fa)
- Operating system: Ubuntu 17.10
- Browser:
    - Chrome: Version 65.0.3325.181 (Official Build) (64-bit)
    - Firefox: 60.0.2 (64-bit)

**Comment by khangmach** [comment]
Note that this also happens in carousels on content pages.
