### ISSUE TITLE
Imported channel not showing at the channel list.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3926]
### Observed behavior
After I imported the channel that I created at the studio, the channel doesn't showing at the channel list.
It will show only if I navigate at the channel `import more` option.
### Expected behavior
Channel should show at the channel list after the channel imported.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/42061511-0cdb9844-7b5d-11e8-91ac-fab64450f2ec.gif)

### Steps to reproduce
Import this channel `d4ac57040400486db3ce12c35f7a8c8c` id then select content to import.
After the channel imported, navigate at the channel list by clicking the import button. 

### Context

 * Kolibri version: 0.10.b8
 * Operating system: Windows 7
 * Browser: firefox 60.0.2

**Comment by jonboiser** [comment]
@mrpau-richard I just tried this out and your custom channel does appear in the list. Could you try checking the 'Channels List' again?

If it doesn't show up. Could you look at any network calls to `/api/remotechannel/d4ac57040400486db3ce12c35f7a8c8c `? The channel might not show up if the Studio API request fails.

**Comment by mrpau-richard** [comment]
@jonboiser It show up at the network call. But the channel still not showing at the `content channels` page. 
![screen shot 2018-06-29 at 5 52 26 am](https://user-images.githubusercontent.com/8663934/42062702-f4f45618-7b60-11e8-99f3-41370bbb5da4.png)

**Comment by jonboiser** [comment]
@mrpau-richard could you copy the response to this endpoint?

http://localhost:8000/api/channel/d4ac57040400486db3ce12c35f7a8c8c/?file_sizes=true

here's mine. `on_device_resources` should be greater than zero.

```
{
    "author": "",
    "description": "For testing only",
    "id": "d4ac57040400486db3ce12c35f7a8c8c",
    "last_updated": "2018-06-28T14:42:55.262007-07:00",
    "lang_code": "en",
    "lang_name": "English",
    "name": "mrpau-channel-test",
    "root": "d4ac57040400486db3ce12c35f7a8c8c",
    "thumbnail": "",
    "version": 36,
    "available": true,
    "num_coach_contents": 0,
    "on_device_file_size": 55380239,
    "on_device_resources": 2,
    "total_file_size": 55380239,
    "total_resources": 2
}
```

**Comment by mrpau-richard** [comment]
Here's mine @jonboiser 

```

[
    {
        "included_languages": {},
        "last_updated": "2018-06-28T21:10:09.512190Z",
        "description": "For testing only",
        "total_resources": 2,
        "total_file_size": 55444032.0,
        "lang_name": "English",
        "lang_code": "en",
        "id": "d4ac57040400486db3ce12c35f7a8c8c",
        "name": "mrpau-channel-test",
        "public": false,
        "version": 36,
        "thumbnail": ""
    }
]
```

**Comment by mrpau-richard** [comment]
It says at the device content that I have 52 MB at my channel.
![screen shot 2018-06-29 at 6 05 36 am](https://user-images.githubusercontent.com/8663934/42063062-91b81114-7b62-11e8-946f-541cf3ce9eaf.png)

**Comment by jeepurs** [comment]
I also observed this issue while testing v0.10 on a Raspberry Pi.  I tried to import a channel that was only partially exported to USB. When importing the channel, the option to select all folders was available, thereby misleading me to think I could import a part of the channel that was never there in the first place. There was no error message, but the import finished and the channel doesn't appear in the Channel List (@jamalex also observed this!)

**Comment by jonboiser** [comment]
This is partly expected behavior: We cannot tell which topics are (not) empty on an external device, so we allow users to "select" and navigate into topics which may in fact be empty. But if they were to actually navigate into the topic all the way to leaf nodes, those leaf nodes will not appear (we _do_ know when a leaf node is not available on the drive, by seeing if its corresponding Files exist).

The (maybe) unexpected behavior is that the channel was "partially" available on the USB drive. In that case, if we were to "import" everything that _was_ available on the USB drive, then we would expect those contents to be available on the server after the import.

I'm not sure what really happens when an export is "interrupted". It's possible that the server thinks the USB drive is empty. Could you try importing it again, and navigate through the topics and verify that leaf nodes are available to import manually (instead of picking its container topic)?

**Comment by indirectlylit** [comment]
>  the option to select all folders was available, thereby misleading me to think I could import a part of the channel that was never there in the first place

this is a known and unfortunate limitation of the current implementation

> There was no error message, but the import finished and the channel doesn't appear in the Channel List (@jamalex also observed this!)

This sounds unexpected. If even one item from the channel was imported, the channel should show up in the list

**Comment by jonboiser** [comment]
#3929
