### ISSUE TITLE
Resolved value for ContentNodeResource.getCollection turns progress_fraction to Promise

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#3927]
### Observed behavior

Here's how I observed this

As a Learner,

1. View a Lesson Playlist (no problem here)
1. View a Lesson Resources
1. Exit back to the Lesson Playlist
1. Observe this error:

Also observed in normal Learn Browse Pages going from Topic -> Some Video -> Topic.

```
vue.runtime.esm.js:587 [Vue warn]: Invalid prop: type check failed for prop "progress". Expected Number, got Promise.

found in

---> <ContentCard> at kolibri/plugins/learn/assets/src/views/content-card/index.vue
       <LessonPlaylistPage> at kolibri/plugins/learn/assets/src/views/classes/LessonPlaylistPage.vue
         <AppBody> at kolibri/core/assets/src/views/app-body.vue
           <CoreBase> at kolibri/core/assets/src/views/core-base.vue
             <Root>
```

At this line 

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/state/actions/classesActions.js#L94,

the resolved value for contentNodes has one array entry (for the resource I actually viewed) where `contentNode.progress_fraction` is of type Promise instead of type Number.

In this situation, I can fix this by force fetching from `ContentNodeResource.getCollection()`.

### Expected behavior

`contentNode.progress_fraction` always is a Number.

### Context

Develop branch + vuex 3 upgrades

**Comment by rtibbles** [comment]
This does not appear to be extant on current develop.

**Comment by indirectlylit** [comment]
still looks like an issue. let's address under #4269
