### ISSUE TITLE
Exam report and exam page not working at the IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3928]
### Observed behavior
Exam exercises not showing its content at the exam page and report page.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/42063851-46e3bf72-7b66-11e8-9f3d-19b537f04d72.gif)
![screen shot 2018-06-29 at 6 27 49 am](https://user-images.githubusercontent.com/8663934/42063927-b07ad164-7b66-11e8-8d48-ac2a21692da0.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.0b8
 * Operating system: Windows 7 32 bit
 * Browser: IE11

**Comment by indirectlylit** [comment]
Hi - could you please provide a bit more information? For example:

* what content is this?
* any errors in the browser or server?
* does it _only_ happen on IE or is it broken on all browsers?

thanks!
