### ISSUE TITLE
topics with no content visible to learner are accessible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3937]
### Observed behavior

http://kolibribeta.learningequality.org/learn/#/topics/t/d744f75a620742b293e44f070e5ba5cb

| viewed as learner | viewer as admin |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/42109422-6e6f5c96-7b92-11e8-82c9-c099b7c4ff68.png) | ![image](https://user-images.githubusercontent.com/2367265/42109429-773bdb60-7b92-11e8-9450-30cbe5a3653a.png) |

### Expected behavior

as a learner, directory should not be visible from parent:

![image](https://user-images.githubusercontent.com/2367265/42109458-8c9a1116-7b92-11e8-924c-77ee9942b624.png)

### User-facing consequences

confusing topic tree for learners

### Steps to reproduce

as a learner, navigate to a topic that contains only coach content

### Context

0.10.0

**Comment by jonboiser** [comment]
Could we require when these kinds of topics are curated that the topic itself be flagged as coach content if 100% of its descendants are coach content?

**Comment by rtibbles** [comment]
The coach content annotation is meant to be doing this already. Was this content reimported after the upgrade to beta 8?

**Comment by jonboiser** [comment]
It could be possible that it was not. I just  installed this channel on beta8 and I don't even see the channel as a learner.

And going directly to the topic with the URL, the 2/2 coach content topic doesn't appear.

**Comment by indirectlylit** [comment]
Great. This issue can be closed, as no users will be affected
