### ISSUE TITLE
handling of exercises with no questions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3938]
### Observed behavior

It's possible to create an exercise on Studio with no questions.

* Coaches can create an exam which includes question-less exercises
* Learners who encounter the exercise see infinite loading:
    ![image](https://user-images.githubusercontent.com/2367265/42110005-76e1e734-7b94-11e8-8bb4-244582063cf5.png)

### Expected behavior

We should probably hide empty exercises from the UI entirely

### User-facing consequences

unexpected behaviors

### Steps to reproduce

create and import a channel with empty exercises

### Context

0.10.0

**Comment by indirectlylit** [comment]
Reported by @jtamiace. @jayoshih we might also consider trying to prevent this on the studio side?

**Comment by jonboiser** [comment]
I think the easiest thing to do would be to not hide these kinds of exercises, because of how fragmented the ContentNode APIs are. We would need to filter the querysets in a lot of places.

I think a message like "This exercise has no questions" instead of the progress bar would be fine.

**Comment by rtibbles** [comment]
That seems reasonable, especially as this is something that should not be allowed in publishing to start with.

**Comment by jonboiser** [comment]
I'm wondering if this is still possible after some recent changes.

I tried creating an exercise with no questions and I'm not able to import it since its `importable` field is false.

**Comment by indirectlylit** [comment]
okay, closing and we can re-open if it reappears
