### ISSUE TITLE
coach-content flag does not seem to be updated after re-publishing and updating

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3939]
### Observed behavior

reported by @radinamatic:

* Imported a channel with coach content (token `nakav-mafak`, channel name "CK 12 Testing"), I can see it as admin or coach, but not as learner.
* Updated the channel on Studio, received the email, correctly updated it on http://kolibribeta.learningequality.org/ and I still cannot see it as the learner

### Expected behavior

Coach content should update as expected

### User-facing consequences

difficult or unable to update state of coach content

### Steps to reproduce

Might have been an issue with that particular channel, as I've just created another with some coach content, and can see it OK as learner. Might be good to check anyways as Studio issue, when updating old channels?

### Context

0.10.0

**Comment by radinamatic** [comment]
Replicated similar state on an upgrade scenario from 0.8 to the tagged 0.10 release. `CK 12 testing channel` has been updated on Studio, I can see it as admin, still not as learner, but if I build an exam or a lesson with its resources, they do appear visible to learners.

Still not sure if this is a Studio or Kolibri issue or both... 😕 

![2018-07-02_2-59-43](https://user-images.githubusercontent.com/1457929/42140908-1f8d3aca-7da5-11e8-9207-7b796d5faec4.png)

**Comment by radinamatic** [comment]
Another detail from the fresh install of 0.10 on Windows 10, that I don't remember noticing before, content is visible under Recommended for learners, by not under Channels:

![2018-07-02_3-55-57](https://user-images.githubusercontent.com/1457929/42141866-4ec88536-7dac-11e8-93ee-d930fc931824.png)
