### ISSUE TITLE
Some KA content is missing assets

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#3941]
### Observed behavior

Visit http://kolibribeta.learningequality.org/learn/#/topics/c/e7350f4cd75a58f7bda6b5f51b8f468e

**Comment by indirectlylit** [comment]
I believe this is a content issue?

**Comment by ralphiee22** [comment]
This exercise no longer shows up on the demo server so I will be closing this issue. If one can give a breadcrumb that leads to missing content then we can reopen.

**Comment by ralphiee22** [comment]
Demo site has been updated and content is confirmed as showing.
