### ISSUE TITLE
PDF rendering problem in PraDigi content

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#3948]
### Observed behavior

Weird `$` appear in middle of text in PDF on K: http://pradigi-demo.learningequality.org/learn/#/topics/c/ea0eeab6f91d5bcc8147b03c594afd1f
Original PDF seems OK: http://www.prathamopenschool.org/CourseContent/PDF/Reading_Cards_6_H.pdf

<img width="316" alt="dolla dolla signs yo" src="https://user-images.githubusercontent.com/163966/42129878-66bc9928-7ca0-11e8-9aec-ee747fa72b08.png">

### Context
 * Kolibri 0.10.0.dev1
 * Operating system
 * Browser: chrome and ff

**Comment by indirectlylit** [comment]
this is likely a problem with pdf.js

Can it be reproduced using their demo? https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by indirectlylit** [comment]
answer: no

**Comment by ivanistheone** [comment]
So is this related to way we use pdf.js, or maybe a bug in the specific version we're using? (I'm assuming the online demo is using the latest version of pdf.js)

**Comment by christianmemije** [comment]
Encoding issue cannot be replicated in latest 0.10, which uses "pdfjs-dist": "^1.9.426". Version was last bumped in https://github.com/learningequality/kolibri/commit/ca34626d7fa39203e6a3aa396a7d9927d48d5ca1#diff-e7a8de5cd277eb87eb1384eaeeb1cd6f

![image](https://user-images.githubusercontent.com/7193975/42351277-f4847610-8068-11e8-8ad6-0f92ed27c4c3.png)

**Comment by ivanistheone** [comment]
Confirm fixed by updating demo site to 0.10: http://pradigi-demo.learningequality.org/learn/#/topics/c/ea0eeab6f91d5bcc8147b03c594afd1f
