### ISSUE TITLE
Import from Kolibri studio disabled

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3949]
### Observed behavior
I can't import a channel from kolibri studio, it will automatically disabled after I clicked the import button.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/42142081-0370ca24-7de0-11e8-990a-e0e1cc2272c0.gif)

### Context

 * Kolibri version. v0.10.0
 * Operating system Windows 10
 * Browser firefox 61.0

**Comment by mrpau-richard** [comment]
This happened only during the fresh installation. but after I restart the Kolibri server,  the Kolibri studio is enabled and I can now import a channel from the Kolbiri studio.

**Comment by indirectlylit** [comment]
Does this happen after every fresh installation, or is it something that you only observed once?

**Comment by indirectlylit** [comment]
Are there any relevant server logs?

**Comment by mrpau-richard** [comment]
Can't reproduce this issue at the new 0.10.0 released. @radinamatic told me that the reason, why the kolibri studio import is disabled it's because there is no internet connection on the device that Kolibri is running. I think that's cause on this issue. Closing this.

**Comment by radinamatic** [comment]
Will be avoided when  #4275 is merged.
