### ISSUE TITLE
errors in VideoRenderer component

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3972]
### Observed behavior

```
http://localhost:8000/learn/#/recommended/245f0f2f45c446168a1c9fbf34ffcab1
```

![image](https://user-images.githubusercontent.com/2367265/42341317-890f3526-8047-11e8-9506-d4152d1aeb56.png)

### Expected behavior

no errors

### User-facing consequences

unknown

### Errors and logs

```
 Invalid prop: custom validator check failed for prop "supplementaryFiles".
```

```
Duplicate keys detected: '/content/storage/e/4/e4c064c9a558810a89a585da27d88835.vtt'. This may cause an update error.
```

### Steps to reproduce

navigate to content item `245f0f2f45c446168a1c9fbf34ffcab1` in the Kolibri Demo channel `bcd99d8aeef04ce6b9e25a88d87eedb7`1

### Context

v0.11.0

**Comment by jonboiser** [comment]
Not seeing these errors at the moment. Can't find the exact video in the OP, but have tried several videos from the Kolibri Demo channel.

**Comment by indirectlylit** [comment]
I would find a video that you know has subtitles and test that, because those are likely the `supplementaryFiles`.

If you still don't repro, please close

**Comment by jonboiser** [comment]
Not seeing this at the moment in Lessons or in Learn page. Tried with several Touchable Earth videos with captions.
