### ISSUE TITLE
setup wizard layout is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3974]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/42341536-3da0ec28-8048-11e8-8710-be5806653892.png)

### Expected behavior

not broken

### User-facing consequences

inconsistency/ugliness

### Steps to reproduce

set up Kolibri fresh

### Context

0.11.0

**Comment by christianmemije** [comment]
Whitespace issue

**Comment by christianmemije** [comment]
Fixed in #3980
