### ISSUE TITLE
Class coach option layout broken.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3982]
### Observed behavior
Class coach option layout is broken.

### Errors and logs
![screen shot 2018-07-06 at 10 19 33 am](https://user-images.githubusercontent.com/8663934/42356748-cf039364-8106-11e8-882b-a278041594e9.png)

### Context

 * Kolibri version: 0.11.0-alpha3
 * Operating system: Windows 10
 * Browser: firefox 61.0.1

**Comment by indirectlylit** [comment]
should be addressed by #3980 - please let me know if it's still there in alpha4
