### ISSUE TITLE
The new learners and coachs account, can't view the kolibri 0.11.0a3 at first login

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3987]
### Observed behavior
When I create a learners account and test to login, the page show like this "The requested URL / was not found on this server."

### Expected behavior
Must login to kolibri page.

### Errors and logs
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. 127.0.0.1:8080 
```

…

### Steps to reproduce
1. login with admin account
2. go to facility and user tab
3. create new learner account
4. try to login the new learner account and see the error page.

…

### Context
Windows 7 and 10
kolibri 0.11.0a3
firefox 61.0.1(64-bit)

### Screenshot
![errorloginpage](https://user-images.githubusercontent.com/38421180/42367122-fb1ae096-80b7-11e8-9165-6e73b2702a72.png)

**Comment by indirectlylit** [comment]
Is there any chance that multiple Kolibri or Python processes are running simultaneously?

**Comment by christianmemije** [comment]
This is an issue with the way we handle `first_login` 
@rtibbles
https://github.com/learningequality/kolibri/blob/e9a394ac7d31aa15bfaa3ed86c84c17ba3182040/kolibri/core/views.py#L95

**Comment by rtibbles** [comment]
Yeah, the first login flag needs to be amended slightly to fall back to the non first login if not available. Will fix.
