### ISSUE TITLE
add new group have a small scroll bar

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3989]
### Observed behavior
I see a small scroll bar on add new group

### Expected behavior
no scroll will show up.

### Context
windows 7
kolibri 0.11.0a3
firefox 61.0.1 (64-bit)

### Screenshot
![small scroll bar](https://user-images.githubusercontent.com/38421180/42369526-143ce946-80bf-11e8-9be9-8d6f552d7529.png)

**Comment by jonboiser** [comment]
The character counter might have added to the vertical height of the form, causing that overflow.

**Comment by indirectlylit** [comment]
we just committed a change that might have resolved a few of these layout issues: #3980 

mind retesting with the new beta? https://github.com/learningequality/kolibri/releases/tag/v0.11.0-alpha4

**Comment by indirectlylit** [comment]
closing - please re-open if you see it again
