### ISSUE TITLE
Merge upwards starting from 0.6.x

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3990]
### Observed behavior

In tried going from 0.6.x to 0.7.x, and there are merge conflicts in `yarn.lock` and `package.json` that I can't resolve.

If someone can merge 0.6.x into 0.7.x, I can do the rest.

 * [ ] 0.6.x into 0.7.x: Merge conflicts
 * [ ] 0.7.x into 0.8.x: Almost works! (just the cherrypy fix left) :+1: 
 * [ ] 0.8.x into 0.9.x: Almost works! (just the cherrypy fix + version numbers left) :+1: 
 * [ ] 0.9.x into 0.10.x: Almost works! (just the cherrypy fix left, however the cherrypy fix got cherry-picked) :+1: 
 * [ ] 0.10.x into develop: Works :+1: (because @rtibbles just did it)
 * [ ] Rename unsupported branches <0.6 (suggesting `deprecated-v0.1.x`)

I also found some dependencies seem to be listed twice in `yarn.lock` since 883795a867d681dbea8756649c7fe8c84fca44de - a commit for 0.6.x, this might as well be solved in the same go.

**The over-serious blahblah....**

If we want to support older release branches, then the practice of putting updates into old release branches and not merging upwards immediately after, can end up as a dangerous show-stopper to any plans of Long Term Support.

We'll quickly*) end up at a point where no single individual is able to easily merge release branches without involving a lot of people, looking through git blames etc... or we'll just have to cherry-pick everything.

*) Quickly = give or take, a few updates on an old release branch, w/o merging forwards, with the sort of time pressure that everything is being released under, then I just anticipate that a lot more decisions like "not right now" are going to be made.

### Expected behavior

All branches should be merge-able upwards. Otherwise, branches should be left explicitly unsupported (for instance by renaming them).

### User-facing consequences

 * Accidental regressions in future releases.
 * Delays for patch updates to older release branches because they cannot receive updates from previous release branches that also received updates.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

Instead of picking the right approach, the fix for 0.6.x got cherry-picked all the way up. Not sure why this was done.

https://github.com/learningequality/kolibri/pull/3969

**Comment by indirectlylit** [comment]
we can probably forget about the 0.6 merge? We're current, so perhaps let's just make sure to stay current in the future

**Comment by benjaoming** [comment]
We could make it more evident which branches are "left behind", i.e. rename them. But I have to say that I don't really know which branches have become unmerge-able. But once they have, I think they're also *unsupported* given that any kind of fix committed to the branch will be difficult to propagate to newer branches.
