### ISSUE TITLE
Missing user feedback and error messages during channel listing and import

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3997]
### Observed behavior

Missing user feedback has caused problems, also before 0.10, and result in unclear information for troubleshooting and issue reports.

> "Generating channel listing. This could take a few minutes…" took so long I looked in the logs, attached. Seems like there are various issues.

Either we quickly implement error handling in the most critical progress tracking parts (channel listing and import/export), or we wait for a proper Activity Manager to be implemented #3494 

Related issues:

 * #3963
 * #3620
 * #3494 

### Expected behavior

If something (anything!) is broken in the channel listing, the user should see it. Even exception messages are more helpful than nothing at all.

### User-facing consequences

Users waiting for no reason for hours due to lack of guidance. Blowing up instantly with a huge ugly exception, would be the lesser of those evils!

### Errors and logs

See #3963

### Steps to reproduce

Unplug your network cable while activities are happening.

### Context

Since Channel listings were introduced.

**Comment by benjaoming** [comment]
> Incidentally, there is a visual indication when an error occurs. A red exclamation mark appears next to "Generating channel listing. This could take a few minutes…"

This likely means that the issue is easier to fix than I initially thought, because the frontend already knows that something has error'ed. However, the current feedback does not guide the user to stop waiting or indicate that the process has halted. Or why (for troubleshooting).

**Comment by indirectlylit** [comment]
this is being addressed in ongoing changes to 0.13.0

**Comment by benjaoming** [comment]
@indirectlylit I'm seeing a couple of issues closed with "this is being addressed in ongoing changes to 0.13.0"

Does it mean I should triage them according to the filed issues? Now? Or later?

Since they have the 0.13 milestone, they could be easy to dig up and triage once the PRs have landed?

Am always happy to give feedback according to issues I've opened :)

**Comment by indirectlylit** [comment]
There are dozens of Kolibri issues and clearinghouse feedback notes that were taken into account during the design work leading up to the [0.13.0 content management upgrades](https://www.notion.so/learningequality/Kolibri-0-13-0-content-management-upgrades-81e2e3aeb38942aa930498c18c17a9d7) project. Because this is a very large change spread across many PRs, it did not seem feasible or worthwhile to try to associate every issue with a specific "fixed by" PR.

Please feel free to open new follow-up issues and clearinghouse notes if you encounter issues with the new implementation or design, respectively. It will be easiest to wait until beta testing begins unless you want to dig through Notion and Figma docs.

**Comment by indirectlylit** [comment]
FYI, here's a good overview of what's being tackled at a high level:

https://docs.google.com/drawings/d/1R-ACapv72bDEx_IptRD7EkVtrz4j4Zz-tk12dNVRTJY/edit

**Comment by benjaoming** [comment]
Thanks for sharing @indirectlylit 

Old-school bug trackers have several stages, rather than "Open" and "Closed". Wondering a bit how we can solve this for Github for 0.13 beta testing - am thinking that by being a bit creative, one way of using the interface would be to search for all "my tickets" tagged with the 0.13 milestone, as in:

"What issues have I opened that are assumed fixed in the 0.13 beta?"

(this solves it for me!)
