### ISSUE TITLE
sqlite3-wal got too big file size.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4006]
### Observed behavior
After I import the Khan Academy(English) channel and browse its downloadable contents the `sqlite3-wal` changed the file size to almost 1gb. This happened without downloading any contents from Khan Academy(English).

### Errors and logs
![screen shot 2018-07-10 at 2 24 37 pm](https://user-images.githubusercontent.com/8663934/42493017-cd59d98e-844d-11e8-9430-df5a847ce10f.png)

### Context

 * Kolibri version: 0.11-0a4
 * Operating system: Windows 10
 * Browser: firefox 61.0

**Comment by jredrejo** [comment]
This is quite easy to reproduce, using a clean database (time on the left)
(**Note**: done using Kolibri from develop, in a powerful computer and a nice Internet fiber connection)
19:21 wal file size= 3 Kb
19:21 Manage Content - Import - Khan Akademy
19:23 choose Math
wal file size = 1.3 Gb
Select Early Math - Counting
Select Numbers 0 to 120 => 6 resources (4MB)
19:25 Import 
Finished in less than 10 seconds
wal file size = 1.3 Gb

Then,
19:25 KHan Academy -> Delete the content imported previously
Preparing .....
19:37.....
19:38 Removing channel 0.10%
wal file size =  4.1 Gb
19:40 100% Finished
wal file size = 4.1 Gb


Analyzing the problem, it's clearly a problem in the wal file getting very fragmented. Doing a VACUUM instruction makes wal pass from 4.1 Gb to 0 bytes.

We have two options:
a. Set a pragma with AUTO_VACUUM=Full;
b. Do a DB vacuum when Kolibri starts and after an operation of importing/deleting content from a channel, as this is the operation that produces more fragmentation

Option 'a' has two important problems:
1. It might delay inserts as vacuum needs to move all the data to a temp wal file to unframent.
2. It does not work if the tables are already created nor any connection is done to the db. It will require a special migration for existing databases.

For this reason I am working in option b to solve the problem, unless a better idea is suggested (@rtibbles , @bonidjukic , @jamalex )
