### ISSUE TITLE
Add new account has bug when selecting a user type.

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4016]
### Observed behavior
Observe when I add new account and selecting the user type, the scroll bar will show. I think this is a bug.

![add new account have bug](https://user-images.githubusercontent.com/38421180/42544656-9fb3536e-84e5-11e8-9fdf-c59207cf467a.png)
  

### Expected behavior
no scroll bar and user type show in full list of details.

### Steps to reproduce
1. login with admin account
2. go to facility page and user tab
3. add new account and choice in user type to see the bug.

### Context
 Kolibri version : 0.11.0a4
 Operating system : windows 7
 Browser : Firefox 61.0.1

**Comment by indirectlylit** [comment]
thanks @mrpau-julius -

would you mind checking if this happens on 0.10?

**Comment by mrpau-julius** [comment]
@indirectlylit  it's not exists on 0.10 only in 0.11.x

**Comment by christianmemije** [comment]
I'm going to say this is not a bug.

**Comment by indirectlylit** [comment]
I've followed up with a more general issue: learningequality/kolibri-design-system#356
