### ISSUE TITLE
device and facility not shown, when upgrading kolibri 0.7.2 to 0.11.0a4 

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4021]
### Observed behaviour
Observe when I upgrade the kolibri 0.7.2 to 0.11.0a4, the device and facility not shown up.

![admin-role](https://user-images.githubusercontent.com/38421180/42670191-f160a50c-868b-11e8-857b-cedb9ceafda2.png)
![device and facility are not availble](https://user-images.githubusercontent.com/38421180/42670195-f5bb4cf6-868b-11e8-9f7a-835997efbc3c.png)

### Expected behaviour
Must show the device and facility

### Context

upgrade to kolibri 0.7.2 to 0.11.0a4
Windows 7
firefox 61.0.1

**Comment by indirectlylit** [comment]
does this mean that you got logged out?

**Comment by mrpau-julius** [comment]
@indirectlylit no, when I login as a superuser/admin, I didn't seen the device and facility.

**Comment by indirectlylit** [comment]
possibly-related issues: #3805, #3806

**Comment by jredrejo** [comment]
@mrpau-julius can you confirm that the bug disappears the second time you start kolibri, after the migration?
I.E.:
- first time you run it, it migrates the data and this bug appear
- second time you run it, nothing is migrated and device and facility are shown.
