### ISSUE TITLE
User taken out of channel navigation when accessing next step activity

### ISSUE THREAD

**Issue by JasonTame** [learningequality/kolibri#4022]
### Observed behaviour

After completing an activity, Kolibri recommends a next step. 

<img width="1224" alt="next_step_modal_topic" src="https://user-images.githubusercontent.com/15672948/42677717-e5f95290-867c-11e8-9516-518a7bcb1e81.png">

If that next step is a topic folder, then the breadcrumbs correctly displays the breadcrumbs navigation. 

![correct_navigation](https://user-images.githubusercontent.com/15672948/42677731-f593a75a-867c-11e8-81a8-ed2f6f47d63e.png)

However, if the next step is another activity in the same topic folder, the breadcrumb changes to Recommended -> Name of Activity 

<img width="1278" alt="next_step_modal" src="https://user-images.githubusercontent.com/15672948/42677764-147fb6d6-867d-11e8-9ce3-4ca7d15ee8e1.png">

![recommended_breadcrumb](https://user-images.githubusercontent.com/15672948/42677902-8195a672-867d-11e8-8f2d-a72579215b10.png)

### Expected behaviour

The breadcrumbs navigation pathway doesn't change, so the user doesn’t need to go all the way back through the channel navigation to get to where they were. 

### User-facing consequences

Mostly just minor frustration as users need to go through all the layers of channel navigation again.

Another issue is if users complete the recommended activity, they won't be taken to the next activity within the topic they were on, so they could also get lost.

**Comment by indirectlylit** [comment]
cc @jtamiace @DXCanas I think you two were looking at this or something similar recently?

**Comment by jtamiace** [comment]
Only similar in the confusing navigation, but this appears to be a different issue. The other issue led a user who clicked on a topic folder in "Recommended" on the home page to a breadcrumb with "Recommended >" instead of the topic tree breadcrumb

The intended design in this reported issue was definitely to have the breadcrumb represent the spot in the topic tree, not "Recommended > [Title]"

**Comment by JasonTame** [comment]
I can work on a fix for this issue, if no one else is working on it already?

**Comment by rtibbles** [comment]
Which version of Kolibri is this on, for context?

**Comment by JasonTame** [comment]
I tested on the kolibri demo channel, so 0.10.0

**Comment by DXCanas** [comment]
@indirectlylit - iirc, the conclusion we arrived at during that meeting was that topic tree should be the only place we view content, meaning we kill the "Recommended" URL and corresponding views? If that ends up being the case, I think this would be resolved?

**Comment by indirectlylit** [comment]
@DXCanas yes, that sounds right to me - but just for links coming from anywhere in 'Recommended'. (There are other contexts with their own content views, e.g. inside a lesson.)

@JasonTame you're welcome to work on a fix, and it would be appreciated! I'd recommend quickly reviewing our [dev workflow docs](http://kolibri-dev.readthedocs.io/en/develop/references/development_workflow.html).

If the change ends up being relatively small and simple, we can target the `release-v0.10.x` branch; however if it turns into something at all risky we'll have to target `develop` instead.

You're welcome to either tackle the narrow task (fixing just this one link) or the broader task that @DXCanas suggested (changing all 'recommended content' links to 'topic tree content' links and deleting the recommended content views from the source code).

In practice, you'll be looking for links to the `RECOMMENDED_CONTENT` page and replacing them with links to `TOPICS_CONTENT`. The specific instance described in your ticket is here:

https://github.com/learningequality/kolibri/blob/30a3da8b80e8c925a130bb481390f73f62ef31c1/kolibri/plugins/learn/assets/src/views/content-page.vue#L225-L231

**Comment by JasonTame** [comment]
@indirectlylit Cool, thanks for the guidance! I've changed the link in content-page.vue, recommended-page.vue and recommended-subpage.vue.
