### ISSUE TITLE
add facility setting to disable 'guest' browsing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4023]
### Observed behavior

Some organizations prefer that their users always be logged in

### Expected behavior

A facility setting can be added, e.g. "Disable guest access".

When this setting is active:

* "Access as guest" is hidden on the log-in page
* When a user visits a page without an active session, they are redirected to the log-in page

### User-facing consequences

Sometimes students are accessing as a guest because it's easier than dealing with a log-in

### Context

k0.10.0

----

cc @jtamiace @rtibbles this seem reasonable?

**Comment by jtamiace** [comment]
Seems reasonable to me. The setup wizard would be a touchpoint for this change, so will think about how this new setting should fit in

**Comment by jtamiace** [comment]
It might make sense for this to be the third step in the setup wizard

<img width="1163" alt="screen shot 2018-07-16 at 2 27 39 pm" src="https://user-images.githubusercontent.com/6668144/42784564-7737c794-8904-11e8-93ff-7c8e0d8ef37f.png">

Here's the rest of the onboarding prototype for review
https://www.figma.com/file/CiaGXfI6OMOjBF9e8hr1c1Ap/Onboarding-0.11-updates
