### ISSUE TITLE
Duplicated questions in exams

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4028]
### Observed behavior
When adding exercises to an exam from a topic that has repeated content nodes within it (like the top level KA channel when some of the elementary maths exercises have been imported). Each copy of the exercise will be rendered distinctly in the exam. This can lead to the same question being repeated in the exam.

### Expected behavior
Dedupe exercise nodes by content_id on exam creation.

### User-facing consequences
Confusing exams.

### Steps to reproduce
1. Import an exercise that is repeated across multiple topics (e.g. any of the exercises in the Khan Academy Counting topic).
2. Create an exam by selecting a topic that has that exercise in it more than once (e.g. the 'Math' topic in KA).
3. Preview the exam and see the same question repeated (but being drawn each time from a different copy of the exercise.

**Comment by jonboiser** [comment]
A fix for this was put in #4086 could @mrpau-dev or someone else provide some additional testing?

**Comment by mrpau-richard** [comment]
Okay @jonboiser we will do a testing on this. Thanks 😄

**Comment by mrpau-richard** [comment]
@jonboiser I observed during my testing, There's still some exam exercises that has the same question but different answer added in the exam. 
![temp](https://user-images.githubusercontent.com/8663934/46338617-3d75ea80-c663-11e8-806c-cfd68820e3d6.gif)

I used the Kolibri-0.11.0a7 version to test this.

**Comment by mrpau-julius** [comment]
Hi @jonboiser I tested this in windows 10. I observed, when I creating an exam having 10 items, but the "Counting objects" topic contain 3 exercises. When I click preview, there are repeating questions, but different choices.
For me, it is good idea to put a same questions but different selecting answers.

**Comment by rtibbles** [comment]
@mrpau-julius note that this is not an instance of a 'repeating question' because the posed question and answer are different (even though the overall form of the question is the same across the questions) so this is fine!

**Comment by indirectlylit** [comment]
thanks - sounds like the primary issue is resolved.

Sounds like there may still be a UX issue because questions look so similar that they appear to be duplicates (cc @khangmach)

I'll file a clearinghouse issue for that
