### ISSUE TITLE
Public Channel Listing

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4029]
Hi, I was given this url to obtain a list of current public channels.

> http://studio.learningequality.org/api/public/v1/channels

https://community.learningequality.org/t/command-line-network-import-where-to-find-the-channel-ids/529

But it no longer works.

For those who use Kolibri CLI, would it be possible to supply a fixed url to obtain such a listing. ?

Regards

**Comment by indirectlylit** [comment]
Hi - the URL loads for me. Are you still getting errors?

**Comment by nobicycle** [comment]
It works now. Maybe a quirk. (Maybe this end :-)
