### ISSUE TITLE
Kolibri Telemetry (ping) Error

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4032]
Few days ago I noticed these errors in the kolibri (0.10.0) on my testing server in Phnom Penh, Cambodia. 

"WARNING 2018-07-15 03:13:59,954 ping Ping failed (403 Client Error: Forbidden for url: https://telemetry.learningequality.org/api/v1/pingback)! Trying again in 15.0 minutes." 

Full logs: https://paste.ubuntu.com/p/pbnmxgTNdv/

**Comment by arky** [comment]
Wondering such telemetry errors block kolibri server from working? I hope not! 

"WARNING  Ping failed (403 Client Error: Forbidden for url: https://telemetry.learningequality.org/api/v1/pingback)! Trying again in 15.0 minutes."

**Comment by indirectlylit** [comment]
> Wondering such telemetry errors block kolibri server from working? I hope not!

nope!

**Comment by arky** [comment]
@indirectlylit  Thanks for clearing that up. Is there a way to turn off logging these failures to $KOLIBRI_HOME/*.log files. 

It is quite possible that Internet in a box users might think these ping failures as a problem.

**Comment by indirectlylit** [comment]
following up - are you still seeing these errors?

**Comment by indirectlylit** [comment]
closing - please alert if you still see this
