### ISSUE TITLE
prop validation errors when watching videos

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4033]
### Observed behavior

observed when previewing (as a coach) and also viewing in a lesson (as a learner):

* `Invalid prop: custom validator check failed for prop "supplementaryFiles".`
* `Invalid prop: type check failed for prop "appBarTitle". Expected String, got Undefined.`

### Expected behavior

no errors

### User-facing consequences

unknown

### Errors and logs

```
vue.runtime.esm.js:587 [Vue warn]: Invalid prop: type check failed for prop "appBarTitle". Expected String, got Undefined.

found in

---> <ImmersiveToolbar> at kolibri/core/assets/src/views/immersive-toolbar.vue
       <CoreBase> at kolibri/core/assets/src/views/core-base.vue
         <Root>
```

and 

```
vue.runtime.esm.js:587 [Vue warn]: Invalid prop: custom validator check failed for prop "supplementaryFiles".

found in

---> <VideoRender> at kolibri/plugins/media_player/assets/src/views/index.vue
       <ContentRender> at kolibri/core/assets/src/views/content-renderer/index.vue
         <ContentPage> at kolibri/plugins/learn/assets/src/views/content-page.vue
           <LessonResourceViewer> at kolibri/plugins/learn/assets/src/views/classes/LessonResourceViewer.vue
             <AppBody> at kolibri/core/assets/src/views/app-body.vue
               <CoreBase> at kolibri/core/assets/src/views/core-base.vue
                 <Root>
```

### Steps to reproduce

As an admin, create a class and add yourself to it as both a coach and a learner. Then...

* Import `Touchable Earth (en) / India / Culture in India / Song` (`698a9d8e8eef589c8ae258cf3be146f4`)
* Add it to a lesson
* Watch it as a learner

### Context

0.11.0 (current `develop`)

**Comment by jonboiser** [comment]
CLosing for similar reasons to #3972
