### ISSUE TITLE
Kolibri should report supported Hashi features to HTML5 apps

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#4035]
In order to ensure proper operation over multiple versions of Kolibri, it's important that the Hashi library does not try to send messages that a particular version of Kolibri doesn't support, or depend on receiving a response to those messages to initialize.

To avoid this, we need to pass a GET parameter to HTML5 apps on load that tells them what Hashi features the Kolibri they're running in supports. We may also wish to have a feature in Hashi that can check if Kolibri supports the minimum necessary features and if not, sends a load error message to Kolibri.

**Comment by rtibbles** [comment]
Hrm, we didn't build this in from the start, is this something we still want to implement, given the more laissez faire approach?

**Comment by rtibbles** [comment]
I think this is being handled in other ways in the custom channels work.
