### ISSUE TITLE
On Raspberry Pi, use ''--no-cache-dir" pip option to install Kolibri 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4040]
Installing kolibri using pip on Raspbian (Raspberry Pi) fails with "MemoryError".  The workaround for this problem is to use "-no-cache-dir".   

$ pip install kolibri 

Full log: https://pastebin.mozilla.org/9089809 

$ pip install --no-cache-dir kolibri 

### Context
 * Kolibri version 0.10.0
 * Operating system:  Raspbian Lite on Raspberry Pi B+ 
 
Downstream bug in IIAB https://github.com/iiab/iiab/issues/908

**Comment by indirectlylit** [comment]
thanks - noted in our docs repo

**Comment by arky** [comment]
@indirectlylit Thanks for adding this to Kolibri docs. 

Meanwhile @iiab/community is investigating how to solve this pip problem on low-powered devices like Raspberry Pi.

**Comment by benjaoming** [comment]
Thanks for reporting @arky 

Could this perhaps be an upstream Pip issue? Ie. that installation of large .whl files are causing the issue?

**Comment by arky** [comment]
@benjaoming I shall do that. Trying to investigate this common problem [@iiab/#920](https://github.com/iiab/iiab/issues/920) further before reporting it pip upstream repo. Please feel free to close this bug. 
Reported  here for documentary purposes.

**Comment by benjaoming** [comment]
Could triage this by generating a huge .whl file and afterwards adding that to PyPi...

**Comment by benjaoming** [comment]
Alright, I've made this release of a bogus package for you:

```
pip install python-bogus-project-honeypot==1531935488.89
```

**Comment by benjaoming** [comment]
*) The above package is 59 MB, because the PyPi limit is 60 MB

**Comment by arky** [comment]
Thanks @benjaoming for creating this bogus package. Using the pip installed from pypa.io doesn't throw any pip cache memory errors. 

So I guess the pip packages shipped in Debian/Ubuntu have some bugs that throws these errors.
