### ISSUE TITLE
Lack of access logs to Kolibri server

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#4049]
### Observed behavior
When running Kolibri using the production build, i.e.
`kolibri --foreground start`
I would like to be able to see the server requests.

### Expected behavior
Server requests should be visible/logged somewhere to have a better view of what's happening under kolibri.
Logs files store information provided by Python logger and code errors. I would like to see also the requests to the server.

### User-facing consequences
This is a very needed information when doing load tests in the server to know which requests are reaching the server and which requests aren't.
Also it would be needed to find out the problems in Kolibri installations in schools.

### Steps to reproduce
Run kolibri in daemon mode or from a console executing
`kolibri --foreground start` 
Look in the logs file or the console: no requests info.

### Context
* All versions of Kolibri since 0.9.3 (previous versions haven't been tested)
* Debian Linux (but it should happen in any OS)

**Comment by indirectlylit** [comment]
I believe this would be addressed by https://github.com/learningequality/kolibri/pull/6619
