### ISSUE TITLE
Preview exam page display not working properly.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4055]
### Observed behavior
When I preview the exam I created with 50 exercises, All exercises detail from the bottom is overlap at the top when I scroll down.
Also the close button overlap when I scroll down the page.

### Expected behavior
Exercise detail and close button display should not overlap at the top.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/42983671-871ca328-8c1a-11e8-8993-ad7bee65d6f0.gif)

### Steps to reproduce
* Create a 50 exercises exam.
* Activate exam.
* Navigate at the preview exam page.

### Context

 * Kolibri version: 0.10.0
 * Operating system: Windows 7
 * Browser: Firefox 61.0.1

**Comment by jonboiser** [comment]
I'm not sure if this is an issue with the current version of the preview modal, since the list of questions on the left is a scrollable list, while the preview area on the right remains in place.
