### ISSUE TITLE
No indication that anything is happening during long wait for content import method selection modal

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#4070]
### Observed behavior

On a slow/high-latency connection (I'm tethering at the moment), it takes a long time to check whether we're online and un-gray the options on this modal:

![image](https://user-images.githubusercontent.com/618416/43102363-c7a9af82-8e7f-11e8-8add-25e020b8bca3.png)

If I didn't know better, I'd think nothing was happening, and no options were available. But then eventually it resolves.

### Expected behavior

Some sort of indication that processing/activity is going on, so that I know to wait, rather than hitting cancel. Perhaps that spinner in the top-right of the modal that @khangmach experimented with for adding of network addresses?

### User-facing consequences

Confusion and frustration.

**Comment by khangmach** [comment]
One option we can do is to not show the radio options upon modal load and first use a system message component used in content export modal: 

Changed text to maybe something like: 
"Loading connections..."

![loader system message](https://user-images.githubusercontent.com/25045166/43492139-7610a118-94dc-11e8-8c76-4c75f53624b1.gif)

**Comment by jtamiace** [comment]
+1 for consistency

**Comment by indirectlylit** [comment]
@khangmach remember to remove 'needs design' when it's resolved.

It looks like in your mockup above, 'cancel' is active but 'continue' is disabled during this state?

**Comment by khangmach** [comment]
@indirectlylit right, so the user can't continue because Kolibri is loading/checking the available connections
