### ISSUE TITLE
set Vue to 2.5.17 and use watcher-based optimizations on responsive window mixin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4075]
In #4065 we're setting vue to a beta version for testing. It's very important that we upgrade vue to 2.5.17 final before release 0.11.0

[check version on npm page](https://www.npmjs.com/package/vue)

**Comment by indirectlylit** [comment]
According to the [releases page](https://github.com/vuejs/vue/releases), 2.5.17:

> is a hot fix that ... does NOT include any changes from 2.5.17-beta.0

Looks like they had an emergency security fix, and those beta changes will come in 2.5.18?

**Comment by indirectlylit** [comment]
also, by committing 34edbc4 we are no longer testing the beta

**Comment by DXCanas** [comment]
A little confused by this issue @indirectlylit, as 2.5.18 still hasn't been released?

**Comment by indirectlylit** [comment]
Darn. I'd hoped it would have been released by now.

I upgraded because we need the performance improvements in https://github.com/vuejs/vue/pull/7824

Unfortunately that change caused a regression: https://github.com/vuejs/vue/issues/8446

I'll need to make a performance update to work around this

**Comment by DXCanas** [comment]
@devon Is there a specific component that was causing issues?

**Comment by indirectlylit** [comment]
Yes it was an optimization in the responsive window mixin, where the computed props were being re-calculated constantly during resizes rather than just at breakpoint thresholds.

I think we'll basically need to revert this commit: 355acf387266f6b0095cd7461e496485268079ba
