### ISSUE TITLE
Text box to fill in a formulaic answer is hidden until you click where it's located

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#4084]
### Observed behavior

Reported by a forum user: On some KA exercises with a formulaic text box response, the text box area is invisible until you click where it's located.

Version: 0.10

See example: http://kolibribeta.learningequality.org/learn/#/topics/c/b2a23f0837985e82aaa56f16ef511e04

See forum post: https://community.learningequality.org/t/kolibri-issue-while-entering-formula-in-question-in-create-excercise/724

…

### Expected behavior

Text box where you type the answer in should be visible when you open the question.

…

### Steps to reproduce

See exercise and click in the white space: http://kolibribeta.learningequality.org/learn/#/topics/c/b2a23f0837985e82aaa56f16ef511e04

**Comment by rtibbles** [comment]
This looks familiar. @christianmemije have we recently changed text box default styling in Kolibri that might have caused what I think is a regression?

@lauradanforth can you update the issue with the Kolibri version this was observed in? (I assume 0.10)

**Comment by christianmemije** [comment]
The issue is due to the reset that is done, particularly setting border to none.

https://github.com/learningequality/kolibri-exercise-perseus-plugin/blob/3548d20a60540b2dda2f4ecd0b47e6106b50fba5/kolibri_exercise_perseus_plugin/assets/src/views/PerseusRendererIndex.vue#L606

**Comment by benjaoming** [comment]
So it sounds like the issue reported in Community Forums is actually related to Studio?

**Comment by indirectlylit** [comment]
> So it sounds like the issue reported in Community Forums is actually related to Studio?

Perhaps @lauradanforth linked to the wrong forum post? Looks like there was also a legitimate Kolibri issue.

I've opened a new issue for the Studio forum post: https://github.com/learningequality/studio/issues/891
