### ISSUE TITLE
Upgrade eslint-plugin-vue and Configure it to use consistent ordering for custom Vue options

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4088]
1. ~Update eslint-plugin-vue to the latest version. Some of the new rules will lead to large changes, so we can apply them gradually.~ Fixed in #5331
1. Our components have two options `metaInfo` and `$trs` that are not considered by the [order-in-components](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/order-in-components.md) rule. So they appear in different places in different components. Vue-router hooks do not seem to have a prescribed order either. To make them consistent, we can specify a desired place for these three (`$trs`, router hooks, `metaInfo`).

**Comment by rtibbles** [comment]
Second part resolved in #5359
