### ISSUE TITLE
Creating a group, then renaming it before refresh returns 403 error

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4093]
### Observed behavior

After creating a new Learner Group, then renaming it, the request will fail with a 403 error.

In terminal (but not the browser, you also see these logs)

```
ERROR    [u"FacilityDataset ('dataset') not provided, and could not be inferred."]
WARNING  "POST /api/learnergroup/?1533150173390=1533150173390 HTTP/1.1" 403 63
```

But a user can refresh the page and then rename it. The requests are different:

**Request before refresh**

```
POST /api/learnergroup/

{id: "f60ea91861d5d72480b6fb62e68a6e93", name: "A1"}
```

**Request after refresh**
```
PATCH http://localhost:8000/api/learnergroup/f60ea91861d5d72480b6fb62e68a6e93/

{name: "A1"}
```
### Expected behavior

A user can rename a group after creating it.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Develop branch

**Comment by indirectlylit** [comment]
ref #4086
