### ISSUE TITLE
In KTextbox, Deleting a character jumps cursor to end of text field

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#4094]
String is being trimmed too aggressively, likely due to our use of `v-model.trim`. 

### Observed behavior

In any `k-input`, deleting a single bookending letter automatically throws the cursor to the next word. 

### Expected behavior

Deleting a single letter only deletes that letter, Not the space before or after it.

### User-facing consequences

Unexpected naming/renaming. Frustration.

### Steps to reproduce

1. Find an input outside of exercises. E.g. New/Edit Group/User/Class/etc.
2. Type out a string that includes a single letter. E.g. "David C", "A Man", "T Roosevelt"
3. Delete the single letter via Backspace/delete

![Demo](https://user-images.githubusercontent.com/9877852/43550825-b2511cda-9599-11e8-800f-07bf92d51a63.gif)

### Context

Kolibri 0.11
Ubuntu LTR 16xx
Chromium 66

**Comment by jonboiser** [comment]
This was observed in a recent bug bash. It's especially noticeable for longer text fields like a lesson description.

**Comment by jonboiser** [comment]
I think we should probably get rid of the `.trim` we us on KeenUITextbox, and just delegate this cleanup step to the forms that require it.

Arguably, this trimming/cleaning shouldn't be used in the majority of cases, maybe only on usernames. With everything else, we should allow trailing spaces

**Comment by jonboiser** [comment]
In the case of usernames, each form that has a username field also validates them on the client-side. So maybe .trim can be removed everywhere without a problem.

**Comment by jonboiser** [comment]
I added a patch to remove .trim in #5241

**Comment by indirectlylit** [comment]
> I think we should probably get rid of the `.trim` we us on KeenUITextbox, and just delegate this cleanup step to the forms that require it.

agreed. in general this should be handled at the data level - it's not necessary to reflect the trimmed content back to the user

**Comment by jonboiser** [comment]
v-model.trim was removed from KTextbox in #5241
