### ISSUE TITLE
Add tests for exam creation

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4110]
### Observed behavior

> Merging [#4107](https://codecov.io/gh/learningequality/kolibri/pull/4107?src=pr&el=desc) into [release-v0.10.x](https://codecov.io/gh/learningequality/kolibri/commit/31a0d851fd0746cdfdb81ea9f902ba3d825030b1?src=pr&el=desc) will **decrease** coverage by `0.05%`.
> The diff coverage is `12.5%`.

### Expected behavior

To avoid regressions in areas that may be hard to reach with manual tests, we need to significantly improve this coverage.

### User-facing consequences

n/a

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

0.10.2+

**Comment by indirectlylit** [comment]
exam creation has been re-implemented with more tests
