### ISSUE TITLE
Code review / systematic search for avoidable queryset traversals

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4111]
### Observed behavior

#4107 addressed a performance issue that was fixable by using normal database aggregation. It would seem reasonable to have a systematic look through the code base to see if there are similar patterns.

If anyone recalls any spurious behaviors they may have hurried into the codebase or otherwise encountered and wonder if it should be replaced by database aggregation, please add here :)

Django is capable of reasonably advanced aggregation.

CC: @jredrejo @bonidjukic 

### Context

0.10.2+

**Comment by rtibbles** [comment]
This issue has mostly been addressed by a broad performance optimization sweep in 0.13.
