### ISSUE TITLE
CLI: Initialization is run too early for some commands

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4112]
### Observed behavior

We should exempt some commands like `dbrestore` and `help` from creating a database. Maybe also some other commands like `status` and `stop`.

Since https://github.com/learningequality/morango/issues/48 was fixed, we should AFAIK be able to load the Django stack without any database connection. Anything else would be a regression.

Running `kolibri manage help` will bootstrap the database.

Related:

#2137

### Expected behavior

User can invoke CLI on a blank installation or during troubleshooting without this overhead. This may also involve `kolibri status` and `kolibri stop`.

### User-facing consequences

Creating a database and bootstrapping a `~/.kolibri` at the wrong time.

### Errors and logs

n/a

### Steps to reproduce

Run `kolibri manage help` on a blank installation.

### Context

All versions released

**Comment by indirectlylit** [comment]
I believe this was addressed in #5494

please re-open if not

**Comment by benjaoming** [comment]
Confirmed that #5494 removed the call to from `kolibri status`. Also of interest to this: https://github.com/learningequality/kolibri-server/issues/23
