### ISSUE TITLE
Error when mastering a Perseus exercise for a second time

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4119]
### Observed behavior

Get this error when mastering an exercise for the second time.

e.g. at http://localhost:8000/learn/#/topics/c/69e5e6abf479581483d441b83d7d76f4

I mastered this exercise once, then refreshing and mastering it again attempts a POST to `/api/masterylog` with an incomplete payload

```
{"completion_timestamp":"2018-08-07T17:58:43.148Z","end_timestamp":"2018-08-07T17:58:43.111Z","pastattempts":[{"correct":1},{"correct":1,"hinted":false,"error":false},{"correct":1,"hinted":false,"error":false},{"correct":1,"hinted":false,"error":false},{"correct":1,"hinted":false,"error":false},{"correct":1,"hinted":false,"error":false},{"correct":1,"hinted":false,"error":false}],"totalattempts":7}
```

Resulting in a validation error

```
{"mastery_level":["This field is required."],"start_timestamp":["This field is required."],"summarylog":["This field is required."],"user":["This field is required."]}
```

(It does not have problems if I just continue doing exercises and extend my streak, which results in PATCHING the previous masterylog, I assume)

### Expected behavior

There are no problems when re-mastering an exercise in a new session.

### User-facing consequences

None, because the initial mastery log is in the server. But an uncaught runtime error could have unexpected side effects in the app.

### Errors and logs

…

### Steps to reproduce

1. Master a perseus exercise
1. Continue your mastery streak by getting one more assessment right.
1. Observe no errors
1. Refresh your browser on that exercise's page
1. "Re-master" it by getting one more assessment correct
1. Observe error

### Context

Develop

**Comment by rtibbles** [comment]
Could be related to #5147

**Comment by indirectlylit** [comment]
is this issue still extant, or would it have been addressed by the PR referenced above?

**Comment by rtibbles** [comment]
I think we should close this unless it recurs.

**Comment by jonboiser** [comment]
Just saw this again on the kolibribeta server (version 0.13.0). I don't think #5393 would have fixed it, since it doesn't address what I described in the OP: that we're attempting to PATCH the log with and incomplete payload. The unique ID constraint thing seems like it was different.

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this issue in 0.15.1 - no errors observed after attempting to master a Perseus exercise for a second time.

**Comment by rtibbles** [comment]
Closing this as fixed.
