### ISSUE TITLE
Channel version shown on content import page is remote version, not current local version

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#4120]
### Observed behavior

I set my local ChannelMetadata version to 0 to trigger updates. It then correctly shows me that a new version (6) is available. However, it also shows that my current version is 6, which is misleading (as I then can't compare to see what version is currently loaded that I'd be upgrading from):

![image](https://user-images.githubusercontent.com/618416/43800934-8f11ef68-9a46-11e8-97a2-605699fbc031.png)

### Expected behavior

The version number in the bottom left of that image should show the version currently loaded (which then matches the topic tree shown below it) rather than the new remote version we'd be upgrading to.

### Steps to reproduce

Load a channel and a piece of content. Then run the following on the terminal and come back to import more content to that channel:
```
echo "from kolibri.content.models import *; ChannelMetadata.objects.all().update(version=0)" | kolibri shell
```

### Context

0.10.2b1

**Comment by jonboiser** [comment]
This only happens because the version you chose is 0 and JS semantics.

The line there is derived from this code:

```
        return this.channelOnDevice.version || this.channel.version;
// 0 || 6 => evaluates to 6
```

I think in practice, since versions start at 1 (?) this discrepancy won't happen.

**Comment by indirectlylit** [comment]
@jonboiser mind reviewing the change above?
