### ISSUE TITLE
Lost Channel Listings V2

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4125]
Suggest to reopen https://github.com/learningequality/kolibri/issues/3679
"Lost Channel Listings"

Hi, I experienced the same problem described in issue 3679,  with version 10.1 of Kolibri.
Pip install. Browser Vivaldi.

```
$ uname -a
Linux tower 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux
```

I was testing the fix of 
https://github.com/learningequality/kolibri/issues/3963
That fix was a success. I was able to download Kahn Academy channel listings.

However,  afterwards I started downloading some content from that channel. After about 8 MB I ran out of internet quota (for the day). Therefore I clicked cancel.

If I then go to Device, I am informed "Content - No channels installed"
Is the 220MB or so channel listing download lost?

Logs attached.

[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2270016/kolibri.log.txt)
[server.log.txt](https://github.com/learningequality/kolibri/files/2270017/server.log.txt)

**Comment by nobicycle** [comment]
New discovery:

With Kolibri reporting "No Content", I went ahead to fetch Kahn Academy listings again. Kolibri returned very quickly - I assume it reused the already downloaded listings.

**Comment by indirectlylit** [comment]
> Suggest to reopen #3679

#3679 is still open
