### ISSUE TITLE
Error message appears green

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#4150]
### Observed behavior

I purposely tried to cause an error, but instead of the expected error message, I got a green bar and got redirected quickly so I couldn't read my message

### Expected behavior

I expected an error message

### User-facing consequences

The green color indicates something went ok, but in fact something went wrong. Confusion.

### Steps to reproduce

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5150483/43927164-74015e10-9be1-11e8-9c90-7ebffd9f80b6.gif)

### Context

…

**Comment by jonboiser** [comment]
What was the error you were trying to cause? What are the steps?

The "Green Bar" actually indicates that you were successful in changing the Facility Settings. So this would be a bug if changing settings forces a log-out.

**Comment by jeepurs** [comment]
Steps to reproduce (also in the gif):
1. Log in as admin on one tab, go to Users tab (or anything in Facility)
2. Open Kolibri on another tab
3. Sign out on new tab
4. Log in as learner on new tab
5. On first tab, try to change Device Settings

**Comment by indirectlylit** [comment]
Yes, inside the green bar it says 'there was a problem saving your settings'

**Comment by Tlazypanda** [comment]
@indirectlylit can I take this up? Thanks :v:
