### ISSUE TITLE
Update languages for 0.11.0

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4152]
### Observed behavior
Change languages not working has a bug. 
refer to Gherkin scenarios
https://github.com/learningequality/kolibri/blob/gherkin-features/integration_testing/features/learner/learner-change-language.feature
![can t change languages](https://user-images.githubusercontent.com/38421180/43944646-7b847b7e-9c34-11e8-97e3-e207629d0b0a.png)

### Expected behavior
Can change languages 

### Context

Kolibri 0.11.0a5
Windows 7
Firefox 61.0.2 (64-bit)

**Comment by jonboiser** [comment]
This might be because all of the translated string references were renamed recently, hence all of the warnings on the right.

**Comment by indirectlylit** [comment]
that is correct. Setting milestone and updating title
