### ISSUE TITLE
Are we using the wrong file to "glue" together core URLs?

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#4155]
At the top of **kolibri/core/urls.py**:

```Kolibri core url patterns
=========================

This module should be the glue between all other url patterns.

Do NOT use kolibri.deployment.default project's urlconf for such! That file can
be modified by users.
...
```

In **kolibri/deployment/default/urls.py**:

```urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('kolibri.core.urls')),
    url(r'', include('kolibri.core.content.urls')),
    url(r'^api/', include('kolibri.core.auth.api_urls')),
    url(r'^api/', include('kolibri.core.content.api_urls')),
    url(r'^api/', include('kolibri.core.logger.api_urls')),
    url(r'^api/', include('kolibri.core.tasks.api_urls')),
    url(r'^api/', include('kolibri.core.exams.api_urls')),
    url(r'^api/', include('kolibri.core.device.api_urls')),
    url(r'^api/', include('kolibri.core.lessons.api_urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'', include(morango_urls)),
]
...
```

So..... it seems we're not following the pattern we specified? Should we be moving those URLs into kolibri/core/urls.py? I'm trying to remember whether there was some sort of blocker for doing that -- I know I've added stuff into the deployment file, but I think I was just following the pattern we used with other core apps.

**Comment by jamalex** [comment]
In the meantime, I'm going to follow the current pattern, as my PR has enough rabbitholes in it.

**Comment by benjaoming** [comment]
I agree very much, we should have URLs served by the applications that control them. The project-wide URL specification should only include application URL patterns, and not the individual patterns of applications.
