### ISSUE TITLE
Kolibri Interactive Exercises  Not Working Properly

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4161]
Hi,

This issue appeared to be the same as   #3620; but that was because internet was down locally today.

The phenomenon is the same however - inability to use the interactive exercises.

Kolibri 10.1, pip install, Vivaldi browser.

Please see attachments below for documentation per Kolibri 10.1

![count with small numbers](https://user-images.githubusercontent.com/1372447/44094537-09e53782-a009-11e8-87ec-44436af4af21.jpg)
![count with small numbers class](https://user-images.githubusercontent.com/1372447/44094538-0a2bcd96-a009-11e8-854d-b51359a943ea.jpg)
![count with small numbers-console](https://user-images.githubusercontent.com/1372447/44094540-0a7335d2-a009-11e8-90c4-2889d355999b.jpg)
![count with small numbers-console-errors](https://user-images.githubusercontent.com/1372447/44094542-0ad12f34-a009-11e8-9500-9501cabb9a66.jpg)
![def52a8e-548a-4e0d-95bf-6bb1a6160d2f](https://user-images.githubusercontent.com/1372447/44094544-0b18108e-a009-11e8-8699-bfc99280fabf.jpg)
[Errors.txt](https://github.com/learningequality/kolibri/files/2287071/Errors.txt)

One difference with 3620 I see is the console errors (See Errorts.txt)  refer to localhost rather than a remote server.

Logs attached:
[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2287121/kolibri.log.txt)
[server.log.txt](https://github.com/learningequality/kolibri/files/2287122/server.log.txt)

**Comment by arky** [comment]
@nobicycle Thanks for reporting. Let me do some digging.

**Comment by rtibbles** [comment]
Thanks for the reports, we have set the machinery in motion to resolve this, and will not be dependent on a particular Kolibri release, just updating the KA channel.

@ralphiee22 can you ping here when the issues should be resolved?

**Comment by indirectlylit** [comment]
this should be resolved with the latest KA channel updates - please re-open if that's not the case
