### ISSUE TITLE
Out of exam when dealing with input type question 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4162]
### Observed behavior
When learner is trying to enter the answer of  input type question, exam automatically gets closed.
Cases:
1. When enter more than two digit answer.
2. When learner is trying to erase the answer(in short backspace takes user out of the exam).

Channel ID : 9ba9b274853845dba7863dd66687568a (Input type question).

Note: This is just sample channel. This issue is arising across the channel.

Please watch attached video for more clarification.
[VID_20180821_164643.zip](https://github.com/learningequality/kolibri/files/2306054/VID_20180821_164643.zip)

### Expected behavior
Exam must accept the answer without exiting the exam.

### Steps to reproduce
1. Create exam which contains input type questions.
2. Enter the answer more than 2 digits and try to erase the answer. Learner automatically gets out of the exam.

### Context
 * Kolibri version : Kolibri 0.9.4b3
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![screenshot from 2018-08-16 18-37-45](https://user-images.githubusercontent.com/12776071/44210471-34e55580-a184-11e8-8cff-8f9a081df54a.png)
![screenshot from 2018-08-16 18-37-54](https://user-images.githubusercontent.com/12776071/44210473-357dec00-a184-11e8-85b8-42f3bce58f4d.png)

### Error
![screenshot from 2018-08-21 17-01-17](https://user-images.githubusercontent.com/12776071/44399099-e0671f00-a563-11e8-861d-55c048b451d4.png)

**Comment by rtibbles** [comment]
This should have been fixed in #4174. Please confirm the fix in 0.9.4-beta4.

**Comment by swapnil106111** [comment]
@rtibbles Tested this issue in Kolibri-0.9.4. It is not going out of the exam but If we type 12345 in the answer box and clears everything then it keeps some digits of the answer in answer box.
Please watch attached video for more clarification.

Before clearing the answer:
![screenshot from 2018-08-23 11-53-40](https://user-images.githubusercontent.com/12776071/44508300-6fdb1200-a6cb-11e8-8b29-49b7c6a61d63.png)

After clearing the answer:
![screenshot from 2018-08-23 11-53-48](https://user-images.githubusercontent.com/12776071/44508315-779ab680-a6cb-11e8-8137-e147c91aa16f.png)

Video:
[VID_20180823_121628.zip](https://github.com/learningequality/kolibri/files/2313248/VID_20180823_121628.zip)

**Comment by rtibbles** [comment]
Should be fixed in #4186.

**Comment by indirectlylit** [comment]
@swapnil106111 would you mind confirming this in 0.9.4?

**Comment by indirectlylit** [comment]
whoops sorry - didn't see the comment above. I'm a little confused about the timeline - will follow-up

**Comment by swapnil106111** [comment]
@indirectlylit Sorry for delay reply. Now, exam feature is working fine.
