### ISSUE TITLE
error details are not keyboard-navigable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4163]
### Observed behavior

the error details are currently implemented using a `<pre>` tag instead of a `<textarea>`:

![image](https://user-images.githubusercontent.com/2367265/44239362-cac1b600-a16d-11e8-8226-98aa5f906162.png)

This means that you can't get a cursor into the text area, or use ctrl-a to select all. Instead, it selects everything on the page:

![image](https://user-images.githubusercontent.com/2367265/44239499-808d0480-a16e-11e8-816c-4e5028eefcfe.png)

### Expected behavior

I expected to be able to put a cursor in there and then:

* use ctrl-a, ctrl-c, or 
* or, move the cursor around and select subsets of the text using the keyboard

### User-facing consequences

slightly different UX than typical for this kind of UI

### Errors and logs

N/A

### Steps to reproduce

Try to tab down to the field

### Context

see #4051

**Comment by indirectlylit** [comment]
cc @DXCanas

**Comment by DXCanas** [comment]
A `<text-area>` seems an odd decision, given that this isn't supposed to be taking any input? I can understand some use cases for subset selection, but wouldn't the "copy-to-clipboard" button be more ideal than doing the `ctrl-a`, `ctrl-c` procedure?

Purely subjective, but being able to tab into the error isn't behavior I'd expect o.o

**Comment by indirectlylit** [comment]
> A `<text-area>` seems an odd decision, given that this isn't supposed to be taking any input? I can understand some use cases for subset selection, but wouldn't the "copy-to-clipboard" button be more ideal than doing the `ctrl-a`, `ctrl-c` procedure?

This is pretty standard behavior for a crash report. Some examples:

Adobe:

![image](https://user-images.githubusercontent.com/2367265/45063855-298b9880-b065-11e8-9dd9-92a20a2d98ff.png)

Mozilla:

![image](https://user-images.githubusercontent.com/2367265/45063863-37d9b480-b065-11e8-9bc6-2d0f452b7a51.png)


OSX:

![image](https://user-images.githubusercontent.com/2367265/45063865-4627d080-b065-11e8-9e95-6388afe21b70.png)


> Purely subjective, but being able to tab into the error isn't behavior I'd expect o.o

 Not all users think like you :)

**Comment by DXCanas** [comment]
Seems fair @indirectlylit - are you able to actually go into the textbox and type?

For the record, I only said I didn't think it was expected behavior in response to the issue:
> I expected to be able to put a cursor in there and then:

Hence the "purely subjective" bit :).

**Comment by indirectlylit** [comment]
fixed in #4232
