### ISSUE TITLE
Exam reports will always show progress for entire class/every group, regardless of recipient assignment

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#4165]
### Observed behavior
An exam assigned to 1 group, will show reports for every group
An exam assigned to 2+ groups, will show reports for every group

### Expected behavior
An exam assigned to 1 group will only show reports for that one grouop
An exam assigned to 2+ groups will only show reports designated to those number of groups
An exam assigned to "entire class" will show reports for the entire class

Proper behavior shown in invision prototype: https://invis.io/MKNL93TAZ2E#/276734704_Exam_Progress_One_Group

### User-facing consequences
- Does not follow specced design
- Shows extraneous data and information that doesn't pertain to the recipients
- Harder to find and sort information for that particular group(s)
- Misleading. The report is showing data for groups/learners that I have no intention to assign the exam to

### Steps to reproduce
- Create a fresh exam
- Change recipients from 'Entire class' to a specific number of groups (1 group or 2, doesn't matter)
- Check the exam reports 
- When "View by groups" is unchecked, see that progress for every learner shows
- When "View by groups" is checked, see that progress for every group shows

### Context
 * Kolibri version: 10.1
 * Operating system: MacOS
 * Browser: Chrome

Screenshots:
<img width="527" alt="screen shot 2018-08-17 at 10 21 14 am" src="https://user-images.githubusercontent.com/25045166/44279722-53406500-a207-11e8-8ab2-2f0ab1f00a49.png">

Exam is designated for 3 groups

<img width="772" alt="screen shot 2018-08-17 at 10 21 27 am" src="https://user-images.githubusercontent.com/25045166/44279733-5e939080-a207-11e8-84aa-0693c35adfb2.png">

Exam actually shows every group

**Comment by khangmach** [comment]
I have a hunch this is possibly due to the exam being assigned to "Entire class" by default once is leaves the curation area. Can still mitigate this by hiding/nulling progress for all groups/learners not currently in the newly assigned groups?

**Comment by rtibbles** [comment]
I think it's just that the exam report just shows the entire class always, regardless of the assignees, but possible I misread the code in question.

**Comment by khangmach** [comment]
@rtibbles Yup, that's the issue I was trying to frame.
