### ISSUE TITLE
uncaught error in setup wizard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4170]
### Observed behavior

Start with a fresh Kolibri installation and load the setup wizard

![image](https://user-images.githubusercontent.com/2367265/44373440-075b1d80-a49e-11e8-913a-8ff49123145f.png)

![image](https://user-images.githubusercontent.com/2367265/44373449-13df7600-a49e-11e8-8314-12dc8b19cdfc.png)

### Expected behavior

no error

### User-facing consequences

unknown 

### Errors and logs

```
Uncaught SyntaxError: Unexpected token <
```

### Steps to reproduce

simply load the page

### Context

0.11.0

**Comment by rtibbles** [comment]
Note that this only happens in dev mode, and is a consequence of the schema.js endpoint being blocked by the setup wizard middleware. Can fix.
