### ISSUE TITLE
insufficient padding between type icons and text

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4175]
### Observed behavior

we have icons directly next to text in many places

![image](https://user-images.githubusercontent.com/2367265/44432159-c0306380-a555-11e8-81b3-7e03edaa3a04.png)

### Expected behavior

Let's do an audit and add sufficient spacing between text and icons as per [Material guidelines](https://material.io/design/layout/spacing-methods.html#spacing)

### User-facing consequences

UI looks cramped

### Context

0.10.0

**Comment by jonboiser** [comment]
If this still exists anywhere, we should replace tight icon/text pairs with KLabeledIcon.

I personally can't find anything like this in Kolibri as of 0.12, however.

**Comment by indirectlylit** [comment]
https://github.com/learningequality/kolibri/issues/3872 is the only one I know of offhand.

we can close this one
