### ISSUE TITLE
Add Search to Lessons

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4185]
###Observed behavior
Currently it is impossible to search for content in lesson creation.

###Expected behavior
Be able to search for content in lesson creation.

###User-facing consequences
Requires strong mental model of the content library before can start using content as a coach.

https://trello.com/c/pNhNvnLT/134-search-in-lessons

**Comment by DXCanas** [comment]
https://github.com/learningequality/kolibri/pull/4253
