### ISSUE TITLE
Windows7 Import/Export error

### ISSUE THREAD

**Issue by Oyster1** [learningequality/kolibri#4190]
### Observed behavior

…

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Installed, setup user, password etc, > Device > Import from USB > error 'No drives that can be written to are connected to the server' received.

### Context

Kolibri ver 0.10.0
Windows 7 64bit
Chrome Version 68.0.3440.106 64bit

**Comment by benjaoming** [comment]
Thanks for opening up this issue! We need a bit more information, as it's not commonly reproducible.

Please provide:

 1. Your `kolibri.log` file from `C:\Users\<username>\.kolibri\kolibri.log`
 1. Open up Command Prompt in Windows, and attach the result of the command `wmic logicaldisk list full /format:csv`

If you need any assistance to complete the above steps, please feel free to say so!

**Comment by Oyster1** [comment]
Hi, hope this is what you want, if not please email me. Thanks.

kolibri.log
INFO 2018-08-24 10:18:26,829 apps Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO 2018-08-24 10:18:27,812 cli Kolibri running for the first time.
INFO 2018-08-24 10:18:27,812 cli We don't yet use pre-migrated database seeds, so you're going to have to wait a bit while we create a blank database...


INFO 2018-08-24 10:18:45,065 cli Automatically enabling applications.
INFO 2018-08-24 10:18:45,065 cli Running update routines for new version...
INFO 2018-08-24 10:18:53,661 cli Running 'kolibri start' as daemon (system service)
INFO 2018-08-24 10:18:54,285 cli Kolibri running on:

INFO 2018-08-24 10:18:54,285 cli Going to daemon mode, logging to C:\Users\neames\.kolibri\server.log
INFO 2018-08-24 10:18:54,316 ping Attempting a ping.
INFO 2018-08-24 10:18:54,706 ping data: {"sysversion": "3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]", "mode": "", "language": "", "platform": "Windows-7-6.1.7601-SP1", "version": "0.10.1", "system_id": "", "database_id": "bec59a8450c04addbaed95618c5f8810", "instance_id": "555451505286b1d74a49aef21535aa47", "node_id": "094a7abbff5c01af684f", "uptime": 0}
INFO 2018-08-24 10:18:56,032 utils Started new MESSAGEPROCESSOR thread ID#moon-idaho-equal-blossom
INFO 2018-08-24 10:18:56,032 utils Started new SCHEDULER thread ID#twenty-finch-bravo-carolina
INFO 2018-08-24 10:18:56,032 utils Started new WORKERMESSAGEHANDLER thread ID#bulldog-mountain-carpet-ohio
INFO 2018-08-24 10:18:56,453 ping Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
ERROR 2018-08-24 10:24:13,535 exception Internal Server Error: /api/tasks/localdrive/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\tasks\api.py", line 332, in localdrive
    drives = get_mounted_drives_with_channel_info()
  File "C:\Python34\lib\site-packages\kolibri\content\utils\channels.py", line 97, in get_mounted_drives_with_channel_info
    drives = enumerate_mounted_disk_partitions()
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\filesystem\__init__.py", line 39, in enumerate_mounted_disk_partitions
    drive_list = get_drive_list_windows()
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\filesystem\windows.py", line 18, in get_drive_list
    drive_list = _parse_wmic_csv_output(_wmic_output())
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\filesystem\windows.py", line 75, in _wmic_output
    raise Exception("Could not run command '{}'".format(cmd))
Exception: Could not run command 'wmic logicaldisk list full /format:csv > C:\Users\neames\AppData\Local\Temp\kolibri_disks-965ff04d-f679-4b9a-869a-51bcb3c9275d.txt'
INFO 2018-08-24 10:28:09,588 apps Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO 2018-08-24 10:28:10,492 cli Kolibri server has successfully been stopped.
INFO 2018-08-24 10:37:34,799 apps Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO 2018-08-24 10:37:35,408 cli Running update routines for new version...
INFO 2018-08-24 10:37:36,905 cli Running 'kolibri start' as daemon (system service)
INFO 2018-08-24 10:37:37,015 cli Kolibri running on:

INFO 2018-08-24 10:37:37,015 cli Going to daemon mode, logging to C:\Users\neames\.kolibri\server.log
INFO 2018-08-24 10:37:37,015 ping Attempting a ping.
INFO 2018-08-24 10:37:37,061 ping data: {"node_id": "094a7abbff5c01af684f", "platform": "Windows-7-6.1.7601-SP1", "database_id": "bec59a8450c04addbaed95618c5f8810", "version": "0.10.1", "mode": "", "uptime": 0, "system_id": "", "instance_id": "555451505286b1d74a49aef21535aa47", "sysversion": "3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]", "language": "en"}
INFO 2018-08-24 10:37:37,124 utils Started new MESSAGEPROCESSOR thread ID#snake-west-delta-kitten
INFO 2018-08-24 10:37:37,124 utils Started new SCHEDULER thread ID#yellow-burger-maine-hamper
INFO 2018-08-24 10:37:37,124 utils Started new WORKERMESSAGEHANDLER thread ID#chicken-lemon-indigo-robin
INFO 2018-08-24 10:37:37,810 ping Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.


Output from 'wmic logicaldisk list full /format:csv' gives error 'Invalid XSL format (or) file name'.
Output from  'wmic logicaldisk list full /format:list' is below.

Access=0
Availability=
BlockSize=
Caption=C:
Compressed=FALSE
ConfigManagerErrorCode=
ConfigManagerUserConfig=
Description=Local Fixed Disk
DeviceID=C:
DriveType=3
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FileSystem=NTFS
FreeSpace=74337411072
InstallDate=
LastErrorCode=
MaximumComponentLength=255
MediaType=12
Name=C:
NumberOfBlocks=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=
ProviderName=
Purpose=
QuotasDisabled=
QuotasIncomplete=
QuotasRebuilding=
Size=319965622272
Status=
StatusInfo=
SupportsDiskQuotas=FALSE
SupportsFileBasedCompression=TRUE
VolumeName=
VolumeSerialNumber=CC025A4B


Access=
Availability=
BlockSize=
Caption=D:
Compressed=
ConfigManagerErrorCode=
ConfigManagerUserConfig=
Description=CD-ROM Disc
DeviceID=D:
DriveType=5
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FileSystem=
FreeSpace=
InstallDate=
LastErrorCode=
MaximumComponentLength=
MediaType=11
Name=D:
NumberOfBlocks=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=
ProviderName=
Purpose=
QuotasDisabled=
QuotasIncomplete=
QuotasRebuilding=
Size=
Status=
StatusInfo=
SupportsDiskQuotas=
SupportsFileBasedCompression=
VolumeName=
VolumeSerialNumber=


Access=
Availability=
BlockSize=
Caption=E:
Compressed=
ConfigManagerErrorCode=
ConfigManagerUserConfig=
Description=Removable Disk
DeviceID=E:
DriveType=2
ErrorCleared=
ErrorDescription=
ErrorMethodology=
FileSystem=
FreeSpace=
InstallDate=
LastErrorCode=
MaximumComponentLength=
MediaType=
Name=E:
NumberOfBlocks=
PNPDeviceID=
PowerManagementCapabilities=
PowerManagementSupported=
ProviderName=
Purpose=
QuotasDisabled=
QuotasIncomplete=
QuotasRebuilding=
Size=
Status=
StatusInfo=
SupportsDiskQuotas=
SupportsFileBasedCompression=
VolumeName=
VolumeSerialNumber=

**Comment by lyw07** [comment]
Based on this info: `Output from 'wmic logicaldisk list full /format:csv' gives error 'Invalid XSL format (or) file name'.`, it's caused by a bug of `wmic` in Win7 when the locale used is not US English. I will have a fix for it.

**Comment by Oyster1** [comment]
Changed locale to US English, same error!

**Comment by lyw07** [comment]
Hi @Oyster1 , thank you so much for the update! Could you try to run `wmic logicaldisk list full /format:"%WINDIR%\System32\wbem\en-us\csv"` and see if you still get the same error? Thanks!

**Comment by Oyster1** [comment]
Hi Lingyi,

Same error in both in UK English locale and US English locale!

My apologies but I shall be away from my office for the rest of the UK day
but will answer and query when I return.

Regards,
Nigel Eames.

**Comment by lyw07** [comment]
Thank you for checking! I will dig into this problem more to see what else could cause the issue.

**Comment by lyw07** [comment]
It looks like the issue is not really related to locale but formats. I can reproduce the issue when I change the `formats` in `Region and Language` to something other than `English (United States)`, although somehow the command`wmic logicaldisk list full /format:"%WINDIR%\System32\wbem\en-us\csv"` fixes the issue in my case. 

A temporary workaround for users in Windows 7 could be setting the Format in `Control Panel--> Region and Language` to `English (United States)`. But we will have a fix for this issue in the future release so that users don't need to change their system formats.

**Comment by Oyster1** [comment]
Hi, Thanks, the output is:
Node,Access,Availability,BlockSize,Caption,Compressed,ConfigManagerErrorCode,ConfigManagerUserConfig,Description,DeviceID,DriveType,ErrorCleared,ErrorDescription,ErrorMethodology,FileSystem,FreeSpace,InstallDate,LastErrorCode,MaximumComponentLength,MediaType,Name,NumberOfBlocks,PNPDeviceID,PowerManagementCapabilities,PowerManagementSupported,ProviderName,Purpose,QuotasDisabled,QuotasIncomplete,QuotasRebuilding,Size,Status,StatusInfo,SupportsDiskQuotas,SupportsFileBasedCompression,VolumeName,VolumeSerialNumber
NEAMES-PC,0,,,C:,FALSE,,,Local Fixed Disk,C:,3,,,,NTFS,68555309056,,,255,12,C:,,,,,,,,,,319965622272,,,FALSE,TRUE,,CC025A4B
NEAMES-PC,,,,D:,,,,CD-ROM Disc,D:,5,,,,,,,,,11,D:,,,,,,,,,,,,,,,,
NEAMES-PC,,,,E:,,,,Removable Disk,E:,2,,,,,,,,,,E:,,,,,,,,,,,,,,,,

**Comment by lyw07** [comment]
Hi @Oyster1 ,
thank you for showing us the output! it's very helpful. One thing that could temporarily fix the issue here is to change the `Format` in `Control Panel-->Clock, Language, and Region --> Region and Language --> Formats --> Format` to `English (United States)`. Please feel free to let me know if that fixes the error in kolibri so that you can find the external drives.
I will also create a pull request to fix the issue from our side, and it will very likely go into our future release 0.11. With this fix in 0.11, you won't need to change the format to US English.

**Comment by indirectlylit** [comment]
@Oyster1 FYI this fix will be available when either 0.10.3 or 0.11.0 is released later this month

**Comment by Oyster1** [comment]
Thanks
