### ISSUE TITLE
Bug on Exam preview, close button overlap

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4191]
### Observed behavior
I observe have a bug in Exam preview, the close button is overlap by the question display. 
So that I can't see the close button.
The questions are from Khan Academy(English)

![close button are overlap by the question](https://user-images.githubusercontent.com/38421180/44578258-09e0a000-a748-11e8-9109-0a3e7d6e5786.png)

…

### Expected behavior
The close button can see below the display questions.

### Context

  * Kolibri version: 0.10.2
 * Operating system: windows 7 64-bit
 * Browser firefox 61.0.2

**Comment by jonboiser** [comment]
This shouldn't happen any more with the current modal implementation. What should happen is that the Close button will appear in its own frame and won't be overlapped by the exercise.
