### ISSUE TITLE
Incorrect channel content size details

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4199]
### Observed behavior
When I select channel contents to import, I see it has 108 resources and 45mb of size but after it was imported it has 177 resources and 43mb of size.

### Errors and logs
This is when I select a channel contents to import.
![screen shot 2018-08-28 at 11 14 26 am](https://user-images.githubusercontent.com/8663934/44698898-5c0d2280-aab4-11e8-94ac-7ff6fb93e19f.png)

After the channel content imported.
![screen shot 2018-08-28 at 10 47 33 am](https://user-images.githubusercontent.com/8663934/44698951-9c6ca080-aab4-11e8-982f-eeb7c2513fe3.png)
![screen shot 2018-08-27 at 3 59 24 pm](https://user-images.githubusercontent.com/8663934/44698962-a7bfcc00-aab4-11e8-842f-3f428869fc03.png)

Here's the [kolibri.log](https://github.com/learningequality/kolibri/files/2326378/kolibri.log)
 
### Context

 * Kolibri version: 0.10.2
 * Operating system: Window 7
 * Browser: Firefox 61.0

**Comment by indirectlylit** [comment]
@lyw07 do you think this is related to #3883

**Comment by lyw07** [comment]
In the `kolibri.log`, there are errors saying 
```
importcontent An error occured during content import: File https://studio.learningequality.org/content/storage/2/c/2ca066c372affaef7b74ccba12e6550c.jpg is corrupted.
```
So for the change from 45MB to 43 MB, I think it's because of the bug in studio: https://github.com/learningequality/studio/issues/921.

**Comment by indirectlylit** [comment]
thanks - closing this since we're migrating to the studio issue
