### ISSUE TITLE
Alignment issue at the change language buttons.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4204]
### Observed behavior
`Cancel` and `Confirm` change language  buttons overlap. 

### Errors and logs
![screen shot 2018-08-30 at 4 29 24 pm](https://user-images.githubusercontent.com/8663934/44839874-6a08a200-ac72-11e8-911e-91c6d50cf9f3.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.3-beta1
 * Operating system: Windows 7
 * Browser: Firefox 61.0.1

**Comment by jonboiser** [comment]
This is probably not an issue anymore, since this change languages modal has minimum width that is enough to have the buttons side-by-side.
