### ISSUE TITLE
Cannot create non-ascii usernames

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#4205]
### Observed behavior

I tried to create a user with username `иван` (ivan in cyrillic) but was not able to.

### Expected behavior

Create a new user  OR  show validation error.

### User-facing consequences

Cannot create usernames in other locales.

### Errors and logs

UI doesn't show a validation error, but JS console has this:

<img width="880" alt="screen shot 2018-08-30 at 5 01 06 pm" src="https://user-images.githubusercontent.com/163966/44857106-c4f0c800-ac77-11e8-8976-bfbf9f6924fd.png">

### Steps to reproduce

  - Go to localhost:8080/facility/#/users
  - Choose ADD USER
  - Enter a non-ascii username (and valid password etc)
  - Click ADD

Actual: nothing

Expected: user created or validation error "username ... invalid; use ascii characters"

### Context

 * Kolibri version: 0.10.3.dev
 * Operating system: Linux
 * Browser: Firefox

**Comment by rtibbles** [comment]
Our validation logic is inadequate for this, we should improve and allow it!

**Comment by indirectlylit** [comment]
let's address this at the same time as we include bulgarian (see #4201)

removing milestone for now

**Comment by rtibbles** [comment]
Also, when I try to do this on develop, it tells me that an account with this username already exists, which is not the error that the API returns.
