### ISSUE TITLE
Wrong display of classes in learners page

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4210]
###  Observed behaviour

I created three classes in admin facility (example: class A, class B and class C) and enrolled at least one learner in class A. When I logged a learner account, I saw three classes instead of one class  in “Learners > Classes page”.

![error in class learner page](https://user-images.githubusercontent.com/38421180/45021582-8044a280-b064-11e8-9bcd-91262ae2ef0b.png)

![click not his class](https://user-images.githubusercontent.com/38421180/45021599-89ce0a80-b064-11e8-9c54-7553df42cddd.png)

![error log](https://user-images.githubusercontent.com/38421180/45021611-8fc3eb80-b064-11e8-9417-b7225b14b03d.png)

### Errors and logs

```
{
  "request": {
	"path": "/learn/api/learnerclassroom/37670de473aa814ac9367d55a44ede6a/",
	"params": {
  	"1536046052189": 1536046052189
	},
	"headers": {
  	"Content-Type": "application/json",
  	"Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2",
  	"X-CSRFToken": "au32PFsU7f1I3l4JfOdx6ryUS5hjhahXknPNdGEkg8Gn8bmyjSYEfGlxgycP90xy"
	},
	"method": "GET",
	"canceled": false
  },
  "url": "/learn/api/learnerclassroom/37670de473aa814ac9367d55a44ede6a/?1536046052189=1536046052189",
  "raw": {},
  "status": {
	"code": 404,
	"text": "Not Found"
  },
  "headers": {
	"Allow": "GET, HEAD, OPTIONS",
	"Content-Language": "en",
	"Content-Length": "77",
	"Content-Type": "application/json",
	"Date": "Tue, 04 Sep 2018 07:27:32 GMT",
	"Server": "0.0.0.0",
	"Vary": "Accept, Accept-Language, Cookie",
	"X-Frame-Options": "SAMEORIGIN"
  },
  "entity": [
	{
  	"id": "NOT_FOUND",
  	"metadata": {
    	"view": "Learner Classroom Viewset Instance"
  	}
	}
  ]
}

```

### Steps to reproduce

1. Logged as admin facility account.
2. Create at least two or three classes (example: class A, class B, or class C).
3. Enroll at least one learner in class.
4. Log-in as learner account and you will see the error/bug.

### Context

 Kolibri version : 0.11.0a5
  Operating system : Windows 7 ultimate (64-bits)
  Browser : Firefox 61.0.2 (64-bit)

**Comment by jonboiser** [comment]
@ralphiee22 The results from the `/api/auth/classroom/` endpoint are not being filtered properly. It seems to return all classrooms to all users.

**Comment by jonboiser** [comment]
On the other hand, it seems like the filtering is working fine for `learn/api/learnerclassroom/`, hence the 404 Julius is getting for the one classroom..

**Comment by indirectlylit** [comment]
Should be addressed

@mrpau-julius please keep an eye out for this during upcoming integration testing
