### ISSUE TITLE
Migrate to material design nav-tabs

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#4214]
### Observed behavior

Current material design tabs are used in a nonstandard way. 
Here are some ways in which their placement can be a concern:
- Visibility of the tabs is lost as the user scrolls down the page. As a result, the information hierarchy is difficult to process and may be lost in some instances.
- Tabs take up a lot of vertical space

### Expected design

Nav-tabs being a standard component working with the app-bar. See material design specifications for more detail: https://material.io/design/components/tabs.html#scrollable-tabs. 

Had discussions with Christian and Jessica about whether we should use material tabs with icons or without. It's a consensus that using the nav-tabs with icons is a good upgrade, and, alternatively, removing the icons completely wouldn't be too detrimental, as there would also be some benefits to that as well (less noisy, more screen space, moving nav-tabs into the app-bar draws attention to tabs even without icons). But, let's try with icons first!

![navtabs](https://user-images.githubusercontent.com/25045166/45049156-9d607d80-b032-11e8-9317-4a05ecb2945d.png)

### Scroll behavior
Appbar hides on scroll-down
Appbar reappears on scroll-up 

### Mobile behaviors
From material design: offset the first tab on the left to signal that tabs are scrollable.
Example:
<img width="404" alt="screen shot 2018-09-10 at 11 18 56 am" src="https://user-images.githubusercontent.com/25045166/45316257-6df6b880-b4eb-11e8-85d7-bda793c916e2.png">

### Nest point counter within profile dropdown
Notes:
- Point counter is NOT a hyperlink and does not link to the profile tab
- Purely informative static text

<img width="412" alt="screen shot 2018-09-04 at 10 49 06 am" src="https://user-images.githubusercontent.com/25045166/45048238-3e016e00-b030-11e8-92ea-5c5814a73665.png">

**Comment by DXCanas** [comment]
Can't find a figma board for this, but what do we think of aligning the start of the sub-tabs with the world "Learn"

**Comment by indirectlylit** [comment]
@DXCanas mind making a new issue with screenshots?
