### ISSUE TITLE
Show error messages windows only in debug mode

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#4216]
### Observed behavior
Quite often, when a network request fails, Kolibri  is showing a big error message window to the user, alarming and producing being much more disturbing than the error itself.

Example:
This was shown while the user was watching a video. The video worked smoothly, but one contentsessionlog failed and made the user think Kolibri was not working:
![captura de pantalla de 2018-09-04 18-28-04](https://user-images.githubusercontent.com/1008178/45049858-2ce04d80-b080-11e8-8981-4a67c36af319.png)

### Expected behavior
I think we should show these error windows only when Kolibri is in debug/develop mode, not in production. For production logs should save all the needed info.

### User-facing consequences
Avoid alarm the user with non-important error messages.

### Context
 * Kolibri version: 0.9.4
 * Operating system: All
 * Browser: All

**Comment by indirectlylit** [comment]
the error behavior was improved in #4105
