### ISSUE TITLE
Requesting Kolibri Development Pip packages 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4218]
Please kindly provide development version (if you haven't already) of Kolibri on pypi.org. It will help downstream IIAB implementers (like me) test and deliver better kolibri experience. 

https://pypi.org/project/kolibri/#history

**Comment by indirectlylit** [comment]
Thanks for the request @arky - this is a good idea. We sometimes do this, especially for debian packages, but it's not consistent.

I'll work on updating our [beta release process](https://kolibri-dev.readthedocs.io/en/develop/references/release_process.html#integration-testing-and-beta-releases) to explicitly include publishing pre-releases to PyPi and our Debian PPA.

**Comment by indirectlylit** [comment]
process updated here: https://github.com/learningequality/kolibri/pull/4368/files#diff-d65b50da06e8fbcc94e7ac875d52ed66R82

we will now try to publish betas of both the debian and python packages
