### ISSUE TITLE
After deleting the channel, still it is showing the channel name in learn tab.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4234]
### Observed behavior
We have deleted a channel in Kolibri-0.9.5b2. But after deleting the channel in device tab, it removes the entry for that channel. But when we go to the learn tab, it shows deleted channel name.
Please find screenshot for more information.

### Expected behavior
When we delete any channel from device tab, it must not show name of same channel in learn tab.

### Steps to reproduce
1. Login with device owner.
2. Delete the channel.
3. Go to the learn tab.
4. You will see deleted channel name in learn tab.

### Context

 * Kolibri version : Kolibri-0.9.5b2
 * Operating system: Ubuntu 14.04
 * Browser: Chrome

### Screenshots
After deleting channel in device tab:
![screen shot 2018-09-11 at 4 58 50 pm](https://user-images.githubusercontent.com/12776071/45357955-9a8efb00-b5e5-11e8-8c5f-ac4045a8f8f2.png)

After deleting channel in learn tab:
![screenshot from 2018-09-11 13_33_26](https://user-images.githubusercontent.com/12776071/45357989-a975ad80-b5e5-11e8-91d2-a439d33f10c7.png)

**Comment by indirectlylit** [comment]
should be addressed in next release

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri-0.9.5b3. Now, it is not showing deleted channel name in learn tab.

![1](https://user-images.githubusercontent.com/12776071/45666941-cd307a80-bb34-11e8-8ab2-8d6bb688507d.png)

![2](https://user-images.githubusercontent.com/12776071/45666946-d4f01f00-bb34-11e8-971d-dbb054136457.png)
![3](https://user-images.githubusercontent.com/12776071/45666947-d4f01f00-bb34-11e8-85ac-f3d8658b56cd.png)

**Comment by indirectlylit** [comment]
great!
