### ISSUE TITLE
exercise is not marked as 'mastered' in lesson view after completion

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4236]
### Observed behavior
When teacher assigns two exercises in a lesson to the students then students try to solve those exercises. Once student complete its mastery for one exercise then he comes back to the lesson where he can see list of exercises. At that time, he is unable to distinguish which exercise he solved.

Please see attached screenshots for more information.

 
### Expected behavior
It must assign star symbol if student complete its mastery.

### Steps to reproduce
1. Login with teacher.
2. Assign a lesson with two exercise.
3. Login with learner.
4. Go to the lesson.
5. Solved first exercise.
6. After finishing first exercise, come back to the list of exercises where you will not see any star symbol.

### Context
 * Kolibri version : Kolibri-0.9.5b2
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
List of exercises in the lesson:
![1](https://user-images.githubusercontent.com/12776071/45422964-7861af80-b6af-11e8-8f13-b6383910b04d.png)

After completing first exercise mastery:
![2](https://user-images.githubusercontent.com/12776071/45422975-7d266380-b6af-11e8-8d14-07317795b6b1.png)

Go to the lesson and see you will not understand which exercise you solved before because of star symbol:
![3](https://user-images.githubusercontent.com/12776071/45422979-8283ae00-b6af-11e8-9c79-39c194ebe995.png)

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri-0.9.5b3. It is working as expected.

![1](https://user-images.githubusercontent.com/12776071/45666400-ef28fd80-bb32-11e8-8702-de01bbb09b1a.png)

**Comment by indirectlylit** [comment]
thanks for testing!
