### ISSUE TITLE
Lots of scrolling in language select modal

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#4237]
### Observed behavior
As languages in Kolibri increase, so will the scrolling required to find your relevant language. Let's make the language select modal more scalable to fit more languages without scrolling, especially on larger devices.

### Expected behavior
A wider modal width, or more columns to fit more languages within view.

### Mock-ups and behaviors
Here we can use a larger width using something like modal-large. Some suggestions:

- For level 2 screen sizes (<840px) and above, use a 2 column format within modals to display more languages. 3 columns maximum. 
- Swap the ic_network icon with ic_earth. The previous icon was looks too much like a network and ic_earth is more easy on the eyes, after discussing with Jessica and Christian. 
![lang select](https://user-images.githubusercontent.com/25045166/45453930-12692e00-b697-11e8-9f3c-b2593c34b996.png)

<img width="341" alt="screen shot 2018-09-12 at 2 24 31 pm" src="https://user-images.githubusercontent.com/25045166/45454110-9cb19200-b697-11e8-87dc-d10fac17e78e.png">

**Comment by indirectlylit** [comment]
related: #4204

**Comment by indirectlylit** [comment]
columns are complete; still need to change the icon
