### ISSUE TITLE
EPUB search results highlight multiple instances of the search token within a single result

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4239]
### Observed behavior

During search, it's possible that multiple results appear within the same context:

However then a separate link and context is shown for each result. This makes it look like there are 4 results instead of 2.

![image](https://user-images.githubusercontent.com/2367265/45513195-e1e8c900-b756-11e8-9e88-097454f27ba6.png)

### Expected behavior

Only have a single link and quoted context section on the right-hand bar. This will make clear that the two results are the only ones visible 

### User-facing consequences

Initially I thought there were 4 results instead of 2

### Steps to reproduce

* Go to http://kolibri-beta.learningequality.org/learn/#/topics/c/3a721243e176458aae5563fd030c9858
* search for 'chord'

### Context

develop

----

cc @christianmemije

**Comment by jonboiser** [comment]
This seems to be a constraint of `mark.js`. I don't think we can disambiguate between `chord (1)` and `chord (2)`.

It might be an improvement to collapse results like these that are _very_ close in location into a single search result. For me, clicking either result doesn't result in a page change.

**Comment by pcenov** [comment]
@radinamatic this one is still extant in 0.15.1:

![2022-03-25_17-03-23](https://user-images.githubusercontent.com/79847249/160146773-ec2ea2ee-2dde-4c34-b487-130120ecaee7.png)
