### ISSUE TITLE
epub 'selected' state in settings does not have sufficient contrast

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4240]
### Observed behavior

It's really hard to see what item is selected.

The buttons are also generally don't follow our style guide conventions. It's okay if they're a bit different, but maybe they can be brought a little closer?

![image](https://user-images.githubusercontent.com/2367265/45513541-c8944c80-b757-11e8-9e8b-59b9f0841fe7.png)

### Expected behavior

Currently-selected items should be easily observable.

### User-facing consequences

Difficulty switching settings

### Context

Develop

----

cc @khangmach @jtamiace @christianmemije

**Comment by khangmach** [comment]
It's tricky to find a good selection state color that works with both light colors and dark colors. Here's one way to be more flexible, @christianmemije 
<img width="540" alt="screen shot 2018-09-13 at 5 53 25 pm" src="https://user-images.githubusercontent.com/25045166/45523406-01dfb300-b77e-11e8-97ae-a26b704dbcb6.png">

#212121 or #fff check svgs depending on the color

**Comment by christianmemije** [comment]
Used @khangmach's suggestion in https://github.com/learningequality/kolibri/pull/4217/commits/bc7c62b0fa2c760542c026d09bfed67d83db422d
