### ISSUE TITLE
epub text size can be increased/decreased indefinitely

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4241]
### Observed behavior

I can continually click the increase/decrease buttons, but after a while the changes become negligible. It also makes it challenging to reset.

![image](https://user-images.githubusercontent.com/2367265/45513945-ed3cf400-b758-11e8-8cfd-3f59baa64d30.png)

### Expected behavior

Either there should be a min/max font size, or we could provide an enumerated set of size options like Kindle:

![image](https://user-images.githubusercontent.com/2367265/45514049-2d03db80-b759-11e8-90b7-cb25b4877bbd.png)

### User-facing consequences

user might get stuck at a big or small font size

### Steps to reproduce

click click click

### Context

develop

----

cc @khangmach @jtamiace @christianmemije

**Comment by khangmach** [comment]
some thoughts:
- I think we should stick with 6 or 7 text values. Something like 10 12 16 20 24 36 48
- Don't think we need a drastic visual representation like kindle. If we have a limited number of values, it's easy to reach and understand there's a min/max limit.

**Comment by christianmemije** [comment]
Limited to 7 sizes in https://github.com/learningequality/kolibri/pull/4217/commits/bc7c62b0fa2c760542c026d09bfed67d83db422d
