### ISSUE TITLE
typography of epubs is difficult to read

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4243]
### Observed behavior

* line spacing is very tight
* default serif font
* 'justified' lacks hyphenation, causing spaces between words
* 'grey' theme is hard on the eyes

### Expected behavior

To the degree that we have control over styling, we should make the text easier to read

### User-facing consequences

users won't be comfortable reading for long periods of time

### Steps to reproduce

see for example:

* http://kolibribeta.learningequality.org/learn/#/topics/c/3991a2b10f444679a65b44d7abee3926
* http://kolibribeta.learningequality.org/learn/#/topics/c/3a721243e176458aae5563fd030c9858

### Context

develop

----

cc @jtamiace @khangmach @christianmemije

**Comment by christianmemije** [comment]
Line height adjusted to 1.4 em in https://github.com/learningequality/kolibri/pull/4217/commits/42c2a9ac7fa6ea56acd78702e2b1ea267ef110aa
I do not want to mess with fonts since a lot of epub come with their own embedded fonts and I do not want to override them.
I'll keep the justified option, but default to left aligned. 
I will change the gray theme color from #6d6d6f to #58585a to improve contrast.

**Comment by indirectlylit** [comment]
Sounds good!

I'm still unclear on the purpose of providing a 'justified text' option - unlike text size and color scheme which have clear usability purposes.

For some context on why I'm opposed, see:

* https://practicaltypography.com/hyphenation.html
* http://theworldsgreatestbook.com/book-design-basics-hyphens-justification/

**Comment by radinamatic** [comment]
I'd agree that the justified text option on ePUB reader is superfluous to say the least, but if it's not creating other issues (and it's not the default option), might as well leave it at this point...

**Comment by indirectlylit** [comment]
you might say it's... _unjustified_ 

:D

**Comment by radinamatic** [comment]
¡Nunca mejor dicho! :sunglasses:
