### ISSUE TITLE
Epub renderer - Some epubs do not load

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#4260]
http://kolibribeta.learningequality.org/learn/#/topics/c/51ae93701a2f462e8da721ffa6a62c0c
http://kolibribeta.learningequality.org/learn/#/topics/c/0d46010189924cb1aa8d3eff481f7a5f

**Comment by jonboiser** [comment]
Neither of these books open on Apple iBooks.

**Comment by jonboiser** [comment]
This should probably still be handled on the UI with an error message. For the accounting book, iBooks gave me a 'book is corrupted' error (might be due to DRM since it is suggested to use Adobe Digital Editions by the publisher). For the Alice and Wonderland book, it just failed to open silently.

**Comment by christianmemije** [comment]
Submitted a fix upstream for the Alice's Adventures in Wonderland epub https://github.com/futurepress/epub.js/pull/826.

**Comment by christianmemije** [comment]
Added error handling to catch the 2nd epub in https://github.com/learningequality/kolibri/pull/4217/commits/3b1fe69aa106a6f13aa56be15c50a4a006d5e3b2
![localhost_8000_learn_ nexus 7](https://user-images.githubusercontent.com/7193975/45786576-efee8c00-bc25-11e8-97c3-c45f2e7a7b45.png)

**Comment by christianmemije** [comment]
Pointing to new version of epubjs that includes the fix in https://github.com/learningequality/kolibri/pull/4217/commits/f6b0b09f6f87bfb88fa829360d04834907fe9f09
