### ISSUE TITLE
add basic kolibri manage command for testing server performance

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4270]
### Observed behavior

We often get reports of performance issues in the field, but it can be challenging to debug with remote users in other timezones with limited connectivity.

### Expected behavior

Let's add a diagnostics command that can be run to help us debug performance issues on peoples' servers. We can request that people run the command when they're experiencing poor performance, and then send us the output.

Some statistics we might include:

* Number of logged-in users
* CPU load
* total and used RAM 
* OS process list
* metrics about the time to hit some test endpoints:
  * a basic ping
  * a processor-intensive command
  * a DB-intensive command
* time to download a large static file (can this be generated so it doesn't need to be distributed?)

If there are other things that would be helpful to include, let's do so. Conversely, things above seem too difficult, let's skip them.

### User-facing consequences

easier to help us debug performance issues

**Comment by jamalex** [comment]
:+1:

**Comment by jredrejo** [comment]
I have already begun to work on it. Actually I was doing it as a command, so it seems we are in sync :)
Reading this description I see a problem for the 'metrics about the time to hit some test endpoints' part. As I see it, this can be done measuring the time those request take in the server. In such case, we are removing the network performance problems out of the equation. I don't know if that's enough. Trying to do it taking into account the request time from a client looks feasible but a bit complex to architect. I don't know if that's complexity is worth. I would like to know other people opinions.

Also, I wonder if the idea is having a predefined list of endpoints that are known to be slow (for the cpu/database intensive requests) or get the stats of all the requests and show the most consuming ones. Both things can be done, but I am afraid creating the latest stats can cause performance interferences (we can fall into the Heisenberg's principle).

So, summarizing, I would like to know what are your ideas/opinion. In the meantime, I will continue working in the four points that are very clear.

**Comment by benjaoming** [comment]
Can I propose 3 commands, based on whether information needs kolibri to be running or not? And do you like the naming + CLI of these?

```
# Basic installation & diagnostic system information, does not require a running instance. Can also include processor/memory/disk information, as this doesn't require kolibri and be reasons that kolibri doesn't even start!
kolibri manage diagnose

# Detailed information about running instance, which requires a running instance. Notice that the `status` command already exists. IMO it seems natural to extend it.
kolibri manage status --runstats

# Future work: Requires a running server. May or may not depend on Velox. May even benchmark an external kolibri.
kolibri manage benchmark
```

**Comment by jredrejo** [comment]
@benjaoming for the `kolibri manage diagnose` option I don't see the point. You can't measure users, cpu/memory usage while running kolibri, slow endpoints, etc. We only can get the list of specs of the hardware, something similar to ask the user to give us the output of `hwinfo`. There are many free tools in Windows and Linux (in MacOS you only need to open the OS  help menu) that  provide that information.

**Comment by bonidukic** [comment]
> There are many free tools in Windows and Linux (in MacOS you only need to open the OS help menu) that provide that information.

While I agree with you that there are many free tools that provide these kind of information, I'm with Ben on this one as it would be much easier to ask of the users to copy/paste the output given by the `diagnose` command rather than asking them to provide us a list of stats we want to know, in the meantime probably having to point them to where and how to find those stats.

Additionally, I'm guessing it would be easier for us as we'd get a standardized output regardless of the OS (hopefully).

**Comment by indirectlylit** [comment]
I like the idea of splitting these up into multiple categories as an implementation detail.

However from a UX point of view, I'd prefer that we can provide users with a single command for them to run, and that will give them a single set of output that they can paste back.

If in the future we decide that the single command takes too long to run or dumps too much information, we can break it up then.

**Comment by radinamatic** [comment]
So great that we are thinking about these commands! 
Agreed with Devon that a single command and "copy-pastable" output would be much easier on the users.

**Comment by indirectlylit** [comment]
> I see a problem for the 'metrics about the time to hit some test endpoints' part.  As I see it, this can be done measuring the time those request take in the server. In such case, we are removing the network performance problems out of the equation. I don't know if that's enough.

Let's try and approach this from the perspective of trying to gather information we would ask for in the course of debugging a problem. For example, if someone says "It's very slow to play videos from our tablet computers which are connected over wifi to the server", what information do we need to collect to help narrow down the source of their issue?

If our tool says that local streaming is fast, we at least rule out the server speed. Maybe then there's wifi interference, or the server is not connected to the router over ethernet, or maybe the tablet itself is too slow? Our tool doesn't provide that information.

I think our goal should be to glean as much information as possible, while acknowledging the limits of the tool.

In a future iteration, we can build a client-side UI and instrumentation into the web app and that will make it easier to diagnose network and client device issues.

**Comment by indirectlylit** [comment]
(I'm not advocating for any particular metrics - just trying to frame our decision-making process about what metrics to include)

**Comment by rtibbles** [comment]
While not directly in Kolibri, inspection of nginx timing logs has been invaluable for understanding how Kolibri is performing under load (and understanding whether load issues are due to Kolibri itself, or network conditions) - would be good to consider being able to either upload these log files, or a parsed summary of them if we start to include nginx in our installers/as a dependency.

**Comment by benjaoming** [comment]
> @benjaoming for the `kolibri manage diagnose` option I don't see the point.

@jredrejo that would be the point: For unpredictable reasons, people may not be able to start kolibri. So _not_ requiring a running instance for diagnostics _is_ intentional. Of course, if Kolibri is running, those diagnostics can be used to measure Kolibri's system foot print.

Note that I'm not trying to argue exactly what should be part of `kolibri manage diagnostics`, the idea of 3 different commands was to clearly frame which metric goes where, if at all possible.

> There are many free tools in Windows and Linux (in MacOS you only need to open the OS help menu) that provide that information.

We actually have another issue open with related metrics: #3285
