### ISSUE TITLE
Incorrect disk size unit in Device info

### ISSUE THREAD

**Issue by bonidukic** [learningequality/kolibri#4272]
### Observed behavior
_Free disk space_ size in the _Device_ -> _Info_ page is currently displaying values which correspond to Kibi, Mebi and Gibi prefixes (KiB, MiB, GiB respectively) rather than values which correspond to Kilo, Mega and Giga prefixes (KB, MB, GB respectively).

Kibi, Mebi and Gibi prefixes denote powers of two, whereas Kilo, Mega and Giga denote powers of ten.

#### Example
If the free disk size is reported to be 154910425088 bytes, then the value displayed should be 154 GB, and not 144 GB which is currently being displayed.

##### Kolibri
![selection_003](https://user-images.githubusercontent.com/2150991/45678311-53ae8180-bb60-11e8-8179-22653627e6b2.png)

##### OS
![selection_006](https://user-images.githubusercontent.com/2150991/45679578-1a2b4580-bb63-11e8-9be9-a47efe994c41.png)

### Expected behavior
To avoid potential confusion, disk sizes should be correctly displayed using Kilo, Mega and Giga prefixes.

### User-facing consequences
Could be confusing to some users if they compare free disk size values from the OS utilities and what Kolibri displays.

With the above used example the difference is 10GB which is a substantial difference.

### Steps to reproduce
Visit _Device_ - _Info_ page in Kolibri and compare the _Free disk space_ size to the one from your OS.

### Context
 * Kolibri version - 0.11.0a5.dev+git.292.gbbc6266b0
 * Operating system - Ubuntu 17.10
 * Browser - Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by indirectlylit** [comment]
possibly related: https://github.com/learningequality/kolibri/issues/3883

**Comment by bonidukic** [comment]
@indirectlylit Actually, I was investigating that particular issue when I found the units mismatch.

**Comment by indirectlylit** [comment]
@bonidjukic if you're interested in another puzzle, see my comment here :) https://github.com/learningequality/kolibri/pull/4285#issuecomment-423005340
