### ISSUE TITLE
Inconsistent use of root: true for dispatching core actions in modules

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4282]
### Observed behavior
In many places where core actions (such as `handleApiError`) are dispatched from within Vuex modules, no options object is passed with `{ root: true }` as recommended in the Vuex docs (and as implemented in some places of the code base).

### Expected behavior
If this is required, then I assume it should be being used in all places where we are dispatching root actions within a module.

### User-facing consequences
We might not actually catch errors, and just cause another error instead?

**Comment by indirectlylit** [comment]
cc @jonboiser if you have thoughts

**Comment by jonboiser** [comment]
This `root: true` only needs to be used if calling a core action from within a namespaced module's action, since the `store` object passed in those actions assumes the module scope.

In all other places where `{ root: true }` is not provided, it is because that particular function has access to the global `store` object. This is why all of the handler functions do not need this option.

**Comment by rtibbles** [comment]
Yes, I am only alerting to its lack within module action definitions

> it should be being used in all places where we are dispatching root actions within a module.

e.g.
https://github.com/learningequality/kolibri/blob/f5ec8ba9525f0ccef48bcc04c721f315471f0b98/kolibri/plugins/facility_management/assets/src/modules/userManagement/actions.js#L92

https://github.com/learningequality/kolibri/blob/aba1d80f165cf6c50b618f344ca777e0cd39876d/kolibri/plugins/learn/assets/src/modules/coreLearn/actions.js#L21

https://github.com/learningequality/kolibri/blob/f5ec8ba9525f0ccef48bcc04c721f315471f0b98/kolibri/plugins/user/assets/src/modules/profile/actions.js#L51

(there are more).

**Comment by jonboiser** [comment]
There are 3 spots that need this option. The patch is in #4292. coreLearn and coreCoach are not namespaced so the references to handleAPiError do not need the root: true option. The setup_wizard reference is also global scope.

**Comment by indirectlylit** [comment]
Just a thought: is there harm to adding `{ root: true }` even when it's not strictly necessary? Might be useful to do it as a convention so that if people copy/paste core action dispatches from one place to another, they 'just work'.

**Comment by jonboiser** [comment]
There's no harm in doing that. I think it might be time to make core a namespaced module as well, so it is more apparent why root: true is needed.

If you see `store.dispatch('core/handleApiError', error, { root: true })` inside of a module's action, it will stand out more.

**Comment by indirectlylit** [comment]
> I think it might be time to make core a namespaced module as well

totally agree
