### ISSUE TITLE
All other usernames get hidden on facility user page when one user has a very long name

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4290]
### Observed behavior
A user with the max length name (120 chars) expands the size of the table outside the fixed width boundary, hiding all other usernames.

![image](https://user-images.githubusercontent.com/1680573/45821663-bfefc900-bcb7-11e8-9702-79a2ee341362.png)

It does show a scrollbar at the bottom of the page, but this is below the fold for all but a very small number of users.

### Expected behavior
Wrap long full names? Elide them? Do something!

### User-facing consequences
Could be confusing if a user has a long name - especially if the users can edit their own name and decide to do something super long!

### Steps to reproduce
Add or edit user.
Give them full name of max length.

### Context
Kolibri 0.11.0-alpha

**Comment by indirectlylit** [comment]
see also #2627
