### ISSUE TITLE
bring Coach search behaviors in line with Learn

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4297]
### Observed behavior

* In #4253 @jonboiser began adding search functionality to lesson and exam resource management.
* In #4183 @rtibbles added a variety of improvements to the Learn resource search functionality

Currently the Learn improvements - particularly pagination and improved filtering - are not yet in Coach

### Expected behavior

* 'Update search' behaviors should be copied over so that filtering can occur before the query is applied
* Users should be able to load additional results if available and desired

### User-facing consequences

Some valid search results might not currently be accessible

**Comment by christianmemije** [comment]
Implemented search in exam creation in #4378
