### ISSUE TITLE
Should choose content format that has available renderer

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#4301]
### Observed behavior

When there are multiple presets available for a piece of content, but there's no renderer capable of handling the first one, it errors out:

![image](https://user-images.githubusercontent.com/618416/45853477-85f3e680-bcfa-11e8-8d47-b78ca017d55b.png)

### Expected behavior

In the case above, we *do* have a PDF renderer, so it could have fallen back to that file and used that renderer.

Additionally: we should ensure we use the new le_utils "order" field to select the highest priority content preset from those available (and renderable).

### Steps to reproduce

1. Create a channel with a content node and an epub
1. Download the channel to kolibri (with epub renderer disabled)
1. Load that content node under /learn/

### Context

0.11 (develop)

**Comment by jamalex** [comment]
Longer-term: we should add in the drop-down for switching between available non-supplementary presets.

**Comment by indirectlylit** [comment]
May want to consider targeting this at 0.10?

**Comment by rtibbles** [comment]
I think so, @indirectlylit - this is a backwards compatibility concern otherwise.
