### ISSUE TITLE
Able to create an exam with less questions than specified

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#4302]
### Observed behavior

If you specify a number of questions larger than those available, app proceeds to try and create the exam with several blank questions that break the app

![screenshot from 2018-09-20 17-59-48](https://user-images.githubusercontent.com/9877852/45854286-3c59ca80-bcff-11e8-883b-c050b5ebbccb.png)
![image](https://user-images.githubusercontent.com/9877852/45854279-3237cc00-bcff-11e8-80e1-a46954ec4a53.png)
![image](https://user-images.githubusercontent.com/9877852/45854326-73c87700-bcff-11e8-84e6-70c5d2c22fb8.png)

### Expected behavior

Catch error and display appropriate error message (coming in #4271)

### User-facing consequences

broken exams

**Comment by rtibbles** [comment]
Is this still extant?

**Comment by indirectlylit** [comment]
this should be addressed in recent work
