### ISSUE TITLE
add management command to initiate permanent deletion of a user

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4303]
### Observed behavior

Currently, when a user is deleted through the UI, that update might not delete progress information associated with the user, and the deletion might not propagate out to other devices that have been synced through Morango.

If an administrator is trying to comply with a GDPR account deletion request, they would currently have to reach out to us for support in making direct updates to the database.

### Expected behavior

We need to add a Django command which will initiate the deletion process for a user:

* set a deletion flag
* purges all related records
* propagates this purge to other devices when they sync

### User-facing consequences

harder process to comply with GDPR and similar account deletion requests

**Comment by ralphiee22** [comment]
This seems to need some development work in morango because we never actually fully delete records since they would still exist in the store. Will probably need to add a `hard_delete` flag in morango.

**Comment by indirectlylit** [comment]
yes I think that is essentially what @jamalex suggested

**Comment by indirectlylit** [comment]
hooray! thanks @ralphiee22
