### ISSUE TITLE
Better Drive Names in Export Dialog box

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4307]
When exporting content packages you will be presented with the following screen. Perhaps more human friendly drive names or paths would be ideal for an average user.  

The testcase was run on my development gnu/linux laptop with latest stable kolibri(0.10.2). 

…
![screenshot from 2018-09-21 12-19-40](https://user-images.githubusercontent.com/808895/45861789-d883e000-bd98-11e8-8178-38c9b3886549.png)

**Comment by indirectlylit** [comment]
@arky for context, how are these drives named in your OS?

**Comment by arky** [comment]
@indirectlylit The drives are named using UUID (standard linux) drive labels. Here is disk geometry. 

$ sudo fdisk -l /dev/sda
Disk /dev/sda: 167.7 GiB, 180045766656 bytes, 351651888 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x000aaaf9

Device     Boot     Start       End   Sectors  Size Id Type
/dev/sda1  *         2048    718847    716800  350M  7 HPFS/NTFS/exFAT
/dev/sda2          718848 101869399 101150552 48.2G  7 HPFS/NTFS/exFAT
/dev/sda3       101869568 192585727  90716160 43.3G 83 Linux
/dev/sda4       192587774 351649791 159062018 75.9G  f W95 Ext'd (LBA)
/dev/sda5       192587776 335529983 142942208 68.2G 83 Linux
/dev/sda6       335532032 351649791  16117760  7.7G 82 Linux swap / Solaris

**Comment by radinamatic** [comment]
Do we even have other options for drive names? Maybe the user changed the labels and renamed the fixed drives, but that is rarely done for external ones that you plug & unplug constantly... :thinking:

**Comment by indirectlylit** [comment]
It looks like on linux we currently display disk manufacturer info as the name, but more common practice is to show things like mount location and identifier ID.

Probably what we want to do is have a primary name with some metadata underneath

**Comment by radinamatic** [comment]
Metadata like size? I often default to recognizing my different drives by remembering their size...

**Comment by indirectlylit** [comment]
metadata like mount point and ID

**Comment by arky** [comment]
From a users perspective, showing a mount point such as "/", "/media" is ideal when screen space is limited or too many drives/partitions are present. 

Perhaps additional information such as disk type (denoted with a usb pen drive icon), disk capacity and disk free space could be shown to the user to make informed decision about exporting the data. 

Am attaching a very common linux application UX experience here.
![startup-disk-creator-3](https://user-images.githubusercontent.com/808895/46309669-327d7480-c5e7-11e8-9759-23b692bbf49e.png)

**Comment by rtibbles** [comment]
The dialog now shoes the mount path by default on Linux, so I think this is fixed.
