### ISSUE TITLE
Learner Lesson Playlist does not update automatically

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4316]
### Observed behavior

1. I try to edit a Lesson X(e.g. add a resource) as a Coach
1. Go to the Learn page (in coach account), then Lesson Playlist (for Lesson X) page, but the Playlist is not up-to-date. The Lesson API is returning the correct object, but the `contentnode_slim?in_lesson` response is not returning all of the resources.
1. Refreshing does not update the list
1. However, if I log-out, then log back in, then go back to the Lesson Playlist, the resources are up to date.

### Expected behavior

The LessonPlaylist Page is up-to-date and reflects the latest changes to a lesson

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jonboiser** [comment]
Adding a `force: true` on this line doesn't seem to work. https://github.com/jonboiser/kolibri/blob/2bc7be47415654837858c20bf1e5c7d1700b20fa/kolibri/plugins/learn/assets/src/modules/lessonPlaylist/handlers.js#L16

**Comment by indirectlylit** [comment]
cc @rtibbles perhaps the result of more aggressive recent caching?

**Comment by rtibbles** [comment]
Yes, seems right as it is on the content node endpoint.

**Comment by rtibbles** [comment]
Have updated milestone as will effect 0.10 too, as I believe they both use the "in lesson" get param.

**Comment by rtibbles** [comment]
Chatted with @ralphiee22 and as the `in_lesson` get param is just a covenience wrapper around the previous `ids` behaviour that was used here, reverting this seems like the simplest fix.

**Comment by jonboiser** [comment]
`in_lesson` is slightly safer than `ids` because it works even if the underlying channel has been deleted. In the coach lesson's workflow, we still use the `id` filter and the Lesson Summary Page can crash if any resource's channel has been deleted.

**Comment by rtibbles** [comment]
OK, can make the ids filter safe to handle this - thanks for info!

**Comment by rtibbles** [comment]
Hrm, the `ids` filter still works fine - the only difference is that it doesn't handle badly formed uuids. The issue in the LessonSummaryPage is due to the frontend not handling the content node not existing, the API request returns properly.

**Comment by jonboiser** [comment]
So one of the actions in LessonSummaryPage uses this code

in lessonSummary/actions.js
```
    return ContentNodeResource.fetchCollection({
      getParams: {
        ids: nonCachedResourceIds,
      },

```

If `nonCachedResourceIds = [ok_node, deleted_node]`, I thought this request would fail completely, instead of filtering out `deleted_node` and still returning a 200 with `[ok_node]`.

**Comment by rtibbles** [comment]
It will return a 200 with just `[ ok_node ]`. The issue stems from this:
```
      return getResourceCache(store, resourceIds).then(() => {
        store.dispatch('SET_WORKING_RESOURCES', resourceIds);
        store.dispatch('SET_LEARNER_GROUPS', learnerGroups);
        store.dispatch('SET_LESSON_REPORT', lessonReport);
        store.dispatch('CORE_SET_PAGE_LOADING', false);
        store.dispatch('SET_PAGE_NAME', LessonsPageNames.SUMMARY);
        store.dispatch('CORE_SET_TITLE', currentLesson.title);
      });
```
So the `workingResources` gets set to the resource ids on the lesson model, regardless of whether the resources exist or not.

**Comment by rtibbles** [comment]
Through a combination of #4321 and #4365 this should now be fixed.
