### ISSUE TITLE
loading-spinner.gif is large and poorly exported

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4329]
### Observed behavior

Our loading spinner is 100KB. It's also poorly exported:

* the outer edges are aliased against the transparent background
* the inner edges are blurry, as though scaled from pixels rather then exported from vectors, which works against the compression
* each frame of the gif re-draws all previous frames, wasting bytes

![loading-spinner](https://user-images.githubusercontent.com/2367265/46098655-c4195c00-c179-11e8-9e52-6946c9c58ae2.gif)

### Expected behavior

The loader should either be a well-exported and optimized gif, or it should be done as an inline SVG.

[The original is here](https://drive.google.com/file/d/0B9ZzDms8cSNgRnlSbzJjOWxGMzQ/view)

### User-facing consequences

ironically slow-loading loading indicator

### Context

0.11

**Comment by MisRob** [comment]
Hi!

I've been watching you for some time, I appreciate what you do :)! I checked developer docs and now I would like to pick a couple of smaller issues to get acquainted with the project and start contributing eventually when I have some free time - can I assign myself to this one and to some other free issues after this one is done ? Thanks.
