### ISSUE TITLE
Total size of channel in the import page is shown as 0

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#4331]
### Observed behavior

In the channel import page, the total size of the channel is shown as 0.

### Expected behavior

The total size of the channel should be shown correctly.

### User-facing consequences

Users don't know how large this channel is.

### Errors and logs

<img width="355" alt="screen shot 2018-09-26 at 12 23 47 pm" src="https://user-images.githubusercontent.com/19424916/46104512-5cb6d880-c188-11e8-8465-edc90455f766.png">

### Steps to reproduce

1. Click import
2. Select `Kolibri Studio`
3. Select a channel at the import page and import the channel metadata -- at this time, the correct total size of the channel is shown
4. Go back to the channel list page
5. Click import
6. Select `Kolibri Studio`
7. Go to the imported channel page and check the total size of the channel

### Context

Kolibri version: 0.11 a7
Operating System: OSX
Browser: Chrome

**Comment by jonboiser** [comment]
For me the response from `http://localhost:8000/api/content/remotechannel/0e173fca6e9052f8a474a2fb84055faf/`, where the total size data comes from, is correct both times (when file sizes are correct and zero).

**Comment by lyw07** [comment]
I tried again but this error still shows up on my laptop. I recorded a video for it:
![tota_size_error](https://user-images.githubusercontent.com/19424916/46167417-96e8ae80-c24a-11e8-923e-44739cf9dbb5.gif)
