### ISSUE TITLE
Not showing 100% while importing the channel.

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4350]
_From @swapnil106111 on September 26, 2018 10:56_

## Summary
When we import channel, it does not show 100% imported. It stops at 99.7% and shows CLOSE button.

I think, size of content is not updated in database.
## Category

Select one: BUG 

## Usage Details

 - Browser: Chrome
 - Channel: bisor-juhol
 - Topic/Content Item: CBSE Khan Academy Math 6-9 (English) -> Class 9 (India) -> Inequalities in a Triangle ->  Inequalities in a Triangle

## How to reproduce

1. Import channel : bisor-juhol
2. Import specific path : CBSE Khan Academy Math 6-9 (English) -> Class 9 (India) -> Inequalities in a Triangle ->  Inequalities in a Triangle

## Screenshots

![error](https://user-images.githubusercontent.com/12776071/46075685-db237280-c1a8-11e8-8d50-c611c552e81f.png)

_Copied from original issue: learningequality/studio#994_

**Comment by indirectlylit** [comment]
Do we have a Kolibri version number?

We've seen similar issues in the past:

* #614
* #4014

**Comment by benjaoming** [comment]
@indirectlylit I moved this issue so it's not following the normal issue template - maybe @swap106111 can add a few more details like the version number.

Otherwise, let's try and see if we can reproduce it...

**Comment by swapnil106111** [comment]
@benjaoming We faced this issue in Kolibri-0.9.5b3.

**Comment by benjaoming** [comment]
@swapnil106111 - thanks for the extra info.

In this case, I'm 99.7% sure it is the same as https://github.com/learningequality/kolibri/issues/4014 :smile: 

This was fixed and released in 0.10.1 - so closing this. Thanks for reporting and please keep doing so :)
