### ISSUE TITLE
IE11 setup wizard step 7 broken text line break

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4353]
### Observed behavior
Setup wizard step 7 broken text line break at the IE11.
### Expected behavior
Text should display properly at the IE11

### Errors and logs
![screen shot 2018-10-02 at 2 13 52 pm](https://user-images.githubusercontent.com/8663934/46332433-16adb900-c64f-11e8-84ff-bedb9a77c3a0.png)

### Context
 * Kolibri version: Kolibri 0.11.0a7
 * Operating system: Windows 7
 * Browser: IE11

**Comment by indirectlylit** [comment]
good catch, thanks

**Comment by indirectlylit** [comment]
@mrpau-richard, this should be addressed but please keep an eye out for it during integration testing next week
