### ISSUE TITLE
large 'play' button in videos sometimes didn't work on touch screens

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4360]
### Observed behavior

While observing users in Kakuma try to play videos on touch-screen tablets, I repeatedly observed users trying and failing to play videos by clicking the 'play' button in the center of the screen. They had more luck using the button next to the time slider.

It was also unclear to the users whether the play was starting and just laggy or if it wasn't starting at all, so it could take quite a few tentative tries before realizing that it simply wasn't working.

This may have been partly because the hit area was so small?

### Expected behavior

Play button should work consistently. Probably, clicking _anywhere_ in the video window should play/pause the video.

### User-facing consequences

Frustration: so close, and yet the video just won't start playing!

### Steps to reproduce

Try to play a video using the center button on an android tablet

### Context

I need to investigate what version they were running, because I think we updated to auto-play, and I don't recall this happening.

**Comment by pcenov** [comment]
@radinamatic cannot replicate in 0.15.1

**Comment by radinamatic** [comment]
Thank you, closing as not extant! 💯
