### ISSUE TITLE
follow-up items from i18n tooling updates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4364]
### Observed behavior

left-overs from #4254

### Expected behavior

* [ ] unit tests for new scripts
* [ ] load `VueIntl` locale data from a `<link>` like the CSS, and [just load current language](https://github.com/learningequality/kolibri/pull/4254#discussion_r222850411)
* [ ] ensure Django has static file caching and cache busting working
* [ ] Look at building the CSS files during `make assets` rather than checking them into git
* [ ] switch command-line [docs to docopt](https://github.com/learningequality/kolibri/pull/4254#discussion_r222925285)
* [ ] preload language fonts earlier, instead of waiting for all JS to load

### Context

k011

**Comment by benjaoming** [comment]
I don't think that unit tests for build tools are essential -- but testing the artifacts resulting from the builds is :)

Builds are generated during all CI test runs, anyways.. so the most obvious failures are caught.

If the CrowdIn CLI gets its own project, we could/should add tests!

**Comment by indirectlylit** [comment]
closing as stale
