### ISSUE TITLE
follow-up from 'Inline nav items' work

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4366]
### Observed behavior

In #4249 @rtibbles added the ability to inline certain webpack files to prevent lots of extra webpack requests.

This is working for CSS, but it looks like some JS is still being loaded in separate requests:

![image](https://user-images.githubusercontent.com/2367265/46556313-41e51200-c8b4-11e8-9cdd-361d2ff9a301.png)

### Expected behavior

All 'nav' JS should be inlined

### User-facing consequences

slower load

### Context

0.11

**Comment by rtibbles** [comment]
![image](https://user-images.githubusercontent.com/1680573/46616524-94e6e100-cacf-11e8-8449-5df79df446c0.png)

Not replicating on develop. Were you testing this in production, or in devserver? As noted in #4249:
> This only affects production, development stays the same, as I didn't want to implement fetching the files from the webpack dev server.
