### ISSUE TITLE
test coverage is incorrectly reported by codecov

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4370]
### Observed behavior

Just noticed the coverage from #4357 seems to miss something. I haven't looked into the cause, I think it's just a call with `--scheduled` that's missing in tests and would be easy to fix?

If it's because threads don't get coverage collected, then perhaps we should rename this issue to deal with this at a later point.

![image](https://user-images.githubusercontent.com/374612/46570964-2853d100-c96d-11e8-98d9-331357d82e44.png)

https://codecov.io/gh/learningequality/kolibri/compare/5093433dea4fc697341ba3bcce580e111af3009e...affa7599b1be6e325553c243b535ad6bc611fd87/diff

### Expected behavior

Coverage

### User-facing consequences

We'll end up breaking an untested core command in production.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

Current `develop`

**Comment by benjaoming** [comment]
@ralphiee22 could you have a quick look?

**Comment by ralphiee22** [comment]
@benjaoming I looked into it, but it does not look like `server.start()` is covered in any of the tests (this is where the vacuum thread is called with `schedule=True`, as well as the ping thread). So do we just want to handle the vacuum case where `scheduled=True` or do we want `server.start()` covered as well?

**Comment by benjaoming** [comment]
@ralphiee22 oh that's an issue on a whole different level then, we are supposed to create coverage reports for every step in `tox.ini` and combine the reports?

Collection of `kolibri start` coverage here:

https://github.com/learningequality/kolibri/blob/56c9adc4a32d0e6327a78a1c029485e27877e7b6/tox.ini#L41

Combination here:

https://github.com/learningequality/kolibri/blob/56c9adc4a32d0e6327a78a1c029485e27877e7b6/.travis.yml#L105-L108

**Comment by ralphiee22** [comment]
Not sure if I'm navigating the report correctly, but this is what I find for that function.
https://codecov.io/gh/learningequality/kolibri/src/develop/kolibri/utils/server.py#L64

**Comment by benjaoming** [comment]
That's no good :/

Changing the title of this issue...

**Comment by jonboiser** [comment]
Codecov has been disabled for now. If we bring it back, let's make sure the coverage reports make more sense.
