### ISSUE TITLE
Kolibri Khmer Translation 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4375]
Filing this bug to translate kolibri in Khmer (km) [Cambodian language](http://www.loc.gov/standards/iso639-2/php/langcodes-keyword.php?SearchTerm=khmer&SearchType=ALL). 

@jflaflamme @manuthchek Please kindly help me with this translation 

https://github.com/learningequality/kolibri/tree/develop/kolibri/locale

**Comment by radinamatic** [comment]
@arky Thank you for initiating this. Khmer locale is already available on [Kolibri Crowdin page](https://crowdin.com/project/kolibri/km#).

@jflaflamme @manuthchek If you want to contribute translations, please contact @carinediaz or me for  the translator onboarding procedure.

**Comment by jflaflamme** [comment]
Just to inform you that @manuthchek have started last week on Crowdin and we will update here once completed or on any blocking points :-)

**Comment by radinamatic** [comment]
@jflaflamme Thank you for the update, and for starting the translation process already!

Don't hesitate to contact us should you have any questions or concerns :slightly_smiling_face:

**Comment by indirectlylit** [comment]
closing as stale. When Khmer has been translated in Crowdin, let's open a new issue to track integration into Kolibri
