### ISSUE TITLE
'view more' is shown even when there's enough space to show everything

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4394]
### Observed behavior

| collapsed | expanded |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/46844954-38bdde80-cda7-11e8-8491-d76da63f0a15.png) | ![image](https://user-images.githubusercontent.com/2367265/46844961-3fe4ec80-cda7-11e8-81cf-f047ccbd84a1.png) | 

### Expected behavior

'view more' should only be shown when there's not enough space on the card to display the text

### User-facing consequences

unnecessary clicking, wasted whitespace

### Context

0.11

**Comment by jonboiser** [comment]
In the usages of `TextTruncator`, the max height is set at 40-50px, which is about two lines. Maybe we could make this as high as 150px to handle the 'expanded' example above. It would probably still work when the cards are wider.
