### ISSUE TITLE
Coach page freeze on Windows 7 IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4398]
### Observed behavior
Browser freeze when I navigate at the coach page using IE11 browser.

### Steps to reproduce
* Install the `kolibri-0.11.0-beta1` on Windows 7 32 bit
* Sign in as superuser
* Create only one class.
* Navigate at the coach page
 
### Context

 * Kolibri version: 0.11.0-beta1
 * Operating system: Windows 7 32 bit
 * Browser: IE11

**Comment by radinamatic** [comment]
Not able to replicate this on my VM setup Win 7 & IE11. Coach pages open correctly, just one class with  2 learners... 

![2018-10-16_22-38-41](https://user-images.githubusercontent.com/1457929/47046026-80bc7700-d194-11e8-9358-9f9a895aaab9.png)

@mrpau-julius @mrpau-richard Does this error happen consistently, even after you restart Kolibri or VM?

**Comment by mrpau-richard** [comment]
@radinamatic yeah, this issue still happened when I restart my Windows 7 VM. I'm using this IE version: 
![screen shot 2018-10-17 at 1 52 41 pm](https://user-images.githubusercontent.com/8663934/47065272-f9fbae80-d214-11e8-8fe3-99327667c244.png)

I think this issue can only reproduce on `IE11.9600.17420` version.

**Comment by christianmemije** [comment]
@mrpau-richard  Are there any console errors when you visit the coach page? Or any server errors?

**Comment by mrpau-richard** [comment]
@christianmemije I have this `.GIF` file to show some browser logs when I navigate at the coach page.
![temp](https://user-images.githubusercontent.com/8663934/47135022-575d3180-d2e1-11e8-913d-fa2e8979095c.gif)

Here's my Kolibri [server.log](https://github.com/learningequality/kolibri/files/2490501/server.log) file.

**Comment by jonboiser** [comment]
The line referred to in the server.log stack trace is different. @jamalex 	Does this change fix the error @mrpau-richard is seeing in the server logs?

The error:

```
  File "C:\Python34\lib\site-packages\kolibri\core\analytics\management\commands\ping.py", line 89, in perform_ping
    return json.loads(response.content or "{}")
  File "C:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

The change

```diff
- return json.loads(response.content or "{}")
+ return json.loads(response.content.decode() or "{}")
```

https://github.com/learningequality/kolibri/blame/release-v0.11.x/kolibri/core/analytics/management/commands/ping.py#L113

**Comment by jonboiser** [comment]
I'm not sure if this would freeze the app in the browser though, especially since there were no obvious run time errors in the screenshot. Would a pending response from the 'ping' freeze the app?

**Comment by indirectlylit** [comment]
> Would a pending response from the 'ping' freeze the app?

no - that should be happening in a completely different thread.

**Comment by jonboiser** [comment]
One thing that looks odd in the screen capture is that the "Form Autocomplete" pop-up appears on the bottom of the screen right after navigating to Coach. But there is no form submission happening.

**Comment by indirectlylit** [comment]
closing as stale. If we see this again, let's re-open
