### ISSUE TITLE
Usage & privacy modal empty

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4410]
### Observed behavior

_View statement_ link in the step 7 of the setup wizard opens an empty modal:

![ubuntu 16 04 3 start running - oracle vm virtualbox_017](https://user-images.githubusercontent.com/1457929/46894831-1f379800-ce76-11e8-9ec9-f59f0ea227ee.png)

### Expected behavior
There should be an actual privacy statement text in there, or at least a documented procedure if the administrator is supposed to provide one...

### User-facing consequences

Confusion about an important issue.

### Steps to reproduce

Install Kolibri and go through the steps of the setup wizard.

### Context

 * Kolibri version: `0.11.0b1`
 * Operating system: Ubuntu 16.04
 * Browser: both FF & Chromium

cc @indirectlylit @rtibbles @aronasorman

**Comment by jonboiser** [comment]
The other privacy statement on the side navigation and the login page are not there either. If these privacy statements are not going to be in 0.11, we need to remove this step in the setup wizard.

**Comment by indirectlylit** [comment]
Bad news. I'm not sure what my prior self was thinking, but it looks like I closed #4306 without merging it. This will require some thought - it affects a lot of things.

We'll have to get these new strings translated and pushed in a patch release. We might want to disable analytics until then.

**Comment by indirectlylit** [comment]
fixed in #4306
