### ISSUE TITLE
Custom icons in Video Player are missing

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4418]
### Observed behavior
@christianmemije reports:
Video player is missing custom icons, never got the points snackbar or completion icon

![screen shot 2018-10-23 at 3 56 58 pm](https://user-images.githubusercontent.com/10248067/47395715-9a9e1280-d6dc-11e8-9267-6806e3df0030.png)

### Expected behavior
All icons should show up.

### User-facing consequences
Alarm, confusion, despair.

### Steps to reproduce
Play a video?

### Context
 * 0.11.0-beta1

**Comment by indirectlylit** [comment]
I wonder if this was affected by my recent font changes...

**Comment by radinamatic** [comment]
I was able to repro the missing fast-forward and back icons on both Chromium and Firefox, but I did get the snackbar notification and completion icons... :thinking:

**Comment by christianmemije** [comment]
@indirectlylit Most likely that was the cause. This is the font file: https://github.com/learningequality/kolibri/blob/release-v0.11.x/kolibri/plugins/media_player/assets/src/views/videojs-style/videojs-font/css/videojs-icons.css
