### ISSUE TITLE
Jerky Exercise report experience for a coach

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4420]
### Observed behavior
@jtamiace and @shivichandra report:
"For a single learner on a single exercise on a single question....
When clicking between answer attempts, everything on the screen disappears while it's loading. Creates a slightly jarring experience"

### Expected behavior
Users should feel like their eyeballs have been massaged with butter? Or at the very least, things shouldn't disappear until something is ready to replace it.

### User-facing consequences
Eye strain? Unpleasant experience at the very least.

### Steps to reproduce
Complete an exercise question as a learner, but make multiple attempts on the question (by getting it incorrect first).
View the exercise report and click between the different attempts.

### Context
* v0.11.0-beta1

**Comment by indirectlylit** [comment]
@rtibbles is this still extant given your recent work?

**Comment by rtibbles** [comment]
I think this should now be addressed yes.
