### ISSUE TITLE
Active exams still appear inactive on the summary page

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4421]
### Observed behavior
@khangmach reports:
The very first time you change an exam from inactive to active, the grey circle doesn't change to a green one. You have to refresh the page to see the change

### Expected behavior
Status should be updated.

### User-facing consequences
A user might be confused and second guess themselves.

### Steps to reproduce
Create an exam.
Activate the exam.
Look at the exam list page.

### Context
* v0.11.0-beta1

**Comment by radinamatic** [comment]
Replicated on Ubuntu 16.04, but does not happen only _the very first time_, but the status changes back and forth are consistently not displayed until the page is reloaded.

**Comment by indirectlylit** [comment]
@jredrejo want to take a stab at this one?

**Comment by DXCanas** [comment]
Not reproducing this is beta 2? Tested in Chrome, Chromium, and Firefox
