### ISSUE TITLE
Session and Summary Log CSV files take a long time to generate

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4422]
### Observed behavior
When there is a reasonable amount of data, the CSV summaries both take a long time to generate.
This can lead a user to think either nothing is happening, or if there is a strict timeout enforced by, e.g. nginx, then it can prevent access to them.

### Expected behavior
Generated the logs asynchronously and let the user know when they are ready to be downloaded.

### User-facing consequences
Inability to download important data.

### Steps to reproduce
On a server with a at least the fake data generated on it, attempt to download either of the CSV files from the Facility Data tab.

### Context
* v0.11.0-beta1

**Comment by khangmach** [comment]
![csv generation](https://user-images.githubusercontent.com/25045166/47186876-d7d26100-d2e6-11e8-8e4e-c1cc944db6f2.png)

@rtibbles  Here's something we could do:

**Left:** 
once the user hits the download button, show a snackbar notification that lets the user know the preparation to generate the file is taking place. The snackbar persists on the screen throughout the application and is cancelable. Cancelling the action stops file generation. 

**Right:** 
once the preparation is done dismiss the previous snackbar and show a new one saying the file is now downloadable. This one is also dismissable. ALTERNATIVELY, and also which may be preferable and quicker, is to automatically start the download after the file is fully prepared (aka after snackbar one dismisses)

**Some notes:**
- The transition of switching snackbars works pretty much exactly like the one we show when Kolibri is not connected to a network and when the network is re-established.
- Inspiration is heavily drawn from Google Drive's download feature (try downloading a folder). Didn't want to invent something new when there's already something that works well out there!

**Comment by rtibbles** [comment]
Yeah, drawing on existing designs seems like a good idea here. What happens if you navigate away from Google Drive and back again while this process is happening, do you have to restart the process?

**Comment by rtibbles** [comment]
(more generally, how transient do we want this to be?)

**Comment by khangmach** [comment]
<img width="507" alt="screen shot 2018-10-23 at 11 13 48 am" src="https://user-images.githubusercontent.com/25045166/47381410-cc02e800-d6b4-11e8-875b-0f03197db827.png">
Currently when you navigate away from gdrive through another URL or closing the tab you get this message and if you navigate away, you lose the process. When you browser back to the original gdrive page, the process doesn't restart. 

I think it makes sense for our log file process to continue if you navigate to a different kolibri page, but maybe not if you exit that specific kolibri browser tab.

**Comment by indirectlylit** [comment]
> I think it makes sense for our log file process to continue if you navigate to a different kolibri page, but maybe not if you exit that specific kolibri browser tab.

This direction makes the process tied to browser state: it's triggered within a particular browser tab, and only that tab gets the chance to download the logs once they've been generated.

Another direction we can consider would be to treat this more like import/export, where all windows (and in fact all users) have a shared view onto a single server state, and you can leave and return to the page without losing that state.


It might look something like:

| State description | Mockup |
|--|--|
| No logs generated |  <kbd>_DOWNLOAD_</kbd><br> No logs are available to download yet. [Generate log file](#) |
| Generating |  <kbd>_DOWNLOAD_</kbd><br> ⟳ Generating log file... |
| Logs available |  <kbd>**DOWNLOAD**</kbd><br> Generated 10 minutes ago. [Regenerate log file](#) |

**Comment by khangmach** [comment]
That sounds fine too. I can't distinguish user preference right now so I think as long as we have something, it'll be a start. Gonna remove the needs design tag

**Comment by indirectlylit** [comment]
All else being equal, recommend we use the version above because I expect it to be easier to implement. (Requires only server-side state, and mirrors implementation of content import/export.)
