### ISSUE TITLE
When deleting a channel, specify which one we are deleting in the task progress

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4423]
### Observed behavior
Task progress just says 'Deleting channel'

### Expected behavior
Task progress says 'Deleting <channel name>'

### User-facing consequences
Know what is happening better when deleting

### Context
v0.11.0-beta1

Is this a good change?

**Comment by indirectlylit** [comment]
this is being addressed in ongoing 0.13.0 work
