### ISSUE TITLE
'All learning records' might be confusing, especially for a coach user

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4424]
### Observed behavior
@laurenlichtman reports while deleting a coach user:
"All the learning records for 'bbadmin' will be lost." (1) 'bbadmin' was a Coach (assuming this user also has logs). (2) I'm not sure if we use the terminology "learning records" anywhere and it may be confusing. How about "All data for 'bbadmin' will be lost."?

### Expected behavior
A message that better summarizes what is happening?

### User-facing consequences
Miscomprehension of what is being deleted.

### Context
v0.11.0-beta1

**Comment by laurenlichtman** [comment]
Or maybe "All data logs" or "All logs" just to use terminology consistent in Kolibri.
