### ISSUE TITLE
In-Context translation enabled through UI?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4431]
### Observed behavior

[In-Context translation](https://crowdin.com/page/in-context-localization) is very secret :)

Currently, it's enabled with an environment var -- but can it be enabled through UI? As a plugin?

Questions:

 * [ ] How can this be made UI-driven or more simple? Can the state change during runtime? Or can we add it as a plugin, requiring a restart?
 * [ ] Where could a button "Translate Kolibri" be located? "Device Info"? As a secret URL mentioned in the docs? New page? (NB! Including static Sphinx user documentation is also on the roadmap)

Opening this here, because I think we can conclude a good solution for this fairly quickly.

### Expected behavior

Used by end-users?

### User-facing consequences

n/a

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by rtibbles** [comment]
Not sure I understand the use case of this, as either way it requires an internet connection. This seems to be an unnecessary complication of the user interface.

**Comment by indirectlylit** [comment]
Adding an `options.ini` switch rather than using a Django settings module might be a worthwhile change

**Comment by benjaoming** [comment]
> Not sure I understand the use case of this, as either way it requires an internet connection. This seems to be an unnecessary complication of the user interface.

Use case is translators being given access to translate directly in the UI, and with no more instructions than to install Kolibri and click a button.

AFAIK everyone only translates through CrowdIn and a lot of translators have lacked context?

**Comment by rtibbles** [comment]
Yes, that's why we have translations.learningequality.org - what I am not understanding is why having translators install Kolibri locally is an improvement over that.

**Comment by benjaoming** [comment]
@radinamatic mentioned being able to see translations locally, okay I'm maybe not understanding the use case properly... @radinamatic can you perhaps decide whether this was important or not?

**Comment by indirectlylit** [comment]
closing - unless the site is connected to crowdin online, enabling translation functionality locally is not useful to translators
