### ISSUE TITLE
Create a script to automate the creation of the new integration testing tab at the spreadsheets.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4432]
### Observed behavior
To create a new [integration testing](https://docs.google.com/spreadsheets/d/1tol65GwoBdqzcsQyH0NHsWARGGKRJrbT6q1UeGH7kHE/edit?pli=1#gid=505990701) it needs to manually copy the base template and edit each scenarios to point it to the Gherkin `.feature` file link.

### Expected behavior
Create a script that can automate the creation of the new integration testing tab in the spreadsheets. It will also update all the scenarios links with the provided version.

**Comment by indirectlylit** [comment]
cool!

**Comment by mrpau-richard** [comment]
Closing this, fixed in #4544
