### ISSUE TITLE
Channel availability cached on channel import

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4435]
### Observed behavior
When a channel has previously been imported, then is deleted, and then the process for importing for that channel is begun again, the previous import status of the content within the granular selection interface is displayed.

### Expected behavior
Granular import status should reflect the actual state.

### User-facing consequences
Needs a refresh to force the view.

### Steps to reproduce
Delete a channel that has been imported.
Without refreshing then try to reimport that channel.

### Context
* v0.11.0-beta1-dev

**Comment by jonboiser** [comment]
I can't reproduce this. By "previous import status" do you mean it skips immediately to "complete" of the last import? E.g.

1. Download Touchable Earth > China -> Status: Completed Import of China
1. Delete Touchable Earth -> Status: Completed Deletion
1. Download Touchable Earth > India -> Status: Completed Import of China

I tried to reproduce this with a similar scenario to the above.

**Comment by rtibbles** [comment]
No, as in the availability of the nodes in the granular import modal. It showed them all as being available on the device already.

**Comment by jonboiser** [comment]
This also happens if you import new material. E.g.

1. Download touchable earth > china
1. Download _more_ from touchable earth 
1. China nodes are not annotated as already imported.

Might need to do a force fetch every time we call from contentnodegranular in the `updateTreeViewTopic` function.
