### ISSUE TITLE
Align make target "release" with current practice and pitfalls

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4436]
### Observed behavior

Need to improve reliability of `make release` to ensure it correctly captures everything. Current instructions are out-dated

Add:

 * [ ] Something about building on a clean environment
 * [ ] Refuse to work if there are more than 2 items in `dist/` -- it doesn't make sense ATM.
 * [ ] Refuse to work if current git repo is unclean

Additionally while we're at it:

 * [ ] Add some echo's to `make dist` because it's impossible to see when it finishes one step and starts the next.

```
Release process documentation:

http://kolibri-dev.readthedocs.io/en/develop/references/release_process.html


Quick check list:

1. Release notes?
2. Downloaded CrowdIn translations?
3. Pushed CrowdIn translations to repo?
4. Version info as tag and in kolibri.VERSION?
5. Did you do a signed commit and push to Github?
6. Check that the .whl and .tar.gz dists work?

Do you want to upload everything in dist/*?

CTRL+C to exit. ENTER to continue.
```

### Expected behavior

(will draft something else)

### User-facing consequences

n/a

### Errors and logs

Just had a problem with a release artifact that I built because of an unclean git repo with .lock files left dirty. Need to figure out what changes them (separate issue).

If the release command verified stuff, that would be better.

### Steps to reproduce

`make release` (it's harmless running it once)

### Context

0.11 and subsequent patch releases.

**Comment by benjaoming** [comment]
Why don't we release Buildkite's artifacts currently:

1) Filenames are not the correct format on Github, so not sure if it'd work
2) Releasing artifacts without a manual verification is in all cases a bad idea. This means that the steps would have to be download locally, test locally, release - not much time saved
3) Releases need signing, too, so we would have to invent a way to sign stuff from Buildkite

Once we have the manual stuff in place, let's have a look at this.

**Comment by indirectlylit** [comment]
> Quick check list

I think we should be careful to only include items here related to the Makefile and build process.

For example "Release notes?" and "Downloaded CrowdIn translations?" are out of scope. Including them makes it likely the checklist will get out of sync with or omit important steps from the primary (source of truth) documentation.

**Comment by benjaoming** [comment]
It is just a check-list... going "yup, done that" seems easy enough :)

But it's also the **last check before doing something something irreversible**.. would rather that it mentions the changelog than not (it might be written on the github release page and not in CHANGELOG.rst or something whack in case we are doing very quick and dirty patch release).

It should definitely align better to current practice and have more guidance and sanity testing. I'll add the automatic verification elsewhere.

What scope things are in is also depending on whether it's a pre-release or a stable release.

**Comment by indirectlylit** [comment]
Yes the checklist is fine.

I'm just trying to flag that the less DRY our documentation gets, the more likely it is that things will get stale and out-of-date as our processes and system evolves.

**Comment by benjaoming** [comment]
I'll make a PR for this, we can surely balance the need of a thorough check list with the need for a maintainable one! :+1:

**Comment by indirectlylit** [comment]
removing milestone so it doesn't become a release blocker

**Comment by indirectlylit** [comment]
release process checklists are now tracked in https://github.com/learningequality/kolibri-release-process
