### ISSUE TITLE
Build and distribute everything in kolibri.plugins

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4443]
### Observed behavior

0.10 had a WIP of the new epub plugin distributed. It wasn't enabled, and thus not built.

However, upon downgrading from 0.11, the issue turns up: Because the plugin exists, yet the stats file isn't present because it wasn't enabled+built when we built the 0.10 distributed package.

This is unaffected by @jredrejo 's fix for avoiding to enable plugins that don't exist.. because in this case, they do, but they're broken :)

CC: @rtibbles 

### Expected behavior

1. That any plugin present in `kolibri.plugins` is built, regardless of whether it's part of the default plugins set for that version.
2. We might add a check for the stats file and skip loading the plugin if it isn't there.. while initializing and enabling plugins.

We propose to add a glob pattern in `default_plugins.txt` like `kolibri.plugins.*` to avoid maintaining this list moving forwards.

### User-facing consequences

We can have problems if we change the default set of plugins, by adding something that isn't enabled or removing a plugin from the enabled set.

### Errors and logs

See the error in #4438 

### Steps to reproduce

Install 0.11 and run it, then downgrade to 0.10 and run it.

### Context

0.11 pre-release (possibly there aren't any further issues)

**Comment by indirectlylit** [comment]
removing milestone so it doesn't become a release blocker

**Comment by rtibbles** [comment]
I have a fix for this.
