### ISSUE TITLE
Broken test when merging 0.10.x to master

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4448]
### Observed behavior

CI fails during a merge of `release-v0.10.x` into `master`.

### Expected behavior

Consistency, why does this not Just Work (tm)? :)

### User-facing consequences

None

### Errors and logs

```
FAILED TESTS:
  channelsGrid component
    ✖ channels appear sorted by name
      HeadlessChrome 70.0.3538 (Linux 0.0.0)
    AssertionError: expected 'beautiful_channel' to equal 'awesome_channel'
      + expected - actual
      -beautiful_channel
      +awesome_channel
      
    at kolibri/plugins/device_management/assets/test/views/channels-grid.spec.js:86262:95
```

### Steps to reproduce

#4447 

### Context

It happened [here](https://travis-ci.org/learningequality/kolibri/jobs/442681833) and consistently happened again after a rebuild.

**Comment by indirectlylit** [comment]
0.10.x to master...  very strange 🤔

**Comment by benjaoming** [comment]
Edited the issue - I assumed wrongly that it was an unreliable test case.. but it also happened on the second rebuild.

**Comment by rtibbles** [comment]
I found another issue in the channels-grid spec the other day that I also fixed. I will check my commit history to see what it was.

**Comment by indirectlylit** [comment]
master is gone!

**Comment by benjaoming** [comment]
`release-v0.10.x` is also in sync with newer release branches and develop :tada:
