### ISSUE TITLE
it's possible to create multiple exams or lessons with the same name in a class

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4450]
### Observed behavior

| lessons | exams |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/47102529-dc691d80-d1f1-11e8-8b9a-ab589fc77aa0.png) | ![image](https://user-images.githubusercontent.com/2367265/47102543-e25efe80-d1f1-11e8-9da0-dc343aa4e266.png) |

### Expected behavior

* Expected a validation error that 'a lesson already exists with that name'. Alternatively, we might need some other way of disambiguating them.
* We should have gherkin stories covering this case

### User-facing consequences

confusion over non-unique items

### Steps to reproduce

create two exams or lessons with the same name

### Context

0.11

**Comment by khangmach** [comment]
@indirectlylit @rtibbles This already seems to be fixed in 0.12 beta

The strings should be updated to:
- (Lesson) A lesson with that **title** already exists
- (Quiz) A quiz with that **title** already exists

since 'title' is their official column label

**Comment by khangmach** [comment]
related: https://github.com/learningequality/kolibri/issues/5101

**Comment by indirectlylit** [comment]
ah good find. we had a dupe here #4626 and it was addressed in #4777
