### ISSUE TITLE
'copy' function doesn't work in lessons or exams

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4451]
### Observed behavior

'copy' function in lessons and exams doesn't work. Clicking 'copy' in modal state B does nothing:

| A | B |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/47102875-b728df00-d1f2-11e8-827f-7768e128ca91.png) |  ![image](https://user-images.githubusercontent.com/2367265/47102886-bee88380-d1f2-11e8-885a-cddcb0cf53b7.png) |

### Expected behavior

* Exam or lesson is copied
* We have gherkin stories to cover this case

### User-facing consequences

cannot copy

### Steps to reproduce

try to copy

### Context

0.11

**Comment by radinamatic** [comment]
Is this result of some of the most recent changes? Copying lessons in 0.11.b1 worked well during the integration testing... 😕

**Comment by indirectlylit** [comment]
there's a chance it's a local issue for me

**Comment by jonboiser** [comment]
I'm seeing it too. I'm noticing something weird where there is a full screen refresh and the URL changes to this:

`http://localhost:8000/coach/?submit=#/620c30d0e8b9c95cc9308c089157a861/lessons/3ed2f7e043164464052f19a61347daaf`

**Comment by jonboiser** [comment]
@christianmemije 	I think it has something to do with this change

https://github.com/learningequality/kolibri/commit/ba3f5d1120578bc4ee839daeb78605d22f011ca7#diff-7063a3f1d7cded9f2ed5f938c0e3500bR40

The copy modal is special in that it can actually emit two 'submit' events because it has two parts. When I remove the `once` modifier, it seems to work.

**Comment by jonboiser** [comment]
The quick fix would be to remove the `.once` directive from k-modals `submit` handler. I have no idea what effects this will have, but it was a relatively recent addition, so it might be okay.

**Comment by indirectlylit** [comment]
yes, that sounds like the safest move to me

**Comment by indirectlylit** [comment]
let's open a new issue so we can revisit in a subsequent release

**Comment by christianmemije** [comment]
Fixed in #4457
