### ISSUE TITLE
Copy Lesson and Exam are not working in Kolibri 0.11.0 beta 2

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4460]
### Observed behaviour
In fresh installation of kolibri 0.11.0beta2. I tried to copy a Lesson but the Copy button cannot click. I checked also the Exam, and same result I cannot copy.

### Expected behavior

Can duplicate the Lesson and Exam.

### Steps to reproduce
* Sign-in as  Admin user
* Import at least one channel
* Go to Coach  > Lessons page or Coach > Exams
* Create a Lessons and try to duplicate

### Context

 * Kolibri version 0.11.0beta2
 * Operating system Windows 7 & 10
 * Browser: Firefox FF 60.0.2

**Comment by indirectlylit** [comment]
thanks! This is being addressed in #4451
