### ISSUE TITLE
Wrong title label in 'Edit exam details' modal (refers to lesson instead of exam)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4468]
### Observed behavior
Too fast code c/p-ing, most probably...

![half term - kolibri - mozilla firefox_088](https://user-images.githubusercontent.com/1457929/47397308-fa250e00-d72e-11e8-9b58-bf8d838b240f.png)

### Expected behavior
Label should refer to the exam, not lesson.

### Steps to reproduce

1. Select any exam from the list
2. Click **Options** and select **Edit details**
3. Observe the title label

### Context

 * Kolibri version 0.11.0.b2
 * Operating system - all
 * Browser - all

@indirectlylit I'm not seeing this string at all on Crowdin, could it be that it never existed...? :confused: 

![all strings - kolibri - crowdin translation - mozilla firefox_089](https://user-images.githubusercontent.com/1457929/47397853-89cbbc00-d731-11e8-9ea9-95e9328675ec.png)

**Comment by indirectlylit** [comment]
This is now [addressed on crowdin](https://crowdin.com/translate/kolibri/582/en-te#q=titlePlaceholder)
