### ISSUE TITLE
should the app bar scroll offscreen?

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4470]
### Observed behavior

In #4465 we moved the sub-nav bar into the app screen, which looks great.

One unfortunate downside is that even more space is taken up by the app bar now, especially on smaller screens:

![image](https://user-images.githubusercontent.com/2367265/47401383-fa54e780-d6f5-11e8-8db2-5730369cf0e0.png)

### Expected behavior

At least on mobile, we shouldn't be taking up so much screen real estate for the app bar all the time. We could follow [this behavior](https://material.io/design/components/app-bars-top.html#behavior), at least on smaller screens:

* Scrolling upward hides the top app bar
* Scrolling downward reveals the top app bar

### User-facing consequences

currently a very small usable window on mobile

### Context

0.12

-----

cc @khangmach @jtamiace @jonboiser @christianmemije  thoughts?

**Comment by khangmach** [comment]
That behavior was mentioned here under "scroll behavior" https://github.com/learningequality/kolibri/issues/4214

**Comment by jonboiser** [comment]
It might be simpler just to shrink the app bar. The top app-bar only shrinks 8px when going from desktop to mobile (could be more). The second bar doesn't shrink at all.

But even with the second bar (64px) gone, I still don't think that exercise in the screenshot will be fully visible (controls + prompt)

**Comment by indirectlylit** [comment]
both shrinking and adding the scrolling behavior would help, with scrolling behavior achieving more saving.

I don't see anything in the [material spec](https://material.io/design/components/tabs.html#spec) about shrinking though

**Comment by rtibbles** [comment]
Scrolling and shrinking would help. It has been discussed before, but using the immersive view for all content presentation would also help (and perhaps making the top bar for the immersive view also hidden on scroll).
