### ISSUE TITLE
clarify device content import permissions

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4475]
### Observed behavior
A learner user can delete a channels after it was given an access to only import and export a channels.

### Expected behavior
A learner user can only import and export a channels. 

Another option is to create another permission that allow the learner or user to delete channel.

### Steps to reproduce
* Grant a permission to a learner user to import and export channels.
* logged-in the learner account and navigate at device page and delete already imported channels.

Tell us about your environment, including:
 * Kolibri version: 0.11.0b2
 * Operating system: Windows 7
 * Browser: Firefox

**Comment by jonboiser** [comment]
This is expected behavior. I think, in practice, permission to manage (which includes deleting channels) should only be given to specific learners.

I think the more common case is to give this permission to coaches.

**Comment by indirectlylit** [comment]
It's an interesting point though - the permission label might be misleading:

![image](https://user-images.githubusercontent.com/2367265/47464016-d1d3f880-d79c-11e8-907b-06d6e0463d2b.png)

Perhaps it should say "Can import, export, and delete content channels" or "Can manage content on this device"

@radinamatic we should probably clarify this in the docs

@jtamiace shall we change the permission text for 0.12?

**Comment by radinamatic** [comment]
As i understand this is not new, that is, granting "device permissions" always included the ability to delete channels, hence effectively _manage_ content, not just import/export capability. 

Is there a plan to maybe separate levels of device permissions? So user can be granted import/export, but not deletion capability? If not, I would favor "Can manage content on this device" label for simplicity.

In any case the user uncertainty is possible, and I will add a clarifying note in the docs. :+1:

**Comment by indirectlylit** [comment]
> Is there a plan to maybe separate levels of device permissions

Not that I'm aware of

**Comment by radinamatic** [comment]
Actually, I kept the docs close to my own understanding (device permissions = permissions to manage content), so just a bit more explicit wording will be necessary:

https://kolibri.readthedocs.io/en/latest/manage.html#permission-to-manage-content

**Comment by jtamiace** [comment]
I think we expected the case of a user with only a role of learner + device permissions to be rare in actual implentation in the field, and I'm not aware of any feedback from users that would suggest we should make a separate permission for deletion. Maybe someone from the imps team can speak on that?

But, couldn't hurt to change the text. Also a fan of the simpler `Can manage content on this device`
