### ISSUE TITLE
localize language name tooltips in language switcher

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4483]
### Observed behavior

In #4461 we added english-language tooltips.  These are helpful for both QA and to help satisfy curiosity from users about what the available languages are.

### Expected behavior

We should localize all language names so that the tooltips are displayed in the currently-selected language.

Recommend that we "over-translate" language names, rather than trying to only translate currently-supported languages. The set of supported languages can change over time (e.g. adding a language during a patch release), so we should come up with a super-set of "potential languages" and translate all of them.

### User-facing consequences

English-language tooltips are not universally understandable

### Context

0.11

**Comment by Aadi71** [comment]
I would love to work on this issue.

**Comment by indirectlylit** [comment]
@Aadi71 I've removed the 'beginner friendly' label because this task requires some knowledge of our internationalization system, which is a bit complex. You're welcome to try working on it, but we might not be able to provide sufficient timely guidance to make it an easy task.

**Comment by rtibbles** [comment]
I think this is unnecessary - either the language names in the selector should be localized, or we should just use native language names. We only added the English names for QA purposes, it seems like feature creep to localize the tooltips.

Most sites simply use native language names and we are already following this practice.
