### ISSUE TITLE
Error loading Khan Academy (en) exercises

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#4491]
### Observed behavior
Reported from a KHGP implementation: Certain exercises (especially when they contain graphs or drawings) from Khan Academy are showing an error when accessed in Kolibri. The observed behavior was from a curated channel that included KA exercises.

Note from Laura: I looked at the exercise on the Studio side and the thumbnail was showing up properly.

![image 1](https://user-images.githubusercontent.com/22602993/47736801-d89fb700-dc45-11e8-8daa-c1b2c8793d6a.png)

Channel token: sogag-nikan
Channel ID 24e73d1b43d14948a16ab99b29c3087d 

…

### Context

Tell us about your environment, including:
 * 0.10.3
 * Windows
 * Experienced on both Chrome ( Version 70.0.3538.77 (Official Build) (64-bit)) and also Mozilla Version 62.0.3 
![image](https://user-images.githubusercontent.com/22602993/47736880-071d9200-dc46-11e8-8cad-b6d164212a34.png)

…

**Comment by indirectlylit** [comment]
Very often these issues turn out to be resolved by re-publishing and updating the channel. @ralphiee22 any thoughts if that might be the case here?

**Comment by BruceRuta** [comment]
Thanks, I re-published the channel and all exercises worked.
