### ISSUE TITLE
make KGrid RTL-compatible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4508]
### Observed behavior

KGrid assumes LTR language. This means alignment is incorrect for RTL:

![image](https://user-images.githubusercontent.com/2367265/47981463-d93eb000-e080-11e8-83ed-79adebfceb4b.png)

### Expected behavior

* rename alignment from "left" and "right" to "start" and "end"
* dynamically switch style based on `isRtl`

### User-facing consequences

alignment issues in RTL

### Steps to reproduce

view any grid page in RTL

### Context

0.11

**Comment by rtibbles** [comment]
What remains to be done for this?

**Comment by indirectlylit** [comment]
just to rename the alignment inputs to 'start' and 'end'

I can have a look at this in my style guide work since I'll be touching various core component APIs

**Comment by rtibbles** [comment]
Note that I touched some of the KGrid code to allow contextual RTLing (i.e. letting the RTL be set by the direction of the elements, rather than the overall dir setting of the page).

**Comment by indirectlylit** [comment]
> rename the alignment inputs to 'start' and 'end'

I'm going to close this as complete. I don't think renaming is necessary or consistent, given that the rest of the CSS is also defined in terms of "left" and "right", with the expectation that things will automagically flip for RTL.
