### ISSUE TITLE
add cache busting for django static files not under webpack control

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4511]
### Observed behavior

Webpack currently adds hashes to ensure that stale static files don't get caught in the cache; however this doesn't currently happen for other static files such as the new fonts.

### Expected behavior

All static files should have hashes so we can safely put long cache periods on them. This should probably be done using [`ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifeststaticfilesstorage)

### User-facing consequences

users may see broken behavior

### Context

0.11

**Comment by indirectlylit** [comment]
cc @rtibbles I tried adding this but it tries and fails to find `Symbola.otf` from perseus.

Adding 2d6404b5a03b4f41bc08f733dccf1fb6f4053bc4 as a temporary work-around for 0.11

**Comment by indirectlylit** [comment]
@rtibbles with my workaround above, my guess is that this is low-priority and not needed for 0.12. Do you concur?

**Comment by rtibbles** [comment]
I think it would be nice to get in, but given the issues you've faced, it is probably not worth blocking over.

**Comment by jonboiser** [comment]
Closing as a duplicate of #7805
