### ISSUE TITLE
differentiate community languages from officially-supported languages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4512]
### Observed behavior

We cannot always find translators for some languages, which means support varies between releases. However, all languages currently are mentioned together, which creates an expectation that they will always be supported

### Expected behavior

distinguish community-supported languages and explain that support may vary release-to-release

### User-facing consequences

better transparency about languages support

### Context

0.11

----

cc @radinamatic @khangmach @rtibbles  thoughts?

**Comment by indirectlylit** [comment]
rough plan...

language switcher:

![image](https://user-images.githubusercontent.com/2367265/49665963-776cbf80-fa0b-11e8-9819-80ded654a2a4.png)

website:

![image](https://user-images.githubusercontent.com/2367265/49665988-83588180-fa0b-11e8-99ed-fd435f9e93d5.png)

**Comment by khangmach** [comment]
I'm a fan of illustrating this on the website, but I'm weirded out by putting this information in Kolibri, where I don't think the majority offline users will understand the motivations behind the feature and the distinctions between community supported vs non-supported languages (what does community supported languages mean??). The only community that matters to them is their own? This seems like information that's better suited in documentation.

**Comment by indirectlylit** [comment]
The main implication is supposed to be that community-supported languages might not exist in every release.

cc @rtibbles this made me realize that the upgrade notifications you're working on should take into account languages available in the release. A couple options:

* add a field in the notification for supported languages
* don't show notifications if the client or server are set to a language not in the supported languages(???)

**Comment by khangmach** [comment]
>The main implication is supposed to be that community-supported languages might not exist in every release.

What is the user expected to do with this info? Does it add value to or aid them in their goal of fixing their current language to one they can understand? This seems like information catered to very few people, people who deal with releases, their installations/updates and need the info

**Comment by rtibbles** [comment]
> Does it add value to or aid them in their goal of fixing their current language to one they can understand?

No. This might be an argument for only showing this information to Admins, as they are the ones who are more likely to be motivated to contribute back upstream or be aware of upgrades, etc?

**Comment by khangmach** [comment]
Agreed it's most relevant to admin accounts

**Comment by indirectlylit** [comment]
cool - thanks for the feedback!

Closing this issue, and adding the upgrade concern to our [MVP upgrade notifications spec](https://docs.google.com/document/d/1h5hyHttxTrZpQq7j0sPCBLNlcV7PcaJ5CrtlJvVZBdM/edit#)
