### ISSUE TITLE
add gherkin story for handling multiple channels in coach reports

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4521]
### Observed behavior

#4519 addressed a bug that slipped through testing

### Expected behavior

Let's add a new story to ensure that we test for scenarios with multiple channels to prevent bug from recuring

### Context

0.11

**Comment by radinamatic** [comment]
Gotcha, will add to 0.12 integration testing prep!

**Comment by indirectlylit** [comment]
coach reports no longer supports this - good catch @radinamatic
