### ISSUE TITLE
Kolibri.apk cannot import a channel in Andriod 6.0

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4533]
### Observed behavior

 For this test I use smartphone cloudfone. In fresh installation, I cannot import a channel even I have 800MB left in my internal storage.

![screenshot_20181115-183849](https://user-images.githubusercontent.com/38421180/48547843-811c6f00-e906-11e8-8c24-94ba00ffa8a3.png)

![screenshot_20181115-183936](https://user-images.githubusercontent.com/38421180/48547859-88dc1380-e906-11e8-938e-37e670368b89.png)

### Expected behavior

Can import a channel.

### Steps to reproduce

1. Download this [Apk](https://drive.google.com/file/d/15O6FCfeng1h9JS-rPyxTqWLfhO2PUcqB/view) in your smartphone and install.
2. Fill up the wizard setup.
3. In Superuser try to import a channel.

### Context

 * Kolibri version: 0.12.0.dev0+git.20181107010307
 * Operating system: Andoroid 6.0

**Comment by indirectlylit** [comment]
cc @DXCanas

**Comment by DXCanas** [comment]
Hi! Where was this apk found?

**Comment by radinamatic** [comment]
@DXCanas I believe it's the same APK we used during the mini Android bug bash a few weeks ago.
In fact it's the same issue some of us already identified that day.

**Comment by indirectlylit** [comment]
closing as most work has been migrated to 
https://github.com/learningequality/kolibri-installer-android/

please re-open there if necessary
