### ISSUE TITLE
exam answers and the options are displayed differently with different students

### ISSUE THREAD

**Issue by AntikaChanda** [learningequality/kolibri#4535]
## Summary
While using the exam feature, the answers and the options are displayed differently with different students.

For instance -
Child 1: found the correct answer options to the above-mentioned question while attempting the exam (subtraction of a-b); but
Child 2 <Screen Shots attached>: found incorrect answer options to the same question. Basically, the answer options (Binomial, Trinomial etc.) was the answer options for another question.

## Category

Select one: BUG

## Usage Details

*Please give details about how you were using Studio.*

It's a platform error.
 - Browser: Chrome
 - Channel: CBSE English medium 3 to 8 (9e5305326ed742d0892479dea825a514)
 - Topic/Content Item: Exam feature

## Screenshots

![image](https://user-images.githubusercontent.com/10248067/98983992-6e79a800-24d6-11eb-8f61-dd7aa2a666c4.png)

![issue_1](https://user-images.githubusercontent.com/30926441/48260067-2b485280-e440-11e8-86cf-8b1e543abbd4.jpg)

**Comment by indirectlylit** [comment]
Hi @AntikaChanda thanks for your report. A couple follow-up questions:

1. Would you mind clarifying what the two images posted represent? They look like the coach and learner view of two different questions for a single child?
2. You're saying the key issue is that the learner doesn't see correct options? E.g. they should see an answer like "2b" in the question posted above?

thanks!

**Comment by swapnil106111** [comment]
@indirectlylit 
Kolibri version : kolibri-0.9.5beta3

Screenshot_1: Instead of giving correct answer of 3 questions,showing "Questions correct : 1 out of 4".
It must show "Questions correct: 3 out of 4"
![issue_2](https://user-images.githubusercontent.com/12776071/48891433-5e87da00-ee61-11e8-961a-e35ee3244c3f.jpg)

Screenshot_2: Options of the question in the exam are interchanging with other question options in the exam.
![issue_1](https://user-images.githubusercontent.com/12776071/48891567-b7f00900-ee61-11e8-9234-d0eac22cfb22.jpg)

**Comment by indirectlylit** [comment]
thank you!

Do you have a sense if these two issues are related - do they always happen concurrently? 

(incorrect answer count in coach view and incorrect answers displayed in learner view)

**Comment by swapnil106111** [comment]
@indirectlylit No, both are appearing randomly.

**Comment by rtibbles** [comment]
@swapnil106111 I have been trying to replicate this locally, but so far without success. Do you have clear steps to replication for this? If so, could you also test these on the latest 0.12.0 beta and see if this is still extant?

**Comment by rtibbles** [comment]
No recent replication, closing as stale.
