### ISSUE TITLE
Export Command: No such file or directory:

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4539]
### Observed behavior
Export command fails

> 		sudo -u $KOLIBRI_USER $KOLIBRI_EXE manage exportchannel $CHANNEL /tmp/KOLIBRI_DATA
> 		sudo -u $KOLIBRI_USER $KOLIBRI_EXE manage exportcontent $CHANNEL /tmp/KOLIBRI_DATA
> 

These used to work but now they do not.

### User-facing consequences
Inability to export using CLI or GUI (see #3274)

### Errors and logs
[kolibri-export.txt](https://github.com/learningequality/kolibri/files/2609586/kolibri-export.txt)
[server.log.txt](https://github.com/learningequality/kolibri/files/2609587/server.log.txt)
[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2609588/kolibri.log.txt)

### Context
 * Kolibri version 0.11
 * Operating system Linux
 * Browser Vivaldi

**Comment by benjaoming** [comment]
Hi @nobicycle

Thanks for filing this!

I am wondering if there indeed is a file missing in the path or if the channel has been broken somehow. Of course, the `export` command might have better guidance.

```
FileNotFoundError: [Errno 2] No such file or directory: '/opt/kolibri/.kolibri/content/databases/1ceff53605e55bef987d88e0908658c5.sqlite3'
```

Does `1ceff53605e55bef987d88e0908658c5` exist on your disk, can you find it in `/opt/kolibri/.kolibri/content/` ?

**Comment by nobicycle** [comment]
@benjaoming  

Yes, the channel got somehow broken. Perhaps to do with having a symbolic link as the content directory and then running the new move content command.

Anyhow I just reinstalled everything and used a content backup for import.

For future reference, is there any command we can run to check the database integrity?

**Comment by benjaoming** [comment]
Oh great idea! I'll see if I can grasp a good suggestion for an issue addressing this particular problem. Meanwhile, we also had this one open: #3285

**Comment by benjaoming** [comment]
Thanks for the feedback @nobicycle - have opened a new issue for this. Please note that it is currently not a milestone target for the next release, since the planning phases are pretty much over.

**Comment by indirectlylit** [comment]
closing as stale
