### ISSUE TITLE
Not able to solve specific KA questions. 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4542]
### Observed behavior
Not showing answers of the questions in proper format because of this not able to proceed.

Channel ID : jagak-sanon
Path: CBSE KA Hindi Class 6 to 9 -> कक्षा 7 (इंडिया) -> 7. त्रिभुजों की सर्वांगसमता -> रूपांतरण और सर्वांगसमता -> प्रतिचित्रण निर्धारित करना

### Expected behavior
Must show as it shows on KA site.

### Steps to reproduce
1. Import the channel.
2. Try to solve the question on Kolibri-0.9.5b3.

### Context
 * Kolibri version : Kolibri 0.9.5b3
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

###Screenshots
1. Kolibri screenshot
![1](https://user-images.githubusercontent.com/12776071/49145719-6f839000-f326-11e8-8689-9fbb6aa60fe2.jpg)

2. KA Site screenshot
https://hi.khanacademy.org/math/in-in-class-7th-math-cbse/in-in-7th-triangle-congruence/in-in-7th-triangle-congruence-transformations-congruence/e/defining-congruence-through-rigid-transformations

![must_show](https://user-images.githubusercontent.com/12776071/49145410-bb820500-f325-11e8-8ce9-4aeee1e2418f.png)

**Comment by swapnil106111** [comment]
@indirectlylit Not able to see behind graph on tablet.
Channel ID : kobos-hibaz
Path : CBSE English medium channel>grade 8>10.Visualising solid shapes>KA Resources > Mapping space around us > Constructing scale drawings.

Tablet Screenshot:
![2](https://user-images.githubusercontent.com/12776071/49274267-cf507700-f49d-11e8-8dbc-3421dd5febc9.jpg)


Expected screenshot:
https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-geometry/cc-7th-scale-drawings/e/constructing-scale-drawings 

![3](https://user-images.githubusercontent.com/12776071/49274281-d7101b80-f49d-11e8-8f04-df6727f7594f.png)

**Comment by swapnil106111** [comment]
Tested on Kolibri 0.11.0
Same issue appearing.

![1](https://user-images.githubusercontent.com/12776071/50276420-eadceb00-0467-11e9-9d25-1e1ae5c87f1c.png)

**Comment by indirectlylit** [comment]
cc @ralphiee22

**Comment by rtibbles** [comment]
Note that I am unable to replicate the issue with the 'Scale drawing' exercise - I believe this is now fixed. The issue in the Hindi exercise is still extant, however.
