### ISSUE TITLE
Upgrade Django 1.11.17 (adds Python 3.7 compatibility)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4548]
### Observed behavior

We should discuss the latest Django 1.11.17 release.  In Kolibri 0.11, we are on 1.11.15.

[The release notes](https://docs.djangoproject.com/en/2.1/releases/1.11.17/) mention:

>  Django 1.11.17 fixes several bugs in 1.11.16 and adds compatibility with Python 3.7.

[Django 1.11.16](https://docs.djangoproject.com/en/2.1/releases/1.11.16/) also had an important bug fix:

> Django 1.11.16 fixes a data loss bug in 1.11.15.

### Expected behavior

We could remove documentation warnings about Kolibri *not* working on Python 3.7?

Perhaps as a patch update in 0.11.1?

### User-facing consequences

Removes the very ugly instructions about downgrading when running with Python 3.7.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

0.11 in general

**Comment by benjaoming** [comment]
This release will also require another Iceqube release because it had a module called `async` (which is now reserved syntax). It's possible to do a 0.0.6 release with a minimal set of changes since Iceqube didn't have any other changes, except for `extra_parameters` which is either a severe bugfix or a dead kwarg... finding out with @aronasorman

**Comment by indirectlylit** [comment]
I noticed in #4614 that `django-filter` was upgraded to `2.0.0`.

Changelog says this added support for python 3.7, but also seems to break our builds.

I wonder if any of our other dependencies are also lacking support for 3.7?

**Comment by benjaoming** [comment]
> I wonder if any of our other dependencies are also lacking support for 3.7?

Good catch about `django-filter`. Our test coverage is low, but at least for the problems introduced by the `async` syntax keyword, it should be caught at import time.

It would be hard to defend adding major dependency bumps in a patch upgrade... even for adding Python 3.7 compatibility, however important that might seem.

**Comment by benjaoming** [comment]
I have done this in other projects: Stated in release notes that "Python 3.x" support was added, but actually it meant that the "support" was added but nothing was changed, i.e. it just got added as a no-op to the test matrix and everything passed :) So it only was meant as an official remark to say "we don't know if previous releases supported this Python 3.x, but we intend to support it fully from here on".

**Comment by nobicycle** [comment]
@benjaoming
Regarding #4182 , I commented:

> Sorry I only just discovered your last message, as I was revisiting the issue: Arch ARM devices do not support python 3.6, so I was checking progress to 3.7
> 
> Yes I would like to test the patch.
> 

How do I get the patch please?

**Comment by benjaoming** [comment]
Sorry about the prolonged wait @nobicycle - am waiting for someone with very sparse internet to add me as a maintainer of a dependency so I can publish an updated Python 3.7 compatible version.

**Comment by benjaoming** [comment]
Hi - just want to add that 0.11.1 was released with these fixes. They seemed to work fine for me, hope it works for your setup @nobicycle ?

Please feel free to open up new issues w/ Python 3.7 problems, should you encounter any.

**Comment by nobicycle** [comment]
Works perfectly. Thank you.
