### ISSUE TITLE
Requesting ContentNode by channel id instead of node id during network import

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#4550]
### Observed behavior

During network import, we are requesting the root ContentNode of the channel by the channel id instead of the root node id (possibly to show the first level of the channel content?). Although in most cases, the channel id is the same as the root id, there are some old channels having different channel id and root id. Example channel id: `7c4e1cf2664435e384b8cbefcafafb53`.
This makes users not able to import channel successfully.

@rtibbles mentioned this on Slack:
> the Kolibri issue is somewhere in the frontend of the device management plugin

### Expected behavior

Users should be able to import channel successfully.

### User-facing consequences

Users cannot import channel from studio to kolibri when the channel id is different from root id.

### Errors and logs

<img width="560" alt="screen shot 2018-12-04 at 10 51 46 am" src="https://user-images.githubusercontent.com/19424916/49465554-c66be800-f7b2-11e8-9b34-9909418e220c.png">

<img width="442" alt="screen shot 2018-12-04 at 10 52 22 am" src="https://user-images.githubusercontent.com/19424916/49465555-c7047e80-f7b2-11e8-9242-beb0a0e9b206.png">
<img width="276" alt="screen shot 2018-12-04 at 10 52 40 am" src="https://user-images.githubusercontent.com/19424916/49465556-c7047e80-f7b2-11e8-9932-2fa28a7e3b1b.png">

### Steps to reproduce

1. Import channel `7c4e1cf2664435e384b8cbefcafafb53` on kolibri

### Context

Kolibri version: 0.11

**Comment by rtibbles** [comment]
Fixed in #4591
