### ISSUE TITLE
Exporting content into local drive fails part way through and then Kolibri no longer recognizes the drive

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#4552]
I've experienced this previously in older versions but not consistently. Exporting content onto an attached USB "failed" today at around 30%, so I dismounted and re-mounted the drive and attempted again with the same result. On the third time dismounting and re-mounting, Kolibri no longer recognized the device as being attached.

v0.11, OSX using Chrome. Mounted drive was an HP USB stick.

I have a copy of the content database if it's helpful -- not sure how to open it.

![image](https://user-images.githubusercontent.com/22602993/49495149-1ca06000-f873-11e8-84d2-53ee3de2ad54.png)

**Comment by indirectlylit** [comment]
If you can reproduce this consistently, let's try inspecting the server logs?

**Comment by rtibbles** [comment]
Closing as stale.
