### ISSUE TITLE
404 error during viewing of device permissions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4558]
### Observed behavior

When viewing the permissions page for a user that has not yet been assigned any device permissions, we get an unhandled 404 error in the JS console:

![image](https://user-images.githubusercontent.com/2367265/49540929-27b0bb80-f886-11e8-8216-79656675529c.png)

### Expected behavior

* If the 404 is expected, we should handle it on the client side
* If we're not supposed to get a 404, or if we're not supposed to make the request, we should fix that

### User-facing consequences

none observed

### Errors and logs

```
[
    {
        "id": "NOT_FOUND",
        "metadata": {
            "view": "Device Permissions Instance"
        }
    }
]
```

### Steps to reproduce

Go to device permissions and edit a non-super user

### Context

0.11.x

**Comment by jonboiser** [comment]
I think this has been fixed a long time ago. When going to a page like https://kolibri-beta.learningequality.org/en/device/#/permissions/fc66c78d9ef21ba9bfa10949716e8945, there is an anticipated 404 error if a DevicePermission record hasn't been created, but the page should still show up.

I'm not sure if there's any where else in the app we make a call to this endpoint's detail view.
