### ISSUE TITLE
allow python path to be modified with an environment variable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4560]
### Observed behavior

Currently there is no way to use external settings files or install additional kolibri plugins with a PEX files.

### Expected behavior

We can add support for a new environment variable, e.g. `KOLIBRI_ADDITIONAL_PY`. When set, this value will be prepended to the internal python path, allowing additional packages to be referenced by the PEX.

### User-facing consequences

Without this, have to choose between being able to use external packages or having a portable, downloadable executable.

### Context

0.11.x

----

cc @jamalex @aronasorman

**Comment by benjaoming** [comment]
This is a limitation in .pex and I'm struggling to remember how and when we talked about it. It came up recently, and I think it was in relation to the C extensions and how they are bundled, how many platforms to support etc.

@lyw07 would you have inputs on this?

@indirectlylit Can you recall if this is limited to the case of using external plugins for .pex files?

**Comment by indirectlylit** [comment]
This was resolved during investigation of using the Sentry SDK in https://github.com/learningequality/kolibri/pull/5773

The key here was to set the environment variable `PEX_INHERIT_PATH=1`: https://pex.readthedocs.io/en/stable/api/index.html#pex.variables.Variables.PEX_INHERIT_PATH

This lets the pex inherit the Python path of the active Python environment.

**Comment by benjaoming** [comment]
yes thanks @indirectlylit - that's EXACTLY what I didn't manage to remember - just a strong feeling that we had this fixed already :)

**Comment by indirectlylit** [comment]
not so much fixed as finally read the documentation :)

**Comment by benjaoming** [comment]
me reading a documentation when I can't remember it :godmode:

**Comment by radinamatic** [comment]
@indirectlylit @benjaoming Remind me what exactly should be mentioned in the user docs...?

**Comment by benjaoming** [comment]
@radinamatic I don't think we need to address this currently. Modifying the path environment is "business as usual" for all applications of Kolibri except .pex - but I don't think there is a strong use cases for running the PEX inside a customized environment... might as well just use a conventional .whl. If a use case (maybe some plugin stuff) would arrive, I think there will be documentation written exactly for that use case?

**Comment by radinamatic** [comment]
Ok, thanks, removing the `user docs` label (it's messing with my issue cleanup 😛)

Please add it again, if it becomes necessary in the future.

**Comment by indirectlylit** [comment]
setting the variable `PEX_INHERIT_PATH=1` is necessary for any situation where a user has installed using the `pex` and tries to enable an external plugin.

We don't publicly document plugin enable/disable functionality because it's not stable yet, but when we do we'll need to add this as a note. Opened a tracker issue here: https://github.com/learningequality/kolibri-docs/issues/149
