### ISSUE TITLE
links have started opening in a new tab

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4562]
### Observed behavior

Links such as "Continue as a guest" have begun opening in a new tab. This is a regression.

### Expected behavior

Same tab unless explicitly made otherwise.

### User-facing consequences

App navigation is broken

### Errors and logs

None

### Steps to reproduce

Click 'continue as guest'

### Context

v0.11

**Comment by indirectlylit** [comment]
cc @rtibbles  caused in #4513 by 4f41ffe1d16bec010e33d80af5585d4a4a9ccdce

**Comment by rtibbles** [comment]
Ah, looks like I misinterpreted how 'external' the external links are - they're external as opposed to router links, but not necessarily external to Kolibri.
