### ISSUE TITLE
Dockerize development workflow

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4566]
### Observed behavior

New features/benefits:

 * Development can be done without installing Node/Yarn (more secure and easier to install Docker)
 * Docker containers operate on your local repository (through a Docker VOLUME) and build+reuse assets there.
 * Documentation is simplified (leaving aside Docker installation to the user's platform)

```sh
# Developer tools
make docker-assets  # builds assets through a Docker container
make docker-devserver  # runs a devserver on port 8000, reloading when you change files
make docker-demoserver # runs a demo server on port 8080
```

This picks up from #4056 and #3775

TODO:

 * [ ] Add optional unique tags to avoid concurrency issues on Buildkite
 * [ ] Link working source directory in dev server with a docker VOLUME
 * [ ] Consolidate new section in docs: "Development with docker containers"
 * [ ] Do not populate `kolibri/dist` before invoking `compilemessages` #3384 
 * [ ] Fix pip version warnings
 * [ ] Restore APK building entirely in a Docker container
 * [ ] Optimize .buildkite pipeline to not need utility scripts

Draft of Docker image inheritance...

```
    --------------------
    |  base (xenial)   |
    | (apt + pip deps) |
    --------------------
     /                 \
  ------------          \
  |  built   |     ------------------------
  |  assets  |     | linked source volume |
  ------------     ------------------------
  / |    |   \                |
exe demo deb  whl         devserver
```

Background: Previous work was supposed to have branched off, but it was contained in another feature branch that got merged. So the PR description of the intentions was buried with all the other closed PRs.

**Comment by rtibbles** [comment]
This doesn't seem to be high priority for the developer experience, closing for now.
