### ISSUE TITLE
New .deb package w/ uWSGI and Nginx configurations

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4567]
### Observed behavior

High-level tracker ticket for this new feature: automated setup of an nginx configuration on linux systems.

See google doc below for ongoing design and spec iteration

### Expected behavior

see https://docs.google.com/document/d/1poW3owLd_v_1QaQiRCcDJ-Fa3KKf1CYcHNQL67jgjM0/edit#

### User-facing consequences

Currently difficult for users to set up nginx

----

cc @benjaoming @jredrejo

**Comment by benjaoming** [comment]
Updated the description.

We could open up individual issues in the installer's repo: https://github.com/learningequality/kolibri-installer-debian

**Comment by indirectlylit** [comment]
thanks for adding those Qs! Since you also added them to the google doc I'll remove them from here to keep this issue high-level

**Comment by indirectlylit** [comment]
closing this tracker issue because work is now ongoing in the https://github.com/learningequality/kolibri-server repo
