### ISSUE TITLE
console-based management command for re-ordering channels

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4572]
### Observed behavior

Currently channels appear to learners in the order they are imported. This can be frustrating when administrators want to prioritize certain channels over others

### Expected behavior

Longer-term we'll add a UI for re-ordering channels.

For this initial pass, let's add some basic management commands to help re-order things.

One option might be something like:

```bash
$ kolibri manage content listchannels
Pos	ID					Name
---	--					----
0	1ceff53605e55bef987d88e0908658c5	Khan Academy (English)
1	f9d3e0e46ea25789bbed672ff6a399ed	African Storybook
2	0e173fca6e9052f8a474a2fb84055faf	Global Digital Library - Book Catalog

$ kolibri manage content setchannelposition --id=f9d3e0e46ea25789bbed672ff6a399ed --pos=0

$ kolibri manage content listchannels
Pos	ID					Name
---	--					----
0	f9d3e0e46ea25789bbed672ff6a399ed	African Storybook
1	1ceff53605e55bef987d88e0908658c5	Khan Academy (English)
2	0e173fca6e9052f8a474a2fb84055faf	Global Digital Library - Book Catalog

$ kolibri manage content setchannelposition --id=f9d3e0e46ea25789bbed672ff6a399ed --pos=10
ERROR: invalid position
```

### User-facing consequences

Currently, it requires backend developer knowledge of kolibri to make changes to channel ordering

### Context

0.11

**Comment by radinamatic** [comment]
Gah, was looking forward to putting the `needs-user-docs` label, but you were faster... 😛 

This command will be greatly appreciated until there is a UI version (maybe similar to resources ordering in Lessons?)! 👍
