### ISSUE TITLE
<Improvement> Not showing user is exist notification on UI.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4575]
### Observed behavior
We are able to create user using CREATE AN ACCOUNT option which is on login page of kolibri. But when someone uses existing username to create account, it will not show any kind of existing user notification on UI.
Not able to distinguish whether account is exist or not.
### Expected behavior
It must show existing username notification on UI if user is exist.

### Steps to reproduce
1. Login with Admin and go to the facility.
2. Click on settings.
3. Select Allow learners to create accounts.
4. Logout and click on CREATE AN ACCOUNT button and use existing username to create account.

### Context

 * Kolibri version : Kolibri 0.11.0 
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshots:
![1](https://user-images.githubusercontent.com/12776071/49732114-840b4500-fca3-11e8-9917-a08ae5515d26.png)

**Comment by indirectlylit** [comment]
thanks - this might be a regression
