### ISSUE TITLE
After a successful backup, remove older backups

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4585]
### Observed behavior

In relation to #4578 and the growth in database storage footprint in addition to some historical problems of accumulated garbage data and redundant backup files, we should have a management command to clean up the database.

### Expected behavior

After a successful database backup, delete all other database backups bar last completed backup.

### User-facing consequences

Large disk-space footprint can easily be recovered. UI can follow.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

#4578 

CC: @jredrejo @indirectlylit @rtibbles @ralphiee22

**Comment by rtibbles** [comment]
The only time we trigger a database backup is when we upgrade, so it's not unreasonable to only maintain the most recent backup.

Once backup has completed successfully here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/utils/main.py#L77

We should then cleanup database backups that are not the most recent backup.

Can add tests for the behaviour in main in the tests for that module: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/utils/tests/test_main.py

**Comment by rtibbles** [comment]
Fixed in #8402
