### ISSUE TITLE
Copied database is not detected in the kolibri 0.11.0

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4600]
### Observed behavior
We have created a new facility in the server and also want same facility in other server but when we copy same database in other server, it will not detect any database and ask user to create new facility.

Please see screenshots for more information.

### Expected behavior
If we copy a database to other server and database has facility then it must not ask user to create facility again.

### Steps to reproduce
1. Create a new facility on kolibri 0.11.0.
2. Stop the server.
3. Copy database file from .kolibri to other location.
4. Delete database file from .kolibri.
5. Copy db.sqlite3 file from copied location to the .kolibri folder.
6. Start the server.
7. Try to access the server.

### Context

 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots: 

![1](https://user-images.githubusercontent.com/12776071/49929815-60d1d700-fee9-11e8-82ef-615e749c101f.png)
![2](https://user-images.githubusercontent.com/12776071/49929816-60d1d700-fee9-11e8-958f-bffbeaa4c268.png)
![3](https://user-images.githubusercontent.com/12776071/49929817-616a6d80-fee9-11e8-8269-955c498af20e.png)
![4](https://user-images.githubusercontent.com/12776071/49929818-616a6d80-fee9-11e8-9473-5744636f3be2.png)
![5](https://user-images.githubusercontent.com/12776071/49929819-62030400-fee9-11e8-8426-c8bb9c1a7cf7.png)
![6](https://user-images.githubusercontent.com/12776071/49929822-63ccc780-fee9-11e8-9324-137324ba19e5.png)
![7](https://user-images.githubusercontent.com/12776071/49929823-63ccc780-fee9-11e8-9cd0-754853c5919c.png)
![8](https://user-images.githubusercontent.com/12776071/49929824-63ccc780-fee9-11e8-9149-2bceb58b96a3.png)
![9](https://user-images.githubusercontent.com/12776071/49929825-64655e00-fee9-11e8-93c1-4590ca43d9c0.png)
![10](https://user-images.githubusercontent.com/12776071/49929826-64655e00-fee9-11e8-93e7-295cc837918d.png)

**Comment by indirectlylit** [comment]
thank you - we will investigate

**Comment by jamalex** [comment]
First, a small note: To stop the Kolibri server, use `kolibri stop`, not `kill`. That will ensure a cleaner shutdown.

When you transfer the database, you should ideally also transfer over the `db.sqlite-wal` and maybe also the `db.sqlite-shm` files. In some cases (especially if you hard-kill the server, rather than using `kolibri stop`, as noted above), data may not have completely been written out into the `db.sqlite3` file from the WAL file.

**Comment by jamalex** [comment]
You can also try running `kolibri manage vacuumsqlite` after `kolibri stop`, which should help to flush the data out of the WAL file.

**Comment by rtibbles** [comment]
Have any of the steps suggested above remedied this situation?

**Comment by swapnil106111** [comment]
@rtibbles By copying db.sqlite3, db.sqlite-wal and db.sqlite-shm files this issue gets solved.

**Comment by rtibbles** [comment]
OK, closing then !
