### ISSUE TITLE
While watching a video on a tablet, the cc options menu will not close

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4602]
### Observed behavior
While watching video on tablet, when user click CC button then CC button options don't disappear clicking on it.

Please watch attached video.

### Expected behavior
It must appear when we click on button and must go behind on click.

### Steps to reproduce
1. Login with learner on tablet.
2. Watch video and click on CC button.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : chrome

### screenshot:
![img_20181213_164656](https://user-images.githubusercontent.com/12776071/49935626-8cf45480-fef7-11e8-989f-7e05f6131dd9.jpg)

[VID_20181213_164504.mp4.zip](https://github.com/learningequality/kolibri/files/2675921/VID_20181213_164504.mp4.zip)

**Comment by rtibbles** [comment]
I think this can be solved by upgrading to a newer version of videojs.
