### ISSUE TITLE
Resume field is missing in recommended in learn tab.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4603]
### Observed behavior
When learner login and watched some part of video. Then learner go to the recommended tab to watch remaining video but learner can not see resume field in recommended tab.

Please see attached screenshot for more information.

### Expected behavior
It must show resume field in recommended tab.

### Steps to reproduce
1. Login with learner.
2. Watch half video.
3. Then go to the recommeded tab to resume the video.

### Context

 * Kolibri version : Kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![3](https://user-images.githubusercontent.com/12776071/49940212-f038b380-ff04-11e8-9100-d3a8972444a2.png)

![1](https://user-images.githubusercontent.com/12776071/49940225-f75fc180-ff04-11e8-82d8-a7feb01ab765.png)
![2](https://user-images.githubusercontent.com/12776071/49940226-f75fc180-ff04-11e8-91e6-97818986f021.png)

[VID_20181213_190858 (1).mp4.zip](https://github.com/learningequality/kolibri/files/2676276/VID_20181213_190858.1.mp4.zip)

**Comment by rtibbles** [comment]
This is within a single session, presumably? We cache the recommendation responses, as they are expensive to calculate, so these will not refresh for 10 minutes.

**Comment by indirectlylit** [comment]
Maybe this is something we could do purely client-side?

**Comment by radinamatic** [comment]
Testing this on the asset from #4703: confirmed that a started item appears under *Resume* only after about 10 minutes during the same session, or immediately after signing out and in again.

**Comment by rtibbles** [comment]
Yeah, we can probably do some client side workaround to update in most cases without fetching from the server.

**Comment by rtibbles** [comment]
These responses are no longer cached, so this is fixed.
