### ISSUE TITLE
Generating a data log file clears the status of content imports

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#4604]
### Observed behavior
After https://github.com/learningequality/kolibri/commit/ad302a5ae3 was applied, there's no way to cancel a single task using JavaScript.

One side effect that arose in #4531 is that there is unexpected interaction between different users of iceqube tasks:

![export](https://user-images.githubusercontent.com/2367265/50033335-f71b0100-ffac-11e8-9cd3-29662ea0bb7b.gif)

### Expected behavior
`cancelTask` should cancel one task, to clear all the tasks we have the `clearTasks` function

### User-facing consequences

User might not understand that a channel was successfully imported if they generate a data log file while the import task is running.

**Comment by indirectlylit** [comment]
Looks like this may have been a 'big hammer' solution to fix #1673

**Comment by rtibbles** [comment]
Yeah, that was it.

**Comment by jredrejo** [comment]
If importing content needs that behaviour I suggest to make it use `clearTasks` instead of `cancelTask` , so cancelTask remains available with the functionality it should have.

**Comment by indirectlylit** [comment]
updated description to reflect a user-facing issue

**Comment by indirectlylit** [comment]
tested and this appears to have been addressed in 0.13
