### ISSUE TITLE
Lessons and quizzes with same name are allowed

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4609]
### Observed behaviour
Coach is able to create lesson with existing name of the lesson. Each lesson must have unique name.
It creates confusion.
 
### Expected behavior
Each lesson must have unique name.

### Steps to reproduce
1. Login with coach.
2. create lesson with existing lesson name.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![1](https://user-images.githubusercontent.com/12776071/49994415-78739300-ffaf-11e8-96f1-cb099e5297a0.png)

**Comment by rtibbles** [comment]
As I noted in exams, this might be something that we want to warn about, rather than disallow outright.

**Comment by indirectlylit** [comment]
merging with #4626
