### ISSUE TITLE
Integrity checks and sanity checks

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4611]
### Observed behavior

In #3285, we discussed some sanity checks for each time Kolibri launches. However, this sole behavior will not scale for start-up once we start adding more elaborate checks. Anyways, some integrity checks are much better suited for on-demand troubleshooting.

 * **Sanity checks**: Those that fire automatically at start-up. Example: A permission check for the file system.
 * **Integrity checks**: Longer-running tests that fire on-demand. Example: Checking to see if expected channel contents are found.

### ~Expected~ Suggested behavior

An integrity check is perhaps most obvious as a management command. I'll suggest the name `dbintegrity`, since all checks would likely revolve around verifying that data in the database is correctly defined and consistent with other disk objects. Here is a mockup:

```
kolibri manage dbcheck

Pre-check: Kolibri is off? [1/3] ..... OK
Pre-check: Time estimate [2/3] ....... OK
Pre-check: Normal consistency [3/3] .. OK

Do not switch on Kolibri while the checks are active. The pre-check found that you
have a »medium-large« database and is estimated to last >1m and <30m, do you
want to continue? [Y/n] Y

Verifying database...

Checking pragma settings [1/6] ....... OK
Checking permissions [2/6] ........... OK
Unused channel data [3/6] ............ OK
Collecting garbage [4/6] ............. OK
Missing channels [5/6] ............... FAIL!
Duplicate users [6/6] ................ OK


!! FAILURES FOUND !!

Missing channels [5/6]

 * Channel ID 1ceff53605e55bef987d88e0908658c5 was not found on disk, please
   ensure that read and write permissions are set correctly. Could not read:

       /home/username/.kolibri/content/databases/1ceff53605e55bef987d88e0908658c5.sqlite3

```

### User-facing consequences

 * Being able to verify copies and replications of Kolibri
 * An example where something went wrong during file copying is seen here: https://github.com/learningequality/kolibri/issues/4539
 * We also know that SD cards are fragile

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by rtibbles** [comment]
Closing this issue as stale - we should open specific follow up issues if needed.
