### ISSUE TITLE
Update to pytest 4.x

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4618]
### Observed behavior

A new major release of pytest is out: https://docs.pytest.org/en/latest/changelog.html

It seems like a smaller release, judging from the release notes. However, the PyUp build also failed, possibly because of this upgrade... we'll have to investigate

### Expected behavior

:100: developer tools contemporary pleasure

### User-facing consequences

Absolutely none

### Errors and logs

Not sure

### Steps to reproduce

n/a

### Context

n/a

**Comment by rtibbles** [comment]
Noting that pytest is now on version 6.

**Comment by rtibbles** [comment]
Going to close this as it is now fixed as stated. We can file follow up issues for newer versions of pytest.
