### ISSUE TITLE
Shows sorry! something went wrong.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4623]
### Observed behavior
When coach is going to the recent tab to see exercise and video progress then it shows error.

### Expected behavior
It must show progress instead of error.

### Steps to reproduce
1. Login with coach.
2. go to the recent tab.
3. Go to the exercise/video and see.

### Context

 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/50138341-4d958180-02c4-11e9-92b7-01a9fb28acc2.png)
![2](https://user-images.githubusercontent.com/12776071/50138342-4d958180-02c4-11e9-9426-fe0709d16751.png)
![3](https://user-images.githubusercontent.com/12776071/50138343-4e2e1800-02c4-11e9-9ac4-e520796024ed.png)

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri0.11.1. It is working as expected.

![1](https://user-images.githubusercontent.com/12776071/51603735-a6de7980-1f30-11e9-9727-7bee0540d921.png)

After clicking on video not showing error

![2](https://user-images.githubusercontent.com/12776071/51603745-ae058780-1f30-11e9-8aa3-819a29290dd0.png)

**Comment by miyer03** [comment]
This was observed in the class yesterday for students as well as when logged in as coach through a tab.
Attached are the error message.

Kolibri 0.12.5
Ubuntu 18.04


[Coach Error Msg.txt](https://github.com/learningequality/kolibri/files/3381174/Coach.Error.Msg.txt)
[Learner Error Msg.txt](https://github.com/learningequality/kolibri/files/3381176/Learner.Error.Msg.txt)

**Comment by indirectlylit** [comment]
@miyer03 this is unlikely to be the same issue, so I filed a new one here: #5763

If you could provide concrete steps to reproduce that would help us.

**Comment by miyer03** [comment]
@indirectlylit I am not sure if you have fixed this with 12.8 release. One way where we observed it to occur or reproduce is when you clear the cache of all the tablets that the students are using. Once that is done this used to occur quite frequently.

**Comment by indirectlylit** [comment]
@miyer03 see #5763
