### ISSUE TITLE
Not able to move in learner of coach tab.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4624]
### Observed behavior
Not able to move or click on anything in the learner of coach tab.

### Expected behavior
It must allow user to click anywhere in the kolibri.

### Steps to reproduce
1. Solve the exercise.
2. Login with coach.
3. go to the learner tab.
4. follow the path from which channel you solved exercise.
5. Click on exercise.
6. Check attempts.
7. Click on other question and see you will not able to move anywhere in the recent tab.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

**Comment by swapnil106111** [comment]
This issue is same as for channel tab. #4610

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.11.1. It is working as expected.

**Comment by indirectlylit** [comment]
thanks for following up @swapnil106111 - that's very helpful to us
