### ISSUE TITLE
Average resource behaviour in channels of coach tab.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4625]
### Observed behavior
When coach goes to the coach tab and click on channel tab. click on channel tab and see avg resource progress.
Sometimes it shows 0%, sometimes it shows -. 

Don't know whether it is issue or not?  But behaviour of the Average resource progress is untrackable.

### Steps to reproduce
1. Solve exercises.
2. Login with coach and click on channel tab.
3. and see behaviour of avg resource progress/

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser : chrome

### Screenshot:
![1](https://user-images.githubusercontent.com/12776071/50145566-e681c800-02d7-11e9-9a89-10b9f04dc83f.png)
![2](https://user-images.githubusercontent.com/12776071/50145567-e71a5e80-02d7-11e9-9098-dab77ce98fbf.png)

**Comment by indirectlylit** [comment]
Currently, we define a "resource" as any content that is not an exercise. Therefore, exercises only have exercise progress, and all other content types have 'resource progress'.

We're hoping to clarify this in 0.12
