### ISSUE TITLE
yarn run lint:fix stopped working

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4629]
### Observed behavior

```
(k012x)d@mac ~/P/l/r/k012x (guest) [1]> yarn run lint:fix
yarn run v1.12.3
$ yarn run lint -w
$ kolibri-tools lint -w
Kolibri CLI: Must specify files or glob patterns to lint!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

lint the things

### User-facing consequences

none

### Context

`develop`

----

cc @rtibbles

**Comment by rtibbles** [comment]
I changed its behaviour deliberately, but I am guessing you would like something to do the equivalent. Would `yarn lint-all:fix` do? (`yarn lint-all` will run linting for all files, but will not fix them).

**Comment by indirectlylit** [comment]
yeah that'd be great.

sometimes after a manual merge I want to run a quick lint/fix on the results

**Comment by rtibbles** [comment]
Also realizing that for some reason `yarn run lint-all` is not catching things on Travis, we currently have some files on develop that are failing linting locally.

**Comment by indirectlylit** [comment]
linting is improved, but `yarn run lint:fix` still seems to not work

```
> yarn run lint:fix
yarn run v1.12.3
$ yarn run lint -w
$ kolibri-tools lint -w
Kolibri CLI: Must specify files or glob patterns to lint!
error Command failed with exit code 1.
```

**Comment by rtibbles** [comment]
You didn't specify any files to lint `Must specify files or glob patterns to lint!`

If you want to lint and fix all files use `yarn run lint-all:fix` (see our discussion above).
