### ISSUE TITLE
Indicate size of the content channel prior to retrieving on network 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#463]
In Belgrade atm, trying to run bellow commands for the latest Kolibri installer (build 24):

```
kolibri manage importchannel -- 7db80873586841e4a1c249b2bb8ba62d
kolibri manage retrievecontent -- network 7db80873586841e4a1c249b2bb8ba62d
```

The second command run for more than 45 minutes and then VM restarted, so I'm not sure if it finished correctly, or run of the space in the VM hd maybe...

Could we add a confirmation dialog for the user indicating the size? Something along these lines:

```
Size of this content channel is 1.5Gb, are you sure you want to install it now? Y/n
```

@jamalex @aronasorman

**Comment by aronasorman** [comment]
We can add this dialog box when `retrievecontent/importcontent` is run at the command line. Does that work @radinamatic?

**Comment by radinamatic** [comment]
Yes @aronasorman, the use case above was done through the command line, and I'm guessing it's working ok on non virtual machine scenarios. However, my crappy connection here on Balkans makes me think that our target user base could also benefit from the information about the size of the content channel they request for download. That would give them some approximate idea about the time they'll need to fully download it. :)

**Comment by aronasorman** [comment]
Well right now it's kinda hard, since both downloading the channel data and the content is done as one step. You need to download the channel first to be able to determine how big the content is. Especially since in the future, we'll want to have them select which specific content to download first.

However we can add in an estimated time to our progress bar (or at least can pass that information to the frontend for them to render). What say you @indirectlylit @ralphiee22 @jamalex?

**Comment by radinamatic** [comment]
I was under the impression that `kolibri manage importchannel -- channelID` could already retrieve the information about the channel size (since when you view the info about the channel on the content curation server there **is** a size for each content channel ID) and `kolibri manage retrievecontent -- network channelID` was just downloading it.

If that's not the case, then the estimated time on the progress bar could be useful!

**Comment by indirectlylit** [comment]
thanks for the info here!

This task needs some planning and design, so I'm migrating it to trello: https://trello.com/c/zGD8iLpq/691-add-size-and-time-estimates-to-content-transfers
