### ISSUE TITLE
Not able identify multiple choice question.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4636]
### Observed behavior
While using kolibri on tablet, learner is not able to identify whether question is single selection or multiple selection. Single selection or multiple selection shows circle to select the answer.

### Expected behavior
It must show checkbox for muliple choice question.

### Steps to reproduce
1. Try to solve multiple choice question on the tablet.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![img_20181219_181507](https://user-images.githubusercontent.com/12776071/50221301-b2330800-03ba-11e9-8a68-ebed17caa1b9.jpg)
![img_20181219_181531](https://user-images.githubusercontent.com/12776071/50221302-b2cb9e80-03ba-11e9-954e-65d8bc2e7bff.jpg)

**Comment by rtibbles** [comment]
Hi @swapnil106111 thanks for filing this issue - this is an issue with the Khan Academy question renderer, so we cannot directly address it. However, when we implement our own question renderer, we will be sure to disambiguate these question types.

**Comment by swapnil106111** [comment]
@rtibbles Same issue appearing for multiple choice questions in the Kolibri 0.12.0b4.

**Comment by rtibbles** [comment]
As noted above, this is an upstream issue with Khan Academy's exercise renderer.
