### ISSUE TITLE
Full network address in content import.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4637]
### Observed behavior
Trying to import content from local network but it is asking for full network address. We have provided ip address and network name but shows could not connect to this address.

But we are able to ping mentioned address.
Need your help so content import from local network will work.

### Steps to reproduce
1. Try to import from local network.
2. Enter ip adress.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/50224498-13130e00-03c4-11e9-8dd5-ea31cc128e0c.png)

**Comment by indirectlylit** [comment]
You may also need to specify a port, e.g. `192.168.0.169:8080` if applicable. Let me know if that works

**Comment by swapnil106111** [comment]
@indirectlylit Tried using 192.168.0.169:8080. And it is working fine. Thank you for immediate reply.
