### ISSUE TITLE
Modal Jitters at Certain Widths

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#4641]
### Observed behavior

Modal jitters and constantly resizes at certain dimensions. [See this video](https://drive.google.com/file/d/1QUFyTsiIv3ftuhC7qo5WI2YIQ7SzWYzK/view?usp=sharing) (gif couldn't display the issue properly due to low framerate issues).

### Expected behavior

Modal stays in place without jitter

### User-facing consequences

Confusion. Disgust. Seizures?

### Steps to reproduce

Open a modal, zoom in an out to change dimensions.
Alternatively: Open a modal, resize window until you see behavior.

### Context

Kolibri 0.12 demo. Chromium 70.0.3538.110

**Comment by indirectlylit** [comment]
The typical way of addressing this is to set `overflow-y: scroll` so that the available width never changes regardless of the content height.

We don't want to do that in this case because most modals don't need the scrollbar. Instead, let's conditionally set `overflow-y: scroll` when the content is `> 80%` of the scrolling pane height using our element query mixin.

**Comment by indirectlylit** [comment]
reported again in #5011

> ![scroll-flash](https://user-images.githubusercontent.com/2367265/52605053-1655d380-2e22-11e9-9c8e-623453f3a383.gif)

**Comment by radinamatic** [comment]
Not sure if it's related, but encountered a similar flicker with video player while testing beta7 in Chrome on Ubuntu 16.04 (no flicker in Firefox).

![flicker-video-player](https://user-images.githubusercontent.com/1457929/52982238-46cedc00-33e5-11e9-8c4f-a4e49b57d463.gif)

**Comment by jeepurs** [comment]
If it helps to convince it's not only my computer, @jredrejo 's machine also showed this behavior during our UN Women training today (when we were demonstrating it on a screenshare..).

**Comment by indirectlylit** [comment]
> Not sure if it's related, but encountered a similar flicker with video player while testing beta7 in Chrome on Ubuntu 16.04 (no flicker in Firefox)

@radinamatic mind opening a separate issue for that one?

**Comment by ralphiee22** [comment]
Can someone reliably replicate this? 
The modal shown in this issue has become a full page now.

**Comment by radinamatic** [comment]
This is a really old issue, we can close it and move on! 👍

**Comment by indirectlylit** [comment]
no, in fact this issue has been reproduced on other modals. @jeepurs experiences it often I believe - she might be able to help.

It will almost certainly be browser and OS-dependent

**Comment by indirectlylit** [comment]
fixed!

**Comment by jeepurs** [comment]
Update: today when I was registering @rtibbles a couple new accounts on the http://jordan-kolibri.mylearningpathway.org

Same browser and machine I've used as always so the specs should be available above ^^

Might it do with the fact that I view at 200%?
