### ISSUE TITLE
First show wrong remaining question count, after 3-4 seconds update question count.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4643]
### Observed behavior
After solving last question in the exam, submit the exam. It will show you 1 questions remaining and after 3-4 seconds remaninng question count shows as expected. 

### Expected behavior
It must show remaining question count if there is any.

### Steps to reproduce
1. Solve the exam.
2. After solving last question, click on submit exam immediately.
3. And see the behaviour.

### Context

 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser  : Chrome

### Video
[VID_20181220_152410.zip](https://github.com/learningequality/kolibri/files/2698499/VID_20181220_152410.zip)

**Comment by rtibbles** [comment]
Note: this is a result of our trailing edge debouncing for saving exam questions, to prevent saving the wrong answer onto the wrong question. Could possibly be resolved by doing a direct save on submitting the exam.

**Comment by swapnil106111** [comment]
@rtibbles Tested in kolibri 0.11.1. It is working as expected.

![1](https://user-images.githubusercontent.com/12776071/51595982-f5cee380-1f1d-11e9-9758-1d2119a93142.png)
