### ISSUE TITLE
dynamic button styles are being lost

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4645]
### Observed behavior

Sometimes buttons change from a normal background color to white:

![image](https://user-images.githubusercontent.com/2367265/50307239-af80f300-044c-11e9-9a1e-1f3ca314b106.png)

This appears to be because Aphrodite's dynamically generated classes are not defined in the page. Whether they existed at one point and were cleaned up, or never existed, isn't entirely clear yet.

### Expected behavior

All aphrodite dynamically-generated classes exist when they're needed

### User-facing consequences

broken styles

### Errors and logs

None

### Steps to reproduce

As a learner - take an exam. Look at the 'submit quiz' button

### Context

0.12

---

cc @rtibbles

**Comment by indirectlylit** [comment]
I believe the issue is that Perseus also uses Aphrodite, and when exercises are loaded it tramples on our styles.

I spent a little bit of time hacking on Aphrodite to make the style element data attribute (`data-aphrodite`) configurable - it's currently hard-coded. I was planning on submitting an upstream patch, putting a temporary fork of Aphrodite into our `kolibri/packages` folder. However it's going too slowly and I need to shift my focus elsewhere...

**Comment by rtibbles** [comment]
Ah that makes sense, gives me enough of a lead to follow up here!

**Comment by rtibbles** [comment]
I think this should have been fixed by #4704?

**Comment by indirectlylit** [comment]
yup, thanks!
