### ISSUE TITLE
Error in render: "TypeError: Unparseable colour: null passed to darken function"

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4646]
### Observed behavior

Exam viewer header is broken:

![image](https://user-images.githubusercontent.com/2367265/50308438-0dfba080-0450-11e9-8c8a-261450578390.png)

### Expected behavior

Exam header works

### User-facing consequences

user lacks ability to go 'back'

### Errors and logs

![image](https://user-images.githubusercontent.com/2367265/50308461-1fdd4380-0450-11e9-9e72-142068cb8d63.png)

### Steps to reproduce

as a learner, take an exam and then view your report

### Context
0.12

----

cc @rtibbles

**Comment by rtibbles** [comment]
In good news, that's a TypeError being thrown inside our own code - glad I set that up!

**Comment by rtibbles** [comment]
Couldn't replicate this exact error any more, but the header and back button sure were a funny colour, so I fixed that instead.
