### ISSUE TITLE
Finish the celery

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#465]
There are still some remnants of Celery in the codebase:

```
➜  kolibri git:(master) ack-grep -i --python celery kolibri                                              1 1  11:39:13
kolibri/deployment/default/celeryconfig/default.py
2:CELERY_RESULT_BACKEND = 'db+sqlite:///results.sqlite3'
4:CELERY_TASK_SERIALIZER = 'pickle'
5:CELERY_RESULT_SERIALIZER = 'json'
6:CELERY_ACCEPT_CONTENT = ['pickle', 'json']
7:CELERY_TIMEZONE = 'Europe/Oslo'
8:CELERY_ENABLE_UTC = True

kolibri/tasks/management/commands/base.py
68:    CELERY_PROGRESS_STATE_NAME = "PROGRESS"
```

And yes, I really don't like Celery :)

**Comment by jamalex** [comment]
You don't get dessert until you finish! Mmmmmm.....

![image](https://cloud.githubusercontent.com/assets/618416/17880217/379dd2d2-68ad-11e6-9e25-4ece75c1c1a1.png)

**Comment by jamalex** [comment]
An ode to how much @benjaoming loves celery:

![](https://deepart-io.s3.amazonaws.com/cache/a1/95/a195ce14521fee34a08029e395a38f47.jpg)

**Comment by jamalex** [comment]
And here's what you've saved us from, if the infection had gone unchecked:

![](https://deepart-io.s3.amazonaws.com/cache/02/56/02564761597db7a0f2a61ea6ccf60117.jpg)

**Comment by benjaoming** [comment]
Closing this issue before it gets out of hand :D

**Comment by jamalex** [comment]
*This* celery surely isn't getting out of hand!

![](https://www.colourbox.com/preview/6787440-celery-bunch-in-a-hand.jpg)
