### ISSUE TITLE
Log all commands being run + arguments

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4652]
### Observed behavior

Getting logs for debugging purposes is a bit difficult, given that the logs do not capture when the user invokes other commands, `kolibri mange migrate ...` or `kolibri plugin ...` etc.

### Expected behavior

Add some `logging.info` call.

### User-facing consequences

Time-consuming explanations for support purposes.

### Errors and logs

n/a

### Steps to reproduce

Run a command like `kolibri manage showmigrations` and see that nothing is logged.

### Context

Community support, Github etc.

**Comment by lyw07** [comment]
should be updated in #5495
