### ISSUE TITLE
Language selection.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4653]
### Observed behavior
When user is trying to change the language, it is changing. But for that perticular user only. If user changed language on server then changed language is appearing only on server not on connected tablets.

Need some guidence in language selection. Please let me know if we missed anything.

### Steps to reproduce
1. Login with device onwer and change the language.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser  : Chrome

### Screenshot
![img_20181224_122929](https://user-images.githubusercontent.com/12776071/50393195-744b3080-077a-11e9-9ed1-d7325cdc694e.jpg)

**Comment by rtibbles** [comment]
This is intended behaviour - it would be best to configure your tablets to have the language you want as the default language for the browser, then users would not need to change it.
