### ISSUE TITLE
add 'started' learner notification type

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4660]
### Observed behavior

The current implementation of notifications includes 'completed' and 'needs help' events. However, some of the mockups also show a 'started' type, which could be very useful information for the coaches.

### Expected behavior

We should include functionality for recording and displaying 'started'-type events

### User-facing consequences

Coaches don't have a complete picture of their learners' activity without 'started' events

### Context

0.12

----

cc @jredrejo @jonboiser @rtibbles

**Comment by jredrejo** [comment]
@indirectlylit  can you give me the link of he mockups with the started event?
The ones I have dont' contain it (from the links at the notion page on Actionable Notifications for Coaches)

I should know if the event is going to be triggered when the started object is a Lesson, an Exercise , of both. Also, I  need to know if it's an event per user or per classroom/group.

**Comment by indirectlylit** [comment]
Hey - 

* mockup - they're alluded to in the [per-learner activity feed](https://www.figma.com/file/D5wXhmWNGyt60SpGBgFucwZU/Coach-reports-0.12?node-id=1385%3A0) (see also image below)
* triggering - same as 'completed' events, so for resources, exercises, exams, lessons I believe?


Note that the 'time spent' column below shouldn't be there:

![image](https://user-images.githubusercontent.com/2367265/51130332-ca037d80-17fa-11e9-8838-7a6f84ab7991.png)

**Comment by jtamiace** [comment]
Here are some locations where a "started" message appears, although it is not on the actionable notifications page

Learner profile > Lesson
https://www.figma.com/proto/D5wXhmWNGyt60SpGBgFucwZU/Coach-reports-0.12?node-id=1278%3A6705&viewport=-63%2C168%2C0.0514209&scaling=min-zoom

To my knowledge there are not yet notification messages for "started" on the dashboard cc @khangmach

**Comment by khangmach** [comment]
Yeah there aren't yet notification messages for "started" interactions on the dashboard. Intentionally omitted because the reasoning was that they didn't seem to qualify as any sort of "completion" event. I don't have an issue with adding it to the dash though

**Comment by indirectlylit** [comment]
cc @jonboiser
