### ISSUE TITLE
Create new exam - requires the Internet

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4661]
### Observed behavior
When creating an exam, if the server is not internet connected, a lag occurs whilst it tries to fetch a font.

Not sure if this issues is related: "Exam page has lag when I creating an exam #4159"

### Expected behavior

…

### User-facing consequences
Due to the lag, users may abandon the idea of using  Kolibri to create an exam if offline.

### Errors and logs

[server.log.txt](https://github.com/learningequality/kolibri/files/2714042/server.log.txt)
[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2714044/kolibri.log.txt)

From the browser console:

> 		Pulling online resources
> 			[INFO: kolibri/core/assets/src/core-app/mediator.js] KolibriModule: coach_module registered
> 			default_frontend-0.11.0.js:46 [INFO: kolibri/core/assets/src/state/modules/core/actions.js] Session set.
> 			16Failed to decode downloaded font: <URL>
> 			16OTS parsing error: invalid version tag
> 			default_frontend-0.11.0.js:1 [WARN: kolibri/core/assets/src/utils/i18n.js] Could not load full font for 'en'
> 			(anonymous) @ default_frontend-0.11.0.js:1

### Steps to reproduce
Create an exam offline.

### Context
 * Kolibri version .11
 * Linux
 * Vivaldi

**Comment by indirectlylit** [comment]
Do you have a way of showing that it is trying to access internet resources? If Vivaldi has the same dev tools as chrome you can look at the Network tab?

In your logs I see lots of import errors that we can look into, and above I see a font parsing error that we can also look into, but I don't see anything related to exam creation depending on the internet

**Comment by nobicycle** [comment]
@indirectlylit
Next time I will upload a picture showing that I was actually in the browser using Create Exam. I will also post from the Network tab instead of just the Console. The problem disappeared once the internet came back up. Perhaps leave this report on standby until this data gets supplied.

**Comment by rtibbles** [comment]
Any updates on this @nobicycle? We have also made some improvements to exam selection that should reduce lag overall, so perhaps this can help isolate any online resources being requested.

**Comment by nobicycle** [comment]
> Any updates on this @nobicycle? We have also made some improvements to exam selection that should reduce lag overall, so perhaps this can help isolate any online resources being requested.

If you don't mind a little wait, I will retest after 1.12 which I believe is in the pipeline.

**Comment by rtibbles** [comment]
Sure, 0.12.0 should be out this week - just wanted to see if there was anything we could do before then if investigation had shown further information. Thanks!

**Comment by nobicycle** [comment]
Just tested using 0.12.
Exams seem renamed as Quiz.
I could create a Quiz no problem.

**Comment by indirectlylit** [comment]
thanks for following up
