### ISSUE TITLE
RTL support needed for ePub renderer

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#4669]
### Observed behavior

Left-aligned text:
<img width="848" alt="kolibri-render-epub-ar" src="https://user-images.githubusercontent.com/163966/50605275-dcdb9100-0e8f-11e9-825d-788d0068b12f.png">

See:
http://35.196.115.213/learn/#/topics/c/e7df2f5a2bc743baacf182e8bf443aba

### Expected behavior

Right-aligned text:

<img width="1079" alt="ibooks-render-epub-ar" src="https://user-images.githubusercontent.com/163966/50605314-fe3c7d00-0e8f-11e9-955b-4ee36a8b7adc.png">

### User-facing consequences

Uploaded Arabic ePubs would be difficult to read.

### Context

Studio channel to use for testing 
https://studio.learningequality.org/channels/e6af491e90f642a9bf12d549bab662aa/edit/e6af491   
 token = `varin-lakod`

Direct link to ePub on Studio:
https://studio.learningequality.org/channels/e6af491e90f642a9bf12d549bab662aa/edit/e6af491/e7df2f5

**Comment by ivanistheone** [comment]
@rtibbles If you're looking at ePub, maybe you can look into the "User should be able to choose one-page or two-page view for reading" referenced in https://github.com/learningequality/kolibri/issues/4530

**Comment by rtibbles** [comment]
I have implemented a fix for this in #4686, but the example content above has its language set as English, so should be properly set to Arabic to work properly.
