### ISSUE TITLE
add FV to kolibri supported languages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4670]
### Observed behavior

translation of Fulfulde Mbororoore is complete

 https://crowdin.com/project/kolibri/fv 

### Expected behavior

add to supported langs

### Context

0.11.1 and 0.12.0

**Comment by radinamatic** [comment]
@indirectlylit Ping me when ready so I can test before we pass it on to Chris! :+1:

**Comment by rtibbles** [comment]
Added!

**Comment by rtibbles** [comment]
This has now been done!
