### ISSUE TITLE
test and document iOS support

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4672]
### Observed behavior

In https://github.com/learningequality/kolibri/pull/4671 we're removing the block on iOS

### Expected behavior

* Add to our integration testing matrix
* Update docs
* Add to the browserlist file - https://github.com/learningequality/kolibri/blob/develop/browserslist

### Context

0.12

----

cc @radinamatic

**Comment by kollivier** [comment]
PR #4676 adds iOS 9.3+ to the list of supported browsers.
