### ISSUE TITLE
some static assets no longer load

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4674]
### Observed behavior

Assets such as the Kolibri logo and login background photo no longer load:

![image](https://user-images.githubusercontent.com/2367265/50660166-b1ba7580-0f53-11e9-8070-2a282123b0f9.png)

### Errors and logs

404s:

![image](https://user-images.githubusercontent.com/2367265/50660148-a8c9a400-0f53-11e9-8cf8-de7963ff3ee2.png)

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Duplicate of #4577
