### ISSUE TITLE
Full Screen Fails on Chromium  71 and Vivaldi

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4680]
### Observed behavior
Using Chromium 71 or  Vivaldi 2.2.1388.34, the full screen button for BOOK resources  either does nothing or distorts.
Using Firefox there is no problem. It does not affect video resources such as Sikana

### User-facing consequences
Very difficult to read books…

### Errors and logs
![1809eba4-bad0-4e8d-9011-645243368501](https://user-images.githubusercontent.com/1372447/50683674-ce3ad880-104d-11e9-9664-87a148ba4268.jpg)

Distortion:
![c58eef80-61b3-4cf4-bb84-9af8830cc31b](https://user-images.githubusercontent.com/1372447/50683792-3b4e6e00-104e-11e9-8b11-03f255e0162c.jpg)

Browser Console

> default_frontend-0.11.0.js:33 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
>     at Object.request (default_frontend-0.11.0.js:33)
>     at Object.toggle (default_frontend-0.11.0.js:33)
>     at a.enterFullScreen (default_frontend-0.11.0.js:218)
>     at a.toggleFullscreen (default_frontend-0.11.0.js:218)
>     at click (document_pdf_render_module-0.11.0.js:15)
>     at a.t (default_frontend-0.11.0.js:7)
>     at a.e.$emit (default_frontend-0.11.0.js:7)
>     at a.onClick (document_pdf_render_module-0.11.0.js:15)
>     at t (default_frontend-0.11.0.js:7)
>     at HTMLButtonElement.t._withTask.i._withTask (default_frontend-0.11.0.js:7)
> request @ default_frontend-0.11.0.js:33
> toggle @ default_frontend-0.11.0.js:33
> enterFullScreen @ default_frontend-0.11.0.js:218
> toggleFullscreen @ default_frontend-0.11.0.js:218
> click @ document_pdf_render_module-0.11.0.js:15
> t @ default_frontend-0.11.0.js:7
> e.$emit @ default_frontend-0.11.0.js:7
> onClick @ document_pdf_render_module-0.11.0.js:15
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> 62XHR finished loading: PATCH "<URL>".
> 31XHR finished loading: GET "<URL>".
> default_frontend-0.11.0.js:207 [INFO: kolibri/core/assets/src/core-app/mediator.js] KolibriModule: html5_app_renderer_module registered
> default_frontend-0.11.0.js:231 XHR finished loading: POST "http://192.168.1.100:8087/api/logger/contentsessionlog/?1546596786456=1546596786456".
> (anonymous) @ default_frontend-0.11.0.js:231
> (anonymous) @ default_frontend-0.11.0.js:389
> i @ default_frontend-0.11.0.js:389
> d.promise @ default_frontend-0.11.0.js:27
> f.promise @ default_frontend-0.11.0.js:65
> (anonymous) @ default_frontend-0.11.0.js:231
> a @ default_frontend-0.11.0.js:153
> (anonymous) @ default_frontend-0.11.0.js:26
> (anonymous) @ default_frontend-0.11.0.js:389
> I @ default_frontend-0.11.0.js:389
> _.when @ default_frontend-0.11.0.js:389
> O.run @ default_frontend-0.11.0.js:389
> e._drain @ default_frontend-0.11.0.js:388
> drain @ default_frontend-0.11.0.js:388
> e.observe.characterData @ default_frontend-0.11.0.js:52
> characterData (async)
> (anonymous) @ default_frontend-0.11.0.js:52
> e.run @ default_frontend-0.11.0.js:388
> e.enqueue @ default_frontend-0.11.0.js:388
> b.when @ default_frontend-0.11.0.js:389
> m.chain @ default_frontend-0.11.0.js:389
> i.then @ default_frontend-0.11.0.js:389
> d @ default_frontend-0.11.0.js:27
> f @ default_frontend-0.11.0.js:65
> e @ default_frontend-0.11.0.js:26
> t.default @ default_frontend-0.11.0.js:33
> w.client @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:1
> Promise.then (async)
> (anonymous) @ default_frontend-0.11.0.js:1
> r @ default_frontend-0.11.0.js:13
> g.fetch @ default_frontend-0.11.0.js:1
> w.fetchCollection @ default_frontend-0.11.0.js:1
> I @ default_frontend-0.11.0.js:46
> (anonymous) @ default_frontend-0.11.0.js:13
> l.dispatch @ default_frontend-0.11.0.js:13
> dispatch @ default_frontend-0.11.0.js:13
> n.(anonymous function) @ default_frontend-0.11.0.js:13
> initSession @ learn_module-0.11.0.js:1
> updateRendererComponent @ default_frontend-0.11.0.js:46
> created @ default_frontend-0.11.0.js:46
> xt @ default_frontend-0.11.0.js:7
> e._init @ default_frontend-0.11.0.js:7
> a @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt @ default_frontend-0.11.0.js:7
> e @ default_frontend-0.11.0.js:7
> fn.$mount @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> C @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt.run @ default_frontend-0.11.0.js:7
> Nt @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> We @ default_frontend-0.11.0.js:7
> Promise.then (async)
> Ge @ default_frontend-0.11.0.js:7
> Ze @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.update @ default_frontend-0.11.0.js:7
> ue.notify @ default_frontend-0.11.0.js:7
> set @ default_frontend-0.11.0.js:7
> SET_STATE @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> l._withCommit @ default_frontend-0.11.0.js:13
> l.commit @ default_frontend-0.11.0.js:13
> commit @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> Promise.then (async)
> r.only @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> handler @ learn_module-0.11.0.js:1
> ri._hook @ default_frontend-0.11.0.js:218
> p @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> we @ default_frontend-0.11.0.js:218
> Ee.confirmTransition @ default_frontend-0.11.0.js:218
> Ee.transitionTo @ default_frontend-0.11.0.js:218
> t.push @ default_frontend-0.11.0.js:218
> De.push @ default_frontend-0.11.0.js:218
> v @ default_frontend-0.11.0.js:218
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> default_frontend-0.11.0.js:231 XHR finished loading: POST "http://192.168.1.100:8087/api/logger/contentsummarylog/?1546596786500=1546596786500".
> (anonymous) @ default_frontend-0.11.0.js:231
> (anonymous) @ default_frontend-0.11.0.js:389
> i @ default_frontend-0.11.0.js:389
> d.promise @ default_frontend-0.11.0.js:27
> f.promise @ default_frontend-0.11.0.js:65
> (anonymous) @ default_frontend-0.11.0.js:231
> a @ default_frontend-0.11.0.js:153
> (anonymous) @ default_frontend-0.11.0.js:26
> (anonymous) @ default_frontend-0.11.0.js:389
> I @ default_frontend-0.11.0.js:389
> _.when @ default_frontend-0.11.0.js:389
> O.run @ default_frontend-0.11.0.js:389
> e._drain @ default_frontend-0.11.0.js:388
> drain @ default_frontend-0.11.0.js:388
> e.observe.characterData @ default_frontend-0.11.0.js:52
> characterData (async)
> (anonymous) @ default_frontend-0.11.0.js:52
> e.run @ default_frontend-0.11.0.js:388
> e.enqueue @ default_frontend-0.11.0.js:388
> b.when @ default_frontend-0.11.0.js:389
> m.chain @ default_frontend-0.11.0.js:389
> i.then @ default_frontend-0.11.0.js:389
> d @ default_frontend-0.11.0.js:27
> f @ default_frontend-0.11.0.js:65
> e @ default_frontend-0.11.0.js:26
> t.default @ default_frontend-0.11.0.js:33
> w.client @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:1
> Promise.then (async)
> (anonymous) @ default_frontend-0.11.0.js:1
> r @ default_frontend-0.11.0.js:13
> v.save @ default_frontend-0.11.0.js:1
> w.saveModel @ default_frontend-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:46
> Promise.then (async)
> r.then @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:46
> I @ default_frontend-0.11.0.js:46
> (anonymous) @ default_frontend-0.11.0.js:13
> l.dispatch @ default_frontend-0.11.0.js:13
> dispatch @ default_frontend-0.11.0.js:13
> n.(anonymous function) @ default_frontend-0.11.0.js:13
> initSession @ learn_module-0.11.0.js:1
> updateRendererComponent @ default_frontend-0.11.0.js:46
> created @ default_frontend-0.11.0.js:46
> xt @ default_frontend-0.11.0.js:7
> e._init @ default_frontend-0.11.0.js:7
> a @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt @ default_frontend-0.11.0.js:7
> e @ default_frontend-0.11.0.js:7
> fn.$mount @ default_frontend-0.11.0.js:7
> init @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> d @ default_frontend-0.11.0.js:7
> f @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> C @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> e._update @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.get @ default_frontend-0.11.0.js:7
> Lt.run @ default_frontend-0.11.0.js:7
> Nt @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> We @ default_frontend-0.11.0.js:7
> Promise.then (async)
> Ge @ default_frontend-0.11.0.js:7
> Ze @ default_frontend-0.11.0.js:7
> (anonymous) @ default_frontend-0.11.0.js:7
> Lt.update @ default_frontend-0.11.0.js:7
> ue.notify @ default_frontend-0.11.0.js:7
> set @ default_frontend-0.11.0.js:7
> SET_STATE @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> (anonymous) @ default_frontend-0.11.0.js:13
> l._withCommit @ default_frontend-0.11.0.js:13
> l.commit @ default_frontend-0.11.0.js:13
> commit @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> (anonymous) @ default_frontend-0.11.0.js:13
> Promise.then (async)
> r.only @ default_frontend-0.11.0.js:13
> (anonymous) @ learn_module-0.11.0.js:1
> handler @ learn_module-0.11.0.js:1
> ri._hook @ default_frontend-0.11.0.js:218
> p @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> r @ default_frontend-0.11.0.js:218
> we @ default_frontend-0.11.0.js:218
> Ee.confirmTransition @ default_frontend-0.11.0.js:218
> Ee.transitionTo @ default_frontend-0.11.0.js:218
> t.push @ default_frontend-0.11.0.js:218
> De.push @ default_frontend-0.11.0.js:218
> v @ default_frontend-0.11.0.js:218
> t @ default_frontend-0.11.0.js:7
> t._withTask.i._withTask @ default_frontend-0.11.0.js:7
> default_frontend-0.11.0.js:33 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
>     at Object.request (default_frontend-0.11.0.js:33)
>     at Object.toggle (default_frontend-0.11.0.js:33)
>     at a.enterFullScreen (default_frontend-0.11.0.js:218)
>     at a.toggleFullscreen (default_frontend-0.11.0.js:218)
>     at click (html5_app_renderer_module-0.11.0.js:1)
>     at a.t (default_frontend-0.11.0.js:7)
>     at a.e.$emit (default_frontend-0.11.0.js:7)
>     at a.onClick (html5_app_renderer_module-0.11.0.js:1)
>     at t (default_frontend-0.11.0.js:7)
>     at HTMLButtonElement.t._withTask.i._withTask (default_frontend-0.11.0.js:7)

### Context
Kolibri version 0.11
Linux
Chromium and Vivaldi
-->

…

**Comment by ivanistheone** [comment]
I recently also observed a "can't go fullscreen in Chrome" bug for ePub renderer as well:

Here is a sample ePub on 0.11.0:
http://kolibridemo.learningequality.org/learn/#/topics/c/bb0ea84e42785c019f3be924b9d7e20b

If you click on the full screen button you get:

<img width="986" alt="screen shot 2019-01-04 at 11 43 02 pm" src="https://user-images.githubusercontent.com/163966/50720392-80889500-107a-11e9-882d-717c820add10.png">

and js stacktrace

```
Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.request (default_frontend-0.11.0.js:9)
    at Object.toggle (default_frontend-0.11.0.js:9)
    at a.enterFullScreen (default_frontend-0.11.0.js:24)
    at a.toggleFullscreen (default_frontend-0.11.0.js:24)
    at fullscreenButtonClicked (document_epub_render_module-0.11.0.js:15)
    at a.t (default_frontend-0.11.0.js:5)
    at a.e.$emit (default_frontend-0.11.0.js:5)
    at click (document_epub_render_module-0.11.0.js:15)
    at a.t (default_frontend-0.11.0.js:5)
    at a.e.$emit (default_frontend-0.11.0.js:5)
```



### Note  >>>>

full screen works fine in Firefox and Safari on the same page.

**Comment by jamalex** [comment]
+1 for being broken on epub on Chrome 71.0.3578.80
