### ISSUE TITLE
Coach tab & item opening trigger the user logout (dev branch)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4685]
### Observed behavior

When logged in as super-admin, opening Coach tab leads to logout:

![coach-logout](https://user-images.githubusercontent.com/1457929/50715293-f3930b00-107c-11e9-88b9-a7a17bf926ee.gif)

Try to login as coach user (both class and facility coaches) also leads to automatic logout after 2 seconds:

![coach-logout2](https://user-images.githubusercontent.com/1457929/50715355-348b1f80-107d-11e9-8745-0c4a074d3f9e.gif)

### User-facing consequences

Super-admin not able to use coach features, coaches not able to login.

### Errors and logs

Nothing discernible in the console or the terminal. 

### Context

- Latest develop branch
- Ubuntu 18.04

cc @rtibbles

**Comment by radinamatic** [comment]
Actually, the logout also happens as soon as _any_ user opens a content item:

![learner-logout](https://user-images.githubusercontent.com/1457929/50718996-4fb65900-1096-11e9-8480-8ae8d360c1bf.gif)

**Comment by rtibbles** [comment]
Curiouser and curiouser!

**Comment by radinamatic** [comment]
Yeah, just my luck... :roll_eyes:

**Comment by radinamatic** [comment]
And today when I restarted the devserver, the error has resolved itself... :confused: 

I did not update the repo, but I did create and new virtualenv.

**Comment by indirectlylit** [comment]
> the error has resolved itself

I haven't reproduced this. Closing, but please re-open if it happens again

**Comment by radinamatic** [comment]
Will do, haven't seen this since the new venv!

**Comment by radinamatic** [comment]
Really weird, saw this on develop today, but it also resolved by stopping the server and running `yarn run devserver` again... 😕
