### ISSUE TITLE
incorrect source string

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4699]
### Observed behavior

https://crowdin.com/translate/kolibri/1002/en-bn#70512

"Learners can only see active quizzes"

`LessonDetailEditor.statusDescription`

### Expected behavior

"Learners can only see active lessons"

### User-facing consequences

confusion over meaning

### Context

0.12

**Comment by radinamatic** [comment]
Excellent catch, I missed it myself... :woman_facepalming:
