### ISSUE TITLE
improve synchronization of content model schemas

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4702]
### Observed behavior

Currently, Kolibri Studio has a modified copy of the content models for generating backwards compatible content databases. Changes need to be propagated to that copy in order to allow for generation of databases with the changed schema.

### Expected behavior

We can instead achieve this by implementing abstract base models that are instantiated in both applications.

### User-facing consequences

currently there is a higher risk of models getting out of sync

### Context

0.12

**Comment by rtibbles** [comment]
This has been mostly resolved by using a minimally modified version of the base models in Studio, any additional syncing will happen by making Studio into a kolibri plugin.
