### ISSUE TITLE
Fixes to resource pages

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#4706]
### Observed behavior
Some outstanding issues with the current exercises page that we need to address:
- Severe lack of screen estate affording the user to interact with the exercise. The presence of top-nav/breadcrumbs/and previously the learn tabs all push down elements and components that correspond to the exercise question (including answer input areas and answer choice selections). 
- Reliance on including navigational elements ever-present on every page. This is valuable usability for the act and intention of navigation to/from various places (e.g. channels tab, import) but shouldn't be present in its current form within pages that stress primary purpose to be heads down focus and engagement (content pages). 
- Legibility of the page suffers. Text everywhere, lack of a clear direction

### Expected behavior and projected improvements
- More clean space to work with
- Standardize on the top-nav style (we already have this applied to lesson resource pages)
- Clear differentiation between "Question area" and "answer areas" (big)

### Design changes
- Top-nav swap
- Eliminate redundancy of title-ception (option 2 ideal)
- Maintain breadcrumb affordance via showing "location", e.g the name of parent topic. Or "From" 
- Eliminate current forms of breadcrumbs
- Add "In-progress" "Completed" labels near the appropriate icon

### Specs and mockup
![topnav comparisons](https://user-images.githubusercontent.com/25045166/50937859-78d64100-142a-11e9-8d13-df033d7cdda9.png)

**Comment by khangmach** [comment]
Updated the documentation using an easier iconography approach. Thanks for the suggestion @jonboiser 
![content page slice](https://user-images.githubusercontent.com/25045166/54151692-a32b8700-43f8-11e9-9529-5a511855ea07.png)

**Comment by jonboiser** [comment]
Another requirement is that if the user comes to the resource through "Recommended", or a subpage like "Popular", then the back arrow goes to that page.

**Comment by indirectlylit** [comment]
> ![image](https://user-images.githubusercontent.com/2367265/54640139-4c532c80-4a4c-11e9-9e02-42c91723ec42.png)

Note that we now have a standard KLabeledIcon component from recent work in coach reports, so we should leverage that and avoid adding a new special-case here
