### ISSUE TITLE
swap out a single question while creating an exam

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4708]
### Observed behavior
We are not able to randomize the single question while creating the exam. It is randomizing all the questions.

### Expected behavior
It must randomize selected question.

### Steps to reproduce
1. Create the exam and click on preview and randomize.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

**Comment by indirectlylit** [comment]
what do you mean by 'randomize a single question'?

**Comment by swapnil106111** [comment]
@indirectlylit Suppose teacher wants to create a exam with 5 questions. From 5 questions, 4 questions teacher wants to be in the exam but one question don't. In such case, randomize a single question is important.
