### ISSUE TITLE
Button name on tablet

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4714]
### Observed behavior
While using learn tab on tablet following things are happened on tablet:
1. CHECK button  shown as CHE...
2. NEXT button shown as NE.

Able to see expected names on Lenovo tab but not on swipe tab.

Lenovo tab model number : TAB3 7 ESSENTIAL
Swipe tab model number : W7

### Expected behavior
It must show whole name on every device.

### Steps to reproduce
1. Go to the learn tab and use on swipe tablet.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot

Swipe tablet:
![img_20190107_143723](https://user-images.githubusercontent.com/12776071/51016053-d38bac00-1594-11e9-840d-ed216325b9e3.jpg)

Lenovo tablet:
![img_20190111_113633](https://user-images.githubusercontent.com/12776071/51016179-56146b80-1595-11e9-8b87-754e98838c05.jpg)

**Comment by rtibbles** [comment]
Fixed in #5004
