### ISSUE TITLE
Change language feature for learner.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4715]
### Observed behavior
While doing signout on tablet there is change language option. Requesting to remove change language feature for learner account.
If learner change the language intentionally or accidently then teacher work will be increased to select expected language everytime.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

**Comment by rtibbles** [comment]
We are not planning to remove this, but we have made the device language a harder default to make this less of an issue.
