### ISSUE TITLE
Coach-facing content should not show up under "Recommended" for non-coaches

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#4717]
### Observed behavior

![image](https://user-images.githubusercontent.com/618416/51058559-0c7c4e80-159e-11e9-9b52-27cc07dd750f.png)

![peek 2019-01-11 12-41](https://user-images.githubusercontent.com/618416/51058655-5107ea00-159e-11e9-8381-780c28f0c2e2.gif)

### Expected behavior

The session above wasn't logged in, so "Recommended" shouldn't have included this coach-only content.

### User-facing consequences

Exposing content to learners unintentionally.

### Context

Kolibri 0.11.0

**Comment by indirectlylit** [comment]
interesting that the 'coach' icon doesn't appear on that card

**Comment by rtibbles** [comment]
We don't show coach content icons to non-coach users.
