### ISSUE TITLE
 $coreTextAnnotation is not defined

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4720]
### Observed behavior

while interacting with exercises

![image](https://user-images.githubusercontent.com/2367265/51062613-8542d100-15c5-11e9-9405-556087c2d203.png)

### Expected behavior

I still think it might be safest to define these globally

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Fine, you've convinced me.

**Comment by indirectlylit** [comment]
just until 0.12 - we can pull it out after

**Comment by rtibbles** [comment]
Any intuition on performance impact of adding them all as global mixins? (I assume the component only watches the reactive prop if it is referenced during render, so I am assuming it would not have an impact).

**Comment by indirectlylit** [comment]
Right - I think it only has an impact if a component defines a new reactive value which has the object as a dependency.

Perhaps a less heavy-handed strategy would be to create a `coreThemeMixin` which maps all the vuex color variables into the current component. This has the advantage of dumping all the variables in at once and perhaps avoiding some of these errors, but still being a bit more explicit about when they're used. However given how often the variables are used, I'd still lean towards the global.

**Comment by rtibbles** [comment]
Oh, except this error is caused by my missing the this, and linting not catching. Going to focus on getting our linting working properly.

**Comment by indirectlylit** [comment]
sounds good!
