### ISSUE TITLE
Not possible to 'complete' an HTML5 App

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4725]
### Observed behavior
In introducing Hashi, the 15s insta-points was removed from HTML5 apps. Now impossible to register any progress.

### Expected behavior
What should progress look like for an arbitrary HTML5 app?

### User-facing consequences
Confusion?

**Comment by rtibbles** [comment]
After extensive discussion, @khangmach @jtamiace and I fell upon 'completion after 5 minutes of total engagement'.

This will be the fallback behaviour for apps that are not able to engage with any future assessments API.

**Comment by indirectlylit** [comment]
but how many points?!??? 🍃

**Comment by rtibbles** [comment]
500 - just like everything else!
