### ISSUE TITLE
Learner exercise answer report UI not working on 0.11.0

### ISSUE THREAD

**Issue by JoseCrz** [learningequality/kolibri#4732]
### Observed behavior

Under the Coach dashboard when you enter the exercise answers report of a learner and try to see the answers given the UI stops working.

![bug2](https://user-images.githubusercontent.com/26424082/51155042-c80dde80-183b-11e9-8055-788426516fcf.gif)

### Expected behavior

To be able to select and see the answers given by the learner and go back to the previous view

### User-facing consequences

The coach is unable to see the answers of the learner and is unable to further interact with the app unless a specific URL in requested.

### Errors and logs

 Looks like there's no error log, not on the browser console nor the command line

<img width="535" alt="image" src="https://user-images.githubusercontent.com/26424082/51155959-0e187180-183f-11e9-8aab-605e0e1c9d90.png">

### Steps to reproduce

1.- Go to the Coach Dashboard.
2.- Select a Learner.
3.- Select a Channel.
4.- Select a Subject.
5.- Continue until you reach the resources of a specific topic.
6.- Select an activity to see the answers.
7.- Click any answer besides the one presented by default.
8.- Try to click a different answer or go back to the previous view

### Context

- Kolibri Version: 11.0

- Operating

System: macOS Sierra 10.12.6 (16G1710)

- Browsers: behavior is present on the following browsers:
Google Chrome 71.0.3578.98 (Official Build) (64 bits)
Safari 12.0.2 (12606.3.4.1.4)
Firefox 64.0 (64-bits)

**Comment by rtibbles** [comment]
Hi @JoseCrz thanks for the bug report! 

This has previously been reported in #4610 - and was fixed in #4688, which is now available in the 0.11.1 release!

Please try upgrading and you should find this issue fixed.
