### ISSUE TITLE
Language switcher vertical alignment

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4739]
### Observed behavior

Language switcher modal is half hidden under the top edge of the browser window.
Switcher modal is correctly aligned on the sign-in page.

![ubuntu 16 04 3 start running - oracle vm virtualbox_374](https://user-images.githubusercontent.com/1457929/51269016-b5bdad00-19c1-11e9-865f-75706be456be.png)

### Expected behavior

Language switcher should be fully visible.

### User-facing consequences

Inability to change to any language that is not visible in the modal.

### Errors and logs
- nothing visible

### Steps to reproduce

1. Sign in or start browsing as a guest.
2. Try changing the language.

### Context

 * Kolibri version: 0.12.0.alpha3
 * Operating system: Ubuntu 16.04
 * Browser: FF 64 & Chrome 71

**Comment by mrpau-richard** [comment]
The same issue with Safari 11.0.3

![screen shot 2019-01-17 at 2 00 36 pm](https://user-images.githubusercontent.com/8663934/51298680-6aa6a700-1a60-11e9-932d-0c6b935b6851.png)

**Comment by radinamatic** [comment]
Still extant on smaller screens: open the responsive view in either FF or Chrome, and the upper half of the modal cannot be accessed.

![2019-02-08_16-07-55](https://user-images.githubusercontent.com/1457929/52492583-641fd100-2bc1-11e9-80d3-7099ee45eb58.png)


![2019-02-08_16-48-06](https://user-images.githubusercontent.com/1457929/52492647-83b6f980-2bc1-11e9-9c7a-54f95682e38c.png)

**Comment by indirectlylit** [comment]
see also #4757

**Comment by rtibbles** [comment]
Fixed in #5035
