### ISSUE TITLE
exam creation breaks when clicking 'select all' on a large topic

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4740]
### Observed behavior

Just filing this is a note for later to investigate further. I'm currently experiencing this in our `coach-data` working branch. Haven't tested in `develop` yet.

Clicking 'select all' on KA Math when creating an exam does two things:

* browser freezes and CPU goes to 100% for a longer period than I've been willing to wait
* server reports a 'URI string too long' type error

I briefly looked at the request (but forget which endpoint) and it indeed had an array with thousands of items.

### Expected behavior

buttery smoothness

### User-facing consequences

:/

### Errors and logs

`414 Request-URI Too Large`

### Steps to reproduce

select-all in KA math

### Context

`coach-data` branch

**Comment by rtibbles** [comment]
Have replicated this. I have some ideas on how to deal with it, but won't be implemented today.
