### ISSUE TITLE
Import button showing while it's in a process of importing a new channel contents

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4751]
### Observed behavior
I can access the import button while it's in process of importing a new channel contents, this happened when I switch to a Kolibri tab and switch back. The behavior is when I import another contents of the channel the first import process will be cancelled.

### Expected behavior
Disable import button when there is still a process that import a channel contents.

### Errors and logs
![gif-temp](https://user-images.githubusercontent.com/8663934/51368836-110bae80-1b2c-11e9-87ca-784581489d17.gif)

### Steps to reproduce
* Log in as super admin
* Import a channel content
* While the import channel contents still in process switch to another Kolibri tab and switch back.
* The import channel will show.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.0a3
 * Operating system: Darwin-17.4.0-x86_64-i386-64bit
 * Browser: iOS Safari 11.0.3

**Comment by indirectlylit** [comment]
cc @ralphiee22

**Comment by mrpau-richard** [comment]
Fixed in #4772
