### ISSUE TITLE
Update new channel version not working

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4752]
### Observed behavior
The update channel button is not working after I updated the channel title at the Kolibri Studio.

### Errors and logs
![gif-temp](https://user-images.githubusercontent.com/8663934/51389231-9d3ac780-1b66-11e9-8c08-5a78a0b3d7f5.gif)

### Context
Tell us about your environment, including:
Kolibri version: 0.12.0a3
Operating system: Darwin-17.4.0-x86_64-i386-64bit
Browser: iOS Safari 11.0.3

**Comment by jonboiser** [comment]
I also saw this recently with a custom channel. I had installed Version 10 of it, and could not get Kolibri to download the newest  Version 12 even after pressing 'Update'

**Comment by radinamatic** [comment]
Possibly related to [this issue reported on Studio](https://github.com/learningequality/studio/issues/1112).
@jayoshih it might have been too soon for discussion about closing it... :confused:

**Comment by rtibbles** [comment]
The correlated issue has been closed on Studio by @radinamatic. Closing this one unless it recurs.
