### ISSUE TITLE
Deleting a user from facility, causes classmates to lose their group memberships

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4756]
### Observed behavior

1. I have a class that has students divided into groups
1. I remove one user from the server through Facility > Users menu
1. I go back to Coach > Class > Groups
1. All of the remaining students are now ungrouped

**Before**
![screen shot 2019-01-18 at 4 44 53 pm](https://user-images.githubusercontent.com/10248067/51419627-f3950f80-1b40-11e9-8193-e8edea155298.png)

**After deleting Albus**

![screen shot 2019-01-18 at 4 45 15 pm](https://user-images.githubusercontent.com/10248067/51419633-fd1e7780-1b40-11e9-9da7-d480a591328d.png)

### Expected behavior

Classmates of the deleted user keep their learnergroup memberships.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
That's a curious cascade - magical.

**Comment by rtibbles** [comment]
Fixed in #4773
