### ISSUE TITLE
No available Super admin filter at the user type dropdown list

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4761]
### Observed behavior
Currently the Super admin is not available at the user type filter.

### Expected behavior
Add Super admin at the list of user type filter.

### Errors and logs
![screen shot 2019-01-21 at 5 02 37 pm](https://user-images.githubusercontent.com/8663934/51463985-90ed7f00-1d9f-11e9-9901-4e6fdc349cf6.png)

Tell us about your environment, including:
* Kolibri version: 0.12.0a3
* Operating system: Darwin-17.4.0-x86_64-i386-64bit
* Browser: iOS Safari 11.0.3

**Comment by indirectlylit** [comment]
interesting idea - thanks

cc @jtamiace - think this is something we should do?

**Comment by Tlazypanda** [comment]
@indirectlylit is this issue available?

**Comment by jtamiace** [comment]
Adding that user to the filter makes sense to me. 

Note to self in thinking forward to the multi-facility experience - we'll need to decide how to display super admins who are not technically a member of that facility, but can still see it

**Comment by jonboiser** [comment]
@Tlazypanda Let's go ahead and add that "Super admins" filter, but keep the current behavior where the "Admin" filter shows both "Admins" and "Super admins". Thanks!

**Comment by indirectlylit** [comment]
thanks all

I think the label should be "Super admins", plural
