### ISSUE TITLE
 associate current value of data_model_version with model rather than serializer

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4765]
### Observed behavior

`data_model_version` is set by the exam serializer

### Expected behavior

set in the model instead

### User-facing consequences

none

### Context

0.12

**Comment by rtibbles** [comment]
This appears to already be the case.

**Comment by indirectlylit** [comment]
not quite - this was based on your comment at https://github.com/learningequality/kolibri/pull/4667#discussion_r247591219

**Comment by rtibbles** [comment]
Oh, gotcha.

**Comment by indirectlylit** [comment]
fixed by @jonboiser in #5431 (https://github.com/learningequality/kolibri/commit/f1b9a0fefd3e2e0b808b53b0e3e16e98b5f7326f)
