### ISSUE TITLE
Burmese fonts missing some characters

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#4771]
### Observed behavior

<img width="792" alt="screen shot 2019-01-21 at 5 56 11 pm" src="https://user-images.githubusercontent.com/163966/51552860-8aaedf80-1e3f-11e9-99c0-fa498a88bfdb.png">

<img width="915" alt="screen shot 2019-01-22 at 12 13 12 pm" src="https://user-images.githubusercontent.com/163966/51552885-98fcfb80-1e3f-11e9-91f3-9319425055fc.png">

### Expected behavior

Show all characters.

### User-facing consequences

Burmese speakers will have difficulty viewing subtitles.

### Errors and logs

Nothing in console.

### Steps to reproduce

1. Go to http://kolibridemo.learningequality.org/learn/#/topics/c/465fabc8b95f58b5a3158343c12122e7
2. Choose subtitles  `ဗမာစာ` = Burmese 
3. Watch a few minutes of video an observe missing-character boxes in subs

### Context
Tell us about your environment, including:
 * Kolibri version: 0.11.1
 * Operating system: Mac
 * Browser: tried both Chrome and Firefox

### Comments

Note this could be a content issue (bad characters or encoding in the subtitles file), because the Burmese subs on this video show up fine:
https://kolibridemo.learningequality.org/learn/#/topics/c/8c35fafb297e5207a8bab4b90211fb88

**Comment by indirectlylit** [comment]
@ivanistheone would you mind posting the subtitles file here?

**Comment by ivanistheone** [comment]
It's this one: http://kolibridemo.learningequality.org/content/storage/c/d/cd48244d855a14a2f7059a3a7c585c8c.vtt

**Comment by jonboiser** [comment]
There doesn't look like there's any more missing-glyph "tofu" on the subtitles, But there do look like some problems with placing the diacritics (see the dotted circles):

**from the same KA video**
![image](https://user-images.githubusercontent.com/10248067/107410277-ec435480-6ac1-11eb-902e-d83f35e3aa19.png)

The same problems appear when simply viewing the VTT file in a text editor. This is the VTT file with Noto Myanmar, which have the same diacritics issues.

![image](https://user-images.githubusercontent.com/10248067/107410758-90c59680-6ac2-11eb-8ccc-af19291331b1.png)

This is the file with Myanmar MN (apple system font), which has the same issues. I'm assuming that the box-with-plus symbol is just an alternate form of the below-letter "+" diacritic in noto.

![image](https://user-images.githubusercontent.com/10248067/107410840-a89d1a80-6ac2-11eb-8e2e-7dd5171ba08c.png).

This is most likely an issue with how the subtitles were originally transcribed. 

```
ဒီအရာဝတၳဳေလးကို ေလထဲကို ေဒါင္လိုက္ေျမွာက္လိုက္ရင္

```
