### ISSUE TITLE
move Sentry clients to an external plugin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4775]
### Observed behavior

In #4774 we're adding Sentry clients so we can do error tracking. However, most users don't need or want these since we're using it for internal error reporting on our own servers.

We could make this into an external plugin; however this isn't currently compatible with our `pex` format, which is how we deploy our demo servers.

### Expected behavior

These should be contained in an external plugin that we'll install as-needed. This can occur when either:

1. pex formats support Python packages that are installed to the system
2. we migrate our demo server environments away from pex files

### User-facing consequences

A little extra bloat in our distributions

### Errors and logs

lots of them, hopefully

### Steps to reproduce

See [instructions on using Sentry](https://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#collecting-client-and-server-errors-using-sentry)

### Context

0.12

**Comment by aronasorman** [comment]
When you do this, can you also add support for [sentry environments](https://docs.sentry.io/enriching-error-data/environments/?platform=python)?

**Comment by indirectlylit** [comment]
yeah, good idea.

I was thinking about hooking into the `nutritionfacts` pingback data and sending all of that, including e.g. run mode, channel lists, etc.

**Comment by indirectlylit** [comment]
this has caused additional issues on ubuntu 14.04 because sentry seems to include some python 3.7+ files:

> ![image](https://user-images.githubusercontent.com/2367265/54968211-1a076a80-4f37-11e9-90ad-b75ba8cbcd7c.png)

@jredrejo is manually removing the offending (and unused) files in https://github.com/learningequality/kolibri-installer-debian/pull/67 .. however solving this issue would be a cleaner long-term solution
