### ISSUE TITLE
regression - setup wizard still has a blue toolbar

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4781]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/51646884-531f6080-1f2f-11e9-92d6-a36d82cf8ab3.png)

### Expected behavior

purple

### Context

0.12

**Comment by radinamatic** [comment]
Ugh, I thought I reported this last week... Noted it in the integration testing spreadsheet, but didn't file the issue 🤦‍♀️

**Comment by rtibbles** [comment]
I also assumed that this would have been fixed by other fixes. Will fix alongside other styling issues.
