### ISSUE TITLE
Exercises missing when importing from any other peer apart from studio

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#4790]
### Observed behavior

Trying to import a channel via peer sync i.e. ```Local network or internet``` source, all other content but exercises are being imported. Importing from studio or a thumbdrive then all of the exercises copy fine.

Tried with a few other channels as well which have exercises (For e.g. ```CK-12 > Math > Elementary Math > Grade 1 > Addition and Subtraction facts to 10```). So it is not just a KA issue.

Rather it seems that the exercises created using Perseus framework are importing but not the rest.

### Expected behavior

All exercises part of the topics imported should have been imported but they weren't. 

### User-facing consequences

Confusing results for all.

### Errors and logs

[snippet_kolibri.log](https://github.com/learningequality/kolibri/files/2795923/snippet_kolibri.log)

### Steps to reproduce

Select to import all contents from any of these channel topics via peer sync i.e. ```Local network or internet``` wherein the source has been seeded initially from the studio -
- ```Khan Academy (English) > Math >1st grade > Place value > Numbers 0 to 120```
- ```CK-12 > Math > Elementary Math > Grade 1 > Addition and Subtraction facts to 10```

After import match with source if all the exercises have been imported.

### Context

Kolibri 0.11.1 - Source on Linux, Firefox 64.0.2
Kolibri 0.11.1 - Destination on Windows 10, Firefox 64.0.2

**Comment by rtibbles** [comment]
Thanks for the report, this seems very problematic!

**Comment by rtibbles** [comment]
One thing I note in the log file is this line:
`ERROR 2019-01-25 16:52:06,943 importcontent An error occurred during content import: File http://192.168.4.34:8080/content/storage/7/3/735d4c10bac106a8a4196f8618207f6b.perseus is corrupted.`
Where an exercise file appears to be corrupted, wondering if this might be causing the issue (or perhaps we are wrongly flagging exercise files as corrupted).

**Comment by intelliant01** [comment]
@rtibbles I had also noticed this. It is possible that this message is in error as I found most of the Perseus based exercises imported correctly but there is no way I can be conclusive on this.

**Comment by rtibbles** [comment]
It's possible that the files are being transferred, but because of the error we might not be then making them as imported.
