### ISSUE TITLE
including channel, topic, or content type in search makes results worse

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4796]
### Observed behavior

searching for `ck-12 addition overview` gives mostly irrelevant results from KA French, while searching for `addition overview` works fine:

| with channel | without channel |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/51776164-f8ac0e80-20ac-11e9-836b-68d83fcabc2b.png) | ![image](https://user-images.githubusercontent.com/2367265/51776225-285b1680-20ad-11e9-91d9-3000c0d7e0ad.png)  |

We've also [seen examples](https://github.com/learningequality/clearinghouse/issues/297) of users typing words like 'video' or 'book' into the search bar as a way to filter by type.

### Expected behavior

Specifying topic, channel, and type information information should help and not hurt search results

### User-facing consequences

reasonable searches return unreasonable results

### Steps to reproduce

Import a few channels and try searching for items within a channel

### Context

0.12

**Comment by rtibbles** [comment]
Going to count this as fixed with the new search filters in 0.15.x
