### ISSUE TITLE
kolibri command not working properly

### ISSUE THREAD

**Issue by 66eli77** [learningequality/kolibri#48]
"kolibri manage dumpdata content --exclude=contenttypes" won't work, 
as well as "kolibri manage dumpdata -- content --exclude=contenttypes" 
and "kolibri manage dumpdata -- --exclude=contenttypes content"

**Comment by MCGallaspy** [comment]
Fixed via https://github.com/learningequality/kolibri/commit/c745f6abe699251a877245ec19ae7b417fd97718
