### ISSUE TITLE
Can't identify the subtitle language name at the download content list

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4806]
### Observed behavior
The video subtitles display the same file name at the download content list. I can't identify which one I need unless I download and open each subtitle files.

### Expected behavior
The file name of the downloadable subtitles should be the language inside in it.

### Errors and logs
![screen shot 2019-01-28 at 5 25 05 pm](https://user-images.githubusercontent.com/8663934/51828593-dcb3a180-2326-11e9-91f5-7925dc12bbe7.png)

### Steps to reproduce
 * Import the `Touchable Earth (en)` channel
 * Import a video with  multiple subtitles

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.0a3
 * Operating system:
 * Browser: iOS Safari 11.0.3

**Comment by indirectlylit** [comment]
looks like we need to expose the language, which should be a property of the file already.

from @ivanistheone 

> maybe something like
> 
> `if file.preset === "subtitle" {and file.lang to the label }`
>
> here
> https://github.com/learningequality/kolibri/blob/cf2b9b52b25fb9d774c8bd6d7102a15a218955e4/kolibri/core/assets/src/views/ContentRenderer/DownloadButton.vue#L32


from @jayoshih 

> subtitles will all have the same format preset (Subtitle), which seems to be the one getting used here. On Studio, we have a `multi_language` field on the presets to determine whether to show the language or the preset name 
>
>  https://github.com/learningequality/studio/blob/develop/contentcuration/contentcuration/models.py#L1054
>
> Since the preset is just a CharField on Kolibri, that information gets lost
