### ISSUE TITLE
Code of Conduct has gone missing

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4809]
### Observed behavior

I can't find the code of conduct presently. Not sure what happened. It's usually mentioned on the right side when reporting issues, like this:

![image](https://user-images.githubusercontent.com/374612/51860722-b4ce3900-233a-11e9-8b33-4566e58c8727.png)

It also went missing in the docs:

![image](https://user-images.githubusercontent.com/374612/51860756-c6174580-233a-11e9-8e8f-c3b77a1feba7.png)

### Expected behavior

We include our work here:

![image](https://user-images.githubusercontent.com/374612/51860825-ee06a900-233a-11e9-886c-fcadd7e426dd.png)

The Code of Conduct is still available here:

https://github.com/learningequality/kolibri/blob/develop/CODE_OF_CONDUCT.rst

### User-facing consequences

Seems obvious. We might also have external links to this that break.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by indirectlylit** [comment]
removed ['critical' label](https://kolibri-dev.readthedocs.io/en/develop/development_workflow.html#priority) since it's not a blocker for release
