### ISSUE TITLE
Kolibri won't start after importing content

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#4810]
### Observed behavior
Forum post: 
"I installed Kolibri version 0.11.0 on my system (windows 8) which is to serve as a server. the installation went well and Kolibri was working alright. However, I realized that after I downloaded content from a channel, Kolibri has not been able to run again on the same system. what I get is an endless “server is starting…please wait” message and the browser never launches the application.

I have installed the same Kolibri version 0.11.0 file on two other systems (windows 7) but I get error messages and it doesn’t load /run on the 2 systems."

### Errors and logs

Relevant logs from:
 I was e-mailed a copy of the kolibri log but am unsure how to put it onto here - if I email it to someone can they add it?

### Context

Tell us about your environment, including:
 * 0.11
 * Windows 8.1
 * Chrome

![image](https://user-images.githubusercontent.com/22602993/51864424-bc2d1c80-2311-11e9-98e6-7b9d1576386a.png)

**Comment by mrpau-richard** [comment]
> I was e-mailed a copy of the kolibri log but am unsure how to put it onto here - if I email it to someone can they add it?

@lauradanforth you can attach the Kolibri log file here or send it to me at richard@mrpau.com
 .

**Comment by mrpau-richard** [comment]
Here's the [Kolibri log](https://github.com/learningequality/kolibri/files/2810869/kolibri.log) file I received from @lauradanforth 

I see on the log file is that the Kolibri port `8080` is occupied at the last line. There is two options to resolve this.

Option 1: Follow the steps to run the Kolibri server from a different port. https://kolibri.readthedocs.io/en/latest/manage.html?highlight=http_ports#run-kolibri-from-a-different-port
       

Option 2: Kill the process that's using the port `8080` at the system and start the Kolibri server again.
https://stackoverflow.com/questions/39632667/how-to-kill-the-process-currently-using-a-port-on-localhost-in-windows/39633428#39633428

**Comment by rtibbles** [comment]
I think this was an issue with the previous polling behaviour of the Windows installer. Closing this unless we receive more contemporary reports.
