### ISSUE TITLE
'help needed' is not currently being reported by the class_summary_api for content

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4817]
### Observed behavior

Haven't implemented yet:

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/class_summary_api.py#L27-L34

### Expected behavior

This query runs fairly often, so we need to be careful about performance. Currently 'needs help' would require a join with the attempt logs, which would be run for every single content item in every lesson in the class.

I'm thinking it would be preferable to add a `help_needed` field to the summary log to make this cheaper. The basic idea would be to update the `help_needed` flag at the same time as notifications are generated.

### User-facing consequences

currently 'needs help' is not reported in our reports

### Context

0.12

----

cc @jredrejo @rtibbles I could use a little help with this if either of you have time

**Comment by rtibbles** [comment]
It was my understanding that needs help was being implemented as a notification? Not as an additional field on the summary log, so that it could be contextualized to a lesson if needed?

**Comment by rtibbles** [comment]
Will take this on!

**Comment by jredrejo** [comment]
@rtibbles 
> It was my understanding that needs help was being implemented as a notification? Not as an additional field on the summary log, so that it could be contextualized to a lesson if needed?

You are right: 
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/notifications/api.py#L273-L291

do you want me to add this to the summarylog or are you doing it
