### ISSUE TITLE
`not a valid content storage filename` 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4818]
### Observed behavior

No apparent user facing error, but this `not a valid content storage filename` error appears in the Terminal for both `fonts` and `img`.

Related to #3874?

### Expected behavior

No errors in Terminal.

### User-facing consequences

Nothing apparent.

### Errors and logs

![workspace 1_008](https://user-images.githubusercontent.com/1457929/51876217-c249ea00-235f-11e9-92a9-43f43b7207e6.png)

![workspace 1_006](https://user-images.githubusercontent.com/1457929/51876242-dd1c5e80-235f-11e9-8e98-b262487b0b02.png)

### Steps to reproduce & Context

Encountered [during testing](https://github.com/learningequality/kolibri/pull/4794#issuecomment-458315959) with Browserstack simulator of Safari on iPad Air 2 with iOS 9.3.

**Comment by rtibbles** [comment]
Fixed in #5003
