### ISSUE TITLE
regression: focus outline styling displays when clicking

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4822]
### Observed behavior

the styles now appear when you click - sometimes briefly, and sometimes permanently:

![image](https://user-images.githubusercontent.com/2367265/51889336-219efe80-234e-11e9-8060-7867f058521f.png)

### Expected behavior

Outlines should only show when keyboard-tabbing. There is a mechanism in `body` like `modality="keyboard"` or something similar. I don't know offhand which library is providing it for us, but it's supposed to apply `outline: none` until the user starts keyboard-navigating.

### User-facing consequences

helpful outline styling for keyboard users is unhelpful and unattractive for mouse and touchscreen users

### Steps to reproduce

click around the app and notice lots of new outlines appearing

### Context

see https://github.com/learningequality/kolibri/pull/4802/files

**Comment by indirectlylit** [comment]
some clues perhaps:

> ![image](https://user-images.githubusercontent.com/2367265/51929307-c05a4800-23ac-11e9-9842-e385a8a57335.png)

**Comment by indirectlylit** [comment]
one thing that's a little tricky is the `modality` switches based on whether the dev tools have focus or not :)

**Comment by jonboiser** [comment]
These styles are coming from the theming in `$coreOutline`. Where should these (not) be applied?

**Comment by indirectlylit** [comment]
The styling is being correctly applied everywhere.

However, when `body:not([modality=keyboard])`, they should be disabled with `outline: none` as highlighted above. This does not appear to be happening anymore.

I believe the cause might be that I've increased the specificity of the outlines (due to applying theme colors with JS), which is causing them to not be overwritten as expected. Perhaps this can be addressed by setting the `outline: none` behavior in the same way as `$coreOutline`? not sure offhand
