### ISSUE TITLE
side nav and app bar issues on iOS

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4825]
### Observed behavior

* app bar becomes detached while scrolling (see #2279, #4612)
* clicking hamburger icon doesn't work

> ![image](https://user-images.githubusercontent.com/2367265/51923230-643cf700-239f-11e9-9a05-7662dcd11123.png)

### Expected behavior

* side nav should be accessible and app bar 

### User-facing consequences

cannot use app

### Steps to reproduce

load in iOS, click and scroll

This can be reproduced in browserstack on iOS, but only using http://kolibribeta.learningequality.org (not localhost - see #4826)

### Context

0.12

**Comment by jonboiser** [comment]
The bar moves to the left when the scrolling changes position from fixed to absolute during the scroll. This probably happens because the page is usually bigger than the viewport.

On the profile page, where the main area isn't wider than the viewport, I don't see it move.

**Comment by jonboiser** [comment]
As for the hamburger button not working, I think it's the 'scrolling-pane' class interfering with the Side Nav appearing. In browserstack, if you remove the 'scrolling-pane' class from the main div, side-nav appears when you click the hamburger.

**Comment by jonboiser** [comment]
On Browserstack Chrome, clicking the search magnifying glass button doesn't work either.

**Comment by jonboiser** [comment]
Removing the `-webkit-overflow-scrolling: touch; // iOS momentum scrolling` rule from `.scrolling-pane` seems to fix it.

**Comment by indirectlylit** [comment]
okay, let's do that then and re-open #2279

**Comment by indirectlylit** [comment]
fixed when #5100 is merged
