### ISSUE TITLE
Add write-to-disk watch mode for kolibri tools to allow single origin dev testing.

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4826]
### Observed behavior

This appears to be due to a browserstack limitation: https://www.browserstack.com/question/758

As a workaround, http://kolibribeta.learningequality.org works fine

Browserstack reports:

> ![image](https://user-images.githubusercontent.com/2367265/51923961-f5609d80-23a0-11e9-9f66-2e02c0b4ba25.png)

We see: 

> ![image](https://user-images.githubusercontent.com/2367265/51923977-001b3280-23a1-11e9-9353-912eef83a207.png)

### Expected behavior

Kolibri should load

### User-facing consequences

unable to use on iOS

### Errors and logs

from Browserstack console: 

> ![image](https://user-images.githubusercontent.com/2367265/51924019-1aeda700-23a1-11e9-925c-e36c080fb9fe.png)

### Steps to reproduce

load kolibri on safari browserstack:

> ![image](https://user-images.githubusercontent.com/2367265/51924082-3c4e9300-23a1-11e9-9592-3792f7006cec.png)

Note that you need to enter your local network IP address, _not_ localhost on iOS. Or just use http://kolibribeta.learningequality.org

### Context

#4589 looks related

k0.12

browserstack device info:

> ![image](https://user-images.githubusercontent.com/2367265/51924041-2640d280-23a1-11e9-86ef-fdda2a04d168.png)

**Comment by jonboiser** [comment]
I just tried this out, and it still seems to be an issue for running the webpack devserver. However, the workaround we've been using is to just rebuild the app manually and run the django webserver, using these two steps

```
yarn run build
kolibri manage --debug runserver -- 0.0.0.0:8000
# Kolibri is accessible at bs-local.com:8000 on browserstack iOS emulators
```

**Comment by rtibbles** [comment]
One other way around it would be to build in watch mode, but write to disk (but only in this circumstance). This would be a bit slower than the regular watch mode, but quicker than doing a full build each time.

**Comment by jonboiser** [comment]
What's the command for running in watch mode?

**Comment by rtibbles** [comment]
We'd have to expose an extra flag on the kolibri-tools build CLI to enable this I think, one that just writes the files to disk instead of using the webpack-dev-server.

**Comment by rtibbles** [comment]
(webpack dev server is the more customisable version of webpack's watch mode)

**Comment by rtibbles** [comment]
This should be implemented by adding a --write-to-disk flag to `build` command: https://github.com/learningequality/kolibri/blob/release-v0.16.x/packages/kolibri-tools/lib/cli.js#L201

that only has an effect when running in `dev` mode. This would skip using the webpack devserver, and would instead write to disk, but still using watch mode.

When using this mode, it should also add a console.warning to tell the user that frequent changes in this mode may fill up their developer machine with lots of different built files.

**Comment by thesujai** [comment]
May i have this assigned?

**Comment by thesujai** [comment]
I have to run the `runWebpackBuild` with ,devserver cache and hot as false right in --write-to-disk option?

**Comment by rtibbles** [comment]
Yes - hot reloading requires the webpack devserver, which this would not be using. I will assign you.
