### ISSUE TITLE
confusing learner flow through quiz

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4834]
### Observed behavior

In this situation, there are 20 questions but only 7 are visible and there is no visible scrollbar:

> ![image](https://user-images.githubusercontent.com/2367265/51936399-f43d6980-23bc-11e9-952a-fc3ea73e8b99.png)

from @laurenlichtman:

> I’m on question 6 but the number of questions didn’t scroll on the right so it was unclear that there was more than 5 questions (besides that it says 5 out of 15 questions). I didn’t realize that I would need to scroll if I wanted to jump around the questions 

from @micahscopes, slightly related:

> Micah almost clicked “submit quiz” after the first question

### Expected behavior

quiz-taking process should be totally fool-proof

### User-facing consequences

learners may do worse on quizzes than they would have otherwise

### Steps to reproduce

take a quiz with 15 or 20 items in it

### Context

0.12

**Comment by khangmach** [comment]
Without redesigning this entire interface (WIP/future milestone), simplest solution seems to be to just make the question list scrollbar visible upon page load.

**Comment by laurenlichtman** [comment]
@khangmach I think that sounds like a really good solution!

**Comment by indirectlylit** [comment]
this works for desktop, but tablets don't show a scrollbar until you start scrolling

**Comment by rtibbles** [comment]
One thing I have implemented in the detail reports is to automatically scroll the side nav bar down as you click through (so that the item you are on will always be put as close to the middle of the side nav bar as possible). I think this would at least help to always show there are more questions to be completed.

**Comment by rtibbles** [comment]
![scroll-side-nav](https://user-images.githubusercontent.com/1680573/52240989-644d6300-2887-11e9-9d8c-627f9c7344a7.gif)

**Comment by indirectlylit** [comment]
I like that a lot

The sudden transition and the fact that all the questions are named so similarly makes it a little confusing though. It almost looks as though you clicked the bottom item, but the item two rows up got selected?

**Comment by indirectlylit** [comment]
nice clap BTW :)

**Comment by rtibbles** [comment]
Yeah - should probably update this to use the Element `scrollTo` method, and set `smooth` on the scrolling behaviour.
