### ISSUE TITLE
add handling for 50* errors in API calls

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4856]
### Observed behavior

We've been getting [many reports in Sentry](https://sentry.io/learningequality/kolibri-frontend/issues/861530473) like

> ![image](https://user-images.githubusercontent.com/2367265/52094290-6c4d9000-2573-11e9-879b-1e71db3f8315.png)

### Expected behavior

If I'm interpreting this correctly, it appears that the API responded with a 502 - possibly from CloudFlare while the demo servers were being restarted?

Kolibri should have better handling of `50*` errors, perhaps by logging them and then going into the 'disconnected' mode?

### User-facing consequences

unsure

### Errors and logs

see above

### Steps to reproduce

I haven't tried this, but my guess is that connecting to a demo server like `kolibribeta` and then restarting the demo server down will trigger this

### Context

k 0.12.0 alpha 7

**Comment by rtibbles** [comment]
We already log most 50* errors that are indicative of some sort of disconnection state and then fall into disconnection mode, see here:
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/core-app/client.js#L54
and here for the list of error codes that we handle like this:
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/disconnectionErrorCodes.js#L1

However, catching these errors in the interceptors would mean that the processes that created them would think that the request had successfully completed, so they are still thrown.

**Comment by rtibbles** [comment]
The fix needed for this issue is to add error handling when the fetch is made. In the case for this particular API endpoint, the lack of a catch and error handling here is the issue: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/modules/coachNotifications/index.js#L67

**Comment by indirectlylit** [comment]
Alternatively, maybe it's better to leave them uncaught and continue to receive sentry notifications?
