### ISSUE TITLE
users should not be able to get 1000% on an exam, unfortunately

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4857]
### Observed behavior

reported by @jtamiace re: @radinamatic's apparent good luck:

![image](https://user-images.githubusercontent.com/2367265/52095361-812c2280-2577-11e9-86d6-8f6cff4e0f5b.png)

### Expected behavior

exams are scored between 0 and 100

### User-facing consequences

????

### Errors and logs

unknown

### Steps to reproduce

see http://kolibribeta.learningequality.org/coach/#/fa4cbfeda32c0c0fbf1832fc1ddd10c3/reports/learners

### Context

k 0.12.0 alpha 7

**Comment by jtamiace** [comment]
And average quiz score of 550% here
http://kolibribeta.learningequality.org/coach/#/fa4cbfeda32c0c0fbf1832fc1ddd10c3/reports/quizzes

<img width="962" alt="screen shot 2019-01-31 at 4 51 35 pm" src="https://user-images.githubusercontent.com/6668144/52095607-8178ed80-2578-11e9-8af0-9d61193acd4a.png">

**Comment by jamalex** [comment]
I can take a look at this -- at least as far as diagnosing what's going on behind the scenes in the DB/API, to start with.

**Comment by jamalex** [comment]
It seems the backend is returning "num_correct", and the frontend is interpreting it as a percentage correct.

The second entry here is for Radina's account:

![image](https://user-images.githubusercontent.com/618416/52152155-37504480-262a-11e9-837d-a0e6ee13f970.png)

A parallel anomaly in the data is that there are actually 11 correct attemptlogs for her for that exam, but two have the same `item`:

```
In [27]: el.attemptlogs.filter(correct=True).values_list('item').distinct().count()
Out[27]: 10

In [28]: el.attemptlogs.filter(correct=True).values_list('item').count()
Out[28]: 11
```

**Comment by jamalex** [comment]
```
In [47]: [(a.item, a.completion_timestamp.strftime("%H:%M:%S")) for a in el.attemptlogs.filter(correct=True).order_by('completion_timestamp')]
Out[47]: 
[(u'a5f508eb2ba05d429812dc43b577ef03', '13:43:01'),
 (u'8358fbbd0a285e9d99da558094eabd4c', '13:43:13'),
 (u'84f8e275aec652bf8a418d133e422f7f', '13:43:25'),
 (u'fc60ecb9f83f505fa31e734e517e6523', '13:43:58'),
 (u'4dd2526065ee572998a06b1fdae9cb4b', '13:44:04'),
 (u'50065107c7a0581e9bb30911ba6cc379', '13:44:10'),
 (u'642e2e18170055d2b44b0e408038176c', '13:44:29'),
 (u'6ef7996754de54ad92b660d06436976c', '13:44:41'),
 (u'9e54ffbf7138534982c617e52d5907bb', '13:44:46'),
 (u'cce3659096295edca9aaeff623fa4a50', '13:44:51'),
 (u'cce3659096295edca9aaeff623fa4a50', '13:44:56')]
```
(so the two attemptlogs for the same question happened at the end, 5 seconds apart)

**Comment by jamalex** [comment]
From Slack discussion, we determined that the client-side needs to use `examMap[status.exam_id].question_count` instead of `examMap[status.exam_id].question_sources.length` at https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/modules/classSummary/index.js#L198

**Comment by jamalex** [comment]
Regarding the second issue (duplicate logs), there seem to be 3 cases of it in the database:
```
In [56]: ExamAttemptLog.objects.values_list("examlog_id", "item").count()
Out[56]: 249

In [57]: ExamAttemptLog.objects.values_list("examlog_id", "item").distinct().count()
Out[57]: 246
```

**Comment by rtibbles** [comment]
Is it possible that item ids could be duplicated across exercises? Could you perhaps double check this with `content_id` also?

**Comment by rtibbles** [comment]
Seems unlikely, but would like to be sure!

**Comment by jamalex** [comment]
It's all from Radina's interactions with that one exam:

```
[(u'a5f508eb2ba05d429812dc43b577ef03', '13:43:01'),
 (u'8358fbbd0a285e9d99da558094eabd4c', '13:43:13'),
 (u'8358fbbd0a285e9d99da558094eabd4c', '13:43:13'),
 (u'84f8e275aec652bf8a418d133e422f7f', '13:43:25'),
 (u'84f8e275aec652bf8a418d133e422f7f', '13:43:25'),
 (u'06bb1d1bdd6250c4ad4912c558801139', '13:43:46'),
 (u'fc60ecb9f83f505fa31e734e517e6523', '13:43:58'),
 (u'4dd2526065ee572998a06b1fdae9cb4b', '13:44:04'),
 (u'50065107c7a0581e9bb30911ba6cc379', '13:44:10'),
 (u'beb5eae9491c564fb6bc5b9c1421d085', '13:44:19'),
 (u'642e2e18170055d2b44b0e408038176c', '13:44:29'),
 (u'6ef7996754de54ad92b660d06436976c', '13:44:41'),
 (u'9e54ffbf7138534982c617e52d5907bb', '13:44:46'),
 (u'cce3659096295edca9aaeff623fa4a50', '13:44:51'),
 (u'cce3659096295edca9aaeff623fa4a50', '13:44:56')]
```

**Comment by jamalex** [comment]
Ah, yeah, will check

**Comment by jamalex** [comment]
Another issue, unless I'm missing something, is that we seem to be anchoring to the PK (`node_id`) of an exercise, rather than the `content_id`. I remember discussing how this could be brittle, especially with cheffed channels.

```
In [67]: e.question_sources
Out[67]: 
[{u'exercise_id': u'b2097b29acbe4349924ff4510c5f8777',
  u'number_of_questions': 12,
  u'title': u'Count with small numbers'}]

In [71]: ContentNode.objects.get(content_id="b2097b29acbe4349924ff4510c5f8777")
DoesNotExist: ContentNode matching query does not exist.

In [72]: ContentNode.objects.get(id="b2097b29acbe4349924ff4510c5f8777")
Out[72]: <ContentNode: Count with small numbers>
```

**Comment by jamalex** [comment]
To @rtibbles' question above: they're all from the same exercise. The exercise has 20 assessments, all with unique ids.

**Comment by rtibbles** [comment]
Yeah, thats a misleading field name on the ExamAttemptLog. In the case of exams in particular, where the assessment content is abstracted from the metadata `content_id` _could_ work, but I am hesistant to suggest we make that shift, when, e.g. the same exercise in different languages in KA is currently published with the same content_id - I can imagine that being very confusing for a user taking an exam.

**Comment by jamalex** [comment]
Since there's only one case of it, is it possible @radinamatic was doing something like interacting with the same exam in multiple tabs?

**Comment by radinamatic** [comment]
> interacting with the same exam in multiple tabs

Can't recall offhand, but I am a tab junkie, so cannot entirely exclude the possibility 😊

**Comment by radinamatic** [comment]
I gather that's something I should steer away in future testing?

**Comment by indirectlylit** [comment]
> I gather that's something I should steer away in future testing?

never steer away from anything in testing :)

**Comment by radinamatic** [comment]
Gotta love a job where it actually pays out to be "naughty" and step out of line now and then... 😎

**Comment by jamalex** [comment]
![image](https://user-images.githubusercontent.com/618416/52156665-712b4600-263e-11e9-8be3-fccf9a4f02d5.png)

**Comment by indirectlylit** [comment]
for posterity:

We identified that the issue was because older exams are represented differently, and the logic was assuming the newer representation when calculating progress.

see https://github.com/learningequality/kolibri/pull/4667
