### ISSUE TITLE
Quiz in indeterminate state in the UI

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#4860]
### Observed behavior
When editing details from the Quiz reports page, when trying to active a previously inactive quiz, the UI seems to indicate that the quiz is now both active and inactive.

![image](https://user-images.githubusercontent.com/1680573/52097258-2dbdd280-257f-11e9-9f08-bc124599fa71.png)

### Expected behavior
Quiz should be in a determinate state, and be thus represented in the UI.

### User-facing consequences
Confusion, alarm, quantum theorists.

### Steps to reproduce
Create a quiz.
Do not activate it.
Go to the Quiz reports page.
Click on the quiz.
Edit the details.
Click on activate.
See the superposition.

### Context
 * Kolibri version: 0.12.0-alpha7-dev?
 * Operating system: Ubuntu
 * Browser: Chrome 71

**Comment by rtibbles** [comment]
Upon clicking both of the save buttons, and then refreshing the page, the Quiz now appears to be in neither state, according to the UI:
![image](https://user-images.githubusercontent.com/1680573/52097362-a6bd2a00-257f-11e9-9467-ca5f485c6cb7.png)

**Comment by rtibbles** [comment]
Also realizing that this is a mock - the data has not been connected up yet.

**Comment by jredrejo** [comment]
This is fixed in #4861

**Comment by indirectlylit** [comment]
is it? I don't recall fixing it

**Comment by jredrejo** [comment]
Yep, it's fixed because the part that was causing the problem (edit quiz from a report) has been totally removed :)

**Comment by indirectlylit** [comment]
magic :)
