### ISSUE TITLE
Reported progress on importcontent tasks jumps between single file progress percent and overall progress

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#489]
To replicate: start a `remoteimport` task. Load and refresh http://127.0.0.1:8000/api/tasks/

Problem: When refreshing, sometimes `percentage` refers to the current individual file download progress, and sometimes to the overall progress across all files.

Needed resolution: `percentage` should consistently refer only to the overall progress, not the subtask progress.

**Comment by indirectlylit** [comment]
there's a possibly related issue here: https://github.com/learningequality/kolibri/issues/614

this issue appears to be resolved though
