### ISSUE TITLE
On the Dashboard, Lessons are not ordered by most recent activity

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4899]
### Observed behavior

On the dashboard, lessons are listed in the order they come from the server.

### Expected behavior
On the dashboard, lessons are listed in descending order according to "most recent activity".

Also, When new activity for a lesson comes through a notification, that lesson is reordered accordingly.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by ralphiee22** [comment]
Is this under `Class Home`, `Reports` or `Plan` for the intended behavior?

**Comment by indirectlylit** [comment]
Class Home
