### ISSUE TITLE
add tests for new ANDROID_ARGUMENT environ switches

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4907]
### Observed behavior

In https://github.com/learningequality/kolibri/pull/4158/files we added handling for `ANDROID_ARGUMENT` but no tests. These new options make assumptions about the format of the data returned from `'android.os.StatFs`, but this data is generally not under our control.

### Expected behavior

We should add mocks for `android.os.StatFs` which shows the kind of data we currently expect it to return, and how it's expected to be handled. That way if that data changes or does something differently, we have explicitly encoded what our previous assumptions were and what has changed.

### User-facing consequences

Might help us debug deviations from our expectations which our users encounter in the wild

### Context

0.12.0

**Comment by DXCanas** [comment]
So the idea here is to include some examples of what the text looks like, essentially for context if something ever breaks?

So we have any docs for writing tests on the Python side that I could learn from?

**Comment by indirectlylit** [comment]
search the code base for `django.test` and `pytest`

docs:

* https://docs.pytest.org/en/latest/ 
* https://docs.djangoproject.com/en/2.1/topics/testing/

sometimes writing a test helps hint at ways to restructure the code. In this case for example, you could make a re-usable `parseAndroidStatFs` function which returns expected metadata. Then your test just needs to try different inputs and outputs of that function rather than dealing with a bunch of other code.

**Comment by indirectlylit** [comment]
changing milestone to 0.13.0 so it doesn't block release

@DXCanas this would still be helpful

**Comment by rtibbles** [comment]
I strongly suspect that the referenced code is no longer necessary and should be cleaned up.

**Comment by rtibbles** [comment]
The referenced code has been removed.
