### ISSUE TITLE
make dashboard links clickable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4917]
### Observed behavior

dashboard quiz and lesson items are not clickable:

![image](https://user-images.githubusercontent.com/2367265/52245166-4686fa80-2895-11e9-85d9-e098f5c4b073.png)

### Expected behavior

should take you to report pages under

* Reports -> Lessons -> [Lesson]
* Reports -> Quizzes -> [Quiz]

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by ralphiee22** [comment]
Do we want anywhere in the `K-Grid` item to be clickable or just the name for example?
![screen shot 2019-02-05 at 6 31 41 pm](https://user-images.githubusercontent.com/6361732/52317308-5a555e00-2974-11e9-82c3-e4a55ae952eb.png)

**Comment by indirectlylit** [comment]
cc @jtamiace @khangmach @jonboiser

**Comment by khangmach** [comment]
progress bar should be clickable too

**Comment by indirectlylit** [comment]
more than that right? specs look like:

![image](https://user-images.githubusercontent.com/2367265/52360985-1608a300-29f2-11e9-8bfe-a93212fdc0b0.png)

**Comment by khangmach** [comment]
yes if possible
