### ISSUE TITLE
regression: Exiting lesson resource selection search always goes to "all channels" root page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4918]
### Observed behavior

When you search for something during a lesson resource selection workflow, exiting the search will take you to the "all channels" list

### Expected behavior

Exiting search should take you to the topic you were viewing when you first initiated the search

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
Yes, noticed the same thing [while pickling](https://github.com/learningequality/kolibri/pull/4801/files#diff-0d42327c581bfadf825c6230b8ae0907R35)...
