### ISSUE TITLE
on MacOs in RTL mode, side-bar slide-in/out animation is broken

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4919]
### Observed behavior

See GIF. Starts after 'select all'. This happens anywhere in the app.
![side bar](https://user-images.githubusercontent.com/10248067/52248138-c6b35d00-28a1-11e9-8c1f-45dcf8f268e1.gif)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri Develop
MacOs

Chrome and Firefox
…

**Comment by jonboiser** [comment]
Also, the user drop down appears on the right, even in RTL

![screen shot 2019-02-04 at 5 26 28 pm](https://user-images.githubusercontent.com/10248067/52248181-0b3ef880-28a2-11e9-8dc9-d5be0b335efa.png)

**Comment by rtibbles** [comment]
@indirectlylit and @jonboiser have both reproduced this, it appears to be a MacOS issue, I, on Ubuntu, cannot.

**Comment by indirectlylit** [comment]
this turned out to be just because of running the devserver with HMR on.

(hot module reloading and RTL are not compatible)
