### ISSUE TITLE
final updates to notifications

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4928]
### Observed behavior

1. **Links to reports** aren't currently enabled when applicable
2. **Learner report 'activity' tab** not yet implemented
3. **Group report 'activity' tab** not designed or implemented
   * current design is missing the activity tab under group reports, which is inconsistent with learner reports and the class dashboard: 
![image](https://user-images.githubusercontent.com/2367265/52294465-4b4bbd00-292e-11e9-8f8c-8613f95155d9.png)
4. **Facility-wide notifications** were overlooked completely. They aren't yet implemented, and the current design would result in unexpected behaviors. facility-wide notifications are important for implementations that do not use classes
   * [current design](https://www.figma.com/file/D5wXhmWNGyt60SpGBgFucwZU/Coach-reports-0.12?node-id=719%3A0) treats the case of "no classes in a facility" differently from the case of a facility with classes. This will result in a poor UX because it prevents facility coaches from experimenting with classes while continuing to use facility notifications

### Proposed updates

1. Under `Home -> All activity`, notifications that [have relevant report pages](https://docs.google.com/spreadsheets/d/1aDGKPmeajS1GDjf4VemsioC0SVOJCQfOEuO_cBvSqyk/edit#gid=0) should be linked to them
2. Page under `Reports -> Learners -> Activity` which behaves the same as above but filtered by learner
3. Page under `Reports -> Groups -> Group -> Activity` which behaves the same as above but filtered by group
4. ~New 'Activity' page for the whole facility as described below~

**Facility activity page**

* This page is a more limited version than the items above because it omits all class-related meta-data and links
* There is no 'clustering' logic - it only displays single items, similar to the pages above
* There is a 'show more' button, similar to above
* There are no references to classes, lessons, exams, groups, etc, and no links to reports
* It should still poll for updates
* Page and route updates
  * New page at `/activity`
    * which displays 'all activity'
    * Uses the same app bar style as the 'All classes page'
    * Includes a link '<- [All classes](#)' at the top
    * Only accessible to facility coaches and admins
  * New link to 'facility activity' in 'All classes' page

**Comment by jtamiace** [comment]
Notes from in-person debrief

- Hash out pros and cons of new coach for non-classroom implementations with imps at design office hours: should facility-wide notifications, as currently implemented, be released with 0.12 or a patch release
- On notifications page, style notifications as links instead of 'show' button
- Spec design for empty states and page layouts for the lesson/exam panels on Home

**Comment by indirectlylit** [comment]
cc @jonboiser

**Comment by indirectlylit** [comment]
cc  @jredrejo

**Comment by khangmach** [comment]
Follow-ups from Design office hours
- For 0.12 release we proceed with development of coach tools/updates we're on track with releasing
- Further consideration for classless facility tools, views and notifications will be punted post release
- We have a good start of use cases and context info on how non-formal contexts can benefit from facility-wide "data" and will compile more before starting to build out any features to accomodate.

**Comment by jredrejo** [comment]
> 2\. **Learner report 'activity' tab** not yet implemented
Currently, the only way to get the info is adding a classroom or learnergroup id to the request. Should we add the option to get learner notifications without incuding the classroom or group id? I am not sure if it makes too much sense: One coach having learners in different classrooms seems an odd scenario.

**Comment by indirectlylit** [comment]
the learner activity tab would still be scoped by class

**Comment by indirectlylit** [comment]
@jonboiser how are we looking on this task? I think a lot is complete?

**Comment by jonboiser** [comment]
All of the bullet points in the OP should have been addressed.
