### ISSUE TITLE
Navigation icons on App Bar are not laid out per Material Design specification

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4931]
### Observed behavior

left- and right-margins on the hamburger are off

![image](https://user-images.githubusercontent.com/2367265/52307184-bf965880-294e-11e9-8697-c5d8ff2fe13e.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/2367265/52307161-af7e7900-294e-11e9-8b8f-eb08708a7a06.png)

### User-facing consequences

minor aesthetic issue, but prominent because it's everywhere

### Context

0.12

**Comment by jonboiser** [comment]
This looks good to me. I'm not sure if this will work out visually, but there is another button on the slide-out menu (click the hamburger button) that might need to be adjusted too.

![Screen Shot 2019-03-18 at 10 59 03 AM](https://user-images.githubusercontent.com/10248067/54552272-f3f92d80-496c-11e9-99f5-f508065b5ff6.png)

**Comment by MisRob** [comment]
That's right, thanks. I'm not sure about increasing right margin, since there's not so much space as in the toolbar and it might look a bit weird (but will try and upload screenshot). But I'm pretty sure I should update the left one, so I'll add a commit to PR for that.

**Comment by jonboiser** [comment]
To be more precise about the slide-out menu, the "X" should overlap the location of the hamburger button exactly.

So if a person were to click the hamburger in the middle, their mouse should be in the middle of the "X" in the slide-out menu.

**Comment by MisRob** [comment]
OK, I'm going to adjust hamburger's left margin to be exactly the same (I left answer to a first comment in the PR), that should solve it.

**Comment by jonboiser** [comment]
#5279
