### ISSUE TITLE
Missing snackbar notification when adding and removing learners to/from groups

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4946]
### Observed behavior

Missing snackbar notification 😢 

### Expected behavior

Snackbar notifying the coach that the learner(s) have been added or removed.
Consistency with the rest of the implemented pattern.

### User-facing consequences

Uncertainty if they are expecting the recognizable pattern.

### Errors and logs

--

### Steps to reproduce

Enroll or remove learners to/from groups.

### Context

 * Kolibri version: `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: Firefox 65, Chrome 70.0.3538.77

cc @rtibbles @indirectlylit

**Comment by jonboiser** [comment]
This wasn't a feature in the device > enroll learners + coaches workflow. we might not have strings to use for a new snackbar.

**Comment by rtibbles** [comment]
I just looked for them, we don't, alack!

**Comment by radinamatic** [comment]
It was in the original [Gherkin scenarios](https://docs.google.com/document/d/159i0gG5nQAG_q3j1S1to0qu33xUgxnIyyhQTGQEqr80/edit#bookmark=id.hyxeysfn613l)... No prob, we'll add it in the next one! 👍

**Comment by rtibbles** [comment]
Fixed in #5207
