### ISSUE TITLE
detail detail endpoint does not exist on kolibri:coach:quizdifficulties

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4951]
### Observed behavior

* `ReportsQuizQuestionListPage`
* `/:classId/reports/quizzes/:quizId/questions`

```
[ERROR: kolibri/core/assets/src/api-resource.js] detail detail endpoint does not exist on kolibri:coach:quizdifficulties.
```

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
same with 

![image](https://user-images.githubusercontent.com/2367265/52438243-aff14e00-2acd-11e9-850b-77cf858eb51d.png)

`ReportsGroupReportLessonExerciseQuestionListPage`

**Comment by ralphiee22** [comment]
https://github.com/learningequality/kolibri/pull/4956 actually solves the `internal server error` issue.
