### ISSUE TITLE
Isolate the Kolibri integration testing spreadsheet build inside the docker environment

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4953]
### Observed behavior
I have this [PR](https://github.com/learningequality/kolibri/pull/4544) that's using a virtualenv to run the scripts and generate the Integration testing spreadsheet at the BuildKite.

@indirectlylit [comment](https://github.com/learningequality/kolibri/pull/4544#discussion_r254383845) to that PR to isolate the build inside the docker environment.

### Expected behavior

>* the build would be isolated in a docker environment, so a python virtualenv would not be needed
>* the dependencies for this pipeline step would be defined in a pip `requirements.txt` file or a Pipenv `Pipfile`
>* the individual steps (install dependencies, run `create_integration_testing_worksheet.py`, upload artifacts) are specified as multiple commands in the 'Create integration testing' block of the `pipeline.yml` file

**Comment by indirectlylit** [comment]
fixed by https://github.com/learningequality/kolibri/pull/5313
