### ISSUE TITLE
document limitations on creating superusers via command-line

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#496]
## Summary

While documenting the `kolibri manage createsuperuser` command, I tested it and encountered the following error:

![kolibri - chromium_022](https://cloud.githubusercontent.com/assets/1457929/18061523/52298ed6-6e23-11e6-92d7-cac155972449.png)
## Traceback or relevant snippet from server.log

Error-box traceback

```
    {
    "request": {
        "path": "/api/session/",
        "entity": "{\"username\":\"didin\",\"password\":\"didin\"}",
        "headers": {
            "Content-Type": "application/json",
            "X-CSRFToken": "XQzflXyJltWRKuP8JluloHyAtVHqGnOS",
            "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2"
        },
        "method": "POST",
        "canceled": false
    },
    "url": "/api/session/",
    "raw": {},
    "status": {
        "code": 500,
        "text": "Internal Server Error"
    },
    "headers": {
        "Date": "Mon, 29 Aug 2016 17:47:53 GMT",
        "Server": "WSGIServer/0.2 CPython/3.4.3+",
        "X-Frame-Options": "SAMEORIGIN",
        "Vary": "Cookie",
        "Content-Type": "text/html"
    },
```
## How to reproduce
1. Log in as the first device owner and start the server.
2. Open the terminal and run `kolibri manage createsuperuser`
3. Log out the first device owner and try to log in as the newly created.

**Comment by ralphiee22** [comment]
For this, by any chance did you create two superusers with the same credentials?
I tried the steps, but I could not replicate.

**Comment by radinamatic** [comment]
@ralphiee22 No, the first superuser (Device Owner) was created through the UI as soon as the setup-wizard was merged. Second one was created with the Terminal command and both username and password were different.

**Comment by ralphiee22** [comment]
can you send me your ~/.kolibri/db.sqlite3 on slack?
I think I may know whats wrong

**Comment by indirectlylit** [comment]
hey all - curious if there was any resolution to this issue?

**Comment by ralphiee22** [comment]
I believe this was a problem in that the `kolibri manage createsuperuser` allows one to create another superuser with the same credentials (`createsuperuser` is a built-in django command). If you were to do it through the UI, it wouldn't allow you to create it with the same credentials. No quick and easy fix is obvious as of now.

**Comment by indirectlylit** [comment]
Okay - sounds like something we need to add to the documentation?

Unfortunately at the moment this is considered "user-facing functionality" because we don't have a UI yet for managing super users.

**Comment by indirectlylit** [comment]
another potentially better alternative would be to prevent `createsuperuser` from creating duplicate users

**Comment by indirectlylit** [comment]
The superuser commands will be obsoleted by upcoming Device Permissions work. closing.
