### ISSUE TITLE
App bar title of "Create account" page should not say "Sign up"

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#4960]
### Observed behavior

<img width="1264" alt="screen shot 2019-02-07 at 4 58 10 pm" src="https://user-images.githubusercontent.com/6668144/52452866-b4cbf700-2af9-11e9-9e46-367c112a192b.png">

### Expected behavior

Title should say "Create an account," not "Sign up," since we do not use that term elsewhere

### User-facing consequences

Minor inconsistency

**Comment by indirectlylit** [comment]
so the titles are duplicated?

![image](https://user-images.githubusercontent.com/2367265/52489423-1bdbc100-2b77-11e9-94de-4b375d50cb49.png)

**Comment by jtamiace** [comment]
Open to other suggestions? Just thought we wiped out the "sign up/in" lingo a while ago

**Comment by indirectlylit** [comment]
it's fine with me - just double checking that's what you're suggesting
