### ISSUE TITLE
Kolibri setup not working on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4964]
### Observed behavior
After I installed the Kolibri-0.12-beta3 on Windows 7 and use IE11 as a browser, the Kolibri setup always loading also there's no error logs at the browser. But when I switch to Google chrome browser the Kolibri setup perfectly worked.

### Expected behavior
Kolibri setup should work on IE11.

### Errors and logs
![screen shot 2019-02-08 at 5 01 14 pm](https://user-images.githubusercontent.com/8663934/52468495-d42f5680-2bc3-11e9-8286-d5746e47f7cb.png)

### Steps to reproduce
* Install the Kolibri-0.12-beta3 on Windows 7
* Use the EI11 browser for the Kolibri setup

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12-beta3
 * Operating system: Windows 7
 * Browser: IE11

**Comment by radinamatic** [comment]
> Kolibri setup should work on IE11

Or are we dropping the support for it, was there a chatter @rtibbles?

**Comment by indirectlylit** [comment]
IE11 should still be supported

**Comment by radinamatic** [comment]
I'll try to replicate and confirm in my own VMs!

**Comment by radinamatic** [comment]
I managed to replicate the issue on IE11:

![2019-02-08_17-04-46](https://user-images.githubusercontent.com/1457929/52493624-e0b3af00-2bc3-11e9-8653-088753326e3d.png)

It's such a pain debugging in IE... 🙄 
![2019-02-08_17-06-16](https://user-images.githubusercontent.com/1457929/52493737-1789c500-2bc4-11e9-951d-1747a60dfaa8.png)

**Comment by rtibbles** [comment]
Note that it is the error above the one highlighted that is the issue, the second error occurred because of the first.

**Comment by radinamatic** [comment]
@rtibbles Nope, even if setup wizard is performed in Chrome, Kolibri is still non responsive in IE11:

![2019-02-08_17-43-32](https://user-images.githubusercontent.com/1457929/52495772-9cc3a880-2bc9-11e9-9b9f-4c331d3d1e28.png)

**Comment by rtibbles** [comment]
Right, this seems like a) a polyfill we need is missing (I think for the `File` constructor API, but I am not 100% sure), and b) something has changed that now needs that polyfill - my bet is something to do with styling.

**Comment by rtibbles** [comment]
Ahah! I think this is because of a lack of the `URL` constructor.

**Comment by rtibbles** [comment]
Fixed in #4990
