### ISSUE TITLE
Not enough space still appear even my hard disk is not full

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4965]
### Observed behavior

I try to import a channel in kolibri studio (online). When I select a channel, I see an error message appeared "Not enough space on your device"  so that I cannot import. 
![not enough space](https://user-images.githubusercontent.com/38421180/52469779-5ec58500-2bc7-11e9-8eda-71bad18d819a.png)

### Expected behavior

If the hard disk is not full the error message will not appeared.

### Context

* Kolibri version 0.12.0 beta 3
 * Operating system Windows 10
 * Browser Firefox 65.0 (64-bit)

**Comment by indirectlylit** [comment]
@mrpau-julius I think you've observed similar behavior in the past. Would you mind linking to related previous issues if you know of them?

**Comment by jonboiser** [comment]
The '-1' in "drive space available" indicates to me that the 'freespace' API is returning an error, see 'getAvailableSpaceOnDrive'.

**Comment by rtibbles** [comment]
Fixed in #4997
