### ISSUE TITLE
spinning snackbar, shaking circular loader

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4969]
### Observed behavior

![spin](https://user-images.githubusercontent.com/2367265/52494292-76c6e580-2b82-11e9-9fe8-a00cbfca62b6.gif)

we've also observed similar weird issues with the `KCircularLoader`, which shakes

### Expected behavior

no unexpected CSS animations

### User-facing consequences

huh

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jonboiser** [comment]
I've only seen this on Kolibri Beta, but never locally.

I also noticed on Kolibri Beta that the notification comes flying from the upper left corner.
