### ISSUE TITLE
points not given after finishing a video

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4970]
### Observed behavior

Reported by @jtamiace during a hack sesson:

> I finished a video but didn’t get points :(

![image](https://user-images.githubusercontent.com/2367265/52494961-310b1c80-2b84-11e9-95e0-e43df4605f7a.png)

### Expected behavior

points are given, and status changes to 'completed'

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jtamiace** [comment]
Note: I can't reproduce this

**Comment by indirectlylit** [comment]
there's a chance you fast-forwarded in the video
