### ISSUE TITLE
not all possibilities for responses are available in quizzes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4971]
### Observed behavior

reported by @laurenlichtman during a hack session:

>  didn’t take a picture of this but not all of the possibilities of what you can include in a free text response (e.g., the “pi” symbol) appeared when answering the question in a quiz. I can tell now that it should be there because I see it available in a Lesson 

confirmed by @shivichandra:

> +1, this made me get some questions wrong! 

### Expected behavior

all necessary symbols should be available

### User-facing consequences

learners may get questions wrong, and coaches may not realize why

### Errors and logs

…

### Steps to reproduce

…

### Context

0.12

**Comment by pcenov** [comment]
@radinamatic as discussed this one will need further clarification

**Comment by pcenov** [comment]
@radinamatic I created and completed a quiz using the questions from Khan Academy's 7th grade Geometry>Area and circumference of circles and the π letter is available in the answer options. Also all the answers containing π which I submitted were accepted as correct. 

I compared the answer options to https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-geometry/cc-7th-area-circumference/e/area_of_a_circle and I noticed that they are also showing 3 additional `log` options but in reality none of these are actually needed for the available exercises so it seems that the issue described above is not extant in Kolibri 0.15.2

Screenshot:

![2022-05-11_17-44-07](https://user-images.githubusercontent.com/79847249/167879683-48fee422-b3c4-4de1-8d62-2dd85eeea9b4.png)

**Comment by rtibbles** [comment]
Excellent! I am going to consider this closed - quite possible that some updates to our perseus render in the interim had fixed this.
