### ISSUE TITLE
icons proportions are slightly off

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4975]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/52497296-8b0ee080-2b8a-11e9-9b6e-bb9305eccc2a.png)

### Expected behavior

SVG icons are scaled proportionally.

likely related to https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/icons/KIcon.vue#L133-L134

Setting only the width or height seemed to negatively impact our ability to position the icon vertically with accuracy and consistency, but setting both seems to squash the icons unexpectedly

### User-facing consequences

...

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by nucleogenesis** [comment]
Pretty sure this is resolved with the new KDS package and approach on icons. 

I haven't heard any similar issues in the many weeks of bug bashes and testing we've had since the icons were added to Kolibri & KDS, so this seems like it's resolved.

**Comment by indirectlylit** [comment]
nice :) the issue was always quite subtle in any case
