### ISSUE TITLE
Clicking a link under the class activity page throws error

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4979]
### Observed behavior

observed by @jayoshih 

> Clicking a link under the class activity page throws
> 
> ```“4-0.12.0b3.js:14 TypeError: Cannot read property 'kind' of undefined”```

### Expected behavior

no error

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context
0.12.0  beta 3

**Comment by jonboiser** [comment]
#4981
