### ISSUE TITLE
cherrypy logging informational messages as errors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4980]
### Observed behavior

Starting Kolibri I see

```
...
INFO:cherrypy.error:[08/Feb/2019:12:53:26] ENGINE Bus STARTING
INFO:cherrypy.error:[08/Feb/2019:12:53:26] ENGINE Serving on http://0.0.0.0:8080
INFO:cherrypy.error:[08/Feb/2019:12:53:26] ENGINE Bus STARTED
...
```

### Expected behavior

These should probably be `info` level message?

### User-facing consequences

things seem like they're going wrong when it's all good

### Errors and logs

see above

### Steps to reproduce

start kolibri

### Context

0.12.0 beta 3

**Comment by jredrejo** [comment]
Totally agree

**Comment by jonboiser** [comment]
I think this is just the way CherryPy works. Someone had a similar question on stackoverflow https://stackoverflow.com/questions/47675574/why-cherrypy-server-logs-error-messages-even-though-it-seems-to-work

**Comment by jredrejo** [comment]
Yep, looking at cherrypy code I don't think this can be changed from outside CherryPy
