### ISSUE TITLE
updateWithNotifications error

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4982]
### Observed behavior

Observed in Sentry the `updateWithNotifications` action is sometimes trying to access an undefined value

### Expected behavior

Ensure that `updateWithNotifications` doesn't make assumptions that values exist 

### User-facing consequences

potentially broken behavior

### Errors and logs

https://sentry.io/learningequality/kolibri-frontend/issues/877447533/

```
Cannot read property 'content_id' of undefined
```

### Steps to reproduce

unknown

### Context

0.12.0 beta 3

**Comment by jonboiser** [comment]
#4981
