### ISSUE TITLE
ePUB reader settings issues

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4985]
### Observed behavior

1. `+ Increase` button seems cut off on the right (or is missing the `box-shadow` there?)
2. Theme buttons have lost their _theming_. They still work (clicking on them does change the fore- & background colors), they just don't represent themselves correctly.

![2019-02-09_0-30-55](https://user-images.githubusercontent.com/1457929/52513495-07450a80-2c03-11e9-8098-6aa9a58380cf.png)

### Expected behavior

Fully colored theme buttons.

### User-facing consequences

Inability to see the various viewing options, especially if they require different contrast.

### Errors and logs
…

### Steps to reproduce
…

### Context

 * Kolibri version: `release-v0.12.x` branch
 * Operating system: all
 * Browser: all

**Comment by radinamatic** [comment]
And while we are at it, how difficult would it be to add a couple more of stronger contrast options? 😊 
Something like yellow-on-black, or blue-on-white?

![2019-02-09_1-59-20](https://user-images.githubusercontent.com/1457929/52515038-f26e7400-2c0e-11e9-950e-1ff8ed5e0333.png)

![2019-02-09_1-58-24](https://user-images.githubusercontent.com/1457929/52515044-f8fceb80-2c0e-11e9-8e40-005d4f8394f7.png)

**Comment by rtibbles** [comment]
Fixed in #5005
