### ISSUE TITLE
Unecessary (back)links?

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4989]
*Unless I'm missing some previous discussion...*

### Observed behavior

Back to *All classes* from *Class home* makes sense as otherwise the user would need 2 clicks to get there:
![2019-02-09_2-39-54](https://user-images.githubusercontent.com/1457929/52515772-fce13b80-2c17-11e9-844a-4c5b7969a13c.png)

Back to *All lessons* from *Reports > Lesson > Lesson detail*, also makes sense.
![2019-02-09_2-48-41](https://user-images.githubusercontent.com/1457929/52515783-15e9ec80-2c18-11e9-8084-026fd53d226d.png)

Idem for the (back to) *All quizzes*:
![2019-02-09_2-55-43](https://user-images.githubusercontent.com/1457929/52515803-4d589900-2c18-11e9-9da0-ce7c21737fa8.png)

But I fail to see why are these necessary: 

1. (back to) *Reports* from *Plan > Lesson/Quizz/Group* - **there is a *Reports* tab right above**...???
![2019-02-09_2-20-27](https://user-images.githubusercontent.com/1457929/52515841-e1c2fb80-2c18-11e9-84af-7043472e7ef5.png)

2. (back to) *Class home* from *Reports* - **there is a *Class home*  tab right above**...???
![2019-02-09_2-40-39](https://user-images.githubusercontent.com/1457929/52515869-539b4500-2c19-11e9-9395-706a0242cafb.png)

3. (back to) *Go back* from group detail page - **there is a *(go back) to Groups* link right above**...???
![2019-02-09_2-53-08](https://user-images.githubusercontent.com/1457929/52515881-7fb6c600-2c19-11e9-979a-2e7103158568.png)

Is it just to follow the pattern, so there would always be "some link" in the same placeholder, even though it is unnecessary and missuses the vertical space?

cc @indirectlylit @khangmach @jtamiace I don't consider this to necessarily be a blocker (hence I didn't put any labels), I'm trying to figure out if this design was intentional, in order to properly document it in the Gherkin scenarios.

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

### Context
…

**Comment by indirectlylit** [comment]
Previously, all three of these were "<- All classes" links:

![image](https://user-images.githubusercontent.com/2367265/52516095-f03df280-2bd9-11e9-9d0d-178c4fefafe7.png)

![image](https://user-images.githubusercontent.com/2367265/52516098-f6cc6a00-2bd9-11e9-8f90-dec749fb14ed.png)

![image](https://user-images.githubusercontent.com/2367265/52516103-02b82c00-2bda-11e9-8d00-c9ce6ea40c8e.png)

* @jonboiser mentioned that when he was on a reports page and clicked the 'back' link, he expected to go the 'Home' page. @khangmach concurred
* I made the 'Plan' page to 'Reports' for consistency, so you sort of go "up" the list?

This one looks like a bug:

![image](https://user-images.githubusercontent.com/2367265/52516127-5fb3e200-2bda-11e9-9098-6fb1c986c711.png)

**Comment by khangmach** [comment]
Upon seeing this pattern implemented, it definitely seems really weird and redundant...
When JB demoed this to me the main thing we found ourselves a bit confused by was the interaction of: 
- clicking into a **particular report** (lesson/quiz/notification/whatever) from CLASS HOME.
- Accidentally clicking the back link expecting to go back to CLASS HOME, but instead going back to All Lessons **(see my screenshot below)**

<img width="426" alt="screen shot 2019-02-10 at 9 34 05 am" src="https://user-images.githubusercontent.com/25045166/52537051-e7067000-2d16-11e9-93ba-6d7dd64168e4.png">

@indirectlylit the implementation you provided in screencaps above adds back links to the wrong pages, as we weren't confused by where we were on the highest level pages (/plan, /reports, /class home) but inside a report.

That said, being power users, all of us are kind of going everywhere in the UI clicking on various things and don't have an established mental model of a teacher. I'm hesitant to make these big changes just based on two people and a few hack sessions and would like to see real users navigate the architecture first. 

the implemented pattern here is unnecessary and convolutes some of the high level info architecture. Let's revert these link changes...SORRY FOR THE CONFUSION....

**Comment by indirectlylit** [comment]
> we weren't confused by where we were on the highest level pages (/plan, /reports, /class home) but inside a report

@jonboiser care to weigh in? that's not what I recalled you saying

**Comment by jonboiser** [comment]
I did say when you are on a top-level page like "Plan" or "Report" it felt like a back button that went back 2 levels to "All classes" feels like it goes back too far. If we revert back to "All Classes" it's going to be mistakenly used pretty often.

When you are a level down, I think the confusion might come from the lack of breadcrumbs and losing the plan or report workflow context. The links work as expected to me though.

Maybe if these new back buttons are made redundant by the purple tabs, they shouldn't be on Class > Plan or Report.

**Comment by jtamiace** [comment]
At the very least, this is the most confusing to me... would suggest it to be Home and not Reports, because Home is higher in the IA than Reports and Plan, despite it being adjacent in the action bar.

<img width="413" alt="screen shot 2019-02-11 at 1 20 55 pm" src="https://user-images.githubusercontent.com/6668144/52594305-07f6c000-2e00-11e9-845d-4706bdfa52ce.png">

Agree with @jonboiser that "all classes" from Reports and Plan felt like it was going too far

> the confusion might come from the lack of breadcrumbs and losing the plan or report workflow context

The more I click through the more I feel this is true also... I can also ask Riddhi to make perception of navigation a focus point during usability tests with Mumbai teachers, since the experience of the real thing is different than the prototype (now planning on having her do some brief testing of the implemented version of coach reports after all)

Results from that can tell us if bringing back breadcrumbs is a good idea 🤷‍♀️
