### ISSUE TITLE
flashing scrollbar in modal

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5011]
### Observed behavior

observed by @jeepurs during a bug bash:

![scroll-flash](https://user-images.githubusercontent.com/2367265/52605053-1655d380-2e22-11e9-9c8e-623453f3a383.gif)

### Expected behavior

* scrollbar should either be fixed on or off but never alternate like that
* also need to watch out for nested scrollbars, which seem to be happening in here

### User-facing consequences

seizure?

### Steps to reproduce

…

### Context

0.12.0 beta4

**Comment by radinamatic** [comment]
> seizure?

Not sure if it's fast enough to cause seizures, but it's sure ugly...

**Comment by indirectlylit** [comment]
dupe: #4641
