### ISSUE TITLE
Learner quiz score not updated

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5013]
### Observed behavior
Learner score not automatically updated after the quiz completed at the coach reports page. 

### Expected behavior
Learner score should be updated after the quiz completed.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/52634093-3f00ca80-2f01-11e9-8063-821bec6f147f.gif)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12-beta4
 * Operating system: Windows 7
 * Browser: FIrefox 65.0

**Comment by indirectlylit** [comment]
good catch!

**Comment by indirectlylit** [comment]
A few other strange behaviors I'm seeing here:

1. the Greg P. user's row is changing state, with the Progress and Score values flickering in and out. @mrpau-richard any chance this is an artifact from the GIF?
2. While Carol H. is 'started', her score says '0%' but it should be undefined

**Comment by mrpau-richard** [comment]
@indirectlylit here's the [video file](https://drive.google.com/file/d/1Qjf--zHPYMcwFPUjxsIY6-DqmT0NPYuu/view) for the clear demonstration. 

I logged in using Greg P. learner account and take a quiz, after I summited it. my score indicate 0% at the coach reports page and the quiz progress completed. But when I browse the Greg P. quiz reports it has 40% score.

**Comment by indirectlylit** [comment]
should be fixed – @mrpau-richard please test in beta 5
