### ISSUE TITLE
handle 403 errors across the app by redirecting to the sign-in page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5014]
### Observed behavior

When the browser is closed mid quiz, and then reopened, Kolibri errors out:
![2019-02-12_12-57-00](https://user-images.githubusercontent.com/1457929/52657859-7ff0e300-2ef1-11e9-9e6c-c6faeed4ccd6.png)

### Expected behavior

If the session is not terminated, no reason the learner should not be able to resume where they left out.
If the session timed out, redirect to sign-in page.

### User-facing consequences

Confusion

### Errors and logs
…

### Steps to reproduce
- Close the browser mid-quiz and restart the device
- Reopen the browser

### Context

 * Kolibri version: `release-v0.12.x` branch
 * Operating system: Ubuntu 18.04
 * Browser: Chrome & FF

**Comment by indirectlylit** [comment]
Looks like you're probably getting logged out when the browser is closed.

I think we may want to respond more generally to unhandled `403` errors by redirecting to the login page?

**Comment by rtibbles** [comment]
A little confused as to why this is happening, because we already do catch any 403 errors and then redirect to the login page, but it doesn't seem to be happening right now.

**Comment by rtibbles** [comment]
Hrm, it will only redirect if it detects a change in the logged in user, which would not be the case if the browser had just been reopened, because the session would not exist at all.

**Comment by rtibbles** [comment]
Fixed in #5076
