### ISSUE TITLE
Superfluous mention of the class in the notification

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5016]
### Observed behavior

I was testing the class with just one learner and no groups, and I noticed that the class was referenced in the notification. Seems superfluous on the Class home since it's already clear which class the user is in

![2019-02-12_2-46-21](https://user-images.githubusercontent.com/1457929/52660181-11af1f00-2ef7-11e9-9144-a2e6ef5f4c19.png)

Is it that the group name defaults to class name when there are no groups?

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

**Comment by indirectlylit** [comment]
cc @jtamiace @khangmach perhaps a tweak for the next round? Could simplify these to just 'Everyone finished...", "Everyone started..."

**Comment by khangmach** [comment]
Yup, let's condense the phrasing as you suggested in the next round.
