### ISSUE TITLE
styling issues with channel import selection

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5029]
### Observed behavior

reported by @jtamiace and @carinediaz 

![image](https://user-images.githubusercontent.com/2367265/52676943-cd188900-2ee0-11e9-8ba6-b9dbf420ba96.png)

### Expected behavior

'view' link should not be floating outside card

### User-facing consequences

things look broken

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
see also quiz creation, e.g. in the Blended Learning channel:

> ![image](https://user-images.githubusercontent.com/2367265/53103681-e7ef8c80-34e2-11e9-9327-3321c4b4cb44.png)

**Comment by jonboiser** [comment]
I put in a fix for this in #5100. It gives that description paragraph a fixed height, and is scrollable if it goes over.

**Comment by indirectlylit** [comment]
thanks!

there's a future update coming to make them more responsive, but that's a new feature
