### ISSUE TITLE
Cannot extract built Kolibri pex sources into windows.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#503]
## # Summary

Running built kolibri pex in windows has a problem, because windows has a  limit of 255 characters in file path and some of the kolibri sources beyond that limit.

![2](https://cloud.githubusercontent.com/assets/8663934/18114592/caab61de-6f6a-11e6-9354-47814cf44fe7.JPG)
## # How to reproduce
1. Build a Kolibri pex file using `make dist` command.
2. Copy the built Kolibri pex file from kolibri/dist/ to windows.
3. Install python in windows.
4. Run Kolibri pex file on windows using this command: `>PythonPath/python.exe kolibriPexFile.pex`

![cmd](https://cloud.githubusercontent.com/assets/8663934/18114788/9a965d08-6f6c-11e6-8759-1b816ceb90bc.JPG)
## # References

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx
https://en.wikipedia.org/wiki/Long_filename
https://support.code42.com/CrashPlan/4/Troubleshooting/Windows_File_Paths_Longer_Than_255_Characters

**Comment by indirectlylit** [comment]
Sounds like this can be closed because we're not using PEX on windows?

feel free to re-open if that's not the case
