### ISSUE TITLE
Facing error while kolibri 0.12.0 deb file installation

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5036]
### Observed behavior
After running below command it shows error:
**sudo dpkg -i kolibri_0.12.0b4-0ubuntu1_all.deb**

File downloaded from https://github.com/learningequality/kolibri/releases.

![1](https://user-images.githubusercontent.com/12776071/52693166-f80be700-2f8b-11e9-9711-e9f9fd5e7a47.png)

### Context
Kolibri version : Kolibri 0.12.0
Operating system : Ubuntu 14.04

### Screenshots:
![3](https://user-images.githubusercontent.com/12776071/52693710-7c129e80-2f8d-11e9-970f-aa28a74c4cf0.png)
![2](https://user-images.githubusercontent.com/12776071/52693711-7c129e80-2f8d-11e9-87cc-38b339ab4354.png)

**Comment by rtibbles** [comment]
Thanks @swapnil106111 - this is because we have not incremented some version data in the code to reflect that it is a beta. Not sure why it has *only* affected the debian installer though.

**Comment by indirectlylit** [comment]
should be addressed when the beta 5 debian is available – cc @benjaoming

**Comment by benjaoming** [comment]
Yup, it's available here for you @swapnil106111 

https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed

**Comment by swapnil106111** [comment]
@benjaoming Able to install kolibri 0.12.0b8 using deb file on ubuntu 14.04.

**Comment by benjaoming** [comment]
Thanks for the feedback @swapnil106111 :100:
