### ISSUE TITLE
contentnodeprogress endpoint is causing issues

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5041]
### Observed behavior

We've seen reports that the `contentnodeprogress` endpoint is timing out. It is also doing something that crashes Vue dev tools

### Expected behavior

Displaying topic-summarized learner progress should not cause performance issues.

### User-facing consequences

slowness

### Errors and logs

`
2019/02/13 14:25:07 [error] 1218#1218: *2530 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.65, server: , request: "GET /api/content/contentnodeprogress/?ids=c332779e47664ba6bc2fe0480a883541%2C3950edd4eea1492b9c1201b9f6f01c8b%2C66429e2110d34ee2afff524a35089772%2C8cdfebf26f0f4686bbb5f09f5f7a019d%2C0d13d659e7554a83a0446ce46a2e06fa%2C29de6ab586d746679c4045f9ed83059a%2C6c8f604c286e41ddab26cdd1788ddc94%2C0687bf14b25a4545a77230ac91eea349%2C4d3a0382f7ae43ef9d66b00ea5b8fd04%2Cd59a09e52e4441dfa9d8939b3e77f445%2C77f64dd3b23748149663158cf4df8e7b%2C49704b5c36d8466f8929117fd20020af%2Ce043adab9d23459486c9e4f8a95200ae%2Ce935323c9680472f9ee8a6aa6f43d4a3%2Cee7eae3ef9554a9d8317a2d96bfc7e82%2C431a10ecb7b047f292f2298d637efd12%2Cd9ace7153cac45f9b2e3a133026af83a%2Cf33c7a56a99c4339818c95b300b87dc5%2C125a84a5c25d4d6c9d24c5b24b4a814f%2C05d9f65d4ab74db0b78c83624c590ba2%2Cb350be9f304a4888a895444dee21eda5%2Cb020de20f49c48cf8b000aec3f19c8d9%2C442adeeeb2884392a123ffc9ceceb271%2C6150957696e44e11bea1f9111bae3e28%2C335ab3e1109d434cae90811ace2a55dd%2C557c165d58094732ab7e78315acb17bd%2C841e68eb25d74e229dd070fb893e2751%2C6f7e0e74996e45699a73e30c401428dc%2C25db9212ce6a4737af101f4a66990aef%2Ca7a0f78bde7a42b5b35584d1a9205d38%2C340ce93726494506aab3d48e4e724f74%2C4baef724f69c490ead0e61e7b8fa5ef7%2C00c8b0bea256411a98b8a27f3f95acb7%2C610eea0b2f50475dbc992bd7080d7d42%2Cd78e51a383104375a2a2c215e17a6eac%2C07b89490a5ce4734b0caf374d76027b4%2C2a1168a42367425589abd9bb15b219d0%2C9721bdd39485407d915a559bcf9d27c7%2Ca21233b747584814b511ce5148989726%2Cdab43e4c7e394edeaf94ad1a75c4905f%2C87f538fa049e4803922c53908740f6c9%2C44f6966a2cdc435eada060115d6b7491%2C1c0db797e3f442aab5f60d146f9b9f0e%2C17f304207f4d4c33b2450549d4856c65%2Cb3b95a5ff5ea4b8a9cb3a64f317857c5%2C85e52c15961244fa9c8bde7bccc2d549%2C80d76376520f4863abc5961bf8ef6592%2C4f2cc0fa175f4137b46369ecbb36df08%2Cf93dbdc8813d4399b8835a4dda462519%2Cd3b3aaa3132b4280b08dec2924fc4f72%2C997c486c8d7b4b658efd91fd3c012cf9%2Cfbf53ffe7c5d4b7db7d60a58ed5013f5&1550060703
`

### Steps to reproduce

…

### Context

0.11.1

----

cc @jredrejo @rtibbles

**Comment by rtibbles** [comment]
Some of this may have been resolved by #7434 - but more likely this is a consequence of calculating aggregate progress from many descendants.

**Comment by rtibbles** [comment]
This has been resolved by updating the contentnodeprogress endpoint to use the same filtering as contentnode, in #8650.

Additionally, we no longer annotate aggregate progress on topics to avoid hierarchical queries.
