### ISSUE TITLE
`--settings` is ignored when running management commands

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#5042]
### Observed behavior

When running a management command such as `kolibri --debug manage runserver --settings=other_settings` for the first time on an empty KOLIBRI_HOME, it runs migrations with the base settings file. So any additional migrations that may be in `other_settings` is ignored. The server does start with the correct settings file though. 
When running with `DJANGO_SETTINGS_MODULE`, everything works as expected.

### Expected behavior

Settings set with `--settings` should be adhered to for all django processes.

### Steps to reproduce

Run `kolibri --debug manage runserver --settings=kolibri.deployment.default.settings.dev` and watch that migrations are ran with base settings file.

### Context

0.12

**Comment by rtibbles** [comment]
This has been fixed.
