### ISSUE TITLE
buttons and top alignment in tables don't mix well

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5046]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/52741441-30aac100-2f8a-11e9-868c-8fd708b142f7.png)

### Expected behavior

layout could be improved a bit

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jonboiser** [comment]
I only see this in CoachExamsPage (the screenshot), because the `<tds>` don't have a vertical-align rule. Does it happen anywhere else?
