### ISSUE TITLE
learn pages (Classroom Assignment Page) should auto-refresh to see newly activated/assigned content

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5047]
### Observed behavior

learner pages doesn't auto-refresh

### Expected behavior

when a coach activates a lesson or quiz, or assigns it to  a learner, or changes its name, they should see the changes without needing to refresh

### User-facing consequences

learners might have trouble seeing content assigned during a class

### Steps to reproduce

* as a learner, open a class page
* as a coach, assign and activate a lesson and a quiz

### Context

0.12.0 beta 4

**Comment by jonboiser** [comment]
Should this also auto-update the title of the lesson or quiz if that changes?

**Comment by indirectlylit** [comment]
If feasible, certainly!
