### ISSUE TITLE
inconsistency between difficult question summary and detail reports

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5052]
### Observed behavior

| summary | detail |
|--|--|
|  "Question 1" | "Repeated addition (1)" |
| "1 of 1 needs help" | three users needing help |
| [Link to page]( http://kolibribeta.learningequality.org/coach/#/4707894249cbe44b7fd142bdb87fe90e/reports/lessons/77c3daea1dcadbdb2f1b8e0a9d278a81/exercises/52afd859b8df5bb1a6a834ddaeaf3f23/questions) | [Link to page](http://kolibribeta.learningequality.org/coach/#/4707894249cbe44b7fd142bdb87fe90e/reports/lessons/77c3daea1dcadbdb2f1b8e0a9d278a81/exercises/52afd859b8df5bb1a6a834ddaeaf3f23/questions/58e624d3713f553fb26c156885e344aa/learners/db6a72b70250db5ed2d69955eece98bd/interactions/0) | 
| ![image](https://user-images.githubusercontent.com/2367265/52757940-4d132180-2fbb-11e9-9140-b09cbe98247c.png) | ![image](https://user-images.githubusercontent.com/2367265/52757930-44bae680-2fbb-11e9-993d-83b4ea3bd6b0.png) |

### Expected behavior

Table summary and detail page should be consistent

### User-facing consequences

possible confusion

### Steps to reproduce

see links to beta site above

### Context

0.12.0 beta 4

----

cc @rtibbles

**Comment by indirectlylit** [comment]
might be partly a dupe of #5026?

**Comment by indirectlylit** [comment]
after a discussion with @rtibbles we came to the conclusion that there are at least 3 independent issues in here. I'll try to tease it apart tomorrow

**Comment by jonboiser** [comment]
On 0.12 beta 5, The links to questions are unusual. In the screenshot below, "Question 1" displays attempt for the same problem (parallelogram with some arrows) for the two users who Need Help on it.

However, "Question 2" (correctly, I think) has "1 of 1" needs help, but the links shows attempts on what I thought was Questions 1, but the second user "learner"'s detail is a different question (graphic of a single ray pointing down). I think it would be correct behavior if the first user "JB" was not in the page for Question 2

Screenshot begins at select all gesture.

![difficult-questions](https://user-images.githubusercontent.com/10248067/53053614-c052e280-3456-11e9-911f-972c6e3ff118.gif)

**Comment by jonboiser** [comment]
But when I log back in later, the difficult questions reports behave like I expected (e.g. question 2 only has details for "learner" on the "ray" question)

**Comment by rtibbles** [comment]
I think I am fixing most of the issues identified here, so assigning in lieu of the other issues being created.

**Comment by rtibbles** [comment]
@jonboiser I think there is an issue with the state persisting between different pages of the difficult question views. I am actively working on these issues, will try to open a PR tomorrow!

**Comment by swapnil106111** [comment]
@rtibbles Same we are facing in Kolibri 0.12.0b4.

**Comment by yogeshmhaskule** [comment]
tested it kolibri.0.12.0. worked.
![quize_2](https://user-images.githubusercontent.com/7850420/53872467-54f73c00-4024-11e9-8c9a-3fa55df023b1.png)
![quize_11](https://user-images.githubusercontent.com/7850420/53872550-853eda80-4024-11e9-9450-db56314d26c8.png)
