### ISSUE TITLE
arrows in back links are not clickable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5053]
### Observed behavior

the arrow in the 'back' links are not clickable:

![image](https://user-images.githubusercontent.com/2367265/52758271-87c98980-2fbc-11e9-9c80-3c9b4b59af66.png)

### Expected behavior

clicking either the arrow or the text should work

### User-facing consequences

annoyance

### Context

0.12.0 beta 4

**Comment by jonboiser** [comment]
#5060
