### ISSUE TITLE
should not show 'Attempt 1' in detail reports when there's only one attempt

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5055]
### Observed behavior

In quizzes, only a single attempt is allowed from the learner's perspective. However in quiz reports, we label that attempt with "Attempt 1":

> ![image](https://user-images.githubusercontent.com/2367265/52758587-ba27b680-2fbd-11e9-98ce-d237317fd7b8.png)

### Expected behavior

Reported by @lauradanforth 

> Since there's only one attempt allowed in Quiz questions, makes sense to not include any mention of 'Attempt #s' in the report

I believe we might track "multiple attempts" in the course of quiz if the learner changes their answer by returning to a question. This may have been intentional to help coaches have insight about the student's thought process, but I agree that this extra information is unexpected and confusing in the context of a quiz report.

### User-facing consequences

Confusion over how to interpret quiz reports

### Steps to reproduce

See for example [this page on the beta server](http://kolibribeta.learningequality.org/coach/#/307fdbe2f00b02e7cefa4eae2446fdb3/reports/quizzes/97e9b841c838654fc84b0e7cc40d96d3/learners/370144fcc757d2ad6d2b14836fd0a509/questions/3/interactions/0)

### Context

0.12.0 beta 4

----

cc @rtibbles @jtamiace @khangmach

**Comment by khangmach** [comment]
Exam reports are buggy for me at the moment and I can't load any pages...but this is a related issue, now closed: https://github.com/learningequality/kolibri/issues/3139

If we decided to cut out showing everything but the final submitted attempt, then we should cut out the "attempt 1" string as well.

**Comment by indirectlylit** [comment]
thanks for digging that up. In the thread, @rtibbles says

> if a student does actually change their answer, this is useful diagnostic information for a coach. What might be good is to reduce the interface prominence of the non-final answers.

The trade-off here is simplicity of the UI vs depth of the information.

Since we haven't lowered the prominence of non-final answers, and since clearly the final answer is the most important piece of information, recommend we go with the recommendation @khangmach made in #3139:

> There should only be one attempt [shown to the coach], which should be based on the final input when the [learner] presses the submit exam button

Down the line if we learn that there's a demand to see how learners change their answers before submitting the quiz we can revisit what that UX might look like for the coach.

thoughts?

**Comment by indirectlylit** [comment]
> Exam reports are buggy for me at the moment and I can't load any pages

@khangmach is this the case on the beta server? if so would you mind opening an issue?

**Comment by navakk9** [comment]
I somehow forgot about this and didn't realize that there can be multiple attempts on a quiz if a learner was to go back and change their answer. I concur with @rtibbles that it would be useful for a coach to have that information because it can provide opportunities to have a diagnostic approach. The main pain point I think is the prominence, because if there are no multiple attempts, it is just useless information for the coach.

**Comment by indirectlylit** [comment]
I suppose the simplest solution then is to only show the "Attempt 1" label if there was more than one attempt. This would apply to both quizzes and exercises.

**Comment by navakk9** [comment]
@indirectlylit - Yes!

**Comment by khangmach** [comment]
sounds good

**Comment by indirectlylit** [comment]
fixed when #5100 is merged
