### ISSUE TITLE
redundant 'needs help' indicator in dashboard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5059]
### Observed behavior

'needs help' is shown twice

![image](https://user-images.githubusercontent.com/2367265/52766973-d0de0580-2fdd-11e9-9cf3-d032efe34d88.png)

### Expected behavior

In the mockups, 'needs help' is separated from the rest of the status indicators. However this becomes inconsistent with how we're displaying status summaries in most other parts of reports now

### User-facing consequences

looks a little silly

### Context

0.12.0 beta 4

----

cc @jtamiace @khangmach think we should treat these consistently with the rest of reports or make a special case for the dashboard?

**Comment by khangmach** [comment]
Good point. I have no qualms with cutting out the **(!) 1** indicator on the right
