### ISSUE TITLE
Label of the learner and coach not pluralized

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5062]
### Observed behavior
Label of the learner and coach not pluralized at the Facility class page
![screen shot 2019-02-14 at 6 41 26 pm](https://user-images.githubusercontent.com/8663934/52781901-abf29c80-3088-11e9-99ed-6874590e8ba9.png)

### Expected behavior
The label should change to singular if the value is only one.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.x-beta-4
 * Operating system: Windows
 * Browser: Firefox 65.0

**Comment by jonboiser** [comment]
The headers will be understandable even when there is only one coach or learner in the class.

Also, there may be multiple classes which may have more than 1 coach/learner, so the header needs to work for both cases.

**Comment by mrpau-richard** [comment]
I understand it now @jonboiser. closing this.
