### ISSUE TITLE
Coach tab not opening

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5068]
### Observed behavior
When logging in with coach user and not assigned to any class. Then coach tab is not opening. Please take a look at attached screenshot for more information.

### Expected behavior
It must show something when class is not assigned to the coach.

### Steps to reproduce
1. Create a coach account.
2. login with coach and click on coach tab.
3. Then assign a class to same coach.
4. login and check the behaviour.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![2](https://user-images.githubusercontent.com/12776071/52839444-28828b00-311c-11e9-90de-f79bc95c2c6f.png)
![1](https://user-images.githubusercontent.com/12776071/52839445-28828b00-311c-11e9-8652-63d3550192bc.png)

![4](https://user-images.githubusercontent.com/12776071/52839443-28828b00-311c-11e9-8ba2-c35a909ef62e.png)
![3](https://user-images.githubusercontent.com/12776071/52839456-2f110280-311c-11e9-9437-c74553ab64ce.png)

**Comment by indirectlylit** [comment]
cc @jonboiser here's the most empty state :)

**Comment by jonboiser** [comment]
This should have been fixed in #5034

**Comment by indirectlylit** [comment]
@swapnil106111 mind testing in beta6?

**Comment by swapnil106111** [comment]
@indirectlylit Tested in kolibri 0.12.0b8. This issue resolved.
![1](https://user-images.githubusercontent.com/12776071/53157849-641fc800-35e8-11e9-9730-e7834236e4ef.png)
