### ISSUE TITLE
Progress report for quizzes is incorrect.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5069]
### Observed behavior
Assign a quiz to the learner and let learner complete the quiz. After completing the quiz, go to the coach tab and click on quizzes. It shows incorrect progress report.

### Expected behavior
It must show correct progress report.

### Steps to reproduce
1. Assign a quiz to the learner.
2. complete the quiz.
3. login with coach and click on quizzes tab.
4. see progress report shows incorrect results.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![7-2](https://user-images.githubusercontent.com/12776071/52839757-27059280-311d-11e9-9595-8a8dc7cb4e32.png)
![7-1](https://user-images.githubusercontent.com/12776071/52839759-27059280-311d-11e9-8218-c655114fa2ea.png)

**Comment by indirectlylit** [comment]
I'm not able to reproduce.

Would you mind testing again with beta6?

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri 0.12.0b9. It is working as expected.

**Comment by indirectlylit** [comment]
thank you
