### ISSUE TITLE
Coach lessons progress not automatically updated

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5070]
### Observed behavior
I have this [video file](https://drive.google.com/file/d/1nGhM0mNdidD2hZmNM6iH6uLVByQ0Mt33/view) showing a learner Carlo logged-in and viewing a lessons. At the coach lesson reports page Carlo progress indicated has not yet started.

### Expected behavior
The learner lessons progress should automatically updated at the coach lesson reports page.

### Errors and logs
![screen shot 2019-02-15 at 8 14 01 pm](https://user-images.githubusercontent.com/8663934/52856417-4cb38b80-315f-11e9-9ff2-7adf1630aa41.png)

### Context

 * Kolibri version: 0.12-beta6
 * Operating system: macOS 10.13
 * Browser: Safari 11.0.3

**Comment by indirectlylit** [comment]
I was not able to immediately reproduce. some questions:

1. is this specific to Safari?
2. if you refresh the report, does the progress show correctly?
3. are there any client or server errors?

**Comment by mrpau-richard** [comment]
> 1. is this specific to Safari?

I can also reproduced it on Firefox `62.0.3`
![screen shot 2019-02-18 at 5 51 14 pm](https://user-images.githubusercontent.com/8663934/52942399-e53b4d00-33a5-11e9-8566-77cc8e2c9ed0.png)


> 2. if you refresh the report, does the progress show correctly?

Yes, the learner progress will update correctly

> 3. are there any client or server errors?

I have these browser errors on Safari 11.0.3 
![screen shot 2019-02-18 at 5 36 11 pm](https://user-images.githubusercontent.com/8663934/52942033-11a29980-33a5-11e9-9d61-608156d1a354.png)
![screen shot 2019-02-18 at 5 29 20 pm](https://user-images.githubusercontent.com/8663934/52942531-216ead80-33a6-11e9-9bba-2f6548fdeeb1.png)

**Comment by indirectlylit** [comment]
looks like the errors are from adding source maps - refs #4983

**Comment by indirectlylit** [comment]
(the map errors are the  same as https://github.com/learningequality/kolibri/issues/5091)

**Comment by jonboiser** [comment]
I'm not able to reproduce this on beta9. For me, one possible culprit of this happening in prior betas is the way notification IDs are converted from numbers to strings (they come over the wire as numbers, but might get converted to string via the resource layer or something). This matters because a lot of important logic tries to find the maximum of the IDs for the purposes of polling (getting the correct ID to  query the 'after=' param), or formatting messages (and lexical order is not the same as numeric ordering). I've had to patch this in areas by reconverting them to numbers where it's really important.

**Comment by indirectlylit** [comment]
@mrpau-richard mind testing again in beta10 tomorrow?

@jonboiser @rtibbles if IDs are being inappropriately transformed to strings by the resource layer, maybe there's a systematic way to prevent it? I know we're gone back and forth on this, including some recent work @ralphiee22 did

**Comment by rtibbles** [comment]
We explicitly force ids to be strings: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/api-resource.js#L249 as per #1255

This is deliberate, and by design.

**Comment by indirectlylit** [comment]
yeah, I guess I would have preferred having an opaque string-based ID, and then a separate integer-based counter field

**Comment by rtibbles** [comment]
Seems like this is not being reproduced in new betas, please reopen if it recurs.
