### ISSUE TITLE
learner 'started' measurement is not correct on content cards when there are 0 correct answers

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5078]
### Observed behavior

correct:

> ![image](https://user-images.githubusercontent.com/2367265/52893081-8d0a0e00-314d-11e9-908f-c417031e89e8.png)

incorrect:

> ![image](https://user-images.githubusercontent.com/2367265/52893100-bcb91600-314d-11e9-9b2b-25bf8a097bca.png)

### Expected behavior

should be started when an attempt has been made

### User-facing consequences

inconsistency

### Errors and logs

none

### Steps to reproduce

start an exercise but don't get any questions correct

### Context

0.12.0 beta 6

**Comment by indirectlylit** [comment]
@ralphiee22 does this touch on the work that you're doing?

**Comment by rtibbles** [comment]
Fixed in #5144
