### ISSUE TITLE
`Select all` checkbox label for channel (sub)topics is hidden in Chrome

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5082]
### Observed behavior

First [noticed](https://github.com/learningequality/kolibri/pull/4997#issuecomment-462197042) in #4997. (cc @rtibbles )

Label for the `Select all` checkbox for channel (sub)topics seems hidden in Chrome (displays correctly in Firefox), and it reappears when  the `overflow-x: hidden` property is unchecked.

![overflow](https://user-images.githubusercontent.com/1457929/52542196-473bf700-2d95-11e9-9285-bd6da73e7f00.gif)

### Expected behavior
Correctly displayed label.

### User-facing consequences
Uncertainty what the checkbox is for.

### Errors and logs
…

### Steps to reproduce
Select channel to import
Observe the topics when the DB is loaded

### Context
 * Kolibri version: 0.12-beta7 DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: Chrome 72.0.3626.109

**Comment by indirectlylit** [comment]
fixed when #5100 is merged
