### ISSUE TITLE
Sometimes learn tab displays "no channels"

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5083]
### Observed behavior

I'm wondering if there are any issues or updates since 0.10.2 that have targeted and fixed this? I couldn't find any.

Reported issue from a user:

> Sometimes when one logs in using the client device, it doesn't show the channels instead it says 'there are no channels but you can start importing them from studio.' This has happened twice while using the raspberry pi and once in one of the client devices in the field, but when you refresh at least twice the channels appear.

### Expected behavior

Should not fail like this.. either fully load the installed channels or fail with a real error, not something that says that no channels are installed?

### User-facing consequences

Users might not think Kolibri works, since it's not common to try and refresh

### Errors and logs

Unfortunately none, but will ask.

### Steps to reproduce

Not sure if the Raspberry Pi 2 plays a role.

### Context

Kolibri 0.10.2 on a Raspberry Pi 2.

**Comment by indirectlylit** [comment]
> Sometimes when one logs in using the client device, it doesn't show the channels instead it says 'there are no channels but you can start importing them from studio.' This has happened twice while using the raspberry pi and once in one of the client devices in the field, but when you refresh at least twice the channels appear.

sounds like either the clients had some info cached and weren't actually hitting the server, or they've somehow got multiple installations of kolibri running concurrently?

**Comment by benjaoming** [comment]
The report had more indications of overload or unresponsiveness of some sort. We asked many times in regards to ghost kolibri processes but never found one, the reporter was quite confident with `ps ax | grep kolibri` :)

**Comment by arky** [comment]
@benjaoming  I have seen this problem with Kolibri on hardware with slower network and I/O on both Raspberry Pi B+ and older i586 hardware that I refurbish as digital libraries for schools and communities. 

Unfortunately I don't have much debugging information to give you precise cause of these failures.   

Possibly related to similar issues we faced on Raspberry Pi pip installs. 
https://github.com/learningequality/kolibri/issues/4040#issuecomment-42475789

Also related to overall poor performance on low-end hardware:  
https://github.com/learningequality/kolibri/issues/5348

**Comment by rtibbles** [comment]
Closing this as stale, please reopen if it recurs.
