### ISSUE TITLE
'Ungrouped' learners when deleting groups

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5084]
### Observed behavior

Before the change of how the groups were formed, the phrase `Learners within this group will become 'Ungrouped'` during the group deletion made sense because there was a `Ungrouped` block on the groups page. However, that is not the case anymore, so this string might cause confusion.

![ubuntu 16 04 3 start running - oracle vm virtualbox_404](https://user-images.githubusercontent.com/1457929/52922948-1fb0d580-3325-11e9-9cca-c41595c4384c.png)

Maybe the easiest thing would be to not include this string in the modal...? 
@khangmach @jtamiace @indirectlylit thoughts?

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: 0.12-beta7 DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: Chrome 72.0.3626.109

**Comment by indirectlylit** [comment]
> Maybe the easiest thing would be to not include this string in the modal...?

agreed

**Comment by khangmach** [comment]
Let's axe the string! Also...should we think about introducing character limits? Or do you think that would hinder translations?

**Comment by radinamatic** [comment]
Actually, that was _under_ the limit... :joy: 
I was testing if the field limit validation works, but I agree that 50 chars might be too long.

**Comment by indirectlylit** [comment]
fixed when #5100 is merged
