### ISSUE TITLE
Missing checkbox label and alignment issue on 'Enroll learners into group'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5085]
### Observed behavior

Vertical alignment of the `Full name` label is inconsistent with the rest of the rows.

![ubuntu 16 04 3 start running - oracle vm virtualbox_405](https://user-images.githubusercontent.com/1457929/52923355-b088b080-3327-11e9-8793-bf1c4fc46084.png)

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: 0.12-beta7 DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: Chrome 72.0.3626.109 & Firefox 65

**Comment by radinamatic** [comment]
I just now realized that the `Full name` is not actually the label for the checkbox - the label should be `Select all`, and it's missing... :confused:

**Comment by jonboiser** [comment]
Would tooltip saying "select all" over the first checkbox be acceptable? Having a displayed label would widen the first checkbox column. And we still need that "full name" header for the second column.

**Comment by jonboiser** [comment]
We could remove "full name" and leave it implied (like the "topic/content" header is implied in the content import/export listing) and use that space for "select all"

**Comment by indirectlylit** [comment]
I don't think we should remove the header completely, but rather make it visually hidden so that screen readers still read it.

I'm pushing a change to also fix the layout so the checkbox label doesn't wrap to two lines:

> ![image](https://user-images.githubusercontent.com/2367265/53104711-bbd50b00-34e4-11e9-8757-8a14784ac06f.png)

**Comment by indirectlylit** [comment]
fixed when #5100 and [jonboiser#4](https://github.com/jonboiser/kolibri/pull/4) are merged
