### ISSUE TITLE
'Go back' from added resource to lesson could be clearer

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5086]
### Observed behavior
(back to) `Coach` is not the most precise indication, after previewing and adding resource to a lesson.
Maybe (back to) `Manage resources`...? 
We already have the string, right @indirectlylit?

![ubuntu 16 04 3 start running - oracle vm virtualbox_407](https://user-images.githubusercontent.com/1457929/52924713-28f27000-332e-11e9-9af0-a6d0327c17bc.png)

### Expected behavior
Clearer indication where the user is going to go.

### User-facing consequences

Lack of clarity where the link leads to.

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: 0.12-beta7 DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: Chrome & Firefox

**Comment by jonboiser** [comment]
It's possible that it did say "Manage resources" before and might have changed in some refactoring.

**Comment by radinamatic** [comment]
Yeah, I had the same impression that was the case... Could we have it back, please? :slightly_smiling_face:

**Comment by indirectlylit** [comment]
fixed when #5100 is merged
