### ISSUE TITLE
Obsolete string in the 'Delete lesson' modal

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5087]
### Observed behavior
This one does not seem to make sense any more...?

![ubuntu 16 04 3 start running - oracle vm virtualbox_408](https://user-images.githubusercontent.com/1457929/52926535-6a871900-3336-11e9-9e54-e14ba5d3070b.png)

### Expected behavior
…

### User-facing consequences
Confusing message, no way to check _progress by Channels_ in this release.

### Errors and logs
…

### Steps to reproduce
…

### Context
…

**Comment by indirectlylit** [comment]
lowered to 'important' - critical is reserved for the hopelessly broken

**Comment by radinamatic** [comment]
Agreed, this is not _hopeless_... :slightly_smiling_face:

**Comment by indirectlylit** [comment]
fixed when #5100 and https://github.com/jonboiser/kolibri/pull/4 are merged
