### ISSUE TITLE
Learn tab when no content.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5088]
### Observed behavior
It shows error when there is no channel imported in the kolibri

### Expected behavior
It must show there is no error kind of error.

### Steps to reproduce
1. Go to the learn tab when there is no channel imported in the system.

### Context

 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshots
![1](https://user-images.githubusercontent.com/12776071/52947885-fc763c80-339d-11e9-9542-5090196b34c9.png)

**Comment by swapnil106111** [comment]
It is showing same error when there is channel imported in the system.
We have installed a pex of version Kolibri 0.12.0b4.

**Comment by swapnil106111** [comment]
After restarting the server, everything is working fine.

**Comment by ralphiee22** [comment]
Was unable to reproduce using beta7 pex, upon going through the setup wizard. Using OSX and chrome.

**Comment by indirectlylit** [comment]
@swapnil106111 if you can provide us with steps to repro we'll follow up

**Comment by swapnil106111** [comment]
@indirectlylit After installing a pex of kolibri 0.12.0b4, we faced this issue. But after restarting the server this issue gets resolved.

We did not see such behaviour for debian installer.

**Comment by indirectlylit** [comment]
okay - if you see it again, please let us know

**Comment by swapnil106111** [comment]
@indirectlylit Tested on kolibri 0.12.0b8. Working as expected.

![1](https://user-images.githubusercontent.com/12776071/53158476-af86a600-35e9-11e9-84d9-c647de17946e.png)
