### ISSUE TITLE
On Profile page, there is no error when trying to change username to one that already is used

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5089]
### Observed behavior
When facility Allow learners and coaches to edit their username is checked. Learner is able to change the username but when it change it with existing username, it must show a error.

### Expected behavior
It must show a error when we are changing username with existing username.

### Steps to reproduce
1. Login with learner.
2. Go to the profile.
3. Change the username with existing username and checked.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
When changing username with existing username, it must show a error. But here it is not showing any error.

![1](https://user-images.githubusercontent.com/12776071/52948708-20d31880-33a0-11e9-8b92-e82041eaa4a5.png)

**Comment by swapnil106111** [comment]
Same issue arising when login with admin account and trying to change the username with existing username.

**Comment by rtibbles** [comment]
Fixed in #5192

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.12.0b12. It is working as expected.

![1](https://user-images.githubusercontent.com/12776071/53627088-7ecbef80-3c2d-11e9-9230-c0be95ccbf8b.png)
