### ISSUE TITLE
Sourcemap file paths incorrect on Safari 11.0.3

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5091]
### Observed behavior
I have these console errors on Safari 11.0.3
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (coach_side_nav-0.12.0b7.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (facility_management_side_nav-0.12.0b7.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (user_module_login_nav_side_nav-0.12.0b7.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (user_module_user_profile_nav_side_nav-0.12.0b7.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (device_management_side_nav-0.12.0b7.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (learn_module_side_nav-0.12.0b7.js.map, line 0)
```
These errors showing on Learn, Coach and Facility pages

### Expected behavior
Should fix those Safari console errors.

### Errors and logs
![screen shot 2019-02-18 at 7 41 16 pm](https://user-images.githubusercontent.com/8663934/52948853-a01f1700-33b5-11e9-9a0f-3515d7070207.png)

### Context
 * Kolibri version: 0.12-beta7
 * Operating system: macOS 10.13.3
 * Browser: Safari 11.0.3

**Comment by indirectlylit** [comment]
possibly a packaging issue - source maps maybe not being bundled?

**Comment by rtibbles** [comment]
This appears to be a path issue - it is not fetching them from the location I would expect.

**Comment by indirectlylit** [comment]
This does not appear to have user-facing consequences.

(@mrpau-richard FYI, rather than deleting the 'user-facing consequences' section of the issue template, it's helpful to explicitly say whether or not there are any)

**Comment by jonboiser** [comment]
This looks to be working for me right now, but the DX isn't great: webpack hosts multiple resources for a single JS/Vue file, and you need to find the one without a `?hash` in its URL to get the real JS source.

![CleanShot 2021-02-22 at 17 27 35](https://user-images.githubusercontent.com/10248067/108791482-09513c00-7534-11eb-8a23-e28dacb667db.png)
