### ISSUE TITLE
issues loading exercises and playing audio in Maharashtra State content channel

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5094]
### Observed behavior
While playing videos on kolibri, there is no sound.

Also exercises are not loading:

* Channel ID : 8fc515793aad4e52b490b03c48ad21de
* Path : Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 - >1 Introduction to Geometrical Figures ->KA Resources -> Revision ->Name shapes 1

> ![1](https://user-images.githubusercontent.com/12776071/52994422-7f9a9f80-343d-11e9-93aa-3dd432456379.png)

### Expected behavior
There must be a sound for a video and exercises must load.

### Steps to reproduce
1. Play video and see.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : ubuntu 14.04
 * Browser : Chrome

**Comment by indirectlylit** [comment]
cannot reproduce.

please include any errors and the specific content you're having trouble with

**Comment by indirectlylit** [comment]
also please test with [beta 7](https://github.com/learningequality/kolibri/releases/tag/v0.12.0-beta7)

**Comment by swapnil106111** [comment]
@indirectlylit Tested on Kolibri 0.12.0b9. Still facing same issue.

Channel ID : 8fc515793aad4e52b490b03c48ad21de

Path : Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 - >1 Introduction to Geometrical Figures ->KA Resources  -> Revision -> Cousin Fal's shape collection

**Comment by indirectlylit** [comment]
I can reproduce this, but only with that video - other videos play fine. When I view the video in the KA channel the audio also plays fine.

How were these videos curated?

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.12.0b12. Not able hear audio for any KA video.

Path : Maharashtra State Class 3 to 9 (English) - BalBharati - 3 - 12 Division - KA resources - Intro to remainders

Checked with two/three videos but facing same issue.

**Comment by indirectlylit** [comment]
@swapnil106111 as indicated above, this and #5095 appear to be issues with the content in channel `8fc515793aad4e52b490b03c48ad21de`

Could you please test the same content from the official KA channel and confirm that audio works there? How was the Maharashtra State channel created?

**Comment by indirectlylit** [comment]
updated issue to also include #5095

**Comment by yogeshmhaskule** [comment]
Tested on kolibri 0.12.0. still getting the same page. added screenshot below:-
![ka_content](https://user-images.githubusercontent.com/7850420/53799763-26645d00-3f61-11e9-85ac-a068d0094d79.png)

**Comment by rtibbles** [comment]
As noted above, this is an issue with the channel in question. Images are missing from the published exercises.

**Comment by indirectlylit** [comment]
@amit3107 the issues you were seeing in #5702 are likely the same as these, and will have to be addressed by who ever published the channel

**Comment by indirectlylit** [comment]
@Marshall-B the issues you were seeing in #5708 are likely the same as these
