### ISSUE TITLE
Questions not loading for KA content.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5095]
### Observed behavior
No question content is loading  for KA content but showing for magogenie.

### Expected behavior
It must show content for all content provider.

### Steps to reproduce
1. Solve KA exercise.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/52994422-7f9a9f80-343d-11e9-93aa-3dd432456379.png)

**Comment by indirectlylit** [comment]
please test with [beta 7](https://github.com/learningequality/kolibri/releases/tag/v0.12.0-beta7)

**Comment by swapnil106111** [comment]
@indirectlylit Still facing same issue on Kolibri 0.12.0b9.

Channel ID : 8fc515793aad4e52b490b03c48ad21de
Path :  Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 - >1 Introduction to Geometrical Figures ->KA Resources -> Revision ->Name shapes 1

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53224655-86265280-369b-11e9-9dff-1da0dfc400db.png)

**Comment by indirectlylit** [comment]
I'm seeing the same behavior as in https://github.com/learningequality/kolibri/issues/5094#issuecomment-466303213

I can reproduce from the Maharashtra State channel but not KA:

| Maharashtra | KA | 
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/53227150-4d05c800-3632-11e9-8850-b883cb3a4b6d.png) | ![image](https://user-images.githubusercontent.com/2367265/53227167-5a22b700-3632-11e9-95a8-f02d4a5eb8dd.png)|

**Comment by rtibbles** [comment]
@swapnil106111 can you test this same question with the latest 0.9.5 beta that is being used in the field? This is looking like a content issue, rather than a Kolibri issue.

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri 0.12.0b. Facing same issue.

**Comment by indirectlylit** [comment]
consolidating with #5094
