### ISSUE TITLE
No content available after pressing back button in exam.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5097]
### Observed behavior
After submitting the exam, press back button of the chrome. You will see "No content channels available".

Please see screenshots for more info.

### Steps to reproduce
1. Create the exam.
2. Submit the exam.
3. After submitting the exam, press back button of the chrome and see the behaviour of the kolibri.

### Context
 * Kolibri version :  Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser  : chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53009314-4116dc00-3461-11e9-9b75-e1ff941d8fd0.png)
![2](https://user-images.githubusercontent.com/12776071/53009312-4116dc00-3461-11e9-818c-1931db93bba9.png)
![3](https://user-images.githubusercontent.com/12776071/53009311-4116dc00-3461-11e9-85b9-e65a2744d4bd.png)
![4](https://user-images.githubusercontent.com/12776071/53009310-407e4580-3461-11e9-9f56-0d34af54813a.png)

**Comment by jonboiser** [comment]
I think this is the line causing https://github.com/learningequality/kolibri/blob/8b380275b72f0471bef89ef0d3705fa9ea348cd7/kolibri/plugins/learn/assets/src/modules/examViewer/handlers.js#L47-L50

What does that else-if branch mean?

I think the solution to this issue is to have a better Page explaining that you can't work on a closed exam.

**Comment by indirectlylit** [comment]
Since the report is available as soon as the exam is closed, I think we should redirect them to the report page.

Perhaps more elegantly, the report and exam could share the same URL and display differently depending on whether the learner has submitted it

**Comment by yogeshmhaskule** [comment]
Checked it in kolibri 0.12.0. woking as expectted
![exam_error2](https://user-images.githubusercontent.com/7850420/53798906-37ac6a00-3f5f-11e9-9454-e877a0c8ae63.png)
![exam_error_1](https://user-images.githubusercontent.com/7850420/53798907-37ac6a00-3f5f-11e9-9099-dbbd94d95a57.png)
