### ISSUE TITLE
View button is not working while creating quiz.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5098]
### Observed behavior
While creating exam, there is a view button on resource.But it is not working.

### Expected behavior
According name of button, it must show a content of the resource.

### Steps to reproduce
1. Create quiz and click on view button of the exercise resource.

### Context
 * Kolibri version :  Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53009818-5d674880-3462-11e9-8305-6b7c0f9ba636.png)

**Comment by jonboiser** [comment]
@swapnil106111 	Does clicking the card still work? Clicking "view" is supposed to expand the description of the exercise if it is long, but this one does not have one (so there should be no "view" button".

**Comment by jonboiser** [comment]
To fix this issue, remove the "View" button when there is no description at all.

**Comment by indirectlylit** [comment]
fixed when #5100 is merged

**Comment by yogeshmhaskule** [comment]
tested on kolibri 0.12.0. worked as expected. 
![exam_view_1](https://user-images.githubusercontent.com/7850420/53799197-df299c80-3f5f-11e9-9a0a-5d56e048e5d7.png)
![exam_view_2](https://user-images.githubusercontent.com/7850420/53799198-dfc23300-3f5f-11e9-85fc-ada33d222d29.png)
