### ISSUE TITLE
exercise file has error in Learners report

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5099]
### Observed behavior

This error occurs when I create a lesson and have an exercise file. After that, I go to Report page at Learner report and check the individual report of learners.

![error_at_learners_report](https://user-images.githubusercontent.com/38421180/53012123-15a1ea80-347d-11e9-87e6-e887189ce150.png)

Even the learners not begin, there is already answered.
![screenshot from 2019-02-19 19_28_43](https://user-images.githubusercontent.com/38421180/53012130-1b97cb80-347d-11e9-9009-b1cc5fc80fa6.png)

### Steps to reproduce

1. Login as Coach Facility
2. Create a lesson with an exercise file
3. Go to Learners Report page, select a learner and check individual the lesson you made.

### Context

Kolibri 0.12.0 beta 7
Ubuntu 14.04 (64bits)
Firefox 65.0(64bits)

**Comment by indirectlylit** [comment]
This should be addressed by the work @ralphiee22 is doing in #5032
