### ISSUE TITLE
Quiz title validation not consistent on all stages of creation

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5101]
### Observed behavior
If I try to title a quiz the same title as another quiz that already exists, there should be consistent error validation message. This isn't the case however as it doesn't appear on step 1 of the quiz creation interface. Seen here:

<img width="748" alt="screen shot 2019-02-19 at 2 57 34 pm" src="https://user-images.githubusercontent.com/25045166/53053859-7e766c00-3457-11e9-81f9-2cb0f7c12c27.png">

There IS correct error validation text in the other places though:

<img width="499" alt="screen shot 2019-02-19 at 3 08 45 pm" src="https://user-images.githubusercontent.com/25045166/53054050-08263980-3458-11e9-9ca5-283095ecdb0e.png">

<img width="763" alt="screen shot 2019-02-19 at 2 57 26 pm" src="https://user-images.githubusercontent.com/25045166/53053928-a82f9300-3457-11e9-8ebc-f2c193b45de6.png">

### Expected behavior
Error validation message on all steps. 

### User-facing consequences
User confusion and all that

### Steps to reproduce
- Click on NEW QUIZ
- Try to give the new quiz a title that already exists
- No error validation msg

### Context
Tell us about your environment, including:
 * Kolibri version - Beta
 * Operating system - MacOS Sierra
 * Browser - Chrome

**Comment by indirectlylit** [comment]
related: https://github.com/learningequality/kolibri/pull/4777 (cc @ralphiee22)

I don't think this is critical for 0.12 because it at least warns before you create, right?

**Comment by ralphiee22** [comment]
Validation only happens on submit events.
So the desired behavior is validation as you type?

**Comment by indirectlylit** [comment]
great point - thanks
