### ISSUE TITLE
On (at least) one modal, dismissing with enter keypress causes it to come back

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5103]
### Observed behavior

This was seen with the privacy modal, and is in other places now:

1. Facility > Class Details > Rename Class
1. Privacy link on sign-in page
1. Privacy link on sign-up page
1. Profile page, change password modal
1. "Change" status button for Lessons

It seems to be for the same reasons as #4973 (privacy modal), the "Edit" button maintains focus while the modal is on, so it gets "clicked" again when you dismiss the modal with an Enter keypress.

The common thing between these two cases is that the privacy link and rename use the text-link versions of the Button.

### Expected behavior

Text-type links do not have this side-effect when "clicked" by an enter-keypress

### Context

Kolibri 0.12 latest

**Comment by indirectlylit** [comment]
> The common thing between these two cases is that the privacy link and rename use the text-link versions of the Button.

iiinteresting

**Comment by radinamatic** [comment]
I can confirm that the issue is fixed for the privacy modal opened from the sidebar, but this is still extant on the privacy modal in the setup wizard in `beta9`... :confused: 

Context: both Firefox 65 and Chrome 72 on Ubuntu 16.04

cc @jonboiser

**Comment by jonboiser** [comment]
This is going to require more hacks specific to the Setup Wizard, since there is some unusual behavior with using the keyboard in the Setup Wizard.

The reason this happens is because on the privacy info page, we have some code that manually focuses the "more information" button for user convenience. since it's focused the button reacts to the enter-keypress from both the modal as well as the superuser form in the previous step. 

One hack I found that seems to work is to delay this autofocusing for about 200ms so that it misses the enter-keyup event.

**Comment by rtibbles** [comment]
Could we also prevent propagation of the click event, once the modal has been closed? Either by explicitly cancelling it, or using the `.stop` event modifier?

**Comment by jonboiser** [comment]
The implementation of KButton actually does use this event with modifiers `@keyup.enter.stop.prevent="handelPressEnter"`. I don't think it's an issue of propagation since I don't think the Modal "close" button and the main window "more information" button are linked that way.

One weird thing I noticed in the devtools is that if you hit enter, you get two "click" events: one with a MouseEvent in its $event payload, and another with a $KeyboardEvent.

If you click with mouse, you only get the MouseEvent

**Comment by radinamatic** [comment]
@jonboiser @rtibbles  Hack seems to be working when I invoke the setup wizard on the release branch after the merge! :+1: :100:
