### ISSUE TITLE
Disabled buttons aren't styled with the lighter color

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5104]
### Observed behavior

Buttons that are disabled by the UI should be a little bit lighter than the purple primary that is used for enabled buttons.

Example from Select Network Address modal (there are no network locations and "Continue" is disabled)

![screen shot 2019-02-19 at 5 26 38 pm](https://user-images.githubusercontent.com/10248067/53059395-88a26580-346b-11e9-9000-703486b391e7.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
caused a regression: 
![image](https://user-images.githubusercontent.com/2367265/53193954-22325a00-35c7-11e9-8035-0d3dfa84b139.png)
