### ISSUE TITLE
In Learn, a topic is "completed" when it is not really

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5105]
### Observed behavior

Notice that the topic has the "completed" star, but not all of it's sub topics are completed

![screen shot 2019-02-19 at 5 41 35 pm](https://user-images.githubusercontent.com/10248067/53059970-ad97d800-346d-11e9-8722-014c2c6b66fe.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jonboiser** [comment]
I went back to the topic, and the icons are behaving as expected. Might be a state-pollution issue.

**Comment by jonboiser** [comment]
Found the converse issue. Topic should be complete. NOt sure how to reproduce this. The mismatch in this screenshot seems persistent though.

![screen shot 2019-02-19 at 5 44 52 pm](https://user-images.githubusercontent.com/10248067/53060098-167f5000-346e-11e9-93b3-70a623731100.png)

**Comment by indirectlylit** [comment]
cc @ralphiee22 I know you're looking at this stuff... maybe you'll be able to shed some light eventually

**Comment by ralphiee22** [comment]
related https://github.com/learningequality/kolibri/issues/5078

**Comment by indirectlylit** [comment]
see also #5132

**Comment by rtibbles** [comment]
Fixed in #5144
