### ISSUE TITLE
0 of 0 have started showing in class home quiz.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5107]
### Observed behavior
There are two learner in the class but instead of submitting quiz by one learner it shows 0 of 0 have started in class home.

### Steps to reproduce
1. Assign a quiz to the class.
2. Submit the exam.
3. See the result in the class home in coach tab.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53070400-0bc3ca00-3505-11e9-8a61-1bbb07720e15.png)

![2](https://user-images.githubusercontent.com/12776071/53070407-10887e00-3505-11e9-919e-96271dd5003b.png)

**Comment by indirectlylit** [comment]
please test again in beta 7

**Comment by rtibbles** [comment]
Is this still extant?

**Comment by mrpau-julius** [comment]
This issue fix in the latest release Kolibri 0.12.0
