### ISSUE TITLE
Activity tab in learner tab in coach report does not list activity

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5108]
### Observed behavior
Activity tab under the learners in coach report shows nothing for a learner.

### Expected behavior
It must show a activities in activity tab.

### Steps to reproduce
1. Submit quiz, lesson and go to the coach report in learner tab for perticular user and see the behaviour.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot

Report tab 
![report](https://user-images.githubusercontent.com/12776071/53072811-43824000-350c-11e9-99f2-3b957805ddce.png)

Activity tab
![activity](https://user-images.githubusercontent.com/12776071/53072818-4715c700-350c-11e9-9f8c-4945efa9d4c1.png)

**Comment by indirectlylit** [comment]
please test again in beta 7

**Comment by rtibbles** [comment]
Is this still extant in the latest beta?

**Comment by mrpau-julius** [comment]
I test this issue, also fix in latest release Kolibri 0.12.0
