### ISSUE TITLE
Lesson report for group.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5111]
### Observed behavior
When we are clicking on lesson report for groups, it does not load any page.

### Expected behavior
It must load a page.

### Steps to reproduce
1. Assign a lesson.
2. go to coach report  and click on groups.
3. Click on group name and click on exercise and see behaviour.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome 

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53086335-e5188a00-352a-11e9-9be6-73b7642230a9.png)

**Comment by indirectlylit** [comment]
I can reproduce this in the latest beta.

My guess is that it's probably happening on items with no progress, so it's sort of the 'group' version of #5099 and relates to #5032

**Comment by yogeshmhaskule** [comment]
Tested in kolibri.0.12.0. And worked as expected.
![lesson_error_1](https://user-images.githubusercontent.com/7850420/53868375-ed3cf300-401b-11e9-8375-9a7523d72ca5.png)
![lesson_error_2](https://user-images.githubusercontent.com/7850420/53868376-edd58980-401b-11e9-9e1b-8c26ab629b9a.png)
