### ISSUE TITLE
Facility name is missing on the Facility Settings page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5117]
### Observed behavior
The name should be under the "Facility" header, and the `facilityConfig` module is not set at all in the DevTools. (Changing and saving settings still works, though)

![screen shot 2019-02-20 at 11 24 33 am](https://user-images.githubusercontent.com/10248067/53118527-2779a100-3502-11e9-8fb7-b5feee9ee6d7.png)

Devtools

![screen shot 2019-02-20 at 11 25 54 am](https://user-images.githubusercontent.com/10248067/53118638-690a4c00-3502-11e9-8d54-27bfdcb0c079.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
I'm going to take this out of 0.12 since multiple facilities are still a very uncommon case

**Comment by rtibbles** [comment]
Fixed in #5233
