### ISSUE TITLE
Apply header-icon pairings consistently throughout pages

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5119]
### Observed behavior
On the username in Exam Reports
<img width="688" alt="Screen Shot 2019-05-13 at 2 54 52 PM" src="https://user-images.githubusercontent.com/10248067/57657091-21d6a900-758f-11e9-9d01-085bff793723.png">

On the class name in Coach Homepage

<img width="555" alt="Screen Shot 2019-05-13 at 2 53 52 PM" src="https://user-images.githubusercontent.com/10248067/57657036-f5bb2800-758e-11e9-8023-fd287854369e.png">

On the headers for channels when importing/exporting

<img width="943" alt="Screen Shot 2019-05-13 at 2 52 31 PM" src="https://user-images.githubusercontent.com/10248067/57656968-ca383d80-758e-11e9-8fd9-5b928d895876.png">

~On the headers for lesson resources (and probably for resources in learn browsing)~

<img width="711" alt="Screen Shot 2019-03-21 at 2 01 21 PM" src="https://user-images.githubusercontent.com/10248067/54784765-dbde1400-4be1-11e9-8b35-a56446fa4a5d.png">

~For example, in Coach > Plan > Lesson, the "Wednesday" lesson header could use a Lesson Icon to its left to match its corresponding page on Coach > Reportgs~

![screen shot 2019-02-20 at 12 01 13 pm](https://user-images.githubusercontent.com/10248067/53120773-72e27e00-3507-11e9-9055-ef86d3235f55.png)

~Similarly, in Facility > Classes > Edit Class, the "Class One" header could use an icon too (to match a similar page in Coach Reports)~

![screen shot 2019-02-20 at 12 03 05 pm](https://user-images.githubusercontent.com/10248067/53120807-85f54e00-3507-11e9-90f6-adba1285bbc1.png)

~And again in  the user permissions page, we could add an icon next to the user name~

![screen shot 2019-02-20 at 12 08 37 pm](https://user-images.githubusercontent.com/10248067/53121126-4ed36c80-3508-11e9-92f2-4430128d6d6b.png)

* Classroom Name header on Class Homepage

### Expected behavior

Consistent symbology throughout the app, I suppose.

### Context

0.12 latest

**Comment by rtibbles** [comment]
For the lesson example, this appears to be related to: #5143

**Comment by rtibbles** [comment]
@jonboiser did a lot of work on this in #5233 - will leave it open until we have confirmed that all instances are covered.

**Comment by indirectlylit** [comment]
copying from thread thread: https://github.com/learningequality/kolibri/pull/5261#discussion_r268362347

two other examples to consider for consistency include coach tools and content cards:

> ![image](https://user-images.githubusercontent.com/2367265/55105926-aaf75680-509b-11e9-8f52-4993fa0d3439.png)

> ![image](https://user-images.githubusercontent.com/2367265/55105975-c2ceda80-509b-11e9-8490-b71aafe50b9e.png)

**Comment by jonboiser** [comment]
Closing this, since all the areas in the OP have been addressed as of #5524. In future UIs, make sure a useful icon accompanies a name header, to more quickly orient the user :+1:
