### ISSUE TITLE
Text-button hover state changes the epub theme colors

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5120]
### Observed behavior
Hovering or mousing over an epub theme color causes it to change color to the hover grey color. See screenshots below:

**BEFORE (beige, 2nd color)**
<img width="291" alt="screen shot 2019-02-20 at 10 56 51 am" src="https://user-images.githubusercontent.com/25045166/53128341-81399580-3519-11e9-8a97-606f40f90804.png">

**DURING HOVER**
<img width="287" alt="screen shot 2019-02-20 at 10 56 57 am" src="https://user-images.githubusercontent.com/25045166/53128361-8a2a6700-3519-11e9-8794-1821a5e3329d.png">

### Expected behavior
Colors not to change

### User-facing consequences
Misleading color change

### Steps to reproduce
1. Open an epub
2. Hover over any theme color

**Comment by jonboiser** [comment]
#5153
