### ISSUE TITLE
Exam report for learner when no content.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5125]
### Observed behavior
When learner gives assigned exam and then submit it. After that, we have deleted a channel on which we have created exam. When learner try to click on submitted exam after deleting the channel, it will open blank page.

### Expected behavior
It must handle such situation.

### Steps to reproduce
1. Create exam on a channel.
2. Submit the exam with learner account.
3. Then delete the channel on which you have created a exam.
4. Then click on submitted exam.

### Context
 * Kolibri version : Kolibri 0.12.0b8
 * Operating system : Ubuntu 14.04 
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53161265-aef10e00-35ef-11e9-8d51-2a51f3410cd9.png)

![2](https://user-images.githubusercontent.com/12776071/53161274-b44e5880-35ef-11e9-8b67-1a104b1c8efd.png)

**Comment by indirectlylit** [comment]
thanks @swapnil106111  

cc @jonboiser - this 'report' case should be covered under #5049 also

**Comment by yogeshmhaskule** [comment]
tested in kolibri 0.12.0. don't know its expected output. Its not a blank page.I have attached images here:-
![exam_1](https://user-images.githubusercontent.com/7850420/53871720-d1891b00-4022-11e9-8bbc-cf6e7cc1f2a7.png)
![exam_2](https://user-images.githubusercontent.com/7850420/53871721-d1891b00-4022-11e9-9fa0-4f4f9066ee1c.png)

**Comment by indirectlylit** [comment]
this is probably marginally more helpful than a blank page I imagine
