### ISSUE TITLE
Facility coach can be a learner on its own class

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5126]
### Observed behavior
Using a super admin account I can assign and enrol a Facility coach on both coaches and Learners in the same class.

### Errors and logs
![screen shot 2019-02-21 at 8 23 25 pm](https://user-images.githubusercontent.com/8663934/53169254-af9d9a80-3617-11e9-896f-e100734838b0.png)

### Context

Tell us about your environment, including:
 * Kolibri version: kolibri-0.12.0-Beta8
 * Operating system: Windows 7
 * Browser: FIrefox 65.0

**Comment by indirectlylit** [comment]
this is currently by design, because there's no other way for the coach to interact with their own lessons and quizzes - see #3492

we may need to revisit this in the future, but for now it's not a bug
