### ISSUE TITLE
Lesson with no resources will marked as completed at the class home page

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5128]
### Observed behavior
Lesson with no resources will marked as completed at the class home page

### Errors and logs
![screen shot 2019-02-21 at 8 55 44 pm](https://user-images.githubusercontent.com/8663934/53170663-a31b4100-361b-11e9-91c6-bc82616b9b2c.png)
![screen shot 2019-02-21 at 8 56 06 pm](https://user-images.githubusercontent.com/8663934/53170681-add5d600-361b-11e9-82b0-6cf8afc8abd0.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.0-beta8
 * Operating system: Windows
 * Browser: Firefox 65.0

**Comment by indirectlylit** [comment]
good catch! we have this one reported here: #5096

**Comment by mrpau-julius** [comment]
same issue found on kolibri 0.12.0 beta 12
![image](https://user-images.githubusercontent.com/38421180/53621748-68318400-3bac-11e9-97be-b1384e547051.png)
