### ISSUE TITLE
'started' icon in learner exercise header is shown too soon

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5132]
### Observed behavior

Shown  as soon as the learner opens the exercise

> ![image](https://user-images.githubusercontent.com/2367265/53214487-a86b9200-3601-11e9-884e-475823071a7e.png)

### Expected behavior

* should only be shown after first attempt
* follow-up from #5123
* see https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/ProgressIcon.vue#L61

### User-facing consequences

slight inconsistency

### Errors and logs

none

### Steps to reproduce

open an exercise but don't start it

### Context

0.12.0 beta 8c

**Comment by rtibbles** [comment]
Fixed in #5144
