### ISSUE TITLE
Error while viewing the difficult questions tab

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5133]
### Observed behavior

reported by @radinamatic :

Error while viewing the difficult questions tab:

![difq](https://user-images.githubusercontent.com/1457929/53212063-c8bc4080-3643-11e9-8654-faeabc689d09.gif)

And nothing available to c/p for the error details:

![2019-02-22_1-41-53](https://user-images.githubusercontent.com/1457929/53212117-f73a1b80-3643-11e9-8fd9-c5c697fd4367.png)

This is with a fresh DB and no previous interactions whatsoever.

### Expected behavior

no error and page shows.

@rtibbles mentioned it looks like we're getting passed the content node ID rather than the content ID when through the URL parameters

### User-facing consequences

broken report page

### Errors and logs

none

### Steps to reproduce

…coming soon...

### Context

0.12.0 beta 8

**Comment by radinamatic** [comment]
### Steps to reproduce

1. Start with a fresh DB
2. Create a lesson and activate
3. Sign in as a learner, start the exercise and give an incorrect answer to a question
4. Sign in as a coach and go to *Coach > Reports > Lessons > '<lesson>' > *Difficult questions* subtab
5. Click on the question

**Comment by radinamatic** [comment]
Extant again on `beta11` 

![difq](https://user-images.githubusercontent.com/1457929/53597535-b9d51100-3ba2-11e9-8752-1c9cdadeb6fd.gif)

[server.log](https://github.com/learningequality/kolibri/files/2916836/server.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/2916837/kolibri.log)

cc @rtibbles
