### ISSUE TITLE
Channel options button empty

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5137]
### Observed behavior
Channel options button display empty during the content import.

### Expected behavior
Should display the text option button during content import.

![screen shot 2019-02-22 at 4 28 54 pm](https://user-images.githubusercontent.com/8663934/53229800-28583180-36c0-11e9-8abe-3910f24c41e7.png)

### Context

Tell us about your environment, including:
 * Kolibri version: kolibri-0.12.0-beta9
 * Operating system: Windows 10
 * Browser: Firefox 65.0

**Comment by indirectlylit** [comment]
thanks - this is documented in https://github.com/learningequality/kolibri/issues/5104#issuecomment-466121475
