### ISSUE TITLE
Super-admin-export-data.feature file need to update

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5138]
### Observed behavior

I see the download button is disabled.
In order to export the data, need to generate first before enable to click the download button.
https://github.com/learningequality/kolibri/blob/v0.12.0-beta9/integration_testing/features/super-admin/super-admin-export-data.feature

![super-user-export-data feature is need to update](https://user-images.githubusercontent.com/38421180/53231295-74ae5d80-363d-11e9-91fb-4ffef5ad0daf.png)

### Context

* Kolibri version 0.12.0 beta 9
 * Operating system Windows 10
 * Browser Firefox 65.0.1 (64-bit)

**Comment by indirectlylit** [comment]
good catch! should I assign it to you?

**Comment by mrpau-julius** [comment]
sure @indirectlylit 👍

**Comment by indirectlylit** [comment]
cc @cpauya if you could review that'd be great!

**Comment by radinamatic** [comment]
@mrpau-julius You can assign @cpauya & me as a reviewers!

**Comment by radinamatic** [comment]
Fixed in #5357, closing!
