### ISSUE TITLE
add dead-link checks to all .rst and .md pages in repo

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5146]
### Observed behavior

we occasionally have dead links in our docs and readme, and other files

see e.g. #5145

### Expected behavior

linting should catch these for us

### User-facing consequences

frustration for new devs

**Comment by indirectlylit** [comment]
if and when we do this, we should also apply to the main docs -^

**Comment by jonboiser** [comment]
I think this is something we can just do manually every once in awhile (e.g. every month). I got a free software https://www.screamingfrog.co.uk/seo-spider/pricing/ that found some dead external links, and will make a follow up issue with details.
