### ISSUE TITLE
hard-code and conditionally display arabic translations of CC licenses

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5148]
### Observed behavior

we want to do https://github.com/learningequality/kolibri/issues/2371 but doing this through the standard crowdin flow is too time-consuming and risky this close to a release

however there is a strong need to have at least the arabic licenses translated:

> In order to make sure users use the content appropriately (the idea of licensing is not very clear to many [Middle East and North Africa] contexts) and to make sure we are doing our best to monitor that, I would push for having it translated

### Expected behavior

see https://creativecommons.org/licenses/?lang=ar for target licenses. Contact Hiba for assistance if necessary

Recommend we hard-code these into a JSON file and then conditionally display them when Arabic is the selected language

### User-facing consequences

Arabic speaker who are not familiar with western content licensing might not understand the usage terms of the content

### Context

0.12.0

**Comment by rtibbles** [comment]
Fixed in #5205
