### ISSUE TITLE
vacuuming isn't happening

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5149]
### Observed behavior

I didn't see an open issue for this, so opening one here. Please close if I missed it. (cc @jredrejo @rtibbles @lyw07)

Observed by @jredrejo that vacuums of the SQLite WAL files do not seem to be occurring, even though we have it set to run on restart and periodically at 3AM

### Expected behavior

WAL files must be occasionally vacuumed to prevent performance and file size issues

### User-facing consequences

poor performance, wasted disk space

### Errors and logs

WAL files are there to help protect against DB locking errors, I believe

### Steps to reproduce

unknown

### Context

0.12.0

**Comment by rtibbles** [comment]
This seems to have been fixed in #5159 :fireworks:
