### ISSUE TITLE
Channel List has layout issues on mobile-width screens

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5154]
### Observed behavior

The layout at cell-phone width causes Options button to break out of the container

![screen shot 2019-02-25 at 3 01 25 pm](https://user-images.githubusercontent.com/10248067/53376667-fb9c5800-3913-11e9-8a31-a6b2d8a81f90.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
Yep, noticed too on `beta9` testing on Ubuntu yesterday.

**Comment by indirectlylit** [comment]
This should be addressed by making the header and options button grid items both take up 100% width at the smallest screen size. In this mode, the options grid item should also have alignment set to `left`

**Comment by indirectlylit** [comment]
behavior updated in #6018
