### ISSUE TITLE
Previous question button empty label

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5157]
### Observed behavior
Previous question button show empty label when answering the first item of the quiz.

### Expected behavior
Should add a label `previous question` to the button.

### User-facing consequences

…

### Errors and logs

![screen shot 2019-02-26 at 5 04 06 pm](https://user-images.githubusercontent.com/8663934/53400630-3fad5c80-39e9-11e9-8d2a-8aefb7021969.png)

### Steps to reproduce
* Log in as a learner with an active quiz.
* Engage to first item of the quiz.
* See the `previous exam` button label

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.x-beta9
 * Operating system: macOS 10.13
 * Browser: Safari 11.0.3

**Comment by indirectlylit** [comment]
should be fixed by https://github.com/learningequality/kolibri/pull/5135
