### ISSUE TITLE
Learner last activity report display invalid date

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5158]
### Observed behavior
At the coach reports page I have an `invalid date` record on a learner. This might related to https://github.com/learningequality/kolibri/issues/5113#issuecomment-465900520

### Expected behavior
Display the exact date/time. 

### User-facing consequences

…

### Errors and logs
![screen shot 2019-02-26 at 6 54 51 pm](https://user-images.githubusercontent.com/8663934/53408346-35935a00-39f9-11e9-95aa-329f75e118d6.png)
![screen shot 2019-02-26 at 7 05 02 pm](https://user-images.githubusercontent.com/8663934/53408459-768b6e80-39f9-11e9-914f-609a96d52dbe.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.0-beta9
 * Operating system: macOS 10.13.3
 * Browser: Safari 11.0.3

**Comment by indirectlylit** [comment]
maybe related https://github.com/learningequality/kolibri/issues/5079

**Comment by rtibbles** [comment]
This should be fixed by #5918.
