### ISSUE TITLE
migrate existing IDs to a counter field

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5191]
### Observed behavior

By design, all our database IDs should be opaque strings: https://github.com/learningequality/kolibri/issues/1255

currently notifications uses integers with semantic information embedded in them, which breaks some assumptions we make in the client-side resource layer: https://github.com/learningequality/kolibri/issues/5070#issuecomment-467175920

### Expected behavior

Notification IDs should be strings like other DB models. We can store the incrementing counter in a separate field

### User-facing consequences

subtle bugs due to casting issues

### Context

0.12

-----

cc @rtibbles @jonboiser @jredrejo

**Comment by rtibbles** [comment]
I don't think this is how we should fix this. UUIDs should be used only when we intend data to be shared across database instances.
