### ISSUE TITLE
Clicking "Try now" button on Disconnected snackbar does not do anything

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5194]
### Observed behavior
![screen shot 2019-02-26 at 1 16 43 pm](https://user-images.githubusercontent.com/10248067/53446917-df0e2780-39c8-11e9-9fca-657ffbd7faa3.png)

Getting this error when clicking it. The `actionCallback` function appears not to be set.

### Expected behavior

When the server is working again, clicking 'Try again' causes a refresh.

### Context

0.12beta9

**Comment by rtibbles** [comment]
Fixed in #5209
