### ISSUE TITLE
Use appropriate permissions for ClassSummary endpoint

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5196]
### Observed behavior

In #5209, we fixed an issue where Promise rejections from unauthenticated requests to the notifications API was being swallowed by UI code (and not showing an AuthMessage component to users). We also added the most basic Permissions to the ClassSummary endpoint so that it would also return a 400 error for unauthenticated users.

However, the Permissions for Class Summary are too basic, and should be refined to be identical to permissions to AttemptLog, Groups, Exams, Lessons APIs, etc. (stuff ClassSummary aggregates).

There is a class `KolibriReportPermissions` that is used on some of the above-referenced APIs, that might be extended (or used as-is, possibly) on ClassSummary.

### Expected Behavior

ClassSummary permissions are exactly the same as endpoints that provide access to coach-only resources (exams, lessons, groups, logs, etc.)

### (Old) Observed behavior

1. When attempting to view a Coach page when an anonymous user, there is no "AuthMessage" component that explains why the page is not accessible. It's just a blank page. (No app bar either)
1. On Facility and Device pages, you do see that message, but on Device it's actually wrapped in KPageContainer (in Facility it's not)

![screen shot 2019-02-26 at 2 24 24 pm](https://user-images.githubusercontent.com/10248067/53450947-6f049f00-39d2-11e9-91e1-d99d1dcdd1e5.png)

### Expected behavior

1. When unauthenticated, accessing the coach pages shows an AuthMessage

### Context
0.12beta9

**Comment by indirectlylit** [comment]
might relate to work done in https://github.com/learningequality/kolibri/issues/5014 ?

**Comment by jonboiser** [comment]
I just tried this out, and the AuthMessage is showing up on coach pages, but you can also see the class name on the app bar.

It seems that the classSummary endpoint is open to unauthenticated users (hence the class name). It is the notifications endpoint that fails with the 403 error, which ends up showing the AuthMessage.

The Classroom API returns a 200, but it is an empty array (since anonymous users are not coaches or admins to any class).

**Comment by rtibbles** [comment]
Some fixes in #5209 - still need proper permissions on the class summary endpoint.

**Comment by rtibbles** [comment]
Fixed in #5308
