### ISSUE TITLE
more exercise progress inconsistencies

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5204]
### Observed behavior

there was an attempt on 'Name shapes 4':

| learner content | coach activity |
|--|--|
|![image](https://user-images.githubusercontent.com/2367265/53468945-0557b580-3a11-11e9-8c82-39671d6b2883.png) | ![image](https://user-images.githubusercontent.com/2367265/53468964-0d175a00-3a11-11e9-8bca-411db66fc9b2.png) |

but it's not shown on content cards:

| channel view | lesson view |
|--|--|
|![image](https://user-images.githubusercontent.com/2367265/53469002-32a46380-3a11-11e9-879b-fdcd24d5f02d.png) | ![image](https://user-images.githubusercontent.com/2367265/53469026-3df78f00-3a11-11e9-934c-243a3b7fdaec.png) |

### Expected behavior

consistent 'started' display

### User-facing consequences

possible confusion

### Errors and logs

none

### Steps to reproduce

In this example, I made one incorrect attempt on the exercise

### Context

0.12.0 beta 9

----

follow up to https://github.com/learningequality/kolibri/pull/5123 cc @ralphiee22

**Comment by rtibbles** [comment]
This was fixed by #5215
