### ISSUE TITLE
Blue Linear Progress Bar (for page loading) appears at Sign In screen

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5211]
### Observed behavior

GIF begins at select all. Towards end, the blue progress bar shows up at the upper left corner.

In other places, the bar is placed below the purple app bar. It's `top` position is being calculated incorrectly.

![progress bar](https://user-images.githubusercontent.com/10248067/53533167-97fa6200-3aae-11e9-8457-74a1144460ab.gif)

### Expected behavior

The linear progress bar only appears underneath the purple app bar.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context
0.12 beta9
…

**Comment by rtibbles** [comment]
Is this on production, or dev mode? (hot or not?)

**Comment by jonboiser** [comment]
devserver with HMR

**Comment by rtibbles** [comment]
OK, good - the FLOUT worried me, but the linear progress loader positioning is extant on production too.

**Comment by rtibbles** [comment]
Fixed in #5212
