### ISSUE TITLE
Consolidate documentation about testing

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#522]
There are a lot of docs in "Getting started" regarding testing:
http://kolibri.readthedocs.io/en/develop/dev/getting_started.html#code-testing

The actual page about testing is comparatively sparse:
http://kolibri.readthedocs.io/en/develop/dev/tests.html

Most likely, this should be reversed -- basic commands for running tests in "getting started", and then linking to the more detailed instructions in the tests page.

**Comment by indirectlylit** [comment]
fixed
