### ISSUE TITLE
Videos are failed to load on kolibri

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5227]
### Observed behavior

All videos on Kolibri-server are failed to load and have an error on console.
![image](https://user-images.githubusercontent.com/38421180/53618581-e468ad80-3c26-11e9-9c01-a73e24dc9bdd.png)

### Expected behavior

Can load the media videos.

### Context

Version: 0.12.0b10
OS: Ubuntu-18.04
Installer: kolibri(apt) with kolibri-server Version: 0.2-0beta3
Server: nginx/1.10.3 (Ubuntu)
Browser: Firefox

**Comment by mrpau-julius** [comment]
I think its same issue on Kolibri 0.12.0 beta 12. when I play the video it will crush down.
 ### Context
OS: windows 10
Browser: Firefox
```
{
  "request": {
    "path": "/api/logger/contentsummarylog/3f02df50b785233d53c735c1b8d1272d/",
    "method": "PATCH",
    "entity": "{\"channel_id\":\"000409f81dbe5d1ba67101cb9fed4530\",\"content_id\":\"f5a7e2bd531d5ec5a84c8002852409d3\",\"kind\":\"video\",\"user\":\"330154c50226defff5dedbd175a7e07f\",\"start_timestamp\":\"2019-03-01T06:35:39.717Z\",\"end_timestamp\":\"2019-03-01T06:17:06.075Z\",\"completion_timestamp\":null,\"progress\":0.1001931862745098,\"time_spent\":-1127.722,\"extra_fields\":{\"contentState\":{\"savedLocation\":13.683832}},\"id\":\"3f02df50b785233d53c735c1b8d1272d\",\"currentmasterylog\":null}",
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2",
      "X-CSRFToken": "cVCX5UqnyeRMnTwH0P23fFwbUUa5SvWKnMYxsCcEv40fk1wpkLTutr7CAKXkAScO"
    },
    "canceled": false
  },
  "url": "/api/logger/contentsummarylog/3f02df50b785233d53c735c1b8d1272d/",
  "raw": {},
  "status": {
    "code": 400,
    "text": "Bad Request"
  },
  "headers": {
    "Allow": "GET, PUT, PATCH, DELETE, HEAD, OPTIONS",
    "Content-Language": "en",
    "Content-Length": "115",
    "Content-Type": "application/json",
    "Date": "Fri, 01 Mar 2019 06:17:07 GMT",
    "Server": "0.0.0.0",
    "Vary": "Accept, Accept-Language, Cookie",
    "X-Frame-Options": "SAMEORIGIN"
  },
  "entity": [
    {
      "id": "MIN_VALUE",
      "metadata": {
        "message": "Ensure this value is greater than or equal to 0.",
        "field": "time_spent"
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/38421180/53623567-5c48c080-3bb2-11e9-8283-60fdf8e0498c.png)

**Comment by jredrejo** [comment]
@mrpau-julius yes, kolibri-server just adds some settings over kolibri code to improve the server performance.
Any issue existing in Kolibri will be present when using kolibri-server.

Please, for kolibri-server ,report only those issues that happen when using kolibri-server and not when using just kolibri.

**Comment by indirectlylit** [comment]
If this is happening in Kolibri, should we not keep the issue open and just remove the reference to `kolibri-server`?

**Comment by radinamatic** [comment]
@mrpau-dev Not sure why it is failing on Windows, but when testing on Ubuntu, make sure to have the `ubuntu-restricted-extras` package installed. VideoJS in Firefox will report that same error if the package is not installed, but otherwise should play without issues:

![ubuntu 16 04 3 start running - oracle vm virtualbox_455](https://user-images.githubusercontent.com/1457929/53664048-af307f80-3c67-11e9-9798-f2bc7d1a45eb.png)

This requirement is [reported in our user docs](https://kolibri.readthedocs.io/en/latest/access.html?highlight=extras#compatibility).

**Comment by jredrejo** [comment]
Reopening this issue as it seems we didn't have an issue for kolibri to track it.

**Comment by radinamatic** [comment]
Unable to replicate this with the latest built dev asset from the 0.12 release branch. Videos play without issues in both Firefox (v62-v65) and Chrome on either Windows 7 or 10. 

@mrpau-julius When you install the `restricted extras` package, are you still having issues with videos on Ubuntu?

**Comment by radinamatic** [comment]
Unable to replicate this with the latest built dev asset from the 0.12 release branch. Videos play without issues in both Firefox (v62-v65) and Chrome on either Windows 7 or 10. 

@mrpau-julius When you install the `restricted extras` package, are you still having issues with videos on Ubuntu?

**Comment by mrpau-julius** [comment]
@radinamatic no more issues. I can play the videos after I installed `ubuntu-restricted-extras`.

**Comment by radinamatic** [comment]
Good news @mrpau-julius, thanks! 👍 

How about Windows, did you or @mrpau-richard find any more occurrences of video playback issues there?

Otherwise we could even close this issue... 😉

**Comment by mrpau-richard** [comment]
I did not encounter this issue on Windows. I think this issue can only reproduce on Ubuntu.

**Comment by indirectlylit** [comment]
great thanks all
