### ISSUE TITLE
500 Internal Server Error while syncing servers

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5253]
**Observed behavior**
While syncing the classroom servers with the cloud, we are receiving the "500 Internal Server Error". This is happening across all classrooms. 

Some of the facility names showing the above error are :-

1. P-SVT-iTeach (Grade 8)
2. P-PDUEMS (Grade 7,8)

Also, some of the databases show synced with size 0.

3cb4ef76f24e1de35fb20839b99de849-fbbb1f981115e4eff811579c179c95a1.sqlite3 Feb. 24, 2019, 11:49 a.m.     
5bc7a0415938ad1968f13c3149785b0b-f12372bb14de9b5f391a3a5ed2fb0168.sqlite3 Feb. 27, 2019, 8:36 a.m.              
bb69fad2c215ce99811665b204d85e4a-d78d126caf484efd15967b98dd49d556.sqlite3 Feb. 23, 2019, 6:05 a.m. 
…

### Expected behavior
 The sync should happen without any issues and the synced databases should have size greater than 0.

…

### User-facing consequences
The data is not getting synced to the cloud and is confined only to the local server in the classrooms. 

### Steps to reproduce
Take any server and execute the sync command to sync the server with the cloud.

…

### Context

 * Kolibri version 0.9.5b3
 * Operating system Ubuntu 14.04
 * Chrome

…
![sync_error2](https://user-images.githubusercontent.com/8583367/54025548-dc79b200-41c0-11e9-8dc3-86c5a5178e17.png)
![sync_error1](https://user-images.githubusercontent.com/8583367/54025549-dc79b200-41c0-11e9-9d80-4fde0bcb6316.png)

**Comment by rtibbles** [comment]
Has been resolved, please reopen if it recurs.
