### ISSUE TITLE
add Gujarati to supported languages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5255]
### Observed behavior

Gujarati has been translated and just needs to be approved

### Expected behavior

Add to supported languages

### User-facing consequences

Gujarati speakers will be able to use the app

### Context

0.12.0

**Comment by jonboiser** [comment]
Does #5307 close this issue?

**Comment by rtibbles** [comment]
I believe so!

**Comment by rtibbles** [comment]
Fixed in #5307
