### ISSUE TITLE
add burmese as a supported language

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5256]
### Observed behavior

burmese is 100% translated an approved, but not in the supported languages

### Expected behavior

burmese should be a supported language

### User-facing consequences

not usable by burmese speakers

### Context

0.12.0

**Comment by rtibbles** [comment]
Closed in #5258 and https://github.com/learningequality/kolibri/commit/02226515df1263ee83ed2d791cffe3b31a8dce61
