### ISSUE TITLE
Monitor dependencies

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#526]
We should have this service (or likewise) to keep track of our Python deps:

https://pyup.io/repos/github/audreyr/cookiecutter-pypackage/

Similar would be useful for NPM dependencies

**Comment by indirectlylit** [comment]
clearing 'future' milestone to make it more likely that we'll come back to it

**Comment by benjaoming** [comment]
This is still important, moreover we should figure out a strategy that balances out the fact that we are pinning versions on a patch digits, rather than a minor digits.

**Comment by benjaoming** [comment]
#2883 is now open and PyUp is tracking the repo -- needs proper integration before we can close this.

**Comment by benjaoming** [comment]
Dependency tracking with PyUp has been implemented, so closing this!
