### ISSUE TITLE
Some HTML5 apps in Thoughtful Learning channel fail to load

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5269]
### Observed behavior

In the `Thoughtful Learning` channel, there are some HTML5 apps failing to load. 
This can be found on kolibridemo site: http://kolibridemo.learningequality.org/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/plan/lessons/e4a5e8f0b2e8d72505472839643797b7/selection/preview/bc38de32126b5f7cb8026fd068df70b9

I'm able to reproduce it locally by importing the specific content.

A user also reported this issue in the forum: https://community.learningequality.org/t/kolibri-html-viewer-not-working/1068/4

This issue only happens in 0.12.0 and 0.12.1 but does not happen in 0.11.1.

### Expected behavior

The HTML5 apps should load successfully

### User-facing consequences

Users are not able to preview the HTML5 apps.

### Errors and logs

<img width="640" alt="Screen Shot 2019-03-14 at 12 53 21 PM" src="https://user-images.githubusercontent.com/19424916/54387296-38788680-4658-11e9-9d8f-e38269920a07.png">

### Steps to reproduce

1. Import content `Thoughtful Learning` --> `Minilessons` --> `21st Century Skills` --> `If I Were President`
2. Go to the Learn tab to check the content

### Context

Kolibri version: 0.12.0 & 0.12.1
Operating system: Mac OSX / Ubuntu
Browser: Chrome

**Comment by rtibbles** [comment]
This should be fixed in #5288

**Comment by radinamatic** [comment]
Still extant on Firefox:

![2019-03-27_18-13-11](https://user-images.githubusercontent.com/1457929/55122663-ef471e80-50bc-11e9-83ae-89c85241974a.png)
