### ISSUE TITLE
CK-12 plix content doesn't "play"

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#5278]
### Observed behavior

Unable to 'play' the CK-12 PLIX content such as https://kolibridemo.learningequality.org/learn/#/topics/c/bdd18f86f27c58bba6c249b498f01823 .
When downloaded, unarchived and index.html fired in a browser, it works.

### Expected behavior

Should work as it seems standard HTML5 content.

### User-facing consequences

Unable to use the interactive content. Lessons built around it won't work.

### Errors and logs

Noticed these deprecation warnings in browser console.
![image](https://user-images.githubusercontent.com/2577060/54475037-9cdf4580-4812-11e9-88a4-a2f50a626f2c.png)
 

### Steps to reproduce

Visit any PLIX content such as https://kolibridemo.learningequality.org/learn/#/topics/c/bdd18f86f27c58bba6c249b498f01823

### Context

Kolibri 0.12.1
Tried with Firefox and Chrome.

**Comment by rtibbles** [comment]
This should be fixed by #5288 - the fix should be in the 0.12.2 release.
