### ISSUE TITLE
Add snackbar/pop-up notifications in more workflows

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5281]
### Observed behavior

Add notifications to workflows, so they behave like similar workflows

* Manage Class Page: Adding/deleting a class
* Class Edit Page: Adding, Removing Learners/Coaches, Renaming the class
* User Page: Adding/Removing user, Editing User details/password
* Facility Settings: Replace UiInfo banner with a notification
* Device Settings: Replace UiInfo banner with a notification
* User permissions page: after updating a user's permissions

### Expected behavior

* Manage Class Page, Adding a class - "The class 'class name' was created"
* Manage Class Page, Deleting a class - "The class 'class name' was deleted"
* Class Edit Page, Removing  Coaches/Learners - "The coach/learner 'name' was un-assigned/un-enrolled from the class."
* Class Edit Page: Adding Learners + Coaches - "N learner(s)/coach(es) were added to the class"
* Class Edit Page, Renaming class: "The class was renamed to 'new class name'"
* User Page, adding a user: "The user 'username' was added to the facility.
* User Page, removing a user: "The user 'username' was removed from the facility.
* User Page, updating a user: "The profile for user 'username' was updated." (We use the new username even if that was changed also.)
* User Page, updating a user's password: "The password for 'username' was updated."

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
this looks useful

**Comment by khangmach** [comment]
Facility > Classes

Context | String | Action label
------------ | ------------- | ----------------------
Adding a class | Class created |
Deleting a class | Class deleted | 
Assigning a coach | Coach assigned | Undo
Assigning multiple coaches | Coaches assigned | 
Removing a coach | Coach removed | Undo
Enrolling a learner | Learner enrolled | Undo
Enrolling multiple learners | Learners enrolled | 
Removing a learner | Learner removed | Undo

Facility > Users

Context | String | Action label
------------ | ------------- | ---------------
Creating a new user | User created | 
Deleting a user | User deleted | 
Updating user password | Password reset | 

Device > permissions

Context | String | Action label
------------ | ------------- | ---------------
Updating permission | Changes saved |

**Comment by khangmach** [comment]
@jonboiser Updated coach strings:

Coach > Plan lesson

Context | String | Action label
------------ | ------------- | ---------------
Creating a new lesson | Lesson created | 
Editing lesson details | Changes saved | 
Deleting a lesson | Lesson deleted | 
Adding a resource | Resource added | 
Adding multiple resources | N resources added |
Removing a resource | Resource removed |
Removing multiple resources | N resources removed |
Removing a resource from the lesson page | Resource removed | Undo
Removing multiple resources quickly from the lesson page | 2 resources removed | Undo

Coach > Plan quiz

Context | String | Action label
------------ | ------------- | ---------------
Creating a new lesson | Lesson created | 
Deleting a lesson | Lesson deleted | 
Adding a resource to a quiz | Resource added |
Adding multiple resources | N resources added |
Removing a resource | Resource removed | 
Removing multiple resources | N resources removed | 
Finishing creating a new quiz | Quiz created
Editing quiz details | Changes saved | 
Deleting a quiz | Quiz deleted

Coach > Plan groups

Context | String | Action label
------------ | ------------- | ---------------
Creating a new group | Group created | 
Deleting a group | Group deleted | 
Editing group name | Changes saved |
Enrolling learner into the group | Learner enrolled | 
Enrolling multiple learners | N learners enrolled | 
Removing learner from group | Learner removed |

**Comment by jonboiser** [comment]
b5379a7 Adds a `showSnackbarNotification` method to the `coreCommonStrings` mixin. To completely resolve this issue, we'll need to insert calls to this method in all the relevant UIs.
