### ISSUE TITLE
Strings in single group sub-tab not displaying localized

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5282]
### Observed behavior

Some strings on group management page and modals do not display localized, despite being translated and approved on Crowdin:

![2019-03-18_15-17-23](https://user-images.githubusercontent.com/1457929/54568158-6a108b00-4993-11e9-8cbd-04aeed9455e4.jpg)

![2019-03-18_15-22-18](https://user-images.githubusercontent.com/1457929/54568165-6ed53f00-4993-11e9-90e2-6cc5ba5e7f21.jpg)

![2019-03-18_15-29-47](https://user-images.githubusercontent.com/1457929/54568170-73015c80-4993-11e9-9b7e-932a770d9261.jpg)

[String translated on Crowdin](https://crowdin.com/translate/kolibri/582/en-es#43232)

### Expected behavior
Localized strings displayed correctly.

### User-facing consequences
Lack of understanding the UI options.

### Errors and logs
…

### Steps to reproduce
Change UI language from English
Go to Coach > Plan > Group and select a group. 
Try to enroll and delete learners.

### Context
0.12.1 (kolibridemo server)

cc @indirectlylit @jonboiser

**Comment by jonboiser** [comment]
It looks like the strings for GroupMembersPage didn't make it into the locale file.

**Comment by radinamatic** [comment]
Notification for the newly created group also pops-up in English.

**Comment by radinamatic** [comment]
All instances of `Select all on page` are from the `facility_management_module-messages.json` file, are we sure that it gets applied to `coach_module-messages.json` too?

![2019-03-18_23-49-28](https://user-images.githubusercontent.com/1457929/54586744-378a8080-49db-11e9-89e9-ad03c35141f4.jpg)

**Comment by rtibbles** [comment]
Yeah, anything in the facility json will not be available to the coach plugin.

**Comment by radinamatic** [comment]
I was under the impression that it could be reused on Crowdin, and that was the reason for including it after the string freeze... 😕

**Comment by rtibbles** [comment]
Yes - it could, but only if the strings were updated.

**Comment by indirectlylit** [comment]
investigating now
