### ISSUE TITLE
Unable to FFWD KA Math videos

### ISSUE THREAD

**Issue by carinediaz** [learningequality/kolibri#5283]
### Observed behavior

While watching a KA math video on the v0.12 Kolibri demo server, I realized I was unable to use the +10s button nor drag the player forward to fast forward the video.

video player unable to ffwd, the video keeps coming back to the very start.

### Expected behavior
when pressing the +10s button or dragging the cursor forward, the expected behavior would be for the video to jump forward. 

### User-facing consequences
frustration

### Errors and logs

…

### Steps to reproduce
access http://kolibridemo.learningequality.org/learn/#/classes/f6e7f562bb0ea654340c726e1f81bbe9/lesson/a719e3d4b9f9d82bce65cca67624c6b8/item/2
Try fast-forwarding the video

### Context

 * Kolibri version: 0.12 (demo server)
 * Operating system: MacOs 10.11.2
 * Browser: Chrome

**Comment by radinamatic** [comment]
Could somebody try Firefox on macOS to confirm that this is a Chrome-only issue?
I can use the ffwd/bwd buttons and jump anywhere on the timeline in Firefox on both Windows and Ubuntu without issues...

**Comment by radinamatic** [comment]
Still unable to replicate this _anywhere but_ on the `kolibridemo` server, same as @rtibbles.

Tested on 0.12.1 installed locally on both Ubuntu and Windows, and even accessed Kolibri running in Windows 7 VM **from the host Chrome browser**, all cases give no back & forth playback issues:

![fwd-Chrome](https://user-images.githubusercontent.com/1457929/54854656-d8fe2480-4cb0-11e9-8499-f9fcc73e68ad.gif)

**Comment by rtibbles** [comment]
As we can only seem to replicate it on the demo server, I'm removing labels and milestones. If we see it still when we update the demo server to 0.12.2, we can reinvestigate.

**Comment by jonboiser** [comment]
Closing this as a probably stale issue. Testing this on the demo server (running 0.14.3 and viewing in Chrome), I can't reproduce this.
