### ISSUE TITLE
User icon RTL alignment 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5284]
Reported by Hiba

### Observed behavior
Some user icons do not align properly and overlap the names:

![user-icon-rtl-align](https://user-images.githubusercontent.com/1457929/54571148-a39ac380-499e-11e9-8764-a308133ea443.png)

### Expected behavior
Consistent and proper icon alignment in RTL mode.

### User-facing consequences
Unclear UI

### Errors and logs
…

### Steps to reproduce
Go to Arabic demo site and browse Facility > Users
…

### Context
0.12

cc @indirectlylit @jonboiser

**Comment by rtibbles** [comment]
Note that this specifically seems to be an issue with LTR text in RTL interface mode.

**Comment by indirectlylit** [comment]
In this case, root cause was actually because I had `position: absolute` on the icon with no additional specification.

Adding `left: 0` was the fix, because then our RTL code actually had something to flip to `right: 0`. Otherwise it just sticks with the browser default which remains `left`.

**Comment by rtibbles** [comment]
Fixed in #5291
