### ISSUE TITLE
Not enough questions freezes the browser during the quiz creation

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5289]
### Observed behavior

When exercises with not enough questions are selected for the quiz, the browser freezes and needs to be closed.

![2019-03-19_9-34-14](https://user-images.githubusercontent.com/1457929/54633073-a51ac900-4a3c-11e9-95b3-550a4e000c1e.jpg)

![2019-03-19_11-32-19](https://user-images.githubusercontent.com/1457929/54633074-a51ac900-4a3c-11e9-82e5-aa236f5d1ff0.jpg)

### Expected behavior

We used to have [an alert message for these cases](https://crowdin.com/translate/kolibri/1002/en-es#70086), but it does not appear to be triggered correctly.

### User-facing consequences
Inability to proceed, forced to restart the browser.

### Errors and logs

```
Not enough questions to reach numQuestions
```

### Steps to reproduce

#. Go to Coach > Plan > Quizzes > New quiz
#. Up the number of questions to 50
#. Select only one exercise
#. Press `Continue`

### Context

0.12.1 (kolibridemo server)

cc @indirectlylit @rtibbles @jonboiser

**Comment by jonboiser** [comment]
> We used to have an alert message for these cases, but it does not appear to be triggered correctly.

@radinamatic Do you know which component this message appears in? And which message exactly it is? 

I do remember seeing a UI message pop up when this situation happened, so maybe the error-handling code was changed.

**Comment by radinamatic** [comment]
It should be here @jonboiser:
kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue

It's the only one that came up when searching the string in the codebase.

**Comment by radinamatic** [comment]
![2019-03-19_13-48-50](https://user-images.githubusercontent.com/1457929/54640762-d059e400-4a4d-11e9-9762-9985cf5ed26a.png)

**Comment by jonboiser** [comment]
Yeah, the `numQuestionsExceed` and the `numQuestionsNotMet` messages are not used in CreateExamPage at the moment.

**Comment by jonboiser** [comment]
I think the code showing this message got deleted at this commit 

https://github.com/learningequality/kolibri/commit/36e4f4ba63a1453794ac1edd3f79e55cd919e0c8#diff-1986ecad4308dce2bab9abf80d3819d4L313-L329

To fix this, we need to copy it back to the `numQuestionsInvalid` computed property.

**Comment by jonboiser** [comment]
As for the freezing, I'm wondering if this line causes an infinite loop.

https://github.com/learningequality/kolibri/blob/e977bb104d5ed7cde7b3fc6c68f049a40aff6271/kolibri/plugins/coach/assets/src/modules/examCreation/selectQuestions.js#L52

The console logs an error, but it doesn't terminate execution of `selectionQuestions`

**Comment by rtibbles** [comment]
Yeah, that seems a likely culprit - should add another condition on whether there are any more questions to look for?
