### ISSUE TITLE
Add 'browser default' to Setup Wizard language options

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#5290]
### Observed behavior
In device settings it is possible to change the default language to 'browser default', but this is not possible in the setup wizard.

### Expected behavior
Can set default language to 'browser default' during setup wizard.

However, a user cannot set the language to "browser default" using the language switcher. Since the LanguageSwitcher component is used in the setup wizard and on the login page (and other places), we need to hide "browser" default in all places not the setup wizard.

### User-facing consequences
A slightly more convoluted initial setup.

**Comment by jonboiser** [comment]
@rtibbles What's the best way to implement this? The language switcher mixin makes a POST to a `set_language` endpoint when a language is picked. If I post `{ code: null }` (for browser default) to it, what do I have to do to make sure that we use the correct language when the page refreshes?

**Comment by rtibbles** [comment]
Hrm, we might have to enhance the `set_language` endpoint to properly process null - I can make a quick PR to handle the backend piece.
