### ISSUE TITLE
Updating a channel shifts it's position in the Learn list

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#5292]
### Observed behavior

Updating a channel shifts it's position in the Learn list to the very last,

### Expected behavior

Should not change the channel order in the learn list.

### User-facing consequences

Have to re-adjust the channel order after an update is annoying.

### Errors and logs

NA

### Steps to reproduce

1. Update a channel that is not last in the Learn listing
2. Refresh the Learn listing after an update and one can see that it has moved to the last

### Context

Kolibri 0.12.1

**Comment by indirectlylit** [comment]
Hi @intelliant01 

We're aware that controlling channel ordering can be frustrating, and making it more predictable and manageable in the Device tab is on our roadmap.

As a short-term work-around, we've added a new terminal command in 0.12 for managing order:
https://kolibri.readthedocs.io/en/latest/manage.html#reorder-content-channels

hope this helps

**Comment by indirectlylit** [comment]
I think this specific issue (don't change order after an update) can probably be addressed before bigger changes are implemented

**Comment by intelliant01** [comment]
Hi @indirectlylit 

> As a short-term work-around, we've added a new terminal command in 0.12 for managing order:
https://kolibri.readthedocs.io/en/latest/manage.html#reorder-content-channels

Am aware and indeed this is the straw I have been hanging on to in this reordering storm. ;)

> I think this specific issue (don't change order after an update) can probably be addressed before bigger changes are implemented

Really hope so.

**Comment by indirectlylit** [comment]
this now only happens in postgres. remaining work to happen under https://github.com/learningequality/kolibri/issues/6560
