### ISSUE TITLE
Consistent style for auth messages

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#5309]
### Observed behavior

Differently styled auth messages:

<img width="1440" alt="Screenshot 2019-03-23 at 15 33 39" src="https://user-images.githubusercontent.com/13509191/54867913-72e3d100-4d86-11e9-9464-e2aba75ce532.png">

<img width="1439" alt="Screenshot 2019-03-23 at 15 33 26" src="https://user-images.githubusercontent.com/13509191/54867912-70817700-4d86-11e9-9144-3739d6649f9c.png">

(seems to have something in common with `KPageContainer` presence)

### Expected behavior

Coach auth message should be wrapped in a card too.
…

### User-facing consequences
Visual inconsistency

**Comment by indirectlylit** [comment]
agreed!

**Comment by MisRob** [comment]
🆗 thanks for checking it. I'll have a look at it then.

**Comment by indirectlylit** [comment]
Wrapping with `KPageContainer` will be the simplest fix

**Comment by rtibbles** [comment]
Fixed in #5361
