### ISSUE TITLE
Lessons created in one class appear in other classes

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5311]
### Observed behavior

Reported by Hiba and confirmed on `0.12.2-beta2` release.

### Expected behavior
Lessons should appear only in class they are created for (until coach expressly copies them to another). 

### User-facing consequences
Learners in other classes seeing lessons not intended for them.

### Errors and logs

…

### Steps to reproduce

1. Create 2-3 classes in the facility
2. Create a lesson in one class and activate it
3. Go to Learn and open other classes (make sure you are enrolled in them)
4. Observe the lesson created in the first class

### Context
 * Kolibri version: `0.12.2-beta2` release
 * Operating system: Windows
 * Browser: Chrome & FF

**Comment by jonboiser** [comment]
1. Is this only happening on the "Learner" side of the app?
1. Does this only happens for Lessons, or also Exams?

The latest changes to the relevant backend API might be in this PR https://github.com/learningequality/kolibri/pull/5274/files

**Comment by radinamatic** [comment]
1. No, appears also if you visit the Learn page as an admin or coach.
2. I rechecked, and it seems to be happening only for Lessons, not Quizzes.

**Comment by jonboiser** [comment]
So for 1 it only happens on the "Learn" page (regardless of user type). For example, a Coach isn't seeing a Lesson for Class 1 in the Coach page for Class 2.

**Comment by radinamatic** [comment]
Correct, it appears only in the Learn page, not on Coach > Class Home or Reports pages.

**Comment by rtibbles** [comment]
I had a different understanding of the steps to reproduce here:
1. Create two classrooms, assign the same user to both.
2. Create a lesson in one of the classrooms.
3. See the lesson in both user's classrooms.

**Comment by rtibbles** [comment]
Fixed in #5312
