### ISSUE TITLE
Buggy horizontal table scrollbar

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5316]
### Observed behavior

**Chrome:**
Horizontal scrollbar attempts to maintain its position as the user scrolls up and down. Arrowing up and down the page works fine though. 
![chrome behavior](https://user-images.githubusercontent.com/25045166/55042929-1a643c00-4ff1-11e9-9054-7308bdbaf010.gif)

**Firefox:**
The overflow isn't contained within the table column. Scrollbar doesn't appear
![firefox behavior](https://user-images.githubusercontent.com/25045166/55042952-32d45680-4ff1-11e9-8f37-788918c47341.gif)

**Safari:**
Correct behavior seen in Safari
![safari behavior](https://user-images.githubusercontent.com/25045166/55042965-441d6300-4ff1-11e9-8dbc-5c9f1d352827.gif)

### Expected behavior
Behavior seen in Safari browser

### User-facing consequences
Buggy 

### Steps to reproduce
- Navigate to facility > users page
- Find a data cell with character overflow and horizontally scroll within the cell
- Then scroll up and down

### Context
 * Kolibri version: 0.12.1
 * Operating system: MacOS
 * Browser: Chrome, Safari, Firefox

**Comment by indirectlylit** [comment]
introduced in https://github.com/learningequality/kolibri/pull/5134

**Comment by jonboiser** [comment]
@khangmach 	For the screenshots, is the window narrow enough that the upsliding AppBar  behavior is being applied? I don't know if it's because how the screen is cropped, but the AppBar looks to be doing unusual things as well as you scroll down.

**Comment by indirectlylit** [comment]
it is - when you scroll down it overshoots and then pops back up. I think that's unrelated though

**Comment by jonboiser** [comment]
I can't reproduce the behavior on the Chrome browser GIF. Could it be related to GPU performance that the slider lags behind?

**Comment by indirectlylit** [comment]
>  the AppBar looks to be doing unusual things as well as you scroll down.

made a new issue for that https://github.com/learningequality/kolibri/issues/5326

**Comment by khangmach** [comment]
So Jessica tried to reproduce this issue on MacOs Chrome and as @jonboiser said, couldn't reproduce it. However, when she disconnected her monitor and tried reproducing behavior on her laptop screen, she got the bug again. Same with me. Connected to external monitor == no bug. Regular monitor yes.

**Comment by jonboiser** [comment]
So no (lagging scrollbar on Chrome) bug on both these scenarios?

1. External monitor is connected, and browser on the laptop screen?
1. External monitor is connected and browser is on external monitor.

**Comment by jonboiser** [comment]
Currently the main 'content' div pushes things down using an inline-style for margin-top. Maybe this should actually be absolutely positioned with `top: X px` instead?

![Screen Shot 2019-03-28 at 3 47 39 PM](https://user-images.githubusercontent.com/10248067/55197823-f29be200-5170-11e9-8f0f-4a237102cfc6.png)

**Comment by khangmach** [comment]
a weird turn of events:

case1: External monitor connected + browser in laptop screen == buggy scrollbar
case2: External monitor connected + browser in external monitor screen == buggy cell text
case3:  External monitor disconnected completely == buggy scrollbar

an example of case 2. Maybe this is hardware related? 
![Mar-28-2019 15-56-22](https://user-images.githubusercontent.com/25045166/55198203-4ce97280-5172-11e9-9643-3bbac638d384.gif)

**Comment by jonboiser** [comment]
On Kolibri beta, this only happens when the window is narrow enough that AppBar slide-up behavior is toggled on. If the AppBar has a fixed position, I don't see it.

And for me the first column seems to move around a lot when I scroll up/down.

![shifting](https://user-images.githubusercontent.com/10248067/55201925-714d4b00-5182-11e9-9d8d-096d046360f9.gif)

**Comment by indirectlylit** [comment]
> scrollbar slide-up behavior

you mean app bar?

**Comment by indirectlylit** [comment]
@khangmach would you mind checking if this behavior is still reproducible? I think it may have been addressed with @jonboiser 's recent refactor of the app bar.

**Comment by khangmach** [comment]
Yup I'm not getting this behavior anymore.
