### ISSUE TITLE
User added twice on the list to enroll in class

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5321]
### Observed behavior
When admin first selects manually a learner with the checkbox, but then searches for a text using the `Search` field, and already selected learner happens to be among the results and gets selected for the second time, will provoke a `Server Error (500)`.

![2019-03-27_15-09-28](https://user-images.githubusercontent.com/1457929/55121714-f704c400-50b8-11e9-8367-9d85c6a5aada.png)

![select-user-twice](https://user-images.githubusercontent.com/1457929/55121722-fec46880-50b8-11e9-995f-55d144a05b5f.gif)

### Expected behavior
Ignore the first selection?

### User-facing consequences
UI error

### Errors and logs

[kolibri.log](https://github.com/learningequality/kolibri/files/3015798/kolibri.log)

### Steps to reproduce
1. Go to Facility > Classes > Class N > Enroll Learners
2. Select a learner with checkbox
3. Use the `Search` field to filter with a string that gives as a result the previously selected learner and at least one other.
4. Check the `Select all` checkbox 
5. Click `Confirm` 

### Context
0.12.2.beta3
Ubuntu/Firefox

…

cc @rtibbles

**Comment by rtibbles** [comment]
Fixed in #5322
