### ISSUE TITLE
app bar will overshoot and detach from top of window on scroll

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5326]
### Observed behavior

when scrolling quickly, it's possible for the app bar to detach from the top of the screen:

![overshoot](https://user-images.githubusercontent.com/2367265/55196591-d5214500-517d-11e9-9ef4-bbbb45a32d9b.gif)

note that when implementing this, we intentionally tried to avoid having any javascript that would re-position the header on every scroll event (e.g. by setting the `y` location as a transform).

The current implementation tries to be clever and "pins" the app bar to the page, allowing them to move upwards and downwards together:

![scroll](https://user-images.githubusercontent.com/2367265/50061939-edce9780-0158-11e9-83c1-65e847b8b5d0.gif)

It does this by flipping between `position: fixed` and `position: absolute`: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreBase/ScrollingHeader.vue#L77-L85

Probably what we want to do is to flip between the two `position` modes, and instead animate just the hiding/showing portions with javascript.

### Expected behavior

app bar should never be lower than its height

### User-facing consequences

things look a little bit broken

### Errors and logs

…

### Steps to reproduce

scroll down and then scroll up quickly

### Context

0.12.2

**Comment by indirectlylit** [comment]
see related issue: https://github.com/learningequality/kolibri/issues/4827

**Comment by khangmach** [comment]
So Jessica tried to reproduce this issue on MacOs Chrome and as @jonboiser said, couldn't reproduce it. However, when she disconnected her monitor and tried reproducing behavior on her laptop screen, she got the bug again. Same with me. Connected to external monitor == no bug. Regular monitor yes.

**Comment by khangmach** [comment]
![Mar-28-2019 15-23-24](https://user-images.githubusercontent.com/25045166/55197055-9637c300-516e-11e9-83d9-390b4e2e60f6.gif)
Example on small screens

**Comment by khangmach** [comment]
![Mar-28-2019 15-22-12](https://user-images.githubusercontent.com/25045166/55197066-9d5ed100-516e-11e9-8c2b-c4f5e1527490.gif)
on large screen

**Comment by indirectlylit** [comment]
still being observed - cc @khangmach

**Comment by jonboiser** [comment]
lodash/clamping the `offset` to be strictly less than 0 seems to work. Is the reason the bar "overshoots" is because of cases where the inline style is both `position: absolute` and the translateY is greater than 0?

**Comment by jonboiser** [comment]
I think the problem is that it's hard to constrain the state space of y-position, absolute/fixed positioning, etc.to avoid the overshoot, which seems to be a combo of y-position being too large and position = absolute, for arbitrary sequences of scroll events.

For now, I'm just going do something more conservative and and give the app bar a fixed position with a binary y-offset when it's hidden or shown (i.e. does not base positioning on the magnitude of scroll events).

**Comment by indirectlylit** [comment]
sounds good!
