### ISSUE TITLE
specify supported browsers and operating systems with single source of truth

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5336]
### Observed behavior

Information about our 'supported platforms and browsers' are scattered around a bit. This includes:

* a [browserlist](https://github.com/learningequality/kolibri/blob/develop/browserslist) file 
* information [embedded in the source code](https://github.com/learningequality/kolibri/pull/4994/files#diff-1c848f18f350e590ad2225d5e1e68317R8)
* information encoded in external spreadsheets [here](https://docs.google.com/spreadsheets/d/1kVhg0evo9EV2aDo10KdIIjwqsoT4rISR7dJzf6s_-RM/edit#gid=989978975) and [here](https://docs.google.com/spreadsheets/d/1CAzop-fEZyF-mra9ByJRWHqg4irco1MrTArcJKM8P-4/edit#gid=0)

We also have this information separately in the [Kolibri user docs](https://github.com/learningequality/kolibri-docs/blob/develop/docs/access.rst#compatibility) repo, but that seems acceptable.

### Expected behavior

Within the Kolibri repo, we should have a single machine- and human-readable representation of our supported browsers.

cc @rtibbles @mrpau-dev @radinamatic thoughts are welcome

### User-facing consequences

Users on older or more obscure OS/browser combinations may receive software that hasn't been fully tested

### Context

0.12.2

**Comment by rtibbles** [comment]
Yeah, I think drawing from the browserlist would be ideal to get rid of the embedded in source code issue (noting that the diff you linked to is a result of transferring that checking from Python to JS, and not a new separation!).

Can fix this in the context of the PR linked above.

**Comment by indirectlylit** [comment]
> the diff you linked to is a result of transferring that checking from Python to JS

yes, that was my fault :)

**Comment by indirectlylit** [comment]
i think? git only knows

**Comment by rtibbles** [comment]
It was both our faults. First mine for the unsupported browser context flag, and then yours for following my folly with the font loading logic.

**Comment by rtibbles** [comment]
This has begun to be addressed here: https://github.com/learningequality/kolibri/pull/8159 but needs the JS browser support code to use this also.

**Comment by rtibbles** [comment]
Fixed in #11685
