### ISSUE TITLE
Select all not working in groups

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5350]
### Observed behavior
In the coach tab, while enrolling learners in the group first select single user and then select select all option and then enroll. It will enroll only one user in the group.

### Expected behavior
When we select select all, it must enroll all users in the group.

### Steps to reproduce
1. Create the group.
2. Select one user while enrolling.
3. Then select select all in groups.
4. Click on enroll.
5. It will enroll only one user in the group.

### Context
 * Kolibri version : Kolibri 0.12.2
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshots
![1](https://user-images.githubusercontent.com/12776071/55711874-4200ce80-5a0b-11e9-942d-2cd54cbc4db4.png)
![2](https://user-images.githubusercontent.com/12776071/55711898-51801780-5a0b-11e9-8f78-c63ceb2b808d.png)
![3](https://user-images.githubusercontent.com/12776071/55711909-56dd6200-5a0b-11e9-8f7c-98a9485c59bb.png)
![4](https://user-images.githubusercontent.com/12776071/55711911-56dd6200-5a0b-11e9-83f8-b9214743fa2a.png)
![5](https://user-images.githubusercontent.com/12776071/55711912-56dd6200-5a0b-11e9-94f1-4b727225dbda.png)

**Comment by jonboiser** [comment]
This looks like the same problem in #5321, which was fixed using the technique in #5322, but only for the Facility > Learner/Coach Enrollment page.

To fix this for Groups, you must also make sure a Set of IDs is sent to the Membership API. Checking one checkbox, then select-all will result in having the first checkbox duplicated in the POST request.

**Comment by rtibbles** [comment]
This is fixed in #5353 and should be in the 0.12.3 release.
