### ISSUE TITLE
re-assigned exercise gives 500 error and does not show 'report error' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5351]
### Observed behavior

[reported in the forums](https://community.learningequality.org/t/bug-report-exercise-created-in-kolibri-studio-not-loading/1108):

> We found a bug when loading an exercise created in Kolibri Studio to our Instance.
> 
> The resource will not load within its frame (spinning wheel) and the log reports a 500 server error.
> 
> This error has started to occur after one of our users completed the exercise as part of a lesson and was re-assigned the same exercise in a later lesson.
> 
> Newly created student accounts can access the exercise and complete questions. However, if they navigate away and then attempt to open it again, the browser is unable to load the exercise (they just see a spinning wheel). This problem persists even if the user logs out and back in. Problem spotted on all devices tested.
> 
> Other exercises (e.g. from Khan Academy) load fine, even after multiple attempts at opening them. Screenshot below. The spinning wheel occurs where the system catches an Uncaught (in promise) error.

### Expected behavior

* exercises should always load without error
* if an error does occur, we should display the standard 'unhandled error' page so it's easier for the user to report it to us

### User-facing consequences

learners experience a broken application

### Errors and logs

![image](https://user-images.githubusercontent.com/2367265/55731243-7d85a380-59df-11e9-8e55-e23a2379baa9.png)

### Steps to reproduce

…

### Context

```
Version: 0.12.1
OS: Linux-4.15.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
Installer: apt
Server: Kolibri internal server
Database: /var/kolibri/.kolibri/db.sqlite3
Device name: watobe-2019-1-ubuntu-s-1vcpu-1gb-lon1-01
Free disk space: 21 GB
Server time: Mon Apr 08 2019 12:47:04 GMT+0200 (South Africa Standard Time)
```

**Comment by jonboiser** [comment]
This seems like a more advanced version of #4119 and #5147, where you can have problems when revisiting exercises and videos after mastering them. However, in those cases, you get a more detailed error from the 'masterylog' endpoint.

In this issue, the error seems to be coming from the 'contentsummarylog' endpoint.

**Comment by jonboiser** [comment]
As for the Uncaught Promise rejections, I think this is because there is no catch branch in the implementation of `ContentPage.initSession` and `ContentPage.updateProgress` (which make calls to those logging endpoints). We can just do the usual thing with 

```
.catch(error => this.$store.dispatch('handleApiError', error)
```
to shore this up.

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this issue in 0.15.1

**Comment by rtibbles** [comment]
Closing as fixed.
