### ISSUE TITLE
Video status not changing on completion

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5354]
### Observed behavior

The In progress symbol of any video doesn't change to yellow on completion of the video. When the video is rerun, it turns to yellow.

### Expected behavior

The progress symbol should turn yellow on completion of the video.

### User-facing consequences
No issue on the overall functionality, but students who are used to checking the completion status, not turning yellow is a kind of distraction

### Steps to reproduce

Run any video and check the progress on completion

### Context

* Kolibri version : Kolibri 0.12.2
* Operating system : ubuntu 14.04
* Browser : Chrome

**Comment by bjester** [comment]
Verified that upon finishing the video, the progress indicator now turns to completed yellow state on the video page as well as the parent topic, and the coach view.

Tested with `v0.12.3-alpha0`
