### ISSUE TITLE
[Feature] Request Guest Access as default landing page

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#5355]
It would be great to have an option to make the guest access page as the default landing page instead of current login page. 

An option to make the 'All Channels' page as default landing page could be provided both in the setup wizard and also in the configuration settings. 
This feature is important for our deployments in Cambodia. 

### User-facing consequences

At the moment, even when allow guest access is enabled. Users have to click the link to get to the content. 

Have the content (All channels) page shown as default landing page would be beneficial for users like young children and non-native english speakers. 

The faster we can get people to the content, the better the user experience.

**Comment by indirectlylit** [comment]
thanks for the suggestion @arky - I've noted it in our feedback tracker. We'll update this issue if it gets put on the roadmap

**Comment by arky** [comment]
@indirectlylit Is there any consensus on this feature request. We need this for our project in Cambodia. Thanks!

**Comment by indirectlylit** [comment]
Hi @arky –

It's not a request we've heard from other users, so it hasn't been prioritized. However it seems like a fairly low-risk change; I'll check with folks to see what they think and report back.

**Comment by arky** [comment]
Thanks @indirectlylit

**Comment by arky** [comment]
Basically when someone goes to http://kolibri.library then they get redirected to http://kolibri.library/en/guestaccess/ 

At the moment, I achieve this by using nginx URL rewrites. Perhaps a checkbox could be introduced facility setup wizard and in settings that sets this URI rewrite kolibri core automatically.

**Comment by indirectlylit** [comment]
ref: https://www.notion.so/learningequality/Updates-to-Kolibri-settings-f374a937f08248848f6c8399c53556a1

**Comment by indirectlylit** [comment]
@arky this has been added to the latest beta. Feel free to test it out, along with the other new 0.13.0 features:

https://github.com/learningequality/kolibri/wiki/0.13.0-beta-testing
