### ISSUE TITLE
Move points indicator from user dropdown into Learn Topnav

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5358]
### Observed behavior
Points are missing from the topnav view and are nested in the user dropdown

### Expected behavior
- Points moved back in their original spot in the learn topnav
- Points removed from the user dropdown
- ~Clicking on the point leaf icon brings the learner to their profile~
- Tooltip behavior stays the same

![points in topnav](https://user-images.githubusercontent.com/25045166/56388956-3072b000-61dd-11e9-9c3e-dec056569692.png)

<img width="278" alt="Screen Shot 2019-04-12 at 11 10 20 AM" src="https://user-images.githubusercontent.com/25045166/56057723-695de100-5d14-11e9-8575-35398158198b.png">

### Notes on particular design choices
- Circle shape behind the leaf SVG makes the point indicator look less like a button. Blends more into the topnav

### User-facing consequences
>`In 0.9.5b3, it used to show on the right hand top of the screen. After watching the videos kids used to see the accumulated points and feel happy about it. Now they are lost or confused as to they are not scoring points.`
`Though no impact functionally the kids getting a bit disinvested as the points are not visible to them. Teacher needs to tell them where to see the points. Leading to some classroom management issues and kids keep raising this as an issue.

**Comment by indirectlylit** [comment]
@khangmach any guidance for mobile?
