### ISSUE TITLE
Auth message is not displayed on classes page for unauthenticated users

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#5360]
### Observed behavior

When logged out user tries to access a learner's classes page, an unexpected error is displayed

<img width="709" alt="Screenshot 2019-04-13 at 19 56 57" src="https://user-images.githubusercontent.com/13509191/56083512-4facbe80-5e26-11e9-8a31-9f1c843e7c9b.png">

### Expected behavior

"Did you forget to sign in? You must be signed in as a learner to view this page " shows up.

### User-facing consequences

Just slight confusion (when user clicks "Back to home" as recommended, he will be redirected to Channels page which can be accessed by unauthorized users)

### Steps to reproduce

1. Make sure you're logged out
2. Visit `/learn/#/classes`

### Context

0.12.3a0.dev0+git.162.gc3af46e5

**Comment by MisRob** [comment]
First investigation showed:

When logged out user visits `learn/#/classes`, following happens
- API returns `403`
- When `CoreBase` is mounted within `LearnIndex`, `authorized` prop is not passed in (I suppose that’s because we allow logged out users to access Channels and Recommended sections maybe)
- `authorized` is set to `true` by default in `CoreBase` which causes `notAuthorized` computed prop to return `false`
- =>`<AuthMessage>` is not displayed, and because there’s an `error`, `<AppError />` fallback is triggered

There’s a [code prepared for handling logged out users](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/classes/AllClassesPage.vue#L22) but at the first sight it seems that it cannot be reached.

I suppose that this might be solved by passing this information into `CoreBase` using `authorized` param which would be calculated in `LearnIndex` according to whether the user is logged in or no and which page is accessed.

**Comment by MisRob** [comment]
Or, based on the fact that there are pages that need to control this behavior, I was also thinking if it would make sense to pull out `AuthMessage` and `AppError` from `CoreBase` and handle it rather locally which would make these things a bit more flexible.

**Comment by jonboiser** [comment]
I'm adding this case to issue #5305. In summary, the reason we're seeing this type of error is because the `showAllClassesPage` function handles errors using the catch-all `handleApiError` Vuex action. One solution would be to replace that `handleApiError` in the catch branch with some other reasonable behavior (like redirecting to a different part of the "Learn" page)

I think to make progress on #5305, in general, we may need to make some architectural change like you're suggesting (separating the error page component from CoreBase) so that individual pages can handle errors in the most appropriate way for the workflow.

**Comment by rtibbles** [comment]
> One solution would be to replace that handleApiError in the catch branch with some other reasonable behavior (like redirecting to a different part of the "Learn" page)

I think that there are quite a few places where we use the `handleApiError` without any extra handling, which I assume was only originally meant as a first pass catch all, it's probably a good idea for us to implement some more intelligent error handling!

**Comment by MisRob** [comment]
@jonboiser OK 👍 , didn't notice that it's related to #5305. Also thanks for the overview of Vuex part of error handling.

**Comment by jonboiser** [comment]
This should be resolved in Kolibri 0.14. If a user is not authenticated, they should be redirected to the main content page if they try to access the `/classes/` URL:

https://github.com/learningequality/kolibri/blob/6443d53eea37bcd8d33c42c592ffb93ab2074f22/kolibri/plugins/learn/assets/src/routes/classesRoutes.js#L10-L20
