### ISSUE TITLE
tox tests won't run on mac

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5364]
### Observed behavior

we currently leverage the daemonization (background) mode of kolibri for tox tests, but this doesn't work on mac so tests stall

see also https://github.com/learningequality/kolibri/issues/4821

### Expected behavior

tox tests should work on mac

### User-facing consequences

mac devs cannot run tox tests locally

### Errors and logs

…

### Steps to reproduce

run `tox -e py3.7` on mac

### Context

macOS, kolibri 0.12.x

**Comment by jonboiser** [comment]
This might be closable once

1. We move the suite of `tox` tests to GH actions
1. Write some documentation on how to run the tests locally using a tool like (e.g. https://github.com/nektos/act)

**Comment by rtibbles** [comment]
I think this is actually already fixed, as we moved the `kolibri start` command out of the tox tests a while back!
