### ISSUE TITLE
Windows installed app shows compilation error

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri#537]
After running the installed app and selecting "Load in Browser" option, following screen is shown (downloaded from http://dungeon.learningequality.org/browse/KOL-MTW-59/artifact/JOB1/Windows-installer/KolibriSetup-0.0.1.dev20160921203604.exe):

![image](https://cloud.githubusercontent.com/assets/7447496/18733006/5277c2f8-801c-11e6-8af5-1d0f6b9b23c7.png)

**Comment by mrpau-richard** [comment]
@jayoshih & @aronasorman I reproduced this issue in windows 7 32 bit. I will try to debug it.

![capture](https://cloud.githubusercontent.com/assets/8663934/18735698/79a947fc-80b2-11e6-8104-23579d668107.JPG)

**Comment by mrpau-richard** [comment]
@aronasorman I fix the `npm` error, and rebuild the Kolibri windows installer.
@jayoshih I tested the Kolibri windows installer latest build from http://dungeon.learningequality.org/browse/KOL-MTW and it's working fine.
