### ISSUE TITLE
rule dockerenvdist does not exist in Makefile

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5375]
### Observed behavior

When running the rule `docker-deb`, it has an [instruction](https://github.com/learningequality/kolibri/blob/develop/Makefile#L224) saying that `make dockerenvdist` or `make dist` should have been run.  
However, the rule `dockerenvdist` does not exist in the Makefile.

### Expected behavior

Instructions given should be correct

### User-facing consequences

Developers who run the make rules manually would be confused.

### Errors and logs

```
make: *** No rule to make target `dockerenvdist'.  Stop.
```
### Steps to reproduce

1. run `make docker-deb` and find out the instruction
2. run `make dockerenvdist`

**Comment by indirectlylit** [comment]
+1 

I just came across this, too

**Comment by jonboiser** [comment]
This is probably stale. Neither of these commands are in the Makefile anymore

To see what happened, you can take a look at the output here
```
git rev-list --all | xargs git grep dockerenvdist
```
