### ISSUE TITLE
update gherkin stories for new coach report workflows

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5399]
### Observed behavior

refs: https://github.com/learningequality/kolibri/pull/5383

cc @khangmach @jonboiser @radinamatic @mrpau-dev 

Do we have existing stories to work from, either from the old workflows or from the work leading up to 0.12.0?

### Expected behavior

workflows are updated so integration testing can proceed

### Context

0.12.x

**Comment by khangmach** [comment]
I do have stories but they're not formatted well. I'll write new ones for these features today

**Comment by khangmach** [comment]
Gherkin stories for these enhancements here: 
https://drive.google.com/open?id=1J9X_1wag_Q5GcnK70pa9goevBHMCRNQJ

**Comment by radinamatic** [comment]
Thank you @khangmach, I'll review those and include in the next gherkin scenarios update!

**Comment by khangmach** [comment]
Thanks @radinamatic

**Comment by khangmach** [comment]
ref: https://github.com/learningequality/kolibri/pull/5460

**Comment by indirectlylit** [comment]
hey @jonboiser @radinamatic - 

@khangmach was kind enough to open a PR. feel free to give feedback and then we'll merge in
