### ISSUE TITLE
Implement get_all_related as property of ContentMetadata Models

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#54]
get_all_related is currently implemented as an API function, but it would seem to make sense to implement this method as a computed property of the models.

However, this also makes me think - are the API methods that deal with a single model better implemented as Model properties/methods?

**Comment by indirectlylit** [comment]
cc @jamalex and @ralphiee22 - I'm not sure I understand the implications here. feel free to weigh in.

**Comment by rtibbles** [comment]
I am not sure I understand the implications here either. What was he on about?
