### ISSUE TITLE
Add group-level reports and preview button to exercise/resource report pages

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5403]
### Observed behavior

Currently, ReportsLesson(Resource|Exercise)LearnerListPage.vue does not have

1. an option to toggle an alternative view that groups learners and presents group-level summary statistics. 
1. a "preview" button that presents the resource or exercise in a way similar to the  exam or lesson creation workflow

### Expected behavior

A way to toggle group reports and preview items is available, along the lines of these designs:

**For ReportsLessonExerciseLearnerListPage**

![Exercise report - groups view (alt)](https://user-images.githubusercontent.com/10248067/56514183-800cf080-64e9-11e9-811f-ced7abadda39.png)

**For ReportsLessonResourceLearnerListPage**
![audio report - learners view](https://user-images.githubusercontent.com/10248067/56514315-cd895d80-64e9-11e9-8523-609f3019787e.png)

Other points:

1. This functionality will account for learners who are in more than one group. For example, if a learner "Pamela" is in two groups "A" and "B", then Pamela's row will appear in both grouped tables, and her progress will be incorporated into the summary statistics.
1. For the Resource version of the report, data for "view count" (to calculate the "Average number of views" statistic) may not be available from the backend
1. Do not add change the table header seen in the ReportsLessonExerciseLearnerListPage mockup to "Answer streak". Keep its current header. 
1. Only add the "Preview" button to the two reports pages discussed above. For example, do not add them to the ReportsGroupReportLessonResourceLearnerListPage.
1. To implement the "Preview" button, it might help to use the strategy used in #5417, where you link to the `RESOURCE_CONTENT_PREVIEW` route and provide extra data in the URL to get the correct exiting behavior (e.g. clicking the "X" button on on the preview page). See https://github.com/learningequality/kolibri/pull/5417/files#diff-59c8f3c9df19d72f38d1c9889771846fL108 for details.
1. The widget with circular icons and counts (e.g. yellow star, blue clock, red exclamation, blank circle) is a new element. The counts mean
    * yellow star - The number of learners in the group who have completed the exercise or resource
    * blue clock - The number (...) who have started the exercise/resource but not finished it
    * red exclamation - The number (...) who "need help" on the exercise (not applicable to non-exercise resources)
    * blank circle - the number (...) who do not fall into the other categories, i.e. the rest.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
@jonboiser @MisRob FYI this issue will require adding new strings, and string freeze is next Thursday. If this seems too ambitious to achieve, we should remove it from the 0.12.y milestone.

**Comment by MisRob** [comment]
JB already told me that this issue has a priority so I stopped working on other issues and have started working on this one yesterday evening and will continue today. I'll do my best to open the PR by the end of this week. So maybe we could leave the milestone here and then we'll see?

**Comment by indirectlylit** [comment]
sounds good. Another technique is to do the updates in two stages:

* initial PR with just the static component structure and strings for translation
* second PR hooking up logic and data, which can be after string freeze

**Comment by MisRob** [comment]
Good idea, thanks.

**Comment by MisRob** [comment]
I've just studied translations and existing translation files and found out that both "Preview" and "View reports by" are actually translated already (`previewLabel`, `viewByGroupsLabel`) from the past even when strings are currently not being used anywhere :)! According to mockups, it seems that there are no other new strings needed.

**Comment by jonboiser** [comment]
This feature was added in #5453 and should be available in the 0.12.4 release

**Comment by indirectlylit** [comment]
In fact it will be in 0.12.y (likely 0.12.4)
