### ISSUE TITLE
Simplify linting process

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#5410]
1. Eliminate HTMLHint and replace all rules with eslint ones
2. Eliminate custom indent/spacing functions - some parts already are or can be replaced by `vue/html-indent`, `vue/script-indent`, for some of them we'll need new eslint rules (mostly spacing stuff)
2. If possible, run prettier on the entire vue component, and using the eslint-plugin-prettier.
3. Run stylelint on the entire vue component after eslint/prettier has been run on it, to reduce callback/promise hell.

So `lint.js` would be simplified to:
1. If JS, run eslint with prettier plugin.
2. If CSS/SCSS/SASS/LESS, run stylelint (open question of whether we want to run prettier or not on our style files too).
3. If Vue component, run stylelint, then run eslint with prettier.

References: #5400

### User-facing consequences

None

**Comment by indirectlylit** [comment]
similar issue from last year here: #4050
