### ISSUE TITLE
Cannot serve serving resources in storage when a custom KOLIBRI_URL_PATH_PREFIX is used

### ISSUE THREAD

**Issue by swiftugandan** [learningequality/kolibri#5414]
### Observed behavior

* Start Kolibri with: `KOLIBRI_URL_PATH_PREFIX=/kolibri KOLIBRI_HTTP_PORT=18888 kolibri-0.12.2.pex --foreground start`
* Import PHET English Channel

```
wget http://localhost:18888/kolibri/content/storage/5/4/541e70e8ed4325d5bed65595632ec22f.png -O /dev/null
```

Output:

```
--2019-04-23 12:59:01--  http://localhost:18888/kolibri/content/storage/5/4/541e70e8ed4325d5bed65595632ec22f.png
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:18888... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-23 12:59:02 ERROR 404: Not Found.
```

### Expected behavior

* Start Kolibri with: `KOLIBRI_URL_PATH_PREFIX=/ KOLIBRI_HTTP_PORT=18888 kolibri-0.12.2.pex --foreground start`
* Import PHET English Channel

```
wget http://localhost:18888/content/storage/5/4/541e70e8ed4325d5bed65595632ec22f.png -O /dev/null
```

Output
```
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:18888... connected.
HTTP request sent, awaiting response... 200 OK
```

### User-facing consequences

When the KOLIBRI_URL_PATH_PREFIX is set to a path other than /, resources (images, pdf, videos, etc) will not be able to load from storage

### Errors and logs

See above

### Steps to reproduce

See above

### Context

* kolibri-0.12.2.pex
* Ubuntu 18.04
* Any

**Comment by indirectlylit** [comment]
Hi @swiftugandan - just a heads-up that we are in the beta-testing phase of 0.12.4, which includes this fix.

If you'd like to help us test this release, any feedback would be welcome!
https://github.com/learningequality/kolibri/releases

Thank you!
