### ISSUE TITLE
Allow an exit path from search

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5418]
### Observed behavior
Currently there isn't a way for a user to easily exit the search view in the LEARN tab. More details here: https://github.com/learningequality/clearinghouse/issues/32. The user has to click on the hamburger menu and then click on the 'Learn' menu option again.

### Expected behavior
Have an easy way to get back to Learn home page. Swap the current appbar with a static back appbar that leads back to the root page of Learn.

Label text: Learn

![end-state](https://user-images.githubusercontent.com/25045166/56693548-8fcb3700-6699-11e9-8054-99f173941fab.png)

### User-facing consequences
Complicates the user experience. Unnecessary navigation back to home

### Steps to reproduce
- Navigate to Learn tab
- Input a search query
- Press search button

### Context
Tell us about your environment, including:
 * Kolibri version: Kolibri 0.12.2
 * Operating system: MacOS
 * Browser: Chrome

**Comment by jonboiser** [comment]
Implemented in #5459, but looks a little different than the description in the original post (different color, label, and back link behavior).

**Comment by indirectlylit** [comment]
This is fine, but the inconsistency with lesson and quiz creation is a little odd

| search in channels | search in quizzes | search in lessons |
|--|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/57497041-cf457600-728a-11e9-96b8-684545581ade.png) | ![image](https://user-images.githubusercontent.com/2367265/57496810-bc7e7180-7289-11e9-95a6-7092103ea130.png) | ![image](https://user-images.githubusercontent.com/2367265/57496934-50503d80-728a-11e9-9a82-389b85289646.png) |
