### ISSUE TITLE
'NaN' in titles of difficult questions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5427]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/56761336-ed22bf00-6751-11e9-937a-1d8bd4d78e96.png)

![image](https://user-images.githubusercontent.com/2367265/56761322-e5631a80-6751-11e9-837b-32e2f885b74c.png)

### Expected behavior

When there is more than one question drawn from a single exercise, the questions should be numbered with incrementing integers

### User-facing consequences

Confusion

### Errors and logs

None

### Steps to reproduce

See it live on the demo server: http://kolibridemo.learningequality.org/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/quizzes/448067d8b82df0a03902ea2aeff939e2/questions

### Context

0.12.2

**Comment by radinamatic** [comment]
Yep, came up during the demo today... :confused:
