### ISSUE TITLE
option to change password is not visible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5428]
### Observed behavior

Report [from the forums](https://community.learningequality.org/t/ability-to-change-password/1132) that users cannot change their passwords:

Profile page:

> ![image](https://user-images.githubusercontent.com/2367265/56763817-1ba39880-6758-11e9-8556-f8eb74723d44.png)

Facility settings:

> ![image](https://user-images.githubusercontent.com/2367265/56763836-23633d00-6758-11e9-8c2a-fc6733e896e3.png)

### Expected behavior

Users should always be able to change their passwords

### User-facing consequences

Need to get the super admin's help with passwords

### Errors and logs

None

### Steps to reproduce

Unsure

### Context

0.12.2

**Comment by jonboiser** [comment]
This was caused by this change https://github.com/learningequality/kolibri/commit/26e7aa09c1b89f4c397ec1be73b137defde7fde6#diff-e6f9d430bec93da2796a5f3a068d8e6dL312

and not updating all the property names of the `facilityConfig` copy that was also loaded into `state.core.facilityConfig`

**Comment by jonboiser** [comment]
So, the users observing this with 0.12.2, do so for a different reason, since #5340 is not part of that codebase.

**Comment by jonboiser** [comment]
To fix this for 0.12.2, we should

1. Put the option to toggle the `learner_can_edit_password` field back in the Facility Configuration page.
1. Make sure the Profile Page allows learners to edit passwords if `learner_can_edit_password` is set to true.

**Comment by rtibbles** [comment]
2) is definitely already the case.

**Comment by rtibbles** [comment]
Looks like we can do 1) for 0.12.3, as the required string still exists!

**Comment by jonboiser** [comment]
Updated #5433 to add 'learn can edit password' back to the UI. And opened #5447 to fix this for release0.12 branch.

**Comment by jonboiser** [comment]
Forgot to add a Changelog entry for #5447. We should also update the forum users after 0.12.3 is released.
