### ISSUE TITLE
Submit button on top right corner of a quiz

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5440]
**Observed behavior**
The students sometimes directly press the Submit button on the top right corner of any quiz without even start or just after attempting the first question. This inturn directly completes the quiz.

**Expected behavior**
The Submit button appears in the last page of the quiz so that students don't press it by mistake. On the last page of the quiz we can have the submit button in the place of next button.

**User-facing consequences**
The exams/quizzes get submitted even before they are attempted or completed. This in turn affects the teacher who had prepared and planned for the quiz.

**Steps to reproduce**
Create a quize and check using any tablet.

**Context**
Kolibri version : Kolibri 0.12.2
Operating system : ubuntu 14.04
Browser : Chrome
![Screenshot_20190430-153902](https://user-images.githubusercontent.com/8583367/56955618-8b9e8e00-6b5f-11e9-9eae-5ed89350b5fd.png)

**Comment by indirectlylit** [comment]
@miyer03 feel free to give feedback on a proposed change in #5448
