### ISSUE TITLE
malformed database

### ISSUE THREAD

**Issue by KW4NP** [learningequality/kolibri#5454]
### Observed behavior

…

### Expected behavior

Kolibri should have started but did not.  Deleting the db.sqlite3 file did not help.  It looks like it could actually be a content database issue but the error does not specify which database is causing trouble.

### User-facing consequences

We can't use Kolibri, and the box is scheduled to leave to an area with very little opportunity for support in a few days.

### Errors and logs

[kolibri.log](https://github.com/learningequality/kolibri/files/3149203/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/3149204/server.log)

### Steps to reproduce

Using IIAB on a Raspberry Pi 3 B+, install Kolibri and download content.  Leave it running for a few days with the occasional power loss.

### Context

Kolibri 12.2
Raspbian

**Comment by rtibbles** [comment]
This looks like an issue with a corrupted job_storage file.

Could you try deleting the `job_storage.sqlite3` in the home directory, and see if this fixes the issue?

If so, we can add some automated catching of this kind of error in future.

**Comment by KW4NP** [comment]
@rtibbles , that did not seem to help.  It looks like the same error coming back.

**Comment by rtibbles** [comment]
OK, yeah looks like it is not the job storage DB, but a malformed Content database. Could you try deleting `131e543dbecf5776bb13cfcfddf05605.sqlite3` from the `content/databases` folder in the kolibri home dir?

**Comment by KW4NP** [comment]
It looks like that was it.  What causes the content database to become corrupted?  Do I need to re-download that content?

**Comment by rtibbles** [comment]
Yes, it looks like the DB was probably corrupted during download, so it would probably need to be reimported, yes.

**Comment by KW4NP** [comment]
Thanks for your help.  It seems to be fixed now, but that is not a beginner level error.  You might want to consider some way to at least indicate which database is down.

**Comment by rtibbles** [comment]
Yes - we have a soon to be released fix to handle corrupted database files automatically!

**Comment by KW4NP** [comment]
That will be nice - a little late for me though.  I will close the issue as you have a fix to be released.

**Comment by indirectlylit** [comment]
fixed by https://github.com/learningequality/kolibri/pull/5419
