### ISSUE TITLE
Edge cases when deleting all recipient groups for a lesson (and probably quizzes)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5462]
### Observed behavior
Setup:

1. Create a Lesson and assign to a group
1. Delete that group. Now the Lesson is literally assigned to nobody.

**Problem 1: Reports incorrectly say lesson recipient is "Entire class"**

On Plan page: "Assigned to nobody" has no more recipients

![Screen Shot 2019-05-07 at 4 56 48 PM](https://user-images.githubusercontent.com/10248067/57340218-b6518f00-70e9-11e9-999b-8c74bb32395e.png)

On Report page: "Assigned to nobody" is assigned to whole class

![Screen Shot 2019-05-07 at 4 56 54 PM](https://user-images.githubusercontent.com/10248067/57340254-c8cbc880-70e9-11e9-8ad4-44abfe5d85c5.png)

**Problem 2: Saving a "No one" quiz with "Entire class" doesn't fix it**

Steps:

1. Get a "no one" lesson by assigning a lesson to a group, then deleting that group
1. Go to the "Edit details" page for the lesson. The "Entire class" option will be selected under recipients
1. Save the lesson
1. The lesson will still be assigned to nobody.

### Expected behavior

1. Problem 1: The report version of lesson accurately conveys that the lesson is assigned to nobody.
1. Problem 2: Saving a quiz with the "Entire class" option selected will re-save quiz and assign it to the whole class. (Alternatively: a quiz being assigned to no one is an option, with its own form control).

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Version 0.12 develop

**Comment by indirectlylit** [comment]
@bjester mind taking a look at this one?

**Comment by bjester** [comment]
@indirectlylit Will do

**Comment by bjester** [comment]
Classes are being filtered out of the API response, so in some cases, the front-end doesn't have enough info to determine whether or not the lesson or quiz is assigned to the class or no one.

**Comment by jonboiser** [comment]
This has been fixed in #5521, it address

Problem 1 (Wrong labels in the Reports page): If a Lesson/Exam has 0 assigned Collections (i.e. Learner Groups or Classroom), then it says "No one" in the recipients column. It also adjust lower-level reports by hiding links to Resource>Learner reports in the Lesson Case, and lists no learners in the Quiz>Learner report.

Problem 2 (Recipients menu in Edit Details inaccurate): If a Lesson/Exam has no assignments, then neither the "Entire" classroom radio button nor any of the learner group checkboxes are selected. The user can select those options and re-save, and the Lesson/Exam will be reassigned.
