### ISSUE TITLE
Edge case with long, unbroken title on content cards

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5464]
### Observed behavior
Related: https://github.com/learningequality/kolibri/issues/5468

These are some PDFs from the TESSA channel, which have as their title, a very long single word, like "namba_ya_moduli_1__kusoma_na_kuandika_kwa_madhumuni_mbalimbali_printable"

On the cards, this ends up being completely elided:

![Screen Shot 2019-05-08 at 3 10 45 PM](https://user-images.githubusercontent.com/10248067/57411883-b4e49d00-71a3-11e9-8147-d36a31fb6bdb.png)

Updated screenshot:

![image](https://user-images.githubusercontent.com/10248067/110861438-fbf5ba80-8272-11eb-9e1d-6f25a8d0f643.png)

### Expected behavior

An alternative way to show at least a little bit of these long titles.

The text should be truncated such that it does not run off the side, even if the text is one long un-spaced string. Hovering should show a tooltip with the whole title.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

v0.12 develop
…

**Comment by radinamatic** [comment]
Still extant ([recent Slack conversation](https://learningequality.slack.com/archives/CB37UM23A/p1607656280385500)), not sure if we could up the priority @jonboiser?

http://35.227.71.104/en/learn/#/topics/c/991073b0312e4959aaa3118340c584a3
http://35.227.71.104/en/learn/#/topics/t/708fc2e73a0f4ab59dfeebfd1203896d
