### ISSUE TITLE
Add coach_content GET filtering to ContentNode endpoint 

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#5467]
### Observed behavior

While browsing channel content within Kolibri as an unauthenticated user, Coach content is correctly hidden from view. Although, as an unauthenticated user, I'm able to search for the name of the content to find it, open it, and view it.

#### Observed: Visible while signed in as user with Coach permissions
![visible-authenticated](https://user-images.githubusercontent.com/819838/57479672-d05ab100-7252-11e9-93bd-57ca55abb21d.png)

#### Observed: Hidden while signed out
![hidden-unauthenticated](https://user-images.githubusercontent.com/819838/57479711-e7010800-7252-11e9-9d57-084fc33e5a56.png)

#### Observed: Discoverable in search
![discoverable-in-search](https://user-images.githubusercontent.com/819838/57479737-f1230680-7252-11e9-9389-c9cf26ac8e99.png)

### Expected behavior

Coach content or other restricted content should not be discoverable in search if the user is not authenticated.

### User-facing consequences

Learners could access coach content by accessing it through search.

### Errors and logs

Nothing relevant in logs.

### Steps to reproduce

1. Sign in as super admin into Kolibri instance.
2. Import entire "Epub Testing Channel" from token `gojad-patot`
3. Browse channel and access "Epub Edge Cases" topic
4. Observe "UNICEF Brochure" and "Grammar Worksheet" are accessible
5. Copy URL to "Epub Edge Cases" topic
6. Sign out
7. Go to previously copied URL
8. Observe "UNICEF Brochure" and "Grammar Worksheet" are missing
9. Search for "UNICEF"
10. Observe you can access the "UNICEF Brochure" from search

### Context

Reproduced in both Chrome 74 and Firefox 66
```
Version:           0.12.3a0.dev0+git.588.gb16cbfff
OS:                Linux-4.15.0-48-generic-x86_64-with-Ubuntu-18.04-bionic
Installer:         devserver
Server:            WSGIServer/0.2 CPython/3.6.7
Database:          /home/bjester/Projects/learningequality/kolibri-data/develop/db.sqlite3
Device name:       phizbo
Free disk space:   1,135 GB
Server time:       Thu May 09 2019 11:54:45 GMT-0700 (Pacific Daylight Time)
Server timezone:   America/Los_Angeles
```

## Proposed solution

* Add coach_content GET param filtering to ContentNode Filter
* In the frontend set it based on the currently logged in user's role
  * false if not {isCoach, isAdmin, isSuperuser}
  * true otherwise

**Comment by jonboiser** [comment]
Some of the missing stuff looks like "Coach content" (they have that blue "person reading a book icon"), I think this is expected behavior, since you need to be logged in as a coach to see these items.

**Comment by bjester** [comment]
@jonboiser Okay so should expected behavior be that it should not be discoverable in search? Or do we care?

**Comment by jonboiser** [comment]
Expected behavior should be that Coach Content does not appear when a user is not authenticated, since an authenticated user is like a Learner, but with even less access (e.g. access to Classroom Assignments)

**Comment by rtibbles** [comment]
Seems like we don't filter based on coach content in the backend: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/content/api.py#L715 although, I wonder if this is a case where filtering it on the frontend might be a better fix (to prevent the search from becoming cached on a per user basis only).

**Comment by rtibbles** [comment]
Or we should just be setting a coach_content filter GET param on the frontend - dependent on the user type.

**Comment by jonboiser** [comment]
Awhile back, @ralphiee22 implemented a filter on some ContentNode APIs that takes a `by_role` parameter (forgetting the exat usage). I assumed this was used everywhere on the Learn page to do the backend filtering

**Comment by rtibbles** [comment]
Yeah - that's a little problematic for caching as it uses user session info to determine the content of the query. It seems to currently be only used on recommendation endpoints (which is sort of OK, as that is per user mostly), but it is also used in the topic handlers.

We should probably change how we handle this to filter explicitly by the role, or filter after fetch on the frontend.

**Comment by indirectlylit** [comment]
> Or we should just be setting a coach_content filter GET param on the frontend - dependent on the user type.

Certainly prefer this to client-side filtering, coupled with real API-level protection checks on the session authorization. Wouldn't want the kids stealing those answer keys ;)

**Comment by indirectlylit** [comment]
0.12.y or 0.13.0? I'd lean towards the latter but don't feel strongly

**Comment by rtibbles** [comment]
Fine with the latter, just so as not to add more to the plate.
