### ISSUE TITLE
Content recommendation caching layer issue

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#548]
## Summary

Since bug bash last week I keep getting this `MultiValueDictKeyError` on Learn with every channel (no error on Explore)...

![kolibri - chromium_089](https://cloud.githubusercontent.com/assets/1457929/18842374/0cecd6d6-8415-11e6-9a65-e4aa8e4c474b.png)

[MultiValueDictKeyError - full traceback.txt](https://github.com/learningequality/kolibri/files/493574/MultiValueDictKeyError.-.full.traceback.txt)

@ralphiee22

**Comment by rtibbles** [comment]
How many channels do you have installed, @radinamatic?

**Comment by radinamatic** [comment]
Four at the moment.

**Comment by radinamatic** [comment]
And it is still there after server restart... :unamused:

**Comment by radinamatic** [comment]
@ralphiee22 Changing `channel_id` to `channel` in `kolibri/content/api.py#L127` did the trick! :+1:
