### ISSUE TITLE
Log files as .txt

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5483]
### Observed behavior

Windows users have issues opening up log files, and often reports lack log info (which surely could also be caused by other challenges).

This will require renaming existing log files and updating documentation.

Follow-up from https://github.com/learningequality/kolibri/issues/2512

### Expected behavior

Windows user can easily navigate to directory with log files and view them.

### User-facing consequences

Easier debugging and more efficient support inquiries.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

0.13

**Comment by lyw07** [comment]
should be resolved in https://github.com/learningequality/kolibri/pull/5495

**Comment by benjaoming** [comment]
Did we get documentation updated @lyw07 ?

> This will require renaming existing log files and updating documentation.

I can move this issue to kolibri-docs to continue it there...

**Comment by lyw07** [comment]
Hi @benjaoming 

I updated the documentation [here](https://kolibri.readthedocs.io/en/latest/manage.html#locate-kolibri-log-files) with the indication that the logs files are named with .txt. The PR is [here](https://github.com/learningequality/kolibri-docs/pull/97).
Do you know if there are other places in the documentation that needs update? Thank you!

**Comment by benjaoming** [comment]
Thanks @lyw07 - no this was exactly the one I failed to find, was trying to read pull requests etc :)
