### ISSUE TITLE
Move HeaderTable and HeaderTableRow into design system

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#5487]
Move `HeaderTable` and `HeaderTableRow` from the coach reports plugin into the core components as mentioned here https://github.com/learningequality/kolibri-data-portal/pull/7#issuecomment-489178124.

**Comment by indirectlylit** [comment]
Issue moved to [learningequality/kolibri-design-system #220](https://github.com/learningequality/kolibri-design-system/issues/220) via [**ZenHub**](https://www.zenhub.com/)
