### ISSUE TITLE
update gherkin stories to exercise import availability behaviors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5493]
### Observed behavior

In https://github.com/learningequality/kolibri/pull/5490 we are changing the expected behaviors and semantics of importing

### Expected behavior

Let's add gherkin stories to help the testers walk through the various scenarios

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Is this still valid/needed?

**Comment by radinamatic** [comment]
Let's not close it just yet - I suggest re-targeting to `upcoming patch`. Availability annotation and importing has changed very much, with so many moving parts (especially in the final stretch), that I doubt the current scenarios cover all the necessary and recommended angles.

**Comment by rtibbles** [comment]
Is this still extant?

**Comment by radinamatic** [comment]
Two major versions and almost 2 years worth of testing after, I'd say it should be good to close.
