### ISSUE TITLE
"Time spent" column in resource/exercise lesson report not being live-updated

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#5496]
### Observed behavior

"Time spent" column in learners table of resource/exercise lesson report is not being live-updated.

![time-spent](https://user-images.githubusercontent.com/13509191/57871067-cf082600-7808-11e9-9396-27b99932ce58.gif)

### Expected behavior

"Time spent" column should be updated together with "Status" and "Last activity" columns. 

### User-facing consequences

Missing information. Can be fixed by page reload.

### Steps to reproduce

1. Add a resource/exercise to a lesson
2. Open two windows (at least one of them anonymous)
3. Login as coach in a first window and navigate to Coach -> Reports -> Lessons -> lesson -> exercise/resource and watch learners table.
4. Login as a lesson learner and watch the resource/fill in the exercise

### Context

Kolibri 0.13.0a0.dev0+git.13.g8e38e23a

**Comment by nucleogenesis** [comment]
Resolved with merge of #5963
