### ISSUE TITLE
Document Hashi capabilities and limitations

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#5504]
Need to have some docs about capabilities of HTML5 app renderer and the limitations (e.g. sandboxing) and on different platforms, e.g., IE.

Sample first draft of things to cover here:
https://files.slack.com/files-pri/T0KT5DC58-FJT5J8Y1W/download/hashi_docs_readme.txt

There is also already some docs here, but more for LE devs (internal docs):
https://github.com/learningequality/kolibri/tree/develop/packages/hashi

With this issue I'm suggesting to add new type of docs for "external" devs, like chef authors or anyone who wants to adapt their HTML5 content to Kolibri (but doesn't need to know inner workings of hashi; just take advantage of it).

### User-facing consequences

Web developers targeting the Kolibri platform will know exactly what features they can use and what workarounds are available.

**Comment by rtibbles** [comment]
I think the main spirit of this is covered by #8086 now - and from 0.15 onwards, the caveats around Hashi are significantly reduced.
