### ISSUE TITLE
Integration Testing Spreadsheet Docker Implementation Improvements

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#5505]
### Things to resolve

The docker setup in #5313 introduces some things to be improved upon at a later time:
- extra requirements file used soley in docker containers
- some permissions reassignment issues that docker could handle for us
    - Improper use of a bind mount. I had avocated for it, but the approach changed and introduced the need for this permission change.
- Introduces potential security issues 
    - addition of a "secret" file directory to an env.list
    - multiple file copies between native machines and containers
- More-verbose-than-necessary environment variable copying
- Buildkite step was made multi-command

**Comment by rtibbles** [comment]
Fixed in #8318
