### ISSUE TITLE
Cancelling content import and export not working 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5513]
### Observed behavior

Cancelling import is not working: once the <kbd>Cancel</kbd> button is clicked, it appears disabled, but the import continues and there seems not to be a way to stop it, even on page reload the bar is still in progress.

### Expected behavior
User should be able to stop the content import if they need.

### User-facing consequences
Unable to cancel import operation.

### Errors and logs
Nothing overt in the command line or the browser console

[kolibri.log.part.log](https://github.com/learningequality/kolibri/files/3194771/kolibri.log.part.log)
(partial during the import operation)

### Steps to reproduce
Try to cancel channel mid import.

### Context
 * Kolibri version: 0.12.y dev branch
 * Operating system: Ubuntu 18.04
 * Browser: FF 66 & Chrome on Ubuntu 18.04

**Comment by bjester** [comment]
If helpful, I see the request to the cancel endpoint never completes; it remains in `(pending)` state.

**Comment by rtibbles** [comment]
How much content were you trying to import (it looks like the import completed very quickly) - does the same behaviour happen if you import a much larger set of content?

**Comment by bjester** [comment]
@rtibbles I saw this in slack while I was setting up Kolibri for another issue and imported a few GB's of content and it did not cancel. In the network tab I saw the request as `(pending)` and continued to be pending even after the import finished.

**Comment by rtibbles** [comment]
Hrm, must be something suspicious happening in the cancel endpoint - when I was working locally, I thought it was just due to the single threaded nature of the dev server, but will take a closer look.

**Comment by radinamatic** [comment]
@rtibbles I think it was around 1GB of content (I was trying to check for some steps in the Gherkin that state 1GB of content triggers the change in the `Space available on the device` field), but I have made several tests to confirm, so other imports could have been smaller.

**Comment by rtibbles** [comment]
OK, seems like the cancellation is failing to complete for some reason. Will investigate.

**Comment by indirectlylit** [comment]
also includes export as per #5528

**Comment by lyw07** [comment]
fixed in #5542
