### ISSUE TITLE
not enough spacing above title

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5515]
### Observed behavior

Post merge of #5502, the spacing above the title is too small:

These changes fix overlapping of progress bar with thumbnails.

Before

![Screenshot from 2019-05-18 00-29-13](https://user-images.githubusercontent.com/35173644/57950166-1e7f4c80-7904-11e9-8415-0e3913a7722a.png)

After

![Screenshot from 2019-05-17 23-30-38](https://user-images.githubusercontent.com/35173644/57947345-49fe3900-78fc-11e9-8f62-376e49b42970.png)

### Expected behavior

standard spacing around the text

### User-facing consequences

not much - slight inconsistency in layout

### Context

0.12.x

**Comment by priyanka-choubey** [comment]
I would like to work on this.. thank you

**Comment by indirectlylit** [comment]
thank you!

**Comment by priyanka-choubey** [comment]
Currently, the padding is of 16px . Should I make it 24. @indirectlylit  
![Screenshot from 2020-02-29 22-22-51](https://user-images.githubusercontent.com/33806116/75611668-8bd23600-5b42-11ea-859e-157cfc8c9083.png)

**Comment by indirectlylit** [comment]
looks good!

**Comment by priyanka-choubey** [comment]
I think there was a misunderstanding my comment. The attached screenshot is of the current padding ie 16px. If it looks okay then the issue can be closed.

**Comment by indirectlylit** [comment]
Ah, I see. Yes, it looks like the current behavior is different from (and better than) the "After" screenshot posted in the description of this issue.

thank you
