### ISSUE TITLE
"Welcome to Kolibri" modal not closing

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5518]
### Observed behavior
The `Welcome to Kolibri` modal not closing after I click the `ok` button

### Expected behavior
It should close when I click the `ok` button

### User-facing consequences

…

### Errors and logs
![Screen Shot 2019-05-21 at 1 10 58 PM](https://user-images.githubusercontent.com/8663934/58070296-1a388500-7bcb-11e9-889b-9bd2512cfe0a.png)

### Steps to reproduce
* Install the Kolibri 0.12.4-beta2 on fresh installation
* After the Kolibri setup finish
* The `Welcome to Kolibri' modal show up and can't close

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.4-beta2
 * Operating system: Windows 7
 * Browser: Firefox 65.0.5

**Comment by mrpau-julius** [comment]
Also on Windows 10, IE edge, the `Welcome model button` is not clickable.
![welcome_model_Button_not_clickable](https://user-images.githubusercontent.com/38421180/58070906-5cfb5c80-7bcd-11e9-88a2-07e5e726372f.png)

**Comment by lyw07** [comment]
same happened to me on macosx with google chrome version 74.0.3729.157 (latest version).
also this issue does not show up in 0.12.3.

**Comment by jonboiser** [comment]
It's because I missed a `submit` listener on this one modal! It's a one line fix coming soon.

**Comment by lyw07** [comment]
for the issue, the current workaround is to refresh the page.
