### ISSUE TITLE
Cancelling channel export not working

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5528]
### Observed behavior
Clicking the <kbd>Cancel</kbd> button during channel export does not work.  It dims the button but the operation still proceeds and eventually shows the dimmed <kbd>Close</kbd> button.

### Expected behavior
The export channel operation is cancelled.

### User-facing consequences
Cannot cancel the export channel operation.

### Errors and logs
None found.

### Steps to reproduce
Import a channel then try to export that.

### Related issue
This is similar to #5513 

### Context
* Kolibri version: 0.12.4b2
 * Operating system: Windows 10 Enterprise Evaluation
 * Browser: IE11, Edge

### Screenshot or .gif
![kolibri--v0 12 4b2--export channel cannot cancel](https://user-images.githubusercontent.com/175580/58149371-48829700-7c95-11e9-9ec2-212e8e217544.gif)

**Comment by indirectlylit** [comment]
thanks - I've expanded the scope of #5513 to include import and export because they are pretty clearly the same issue
