### ISSUE TITLE
Import error - failure at 199.32% (sic)

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#5529]
Import of two files from Osmosis - first import post installation.
System reported 199% downloaded!
![2019-05-22 16 55 40 192 168 1 104 c4399d75a822](https://user-images.githubusercontent.com/1372447/58164791-1125e180-7cb9-11e9-9643-3ad24fe67d5e.jpg)
![2019-05-22 16 55 16 192 168 1 104 c3ef5b28cea6](https://user-images.githubusercontent.com/1372447/58164792-11be7800-7cb9-11e9-99b0-7dd79264abd7.jpg)

### Errors and logs

attached
[kolibri.log](https://github.com/learningequality/kolibri/files/3206734/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/3206733/server.log)

### Context
 * Kolibri version
12.3
Linux alarm 5.0.11-1-ARCH #1 SMP Fri May 3 01:14:14 UTC 2019 aarch64 GNU/Linux
Vivaldi

**Comment by indirectlylit** [comment]
hi - are you running the `kolibri-server` debian package?

If so, this is likely a duplicate of https://github.com/learningequality/kolibri-server/issues/14

**Comment by nobicycle** [comment]
Hi indirectlylit,
Running Arch Linux on a Pine Rock64 Single Board Computer
virualenv install

**Comment by indirectlylit** [comment]
okay - so you installed with `pip install`? in that case it's probably a different issue

**Comment by indirectlylit** [comment]
closing because much of import/export has been refactored in 0.13. If this is observed again, let's re-open
