### ISSUE TITLE
Empty container showing when I import a channel

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5537]
### Observed behavior
There is an empty container showing when I import a channel. 

### Expected behavior
That container should not show if it's empty

### User-facing consequences

…

### Errors and logs
![Screen Shot 2019-05-23 at 12 08 52 PM](https://user-images.githubusercontent.com/8663934/58225284-e2a91480-7d53-11e9-8ff1-4fff2639b180.png)

<--
Please wrap errors in triple backticks for clean formatting like this:
```
01:10 info: something happened
01:12 error: something bad happened
```
-->

…

### Steps to reproduce
* Using an admin account
* Select and import a channel 
* The empty container will show up in a few seconds

### Context
Tell us about your environment, including:

* Kolibri version: v0.12.4-beta3
* Operating system: Windows 7
* Browser: Firefox 67.0

**Comment by radinamatic** [comment]
Isn't that just the container, before the content inside is loaded? 

![Ubuntu16 04 (0 12 4-b3)  Running  - Oracle VM VirtualBox_050](https://user-images.githubusercontent.com/1457929/58225781-09e7ed80-7d24-11e9-8b4f-e992b1b3c177.png)


Does the channel content appear at all, or you're just stuck at that point? Any errors in logs, Console...?

**Comment by mrpau-richard** [comment]
The channel properly loaded in a few seconds with no javascript error. It's just that empty container showing when you import a channel.

**Comment by indirectlylit** [comment]
@mrpau-richard could you please fill out the rest of the issue template?
