### ISSUE TITLE
descenders in text are clipped in select dropdowns

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5538]
### Observed behavior

See the 'g' in 'English' below. This seems to be happening many places

![image](https://user-images.githubusercontent.com/2367265/58226383-4b07df80-7cdb-11e9-9a5e-3f5ff3f67207.png)

### Expected behavior

no clipping

### User-facing consequences

hard-to-read text

### Context

0.12.3

**Comment by indirectlylit** [comment]
this seems to have regressed. Observed in 0.13.0 alpha 0:

![image](https://user-images.githubusercontent.com/2367265/60378608-a3688600-99d9-11e9-82db-82985644bbe8.png)


However, doesn't seem to exist in 0.12.5:

![image](https://user-images.githubusercontent.com/2367265/60378615-c2ffae80-99d9-11e9-9ef5-0f1ba5b64e06.png)

**Comment by nucleogenesis** [comment]
I'm not seeing this anymore tested in Chrome / IE11 (Windows 10) or Chromium / Firefox (Debian)

**Comment by indirectlylit** [comment]
great, thanks
