### ISSUE TITLE
kTextbox is not fully set up to pull colors from the theme

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5539]
### Observed behavior

A few of the colors come from the theme, but others (such as various text colors) do not. For example:

* `$ui-input-feedback-color--invalid`
* `$ui-input-text-color--disabled`
* `$ui-input-text-color`

### Expected behavior

all values should pull from the theme

### User-facing consequences

inconsistent UX and hard-to-maintain code

### Context

0.12.3

**Comment by indirectlylit** [comment]
@nucleogenesis another KSelect issue

**Comment by rtibbles** [comment]
Looking at https://github.com/learningequality/kolibri-design-system/blob/main/lib/KTextbox/index.vue this appears to have been resolved.
