### ISSUE TITLE
"ePUB document" option is missing file size in the 'Download content' dropdown

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5543]
### Observed behavior

~Dropdown for <kbd>Download content</kbd> seems to be presenting unformatted (JSON?) data instead of the human-readable information:~

The unformatted JSON string issue is fixed in #5540, but the button label is still missing the file size.

![haruko-jpeg - Kolibri - Mozilla Firefox_056](https://user-images.githubusercontent.com/1457929/58288981-6810e100-7db5-11e9-8a2a-06ecb4515d94.png)

Seems to happen for all the ePUB documents, but not on other types of content on 0.12.4b4 at the hack sesh server http://35.236.125.21:8080

### Expected behavior

Dropdown should read `ePUB document` and give the size.

### User-facing consequences
~User confusion and uncertainty if it's safe to download.~

User does not know how large the epub file will be before downloading it.

### Errors and logs

…

### Steps to reproduce
Open any ePUB resource and try to download.

### Context

 * Kolibri version: 0.12.4b4 at http://35.236.125.21:8080
 * Operating system: Ubuntu 18.04
 * Browser: both Chrome and Firefox

…

**Comment by indirectlylit** [comment]
this will be fixed by 230ed541feabfcbe2e2eb252f2239ba13e9043e6 in #5540

**Comment by jonboiser** [comment]
Just checked on this right now, and it does show "epub document", but it does not show the file size.

**Comment by indirectlylit** [comment]
Yes, it was fixed after string freeze. We should make a new string for 0.13.0 with the file size

**Comment by nucleogenesis** [comment]
> Yes, it was fixed after string freeze. We should make a new string for 0.13.0 with the file size

Should we set this issue's milestone to 0.13.0?

**Comment by indirectlylit** [comment]
good call, thanks
