### ISSUE TITLE
Facility settings change for guest access not reflected on sign-in page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5547]
### Observed behavior
Changing the facility settings seems to have inconsistent results on the sign-in page: sometimes it does not reflect correctly until the cache is cleared several times, the UI language is changed, or another setting is checked/unchecked.

![facility-settings](https://user-images.githubusercontent.com/1457929/58334343-a652e280-7e3f-11e9-9d8b-8722155850cc.gif)

In the above recording, after the `Allow users to access content without signing in` option has been unchecked, the `Explore without account` link remains on the sign-in page even after several reloads with the cache cleared. It only disappears once another option is changed, and sign-in page reloaded. Furthermore, when subsequently checked again, to try to re-allow guest access, the link does not reappear after reloads until the UI language is changed.

### Expected behavior
Facility settings change should have immediate and consistent results.

### User-facing consequences
Unclear functionality and inability to configure the facility access according to specific needs.

### Errors and logs
Nothing overt in the console

[server.log](https://github.com/learningequality/kolibri/files/3217288/server.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/3217289/kolibri.log)

### Steps to reproduce
Try changing the facility settings for guest and simplified sign-in access, and observe the results on the user sign-in page.

### Context

 * Kolibri version: 0.12.4b3
 * Operating system: Ubuntu 16.04
 * Browser: Chrome & Firefox

**Comment by jonboiser** [comment]
I'm able to reproduce this with the  PEX, but not while running the `release-0.12.y` branch locally (using the `devserver` command).

I notice that on the PEX version, the reload is _a lot_ faster than with the local devserver. When running from the PEX, the refresh is almost instant, whereas on development mode, there is the usual blank screen, then first paint after maybe 0.5s.

**Comment by indirectlylit** [comment]
@jonboiser assigning this to you along with #5594

**Comment by rtibbles** [comment]
Fixed in #5601
