### ISSUE TITLE
'Select all' button disabled during the import from local drive

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5548]
### Observed behavior
Weird case of the <kbd>Select all</kbd> button being disabled when trying to import a channel from the local drive.

![Ubuntu16 04 (0 12 4-b3)  Running  - Oracle VM VirtualBox_046](https://user-images.githubusercontent.com/1457929/58339322-993af100-7e49-11e9-9f20-cfd80434673e.png)

### Expected behavior
Haven't seen the <kbd>Select all</kbd> button disabled unless *all* the content is already been imported on the device...? :thinking: 

### User-facing consequences
User being forced to select folders one by one.

### Errors and logs
Nothing in the browser console or network tab, import is ultimately successful.

DB of the channel in question (from the local drive): 
[27bb0abc24d44dd9896be50d47b2357e.zip](https://github.com/learningequality/kolibri/files/3217570/27bb0abc24d44dd9896be50d47b2357e.zip)

### Steps to reproduce
Not sure if you can try to simulate the import with just the above DB, the full `KOLIBRI_DATA` folder is too big to import here...

### Context
 * Kolibri version: 0.12.4b3
 * Operating system: Ubuntu 16.04
 * Browser FF & Chrome

**Comment by jonboiser** [comment]
This is actually a little unusual, since the "Select all" checkbox is disabled, but not checked. 

Normally, it would be both disabled and checked, meaning that all of the resources in the topic are already "Available" on the server, and cannot be re-imported.

**Comment by radinamatic** [comment]
> a little unusual

Hence my confusion... Is it something related to this particular version of the Living Values channel DB?

**Comment by jonboiser** [comment]
It could be specific to the Living Values channel (topic structure, how it's availability got annotated, something new in Studio, etc.), since I've never seen this before.

**Comment by jonboiser** [comment]
I'm also noticing that the Living Values channel doesn't show its thumbnail on the Channel List page, only on the Select Content Page.

**Comment by jonboiser** [comment]
The Select All is being disabled because of this function

https://github.com/learningequality/kolibri/blob/abecb96bbd738c08e5a9df0c1702ef54d2daa436/kolibri/plugins/device_management/assets/src/views/SelectContentPage/ContentTreeViewer.vue#L105-L120

Each of the items are being annotated as `available: false`, which is why this function is returning True for this channel. I keep forgetting the meaning of "available". In the context of a Local Import (From external drive), I thought "available" was supposed to mean "files are on the external drive".

The files are showing up, though, because they are annotated as "importable".

Should this function be looking at the `importable` field instead of the `available` field?

**Comment by indirectlylit** [comment]
this might also be affected by work that @rtibbles is doing here: https://github.com/learningequality/kolibri/pull/5490

@jonboiser would you mind reviewing his PR and seeing how it affects this behavior?

**Comment by jonboiser** [comment]
#5490 looks to be compatible with this (i.e. the `node.importable` field is implemented), assuming the fix is to change the predicated in `every` to check `!node.importable`

**Comment by radinamatic** [comment]
Just replicated this while testing the upgrade scenario from 0.10 to 0.12.4b6 on Ubuntu 16.04, with the Funza games channel (`gosim-bajih`):

![2019-06-04_0-06-36](https://user-images.githubusercontent.com/1457929/58835151-d713f280-865d-11e9-8741-f5e5eac284b4.png)

Steps to replicate:

1. Import one of the games from Studio
2. Export the game to local drive
3. Import 2 more games from Studio
4. Export those too onto the local drive (all three games will display unchecked for export - the game that was previously exported is not annotated as already present on the local drive)
5. Delete the Funza channel from Device > Channels
6. Try to import from the local drive: once the DB is imported, it will present as above, with the `Select all` checkbox empty and disabled.

**Comment by rtibbles** [comment]
Should be fixed in #5572

**Comment by radinamatic** [comment]
So the original issue is solved, yey! :+1: 

However, found a new one, filed as #5639.
