### ISSUE TITLE
TAB navigation with new modals in Firefox

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#555]
## Summary

Something is fishy with TAB navigation with new modals in Firefox: seems as if nothing can get focus except the `Close` button... :scream_cat:

In Chrome everything works OK.

## System information

Tested on Kolibri installer build 75 in Windows 7, and latest master.

 - Version: latest master & Win installer
 - Operating system: Windows
 - Browser: Firefox

## How to reproduce

1. Open Kolibri in Firefox
1. Try TAB navigating through modals (Login, User management...)

**Comment by indirectlylit** [comment]
Thanks - I'm able to reproduce this in FF47 using browserstack. (looks not to be an issue in FF48)
