### ISSUE TITLE
epub renderer does not work when devserver is run with hot reload

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5550]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/58345146-8b1aaf80-7e0c-11e9-9f42-dd7c2df486e4.png)

![image](https://user-images.githubusercontent.com/2367265/58345136-83f3a180-7e0c-11e9-9e6a-e0746a5f2f3c.png)

### Expected behavior

without hot reload

![image](https://user-images.githubusercontent.com/2367265/58345105-70483b00-7e0c-11e9-8395-b11db56a018a.png)

### User-facing consequences

In this case none, but from @rtibbles it sounds like there could possibly be user-facing issues in the future:

> My guess would be it is because of the content specific directional css stuff erroring when there are no css files being generated (as is the case for hot reload)
>
> I can imagine an edge case of this if a renderer had no associated css files

Otherwise, this is mainly a developer-hindrance. @bjester did you run into this?

### Errors and logs

```
Mediator.js:246 Uncaught (in promise) TypeError: Cannot read property 'endsWith' of undefined.
```

### Steps to reproduce

Run devserver with hot reload enabled and open an epub

### Context

0.12.3

**Comment by bjester** [comment]
@indirectlylit I did not run into this. I don't really use hot reload

**Comment by rtibbles** [comment]
Fixed by https://github.com/learningequality/kolibri-design-system/pull/225

**Comment by indirectlylit** [comment]
nice
