### ISSUE TITLE
non-standard styling in epub renderer

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5564]
### Observed behavior

**1 - icons are black with purple circles:**

Should be completely black or completely purple

![image](https://user-images.githubusercontent.com/2367265/58500803-c9c7a700-8137-11e9-837b-b2ee5ee5e49c.png)

**2 - Non-standard elevations and drop shadow usage.** [original reference](https://github.com/learningequality/kolibri/pull/5579#issuecomment-497120316)

Our drop shadows should be kept consistent with elevation. We have a set of [standard drop shadows](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/styles/materialDesignElevations.scss) that we're not using here.

It's also not clear to me why the header and footer elements have drop shadows or elevations at all.  This is not consistent with Material [elevation conventions](https://material.io/design/environment/elevation.html) or our other renderers. (cc @khangmach @jtamiace)

| current | flattened |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/58593545-0bcc1800-8220-11e9-8398-8943c2daffa0.png) | ![image](https://user-images.githubusercontent.com/2367265/58593332-76308880-821f-11e9-8d71-a4f3a3080991.png)  |

**3 - No rounded corners**

In general we avoid hard corners. Standard practice is to use `border-radius: $radius;` which is `4px`.

> ![image](https://user-images.githubusercontent.com/2367265/58594306-096abd80-8222-11e9-83b7-c970ae34ed8c.png)

### Expected behavior

Consistent UI with the rest of the app

### User-facing consequences

small UI inconsistencies

### Steps to reproduce

view an epub

### Context

0.12.3

**Comment by khangmach** [comment]
Nice. 
- Let's flatten the epub shadow as you suggested. 
- Add the round corners back on the renderer
- Remove the purple from the left/right arrows

**Comment by jtamiace** [comment]
Another non-standard styling thing: I think it would be good to either remove this current animation entirely, or change it to a sliding motion, from the left side for table of contents, from the right side for the filters and search panels.

Hopefully the gif captures it well enough, but it's zooming in and out of the center of the panel, which looks strange and unnatural for a side panel

![epub animation](https://user-images.githubusercontent.com/6668144/58649407-eb07cf00-82c0-11e9-8877-ed96242b6fc6.gif)

**Comment by khangmach** [comment]
woah they almost look like two separate animations. We could just apply the hamburger drawer animation to these two sides

**Comment by jonboiser** [comment]
This was fixed in #5730. The internal panels of the EPUB renderer were made flatter, the side panel animations were removed, and various box shadows were removed.
