### ISSUE TITLE
EPUB: components and loading error show above floating app top bar

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5565]
### Observed behavior

observed by @bjester:

> ![image](https://user-images.githubusercontent.com/2367265/58509557-ac043d00-814b-11e9-8ce1-0e2b4dbf29ec.png)

> 
![image](https://user-images.githubusercontent.com/2367265/58510886-84fb3a80-814e-11e9-8e8e-f08ab5ced4ea.png)

### Expected behavior

Z-indexes should be respected

### User-facing consequences

slightly broken-looking behavior

### Steps to reproduce

* make window small enough that the app bar will scroll offscreen
* scroll down and then back up again

### Context

Linux, Chrome, 0.12.4-beta4

**Comment by bjester** [comment]
@indirectlylit I think you need to decrease the page height in order to get it to happen, beyond the breakpoint that causes the app top bar to show / hide on scroll. I think that for sure caused it but I don't remember exactly.

**Comment by indirectlylit** [comment]
thanks that's right - it only occurs when the top bar is "floating". will update the issue
