### ISSUE TITLE
Learn page - coach-content icons and annotations are shown to learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5567]
### Observed behavior

reported by @jonboiser - learners see coach annotations even though they have no access to that content:

| card | user |
|--|--|
|  ![image](https://user-images.githubusercontent.com/2367265/58511486-be807580-814f-11e9-9cbf-761e220568ad.png) |  ![image](https://user-images.githubusercontent.com/2367265/58511510-cdffbe80-814f-11e9-9bc0-eccbe7644007.png) |

### Expected behavior

Since the coach content is not accessible to learners, these annotations should be hidden completely

### User-facing consequences

meaningless/confusing extra information shown to learners

### Steps to reproduce

* import a channel with a combination of coach and learner content, such as the epub testing channel (`9096a64765c64af18519a9d9509e64a9`)
* view as learner

### Context

0.12.3

**Comment by rtibbles** [comment]
Ah, this is probably because of the simplifications I made, where coach content info is always sent to the frontend, so the indicator just needs to check the user role to see if it should display.

**Comment by jonboiser** [comment]
This is fixed in #5571. The coach-content icon (a blue person reading a book) is only shown on cards if the `session` indicates that the viewer is authenticated and not a learner (meaning they are at least a coach or higher).
