### ISSUE TITLE
epub: broken layout in some books

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5568]
### Observed behavior

columns are clipped:

![image](https://user-images.githubusercontent.com/2367265/58512085-0f449e00-8151-11e9-8ace-60708519f48a.png)

### Expected behavior

columns should be fully visible

### User-facing consequences

very hard to read book

### Steps to reproduce

see http://kolibribeta.learningequality.org/en/learn/#/topics/c/bec24a1298a14bb18ecf4851ad2da0f3

### Context

0.12.4-beta4

**Comment by rtibbles** [comment]
Context says 0.12.3, but this appears to be 0.12.4 beta?

**Comment by indirectlylit** [comment]
thanks - updated to 0.12.4-beta4

**Comment by bjester** [comment]
Do we know if this was a regression? Not that that will affect my self-assignment, but just wondering if any of the recent changes I did helped or hurt the rendering of this book.

**Comment by indirectlylit** [comment]
I don't know, sorry

**Comment by bjester** [comment]
So this particular EPUB has some `margin`s in its styles, which are causing the rendering issues. We'll probably continue to get issues like this, as EPUB's contain HTML and CSS, so handling rendering of all possibilities will be difficult if not impossible.

**Comment by indirectlylit** [comment]
did you identify if this was always broken or a regression?

**Comment by bjester** [comment]
@indirectlylit I didn't check but based on the issue, I doubt it was a regression.
