### ISSUE TITLE
creative commons licenses are written from perspective of content creator

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5569]
### Observed behavior

Noticed by @jamalex, our CC licenses are currently displayed to learners and coaches but written from the perspective of the content creator, e.g.:

> **Attribution-NonCommercial-ShareAlike**
> 
> This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.

This should also be taken into account when we address #2371

### Expected behavior

perhaps something like:

> **Attribution-NonCommercial-ShareAlike**
> 
> This license lets you remix, tweak, and build upon this work non-commercially, as long as you credit the copyright holder and license your new creations under identical terms.

### User-facing consequences

The terms of the license don't really make sense in this context as currently written

### Steps to reproduce

View any KA content

### Context

0.12.4

**Comment by jonboiser** [comment]
The current localizations of the CC licenses seem to be copied from the website and only cover a subset the languages.

To fix this issue, do we need to change the English version to the content-consumer-focused version, and then have it localized to all supported languages?

**Comment by indirectlylit** [comment]
> The current localizations of the CC licenses seem to be copied from the website and only cover a subset the languages.

Correct. This was done as a stop-gap solution post-string-freeze in #5205

> To fix this issue, do we need to change the English version to the content-consumer-focused version, and then have it localized to all supported languages?

Yes, I think so - that's basically what #2371 is about.

Once we've enumerated all the English strings, we can work in a google doc to make sure we have both a content creator's perspective and the content consumer's perspective. Then we can get all both versions translated in crowdin for all languages and all licenses.
