### ISSUE TITLE
Rephrase 'no drives found' message to be less confusing

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5575]
### Observed behavior
The current message is `No drives that can be written to are connected to the server` which is a bit confusing to me, If I speed-read to it.

@indirectlylit suggested to replace it with `Could not find a connected drive`

### Expected behavior
Rewording the message into a less confusing.

### Errors and logs

![Simulator Screen Shot - iPad Pro (12 9-inch) - 2019-05-29 at 09 48 40](https://user-images.githubusercontent.com/8663934/58526235-e2e85a80-8200-11e9-90ac-03136bd3214f.png)

### Steps to reproduce
* Export a channel content with no drives available
* The message will display.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4-beta4
 * Operating system: iOS
 * Browser: Safari 11.0.3

**Comment by jonboiser** [comment]
I originally added that "can be written to" detail, since it seemed that you could have peripheral drives connected to the server, but would not be recognized as exportable for whatever reason. In other words, at the time, "connected" did not always mean "exportable" or "writable".

**Comment by indirectlylit** [comment]
perhaps leave it more ambiguous then? e.g.

> Could not find a valid drive


see also https://github.com/learningequality/clearinghouse/issues/389

**Comment by jonboiser** [comment]
I'm not sure if this has ever been confusing, but I wonder if people will connect a USB drive to a client laptop (as opposed to a server laptop or tower) or something and expect the import dialogue to recognize their USB drive. (Hence the added detailed about it being "connected to the server")

**Comment by indirectlylit** [comment]
yes, that's a good point. Okay well... maybe keep it much closer to the original, but try to tighten up the language?

> Could not find a writable drive connected to the server
