### ISSUE TITLE
Multiple admin users can't import simultaneously

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5576]
### Observed behavior
I'm just worried about this situation if someone attempt to import and another admin user are preparing or searching to import and found out they cannot import because someone uses already.

Maybe allow the admin users can import simultaneously.

![impot race](https://user-images.githubusercontent.com/38421180/58528229-5a6db800-8208-11e9-9d90-8edad593bf75.gif)

### Context
Tell us about your environment, including:
 * Kolibri version : 0.12.4b4
 * Operating system: Windows 10
 * Browser: Firefox 67.0(32 bit), IE11 and Microsoft Edge

**Comment by radinamatic** [comment]
Warning not to do other system maintenance operations while the import is in progress, and to do it when no learner is using the platform, is already included in the docs.

![2019-06-03_14-09-07](https://user-images.githubusercontent.com/1457929/58798098-6bed0080-860a-11e9-92df-6a303ea62329.png)

**Comment by indirectlylit** [comment]
this is being addressed by ongoing work in 0.13.0
