### ISSUE TITLE
in-progress quiz scores are shown to coaches

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5585]
### Observed behavior

Scores are shown before the quiz has been submitted, giving an inaccurate portrayal of a learner's performance:

![image](https://user-images.githubusercontent.com/2367265/58607116-2a97d200-8253-11e9-971e-51347816081d.png)

### Expected behavior

Scores should not be shown until the learner is finished with it. The 'average score' reported at the top should only include completed quizzes.

### User-facing consequences

Confusing view of quiz results.

### Context

0.12.3

**Comment by indirectlylit** [comment]
Shifting milestone for follow-up.

See extensive thread here: https://learningequality.slack.com/archives/C0LKG14NL/p1559188069004200

High level goal: 
![image](https://user-images.githubusercontent.com/2367265/58672215-a8fb7f00-82fa-11e9-98c1-fef8869b5e8d.png)

**Comment by nucleogenesis** [comment]
This issue was completed with https://github.com/learningequality/kolibri/pull/5595 and it's subsequent bugfixes
