### ISSUE TITLE
Edited value of the class does not show.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5590]
### Observed behavior
1. When a class is renamed, the new value is not shown after the <kbd>Save</kbd> button is clicked and the `Rename class` modal dialog closes.
2. Also noticed that there's no **Super admin edits a class name.** Gherkin `.feature` file to test this yet.

### Expected behavior
The new class name must show after the <kbd>Save</kbd> button is clicked and the `Rename class` modal dialog closes.

### User-facing consequences
User gets confused when the new value is not displayed and may repeat the edit process again.

### Errors and logs
N/A

### Steps to reproduce

1. Login as super admin.
1. Go to Facility -> Classes.
1. Click on an existing class (or create a new class then click on that).
1. At the `Edit Class` page, click on the <kbd>Edit</kbd> link next to the class name.
1. At the `Rename class` modal dialog, type-in the new value for the class name then click <kbd>Save</kbd>.
1. Notice that the class name did not reflect the new value.

### Context
 * Kolibri version: 0.12.4-beta4
 * Operating system: Client=iPad2 on iOS9.3; Server=Ubuntu-18.04
 * Browser: Safari 9.3 on iPad2

**Comment by jonboiser** [comment]
This should be fixed by #5544
