### ISSUE TITLE
File exist error after the upgrade from 0.10 to 0.12.4-beta6

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5597]
### Observed behavior
I can't start the Kolibri server in Windows 7 it has an file exist error after I upgrade from `0.10` to `0.12.4-beta6`

### Expected behavior
I should be able to start the Kolibri server after the upgrade.

### User-facing consequences
The user might not able to start the Kolibri server after the upgrade.

### Errors and logs
![Screen Shot 2019-05-31 at 10 52 33 AM](https://user-images.githubusercontent.com/8663934/58679302-80749300-8395-11e9-904d-1dfe01e1db76.png)

### Work-around 
Manually delete the kolibri.log file path and restart the kolibri server.

### Steps to reproduce
* Install the Kolibri 0.10 on WIndows 7
* After the installation, upgrate it using the 0.12.4-beta6 Windows installer
* Manually start the Kolibri server using the command prompt.
* The file exist error show up at the command prompt.

### Context

Tell us about your environment, including:
 * Kolibri version:  0.12.4-beta6
 * Operating system: Windows 7
 * Browser: N/A

**Comment by mrpau-julius** [comment]
Same error on windows 10, cannot start the Kolibri server after the upgrade.
![sameErrorwin10](https://user-images.githubusercontent.com/38421180/58682037-97b97d80-83a1-11e9-9662-2a350a7b8aef.png)

**Comment by radinamatic** [comment]
Confirmed that this is the issue only on Windows. Upgrading to 0.12.4b6, either on Ubuntu where 0.10 was running as PEX, or when it was installed from DEB, creates no issues regarding the path of the log files.

**Comment by lyw07** [comment]
thank you for testing! I will have a fix soon

**Comment by indirectlylit** [comment]
nicely done!

**Comment by rtibbles** [comment]
This should be fixed in #5609 but will wait for confirmation before closing.

**Comment by lyw07** [comment]
confirmed by @radinamatic that this has been fixed.
