### ISSUE TITLE
CK12 HTML5 app 'next' button styling is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5619]
(originally reported by @mrpau-richard in https://github.com/learningequality/sushi-chef-ck12/issues/8 but can't transfer back to kolibri for some reason)

### Observed behavior

Exercise next button over size.

### Expected behavior
The button size should be in standard.

### Errors and logs
![Screen Shot 2019-06-04 at 5 29 15 PM](https://user-images.githubusercontent.com/8663934/58868325-a9c35500-86ee-11e9-9692-a40833b7e021.png)

### Steps to reproduce
* Import this `gizaf-karaz` from the studio
* Find the exercise  `The fying birds` at the Math contents and import it
* Engage to that exercise 

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.4-beta6
 * Operating system: Windows
 * Browser: Firefox 67.0

…

**Comment by indirectlylit** [comment]
see thread here - https://learningequality.slack.com/archives/CB37UM23A/p1559667319000400

links: 

* beta server: http://kolibribeta.learningequality.org/en/learn/#/topics/c/ccff6ad0bf0b56a6b6e5fa53327d18e0
* demo server: https://kolibridemo.learningequality.org/learn/#/topics/c/ccff6ad0bf0b56a6b6e5fa53327d18e0 

@kollivier:

> Okay, so I see two primary differences. One is that the  script loading order is different, although the new version is closer to the original. The second is that 0.12.4 beta 'cleans up' some of the HTML and makes it compliant. One weird thing that gets changed is that the original html has `<input>(several divs)</input>` and the cleaned up version has the input tag be self-closing. This could end up changing CSS paths if they're expecting a certain DOM structure.
> 
> * kolibribeta version: https://gist.github.com/kollivier/ac1c687b95ef82f99b4276ab3b7212b1
> * kolibridemo version: https://gist.github.com/kollivier/a011843ce976ee7b483aaebce0a96e82


 @rtibbles:


> I think this might be the issue:
> https://github.com/learningequality/kolibri/blob/release-v0.12.y/kolibri/core/content/views.py#L155
> 
> This may be forcing the undesirable self-closing inputs

**Comment by rtibbles** [comment]
Having investigated further, and looking at the diffs in what Chrome actually renders from the new endpoint, compared to the previous endpoint, the HTML end tags are identical (i.e. the backend HTML parser is just pre-emptively doing what Chrome would be doing later, so I don't see this as an issue).

I also just tried copy pasting the rendered DOM elements from a broken version into a page that was working, and the issue did not replicate.

I think this is a subtle issue to do with the fact that the DOM is fully rendered when the Javascript is loaded, and hence the CK12 code is measuring something wrong and making the height of the window too big or somesuch.

**Comment by nucleogenesis** [comment]
I've done a little bit of digging into this issue and the several other PLIX exercises have the same problem. http://kolibribeta.learningequality.org/en/learn/#/search?searchTerm=plix

Is it possible (or reasonable/reliable) to modify the `/build/themes/plix/css/plix.css` file during cheffing of all PLIX resources to remove the `height: 100%` defined on the several button classes that are ultimately rendering the super tall buttons? 

On another note, I also did a bit of digging into the code in the zip file and the JS is obfuscated, making it hard to really see what is going on and when/how things are loaded from the fake AJAX process that eventually loads the part of the DOM that has the buttons causing the issues.

cc @rtibbles

**Comment by kollivier** [comment]
@nucleogenesis It is something we can try, but CK-12 chef is really old and is currently in a broken state, so we need to get that fixed up first before we can test this. Also, it's possible that changes made to fix the 0.12 rendering could break rendering under previous versions, so I'd like to avoid having to patch specific content to fix it in 0.12 if possible.

**Comment by indirectlylit** [comment]
any chance this has been addressed by recent changes to hashi?

**Comment by kollivier** [comment]
**Update!**

Looks like this is caused by the doctype stripping bug. The content does have <!doctype html> specified, and with the doctype restored, the content renders as expected:

![image](https://user-images.githubusercontent.com/29585/76786926-4bdf9580-6775-11ea-880c-9689ed9ad24b.png)

**Comment by indirectlylit** [comment]
awesome! glad to hear.

Once https://github.com/learningequality/kolibri/pull/6646 makes its way into the mainline we can close this

**Comment by cpauya** [comment]
This also exists on Android 7.1.2 as of BuildKite build 144 -> https://buildkite.com/learningequality/kolibri-android-installer/builds/144#36249ca3-3fd8-450c-bd20-dc3efc373435

Context: 

* Kolibri version: 0.13.3a0.dev0
* Channel: Radina test channel - The Flying Birds (PLIX)
* Operating system: Android 7.1.2 (based on BlueStacks)
* Browser: n/a

![2020-05-07-thu--android testing - plix issue 1](https://user-images.githubusercontent.com/175580/81278069-c6e36f00-9087-11ea-9d01-eb18e7815107.gif)

**Comment by indirectlylit** [comment]
#6646 was merged in March, but sounds like this issue has not been addressed

**Comment by kollivier** [comment]
Did the ProFuturo PRs ever make it into 0.13.x? I thought we only merged them into 0.14? Or has 0.14 testing reproduced this issue as well?

**Comment by indirectlylit** [comment]
ah thanks - for some reason I thought this was reproduced on 0.14

@cpauya would you mind testing in the latest 0.14 beta and re-opening if it still exists there?

**Comment by cpauya** [comment]
This is fixed in [kolibri v0.14.0-beta5](https://buildkite.com/learningequality/kolibri-python-package/builds/1254)! 
Channel: Kolibri QA Channel - Teddy Bear Box (PLIX)
Operating system: Android 7.1.2 (based on BlueStacks)

Yey! 😺
![2020-06-25-thu--v0 14 0-b5 testing--1-- recheck ok](https://user-images.githubusercontent.com/175580/85700281-cc1b7c80-b70e-11ea-85ab-e239f5d563ef.gif)

**Comment by mrpau-richard** [comment]
I also tested this on Windows 7 and I confirmed the issue fixed on beta5
![c1](https://user-images.githubusercontent.com/8663934/85795369-b9369580-b76a-11ea-818a-ddde1e7dfe14.PNG)
