### ISSUE TITLE
On Lesson Summary Page, Channel titles can be outside of draggable cards in IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5622]
### Observed behavior
Channel title overlap on it's container when dragging a resources on lesson.

### Expected behavior
The channel tittle must display inside on it's container.

### User-facing consequences

…

### Errors and logs
This is on IE11 that's overlap the channel tittle
![Screen Shot 2019-06-05 at 11 22 44 AM](https://user-images.githubusercontent.com/8663934/58929107-09217380-8788-11e9-8a33-ba60cf19132b.png)

This is on Firefox 67.0 that's display the channel tittle inside on it's container
![Screen Shot 2019-06-05 at 11 24 18 AM](https://user-images.githubusercontent.com/8663934/58929174-61f10c00-8788-11e9-89bd-7943e8cb05d0.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4b6
 * Operating system: Windows 7
 * Browser: IE11

**Comment by pcenov** [comment]
@radinamatic this one is fixed in 0.15.1:
![2022-03-24_16-47-28](https://user-images.githubusercontent.com/79847249/159942911-f60680a6-0025-4a24-b849-77e10c191e47.png)

**Comment by rtibbles** [comment]
Closing, as resolved!
