### ISSUE TITLE
Investigate if we should switch from pytz to dateutil

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#5628]
We currently use the python pytz library for all of our timezone needs. However, this article suggests that something may be rotten in the state of pytz: https://typesandtimes.net/2019/05/royal-astronomical-society-python and that dateutil might be a better replacement.

I don't know if this is the case, but I think it is worth investigating.

**Comment by indirectlylit** [comment]
it's actually already a dependency

https://github.com/learningequality/kolibri/blob/96648d239da3b60fc90352a2e9d01d96d55a4e7d/requirements/base.txt#L28

(I don't see it in use)

**Comment by rtibbles** [comment]
Oh right... curious.

**Comment by rtibbles** [comment]
Looks like we added it because Android doesn't come with it, for use alongside iceqube https://github.com/learningequality/kolibri/pull/1610 - but not clear that we need it for that even.

**Comment by jonboiser** [comment]
Added to the list of [backburner issues](https://github.com/learningequality/kolibri/discussions/7806)
