### ISSUE TITLE
Page titles not rendered properly in Telugu

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5634]
### Observed behavior
Browser page title in Telugu is not properly rendered, all other languages display correctly.

![Ub1604-0 12 4b6  Running  - Oracle VM VirtualBox_081](https://user-images.githubusercontent.com/1457929/59075472-f8c8e000-88d0-11e9-948b-3f26c871139c.png)

### Expected behavior
Legible page title in Telugu.

### User-facing consequences
User uncertainlty about position.

### Errors and logs
Nothing visible in network tab or console.

### Steps to reproduce
Change language to Telugu.

### Context
 * Kolibri version: 0.12.4.b6
 * Operating system: Ubuntu 16.04
 * Browser: Firefox & Chrome

**Comment by rtibbles** [comment]
My guess is that this may be outside of our control - we load fonts for use inside the web page, but we have no control over the title. It would be resolved by the user doing this: https://askubuntu.com/questions/971757/install-telugu-language-pack/971759#971759

**Comment by radinamatic** [comment]
Right, I'll recheck on Windows, that should confirm that it's Ubuntu-specific.

**Comment by radinamatic** [comment]
Confirmed that issue is not extant on Windows:

![Win10 (0 11 1 signed)  Running  - Oracle VM VirtualBox_084](https://user-images.githubusercontent.com/1457929/59110575-b7234e00-893f-11e9-890d-57a410ca23dd.png)

On the other hand, installing Telugu language pack on Ubuntu fixes the issue on Firefox, while in Chrome there's this curious situation where the page title is displayed correctly in the browser title bar, but not in the tab title, even after all the recommended fonts from the above link are installed...  :woman_shrugging: 

![Ubuntu16 04 (0 10 3)  Running  - Oracle VM VirtualBox_088](https://user-images.githubusercontent.com/1457929/59111311-0f0e8480-8941-11e9-96f1-780b2208ff0d.png)

**Comment by radinamatic** [comment]
Confirmed that it's not something that we can fix on our side, closing!
(I may add a note in the docs)
