### ISSUE TITLE
Preview button for exercises in the lessons does not work in the Difficult questions subtab

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5636]
### Observed behavior
<kbd>Preview</kbd> button for exercises in the lessons does not work when pressed from the `Difficult questions` subtab, but works properly when pressed from the `Report` subtab.

![preview-lesson-diffque](https://user-images.githubusercontent.com/1457929/59112180-c9eb5200-8942-11e9-9c0c-8b88bdfe1322.gif)

### Expected behavior
Button must be functional and open the exercise preview, offer feedback why there's no preview on button press, or at minimum be displayed as disabled...?

### User-facing consequences
Nothing happening upon pressing a button equals frustrated users

### Errors and logs
…

### Steps to reproduce
Go to `Coach > Reports > Lessons > '<lesson>' > Difficult questions` and press the <kbd>Preview</kbd> button

### Context
 * Kolibri version: 0.12.4b7 upgraded from 0.10.3
 * Operating system: Ubuntu 16.04
 * Browser: FF & Chrome

**Comment by rtibbles** [comment]
Fixed in #5640
