### ISSUE TITLE
sentry issue on ubuntu 14.04

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5646]
### Observed behavior

Observed:

![image](https://user-images.githubusercontent.com/2367265/59227959-97409400-8ba4-11e9-96f7-49c9c674624c.png)

See also:

* https://learningequality.slack.com/archives/CB37UM23A/p1560165318063600
* https://github.com/learningequality/kolibri/issues/4775
* https://github.com/learningequality/kolibri/pull/5346
* https://github.com/learningequality/kolibri-installer-debian/pull/67

### Expected behavior

Installs the same as in 0.12.3.

To-do:

* [x] @indirectlylit and @jredrejo to remove tornado.py in the debian package: https://github.com/learningequality/kolibri-installer-debian/blob/master/debian/rules#L35
* [ ] ~@indirectlylit to try downgrading sentry~ choosing not to downgrade sentry unless absolutely necessary to avoid additional testing

### User-facing consequences

users cannot upgrade

### Steps to reproduce

Install debian package

### Context

ubuntu 14.04

**Comment by indirectlylit** [comment]
cc @mrpau-dev @radinamatic

**Comment by indirectlylit** [comment]
14.04 is not currently part of our test suite, but we have users using it, so perhaps it should be?

**Comment by radinamatic** [comment]
I understand that this is on a case basis, but do we have a plan/strategy until when we are willing to support the OSes that are EOL?

**Comment by benjaoming** [comment]
> 14.04 is not currently part of our test suite, but we have users using it, so perhaps it should be?

Nah, I don't think so.. there should be advantages of dropping support of something? :) But detecting such failure of compiling into Python bytecode is interesting. Added tests for that above.

**Comment by benjaoming** [comment]
We also continue to slightly support 14.04 by supporting Python 3.4.

**Comment by indirectlylit** [comment]
In practice, we have a large number users currently on 14.04 so our dropped support was preemptive. We'll need to keep testing it until we are sure that they are mostly migrated away, or we'll end up simply paying the price later.

**Comment by benjaoming** [comment]
> In practice, we have a large number users currently on 14.04 so our dropped support was preemptive. 

Supporting people using an EOL operating system.. let's talk about this Monday next week :)
