### ISSUE TITLE
Invisible answer on the exercise

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5648]
### Observed behavior
Answer on the exercise is showing invisible

### Expected behavior
The answer of the user must visible to them

### User-facing consequences
Can't see the user answer because it's invisible

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/59243144-184d6900-8c41-11e9-9ff8-3890487b1236.gif)

### Steps to reproduce
* Import the exercises on this channel `nakav-mafak`
* Engage to it's exercises
* Observe your answer is not showing in the box.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4b7
 * Operating system: Windows 7
 * Browser: Firefox 67.0.1, Chrome 75.0

**Comment by indirectlylit** [comment]
should be fixed by https://github.com/learningequality/kolibri/pull/5644
