### ISSUE TITLE
Some channel contents are not showing on the guest user

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5649]
### Observed behavior
Some channel contents are not showing on the guest user.

### Expected behavior
Channel contents must show the same on guest and not guest users.

### User-facing consequences
Some contents might no accessible to the guest user.

### Errors and logs
On the guest user there are only 4 contents on CK-12 testing channel
![Screen Shot 2019-06-11 at 3 18 25 PM](https://user-images.githubusercontent.com/8663934/59252169-0cbc6b00-8c5e-11e9-81a4-64b590c9637c.png)

On Logged in user there are 5 contents on CK-12 testing channel
![Screen Shot 2019-06-11 at 3 19 01 PM](https://user-images.githubusercontent.com/8663934/59252312-6c1a7b00-8c5e-11e9-9297-3ff38737e715.png)

### Steps to reproduce
* Import this CK-12 channel nakav-mafak
* Browse this channel on guest and not guest users.
* Observe the channel contents not showing the same on guest.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4b7
 * Operating system: Windows 7
 * Browser: Firefox 67.0.1

**Comment by radinamatic** [comment]
@mrpau-richard The difference you observe is because all the resources in the `ePUB` topic are annotated as **coach resources**, and that's the reason  you do not see them as guest.

**Comment by mrpau-richard** [comment]
Okay, @radinamatic closing this.
