### ISSUE TITLE
Zoom-out issue with PhET content on iPad2

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5656]
### Observed behavior
On iPad2, when trying to zoom-out of a PhET simulation, the whole content is still shown in their zoomed sizes instead of the showing the whole simulation.  See attached `.gif`.

### Expected behavior
The whole PhET contents should be shown when zooming-out under iPad2. 

### User-facing consequences
User cannot continue with the simulation.  The only recourse is to navigate out and back to the page.

### Errors and logs
N/A

### Steps to reproduce
1. Under 0.12.4-beta8, import the **CK-12 Testing** channel using the `nakav-mafak` token.
1. Open the `CK-12 Testing > HTML5 > PhET > Bending Light` content in the iPad2 simulator. 

### Context
Kolibri version: 0.12.4-beta8
Operating system: iPad2 on iOS 9.3 Simulator
Browser: Safari 9.3
Channel: CK-12 Testing

![kolibri-0 12 4-beta8--ipad2 zoom issue with PhET content](https://user-images.githubusercontent.com/175580/59333417-da2c7400-8d2a-11e9-9996-0416e370cc50.gif)

**Comment by cpauya** [comment]
This exists on v0.12.3 too.

**Comment by pcenov** [comment]
@radinamatic this issue is no longer extant in Kolibri 0.15.1
Tested on iPad4 on iOS 14.4 Simulator
Browser: Safari 14.4
![2022-03-10_16-32-51](https://user-images.githubusercontent.com/79847249/157690788-c23d2b54-c5eb-480b-b124-3620889e1816.png)

**Comment by rtibbles** [comment]
Closing as fixed.
