### ISSUE TITLE
unable to generate signed APK on buildkite

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5661]
### Observed behavior

For 0.12.4 release, we are not able to generate a signed APK because of this step: https://github.com/learningequality/kolibri/blob/v0.12.4/.buildkite/pipeline.yml#L50 (added after 0.12.3 release, so we didn't have this issue before)

The details of the error: https://buildkite.com/learningequality/kolibri/builds/11235#ac94c825-7cf2-49b8-b9da-396cba9422c9

We've uploaded the artifacts to github release page in the previous upload step (https://github.com/learningequality/kolibri/blob/v0.12.4/.buildkite/pipeline.yml#L28), so the attempt to upload the artifacts again to github release page got rejected. 

The solution is to remove the second upload step in the pipeline.yml file.

### Expected behavior

we should be able to successfully generate a signed APK for releases

### User-facing consequences

users can't have a signed APK to run

### Errors and logs

https://buildkite.com/learningequality/kolibri/builds/11235#ac94c825-7cf2-49b8-b9da-396cba9422c9
```
DEBUG: {'headers': {'X-Frame-Options': 'deny', 'X-Oauth-Scopes': 'public_repo, repo:status, repo_deployment', 'X-Xss-Protection': '1; mode=block', 'Content-Length': '211', 'Cache-Control': 'no-cache', 'Strict-Transport-Security': 'max-age=31557600', 'Content-Type': 'application/json; charset=utf-8', 'X-Accepted-Oauth-Scopes': 'repo', 'X-Content-Type-Options': 'nosniff', 'Date': 'Wed, 12 Jun 2019 20:40:55 GMT', 'X-Github-Media-Type': 'github.v3; param=full; format=json', 'Content-Security-Policy': "default-src 'none'", 'X-GitHub-Request-Id': 'C780:1866:45DE00:4D943A:5D016356'}, 'url': 'https://uploads.github.com/repos/learningequality/kolibri/releases/17944926/assets?name=kolibri_0.12.4-0ubuntu1_all.deb', 'connection': <requests.adapters.HTTPAdapter object at 0x7fc03a0467f0>, '_content': b'{"message":"Validation Failed","request_id":"C780:1866:45DE00:4D943A:5D016356","documentation_url":"https://developer.github.com/v3","errors":[{"resource":"ReleaseAsset","code":"already_exists","field":"name"}]}', 'status_code': 422, 'reason': 'Unprocessable Entity', '_next': None, 'encoding': 'utf-8', 'request': <PreparedRequest [POST]>, 'raw': <urllib3.response.HTTPResponse object at 0x7fc03978a390>, 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(0, 4, 471614), '_content_consumed': True, 'history': []}

--
  | Traceback (most recent call last):
  | File ".buildkite/upload_artifacts.py", line 265, in <module>
  | main()
  | File ".buildkite/upload_artifacts.py", line 261, in main
  | upload_artifacts()
  | File ".buildkite/upload_artifacts.py", line 245, in upload_artifacts
  | asset=open(artifact["file_location"], "rb"),
  | File "/var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/env/lib/python3.4/site-packages/github3/decorators.py", line 30, in auth_wrapper
  | return func(self, *args, **kwargs)
  | File "/var/lib/buildkite-agent/builds/vader-1/learningequality/kolibri/env/lib/python3.4/site-packages/github3/repos/release.py", line 279, in upload_asset
  | raise error_for(r)
  | github3.exceptions.UnprocessableEntity: 422 Validation Failed
```

### Steps to reproduce

…

### Context

kolibri version: 0.12.4

**Comment by lyw07** [comment]
@rtibbles @radinamatic I was removing the step of uploading the artifacts again after signing windows installer, but I saw [this issue](https://github.com/learningequality/kolibri-installer-windows/issues/84), which mentioned that we would like to have the signed windows installer on the github release page. 

If that's the case, then I feel that we shouldn't go with the way of removing the duplicated step of uploading artifacts again but deleting the artifacts on the github release page first and then uploading them again.

If we remove the step of uploading the artifacts again, then the signed windows installer would only be found in the buildkite build step, under the `Artifact` section. 

Could you confirm whether we want to have the signed windows installer on github release page or not? Thank you so much! :)

**Comment by lyw07** [comment]
confirmed that this has been fixed with the 0.12.5 release

**Comment by indirectlylit** [comment]
milestone should be 0.12.5, correct?

**Comment by lyw07** [comment]
yes it’s 0.12.5
