### ISSUE TITLE
RTL layout and alignment issues related to exercise renderer 

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5662]
### Observed behavior

| LTR | RTL |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/59450323-f7b71780-8dd6-11e9-9743-28107f19d70b.png) | ![image](https://user-images.githubusercontent.com/2367265/59450324-fa197180-8dd6-11e9-9d1c-9e8d79b990d8.png) |

### Expected behavior

RTL alignment should be the correct inverse of LTR:

* the title should be right-aligned with the exercise icon on the right and the progress icon on the left. (the English title should be a locally LTR inline block within an outer RTL wrapper)
* ~the 'use a hint' link should be left-aligned~ migrated to https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/193

### User-facing consequences

subpar formatting for RTL users

### Steps to reproduce

https://kolibridemo.learningequality.org/en/learn/#/topics/c/7c9e658ea8de53ceaac9ea9f4fb63c6d

switch to arabic or another RTL language

### Context

0.12.4

**Comment by jonboiser** [comment]
Fixing the alignment of the "Use a hint" button would need to be done in the perseus-renderer-plugin.

**Comment by indirectlylit** [comment]
would you like that I split that component into a second issue under that repo?

**Comment by jonboiser** [comment]
> would you like that I split that component into a second issue under that repo?

Yup, let's do that.

**Comment by indirectlylit** [comment]
new issue for Perseus created here: https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/193
