### ISSUE TITLE
Used to work prior to 0.12.4: kolibri systemd service fails on Internet-in-a-Box

### ISSUE THREAD

**Issue by holta** [learningequality/kolibri#5664]
Whereas pip install of 0.12.x used to work, this no longer works with 0.12.4

The key error would seem to be:
```
IOError: [Errno 2] No such file or directory: '/home/kolibri/SQLITE_MAX_VARIABLE_NUMBER.cache'
```

_Plz see the bug report at https://github.com/iiab/iiab/issues/1675#issuecomment-501853558_

Noting that Kolibri runs out of virtual environment `/usr/local/kolibri/bin/kolibri` not `/home/kolibri` on Internet-in-a-Box, as is reconfirmed by:

```
root@box:~# /usr/local/kolibri/bin/kolibri --version
0.12.4
```

**Comment by lyw07** [comment]
I assume the directory `/home/kolibri` doesn't exist?

**Comment by holta** [comment]
> I assume the directory `/home/kolibri` doesn't exist?

Correct.

/home/kolibri does not exist and never has existed in past Kolibri installs on Internet-in-a-Box, over the past year anyway.

**Comment by rtibbles** [comment]
We can fix this by upgrading morango to 0.4.6 for 0.12.5

**Comment by lyw07** [comment]
@rtibbles I notice that we put the file to the home directory of the user: https://github.com/learningequality/morango/blob/master/morango/constants/file.py#L4

We can change the location of the file to KOLIBRI_HOME directory in morango 0.4.6 to prevent this issue, but are there any concerns about this? Is there a specific reason that we put the file in home directory of the user?

**Comment by rtibbles** [comment]
Note that 0.4.6 has been released pre-emptively, but the change is here in PR: https://github.com/learningequality/morango/pull/73

**Comment by rtibbles** [comment]
(it removes the need to write it to disk at all)

**Comment by lyw07** [comment]
ah thank you for the link! I didn't see the PR previously

**Comment by lyw07** [comment]
also I think a temporary workaround to make kolibri start successfully before we release 0.12.5 is to create the `/home/kolibri` so that the file can be written there.

**Comment by holta** [comment]
> also I think a temporary workaround to make kolibri start successfully before we release 0.12.5 is to create the `/home/kolibri` so that the file can be written there.

That does not work.  Unfortunately.

If other possible workarounds arise, please LMK, as this issue is affecting almost every IIAB install :-/

**Comment by lyw07** [comment]
Hi @holta , do you mean that creating `/home/kolibri` failed? or after creating `/home/kolibri`, the error `IOError: [Errno 2] No such file or directory: '/home/kolibri/SQLITE_MAX_VARIABLE_NUMBER.cache'` still exists?

**Comment by holta** [comment]
> Hi @holta , do you mean that creating `/home/kolibri` failed? or after creating `/home/kolibri`, the error `IOError: [Errno 2] No such file or directory: '/home/kolibri/SQLITE_MAX_VARIABLE_NUMBER.cache'` still exists?

Correct.

When root creates /home/kolibri (which I'd hoped would be a temporary workaround) this does not help anything &mdash; the exact same failures occur.

**Comment by lyw07** [comment]
Do you mind trying another command `sudo chown -R kolibri /home/kolibri` so that the user `kolibri` will have access to the directory? Thank you!

**Comment by holta** [comment]
> Do you mind trying another command `sudo chown -R kolibri /home/kolibri` so that the user `kolibri` will have access to the directory? Thank you!

At first that partially but not completely worked &mdash; see the failure ~4 lines down here:
```
root@box:~# systemctl status kolibri
● kolibri.service - Kolibri
   Loaded: loaded (/etc/systemd/system/kolibri.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-06-13 17:47:13 EDT; 44s ago
  Process: 30955 ExecStop=/usr/local/kolibri/bin/kolibri stop (code=exited, status=1/FAILURE)
  Process: 31142 ExecStart=/usr/local/kolibri/bin/kolibri start (code=exited, status=0/SUCCESS)
 Main PID: 31280 (kolibri)
    Tasks: 155 (limit: 4915)
   CGroup: /system.slice/kolibri.service
           └─31280 /usr/local/kolibri/bin/python2 /usr/local/kolibri/bin/kolibri start

Jun 13 17:47:03 box.lan kolibri[31142]: INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Jun 13 17:47:13 box.lan kolibri[31142]: INFO     Sqlite database Vacuum finished.
Jun 13 17:47:13 box.lan kolibri[31142]: INFO     Running 'kolibri start' as daemon (system service)
Jun 13 17:47:13 box.lan kolibri[31142]: INFO     Kolibri running on:
Jun 13 17:47:13 box.lan kolibri[31142]:
Jun 13 17:47:13 box.lan kolibri[31142]:         http://192.168.0.121:8009/
Jun 13 17:47:13 box.lan kolibri[31142]:         http://10.8.0.26:8009/
Jun 13 17:47:13 box.lan kolibri[31142]:         http://127.0.0.1:8009/
Jun 13 17:47:13 box.lan kolibri[31142]: INFO     Going to daemon mode, logging to /library/kolibri/logs/kolibri.txt
Jun 13 17:47:13 box.lan systemd[1]: Started Kolibri.
```
Then after I reran `cd /opt/iiab/iiab; ./runrole kolibri` the output of `systemctl status kolibri` became clean as it should be, without any failures at all.

Finally, IIAB has also just now implemented its own temporary workaround, pinning all IIAB installs to 0.12.3 for now, as an emergency patch (PR iiab/iiab#1735).

(Can you perhaps provide a rough estimate as to when 0.12.5 might be released, so that IIAB can revert to using Kolibri's very latest version by default, at that point?)

**Comment by lyw07** [comment]
Hi @holta thank you for trying the command and testing!

For 0.12.5, we are planning to release it some time next week. But we can give you a beta to test prior to the final release, as soon as we have the fix in.

**Comment by lyw07** [comment]
Hi @holta, we just released a [beta version of 0.12.5](https://github.com/learningequality/kolibri/releases/tag/v0.12.5-beta1) that contains the fix to the issue. Are you interested in testing if it fixes your issue? You are able to install it through `pip install kolibri --pre`. Please feel free to let me know if you have any questions! Thank you!

**Comment by holta** [comment]
> Hi @holta, we just released a [beta version of 0.12.5](https://github.com/learningequality/kolibri/releases/tag/v0.12.5-beta1) that contains the fix to the issue. Are you interested in testing if it fixes your issue? You are able to install it through `pip install kolibri --pre`. Please feel free to let me know if you have any questions! Thank you!

@lyw07 is the `--pre` flag absolutely necessary?

Note that IIAB uses Ansible to do pip installs (I don't see any obvious was to include a `--pre` flag within https://docs.ansible.com/ansible/latest/modules/pip_module.html) so it's a very important question, as you can see from this essential stanza here:

https://github.com/iiab/iiab/blob/master/roles/kolibri/tasks/main.yml#L23-L30

**Comment by lyw07** [comment]
@holta yes `--pre` flag is necessary because not including it will download the stable release 0.12.4 for you. 
Could you try adding it to `extra_args` field so that it will be 
```
extra_args: --no-cache-dir --pre
```

**Comment by holta** [comment]
> extra_args: --no-cache-dir --pre

This works, as later confirmed by:
```
root@box:~# /usr/local/kolibri/bin/kolibri --version
0.12.5b1
```
And then by running http://box/kolibri to reconfirm, which shows 0.12.5b1 down below.

Of course if you know how to guarantee http://box/kolibri logins work every time you get 10 Million Dollars cash (as Kolibri logins break for us regularly, for no apparent reason, as documented @ iiab/iiab#1532 !)

**Comment by lyw07** [comment]
@holta Thank you so much for testing and confirming that the beta fixes this specific issue! We will release the stable version 0.12.5 soon, by the end of this week.
