### ISSUE TITLE
Replace 'AppError' page with 'Page not found' when receiving a 404 response on a detail page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5666]
### Observed behavior

This issue is extracted from #5305. And is focused on this one case:

> Accessing a detail-type page when the underlying object no longer exists

Examples:

1. Viewing a User Permissions Page when the FacilityUser has been deleted
1. Viewing a Lesson Plan or Report page when the Lesson or Lesson Resource has been deleted
1. Visiting a Coach link for a class that has been deleted (it's handled like a 403 error)
1. Viewing ContentNode that has been deleted
1. Viewing a Quiz Plan or Report page when the Quiz has been deleted
1. Viewing a Learner Report page when the LEarner has been deleted
1. Visiting a report page for a learner or learner group when they have been deleted
1. (Add more)

(need to enumerate all cases to verify this issue is fixed)

In virtually all cases, if this happens, we get the generic AppError page.

### Expected behavior

When ever a user tries to *access* a detail-type page of deleted record, then they see a 'Page Not Found' screen that looks like this

![Screen Shot 2019-06-13 at 2 59 45 PM](https://user-images.githubusercontent.com/10248067/59470244-fcd29180-8deb-11e9-9faf-1c268dec3aa5.png)

### User-facing consequences

Instead of seeing a generic AppError page, they will see a 404-like page that indicates that the thing they are trying to access has been deleted.

### Context

Kolibri Version 0.12.4

**Comment by jonboiser** [comment]
Could we use a different phrase? "we can't seem to find" seems kind of misleading for most of the cases, even if some other websites use it to strike a certain tone.

A generic explanation about the item being deleted (which probably explains the reality 90% of the time) might be more helpful.

**Comment by indirectlylit** [comment]
Created a [string audit doc](https://docs.google.com/document/d/1B7E9RrxLatDF8R9a8JG8W8tEez6KrjrwPQPbE1biKsg/edit#)
