### ISSUE TITLE
phantomjs for kolibri on raspberry pi 

### ISSUE THREAD

**Issue by 3kay** [learningequality/kolibri#567]
Hi,

I just tried a kolibri install on an Raspberry Pi 3 Raspbian Jessie Lite, following the documentation
http://kolibri.readthedocs.io/en/latest/dev/getting_started.html
I had to download the kolibri-master.zip as the git cloning gave me permission errors.
$pip install -r requirements.txt (went smooth - no errors)
$pip install -r requirements/dev.txt (errors - ignored)
$npm install 
broke at: 
phantomjs-prebuilt
I searched for it in the /kolibri/node_modules directory and there was no such module present.
Google search revealed that phantomjs does not exist for ARM and that it has to be compiled from source. That compilation turned out to be really hard on rpi but now i have a compiled version for arm in /kolibri/node_modeles/phantomjs-prebuilt directory.
When i try again, 
$npm install
I get the following errors
.........
.........
2287 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
2288 verbose stack Error: /home/pi/kolibri/node_modules/phantomjs-prebuilt: Appears to be a git repo or submodule.
2288 verbose stack     at /home/pi/.nvm/v0.10.26/lib/node_modules/npm/node_modules/npm-install-checks/index.js:137:15
2288 verbose stack     at /home/pi/.nvm/v0.10.26/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
2288 verbose stack     at Object.oncomplete (fs.js:107:15)
2289 verbose cwd /home/pi/kolibri
2290 error Linux 4.4.21-v7+
2291 error argv "node" "/home/pi/.nvm/v0.10.26/bin/npm" "install"
2292 error node v0.10.26
2293 error npm  v3.10.9
2294 error path /home/pi/kolibri/node_modules/phantomjs-prebuilt
2295 error code EISGIT
2296 error git /home/pi/kolibri/node_modules/phantomjs-prebuilt: Appears to be a git repo or submodule.
2297 error git /home/pi/kolibri/node_modules/phantomjs-prebuilt
2298 error git Refusing to remove it. Update manually,
2298 error git or move it out of the way first.
2299 verbose exit [ 1, true ]

Has anyone tried kolibri on rpi3 and experienced such a problem? Any solution?

best,

LK

**Comment by indirectlylit** [comment]
Hi - thanks for the question!

The 'getting started' instructions - and the various Node.js and NPM dependencies that it references - are for the development environment only. We don't currently have plans to support Kolibri development on the Pi.

The resulting Kolibri application server is pure Python and will absolutely be installable on the Pi. Unfortunately, I don't believe we have stand-alone packages or installers available yet.

Kolibri is still in relatively early stages of development. If you're looking to deploy content soon, [KA Light](https://learningequality.org/ka-lite/) may work for you.
