### ISSUE TITLE
Add a "Done" message on successful DB imports

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#5672]
Kolibri with Postgres currently takes about 52 minutes to import the entire KA content database. Unfortunately Kolibri doesn't have a "done" message, making it a slight inconvenience to track the exact time the DB import has finished. I believe my logging is at INFO level.

The fix is to add a simple "Done!" message after the entire DB import is done, on the INFO level.

**Comment by indirectlylit** [comment]
@aronasorman this is referring to command-line imports I assume?

**Comment by aronasorman** [comment]
to both GUI triggered downloads, and CLI downloads. Basically as an admin, I want to see how long a content import takes. I have access to kolibri's timestamped logs.

The easiest way to do this is to just add a `logging.info("DONE importing {channel}")` at the bottom of the `importcontent` command.
