### ISSUE TITLE
Kolibri on Postgres takes more than 30 minutes to import a DB

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#5673]
I'm using a Kolibri instance with Postgres, and it took around 52 minutes to import the entire Kolibri DB. This is with Kolibri with a Postgres DB and a mounted network drive as its home directory.

The goal to close this issue is to bring it down to 20 minutes or less.

**Comment by rtibbles** [comment]
Let's go big or go home. 5 minutes or less!
