### ISSUE TITLE
Super admin label makes user CoreTable get internal vertical scroll

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#5678]
### Observed behavior
Unnecessary vertical scrollbar

![image](https://user-images.githubusercontent.com/1680573/59729561-c6ce4c80-91f3-11e9-96e5-70420d25fc19.png)

### Expected behavior
Don't show a scroll bar unless you have to.

### User-facing consequences
Ugly

### Context
 * Kolibri version: 0.12.4
 * Operating system: Ubuntu
 * Browser: Chrome

**Comment by nucleogenesis** [comment]
@rtibbles I'm not able to replicate this on Debian w/ Chromium or Chrome. I've looked at every table where users are listed that I can think of but perhaps I'm not looking in the right place?

**Comment by rtibbles** [comment]
Hrm - let me see if I can still replicate on current release.

**Comment by rtibbles** [comment]
I also can no longer replicate. Let's close this and reopen if it recurs!

**Comment by bjester** [comment]
I can replicate this whenever a user doesn't have name. The fix is fairly straightforward, so I'll throw it in.

**Comment by bjester** [comment]
Reopening for fix: https://github.com/learningequality/kolibri/pull/5919

**Comment by jonboiser** [comment]
Fixed for this particular table in #5919 by making sure rows with an empty full name cell get the same height as other cells.

I think that we should probably not allow facility users to be made without a full name in the importusers command, as this isn't allowed when making a user inside of Kolibri.

**Comment by rtibbles** [comment]
Seems like a reasonable restriction - can you open an issue?
