### ISSUE TITLE
Question text is sometimes not visible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5682]
### Observed behavior

We had a user report:

> Sometimes, I was unable to establish/replicate my steps for this- For some reason, the actual questions don’t appear on the computer version. It just shows the answers. On my mobile device, it works well though.  There seems to have been an issue -Invisible answer on the exercise #5648 which seems to have been addressed but then this came up. 
> 
> ![image](https://user-images.githubusercontent.com/2367265/59793830-89c29280-92a5-11e9-9268-d6610b06d583.png)

### Expected behavior

Question text should always be visible

### User-facing consequences

Learners will not be able to answer questions

### Errors and logs

unknown

### Steps to reproduce

unknown

### Context

* Operating system used: Windows 10 Pro
* Browser: Version 74.0.3729.169
* Kolibri Beta Version 0.12.4b7

**Comment by rtibbles** [comment]
Not clear what the circumstances for replication are. Closing.
