### ISSUE TITLE
Kolibri PyPi page description is not formatted correctly

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5684]
### Observed behavior

Since 0.12.4, after we changed README.rst to README.md, our PyPi page description has not been formatted correctly.
<img width="400" alt="Screen Shot 2019-06-19 at 1 10 35 PM" src="https://user-images.githubusercontent.com/19424916/59797081-b5d51800-9293-11e9-8fa9-ac1bbd361a41.png">

### Expected behavior

correct PyPi page description

### User-facing consequences

hard to read for people who look at Kolibri PyPi page

### Errors and logs

Log from the buildkite build:
```
python setup.py bdist_wheel --static
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
```
Docker image packages' versions:
```
root@8a00c8ddc845:/kolibri# pip show setuptools
Name: setuptools
Version: 39.0.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python2.7/dist-packages
Requires: 
```
```
root@8a00c8ddc845:/kolibri# pip show wheel
Name: wheel
Version: 0.30.0
Summary: A built-package format for Python.
Home-page: https://github.com/pypa/wheel
Author: Alex Grönholm
Author-email: alex.gronholm@nextday.fi
License: MIT
Location: /usr/lib/python2.7/dist-packages
Requires: 
```

### Steps to reproduce

https://pypi.org/project/kolibri/0.12.4/

### Context

…

**Comment by jonboiser** [comment]
The project description is formatted correctly as of 0.12.5 👍
