### ISSUE TITLE
Port content operations to use Django's Storage class

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#5698]
One of the difficulties in managing Kolibri in a cloud setting is its hard requirement for a filesystem. That's because we hard code file `open`, `write` and `read` calls. That requires us to have a shared filesystem among different replicas.

We should port Kolibri to use the [Django Storage class](https://docs.djangoproject.com/en/2.2/ref/files/storage/) for content storage interaction. Django comes with a filesystem storage backend that should maintain compatibility with our current setup. But this additional abstraction will then allow us to use Google Cloud Storage, Amazon S3 or Minio.

Allowing different Storage backends will not only make Kolibri on Cloud setups more reliable, but also make hosting cheaper in the short term, and A LOT cheaper in the long term.

**Comment by indirectlylit** [comment]
what kinds of content operations are being referred to here?

**Comment by rtibbles** [comment]
This is a won't fix - content specific file operations are handled separately for cloud instances.
