### ISSUE TITLE
The size of the channel thumbnail placeholder is different from real thumbnails

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5706]
### Observed behavior

In the Device > Channels page, channels without thumbnails have a grid icon in a gray rectangle. We tried to get it looking square with CSS, but things might have changed, so it it is more rectangular now.

![Screen Shot 2019-06-25 at 10 49 49 AM](https://user-images.githubusercontent.com/10248067/60121094-2d44f480-9737-11e9-8a55-db5537d50464.png)

### Expected behavior

Thumbnail-less channels have a default thumbnail placeholder that is the same size as other channels with a thumbnail.

One implementation would be to use an actual image instead of a div whose size and icon placement is managed with CSS.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

0.13

**Comment by indirectlylit** [comment]
note that channel thumbnails should be 16:9, but we'll standardize on that in 0.13.0
