### ISSUE TITLE
unhandled error: "content_assessmentmetadata" already exists

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5711]
### Observed behavior
Can someone knows what's the cause of having this `content_assessmentmetadata file exist` error

I did not reproduce this issue during upgrade installation. And this showing on Windows command prompt  

This is reported at this [issue](https://github.com/learningequality/kolibri-installer-windows/issues/78#issuecomment-502683072)

![image](https://user-images.githubusercontent.com/2367265/59607745-e70de680-90e1-11e9-90f7-42445fa6af78.png)

### Expected behavior
I need more information about this command prompt error `content_assessmentmetadata file exist`

### User-facing consequences

…

### Errors and logs
`content_assessmentmetadata file exist`

### Steps to reproduce
This error was reported on this  [issue](https://github.com/learningequality/kolibri-installer-windows/issues/78#issuecomment-502683072)

### Context

…

**Comment by rtibbles** [comment]
Closing as no additional occurrences reported since.
