### ISSUE TITLE
Kolibri demo banner visible on non-login pages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5715]
### Observed behavior

The demo banner is visible on all `/user` pages:

| page | image |
|--|--|
| sign-in | ![image](https://user-images.githubusercontent.com/2367265/60211988-1ffe3780-9815-11e9-99be-9989285d0ddf.png) |
| create account | ![image](https://user-images.githubusercontent.com/2367265/60212027-30161700-9815-11e9-9f31-67d2d283d7a6.png) |
| profile |  ![image](https://user-images.githubusercontent.com/2367265/60212094-4b812200-9815-11e9-8fbb-87797cd2a06e.png) |

### Expected behavior

banner is only visible on sign-in page

see note in https://github.com/learningequality/kolibri/pull/5412#issuecomment-487236781

### User-facing consequences

sub-par UX on account creation and profile pages

### Context

0.12.5

**Comment by jonboiser** [comment]
In the F12 developer tools while viewing an EPUB, I get an endless stream of these "Permission denied" errors ([sentry link](https://sentry.io/organizations/learningequality/issues/1087623753/?project=1379172&query=is%3Aunresolved&statsPeriod=14d)). They have no traceback and I'm not sure if it's coming from app code or the sentry SDK.

**Comment by jonboiser** [comment]
Fixed in #5716, by fixing the Vuex getter that determines whether that banner should be shown or not.
