### ISSUE TITLE
refactor User Auth, Learn, Device, and Facility apps to use new Coach-style page indexes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5719]
### Observed behavior

In Kolibri, we use a thin wrapper around the Vue router which allows routes to be associated with handler functions in addition to components. For some context on the motivations of this design decision, see https://github.com/vuejs/vue-router/issues/958

The typical pattern we originally used for routing in an app was roughly that all routes have a `name` (taken from a list of string constants), a `path`, and a `handler` (usually calling a Vuex action responsible for loading any data necessary for rendering the page):

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/user/assets/src/routes.js#L21-L29

The `handler` would also be responsible for setting core Vuex `PageName` state. This would in turn be checked by a single index page responsible for the whole app, containing a single instance of `CoreBase`. Both the props passed to `CoreBase` and the page component displayed within `CoreBase` needed to be dynamically set based on the current `PageName`:

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/user/assets/src/views/UserIndex.vue#L1-L14

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/user/assets/src/views/UserIndex.vue#L25-L29

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/user/assets/src/views/UserIndex.vue#L46-L48

In more complex apps (such as Coach), this pushed a lot of complexity into a single Vue file and made it very hard to maintain.

### Proposed common routing pattern

In the new Coach implementation, routes are now associated with both a `handler` _and_ a `component`, and the `name` (if not specified) is drawn automatically from the component name:

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/coach/assets/src/routes/index.js#L49-L53

Additionally, we sometimes embed information about the page title directly in the route as a `meta` tag (let's discuss this and evaluate if we want to re-use the pattern).

In coach, the index page becomes trivial band contains no logic:

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/coach/assets/src/views/CoachIndex.vue#L3

Conversely, each individual page ends up having its own instance of `CoreBase`:

https://github.com/learningequality/kolibri/blob/9f6eca3b2f078e00a6b7edd6776aff6aab5d4cfd/kolibri/plugins/coach/assets/src/views/home/HomeActivityPage.vue#L3-L27

This has the effect of pushing the complexity to many more top-level index files, typically (though not always) one per route. Usually we use a naming convention like `[Name]Page.vue` for these files. We've found this to be easier to maintain because it removes most reliance on maintaining a list of `PageName` constants.

See also:

* [slack thread](https://learningequality.slack.com/archives/CB37UM23A/p1637678295220600) discussing this issue and related issues with `CoreBase`, back-links, full-screen modals, etc
* related proposal regarding handling of nested routes: https://github.com/learningequality/kolibri/issues/4904

### User-facing consequences

None

### Context

0.12.x

**Comment by rtibbles** [comment]
This has been completed as part of the work to remove the CoreBase component.
