### ISSUE TITLE
user language settings are not persisted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5727]
### Observed behavior

When a user selects a language, that setting is not persisted across sessions.

### Expected behavior

User language settings should be persisted across sessions

### User-facing consequences

Users need to set their language every time they log in

### Steps to reproduce

* Set the default language of a server to English
* Log in as a different user
* Set your language to French
* Log out. At this point the sign-in page will be in English. It's not clear to me whether this is desirable (because it's the default server language) or not (because it should maintain the language of the most recent user, since they're likely to still be sitting in front of the computer)
* Log back in again. At this stage, it shows English even though it should definitely be French

### Context

0.12.5

**Comment by jonboiser** [comment]
In the logout_view, the reverse lookup of `redirect_user` always returns the english URL `/en/redirectuser`. I tried changing my Device Settings, and it doesn't change it. Maybe calling `logout` the line above defaults everything to English?

https://github.com/learningequality/kolibri/blob/a618e8740909f30de65e2e0d8aa484ce07a189f0/kolibri/core/views.py#L94-L97

**Comment by rtibbles** [comment]
Yes - I think the issue here is that once the session is logged out, the currently active translation context switches. Can dig into this.

**Comment by rtibbles** [comment]
Fixed in #5746
