### ISSUE TITLE
Migrate codebase to Vue 3 unified named and scoped slot syntax

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5729]
### Observed behavior

From https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax

> The `v-slot` directive was introduced in Vue 2.6.0, offering an improved, alternative API to the still-supported `slot` and `slot-scope` attributes. ... The `slot` and `slot-scope` attributes will continue to be supported in all future 2.x releases, but are officially deprecated and will eventually be removed in Vue 3.

Furthermore, from https://vuejs.org/v2/guide/components-slots.html#Named-Slots-Shorthand

> Similar to `v-on` and `v-bind`, `v-slot` also has a shorthand, replacing everything before the argument (`v-slot:`) with the special symbol `#`. For example, `v-slot:header` can be rewritten as `#header`

### Expected behavior

We should replace all instances of `slot` and `slot-scope` attributes in our codebase with the new syntax

### User-facing consequences

None

### Context

0.12.5

**Comment by jonboiser** [comment]
The remaining usages of this deprecated syntax can be found by uncommenting these two lines from `.eslintrc.js` and viewing the error report from ESLint

https://github.com/learningequality/kolibri/blob/c8ff8d027ab2764df36bcc1d9671aa1f84ecb412/packages/kolibri-tools/.eslintrc.js#L186-L188

Once those cases are resolved (excepting the ones related to CoreBase, see #6717) this issue can be closed. The CoreBase-specific issue (#6717) is still a blocker to making the codebase fully Vue 3-compatible.

**Comment by jonboiser** [comment]
The deprecated `slot=` syntax only remains in one place, here:

https://github.com/learningequality/kolibri/blob/5fd6c5ea7fda34c2f9c0728b8d87f38b7d785dd2/kolibri/plugins/slideshow_viewer/assets/src/views/SlideshowRendererComponent.vue#L55-L62

The `hooper` library will not be updated to be Vue 3 compatible, so we'll need to replace it as part of a Vue 3 migration.

**Comment by rtibbles** [comment]
I think this is as fixed as possible - the only caveat being we will have to replace Hooper if we do a Vue3 upgrade.
