### ISSUE TITLE
track versions of each activated plugin

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#5736]
### Observed behavior

Activating, deactivating, or upgrading plugin does not trigger Kolibri's `update` logic, and hence doesn't trigger `collectstatic`, `migrate`, etc even at times when they may be needed.

### Expected behavior

We should keep track of what version of each plugin is installed, as an entry in the .data_version file (or perhaps a new file).

MVP: changing a plugin could just wholesale trigger the running of the main `upgrade` function.

Better: when either Kolibri or a plugin version changes, we call the hooks for Kolibri itself and for each of the plugins to give them a chance to run any upgrade logic needed.

**Comment by indirectlylit** [comment]
updated the title because I believe this info would probably end up being stored in `kolibri_settings.json`

**Comment by indirectlylit** [comment]
see also https://github.com/learningequality/kolibri/issues/2510

**Comment by rtibbles** [comment]
Fixed in #5957
