### ISSUE TITLE
lint-frontend yarn command exits without showing a report for some errors sometimes missing changed files

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5752]
### Observed behavior

See [this Travis build](https://travis-ci.org/learningequality/kolibri/jobs/556056997#L886)

It exited with an error but did not actually print out the ESLint report explaining what the error was. It turned out, that it was an import-order error (which was discovered because my text editor pointed it out).

### Expected behavior

ESLint error reports are shown for all lint errors.

**Comment by jonboiser** [comment]
This is also happening for some stylelint rules. [This build](https://travis-ci.org/learningequality/kolibri/jobs/565708533) failed without an informative error for what seems like a CSS attribute order error.

**Comment by nucleogenesis** [comment]
Noting that this was run into again when a file that needed to be made `Prettier` was causing our `kolibri-tools lint` command to exit with code 1 but without any output to tell what the source of the failing exit code was.

At least one improvement that might fix this issue altogether is to ensure `Prettier` always prints to console the issues it finds even if it's not fixing them for you.

**Comment by nucleogenesis** [comment]
Additionally, `kolibri-tools lint` are not finding changed files unless given the file in the `--pattern` flag's arg

**Comment by nucleogenesis** [comment]
I have not run into this in the last couple years
