### ISSUE TITLE
auto-generate consistent environment variables for options

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5754]
### Observed behavior

* We allow configuration to be set in both `options.ini` and as environment variables
* Environment variables usually follow the pattern `KOLIBRI_[option_name]`
* We've had a couple recent deviations from this pattern, e.g. SENTRY and OIDC
* The main reason we allowed vars to be specified separately from options was so that we could still handle some legacy envvars

https://github.com/learningequality/kolibri/blob/3a2356883278f79b4a7655a47c7fa6db70acc184/kolibri/utils/options.py#L50-L177

### Expected behavior

* In `options.py`, rather than specifying `envvars` we should specify `envvar_aliases`
* All envvars should be generated by prepending `KOLIBRI_` to the option name
* Most existing envvar definitions can be removed

### User-facing consequences

Inconsistent environment variable definitions

### Context

0.12.5

**Comment by rtibbles** [comment]
Sounds good to me.
