### ISSUE TITLE
On Learn Resource Cards, progress bar is too low

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5755]
### Observed behavior

On the resource cards, the progress bar is too low, resulting in the wrong visual appearance for square shaped and rectangular cards

![Screen Shot 2019-07-09 at 12 00 25 PM](https://user-images.githubusercontent.com/10248067/60915701-58ecd200-a241-11e9-9ff1-e421f41ff0c7.png)
![Screen Shot 2019-07-09 at 12 00 10 PM](https://user-images.githubusercontent.com/10248067/60915702-58ecd200-a241-11e9-85c3-68fddb7dd21a.png)

### Expected behavior

The progress bar is in the correct place, for both versions of resource cards.

### Context

Kolibri 0.13

**Comment by luna215** [comment]
I can't seem to reproduce the low bar issue for the square cards. what browser and operating system were you using?
