### ISSUE TITLE
Brief flash of incorrect app bar label in import/export

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5759]
### Observed behavior

Reported by @jonboiser in https://github.com/learningequality/kolibri/pull/5653#issuecomment-509757634

> When importing from a USB drive, the "Select content from 'channel name' "label still appears briefly before changing to "<- Export to 'drive name'"
> 
> ![image](https://user-images.githubusercontent.com/2367265/60989690-754d4500-a2fb-11e9-8efb-761fba2e808e.png)

### Expected behavior

No unexpected flashes of app bar labels

### User-facing consequences

slightly disorienting state changes

### Steps to reproduce

Begin process of export

### Context

0.12.5

**Comment by nucleogenesis** [comment]
Removing this watcher here: https://github.com/learningequality/kolibri/blob/3743ee85ba10e26d672b14420ba3de2a8bd20b05/kolibri/plugins/device_management/assets/src/views/SelectContentPage/index.vue#L212-L216 fixes this issue - I haven't noticed any side effects in testing.

**Comment by rtibbles** [comment]
@nucleogenesis did you implement this fix?

**Comment by pcenov** [comment]
@radinamatic this issue is no longer extant in 0.15.1

**Comment by rtibbles** [comment]
Closing as no longer extant.
