### ISSUE TITLE
pass buildkite env vars prefixed with KOLIBRI_BUILD_ into docker

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5769]
### Observed behavior

Currently for UNW custom installers, we have an env var `BACKGROUND_IMAGE` that is defined in buildkite and gets passed into docker through `env.list`. 
As we will probably add more related env vars later for the custom installers, it will be better if we have a script that autogenrate the `env.list` to include all the env vars prefixed with `KOLIBRI_BUILD_` in the current environment.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Fixed in #5778
