### ISSUE TITLE
unexpected language behavior in shared-domain environment

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5771]
### Observed behavior

reported by @aronasorman 

> it looks like user language cookies are shared across domains -- if i open up `mexico.leq`it defaults to `es-es` (correct). But when I then open `jordan.leq` it also opens `es-es`, it looks like the language cookies are shared in at least the `*.unwomendemo.leq` domain?

### Expected behavior

If in fact this is a cookie-related issue, we should ensure that cookies from subdomains are kept independent of one another.

### User-facing consequences

Unexpected behavior when navigating between multiple Kolibri instances

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by aronasorman** [comment]
Hmm I'm unsure if it's a cookie-related issue now. Cookie-sharing across hosts is done by the `Set-Cookie` response header, but it looks like we don't set that in the main request at least.

**Comment by aronasorman** [comment]
Ah nvm, we do have some set-cookie headers, sent through `/api/auth/session/current`

**Comment by rtibbles** [comment]
We no longer use cookies for setting the language, so this issue cannot be extant.
