### ISSUE TITLE
links in coach dashboard have a leading underlined space

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5779]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/61334370-ff574b00-a7de-11e9-8a9c-475f5f5ff495.png)

### Expected behavior

underline should begin at start of text

### User-facing consequences

things look a little bit broken

### Steps to reproduce

view activity in coach dashboard

### Context

0.12.5

**Comment by jonboiser** [comment]
Probably need to do something similar to this https://github.com/learningequality/kolibri/commit/589b2cefa223a4455ad7269dfd70af93f81f1a96#diff-20e5ff25899fd87d56630a24f741f914: wrap the text in a span to get rid of extra whitespace

**Comment by indirectlylit** [comment]
Yeah. I've noticed that Prettier will sometimes cause breakage like this by re-formatting and wrapping across multiple lines even when the whitespace is significant.

We might want to check our options and make sure we're being as strict as possible with respect to significant whitespace:

https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting

**Comment by luna215** [comment]
I think this was a styling issue within the class `link`. I made a PR that can fix this issue. 
https://github.com/learningequality/kolibri/pull/5808
