### ISSUE TITLE
check_debian_user is run unconditionally, even when running CLI via pip or PEX

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#5786]
### Observed behavior

Trying to run a kolibri command inside a virtualenv using a pip-installed kolibri version.

Because I separately also have the DEB installed, when [`check_debian_user`](https://github.com/learningequality/kolibri/pull/3934/files#diff-8f9ca278df35a8b43572c4b10dafe306R22) is called, it displays the ["You are running this command as the user" message](https://github.com/learningequality/kolibri/pull/3934/files#diff-acc9016e41b9367b7e8b63511df4786aR25) and requires user input in order to continue. As I'm running this in a headless mode, via the Python `sh` module, this blocks the script.

### Expected behavior

1. I would expect this message to only be displayed if I'm actually running the Debian-installed version of `kolibri`, not when I'm inside a virtualenv.
2. Additionally, when this message otherwise _would_ still be displayed, I would want to be able to override it with something like `--noinput`.

CC @lyw07

**Comment by lyw07** [comment]
Thanks for reporting this issue! If we would like to display this image only when running the deb installer, I assume we will move the sanity check out of the kolibri source code but putting it into kolibri-installer-Debian source code?

**Comment by jamalex** [comment]
Or perhaps it could live in Kolibri, but we could add in better mechanisms to detect what method is being used to call the CLI (or run the server). So the Debian CLI entry point (and system service) could set an envvar, as could the PEX CLI entry point, etc, before passing to the Kolibri CLI code. This would also be useful for our tracking of what methods people are using to install/run Kolibri, as right now we only report what OS it is.

**Comment by lyw07** [comment]
yes that sounds better than putting the logic back to kolibri-installer-debian. I will try to see if there's a way for us to figure out how users install/run kolibri.

**Comment by rtibbles** [comment]
First thing would be to check if this function solves the issue: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/server.py#L491

If not, would be good to fix the behaviour for this function if possible, and then use it to conditionally trigger the check debian user function.

**Comment by lyw07** [comment]
thank you! I didn't realize that we have that function now. I will try using the function to see if it works in this case :)

**Comment by lyw07** [comment]
I started to work on this but have some questions regarding the `--noinput` flag, and it would be great if anyone can clarify this:

Since the `check_debian_user` is a function called in `cli.py`, having a `--noinput` flag means that we will need to add it to the top-level kolibri commands, so that users can run something like `kolibri start --noinput` to override the message in `check_debian_user`.

If that's the case, then this `--noinput` should also apply to other functions/commands that need user input. I'm just wondering if my understanding is correct. Thank you!

**Comment by rtibbles** [comment]
Should be fixed in #5859 - if not, please reopen.
