### ISSUE TITLE
Django language cookie persistently overrides device language setting

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#5794]
### Observed behavior

When a super admin sets the device language - for example, to Spanish - and a user later uses the language selection modal to personalize to different language, for example, French - then the browser that the user used to select French will not automatically revert to using the device language.

The translation logic prioritizes the language code in the URL first, then sessions and cookies, then the device language setting. However, we are not clearing that cookie regularly and a user must enter an Incognito browser to access Kolibri in the device settings language.

### Expected behavior

At some point, the device settings language ought to take priority. Using a user's language of choice that they personally set in the browser for an extended period of time makes sense - however - it ought to be safe to assume that the device admin has set a language that best serves their and their learners' needs for the most part.

Ideally, we would have a timed refresh where a browser's cookie expires and the browser defaults to the device language.

### User-facing consequences

Users may need to manually adjust their language settings  between sessions, particularly in a shared context.

**Comment by rtibbles** [comment]
Can probably resolve this by explicitly setting https://docs.djangoproject.com/en/1.11/ref/settings/#language-cookie-age to a specific/somewhat low value.

**Comment by nucleogenesis** [comment]
I added `LANGUAGE_COOKIE_AGE = 60` to the base.py conf file and the cookie expires as expected.

Now that I'm working with it, I'm thinking that we might not need the Django language cookie at all.

If we don't set any cookie at all - the language code is still stored on the user's session. So, if you select a language different than the device language, you will continuously see Kolibri in that language until your session is killed by the server or the session cookie is cleared from your browser.

Even if your session is killed or your session cookie is cleared, you will continue seeing Kolibri in your chosen language because we prioritize language code in the URL as the primary indicator for what language to direct to. The session expiring will only redirect you to the device language when you go to Kolibri root.

So - perhaps - it would be worth considering if we need to store the language on _either_ the cookie or the session but not both?

**Comment by indirectlylit** [comment]
That seems right to me.

The other thing to consider though is that the user's language selection should really be retained across sessions, so it ought to be stored as an attribute on the user model.

**Comment by rtibbles** [comment]
It think it would be reasonable not to use the Django language cookie - however, I think, as @indirectlylit suggests, we should store it as extra information about the user, so maybe we can do both things in tandem?
