### ISSUE TITLE
adjust facility data download layout

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5798]
### Observed behavior

There is space for the "Generated 3 months ago" timestamp text alongside the download button, but instead it displays below:

> ![image](https://user-images.githubusercontent.com/2367265/61750183-849bac00-ad59-11e9-943c-c8c6683b50dd.png)

### Expected behavior

The <kbd>Download</kbd> button, the timestamp text, and the 'generate' link should each individually be inline block elements in a single line. This will allow them to wrap like so:

> ![image](https://user-images.githubusercontent.com/2367265/61750304-e0663500-ad59-11e9-8475-a800bf5ce85f.png)

ref: https://learningequality.slack.com/archives/CAKK24483/p1563918143002700?thread_ts=1563917105.000600&cid=CAKK24483

### User-facing consequences

The timestamp text is not as obviously associated with the 'Download' button as it should be, leading to potential confusion about why 'generate' and 'download' are independent actions.

### Context

0.12.5

**Comment by priyanka-choubey** [comment]
@jonboiser I would like to work on this. thanks
