### ISSUE TITLE
Can't add fields to Collection model

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#5802]
### Observed behavior

A field was added to the Collection model, and the custom migration where the DeviceOwner is removed (`0004`) is broken because the field they added has not been migrated at the time of accessing the most up to date "Real" `Facility` model (https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/migrations/0004_auto_20170816_1607.py#L21).
Thus, Kolibri is not able to migrate properly when adding fields to the `Collection` model. 

### Expected behavior

Kolibri should be able to migrate successfully.

### Developer-facing consequences

Won't be able to add fields to the `Collection` model in the future.

### Steps to reproduce

First observed here https://github.com/learningequality/kolibri/pull/5373

### Possible Solution

Fix the migration `0004` to prevent it from erring out when accessing the Real `Facility` model, and forcefully/manually squash migrations so that device owners never get created.

**Comment by indirectlylit** [comment]
fixed in 0.13
