### ISSUE TITLE
How does you connect the js and backend

### ISSUE THREAD

**Issue by sarveshwaranj** [learningequality/kolibri#5815]
you use sqlite for db and rest api for getting contents but I don't know how the js and backend is connected and how we receive the data from backend
And where is the assets files and vue.js files 
I installed through pip command

**Comment by rtibbles** [comment]
Hi @sarveshwaranj - thanks for your interest in Kolibri! We detail how data is passed between the backend and the frontend in the developer docs: https://kolibri-dev.readthedocs.io/en/develop/dataflow/index.html

Hope this helps your understanding! I am going to close this issue, as it is not describing an issue with Kolibri, and is more of a question.
