### ISSUE TITLE
Unable to update a channel and continuous warnings in log

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#5825]
### Observed behavior

Such warning is flooding the kolibri.txt log when any attempt is made to update any channel after upgrade to 0.12.7 from 0.12.6a2 -

```WARNING 2019-07-27 15:53:59,877 utils Got an exception running <bound method Worker.check_jobs of <iceqube.worker.Worker object at 0x7f5709dccdd0>>: unsupported pickle protocol: 4```

Channel update process gets stuck at ``` Generating channel listing. This could take a few minutes… ```

The only way to stop the warnings seem to be to stop the kolibri process.

### Expected behavior

Should proceed with the channel update process and should not result in the continuous warnings in the log.

### User-facing consequences

Can't update channels. 
Disk space will fill fast.

### Errors and logs

Log file attached herein in case it helps spot any other information required.
[warnings_kolibri.txt](https://github.com/learningequality/kolibri/files/3438125/warnings_kolibri.txt)

### Steps to reproduce

Try updating a channel after upgrade to 0.12.7 as per the environment details given below as this problem doesn't manifest on Windows.

### Context

kolibri-server 0.12.5
kolibri deb 012.7
Ubuntu 18.04

**Comment by intelliant01** [comment]
Updated to kolibri-server 0.3.0 but problem remains same.

**Comment by intelliant01** [comment]
Does Kolibri now need Python 3+ on Linux as pickle 4 is supported by Python 3.6?
The [documentation ](https://kolibri.readthedocs.io/en/latest/install.html?highlight=python#other-linux-macos) doesn't say so.

**Comment by rtibbles** [comment]
This could happen if the new Kolibri version is being run with Python 3.6, but the worker process is still running in the background with an older Python version. Are there any extant processes that could be running an old Python version?

This seems to accord with what I see in the log where the Worker process is getting database locked errors, presumably because there are now two worker processes running?

**Comment by intelliant01** [comment]
Thanks @rtibbles. 

Yes, the problem was due to an old pex instance also firing up while I was making the switch to kolibri-server.

Now with pex completely removed, I am facing another issue. Shall create that anew.
