### ISSUE TITLE
There was an error showing this item 

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5827]
### Observed behavior

While solving a lesson, students sometimes get this error message instead of the question being displayed.

> **There was an error showing this item.**

### Expected behavior

Instead of the above message, the question should get rendered correctly.

### User-facing consequences

Students not able to answer the questions.

### Errors and logs

![Screenshot_2019-07-26-11-11-42 (1)](https://user-images.githubusercontent.com/8583367/62032831-4a725480-b208-11e9-9bcb-1cdafb5981be.png)
[kolibri (6).txt](https://github.com/learningequality/kolibri/files/3441007/kolibri.6.txt)

### Steps to reproduce

Occurs sometimes while the students are solving a lesson

### Context

Tell us about your environment, including:

 * Kolibri version : 12.5
 * Operating system : Ubuntu 18.04
 * Browser: Google Chrome

**Comment by indirectlylit** [comment]
@miyer03 the next time this happens, is it possible to access debugging logs from the console?

**Comment by miyer03** [comment]
@indirectlylit are you talking about the debug log in the kolibri/logs folder or any other log from the tablet.

**Comment by indirectlylit** [comment]
Sometimes it's possible to see javascript errors on the tablet. See for example: https://stackoverflow.com/a/2334977

**Comment by rtibbles** [comment]
This is almost certainly a result of slow loading of the assessment item data. Performance improvements and changes to exercise rendering should fix this in future, so let's file a new issue if this recurs.
