### ISSUE TITLE
Kolibri loading takes time in 12.5

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5828]
**### Observed behavior**
Its observed that the kolibri takes time to load and the students need to wait for minutes before the page loads or the question comes up.

…

**### Expected behavior**
Loading should not takes minutes.

…

**### User-facing consequences**
This leads in disinvestments of teachers and students.

…

### Errors and logs
Relevant logs from:
[kolibri (7).txt](https://github.com/learningequality/kolibri/files/3441089/kolibri.7.txt)
[kolibri (8).txt](https://github.com/learningequality/kolibri/files/3441090/kolibri.8.txt)
[kolibri (9).txt](https://github.com/learningequality/kolibri/files/3441091/kolibri.9.txt)
[kolibri (10).txt](https://github.com/learningequality/kolibri/files/3441092/kolibri.10.txt)

**### Steps to reproduce**
Try accessing kolibri through tablets in a classroom.

**### Context**

 * Kolibri version : 12.5
 * Operating system : Ubuntu 18.04
 * Browser : Google Chrome

**Comment by rtibbles** [comment]
We've removed the blockers to application startup since this issue was filed.
