### ISSUE TITLE
Landing page after Sign In might not be predictable for different roles

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5837]
### Observed behavior

The landing page (the page you go to after signing in) might not be predictable for some (probably rare) cases. Mainly, when non-admins are promoted to superuser, as well as the Class coach

Here's how the current landing pages go by role

* (Super) Learner -> Learn
* (Super) Class Coach -> Learn
* (Super) Facility Coach -> Coach
* Super Admin (any role, first login) -> Device (See #4747)
* Provisioning Super Admin (first login) -> Device
* Provisioning Super Admin (second login) -> Facility
* (Super) Admin -> Facility

### Expected behavior

On First Login (ever or _after_ receiving super admin permissions), all users who have super user permissions are redirected to the Device page.

On second Login:

* (Super) Learner -> Learn 
* (Super) Class Coach -> Coach
* (Super) Facility Coach -> Coach
* Provisioning Super Admin -> Device
* Not-provisioner (Super) Admin -> Device

New Changes:

* Users are redirected to Device Page after receiving SA permissions
* Class Coaches land on Coach page (instead of Learn)
* Admins land on Device page (instead of Facility)

### References

This blocks #4747 

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context
Kolibri 0.13

**Comment by khangmach** [comment]
>Maybe some guidance for super admins on how to best create Super Admin accounts (does it make sense to make a Super Admin/Coach or Learner?)

People make super admins for various reasons so instead of writing specific guidance, it could be in the user's best interest if there was predictability of where users land. The landing could be determined not by their base role or any transformations in their role, but what their current role is. 

(Super) Learner -> Learn
(Super) Class Coach -> ~~Learn~~ **Coach**
(Super) Facility Coach -> Coach
Super Admin (any role, first login) -> Device
Provisioning Super Admin (first login) -> Device
Provisioning Super Admin (second login) -> ~~Facility~~ **Device**
(Super) Admin -> ~~Facility~~ **Device**

**Comment by jonboiser** [comment]
So, for example, Super Admin Learners still go to "Learn" upon second login?

**Comment by khangmach** [comment]
what's a super admin learner? a Super admin that has been demoted to a basic learner role via another super admin?

**Comment by jonboiser** [comment]
You can create a Learner Account with Super Admin permissions by:

1. Create a basic learner account in Facility > User page
1. In the Device > Permissions, you can then give that learner Super Admin permissions. (so the learner is actually "promoted")

The landing page logic is driven by that Step 1, but the "Super Admin Learner" will have access to every other page.

**Comment by khangmach** [comment]
So:
- landing page is dictated by current role
- Any assigned super admin permissions after-the-fact just allows them to see the Device tab

So in this case, yeah they'd be landing on Learn. They're still a learner, just with access to device tab for whatever reasons

**Comment by jonboiser** [comment]
Okay, this makes implementation of #4747 a little more complicated, because we'll need to put extra logic for re-directing to Device page and showing the "Welcome..." or "Permissions Changed" modal in each of Facility, Coach, and Learn plugins, depending on whether the promoted or new superuser has a "current role" of Admin, Facility/Class Coach, or Learner, respectively.

Alternatively, we can show that Welcome modal on the natural landing page (but the messages will need to be different, since the current messages references the "Permissions" tab on the DEvice page.)

**Comment by khangmach** [comment]
this would be a great use of a global banner component. So no matter where you are or landed post-login, you would see the new information. I imagine the logic for that would be easier?

**Comment by jonboiser** [comment]
So to fix this specific issue, should we just enforce the "always go to the same page" policy described in "Expected Behavior" above?

For #4747, we can narrow the scope of that issue to be for only Provisioning Admins and New Admins (created as an Admin, then given Super Admin permissions) since they will always go to the "Device" page under the new policy.

Newly promoted Learners and Coaches will go to their respective landing pages and not see a notification, so we would need to figure something out for them, if we do want to show a notification.

**Comment by khangmach** [comment]
> On first login, still go to their intended landing page.

for which user types is this referring to?

>(?) Super Admins always have similar first and second Sign In experience, regardless of their "base" role

So if their base role is a learner and they're promoted to learner with perms
1st login == land on device
2nd & beyond == land on device?

**Comment by jonboiser** [comment]
No, I actually just crossed out that second item, since we were saying that, e.g. Learners with Super Admin permissions should always land on the Learn page.

Currently, they land on Device page if they've never logged in before, then Learn page afterwards.

**Comment by khangmach** [comment]
I'm gonna make a table or something. Really confused about what's feasible technically.
Edit:
https://docs.google.com/document/d/1U5EdiGhtial2Kjr1Acr28cQtzq_VmVvGZrBQ1dkm3m8/edit#

**Comment by indirectlylit** [comment]
FYI there has been some previous in-depth conversation on this topic. See e.g.:

* https://github.com/learningequality/kolibri/issues/1684
* https://github.com/learningequality/clearinghouse/issues/85

Recommend reviewing those threads

**Comment by rtibbles** [comment]
Not clear that we need to change this behaviour, closing this issue for now.
