### ISSUE TITLE
"Close" button on "Usage and privacy" modal does not work

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5838]
### Observed behavior
More information close button not working during the Kolibri setup.

### Expected behavior
Close button should work properly.

### User-facing consequences
User can't close the modal during the Kolibri setup.

### Errors and logs
![Screen Shot 2019-07-31 at 2 39 04 PM](https://user-images.githubusercontent.com/8663934/62191135-7ecf4780-b3a5-11e9-82b7-638efebef362.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.7
 * Operating system:  Ubuntu 14.04
 * Browser: Firefox 60.0

**Comment by jonboiser** [comment]
This should be fixed in #5830 for all of these modals.

Here are some workarounds for now:

1. Refresh the page
1. The Privacy Modal should still respond to pressing "Escape" on the keyboard, if the pop-up is in focus.
