### ISSUE TITLE
User menu button has no visual in-focus indicator

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5845]
### Observed behavior
[Discovered](https://github.com/learningequality/kolibri/pull/5839#issuecomment-517759637) while testing #5839:

> in Firefox there is a slight button color change when the user menu button receives focus, but no border/outline (**issue 1a**), and on the next <kbd>Tab</kbd> press the inner text label receives focus (**issue 1b** - there's no need for the label to be focusable).

> In Chrome the text label does not seem focusable, but the user menu button has no visual focus indicator whatsoever (**issue 1c**).

### Expected behavior
Consistent styling for buttons when in focus.

### User-facing consequences
Not knowing where the current focus is.

### Errors and logs
…

### Steps to reproduce
Use the <kbd>Tab</kbd> key to focus user menu button.

### Context
 * Kolibri version: 0.13.0.dev
 * Operating system: all
 * Browser: Chrome & FF

**Comment by indirectlylit** [comment]
Let's use the same default `$coreOutline` as other components, and remove any special styling like changing the background color.

**Comment by radinamatic** [comment]
#5852 did not fix this, as user menu button still does not have a visual indicator on current `develop`. Reopening.

![user-menu](https://user-images.githubusercontent.com/1457929/67907784-670c8880-fb79-11e9-8244-b1ccf095728c.gif)
