### ISSUE TITLE
options should be in line with item title, not 'back' link

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5846]
### Observed behavior

Observed during an audit of our responsive grids and page layouts (cc @jtamiace)

The 'options' button is currently associated with (next to or directly below) the 'back' link:

| large | small |
|--|--|
|  ![image](https://user-images.githubusercontent.com/2367265/62417183-86d5f400-b5fe-11e9-89e3-4fbc76f9bdef.png) | ![image](https://user-images.githubusercontent.com/2367265/62417187-91908900-b5fe-11e9-896b-ac802359182b.png) |

### Expected behavior

Since 'options' refers to the current page, I would expect it to be associated with the item title:

| large | small |
|--|--|
|  ![image](https://user-images.githubusercontent.com/2367265/62417211-1e3b4700-b5ff-11e9-8a12-2440b0494222.png) | ![image](https://user-images.githubusercontent.com/2367265/62417228-80944780-b5ff-11e9-80ed-848627515ecc.png) |

### User-facing consequences

Slight cognitive dissonance

### Context

0.12.5

**Comment by priyanka-choubey** [comment]
@indirectlylit @kollivier @radinamatic  I would like to work on this :smile:

**Comment by indirectlylit** [comment]
Thanks for the interest!

I just checked and it looks like this issue was actually addressed already. Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/2367265/74789396-7d923900-5269-11ea-9585-880823f08786.png)

Feel free to take a look through other [beginner-friendly issues](https://github.com/learningequality/kolibri/labels/TAG%3A%20beginner%20friendly)
