### ISSUE TITLE
Appbar active tab loses its active state when user clicks into a subtab

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5857]
### Observed behavior
Appbar active tab loses its active state when a user clicks in a subtab that is *not* in the first position. 

![losing active state](https://user-images.githubusercontent.com/25045166/62585479-e128bc00-b86d-11e9-8831-f11fbb776030.gif)

### Expected behavior
Appbar active tab does not lose its active state

### User-facing consequences
- Inconsistent behavior
- Bad indication of location, especially if you're navigating to a report from class home

### Steps to reproduce
- Navigate to coach plugin
- Click into reports
- See 'Reports' becomes the active tab
- Click into the 'quizzes' subtab
- See 'Reports loses its active state

### Context
 * Kolibri version: beta site
 * Operating system: MacOS Sierra
 * Browser: Chrome/Firefox

**Comment by jonboiser** [comment]
Maybe caused by the recent router changes in #5774, as this was meant to fix router problems within the Coach plugin.

I can't reproduce it inside of the Learn plugin, when doing similar navigation ("Channels" tab stays active even at the channel list level, or when at a topic).

**Comment by khangmach** [comment]
Yeah this seems to be only happening in the coach plugin as far as my eyes can see

**Comment by indirectlylit** [comment]
this is only in the `develop` branch, not 0.12.x

**Comment by bjester** [comment]
I can't reproduce this on branch `release-v0.13.x`

**Comment by radinamatic** [comment]
Seems to be resolved on 0.13.0b3, tested on Ubuntu 16.04 and macOS Mojave.

**Comment by indirectlylit** [comment]
great, thank you
