### ISSUE TITLE
Kolibri server is not starting in the Kolibri windows GUI. 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#586]
## Summary

Kolibri server is not starting in the Kolibri windows GUI. 

## System information

 - Version: 0.0.1.x
 - Operating system: windows 8.1

## How to reproduce

1. Install Kolibri installer in windows 8.1
1. Run the Kolibri application
1. Start the Kolibri server using Kolibri windows GUI. . 

REF: https://trello.com/c/wkkJdIEF/609-windows-8-1-tray-icon-doesn-t-reflect-true-running-state-or-correctly-start-server

**Comment by mrpau-eduard** [comment]
I try to run [kolibri](http://dungeon.learningequality.org:8085/browse/KOL-MTW-82/artifact/JOB1/Windows-installer/KolibriSetup-0.0.1.dev20161011203627.exe) on windows 8.1 64bit and windows 8.1 32bit but I can't replicate this issue.

**Comment by jayoshih** [comment]
I was able to replicate this error: 

Installer KolibriSetup-0.0.1.dev20161011203627
OS: Windows 10. 
Description: When I clicked the desktop icon, it said `Kolibri is already running` and when I tried to use the task-tray icon, the `Start Server`, `Stop Server`, and `Load in Browser` options were grayed out

![windows error](https://cloud.githubusercontent.com/assets/7447496/19542859/21813e38-9627-11e6-9529-22e4b6b875ad.PNG)

**Comment by jayoshih** [comment]
Link to the installer I used: http://dungeon.learningequality.org/browse/KOL-MTW-83/artifact/JOB1/Windows-installer/KolibriSetup-0.0.1.dev20161011203627.exe

**Comment by mrpau-richard** [comment]
@jayoshih I can't reproduce this issue in windows 10 64 bit using the Kolibri installer you give above. I created a screen recording on how I install the Kolibri installer.
https://www.youtube.com/watch?v=RevKlLktRFw&feature=youtu.be

**Comment by mrpau-richard** [comment]
Hi @jayoshih I  reproduced this issue in windows 8.1. I think it's because the `KOLIBRI_SCRIPT_DIR` environment variable is not set properly.

**Comment by radinamatic** [comment]
I wasn't able to reproduce this error before, but tested the [latest installer](http://dungeon.learningequality.org:8085/browse/KOL-MTW-87/artifact) and it seems to be running OK on Win 8.1. `KOLIBRI_SCRIPT_DIR` variable is there:

![ie11 - win8 1 ready for ka lite running - oracle vm virtualbox_148](https://cloud.githubusercontent.com/assets/1457929/19569570/870f6386-96f6-11e6-9ee0-52048c89e603.png)

**Comment by mrpau-richard** [comment]
This issue is fixed by setting the `KOLIBRi_SCRIPT_DIR` properly.
