### ISSUE TITLE
No vertical spacing between Channel Cards in Device > Channels page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5868]
### Observed behavior
![Screen Shot 2019-08-12 at 1 01 02 PM](https://user-images.githubusercontent.com/10248067/62894298-52022500-bd01-11e9-97ab-93593d9fc4ae.png)

This is caused by removal of the `windowGutter` property in this [change](https://github.com/learningequality/kolibri/pull/5843/files#diff-192738a96c7af0b0f187e844255a82c1R79)

### Expected behavior

There is some spacing between the cards
### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Version 0.13

**Comment by indirectlylit** [comment]
thanks
