### ISSUE TITLE
validation message is shown immediately on auto-focus of multi-facility account creation page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5875]
### Observed behavior

minor issue with auto-focus after showing facility selection modal:

* on the sign in page, no validation is initially displayed (correct)
* on create account page, validation is immediately displayed

| sign in | create account |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/63043409-08404880-be81-11e9-9bc9-db7d42468c06.png) | ![image](https://user-images.githubusercontent.com/2367265/63043424-0fffed00-be81-11e9-88cd-860bee9b49ab.png)|
| ![image](https://user-images.githubusercontent.com/2367265/63043223-a1bb2a80-be80-11e9-979d-3c14cfc0841b.png) | ![image](https://user-images.githubusercontent.com/2367265/63043244-af70b000-be80-11e9-92cf-0dafc06e67c6.png) |

### Expected behavior

no validation is initially displayed

### User-facing consequences

slightly aggressive validation

### Steps to reproduce

* Create a second facility, e.g. using `http://localhost:8000/api/auth/facility/`
* navigate to account creation page `http://localhost:8000/en/user/#/create_account`
* refresh and choose a facility
* note that validation message is shown immediately

### Context

0.12.8

**Comment by jonboiser** [comment]
This might be happening since, on the Sign Up Page, the "Full name" field has "autofocus=true". So the field is focused on the first load, then blurred when the modal pops up and focus is given to the modal.

If this is what's happening, we might be able unblur that field immediately before the modal shows up. IDK if that will get be fast enough, though.

**Comment by indirectlylit** [comment]
this would also be addressed more generally by implementing https://github.com/learningequality/kolibri/issues/2184

I'm sort of inclined to do that for 0.13.x - would you be interested in taking it on?

**Comment by Tlazypanda** [comment]
@indirectlylit is this issue still available?

**Comment by indirectlylit** [comment]
@Tlazypanda it may have been addressed by the work on https://github.com/learningequality/kolibri/issues/2184 during 0.13

However – if you're interested – it would be super helpful to confirm whether or not this is true.  You can generate multiple facilities by running:

```
kolibri manage generateuserdata --facilities 2
```

**Comment by jonboiser** [comment]
In 0.14, #6777 removes the "Select Facility" modal which cause the form to lose focus and show that error.
