### ISSUE TITLE
Super admin cannot access the second facility they created

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5876]
### Observed behavior
Discovered while [testing the 0.12.8 RC1](https://learningequality.slack.com/archives/C920Q1LNS/p1565819521070600?thread_ts=1565819521.070600&cid=C920Q1LNS).

Super admin creates the first facility upon installation, and then the second one through the `/api/auth/facility/`, but they are _not_ a registered user on the second one and can't sign in.

@rtibbles noted:

> They do technically have permission on the second one, but because we always send the facility data with the login, we only try to authenticate them against users in *that* facility.

### Expected behavior

Super admin should have a seamless experience to access the second facility, and maybe even be signed in automatically?

### User-facing consequences

Inability to manage facility and suboptimal super admin UX.

### Errors and logs

…

### Steps to reproduce

1. Sign in as super admin. 
2. Create a second facility through the `/api/auth/facility/`
If you sign out, you can create a learner account, but you cannot sign in as super admin to the second facility.

### Context

 * Kolibri version: 0.12.8 RC1
 * Operating system: all
 * Browser: all

cc @indirectlylit I've put the tentative 0.13 milestone, but up to you!

**Comment by jredrejo** [comment]
I am not sure of the right approach here. If one user sets kolibri up and creates one facility, he's technically the superuser. If another facility is created, shouldn't it have a different superuser to administrate it?
Do we really want one superuser having the power over all the users, classrooms, etc. in all the facilities?  ( throwing the stone and running away)

**Comment by radinamatic** [comment]
I don't recall that we made a conscious decision either way... 

In my head a super user is the **master** of the **device** and all the facilities that may be hosted on it, but there might be a reasoning to support a different setup. We do have a *Facility admin* users too, right?

**Comment by rtibbles** [comment]
The superuser *is* intended to be able to administrate all facility data on the device, whether it is their facility or not. We might want to change this, but it is part of the implied trust in the syncing model, whereby you should only sync your data to 'trusted devices'.

It's also a recognition of the simple fact that someone who has super admin access to the device can probably do what they want in the backend anyway - but maybe that's not really always the case.

**Comment by jredrejo** [comment]
if with all the data we mean channels and device setup, it's clear and that's fine so far. If we include also classes, lessons, groups, users... then the superadmin does not have access to this when syncing. Every facility has its own admin who access this "other" data. 

If we want the superuser to access to everything, this issue is obviously a bug and must be fixed, but I still don't see clearly if this is a bug or a feature.

**Comment by jonboiser** [comment]
This should be resolved with the new superuser features we added in Kolibri 0.14. Superusers should be able to access Facility + Coach data across the entire device.
