### ISSUE TITLE
Unable to reset filters in Manage resources for Lessons & Quizzes

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5882]
### Observed behavior

When filtering search results in **Manage resources** page while building lessons and quizzes, resetting the filter to *All* does not bring back all search results - it still seems stuck with just the current filter. 

It is also not possible to reset the search by clicking the **Reset** `X` button - it does nothing.

![filter-reset](https://user-images.githubusercontent.com/1457929/63286901-5dcd8880-c2b9-11e9-8dad-e6d7d4afe10c.gif)

### Expected behavior
Resetting the search and filtered results should work properly.

### User-facing consequences
User is not able to reset the search and filters.

### Errors and logs
The only observable error in the Console happens at the beginning of the search:

```
Invalid prop: type check failed for prop "searchTerm". Expected String with value "undefined", got Undefined
```

### Steps to reproduce
1. Search for resources to add to a lesson or a quiz.
2. Try filtering or resetting the search results.

### Context

 * Kolibri version: current `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: both FF & Chrome

cc @indirectlylit @jonboiser 
Again, tentative milestone set to 0.13, adjust if necessary.

**Comment by radinamatic** [comment]
@mrpau-dev We also need to add a *Reset search* scenario to **Create quizzes** feature file, and include all the search scenarios into **Create lessons** one, since they seem to be missing:

https://github.com/learningequality/kolibri/blob/release-v0.12.x/integration_testing/features/coach/coach-create-quiz.feature
https://github.com/learningequality/kolibri/blob/release-v0.12.x/integration_testing/features/coach/coach-create-lesson.feature

**Comment by indirectlylit** [comment]
set milestone to 'upcoming patch'

**Comment by radinamatic** [comment]
Filtering by channel & type of resource is now working on 0.12, but clearing the search field does not yet bring back all the channels. Same is valid for 0.13, will open a separate issue!

**Comment by jonboiser** [comment]
Closing as a duplicate
