### ISSUE TITLE
Focused buttons, links, etc. do not have an outline

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5884]
### Observed behavior

In keyboard modality, focused buttons, links, and form elements, do not have an outline (light green in default theme)

### Expected behavior
In keyboard modality, focused buttons, links, and form elements, have an outline (light green in default theme)

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri develop

**Comment by jonboiser** [comment]
The Observed Behavior is actually not consistent. I'm seeing a mix of outlined and non-outlined buttons in the Setup Wizard.

Focused:

* The Icon button <- on the top
* Radio buttons for Yes No forms
* All buttons on the language selector

Not focused:

* Other buttons on different steps (e.g. "Continue")

**Comment by radinamatic** [comment]
Weird thing is that on the first setup wizard step no elements seem to have focus outline, but when one uses the mouse to advance to the Step 2, suddenly focus outline is there.
