### ISSUE TITLE
remove stemmed_metaphone field from content nodes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5885]
### Observed behavior

The stemmed metaphone field is causing errors, and is not used. Reported from @jeepurs and @rtibbles 

![image](https://user-images.githubusercontent.com/2367265/63297178-a10e0400-c285-11e9-8e27-2041f8ca7942.png)

* this field was added here: https://github.com/learningequality/kolibri/pull/461
* we stopped using it here: https://github.com/learningequality/kolibri/pull/3599

### Expected behavior

Remove the field entirely

### User-facing consequences

errors in console

### Errors and logs

see screenshot above

### Steps to reproduce

…

### Context

0.12.8

**Comment by rtibbles** [comment]
https://sentry.io/organizations/learningequality/issues/1170519046/
https://sentry.io/organizations/learningequality/issues/1170519041/
https://sentry.io/organizations/learningequality/issues/1170456873/
https://sentry.io/organizations/learningequality/issues/1170456872/

**Comment by indirectlylit** [comment]
causing issues with UN Women online deployments

**Comment by rtibbles** [comment]
Previous fix was only temporary, so reopening for full fix.
