### ISSUE TITLE
Some immersive pages have the wrong exit link, esp. if coming from a notification

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5889]
### Observed behavior

Some immersive-style coach pages like 'ReportsLessonLearnerExercisePage' can be linked to by certain notifications on the Class home page activity feed and activity page, and should go back to _those_ pages when exiting via the "X" button on the top of the page. Some of these pages, however, have their exit linked hardcoded to a specific page:

https://github.com/learningequality/kolibri/blob/9d2a49d03349e4d1165747fde2aac99926e8930a/kolibri/plugins/coach/assets/src/views/reports/ReportsLessonLearnerExercisePage.vue#L32-L36

Here's one of the pages where the URL correctly remembers the last location

https://github.com/learningequality/kolibri/blob/9d2a49d03349e4d1165747fde2aac99926e8930a/kolibri/plugins/coach/assets/src/views/reports/ReportsLessonExerciseLearnerPage.vue#L32-L36

### Expected behavior

Immersive pages that can be linked to from more than one place should go back to the correct location when hitting the exit button.

### Context
Kolibri 0.12.8 as of 9d2a49d03349e4d1165747fde2aac99926e8930a

**Comment by priyanka-choubey** [comment]
@indirectlylit  Can I work on this?
