### ISSUE TITLE
update AuthMessage to include a link to sign in, and redirect back to previous page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5892]
### Observed behavior

Currently when a session is lost, the user signs in but loses their place

### Expected behavior

The user should have a link to sign in and then be redirected back to the page they were on previously.

![image](https://user-images.githubusercontent.com/2367265/63458091-fde4f800-c406-11e9-926c-3842618c2a09.png)

Note that we already have some redirect behavior that can be leveraged for this. We would essentially send someone to e.g.:

`https://kolibridemo.learningequality.org/en/user/#/signin?next=https%3A%2F%2Fkolibridemo.learningequality.org%2Fen%2Fcoach%2F#/`

https://github.com/learningequality/kolibri/blob/715b3393803ba65680f8c07c1db20e9400b30c92/kolibri/plugins/user/assets/src/views/SignInPage/index.vue#L338-L345

### User-facing consequences

getting logged out causes user to lose their place in the app

### Context

0.12.x

**Comment by rtibbles** [comment]
Note to allow for cases where the user plugin is disabled, this link should attempt to get the user page link and fall back to the base redirect link if not present.

**Comment by jonboiser** [comment]
If, say an already signed-in Learner sees this message, should we change the messages? Like "Sign out and go to Sign In Page", or something like that?

Similarly with the header "Did you forget to sign in?", should it be different since the user actually is signed-in, but maybe with the wrong account.

**Comment by radinamatic** [comment]
`Sign out and go to Sign In Page` sounds a bit convoluted and potentially confusing. And why would they need to sign in again, shouldn't it be enough to direct them to **Learn** again?

Maybe `Access to this page is restricted` as a header and `Go to Learn` link at the bottom...?

**Comment by jonboiser** [comment]
Going to Learn isn't general enough, I don't think. It could be a coach who has content management permissions trying to go to Device > Users, as well.

So the assumption I'm making here is that if the browser has a session and some user tries to go to a page that would not be authorized under that session, then the user might mistakenly be using the wrong credentials.

I've decided that in this case, that I will log the user out to be consistent with the anonymous user situation described in the original post. It's just that a more informative text could help educate the user.

**Comment by jonboiser** [comment]
> Note to allow for cases where the user plugin is disabled, this link should attempt to get the user page link and fall back to the base redirect link if not present.

In practice, a user cannot access a Coach, Facility, or Device Page without logging in (via the User Plugin's Sign In Page).

However, there is the one case where a user might try to access select pages in the Learn plugin (e.g. Class Assignments), so we will just send them back to the root of the Learn Page.

**Comment by indirectlylit** [comment]
> If, say an already signed-in Learner sees this message, should we change the messages?

In those cases, let's simply not show the link
