### ISSUE TITLE
Channel exercise hint number overlap

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5899]
### Observed behavior
Channel exercise number label overlap.

### Expected behavior
Number label should not overlap outside the container

### User-facing consequences

![Screen Shot 2019-08-23 at 4 51 40 PM](https://user-images.githubusercontent.com/8663934/63580194-dc326f00-c5c6-11e9-86e7-1e46a464d474.png)

### Steps to reproduce

…

### Context

 * Kolibri version: 0.12.8
 * Operating system: Ubuntu 18.04
 * Browser: Firefox 68.0.2

**Comment by radinamatic** [comment]
That should be the **hint** number (1 of 1). Maybe change the issue title for clarity @mrpau-richard?

**Comment by pcenov** [comment]
@radinamatic this one is fixed in 0.15.6:

![2022-08-03_16-37-47](https://user-images.githubusercontent.com/79847249/182622469-639787f7-182c-4409-a75f-0ec39084e726.png)

**Comment by rtibbles** [comment]
Closing as fixed.
