### ISSUE TITLE
create new KButtonGroup component and remove margins on KButton

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5900]
### Observed behavior

KButtons have built-in margins that are intended to keep adjacent buttons a consistent distance apart:

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/packages/kolibri-components/src/buttons-and-links/buttons.scss#L13

However, these need to be reset often when buttons are used on their own. See for example:

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/core/assets/src/views/CoreTable.vue#L136-L138

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/core/assets/src/views/language-switcher/LanguageSwitcherList.vue#L116

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/plugins/device_management/assets/src/views/DeviceSettingsPage/index.vue#L143-L145

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/plugins/device_management/assets/src/views/ManageContentPage/index.vue#L127-L129

and many others

### Expected behavior

* `KButton` should have no margins
* Add a new `KButtonGroup` component whose role is to enforce consistent spacing between child buttons
* search for and remove margin resets
* find all instances where buttons are used adjacent to each other, and use the KButtonGroup
* ensure that the button group addresses #5606

### User-facing consequences

None, but harder to maintain code

### Context

0.12.8

**Comment by jonboiser** [comment]
can this be implemented with a css class like `.button-group`? What else would the KButtonGroup component do?

**Comment by indirectlylit** [comment]
Yes, it could and you're right, it wouldn't do much besides setting spacing on its children.

However I've strongly been drawn towards thin wrapper components, particularly for the shared component library, for a few reasons:

1. **No pollution of the global CSS namespace.** If Studio for example wants to use the component library, they can rest assured that we won't clobber their existing styles
2. **Auto-generated documentation.** We've done a lot of existing work on auto-generating docs pages for components, but any docs for global styles would need to be manually maintained.
3. **Component naming conventions.** I am enjoying the naming conventions for component sets that "work together". Existing examples: `KGrid`/`KGridItem`, `Navbar`/`NavbarLink`

Whether a component exists for styling, logic, or both doesn't seem like a super critical distinction to me. What do you think?

**Comment by nucleogenesis** [comment]
Closing this because of the merges just above.

**Comment by indirectlylit** [comment]
huzah!
