### ISSUE TITLE
Migrations / Initialization happens without checking if another instance is running

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5906]
### Observed behavior

Kolibri 0.13.0.dev runs migrations even though another instance is running, which can potentially lead to database corruption.

CC: @rtibbles 

### Expected behavior

Kolibri should immediately quit.

### User-facing consequences

Almost certainly bad.

### Errors and logs

```
➜  kolibri git:(develop) kolibri start --foreground          
WARNING:root:No C Extensions available for this platform.

INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Version was 0.13.0.dev0+git.20190716150511, new version: 0.13.0.dev0+git.20190822215051
INFO     Running update routines for new version...
Operations to perform:
  Apply all migrations: admin, analytics, auth, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  Applying content.0019_contentnode_slideshow_options... OK
  Applying morango.0013_auto_20190627_1513... OK
Operations to perform:
  Apply all migrations: admin, analytics, auth, content, contenttypes, device, discovery, exams, kolibriauth, lessons, logger, morango, notifications, sessions
Running migrations:
  Applying content.0019_contentnode_slideshow_options... OK
  Applying morango.0013_auto_20190627_1513... OK
Installed 2 object(s) from 1 fixture(s)
INFO     Sqlite database Vacuum finished.
INFO     Running Kolibri
ERROR    Port 8080 is occupied.
Please check that you do not have other processes running on this port and try again.
```

### Steps to reproduce

Run Kolibri 0.12, so it shares directory with current `develop`. Then run `kolibri start --foreground`.

### Context

Development env. for current `develop` branch on a system with 0.12.8 installed from .deb.

### Related

The otherwise great #5494

**Comment by rtibbles** [comment]
Sounds good - just need to run the sanity check before we do the update logic, yes?

**Comment by benjaoming** [comment]
Agreed, but aren't sanity checks already run when `kolibri start` is run?

**Comment by rtibbles** [comment]
Yes - but the update is run before the sanity checks currently.

**Comment by benjaoming** [comment]
Oh interesting: Not having run updates isn't sane, but system should be sane before running them... this is a Catch 22 :)

Should we split something up here or will it be safe to run sanity checks before migrations/upgrading?

**Comment by rtibbles** [comment]
I think it's fine to run them before - they used to be run at module import, so it's just a matter of reinstating that order (but not having to run them at module import).
