### ISSUE TITLE
Briefly broken responsivenes on Device > Channels

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5909]
### Observed behavior

Brief break in responsiveness when the window is manually resized causes the channel thumbnails to loose margin/padding. First noticed with UI in Arabic, but reproduced arain when changed to English.

![2019-08-28_22-50-39](https://user-images.githubusercontent.com/1457929/63916141-a0474180-c9ec-11e9-9426-5d25e806df04.png)

![broken-responsive](https://user-images.githubusercontent.com/1457929/63915949-2020dc00-c9ec-11e9-8fcf-0fa5b778fdeb.gif)

### Expected behavior
Consistent margin/padding when resizing browser window

### User-facing consequences
Unclean UI
…

### Errors and logs
…

### Steps to reproduce
…

### Context

 * Kolibri version: encountered while testing asset from #5905, so probably present on `release-v0.12.x` branch  
 * Operating system: Windows 7
 * Browser: Firefox

@indirectlylit `upcoming patch` good?

**Comment by indirectlylit** [comment]
switching to 0.13.0 because this UI will be re-worked

**Comment by indirectlylit** [comment]
behavior updated in https://github.com/learningequality/kolibri/pull/6018
