### ISSUE TITLE
create gherkin story to exercise new Windows startup error reporting

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5911]
### Observed behavior

In https://github.com/learningequality/kolibri-installer-windows/pull/135  and https://github.com/learningequality/kolibri/pull/5905 we added functionality to detect and report when and why the server fails to start

### Expected behavior

We should add gherkin stories to exercise this new functionality

### Context

0.12.7

**Comment by cpauya** [comment]
Hi @indirectlylit - I think this [Gherkin story feature file](https://github.com/learningequality/kolibri/blob/develop/integration_testing/features/super-admin/super-admin-windows-installer-setup-error-log.feature) already addresses this?

**Comment by indirectlylit** [comment]
fixed in https://github.com/learningequality/kolibri/pull/5742
