### ISSUE TITLE
On Usage and privacy modal When clicking the button close, The model doesn't close.

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#5913]
I found a bug. is this issue opened? I'm not sure.

### Observed behavior
On Usage and privacy modal When clicking the button close, The model doesn't close.

<img width="1135" alt="Screen Shot 2019-09-02 at 12 24 27" src="https://user-images.githubusercontent.com/3889468/64088579-11844d00-cd7d-11e9-894a-6cea7a31c161.png">

…

### Expected behavior

As what you expect.

…

**Comment by jonboiser** [comment]
Could you check which version of Kolibri you are using? This should have been fixed in version 0.12.8, as well as the latest 'develop' branch.

**Comment by rationality6** [comment]
It's on 'develop' branch channel.

**Comment by jonboiser** [comment]
Which page did you open the Privacy modal? In the screenshot, are you on the sign up page?

**Comment by rationality6** [comment]
Yes! on the sign up page. http://localhost:8000/en/user/#/create_account

**Comment by jonboiser** [comment]
Since you have access to the code, could you see if SignUpPage.vue matches what you have? The current code _should_ be responding to clicking the "close" button (PrivacyInfoModal has a `@submit` handler)

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/plugins/user/assets/src/views/SignUpPage.vue#L97-L104

**Comment by rationality6** [comment]
No, not matched. This is code I can see.

    <PrivacyInfoModal
      v-if="privacyModalVisible"
      hideOwnersSection
      @cancel="privacyModalVisible = false"
    />

After add "@submit="privacyModalVisible = false"" It' works find

<img width="181" alt="Screen Shot 2019-09-04 at 10 17 34" src="https://user-images.githubusercontent.com/3889468/64218643-85e5fa00-cefd-11e9-83e1-af169fa77823.png">

I'm sure that I'm on a "develop" channel as well.

**Comment by jonboiser** [comment]
Yeah, we might have fixed it since you last checked it out. Could you try updating with `git pull origin develop`?

**Comment by rationality6** [comment]
Thank you for helping. closing this.
