### ISSUE TITLE
PDF renderer shows wrong page size

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#5917]
### Observed behavior

<img width="974" alt="Screen Shot 2019-09-04 at 9 19 54 AM" src="https://user-images.githubusercontent.com/163966/64258871-fd179000-cef5-11e9-8bf6-e112d7d609b1.png">

http://35.227.71.104/learn/#/topics/c/c1b42abb8ee45d2596e79197c46cd4c6

### Expected behavior

<img width="1040" alt="expected" src="https://user-images.githubusercontent.com/163966/64258883-00ab1700-cef6-11e9-9821-405ba4915def.png">

The [PDF file](http://35.227.71.104/downloadcontent/cf9a417eec5235696d787cf0eca72dcd.pdf/Introduction_Document.pdf) was tested in several other PDF readers and page always renders fine (half width as expected).

### User-facing consequences

The PDFs of this specific channel will be difficult to read. 

### Steps to reproduce

Try viewing 
http://35.227.71.104/learn/#/topics/c/c1b42abb8ee45d2596e79197c46cd4c6
in full screen mode

### Context

This PDF in the above links was obtained from a double-width PDF which was then cropped.

Here is a link to the original PDF
http://www.pointb.is/s/21CSGuide_English.pdf
and this is the code that cuts each page into left and right halves:
https://github.com/learningequality/sushi-chef-pointb-21csguide/blob/master/sushichef.py#L28-L62

Tested on latest: release-v0.12.x and 0.11.1

**Comment by jonboiser** [comment]
The PDF renderer appears to be reserving 2x the space for the right-side pages (with binding on the left). The renderer must be inferring this page width from something in the PDF file.

Is there anything different about these right-side pages when they're being cheffed? It's as if they are still using the same dual-page-width dimensions from the original PDF.

**Comment by ivanistheone** [comment]
@jonboiser Yes, the original PDF is 2x sized, so the chef code performs a "crop" operation by setting the `cropBox` and `trimBox` to half size, see
https://github.com/learningequality/sushi-chef-pointb-21csguide/blob/master/sushichef.py#L51-L54  (and `mediaBox` too but not show in this code)

The PDF rendering in any other PDF reader is fine (shows half-page), but somehow PDF.js doesn't seem to respect the page crop info, hence filing the issue here.

See #sushi-chefs threads:
  - https://learningequality.slack.com/archives/C6S90FCDT/p1567402734002400
  - https://learningequality.slack.com/archives/C6S90FCDT/p1567587911006900

**Comment by cpauya** [comment]
We can also use the PDF.js demo site here to validate the .pdf rendering: https://mozilla.github.io/pdf.js/web/viewer.html - just open the .pdf file you want to test.

<img width="1266" alt="Screenshot 2019-09-05 09 54 46" src="https://user-images.githubusercontent.com/175580/64305866-5ac5de00-cfc3-11e9-89ec-9b54b2ab7d9f.png">

**Comment by ivanistheone** [comment]
Thx @cpauya ; the above screenshot confirm that a more recent version of PDF.js would fix this issue.

The Kolibri `document_pdf_render` is pinned to 1.9.x:
https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/document_pdf_render/package.json#L7  which is 2 years old according to npm https://www.npmjs.com/package/pdfjs-dist

I will let the Kolibri team investigate further—there might be API differences or other obstacles to updated, but definitely worth looking into.

**Comment by rtibbles** [comment]
I tried to upgrade PDF.js at one point and everything broke. We should do it, but it will not be straight forward.

**Comment by rtibbles** [comment]
It seems that even with an upgrade of PDFJS, this has not been resolved.

**Comment by rtibbles** [comment]
Fixed in #9888
