### ISSUE TITLE
Extra scrollbar in report error modal

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5922]
### Observed behavior
There is an extra third scrollbar in the report error modal. 
- See thread here: https://learningequality.slack.com/archives/CB37UM23A/p1567704776028300

Screenshot of the scrollbar here:
![scrolbar](https://user-images.githubusercontent.com/25045166/64370173-c1062d00-cfd2-11e9-9374-68cba0086c25.png)

### Expected behavior
Only two scrollbars. One for the inner container of the markdown text, one for the modal contents.

### Steps to reproduce
- Navigate to a resource
- Delete part of the content id URL to get an error
- Press "Help us by reporting this error"
- Scroll thru the modal, see three scrollbars

### Context
 * Kolibri version: beta site
 * Operating system: MacOS
 * Browser: Chrome, Firefox

**Comment by rationality6** [comment]
Sorry, could you help me how to navigate to the resource?
I couldn't find the menu.

**Comment by indirectlylit** [comment]
@rationality6 

> * Navigate to a resource
> * Delete part of the content id URL to get an error
> * Press "Help us by reporting this error"
> * Scroll thru the modal, see three scrollbars

By "Navigate to a resource", it means just go to any content in Kolibri as a learner

**Comment by muhammadalics** [comment]
I tried to reproduce this using Firefox on Ubuntu but it appears that it works fine (for Firefox on Ubuntu).

**Comment by indirectlylit** [comment]
thanks for checking @muhammadalics - we can close as not reproducible in that case

**Comment by muhammadalics** [comment]
Thanks. Yup, only two vertical scroll bars are there. Posting this for reference: 
![kolibri_scrolbar](https://user-images.githubusercontent.com/59783720/114223348-f13f4b80-992c-11eb-97eb-a433052f4e1f.gif)
