### ISSUE TITLE
'importusers' and “createsuperuser” management commands should not allow empty 'full name' field

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5923]
### Observed behavior

The `kolibri manage importusers` command allows empty 'full name' fields when importing from CSV  files and defaults them to the empty string. This allows Facility Users to be made who have an empty full name, which is not possible inside the Kolibri UI, and can cause layout issues.

### Expected behavior

`importusers` doesn't allow empty 'full name' fields.

### User-facing consequences

…

### Context

Kolibri 0.13

**Comment by radinamatic** [comment]
`kolibri manage createsuperuser` will also have the same issue:

![2019-09-06_18-07-12](https://user-images.githubusercontent.com/1457929/64445001-baaca980-d0d5-11e9-930c-1cad907ad35e.png)

**Comment by jonboiser** [comment]
`createsuperuser` is a built-in management command in Django, so might need to do something different to enforce a non-empty full_name.

**Comment by rtibbles** [comment]
It would be different - but we already do some custom handling of this to make it work with the FacilityUser. The easiest thing would probably to make the `full_name` default to the `username`.

As it is editable after the fact, I think this would be a relatively harmless workaround.

**Comment by jonboiser** [comment]
@rtibbles 	Where is this "custom handling" done in the Kolibri code? At `auth.models.FacilityUser::create_superuser`?

**Comment by rtibbles** [comment]
Yup - https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/models.py#L580 on the model manager rather than the model itself.

Adding in the fullname where superuser FacilityUser is created ought to do it: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/models.py#L592

**Comment by radinamatic** [comment]
> The easiest thing would probably to make the `full_name` default to the `username`.

Sounds like reasonable workaround to me, and makes it easier for the users!

**Comment by radinamatic** [comment]
This will almost certainly need user docs update, if not Gherkin scenarios too...

**Remember the proper tags, people!!!**
