### ISSUE TITLE
Last attempt on a quiz question not displayed in the detailed quiz report

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5925]
### Observed behavior
Observed while [testing](https://github.com/learningequality/kolibri/pull/5595#issuecomment-528623695) the  #5595. 

When coach is looking at the detailed quiz report for a learner, it always lags behind one question: learner has answered it, but that last attempt is not displayed to the coach until the page reload.

![reload-to-see-answer](https://user-images.githubusercontent.com/1457929/64388916-f21d4680-d040-11e9-98ae-f0130e9fc5f8.gif)

This issue persists even after the learner submits the quiz.

![reload-to-see-the-last-answer-on-completed-quiz](https://user-images.githubusercontent.com/1457929/64388965-124d0580-d041-11e9-89aa-766b1565ee2c.gif)

### Expected behavior
All attempts must be correctly displayed in the detailed report.

### User-facing consequences
Inaccurate and inconsistent information provided to the coach.

### Errors and logs
…

### Steps to reproduce
See the GIF screencasts.

### Context
 * Kolibri version: #5955 (develop) dev branch
 * Operating system: Ubuntu 18.04
 * Browser: Chrome & Firefox

**Comment by nucleogenesis** [comment]
Resolved with merge of #5970
