### ISSUE TITLE
Running command "kolibri" (no args) gives return status 0

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5930]
# Observed behavior

Edit: Original issue removed. Running "kolibri" and getting no output was due to the "auto_cd" option on ZSH being switched on implicitly by an Oh My ZSH plugin.

Only remaining issue now is that non-0 return code is potentially a bad idea in case kolibri is invoked with its arguments truncated by mistake.

### Expected behavior

Status code 1 and usage instructions.

### User-facing consequences

~Not being able to figure out whether to use `--help` `help` or `-h` or `man kolibri` etc.~

### Errors and logs
n/a

### Steps to reproduce

Run `kolibri`

### Context

Current `develop` branch

**Comment by benjaoming** [comment]
@rtibbles can I also quickly ask in relation to the screenshot above from the old usage instructions: Have `diagnose` and `restart` been removed by mistake or intention?

**Comment by rtibbles** [comment]
As far as I could tell, they weren't implemented, so I removed them - did I miss something?

**Comment by benjaoming** [comment]
le sigh

you are right

**Comment by benjaoming** [comment]
From Kolibri 0.4:

![image](https://user-images.githubusercontent.com/374612/64455338-be4c2a80-d0ed-11e9-99a5-8f655165d667.png)

**Comment by indirectlylit** [comment]
rule number 23 of roadmaps: never mention the roadmap in code or documentation :D

**Comment by jredrejo** [comment]
@benjaoming running kolibri in develop, with `Click`and after running `pip uninstall docopt` I get this output:
```
(venv) jose@jose-xps:/datos/le/mio/kolibri$ kolibri
WARNING:root:No C Extensions available for this platform.

INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
WARNING  Ignoring unknown section in options file /home/jose/.kolibri/options.ini under top level: Debug.
Usage: kolibri [OPTIONS] COMMAND [ARGS]...

  Kolibri management commands

  For more information, see:
  https://kolibri.readthedocs.io/en/latest/advanced.html

  You can also run: kolibri COMMAND --help

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  manage    Invoke a Django management command
  plugin    Manage Kolibri plugins
  services  Start worker processes
  shell     Launch a Django shell
  start     Start the Kolibri process
  status    Show the status of the Kolibri process
  stop      Stop the Kolibri process
(venv) jose@jose-xps:/datos/le/mio/kolibri$ echo $?
0
```
So usage instructions appear.
Status code is  `0`, but I don't know why this issue says `1` is expected if there are no errors.

**Comment by benjaoming** [comment]
You're right @jredrejo - but how? What? I don't even...???

```
➜  kolibri git:(utils.cli-unicode) which kolibri
/home/user/.virtualenvs/kolibri/bin/kolibri
➜  kolibri git:(utils.cli-unicode) kolibri
➜  kolibri git:(utils.cli-unicode) pip uninstall docopt
Uninstalling docopt-0.6.2:
  Would remove:
    /home/benjamin/.virtualenvs/kolibri/lib/python3.6/site-packages/docopt-0.6.2.dist-info/*
    /home/benjamin/.virtualenvs/kolibri/lib/python3.6/site-packages/docopt.py
Proceed (y/n)? y
  Successfully uninstalled docopt-0.6.2
➜  kolibri git:(utils.cli-unicode) kolibri
WARNING:root:No C Extensions available for this platform.

INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
Usage: kolibri [OPTIONS] COMMAND [ARGS]...

  Kolibri management commands

  For more information, see:
  https://kolibri.readthedocs.io/en/latest/advanced.html

  You can also run: kolibri COMMAND --help

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  manage    Invoke a Django management command
  plugin    Manage Kolibri plugins
  services  Start worker processes
  shell     Launch a Django shell
  start     Start the Kolibri process
  status    Show the status of the Kolibri process
  stop      Stop the Kolibri process
```

**Comment by jredrejo** [comment]
:D @benjaoming now you can try to install docopt again and see what happens

**Comment by benjaoming** [comment]
The behavior returns upon installing docopt. Oh dear oh dear, what is this.

**Comment by benjaoming** [comment]
I have some bug in my shell, writing "kolibri" issues a "cd kolibri". Probably Something with ZSH or Oh My ZSH. Edit: Here is the problem https://unix.stackexchange.com/questions/126719/how-to-disable-auto-cd-in-zsh-with-oh-my-zsh

The only issue here would be the return code being zero.
