### ISSUE TITLE
Are these option boxes located currently?

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#5933]
Instructions:

are these option boxes located currently?

seems they are not.

### Example 1

<img width="939" alt="Screen Shot 2019-08-18 at 15 49 33" src="https://user-images.githubusercontent.com/3889468/64524563-ba144d00-d339-11e9-83bc-ed3d7b47416e.png">

### Example 2

<img width="885" alt="Screen Shot 2019-09-09 at 19 41 29" src="https://user-images.githubusercontent.com/3889468/64524658-f8aa0780-d339-11e9-8f47-471ba05451f1.png">

…

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

 * Kolibri version: latest dev
 * Operating system: mac os Mojave
 * Browser: chrome
…

**Comment by jonboiser** [comment]
Yes, this is a bug currently in develop. We have an issue for it here #5868

**Comment by rationality6** [comment]
Okay closing this.
