### ISSUE TITLE
answer box missing for an exercise

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5934]
### Observed behavior

The answer box is missing for an exercise in the KA English channel. And if I click next, it will determine that I answer the question correctly, although I don't input anything.

This was originally reported by a student during site visit, and I found the same issue on kolibri demo. However, I'm not sure if this is a Kolibri issue or KA (en) issue, since there are no errors showing in the dev console.

### Expected behavior

There should be an answer box for students to put their answers

### User-facing consequences

Students cannot enter their answers, and the program automatically thinks they answer the question correctly.

### Errors and logs

On Kolibri demo:
<img width="578" alt="Screen Shot 2019-09-11 at 5 17 29 PM" src="https://user-images.githubusercontent.com/19424916/64744434-b5c26e00-d4b8-11e9-9174-18db7c306f40.png">

On KA website:
<img width="315" alt="Screen Shot 2019-09-11 at 5 19 08 PM" src="https://user-images.githubusercontent.com/19424916/64744540-2073a980-d4b9-11e9-84dc-62b47e3dee09.png">

### Steps to reproduce

1. go to https://kolibridemo.learningequality.org/en/learn/#/topics/c/f3fc43e06d385c149c531563d21308e7
2. do the exercises to find the one that has missing answer box

### Context

Kolibri version: 0.12.7 & 0.12.8
Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic I'm not able to see the above specified exercise at the current version of kolibri-demo now, perhaps this was a content issue?

**Comment by rtibbles** [comment]
Closing as no longer extant.
