### ISSUE TITLE
kolibri start --foreground does not show port and address

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5938]
### Observed behavior

It would be VERY nice to know where kolibri thinks it's running :)

![image](https://user-images.githubusercontent.com/374612/64887360-b863c580-d668-11e9-8e2b-57a571551b1e.png)

### Expected behavior

The same information as is displayed w/o `--foreground`

### User-facing consequences

Some debugging is harder.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

0.12.8

**Comment by rationality6** [comment]
<img width="694" alt="Screen Shot 2019-09-19 at 16 46 45" src="https://user-images.githubusercontent.com/3889468/65223902-15de9300-dafd-11e9-9a60-b78de7077853.png">

Is this already fixed on latest dev right?

I can see port and address there.

**Comment by benjaoming** [comment]
That's true, I see it there. Thanks @rationality6
