### ISSUE TITLE
On Windows Chrome, scrollbars appear on truncated areas with missing overflow-x/y rules

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5943]
### Observed behavior

In at least two places (The username on the top-right of the AppBar, and in Coach/Learner enrollment table), scrollbars appear next to names in Chrome Windows.

This appears to be because of

1. An `overflow-x` rule
2. A little bit of vertical overflow
3. A lack of a `overflow-y` rule

Or something similar in the other dimension. The screenshots below show both cases.

![username](https://user-images.githubusercontent.com/10248067/65185037-975df480-da1b-11e9-9b0b-8ccce51e91e6.png)
![Capture](https://user-images.githubusercontent.com/10248067/65185038-975df480-da1b-11e9-8d8f-e98ed3b6be11.PNG)

### Expected behavior

The scrollbar doesn't appear in these two (and other similar places), since usually the content isn't tall enough to scroll.

### User-facing consequences

Windows Chrome users see a scrollbar

### Context
Kolibri 0.13 (develop and version on kolibribeta.learningequality.org)

**Comment by jonboiser** [comment]
For the `.username` class in AppBar.vue, adding a `overflow-y: hidden` rule seems to fix it.

For the issue in the Class Enrollment page, in UserTable.vue, adding a rule that targets the "role" column with an `overflow-x: hidden` rule that overrides the default from CoreTable seems to fix that area.

**Comment by indirectlylit** [comment]
When addressing this, we need to be careful of another pervasive issue, clipped descenders:

* https://github.com/learningequality/kolibri/issues/5553
* https://github.com/learningequality/kolibri/issues/5538

**Comment by jonboiser** [comment]
I think this might be a stale issue.
