### ISSUE TITLE
Resources in a lesson do not appear in the order set by the coach in Reports

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#5964]
### Observed behavior

The order set for learners in 'Edit details'
<img width="1003" alt="Screen Shot 2019-10-01 at 2 40 48 PM" src="https://user-images.githubusercontent.com/6668144/66002920-a56b3680-e459-11e9-8035-ae45739a6efe.png">

The order in the lesson reports:
<img width="972" alt="Screen Shot 2019-10-01 at 2 41 00 PM" src="https://user-images.githubusercontent.com/6668144/66002938-af8d3500-e459-11e9-9a0d-3a7045027161.png">

And the order seen by the learners:
<img width="873" alt="Screen Shot 2019-10-01 at 2 45 10 PM" src="https://user-images.githubusercontent.com/6668144/66003152-232f4200-e45a-11e9-98b3-5fc03ad2cfee.png">

### Expected behavior

The order in the Reports is out of order, and should be the same as in 'Edit details' and what is shown to the learner

### User-facing consequences

Confusion for the coach if they want to set a specific order of resources for a learning pathway

### Steps to reproduce

As a coach:
1. Create a lesson
2. Add resources and change the order
3. Save changes and observe the order in the lesson report
4. Go to 'edit details' and see the difference

### Context

http://kolibribeta.learningequality.org/en/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/lessons/509ea42b8cac6452f269b3790e3f2618/resources

0.13.0a1.dev0+git.66.g428278f8
MacOS
Chrome

**Comment by jonboiser** [comment]
It looks like the report orders the resources alphabetically by title.
