### ISSUE TITLE
String audit (content/resource <> material; performance <> score)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5965]
### Observed behavior

During the [discussion about Kolibri ecosystem Glossary](https://docs.google.com/document/d/1_pctX5MdTblQlQumow0CCu28qOaE88BW72iw4qqs9yA/), we pinpointed the need to better define some terms. Proposed changes include:

1. Switch to using the term **resource** instead of **content** or **material**.
2. Consolidate **performance** and **score** (better define the difference, maybe start using just one term?)

The first item will require string audit and refactor on both Kolibri & Studio, and even though the number of strings with this term in Kolibri is not great, my intuition is that this will have broader ramifications and further discussion, so I'm not putting in the milestone for now. cc @indirectlylit 

### Expected behavior
…

### User-facing consequences
Clearer terminology, improved understanding.
…

### Errors and logs
…

### Steps to reproduce
…

### Context
…

**Comment by rtibbles** [comment]
I am still against switching from 'resource' to 'material' - 'resource' is absolutely the right word in English for this, as evidenced by the fact that we are in the business of distributing Open Educational *Resources* not Materials.

The main argument I have heard in favour of this switch has been to make it clearer to translators, but that implies to me that we should be using translation context to maintain this (and explanation in the glossary), and not changing the English term.

**Comment by radinamatic** [comment]
I would agree with the decision not to make this a string refactor, but restrict it to context information for the translators.  

Actually, the original discussion started with the need to avoid the term **content**, as per recommendation from @shivichandra. My only question is _are we even able to_? How do we start talking about **Studio** at all? Resource curation platform...? :thinking:

**Comment by rtibbles** [comment]
Sounds right, or even a 'resource aggregation, alignment, creation, and editing' platform.

**Comment by radinamatic** [comment]
Sounds :+1: , but that does imply a string refactor across the whole ecosystem.
