### ISSUE TITLE
KDropdownMenu refocuses after scrolling/clicking out of view

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#5974]
### Observed behavior

Clicking dropdown menu button and scrolling outside of view, and clicking anywhere in the window brings focus back to the button.
![Oct-09-2019 15-07-55](https://user-images.githubusercontent.com/6361732/66524276-d6291c80-eaa6-11e9-9107-5394efe7447a.gif)

Has something to do with this
https://github.com/learningequality/Keen-UI/blob/next/src/UiPopover.vue#L149

### Expected behavior

When clicking outside, it should not refocus to the dropdown menu button.

### User-facing consequences

Users confused with inconsistent UI/behavior.

### Steps to reproduce

1. Go to user page, or anywhere with dropdown menu.
2. Click dropdown menu and scroll out of view of the button.
3. click anywhere in window.

### Context

Chrome

**Comment by nucleogenesis** [comment]
I am not able to replicate this - closing as it has likely been resolved inadvertently.
