### ISSUE TITLE
transitions on modals and snackbars are sometimes not shown

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5979]
# Observed behavior

Modals and snackbars both are supposed to have `enter` and `leave` transitions. However in many cases, they are either shown or disappear immediately with no transition.

### Expected behavior

`enter` and `leave` transitions are always shown

### User-facing consequences

UI feels more abrupt, less smooth

### Steps to reproduce

two specific examples:

* click button to create a new lesson. There is a `leave` transition but no `enter` transition on the modal
* add/remove items from a lesson. There is an `enter` but no `leave` transition

### Context

0.12.x

**Comment by jonboiser** [comment]
Which modals have the enter transition you're expecting? They all seem to have the same fast enter behavior.

**Comment by jonboiser** [comment]
For modals, it seems that because we always wrap KModal, that the 'enter' transition defined on KModal is never actually shown. I tried a hack where I render ChangeUserPasswordModal as an empty div, then show the wrapped KModal in the 'mounted' hook, which will then show the proper transition.

**Comment by jonboiser** [comment]
Adding the `appear` directive to the KModal's transition seems to help.

**Comment by indirectlylit** [comment]
> For modals, it seems that because we always wrap KModal, that the 'enter' transition defined on KModal is never actually shown

exactly. My initial thought was that we would need to add some sort of `visible` attribute to `KModal` and have an inner div hide/show inside the transition

> Adding the `appear` directive to the KModal's transition seems to help.

that would be great if the fix were that easy!

**Comment by jonboiser** [comment]
This should be fixed in develop for both Modals and Snackbars
