### ISSUE TITLE
images from questions not appearing in learner quiz view

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5986]
### Observed behavior

Reported by @miyer03 [in this comment](https://github.com/learningequality/kolibri/issues/5702#issuecomment-527350719):

* G8 -> 11 statistics -> Sub-divided bar graph -> assessments

Contact Manoj or Devon for the channel ID 

![WhatsApp Image 2019-08-29 at 5 53 03 PM (1)](https://user-images.githubusercontent.com/8583367/64154810-2fba7d80-ce4f-11e9-8f94-c44780853d42.jpeg)

### Expected behavior

Graph should be visible

### User-facing consequences

Learner cannot complete quiz

### Errors and logs

None provided

### Steps to reproduce

Unknown

### Context

Unknown

**Comment by indirectlylit** [comment]
@miyer03 I tested this locally in the 0.12.x branch and was not able to reproduce.

Are you able to reproduce in your office? If so, you can give us access to it with [ngrok](https://ngrok.com) and we can see exactly what you're seeing.

| note | image |
|--|--|
| graph shows as expected | ![image](https://user-images.githubusercontent.com/2367265/67437478-c1b84a00-f5a5-11e9-9779-57a78ece54f1.png) |

**Comment by miyer03** [comment]
@indirectlylit This happened sometime back. Will try to reproduce and if it occurs will report it to you. The image issue have reduced significantly in 12.8 compared to 12.5

**Comment by rtibbles** [comment]
No reports of this in some time, and unlikely to recur in this form after 0.14.7 is released.
