### ISSUE TITLE
'☣ LOCALPATH' shown in KA Math hint

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5988]
### Observed behavior

* URL: http://localhost:8000/ko/learn/#/topics/c/f56881f0a2f25dfa910fedd7b0593325
* Name: Relate addition and subtraction
* Channel: Khan Academy (en) public channel

![image](https://user-images.githubusercontent.com/2367265/67522290-59c73980-f661-11e9-958c-72bbca2bff6c.png)

![image](https://user-images.githubusercontent.com/2367265/67522410-88ddab00-f661-11e9-9929-9da2e22dc33a.png)

### Expected behavior

Hints show as expected.

### User-facing consequences

cannot use hint; app looks confusing

### Errors and logs

![image](https://user-images.githubusercontent.com/2367265/67522307-63e93800-f661-11e9-8a91-2bcdceaa200f.png)

### Steps to reproduce

* Import KA first-grade math
* Navigate to exercise given
* Take a hint

### Context

0.12.9 alpha

**Comment by rtibbles** [comment]
Is this still happening?

**Comment by indirectlylit** [comment]
I don't see it, no
