### ISSUE TITLE
Add warnings to catch invocations of translation functions before polyfill loading occurs

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6003]
### Observed behavior
On two occasions now we have fixed Kolibri due to invocation of translation machinery in module scope breaking on Intl-polyfilled browsers. (#5254, #6002)

### Expected behavior
The linter should catch these invocations in module scope and error.

Alternatively, we can add a flag like `i18nReady = false` that gets set to `true` after `setupi18n` has been invoked. Then the translation machinery should complain if run too early

### User-facing consequences
Total breakage in old browsers.

**Comment by jredrejo** [comment]
Would not it better to set 0.12.x as the milestone?

**Comment by indirectlylit** [comment]
Updated description and title.

I don't believe this should be a blocker for 0.12.9
