### ISSUE TITLE
'Change language' in the user profile menu is not focusable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6006]
### Observed behavior

Follow-up from #5999 

https://github.com/learningequality/kolibri/pull/5999#issuecomment-547386757

- ~`BlockItem` components (eg, Coach > Class Home > Quizzes and Lessons lists) don't have any keyboard outline style.~ addressed by #5852
- The keyboard focus indicator skips "Change language" in the user profile menu.

### Expected behavior

proper focus rings everywhere

### User-facing consequences

accessibility not as good

### Context

0.13.x develop branch

**Comment by radinamatic** [comment]
I was just today testing #5999 for this, will finish a deeper dive and post more issue instances tomorrow.

One thing I don't remember, what was the visual indicator we decided for when a `select` element (drop-down _menu_) is in focus? Right now I can only see the bottom edge getting a bit thicker, but that hardly seems enough :confused:

**Comment by indirectlylit** [comment]
@radinamatic can you please post a screenshot

**Comment by radinamatic** [comment]
`Show active/inactive quizzes` filter, for example:

![focus](https://user-images.githubusercontent.com/1457929/67823282-b80d7580-fac2-11e9-9fba-2da8513e1e50.gif)

**Comment by indirectlylit** [comment]
thanks - yeah that's been the implementation forever.

I do think the right direction to go is to use the standard outline everywhere, consistently, unless there's a good reason not to in specific instances

**Comment by radinamatic** [comment]
> I do think the right direction to go is to use the standard outline everywhere, consistently, unless there's a good reason not to in specific instances

Agreed, let's go with that for the time being. Let's think of the way to put these states in the style guide (design system).

**Comment by radinamatic** [comment]
_transferred to #6016_

**Comment by radinamatic** [comment]
_[reopened](https://github.com/learningequality/kolibri/issues/5845#issuecomment-549006533) #5845_

**Comment by radinamatic** [comment]
_working correctly on current `develop`, deleting_

**Comment by radinamatic** [comment]
Ok, I went through all the rest of the coach and admin workflows and did not find other issues. 🙂 

Will check Learner tomorrow, but these seem to be good to start working on! 😉

**Comment by radinamatic** [comment]
> The keyboard focus indicator skips "Change language" in the user profile menu.

`Change language` is not present in the focus order **at all**:

![LEDev1911n (start)  Running  - Oracle VM VirtualBox_044](https://user-images.githubusercontent.com/1457929/67997153-23864d00-fc53-11e9-8bcb-c4f2cc971636.png)

**Comment by radinamatic** [comment]
_transferred to #6016_

**Comment by radinamatic** [comment]
_transferred to #6015_

**Comment by indirectlylit** [comment]
@radinamatic I think this audit may be expanding beyond the scope of a single issue, which will make it a bit harder to resolve. We'll keep it open for now but I expect we'll need to break it up a bit

**Comment by radinamatic** [comment]
I was thinking the same thing @indirectlylit. 
I can separate each instance to a single issue if that helps...?

**Comment by indirectlylit** [comment]
recommendation:

1. Create one roll-up issue for all instances where something can get keyboard focus, but does not use the standard outline. (Please put all information in the issue description, not as comments)
2. Create new, independent issues for cases where something cannot get keyboard focus, or otherwise behaves strangely

**Comment by radinamatic** [comment]
Cleaned up the comments and opened new issues. This then becomes only about the `Change language` not being focusable, and I changed the title accordingly, hope that is OK.
