### ISSUE TITLE
Facility admin pages very slow with thousands of users

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6008]
### Observed behavior

Reports that on a server with ~8000 users, facility pages are sometimes giving errors and timeouts are occurring:

![image](https://user-images.githubusercontent.com/2367265/67884531-3be75200-fb03-11e9-840e-596f5c8b5d3b.png)

### Expected behavior

The user interface should remain responsive and not cause user-facing errors, even for very high numbers of users (to be defined).

We may also want to provide guidance to users on how to user Postgresql rather than SQLite

### User-facing consequences

Inability to administer server.

### Errors and logs

None on the backend. Waiting for info re: client

### Steps to reproduce

Presumably, create a server with tens of thousands of users and interact with the Facility tab

### Context

EC2 from AWS with the following specs:

* T3 Large:  2vCPU, 8 GB of RAM
* Runs on 2.5GHX Intel Processor

Kolibri 0.12.8

**Comment by KevinTripp** [comment]
Here is the chrome dev tools view of the page loading. It is one call that is getting a 504 error. 

![image](https://user-images.githubusercontent.com/2286110/67886957-c5594d00-fb20-11e9-92fd-d2f2a0c817c4.png)

Request URL: https://kolibri.connectedcorrections.com/api/auth/classroom/?parent=79f960e7d7afd0754776f9fcb04fe035&1572459020932=1572459020932
Request Method: GET
Status Code: 504 
Remote Address: 107.23.10.241:443
Referrer Policy: no-referrer-when-downgrade

**Comment by KevinTripp** [comment]
@indirectlylit This is blocking our rollout of Kolibri, even though we are working on a few workarounds.  What is the status of this issue?

**Comment by indirectlylit** [comment]
Hi @KevinTripp –

Sorry, we haven't had a chance to triage this issue yet. I'll update where once we've investigated the scope of a mitigating change.

**Comment by KevinTripp** [comment]
@indirectlylit Thanks, I appreciate the update.

Is it possible to create classes and modify what students are part of a class via the api?

**Comment by rtibbles** [comment]
Hi @KevinTripp this is possible - I am seeing if we can do a workaround here within the scope of 0.12.9 to avoid having to interact with the API directly.

What is the approximate number of classes that is being displayed on this page, so I can ensure that I am testing against the appropriate scale? Also, do you have a sense of how many coaches are assigned to each classroom on average?

**Comment by rtibbles** [comment]
Just as a follow up here - I've done some investigating, and this would be too risky to properly fix within the scope of 0.12.9, but we can do a fix within 0.13.0 (currently targeted for early December).

**Comment by KevinTripp** [comment]
@indirectlylit @rtibbles Thank you for expediting a fix into 0.13.0! For posterity  we have around 15 classes in the system and 0-1 coach per class. We are trying to fit all 30+ classes we have into the system.

**Comment by rtibbles** [comment]
That is not a lot - thanks for the detail, it really should not bork on that few classes.

**Comment by indirectlylit** [comment]
@KevinTripp: @rtibbles has added a change to 0.12.9 which may help mitigate this. Beta 3 includes this change. Would you mind testing to see if it helps?  (assets should be built and posted within an hour)

https://github.com/learningequality/kolibri/releases/tag/v0.12.9-beta3

**Comment by KevinTripp** [comment]
@indirectlylit Cool, let me see if I can get some resources to install the beta version.  We haven't encountered this issue on our UAT instance, so it will take time for us to validate the fix.

**Comment by KevinTripp** [comment]
The fix looks good on our uat instance.  We don't have a 1:1 user base for UAT and Prod so I'm not able to tell if it will resolve the issue.  We will likely push out the fix to Prod in the next few days depending on availability. I'll keep you posted on the resolution of the fix.

**Comment by indirectlylit** [comment]
thanks for the update

**Comment by KevinTripp** [comment]
@indirectlylit Sadly, the fix didn't resolve the issue on production.  The same issue and symptoms above are still occurring.  The network page in google looks the same.

We haven't tried to upgrade from sqlite to postgres yet.

Version:           0.12.9b3
OS:                Linux-4.14.109-99.92.amzn2.x86_64-x86_64-with-glibc2.2.5
Installer:         whl
Server:            Kolibri internal server
Database:          /home/ec2-user/.kolibri/db.sqlite3
Device name:       ip-10-134-40-27.ec2.internal
Free disk space:   32 GB
Server time:       Fri Nov 08 2019 12:43:55 GMT-0500 (Eastern Standard Time)
Server timezone:   UTC

**Comment by rtibbles** [comment]
Hrm, sorry to hear that @KevinTripp. Possible that it caused a speedup, but an insufficient one to prevent the network timeout.

**Comment by indirectlylit** [comment]
Okay – sounds like the full fix will have to wait until 0.13.0 after all

**Comment by KevinTripp** [comment]
@indirectlylit Got it, I appreciate the help so far on the issue!

**Comment by rtibbles** [comment]
@KevinTripp note that this was autoclosed because of a reference in the above pull request - we are happy to reopen if the issue persists!

**Comment by KevinTripp** [comment]
@rtibbles @indirectlylit Thanks for the heads up.  To make sure I can communicate back the status of this with the rest of my team I want to check a few things.  Outside of the hotfix, was another change made?  If so, how was the other change different than what was done in the hotfix?  Are you still slated to release 0.13.0 early in December?

I really appreciate the help on this! We are excited to move our students from ka-lite to kolibri, but right now that can't happen.  Since we aren't able to add classes or assign students to classes we aren't able to have teachers use the system.  The risk there is that teachers without assigned classes would see students at other, regulated, facilities.  That would be a breech of data for us. Our team doesn't feel moving forward with out deployments due to that risk.

I forget if I've asked this, Is it possible to create classes via the backend/API?

**Comment by rtibbles** [comment]
Yes, another change was made in 0.13.0 (as opposed to the hotfix that was released with 0.12.9).

It is possible to create classes via the API - but we don't currently have token based auth, so it's a bit tricky, as you have to set a session and CSRF cookie on the requests you are making.

You can do it from the browsable API from the browser though too at: `/api/auth/classroom`

**Comment by KevinTripp** [comment]
@rtibbles Cool, good to know about creating classes. I think we are already using  a CSRF token for the authentication. 

@indirectlylit  Is there a tentative date for the release of 0.13.0?

**Comment by indirectlylit** [comment]
@KevinTripp we are aiming for mid-December, before the holidays

**Comment by KevinTripp** [comment]
@indirectlylit Cool, I appreciate the info!

**Comment by KevinTripp** [comment]
@indirectlylit We installed .13 on our server this morning and the fix looks good.  Thank you for the help!

**Comment by indirectlylit** [comment]
very glad to hear - thanks for the heads up!

FYI, we'll be releasing a 0.13.1 patch in a week or two with some follow-up fixes
