### ISSUE TITLE
Improperly escaped interface strings

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6012]
### Observed behavior
On Device page: `Uncaught SyntaxError: missing ) after argument list` - caused by attempted bootstrapping of device strings into the page.

### Expected behavior
Strings should not escape their escaping!

### User-facing consequences
No translations on device page!

**Comment by indirectlylit** [comment]
duplicate :) https://github.com/learningequality/kolibri/issues/5981
