### ISSUE TITLE
Individual questions in detailed quiz and lesson reports not accessible by keyboard

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6016]
### Observed behavior
Individual questions in detailed quiz and lesson reports are not accessible by keyboard for both coach and learner users. The only element that gets the focus after the `Back` button is the `Show correct answer` checkbox.

![quiz-lesson-report-focus](https://user-images.githubusercontent.com/1457929/67910140-d0909500-fb81-11e9-9770-2446562b1f7e.gif)

However, on the lesson preview, questions are accessible by keyboard.

![lesson-preview-focus](https://user-images.githubusercontent.com/1457929/67910364-b30ffb00-fb82-11e9-9419-fbb1ac9f0530.gif)

### Expected behavior
Coaches and learners using keyboard must be able to access and review all the questions in the report.

### User-facing consequences
Inability to interact with the quiz report when using keyboard.

### Errors and logs
…

### Steps to reproduce
Open quiz or exercise in a lesson report and try to access any question after the first by keyboard.

### Context
- Kolibri version: current develop
- Operating system: Ubuntu 18.04
- Browser: both FF & Chrome

**Comment by bjester** [comment]
@radinamatic The most appropriate and quickest win here would be to make this operate similar to a `listbox`, so arrow keys would be used to navigate the question list and tab would move from the list to the "Show correct answer" checkbox. What do you think?

The other option I'm considering is refactoring this to be more like a `tabpanel`. I think that could make sense as clicking a question changes the URL, and right now there isn't any ARIA connection between the question list and the question content on the right side. That may be a significant amount of work though.

**Comment by radinamatic** [comment]
Thanks for investigating this, I was hoping that given that in the preview the questions are navigable by keyboard, there was a faster way to get that functionality back in the working exercise too.

I agree that the `tabpanel` looks like a more complete pattern, but I think we can do with the `listbox` basic navigability for the time being, to get this working for 0.13. 

We'll reevaluate later with @indirectlylit for which patch release to do the refactor that you propose.

**Comment by indirectlylit** [comment]
agreed with both. Mind opening a follow-up issue on the `tabpanel` suggestion, and this issue can be closed with the `listbox` strategy?
