### ISSUE TITLE
app bars in content management flows should conform to audit

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6021]
### Observed behavior

App bars in the content management flows do not conform to the conventions established in the [0.12.y audit](https://docs.google.com/document/d/1C7Gj_eQ2FV8adJPpB4PTnd1oJUQxIhpBXbM1aufCWwM/edit#)

For example:

![image](https://user-images.githubusercontent.com/2367265/68254976-d7376600-ffe0-11e9-9126-78baca601eb5.png)

### Expected behavior

Consistent use of color, available action, and text

### User-facing consequences

harder to learn app conventions

### Context

0.13.0 alpha

ref: https://github.com/learningequality/kolibri/pull/6018

**Comment by nucleogenesis** [comment]
@indirectlylit this seems stale - I recall that we put some effort into cleaning all of this up but cannot find a PR where all of it was applied.

I'm closing this - if @khangmach or others identify specific places where we're not abiding the design instructions we can create a new and targeted issue to resolve the specific issue

![screenshot-kolibri-beta.learningequality.org-2021.04.13-07_42_23.png](https://images.zenhubusercontent.com/60184d3dded61107db88cd6e/6e489d48-df59-49fa-ba07-813b977f6063)
