### ISSUE TITLE
confusion about how to toggle between bulk and granular import modes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6023]
### Observed behavior

The bulk and granular import modes are two states of the same page, but it's not easy to toggle between them. Clicking the <kbd>IMPORT MULTIPLE</kbd> button leaves you "stuck" in that mode.

The user is unlikely to see the ✕ turn into a ← in the app bar because they would be looking at the place on the screen they just clicked.
 
![import-multiple](https://user-images.githubusercontent.com/2367265/68258007-1fa75180-ffea-11e9-9964-a6db5411ecc8.gif)

### Expected behavior

After switching to 'bulk' mode, there should be some way to return to 'granular' mode in exactly the same location as the <kbd>IMPORT MULTIPLE</kbd> button.

### User-facing consequences

confusion about how to toggle between modes

### Context

0.13.0 alpha

ref: https://github.com/learningequality/kolibri/pull/6018

**Comment by khangmach** [comment]
Yeah this isn't noticeable in the implementation. Will adjust accordingly by transferring over the secondary btn to the second view

**Comment by indirectlylit** [comment]
this has been addressed
