### ISSUE TITLE
options should be aligned with header, not back link

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6024]
### Observed behavior

In many places in the Coach tools, the 'options' button is associated with the 'back' link:

![image](https://user-images.githubusercontent.com/2367265/68312275-abab8e80-0067-11ea-8291-e4194591a5c6.png)

### Expected behavior

The 'options' button should be associated with the thing it operates on, named in the header:

![image](https://user-images.githubusercontent.com/2367265/68312492-fcbb8280-0067-11ea-9d56-42a0634924fb.png)

### User-facing consequences

less clear expectations about what options might be available

### Context

0.12.x

**Comment by gianpaj** [comment]
This doesn't seem to be an issue any more (current develop branch ae47e83cc )

![127 0 0 1_8000_en_coach_](https://user-images.githubusercontent.com/899175/70871176-41eea080-1f94-11ea-8da2-593ce602ecb4.png)

**Comment by indirectlylit** [comment]
I believe you are correct - thanks for testing!
