### ISSUE TITLE
app bar linear loader appears below app bar

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6029]
### Observed behavior

Not sure how pervasive this is, but watch the linear loader on the app bar - it is below the app bar, over the page content:

![loader](https://user-images.githubusercontent.com/2367265/68333909-59319880-008e-11ea-9317-6608d0d2d8f2.gif)

### Expected behavior

loader is always attached to app bar

### User-facing consequences

minimal, but might look very broken if loading were to take longer

### Steps to reproduce

click 'enroll users', possibly with bandwidth throttling turned on

### Context

0.12.x

**Comment by jonboiser** [comment]
Should be fixed in #6465. Thanks @bransgithub! I looked around, and didn't see any other cases like this.
