### ISSUE TITLE
Design making lesson visibility toggle inactive until coach adds at least one resource

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6038]
### Observed behavior

Noted during the [testing](https://github.com/learningequality/kolibri/pull/5996#issuecomment-551200148) of #5966:

> should an empty lesson be allowed to be made visible to learners? Since it appears on learner side almost immediately after it's made visible, shouldn't the visibility toggle be inactive as a precaution, _until_ coach adds at least one resource? An empty lesson might be confusing to the learner... :thinking: 

![empty-lesson](https://user-images.githubusercontent.com/1457929/68415579-f70e8b80-0192-11ea-9ec8-956702b0b7ce.gif)

### Expected behavior
Lesson without resources should not be visible to learners.

### User-facing consequences
User confusion

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: develop branch after the #5966 is merged (0.13)
 * Operating system: all
 * Browser: all

**Comment by indirectlylit** [comment]
Updating this will require new strings and a bit of additional design.

Do we see this as critical for 0.13 or can it wait until the next release? My sense is that this is certainly nice to have, but doesn't affect core functionality or usability

@jtamiace @khangmach thoughts?

**Comment by jtamiace** [comment]
Maybe for a patch release? Doesn't seem absolutely critical imo

**Comment by indirectlylit** [comment]
it will have to wait until the next major release due to new strings, but that sounds fine to me

**Comment by rtibbles** [comment]
Immediate behaviour is obvious, but will need some user feedback to explain why it is disabled.

**Comment by rtibbles** [comment]
Closing in favour of https://github.com/learningequality/kolibri/issues/4608
