### ISSUE TITLE
apply json.dumps to all javascript output strings

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6044]
### Observed behavior

we should avoid

```python
"<script>console.log('{}')</script>".format(output_string)
```

### Expected behavior

we should always do

```python
"<script>console.log({})</script>".format(json.dumps(output_string))
```

### User-facing consequences

There might be edge cases where the value of the string will create broken javascript. This can prevent the entire page from loading, as we saw in #5981

### Context

0.12.x

**Comment by jonboiser** [comment]
I looked through all the relevant Python code and it seems like we do this everywhere, except possibly this one spot. Should we be passing `urls='","'.join(urls)` through `json.dumps` as well?

https://github.com/learningequality/kolibri/blob/5eaeaee31d5e2b3a810662129ed0dae3d9204bc8/kolibri/core/webpack/hooks.py#L408-L414

**Comment by rtibbles** [comment]
Might be safer - we would need to change this to something like:
```
 + [ 
     '<script>{kolibri_name}.registerKolibriModuleAsync("{bundle}", JSON.parse({urls}));</script>'.format( 
         kolibri_name="kolibriCoreAppGlobal", 
         bundle=self.unique_id, 
         urls=json.dumps(json.dumps(urls)), 
     ) 
 ] 
```
Or whatever the appropriate double `json.dumps` code is?

**Comment by jonboiser** [comment]
I think the single `json.dumps` looks right, since the code that gets interpolated results in the urls argument being evaled to an array.

In python repl:
```
>>> json.dumps(json.dumps(["a","b","c"]))
'"[\\"a\\", \\"b\\", \\"c\\"]"'

>>> json.dumps(["a","b","c"])
'["a", "b", "c"]'

```

In Node repl:
```
> JSON.parse('"[\\"a\\", \\"b\\", \\"c\\"]"')
'["a", "b", "c"]' # string literal
> JSON.parse('["a", "b", "c"]')
[ 'a', 'b', 'c' ] # array literal
>
```

**Comment by rtibbles** [comment]
The rationale for the double `json.dumps` (which needs a bit more than I put) is described here: https://github.com/learningequality/kolibri/pull/6020/files?file-filters%5B%5D=.py#r344478274

And is still what we are using here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/webpack/hooks.py#L276

The extra `'` wrapping when parsing in the Node repl is what this is meant to avoid, as doing a naive dump to a Javascript compatible string has caused us errors in the past.

However, I tested this out in my Node repl and it gave errors, so there might still be soemthing I am missing.

**Comment by jonboiser** [comment]
It's probably best not to mess with this, if it's working. It looks like all of the other places we manually construct template code are safe.

**Comment by rtibbles** [comment]
Yeah, this specific instance is only for arrays of URLs, which is a significantly more constrained data set than the other instances we've had to deal with.
