### ISSUE TITLE
Update Gherkin stories for upgrade of Vodafone - Instant Schools from v0.6.3

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6064]
### Observed behavior
Found out that we need to update one or more Gherkin scenario/s during integration testing of upgrade from Kolibri v0.6.3 to v0.12.9b2 for Vodafone - Instant Schools under Ubuntu 16.04:

**Super admin change profile information**

1. no `username` field - https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/super-admin/super-admin-change-profile-information.feature#L10

**Super admin profile command**

1. no `"xxxxxxxx_xxxxxx_requests_performance.csv"` file generated after I followed https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-profile-command.feature#L13

**Super admin benchmark command**

1. change `operative` to `operating` - https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-benchmark-command.feature#L6

**Super admin cancel import channel**

1. Change from `And I don't see the content channel whose import has been canceled` to `And I may see or may not see the content channel whose import has been cancelled because the import may have completed the import of small-sized sub-topic/s.`
at https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-cancel-import-channel.feature#L29 and at https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-cancel-import-channel.feature#L55

**Super admin import more from content channel**

1. Change from `And I see the *Select content from '<drive>'* page with the list of available content *Channels* on the <drive> local drive` to `And I see the *Select content* page with the list of available content *Channels* on the <drive> local drive`.  Notice that the `from '<drive>'` is missing at the modal already.  I don't know if this is a bug or not but I'm adding it here (see attached screentshot).  See https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-import-more-from-content-channel.feature#L52
![kolibri--v0 12 9b2--import more content from device](https://user-images.githubusercontent.com/175580/68927371-969ad200-07c2-11ea-9135-d161e968e35b.gif)

**Super admin find user**

1. Cannot run `kolibri manage generateusers` on this https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/super-admin/super-admin-find-user.feature#L4 - filed a related issue at https://github.com/learningequality/kolibri/issues/6066

**Super admin change facility settings**

1. At https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/super-admin/super-admin-change-facility-settings.feature#L17 - user still cannot edit their username even when `Allow learners and coaches to edit their username` checkbox is enabled.

1. At https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/super-admin/super-admin-change-facility-settings.feature#L46 - user cannot login without a password even when `Allow learners to sign in with no password` was checked.

1. Change `*Continues as a guest*` to `*Access as Guest*` At https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/super-admin/super-admin-change-facility-settings.feature#L67

**Learner engage lesson**

1. Change `*Started*` with `*In Progress*` in multiple locations at https://github.com/learningequality/kolibri/blob/86a13eefc0fdc1128be4b1aeec55217fd0f96e62/integration_testing/features/learner/learner-engage-lesson.feature

**Learner engage quiz**

1. Change `*Started*` with `*In Progress*` in multiple locations at https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/learner/learner-engage-quiz.feature

**NOTE**: Will update this if there are other Gherkin scenario files that may need revision/s.

### User-facing consequences
N/A

### Errors and logs
N/A

### Steps to reproduce
N/A

### Context
Kolibri installer: Kolibri installer v0.12.9b2
OS: Ubuntu 16.04
For: Integration Testing for Upgrade from v0.6.3 to v0.12.9b2 for use in Vodafone - Instant Schools

Integration Testing Spreadsheet: https://docs.google.com/spreadsheets/d/1vEiNHzJ63kXWWkoC5yyDvnQsmdj6GboU7AycKAbsBs8/edit?pli=1#gid=312561886

/cc: @radinamatic

**Comment by indirectlylit** [comment]
removing from 0.12.9 release so it's not a blocker

**Comment by rtibbles** [comment]
This upgrade has occurred, so I am assuming that this work has been done or is no longer needed.
