### ISSUE TITLE
tracking of content resource visibility in exported channels

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6067]
# Observed behavior

In the current work on 0.13.0 content management, we're beginning to treat duplicate resources 
individually, so that the user can import or delete them separately. See for example:

* https://github.com/learningequality/kolibri/issues/4082
* https://github.com/learningequality/kolibri/issues/4549

This new 'visibility' tracking information is stored in the Kolibri database, but does not get persisted when a user exports the content to disk.

### Expected behavior

Users may expect content exported to disk to retain the visibility settings, if the export process was intended as a form of curation. While this might not always be true, based on user feedback so far that seems to be the dominant expectation.

Because content databases are immutable, in order to implement this, we would need to add some kind of manifest file that travels along with the content and database file and specifies visibility. This could either be a plain-text file, JSON, or a SQLite DB, for example.

### User-facing consequences

Intentional user decisions made during the "export as curation" process are lost.

### Context

0.13.0 alpha 0

**Comment by indirectlylit** [comment]
cc @rtibbles made this a P2 nice-to-have for 0.13.0

**Comment by rtibbles** [comment]
This has begun to be addressed in #9460 and will be fixed by #9467.
