### ISSUE TITLE
usability issues related to accessing the task manager

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6068]
### Observed behavior

**Mulitple primary buttons and bottom bar on main page**

In the current implementation, the primary landing page for resource management has both a primary <kbd>Import</kbd> button and a primary <kbd>View tasks</kbd> button.

![image](https://user-images.githubusercontent.com/2367265/68957831-d947b480-0798-11ea-9d95-3c10b1bbcab9.png)

According to [our conventions](http://kolibribeta.learningequality.org/design/components/buttons#visualstyles):

> There should only be one primary button visible at a time, and it should be a common or default action.

According to @khangmach this is left over from an older design. These might be the latest [figma mockups](https://www.figma.com/file/eJd6xQiNgebzzRWn2XDDS92R/0.13-content-import?node-id=64%3A234)?

The bottom bar is used outside of a modal-like page. Bottom bars are more commonly used in situations where the user is in the middle of some full-screen-modal type activity.

**Getting 'stuck' in import screen**

It is difficult to toggle back and forth between the ongoing tasks and the current page - once you view the task manager and then return, you're stuck deep in the import page:

![task-manager](https://user-images.githubusercontent.com/2367265/69011299-3f6a3e00-0937-11ea-9c7c-232fa5cc1f92.gif)

### Expected behavior

* It should be possible to access the task manager more easily
* After initiating an import, I would expect to be taken to the tasks page and then back to the main channel. I would not expect to remain on the channel import page

### User-facing consequences

inconsistency in UI conventions and challenges navigating

### Context

0.13.0 alpha 0

**Comment by khangmach** [comment]
RE: Getting 'stuck' in import screen

forcing the user to be be redirected to a task modal for every task initiated seems incredibly annoying to encounter for granular selections. I would strongly prefer to be neutral and leave it to the user to choose whether or not they want to view their tasks or keep on selecting content/channels (I've taken drive's approach for this design). 

For making the task manager more accessible, we can further customize the snackbar to have a dismiss "X" icon and have the behavior of the snackbar change to be ever-present once a task is initiated. Let's see how behaviors feel at the hack session
