### ISSUE TITLE
use standard CoreTable and enter/leave transitions for task manager

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6072]
### Observed behavior

current table view is slightly non-standard:

![image](https://user-images.githubusercontent.com/2367265/68966779-e8386200-07ac-11ea-9fc0-3ec30f657d48.png)

### Expected behavior

* Standard `CoreTable` behavior with row-dividers, right button alignment, and secondary button style
* `transition-group` enter/leave transitions

### User-facing consequences

inconsistent UI

### Context

0.13.0 alpha

**Comment by khangmach** [comment]
Row divides and the secondary button styles should be reflected in figma

**Comment by indirectlylit** [comment]
flat button style is still primary: 

![image](https://user-images.githubusercontent.com/2367265/69160726-0c9b8380-0ab8-11ea-9406-ff6f7256cf7c.png)
