### ISSUE TITLE
New Github issue templates

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6086]
### Observed behavior

Note: This is about a new feature that Github has launched for differentiated issue templates - not about our current single issue template

Issue reports can have fewer oddly deleted fields and perhaps better and more concise inputs. Not least, already active developers may bother with fewer irrelevant headlines that are semi-skipped, perhaps setting a bad example.

I'm hoping we can take the time to chat a bit about what differentiated issue templates we'd like to have.

Example:

https://github.com/pypa/pip/issues/new/choose

Example source:

https://github.com/pypa/pip/tree/master/.github/ISSUE_TEMPLATE

Documentation:

https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

### Expected behavior

I could suggest the following issue templates:

1. Bug report
1. UX issue
1. Feature request (with a template that concretely focuses on becoming part of the community and creating the feature yourself)
1. Internal issue report
1. Devops and release workflows

### User-facing consequences

We can hopefully encourage more/better issues and contributions

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

n/a

**Comment by benjaoming** [comment]
Closing this, as I gather from @indirectlylit that there isn't evidence that the current issue template causes _issues_ :)

**Comment by indirectlylit** [comment]
for posterity:

I imagine this could be a useful addition in the future, but I haven't experienced a need for it so far.

What would help with some pain points though would be something like vue.js does, so that contributors don't need to understand how Markdown or Github work in detail: 

https://github.com/vuejs/vue/issues/new
