### ISSUE TITLE
import is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6096]
### Observed behavior

trying to import doesn't work:

![import](https://user-images.githubusercontent.com/2367265/69167242-a0724d00-0ac2-11ea-9a37-a21040f7f812.gif)

### Expected behavior

import should work

### User-facing consequences

cannot import

### Errors and logs

none observed

### Steps to reproduce

unsure. it happened during all imports, but then I cleared my `KOLIBRI_HOME` folder and things started working again

### Context

0.13.0 alpha 3

**Comment by indirectlylit** [comment]
I tried clearing my entire DB and content, and things started working again.

**Comment by jonboiser** [comment]
This is a new class of bug to me. The task seems to finish immediately, but doesn't transfer any files.

Other things I've seen

1. Task starts but never goes from Queued to Running
1. Task goes to Running, but stays at 0% indefinitely

**Comment by radinamatic** [comment]
That's exactly what was happening on #6049, see my [comment](https://github.com/learningequality/kolibri/pull/6049#issuecomment-555021591). @rtibbles said he had an inkling what was the issue, but is in the air atm probably...

**Comment by rtibbles** [comment]
Yes, this was not a performance improvement, but rather a bug induced by including the importability annotation in the content import task that I had not yet resolved on the above PR, will fix ASAP.

**Comment by indirectlylit** [comment]
sorry for merging the PR before it was ready!
