### ISSUE TITLE
partially-completed transfers do not show how much succeeded

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6100]
### Observed behavior

After canceling a transfer, metadata does not give any indication that some of the content was successfully imported and is now on the device:

![completion-after-cancel](https://user-images.githubusercontent.com/2367265/69189446-6158f180-0aec-11ea-9fdb-58f1c783c36e.gif)

### Expected behavior

metadata should indicate how much content was successfully imported before the transfer stopped

### User-facing consequences

confusion about what actually happens after a transfer gets canceled. Is everything deleted, or did some resources get saved?

### Context

0.13.0 alpha 0

**Comment by rtibbles** [comment]
Can handle this in the same way as #6098 by updating the task metadata after cancellation.

**Comment by indirectlylit** [comment]
do we in fact need new strings for this?

**Comment by rtibbles** [comment]
Could do it without by just changing the numbers - do we use different strings for when the job is finished versus in progress?

**Comment by jonboiser** [comment]
When a task is completed/canceled, we don't show a progress bar. We can both keep the progress bar when the task is canceled (so we have a stopped progress bar at e.g. 75%) and cobble together some copy from the existing strings to display the completed # resources/filesize

**Comment by indirectlylit** [comment]
chatted with @jonboiser and @khangmach. @rtibbles will it be possible to use these strings?

For ongoing transfers and failures/cancelations:

> 50 of 100 resources (10MB of 20MB) imported

```
      importPartialRatio:
        '{currentResources} of {totalResources} {totalResources, plural, one {resource} other {resources}} ({currentSize} of {totalSize}) imported',
      exportPartialRatio:
        '{currentResources} of {totalResources} {totalResources, plural, one {resource} other {resources}} ({currentSize} of {totalSize}) exported',
      deletePartialRatio:
        '{currentResources} of {totalResources} {totalResources, plural, one {resource} other {resources}} ({currentSize} of {totalSize}) deleted',
```


For successes:

> 100 resources (20MB) successfully imported



```
      importSuccess:
        '{totalResources} {totalResources, plural, one {resource} other {resources}} ({totalSize}) successfully imported',
      exportSuccess:
        '{totalResources} {totalResources, plural, one {resource} other {resources}} ({totalSize}) successfully exported',
      deleteSuccess:
        '{totalResources} {totalResources, plural, one {resource} other {resources}} ({totalSize}) successfully deleted',
```

**Comment by rtibbles** [comment]
Seems fine to me.
