### ISSUE TITLE
discrepancy between string in source and crowdin variables

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6110]
### Observed behavior

Crowdin and the source code may be out of sync on a few strings

Ref: https://github.com/learningequality/kolibri/pull/6111/files#diff-85b8dc952a3af3b9572437374d3e5278 in NewChannelVersionPage.vue:

![image](https://user-images.githubusercontent.com/2367265/69565903-bb353d80-0f6a-11ea-95d6-88048ec919c2.png)

![image](https://user-images.githubusercontent.com/2367265/69565914-bf615b00-0f6a-11ea-98ab-d32109457f5e.png)

### Expected behavior

Strings in crowdin and github should be the same, and use the same parameters

### User-facing consequences

some strings will not render correctly

### Steps to reproduce

We need to double-check that these strings work as expected

### Context

0.13.0 alpha 4

**Comment by radinamatic** [comment]
Just noticing this now, what exactly is the issue (if still extant)?

**Comment by indirectlylit** [comment]
@radinamatic thanks for the reminder

@jonboiser sorry about this - would you mind taking a look?

**Comment by jonboiser** [comment]
The messages on the crowdin page (for Hindi and French at least) match the messages in the code for the two examples in the OP, and every other message with variables in NewChannelVersionPage

**Comment by indirectlylit** [comment]
great, thank you
