### ISSUE TITLE
learner progress not propagated all the way up topic tree

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6112]
### Observed behavior

child topic:

![image](https://user-images.githubusercontent.com/2367265/69362951-5fa24180-0c44-11ea-9aff-cb3fdfb9640b.png)

parent topic:

![image](https://user-images.githubusercontent.com/2367265/69362963-6630b900-0c44-11ea-84b1-817fe5a8e64e.png)

### Expected behavior

progress is propagated all the way to the root

### User-facing consequences

missing waypoints on finding in-progress and completed resources

### Steps to reproduce

* go deep in a topic tree and make progress on an exercise
* navigate up the topic tree towards the root

### Context

0.13.0 alpha 3

**Comment by rtibbles** [comment]
Does this persist if you refresh?

**Comment by indirectlylit** [comment]
yes

**Comment by rtibbles** [comment]
Curious.

**Comment by rtibbles** [comment]
Note that this should be easier to do now once #7431 is merged, as all content nodes loaded into the frontend now have ancestor information associated.

**Comment by nucleogenesis** [comment]
This issue is no longer an issue - see https://kolibri-beta.learningequality.org/en/learn/#/topics/1d8f6d84618153c18c695d85074952a7 when logged in as `learnerdemo/pass` - there are all sorts of examples similar to this there.

**Comment by nucleogenesis** [comment]
@indirectlylit -- is the expectation that the in-progress icon show on the Channel card as well? 

Currently it propagates up to through all topic cards - but not to the channel card (at the Learn root).

I'll reopen until I know for sure that this is the requirement (cc @jtamiace )

**Comment by indirectlylit** [comment]
My personal expectation is definitely that it would show up on the channel cards.

If there was a technical or UX reason why we didn't implement that originally, I don't recall what it was.

**Comment by rtibbles** [comment]
I don't think there's any technical reason not to - just a matter of querying for progress on the root topic of the channel.

**Comment by nucleogenesis** [comment]
The answer to the question was in the code - once the progress was properly propagated to the front-end the icons showed up on their own! :)

**Comment by rtibbles** [comment]
Also possible that due to this issue: https://github.com/learningequality/kolibri/issues/5041 - this issue may still manifest for large topics.
