### ISSUE TITLE
profile name scroll arrow unexpected behavior

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#6122]
![image (6)](https://user-images.githubusercontent.com/5150483/69453635-2d164880-0d19-11ea-8448-94ce4d8ab9a7.png)

Chrome Version 77.0.3865.75 (Official Build) (64-bit) on Ubuntu 14.04

instantschools-testsite.learningequality.org

Ask Liz for superuser password

**Comment by nucleogenesis** [comment]
@indirectlylit This is targeted for 0.13 - but we need this for the Vodafone build so I'll be working on it in 0.12 and will need another beta cut for that when it is resolved.

**Comment by indirectlylit** [comment]
sounds good! I'll adjust the milestone

**Comment by indirectlylit** [comment]
@nucleogenesis tried for a couple days trying to reproduce this and was unable to. There seemed to be something slightly different between running it in production through google cloud versus in production locally.
