### ISSUE TITLE
not possible to 'complete' a slideshow

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6123]
### Observed behavior

Reported by @jayoshih during the beta1 bug bash:

> Not getting "completed" on slideshows (just shows as being in progress)
> 
> http://kolibribeta.learningequality.org/en/learn/#/topics/c/94f479f45b0d5ce7b132b3cfadc55573

### Expected behavior

Should be possible to 'complete' a slideshow by spending a minimal amount of time on each slide

### User-facing consequences

implications for coach and learner  tracking of progress

### Steps to reproduce

…

### Context

0.13.0 beta1

**Comment by nucleogenesis** [comment]
Addressed in #6226
