### ISSUE TITLE
invalid tasks can get sometimes appear in task list response

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6124]
### Observed behavior

Observed by @jonboiser that sometimes tasks will appear in the API response that seem to be lacking basic information, e.g. channel ID or type.

We have some client-side validation to avoid showing these to users, but it means that over time the task list gets cruft added to it, which may be an indication of a memory leak or other problems.

### Expected behavior

all tasks returned from the server should be valid

### User-facing consequences

risk of memory leak

### Errors and logs

none

### Steps to reproduce

unknown

### Context

0.13.0 beta1

**Comment by rtibbles** [comment]
This could also be pingback and vacuum tasks that are periodically scheduled into the task queue.

**Comment by indirectlylit** [comment]
@jonboiser does this have user-facing impact? I'll remove from 0.13.0 if not...

**Comment by jonboiser** [comment]
The examples I've seen so far don't have any user-facing impact.

**Comment by vkWeb** [comment]
The invalid looking task that is returned is indeed the ping scheduled job as @rtibbles said. 

Recently, we assigned constant job_ids to these schedules jobs, `0` was assigned to the ping job and `1` was assigned to the vacuum job. 

Looking at the database we can see that the ping job gets completed and sticks on the jobs table that gets returned when GET API is called. 

So, there isn't any memory leak. Hence, this issue can safely be closed.

![image](https://user-images.githubusercontent.com/26724128/115541074-55aec300-a2bc-11eb-9f31-5671ec0332a3.png)

**Comment by jonboiser** [comment]
@vkWeb Sounds good to me. Thanks for looking into this!
