### ISSUE TITLE
task progress counts might be overestimated due to duplicate resources

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6141]
### Observed behavior

From @rtibbles in #6132

> My main concern is that duplication may throw off the totals here for the resource counts, and it could look like not everything has imported when it actually has.

### Expected behavior

* Counts should be accurate if possible
* If not possible, we should design around the problem by being less precise

### User-facing consequences

discrepancy between task manager and actual counts

### Steps to reproduce

…

### Context

0.13.0 beta 1

**Comment by rtibbles** [comment]
I think this should be resolved by moving to non-duplicate counts everywhere - if we see a discrepancy we should open a new issue precisely describing it.
