### ISSUE TITLE
follow-up from 6105

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6144]
follow-up from comments in https://github.com/learningequality/kolibri/pull/6105

The primary learner-facing items were:

1. use `KTooltip` rather than a `title` attribute
2. ~increase print margins to 3/4"~

There were also a few minor code comments, which are not blockers but might also be addressed

**Comment by bjester** [comment]
@indirectlylit I'm not entirely sure what is expected by "increase print margins to 3/4". The user has control over the actual print margins in the print dialog.

**Comment by indirectlylit** [comment]
Hm, that's interesting. I was experimenting with this in the context of "print to PDF" on Chrome, so unsure if that changes my perspective (I understand that other flows and browser will behave differently).

However, typically a PDF has some built-in margins, in addition to the margins that can be set during printing. 

In-doc margins:

![image](https://user-images.githubusercontent.com/2367265/69589285-775d2b00-0fa0-11ea-8256-7fd2fcbd5b27.png)

Chrome's print window has margin settings hidden by default, under 'More settings'. Once shown, the default value is "minimum". MacOS native print dialog doesn't actually show margins, but does have a "scale" which by default is 100%. (It's not totally clear to me what "scale" means for fluid webpages being converted to a fixed paper size...)

| chrome | macos |
|--|--|
|  ![image](https://user-images.githubusercontent.com/2367265/69589486-12ee9b80-0fa1-11ea-8150-ee6ca714c217.png)  | ![image](https://user-images.githubusercontent.com/2367265/69589450-f3f00980-0fa0-11ea-86bd-5b3c0d091f6d.png) |

So anyways... at least on Mac, my sense it that margin control happens by default in the document. If the user wishes they can add _additional_ margins using the print dialog, but my guess is most users will not do this.

**Comment by radinamatic** [comment]
Firefox has 1 inch margins by default, but leaves to the user to set them separately in the *File > Page setup* menu, along with other options:

![2019-11-26_1-38-06](https://user-images.githubusercontent.com/1457929/69589941-27a55080-0fee-11ea-95e2-8f325a3540bd.png)

**Comment by bjester** [comment]
@indirectlylit I believe Chrome will remember what you set for `Margins`, so the value `Minimum` I'm guessing is something you've used previously. There is in fact a `Default` option for `Margins`, which I assume is truly the default (as it is for me) and not `Minimum`.

**Comment by indirectlylit** [comment]
okay sounds good - let's skip the margins!
