### ISSUE TITLE
Add more helpful strings for CSV export columns

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#6151]
Follow up on https://github.com/learningequality/kolibri/pull/6147

Since the CSV export feature was added after string freeze, we didn't have total flexibility in structuring CSV exports that may require additional columns and thus additional user strings. This is to follow up on the specific reports that could use more specific strings for the CSV export headers.

For example, some report tables describe learner status as "X learners have not started" and "Completed by X of Y learners". In the CSV export, the single column that describes these learner tallies becomes multiple columns with quantities for each status, so specific strings for these columns could be helpful.

With the flexibility to add strings, it's the developer's discretion to add more specificity or to restructure exported columns for optimal detail.

### Context

Target: next 0.13.x patch

**Comment by indirectlylit** [comment]
Unfortunately we can't add in a patch because we generally don't generally do translation passes on patch releases/ 

However, after your work gets merged from `0.13.x` to `develop`, we can add the strings there and they'll get used in `0.14.x`.

I'll update the milestone here accordingly

**Comment by bjester** [comment]
Ah I didn't remember that was the case. I thought we could add strings for patch releases :man_facepalming:

**Comment by indirectlylit** [comment]
we did it once during 0.12, but that was a special case

**Comment by indirectlylit** [comment]
On the other hand, we will often add new _languages_ or updates to existing translations during patch releases. Just no new source strings

**Comment by jonboiser** [comment]
Changes to be made:

* For assignments, `Recipients (1)` will become `Recipient type`, `Recipients (2)` will be `Recipients`. If an assignment has both individuals and group assignees, the recipient type will be `Groups and individuals`, other wise `Groups` or `Class`. If the recipient is the (Entire) class, `Recipients` cell will have the classroom name

**Comment by indirectlylit** [comment]
Sounds good. We should make sure to mention these in the changelog in case anyone is scripting against the exports (unlikely but possible)
