### ISSUE TITLE
Points and 'Next resource' snackbars not appearing when learner/guest finishes viewing the video

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6153]
### Observed behavior
Encountered while [updating the Gherkin scenarios](https://github.com/learningequality/kolibri/pull/6135/files#r350267987) for the upcoming integration testing. 
0.12 version had a short lasting snackbar informing the learner that they have been granted 500 points, and inviting the guest to create account so they can accumulate points, followed by the *Next resource* snackbar remaining visible until the user clicks on it or closes it. Both are visible on our kolibridemo running 0.12.9, and missing on the `release-v0.13.x` dev branch.

### Expected behavior

This gherkin story should pass, as well as updates mentioned in link above:

https://github.com/learningequality/kolibri/blob/develop/integration_testing/features/learner/learner-engage-content-channels.feature

### User-facing consequences

Learners are not encouraged to proceed

### Steps to reproduce
View video as a learner and guest.

### Context
 * Kolibri version 0.13.x dev branch
 * Operating system: Ubuntu 18.04
 * Browser: FF & Chrome

cc @indirectlylit @jtamiace

**Comment by bjester** [comment]
It looks like a `sessionInitialized` event isn't being fired from the content renderer any more, which causes a handler to go un-fired that sets whether the content was incomplete when the user started.

**Comment by rtibbles** [comment]
Should be fixed in #6163
