### ISSUE TITLE
'Next steps' and 'Resume' sections missing from Learn > Recommended

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6155]
### Observed behavior
Encountered while [updating the Gherkin scenarios](https://github.com/learningequality/kolibri/pull/6135/files#r350268855) for the upcoming integration testing. 
0.12 version had both 'Next steps' and 'Resume' sections (visible on our kolibridemo running 0.12.9 on the right), but are missing on the `release-v0.13.x` dev branch (left window below).

![2019-11-26_23-07-09](https://user-images.githubusercontent.com/1457929/69677057-5c72df80-10a2-11ea-8f27-736d54d78872.png)

### Expected behavior

Next steps and Resume should both be available from the 'Recommended' page

### User-facing consequences

Less helpful guidance, missing features

### Errors and logs

N/A

### Steps to reproduce

View *Learn > Recommended* as a learner.

### Context

 * Kolibri version 0.13.x dev branch
 * Operating system: Ubuntu 18.04
 * Browser: FF & Chrome

cc @indirectlylit @jtamiace

**Comment by jtamiace** [comment]
I'm not aware of this feature being intentionally removed

**Comment by jtamiace** [comment]
I would argue that, although all sections on this page are not useful, the ones removed are the most useful of the non-useful

**Comment by rtibbles** [comment]
It seems like `Resume` has been accidentally renamed to `Recommended`: https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/plugins/learn/assets/src/views/RecommendedPage.vue#L47

Next steps should still be appearing - possible that a backend change has caused the returned values to be empty.

**Comment by indirectlylit** [comment]
> It seems like Resume has been accidentally renamed to Recommended

change here

https://github.com/learningequality/kolibri/commit/74074013ac512e908c8a640f8e2c457b1b943e56#diff-24ca2bd7995ee4b7af179b6bc96bac78

**Comment by bjester** [comment]
I now have `Next Steps` appearing for me. I wonder if https://github.com/learningequality/kolibri/pull/6159 and https://github.com/learningequality/kolibri/pull/6163 affected that?

**Comment by mrpau-richard** [comment]
I have the same issue the `Next steps` and  `Recommended` are not showing on Chrome(78.0)
![Screen Shot 2019-11-29 at 10 34 36 AM](https://user-images.githubusercontent.com/8663934/69839884-5d6b6300-1294-11ea-803c-7010d8a728d8.png)
