### ISSUE TITLE
make sure we don't overload SQL variables pk__in and id__in

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6157]
### Observed behavior

We've had previous instances of hitting the maximum variable limit for SQLite, and according to @rtibbles these can be caused by `pk__in` and `id__in` filters (cc @ralphiee22)

For example, see 

https://github.com/learningequality/kolibri/blob/b751754f79c23990515fa6ebf24d1b3029f57f13/kolibri/core/content/utils/import_export_content.py#L56-L58

### Expected behavior

ensure we don't hit max vars

### User-facing consequences

crashed server

### Steps to reproduce

unknown

### Context

0.13.0 beta 2

**Comment by indirectlylit** [comment]
see also this suggestion by @bjester:

https://github.com/learningequality/kolibri/pull/6154#issuecomment-558884477

**Comment by ralphiee22** [comment]
https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/mixins.py#L53
Mixin which bypasses the need to use `pk__in` and `id__in`, by passing in the list of ids inline and avoiding parameterized queries.

**Comment by indirectlylit** [comment]
@ralphiee22 anything else needed on this issue?

**Comment by rtibbles** [comment]
I think we just need to do a quick audit for these and then replace with the helper above where relevant.
