### ISSUE TITLE
Device Setting -> Landing Page radio buttons are not usable

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6162]
### Observed behavior

See http://kolibribeta.learningequality.org/en/device/#/settings

The Radio button for "Sign-in Page" is not usable when setting the "Landing page" option.

### Expected behavior

Radio button control is usable and the setting is changed after clicking save

### Context

Kolibri 0.13 beta 3

**Comment by radinamatic** [comment]
Still extant on 0.13.0b3.

**Comment by indirectlylit** [comment]
ref: https://www.notion.so/learningequality/Updates-to-Kolibri-settings-f374a937f08248848f6c8399c53556a1
