### ISSUE TITLE
Kolibri server not starting

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#6165]
### Observed behavior
The kolibri server is not starting when entered the ip 127.0.0.1:8008. 
![Screenshot from 2019-11-28 10-20-48](https://user-images.githubusercontent.com/8583367/69778050-d7361a80-11c8-11ea-91f8-9a5f0529d24a.png)

### Expected behavior
The server should start and show the kolibri login page

…

### User-facing consequences

Teachers will not be able to conduct classes

### Errors and logs

[kolibri.txt.tar.gz](https://github.com/learningequality/kolibri/files/3899893/kolibri.txt.tar.gz)

### Steps to reproduce
This was a sudden behaviour. Attached logs for reference, which show some exceptions. The server was working fine till yesterday.

### Context

 * Kolibri version 12.9
 * Operating system Ubuntu 16.04
 * Browser Chrome

**Comment by miyer03** [comment]
Could this be possible because I tried opening the 13.0 beta server where I had 12.9 installed and running. I uninstalled and installed Kolibri from PPA and 13.0b3 got installed

**Comment by jredrejo** [comment]
@ralphiee22 it's an iceqube issue, could it be due to the version mix @miyer03  comments?

**Comment by miyer03** [comment]
@jredrejo just to clarify I tried to open the Online beta server to check 13.0 beta3 after which when I tried opening 12.9 installed in my system, it gave this issue.

**Comment by jredrejo** [comment]
@miyer03 0.13.0 does delete some fields in one of the tables in your database. Going back to 0.12.9 afterwards using the same databasse is not possible for sure.

**Comment by indirectlylit** [comment]
There should be a backup of the database in `~/.kolibri` which would allow you to downgrade again.

I'll add a [caution](https://github.com/learningequality/kolibri/wiki/0.13.0-beta-testing#caution) on the beta release page noting this.

**Comment by indirectlylit** [comment]
Closing because the issue was due to a downgrade.

@miyer03 let us know if you need help restoring the previous DB

**Comment by rtibbles** [comment]
@jredrejo yes - the iceqube storage schema changed between 0.12.x and 0.13.x, so a downgrade would cause issues.
