### ISSUE TITLE
Device setting change for 'Learners should only see resources assigned to them in classes' not saved

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6167]
### Observed behavior
Reports as saved inline, but as soon as the admin navigates to a different subtab and returns, checkbox is unchecked again.

![Learners should only see resources assigned to them in classes](https://user-images.githubusercontent.com/1457929/69836486-5ff49b00-1249-11ea-8700-cf2e69b781fd.gif)

Maybe just not active in `kolibri_0.13.0b3`?

### Expected behavior
Setting change correctly saved.

### User-facing consequences
Inability to use the feature.

### Errors and logs
Nothing observable in the console.

### Steps to reproduce
Change the `Learners should only see resources assigned to them in classes` device setting, navigate away and return.

### Context
 * Kolibri version: kolibri_0.13.0b3-0ubuntu1
 * Operating system: Ubuntu 16.04
 * Browser: both FF & Chrome

**Comment by indirectlylit** [comment]
this functionality is not yet implemented

**Comment by indirectlylit** [comment]
ref: https://www.notion.so/learningequality/Updates-to-Kolibri-settings-f374a937f08248848f6c8399c53556a1
