### ISSUE TITLE
Items in 'Birth year' <select> drop-down are not visible

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6168]
### Observed behavior
Issue is problematic when **creating account** and navigating by keyboard in Firefox, as many options in the drop-down are hidden inside the container, and the user is unable to see where the current focus is. 

![select](https://user-images.githubusercontent.com/1457929/69836797-96331a00-124b-11ea-87ab-df24c9ac2666.gif)

On Chrome the issue is not extant, as the `<select>` options in focus always seem to be visible, even though it remains inside the container, and partially occluded.

### Expected behavior
Sighted keyboard user must see which year in the drop-down is currently in the focus.

### User-facing consequences
Inability to provide demographic data.

### Steps to reproduce
Try to select the year navigating by keyboard.

### Context

• Kolibri version: kolibri_0.13.0b3-0ubuntu1
• Operating system: Ubuntu 16.04
• Browser: Firefox 70, but not Chrome

**Comment by indirectlylit** [comment]
Updated to remove references to z-order.

cc @jtamiace this relates to having a select box at the bottom of a scrolling window :(

**Comment by indirectlylit** [comment]
one thing that's very strange here is that the inner box is scrolling instead of the outer box, as shown below. Fixing this might help with the problem:

![image](https://user-images.githubusercontent.com/2367265/69923878-bdad0100-145c-11ea-8ce3-1d29c6f7b9be.png)

**Comment by indirectlylit** [comment]
same issue reported by @jamalex during bug bash for beta 1

![image](https://user-images.githubusercontent.com/2367265/69927371-9e1dd480-146c-11ea-9a0f-c2b8e5ed70d9.png)

**Comment by jonboiser** [comment]
I've tried in the edit profile page to avoid this by adding enough extra space below the bottom of the form so that the dropdown could fall into it if it were ever opened. Must have forgot to implement something similar in the setup wizard.

**Comment by jonboiser** [comment]
Re-opening this so we can apply a similar fix to the User Profile version of this form

![Screen Shot 2019-12-19 at 12 48 29 PM](https://user-images.githubusercontent.com/10248067/71208498-f2db9080-225d-11ea-972e-f82fcf190bf3.png)

**Comment by jonboiser** [comment]
This issue should be fixed for the other User Profile forms in #6431
