### ISSUE TITLE
task progress percentage can be a very long negative number in scientific notation during import

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6170]
### Observed behavior
When I import this channel `nosov-pagif` random data is shown briefly

### Expected behavior

It should display the correct progress of the channel import.

### User-facing consequences

confusion and broken-looking behavior

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/69861980-6ed45f80-12d4-11ea-9cc4-abbc87fcf4ff.gif)

### Steps to reproduce

…

### Context

 * Kolibri version: Kolibri 0.13 b3
 * Operating system: Windows 7
 * Browser: Firefox(70.0.1)

**Comment by radinamatic** [comment]
Not sure if I would describe this as a **broken** progress bar... 🤔 

Channel is small, so the bar appears just for a moment, but I also noticed this strange sequence of numbers when importing. Was that what you were referring to @mrpau-richard?

![2019-12-01_3-55-06](https://user-images.githubusercontent.com/1457929/69919241-30c57000-147b-11ea-86de-2f11a298a69e.jpg)

cc @nucleogenesis

**Comment by indirectlylit** [comment]
updated description and title

**Comment by lyw07** [comment]
this is because cloudflare compresses json files, and for compressed files `content-length` is not available in the header. The file size is set to 1e+100 which caused the issue when calculating the progress.
this issue should be fixed by https://github.com/learningequality/kolibri/pull/6198
