### ISSUE TITLE
responsive design fails on small screens

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6171]
### Observed behavior
Several instances of responsive design issues on mobile phones.

#### Points icon
Firefox on Android | Chrome on Android | Safari on iPhone5
-------- | -------- | --------
![IMG_20191129_182423328](https://user-images.githubusercontent.com/1457929/69918037-6cf1d400-146d-11ea-8414-e5e2a90cef4c.jpg) | ![IMG_20191130_153146204](https://user-images.githubusercontent.com/1457929/69918021-49c72480-146d-11ea-8eec-b8f5d38e7d16.jpg) | ![IMG_20191130_225259214](https://user-images.githubusercontent.com/1457929/69918347-14bcd100-1471-11ea-9908-d5621d053e8c.jpg)

Next & Previous buttons in a quiz | More information icon is barely visible
-------- | --------
Overlapping buttons when the translated UI is longer than in English makes the usage from challenging to impossible. | *Create account* and *Edit profile* modals. Issue displays on all 3 browsers (Chrome & FF on Android, Safari on iPhone)
![IMG_20191129_184743589](https://user-images.githubusercontent.com/1457929/69918715-d970d100-1475-11ea-8d54-6101f809c6fa.jpg) | ![IMG_20191201_013321492](https://user-images.githubusercontent.com/1457929/69918598-67e45300-1474-11ea-8da1-a31bc221ad45.jpg)

### Expected behavior
App responsive and adaptable to smaller screens.

### User-facing consequences
Confusing UI and impossibility to use all the features.

### Errors and logs
…

### Steps to reproduce
Use small mobile device as a client to navigate Kolibri.

### Context
 * Kolibri version: 0.13.0b3 run as a server on Ubuntu 16.04 & macOS Mojave VMs
 * Client OS: Motorola G5 (Android 8.0.1), Motorola G6 (Android 9), iPhone 5
 * Browsers: all (Chrome & FF on Android, Safari on iPhone)

**Comment by indirectlylit** [comment]
broke this apart into its constituent issues:

* https://github.com/learningequality/kolibri/issues/6357
* https://github.com/learningequality/kolibri/issues/6358
* https://github.com/learningequality/kolibri/issues/6359
