### ISSUE TITLE
'View all' button removed from 'Lessons', 'Quizzes' and 'Class activity' blocks?

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6172]
### Observed behavior
Updating [coach pickles](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/coach/coach-class-home.feature) atm, and noticing that 'Lessons', 'Quizzes' and 'Class activity' blocks in 0.13 (left) do not display the `View all` button when the class has no lessons, quizzes or activity, as they did in 0.12 (right).

![2019-12-01_22-51-13](https://user-images.githubusercontent.com/1457929/69921078-5197c080-148f-11ea-8126-51a25719682f.jpg)

I can see the logic if the change was intentional, just making sure that it actually is, intentional 😉 

cc @indirectlylit @khangmach @jtamiace 

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

### Context
…

**Comment by indirectlylit** [comment]
Yup, this change was intentional: https://github.com/learningequality/kolibri/pull/5944

**Comment by radinamatic** [comment]
Great, will update the pickles accordingly, closing! 👍
