### ISSUE TITLE
Unable to clear filters in Manage resources for Lessons & Quizzes 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6173]
### Observed behavior
Still extant on 0.12.x branch, (tracked in #5882) too: clearing the search field does not yet bring back all the channels, as specified by the [Gherkin scenario](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/coach/coach-create-lesson.feature#L76).

### Expected behavior
Deleting the search term should reload the page and display all the channels on the device (or just those with exercises in case of the quiz builder).

### User-facing consequences
Inconsistent search behavior.

### Errors and logs
Nothing observable in the console.

### Context
 * Kolibri version: 0.13.0b3
 * Operating system: all
 * Browser: all

**Comment by jonboiser** [comment]
Closing as a duplicate
