### ISSUE TITLE
Filters for quizzes and lessons still refer to old statuses

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6174]
### Observed behavior
We invested much effort into changing the statuses of lessons and quizzes from active/inactive to visible/invisible and started/ended respectively, but we seem to have forgotten them in the filters 😞 

![old-statuses](https://user-images.githubusercontent.com/1457929/69922973-169e8880-14a1-11ea-859f-923804052c15.gif)

@indirectlylit Do we even have strings for the new statuses?

### Expected behavior
Wording of the filters should display consistent status options.

### User-facing consequences
User confusion because of the inconsistent status wording.

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: 0.13.0b3
 * Operating system: all
 * Browser: all

**Comment by indirectlylit** [comment]
If we don't have strings, we may need to temporarily hide this filter

**Comment by nucleogenesis** [comment]
@indirectlylit @radinamatic 

I think we'll need to hide them for now.

For lessons, what would the strings be?

"Visible lessons" & "Not visible lessons"?

Quizzes have more than 2 states now - so what would the strings for that be?

- Not started ("Not started quizzes")
- Started ("Started quizzes")
- Ended ("Ended quizzes")

**Comment by indirectlylit** [comment]
> For lessons, what would the strings be?

I think we'll have to punt this back to design. Would you mind filing a PR to remove the functionality for now, and update relevant gherkin stories if necessary?

I'll open a follow-up issue to do the design work and re-instate the functionality if necessary

**Comment by radinamatic** [comment]
@nucleogenesis I'll adjust the Gherkin scenarios, no worries! 
There simply will be no filters for now, correct, nothing else changes?

**Comment by nucleogenesis** [comment]
Yup! PR Incoming
