### ISSUE TITLE
Task Bar counts failed tasks as "done" in progress bar, but not in the"x of y tasks complete" label

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6177]
### Observed behavior

reported by @jtamiace during the 0.13.0 beta1 bug bash:

> 2 of 7 tasks failed, and the summary statement said '5 of 7 tasks complete'.
> 
> ![image](https://user-images.githubusercontent.com/2367265/69924866-48dcc580-1462-11ea-8bfb-e9802c31bf74.png)
> 
> ![image](https://user-images.githubusercontent.com/2367265/69924872-4e3a1000-1462-11ea-97b9-d4eb7f1ea483.png)

### Expected behavior

* Would be more accurate to say '7 of 7 tasks complete'.
* The task bar should also reflect this ratio, and _not_ incorporate actual number of resources or disk size

### User-facing consequences

confusing accounting of failed processes

### Steps to reproduce

start a number of imports, and cancel a few of them

### Context

0.13.0 beta 3

**Comment by indirectlylit** [comment]
related: https://github.com/learningequality/kolibri/issues/6183

**Comment by indirectlylit** [comment]
thanks for renaming

**Comment by jonboiser** [comment]
@indirectlylit @jtamiace Should we count Completed + Canceled + Failed tasks as "Complete" for the purposes of this task bar? There's a utility function in the code that groups these together as "clearable" that we can use to count them.

All "clearable" tasks will contribute 1 whole unit to the progress bar. Any queued or running Tasks will contribute their percentage value to the progress bar and 0 to the label.

E.g. if you have 1 canceled task + 1 in-progress task at 50%:

Label: "1 of 2 Tasks complete"
Progress Bar: (100% + 50%) /2 = 75%

**Comment by jtamiace** [comment]
I think counting completed, canceled, and failed as "complete" would solve the confusion.

**Comment by radinamatic** [comment]
I fail to see _failed_ as _completed_, but it might be nitpicking in the current crunch... 😛

**Comment by jonboiser** [comment]
There was some feedback from a bug bash that we could both make the message more specific about succeeded vs failed, and also divide the progress bar into different colored sections like we do on coach reports. (e.g. completed vs. canceled vs. failed).

**Comment by radinamatic** [comment]
I agree that would be preferable as more specific and correct info for the user. I could maybe also see _cancelled_ as _completed_ because the _cancel_ action was instigated by the user (and it was, presumably successfully concluded), but _failed_ should fall in a separate category.

The question remains if we can implement this **now**, or leave it for the patch release...?

**Comment by rtibbles** [comment]
Fixed in #6391

**Comment by indirectlylit** [comment]
> There was some feedback from a bug bash that we could both make the message more specific about succeeded vs failed, and also divide the progress bar into different colored sections like we do on coach reports. (e.g. completed vs. canceled vs. failed).

...

> I agree that would be preferable as more specific and correct info for the user. I could maybe also see cancelled as completed because the cancel action was instigated by the user (and it was, presumably successfully concluded), but failed should fall in a separate category.

I'll open this as a clearinghouse issue
