### ISSUE TITLE
channel listings will not load while a task is in progress

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6178]
### Observed behavior

Channel listing get stuck while a task is in progress:

![image](https://user-images.githubusercontent.com/2367265/69925108-521a6200-1463-11ea-9f51-8f4a26450a32.png)

![image](https://user-images.githubusercontent.com/2367265/69925129-6c544000-1463-11ea-9e76-14763a174640.png)

### Expected behavior

Operations that are not visible to the user in the task manager should never be blocked by tasks which are visible to the user.

### User-facing consequences

The user cannot continue to queue up new content while imports are in progress

### Steps to reproduce

1. start a long-running import
2. try to import from a new channel that has never been viewed before

### Context

0.13.0 beta 3

**Comment by rtibbles** [comment]
I reported this during the beta 0 bug bash - fixing this will require parallel task execution, and better handling of database locking.
