### ISSUE TITLE
progress bar is sometimes not updated while content downloads

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6179]
### Observed behavior

reported by @jamalex during the beta 1 bug bash:

> Bulk import of 3 channels appears to hang on first channel in task manager. it seems the downtime is being used to actually download the content. It just doesn't update the progress bar.
> 
> Eventually, it continued, after sitting at 0% for 5 mins. Looks like it had finished importing metadata, but then stalled, then started annotating availability. Not clear what it was doing in the interim.This is a faaaast computer and the channel was small.

### Expected behavior

progress bar should accurately reflect progress

### User-facing consequences

confusion about whether anything is happening

### Errors and logs

[kolibri.txt](https://github.com/learningequality/kolibri/files/3909109/kolibri.txt)

relevant section:

```
INFO 2019-11-21 14:30:34,259 annotation Annotating ContentNode objects with children for level 2
INFO 2019-11-21 14:30:34,260 annotation Annotating ContentNode objects with children for level 1
INFO 2019-11-21 14:30:34,295 channel_import Channel 000409f81dbe5d1ba67101cb9fed4530 successfully imported into the database
INFO 2019-11-21 14:33:10,500 cherrypy.access.140709951355472 127.0.0.1 - - "GET /static/kolibri.plugins.device.app/kolibri.plugins.device.app-0.13.0b1.js.map HTTP/1.1" 200 218608 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-11-21 14:33:10,605 cherrypy.access.140709951355472 127.0.0.1 - - "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b1.js.map HTTP/1.1" 200 1086302 "" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-11-21 14:38:50,295 annotation Setting availability to True of 1474 LocalFile objects based on passed in checksums
INFO 2019-11-21 14:38:50,325 annotation Setting availability of non-topic ContentNode objects based on LocalFile availability
INFO 2019-11-21 14:38:50,345 annotation Annotating ContentNode objects with children for 3 levels
INFO 2019-11-21 14:38:50,349 annotation Annotating ContentNode objects with children for level 3
```

### Steps to reproduce

bulk import multiple channels

### Context

0.13.0 beta 1

**Comment by pcenov** [comment]
@radinamatic I was not able to replicate the above described issue and specifically the 5 minute wait before the progress bar starts showing the progress. At the same time it does take several seconds for one of the channels to start importing and then this is followed by the rest so it seems that there's room for improvements on that front. Attaching a video for illustration:

https://user-images.githubusercontent.com/79847249/157871026-128a4184-2a0c-4157-8fd8-a70f66114d89.mp4

**Comment by rtibbles** [comment]
Going to close this as fixed - seems like there's potential for minor performance improvements, but the issue as described is not extant.
