### ISSUE TITLE
Renderer breaks when switching between contents quickly

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#618]
## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Develop
 - Operating system: Mac
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-02 at 3 55 22 pm](https://cloud.githubusercontent.com/assets/10454785/19950514/30714d90-a115-11e6-850f-bd7b8a15db69.png)

## How to reproduce

1. Login as learner
2. Quickly click between exercise and non-exercise items

## Screenshots

![screen shot 2016-11-02 at 3 55 12 pm](https://cloud.githubusercontent.com/assets/10454785/19950523/41264d3e-a115-11e6-9809-6bf85f3870d2.png)

**Comment by 66eli77** [comment]
fixed in PR #619

**Comment by indirectlylit** [comment]
Since this issue is unrelated to #619, can we submit it as a separate PR?

**Comment by rayykim** [comment]
fixed
