### ISSUE TITLE
scrolling and paging issues with slideshow

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6180]
### Observed behavior

reported during the 0.13.0 beta 1 bug bash

by @jayoshih 

> When I use the touch screen to swipe left on the first slide in the slideshow, it takes me back to the previous page

by @khangmach 

> In slideshows, each swipe on the mac trackpad runs through 3 slides instead of 1

by @nucleogenesis 

> Outlines on left/right buttons on Slideshow are clipped on the sides - maybe a bit too big visually? (hit tab to see them)

### Expected behavior

scrolling and paging should behave reasonably and accessibly for all input modalities

### User-facing consequences

hard to use slideshow

### Steps to reproduce

import channel `nosov-pagif` and scrolling and paging

### Context

0.13.0 beta 3

**Comment by nucleogenesis** [comment]
by @jayoshih

> When I use the touch screen to swipe left on the first slide in the slideshow, it takes me back to the previous page

This has been replicated by @radinamatic on Windows touch screen laptop in Chrome and Edge - but does not happen in Firefox.

I do not have a touchscreen laptop running Windows so I'm not able to reliably test any possible fix for this issue. Perhaps this can be made into its own separate issue - I can help guide on the whole Slideshow composnent feature.

by @khangmach

> In slideshows, each swipe on the mac trackpad runs through 3 slides instead of 1

I discussed this with Khang and it seems to be that if you use the "swipe" touchpad gesture on Mac - whereby you tap with two fingers and then swipe *quickly* with one - then it will do bypass 3 slides.

However, he noted that if the single-fingered swipe is a bit slower, it works as expected.

Similarly to the above - I don't have a Mac and I cannot reliably replicate this locally to test any possible fix. Again, I'd be happy to guide anybody on the basics of the Slideshow component and Hooper plugin that is used for the slideshow.

**Comment by indirectlylit** [comment]
deprioritizing for 0.13 because we don't have many slideshows in the wild

**Comment by pcenov** [comment]
@radinamatic This issue is no longer extant in 0.15.1 - retested with an iPad Pro 4th generation simulator plus real android device and did not observe any issues with viewing or scrolling a slideshow.

**Comment by radinamatic** [comment]
Thank you @pcenov, closing!
