### ISSUE TITLE
recipients column in coach tools in not accurate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6182]
### Observed behavior

recipients column always indicates assignment to the entire class, even when that's not true:

![groups](https://user-images.githubusercontent.com/2367265/69926711-644bce80-146a-11ea-8f2b-82ec444fb367.gif)

### Expected behavior

recipients column should be accurate

### User-facing consequences

confusion

### Errors and logs

none observed

### Steps to reproduce

create a lesson and assign it to a group

### Context

0.13.0 beta 3

**Comment by rtibbles** [comment]
Fixed in #6191
