### ISSUE TITLE
improve handling of video transcripts with RTL languages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6187]
### Observed behavior

observed during the beta 1 bug bash by @jeepurs:

> Arabic video transcript looks left to right
> 
> http://kolibribeta.learningequality.org/en/learn/#/topics/c/ac962cea9c185057baec90ec6c46814c is an example video of the TED ones in Arabic
> 
> ![image](https://user-images.githubusercontent.com/2367265/69928118-79772c00-146f-11ea-9382-1f3387d60c8e.png)

### Expected behavior

This is rather subtle, especially when the app language and transcript language might be different from each other.

* The overall user interface layout should conform to the current language set at the application level. In this case, if Kolibri is set to Arabic then UI elements that are typically on the right should be on the left, and vice-versa. For example, the overall transcript viewer and the specific location of timestamps should be mirrored. See #4686 for an example of making the epub content renderer RTL-compatible
* The individual text transcript lines should be aligned based on their actual content. If Kolibri is set to English but the transcript is in Arabic, the text should be right-aligned. If Kolibri is in Arabic but the text is in English, the text should be left-aligned. In general this can be achieved by simply setting `dir="auto"`. See #3781 for more info

### User-facing consequences

users of RTL languages have a less-optimal experience

### Steps to reproduce

* view RTL-language transcripts with the app set to an LRT language
* view LTR-language transcripts with the app set to an RTL language
* view RTL-language transcripts with the app set to an RTL language

### Context

0.13.0 beta 3

**Comment by indirectlylit** [comment]
migrated part of issue to https://github.com/learningequality/kolibri/issues/6239

**Comment by marcellamaki** [comment]
This probably needs confirmation that it can be reproduced, but I think this could be done within the scope of the issue and doesn't necessarily need QA re-review
