### ISSUE TITLE
average score info icon is an exclamation mark

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6188]
### Observed behavior

reported by @jtamiace during the 0.13.0 beta 1 bug bash:

> currently using the 'error' icon:
> 
> ![image](https://user-images.githubusercontent.com/2367265/69929322-767e3a80-1473-11ea-875b-431c8d1705dd.png)

this is defined in the `AverageScoreTooltip` component

### Expected behavior

should use an 'info' icon, which is an `i`

### User-facing consequences

confusing use of iconography

### Steps to reproduce

view any page using the `AverageScoreTooltip` component

### Context

0.13.0 beta 3

**Comment by jonboiser** [comment]
Fixed in #6264
