### ISSUE TITLE
Device Name changes to Task Manager

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#6189]
### Observed behavior
The  Device name on the top left corner on the device pages changes to Task Manager once the tasks (channel import) are viewed and the back button is pressed.

### The device name is shown as Device, which is correct
![oie_EJYergllHLB6](https://user-images.githubusercontent.com/8583367/69946258-500edc80-1511-11ea-9f93-edd86bf42097.png)
### On clicking task its changes to Task Manager which is correct
![oie_Md7wnrGkQtpe](https://user-images.githubusercontent.com/8583367/69946275-57ce8100-1511-11ea-8534-55f467bab232.png)
### On going back the name still remains as Task Manager instead of changing to Device
![oie_bP5DPLCAffvn](https://user-images.githubusercontent.com/8583367/69946299-6157e900-1511-11ea-81bf-68b2e3f15c33.png)

### Expected behavior
The Device name should change to Device when the back button is pressed

### User-facing consequences
The user may get confused as to whether the landed page is correct or not.

### Steps to reproduce
1. Go to Device and Import any channel
2. Click on view Task Manager
3. Click Back to Channels

### Context
 * Kolibri version 13.0.b3
 * Operating system : Linux Mint 19.2 Cinnamon
 * Browser Firefox

…

**Comment by indirectlylit** [comment]
good find, and clear steps to reproduce - thank you!
