### ISSUE TITLE
Wrong grammatical number agreement in 'someTasksComplete' message 

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6192]
https://github.com/learningequality/kolibri/blob/b751754f79c23990515fa6ebf24d1b3029f57f13/kolibri/plugins/device/assets/src/views/ManageContentPage/BottomBar/TasksBar.vue#L63-L66

Should be

```
         '{done, number} of {total, number} {total, plural, one {task} other {tasks}} complete', 

```

e.g. "1 of 5 tasks" instead of "1 of 5 task"

**Comment by rtibbles** [comment]
I think agreeing with the total here is correct? {1} out of {5 tasks} - the only question for me is for inflected languages, whether the `complete` should agree with {1} or {5 tasks}.

**Comment by jonboiser** [comment]
I think in that case, the `done` number should agree with the `completed` adjective, like in hebrew https://translate.google.com/#view=home&op=translate&sl=en&tl=ru&text=one%20task%20is%20done.%20two%20tasks%20are%20done.

And kind of matching our understanding in English where if you removed the "of X" part, you would understand the "completed" going with the tasks in the "numerator".

There are probably other cases like this in the app where we need to inflect the adjective as well.

**Comment by indirectlylit** [comment]
unfortunately we need to push to 0.14 due to string changes
