### ISSUE TITLE
Command Line - Enhancement Request - List Channel Status

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#6196]
Hello team Kolibri

Would it be possible to provide a command line option to list channel status, as in \<channel\>|\<status\>
?
This would allow intelligent  automation of channel updates - admin could ask user groups whether they wish to proceed with an update.

**Comment by indirectlylit** [comment]
Thanks for the request!

So that we have a bit more context, would you mind elaborating a bit on:

* A bit more detail of the scenario(s) you're envisioning. For example, is this a roaming admin who visits local implementations and talks with the local users?
* What do your users currently need to do, because they don't have this feature?
* What kind of information would you expect to be reflected in the `<status>`? Just channel version info, or also more details about what has changed in the new version?
* What sort of automation are you envisioning? Are you thinking of writing scripts that would parse the output of this command? (Alternatively, would the CLI be meant for humans or script consumption?)

**Comment by nobicycle** [comment]
Before refreshing a channel one should consult users to ask it the update is desired. Impact such as how much data will be deleted and how long the download will take. This information can be manually obtained from the GUI  by clicking import, copy, past- but multiplied by N channels

Any manual procedure is fraught with error. Plus this manual procedure needs to be done daily!
A CLI script could be programmed to gather the information, saving time and effort.

If the information could be enhanced, as you suggest with " more details about what has changed in the new version?" then that would be excellent.

If the site is clever, they could email the channel stakeholders with this information - increasing user engagement with Kolibri.

This system would also give ''at a glance' status of all channels where update is possible, but actually this should be indicated in the GUI import screen - an indicator next to each channel.

**Comment by indirectlylit** [comment]
thanks for the info!

In fact, some of what you describe will be present in the upcoming 0.13.0 release, specifically the ability to view information about how a channel update compares to the current version.

Please feel free to test out the beta and give feedback. More info here: https://github.com/learningequality/kolibri/wiki/0.13.0-beta-testing

**Comment by nobicycle** [comment]
> Please feel free to test out the beta and give feedback. More info here: https://github.com/learningequality/kolibri/wiki/0.13.0-beta-testing

I will.
Is there a list for beta testers? If so please add my email, if you know it from github.

**Comment by nobicycle** [comment]
Wow what a major release with so many really good additions.
Thank you team Kolibri.

I can't test the update yet because all channels are up to date.

**Comment by indirectlylit** [comment]
> I can't test the update yet because all channels are up to date.

One strategy for testing would be to self-publish a channel in studio and experiment with updating it

> Is there a list for beta testers? If so please add my email, if you know it from github.

Not yet - we're still experimenting with ways to manage the beta testing process. However this is something we're considering for future releases

**Comment by rtibbles** [comment]
I think the motivation for this issue has been resolved. The `kolibri manage listchannels` command also provides some of the command line functionality.
