### ISSUE TITLE
Better exception message for malformed db (especially in initialize => dbbackup)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6201]
### Observed behavior

An issue was reported here: https://community.learningequality.org/t/service-fails-at-startup/1337

We can see that `initialize` is called during an upgrade which leads to `dbbackup` producing the malformed db error outside of where it's normally anticipated.

### Expected behavior

1. A better failure message pointing to our updated troubleshooting section: https://kolibri.readthedocs.io/en/latest/manage.html#troubleshoot-database-issues
1. Catching the malformed db error in `dbbackup` or `initialize`.

### User-facing consequences

Bad advice making it harder to troubleshoot the issue.

### Errors and logs

```
Nov 28 15:15:50 raspberrypi kolibri[1390]: File “/usr/lib/python3/dist-packages/kolibri/utils/cli.py”,
Nov 28 15:15:50 raspberrypi kolibri[1390]: backup = dbbackup(version)
Nov 28 15:15:50 raspberrypi kolibri[1390]: File "/usr/lib/python3/dist-packages/kolibri/core/deviceadmi
Nov 28 15:15:50 raspberrypi kolibri[1390]: for line in db.connections[“default”].connection.iterdump(
Nov 28 15:15:50 raspberrypi kolibri[1390]: File “/usr/lib/python3.7/sqlite3/dump.py”, line 56, in _iter
Nov 28 15:15:50 raspberrypi kolibri[1390]: for row in query_res:
Nov 28 15:15:50 raspberrypi kolibri[1390]: sqlite3.DatabaseError: database disk image is malformed
Nov 28 15:15:51 raspberrypi systemd[1]: kolibri.service: Control process exited, code=exited, status=1/FA
Nov 28 15:15:51 raspberrypi systemd[1]: kolibri.service: Failed with result ‘exit-code’.
Nov 28 15:15:51 raspberrypi systemd[1]: Failed to start LSB: kolibri daemon, an offline education platfor
lines 1-15/15 (END)
```

### Steps to reproduce

Not sure!

### Context

Not sure, but definitely 0.13 relevant.

**Comment by radinamatic** [comment]
Updated documentation link for [the steps to repair a malformed database](https://kolibri.readthedocs.io/en/latest/manage/get_support.html#malformed-db).

**Comment by rtibbles** [comment]
Documentation was updated, and we now attempt to do automatic recovery.
