### ISSUE TITLE
Add/sub channel - the content folders are in reverse order

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#621]
*Please specify the Kolibri version you were using and your operating system!*

 - Version: Develop
 - Operating system: Mac
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
INSERT TRACEBACK, LOG MESSAGES ETC. HERE
```

## How to reproduce

1. Login as learner
1. Go through the folders - breadcrumbs from Explore > Math > Arithmetic

## Screenshots

Khan Academy's
![screen shot 2016-11-03 at 10 48 29 am](https://cloud.githubusercontent.com/assets/10454785/19978175/39bc9898-a1b3-11e6-91cd-bf4a1e5b3f13.png)

Kolibri's
![screen shot 2016-11-03 at 10 48 55 am](https://cloud.githubusercontent.com/assets/10454785/19978178/3d918c8a-a1b3-11e6-88c5-3903ab6bdb17.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by indirectlylit** [comment]
migrating issue to https://github.com/ralphiee22/ka-sushi-chef/issues/1
