### ISSUE TITLE
main page scrolls behind modals

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6212]
### Observed behavior

This appears to be a regression. The page will scroll behind modal.

![scroll](https://user-images.githubusercontent.com/2367265/70166184-24a70180-1679-11ea-972a-740c2de95178.gif)

### Expected behavior

Page should not scroll behind modal

### User-facing consequences

distracting interaction with main page when focus should be entirely contained to modal

### Steps to reproduce

open any modal and scroll

### Context

0.13.0 beta 3

**Comment by indirectlylit** [comment]
@jonboiser I've played around with this for a bit and don't see an obvious fix. I assume this is what used to work:

https://github.com/learningequality/kolibri/blob/ae47e83cc8f9c2a31d95f5915bb2e8edaed3cd3e/packages/kolibri-components/src/KModal.vue#L283-L285

 Any ideas? I imagine this is related to the scrolling refactor we did.

**Comment by jonboiser** [comment]
I'm not sure that 'preventScroll' method was ever working, but we were getting the effect we wanted through some other coincidence. Based on some stuff I've read online, it seems like you can't put this handler on the 'scroll' event, but rather need to `.preventDefault()` higher-level events like mouse wheel scrolls, mobile touches, keyboard arrows etc. This [Stackoverflow article](https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily)  shows a way to implement this for lots of modalities.

It seems that a more reliable, but less aesthetic way is prevent scrolling is to remove the scrollbar whilst the modal is open by setting `overflow: hidden` via this JS code:

```javascript
window.document.documentElement.style['overflow'] = 'hidden';
```
