### ISSUE TITLE
Unable to import a channel from an attached drive

### ISSUE THREAD

**Issue by larryyoung1200** [learningequality/kolibri#6213]
### Observed behavior

Failed to recognize that there were exported channels on the attached 4 TB Seagate drive. 
![image](https://user-images.githubusercontent.com/58528849/70172615-0bb14700-169f-11ea-9de9-f75e9c647c3e.png)
…

### Expected behavior

Expected it to display my available channels and allow me to import one.
…

### User-facing consequences

…

### Errors and logs

I don't see any log entries regarding the failed import.  
[kolibri.txt](https://github.com/learningequality/kolibri/files/3923552/kolibri.txt)

…

### Steps to reproduce

I can reproduce for you anytime.
…

### Context

Kolibri 0.13.0b3
Windows 10 Pro Version 1909
Firefox Browser version 70.0.1 (64 bit)
…

**Comment by jonboiser** [comment]
Hi @larryyoung1200, could you take a look at this [support forum post](https://community.learningequality.org/t/cannot-import-data-from-a-local-drive/1298/8) from a user with a similar issue? There are some troubleshooting steps you can try there to see if there is something specific to your Seagate Drive.

**Comment by larryyoung1200** [comment]
I’m afraid I’m having the same problem the person that reported the original problem had.  Please see screen shot below & identify for me where the Login button is on the “top right corner”.

 
I’m afraid I don’t understand the instruction to stop Kolibri.  When you do that you get a not found error since the port is closed.

Point is, I don’t want to copy the data.  I want to import the channels like the system says I should be able to, but I can’t.

![LocalDriveNotAuthenticated](https://user-images.githubusercontent.com/58528849/70279376-5eb0fa00-1784-11ea-8baf-f2d53d0929fc.jpg)

**Comment by larryyoung1200** [comment]
Hi,

 

I’m afraid I’m having the same problem the person that reported the original problem had.  Please see screen shot below & identify for me where the Login button is on the “top right corner”.

 



I’m afraid I don’t understand the instruction to stop Kolibri.  When you do that you get a not found error since the port is closed.

 

Point is, I don’t want to copy the data.  I want to import the channels like the system says I should be able to, but I can’t.

 

Regards,

 

Larry Young



3131 South Ridgewood Ave.

Suite 103

South Daytona, FL 32119-3562

 <http://www.layounginc.com/> http://www.layounginc.com

(530) 532-4718 (Office)

(530) 370-1533 (Mobile)

**Comment by larryyoung1200** [comment]
Hi,

 

I tried following the instructions from the Support Forum but nothing helps.  Here are the results of the Import.



 

Here’s what happens when I follow the instructions from the forum.



 

And there is no Log In button.

 



 

I don’t want to copy ALL of the channels from the 4 TB USB disk because I don’t have enough room on my local drive.  I need to be able to select specific channels.  

 

I am running the latest beta version.

 



 

Version:           0.13.0b4

OS:                Windows-8-6.2.9200

Installer:         Windows

Server:            Kolibri internal server

Database:          C:\Users\Larry Young\.kolibri\db.sqlite3

Device name:       DESKTOP-2BKTAGS

Free disk space:   519 GB

Server time:       Tue Dec 10 2019 17:46:31 GMT-0500 (Eastern Standard Time)

Server timezone:   America/New_York

 

Obviously, the ability to select channels from a USB drive is a feature of Kolibri, but it doesn’t work.  Can we get that feature working?

 

Regards,

 

Larry Young



3131 South Ridgewood Ave.

Suite 103

South Daytona, FL 32119-3562

 <http://www.layounginc.com/> http://www.layounginc.com

(530) 532-4718 (Office)

(530) 370-1533 (Mobile)

**Comment by jonboiser** [comment]
Hi Larry, your screenshots aren't appearing on the issue. It might have something to do with commenting on issues through email. If you're getting this by email, could you log on to GitHub and upload the screenshots again?

**Comment by larryyoung1200** [comment]
Hi,

I tried following the instructions from the Support Forum but nothing helps.  Here are the results of the Import.
![Picture1](https://user-images.githubusercontent.com/58528849/70580242-082b2d80-1b81-11ea-8d9a-ad7dfb4e740a.jpg)

Here’s what happens when I follow the instructions from the forum.

![picture0](https://user-images.githubusercontent.com/58528849/70580676-9eac1e80-1b82-11ea-82b3-36f2681d70de.jpg)

And there is no Log In button.

![Picture2](https://user-images.githubusercontent.com/58528849/70580259-2002b180-1b81-11ea-9fb9-fb57a8abb885.jpg)

I don’t want to copy ALL of the channels from the 4 TB USB disk because I don’t have enough room on my local drive.  I need to be able to select specific channels.  

I am running the latest beta version.

![Picture3](https://user-images.githubusercontent.com/58528849/70580290-3ad52600-1b81-11ea-9dd7-6bf3b4d910cf.jpg)

Obviously, the ability to select channels from a USB drive is a feature of Kolibri, but it doesn’t work.  Can we get that feature working?

Also, I did import a partial channel from Kolibri Channel but it never completed.

![Picture4](https://user-images.githubusercontent.com/58528849/70580314-52141380-1b81-11ea-901b-22a7108447ea.jpg)

At this point I can not do anything.  I can not create a class or do anything.  Here's the message I get.

![Picture5](https://user-images.githubusercontent.com/58528849/70580974-96081800-1b83-11ea-9f9f-80b71da82e56.jpg)

Please let me know if there's anything else you need.
Regards,
Larry

**Comment by larryyoung1200** [comment]
The exact same problem occurred with beta 5.

**Comment by jonboiser** [comment]
@larryyoung1200 Thanks for the screenshots.

Something looks wrong in the section that says

```
metadata: {
   channels: []
}
```

If there are channels on those drives, there should be data inside the `[]`.

Would you mind sending us a screenshot of what the hard drive looks like in Windows Explorer so we can see the directory structure of the files. For reference, here's what it should look like (screenshot from my Mac computer), looking at the very top-level of my USB drive:

![Screen Shot 2019-12-10 at 6 03 11 PM](https://user-images.githubusercontent.com/10248067/70584873-563b3380-1b77-11ea-8c2f-35821dfb7137.png)

 Because there are three files in the 'databases' folder, Kolibri will show that i have 3 channels I can import from it.

It also looks like you were able to log in, to get one of the screenshots. For reference, here's a screenshot of the `locahost:8080/api/tasks/tasks/localdrive` page.

![Screen Shot 2019-12-10 at 6 10 54 PM](https://user-images.githubusercontent.com/10248067/70585294-a8308900-1b78-11ea-801f-a2f3b1340086.png)

The login button is on the very right of the top black panel. After I log in, and refresh the page, I will see information about my hard drives.

**Comment by larryyoung1200** [comment]
Your screen shots help a lot.  The file structure of my USB drive is different than yours.  As you can see below, under Kolibri_Data I have 3 sub-directories; content; databases; storage.  You have one subdirectory; content.  Your sub-directories of content are databases & storage.

![Picture6](https://user-images.githubusercontent.com/58528849/70625160-d56c4e00-1bef-11ea-9da8-7bf53589dd5b.jpg)

Also, my screenshots of locahost:8080/api/tasks/tasks/localdrive are very different.  There is no login button on the top right.  There is no Django REST framework.

**Comment by jonboiser** [comment]
Could you try copying the files inside of `F:/KOLIBRI_DATA/databases` folder to `F:/KOLIBRI_DATA/content/databases` so it matches my directory structure? 

The end result should be that `F:/KOLIBRI_DATA/content/databases` will have the .sqlite3 files.

Also, move the `F:/KOLIBRI_DATA/storage` folder to `F:/KOLIBRI_DATA/content/storage` so it matches the directory structure in my screenshot.

I think that will fix the problem you were having.
