### ISSUE TITLE
Route with name 'RESOURCE_USER_SUMMARY' does not exist

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6218]
### Observed behavior

observed in console

```
[vue-router] Route with name 'RESOURCE_USER_SUMMARY' does not exist
```

### Expected behavior

no errors

### User-facing consequences

not apparent but may be indicative of something broken

### Steps to reproduce

I don't have precise steps yet, but these occurred while adding items to a lesson, clicking 'manage resources', and using browser back/forward.

### Context

0.13.0 beta 3

**Comment by jonboiser** [comment]
`RESOURCE_USER_SUMMARY` is the route name given to the "<-" button on the lesson resource preview it seems

https://github.com/learningequality/kolibri/blob/a304fd56330db03596717484a8801f905b26be97/kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js#L159-L170

I don't think this was ever a real route, based on the history of the router modules.

We need to change the code above to point to the real route name so the "<-" button works.
