### ISSUE TITLE
RTL language handled differently across interfaces

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#6219]
### Observed behavior

Arabic channel names do not read the same depending on whether they are a content channel tile or a top level breadcrumb

### Expected behavior

The titles would be handled RTL similar across each layout

### User-facing consequences

Not being able to read a correct tile

### Errors and logs

…

### Steps to reproduce

1. Visit http://australia-kolibri.mylearningpathway.org or http://jordan-kolibri.mylearningpathway.org
2. Click through "Earn - Job Skills" and search for HP LIFE (arabic) folder. Observe how the title are displayed in the tile
3. Click on HP LIFE folder and view how the title is displayed across the breadcrumb
4. They aren't the same

![Screenshot from 2019-12-04 15:31:12](https://user-images.githubusercontent.com/5150483/70198211-17166980-16c3-11ea-82b8-f91a2fac87b9.png)

![Screenshot from 2019-12-04 15:31:25](https://user-images.githubusercontent.com/5150483/70198216-1b428700-16c3-11ea-855f-ec7fcd01f5b8.png)

### Context

Linux, Chrome

From @jonboiser 
>I think the issue might be because we are wrapping the text inside the tile/card inside another component (TextTruncator) that doesn’t have the language “direction” rule that we usually put in components. The breadcrumb version of the title is not wrapped up this way and should have the correct direction rule on it.

**Comment by jonboiser** [comment]
These bidirectional e.g. Latin + Arabic texts are pretty problematic. When you narrow the page and cause the line to break into two lines, you can also see that it doesn't read the same any more either, with our convention of using `dir = auto`

Same topic title, broken over two lines (dir="auto") which is what's going on in the Card version above.

![Screen Shot 2019-12-05 at 5 40 15 PM](https://user-images.githubusercontent.com/10248067/70288359-4d68ed00-1786-11ea-90ad-298667fba15d.png)

Same topic title, broken over two lines (dir="rtl). Here, the title reads more correctly, but the parens are now misplaced and the "HP LIFE" is not in the intended location anymore.

![Screen Shot 2019-12-05 at 5 40 44 PM](https://user-images.githubusercontent.com/10248067/70288386-5e196300-1786-11ea-86c3-30bb50cbb28a.png)
"):

**Comment by indirectlylit** [comment]
see also - probably a different problem but maybe inter-related: https://github.com/learningequality/kolibri/issues/5468

**Comment by rtibbles** [comment]
@pcenov could you reinvestigate this in 0.15 onwards?

**Comment by pcenov** [comment]
@rtibbles The current design in 0.15.6 is quite different but still by looking really closely at the way the titles are displayed I was able to identify some instances where it would look better if the RTL title were right aligned:

Library page:

![2022-08-01_17-30-49](https://user-images.githubusercontent.com/79847249/182180586-a3f35947-091a-4fe3-9322-be10eb54cada.png)

Library page in responsive design view (the text breaks incorrectly in two lines as commented above by JB):

![2022-08-01_18-10-12](https://user-images.githubusercontent.com/79847249/182181690-1e6ab521-7a51-4acc-ab5e-a2ef198895c0.png)


Browse channel page:

![2022-08-01_17-34-23](https://user-images.githubusercontent.com/79847249/182180773-103bca4b-b020-463a-ba7c-84a75721ed7c.png)

**Comment by indirectlylit** [comment]
These look like examples of where using `dir="auto"` does not result in optimal behavior, presumably because the first characters in the titles are Latin which establishes an overall LTR base direction for that block.

Refs:

* https://design-system.learningequality.org/writing/#i18n
* https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#beyond

**Comment by rtibbles** [comment]
I think because we are already using dir="auto" here, I think we've done about as much as we can, without adding a lot of complexity that could go wrong in other ways, so I am closing this as won't fix.
