### ISSUE TITLE
gif images - out of bounds

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#622]
## Summary

Depending on the exercise content, some that have gif images are displayed outside of the card whenever you use the hint button.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: dev
 - Operating system: Mac
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-03 at 12 58 13 pm](https://cloud.githubusercontent.com/assets/10454785/19983258/88ae58ac-a1c6-11e6-94d1-b03b2db88423.png)

## How to reproduce

1. Log in as a learner
2. [Add-sub channel] 
Explore > Math > Arithmetic > Addition and Subtraction > Addition and subtraction word problems within 10

## Screenshots

![screen shot 2016-11-03 at 12 58 05 pm](https://cloud.githubusercontent.com/assets/10454785/19982973/6876bdaa-a1c5-11e6-8d65-901aea08f7d5.png)

![screen shot 2016-11-03 at 1 02 59 pm](https://cloud.githubusercontent.com/assets/10454785/19983233/6f7eb37c-a1c6-11e6-9551-4ef8918b7909.png)

![screen shot 2016-11-03 at 1 06 53 pm](https://cloud.githubusercontent.com/assets/10454785/19983240/731addf8-a1c6-11e6-9766-9b50701a9703.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by 66eli77** [comment]
fixed here https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/9
