### ISSUE TITLE
pagination value is too low for learner management in classes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6224]
### Observed behavior

For example, during individual assignment, only 5 learners are shown at a time

![image](https://user-images.githubusercontent.com/2367265/70252326-1a970880-1736-11ea-89be-2ef2f8f7e991.png)

Similar behavior exists for group enrollment

### Expected behavior

I would expect to be able to see my entire class roster at once. Typically classes will have less than 50 users, so a page size of 50 might be a good value.

This work should be done after https://github.com/learningequality/kolibri/issues/6222 (having buttons always shown in the footer) so that buttons aren't forced far down the page

### User-facing consequences

Extra clicks and more complicated UI to manage users within a class

### Steps to reproduce

Add a dozen users to a class and manage them in groups and individually

### Context

0.13.0 beta 3

**Comment by metodimilevqa** [comment]
I confirm the fix is successful with #7820. Verified with Kolibri v0.14.7-alpha4, Windows 10, Chrome (latest).
