### ISSUE TITLE
ValueError: pickle protocol 4 asked for; the highest available protocol is 2

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6238]
### Observed behavior

While testing https://github.com/learningequality/kolibri/pull/6207 got error related pickle protocols

### Expected behavior

no errors

### User-facing consequences

unknown

### Errors and logs

```
ERROR    Job 767a126271ec48daabf6d5ff1d1f3129 raised an exception: Traceback (most recent call last):
  File "/Users/d/.pex/install/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl.1c96f71514c7e69b0d22c18963272db7a4f3d938/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/Users/d/.pex/install/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl.1c96f71514c7e69b0d22c18963272db7a4f3d938/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/d/.pex/install/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl.1c96f71514c7e69b0d22c18963272db7a4f3d938/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/.pex/install/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl.1c96f71514c7e69b0d22c18963272db7a4f3d938/kolibri-0.13.0b4.dev0+git.7.g1e965215-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
ValueError: pickle protocol 4 asked for; the highest available protocol is 2
```

### Steps to reproduce

ran pex `start` command

### Context

pex from https://github.com/learningequality/kolibri/pull/6207 on macOS

**Comment by micahscopes** [comment]
Not sure but I think maybe we need to set the pickle protocol version in our django-redis-cache options:
http://niwinz.github.io/django-redis/latest/#_pickle_version

I'll try this in a bit.
c.c. @rtibbles

**Comment by rtibbles** [comment]
The only reason that it should be asking for a higher pickle version than is available is if there are different Python versions at play - also @micahscopes I assume no one running the pex is using redis, so I feel like it's not the redis version that is the issue.

Seems more likely to be pickling that's happening either in `diskcache` or in SQLAlchemy (for async tasks). The latter seems the most likely, if a task runner running Python2 is still running in the background, but a Python3 server queues something up in the task queue with its pickle protocol.

**Comment by jtamiace** [comment]
Scenario: P2P channel import from Devon

A short story:
<img width="605" alt="Screen Shot 2019-12-12 at 2 58 05 PM" src="https://user-images.githubusercontent.com/6668144/70755930-0c298d80-1cf0-11ea-94f3-ea03024aaecc.png">
<img width="1227" alt="Screen Shot 2019-12-12 at 2 58 12 PM" src="https://user-images.githubusercontent.com/6668144/70755931-0c298d80-1cf0-11ea-9c5c-fb0e5029215d.png">
<img width="1231" alt="Screen Shot 2019-12-12 at 2 58 18 PM" src="https://user-images.githubusercontent.com/6668144/70755932-0c298d80-1cf0-11ea-945e-9db02f4f4fb4.png">
<img width="1226" alt="Screen Shot 2019-12-12 at 2 58 25 PM" src="https://user-images.githubusercontent.com/6668144/70755933-0c298d80-1cf0-11ea-978b-f0eae4e17553.png">
![Screen Shot 2019-12-12 at 2 58 32 PM](https://user-images.githubusercontent.com/6668144/70755934-0c298d80-1cf0-11ea-8718-b052c0a7afd0.png)

**Comment by rtibbles** [comment]
Were you running the pex or the app?

**Comment by jtamiace** [comment]
pex

**Comment by rtibbles** [comment]
Had you previously run the app?

**Comment by jtamiace** [comment]
Yeah I have the mac app installed, also have installed other pex files before, and have run the dev server locally

**Comment by rtibbles** [comment]
OK - my suspicion is that a task has been created by the mac app, which uses Python 3.7, and then the pex file has picked up that task and tried to run it. We could guard against this by trying to force the task scheduler to only use pickle version 2. Thoughts @indirectlylit ?

**Comment by indirectlylit** [comment]
That sounds fine.

I don't quite understand what is meant by "the pex file has picked up that task and tried to run it" though:

* Is a "task" in this case an entry in the jobs DB?
* Should all tasks have been cleared when the mac app quit? If they didn't, would it been due to the zombie issue?
* Perhaps there's some way to more forcefully prevent multiple instances of Kolibri from accessing the same DB at the same time?

**Comment by indirectlylit** [comment]
also reported here by @lauradanforth https://github.com/learningequality/kolibri/issues/6267

**Comment by indirectlylit** [comment]
closing in favor of these three issues:

* https://github.com/learningequality/kolibri/issues/6247 (prevent zombies)
* https://github.com/learningequality/kolibri/issues/6317 (pin pickle protocol)
* https://github.com/learningequality/kolibri/issues/6316 (eventually, stop using pickle)
