### ISSUE TITLE
'unsupported browser' message is not internationalized

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6240]
### Observed behavior

Regardless of what language Kolibri or a user's browser is set to, they always see the message in English:

![image](https://user-images.githubusercontent.com/2367265/70378600-10604000-18d7-11ea-9de8-dcb6a1fe191e.png)

### Expected behavior

'unsupported browser' should show in the default language of the server

### User-facing consequences

less helpful message in other language

### Steps to reproduce

* set default device language to something other than english
* load any page using a user agent of an unsupported browser

### Context

0.13.0

**Comment by priyanka-choubey** [comment]
Can I take this up?

**Comment by indirectlylit** [comment]
no longer an issue - see https://github.com/learningequality/kolibri/pull/6635#issuecomment-596695527
