### ISSUE TITLE
videos not playing in mac app & Safari, but do in Firefox/Chrome

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6242]
`0.13.0b3` on Mojave 10.14.3.

Both macApp and Safari seem to be having the same issue with playing videos, but Firefox & Chrome play just fine:

![2019-12-01_3-11-02](https://user-images.githubusercontent.com/1457929/69908512-586cf780-13eb-11ea-8b34-fd5f5457481b.jpg)

![2019-12-01_3-17-38](https://user-images.githubusercontent.com/1457929/69908505-3d01ec80-13eb-11ea-9b23-8a62ed5052cb.jpg)

[logs.zip](https://github.com/learningequality/kolibri-installer-mac/files/3907784/logs.zip)

**Comment by kollivier** [comment]
Just a note that I tried this on my end by importing Radina Testing Channel with the latest Kolibri Mac app build on Mojave 10.14.5 and was unable to reproduce the problem. The videos load and play for me both in Safari and in the Mac app. Is it possible to upgrade the testing machine to 10.14.5?

**Comment by kollivier** [comment]
Also, I checked the video file and it's using H.264 for video and AAC for audio, which are supported codecs.

**Comment by radinamatic** [comment]
> it sounds like this is a regression?

I have been running tests on Mojave only from 0.13.0b3, so cannot be sure if it's a regression. The [test results from High Sierra were described here back in October](https://github.com/learningequality/kolibri-installer-mac/issues/4#issuecomment-546187218).

@mrpau-richard could you re-test on your Mojave VM to confirm?

**Comment by mrpau-richard** [comment]
> @mrpau-richard could you re-test on your Mojave VM to confirm?

I did not reproduce this issue on macOS 10.14.5 @radinamatic , The video played properly on `Safari 12.1.1`

**Comment by indirectlylit** [comment]
lowering priority because the results seem to be intermittent

**Comment by radinamatic** [comment]
Agreed, apparently only my Mojave VM has issue with this.

**Comment by rtibbles** [comment]
Is this still extant?

**Comment by radinamatic** [comment]
@pcenov Could you test this on the latest Mac app? Thank you!

**Comment by pcenov** [comment]
Hi @rtibbles and @radinamatic, I had the latest Mac app (v0.14.7) already installed on my Mac mini (macOS Catalina 10.15.7) and when this morning I checked the videos all were playing correctly. Then I decided to check what will be the case with a 0.15 build of the app which I downloaded from [here](https://buildkite.com/learningequality/kolibri-macos/builds/3744) and which I was able to install on the mac mini but not able to run it as it shows the following error message:

![test](https://user-images.githubusercontent.com/79847249/129922540-c05a2f00-ce3a-423d-984f-fc709716a69b.jpg)

Then I decided to access the 0.15 build through the Safari browser by using my windows laptop as a server. Surprisingly the videos won't play in that case:

![test 2](https://user-images.githubusercontent.com/79847249/129923504-976cff8d-2093-4925-a21d-a5dc10a23ef9.jpg)

After that I reinstalled the 0.14.7 build and wanted to confirm that the videos are playing correctly however the app remains stuck at the loading screen and I'll have to further investigate how to get it going again. :)

**Comment by pcenov** [comment]
Hi @rtibbles, had a chance to have a look at this one today with the [latest 0.15 build](https://buildkite.com/learningequality/kolibri-macos/builds/3804) and I can confirm that the issue is extant there - the videos are not playing neither in the app nor in Safari (14.1.2):
![safari](https://user-images.githubusercontent.com/79847249/130780082-82046620-6809-42dd-8395-600c6ac32b1a.jpg)

**Comment by pcenov** [comment]
@rtibbles and @radinamatic the issue reported here in my last comment is still present in the [latest 0.15 build](https://buildkite.com/learningequality/kolibri-macos/builds/4939#000fe592-3efd-41fa-ac48-836d9320259b). The videos are not playing neither in the app nor in Safari (14.1.2). Videos are playing fine in Chrome browser though so it must be a specific setting that Safari requires in order to play them.
