### ISSUE TITLE
occasional zombie processes related to unclean shutdown

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6245]
### Observed behavior

observed by @jamalex and @indirectlylit during testing of zerofconf work

> occasional zombie process happening when I CTRL-C a `kolibri start --foreground` server

This caused me some very confusing issues when I had closed all my terminals and Kolibri was still running in the background

### Expected behavior

Clean and complete shutdown

### User-facing consequences

Could get very difficult-to-debug behaviors if zombie processes are accessing DBs

### Steps to reproduce

unknown

### Context

0.13.0 beta 4

**Comment by micahscopes** [comment]
In the zeroconf-py2compat there are [a couple lines that catch all exceptions and log them](https://github.com/learningequality/python-zeroconf-py2compat/blob/master/zeroconf.py#L1945). I know that was causing really bad zombie processes in the past, ones that I couldn't even kill without rebooting. I prevented one particular exception where zeroconf was trying to unregister a peer that had already been unregistered by another listener. That shouldn't happen now since there will only be one listener, plus I added a case to avoid it... But I wonder if there aren't some other exceptions happening during shutdown, that are being logged but should not be?

@jamalex @indirectlylit did either of you see any errors with the zombies?

**Comment by indirectlylit** [comment]
Here's a recent stack trace after hitting `^C`. It includes a concerning error, but I don't actually see any running Python processes and running `lsof -i -P | grep 8080` produces no results.

* devserver beta 7
* macos 10.14.6
* Python 2.7.16

```
^CINFO     ENGINE Caught signal SIGINT.
INFO     ENGINE Bus STOPPING
WARNING  JOBCHECKER shut down event received; closing.
WARNING  JOBCHECKER shut down event received; closing.
WARNING  SCHEDULECHECKER shut down event received; closing.
INFO     
Kolibri instance '7f1f649cc4a16c2507e6e05094cca35b' has left the zeroconf network.

(k013x) d@slate ~/P/l/k013x (release-v0.13.x) [130]> INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
INFO     ENGINE Caught signal SIGINT.
INFO     ENGINE Bus STOPPING
INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
INFO     ENGINE Waiting for child threads to terminate...
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local. (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/Users/d/Projects/le/k013x/.venv/lib/python2.7/site-packages/zeroconf.py", line 1426, in run
  File "/Users/d/Projects/le/k013x/.venv/lib/python2.7/site-packages/zeroconf.py", line 1838, in wait
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 289, in __exit__
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 216, in __exit__
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 203, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by rtibbles** [comment]
Interesting - I think the price of no zombies may, at least in the short term, be slightly unclean shutdowns. More concerning on MacOS is the issue reported here #6307

**Comment by rtibbles** [comment]
I also wonder if we might just want to vendor zeroconf in the near future to iterate on this kind of issue more rapidly.

**Comment by indirectlylit** [comment]
hooray!

**Comment by jamalex** [comment]
>I also wonder if we might just want to vendor zeroconf in the near future to iterate on this kind of issue more rapidly.

I'd recommend avoiding this if possible, as after forking the older py2-compatible release version, I was careful to cherry-pick as much as possible from their ongoing development, and maintain a history that can still be reconciled with updates they make upstream, as desired.

Did we actually end up needing to make any zeroconf changes for this release, or was it all in Kolibri?

**Comment by rtibbles** [comment]
The only update we had to make was vendoring the enum compatibility code into zeroconf, hopefully should be able to avoid touching it in future.
