### ISSUE TITLE
Missing padding on import from local drive page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6246]
### Observed behavior
Since there is no `Import from token` button when using the local drive as import source, some more padding is required between the link to select entire channels or topics/resources, and the language filter.

![2019-12-08_22-42-16](https://user-images.githubusercontent.com/1457929/70396953-fd03c080-1a0d-11ea-8b30-6612593f9274.png)

![2019-12-08_22-50-10](https://user-images.githubusercontent.com/1457929/70396955-04c36500-1a0e-11ea-95f1-dd07f18fa15e.png)

### Expected behavior
Appropriate padding between elements.

### User-facing consequences
Inconsistent design

### Errors and logs
…

### Steps to reproduce
Go to Device > Channels and select to import from an attached drive.

### Context
 * Kolibri version: 0.13.0b4
 * Operating system: Windows 7
 * Browser: both Chrome & FF

**Comment by indirectlylit** [comment]
looks like this is not specific to Windows
