### ISSUE TITLE
vertical scrollbar an the bottom of the import page

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6248]
### Observed behavior
When resizing the browser window manually, bottom bar gets a bit _jumpy_ and gains a scrollbar when number of selected resources is displayed above.

![vertical-scroolbar](https://user-images.githubusercontent.com/1457929/70406808-32c29c80-1a42-11ea-82d1-09e1e699c2fb.gif)

### Expected behavior
There should be no need for that scrollbar, maybe adjust the height?

### User-facing consequences
Inconsistent UI design.

### Errors and logs
…

### Steps to reproduce
Try to import resources from a channel and resize window width manually.

### Context
 * Kolibri version: 0.13.0b4
 * Operating system: Windows 7
 * Browser: both Chrome & FF

**Comment by indirectlylit** [comment]
there are a few other places that aren't responsive
