### ISSUE TITLE
Inconsistent wording in the topbar for import pages 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6252]
### Observed behavior

When selecting Studio as a source, topbar wording is _just_ **Kolibri Studio channels**, while for the other two options it's **Import from '(source)'**. 

Import from Studio | Import from local address | Import from attached drive
------------ | ------------- | -------------
![2019-12-09_9-54-59](https://user-images.githubusercontent.com/1457929/70421952-256dd800-1a6b-11ea-9772-d39110971869.png) | ![2019-12-09_9-55-45](https://user-images.githubusercontent.com/1457929/70421972-30286d00-1a6b-11ea-8d38-c7928a85aa37.png) | ![2019-12-09_9-54-26](https://user-images.githubusercontent.com/1457929/70422004-3cacc580-1a6b-11ea-9f2a-60c68466f416.png)

Not sure if this was intentional, but is inconsistent. 
I'd recommend renaming the first to **Import from Kolibri Studio**.

### Expected behavior
Wording consistency when indicating for import sources.

### User-facing consequences
Uncertainty if there's an additional difference (a part from different sources)

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: 0.13.0b4
 * Operating system: Windows 7
 * Browser: both Chrome & FF

**Comment by indirectlylit** [comment]
Since this requires string updates, we won't be able to do it in 0.13

**Comment by radinamatic** [comment]
Leaving the last word to you, but don't we already have `Import from` part localized in the other two imports? Wasn't there a string-reuse option that you recommended to someone on a recent PR?

**Comment by indirectlylit** [comment]
If we went this route, it would end up saying 

> Import from 'Kolibri Studio channels'

whereas what I think we want is probably just

> Import from Kolibri Studio

I agree it would be possible to improve on the current behavior, but I'm also about to start triaging out P2 issues :)

**Comment by radinamatic** [comment]
Right, I my head I was leaving **Kolibri Studio** untranslated and just pasting the **Import from...** in front, but I see your point!
