### ISSUE TITLE
persist content task list across server restarts

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6255]
### Observed behavior

Restarting the server clears the list of completed tasks

### Expected behavior

Completed task list should persist across restarts. Any tasks that were ongoing when the server restarted should show as either canceled or failed.

### User-facing consequences

users lose access to important historical information

### Steps to reproduce

* let a few tasks run to completion
* start a new task
* stop server
* start server

### Context

0.13.0 beta 3

**Comment by jonboiser** [comment]
It looks like the job that underlies the task sticks around in the `job_storage.sqlite3` DB, but it doesn't get returned from the `/api/tasks` endpoint. I think that the job/task metadata doesn't actually get persisted in the job storage DB (but maybe it's stored in memory?), so it might not be serializable after the restart.

**Comment by rtibbles** [comment]
It does get persisted in the database, but at the moment, we clear the job storage DB on server restart, so that's why it doesn't currently persist across restarts.

**Comment by jonboiser** [comment]
I just tried this locally and there are some rows in the `jobs` and `scheduledjobs` tables that don't go away after I restart the webpack server.

I just assumed that they weren't being returned from `/api/task` endpoint, because the only thing these rows have is an `id` and no other displayable metadata.

**Comment by vkWeb** [comment]
I looked into this & I think upon server restart, the jobs are getting cleared from the `job_storage.sqlite3` db. 

But I cannot find the code where this deletion of records is happening :thinking:

**Comment by rtibbles** [comment]
Fixed in #7951
