### ISSUE TITLE
hide '+' and '-' when value is 0

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6259]
### Observed behavior

Shows '+' and '-' even when value is 0

![image](https://user-images.githubusercontent.com/2367265/70471635-6fae8380-1a82-11ea-81ee-dfb5fe0bcc39.png)

### Expected behavior

just show 0

### User-facing consequences

slight confusion

### Context

0.13.0 beta 3

**Comment by jonboiser** [comment]
Fixed in #6263
