### ISSUE TITLE
"Individual learners" looks like it's one of the group names

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6260]
### Observed behavior

We don't distinguish between group names and the category of individual learners

![image](https://user-images.githubusercontent.com/2367265/70472229-9f11c000-1a83-11ea-8171-64be620ee3f7.png)

### Expected behavior

should be more clear what the categories are

### User-facing consequences

possible confusion

### Steps to reproduce

create and assign to groups and individuals

### Context

0.13.0

**Comment by jonboiser** [comment]
In #6441, I added a "Persons" icon to make the "Individual learners" checkbox stand out a little more.
