### ISSUE TITLE
Updating a channel when no nodes have changed will download whole channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6262]
### Observed behavior

ref: https://www.notion.so/learningequality/0-13-0-bug-bash-2-775cb90a4bda4c59afe29a21b0153b59?p=0e50134d6a3349d4a078523406f40752

from @jonboiser 

> Updating a channel, when no nodes have changed will end up downloading whole channel (due to unexpected Python type coercion behavior)
> 
> The problem is the red code will evaluate to False, when node_ids is [], which is not what we want.
> 
> Mistake was assuming Python acted like JS and would consider a `[]` to be truthy.
> 
> JB Will add a patch to fix this in another PR.
> 
> ![image](https://user-images.githubusercontent.com/2367265/70474942-5dcfdf00-1a88-11ea-9726-5b1d7910c870.png)

### Context

0.13.0 beta 3

**Comment by lyw07** [comment]
how do I reproduce this case to have no nodes have changed while publishing a new version of the channel on studio? thank you!

**Comment by jonboiser** [comment]
@lyw07 You can simply rename a a topic or other node and re-publish, then you should get the same situation where zero nodes will be updated.

The third row on the Upgrade Channel Page should say something like `Resources to be updated: 0`

**Comment by jonboiser** [comment]
Should be fixed in #6300

**Comment by radinamatic** [comment]
I don't have the same setup as in #6280, but tested something similar in the latest dev build from this morning on Ubuntu, and it seemed not to be happening 👍 
Will confirm with the upcoming test with the next beta!
