### ISSUE TITLE
issues scrolling HTML5 apps in iOS

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6272]
### Observed behavior

@richard reported that the scrollbar is not visible in iOS for html5 apps

### Expected behavior

scrolling inner scrolling should work

### User-facing consequences

cannot currently scrol html5 on iOS

### Steps to reproduce

@rtibbles  would you mind linking to some specific content that exhibits this on the demo server?

### Context

0.13.0 beta 4

**Comment by rtibbles** [comment]
https://kolibridemo.learningequality.org/en/learn/#/topics/c/c1b7e1b7d832522bb74a0326723e7afe

**Comment by pcenov** [comment]
@radinamatic as far as I can see this is no longer extant in 0.15.1 in iOS.

**Comment by rtibbles** [comment]
Closing as fixed.
