### ISSUE TITLE
Update channel feature and annotation questions

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6280]
### Observed behavior
Long story, please bear with me... 🙂 

All in all the walk through the feature was relatively seamless, I just need some clarity on reported resources during the update process, to help me with writing Gherkin scenarios and the documentation.

1. I first imported an old version of my testing channel that I had on an external drive.

   ![import-v9](https://user-images.githubusercontent.com/1457929/70646194-b220bd80-1c46-11ea-96fa-0e70ec07d617.png)

2. Completed task reported 23 resources and 13 MB imported. 

   ![imported-v9](https://user-images.githubusercontent.com/1457929/70646527-5b67b380-1c47-11ea-8b7d-172c0c9a5b75.png)
  
3. After opening the `Manage` page for the channel, it rightfully reported the newer version that is available on Studio (v55).

   ![v55-changes-over-v9](https://user-images.githubusercontent.com/1457929/70646580-805c2680-1c47-11ea-965e-fafe394092e8.png)

4. Pressing the `Update channel` button, starts the corresponding task, but it's **unclear what these 10 resources and 30 MBs refer too**...? These values were nowhere to be seen in the previous steps.

   ![update-v9-to-v55](https://user-images.githubusercontent.com/1457929/70646780-e2b52700-1c47-11ea-8cd2-82c560b72d09.png)

   Is this step only supposed to update the DB to the newer version? Which resources are then being imported...? 😕 

5. After the above _update_ has been performed, this is visible in the `Manage` page for the channel (this is the only channel on the device):

   ![manage-v55-after-update-from-v9](https://user-images.githubusercontent.com/1457929/70647158-9dddc000-1c48-11ea-9dc2-e28cb3de8a84.png)

   I know some discrepancies are to be expected, but this is a smallish channel, and I'm only concerned what happens when working with channels with thousands of resources weighing gigabytes, and the user uncertainty around potential exponential increase in _discrepancies_. 

6. When I selected all available to **Import more** from Studio, it reported 162 resources and 240MB selected, of which 155 were finally imported:

   ![all-v55-resources-imported-over-v9](https://user-images.githubusercontent.com/1457929/70648115-b058f900-1c4a-11ea-8dc5-ea7f9242d669.png)

7. Finally, trying to import version 9 again from the external drive leads to nowhere, which is good 👍 
   The only small glitch is that it seems to load the old channel name above the topic tree.

   ![trying-to-update-from-v9-over-v55](https://user-images.githubusercontent.com/1457929/70648749-07130280-1c4c-11ea-8656-6f8846d75d56.png)

@jonboiser @indirectlylit ~Not technically~ Just became an issue, ~but~ I would appreciate some clarity regarding the questions in steps 4-5-6.

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
[logs.zip](https://github.com/learningequality/kolibri/files/3951982/logs.zip)

### Steps to reproduce
…

### Context
 * Kolibri version: 0.13.0b5
 * Operating system: Ubuntu 16.04
 * Browser: Firefox & Chrome

**Comment by radinamatic** [comment]
Tried repeating the steps with another older channel from the same external drive, and now we are entering the _bug_ zone and unmet expectations regarding the channel update process 😞 

1. Imported v13 of the PhET channel on the drive, reported only 8 resources and 17 MB selected/imported.

   ![import-PhET-v13-drive](https://user-images.githubusercontent.com/1457929/70667528-66cfd480-1c71-11ea-97d9-933c6a71f056.png)

   Are the selected resources per topic expected to sum up to the total at the bottom? If not, I need to clearly state that in the docs.

2. While trying to update the channel from Studio, suddenly the 17MB from the local import became 36MB **On the device**. Magically doubled?

   ![PhET-v15-available-Studio](https://user-images.githubusercontent.com/1457929/70667669-c0380380-1c71-11ea-84f6-4288dccc7bfb.png)

3. The information about what's new in the channel v15 creates the expectation that by updating the channel **only 15 resources** will be imported. 

   **Is that a correct assumption?** Again, if not, it needs to be clearly stated in the docs.

   ![PhET-resources-to-be-updated-with-v15](https://user-images.githubusercontent.com/1457929/70667752-f8d7dd00-1c71-11ea-8a8d-d713a56f7ab7.png)

4. Contrary to the expectation from above, many more resources seem to be pulled in during the channel update, something that the user did not clearly consent for.

   ![PhET-final-resources-updated-with-v15](https://user-images.githubusercontent.com/1457929/70667888-5704c000-1c72-11ea-8862-dd6ac4c8a36c.png)

    Not such a big issue in the case of this channel, but imagine the same happening with the KA EN, or similarly sized channel.

5. Apparently the _Update channel_ process imported the complete current PhET channel (proved by trying to **Import more** from Studio, and nothing being available), which is **not** what I expected.

    ![PhET-nothing-to-import-more-v15](https://user-images.githubusercontent.com/1457929/70668000-a0eda600-1c72-11ea-8036-4bb0f61a418a.png)



[new-logs.zip](https://github.com/learningequality/kolibri/files/3953001/new-logs.zip)

**Comment by jonboiser** [comment]
For at least one of the questions, there might be an explanation

> Contrary to the expectation from above, many more resources seem to be pulled in during the channel update, something that the user did not clearly consent for.

This issue #6262 shows this can happen when the "Resources to be updated" value is 0. What you saw is unusual because 15 resources were to be updated, so the default behavior of downloading the whole channel shouldn't happen...

**Comment by radinamatic** [comment]
Glad to have added another breadcrumb to the debugging information 😹 
(even thought it brings more questions than answers)

**Comment by indirectlylit** [comment]
@radinamatic I've tried to break this apart into its constituent parts. Please feel free to add details to these, or open additional ones if it seems that I missed anything:

* https://github.com/learningequality/kolibri/issues/6349
* https://github.com/learningequality/kolibri/issues/6351
* https://github.com/learningequality/kolibri/issues/6353
* https://github.com/learningequality/kolibri/issues/6354

**Comment by radinamatic** [comment]
Fair enough, I should have done it myself!
Storyteller :stuck_out_tongue:
