### ISSUE TITLE
Calling sys.exit in registerfacility kills parent process if invoked via call_command

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#6284]
### Observed behavior

The kolibri-un-women-common-plugin has a management command that calls registerfacility repeatedly. It was exiting after the first time around the loop because of the `sys.exit` in https://github.com/learningequality/kolibri/blob/release-v0.12.x/kolibri/core/auth/management/commands/registerfacility.py#L30

### Expected behavior

Command should complete and return without calling `sys.exit`.

### User-facing consequences

:broken_heart:

**Comment by indirectlylit** [comment]
@jamalex would you mind reviewing #6432
