### ISSUE TITLE
report P2P exports as well as imports in task manager

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6294]
### Observed behavior

When another Kolibri instance imports content from my device, I have no indication or record of that

### Expected behavior

I would expect P2P transfers from my device to show up as exports in the task manager.

### User-facing consequences

Lack of transparency about activity of their Kolibri device on their network

### Steps to reproduce

* Set up two Kolibri instances on the same network
* Import from one to the other
* Check task manager on both. There should be import/export "pairs"

### Context

0.13.0 beta 6

**Comment by rtibbles** [comment]
As we increase the peer to peer activity with the way we are managing imports from peers this will become very difficult.

Closing this as won't fix.
