### ISSUE TITLE
Max call stack errors when closing a modal whilst the disconnected screen is on

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6301]
### Observed behavior

1. Open any modal in Kolibri
1. Stop the server
1. The disconnected overlay will show up
1. Close the modal you opened in first step
1. See errors in console

This might be because the KModal is using some part of the DOM that the disconnected overlay is using and might be causing some bottomless recursion

This also makes forms in the modal unusable when disconnected overlay is showing. See the "Select Network Location > New Address" form

![Screen Shot 2019-12-13 at 10 58 01 AM](https://user-images.githubusercontent.com/10248067/70824796-db049800-1d97-11ea-8ae9-be4eb6bb297e.png)

### Expected behavior

1. No errors

### User-facing consequences

…

### Errors and logs

…

### Context
Kolibri 0.13.beta6

**Comment by jonboiser** [comment]
This seems to happen because both CoreSnackbar and KModal create an event listener for the 'focus' event that seem to cause them to go back and forth between one another's handler.

**Comment by indirectlylit** [comment]
should the the disconnected overlay be over the modal?

**Comment by jonboiser** [comment]
The two backdrops (GlobalSnackbar and KModal) actually have the same z-index of 24 (and I'm guessing the modal itself must be a little higher). So one way to mitigate this might be to put the GlobalSnackbar's backdrop higher than KModal's.
