### ISSUE TITLE
enabling a plugin does not run collectstatic

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#6304]
### Observed behavior

Missing static assets folder `.kolibrihome/static/kolibri.plugins.h5p_viewer.main`

### Expected behavior

Static asserts folder with js/css files needed for the `h5p_viewer` plugin.

### User-facing consequences

Users will have difficulty enableing the h5p plugin

### Steps to reproduce

First download and run Kolibri for the first time

```shell
mkdir testkhome
cd testkhome

wget "https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri-buildkite-build-6268-12902-kolibri-0.13.0b6.dev0_git.26.gad37f5e7.pex?generation=1576251450977510&alt=media" -O kolibri-013b6-test.pex

export KOLIBRI_LANG=en
export KOLIBRI_HOME=/testkhome
export KOLIBRI_PORT=9090
export KOLIBRI_PEX_FILE=kolibri-013b6-test.pex
python $KOLIBRI_PEX_FILE start --foreground --port=$KOLIBRI_PORT
```
Kolibri will start and run the migrations as usual

Second stop Kolibri
```
^C
```

Third enable plugin
```shell
python $KOLIBRI_PEX_FILE plugin enable kolibri.plugins.h5p_viewer
```
(this is where the bug happens)

Finally start and stop Kolibri one more time:
```shell
python $KOLIBRI_PEX_FILE start --foreground --port=$KOLIBRI_PORT
^C
```

Expected: `static/kolibri.plugins.h5p_viewer.main` dir to exist

Observed: `static/kolibri.plugins.h5p_viewer.main` dir is missing

 

### Context
 * Kolibri version: 0.13b6
 * Operating system: linux
 * Browser: Chrome

### Workarounds

1. Enable the plugin before first run
2. Run `python $KOLIBRI_PEX_FILE manage collectstatic` after enabling the plugin

**Comment by indirectlylit** [comment]
interestingly, when I run `kolibri plugin enable kolibri.plugins.h5p_viewer` I get

```
INFO     Enabling plugin 'kolibri.plugins.h5p_viewer'
WARNING  kolibri.plugins.h5p_viewer already enabled
```

Is this supposed to be enabled by default?

**Comment by rtibbles** [comment]
> Is this supposed to be enabled by default?

It is in development, but is not in production.

**Comment by indirectlylit** [comment]
closing because #6306 is merged. @ivanistheone please re-open if you still encounter issues
