### ISSUE TITLE
h5p woff static files are not ignored by git

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6312]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/70856989-8a766300-1e9b-11ea-8e13-6419f9f81f56.png)

### Expected behavior

I think this file should be ignored? I did see this in `.gitignore` but unsure what the expected behavior is:

```
# don't ignore the TTF font for H5P
!h5p-core-18.ttf
```

### User-facing consequences

I was noticing these files changing unexpectedly and getting added to git?

Might be interacting with git LFS in `.gitattributes`?

```
# use Git LFS to track large binary files
*.otf filter=lfs diff=lfs merge=lfs -text
*.ttf filter=lfs diff=lfs merge=lfs -text
*.ttc filter=lfs diff=lfs merge=lfs -text
*.woff filter=lfs diff=lfs merge=lfs -text
```

### Steps to reproduce

* I had been trying to repro https://github.com/learningequality/kolibri/issues/6304
* at some point I had both https://github.com/learningequality/kolibri/pull/6306 and https://github.com/learningequality/kolibri/pull/6268 merged in
* ran `yarn run build` at some point

### Context

0.13.0 beta 7

**Comment by rtibbles** [comment]
Odd - I think previously we only had the ttf for h5p, so perhaps I should add exceptions for these too?

**Comment by nucleogenesis** [comment]
I encountered this while rebasing:

```
First, rewinding head to replay your work on top of it...
Encountered 1 file(s) that should have been pointers, but weren't:
	kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff
```

Note that I couldn't revert the changes or stash them or anything. In order to checkout a new branch I resorted to committing the file to the branch I was on.

**Comment by indirectlylit** [comment]
also observed by @radinamatic
