### ISSUE TITLE
newly-imported channels do not show without refresh and are not labeled

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6314]
### Observed behavior

This issue is a combination of:

* a regression from https://github.com/learningequality/kolibri/issues/2030
* new functionality not-yet implemented

| step | screenshot |
|--|--|
| original channel listing |![image](https://user-images.githubusercontent.com/2367265/70857178-a0d1ee00-1e9e-11ea-8aa4-41f5accac722.png)|
| start a content import, and click "Back to channels" before it completes | ![image](https://user-images.githubusercontent.com/2367265/70857180-a4657500-1e9e-11ea-9e5b-c510a8a13975.png)|
| After import complete, the channel does not show up | ![image](https://user-images.githubusercontent.com/2367265/70857171-8e57b480-1e9e-11ea-8557-290879abeeba.png)|

### Expected behavior

* If an import related to a channel completes while viewing the channel list, the channel should move to or appear at the top of the channel list
* If an import related to a channel completes before viewing (or refreshing) the channel list, it should appear in its default position
* The 'New' label should appear next to any channel that has an 'import' task still visible in the task list.
* Clearing the task list using the button on the channel list page should clear 'New' labels, but _not_ change the channel order
* Navigating away from and back to the channel list moves channels to their default order

Original specs are very slightly different but the same in broad strokes:

https://www.figma.com/file/eJd6xQiNgebzzRWn2XDDS92R/0.13-content-import?node-id=472%3A0

![image](https://user-images.githubusercontent.com/2367265/70857283-3ae66600-1ea0-11ea-81f8-ac98ab49b203.png)

### User-facing consequences

This feature was important for https://github.com/learningequality/clearinghouse/issues/254

### Steps to reproduce

* Begin import of a new channel
* Navigate to 

### Context

0.13.0 beta 7

**Comment by rtibbles** [comment]
Fixed in #6355
