### ISSUE TITLE
allow display of custom licenses in Kolibri

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6326]
### Observed behavior

from @kollivier 

> Videos with special permissions just say to contact the author, but I think on Studio we can add the actual license text

### Expected behavior

kolibri users should see actual license text

### User-facing consequences

unclear license

### Context

0.13.0

**Comment by jonboiser** [comment]
@kollivier Does the wording of the special licenses just go in this same `license_description` here on the left? If a piece of content has this, we can show, but I think we actually remove it from the serializer as a general rule to reduce the data that goes over the wire and rely on the `license` enum on the right.

<img width="415" alt="Screen Shot 2020-05-04 at 2 39 45 PM" src="https://user-images.githubusercontent.com/10248067/81016381-27b74100-8e15-11ea-861c-f1b748c7060f.png">

**Comment by jonboiser** [comment]
So maybe what we could do add the `license_description` to the serializer, but default it to `''` if it is a license type that Kolibri already has a reference description for.

**Comment by rtibbles** [comment]
That seems like the correct behaviour.

**Comment by jonboiser** [comment]
But because these special `license_description` are pre-written, I don't expect we will localize them like we do for the CC licenses (for some languages).

**Comment by rtibbles** [comment]
Looks like the serializer is actually returning this, but our translation machinery is always inserting the special permissions translated description. Adding a special case to the frontend to display the custom description when available.
