### ISSUE TITLE
Perseus exercises appear above the BottomBar widget

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6327]
### Observed behavior

reported by @jonboiser that exercises are over the bottom bar:

![image](https://user-images.githubusercontent.com/2367265/70873212-8a409b00-1f61-11ea-8424-3cebdb92d22d.png)

### Expected behavior

exercise below bottom bar

### User-facing consequences

broken UI

### Steps to reproduce

create or take a quiz with "place value when multiplying and dividing by 10"

### Context

0.13.0 beta 6

**Comment by nucleogenesis** [comment]
I tried to replicate this without luck on the Kolibri beta server (beta7).

![perseus-does-not-overlay](https://user-images.githubusercontent.com/6356129/71132555-b308a080-21ac-11ea-8dc9-775165562e76.gif)

Try it out logging in as learner `queencreens` and taking the quiz in SUPER LE CLASS called "divide"

**Comment by nucleogenesis** [comment]
Just kidding about the last comment - it appears this way in the Quiz Preview page.

It is fixed by making the z-index on the bottom bar 1062. Will make a PR.

**Comment by rtibbles** [comment]
Fixed in #6396
