### ISSUE TITLE
Transcript controls aren't dismissed when you select another control

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6328]
### Observed behavior

reported by @khangmach 

> Transcript controls aren't dismissed when you select another control
> 
> ![image](https://user-images.githubusercontent.com/2367265/70873347-45693400-1f62-11ea-8071-6ec0160b0e0a.png)

### Expected behavior

selecting another control should dismiss the transcript control

### User-facing consequences

overlapping menus

### Context

0.13.0 beta 4

not tested in recent betas

**Comment by bjester** [comment]
@indirectlylit This is essentially the same as https://github.com/learningequality/kolibri/issues/6036

**Comment by indirectlylit** [comment]
thanks - closing as duplicate
