### ISSUE TITLE
Exercise content - answer choice text does not appear 

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#633]
## Summary

This exercise content MC type question - the text does not appear in the answer choices. When you hit the back button in the breadcrumb, the page doesn't change and the MathJax error shows up in the console.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-07 at 3 08 12 pm](https://cloud.githubusercontent.com/assets/10454785/20080216/4d9bb66c-a4fd-11e6-9410-1ea295fb71d7.png)

## How to reproduce

1. Log in as learner
2. Explore > Math > Pre-algebra > Fractions > Multiplying whole numbers and fractions > Multiply fractions and whole numbers 2

## Screenshots

![screen shot 2016-11-07 at 3 04 26 pm](https://cloud.githubusercontent.com/assets/10454785/20080211/47638518-a4fd-11e6-803e-c865145da92a.png)

**Comment by 66eli77** [comment]
https://groups.google.com/forum/#!topic/mathjax-users/UT9qMPPwbzg
seems like this is a serious issue. MathJax and webpack do not get along.
