### ISSUE TITLE
Quiz recipients only lists Groups and not the Individual learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6331]
### Observed behavior

reported by @lauradanforth during bug bash 2:

> On Plan page, Quiz recipients only lists Groups and not the Individual learners that are also assigned

https://www.notion.so/learningequality/0-13-0-bug-bash-2-775cb90a4bda4c59afe29a21b0153b59?p=24358cef941f4042b777aec8b9d8a612

recipients shown:

![image](https://user-images.githubusercontent.com/2367265/70874493-36d14b80-1f67-11ea-9727-cf7be81f9b54.png)

### Expected behavior

The recipients who should be shown:

![image](https://user-images.githubusercontent.com/2367265/70874501-3df85980-1f67-11ea-9fa8-3274a80587f8.png)

### User-facing consequences

incomplete information

### Steps to reproduce

not tested on latest beta - not sure if it's still an issue?

### Context

0.13.0 beta 4

**Comment by rtibbles** [comment]
Fixed in #6347
