### ISSUE TITLE
User counts label are not in the same position

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6335]
### Observed behavior
The user counts label are not in the same position in two different browsers

### Expected behavior
User counts label should be in the same position

### User-facing consequences

…

### Errors and logs
![Screen Shot 2019-12-16 at 12 34 08 PM](https://user-images.githubusercontent.com/8663934/70879868-e22ede80-2001-11ea-8c59-037a4b22346d.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0b7
 * Operating system: Windows 7
 * Browser: Firefox and IE11

**Comment by jonboiser** [comment]
Should be fixed in #6458, by replacing the experimental `text-align: end` rule with `text-align: right`. Positioning of the controls is correct in RTL, but haven't look closely at the localized text to see if direction is correct without the `end` rule (e.g. in Arabic).

**Comment by indirectlylit** [comment]
should be fine using `right` because our RTL CSS transformation will flip it the other way
