### ISSUE TITLE
keyboard navigation is broken in safari and mac app on some pages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6338]
### Observed behavior

focus never escapes from the app bar on some pages:

![2019-12-15 21 05 41](https://user-images.githubusercontent.com/2367265/70880687-bf0f1b00-1f7e-11ea-817e-5b4bbe4366d4.gif)

### Expected behavior

focus can reach entire page, and 'skip to content' works as expected

### User-facing consequences

limited keyboard accessibility for mac users

### Steps to reproduce

open learn and coach and try tabbing through

### Context

0.13.0 beta 7

**Comment by jonboiser** [comment]
Can you check if your Mac is set to access elements with a keyboard? 

Check out this article 

https://a11yproject.com/posts/macos-browser-keyboard-navigation/

Go to "Browser settings to enable full keyboard navigation"

The problem is that Safari doesn't let anchor tags be keyboard-focusable by default, which explains why the Skip Nav LInk doesn't work on Learn > Classes (it's only anchor tags in the main area). I'm guessing it's the same in the Coach Home Page (all links, no buttons)

**Comment by radinamatic** [comment]
One of the great world mysteries why Apple leaves that option seriously limited by default 😒 
Just wondering what is the business logic behind that...

**Comment by jonboiser** [comment]
@kollivier Can you configure the Kolibri Mac App to have these accessibility settings turned on?

**Comment by radinamatic** [comment]
I don't think you can configure **any** Mac app for this **separately** -  it's a general setting for the whole OS, and user must enable it by themselves.

@indirectlylit should just check if by setting that properly, he has the proper, _normal_ keyboard navigation in the Kolibri macApp.

**Comment by jonboiser** [comment]
That might have changed. When I just fixed it for my new computer, the setting was in the Preference menu of Safari itself.

There's also an OS-wide setting that lets users keyboard control modals that appear like the empty trash can confirmation modals, etc, but that actually didn't help with Safari.

**Comment by radinamatic** [comment]
Gah, they are making it even worse and more complicated than it was before 😡

**Comment by kollivier** [comment]
It looks like there's a way (a "tab to links" setting), but wx (the GUI toolkit we're using right now) doesn't provide access to it. I'm thinking of switching to PyObjC for the next version so we have direct access to the WebView and full control over the GUI on Mac. This also would allow us to try some things to fix the Mac app scrolling problems.

**Comment by indirectlylit** [comment]
off-topic, but...

> I'm thinking of switching to PyObjC for the next version

a couple other options:

* Qt
* Electron

**Comment by indirectlylit** [comment]
we might want to consider adding this to docs

**Comment by radinamatic** [comment]
> we might want to consider adding this to docs

It's in the queue! 👍
