### ISSUE TITLE
lesson reports showing up for learners to whom it was not assigned

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6342]
### Observed behavior

observed by @jamalex 

> Going into Reports > Learners, and clicking into a specific learner to whom a Lesson is not assigned, it still shows up in their assigned list

### Expected behavior

reports are only shown for assigned learners

### User-facing consequences

noise in coach reports

### Context

0.13.0 beta 6

**Comment by indirectlylit** [comment]
This might also be related to notes from @jonboiser and @jtamiace:

----

### recipients don't match on Report vs. Learners Tab

[http://kolibribeta.learningequality.org/en/coach/#/612355f5712f26fb842aecf17fb2c376/reports/lessons/f10ae0ca4dc9f5a73bbe1469b1db3ffd/learners](http://kolibribeta.learningequality.org/en/coach/#/612355f5712f26fb842aecf17fb2c376/reports/lessons/f10ae0ca4dc9f5a73bbe1469b1db3ffd/learners)

In other reports, individual learner "Jamal Khan" is missing from tables or panels (e.g. he's missing in this table :[http://kolibribeta.learningequality.org/en/coach/#/612355f5712f26fb842aecf17fb2c376/reports/lessons/f10ae0ca4dc9f5a73bbe1469b1db3ffd/resources/9148b9841a275555adc9490d7b058c68/learners](http://kolibribeta.learningequality.org/en/coach/#/612355f5712f26fb842aecf17fb2c376/reports/lessons/f10ae0ca4dc9f5a73bbe1469b1db3ffd/resources/9148b9841a275555adc9490d7b058c68/learners)

+1, same for Jessica

[http://kolibribeta.learningequality.org/en/coach/#/c49637cef76d2912feb43b0f0ba917cc/reports/lessons/6cd91f9de8bf48bc54a9c8ede13cc525/learners](http://kolibribeta.learningequality.org/en/coach/#/c49637cef76d2912feb43b0f0ba917cc/reports/lessons/6cd91f9de8bf48bc54a9c8ede13cc525/learners)

**Comment by rtibbles** [comment]
Fixed in #6347
