### ISSUE TITLE
first 'individual learners' checkbox click is ignored

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6343]
### Observed behavior

observed by @radinamatic 

> Takes 2 clicks to select individual learners when copying the lesson
> 
> ![image](https://user-images.githubusercontent.com/2367265/70881668-1e225f00-1f82-11ea-8e4d-e64baddce068.png)

### Expected behavior

checkbox behaves as expected

### User-facing consequences

confusion

### Steps to reproduce

see gif

### Context

0.13.0 beta 6

**Comment by radinamatic** [comment]
GIF became PNG for some reason, original here:

![copy-lesson-individual-learners](https://user-images.githubusercontent.com/1457929/70904747-6a14e880-2002-11ea-88f8-fc1e9b6b83c5.gif)

The list of individual learners was actually appearing when **unchecking** the checkbox.

https://www.notion.so/learningequality/Takes-2-clicks-to-select-individual-learners-when-copying-the-lesson-1342befcae5e43f6872ae6b84515cb42
