### ISSUE TITLE
Created new classes not automatically showing up when created in another window

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6344]
### Observed behavior
I need to refresh the page to show the new created class on Firefox
### Expected behavior
New created class must show automatically on the Classes without a browser refresh

### Errors and logs
![Screen Shot 2019-12-16 at 1 26 02 PM](https://user-images.githubusercontent.com/8663934/70881768-9cc1df80-2008-11ea-8516-e1478a0d6860.png)

### Steps to reproduce

…

Tell us about your environment, including:
 * Kolibri version: 0.13.0b7
 * Operating system: Windows 7
 * Browser: Firefox

**Comment by DXCanas** [comment]
Can't replicate this behavior on latest dev build `Kolibri 0.13.0b7.dev0+git.18.gfa38d6dd` on Windows 10 with FF 71

**Comment by mrpau-julius** [comment]
I reproduce this issue on Windows 10. When I create a new class in Firefox, the Edge browser need to refresh to see the new class.
![classes](https://user-images.githubusercontent.com/38421180/70962876-980d3200-20c1-11ea-9295-a3707d7a9fd0.gif)

**Comment by DXCanas** [comment]
Is auto update across sessions expected behavior? @indirectlylit @jtamiace ?

**Comment by indirectlylit** [comment]
Ah, I misunderstood the issue.

No, auto-update is not currently implemented.

**Comment by rtibbles** [comment]
Closing this as wontfix.
