### ISSUE TITLE
Same user identification number or student ID number

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#6346]
### Observed behavior

Allow to create the same user identification number or student ID number.

### Expected behavior

Identification number must be unique.

### User-facing consequences

…

### Errors and logs

![identifier](https://user-images.githubusercontent.com/38421180/70884085-df3aea80-200f-11ea-9721-fc7bbcdc19cf.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version : 0.13.0 beta 7
 * Operating system : Windows 10 
 * Browser : Firefox 71.0 (64-bit) and Edge 

…

**Comment by indirectlylit** [comment]
duplicates are allowed by design
