### ISSUE TITLE
remove resource counts in content import tree view

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6349]
# Observed behavior

For performance reasons, we cannot calculate precise counts. This leads to inconsistencies, where the counts don't add up to the total reported. For example:

![image](https://user-images.githubusercontent.com/2367265/70942382-69c91d00-2003-11ea-8660-0aefa1bfbac6.png)

### Expected behavior

Rather than reporting precise counts, we should use these more nebulous strings:

https://github.com/learningequality/kolibri/blob/ae47e83cc8f9c2a31d95f5915bb2e8edaed3cd3e/kolibri/plugins/device/assets/src/views/SelectContentPage/treeViewUtils.js#L16-L19

### User-facing consequences

confusion about what's actually selected and on the device

### Steps to reproduce

import content

### Context

0.13.0 beta 7

**Comment by lyw07** [comment]
fixed in #6377
