### ISSUE TITLE
Incorrect video content progress percentage

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#635]
## Summary

In any given video content, the progress percentage keeps increasing regardless if you go replay it or not.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## How to reproduce

1. Login 
2. Go to any video content

## Screenshots

![incorrect percentage](https://cloud.githubusercontent.com/assets/10454785/20081269/537d8186-a503-11e6-8eb6-82071482c205.gif)

**Comment by 66eli77** [comment]
@christianmemije  you seems the person mostly familiar with this feature, assign you this issue

**Comment by christianmemije** [comment]
Unfortunately, that is normal behavior.

**Comment by indirectlylit** [comment]
noted here: https://trello.com/c/CBybun41/689-improve-progress-tracking-of-content
