### ISSUE TITLE
broken points icon layout on small screens

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6357]
### Observed behavior

| safari | ios |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/70946706-84ec5a80-200c-11ea-9f6e-65a73670e7d9.png) |![image](https://user-images.githubusercontent.com/2367265/70946729-903f8600-200c-11ea-83ca-aeb65f2b592d.png)|

### Expected behavior

points icon should either be hidden or render correctly

### User-facing consequences

broken-looking layout

### Steps to reproduce

view on small screen

### Context

0.13.0 beta 7

**Comment by radinamatic** [comment]
That's not only on Safari, It's on all small sized displays

**Comment by radinamatic** [comment]
Right there :joy:

**Comment by rtibbles** [comment]
Fixed in #6367
