### ISSUE TITLE
Quiz bottom bar element ordering reversed in MS browsers

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#6361]
### Observed behavior

The ordering for elements in the quiz bottom bar is reversed for IE 11 and Edge browsers.
![screenshot-live browserstack com-2019 12](https://user-images.githubusercontent.com/819838/70949929-009dd580-2014-11ea-97b6-3c95a560a4d1.png)

### Expected behavior

For the elements to be in the proper order.

### User-facing consequences

The biggest issue is with the quiz status because it says `of 8 questions answered 0` instead of `0 of 8 questions answered`

### Steps to reproduce

1) Create a quiz and start it
2) Sign in as learner
3) View quiz in IE 11 or Edge

### Context

IE 11 and Edge
Kolibri 0.13

**Comment by lyw07** [comment]
fixed in #6415
