### ISSUE TITLE
add ability to name device

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6363]
### Observed behavior

Devices appear to each other in P2P scenarios such as content import, and will eventually appear in KDP.

from @rtibbles 

> ![image](https://user-images.githubusercontent.com/2367265/70954291-6e9cc980-2021-11ea-8165-06f74c6a8f56.png)

Currently, other devices appear as random strings.

### Expected behavior

* Device owners should be able to name their device, both in device settings and during setup
* By default, we might use the OS's network name

### User-facing consequences

Hard to understand which device is which when there are multiple on the network

### Context

0.13.0

**Comment by jonboiser** [comment]
Fixed in #6740 and #6801
