### ISSUE TITLE
unlisted channel indicator should be shown on main channel list page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6365]
### Observed behavior

'unlisted channel' indicator is not shown on the main channel list, but is shown on 'import' page:

| main channel list| import channel list|
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/70959239-83348e00-2030-11ea-8a4e-1c50a0a08a5c.png)|![image](https://user-images.githubusercontent.com/2367265/70959215-73b54500-2030-11ea-9858-aa049723e85f.png)|

### Expected behavior

indicator should be shown on main channel list page

### User-facing consequences

Users investigating the new 'hide unlisted channels' setting have less ability to create expectations about what's happening.

This is particularly important because unlisted channels imported prior to 0.13 will _not_ actually be tracked as unlisted.

### Context

0.13.0

**Comment by jonboiser** [comment]
This should be fixed in #6355. It works for channels downloaded directly from studio. Still haven't checked if it will work if the channel goes from Studio -> Server -> Other Server (via USB or P2p).
