### ISSUE TITLE
maintain order of channels across lists 

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6366]
### Observed behavior

Switching between channel list and import views is a bit confusing because orders are similar but slightly different.

| channel list | import channel list |
|--|--|
| ![localhost_8000_en_device_ (1)](https://user-images.githubusercontent.com/2367265/70959750-e2df6900-2031-11ea-81ca-d07fbc8b7136.png)|![localhost_8000_en_device_](https://user-images.githubusercontent.com/2367265/70959745-dd821e80-2031-11ea-88f9-2e70b23a6681.png)|

### Expected behavior

Expect order on both pages to be consistent. In practice, this would mean bubbling any on-device channels to the top of the import list.

### User-facing consequences

on-device channels look like they went missing, but really just moved down in the list

### Context

0.13.0 beta 7

**Comment by jonboiser** [comment]
Should be fixed in #6446. Thanks @bransgithub!
