### ISSUE TITLE
Lesson completed even before attempting

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#6368]
### Observed behavior
Sometimes in a class when a students open a new lesson, it automatically shows a star mark and completed whereas the student has not even started the exercise.

### Expected behavior
The exercise should show star mark and completed once the student has completed the exercise and attained mastery.

### User-facing consequences
Students are confused as to how could they get star even without attempting the exercise.

### Steps to reproduce
This issue is not consistent and occurs randomly in the classroom. One observation had been, after completing the first lesson and attaining Mastery when the student goes to the next lesson, the correct answers, mainly the green tick marks get carried to the next lesson and it shows star mark. Has been difficult to reproduce this issue everytime, but they do occur

### Star mark in lesson even though the student has not started

![IMG_20191214_124243](https://user-images.githubusercontent.com/8583367/70970966-d0167400-20c5-11ea-97ba-a191b7284d32.jpg)

### Context

 * Kolibri version 12.8
 * Operating system : Xubuntu 18.04
 * Browser Chrome

…

**Comment by miyer03** [comment]
@indirectlylit Please let me know what more clarification is needed to help resolve this. Like I said its not always replicable. And one scenario observered is after completing the first lesson with mastery, when the student goes to the next lesson, the green ticks for the correct answers from the first lesson is carried to the 2nd lesson, which is not started yet and to shows completed with star mark.

**Comment by indirectlylit** [comment]
Hi @miyer03 -

* This issue refers to opening and mastering a lesson, but the screenshot is of an exercise. Is this an exercise within a lesson?
* A short video showing the complete interaction would be helpful
* You could possibly send us a copy of the database or exported interaction logs and indicate the username, lesson name, and exercise name that exhibited the behavior

**Comment by jonboiser** [comment]
@miyer03 Do the Lessons share Resources? For example if you have Lesson A which is the same as Lesson B (they have the same exercises, videos, and so on), then mastering Lesson A also means mastering Lesson B. A video in Lesson A is not considered different from the same video in Lesson B with regard to learner progress.

**Comment by miyer03** [comment]
@jonboiser They are different levels of difficulty under the same topic. For example for grade 7 Ratios.. will have an exercise with Level1 which is kind of easy, Level2 which is kind of intermediate and Challenge set which is kind of difficult. After the student attains Mastery in Level 1, he goes to Level2. This is not about the video lesson. But you can consider them as 2 different sets of exercises under the same topic/chapter

**Comment by rtibbles** [comment]
I believe this may actually be a disguised occurrence of this issue: https://github.com/learningequality/studio/issues/1055

This is not a Kolibri issue, so closing with this back ref.
