### ISSUE TITLE
Star mark shows inside the topic but outside it doesn't

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#6369]
### Observed behavior
When a student completes a lesson, the star mark appears inside the topic, but on existing the topic its doesn't show.

Inside the topic screen shot
![IMG_20191214_122812](https://user-images.githubusercontent.com/8583367/70973430-a8c2a580-20cb-11ea-8a11-97a2bb3ee093.jpg)

Outside the topic screen shot
![IMG_20191214_122823](https://user-images.githubusercontent.com/8583367/70973502-c7c13780-20cb-11ea-86fa-baeebad00898.jpg)

### Expected behavior
Ideally in both the places it should show completed with star mark

### User-facing consequences
Student get confused as to why the star mark is not shown correctly.

### Steps to reproduce
Complete all the lessons in topic and see whether the completed star mark comes. Once that appears, exit the topic to see if the star mark is consistent outside.
…

### Context

 * Kolibri version 12.8
 * Operating system Xubuntu 18.04
 * Browser Chrome

…

**Comment by pcenov** [comment]
@radinamatic - this one is fixed in 0.15.1:
![2022-03-15_10-16-32](https://user-images.githubusercontent.com/79847249/158334949-6ba7c13c-e414-404e-98c8-0e660f929e36.png)

**Comment by radinamatic** [comment]
Thank you, @pcenov, closing!
