### ISSUE TITLE
Mastery log - bad request

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#637]
## Summary

When you navigate through the exercise content enough times (maybe 3-5 times), the exercise content that was once there disappears. When you try to refresh the page, the content is still empty.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-08 at 3 18 07 pm](https://cloud.githubusercontent.com/assets/10454785/20121774/2306e0d6-a5c8-11e6-826b-e2e21e1301a7.png)

![screen shot 2016-11-08 at 3 18 22 pm](https://cloud.githubusercontent.com/assets/10454785/20121778/29e6fbca-a5c8-11e6-857e-9dd880bb04bb.png)

## How to reproduce

1. Log in as a learner
2. Explore > Math > Pre-algebra > Fractions > Multiplying fractions
3. Go through this content several times and sooner or later it'll show up empty.

## Screenshots

![screen shot 2016-11-08 at 3 18 13 pm](https://cloud.githubusercontent.com/assets/10454785/20121788/339651fc-a5c8-11e6-9f31-5a1697663cb4.png)

**Comment by 66eli77** [comment]
I cannot reproduce this issue, @rayykim do you still encounter this issue?
