### ISSUE TITLE
background tasks continue to run after server shutdown

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6374]
### Observed behavior

when I shut down the program with ctrl+c during content import, the server would be shut down, but content import would still continue in the background until it finished

### Expected behavior

content import should be canceled if server has been shut down

### User-facing consequences

users get unexpected content imported to their kolibri

### Errors and logs

…

### Steps to reproduce

1. import a large amount of data (90GB if you are running on a fast network)
2. stop the kolibri program
3. check that server has been shut down by checking port 8080 `lsof -i tcp:8080`
4. check that kolibri process is still running by checking `ps -a | grep kolibri`

### Context

Kolibri version: 0.13.0beta7
Operating system: MacOSX

**Comment by indirectlylit** [comment]
after chatting with @rtibbles we decided to go with an approach like:

* attempt a clean cancel
* if things are still canceling after maybe 10s or so, force kill

**Comment by rtibbles** [comment]
Fixed in #6380
