### ISSUE TITLE
Importing more content (or deleting resources) to a channel undoes its original position in channel list

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6376]
### Observed behavior

~Similar to #5292, if you import more content to a channel, it will always be moved to the bottom of the Device > Channel page even if you had given it a different order (or didn't reorder it but just imported it in the past at some point). Because a lot of places in the app use the same order, we also see #5292~

Edit: This has been resolved for Kolibri when using Sqlite, but when using Postgresl, what seems to happen is that the newly modified channel goes to the _top_ of the list. It's because the channel in this case falls into this branch:

https://github.com/learningequality/kolibri/blob/0ee38838e5fc74d1f85b15c867f53ec4c261448c/kolibri/core/content/utils/annotation.py#L479-L482

~A somewhat mitigating factor is that newly updated channels will temporarily be moved to the top of the channel and have a green "New" label attached to it, so it will be easy to find immediately after the import.~

### Expected behavior

Updating a channel doesn't move it to the ~"bottom"~ top of the channel list.

### User-facing consequences

1. Users will need to move the channel again
1. Users might not immediately realize the channel moved 

### Errors and logs

…

### Steps to reproduce
1. Run Kolibri using Postgresql as DB
1. Run a similar scenario as described above

### Context
Kolibri 0.13

**Comment by jonboiser** [comment]
Unforunately, this unwanted re-ordering issue is still happening when using Postgresql, except that the channel goes to the top of the list.

**Comment by indirectlylit** [comment]
we could open a new issue for the postgres case and tackle it in the next patch if desired

**Comment by indirectlylit** [comment]
migrating additional work to https://github.com/learningequality/kolibri/issues/6560 and re-closing this
