### ISSUE TITLE
h5p content with multiple libraries versions doesn't load

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#6379]
### Observed behavior

This h5p node doesn't load `Server Error (500)`
http://35.185.120.102/en/learn/#/topics/c/6b46831376bf51e5a64f5033e2b07f96

```
  File "/home/kolibri/.pex/install/kolibri-0.13.0b7.dev0+git.9.g143bfeb5-py2.py3-none-any.whl.ec59b00e655c3471bbdd7348652d6317a9f07d65/kolibri-0.13.0b7.dev0+git.9.g143bfeb5-py2.py3-none-any.whl/kolibri/core/content/views.py", line 84, in recursive_h5p_dependencies
    info = zf.getinfo(librarypath)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named u'FontAwesome-4.5/library.json' in the archive"
```

So presumably some H5P library is "requiring" FontAwesome version `4.5`

however,  The h5p file contians only version `4.3` :

```
  inflating: FontAwesome-4.3/FontAwesome.otf
  inflating: FontAwesome-4.3/README.md
  inflating: FontAwesome-4.3/font-awesome.css
  inflating: FontAwesome-4.3/fontawesome-webfont.eot
  inflating: FontAwesome-4.3/fontawesome-webfont.svg
  inflating: FontAwesome-4.3/fontawesome-webfont.ttf
  inflating: FontAwesome-4.3/library.json
```

so we get the error when trying to access.

### Expected behavior

  - The presentation to load using by using whatever version of FontAwesome is available

Source:  https://h5p.org/impressive-presentation

Not sure how the "fallback" mechanism is handled in other h5p implementations, and "find closes version logic" might be out of scope. A quick hack would be simply skipping files that don't exist in the zip.

### User-facing consequences

Certain h5p nodes might not render (not this is the only place I have found this error)

### Steps to reproduce

visit http://35.185.120.102/en/learn/#/topics/c/6b46831376bf51e5a64f5033e2b07f96

### Context

The js libraries are loaded recusively by this code: https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/content/views.py#L82-L89

the line `        info = zf.getinfo(librarypath)` should probably check if `librarypath` exists first.

**Comment by rtibbles** [comment]
This was fixed with special fallback handling in #7989
