### ISSUE TITLE
update perseus plugin with latest translations

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6383]
ref: https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/211

**Comment by jonboiser** [comment]
@rtibbles Does merging learningequality/kolibri-exercise-perseus-plugin#211 resolve this issue? Do we need to bump the version on requirements.txt and release a new version of the perseus plugin?

**Comment by rtibbles** [comment]
I am finalizing the new plugin version now!

**Comment by rtibbles** [comment]
Fixed in #6399
