### ISSUE TITLE
13.0 beta 7, problem while installing 

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#6388]
### Observed behavior
After complete installation the kolibri page 127.0.0.1:8080 is not opening.
![Screenshot from 2019-12-18 12-05-48](https://user-images.githubusercontent.com/8583367/71062960-bfcbcb00-2191-11ea-9799-1abb0139f22d.png)
![Screenshot from 2019-12-18 12-19-44](https://user-images.githubusercontent.com/8583367/71062962-bfcbcb00-2191-11ea-9e22-f6fb21274feb.png)
![Screenshot from 2019-12-18 12-26-42](https://user-images.githubusercontent.com/8583367/71062963-c0646180-2191-11ea-961d-865a1df5257a.png)

### Expected behavior
Kolibri should open and give the login page at 127.0.0.1:8080

### User-facing consequences
Cannot use Kolibri

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/3977049/daemon.txt)

[kolibri.txt](https://github.com/learningequality/kolibri/files/3977050/kolibri.txt)

### Steps to reproduce
Try installing Kolibri using 13.0 beta 7 debian vesion

### Context

 * Kolibri version 13.0 b7
 * Operating system Linux Mint 19.2 Tina
 * Browser Chrome and Firefox

**Comment by miyer03** [comment]
This was done after complete uninstall of the previous version 12.9

**Comment by lyw07** [comment]
I installed the unsigned kolibri 0.13.0 beta 7 Debian installer on a Linux Mint 19.2 VM but was unable to reproduce this issue

**Comment by jonboiser** [comment]
In the logs I'm seeing this error that might explain why there's a blank screen on the browser. I think these are very recent, since they appear at the bottom of daemon.txt.

I'm guessing the JS bundle isn't being built.

```
AttributeError: module 'kolibri.core.webpack.hooks' has no attribute 'WebpackInclusionHook'

```

In the code the main export of this module is called "WebpackBundleHook". But there is an export `WebpackInclusionMixin`? Is there code in the debian packager that's outdated?

**Comment by jonboiser** [comment]
@lyw07 Do you think it's relevant that this was done after uninstalling 0.12.9? That branch does have a `kolibri.core.webpack.hooks.WebpackInclusionHook`, but this was renamed or deleted in the 0.13 branch.

https://github.com/learningequality/kolibri/blob/release-v0.12.x/kolibri/core/webpack/hooks.py#L444

https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/webpack/hooks.py#L415

**Comment by lyw07** [comment]
ah yeah it could be. I will test this on my VM. Thank you for the info!

**Comment by lyw07** [comment]
I tried to install and uninstall 0.12.9 before installing 0.13.0beta7, but the file `/usr/lib/python3/dist-packages/kolibri/plugins/learn/hooks.py` that is causing the error doesn't exist after uninstalling 0.12.9.
I checked both the unsigned debian installer from github and the signed installer from PPA for 0.13.0beta7, but both of them don't contain this file.

**Comment by rtibbles** [comment]
@miyer03 was this server running just Kolibri or also the Kolibri server package? I wonder if uwsgi was still initialized and nginx not properly restarted, and hence looking for non existent python modules from the previous version.

**Comment by miyer03** [comment]
@rtibbles I had kolibri-server running in the system. I tried to uninstall completey by running sudo apt-get remove kolibri-server , sudo apt-get remove kolibri, pip uninstall kolibri and pip uninstall kolibri-server. Please let me know if anything else needed to be done. Since, most of the classroom currently are on 12.8 or 0.9.5b3 any specific steps need to be followed to uninstall the previous version and install the new version when we go to schools so that the DB is not corrupted.

**Comment by jredrejo** [comment]
hi @miyer03 , don't do `pip uninstall kolibri-server` as kolibri-server is not a pip package. 
In any case, in order to try to reproduce it, let me know if I understood correctly the steps you did:

1. You had kolibri-server + kolibri 0.12.9 installed (using deb packages, not pip)
2. You did `apt-get remove kolibri-server kolibri`
3. You installed the kolibri 0.13.0 beta 7 deb package

and then, the package didn't start kolibri and you saw the blank screen in the browser
is it correct?

also , can you try to do `sudo kolibri stop` , `sudo service nginx restart` to ensure there's not a remaining config from `kolibri-server` active, and then `sudo kolibri start`

I will try to reproduce the problem if you can confirm the above steps are correct.

**Comment by miyer03** [comment]
@jredrejo You are correct. I don't think nginx is there in my system now. 12.9 was not completely uninstalled hence tried pip uninstall. I could be wrong there. If you are available now. I can try giving remote access if that works for you to understand better.

Its still showing blank page

**Comment by jredrejo** [comment]
> f you are available now. I can try giving remote access if that works for you to understand better.

I don't think I will have a chance to connect before 15:30 pm GMT. Having a remote access would make it much easier,  would it be possible to access at that time?

**Comment by miyer03** [comment]
@jredrejo @indirectlylit not sure if this is a bug or installation issue. To make sure this doesn't happen could be please highlight the steps if the current server is either using a older version of pex or deb file and also, if it uses the kolibri-server. This is because once we roll out in school, the upgradation happens smoothly and we also don't end up loosing any data.

**Comment by indirectlylit** [comment]
Thanks @miyer03 

Yes we've been testing various upgrade paths to make things smooth, but so far we haven't been able to reproduce this. I'll talk with the team and see if there are any "best practices" we can advise on for upgrading

**Comment by miyer03** [comment]
I am not able to install new kolibri in my system. This is a test server and hence not worried on any previous DB. Is there any way to do a clean install or do I need to reformat the system.

[daemon.txt](https://github.com/learningequality/kolibri/files/4024958/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4024959/kolibri.txt)

**Comment by jredrejo** [comment]
> I am not able to install new kolibri in my system. This is a test server and hence not worried on any previous DB. Is there any way to do a clean install or do I need to reformat the system.
> 
> [daemon.txt](https://github.com/learningequality/kolibri/files/4024958/daemon.txt)
> [kolibri.txt](https://github.com/learningequality/kolibri/files/4024959/kolibri.txt)

Hello @miyer03  about your latest message, looking at the logs I see two problems:
1. Permissions problems in the` /home/kolibri/.kolibri` folder
2. The installation is upgrading the configs from a previous beta to the stable release, and it can't, likely due to the permission problems

If you're not worried for a previous db, can you delete the ` /home/kolibri/.kolibri` and restart the daemon or the application so it creates a new config folder from scratch?

**Comment by miyer03** [comment]
I dropped kolibri, deleted the folder and started kolibri but still the same issue.  I tried to restart both kolibri and kolibri-server.
![Screenshot from 2020-01-09 10-53-14](https://user-images.githubusercontent.com/8583367/72040345-49bd0e80-32ce-11ea-9cf0-8a95a43784db.png)


[daemon.txt](https://github.com/learningequality/kolibri/files/4038692/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4038693/kolibri.txt)

**Comment by lyw07** [comment]
thank you so much @miyer03 for checking and helping us debug the issue!
In the log file, I see this:
```
 File "/usr/lib/python3/dist-packages/kolibri/dist/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/usr/lib/python3.6/import-lib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./kolibri/plugins/learn/templatetags/learn_tags.py", line 21, in <module>
    from .. import hooks
  File "./kolibri/plugins/learn/hooks.py", line 8, in <module>
    class LearnSyncHook(webpack_hooks.WebpackInclusionHook):
AttributeError: module 'kolibri.core.webpack.hooks' has no attribute 'WebpackInclusionHook'
```
The issue still comes from the file `./kolibri/plugins/learn/hooks.py`, which existed in 0.12.x versions but has been deleted in 0.13.0. but the version in the log file did indicate that you installed 0.13.0.

Do you mind checking the result of the following command?
```
ls -l /usr/lib/python3/dist-packages/kolibri/plugins/learn/
```
Also what is the output when you run
```
> python3.6
>>> import kolibri
>>> kolibri.__file__
>>> kolibri.__version__
```
thank you!

**Comment by miyer03** [comment]
Hi @lyw07 attached the screen shot with the output. Have tried to install kolibri server

![image](https://user-images.githubusercontent.com/8583367/72128865-4abb7200-339a-11ea-8937-c77469df00fb.png)

**Comment by lyw07** [comment]
thank you! with this, we can confirm that although the version says 0.13.0, somehow part of the code is still 0.12.9.
I tried with installing kolibri 0.13.0 directly on top of 0.12.9, but still unable to reproduce the error.

do you mind trying uninstall kolibri and install it again with the following steps?
```
sudo apt-get purge kolibri
ls -l /usr/lib/python3/dist-packages/kolibri    <-- to check whether kolibri package has been fully removed
sudo dpkg -i kolibri_0.13.0-0ubuntu1_all.deb (or any kolibri installation you would prefer)
```
please let us know if you continue to see the issue. thank you so much for your patience!

**Comment by miyer03** [comment]
@lyw07 for the last step I need to download the package from the website, correct ? Also will the steps remove kolibri-server as well

**Comment by lyw07** [comment]
@miyer03 I'm sorry I forgot that you also have kolibri-server installed. Then step one would remove kolibri as well as kolibri-server at the same time. Do you have any configurations on kolibri-server that you need to save? 
in this case, the last step would be `sudo apt-get install kolibri-server`.
sorry for the confusion

**Comment by miyer03** [comment]
Screenshots after the first 2 steps 
![Screenshot from 2020-01-10 11-51-58](https://user-images.githubusercontent.com/8583367/72130740-645fb800-33a0-11ea-9bfa-f2bcbfcbc0b1.png)
![Screenshot from 2020-01-10 11-55-47](https://user-images.githubusercontent.com/8583367/72130741-645fb800-33a0-11ea-9209-f73d36dee342.png)

**Comment by lyw07** [comment]
could you try
```
pip3 uninstall kolibri
```
or if that doesn't work
```
sudo pip3 uninstall kolibri
```
does either of these command remove that folder?

**Comment by miyer03** [comment]
Attached the screenshot. Would you be comfortable with remote access. I can try giving you that now if that works.
![image](https://user-images.githubusercontent.com/8583367/72131138-69713700-33a1-11ea-8395-487cdb3c7494.png)

**Comment by lyw07** [comment]
sure that works for me :)

**Comment by miyer03** [comment]
@lyw07 could you help me with the steps and the your email id. my email is manoj.iyer@motivationforexcellence.org

**Comment by lyw07** [comment]
@miyer03 oh I'm sorry I can't recall the steps using things such as teamviewer right out of my mind currently.
instead of letting me access to your server remotely, do you mind trying one last thing `sudo rm -rf /usr/lib/python3/dist-packages/kolibri` and check if you can successfully remove the folder? since we have uninstalled kolibri entirely, it should be safe to remove it.

**Comment by miyer03** [comment]
Here is the screen shot
![image](https://user-images.githubusercontent.com/8583367/72131669-efda4880-33a2-11ea-8962-d5ccab4d85d5.png)

**Comment by lyw07** [comment]
thank you! I have sent you an email with steps to allow me to access your server remotely. My email is lingyi@learningequality.org

**Comment by miyer03** [comment]
thanks @lyw07 for helping install kolibri

**Comment by indirectlylit** [comment]
@lyw07 would you mind posting a short summary of what the problem was

**Comment by lyw07** [comment]
@indirectlylit I'm sorry I'm not too sure what caused the problem, but the issue was that when 0.13.0 was installed, the old version of 0.12.9 was uninstalled uncleanly with `sudo apt-get purge kolibri`. To resolve this issue, I uninstalled 0.13.0, removed the remaining kolibri files for 0.12.9 in `/usr/lib/python3/dist-packages/kolibri` and reinstalled kolibri 0.13.0.

I'm not able to reproduce this error when upgrading from 0.12.9 to 0.13.0 on my Linux Mint VM though

**Comment by indirectlylit** [comment]
thank you!
