### ISSUE TITLE
Exercise preview panel is not inside a KPageContainer

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6395]
### Observed behavior
Just noticed this on kolibribeta: The quiz preview section should have the KPageContainer surrounding it to match the Lesson Creation workflow.

![Screen Shot 2019-12-18 at 3 45 29 PM](https://user-images.githubusercontent.com/10248067/71132887-a2a4f580-21ad-11ea-8ba7-49b3d21d107d.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
ref https://github.com/learningequality/kolibri/pull/6391#discussion_r359636505
