### ISSUE TITLE
In many KA Videos, the transcript will flash text in a different language before the default one

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6397]
### Observed behavior
Here's a video: transcripts flash in a different language (looks like a Chinese language to me, but I've seen it flash in Cyrillic, Thai, Hebrew, etc.) before settling on English. Video comes from http://kolibribeta.learningequality.org/en/coach/#/30520f6b451e2a0ab7a56a3a9896a97f/plan/lessons/f428348d9ad203099ec983e443e4f47d/selection/preview/b34d1597055b5022a44714c11b7d29be

![Kapture 2019-12-18 at 16 15 58](https://user-images.githubusercontent.com/10248067/71134080-c833fe00-21b1-11ea-8756-5962c9873d22.gif)

I'm guessing KA is more prone to this because its videos are localized to more languages. I haven't seen this on Touchable earth whose videos usually only have transcripts in 0-3 languages.

I think that the initial flash is from the language that is first in the language list too.

### Expected behavior

Transcripts don't change their text after the component mounts.

**Comment by jonboiser** [comment]
Fixed in #6476. Thanks @bransgithub!

**Comment by indirectlylit** [comment]
@bransgithub feel free to submit a PR adding yourself to https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md

**Comment by indirectlylit** [comment]
whoops, I see you already did that - nice!
https://github.com/learningequality/kolibri/pull/6476/files#diff-a8b2df7fd69554249528b6ce108f533bR66
