### ISSUE TITLE
Broken "Next Content" button on last content 

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#640]
## Summary

When you master the last exercise content in the topic folder, the "Next Content" button appears along with this error.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-09 at 3 03 24 pm](https://cloud.githubusercontent.com/assets/10454785/20158357/9c345738-a68e-11e6-977d-d515895a85a8.png)

## How to reproduce

1. Login as a learner
2. Explore > Math > Pre-algebra > Fractions > Dividing unit fractions and whole numbers > Dividing unit fractions by whole numbers 2

## Screenshots

![screen shot 2016-11-09 at 3 53 29 pm](https://cloud.githubusercontent.com/assets/10454785/20159313/b2effbac-a694-11e6-9f66-1c2571a51735.png)

**Comment by rayykim** [comment]
UX suggestion: replace "Next Content" button with another one that allows you to move onto the next topic folder

**Comment by 66eli77** [comment]
fixed here https://github.com/learningequality/kolibri/pull/649
