### ISSUE TITLE
prevent Perseus z-indexes from interacting with app styling

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6404]
### Observed behavior

ref: https://github.com/learningequality/kolibri/pull/6396

we had to set a very high, arbitrary z-index value

### Expected behavior

z-indexes should map to Material elevations - https://material.io/design/environment/elevation.html#default-elevations

to achieve this we can either put perseus in an iframe, or update the styling to conform with Material conventions

### User-facing consequences

occasional bugs, code maintenance burden

### Context

0.13.0

**Comment by rtibbles** [comment]
Best fixed by putting Perseus in an iframe.

**Comment by rtibbles** [comment]
We no longer appear to need this magic z-index, so going to close this as resolved.
