### ISSUE TITLE
Fulfulde language should not be 'Undetermined'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6405]
### Observed behavior

I'm guessing there must be an improper language code or similar somewhere that makes Fulfulde appear as `Undetermined` when channel is imported. I don't recall seeing this on any other KA channel:

![2019-12-18_16-02-06](https://user-images.githubusercontent.com/1457929/71144295-d28be180-221d-11ea-89d7-00b16bbc3110.png)

Since it's appearing on channel description, I'm doubting if this is a Kolibri issue at all...? 🤔 
cc @ralphiee22 

### Expected behavior
Language name being properly rendered.

### User-facing consequences
Incorrect channel description that looks like a broken code.

### Errors and logs
…

### Steps to reproduce
Import KA Fulfulde channel (`huluf-fapiz`).

### Context
 * Kolibri version: 0.13.0b7 
 * Operating system: all
 * Browser: all

**Comment by radinamatic** [comment]
On this version 2 of the channel that I have on my dev env VM, language is rendered properly... 🤔 

![2019-12-19_5-58-52](https://user-images.githubusercontent.com/1457929/71146372-509fb680-2225-11ea-9827-1f4e7f99020d.png)

**Comment by indirectlylit** [comment]
I'm guessing this is an upstream content issue

**Comment by radinamatic** [comment]
Filed an issue on the KA sushi chef repo: https://github.com/learningequality/sushi-chef-khan-academy/issues/16

**Comment by jonboiser** [comment]
This is an upstream issue with how the description for KA Fufulde is generated.
