### ISSUE TITLE
no bash prompt after Kolibri exits

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6407]
### Observed behavior

hang on 'Waiting for child threads to terminate...'

I waited for a few minutes. However then I pressed 'enter' and the process actually seemed like it had finished.

Looks sort of like the behavior described here: https://stackoverflow.com/questions/23125527/how-to-return-to-bash-prompt-after-printing-output-from-backgrounded-function

### Expected behavior

prompt shown after full exit

### User-facing consequences

user will not know that process has actually exited and might sit there waiting 

### Errors and logs

```
^CINFO     ENGINE Caught signal SIGINT.
INFO     ENGINE Bus STOPPING
WARNING  SCHEDULECHECKER shut down event received; closing.
INFO     Kolibri instance '211d7b3fd94d8fb8908e8014513318ac' has left the zeroconf network.
WARNING  JOBCHECKER shut down event received; closing.
WARNING  JOBCHECKER shut down event received; closing.
(k013x) d@slate ~/P/l/k013x (release-v0.13.x) [130]> INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
INFO     ENGINE Caught signal SIGINT.
INFO     ENGINE Bus STOPPING
INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
INFO     ENGINE Waiting for child threads to terminate...
```

### Steps to reproduce

kill server with ^C 

### Context

0.13.0

**Comment by lyw07** [comment]
I'm not able to reproduce this with 0.13.0 pex file. Does this still happen on your machine? Thank you!

**Comment by indirectlylit** [comment]
yes, I still reproduce, but I'll de-prioritize if not everyone sees it

**Comment by jonboiser** [comment]
@lyw07 This seems to happen more consistently when using the devserver `yarn run devserver-hot`. When running the server from the PEX, like you said, the shell prompt is restored after the `ENGINE Waiting for child threads to terminate...` log.

**Comment by lyw07** [comment]
thank you for the information!

**Comment by rtibbles** [comment]
No longer replicates due to zeroconf fixes.
