### ISSUE TITLE
multiple instances of Kolibri can access the same DB at the same time

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6408]
### Observed behavior

I am able to run both a pex and an app on MacOS simultaneously

### Expected behavior

The second Kolibri instance should fail to start with an error that another instance appears to already be running.

One way to achieve this would be for Kolibri to periodically write timestamps to a file like `$KOLIBRI_HOME/heartbeat.txt`. Whenever a new instance of Kolibri starts, it would read this file and error out if the most recent timestamp is within some threshold of the current time (e.g. 30 seconds).

### User-facing consequences

more likely to get situations like https://github.com/learningequality/kolibri/issues/6334

### Context

0.13.0

**Comment by rtibbles** [comment]
Our current sanity check only checks same port, it would be relatively straightforward to extend this to check for Kolibri running on any port (without having to add anything new).

**Comment by rtibbles** [comment]
Fixed in #6412
