### ISSUE TITLE
pin mac app

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6409]
### Observed behavior

builds currently track the HEAD of the mac repo

ref: https://github.com/learningequality/kolibri-installer-mac/issues/42

### Expected behavior

0.13.0 final should be pinned to a specific version of the mac app, creating predictable builds

### User-facing consequences

unpredictable builds

### Context

0.13.0

**Comment by indirectlylit** [comment]
It is not pinned, but v0.1.0 was tagged here: https://github.com/learningequality/kolibri-installer-mac/releases/tag/v0.1.0

We just need to be careful because the kolibri app still tracks the head of that repo

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/8935
