### ISSUE TITLE
IndividualLearnersSelector strings were not pushed to Crowdin

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6417]
### Observed behavior

The CSV for the coach module that was uploaded to Crowdin did not include the IndividualLearnersSelector component's new strings.

This PR was made to ensure they'd be included: https://github.com/learningequality/kolibri/pull/6055

But they are not currently on Crowdin.

If I run `yarn makemessages` now the strings are included in the CSV - so the extraction appears to work as expected.

If you go to Crowdin and the 0.13 branch - then to Settings - then to the `coach` module row and go to the little dots menu on the right end of the row you can download the CSV that was uploaded.

### Expected behavior

Strings should have been included in the upload to Crowdin before string freeze.

### User-facing consequences

The strings in the Invidual Learners Selector component will all be in English.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by bjester** [comment]
Is it possible that it wasn't included because in that PR your component wasn't being used by anything?

**Comment by nucleogenesis** [comment]
That's what it is @bjester 

I created a new component and extracted messages and it didn't show up.

Once I imported it into another component and ran the message extraction, the messages showed up.

**Comment by bjester** [comment]
Dang. I should have tested that before approving that PR. I had no idea.

**Comment by jonboiser** [comment]
Uploaded the new strings by running Kolibri with #6449. They appear to be up on the 'release-v0.13.x' Crowdin version

<img width="697" alt="Screen Shot 2020-01-09 at 11 21 24 AM" src="https://user-images.githubusercontent.com/10248067/72097948-56dbfc80-32d2-11ea-9422-a5aa2a39b54b.png">

But it also seems to add new namespaces of strings for the H5P plugin, and completely renames the Perseus plugin namespace (see the sections with 0% translated). There also seem to be new strings in the "device" namespace.

<img width="1376" alt="Screen Shot 2020-01-09 at 11 20 36 AM" src="https://user-images.githubusercontent.com/10248067/72097991-7115da80-32d2-11ea-9aca-291be3a176e5.png">

**Comment by indirectlylit** [comment]
this is done
