### ISSUE TITLE
required .mo files are not being added

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6426]
### Observed behavior

we had a critical last-minute issue because some languages were not showing up. This was because the .mo files were not being added, which is an error-prone process:

https://kolibri-dev.readthedocs.io/en/develop/i18n.html#adding-a-newly-supported-language

### Expected behavior

Let's figure out a system that will add mo files and complain loudly if they are not there

### User-facing consequences

Challenging, obscure bugs and missing langs

### Context

0.13.0

**Comment by jonboiser** [comment]
@rtibbles @ralphiee22 Can we add a unit test to check for the `mo` file for the relevant languages?

**Comment by rtibbles** [comment]
I think so - would just need to check the ones listed in EXTRA_LANGS info.

**Comment by indirectlylit** [comment]
this has been addressed by adding all mo files
