### ISSUE TITLE
Yoruba not always displaying using Noto fonts

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6427]
### Observed behavior

observed by @jonboiser  that Yoruba displays in a mix of Helvetica and Noto:

![image](https://user-images.githubusercontent.com/2367265/71300849-a2dbf700-234d-11ea-93a6-156ecb54a446.png)

![image](https://user-images.githubusercontent.com/2367265/71300843-98216200-234d-11ea-858e-21a54e2534e0.png)

![image](https://user-images.githubusercontent.com/2367265/71300845-9ce61600-234d-11ea-8675-5f85bf7d49f2.png)

### Expected behavior

fonts are all noto

### User-facing consequences

less pleasant typography

### Context

0.13.0

**Comment by jonboiser** [comment]
This doesn't look like an issue right now. This might have been caused by a similar font files issue that was causing problems with our South and South East Asian locales in 0.14.5.
