### ISSUE TITLE
sign-out button is incorrectly aligned in RTL langs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6428]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/71301121-62ca4380-2350-11ea-9091-f16749150632.png)

![image](https://user-images.githubusercontent.com/2367265/71301123-665dca80-2350-11ea-8582-e0903413ddcb.png)

### Expected behavior

correct alignment 

### Context

0.13.0

**Comment by jonboiser** [comment]
Should be fixed in #6431
