### ISSUE TITLE
Occasional console error in Learn page 

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#643]
## Summary

When you navigate through several video or exercise content on the Learn page, the console error shows up in dev tools. It doesn't affect the UX/workflow in content but still displays console errors.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## Traceback or relevant snippet from server.log or browser console

![screen shot 2016-11-10 at 12 06 28 pm](https://cloud.githubusercontent.com/assets/10454785/20192307/277bf1e8-a73e-11e6-95c9-58a406b7dbea.png)

## How to reproduce

1. Login as learner
2. Go to Learn page and click on any video content
3. Then click back button and go to another video or exercise content couple times and the error will show up.

**Comment by indirectlylit** [comment]
cannot reproduce - may have been fixed?
