### ISSUE TITLE
Port availability check fails when using socket activation

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#6434]
It is possible to run Kolibri as a socket-activated system service on Linux, using configuration such as this:

https://github.com/endlessm/eos-kolibri/tree/master/data/system

The way socket activation works here is systemd creates a socket with a certain port number, then passes the socket to Kolibri when it receives a connection. CherryPy knows how to use that socket, instead of trying to create its own.

This works well, except that Kolibri's start script checks for port availability on its own, effectively bypassing CherryPy's socket activation support:

https://github.com/learningequality/kolibri/blob/7312a5353021a22fc7b9701468e470cba5e1c62b/kolibri/utils/cli.py#L439

https://github.com/learningequality/kolibri/blob/7312a5353021a22fc7b9701468e470cba5e1c62b/kolibri/utils/sanity_checks.py#L18

As a result, Kolibri fails to start, claiming that the port is already in use. (It is in use, but that's with a socket that has been passed to Kolibri).

I have been working around this by simply patching out the sanity check in my case since we're launching Kolibri with a wrapper script that takes care of it (https://github.com/learningequality/org.learningequality.Kolibri/pull/2), but an implementation which either uses CherryPy to check port availability, or takes into account socket activation itself (http://0pointer.de/blog/projects/socket-activation.html), might be a better approach.

**Comment by indirectlylit** [comment]
thanks for the report

**Comment by indirectlylit** [comment]
@dylanmccall this should be addressed by the change @lyw07 made in #6436, and will be included in 0.13.1

Feel free to give it a try!
