### ISSUE TITLE
ping happens every second instead of every 15 minutes

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6439]
### Observed behavior

When the internet is not available and ping fails, kolibri keeps pinging every second.

### Expected behavior

as stated in the error message, kolibri should ping every 15 minutes

### User-facing consequences

users who have constant unstable network connections would see a lot of warning messages in the log file. 

### Errors and logs

```
INFO     ENGINE Serving on http://0.0.0.0:8080
INFO     ENGINE Bus STARTED
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
```

### Steps to reproduce

1. turn wifi off
2. run `kolibri start`

### Context

Kolibri version: 0.13.0

**Comment by rtibbles** [comment]
Hrm - that's troubling - what does your `job_storage` sqlite3 file look like in the scheduled jobs table?

**Comment by lyw07** [comment]
the table is this:

<img width="693" alt="Screen Shot 2020-01-07 at 2 58 48 PM" src="https://user-images.githubusercontent.com/19424916/71936474-5d496780-315e-11ea-8503-83503d3013dd.png">

**Comment by rtibbles** [comment]
Was Kolibri running when you looked at this? If so, what time did you look at it?

**Comment by lyw07** [comment]
yes, kolibri was running when I looked at this. it was a fresh install of kolibri 0.13. the time I looked at it was around the scheduled time of the first job I believe.

**Comment by rtibbles** [comment]
Had the ping already failed at that time?

**Comment by rtibbles** [comment]
The only thing I can think of is that somehow this line is setting a date in the past: https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/analytics/utils.py#L437

**Comment by lyw07** [comment]
yes the ping failed multiple times. I tried to log out some debug messages and got these:
```
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
INFO     15
INFO     900
INFO     2020-01-07 14:35:21.266781 <--- datetime.datetime.now()
INFO     2020-01-07 14:50:21.267046 <--- datetime.datetime.now() + datetime.timedelta(seconds=checkrate * 60)
2020-01-07 14:50:21.273858 <--- date_time value in `change_execution_time`
INFO     ENGINE Serving on http://0.0.0.0:8080
INFO     ENGINE Bus STARTED
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
INFO     15
INFO     900
INFO     2020-01-07 14:35:21.965858
INFO     2020-01-07 14:50:21.966063
2020-01-07 14:50:21.970362
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
INFO     15
INFO     900
INFO     2020-01-07 14:35:22.688755
INFO     2020-01-07 14:50:22.688881
2020-01-07 14:50:22.693611
WARNING  Ping failed (could not connect). Trying again in 15 minutes.
INFO     15
INFO     900
INFO     2020-01-07 14:35:23.405584
INFO     2020-01-07 14:50:23.405730
2020-01-07 14:50:23.411099
```
the date and time looks correct to me...
my guess is that after we change the scheduled time of the job, it doesn't get updated correctly in `change_execution_time`

**Comment by lyw07** [comment]
sorry for the message I posted above:
> the time I looked at it was around the scheduled time of the first job I believe.

it should be around 15 minutes before the scheduled time indicated in the picture. I didn't check the time correctly.
so the database value is correct.

**Comment by rtibbles** [comment]
My other guess is that the scheduler thread is picking up the same job repeatedly and putting it into the queue.

**Comment by rtibbles** [comment]
But, I feel like that shouldn't be happening as it's a single thread....

**Comment by lyw07** [comment]
the issue is from here: https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/tasks/scheduler.py#L240

**Comment by lyw07** [comment]
since it's running on my local machine, it's comparing a utc now with pacific time now, so the scheduled time is always in the past of "now"

**Comment by rtibbles** [comment]
Ah - can you submit a fix to make sure the scheduler only uses UTC time throughout?

**Comment by lyw07** [comment]
sure I will do that!
