### ISSUE TITLE
Device page buttons alignment issue on IE11 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6442]
### Observed behavior
Buttons are not aligned at the `device channel` page, using IE11 browser.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
Observe that the options and import buttons are not aligned in the channels label
![Screen Shot 2020-01-08 at 11 23 57 AM](https://user-images.githubusercontent.com/8663934/71948598-78be7c00-320b-11ea-8bbb-ac9533763856.png)

This is the display on Firefox 72. 
![Screen Shot 2020-01-08 at 11 39 43 AM](https://user-images.githubusercontent.com/8663934/71948779-2467cc00-320c-11ea-924c-3ab231aaf35f.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0b8
 * Operating system: Windows 7
 * Browser: IE11

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
