### ISSUE TITLE
Select resources text broken on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6443]
### Observed behavior
Select resources text did not display the full length on IE11 browser.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![Screen Shot 2020-01-08 at 11 59 20 AM](https://user-images.githubusercontent.com/8663934/71949583-0780c800-320f-11ea-95c0-beb016b5d95a.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

**Comment by jeepurs** [comment]
I may have seen a related bug, in the form of the button hanging off the border of the expected square.

UN Women country server (Mexico): https://mexico-kolibri.mylearningpathway.org
Browser: Chrome 77.0.3865.75
Version: v0.12

I see this bug when I open developer tools and the window is reduced:

![image](https://user-images.githubusercontent.com/5150483/73578756-47655480-4435-11ea-8204-1e937c0676fa.png)

**Comment by jonboiser** [comment]
Fixed in #6506 by giving the "select resource" button more room in the card, so it can grow into the card instead of into the right overflow area.

**Comment by radinamatic** [comment]
Apparently the cards in other languages are more greedy, and the above wasn't _enough_ room. 

![Win7 (new start)  Running  - Oracle VM VirtualBox_303](https://user-images.githubusercontent.com/1457929/74160994-9160ee00-4c1e-11ea-8701-ce57b68bcd4b.png)

**Comment by jonboiser** [comment]
@nucleogenesis I think maybe using the flex-grow for that cell approach might be best for this button if there's no optimal width for this element.

**Comment by jonboiser** [comment]
@radinamatic Do you think french is has the longest message for this particular button? We can just keep allocating more space in the min-width rule for the button to accommodate french.

**Comment by radinamatic** [comment]
I checked all the languages, @jonboiser, and French and Brazilian Portuguese are the only ones that are cut out.

 
![Win7 (new start)  Running  - Oracle VM VirtualBox_308](https://user-images.githubusercontent.com/1457929/74260748-5e8c2800-4cfa-11ea-9c45-664759ac1642.png)

**Comment by jonboiser** [comment]
@radinamatic Thanks for going through all the languages. I think the initial solution was the least invasive, but I'm going to have to make a bigger change to the layout so it works for all languages.
