### ISSUE TITLE
Import percentage alignment issue on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6447]
### Observed behavior
Channel import percentage label not aligned properly on IE11

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![Screen Shot 2020-01-09 at 3 01 10 PM](https://user-images.githubusercontent.com/8663934/72048110-05923400-32f7-11ea-9d58-1e07c0a855fd.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

**Comment by jonboiser** [comment]
@mrpau-richard Do you remember if the percentage looks correct if it's only in the single digits (e.g. 5%)? I'm noticing on newer browsers that the progress bar will actually shorten to make more room when the progress goes from e.g 9% to 10%. That must not be happening with IE11, so maybe we'll need to add a hack like adding a non-breaking space between the number and the percentage, or give the percentage a fixed width.

**Comment by mrpau-richard** [comment]
>@mrpau-richard Do you remember if the percentage looks correct if it's only in the single digits (e.g. 5%)?

Still the same display with a single digit percentage @jonboiser and that is the alignment of the  progress bar at the first it show up.
![Screen Shot 2020-01-17 at 1 07 24 PM](https://user-images.githubusercontent.com/8663934/72585869-9c2fa800-392a-11ea-8a50-e4c840cc4389.png)
