### ISSUE TITLE
Channel scrollbar issue on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6453]
### Observed behavior
Channel scrollbar not showing on IE11 until I refresh the page.

### Expected behavior
Scrollbar should show automatically without a page refresh.

### User-facing consequences

…

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/72239327-a0eb1800-361b-11ea-9a7f-246da7d72a79.gif)

### Steps to reproduce

…

### Context

 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
