### ISSUE TITLE
Disabled arrows button can click on Microsoft edge browser

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#6454]
### Observed behavior

In Facility > users page, I tried to click the disabled arrow button and its goes to next.
![arrow_button2](https://user-images.githubusercontent.com/38421180/72239477-2373d780-361c-11ea-930a-3390042b33fc.gif)
 

### Expected behavior

The disabled arrow button must be not click.
### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Sign as super admin or admin facility
2. Go to Facility > Users page
3. Click the disabled arrow button

### Context

Tell us about your environment, including:
  Kolibri version : 0.13.0
  Operating system: Windows 10 Pro 2015
  Browser: Microsoft Edge 20.10240.16384.0

**Comment by jonboiser** [comment]
@mrpau-julius Are you able to reproduce this bug on any versions of IE11?

I don't have access to a version of Edge this old, and it doesn't reproduce on the latest versions.

There is a similar bug where if type in filter in the search box and there are no results, the arrow buttons will be not be disabled and you can click them. I will try and see if fixing that bug will also fix this one.

**Comment by mrpau-julius** [comment]
@jonboiser  On my IE11 2015, the Kolibri cannot run. I think it's another issues on Window 10 pro 2015.
![cant_IE11_2015_on_windows10](https://user-images.githubusercontent.com/38421180/72319993-a7d95f80-36db-11ea-9b4b-73efd5b9fd31.png)

**Comment by jonboiser** [comment]
This might be similar to #6444 , where events are being emitted even when the emitting element is "disabled" (or in the setup wizard case, a completely different element is emitting the event). We'll need to be more defensive about this.

#6458 should fix this by adding a guard against going outside of the allowable page range even if a disabled arrow button is emitting "click" events.
