### ISSUE TITLE
missing breadcrumbs

### ISSUE THREAD

**Issue by rayykim** [learningequality/kolibri#646]
## Summary

When you navigate to one of the lower levels of the breadcrumb, the breadcrumb disappears.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: develop
 - Operating system: mac
 - Browser: chrome

## How to reproduce

1. Login as Learner
2. Go to Explore Page
3. Choose a folder and go through each level of the breadcrumb.

## Screenshots

![disappearing breadcrumb](https://cloud.githubusercontent.com/assets/10454785/20196971/04fcd3d0-a752-11e6-8c4e-3b48a0e4f319.gif)

**Comment by radinamatic** [comment]
Had the same thing happen on my new dev repo yesterday and thought it a fluke, but apparently not...
Ubuntu 16.10, Python 3

**Comment by 66eli77** [comment]
seems get fixed in the latest develop branch.
