### ISSUE TITLE
KaLite vs Kolibi Data Size

### ISSUE THREAD

**Issue by frankarl** [learningequality/kolibri#6461]
why Kalite folder takes 81 GB and Kolibri only 17 GB ??

Maybe obvious but I am new user.

Thanks
…

**Comment by frankarl** [comment]
in spanish versions

**Comment by indirectlylit** [comment]
Hi @frankarl – thanks for taking the time to sign up for github!

In the future, I'd recommend [posting in our community forums](http://community.learningequality.org/) to ask these sorts of general questions.

A lot has changed between KA Lite and Kolibri, so it's hard to make direct comparisons without more information. Are you referring to the size of the Khan Academy channel? Which specific directories are you comparing?

**Comment by frankarl** [comment]
Hi Devon,

Yes I am kinf of a novice with Kolibri and did not make myself very clear. Mi Content folder in Kalite is 81 GB and the Content Folder in Kolibri in both cases both for Spanish Khan is only 17 GB.

Thanks a lot. I also notice a great difference between the content directories in Kolibri between the Spanish and English versions.

We have been retained to install Khan with Kolibri in 150 schools in Colombia and want to make sure we get the right sized USB drives.

Will make sure I go to the Community forum next time.

Thanks

Frank

**Comment by indirectlylit** [comment]
Yes, I'm showing the following sizes:

| Spanish | English |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/72315090-5337d500-3646-11ea-80d4-2d9632db5a06.png) |![image](https://user-images.githubusercontent.com/2367265/72315098-5af77980-3646-11ea-8523-d5727f119801.png)|

Some of our size calculations have been updated in 0.13.0, so I would recommend actually exporting the content onto a large disk and double-checking the accuracy before purchasing many smaller USB sticks. If you see any discrepancies with these values, please feel free to open a new github issue about that here.

As far as the difference with KALite, the videos are likely compressed differently. I would mainly browse through the content and do a sanity check that the resources you expect to see are generally there.

good luck!

**Comment by frankarl** [comment]
Hello Devo,

We do agree completely on the sizes and my main question is “why” of such a major discrepancies not only between Kalite and Kolibri which ia astronomical, from 17 to 81 GB but between Spanish and English in Kolibri when the size differential for both languages in Kalite was minimal. I do not know if there is a compression difference, but if the number of videos is the same a 5:1 ratio is astonishing.

Thanks a lot

Frankarl

**Comment by rtibbles** [comment]
Hi @frankarl - I think the main explanation for this difference is that over the years, Khan Academy has added a huge amount of new video content in English, most of which we now distribute over Kolibri (but we have not been updating the content packs for KA Lite for some time now).

In contrast, the amount of new Spanish content in that same period is not that big, so our compression has reduced the apparent size of Spanish content, while only just keeping the size of the ever growing KA English library in check.

**Comment by frankarl** [comment]
Hello Richard,

If there are more videos in Kolibri than KaLite, then the 81 GB KALite vs 17 GB Kolibri is still more perplexing.

Thanks

**Comment by rtibbles** [comment]
The Spanish content is smaller in Kolibri because we have done a lot more video compression to reduce the size. The number of videos in Spanish has probably not changed that much.

It is only in English that the number of videos has increased, but we have stopped it ballooning by compressing them more.

**Comment by frankarl** [comment]
Thanks a lot Richard, mystery solved !!!!!
