### ISSUE TITLE
Display the Python version where Kolibri server is running

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6462]
### Observed behavior
During the testing it's good to know on what Python version i'm running on the Kolibri server, This also helpful when it comes on reporting and debugging an issue.

Some operating Systems had a multiple pre installed Python version, and it's difficult to pinpoint on what version that Kolibri use to run.

### Expected behavior
I expect to display the Python version at the Device info page or at the kolibri benchmark command output.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
cc @jredrejo as the `benchmark` command is his baby :wink:

**Comment by jredrejo** [comment]
Thanks, I will take care of adding it

**Comment by indirectlylit** [comment]
thanks for the recommendation @mrpau-richard - good idea.
