### ISSUE TITLE
Add a simpler method to handle non-linear navigation in Immersive Pages (e.g. exiting and going "back")

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6468]
### Observed behavior

Because Kolibri uses the navigation-scarce UI variant (often called "Immersive Pages") in a lot of places, we often need to append parameters like `?last`, `?last_id`, `?searchTerm` into the URL to maintain the previous location, so that the one or two navigational elements on the page (usually an "X", "<-" button on the top navigation or "Exit..." link on the bottom) mimics the Browser back button and goes to the right location.

For various reasons, these query parameters need to be manually managed and be added, removed, or kept as users navigate to different locations. It also causes a lot of coupling, as different components must be aware of these query params (see for example `LessonResourceSelectionPage/index`).

For example, in the Lesson Resource Management workflow we start at the Selection Topic Page (some topic in a channel)

There are three transitions possible here:

1. Click a another topic
1. Click a resource to preview it
1. Click "Finish" or the "X" button
1. Initiate a search

If you initiate a search, there are two possible transitions

1. Exit search (needs to store last topic ID)
1. Do a new search (same)
1. Filter the search (same, plus adds new query params)
1. Go into a topic (same)
1. Preview a resource (same, plus needs to store search term)

And so on. At each of these transitions, we are in the same Immersive style Page, but the "exit" behavior changes and needs to be derived from the extra query params).

It might be possible is to externalize this navigation logic into a state machine (implemented in Vuex or through VueRouter guards) so that the components don't need to know so much about this navigation flow and can use a simpler interface like "exit" or "go to next thing".

**Comment by nucleogenesis** [comment]
I believe that this is no longer going to be an issue with the CoreBase refactor as each page to which we navigate in an Immersive context will define its own back/close behavior as it wraps itself in an ImmersivePage
