### ISSUE TITLE
Coach resources items display issue 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6469]
### Observed behavior
Coach resources items display issue on exam reports page. The icon did not align to the exam item.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![Screen Shot 2020-01-16 at 10 32 09 AM](https://user-images.githubusercontent.com/8663934/72489265-80ef6a80-384e-11ea-8467-b138a54a0619.png)
![Screen Shot 2020-01-16 at 10 33 28 AM 1](https://user-images.githubusercontent.com/8663934/72489274-8a78d280-384e-11ea-98a3-53e1ffc893bf.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13
 * Operating system: WIndows 7
 * Browser: IE11, FF72

**Comment by jonboiser** [comment]
Fixed in #6505
