### ISSUE TITLE
In TextTruncator, allow an option to apply the "shave" only if the amount of text that will be hidden is substantial

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6477]
### Observed behavior

In the implementation of TextTruncator, we always truncate the text if the text will exceed a certain max height prop.

In some cases, this leads to a situation where 75% of a paragraph is shown and the last 25% is hidden. It might have been better just to show the whole paragraph and spare the user from clicking a button to see the rest.

Example: (3 lines shown, 1 line hidden)

<img width="1031" alt="Screen Shot 2020-01-17 at 2 37 13 PM" src="https://user-images.githubusercontent.com/10248067/72650975-e454c780-3936-11ea-99d1-e203d4f9b226.png">

<img width="1056" alt="Screen Shot 2020-01-17 at 2 37 18 PM" src="https://user-images.githubusercontent.com/10248067/72650980-e9197b80-3936-11ea-821d-3b6399f40564.png">

### Expected behavior

For certain situations, do not trim the text esp. if the untrimmed text is not that much bigger.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by Kalovelo** [comment]
Hello @jonboiser , could I work on this issue?

**Comment by jonboiser** [comment]
@Kalovelo , yes, any help on this issue would be appreciated.

**Comment by Kalovelo** [comment]
It seems like `textTruncator` has been removed from `TopicsPage` on this [commit](https://github.com/learningequality/kolibri/commit/a1f37830fd1d55043867b3338a357fa05c604ced#diff-98afdf62d41fff77bd66c302cf23e1bcf8aa203c53049d27b81699e9db5a622fL57).
![image](https://user-images.githubusercontent.com/45261205/112195914-29e3e300-8c13-11eb-8f52-84f1e96b5851.png)


I searched for components or pages that use the `showViewMore` prop on the `textTruncator` : Only [RecommendedPage](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/plugins/learn/assets/src/views/RecommendedPage.vue#L31-L49) is using it on component [ContentCardGroupHeader](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/plugins/learn/assets/src/views/ContentCardGroupHeader.vue#L32) where truncator is used on card components (not text)
![image](https://user-images.githubusercontent.com/45261205/112196093-58fa5480-8c13-11eb-8e63-0598caeb5aa2.png)


Any tips on how should I proceed? Thank you!

**Comment by jonboiser** [comment]
Oh, that's interesting. I didn't notice that was done in that commit.

The `showViewMore` in `RecommendedPage`/`ContentCardGroupHeader` is not used as a prop in `TextTruncator` (they just have the same name by coincidence).

I need to look into this, but I think if https://github.com/learningequality/kolibri/commit/a1f37830fd1d55043867b3338a357fa05c604ced#diff-98afdf62d41fff77bd66c302cf23e1bcf8aa203c53049d27b81699e9db5a622fL57 removed `TextTruncator` from the topics pages, then that actually resolves the problem that prompted me to write this issue.

I think I should just close this issue for now, unless you have a good idea on how to implement this new feature.

If you are interested, this issue https://github.com/learningequality/kolibri/issues/7557 is much more important and affects the majority of places where we use `TextTruncator` _without_ the `showViewMore` prop.

**Comment by jonboiser** [comment]
Closing because, as @Kalovelo found, the text truncator was removed from the TopicPage, so this is no longer an issue.
