### ISSUE TITLE
Some transcripts don't get highlighted based on where the video is

### ISSUE THREAD

**Issue by jayoshih** [learningequality/kolibri#6487]
### Observed behavior
When I open the transcript for some videos (not all, but some), the transcript doesn't get highlighted based on where the video is at
![transcript](https://user-images.githubusercontent.com/7447496/72845469-89cbac00-3c53-11ea-9c9c-180cf878933c.gif)

### Expected behavior

I expected to get the left border when the video started playing

### User-facing consequences

Nothing too blocking, just potentially not being able to follow along with a video

### Steps to reproduce

1. Open [this page](http://kolibri-beta.learningequality.org/en/learn/#/topics/c/3b5e9c9a93ef5ce9b2eb6f6815dc6b23)
2. Turn on transcripts and jump around

### Context

Kolibri version: This is on the Kolibri beta site (0.13)
OS: I was using Edge, but it seems to be an issue in Chrome too
Browser: Windows 10

**Comment by jonboiser** [comment]
I'm not able to reproduce this on Browserstack. I tried Win 10 + Edge 86, and Win 10 + Chrome 86.

It's possible that some changes to the scrubbing might have fixed this, but that's just a guess

https://github.com/learningequality/kolibri/commit/95b6783abfbe919cf5e0a70b9491e1c84c7f8730#diff-29f14c97ab00b8a275aec4e7147bcb4f17769e94b13d93e6142c717a77cdbf6a
