### ISSUE TITLE
incorrect counting of resources when importing duplicates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6509]
### Observed behavior

reported by @jamalex 

> This happens when some of the resources selected already existed from being imported via another place in the tree. Have we considered displaying this differently? My first assumption on seeing it was that some of the files failed to import.
> 
> ![image](https://user-images.githubusercontent.com/2367265/73575419-01a48e00-442d-11ea-8631-1bd699884932.png)
> 
> (and the 22 of 46 / 38MB of 38MB feels a bit inconsistent too)

### Expected behavior

The intended behavior here is that it would show 46 of 46 because we are now treating duplicates as distinct resources from the end-user’s perspective.

However, the total file size should represent only the newly transferred stuff. For example if you imported 5 resources, all dupes, it should say “5 of 5 resources (0 MB of 0 MB) imported”

### User-facing consequences

confusing/inconsistent counting

### Steps to reproduce

* Create or find a channel that has some resources duplicated across multiple topics
* Import one copy
* Import another copy

### Context

0.13.0

**Comment by indirectlylit** [comment]
@rtibbles is this addressed by your recent work?

**Comment by rtibbles** [comment]
No, I've not touched this part.

**Comment by radinamatic** [comment]
![Selection_893](https://user-images.githubusercontent.com/1457929/88958165-60de4080-d2a0-11ea-8d41-02081ea81ca6.png)

![Selection_892](https://user-images.githubusercontent.com/1457929/88958161-5fad1380-d2a0-11ea-8a11-e9bde418d19f.png)

**Comment by indirectlylit** [comment]
@radinamatic I think these screenshots are unrelated to this issue. Would you mind making a new issue?

**Comment by rtibbles** [comment]
I think this issue might be more relevant? https://github.com/learningequality/kolibri/issues/6351
