### ISSUE TITLE
create linting rule to ensure that migrations are given meaningful names

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6515]
### Observed behavior

We have many migrations with auto-generated names such as `/0005_auto_20191203_0951.py`

### Expected behavior

* We should force developers to name new migrations meaningfully with a linting rule
* Existing migrations should either be meaningfully renamed, or ignored from the linting rule

### User-facing consequences

developers have a harder time scanning the history of migrations

### Context

0.13.0

**Comment by benjaoming** [comment]
This would fit really well as a pre-commit hook, disqualifying a new migration file if it contains `_auto_` in the name.

**Comment by indirectlylit** [comment]
we'll need something that breaks the build because pre-commit hooks can be bypassed or not installed

**Comment by adamchainz** [comment]
Run `pre-commit run --all-files` in your CI!

**Comment by benjaoming** [comment]
@indirectlylit @adamchainz that is already presented in #6583

**Comment by benjaoming** [comment]
@adamchainz just tested this, and your solution from  #6603 works with `--all-files`, as it also complains about existing (previously) committed files in the repo.

Some times testing something is much easier than trying to find documentation :)

```
$ gc --no-verify
[precommittest 2d7ddc52a] Lala
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 kolibri/core/analytics/migrations/0002_auto_20202020202.py

$ pre-commit run --all-files no-auto-migrations
no auto-named migrations.................................................Failed
hookid: no-auto-migrations

We do not allow _auto_ in migration names. Please give the migration a telling name.

kolibri/core/analytics/migrations/0002_auto_20202020202.py
```
