### ISSUE TITLE
Videos with subtitles not working occasionally

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6525]
### Observed behavior

I was testing 0.12.10-beta3 and imported Touchable Earth - the videos would not learn. After some debugging with help from @rtibbles we noted that it was related to the loading order between the video library and the i18n initialization. 

If the language was set as `null` by the video lib because the global i18n data isn't loaded yet, then the whole media player does not load.

Note that going into the localStorage and manually giving it a lang code - it works.

### Expected behavior

Videos always work - the video player is not initialized without necessary language data.

### User-facing consequences

Videos on rare occasion do not work.

### Errors and logs

…

### Steps to reproduce

- Install 0.12.10-beta3 through pip (which is what I did) using the tar.gz
- Run the server on a new KOLIBRI_HOME
- Run through setup wizard
- Import Touchable Earth (at least one video)
- Try to view a video that you imported and... see the error maybe, but probably not?

### Context

Debian
0.12.10-beta3
Chromium

**Comment by pcenov** [comment]
@radinamatic this one is not extant in 0.15.1 - all the videos play fine.

**Comment by rtibbles** [comment]
Closing as fixed.
