### ISSUE TITLE
Cannot import a second channel from Studio in IE11

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6528]
### Observed behavior
Noticed while testing the 0.13.1b1.

When using IE11 it seems to be possible to import resources only from one public channel on Studio, as when you make a second attempt and press the `Select resources` button for any other  channel, nothing happens (user would expect to see the channel topic tree loading at this point).

- It is still possible to import unlisted channels using the token.
- If user stops and restarts Kolibri, they are now able to import, but only once.
- It is possible to import resources correctly from more than one channel in FF & Chrome. 

### Expected behavior
User needs to be able to import from more than one channel.

### User-facing consequences
Impossibility to import content on IE11.

### Errors and logs
Nothing visible in the console or network tab

### Steps to reproduce
1. Open Kolibri in IE11 on Windows 7.
2. Import a resource from one channel from Studio
3. When the task is finished, try importing from another channel.

### Context
 * Kolibri version: 0.13.1b1
 * Operating system: Windows 7
 * Browser: IE11

I'll install on Windows 10 and see if I can replicate on Edge.

cc @jonboiser @indirectlylit @lyw07

**Comment by radinamatic** [comment]
Not able to replicate in Edge on Windows 10, so might be an IE11-only issue.

**Comment by jonboiser** [comment]
Based on how the problem manifests, this might be due to #5343, but that's not specific to a channel being _second_, but simply that it's a channel that has never been viewed by the Kolibri server (and doesn't have its metadata DB downloaded yet).

If that's the case, there is a workaround for now which is to refresh the page after the metadata DB has been successfully downloaded.

**Comment by radinamatic** [comment]
So refresh **before** pressing the `Select resources` button? 
Isn't the metadata DB downloaded after that button is pressed?

**Comment by jonboiser** [comment]
Refresh after pressing "select resources" and getting the blank page with the header saying "Loading channel..." . Is that what you see too when you get this issue?

**Comment by radinamatic** [comment]
I don't get the blank page (or any _new_ page for that matter), after pressing `Select resources` button.
That action simply has no effect at all, and refreshing the page afterwards just brings the `Kolibri Studio channels` again.

![IE11-refresh](https://user-images.githubusercontent.com/1457929/74187431-cf750680-4c4c-11ea-9dbd-18e1030db38a.gif)

**Comment by jonboiser** [comment]
I'm not able to reproduce this on Browserstack (Win 7, IE11, devserver). Could you try to see if it works when clicking the button with the keyboard?

**Comment by radinamatic** [comment]
Hm, more issues... None of the `Select resources` buttons are focusable when navigating by keyboard using the TAB key:

![IE11-keyboard](https://user-images.githubusercontent.com/1457929/74189451-b2423700-4c50-11ea-8353-c376612714c9.gif)

**Comment by jonboiser** [comment]
Not seeing the keyboard issue that on my browserstack setup either. I'm guessing the problems you're seeing have to do with a general "unclickability" of those "select resources links".

Do you at least see URLs appear in the bottom status bar when you hover over them?

Do direct links like this: http://localhost:8000/fr-fr/device/#/content/channels/0705df55d9745fefa08b20f8bf4cc5bf still work?

**Comment by radinamatic** [comment]
Yes to both, I can right click and open the link all right...

On another hand, is it intentional that those links appear `disabled` when inspected? :confused: 

![a-button-disabled](https://user-images.githubusercontent.com/1457929/74191316-ac9a2080-4c53-11ea-8524-08081b4e79f7.gif)

**Comment by jonboiser** [comment]
That might be it: the buttons are disabled. There's logic that says to disable this button if there are any "active" tasks (tasks not completed or canceled) in the queue. Are there any tasks running?

I feel like this blocking is something we wanted to remove in 0.13, but only when it's "safe", of which "safeness" hasn't been fully worked out yet. At the same time this code doesn't look like it was completely leftover by accident, since it has been made more specific by looking at "active" tasks instead of any tasks (like it was before).

So the real issue here might be that IE11 isn't styling these disabled pseudo-button links properly (to look like disabled real-buttons).

**Comment by radinamatic** [comment]
No tasks running, previous import has finished and labeled as completed, but I did not clear the task.
Let me see if something changes when I clear the task.

**Comment by jonboiser** [comment]
Actually "active" will include "completed" tasks as well, based on the filter's implementation

https://github.com/learningequality/kolibri/blob/698a013e793d0b0697a57973466a4f560b9dbe72/kolibri/plugins/device/assets/src/modules/manageContent/index.js#L105-L108

**Comment by radinamatic** [comment]
Is that really the best way to label tasks? It means that the user has to manually clear all completed tasks for the queue to be considered empty and the new import able to begin...? It does not sound very user-friendly to me.

**Comment by rtibbles** [comment]
Also worth noting that the metadata import task now runs in a separate queue from the other tasks, so that it gets fast tracked past long running download tasks.

**Comment by jonboiser** [comment]
yeah, since activetasklist is only used on this page, it makes sense to me to unblock the buttons when there are no canceled OR completed tasks to resolve part of this issue.

**Comment by radinamatic** [comment]
Confirmed that I'm able to import a _second_ channel (and more after) if I manually clear the previous completed task. 

This happens only in IE11, in FF & Chrome is possible to import resources from new public channels without clearing the completed tasks.

**Comment by jonboiser** [comment]
That's really odd. Now it seems like there's a bug with FF and Chrome, since the buttons should be disable according to the code 🤷‍♂

**Comment by rtibbles** [comment]
But aren't we meant to be letting people import more while something else is already importing? The priority queue allows the metadata task to go ahead regardless of current imports, so they can just keep queueing up.

**Comment by jonboiser** [comment]
Yeah, the "Import more" menu option is not disabled on "Device > Channels" unless a channel is being deleted.

It's possible that we disabled the "Select resources" button b/c of the original issue with the metadata download step effectively blocking up the queue, and just forgot to remove that disabling logic?

**Comment by rtibbles** [comment]
That sounds well within the realms of plausibility!

**Comment by jonboiser** [comment]
To resolve this issue, let's just remove the disabling on the "Select Resource" button altogether.

**Comment by indirectlylit** [comment]
sounds good
