### ISSUE TITLE
suggested number for questions is empty when no exercises are selected in quiz

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6529]
### Observed behavior

The suggested number for questions is empty when no exercises are selected during creating a quiz.

### Expected behavior

The suggested number should be 0 if no exercises are selected

```diff
- The max number of questions based on the exercises you selected is . Select more exercises to reach 9 questions, or lower the number of questions to .
+ The max number of questions based on the exercises you selected is 0. Select more exercises to reach 9 questions.
```
### User-facing consequences

…

### Errors and logs

<img width="1001" alt="Screen Shot 2020-02-10 at 1 24 11 PM" src="https://user-images.githubusercontent.com/19424916/74191694-f1e53080-4c08-11ea-8d88-053cdc223a4c.png">

### Steps to reproduce

1. Create a new quiz
2. Do not select any content
3. Click `Continue`
4. See the error `No exercises are selected`
5. Change the number in the field `Number of question` to any number you like
6. See the error
`The max number of questions based on the exercises you selected is . Select more exercises to reach 9 questions, or lower the number of questions to .`

### Context

Kolibri version: 0.13.1b1
Operating system: MacOSX
Browser: Chrome

**Comment by Ali-Kazmi** [comment]
Hi everyone! Just made a pr for this, it was a fairly quick fix. Let me know if anything looks wrong. I don't think i have access to change labels on the pr

**Comment by jonboiser** [comment]
Fixed in https://github.com/learningequality/kolibri/commit/d511d12ee907ce0efadc1adb43bfeff2eb7a9529
