### ISSUE TITLE
Database is open while the server is idle

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#6534]
### Observed behavior
After kolibri starts, the db is kept open, with the journal file created, even if the server is idle, not receiving any query. This has produced corruptions in the db in the past.

### Expected behavior
Once the server starts, the db should be closed and not journal should appear while there are not requests  nor jobs happening.

### User-facing consequences

Possible corruption of the main db

### Steps to reproduce

1. Start Kolibri
2. don't do any request 
3. check the files db.sqlite3-wal and db.sqlite3-shm exist in the kolibri folder.

### Context

Tell us about your environment, including:
 * Kolibri version 0.13.0 
 * Linux

**Comment by lyw07** [comment]
fixed in #6535
