### ISSUE TITLE
Unable to access Learners tab in Coach > Reports

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6552]
### Observed behavior

When in Coach > Reports, and after clicking the "Learners" subtab, the page goes blank

![learners](https://user-images.githubusercontent.com/6668144/74470984-4fb98880-4e54-11ea-8866-a866f85211fd.gif)

### Errors and logs

<img width="547" alt="Screen Shot 2020-02-13 at 11 28 33 AM" src="https://user-images.githubusercontent.com/6668144/74470787-01a48500-4e54-11ea-95c5-58eac46b6241.png">

### Context

http://kolibribeta.learningequality.org/en/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/quizzes
Kolibri 0.13.1b2
MacOS Mojave
Chrome

**Comment by jonboiser** [comment]
@jtamiace Can you see if this happens on other classrooms? Based on the error, I think this might be caused by a channel deletion, or something like that.

**Comment by jonboiser** [comment]
@indirectlylit I think we need to make filter callback safer in case `this.contentMap[ID]` is undefined, like use `lodash/get(this.contentMap, [status.content_id, 'kind'])`. 

```
      exercisesCompleted(contentStatuses) {
        const statuses = contentStatuses.filter(
          status =>
            this.contentMap[status.content_id].kind === 'exercise' &&
            status.status === this.STATUSES.completed
        );
        return statuses.length;
      },

```

**Comment by jtamiace** [comment]
I am not able to reproduce in other classes

**Comment by jonboiser** [comment]
This might be the offending lesson

http://kolibribeta.learningequality.org/en/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/lessons/558cb953562ebd5da0693a15332de8e2/resources

Get this stack trace

```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'content_id' of undefined
    at ReportsLessonReportPage.vue:130
    at Array.map (<anonymous>)
    at Sub.table (ReportsLessonReportPage.vue:129)
    at Watcher.get (vue.runtime.esm.js:4473)
    at Watcher.evaluate (vue.runtime.esm.js:4578)
    at Sub.table (vue.runtime.esm.js:4830)
    at Sub.<anonymous> (ReportsLessonReportPage.vue?06f1:1)
    at Sub.Vue._render (vue.runtime.esm.js:3542)
    at Sub.updateComponent (vue.runtime.esm.js:4060)
    at Watcher.get (vue.runtime.esm.js:4473)
```

And the contentnode in this lesson is 404

http://kolibribeta.learningequality.org/en/learn/#/topics/c/55fd78bc460f43508497beef797bf2f6.

**Comment by jonboiser** [comment]
I wonder if the "clean out lessons" after deleting content logic (#5140) doesn't work for granular deletion.

**Comment by jonboiser** [comment]
Just tested that possibility, and it does seem like granular deletion does cause lessons to be cleaned of deleted nodes... So not sure how this one contentnode got left behind in this lesson.
