### ISSUE TITLE
cannot change device language to 'browser default'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6557]
### Observed behavior

Trying to set the default device language as 'Browser default' does not work:

![image](https://user-images.githubusercontent.com/2367265/74486514-f1030780-4e71-11ea-8538-d71dd1d2e20c.png)

### Expected behavior

Setting should work or be removed

### User-facing consequences

broken behavior in device settings

### Errors and logs

* Request URL: `http://localhost:8000/api/device/devicesettings/`
* Request Method: `PATCH`
* Status Code: `400 Bad Request`
* Response: `language_id`

### Steps to reproduce

Try to set language to browser default

### Context

0.13.1 beta 2
mac
devserver

**Comment by rtibbles** [comment]
My guess would be that we need to mark this field as nullable on the serializer.

**Comment by jonboiser** [comment]
It's actually failing at the validation from language_id validation here https://github.com/learningequality/kolibri/blob/73ae3e3066128bda2297ea00cf5be32bb4af7928/kolibri/core/device/serializers.py#L36-L44

When language_id is null, it's not passing the `check_for_language`, but I don't see that custom validation error in the logs or response.

If I add a branch to pass through `language_id = None`, it seems to work. The `DeviceSettingModel` already allows blank and null language_id

**Comment by jonboiser** [comment]
> If I add a branch to pass through `language_id = None`, it seems to work. The `DeviceSettingModel` already allows blank and null language_id

Yeah, this is how the old DeviceLanguageSettingViewset worked (pass through None values). https://github.com/learningequality/kolibri/commit/c256321225d7231fcbeaad13b3f66063055873ac#diff-5c2a74fbedf7ad859adad5b2f40bf5a2L133
