### ISSUE TITLE
disable 'edit channel order' when there's only one channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6558]
### Observed behavior

| main page | reorder page |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/74488589-8359da00-4e77-11ea-9f11-801520341fc2.png) | ![2020-02-13 15 43 33](https://user-images.githubusercontent.com/2367265/74488643-b7cd9600-4e77-11ea-9359-0888306cf336.gif)|

### Expected behavior

option to reorder should be disabled

### User-facing consequences

slightly strange UX for single-channel view

### Steps to reproduce

Have one channel and reorder

### Context

0.13.1 beta 2

**Comment by Tlazypanda** [comment]
@indirectlylit @kollivier @radinamatic can I work on this? Thanks :v:
