### ISSUE TITLE
Make accessing classSummary/contentMap (and other maps) safer in Coach page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6563]
### Observed behavior

#6552 was caused by a runtime error where we tried to access a property from an undefined object since the `classSummary/contentMap` getter did not have an associated value for a content ID, because the content item was possibly deleted and the lessons using that content were not properly cleaned up.

We should make sure that we don't get runtime errors like this that make pages inaccessible.

Should also look into other maps from the `classSummary` module that might pose a similar risk.

### Expected behavior

The possible mismatches between the Kolibri content library + the logs data + the lessons + quizzes, etc. don't cause crashes anywhere in Kolibri, and esp. the coach pages.

### User-facing consequences

…

**Comment by indirectlylit** [comment]
Flagging for 0.14.0 as part of the data and content syncing process:

https://www.notion.so/learningequality/0-14-Kolibri-must-gracefully-support-missing-content-b7cf0277ac184cd7a4dd6656158e1f9c

- Administrators and coaches should be given an indicator that information is missing when viewing data that references unavailable content. This includes for example exporting CSV data and viewing coach reports
- Learners will have missing content hidden from them
- We will disable auto-removal of unavailable content nodes from lessons, which would cause unintended "edits" _[note from Devon - Oct 2020 - I believe this was completed in 0.14]_
