### ISSUE TITLE
Mastery model change on Studio is not registering as a resource to be updated on Kolibri

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6564]
### Observed behavior
Changing the mastery model for exercises on Studio and then republishing, leads to a new version of the channel being registered on Kolibri, but does not allow to re-import anything: if the exercises were already present on the device, the change in mastery model is not registered (checkboxes are disabled and not actionable).

### Expected behavior
Ability to update exercise resources on Kolibri when their mastery model is changed and channel republished on Studio.

### User-facing consequences
Inability to adapt the mastery model according to needs, and update resources locally.

### Errors and logs
...

### Steps to reproduce
(you'll need access to a channel on Studio)
1. Import a couple of exercises on your Kolibri device.
2. Change the mastery model for those exercises on Studio.
3. Publish the channel.
4. Update the channel in Kolibri.
5. Try to `Import more` and update the exercises.

### Context
 * Kolibri version: 0.13.1b2
 * Operating system: Windows 7 & 10
 * Browser: Firefox & Chrome
 * Channel I used on Studio is `nakav-mafak`

cc @indirectlylit to review labels and the milestone

**Comment by rtibbles** [comment]
I am confused - what is the error here? The exercise files have not updated, so why would we need to redownload them?

After updating the channel, is the new mastery model not in place as expected?

**Comment by radinamatic** [comment]
I was sure that the first time I tested this scenario the mastery model did not change locally, but just retried it again with a second change, and it does appear to be updated locally. :confused: too now...

Another thing is that the user who reported this initially (mastery model does not update locally after being changed on Studio) is working with Kolibri 0.12, so I'll have to install their version to do some more testing.

**Comment by rtibbles** [comment]
This does appear to be working as intended but perhaps the additional information demanded in #6230 would help.
