### ISSUE TITLE
Missing images in Perseus exercises when the mastery model is changed on Studio

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6565]
### Observed behavior
(continues after #6564)

Since it was impossible to update the channel with the exercises whose mastery model I changed on Studio, when I deleted it and imported again from scratch, I got various 404 errors and missing images in the affected exercises. 

Issue is confirmed by testing this workflow on two different Windows VMs, so not a fluke.

![Win10 (start)  Running  - Oracle VM VirtualBox_336](https://user-images.githubusercontent.com/1457929/74497958-55a87b80-4edf-11ea-86f1-7461f96c580b.png)

Could that be because of the mastery model change? In the same channel I have a _control_ exercise with the unchanged mastery model, and no 404 errors in it... :thinking: 
Exercises are from `Counting` topic on KA English imported to my testing channel `nakav-mafak`. 

![Kolibri Studio (Beta) - Mozilla Firefox_337](https://user-images.githubusercontent.com/1457929/74498289-61e10880-4ee0-11ea-8488-6ab247240721.png)

### Expected behavior
Correctly displayed images in exercises.

### User-facing consequences
Inability to interact with the exercises

### Errors and logs
No errors on Studio, and initially I only saw the usual 404 on an image inside the zipcontent (we've seen these Perseus errors before), and another error which appears intermittently:

```
TypeError: "state.core.logging.attempt.interaction_history is undefined"
    currentInteractions index.vue:181
    key vuex.esm.js:836
    VueJS 3
    beforeDestroy index.vue:270
    invokeWithErrorHandling VueJS
vue.runtime.esm.js:1888:12
    VueJS 37
    SET_EMPTY_LOGGING_STATE logging.js:
```
![404s-exercises](https://user-images.githubusercontent.com/1457929/74498619-7a9dee00-4ee1-11ea-898a-9092eea4752f.gif)

```
Data load failed: http://127.0.0.1:8080/zipcontent/c9ad888fe4d4f271c15272f08b9128a1.perseus/images/cd7b86152d1ff093ac300a13e207d33ff159ef9e-data.json undefined
```
@jayoshih wrote:
> Those are referencing certain svg/json information embedded in the perseus files, so it seems more related to the zips being generated than the mastery model change. It could be that something broke at some point, and the change in mastery model caused the zips to be regenerated

### Steps to reproduce
Import the exercises from the **KA EN** sub-topic in the channel with `nakav-mafak` token.

### Context
 * Kolibri version: 0.13.1b2
 * Operating system: Windows 7 & 10
 * Browser: Firefox & Chrome

cc @indirectlylit to review the labels and the milestone

**Comment by indirectlylit** [comment]
do you happen to know if this is a regression?

**Comment by jonboiser** [comment]
@radinamatic @metodimilevqa Could you see if this is still an issue on the latest versions of Kolibri + Studio

**Comment by radinamatic** [comment]
I'd say this has gone bye-bye with all the changes since last year, but we will try to reproduce! 👍🏽

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate the above described issue namely the images of questions for which I've changed the mastery model no longer disappear as previously experienced by you. Therefore it seems that we can close this one.

**Comment by radinamatic** [comment]
Thank you for testing @pcenov & @metodimilevqa! 💯 
As suspected, issue is long gone, will close it now!
