### ISSUE TITLE
On Facility > Users page, need a more specific empty state when only user type filter is used

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6571]
### Observed behavior
In this screenshot, the empty state message makes it seem like I was searching for a username `""`, but I was actually filtering by user kind and got no results.

<img width="1071" alt="Screen Shot 2020-02-14 at 3 40 07 PM" src="https://user-images.githubusercontent.com/10248067/74576614-7228d000-4f40-11ea-8b94-693cde51debc.png">

### Expected behavior

1. More specific empty-state messages for when you get zero results for username search and/or user kind. E.g. if `username filter = '' and type = learner` => `there are no learners in the facility`

### Context

Kolibri 0.13.1

**Comment by indirectlylit** [comment]
moving to 0.14 because it requires string updates

**Comment by jonboiser** [comment]
New empty states:

1. No users of a given kind: `No (Learners|Admins|Super admins|Coaches) exist`
1. No users matching filter (show same message even if user type filter is applied): `There no users that match the filter: ''`
