### ISSUE TITLE
Thumbnails not updated during channel update

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6576]
### Observed behavior

Reported by @intelliant01 in https://github.com/learningequality/kolibri/issues/4948#issuecomment-586580702

>  Thumbnails are not being synced upon version upgrade. They do so only upon _specific_ content deletion and re-import. Am experiencing this with multiple channels.
> 
> ![thumbnails_not_updating](https://user-images.githubusercontent.com/2577060/74587359-66f4a380-5017-11ea-9e54-2251192143c7.gif)

### Expected behavior

Updating a channel should update thumbnails and any other supplementary files (e.g. subtitles) for any currently-imported resources

### User-facing consequences

incomplete update

### Steps to reproduce

* Publish a channel in Studio
* Import in Kolibri
* Update channel resources with new thumbnails in Studio
* Update channel in Kolibri

### Context

0.13.0 and 0.13.1rc1

**Comment by jonboiser** [comment]
I wonder if this might be related to #7523 (and fixed in #7555). It's possible that if only a subset of a topic's descendants are upgraded, it might not get its thumbnail updated under the old logic.

**Comment by rtibbles** [comment]
Pretty sure it's a similar issue, and if not, I had flagged it as being fixed in #7274, so I think this is safe to close.
