### ISSUE TITLE
Incorrect link in getting_started.html

### ISSUE THREAD

**Issue by Tlazypanda** [learningequality/kolibri#6577]
### Observed behavior
While setting up the project I noticed that currently the [loaded with Pipenv](https://docs.pipenv.org/en/latest/advanced/#automatic-loading-of-env) is incorrect in getting_started.html file since the domain has expired and it needs to be updated.

### Expected behavior
The link should be directed to https://pipenv.kennethreitz.org/en/latest/advanced/#automatic-loading-of-env.

### Steps to reproduce   
Visit this link https://kolibri-dev.readthedocs.io/en/develop/getting_started.html and check out the Environment variables section.

**Comment by Tlazypanda** [comment]
@kollivier @divad12  Hey there can you approve this issue and can i work on this? I am interested in rgsoc and would love to contribute to this project :heart:

**Comment by rtibbles** [comment]
Please do! I have assigned you to the issue, I would recommend making the PR to the develop branch to fix this.
