### ISSUE TITLE
add minimum disk space threshold for importing resources

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6589]
### Observed behavior

Users sometimes import content until the disk is completely full, which can cause the computer to malfunction

### Expected behavior

Set a "minimum free space", and then when an import hits that threshold of remaining space on the target, it would fail

### User-facing consequences

avoid having it go all the way until the drive fills up completely, which can lead to system instability if it's the system or DB drive

### Context

0.13.x

**Comment by jonboiser** [comment]
When importing content on the UI, we do try to prevent users from going over the amount of free-space. E.g. if they select too much, they should see a warning and the "import" button should be disabled. So at the time the import is kicked off, there should be enough disk space (assuming a minimal delay between selection and clicking "import")

If the free space shrinks after an import is kicked off, I think this should be handled by the `importcontent` command.

**Comment by indirectlylit** [comment]
True, I think there are at least two components here:

1. Update the existing validation behavior to include some buffer, e.g. 50MB, to prevent people from getting too close to filling up their drive entirely. This buffer could have a default value that can be overwritten in `options.ini`
2. Display a new, internationalized error in the case of out-of-space errors

(these are important for the android work FYI)

**Comment by indirectlylit** [comment]
I would maybe talk with @jamalex and @khangmach about resolving any design details

**Comment by rtibbles** [comment]
This has mostly been resolved, any additional user facing updates will be included in upcoming syncing work.
