### ISSUE TITLE
Add check for open database connections

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6590]
### Observed behavior

@jredrejo reported that a large percentage of our recent DB issues during the 0.13.0 release were caused in part by DB connections that had been left open

### Expected behavior

We should have checks built-in to Kolibri that check for connections left open, and log loud warnings about this.

Preferably these checks would also fail the Travis builds

### User-facing consequences

DB corruption

### Context

0.13.1

**Comment by b-thebest** [comment]
Can I work on this issue ?

**Comment by jredrejo** [comment]
hi, @b-thebest of course you can. I think this is already fixed in 0.14.6 but if you want to take a look, it's completely fine

**Comment by rtibbles** [comment]
I think we have resolved this now in 0.14.6, and no reports of replication.
