### ISSUE TITLE
unrecognized text on kolibri translations server

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6605]
### Observed behavior

On the Kolibri translations server with 0.13.1, all the in-context strings are shown as `Unrecognized text`. The server was deployed in a regular way so not sure if this is related to some missing translations files in Kolibri code.

### Expected behavior

Translators should be able to translate the string through the server

### User-facing consequences

translators are unable to translate

### Errors and logs

<img width="497" alt="Screen Shot 2020-02-27 at 12 34 03 PM" src="https://user-images.githubusercontent.com/19424916/75484477-b9aa5580-595d-11ea-9e87-69576e16f10a.png">
<img width="351" alt="Screen Shot 2020-02-27 at 12 35 44 PM" src="https://user-images.githubusercontent.com/19424916/75484595-f0806b80-595d-11ea-98d5-fcf028c734f4.png">

### Steps to reproduce

go to the current translations server

### Context

Kolibri version: 0.13.1

**Comment by indirectlylit** [comment]
@radinamatic have you ever encountered this before?

**Comment by radinamatic** [comment]
@indirectlylit Yes, it [does happen occasionally](https://learningequality.slack.com/archives/C59J8FEPN/p1562545968037100), not sure what the actual cause is.

**Comment by indirectlylit** [comment]
I wonder if we maybe need to regenerate the dummy language (`ach_UG`)

**Comment by indirectlylit** [comment]
submitted a PR - @lyw07 want to review/merge and see if that helps?

**Comment by lyw07** [comment]
Thank you! I will review the PR :)
