### ISSUE TITLE
Unable to download log reports 

### ISSUE THREAD

**Issue by dtirkey** [learningequality/kolibri#6612]
### Observed behavior
session log says generating report

…

### Expected behavior
should give option for downloading the report

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
@dtirkey Please try exporting from the command line:

https://kolibri.readthedocs.io/en/latest/manage/command_line.html#export-data-logs

If you are not used to working with the command line, scroll up and [read from the beginning of the section](https://kolibri.readthedocs.io/en/latest/manage/command_line.htm).

**Comment by dtirkey** [comment]
![UNADJUSTEDNONRAW_thumb_49c2](https://user-images.githubusercontent.com/61696687/76147114-fb09d600-60be-11ea-810b-080310a9c352.jpg)
![5cc3fccb-e4d2-44d4-b545-5ca60b5fe904](https://user-images.githubusercontent.com/61696687/76147136-21c80c80-60bf-11ea-87ba-d76b35e78d09.jpg)
We tried, this is the screen shot of the message we are getting now.

**Comment by indirectlylit** [comment]
@dtirkey could you please post your log files [as described here](https://kolibri.readthedocs.io/en/latest/manage/get_support.html#locate-kolibri-log-files)

FYI, technical support is available through our [community forums](https://community.learningequality.org/)

**Comment by lyw07** [comment]
Hi @dtirkey, if you installed kolibri through our windows installer, please try the following in the command prompt to run the kolibri commands:
```
cd C:\Python34\Scripts
kolibri manage exportlogs --log-type summary
kolibri manage exportlogs --log-type session
```

The errors shown in the screenshot indicate that Python is not in the system path. 
Thank you!
