### ISSUE TITLE
"Channel name unavailable" after bulk import

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6616]
### Observed behavior

This appears to be a regression of https://github.com/learningequality/kolibri/issues/6175

Noticed that when an import actually completes, the channel shows up.

![2020-03-02 14 00 08](https://user-images.githubusercontent.com/2367265/75722351-e5e01200-5c8e-11ea-8487-e9839c721b74.gif)

### Expected behavior

All channel names should show after initiating a bulk import. 

Additionally, if the task manager is opened by another user in another browser or device, they should also see the names of any waiting or in-progress bulk imports.

### User-facing consequences

Confusing behavior in task manager

### Errors and logs

None

### Steps to reproduce

Using the bulk import function, queue up a few channels and let er rip.

### Context

* 0.13.1
* Windows 10

**Comment by jonboiser** [comment]
I don't think this is a regression unless the channel name _never_ appears (even after the import starts) which is what was fixed originally.

When the Tasks are queued, we don't have the name available instantly, but rather have to wait until we have completed downloading the channel metadata DB from the remote source. Until that point all we have is the Channel ID.

**Comment by indirectlylit** [comment]
thanks for the clarification
