### ISSUE TITLE
need ability to display photo credit for Kolibri home screen image

### ISSUE THREAD

**Issue by carinediaz** [learningequality/kolibri#6641]
Thanks to @laurenlichtman who flagged this oversight on my part:

The image in the Kolibri home screen is missing the photographer's credit. His name is Thomas Van Den Driessche and we must credit him in order to be able to use the image. 

@jamalex suggestion: to have it along the version indicator, right after "usage and privacy"
<img width="712" alt="Screen Shot 2020-03-09 at 2 05 51 PM" src="https://user-images.githubusercontent.com/25229495/76259494-f0f8ec00-6212-11ea-84af-f30dbd7154d0.png">
Since there's a command that allows for the photos to be swapped, this should take an optional argument for the credit and it would only show up if one (photo credit) is set.

**Priority: high** 
(cc @indirectlylit @rtibbles) 
…

Required actions:
- [x] Add string to page: `Photo credit: {photographer_name}`
- [x] Display string after Usage and Privacy
- [x] Add photo credit name to the Kolibri theme https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/default_theme/kolibri_plugin.py#L53 and set value to `Thomas Van Den Driessche`
- [x] Extra cleanup: Delete this management command as it no longer actually affects the background image: https://github.com/learningequality/kolibri/blob/44bf1ed3591321f4b7ef7c4e5c6ceda8c01db7ae/kolibri/plugins/user/management/commands/background.py

**Comment by indirectlylit** [comment]
This will require string updates (e.g. "Photo credit: {photographer_name}" and some nuanced changes to the management commands, so if the photographer is okay with leaving things as-is for another month or two, this would be much easier in 0.14. Let me know if there is more urgency

**Comment by carinediaz** [comment]
@indirectlylit No worries, we can punt it for v0.14. Let's just make it happen. Thank you!

**Comment by rtibbles** [comment]
Note - the management command is now a noop, as its functionality has been overridden by the theme hook. So this would just require adding a name for photo credit to the theme hook, and using that in the frontend.

Ideally, we would also handle the case where the photo credit name is undefined, for old hooks that have not been updated.
