### ISSUE TITLE
'try answer' button can be pressed multiple times for the same answer

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#665]
![image](https://cloud.githubusercontent.com/assets/2367265/20329574/f6d56222-ab4d-11e6-825e-9c9d58d980dd.png)

The 'try again' button will happily re-try the same answer over and over, with no feedback to the user. This will negatively affect their performance.

**Comment by indirectlylit** [comment]
cc @rayykim

**Comment by rayykim** [comment]
@indirectlylit @66eli77 khan academy has similar feature as our 'try again' button - it will have the user re-try again and again regardless if it was the same previous answer. KA has their button "shake" everytime it's wrong - this animation might help with the UX of ours too

**Comment by 66eli77** [comment]
addressed in this PR https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/18
