### ISSUE TITLE
Unused Component Answer.vue in Coach

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6656]
### Observed behavior

I'm working through Kolibri and found that `kolibri/plugins/coach/assets/src/views/common/Answer.vue` doesn't appear to be imported and used anywhere. I'm updating `mat-svg` to use `KIcon` directly and wanted to make the change in that file and see where I can verify that it works properly but I cannot find anywhere it is used.

I'm not sure if I'm just missing something but I've searched and cannot find it referenced anywhere except for `kolibri/plugins/coach/assets/src/views/common.js`

If I search the whole repo for "<Answer" or "import Answer" I see two results where `AnswerIcon` and `AnswerHistory` are used but that is all.

### Expected behavior

Either remove an unused component or leave a comment in it explaining why we're keeping it?

### User-facing consequences

None - just developer experience.

### Context

`develop` branch

**Comment by indirectlylit** [comment]
Nope, I don't see any indication of it. Feel free to delete

**Comment by nucleogenesis** [comment]
Bah! I found it used in `kolibri/plugins/coach/assets/src/views/common.js` - gotta take that `*.vue* filter off my global search :100:
