### ISSUE TITLE
Uninformative big X for no attempt in Coach Reports

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6658]
### Observed behavior

In `kolibri/plugins/coach/assets/src/views/common/LearnerQuizReport.vue` (Coach > Reports > Quizzes > Quiz Reports > Learner Quiz Report Details) - there is a `v-if` directive where if there are no attempts on the exam, we just show a big X.

![image](https://user-images.githubusercontent.com/6356129/76595625-5b32ba80-64b9-11ea-8142-43d7030058a2.png)

To see this - set line 5 of that file (the v-if in ExamReport) to `v-if="!examAttempts"` and load the report page. I could not find a way to see this otherwise but may not have tried everything.

### Expected behavior

1. This is an ostensibly inaccessible page. The page prior lists Learners whose names link to the LearnerQuizReport page - but if there are no `examAttempts` for that Learner on the quiz, then there is no link.

2. If for some reason or by some method this page is accessible, a big black X is not informative about what the issue is.

### User-facing consequences

One of two issues:
- Unreachable code
- Reachable code that shows a kind of angry and meaningless sort of error page. If this is a place that can be reached it ought to have a meaningful message describing what happened and why there is nothing there.

### Steps to reproduce

See the bit about negating the `v-if` above.

### Context

`develop` branch

**Comment by indirectlylit** [comment]
thanks - this was a last minute fix due to string freeze in 0.13 I believe

let's fix for 0.14
