### ISSUE TITLE
exercises in odd state

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#666]
After returning to an exercise that has been mastered, it allows me to answer it once. Then the there is no button on the left - either 'next content' or 'next question'

**Comment by 66eli77** [comment]
this is likely related to another odd state that newly created user inherits some attemplogs from existing user.

**Comment by jamalex** [comment]
![](https://static1.squarespace.com/static/52c2df7ae4b0d215dded86fd/t/550d8f2de4b0961711de9f84/1426951982536/)

**Comment by 66eli77** [comment]
turns out the odd state I mentioned above is due to a mistake on the field name in ContentSummaryFilter. Need to pass `user_id` instead of `user` when fetch the summaryCollection

**Comment by indirectlylit** [comment]
I believe this has been addressed
