### ISSUE TITLE
Ordering of `/api/channels` does not match `/device/api/device_channels`

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6666]
### Observed behavior

In the community forums, a user reported that on RACHEL devices (via [this extension](http://oer2go.org/viewmod/en-kolibri-index)), the channel order on the RACHEL home screen doesn't match the ordering inside of Kolibri itself.

I believe that this because of a [mismatch](https://community.learningequality.org/t/no-drives-with-kolibri-resources-are-connected-to-the-server/1465/20?u=jonathan) of `/api/channels/` (used by RACHEL) and `/device/api/device_channels` (used by Kolibri), especially after an Admin has manually reordered channels.

### Expected behavior

Same ordering for both endpoints, so the RACHEL homepage matches Kolibri. I do not believe this should have any effect on Kolibri (but please check!)
…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri 0.13.1

**Comment by benjaoming** [comment]
@jonboiser I was looking at [the Rachel module](http://oer2go.org/viewmod/en-kolibri-index) and it calls this endpoint:

```
$channeldata = file_get_contents('http://127.0.0.1:9090/api/channel/?available=true&format=json');
```

Which makes me confused, as it's a 404 - should be `/api/content/channel/`. [The oer2go preview page for Kolibri](http://oer2go.org/cgi/sample_wrap.php?moddir=en-kolibri-index) currently doesn't work so having a hard time understanding whether there's some trick to this or I'm looking at the wrong code.

**Comment by benjaoming** [comment]
To fix this, should we suppose that RACHEL calls the correct `/api/content/channel` in some other version of the module?

* PHP's `file_get_contents` does not use the HTTP cache headers (otherwise set via the `@cache_forever` decorator in the API endpoint) -- so that doesn't seem to be the source. Although if a later module does use a cache-enabled XHR, it might be relevant to look into.
* Both endpoints are using the same `ChannelMetadata.objects.all().select_related("root__lang")` queryset and the SQL is this:

Both `/device/api/device_channel/` and `/api/content/channel/?available=true&format=json` create this SQL, notice the `ORDER BY` is correctly preserved:

```
DEBUG    (0.002) SELECT "content_channelmetadata"."id", "content_channelmetadata"."name", "content_channelmetadata"."description", "content_channelmetadata"."author", "content_channelmetadata"."version", "content_channelmetadata"."thumbnail", "content_channelmetadata"."last_updated", "content_channelmetadata"."min_schema_version", "content_channelmetadata"."root_id", "content_channelmetadata"."published_size", "content_channelmetadata"."total_resource_count", "content_channelmetadata"."order", "content_channelmetadata"."public", "content_contentnode"."id", "content_contentnode"."parent_id", "content_contentnode"."license_name", "content_contentnode"."license_description", "content_contentnode"."title", "content_contentnode"."coach_content", "content_contentnode"."content_id", "content_contentnode"."channel_id", "content_contentnode"."description", "content_contentnode"."sort_order", "content_contentnode"."license_owner", "content_contentnode"."author", "content_contentnode"."kind", "content_contentnode"."available", "content_contentnode"."lang_id", "content_contentnode"."num_coach_contents", "content_contentnode"."on_device_resources", "content_contentnode"."lft", "content_contentnode"."rght", "content_contentnode"."tree_id", "content_contentnode"."level", "content_language"."id", "content_language"."lang_code", "content_language"."lang_subcode", "content_language"."lang_name", "content_language"."lang_direction" FROM "content_channelmetadata" INNER JOIN "content_contentnode" ON ("content_channelmetadata"."root_id" = "content_contentnode"."id") LEFT OUTER JOIN "content_language" ON ("content_contentnode"."lang_id" = "content_language"."id") WHERE "content_contentnode"."available" = 1 ORDER BY "content_channelmetadata"."order" ASC; args=(True,)
```

**Comment by rtibbles** [comment]
A manual and automated inspection of the outputs of these two channels confirms that this is not the case. Closing.
