### ISSUE TITLE
when creating a lesson, incorrect validation briefly shows

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6676]
### Observed behavior

When creating a lesson, there is very briefly a message that says that the name is already used:

![2020-03-19 12 15 40](https://user-images.githubusercontent.com/2367265/77105877-7c286d80-69db-11ea-8331-77b9e0b9fcc1.gif)

### Expected behavior

No validation message should be shown in this case

### User-facing consequences

Slight confusion

### Steps to reproduce

create a lesson

### Context

0.13.1

**Comment by jonboiser** [comment]
This is a duplicate of #6593

**Comment by jonboiser** [comment]
Fixed in #7552
