### ISSUE TITLE
CSV headers headers for session and summary logs are not internationalized

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6681]
### Observed behavior

Headers of the CSV data in session logs and summary logs are not internationalized:

![image](https://user-images.githubusercontent.com/2367265/77129874-dd1f6800-6a12-11ea-8397-1e0f28fcfd57.png)

![image](https://user-images.githubusercontent.com/2367265/77129903-f88a7300-6a12-11ea-9f1b-b7455eea8164.png)

### Expected behavior

Headers should be in the current language of the user that is triggering the export. This is consistent with our treatment of CSV file exports in Coach Reports

### User-facing consequences

Non-English-speaking users will have trouble using the CSV files

### Context

0.13.2

**Comment by jredrejo** [comment]
This can  not be done as it was done in the coach page as the export is done in the background in a task, not exporting the content of a table in the frontend.

**Comment by jredrejo** [comment]
Blocked by #10106
