### ISSUE TITLE
Question: workflow for content export

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#6685]
If I supply a linux formatted drive owned by root I get an error that no writable drive is found. Am I supposed to format or chown such as drive? do you expect fat32 or a format with no permissions?

**Comment by indirectlylit** [comment]
You can see the logic for drive discovery here: https://github.com/learningequality/kolibri/tree/develop/kolibri/core/discovery/utils/filesystem

By following that logic, maybe you can come up with a clue as to why a drive is being filtered out?

Sometimes there are issues with which user the drive is being mounted by versus which user is running Kolibri, for example.

**Comment by tim-moody** [comment]
I recommend mentioning the permissions problem in the docs. I suppose a fat32 usb from the factory will not have the problem. btw usbs are automounted by root upon insertion.

**Comment by rtibbles** [comment]
Question answered, closing!
