### ISSUE TITLE
Added channel item does not show up in subtopic

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6687]
### Observed behavior

I updated a test channel twice, in both updates I added a new item. None of the 2 new items showed up after updating.

I believe this is related to https://github.com/learningequality/kolibri/issues/6575 - as some of the behavior might be explain by the full absence of new channel nodes in subtopics.

### Expected behavior

The subtopic is reload with new items

### User-facing consequences

Inability to add new channel items

### Errors and logs

No errors seen

### Steps to reproduce

1. Import a channel that you can edit in Studio
1. Edit the channel in studio, adding a new item in a subtopic
1. Update the channel
1. Go to Learn tab and see that it doesn't show up.

![import_channel](https://user-images.githubusercontent.com/374612/77435582-c433ff80-6de2-11ea-810b-850dd4dc07b6.gif)

### Context

Kolibri 0.13.2.dev

**Comment by indirectlylit** [comment]
Updating a channel doesn't actually mean it will import the new content - it just means that it will become available.

However, other people (myself included) have also found the current UX very unintuitive. We have an open issue to address the UX issue here: https://github.com/learningequality/kolibri/issues/6227

**Comment by benjaoming** [comment]
Oh yikes, thanks for explaining that - I absolutely missed that from the way it was presented -- all the nice "Update" buttons give a different impression.
