### ISSUE TITLE
Channel update diff viewer: Wrong "currently installed" version

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6689]
### Observed behavior

Assigning myself for clarification of this issue.

Observed while trying to reproduce https://github.com/learningequality/kolibri/issues/6575. Using a custom private testing channel used for clean reproduction:

Had **Version 1** installed. **Version 2** is printed some places as the currently installed version, while "Update" buttons are displayed as well.

![screenshot-2020-03-22-19:01:29](https://user-images.githubusercontent.com/374612/77439873-e4b28880-6de7-11ea-9c21-d4b0b903b359.png)

![screenshot-2020-03-22-19:02:03](https://user-images.githubusercontent.com/374612/77439738-b3d25380-6de7-11ea-86b0-95ed0722ddfe.png)

### Expected behavior

"Version 1" is correctly displayed as currently installed channel

### User-facing consequences

Confusion, but this did not block updating the channel to Version 2.

### Errors and logs

No errors found in logs

### Steps to reproduce

Create a clean new channel as Version 1.

### Context

0.13.2.dev

**Comment by jonboiser** [comment]
@benjaoming Could you take a look at the actual SQLite files to see what the versions are. When upgrading, there should be a plain `.sqlite` file for the currently installed version, then a file with the same ID but slightly different file extension for the potential upgrade version (i'm forgetting the exact extension).

I've had this problem before too, but it was because Studio was caching the `sqlite` files, but the `/api/channels` endpoint was reporting a new version, so one could do the upgrade workflow in Kolibri but still end up with a not-new version of the sqlite file.

**Comment by benjaoming** [comment]
Thanks @jonboiser 

> one could do the upgrade workflow in Kolibri but still end up with a not-new version of the sqlite file.

I think this case is the opposite: I did not do the upgrade workflow, yet I had the latest version from Studio reported -- see especially the second screenshot, where it reports that "version 2" (latest version) is installed and that I need to upgrade at the same time.

Let me have a go at seeing if this reproduces systematically or not.

**Comment by jonboiser** [comment]
Oh, I see. It's strange that the UI is telling you that you have "Version 2",  but still behaving like you have "Version 1" (i.e. showing you the update notifications). Have you found a way to get the UI to show "Version 1" again (resetting the server, etc.)?

When you go to the `Device > Channels` page could you inspect your Network tab and look for `/api/device_channels/` and look at the entry for "Benjamin's test" and see what version that reports.

**Comment by benjaoming** [comment]
Hmm, I closed this issue and commented earlier today -- seems I did that without an internet connection *sigh*

I tried to reproduce this in many ways today and gave up. I tried with a blank "Version 1" kind of channel.

I'll be sure to fetch raw data from the endpoints if I see this again. I was debugging other things, so only managed to grab the screenshots in the fly-by.
