### ISSUE TITLE
yarn run devserver / build commands not cached

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6692]
### Observed behavior

When developing Kolibri, frontend assets make up a lot of build time. On an 8 GB system, I have 120-180 seconds with a generally unresponsive system.

This impacts every time that the dev server has to be restarted: Switching git branches etc.

An option is to build production assets with the `-s` switch to build on single-core, such that the dev laptop is responsive while building, but this takes the build time to. **I'm a bit confused about whether this `-s` switch is for the better -- I get faster builds using single-core! (A record-breaking 131 seconds)**

_Multi-core build_

![image](https://user-images.githubusercontent.com/374612/77532405-1afa1180-6e95-11ea-8039-abcda283c7f4.png)

Anecdotally, this issue was initially filed as a blank because of a delayed press on ENTER got registered in the Github window while Kolibri assets were building :)

### Expected behavior

I see the same build times invoking `yarn run devserver` twice. First time: 149 seconds, second time 162 seconds.

I would expect the second time to run faster.

### User-facing consequences

None

### Errors and logs

None

### Steps to reproduce

1. Run `yarn run devserver`
1. Wait for frontend assets to be built
1. Exit and re-run, see that it takes the same amount of time.

### Context

0.13.2.dev

**Comment by rtibbles** [comment]
Have done some prototyping with Webpack 5 that does exactly this, but it's not quite ready for prime time yet.

**Comment by rtibbles** [comment]
This was fixed in #9014
