### ISSUE TITLE
Not able to create lessons, quiz or group

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#6693]
### Observed behavior

In the Coach module, logged in as super admin -
When trying to create a lesson, I get the following message - ` There was a problem saving this lesson `
When trying to create a group, I get the `Something went wrong` screen but no error details.
When trying to create a quiz, I don't get any error response but the quiz also doesn't get created after having chosen the exercise questions.
I do see an exception in the kolibri.txt log.

### Expected behavior

Should be able to create a lesson, quiz and group.

### User-facing consequences

Unable to function with Kolibri

### Errors and logs

I see a specific exception each time I tried -
[kolibri.txt](https://github.com/learningequality/kolibri/files/4381030/kolibri.txt)

### Steps to reproduce

Intuitive. Nothing specifically different from the usual process.

### Context

Kolibri: 0.13.1
Kolibri-server: 0.3.6
Ubuntu 18.04.3

**Comment by indirectlylit** [comment]
Thanks @intelliant01 

I'm seeing a lot of errors like:

```
kolibri.core.auth.models.DoesNotExist: Collection matching query does not exist.
```

We may have to work with you to understand how the DB got into the state it's in. Is there any other context you can provide about this installation? (number of classes/users, how long it's been in use for, used advanced features like data syncing, etc?)

**Comment by intelliant01** [comment]
@indirectlylit this is the system that I use mostly for training teachers. This could be the crucial part - It has a database that was synced from data from 3-4 one year old production installations while working with the MFE Nalanda project team almost a year ago. All along since then I have been able to create lessons etc in this. Not sure when did it stop working. 

Database size could be around 2 GB. Can compress and share.

**Comment by indirectlylit** [comment]
thanks that would be helpful.

It would be best if we could figure out how it got in this state, but at the least we can probably add checks to bypass these errors or clean up missing references

**Comment by intelliant01** [comment]
@indirectlylit Database available herein - https://drive.google.com/open?id=1t24Y7gg5-9wkIrHO3xEVd7AX_3qbVpAh

**Comment by intelliant01** [comment]
@indirectlylit Some additional information.
The above error is applicable to all pre-existing coaches, admin, superadmin. 
If I create any new user with any of these roles then they are able to create lessons, quizes and groups.

The sequence of events for the syncing of data from multiple facilities as well as related issues and bugs is recorded in this email thread - [facilitydatasync-emails.pdf](https://github.com/learningequality/kolibri/files/4485131/facilitydatasync-emails.pdf) and it may be helpful.

**Comment by indirectlylit** [comment]
thank you - targeted to the next milestone

**Comment by rtibbles** [comment]
Hi @intelliant01 - this issue still extant? We've not had any reports of it, so we suspect it may be to do with collection hierarchy corruption during syncing.

**Comment by intelliant01** [comment]
@rtibbles safe to close. I have also discarded the old databases.
