### ISSUE TITLE
Kolibri database is locked error 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6703]
### Observed behavior
This happened when I import more than 20GB of KA channel contents and using multiple browsers for Kolibri testing.

I'm using Windows 7 VM with 512MB of memory 1 CPU 27MB Video memory

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
```
[33mWARNING  Got an exception running <bound method Scheduler.check_schedule of <kolibri.core.tasks.scheduler.Scheduler object at 0x0488AE30>>: (sqlite3.OperationalError) database is locked [SQL: 'SELECT scheduledjobs.id AS scheduledjobs_id, scheduledjobs.interval AS scheduledjobs_interval, scheduledjobs.repeat AS scheduledjobs_repeat, scheduledjobs.queue AS scheduledjobs_queue, scheduledjobs.obj AS scheduledjobs_obj, scheduledjobs.scheduled_time AS scheduledjobs_scheduled_time \nFROM scheduledjobs \nWHERE scheduledjobs.queue = ? AND scheduledjobs.scheduled_time <= ?'] [parameters: ('kolibri', '2020-03-26 11:55:45.701044')] (Background on this error at: http://sqlalche.me/e/e3q8)[0m
```
[deamon.txt](https://github.com/learningequality/kolibri/files/4391303/deamon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4403446/kolibri.txt)

### Steps to reproduce
* Import more than 20GB of KA channel contents
* While importing KA contents Install IE11, Firefox and Chrome browsers
* While importing KA contents do some integration testing with this [Spreadsheet](https://docs.google.com/spreadsheets/d/1kT2wR1WOVwzmqjDUCZvPgtwZX3d5JQtuj44W02ya9rE/edit?pli=1#gid=971465005) using those three browsers 

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.2-beta1
 * Operating system: Windows 7
 * Browser

**Comment by radinamatic** [comment]
@mrpau-richard It would be good if you could specify the steps that lead to this error in a bit more detail, and provide the `kolibri.txt` log file too.

Does the error resolve if you restart the server, and/or limit to using just one browser?

**Comment by mrpau-richard** [comment]
> Does the error resolve if you restart the server, and/or limit to using just one browser?

The Kolibri server cannot start unless I manually delete the database that causing this error.

**Comment by mrpau-richard** [comment]
I re-encounter this issue again when I cancel the import of more than 20GB KA channel content. The Kolibri server still running but I can't sign in and the message "Sorry! Something went wrong" will show up.

I uploaded the log files below:
[kolibri.txt](https://github.com/learningequality/kolibri/files/4406444/kolibri.txt)
[daemon.txt](https://github.com/learningequality/kolibri/files/4406447/daemon.txt)

**Comment by cpauya** [comment]
@mrpau-richard Are you using a VM for this?  If so, please edit and put the VM details in your first post (ram, disk size, # of processors, graphics ram) - they'll be helpful.  If not, please ignore this. 😺

**Comment by cpauya** [comment]
Here's the [Kolibri Hardware requirements](https://kolibri.readthedocs.io/en/latest/install/system_requirements.html) - it needs at least 2GB RAM for Windows. 

As discussed, can you can increase the 512MB RAM in your VM @mrpau-richard and see if you still encounter the issue?

**Comment by mrpau-richard** [comment]
I re-tested this issue again and I can't reproduce this when I upgraded the VM hardware into Kolibri requirements. and I used IE11 browser to import  21gb KA contents without doing integration testing in it.

**Comment by indirectlylit** [comment]
Closing because it sounds like the issue can be attributed to running Kolibri in a VM with less resources than the hardware requirements

Please re-open if I've mis-understood
