### ISSUE TITLE
yarn install erroring on aphrodite, Keen-UI when using git with SSH

### ISSUE THREAD

**Issue by andyhaskell** [learningequality/kolibri#6707]
### Observed behavior

Following the instructions [here](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#setting-up-kolibri-for-development) for setting up Kolibri, I ended up getting an error when running `yarn install` for aphrodite and Keen-UI:

`fatal: Could not read from remote repository.`

After further investigation, I found that I get this error running:

`git ls-remote --tags --heads https://github.com/learningequality/Keen-UI/`

but not running:

`git ls-remote --tags --heads git@github.com:learningequality/Keen-UI.git`

and in turn discovered that yarn install succeeds if I comment out this section of my git config:

```
[url "git@github.com:"]
        insteadOf = https://github.com/
```

since I will have switched back to communicating with GitHub over HTTPS, rather than SSH. So I think the fix would be either a workaround that allows doing yarn install with SSH, or a note in the documentation explaining that this needs to be run with git configured to use HTTPS to communicate with GitHub.

### Expected behavior

Expected behavior was a successful installation with yarn install.

### User-facing consequences

Unexpected speed bump to getting started with installing the Kolibri system for development.

### Errors and logs

When running yarn install, I got the following terminal output:

```
(virtualenv-andy) andy:~/kolibri$ yarn install
yarn install v1.21.1
$ node ./packages/kolibri-tools/lib/npm_deprecation_warning.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/learningequality/Keen-UI/
Directory: /home/andy.haskell/kolibri
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/learningequality/aphrodite/
Directory: /home/andy.haskell/kolibri
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### Steps to reproduce

Following the steps in the get started docs:

1. Set up a virtual environment, install Python dependencies:
```
python3 -m venv ./virtualenv-andy
source ./virtualenv-andy/bin/activate
pip install -r requirements.txt --upgrade
pip install -r requirements/dev.txt --upgrade
pip install -r requirements/build.txt --upgrade
pip install -r requirements/test.txt --upgrade
pip install -r requirements/docs.txt --upgrade
pip install -e .
```

2. Set up Node

```
nodeenv -p --node=10.15.3
npm install -g yarn
```

3. Run `yarn install`

```
yarn install
```

### Context

Kolibri version: current `develop` branch as of commit https://github.com/learningequality/kolibri/commit/27d11d9c838655f43a77aa297c0d5429e8e1cf65 
Operating system: Ubuntu 18.04

**Comment by indirectlylit** [comment]
I haven't heard of anyone else running into this so I'm not sure how to explain. However we will soon be vendoring keen, which may make this issue disappear.

cc @nucleogenesis

**Comment by rtibbles** [comment]
Have not seen any replications, so closing this for now.
