### ISSUE TITLE
Granular import on Windows

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6714]
### Observed behavior
Windows 10 VM was set up to import a large amount (10GB) of resources from a local network peer (0.13.2 instance running on Ubuntu VM on another physical device). Since Windows VMs have a limitation that they auto shut down after 60 minutes, I expected that this process will require several restarts. The first 2 restarts were uneventful, and the import apparently proceeded well. However, after the subsequent restart the import was not progressing further than _Generating channel listing..._ step. 

![Win10C  Running  - Oracle VM VirtualBox_387](https://user-images.githubusercontent.com/1457929/77929537-1032e880-72aa-11ea-8134-9882f785f138.png)

Furthermore, the **Channels** page reported only ~400MB on KA EN as imported, when it has certainly imported more, and the size of the `/content` folder is >8GB:

![Win10C  Running  - Oracle VM VirtualBox_386](https://user-images.githubusercontent.com/1457929/77929273-c0ecb800-72a9-11ea-9cb1-71fd9552cc42.png)

From the logs it seemed like at some point the source Ubuntu peer has shut down, and but even after restarting it, it was not possible to resume the import on Windows VM. Even when I then tried to import directly from Studio, that intent got stuck at the same step as the import from the peer.

![Win10C (start)  Running  - Oracle VM VirtualBox_394](https://user-images.githubusercontent.com/1457929/77930226-e9c17d00-72aa-11ea-9ccc-2388c90d1269.png)

### Expected behavior
Import operation able to resume after restart.

### User-facing consequences
Inconsistent and unreliable import workflow.

### Errors and logs

Since at the stuck import step it's impossible to **cancel** the operation, I got this error when pressing the back-arrow button to go back:

![Win10C (start)  Running  - Oracle VM VirtualBox_393](https://user-images.githubusercontent.com/1457929/77930497-3c9b3480-72ab-11ea-9117-2a67cbaa12db.png)

Relevant logs from `~/.kolibri/logs/`

[logs.zip](https://github.com/learningequality/kolibri/files/4403705/logs.zip)

[zipped db.sqlite3](https://drive.google.com/open?id=1S8tz1-GMwjFAd5A0lXFdAEfZAjmKnsdX)

### Steps to reproduce
_This may be long to repro because it presumes having at least 10GBs of content available on one local peer._

1. Follow the steps from the relevant [Gherkin scenario](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/super-admin/super-admin-import-granular-from-peer.feature) importing on Windows.

### Context

 * Kolibri version: 0.13.2b1
 * Operating system: 
   * peer1: Windows 10 VM (imported into)
   * peer2: Ubuntu 18.04 (imported from)
 * Browser: FF & Chrome

@jonboiser @indirectlylit

**Comment by jonboiser** [comment]
When you restart the server on the windows VM, is there a task in the task manager for the interrupted transfer?

It seems that ending the transfer abruptly has put the whole Task queue in a bad state, which leads to you also getting stuck trying to view the channel contents ( which can also depend on creating and completing a task).

**Comment by radinamatic** [comment]
> When you restart the server on the windows VM, is there a task in the task manager for the interrupted transfer?

IIRC I don't think there was anything incomplete in the task queue after the third restart.

This limitation of Windows VMs provoking errors of this nature might seem over the top, but when you think of devices that are housed in places with inconsistent power supply, where blackouts are frequent, it might not be a bad idea to think of strategies how to make the import/export task queuing less brittle and prone to end up in bad states because of server shutdowns.

**Comment by radinamatic** [comment]
Apparently I made an error and run this scenario with **0.13.1b2**, instead of **0.13.2b1** :woman_facepalming: :disappointed:

Just rerun several permutations of this workflow (from/to Ubuntu/Windows peer and from Studio; with the Windows VM auto-shutdown, or directly powering the VM down, etc.), on the correct 0.13.2b1 version, and each time I was able to resume the import operations without issues, and no DB errors, locked, malformed or otherwise.

So, yey for me discovering an issue that was there on 0.13.1, but apparently is not there anymore on 0.13.2 :blush: 

If there are no other concerns, we can close this!

**Comment by lyw07** [comment]
🎉yay! thank you for testing, Radina! yes I agree that we can close this now :)

**Comment by indirectlylit** [comment]
thank you!
