### ISSUE TITLE
No auto-discovery of Kolibri peers in Ubuntu 16.04.6

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6724]
### Observed behavior

Installed Kolibri v0.13.2-beta1 in two Ubuntu 16.04.6 VMs and when trying to import content from "Local network or internet" each other.  The auto-discovery of Kolibri peers did not work.

Setup:
* I have 2 VMs running both with channel contents for importing.
* Both VMs have `gufw` (graphical firewall in Ubuntu) installed and have allowed incoming/outgoing network traffic .
* I tried auto-discovery first without `gufw` but that didn't work.  Thus I installed it to specifically allow network traffic.

Screenshot of the two VMs (a `.gif` would have been better but it's >10MB):
<img width="2566" alt="Screenshot 2020-03-31 19 43 06" src="https://user-images.githubusercontent.com/175580/78022655-eb14a780-7387-11ea-81c6-ebbbf303d5d4.png">

### Expected behavior

Auto-discovery of Kolibri peers to work without having to manually input the Kolibri server IP and port.

There's [already a warning in the Channels and Resources documentation](https://kolibri.readthedocs.io/en/latest/manage/resources.html#import-from-a-local-network-or-internet) regarding "inability to discover other peers", etc.

### Steps to reproduce
1. Setup two Ubuntu 16.04.6 VMs, with bridged networking.
1. Install [kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1)
1. Attempt to do the "Import from Local network or internet" task

### Context
 * Kolibri version: [kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1)
 * Operating system: VM Ubuntu 16.04.6 Desktop, 4GB RAM, 2 CPUs, 768 Video RAM, 64GB disk
 * Browser: Firefox v74 (default of Ubuntu)

### Note/s:
* I recorded a `.gif` of the two VMs but cannot import it here due to the 10MB limit of Github, it is about 32MB.  Will try another later.

**Comment by radinamatic** [comment]
Agreed that auto-discovery of peers seems very sensitive to network setup, especially if servers are running on different OSes... 

In my testing it works well between two Ubuntu 18.04 peers; Windows 10 cannot auto-detect Ubuntu peer, but can import from it when the IP is saved manually; Ubuntu 18.04 can neither auto-detect a Windows 10 peer, nor it can find/access it when you try to save the IP manually.

**Comment by radinamatic** [comment]
Ping from Ubuntu to Windows works, but Kolibri is still unable to add/save the local address:

![2020-03-31_13-48-05](https://user-images.githubusercontent.com/1457929/78023623-40849080-7357-11ea-98e6-f8e5345e7703.png)

**Comment by radinamatic** [comment]
Did some more digging, and on Windows 10 you need to explicitly allow both Python and `kolibri.exe` through the firewall, to be able to add a peer for import. Auto-discovery  will still not work, but at least you can add the peer IP manually, it will be saved and import enabled.

**Comment by indirectlylit** [comment]
Are these issues with Kolibri, or are these things we should address in documentation?

**Comment by cpauya** [comment]
I Agree.  Based on @radinamatic's findings, I think we can close this and address it in our documentation instead.

**Comment by radinamatic** [comment]
Agreed, these Windows details will be added in the next docs update!
