### ISSUE TITLE
Windows import woes: django.db.utils.OperationalError: database is locked 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6726]
### Observed behavior
Experienced a similar error as in  #6703, but on Windows 10 with 8GBs of RAM, so that's probably not the issue.

1. In the first round Kolibri on Windows imported successfully 4GBs of content from a local Ubuntu peer, but toward the end lingered a **long** time at 100% and reported this error:

   ![Win10C (start)  Running  - Oracle VM VirtualBox_404](https://user-images.githubusercontent.com/1457929/78026017-454b4380-735b-11ea-949c-0049c672fa98.png)

   [error-Win2.txt](https://github.com/learningequality/kolibri/files/4409015/error-Win2.txt)

   ![Win10C (start)  Running  - Oracle VM VirtualBox_405](https://user-images.githubusercontent.com/1457929/78026036-4b412480-735b-11ea-8ca6-bdc0e24b3da2.png)

   However, after the reload the import task was eventually reported as completed, and the content displayed correctly. 

2. I restarted the VM and initiated another import task of around 4GB. When I returned to the VM it was shut down, and upon restart it did not display that second batch of content as imported.

3. I tried a smaller import (1GB) of the same content as in the previous step. The progress bar was moving steadily, but again seemed to get stuck at 100%, throwing the same error as in step 1.

   ![Win10C (start)  Running  - Oracle VM VirtualBox_408](https://user-images.githubusercontent.com/1457929/78027059-ff8f7a80-735c-11ea-8fbc-dd93c8d21dc7.png)

   [error-Win3.txt](https://github.com/learningequality/kolibri/files/4409025/error-Win3.txt)

4. At this point it again seems impossible to start any import tasks, neither from a peer nor from Studio, as the task is just sits waiting in the queue, since the database is locked.

   ![Selection_409](https://user-images.githubusercontent.com/1457929/78027328-7a589580-735d-11ea-9f50-75a9b8e7957f.png)
 
### Expected behavior
Import operation able to resume after restart.

### User-facing consequences
Inconsistent and unreliable import workflow.

### Errors and logs

[logs.zip](https://github.com/learningequality/kolibri/files/4409042/logs.zip)

[zipped db.sqlite3](https://drive.google.com/open?id=1yL2yyPB0PLTnY2gfhuGcIo2nR3Dy0HYo)

### Steps to reproduce
See above.

### Context

 * Kolibri version: 0.13.2b1
 * Operating system: 
   * peer1: Windows 10 VM (imported into)
   * peer2: Ubuntu 18.04 (imported from)
 * Browser: FF & Chrome

@jonboiser @indirectlylit

**Comment by radinamatic** [comment]
Apparently I made an error and run this scenario with **0.13.1b2**, instead of **0.13.2b1** :woman_facepalming: :disappointed:

Just rerun several permutations of this workflow (from/to Ubuntu/Windows peer and from Studio; with the Windows VM auto-shutdown, or directly powering the VM down, etc.), on the correct 0.13.2b1 version, and each time I was able to resume the import operations without issues, and no DB errors, locked, malformed or otherwise.

So, yey for me discovering an issue that was there on 0.13.1, but apparently is not there anymore on 0.13.2 :blush: 

If there are no other concerns, we can close this!

**Comment by indirectlylit** [comment]
thank you for your thorough investigation!
