### ISSUE TITLE
Users should be warned that resource deletion tasks cannot be canceled

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6727]
### Observed behavior
Cannot cancel a delete task in Kolibri v0.13.2-beta1 under a Ubuntu 16.04.6.

### Expected behavior
User should know in advance that they are not able to cancel a delete task.

![kolibri-v0 13 2-b1--cannot cancel delete task 2](https://user-images.githubusercontent.com/175580/78030519-cd017400-7394-11ea-864b-df311a69960d.gif)

### User-facing consequences
User cannot cancel a delete task.  This may affect users with large channels and/or they have accidentally deleted it.

### Steps to reproduce
1. Install [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1) in an Ubuntu 16.04.6 VM
1. Import a channel
1. Delete the imported channel
1. Notice that you cannot cancel the delete task

Note: This was encountered while [testing this Gherkin story](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/super-admin/super-admin-cancel-import-channel.feature#L26).

### Context
* Kolibri version: [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1)
* Operating system: Ubuntu 16.04.6 VM (2GB RAM, 2CPUs, 64GB disk)
* Browser: Firefox v74

**Comment by radinamatic** [comment]
Yeah, we had several discussions around it prior to releasing 0.13, see #6250 and #6251. 

It needs additional UX, and user strings, so not possible at this time.
@indirectlylit Maybe retarget to 0.14?

**Comment by cpauya** [comment]
Oops sorry if this was a duplicate.  I searched in the issues list before reporting but I did not include "closed" ones.  Should we close this?

**Comment by radinamatic** [comment]
The other one is closed, I suggest we keep this and re-target to 0.14.

**Comment by marcellamaki** [comment]
Dev working on this issue can propose a string as needed, and tag Radina or comms in review, while we figure out improvements to string processes

**Comment by marcellamaki** [comment]
Quick clarifying question - does this apply to _all_ deletion tasks? There is a specific example here with resource deletion, but I looked over channel deletion, and it seems like this is the same on the UI side. 

After doing a search, it seems like in addition to channels and resources, deletion tasks exist for: 

- Group
- Lesson
- Exam
- Class 
- User 

While some of these are not as long of a task (such as deleting a lesson or user, which I can imagine a user would expect to complete quickly), @jonboiser and @nucleogenesis - do either if you know if this "no cancellation" applies to all of these tasks? If so, would it be good to add the string I come up with to all of these modals, just for consistency? And perhaps modify to "you cannot cancel or undo" (if that is in fact true). Appreciate your thoughts also @radinamatic

**Comment by jonboiser** [comment]
> does this apply to _all_ deletion tasks? There is a specific example here with resource deletion, but I looked over channel deletion

Channel deletion is just a special case of resource deletion, so the inability to cancel should be mentioned in both situations.

> And perhaps modify to "you cannot cancel or undo" (if that is in fact true).

Yeah, the more common pattern is to emphasize that a deletion cannot be undone, and it's just assumed that it cannot be canceled. 

However, it's not a common pattern to emphasize the inability to cancel. It's just something we have to do for this issue since the technical limitations with resource deletion break an expectation that you can cancel a process (as you can if deleting large number of files on your OS).

**Comment by rtibbles** [comment]
> deletion tasks exist for

Important to note that the emphasis here is on asynchronous tasks that are running for a long time, and that we show progress indication for. The other tasks you have listed outside of Channel/Resource deletion all happen synchronously.

**Comment by radinamatic** [comment]
In my mind any action by the user that can change the state of their facility and/or device, and does not have the options to cancel or undo the outcome, should have the corresponding `Are you sure you want to continue? This action cannot be undone.` alert, and require the explicit confirmation step by the user. We can establish priorities in terms async tasks first, synchronous maybe later, but ideally all should have them.
