### ISSUE TITLE
cannot upload using production server

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6750]
### Observed behavior

cannot upload using production server, however I can using the devserver. This was observed when running the pex:

![2020-04-02 18 12 25](https://user-images.githubusercontent.com/2367265/78314091-be8a9800-750d-11ea-81fb-c433a22402bc.gif)

A similar thing is happening when trying to do granular import of content

### Expected behavior

upload and import works in both versions

### User-facing consequences

cannot use key functions

### Errors and logs

expecting JSON

### Steps to reproduce

* Download pex from a recent PR, e.g. https://github.com/learningequality/kolibri/pull/6716
* Try to upload users
* Try to import content

### Context

profuturo branch

**Comment by indirectlylit** [comment]
this change to `client.js` caused a regression with importing:

https://github.com/learningequality/kolibri/pull/6674/files#diff-1c2488e6a8447b7998fecb3ea0ba1af4

**Comment by jredrejo** [comment]
Solved in #6768
