### ISSUE TITLE
Cannot update thumbnails in new channel version

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#6751]
### Observed behavior

The ASB channel (f9d3e0e46ea25789bbed672ff6a399ed) v25 is roughly the same as v24 except that topic thumbnails were regenerated.

Going through the channel UPDATE procedure left me in this state:

![Screen Shot 2020-04-02 at 10 32 04 PM](https://user-images.githubusercontent.com/163966/78318532-ffe16e80-7532-11ea-9a55-5a5c584e0521.png)

clearly Kolibri understands the .zip files are the same and we already have them so nothing new to import, but what about the topic thumbnails? Are they not files too? Just because available=True for the old version doesn't mean user doesn't want available=True for the new thumbnails ;)

Here is a proof-by-screenshot that thumbnails are still missing despite exhausting all Kolibri-side options for UPDATE and IMPORT MORE:

![Screen Shot 2020-04-02 at 10 30 45 PM](https://user-images.githubusercontent.com/163966/78318653-4cc54500-7533-11ea-846c-60441fe991dd.png)

### Expected behavior

All folders to have thumbnails after the UPDATE step.

proof by screenshot that topic thumbnails exist on Studio (if you squint and undo-the 80%-darken overlay, you will see there is a 40-up thumbnail underneath for each topic node):

![Screen Shot 2020-04-02 at 10 44 30 PM](https://user-images.githubusercontent.com/163966/78318745-8d24c300-7533-11ea-838e-9a2de3062b02.png)

### User-facing consequences

Potential confusion about "why are not files being updated in the new version." 

### Steps to reproduce
 
 - Publish channel vN on Studio 
 - IMPORT channel vN on Kolibri
 - Update topic thumbnails in Studio and publish version v(N+1)
 - UPDATE channel in Kolibri (you shold be notified v(N+1) is availble)

After update theoretically we should have v(N+1) on Kolibri (nodes+metadata+associated files), but actaully supplementary files like thumbnnails don't seem to get updated.

### Context

 * Kolibri version: 0.13.1
 * Operating system: Linux in k8s

**Comment by ivanistheone** [comment]
Deleting the channel and re-importing pulled in the new thumbnails:

![Screen Shot 2020-04-02 at 11 35 01 PM](https://user-images.githubusercontent.com/163966/78321674-a7ae6a80-753a-11ea-8f03-4c2e5b5e1e97.png)

**Comment by indirectlylit** [comment]
Is this a variation on the behavior you reported here? https://github.com/learningequality/kolibri/issues/6351#issuecomment-586615902

**Comment by ivanistheone** [comment]
@indirectlylit Yes, this issue is a duplicated of the limitation reported in  https://github.com/learningequality/kolibri/issues/6351#issuecomment-586615902. The "Workaround 1" documented in that comment doesn't work anymore since the UPDATE workflow is different.

**Comment by indirectlylit** [comment]
thanks - we'll leave this open as a top-level issue and hopefully resolve them together

**Comment by indirectlylit** [comment]
should be addressed
