### ISSUE TITLE
display issue on p2p modal when static address name is too long

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6754]
### Observed behavior

We allow 40 characters for the name of static address that users can define in the p2p import/export modal. However, when a user defines a name with 40 characters, the name would partially cover the "Forget" text after it.

### Expected behavior

Users should be able to clearly see both the name and "Forget" text when defining a long name.

If the name is too long, it should be elided with "..."

### User-facing consequences

users won't be able to see the name nor "Forget" text clearly

### Errors and logs

<img width="396" alt="Screen Shot 2020-04-03 at 9 27 37 AM" src="https://user-images.githubusercontent.com/19424916/78383788-d3a70b80-758d-11ea-9bbb-04fcf397cc5f.png">

### Steps to reproduce

1. go to channel import page and choose "local network or internet" import
2. click "add a new address"
3. enter the full static address and a random name with 40 characters
4. click "confirm"

### Context

Kolibri version: 0.13.2b1
Operating system: MacOSX
Browser: Chrome

**Comment by rationality6** [comment]
Can I pick this?

**Comment by indirectlylit** [comment]
sure, you can target a change to `develop` and use `text-overflow: ellipsis;`
