### ISSUE TITLE
Error when evaluating setter "rawTime"

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#676]
## Summary

Console `[Vue warn]` while playing MP3 file, playback has no issues.

## System information

 - Version: latest develop
 - Operating system: Ubuntu 16.10
 - Browser: Firefox & Chrome (somewhat different warn, though, see screenshots)
 - Content channel ID: 8b4d3e6d3d4842ba8ea658335b5dd252

## Traceback or relevant snippet from server.log or browser console

```
[Vue warn]: Error when evaluating setter "rawTime": TypeError: this.$els.audio is undefined

[Vue warn]: Error when evaluating setter "rawTime": TypeError: Cannot set property 'currentTime' of undefined
```

## How to reproduce

1. Import channel
1. Go to `Explore - Science - Audio`
1. Load any of the MP3 files.

## Screenshots

Firefox:

![nyman - a la folie - cut1 - khan academy testing - kolibri - mozilla firefox_017](https://cloud.githubusercontent.com/assets/1457929/20413533/c33af166-ad2d-11e6-9db3-8e0ce4bdfed5.png)

Chrome:

![nyman - a la folie - cut2 - khan academy testing - kolibri - google chrome_018](https://cloud.githubusercontent.com/assets/1457929/20413535/cd50c48c-ad2d-11e6-9e4b-6bfdc508f5b3.png)

**Comment by 66eli77** [comment]
@radinamatic @indirectlylit @christianmemije  are you able to use the `+20s` or `-20s` or `seeking` features of the audio player? None of these works for me.

**Comment by radinamatic** [comment]
@66eli77 I vaguely remember some seeking was functional when I was checking @christianmemije's re-design of the media download button, but haven't tested it after it...

I'll try it again asap!

**Comment by 66eli77** [comment]
it turns out, some mp3 are not seekable on Chrome, but the same mp3 works on firefox and safari.

**Comment by 66eli77** [comment]
it works on firefox and safari, and if I load another audio file from the internet, it works on Chrome too. This may be that the dev server cannot handle streaming on Chrome, or maybe that all the mp3 files in my channel are not seekable on Chrome.

**Comment by indirectlylit** [comment]
> This may be that the dev server cannot handle streaming

That's likely the reason - I believe with many media files you need to run the production cherrypy server for seeking to work.

**Comment by indirectlylit** [comment]
tested and this issue appears to be fixed
