### ISSUE TITLE
Idle Kolibri uses CPU and has disk activity

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#6778]
### Observed behavior

With no clients attached or consuming content I see a consistent 4% CPU used by kolibri.
I also see continuous writes to disk.

### Expected behavior

No use of resources

### Context 
 * Kolibri version 0.13.1
 * Operating system Ubuntu 18.04.4
 * HW Intel NUC

**Comment by rtibbles** [comment]
Kolibri has a task runner that uses the database, including scheduled tasks, so this is expected behaviour.
