### ISSUE TITLE
Question: Kolibri urls

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#6779]
A kolibr content url looks to be formed as
<KOLIBRI_URL_PATH_PREFIX>/<default lang>/learn/#/topics/<content id>

In my install <default lang> is en so urls contain en even for Spanish Khan Academy. I take it this is because the topics page labels are in English even though the content is in Spanish once I navigate there. Would the reverse also be the case, that if I set default language to ES I would get /es/ in a url to English Khan Academy but the labels would be in Spanish?

Is there a way to get the value of the default language, say through kolibri manage?

**Comment by tim-moody** [comment]
@ivanistheone advice that /kolibri/learn/#/topics/1ceff53605e55bef987d88e0908658c5 will do a redirect to the url including lang seems to be correct.

**Comment by indirectlylit** [comment]
that is correct
