### ISSUE TITLE
Longer `yarn devserver` startup in develop compared to 0.12.x

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6784]
### Observed behavior

Starting the devserver takes longer than it used to. I did some work on 0.12 after having worked exclusively on develop for a while and it was immediately noticeable.

I measured once and got the following from `yarn devserver` to `Initial build complete...`

0.12.x: 0m 52s
0.14.x 1m 08s

I know a 16s difference isn't all that much - but it would be pretty cool if we got the time back down.

0.12.x `Kolibri Build: Initial build complete in 48.674 seconds`
0.14.x `Kolibri Build: Initial build complete in 63.491 seconds`

Here is a CSV of each module and it's timing... not sure if it is just a matter of things being added to each module (some are a bit faster even) or if this can be optimized somehow.

[comparison.xlsx](https://github.com/learningequality/kolibri/files/4472516/comparison.xlsx)

### Expected behavior

Optimized build time.

### User-facing consequences

None

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
@indirectlylit did we merge the tree-shaking? Possible that doing this in develop might be causing the slowdown.

**Comment by indirectlylit** [comment]
No, decided it wasn't worth it: https://github.com/learningequality/kolibri/pull/6241

**Comment by rtibbles** [comment]
Hrm - my assumption is that it might be just more building going on. Plus, I am jealous that @nucleogenesis builds in half the time mine does!
