### ISSUE TITLE
etag not accounting for plugin_data

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#6785]
### Observed behavior

When we generate etags we are not accounting for plugin_data that is bootstrapped in `kolibri_plugin.py` files. 

etag generation happens here: https://github.com/learningequality/kolibri/blob/3a6bdb2aeeb6c7360558cee4ecd93ff93dab8274/kolibri/core/decorators.py#L319

### Expected behavior

When data necessary to front end rendering (ie, plugin_data) changes, then the etag for that resource should be generated anew.

### User-facing consequences

Changes not being reflected due to incorrect HTTP 304 responses are received when the plugin_data has changed but is not generating a new etag accordingly.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Fixed in #7107
