### ISSUE TITLE
When only one language option is hiding "below the fold", maybe just show directly?

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#6794]
### Observed behavior

See the list at the bottom of the screenshot:
![image](https://user-images.githubusercontent.com/618416/79396636-35be2400-7f31-11ea-9aa4-4b07a04c27ac.png)

### Expected behavior

It would take the same amount of space to show the hidden language directly as it does to show the button to unveil it.

**Comment by indirectlylit** [comment]
seems like this will be useful for PF MVP so will do this in 0.13.x
