### ISSUE TITLE
Some issues with `make i18n` commands encountered while releasing 0.13.2 + 0.13.3

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6796]
### Observed behavior

Some issues that came up when trying build 0.13.2 with Italian

1. During `make i18n-update`, `django.mo` files for extra languages will be deleted. They are needed to support a subset of locales.
1. This might be user error, but `noto-full` and `noto-subset` CSS files for Italian were not automatically generated during the process of generating the i18n-related assets, and this wasn't detected until noticing 404 errors while viewing the `it` version of app.
1. Running `python build_tools/i18n/fonts.py update-font-manifest` at a fresh checkout of `release-0.13` will throw this error:

```
Traceback (most recent call last):
  File "build_tools/i18n/fonts.py", line 641, in <module>
    main()
  File "build_tools/i18n/fonts.py", line 627, in main
    command_update_font_manifest(args.ref)
  File "build_tools/i18n/fonts.py", line 560, in command_update_font_manifest
    noto_source.update_manifest(ref)
  File "/Users/jon/Github/kolibri/build_tools/i18n/noto_source.py", line 191, in update_manifest
    utils.json_dump_formatted(new_manifest, FONT_MANIFEST_PATH)
TypeError: json_dump_formatted() missing 1 required positional argument: 'file_name'
```

On the face of it, the call to `utils.json_dump_formatted` is missing a third argument for the file name i.e. `manifest.json`.

4. (found in 0.13.3 development) an issue with the `zh-Hans` locale (see comment below) A suggestion was to use [this django utility](https://github.com/django/django/blob/stable/1.11.x/django/utils/translation/trans_real.py#L81) to generate the name with the correct casing.

### Expected behavior

1. extra language mo files aren't deleted
1. clarification on steps to generate noto-related assets, especially after adding a new language.
1. no error when running `update-font-manifest`
1. Code generated to include `zh-Hans` should not change that exact casing (see comment below).
### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
Adding two issues encountered while working to enable Khmer, Nepali & Chinese:

1. Linter at the end of the `make i18n-update...` command first lingers a long time over this step:

```Kolibri Linter: Linting errors for kolibri/plugins/device/assets/src/views/SelectContentPage/DeleteResourcesModal.vue
Kolibri Linter: kolibri/plugins/device/assets/src/views/SelectContentPage/DeleteResourcesModal.vue did not conform to prettier standards
Kolibri Linter: Rewriting a prettier version of kolibri/plugins/device/assets/src/views/SelectContentPage/DeleteResourcesModal.vue
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```
    It eventually continues but then errors out here:

```Kolibri Linter: Linting errors for kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue
Kolibri Linter: kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue did not conform to prettier standards
Kolibri Linter: Rewriting a prettier version of kolibri/plugins/media_player/assets/src/views/MediaPlayerIndex.vue
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:194: recipe for target 'i18n-transfer-context' failed
make: *** [i18n-transfer-context] Error 1
```

2. As noted in [this PR comment](https://github.com/learningequality/kolibri/pull/6803#issuecomment-618121576), we need to change the renaming logic used to produce the `intl-locale-data.js` to account for locale names with 4 characters in the second part (like `zh-hans`), where it should capitalize just the first (to produce `zh-Hans.js`) instead of [all of them](https://github.com/learningequality/kolibri/blob/develop/build_tools/i18n/intl_code_gen.js#L71).

**Comment by indirectlylit** [comment]
> During make i18n-update, django.mo files for extra languages will be deleted. They are needed to support a subset of locales.

I believe this should be addressed  by c6047559d0e39783583e73867003cbc205aa5bb5

**Comment by indirectlylit** [comment]
I believe this should be closable. If there are still issues, maybe we can make new individual issues for them because there's a lot in here

**Comment by jonboiser** [comment]
Sounds good. We can use this issue as a reference if something happens the next time a new language is added.
