### ISSUE TITLE
'More info' button on the demo site banner cuts the string when too long

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#6799]
### Observed behavior
Reported by the Italian translator while checking the demo site after the upgrade to 0.13.2.
Full string in Italian is _Altre informazioni_, but happens in other languages too.

![Schermata da 2020-04-18 10-55-00](https://user-images.githubusercontent.com/1457929/79721971-89d75880-82e3-11ea-9867-535c1e2cecea.png)

### Expected behavior
Correctly and completely displayed string.

### User-facing consequences
Translation gives the incorrect appearance.

### Errors and logs
…

### Steps to reproduce
Go to the demo site and change language to Italian, Spanish or Portuguese. 

I see button is 100% `max-width`, and if that property is unchecked, the button actually expands and displays the whole string.

![button-more-info-demo-site](https://user-images.githubusercontent.com/1457929/79723096-7dec9600-82e5-11ea-9708-b373e7910c61.gif)

### Context

 * Kolibri version 0.13.2 on the demo banner
 * Operating system: Ubuntu 18.04
 * Browser: Firefox & Chrome

**Comment by sujithgnth** [comment]
@radinamatic Can I pick this up?

**Comment by radinamatic** [comment]
@sujithnath You are welcome to take a stab at it! :+1: :slightly_smiling_face: 

When you open the PR, cc @jonboiser or @indirectlylit to review!
