### ISSUE TITLE
Vue warn errors on reloading exercise in Chrome but not in Firefox

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#680]
## Summary

If I select exercise through Explore it displays OK, but once I try to reload the page a bunch of console `[Vue warn]` errors appear and no exercise. Happens only on Chrome, FF seems unaffected.

Happens on all the `Basic addition and subtraction` exercises.

## System information

 - Version: latest develop
 - Operating system: Ubuntu 16.10
 - Browser: Chrome

## Screenshots

![error - kolibri - google chrome_021](https://cloud.githubusercontent.com/assets/1457929/20493089/bbc47bea-b017-11e6-8158-1b1bf0a4ff43.png)

**Comment by radinamatic** [comment]
I just realized that the issue happens when I use my `Clear cache` extension which is configured to :boom: everything, but not if the normal browser reload is used. Does that mean that something is relying exclusively on cache, and not caching again if something is missing?

**Comment by radinamatic** [comment]
Still doesn't explain why it happens only on Chrome... :thinking:

**Comment by radinamatic** [comment]
Used BleachBit to vacum everything in FF cache & preferences, but it still loads fine!

**Comment by indirectlylit** [comment]
This may have been a cookie issue, fixed in 54b11d18e8a08bdade5cb77eb3e76a4b8fe30f51

Would you mind re-testing with the latest `develop` branch?

thanks!

**Comment by radinamatic** [comment]
No dice... :(

(pulled latest develop)

Selecting exercise from Explore, normal browser reload, copying & pasting the URL all work fine, but as soon as I delete the cache, weather through default Chrome settings or my `Clear cache` extension, everything goes red:

![errorkolibrichrome](https://cloud.githubusercontent.com/assets/1457929/20817285/05929e3e-b827-11e6-8c81-bb5b5be04f4c.png)

**Comment by radinamatic** [comment]
![error - kolibri - google chrome_051](https://cloud.githubusercontent.com/assets/1457929/20817325/3d292520-b827-11e6-851e-a997d99baa94.png)

**Comment by radinamatic** [comment]
But if I do a simple reload of the page with error, red goes away:

![find the missing number add and subtract within 1000 - khan academy math en add-sub - kolibri - google chrome_052](https://cloud.githubusercontent.com/assets/1457929/20817352/6d98981c-b827-11e6-8be9-0b589d4b8f71.png)

**Comment by 66eli77** [comment]
this issue seems disappeared on the latest develop branch

**Comment by radinamatic** [comment]
Quite possibly @66eli77, a lot of water under the Kolibri bridge since this issue... :wink: 

Closing now, will reopen if it reappears!
