### ISSUE TITLE
when clone kolibri project got git lfs font file download smudge error

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#6814]
Instructions:
 * when clone kolibri project got git lfs font file download smudge error

### Observed behavior
got an error.

### Expected behavior
cloning done.

### User-facing consequences
got an error.

### Errors and logs

```
Cloning into 'kolibri'...
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 203513 (delta 156), reused 138 (delta 73), pack-reused 203238
Receiving objects: 100% (203513/203513), 92.68 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (144739/144739), done.
Downloading kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff (9.1 KB)
Error downloading object: kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff (72aab79): Smudge error: Error downloading kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff (72aab79fd884694d10f730d54d5ca7aa354d05ca9983badddbf1ba91cd727e2d): batch response: Invalid deploy key for rationality6/kolibri

Errors logged to /Users/hyun/github/kolibri/.git/lfs/logs/20200428T203412.266318.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

```
fatal: kolibri/core/content/static/assets/h5p-standalone-dist/fonts/h5p-core-23.woff: smudge filter lfs failed
```

### Steps to reproduce
git clone kolibri
…

### Context
 * Kolibri version: develop
 * Operating system: OSX Mojave
 * Browser: Chrome

…

after type below everything seems fine
```
git lfs install --skip-smudge
git checkout -f HEAD
```

Seems this is bug from git lfs

https://documentation.red-gate.com/soc7/troubleshooting/error-messages/smudge-error-error-downloading

Is this a bug need to update to document or already solved?

Thank you.

**Comment by indirectlylit** [comment]
We should not be using `--skip-smudge` because that will prevent the binary files from being downloaded. Something else must be wrong.

I cannot reproduce the problem:

```
git clone https://github.com/learningequality/kolibri/
Cloning into 'kolibri'...
remote: Enumerating objects: 275, done.
remote: Counting objects: 100% (275/275), done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 203513 (delta 156), reused 139 (delta 74), pack-reused 203238
Receiving objects: 100% (203513/203513), 92.50 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (144743/144743), done.
Filtering content: 100% (55/55), 7.87 MiB | 1.40 MiB/s, done.
```

Could you please verify that you have recent versions of git and git LFS, and try again?

**Comment by rationality6** [comment]
After force lfs install. works fine.

This is a bug from git lfs

https://github.com/git-lfs/git-lfs/issues/911

Thank you @indirectlylit 

Closing this

![Screen Shot 2020-04-29 at 4 44 57 PM](https://user-images.githubusercontent.com/3889468/80572307-059a7900-8a39-11ea-97a5-985e523403e9.png)
