### ISSUE TITLE
Confusing events when trying to enable h5p_viewer plugin and importing sample content

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#6815]
### Observed behavior

When trying to enable h5p_viewer plugin and trying to import sample contents I was unable to import immediately after enabling plugin. Kolibri needs a restart. [Dev doc](https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/plugins.html?) lacks this detail.

During this trial, I updated Kolibri from 0.13.2rc3 to 0.13.2 to ensure that I was on the latest and noticed that non-core plugin h5p_viewer had been automatically disabled. If this is expected behaviour then it may need to be documented as well.

The sequence of events are as follows :

*Day 1 -*
1. Was on 0.13.2rc3 on Windows 10.
2. Enabled plugin, checked that it was enabled
3. Tried import, did not work
4. Restarted Kolibri
5. Tried import, did not work
6. Updated to 0.13.2
7. Tried import, did not work
*Day 2 after receiving guidance about restart from @ivanistheone -*
8. Restarted Kolibri
9. Tried import, did not work
10. Checked previous day's archived log and spotted that plugin was not enabled during the kolibri update sequence. 
11. Enabled the plugin
12. Restarted Kolibri
13. Import worked 

**Could the update process have disabled the previously enabled "non-core" plugin?** Am not yet sure about this.

### Expected behavior

h5p_viewer plugin should have been enabled upon command executing else should have been prompted to restart Kolibri at the terminal's response.

[Dev doc](https://kolibri-dev.readthedocs.io/en/develop/backend_architecture/plugins.html?) should have the detail about required restart after enabling a plugin.

Non-core plugin h5p_viewer should not have been disabled upon upgrade of Kolibri.

Noticed a SSL handshake error in logs while trying to import content from Studio.
 
### User-facing consequences

Confusing system behaviour for admins / developers.

### Errors and logs

[kolibri-2020-04-27.txt](https://github.com/learningequality/kolibri/files/4545615/kolibri-2020-04-27.txt)

### Steps to reproduce

Shared above.

### Context

Kolibri 0.13.2rc3 and 0.13.2
Windows 10
Python 3.4.3

**Comment by intelliant01** [comment]
Realised a mistake I had done. 

On Day 1 commands were executed in a cygwin terminal which assumed a different user home `/home/USERNAME/` and created a `.kolibri` folder therein instead of making modifications to the standard .kolibri folder for the user i.e. under `C:\Users\USERNAME`. The later folder would have been affected by executing the plugin enabling command in `cmd` terminal which I did on Day 2 only.

The log file from the cygwin home - `/home/USERNAME/.kolibri` is attached below.

[kolibri.txt](https://github.com/learningequality/kolibri/files/4547626/kolibri.txt)

@ivanistheone Could you pls check and ratify via the logs if this issue is worth pursuing further or should be closed?

The only points that may remain open is the addition to the documentation regarding restarting of Kolibri after enabling or disabling a plugin and improving the terminal messaging during enabling / disabling of plugin to include the need for restart.

**Comment by ivanistheone** [comment]
Added a comment in the docs https://github.com/learningequality/kolibri/pull/6816

We'll also assume the SSL handshake errors in the logs were due to so-so internet connectivity.

Okay closing since all seems to be normal. Thx for following up.
