### ISSUE TITLE
PF-related CSV import updates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6821]
## Coach identifiers

The identifiers currently used are not consistent with our user-facing terminology. In order to address this, let's update as follows:

* `COACH` -> `FACILITY_COACH`
* `ASSIGNABLE_COACH` -> `CLASS_COACH`

## Password behavior

1. Should be a required field. Empty fields should throw an error
2. On export, output an asterisk (`*`) instead of an empty field
3. On import, leave unchanged in the case of an asterisk. Otherwise, update with the value.
4. Remove "If it's not provided the system will set it to 'kolibri'" behavior

## Update users issue

This is still an issue: https://github.com/learningequality/kolibri/issues/6787

## Handling of class lists

Class names in comma-separated lists should be case-insensitive, and have any leading or trailing whitespace trimmed.

The following two values should be treated identically:

```
My class,another class
```

and

```
My class,  AnotheR ClasS
```

## NEW: do not export super admins

Request that super admins not be included in exported users

### Context

latest `pf-mvp` branch

**Comment by jredrejo** [comment]
@indirectlylit For the COACH identifiers, technically it's a trivial change, however, it's going to break the consitency with the rest of the code in Kolibri, using https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/constants/role_kinds.py

**Comment by jredrejo** [comment]
@indirectlylit about the password behaviour. Currently when a password value is not in the csv, it sets "kolibri" when creating an user because passwords can't be empty when creating an user. Don't you think that's better than triggering an error and skipping the user if it's empty?

If not, when creating an user, should `*` be replaced by a default password or trigger an error too?

**Comment by indirectlylit** [comment]
> For the COACH identifiers, technically it's a trivial change, however, it's going to break the consistency with the rest of the code in Kolibri

These are user-facing strings, so there is no requirement that they are consistent with Kolibri code. They must instead be consistent with user-facing documentation and UI.

**Comment by indirectlylit** [comment]
> @indirectlylit about the password behaviour. Currently when a password value is not in the csv, it sets "kolibri" when creating an user because passwords can't be empty when creating an user. Don't you think that's better than triggering an error and skipping the user if it's empty?
> 
> If not, when creating an user, should * be replaced by a default password or trigger an error too?

My intuition is that setting the password to the word "kolibri" seems arbitrary and unexpected.

I think we should tailor the errors to the condition to help people learn the behavior:

| scenario | condition | error message |
|--|--|--|
| New user | Asterisk or blank password field | _This user does not exist yet, so you must provide a password_ |
| Existing user | Blank password field | _The password field is required. To leave the password unchanged, insert an asterisk (*)_|

**Comment by indirectlylit** [comment]
looks good! opened one follow-up issue: https://github.com/learningequality/kolibri/issues/6850
