### ISSUE TITLE
Editing a coach user to change the type causes a crash when Save button is clicked twice.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6824]
### Observed behavior

Issues so far:

1. When I edit a coach and change the type then click `Save` the modal does not close and clicking the `Save` button again causes an error that shows the crash dialog.  The only way to recover was to click the `Refresh` button on the crash dialog that is shown.  This is very similar to this issue: https://github.com/learningequality/kolibri/issues/6400 

1. Another issue is that the modal dialog did not close after clicking the `Save` button.  This is the same with this issue: https://github.com/learningequality/kolibri/issues/6673

![2020-04-29-wed--pr test for richard tibbles 2](https://user-images.githubusercontent.com/175580/80575147-a38c4480-8a35-11ea-87e8-e209a552d81d.gif)

Here's the screenshot of the error in the Firefox v75.0 console:
<img width="1478" alt="Screen Shot 2020-04-29 at 4 31 09 PM" src="https://user-images.githubusercontent.com/175580/80576026-0d591e00-8a37-11ea-94d7-a5e1dc5affef.png">

### Expected behavior
The modal form should have closed when the `Save` button was clicked.

### User-facing consequences
User gets confused by the behavior.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4550530/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4550531/kolibri.txt)

### Steps to reproduce
1. Install [Kolibri v0.13.2](https://github.com/learningequality/kolibri/releases/download/v0.13.2/kolibri-0.13.2-unsigned.exe)
1. Create a coach user.
1. Edit that coach user and change the coach type then click the `Save` button.
1. Notice that the modal form did not close.
1. Click the `Save` button again to show the crash dialog.

### Context

* Kolibri version: [Kolibri v0.13.2](https://github.com/learningequality/kolibri/releases/download/v0.13.2/kolibri-0.13.2-unsigned.exe)
* Operating system: Windows 7
* Browser: Firefox v75.0

**Comment by indirectlylit** [comment]
The second issue (modal not closing) has been addressed in `develop` so let's keep the scope of this to the first issue
