### ISSUE TITLE
Kolibri "Enter channel token" form starts with capitals

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#6831]
### Observed behavior
When using Kolibri on a mobile device (Android) and going to import a channel, the Channel token form field defaults to capitalize-first keyboard.

![Enter channel token starts with capital](https://user-images.githubusercontent.com/163966/80716363-8737e880-8ac5-11ea-97d0-08541b22a0f8.jpg)

### Expected behavior

Let me start typing with lowercase letters.

### User-facing consequences

Requires an extra step to change to lowercase keyboard.

Users who don't know channel tokens are case sensitive will get an error
![Screenshot_20200423-170138_Kolibri](https://user-images.githubusercontent.com/163966/80716404-974fc800-8ac5-11ea-80ff-08caa1215f15.jpg)

### Context
 * Kolibri version: 0.13.2
 * Operating system: Android
 * Browser: webview inside Android app; but same behaviour observed previsously in client-server model when client is mobile browser

### Possible solution

set `autocapitalize="none"` on the form field: https://stackoverflow.com/a/5171812

**Comment by indirectlylit** [comment]
In addition, we should make the the input case-insensitive and trim whitespace

**Comment by Lewiscowles1986** [comment]
https://github.com/learningequality/kolibri-design-system/pull/29 has the autocapitalize.

By case-insensitive, would you prefer lowercase trimming or uppercase trimming (I think it's lowercase)

I guess the backend could become case insensetive and have the frontend only trim what it sends there (backend should also trim). Where is it getting the value from I guess is the question. Is is from SQL, or a file-system?

**Comment by indirectlylit** [comment]
This should be fixed the next time we bump the version of our design-system repo

**Comment by Lewiscowles1986** [comment]
Upstream only merged the changes to KeenUI today. Not sure if this was ever fixed locally, but now the upstream patches too 👍
