### ISSUE TITLE
backport disabling of BasicAuth

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6836]
### Observed behavior

back-port https://github.com/learningequality/kolibri/pull/6807 to 0.13

we originally targeted to 0.14 out of an abundance of caution but it ought to be safe enough in 0.13 with some quick sanity integration testing

### User-facing consequences

issues on IIAB

### Context

0.13.2

**Comment by benjaoming** [comment]
@radinamatic this is time-consuming to test as it involves simulating the behavior of another application with BasicAuth (IIAB being the only known one) and the affected case is isolated. Testing just once would be fine I think.. a recurring test scenario would not become relevant again once BasicAuth is removed?

There wasn't any positive case in which we're needing/using BasicAuth, @indirectlylit ?

Looking back at the change from #6807, I think it should have had an inline code-comment with a URL reference to the IIAB issue so it's "easily" understandable why this setting was added.

**Comment by indirectlylit** [comment]
> There wasn't any positive case in which we're needing/using BasicAuth, @indirectlylit ?

Not that we're aware of - just hard to know for sure. Agreed that we should add a comment when putting this in 0.13. 

I don't think it's necessary to fully reproduce the original failure and fix. More important is just to sanity check that nothing is obviously broken
