### ISSUE TITLE
Missing breadcrumbs navigating search results

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6841]
# Observed behavior

When navigating to an item from the search results list, it's not possible to determine which topic it originates from.

Searching "Geometry" in "Ubongo" (channel in development) shows 3 identical results (because the same video is reused 3 times in different topics). They appear to be exact duplicates because of missing topic tree information, such as breadcrumbs.

![missing navigation](https://user-images.githubusercontent.com/374612/80914846-9f6e6880-8d4e-11ea-9521-7f84e8e9609e.gif)

### Expected behavior

User can always consistently tell where they are in a channel tree structure and will understand search results as belonging to the same tree.

Additionally, one may receive the same results several times in the search results list, in which case results look like duplicates.

### User-facing consequences

The usefulness of search results are reduced when they cannot be used to navigate beyond single search results.

### Errors and logs

n/a

### Steps to reproduce

Try searching a channel with contents that are reused across topics.

### Context
0.13

**Comment by indirectlylit** [comment]
This behavior should already be implemented:

![image](https://user-images.githubusercontent.com/2367265/80982078-a8f3e100-8ddf-11ea-810b-0997e8e27833.png)

For example, see:

https://kolibri-demo.learningequality.org/en/learn/#/search?searchTerm=waves

**Comment by indirectlylit** [comment]
let me know if I'm misunderstanding and we'll re-open, but I think those videos need to share a common content node when they exist in multiple locations in the tree

**Comment by benjaoming** [comment]
That's super nice, going to get that implemented on Ubongo Kids

But have you tried following a search result? I still can't tell how one navigates from the search result to the topic that it's nested in.

**Comment by benjaoming** [comment]
The example with duplicate items have been fixed, thanks so much for the pointer @indirectlylit 

![image](https://user-images.githubusercontent.com/374612/80999762-7bda1980-8e45-11ea-873e-8ac8949c0e09.png)

What remains now would be items that do not have multiple locations (items in 1 location).

**Comment by indirectlylit** [comment]
thanks filed a follow-up issue on the unresolved piece: https://github.com/learningequality/kolibri/issues/6843
