### ISSUE TITLE
change 'back' behavior for navigating to content from search results

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6843]
### Observed behavior

As originally reported in https://github.com/learningequality/kolibri/issues/6841

* navigating to a topic from search takes you to a location within the channel hierarchy
* navigating to a resource from search takes you to a "sub-page" of search, without the ability to go to the channel hierarchy

![2020-05-04 09 30 18](https://user-images.githubusercontent.com/2367265/81011438-d440f500-8e0c-11ea-8eab-8cd48937e18c.gif)

### Expected behavior

Search results should probably take you to the location in the channel hierarchy for consistency. This also relates to proper use of the "back" arrow in Material design, which usually functions as a way of going "up" the hierarchy and is not the same as browser-back, which is how it's being implemented now.

If/when we eventually include lessons and their contained resources in search, having a resource in a lesson would behave as another "location", whereby clicking 'back' would take the learner to the lesson. (ref: https://github.com/learningequality/clearinghouse/issues/367)

### User-facing consequences

* User cannot navigate to a channel location from a search result
* Inconsistent use of 'back' button

### Steps to reproduce

search for an item and navigate to it

### Context

0.13.2

**Comment by indirectlylit** [comment]
@khangmach @nucleogenesis  relates to ongoing app-bar 'back' link work. Does the proposal look correct to you?

**Comment by khangmach** [comment]
Yeah Ben has a fair point. It's hard to find a way to get to the tree context of the search result. Clicking on a location link should direct you to that location instead of the resource render.

**Comment by khangmach** [comment]
We can address this in the next Learn update

**Comment by rtibbles** [comment]
This has been resolved by the implementation of within topic navigation within the content page.
