### ISSUE TITLE
re-enable the ability to assign lessons and quizzes to individual learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6849]
### Observed behavior

In 0.13 we had to drop this functionality at the last minute because strings weren't translated

cc @jonboiser @radinamatic @nucleogenesis 

### Expected behavior

translate the strings and enable the functionality!

### Context

0.13.x

**Comment by nucleogenesis** [comment]
I'm pretty sure @jonboiser already did this here: https://github.com/learningequality/kolibri/pull/6441

**Comment by indirectlylit** [comment]
thanks!
