### ISSUE TITLE
The /deep/ syntax is being deprecated

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#6876]
The /deep/ syntax is being deprecated

https://stackoverflow.com/questions/48032006/how-do-i-use-deep-or-in-vue-js

Do we need to replace /deep/ syntax to ::v-deep? I already tried to replace all and seem okay to me. How do you guys think?

### Observed behavior

<img width="542" alt="Screen Shot 2020-05-14 at 4 41 44 PM" src="https://user-images.githubusercontent.com/3889468/81906850-dc194a00-9601-11ea-9502-8a271e582c5b.png">

### Expected behavior

<img width="435" alt="Screen Shot 2020-05-14 at 4 41 49 PM" src="https://user-images.githubusercontent.com/3889468/81906860-df143a80-9601-11ea-84cf-cff6f96ec4ab.png">

### Errors and logs

deprecated syntax

### Context
Kolibri version latest dev
macOS Catalina 10.15.4
Chrome 81.0.4044.138 (official build) (64-bit)

**Comment by jonboiser** [comment]
@rationality6 Do you know where this new `::v-deep` decorator is documented in the Vue Docs and when it will be deprecated (in Vue 3?) I think if this new syntax works with with our current Vue 2 code base, we can try gradually moving to it right now.

**Comment by jonboiser** [comment]
It's actually a feature for vue-loader ([Link](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors)). And it is apparently Chrome that is deprecating the selector.

Thev vue-loader docs make it seem that `::v-deep` can be globally replaced anywhere `/deep/` is.

**Comment by rationality6** [comment]
@jonboiser, Yes, I've tried to find the documentation, but I couldn't.

Here is a summary about differences between `/deep/`, `::v-deep` and `>>>` [link](https://github.com/vuejs/vue-loader/issues/913#issuecomment-544833664)

<img width="768" alt="Screen Shot 2020-05-20 at 7 59 31 PM" src="https://user-images.githubusercontent.com/3889468/82438704-70891e00-9ad4-11ea-87ad-3873c9f6680d.png">

**Comment by indirectlylit** [comment]
@rationality6 are you seeing the deprecation errors in production, or only in the development server?

`/deep/` should be compiled away in production, so these warnings ought to be in the dev server only and can be safely ignored. If that's not the case, we have a webpack problem.

Ref: https://github.com/vuejs/vue-loader/issues/913

**Comment by rationality6** [comment]
@indirectlylit, I hadn't seen the deprecation error message in the console in both side production and development. I just found that while I searched about what is `/deep/` syntax for.
If Kolibri don't have a problem, it's okay

close this.

**Comment by indirectlylit** [comment]
thanks for investigating!
