### ISSUE TITLE
allow coaches to edit profile even if learners cannot

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6878]
### Observed behavior

Currently we have settings that affect both learners and coaches simultaneously:

![image](https://user-images.githubusercontent.com/2367265/81995513-6ad89780-95ff-11ea-8942-6d6b932550f8.png)

### Expected behavior

* Some users would like these settings to be separated so that coaches can perform these actions but learners cannot
* This is also important for learners when password-free login is enabled, because the 'change password' setting is meaningless for learners in that case.

### User-facing consequences

Implementors must make the choice between granting users more capability than desired, or preventing coaches from having enough capability

### Context

to be implemented in the `pf-mvp` branch and then merged to `develop`

**Comment by indirectlylit** [comment]
Leaving this open for now and switching milestones, because we'll be implementing a more sophisticated version in the `app-support` branch.

**Comment by jredrejo** [comment]
I think we can close this, as this code was integrated in the work done in `app-support`, so it can be considered completed.
@indirectlylit please, reopen it in case I'm missing something.
