### ISSUE TITLE
Tooltips do not respond on smaller screen sizes

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6888]
### Observed behavior

| Example 1 | Example 2 |
| -------- | -------- |
| ![Screenshot_20200507-140509_Kolibri](https://user-images.githubusercontent.com/6668144/82356358-480c0180-99b8-11ea-9008-5babfa28b430.jpg) | ![Screenshot_20200507-142548_Kolibri](https://user-images.githubusercontent.com/6668144/82356361-49d5c500-99b8-11ea-9da0-70ee292ae6d3.jpg) |

### Steps to reproduce

Long tap on any content card in Learn or Coach
Click the info icon on any input field

### Context

Kolibri version: 0.13.3
OS: Android

**Comment by indirectlylit** [comment]
Note that one of these examples overlaps with the issue in https://github.com/learningequality/kolibri/issues/6359

That issue recommends a different placement for that particular case. This issue should be a general solution.
