### ISSUE TITLE
Page jump while navigating through topics in resource selection

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6889]
### Observed behavior

Jumping to the top of the page while navigating through resource selection is a slightly jarring experience

| Click a topic | Jump to top of page | 
| ---------- | ------------------- |
| ![Screenshot_20200507-140147_Kolibri](https://user-images.githubusercontent.com/6668144/82357110-8229d300-99b9-11ea-950c-799102dddcc3.jpg) | ![Screenshot_20200507-140152_Kolibri](https://user-images.githubusercontent.com/6668144/82357122-87871d80-99b9-11ea-8084-2dd80737a015.jpg) |

### Expected behavior

A nicer option could be to jump the user to the top of the topic list

### Steps to reproduce

1. Go to Device > Channels
2. IMPORT
3. Select Studio
4. Select a channel
5. Navigate through channel

### Context

Kolibri version 0.13.3
OS: Android

**Comment by indirectlylit** [comment]
related: https://github.com/learningequality/kolibri/issues/6911
