### ISSUE TITLE
Channel filter too wide on the Learn search results page on mobile

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6891]
### Observed behavior

| 1 | 2 |
| - | - |
| ![Screenshot_20200519-103623_Chrome](https://user-images.githubusercontent.com/6668144/82359597-f023c980-99bc-11ea-9d5b-f23088cc9032.jpg) | ![Screenshot_20200519-103625_Chrome](https://user-images.githubusercontent.com/6668144/82359645-003ba900-99bd-11ea-8090-6cf9856f337c.jpg) |

### Expected behavior

On small screens, the select box should fit fully within the screen

### Steps to reproduce

Search something in Learn

### Context

Kolibri version 0.13.3
OS: Android & Chrome browser

**Comment by khangmach** [comment]
A note: channel filter seems to be normal if there's only one result card in view
