### ISSUE TITLE
collect and report aggregate stats about client browsers through telemetry

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6892]
### Observed behavior

We do not currently collect any aggregate information about client browsers.

### Expected behavior

We should collect some anonymous stats about client browsers and operating systems.

### User-facing consequences

We don't have sufficient data to make important decisions about browser support.

### Context

0.13.3

**Comment by paulbusse** [comment]
I've done something similar in the past. But I need more specific requirements:
- some architecture, how do want to get the info centrally?
- where do I collect the info from
- What are the stats you are looking for e.g. nr. of different browsers used per day

**Comment by rtibbles** [comment]
We have written up a specification here, let us know if there are any questions:

To capture browser data, we should add a field for device information to the UserSessionLog (https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/logger/models.py#L165)
This field should be a `CharField` called `device_info`.

The user agent string would then need to be passed into the update_log method in the session API: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/auth/api.py#L667

We should enhance the UserSessionLog update_log method to accept this additional argument of the UserAgent string (https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/logger/models.py#L180)

If a new log is created, it should set a string generated from the user agent to the `device_info` field. It should take the following format:
`"{os_family},{os_major_version}/{browser_family},{browser_major_version}"`

Where the above formatting variables correspond to data outputted by parsing the User Agent string with https://github.com/ua-parser/uap-python#retrieve-data-on-a-user-agent-string with the variables being set to "" when uap-python returns `None` for these values.

If no new log is created, we do not need to parse the user agent string or set this.

To return this data to the telemetry server, this data would need to be aggregated and added to the telemetry statistics: https://github.com/learningequality/kolibri/blob/42012dfb5423a09558758425ce3e1c97da8e379e/kolibri/core/analytics/utils.py#L170, the usersessionlogs would be aggregated on a per facility basis to provide aggregate counts of each different device info string. This data can be returned in the form of a dict with the `device_info` string as the key, and the count as the value. This should be returned from the `extract_facility_statistics` function as the `dis` (`# device_info_stats`) key of the its output dict.

By adding it to our facility statistics, it will then be automatically included in our telemetry pingbacks.

**Comment by paulbusse** [comment]
I propose to change the format to
`"{os_family},{os_major_version}/{browser_family},{browser_major_version}"`
This should make parsing later easier as there OS families with spaces (e.g. MAC OS X), but there are (exotic) OS families that end on digits (e.g. plan9 and 0S2)

**Comment by rtibbles** [comment]
Yes, that seems like a good improvement. There may still be issues with those separators being used inside the text, but looking through the names in the yaml file: https://github.com/ua-parser/uap-core/blob/ec8322ffe14f94d88131cec550705f392085a519/regexes.yaml seems like they will be fairly exotic, and not ones we are as worried about counting or introspecting.

I have updated the comment above.

**Comment by rtibbles** [comment]
Fixed in #7658

**Comment by indirectlylit** [comment]
Thanks for your contribution @paulbusse 

Feel free to add your name to https://github.com/learningequality/kolibri/blob/develop/AUTHORS.md
