### ISSUE TITLE
Plus symbol on question number in quiz creation undergoes weird line break

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6893]
### Observed behavior
![image](https://user-images.githubusercontent.com/25045166/82391543-67c21a80-99f6-11ea-8307-aceaf95cfe39.png)

### Expected behavior
Minus and plus sign are side by side and do not break

### User-facing consequences
Buggy look

### Steps to reproduce
Try making a new quiz

### Context
Kolibri version 0.13.3
OS: Android & Chrome browser

**Comment by rationality6** [comment]
Hi, @khangmach
Is this problem already fixed on latest dev?
This is my screenshot with env below

<img width="489" alt="Screen Shot 2020-05-20 at 8 23 12 PM" src="https://user-images.githubusercontent.com/3889468/82440714-c6ab9080-9ad7-11ea-9cdc-b0ec8ca7e420.png">

Kolibri version latest dev
macOS Catalina 10.15.4
Chrome 81.0.4044.138 (official build) (64-bit)
