### ISSUE TITLE
Buggy padding on exercise progress tracker

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6894]
### Observed behavior
![image](https://user-images.githubusercontent.com/25045166/82391693-cb4c4800-99f6-11ea-8b62-faa1e44ce623.png)

Padding top and bottom need to match. Currently there is too much padding on the bottom. We should either match the top padding or reduce the bottom padding to match the top

### Expected behavior
Same top and bottom padding

### User-facing consequences
Layout issues

### Steps to reproduce
Play with an exercise in learn

### Context
Kolibri version: 0.13.3
OS: Android

**Comment by indirectlylit** [comment]
That space is reserved for messages, so unless we want the bottom bar shifting in height, this is working as designed:

![image](https://user-images.githubusercontent.com/2367265/82502516-22602480-9aac-11ea-9570-b18a598ab0c8.png)
