### ISSUE TITLE
headers can take up lots of space on small screens

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6900]
### Observed behavior

| Some headers can be very large on smalls screens |
|--|
|![image](https://user-images.githubusercontent.com/2367265/82494041-d1e1ca80-9a9d-11ea-8736-afad99c3f32d.png)|

### Expected behavior

A few options:

* change font sizes globally and/or responsively (would need to be assessed globally)
* do nothing; the behavior works as intended and the user can easily scroll down
* determine how to address on case-by-case basis

### User-facing consequences

more scrolling and less efficient use of screen real estate

### Context

0.13

**Comment by rtibbles** [comment]
This has been addressed in learn in 0.15. We should open specific issues for any other extant concerns.
