### ISSUE TITLE
'Welcome' modal shows up every time app is restarted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6903]
### Observed behavior

This is shown every time the app restarts:

![image](https://user-images.githubusercontent.com/2367265/82496727-08214900-9aa2-11ea-9fae-373d853b376a.png)

### Expected behavior

modal should only be shown once

### User-facing consequences

annoyance

### Context

0.13.2

**Comment by jonboiser** [comment]
Fixed in #6938
