### ISSUE TITLE
Automated tests and gherkin stories still needed for #6865

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#6904]
We didn't have time to do automated tests or gherkin stories for https://github.com/learningequality/kolibri/pull/6865 -- but if would be good to have these before this ships in 0.14, even if it's still a hidden feature at that point.

**Comment by indirectlylit** [comment]
cc @jamalex

**Comment by radinamatic** [comment]
@jamalex Does this [Gherkin by @kollivie](https://www.notion.so/learningequality/Gherkin-scenarios-50a7e8196d5046d4ad6f6a7fb2448bf0#c6b3a6d94ea04185b5be8c58a539901e)r covers all that needs to be tested?

**Comment by jamalex** [comment]
That looks good, yep! There may be some more nuanced stuff around rescanning etc, but we need to think more about how we might do scanning in the first place. For the current functionality, this seems fine.

**Comment by radinamatic** [comment]
Awesome, thank you, will open the PR to transfer the Gherkin to the repo!
