### ISSUE TITLE
Questions answered seems to be out of sync in quiz

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6905]
### Observed behavior
Questions answered is 0, but on the 4th question.

![image](https://user-images.githubusercontent.com/1680573/82577735-3eada100-9b40-11ea-87ae-9d5660301545.png)

Possible that the previous 3 questions were not attempted, but needs verification.

### Expected behavior
Questions answered should match the number answered.

### User-facing consequences
Confusing learner experience.

### Steps to reproduce
Create a quiz as a coach, then take the quiz as a learner, answer a question move on to the next.

### Context
 * Kolibri Android app
 * Android ?
 * Android WebView

Motorola One Power

**Comment by indirectlylit** [comment]
were the first three questions actually answered?

**Comment by rtibbles** [comment]
Not going to get more info on this, so closing.
