### ISSUE TITLE
Lesson preview of exercise doesn't display in coach lesson creation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6906]
### Observed behavior
Preview appears to fail to render the exercise.

![image](https://user-images.githubusercontent.com/1680573/82578122-d4493080-9b40-11ea-9360-aafa578d7082.png)

![image](https://user-images.githubusercontent.com/1680573/82578139-d90de480-9b40-11ea-89c6-8cea1cae748b.png)

### Expected behavior
Preview should display in all screen sizes

### User-facing consequences
Confusion for a coach creating lessons on mobile.

## Context
Kolibri Android app
Android ?
Android WebView
Motorola One Power

**Comment by MisRob** [comment]
I've checked this issue for a couple of resources and the preview seems to be rendered though horizontal and vertical scrollbars are not visible (I suppose that on smaller screens it can look like that preview is not rendered or scroll behavior is not working at all):

For example this preview in Chrome
![preview-browser](https://user-images.githubusercontent.com/13509191/83757594-01353180-a671-11ea-939c-e128de6480b5.png)

looks like
![preview-android](https://user-images.githubusercontent.com/13509191/83758432-5d4c8580-a672-11ea-8466-387a14dbf08c.jpg)

in Android app and I am able to use vertical scroll for questions lists and content area but can't scroll horizontally there.

It seems that there are two issues:

**1. (both browser and Android) The need for a different page layout for smaller resolutions**

Maybe getting rid of questions list aside and rather using drop down menu for questions selection and displaying question content area below the menu?

**2. (Android specific) Make horizontal scroll work for content area and indicate it to users**

I am not familiar with Android apps and planning to look into it in more detail though after a brief research it seems that there is some settings that might be helpful:
https://developer.android.com/reference/android/webkit/WebView#setScrollBarStyle(int)
https://developer.android.com/reference/android/webkit/WebView#setInitialScale(int)

@indirectlylit @khangmach @jtamiace Any UX/UI suggestions?

**Comment by indirectlylit** [comment]
One option would be mirroring the learner experience of quizzes, which hides side bar on small screens and leverages ‘next’/‘previous’ buttons instead. Some design is still required though.

however given the size of this effort and the fact that coaching with a small device is uncommon, I'm removing this from the current milestone

**Comment by rtibbles** [comment]
I think the issue as originally described does not appear to be extant, so I am going to close this.
