### ISSUE TITLE
Using Android native keyboard search as you type doesn't happen unless you click out of the keyboard

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6908]
### Observed behavior
In Device channel filtering, we use search as you type to filter channels.
If you are using the Android keyboard, this does not trigger anything until you close out the keyboard.

![image](https://user-images.githubusercontent.com/1680573/82578926-ebd4e900-9b41-11ea-8919-4f83a5f1a239.png)

### Expected behavior
Ideally search as you type should work regardless of the input modality.

We might need a search button if this is not possible?

### User-facing consequences
Confusing as to when the search will actually happen or how to trigger it.

**Comment by bjester** [comment]
Note: The standard Android keyboard already has a return button that essentially acts as a search button.

**Comment by indirectlylit** [comment]
@kollivier would you mind reviewing this?
