### ISSUE TITLE
Copies of lessons don't reflect recent deletions or reordering of resources

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6916]
### Observed behavior

When I add 4 resources into a lesson, delete 2 resources from the lesson, and make a copy of the lesson, the copy of the lesson will end up having 4 resources instead of 2.
However, if after deleting 2 resources, I go back to the list of all lessons, and go to the specific lesson page again to make a copy of it, the copy of the lesson will contain the correct number of resources.

### Expected behavior

copy of the lesson should contain the correct number of resources

### User-facing consequences

users may be confused by the lesson copy

### Errors and logs

no errors in the log

### Steps to reproduce

1. add 4 resources to a lesson
2. delete 1 resource in the lesson
3. make a copy of the lesson
4. check the number of resources in the copy of the lesson, the number shows 4 instead of 3

### Context

Kolibri version: 0.13.2
Operating system: MacOSX
Browser: Chrome

**Comment by paulbusse** [comment]
I reproduced the issue and found that changes made to lesson resources (deletion and changing the order) are ignored when creating a copy. Using the developer tools in the browser, one can see that the information sent to the backend contains the wrong information (deleted resource, wrong order of the resources).
After _refreshing the page_, the copy behaves as expected. Imho, this is a frontend issue.

**Comment by jonboiser** [comment]
Yeah, this is a frontend issue. When we copy a lesson it seems like we're actually POSTing a new lesson with stale information about the lesson. I'm not sure how the UI is holding on to the lesson resources as initially fetched, while still presenting the latest changes (deleting and reordering items). 

We may be duplicating the lesson data somewhere in Vuex or somewhere and sending the wrong copy to the lesson endpoint.

**Comment by jonboiser** [comment]
Fixed in 482f293f2deec49384553aac9b5afb7de8f5a193
