### ISSUE TITLE
Long channel names truncated in two UI components

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#6918]
### Observed behavior

I have a feeling these are both part of the same bredcumbs component, so reporitng together.

1. During channel import, the channel name above the select content component is cutoff:
<img width="995" alt="WHY CUTOFF" src="https://user-images.githubusercontent.com/163966/82684340-68d69000-9c20-11ea-8f23-7edb629c7d39.png">

2. Also gets cut off in breadcrumbs:
![Screen Shot 2020-05-22 at 11 31 31 AM](https://user-images.githubusercontent.com/163966/82684412-902d5d00-9c20-11ea-9e48-97bc14ebaa46.png)

### Expected behavior

I would have expected to see the complete channel name in those places, given there is room for it. 

### Possible fix

Perhaps it is possible for the breadcumb component not to apply the max-width property for the last item in the list?

**Comment by MisRob** [comment]
Re-opening since this will be fixed after we install the new version of KDS which hasn't happened yet
