### ISSUE TITLE
app-support: preinstalled content can be deleted, but not added again

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#6926]
This involves the Kolibri flatpak on Linux, built from the app-support branch, with a content extension installed so Kolibri has the environment variable _KOLIBRI_CONTENT_FALLBACK_DIRS_ set to include `/path/to/some/content/extension`. In this environment, it is possible for an administrator to delete content that was preinstalled, and this is presented correctly in the UI: the content is no longer browsable, and it appears as deleted in the user interface.

To reproduce this, I'm using a content extension which includes the English Khan Academy (1ceff53605e55bef987d88e0908658c5) Resources node (c4b7fbced0815809a1f7ed411f49cd9c).

 * Navigate to the management page for the Khan Academy channel. Choose Resources, then select "Explore new features" and click Delete. This should finish successfully.
 * Note that the content is no longer listed when browsing the channel.
 * Go back to the management page for the Khan Academy channel, and click "Import more". Note that the text to the right side of the Resources section correctly says "8 of 9 resources on your device". Browse into this section.

The "Explore new features" section is checked, with the checkbox disabled, and the interface says "Already on your device". There is no obvious way to add this content back. Note that it is possible to navigate one level up, select the Resources section and import all of the content from that section, in which case Kolibri will correctly import the deleted content.

**Comment by sakshampathak1508** [comment]
Hi i would like to work on this issue

**Comment by rtibbles** [comment]
@dylanmccall I wasn't able to replicate this issue on the current 0.15 branch.

**Comment by rtibbles** [comment]
Have confirmed with @dylanmccall that this is no longer extant. Closing!
