### ISSUE TITLE
PEX designed for Python 2.7

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6937]
### Observed behavior

Python 2.7 is not installed on many recently released platforms and is end-of-life. Running the .pex on such platforms gives an error.

Having `#!/usr/bin/env python` could solve this, otherwise `#!/usr/bin/python3`. The quick gains of a .pex are reduced if one also has to install python 2.

Documentation on download page says:

> You can run the portable offline executable if you have Python 2.7+ or 3.4+ installed.

This is contradicted by the current shebag `#!/usr/bin/python` because there are no systems where this would point to Python 3. It's discouraged to link `python` to Python 3, since many programs would expect `python` to point to Python 2.

See: https://wiki.ubuntu.com/Python/3

> /usr/bin/python will point to Python 3. No, this is not going to happen (unless PEP 394 advocates otherwise, which is doubtful for the foreseeable future). /usr/bin/python and /usr/bin/python2 will point to Python 2.7 and /usr/bin/python3 will point to the latest supported Python 3 version. 

### Expected behavior

Running the .pex should be easy

### User-facing consequences

Needs instructions of installing Python 2.

### Errors and logs

```
➜  ./kolibri-0.14.0.dev0_git.20200528110047.pex start --foreground --debug
zsh: ./kolibri-0.14.0.dev0_git.20200528110047.pex: bad interpreter: /usr/bin/python: no such file or directory
```

### Steps to reproduce

See above

### Context

Ubuntu 18.04 desktop with "minimal" chosen during installation or any new default Ubuntu 20.04.

**Comment by Lewiscowles1986** [comment]
I think `/usr/bin/env python` may work better, or just having people run the files using their python interpreter of choice rather than forcing one using shebang's which can be OS / distro specific.

**Comment by rtibbles** [comment]
We are no longer prioritizing the pex as a distribution mechanism, so I would say this is a won't fix until we drop Python 2.
