### ISSUE TITLE
Content progress states don't carry over to search results

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6941]
### Observed behavior
Content progress states of in-progress and complete do not carry over into the search results. 

**Screenshot 1:** 
I have made some progress on "Dalton's law of partial pressures" as indicated on the exercise card

<img width="994" alt="Screen Shot 2020-05-28 at 11 55 37 AM" src="https://user-images.githubusercontent.com/25045166/83182252-eeec4e00-a0da-11ea-9d2a-df7246771d93.png">

**Screenshot 2:** 
The in-progress state on the card does not carry over to search results

<img width="1068" alt="Screen Shot 2020-05-28 at 11 56 05 AM" src="https://user-images.githubusercontent.com/25045166/83182235-e98f0380-a0da-11ea-9baf-a5617b14e195.png">

### Expected behavior
Progression states should carry over to aid user recognition. This especially important as quizzes and lessons will soon be searchable as well and we don't want to leave an impression that those are in not started states.

Duplicate items can be handled in a way such as:
<img width="475" alt="Group 19" src="https://user-images.githubusercontent.com/25045166/83183496-c06f7280-a0dc-11ea-8c12-2db1643cf09f.png">

### User-facing consequences
Mismatch in progression states could be confusing to learners at first. They have to inspect further to see if it is indeed the content they were looking for. 

### Steps to reproduce
- Engage with a content item in Learn > channels
- Search for that exact item in Learn > search

### Context
Tell us about your environment, including:
 * Kolibri version: beta
 * Operating system: MacOS
 * Browser: Chrome

**Comment by nucleogenesis** [comment]
Try checking this out and replicating it with the branch: https://github.com/learningequality/kolibri/pull/8000 - I did some work making sure progress was properly gathered from the API on the frontend.

**Comment by rtibbles** [comment]
This is no longer extant after the release of 0.15
