### ISSUE TITLE
ifcfg and ifaddr follow-up

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6942]
### Observed behavior

follow-up from https://github.com/learningequality/kolibri/pull/6764

* In #6764 we switched from depending on `ifcfg` directly to calling `zeroconf.get_all_addresses`
* The same PR pointed at [a new version of our fork of zeroconf](https://github.com/learningequality/python-zeroconf-py2compat/pull/2/files) which adds conditional logic for Android
* It was [recommended that](https://github.com/learningequality/kolibri/pull/6764#issuecomment-629350924) this would have been better addressed by patching `ifcfg` directly, which makes sense.
* A [subsequent change](https://github.com/learningequality/python-zeroconf-py2compat/pull/3/files) to the zeroconf fork removed `ifcfg` altogether which was a bit surprising to see, because in the past we've iterated on `ifcfg` to solve a variety of os-specific issues.

### User-facing consequences

I am a little concerned about the risk of regressions here due to an unexpected dependency change. Let's document what changes we're making and why more methodically, and if we're deciding to change dependencies, we need some rigorous regression testing.

### Context

`app-support` branch and 0.14.0

**Comment by jamalex** [comment]
Sorry, I agree that this was done too hastily -- it was part of getting things working for Flatpak (which doesn't have the necessary networking tools available within the sandbox to use ifcfg). Discussion was [here](https://learningequality.slack.com/archives/CM5KYJ8MQ/p1590174742042800).

`ifaddr` is pure Python and looks to not have the same dependencies on access to command-line tools as `ifcfg`.

Before we merge in from the app-support branch (which is the only place this change was made so far, I believe -- though I guess that's now been/being merged into develop), let's definitely be sure to do more cross-platform/environment testing (Windows, OSX, Flatpak, Android, Debian).

**Comment by indirectlylit** [comment]
Thanks sounds good.

Also just a reminder of this item in the PR checklist:

>   If this includes an internal dependency change, a link to the diff is provided

**Comment by indirectlylit** [comment]
I believe this may be addressed. Let's follow up with @jamalex and close if appropriate

**Comment by jamalex** [comment]
Yep, we're back to where we were before.
