### ISSUE TITLE
Completed terminology on quiz cards does not read well

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6944]
### Observed behavior
When learners finish a quiz, their quiz card goes from an in-progress text indicator "N questions left" to "Completed: n%". As seen below in the screenshot, it reads like the learner has completed 50% of the quiz. 

<img width="682" alt="Screen Shot 2020-05-27 at 1 22 07 PM" src="https://user-images.githubusercontent.com/25045166/83205312-148d4d80-a103-11ea-88cc-0b41305524fb.png">

### Expected behavior
Better terminology to more accurately describe the percentage. It indicates a quiz score so I would expect terminology along the lines of "Score/Scored". See below:

<img width="716" alt="Screen Shot 2020-05-28 at 4 52 22 PM" src="https://user-images.githubusercontent.com/25045166/83205558-b4e37200-a103-11ea-915e-d5a3e0c55d0d.png">

### User-facing consequences
Misleading completion indicator

### Steps to reproduce
Complete a quiz and navigate back to the quiz in the classes tab

### Context
Tell us about your environment, including:
 * Kolibri version: beta
 * Operating system MacOS
 * Browser: Chrome

**Comment by Tlazypanda** [comment]
@khangmach can I work on this?  :v:
