### ISSUE TITLE
Exercise question preview desperately needs more scrolling room

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6945]
### Observed behavior
While previewing an exercise in quiz creation or lesson resource management, there is extremely little room for scrolling through an exercise's question list. 

![GIF1](https://user-images.githubusercontent.com/25045166/83206883-bfebd180-a106-11ea-89ce-ca11f653b002.gif)

This is more drastic on smaller-medium screens:

![GIF2](https://user-images.githubusercontent.com/25045166/83206908-cbd79380-a106-11ea-8353-fa3e23a26895.gif)

### Expected behavior
Show the entire question list similar to the quiz preview in Lessons or in the quiz-taking screen

<img width="871" alt="Screen Shot 2020-05-28 at 5 16 01 PM" src="https://user-images.githubusercontent.com/25045166/83207032-19ec9700-a107-11ea-9a94-882e92b95455.png">

<img width="997" alt="Screen Shot 2020-05-27 at 1 04 19 PM" src="https://user-images.githubusercontent.com/25045166/83207083-2cff6700-a107-11ea-9ba9-7a28646b2221.png">

### User-facing consequences
The small space is frustrating to scroll through. Often you will find yourself doing a scrolling motion on the trackpad or mouse and accidentally over-scroll outside of the question list container -- which causes the entire page to scroll instead of just the question list. 

### Steps to reproduce
- Navigate to Coach > Quizzes
- Make a new quiz
- Preview an exercise and scroll through the question list

### Context
Tell us about your environment, including:
 * Kolibri version: Beta
 * Operating system: MacOS
 * Browser: Chrome

**Comment by khangmach** [comment]
This should be an easy fix. We already have an available layout via quiz details page in coach (plan tab -> quizzes -> quiz details)

<img width="3664" alt="s1" src="https://user-images.githubusercontent.com/25045166/114059605-62a5ce00-9849-11eb-911f-e6619e76c315.png">

**Comment by sairina** [comment]
@khangmach and @jonboiser -

Currently, I've made some changes to the original scroll. Option 1 is on the left, and Option 2 is on the right:
|Maintains some scrolling|Has no scrolling|
|--|--|
|![2021-06-02 14 29 33](https://user-images.githubusercontent.com/13563002/120554759-fcec4300-c3ae-11eb-9ee6-38788843faed.gif)|![2021-06-02 14 28 17](https://user-images.githubusercontent.com/13563002/120554645-d9c19380-c3ae-11eb-93f9-551f408642b7.gif)|

Which one is closer to the behavior we would expect to see? With Option 2, there is no scrollbar at all for the questions column, but gets rid of the `maxHeight` that the outer container (the `MultiPanelLayout` component) has, which would have other effects in other components in the code.

**Comment by khangmach** [comment]
For option 1, do you have to scroll through the page scrollbar first in order to scroll through the question list?

**Comment by sairina** [comment]
No, you can scroll through the question list without getting to the bottom of the page scroll. That works as long as you are hovering over the question list.

**Comment by indirectlylit** [comment]
Relevant previous work and discussion:

* [Note about UX issues with nested scrolling areas](https://github.com/learningequality/clearinghouse/issues/291)
* [Design work on responsive behaviors](https://docs.google.com/presentation/d/1tBbRvjjgtpZZ8mc5mAUvTUPI7IN_7Q5LmX0qhH2ealY/edit#slide=id.g5c315d115c_0_21)
* [Previous update to quiz view](https://github.com/learningequality/kolibri/pull/5448)
* [Discussion about similar side-by-side scrolling panels](https://learningequality.slack.com/archives/CAKK24483/p1556558623060400) and [subsequent sketch](https://learningequality.slack.com/archives/CAKK24483/p1556822354073000)

My personal rule of thumb has been to always avoid nesting scrolling panels, and when possible to only have a single scrolling area on a page. There are exceptions when this isn't possible, but generally these introduce other complexities on smaller screens.

**Comment by sairina** [comment]
Couple things I'm thinking about now:
- From the Slack conversation and [subsequent gif](https://learningequality.slack.com/archives/CAKK24483/p1556924591087000), I'm gathering that there shouldn't be any scrollbars at all for the page itself - and the scrolling should actually happen in the `MultiPaneLayout` container?
- That makes me wonder, should there be space between the end of the container and the bottom of the page? (see gifs from [comment above](https://github.com/learningequality/kolibri/issues/6945#issuecomment-853396827)) That seems to be creating some of the extra scrolling that's happening on the page scroll.
- Also, it seems that the `header` in the `MultiPaneLayout` is giant and does not change even if the size of the window is reduced, which is making the rest of the container shrink, and thus making that space for the `QuestionList` also shrink. I see that in the spec, the header should say the same, but should that be the case when the height of the window changes (as opposed to the width)?

**Comment by sairina** [comment]
Also, I noticed that [`MultiPaneLayout`](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/MultiPaneLayout.vue) has no K-components -  I'm wondering if this is part of the reason why it is also not responsive at different break points (width-wise, for sure) 😬 . Should there be a refactor of this component, instead of just trying to fix the scrolling?

**Comment by khangmach** [comment]
>I'm gathering that there shouldn't be any scrollbars at all for the page itself - and the scrolling should actually happen in the MultiPaneLayout container?

I think we can try this approach. This means that the page length would be determined by the max width of the container though, right?

>That makes me wonder, should there be space between the end of the container and the bottom of the page?

I never knew why the extra space was there and it doesn't serve a visible purpose. We can scrap it. 

>Also, it seems that the header in the MultiPaneLayout is giant and does not change even if the size of the window is reduced

Once it's developed, I want to carry over the page header styles from the new content renderer page. That should take care of the huge header issues.

**Comment by sairina** [comment]
- Extra space: it's actually in _everything_, so is there a reason why it is there? @jonboiser @indirectlylit  - maybe you have some context?

https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreBase/index.vue#L581
