### ISSUE TITLE
Lesson resource selection is missing topic title and description

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#6957]
### Observed behavior
The lesson resource page pictured on the left is missing the topic title and description. Quiz exercise selection does this correctly, pictured on the right.

<img width="1271" alt="Screen Shot 2020-05-29 at 1 59 19 PM" src="https://user-images.githubusercontent.com/25045166/83305135-0b5cb900-a1b5-11ea-9dd9-515549e426a5.png">

### Expected behavior
Titles and descriptions show for the current node the user is on. Unless we have a really good reason for omitting this information, the two modes should show as much consistent information as possible

### User-facing consequences
Users dealing with two similar interfaces with different information for ambiguous reasons.

### Steps to reproduce
- Open lesson resource management on a lesson
- Create a new quiz 
- Navigate to the same topic for both
- Compare

### Context
Tell us about your environment, including:
 * Kolibri version: 0.14 pex
 * Operating system: macOS
 * Browser: Chrome

**Comment by rtibbles** [comment]
Feel like this could be fixed in 0.13, as it wouldn't require any strings (just the content based title and description text).

**Comment by Tlazypanda** [comment]
@khangmach can I work on this?  :v:
