### ISSUE TITLE
replace remaining strings that say 'exam' with 'quiz'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6972]
### Observed behavior

see e.g.

https://github.com/learningequality/kolibri/blob/77a5184970072e81f81d913af7c53dae82089dd2/kolibri/plugins/coach/assets/src/views/common/LearnerQuizReport.vue#L86

> This exam has not been started yet

possibly exists in other places?

### Expected behavior

> This quiz has not been started yet

### User-facing consequences

inconsistent nomenclature

### Context

0.14

**Comment by Tlazypanda** [comment]
@indirectlylit Looked through the files could find in one more place  :sweat_smile: `assets/learn/src/modules/examViewer/handlers.js`  but might have to check again to make sure didn't miss anything

**Comment by indirectlylit** [comment]
thanks for checking @Tlazypanda 

I think those are just internal error messages
