### ISSUE TITLE
Kolibri design system and Kolibri are separated

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#6979]
After they are separated.

many issues moved to Kolibri design system especially UI parts

Is there a guideline to move?

**Comment by rationality6** [comment]
I found documentations https://kolibri-design-system.netlify.app/
and these comments

`
Share ideas or concerns with Devon, Jessica, and Jacob directly
Submit a pull request  or issue  to the GitHub repo
Leave a comment in the Notion project 
`

Close this

**Comment by indirectlylit** [comment]
thanks!  it's still a work in progress

we have a number of open issues: https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+design+system%22
