### ISSUE TITLE
import/export: drive listing improvements

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#698]
## Part 1 - drive listing

Currently, the single-drive view looks different from multiple-drives. We also completely hide drives that are deemed "not available" - i.e. drives that don't have data on import and or are not writable on export.

We've had feedback that all these special cases are confusing, and that it would be simpler to always use the same radio button UI:

 * All drives should be shown as radio buttons
 * Drives that are 'not available' should be disabled radio buttons. After the drive name, we should add text such as _(not writable)_ or _(no Kolibri data found)_ to indicate why they're disabled.
 * If only one drive is available, it should still be shown as a radio button.

## Part 2 - translation strings and pluralization

The import/export modal window don't currently use `$tr` wrapping, and therefore don't properly pluralize messaging. All user-facing strings should be wrapped and make use of pluralization directives as necessary.

See e.g.:
 * http://formatjs.io/guides/message-syntax/#plural-format
 * https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach_tools/assets/src/vue/reports/summary-section/index.vue#L115

## Part 3 - layout

Currently everything is center-aligned, which looks messy for lists of radio buttons and is inconsistent with other modal dialogs.

Let's take out out the center-alignment and make the text alignment consistent with other modals: left-aligned headers, and right-aligned buttons.

**Comment by DXCanas** [comment]
RE: Drive listing

Excuse my ignorance, but how do we go about showing drives? Does it automatically pick up a flash drive if it's plugged into the machine?

**Comment by indirectlylit** [comment]
yes. The nuance is that drive interaction is for the machine running the Kolibri server, not the client. So there is a potential UX confusion if these are on different machines.

**Comment by DXCanas** [comment]
> We've had feedback that all these special cases are confusing...
Do you happen to know where I can find these feedback docs?

Is there any reason we don't want to use a `select`?

**Comment by indirectlylit** [comment]
For this UI specifically: eventually we want to add additional meta-data about each channel, such as available disk space and the names of channels in them. Much easier to nicely format that in a list of radio buttons.

More generally, select boxes:

* are really hard to style correctly in a cross-platform way
* hide the options until the user clicks in

**Comment by DXCanas** [comment]
Fair enough. I've seen drive selection done as a select box before, but radio buttons make more sense with our use cases.

**Comment by indirectlylit** [comment]
>> We've had feedback that all these special cases are confusing...

> Do you happen to know where I can find these feedback docs?

I can't find anything documented beyond this card: https://trello.com/c/2TISd8cH/631-drive-listing-is-confusing-when-only-one-drive-is-available-better-to-show-a-radio-button-consistent-with-other-views

But definitely a few people have commented that they want to see consistent views regardless of how many drives are available, and that all drives should be shown (with some disabled with reasons).

**Comment by indirectlylit** [comment]
done!
