### ISSUE TITLE
Unexpected arrows next to username list

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#6987]
### Observed behavior

When navigating the Profuturo online server as an admin under the Users tab, there are unexpected arrows which appear next to each username

### Expected behavior

There are no expectations of arrows

### User-facing consequences

User may be confused by the design, but otherwise there seems to be consequence on clicking on the arrows

### Steps to reproduce

1. Navigate to Profuturo online server: profuturo.learningequality.org
2. Log in as an admin
3. Navigate to the Facilty --> Users tab
4. View the user list

### Context

 * Kolibri version: Profuturo online server v0.13.3
 * Browser: Chromium Version 81.0.4044.138 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

![Screenshot from 2020-06-03 18-20-14](https://user-images.githubusercontent.com/5150483/83696089-88c76580-a5c9-11ea-9a74-dc07b22fa115.png)

I tested the view when the window size of my browser was reduced - the problem remained

![Screenshot from 2020-06-03 18-21-03](https://user-images.githubusercontent.com/5150483/83696087-88c76580-a5c9-11ea-8c40-0ad25d910d37.png)

I changed the Zoom percentage to 50% and that eliminated the arrows

![Screenshot from 2020-06-03 18-21-46](https://user-images.githubusercontent.com/5150483/83696086-882ecf00-a5c9-11ea-9f71-bca003402fea.png)

**Comment by radinamatic** [comment]
Not able to repro this on Chromium Version 83.0.4103.61 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit), no arrows anywhere from 50% all the way up to 300%. I'm also not seeing them in neither Firefox 76.0.1 or Chrome on my Ubuntu 18.04.

@jeepurs Could you try to update your Chromium to the latest version?

![chromium-zoom](https://user-images.githubusercontent.com/1457929/83697708-060dcd00-a600-11ea-840e-86e3b106c519.gif)

**Comment by jeepurs** [comment]
Thanks @radinamatic !  I just upgraded to Chromium Version 83.0.4103.61 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit) and I still can see the same issue.

**Comment by indirectlylit** [comment]
@jeepurs would you mind testing on the LE demo server? It should use the same code for this page

**Comment by jeepurs** [comment]
@indirectlylit @radinamatic Of course. I just logged in as super admin and admin on the Kolibri Demo server and could not reproduce the same issues I saw on the ProFuturo site

**Comment by Tlazypanda** [comment]
@indirectlylit @radinamatic Yeah I checked too not reproducible locally :sweat_smile:

**Comment by jeepurs** [comment]
A somewhat related view on a different online server - Akello Digital Classroom:

![Screenshot from 2020-06-05 23-39-18](https://user-images.githubusercontent.com/5150483/84167863-bf2b3780-aa44-11ea-9ef1-7c5aeea086ce.png)


When I zoom, the horizontal arrows disappear, but the vertical ones remain:

![Screenshot from 2020-06-05 23-38-58](https://user-images.githubusercontent.com/5150483/84167992-e5e96e00-aa44-11ea-91bd-24259e525e9f.png)

**Comment by rtibbles** [comment]
We have not seen these recently - although that may just be a consequence of @jeepurs no longer testing on her extreme browser zoom/resolution combo. Going to close for now.
