### ISSUE TITLE
Unable to scroll down and select in the 'language drop down box' 

### ISSUE THREAD

**Issue by riddhiavlani** [learningequality/kolibri#6989]
### Observed behavior

Unable to scroll languages in the language drop down box while importing resources. The scroll bar jumps back to the top if i try to scroll down

### Expected behavior

…

### User-facing consequences

Unable to select languages at the bottom of the list

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri version 0.13.3
OS Windows 10
Browser Chrome
![bug](https://user-images.githubusercontent.com/44633158/83755215-d3f57d00-a68a-11ea-82c2-7f7058773a97.gif)

**Comment by radinamatic** [comment]
I'm able to replicate this on Firefox 76 on Ubuntu 18.04, so it seems rather universal!

![channel-language-selector](https://user-images.githubusercontent.com/1457929/83785569-c98ab180-a691-11ea-95df-72b854a835c6.gif)

Even when using keyboard, there's no way to navigate further down than 4th language :confused:

**Comment by jonboiser** [comment]
Also reproduced it on the `kolibri-beta` site, but I am not seeing this behavior using the development server.

**Comment by radinamatic** [comment]
My recording above is made while running the server from the current `develop` branch.

**Comment by jonboiser** [comment]
@radinamatic Could you check your network tab and see if there are any tasks in the `/api/tasks` request? On kolibri-beta there was one of those "empty" Completed tasks that don't appear on the Task Manager.

On a hunch, I tried clearing out the task queue on `kolibri-beta` and it seems to have fixed it for me on the website.

**Comment by jonboiser** [comment]
on this component `AvailableChannelsPage.vue`, there is a reactive dependency to the tasks via the `channelIsBeingDeleted` getter, which might be the reason the dropdown is getting reset on every task poll.

**Comment by jonboiser** [comment]
And just replicated this on the devserver by letting a import task complete. This bug  doesn't happen when the task is in-progress, only after it is completed.

**Comment by jonboiser** [comment]
I narrowed this down to the `computed.allChannels` property

https://github.com/learningequality/kolibri/blob/92242246c9545cb59f555d5a4b61ff8c7ed4c2b0/kolibri/plugins/device/assets/src/views/AvailableChannelsPage/index.vue#L174-L179

It has a linkage to the `tasks` state in Vuex via this `installedChannelsWithResources` getter. It must be causing a full-re render which ends up moving focus back up to the first option in the dropdown.
