### ISSUE TITLE
Unexisting role is being used and created in create_dummy_facility_data test helper

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#6993]
### Observed behavior
There is an useful helper called `create_dummy_facility_data`, https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/test/helpers.py#L32 that can be used in tests that need a facility with classes and users created. The test creates users with all the roles Kolibri has and classes with them enrolled or assigned.

However, this function is using a non-existing role: `classadmin` in several parts of the code, creating users and assigning them to the classes:
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/test/helpers.py#L75-L80
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/test/helpers.py#L123

### Expected behavior
To avoid confussion the code using or creating this kind of users should be removed

### Context
all versions of kolibri
It only affects to developers, not end users.

**Comment by indirectlylit** [comment]
@cpauya would you mind taking a look at this in the context of your current work?

**Comment by cpauya** [comment]
This is very similar to https://github.com/learningequality/kolibri/blob/develop/kolibri/core/logger/management/commands/generateuserdata.py management command I've been modifying in the PR: https://github.com/learningequality/kolibri/pull/7013 but I think this was used primarily for unit tests before - whereas the `generateuserdata` is used for integration testing.

I agree this needs to be updated to be useful or just removed if not used in any unit tests.
