### ISSUE TITLE
Kolibri is unable to start using python 3.8

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7004]
### Observed behavior

I upgraded the python to version 3.8.3 and installed it. When I run there's an dialog message "Kolibri is unable to start: You can find additional information in your Kolibri home folder:" and the logs was empty.

I tried to run it using command prompt and it can't run because of an attribute error ` 'time' has no attribute 'clock' `

![python38-error](https://user-images.githubusercontent.com/38421180/84003447-a1a29300-a99c-11ea-8e09-572f3c61270a.png)

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version 0.13.3
 * Operating system Windows 10
 * Browser n/a

**Comment by indirectlylit** [comment]
looks to be related to this: https://github.com/sqlalchemy/sqlalchemy/issues/4731

possibly time to [upgrade](https://github.com/sqlalchemy/sqlalchemy/releases) - we're currently at `1.2.10`

**Comment by rtibbles** [comment]
I have an open draft PR that does this upgrade: https://github.com/learningequality/kolibri/pull/6994

Noting that we could potentially do a patch upgrade without this PR, but not the full minor version upgrade.

**Comment by rtibbles** [comment]
OK - looks like we would need to merge #6994 in order to address this, as a patch version of SQL Alchemy would not support Python 3.8.

**Comment by indirectlylit** [comment]
@mrpau-julius  should be addressed - would you mind testing and re-opening if there are still issues?
