### ISSUE TITLE
default 'network access' setting value

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7012]
### Observed behavior

After upgrading, all access is blocked:

![image](https://user-images.githubusercontent.com/2367265/84105159-586a3780-a9cc-11ea-8338-b85dda18249a.png)

### Expected behavior

The value should:

* default not to restrict for upgrades from 0.13.x
* default not to restrict for non-app context
* default to restrict for app-contexts

### User-facing consequences

users are locked out of Kolibri after upgrading

### Steps to reproduce

run 0.13, then switch to `app-support` branch on the same DB

### Context

0.14

**Comment by jredrejo** [comment]
Kind of fixed (was it actually an issue?)  in #7015
