### ISSUE TITLE
📖 Documentation for expected behavior of options (env vars, options.ini)

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7014]
### Observed behavior

Expected behavior of options is not documented.

related:

* https://github.com/learningequality/kolibri/issues/7009

### Expected behavior

Options and their behaviors are thoroughly documented - both those which can be set by env var and in options.ini.

At the very least this can be done as comments in options.py, but preferably it's pulled into the developer documentation to make it easier to link to and reference.

### User-facing consequences

confusion over how to use options and what to expect from them

### Context

0.13

**Comment by radinamatic** [comment]
:100: x :100:

**Comment by rtibbles** [comment]
All options and env vars are now documented.
