### ISSUE TITLE
Sync All and Import Facility buttons spaced too close on Facilities tab 

### ISSUE THREAD

**Issue by Tlazypanda** [learningequality/kolibri#7016]
### Observed behavior
The sync all and import facility buttons on the facilities page are spaced a little too close together.  
  
![image](https://user-images.githubusercontent.com/33183263/84188257-f3d4d880-aab0-11ea-840b-5188bcc4073b.png)

### Expected behavior
There should be enough spacing between the buttons.

### User-facing consequences
User experience might be hampered since it doesn't look good.

### Steps to reproduce

- Navigate to Facilities tab in the device section .

### Context
 * Kolibri Latest develop
 * Ubuntu 16.04
 * Chrome

**Comment by indirectlylit** [comment]
likely needs to use the `KButtonGroup` component

**Comment by indirectlylit** [comment]
the spacing is addressed, but the shadow clipping is still an issue.

ref: https://github.com/learningequality/kolibri-design-system/issues/32
