### ISSUE TITLE
non-provisioned devices are not redirected to Setup Wizard when going to `/user/` routes

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7020]
```
DeviceNotProvisioned at /en/user/
No exception message supplied
```

After starting the server with a new `KOLIBRI_HOME` I refreshed at `/en/user` and it did not redirect me to Setup Wizard as expected.

_Originally posted by @nucleogenesis in https://github.com/learningequality/kolibri/pull/7010#issuecomment-641496655_

**Comment by jonboiser** [comment]
@rtibbles My hunch is that this might be because of some changes to the redirect hooks in `core/views.py`?

**Comment by rtibbles** [comment]
My guess would be that parallel changes in develop are causing errors in the middleware - will debug.

**Comment by rtibbles** [comment]
Oh... we deleted the middleware a while ago, and I think we were relying on root redirects to handle this, so I don't think this is new behaviour. It's just more egregious now, because the user page accesses device settings info in its plugin data, and gives this exception.

**Comment by rtibbles** [comment]
OK, so the issue here is that we were previously doing the redirect in the frontend, but because the user page now tries to access a device setting during its data bootstrapping, it blocks the page from loading and so the redirect doesn't happen.
