### ISSUE TITLE
Logged-in users are not authorized for `/app/api/initialize` 

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7021]
Not sure if it is intentional but `/app/api/initialize` no longer works even when logged in I get a 403.

_Originally posted by @nucleogenesis in https://github.com/learningequality/kolibri/pull/7010#issuecomment-641501563_

**Comment by jredrejo** [comment]
` /app/api/initialize` has never worked, the right url is `  /app/api/initialize/<token>` 
Example:
http://localhost:8000/app/api/initialize/01f5bcbe590b45e987ae0471c002ec47

To get the token, from a kolibri shell:
```
from kolibri.core.device.models import DeviceAppKey
DeviceAppKey.get_app_key()
```

**Comment by indirectlylit** [comment]
cc @nucleogenesis is this closable then?
