### ISSUE TITLE
linting between pre-commit and package.json is inconsistent

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7032]
### Observed behavior

mentioned by @rtibbles:

> our frontend linting commands in our package.json don't match the way we do linting in our pre-commit hooks/travis linting. Would be good to update those if possible.
> 
> There was an update you had made to the build tools Javascript which was getting linted by travis, but doesn't get linted by default by our package.json commands.

### Expected behavior

linting when running devserver should be consistent with  `pre-commit`, which is used by travis

### User-facing consequences

devs think PRs are good but they turn out not to be

### Steps to reproduce

make a change to build tools. This will be linted by `pre-commit` but not the devserver

### Context

0.14

**Comment by DXCanas** [comment]
Can someone shed light on why we're using both Black and flake8 to begin with? Black is supposed to be pep8 compliant, and it just feels like there might be too many cooks in the kitchen in regards to linting.

**Comment by indirectlylit** [comment]
`black` is a formatter and `flake8` is a linter - they do different things

**Comment by indirectlylit** [comment]
for example, flake will warn about undefined variables and fix up import ordering for you

**Comment by rtibbles** [comment]
Except that flake8 is also auto-formatting files, so it does have some overlap with black's role.

> fix up import ordering for you

Fairly sure that flake8 doesn't modify import ordering, that's this hook: https://github.com/learningequality/kolibri/blob/develop/.pre-commit-config.yaml#L16

I think the issue that @DXCanas is raising is if flake8 is also modifying files, then we should stop it doing that and let black handle that.

**Comment by rtibbles** [comment]
I think I slightly misled @DXCanas here by failing to mention the linting role of flake8 during our conversation, so that's my fault!
