### ISSUE TITLE
Improve swagger documentation for method-based DRF endpoints

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7036]
The ask: more detailed documentation on swagger, like what is done for the more full-featured `ModelViewSets`

For example, this `cleartasks` endpoint is implemented as a method on the main viewset....

https://github.com/learningequality/kolibri/blob/9b29c129ebf93eaf6263a297461bf4e1bb70f986/kolibri/core/tasks/api.py#L248-L259

...The swagger docs will show a comment, but no extra documentation about the parameters

![image](https://user-images.githubusercontent.com/10248067/84429144-8b831580-abdc-11ea-92fd-3ce9342d9037.png)

Compare to this endpoint, which seems to automatically create documentation on the payload shape

![image](https://user-images.githubusercontent.com/10248067/84429287-ba00f080-abdc-11ea-85c7-78717cfad5bb.png)

**Comment by rtibbles** [comment]
Guessing the information is introspected from the serializer - so this will be the case for any endpoint we setup that does not have an explicit serializer associated with it. Will look into alternatives here.

**Comment by jonboiser** [comment]
I'm having a hard time finding a newbie-level tutorial on this, but I think if you can somehow provide an OpenAPI schema for these endpoints (maybe in some external YML file?), Swagger will be able to show it on its API explorer.

It might also be beneficial just do the work and making really basic Serializer classes for these endpoints, instead of sending these `Response(dictionaryLiteral)` type responses.

**Comment by rtibbles** [comment]
This was addressed by automatic serializer generation here: #8138 to help with this.
