### ISSUE TITLE
BackLink 'to' prop does not look like it's passed to RouterLink correctly

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7038]
Example from `Device/ManageTasksPage.vue`

BackLink to prop looks right (an object like `{ name: ... }`

<img width="829" alt="CleanShot 2020-06-10 at 14 26 55@2x" src="https://user-images.githubusercontent.com/10248067/84320460-8d8a9d00-ab26-11ea-987e-71a688eedbc1.png">

But the child `RouterLink`'s to prop is a function which seems different. And also the link does not have the correct URL and just displays the current location.

<img width="1497" alt="CleanShot 2020-06-10 at 14 26 47@2x" src="https://user-images.githubusercontent.com/10248067/84320463-8ebbca00-ab26-11ea-8de1-af251c875bbe.png">

**Comment by nucleogenesis** [comment]
@jonboiser `BackLink.vue` lives here `kolibri/plugins/device/assets/src/views/ManageTasksPage/BackLink.vue` in Kolibri right now. We have a general plan to move that into KDS but haven't yet.

**Comment by nucleogenesis** [comment]
Fixed #7041
