### ISSUE TITLE
Question: are .deb installers available for Kolibri Betas & Release Candidates?

### ISSUE THREAD

**Issue by holta** [learningequality/kolibri#7043]
I'm not seeing a .deb installer within the "Assets" section of https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta2

Is there another way to install/test Kolibri pre-releases as part of Internet-in-a-Box (IIAB) ?

(IIAB currently requires a .deb file and uses https://learningequality.org/r/kolibri-deb-latest as seen within https://github.com/iiab/iiab/blob/master/roles/kolibri/defaults/main.yml &mdash; is another URL available providing .deb file(s) for Kolibri pre-releases?)

**Comment by DXCanas** [comment]
Yes, sorry - the build pipeline is under active development, so the "Assets" section of that page isn't being updated the way it used to be. This will be resolved soon!

For now, you should be able to click on the commit hash associated with that release tag to take you to that commit's page. From there, you should be able to see the checks that apply to that commit - right now it's a red X. It's usually a green check (some dependency issues):
![Commit Checks](https://user-images.githubusercontent.com/9877852/84552383-5c949e80-acc5-11ea-8218-945b34de96ec.png)

Clicking on "Details", as highlighted, will take you to our the buildkite page. From there you should be able to see the Debian pipeline - clicking on the step itself will take you to the associated build, where you should be able to navigate to the step labeled with the Debain logo, then to Assets, where you can download the debian installer.

If you don't want to click through all that, [this is a direct link to the download!](https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/132/jobs/07dbede2-3ec8-4e32-935e-d22f703a25d7/artifacts/eafcd699-78b7-413c-a72b-42444d39975c)

I'm working on getting the Assets section back up to automatic updating- this is just an awkward development stage.

**Comment by indirectlylit** [comment]
@holta we'll also be doing our best to keep this page up-to-date during the beta-testing process:

https://github.com/learningequality/kolibri/wiki/0.14.0-beta-testing

Your testing is very much appreciated!

**Comment by holta** [comment]
Question:

Can Kolibri .deb installers like the current one ([v0.14.0-beta3](https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed/+files/kolibri_0.14.0~beta3-0ubuntu2_all.deb)) be made available directly within the assets section of GitHub releases like https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta3 so they're discoverable and findable ?

**Comment by indirectlylit** [comment]
I believe @DXCanas is working on that, but it's taking some time to get our various buildkite pipelines to play nicely with github releases

in the meantime, we're trying to keep the wiki page linked above as up-to-date as we can
