### ISSUE TITLE
follow-up from app-support merge

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7048]
### Observed behavior

> Everything seemed straight forward, except for the PdfRendererIndex.vue. @nucleogenesis advised that I resolve in favour of app-support and that he can do further cleanup from there.

### Expected behavior

finish integrating PDF renderer changes in both branches for 0.14

### User-facing consequences

missing functionality

### Context

0.14

**Comment by rtibbles** [comment]
Note - to clarify, I think the functionality is all there, but more that the styling that is not aligned with changes made after the Kolibri design system refactor.
