### ISSUE TITLE
Failed to build Integration testing spreadsheet on BuildKite

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7063]
### Observed behavior
When I unblock the `Create integration testing worksheet?` steps at the [Kolibri Python Package](https://buildkite.com/learningequality/kolibri-python-package) pipeline the build always failed.

### Expected behavior
It should build the integration testing spreadsheet

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

Tell us about your environment, including:
 * Kolibri version: release-v0.14.x
 * Operating system
 * Browser

**Comment by radinamatic** [comment]
Maybe @DXCanas can support?

**Comment by DXCanas** [comment]
I'm on it with a few other preventative measures.

**Comment by DXCanas** [comment]
@indirectlylit Do you have any idea of this needs to be in the release?

**Comment by indirectlylit** [comment]
@DXCanas this is critical to begin integration testing

**Comment by radinamatic** [comment]
Thank you @DXCanas! @mrpau-richard merged some changes in the script to generate the spreadsheet this morning, and even I was able to trigger one successful build just now! :tada: 
Closing!
