### ISSUE TITLE
'confirm' doesn't work when leaving the language the same

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7067]
### Observed behavior

'confirm' does nothing:

### Expected behavior

confirm should close the modal

### User-facing consequences

annoyance

### Errors and logs

```
[WARN: kolibri/core/assets/src/core-app/client.js] entity is deprecated for accessing response data, please use the data key instead
```

### Context

0.14

**Comment by MisRob** [comment]
Fixed in #7231
