### ISSUE TITLE
Errors when generateuserdata is used in Command Prompt under Windows 7 or 10.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7077]
### Observed behavior

Errors when the `generateuserdata` management command is used in the Command Prompt under Windows 7 or 10.
<img width="739" alt="Screen Shot 2020-06-18 at 3 40 25 PM" src="https://user-images.githubusercontent.com/175580/84998496-7d0b9f80-b182-11ea-83fd-f7d49ba7722f.png">

There are sample data generated BUT the errors are very misleading for the user.
<img width="739" alt="Screen Shot 2020-06-18 at 4 41 15 PM" src="https://user-images.githubusercontent.com/175580/84998564-944a8d00-b182-11ea-9313-db435f159f0e.png">

### Expected behavior
No errors must show when running the command.

### User-facing consequences
Works as intended but the error messages shown confuses the user.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4797367/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4797369/kolibri.txt)
[2020-06-18-thu--command prompt errors 1.txt](https://github.com/learningequality/kolibri/files/4797370/2020-06-18-thu--command.prompt.errors.1.txt)

Relevant lines in the Command Prompt:
```
...
--- Logging error ---
Traceback (most recent call last):
  File "c:\python36\lib\logging\__init__.py", line 996, in emit
    stream.write(msg)
  File "c:\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 78-81: c
haracter maps to <undefined>
...
...
  File "c:\python36\lib\site-packages\kolibri\core\logger\management\commands\ge
nerateuserdata.py", line 212, in handle
    utils.logger_info("    Learner {learner}...".format(learner=user))
  File "c:\python36\lib\site-packages\kolibri\core\logger\utils\user_data.py", l
ine 49, in logger_info
    logger.info(message)
Message: '    Learner "????"@"Home Facility Admin"...'
Arguments: ()
←[37mINFO         Learner "????"@"Home Facility Admin"...←[0m
←[37mINFO         Learner "Natasja Bach"@"Home Facility Admin"...←[0m
←[37mINFO         Learner "Hansen M"@"Home Facility Admin"...←[0m
←[37mINFO         Learner "Leach J Martha"@"Home Facility Admin"...←[0m

C:\Users\IEUser>
```

### Steps to reproduce

1. Use the artifact at [release-v0.14.x-beta2](https://buildkite.com/learningequality/kolibri-python-package/builds/1137) to test in a Windows 7 or 10 VM.
1. Install Kolibri
1. Launch Command Prompt then run `kolibri manage generateuserdata`
1. Notice the errors shown.

### Note when Debugging
The logging function is already [wrapped in a catch-all exception handling function](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/logger/utils/user_data.py#L44).  However, based on readings, this is NOT a Python issue but with the Command Prompt handling of Unicode character encoding under Windows 7 or 10.  

There are various work-arounds without the need to modify the source like: [Using UTF-8 Encoding (CHCP 65001) in Command Prompt / Windows Powershell (Windows 10)](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window) - but haven't tried those.

So far the most reliable/technical explanation is provided here: https://wiki.python.org/moin/PrintFails - which states:

> Setting to "utf-8" is not recommended as this produces an inaccurate, garbled representation of the output to the console.  For best results, use your console's correct default codepage and a suitable error handler other than "strict".

### Possible Solutions

1. [Python, Unicode, and the Windows console](https://stackoverflow.com/a/32176732/845481) - references the [PrintFails](https://wiki.python.org/moin/PrintFails) topic above and provides the most simple solution as of Python v3.6:

    > `print(unicode_string)`

### Context
* Kolibri version: [release-v0.14.x-beta2](https://buildkite.com/learningequality/kolibri-python-package/builds/1137)
* Operating system: Windows 7 or 10 in a VM
* Browser: n/a
* Python: v3.6.8

**Comment by radinamatic** [comment]
Should be fixed by  #7078.
