### ISSUE TITLE
Learner recommended page server error 500

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7080]
### Observed behavior
Learner recommended page server error 500.

This learner account was generated by `generateuserdata` command. I tried it with the learner account I manually created and I can't reproduce the error. 

### Expected behavior

user can access recommended page

### Errors and logs
![c2](https://user-images.githubusercontent.com/8663934/85029259-af32f680-b1ae-11ea-981b-e8de7dde63ac.PNG)

```
{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "content-length": "27",
    "content-type": "text/html",
    "date": "Thu, 18 Jun 2020 13:23:55 GMT",
    "server": "0.0.0.0",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/content/contentnode/f87695112a8685760a9193acab2ddf08/next_steps/",
    "params": {
      "user_kind": "learner",
      "contentCacheKey": 1592485524
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "X-CSRFToken": "1pKgTiB8pRODMZqI9YsqslfiDRtTNi4ZLfqPD41Sxzt1TFNUeHrP1v0mzGDZJJPC"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1,
    "cacheBust": false,
    "method": "get"
  },
  "request": {}
}
```

### Steps to reproduce

1. Assuming that  0.14.0b2 is already installed and channel token `nakav-mafak` contents are imported
2. Stop the kolibri server
3. Run `kolibri manage generateuserdata --no-onboarding --facilities 2` at the command prompt
4. Start the Kolibri server
5. Log in a learner user generated in `generateuserdata` and access recommended page

### Context

 * Kolibri version:  0.14.0b2
 * Operating system: Windows 10
 * Browser: Chrome 83 & IE11

**Comment by cpauya** [comment]
@mrpau-richard What channel did you use for this test?

**Comment by cpauya** [comment]
Tried this on my local Windows 10 VM using Chrome v83.  Users were created from `kolibri manage generateuserdata --facilities 2 --no-onboarding`, username: `Wingthe` password: `password`.  

No error/s at the recommended page but I haven't imported any content yet.
<img width="1016" alt="Screen Shot 2020-06-19 at 5 19 05 PM" src="https://user-images.githubusercontent.com/175580/85117450-71d37500-b251-11ea-82fb-aee10d10bc4a.png">

**Comment by cpauya** [comment]
I imported the `nakav-mafak` channel and tried again but there's no error so far.  The `Wingthe` and the `superuser` users are both from the `generateuserdata` command.

<img width="1016" alt="Screen Shot 2020-06-19 at 6 19 18 PM" src="https://user-images.githubusercontent.com/175580/85122839-cbd83880-b259-11ea-8857-298a6b645cef.png">

Relevant log files for reference:
[console-export-2020-6-19_18-18-43.txt](https://github.com/learningequality/kolibri/files/4803976/console-export-2020-6-19_18-18-43.txt)
[daemon.txt](https://github.com/learningequality/kolibri/files/4803979/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4803984/kolibri.txt)

I used this [kolibri v0.14.x-beta2 installer - for integration testing](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1137/jobs/495a1f23-0cbd-47cb-b134-129fc51b740d/artifacts/0833a0dd-4263-4d48-ae5e-226afb249aa8)

**Comment by mrpau-richard** [comment]
@cpauya I use the `nakav-mafak` channel token, I forgot to  add that to the steps to reproduce.

**Comment by rtibbles** [comment]
@mrpau-richard do you still have the log file for this? Would be useful to look at it to see the full traceback of the 500 error.

**Comment by rtibbles** [comment]
Not able to replicate, closing.
