### ISSUE TITLE
Filter controls are hidden when there are no results.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7081]
### Observed behavior
While testing [learner-find-content-item.feature](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/learner/learner-find-content-item.feature) - the filter controls are hidden when there are no results.

![2020-06-18-thu--v0 14 x-b2--search filter bug](https://user-images.githubusercontent.com/175580/85030435-0a191d80-b1b0-11ea-82d7-799c85cadd70.gif)

### Expected behavior
The filter controls must still show even when there are no results to let the user reset their filters.

### User-facing consequences
No way for user to reset the filter but to close the dialog.

### Errors and logs
[2020-06-18-thu--filter bug--127.0.0.1-1592533149325.log](https://github.com/learningequality/kolibri/files/4799157/2020-06-18-thu--filter.bug--127.0.0.1-1592533149325.log)
[daemon.txt](https://github.com/learningequality/kolibri/files/4799160/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4799162/kolibri.txt)

### Steps to reproduce

1. Install Kolibri v0.14.x-b2 using the [build artifact](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1137/jobs/495a1f23-0cbd-47cb-b134-129fc51b740d/artifacts/0833a0dd-4263-4d48-ae5e-226afb249aa8) at BuildKite
1. Import 2 channels:
    1. import using the `nakav-mafak` token for first channel
    1. use "Touchable Earth (en)" for second channel
1. After import is done, go to the Learn > Channels page and do a search: use `te`
1. In the search dialog, select the filter dropdowns for `Type` and `Channels`:
    1. Type == "Apps"
    1. Channels == "Touchable Earth (en)"
1. Notice the "No results for 'te'" text and that the filter controls are now gone.

### Context
* Kolibri version: [release-0.14.x-beta2](https://buildkite.com/learningequality/kolibri-python-package/builds/1137)
* Operating system: Windows 7 VM
* Browser: Firefox v75 and Chrome v81

**Comment by cpauya** [comment]
This is fixed as of [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d) - the filter controls are still there (even when there are no results with further filters). Yey! 😺 
<img width="1016" alt="Screen Shot 2020-06-24 at 6 57 43 PM" src="https://user-images.githubusercontent.com/175580/85543625-d07f6100-b64c-11ea-9aa1-124446424eec.png">

**Comment by indirectlylit** [comment]
thanks for confirming @cpauya !
