### ISSUE TITLE
crossComponentTranslator breaks across components

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7088]
### Observed behavior

Despite `crossComponentTranslator` being forbidden in our code except in the most extreme circumstances, we, it seems that it needs some TLC.

It does not allow for us to import translations from across plugins according to @rtibbles who said:

> I think making sure that we can leverage the translation memory for it is probably safest?

Considering that `crossComponentTranslator` is something that we would only ever permit in our code at a time where we have a deadline - that is - in the few weeks just before a release - this seems like something we should fix before the next release so that we don't have to do it under pressure a week into string freeze.

### Expected behavior

`crossComponentTranslator` should work across the whole app when we end up needing to use it again

### User-facing consequences

None - but we can save ourselves some potential stress if we fix this before our next release's string freeze.

**Comment by rtibbles** [comment]
This was fixed by #8224
