### ISSUE TITLE
Question number has a zero value

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7097]
### Observed behavior

There's an error occurs when the learner takes a quiz. 
![q1-zero-number](https://user-images.githubusercontent.com/38421180/85150233-da881500-b284-11ea-851a-ccd699abec52.png)

### Expected behavior

Learners can take a quiz.
### User-facing consequences

…

### Errors and logs

```
Question number 0 is not valid for this quiz
```

### Steps to reproduce

1. Create a quiz
2. Log in as a learner
3. take a quiz

### Context

* Kolibri version : 0.14.0b2
 * Operating system : Windows 7
 * Browser : IE11 and Chrome

**Comment by jredrejo** [comment]
The problem is in the quiz creation, as it's created with 0 questions:
![image](https://user-images.githubusercontent.com/1008178/85312514-389c3e80-b4b7-11ea-9561-674bc6a546df.png)
