### ISSUE TITLE
No display of exercises

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7101]
### Observed behavior

Learners can't view the exercises that they choose.
![Cant-displlay-exercises](https://user-images.githubusercontent.com/38421180/85157494-24c1c400-b28e-11ea-8225-f9747459bb3d.png)

### Expected behavior

Learners can take exercises.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Log in as a learner
2. Go to learn page recommended tab
3. Select an exercise

### Context

* Kolibri version: 0.14.0 beta 2
 * Operating system: Windows 7
 * Browser: chrome and IE11

**Comment by jredrejo** [comment]
I think this is probably fixed with #7118
