### ISSUE TITLE
Setup file corrupt for 0.14.0-beta3 on Windows

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7108]
### Observed behavior

Downloaded 0.14.0-beta3 installer for Windows twice. Each time is gives this message upon installation attempt on Windows 10.

![image](https://user-images.githubusercontent.com/2577060/85231800-d04a5000-b417-11ea-9622-d42486943fc0.png)

### Expected behavior

Should have installed correctly.

### User-facing consequences

Unable to install latest Kolibri release.

### Errors and logs

…

### Steps to reproduce

…

### Context

OS: Windows 10 Pro 1909

**Comment by indirectlylit** [comment]
@mrpau-dev mind investigating?

**Comment by radinamatic** [comment]
Yes, please @mrpau-dev, error replicated on both Windows 7 & 10.

Windows 7 | Windows 10
------------ | -------------
![Selection_631](https://user-images.githubusercontent.com/1457929/85241325-b6baff80-b43b-11ea-919e-1a609f7a3a0e.png) | ![Selection_632](https://user-images.githubusercontent.com/1457929/85241359-d81beb80-b43b-11ea-9997-a50c92b96b5f.png)




Was there something missing from the latest PR that was merged on windows-dev repo that we tested?

**Comment by mrpau-richard** [comment]
I think this is one of the reasons why it's corrupted https://jrsoftware.org/isfaq.php#corrupt

@indirectlylit any idea where I can find the specific build on the BuildKite that produce this corrupted beta3 installer?

**Comment by cpauya** [comment]
I think it was downloaded from the [Kolibri Github releases](https://github.com/learningequality/kolibri/releases/) page @mrpau-richard - that's the corrupted one.  Built: Fri, 19 Jun 2020.
<img width="739" alt="Screen Shot 2020-06-22 at 3 18 34 PM" src="https://user-images.githubusercontent.com/175580/85259479-ba7e6e80-b49b-11ea-885a-c088db650bdd.png">


I just tested the [latest build on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1188) and it worked so far. Built: Sat, 20 Jun 2020.
<img width="739" alt="Screen Shot 2020-06-22 at 3 15 28 PM" src="https://user-images.githubusercontent.com/175580/85259503-c407d680-b49b-11ea-9c57-659de7163ea4.png">

Which build did we get the beta3 (on the Github releases) from @indirectlylit?

**Comment by radinamatic** [comment]
I think it was this one:
https://buildkite.com/learningequality/kolibri-python-package/builds/1170

**Comment by cpauya** [comment]
I downloaded the Windows artifact from that build (built: Fri, 19 Jun 2020) and it worked - maybe the one on Github is not completely copied (thus the corruption) as explained in the above link from @mrpau-richard?
<img width="739" alt="Screen Shot 2020-06-22 at 3 40 18 PM" src="https://user-images.githubusercontent.com/175580/85263702-249a1200-b4a2-11ea-9f04-6da646143de7.png">

**Comment by cpauya** [comment]
On a side note, was wondering why the build info is missing in the Kolibri version @indirectlylit - is this intentional?  I think it's useful to pinpoint the build used for the installer/package.

**Comment by indirectlylit** [comment]
When a build is created from a tagged release, it should be the same one available from the releases page:

https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta3

**Comment by cpauya** [comment]
> When a build is created from a tagged release, it should be the same one available from the releases page:
> 
> https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta3

Ah, then I think we just need to replace the one on Github (re copy It from Buildkite).

**Comment by cpauya** [comment]
> On a side note, was wondering why the build info is missing in the Kolibri version @indirectlylit - is this intentional? I think it's useful to pinpoint the build used for the installer/package.

As per @indirectlylit on Slack:
> builds from releases that have a git tag and github release just show the version number

**Comment by indirectlylit** [comment]
@mrpau-richard @radinamatic is this still an issue?

**Comment by radinamatic** [comment]
I think this was an one-time issue with corrupted upload to the release page, and hasn't been seen since!
At lease the past 3-4 betas were OK, closing this!
