### ISSUE TITLE
Login screen is appearing with app-mode enabled and allow other browsers to connect disabled

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7115]
### Observed behavior
This is a regression in 0.14 beta.
After enabling app-mode, if the settings that allow other browsers to connect is disabled, accessing from a non-authorized browser should provide a non-authorized error, however it shows the login screen and the list of users.

Depending on the settings combination, login becomes impossible too:

![password_error](https://user-images.githubusercontent.com/1008178/85324109-87eb6a80-b4c9-11ea-863f-ea91c78d1274.gif)

### Expected behavior
In app-mode if allow other browsers to connect is disabled, the login screen should not visible from other browsers

### User-facing consequences
This is an app vulnerability

### Steps to reproduce
Enable app-mode
Disable access from other browsers in the device settings
Try to access to kolibri from a different browser (or an incognito window)

### Context
In branch develop there's no issue, in branch release-v0.14.x the error happens

**Comment by rtibbles** [comment]
Note that this is only an issue if you have previously not been in app mode when provisioning the device, and then switch to app mode. For devices provisioned in app mode, this would not occur.

**Comment by jredrejo** [comment]
@micahscopes  sorry, I forgot to manually close this issue. It was solved with  #7223
