### ISSUE TITLE
exact word matches should display first in user search

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7131]
### Observed behavior

My username is 'd' and my full name is 'd'. In order to find the user I need to page through multiple pages

![2020-06-22 16 47 34](https://user-images.githubusercontent.com/2367265/85347238-e3f3c600-b4ac-11ea-99d8-1f602bd600e0.gif)

### Expected behavior

exact word matches should display first in all user searches (e.g. class assignment, device permission, facility user list, etc)

### User-facing consequences

harder to find users in a large facility

### Steps to reproduce

search for users in a large facility

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
There are libraries we can use to return some sort of relevance-sorted filtering of the names. But I don't believe this will work if/when we return paginated lists of Facility users (since not all the users will be in-memory).

**Comment by kollivier** [comment]
Are we doing a `contains` search? I think doing a `startswith` query instead of `contains` would work for usernames and first / last name, and then the exact match should be the first result so long as it's sorted alphabetically.

**Comment by jonboiser** [comment]
The filtering in the video is done on the front-end, probably doing a simple substring match.

If we do change things to make fetch a paginated list for this page, I think I would implement the search maybe using the technique you described, but where the `startswith` results take precedent over the `contains` result (we still want both).

But maybe in the short term, we could change the front-end filtering to do the same (exact match > starts with match > substring match).

**Comment by indirectlylit** [comment]
nice!

**Comment by metodimilevqa** [comment]
I confirm the fix is successful with #7820. Verified with Kolibri v0.14.7-alpha4, Windows 10, Chrome (latest).
