### ISSUE TITLE
leakage between facilities

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7137]
### Observed behavior

refs:

* https://www.notion.so/learningequality/leakage-between-facilities-5bfe10e8cea24886902337282a38d20a
* https://www.notion.so/learningequality/Wrong-facility-s-classes-list-shows-up-in-All-classes-list-dd3ff1b12fc0426c873bd42de60a3fe7

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
Based on the the descriptions, the root cause of this issue might be the same as in #7138
