### ISSUE TITLE
regression in breadcrumb styling

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7140]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/85357700-c4699700-b4c6-11ea-95c3-54d570927b9a.png)

### Expected behavior

single-line behavior:

![image](https://user-images.githubusercontent.com/2367265/85357718-d3e8e000-b4c6-11ea-83d2-9f78818dd991.png)

### Steps to reproduce

see:

* https://kolibri-beta.learningequality.org/en/learn/#/topics/t/fca3246f932c5a2ca13cec784a573036
* https://kolibri-demo.learningequality.org/en/learn/#/topics/t/fca3246f932c5a2ca13cec784a573036

### Context

0.14.0 beta 3

**Comment by bjester** [comment]
This has been fixed in the above KDS PR.
