### ISSUE TITLE
Funza window overlap

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7143]
### Observed behavior
Funza window overlap at the `download resource` button

### Errors and logs
This is the display on IE11, Chrome, Firefox

![IE](https://user-images.githubusercontent.com/8663934/85374567-91c3ab00-b567-11ea-9cae-207e413511ca.PNG)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0b2
 * Operating system: Windows 10
 * Browser: IE11 Chrome 88 Firefox 77

**Comment by micahscopes** [comment]
Resolved by #7216.
