### ISSUE TITLE
padding needed above 'new version' banner

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7149]
### Observed behavior

insufficient padding

![image](https://user-images.githubusercontent.com/2367265/85484858-829b2800-b57c-11ea-918b-2705754edc24.png)

### Expected behavior

padding consistent with other pages - some multiple of 8px

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
I'm guessing this is because of the un-even padding of KPageContainer that I mentioned here https://github.com/learningequality/kolibri-design-system/issues/39

It's just that this is more visible because the banner's background color is not white.
