### ISSUE TITLE
Shouldn't be able to sync unregistered facility to KDP

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7150]
### Observed behavior

My facility was never registered (is missing the green shield icon indicator). 

Ref: https://www.notion.so/learningequality/Shouldn-t-be-able-to-sync-unregistered-facility-to-KDP-686ed01c7d30421292dac7a9a75dec02

### Expected behavior

Intended behavior if a facility has not yet been registered is that the flow jumps to device selection

### Context
0.14.0 beta 3

**Comment by jonboiser** [comment]
This should be fixed by this change https://github.com/learningequality/kolibri/commit/871c9821308523ffd2e423ab469d1935cb1adaa5#diff-b4c883195f3f0539d566af6da9625eabL48

But I've noticed that sometimes a facility can go from registered to not registered

**Comment by indirectlylit** [comment]
hm okay - mind opening a new issue for that and closing this one?
