### ISSUE TITLE
quiz preview is broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7151]
### Observed behavior

Quiz preview functionality is misbehaving. Reported by @jtamiace -

https://www.notion.so/learningequality/Black-overlay-a-k-a-scrim-while-creating-a-quiz-and-preview-of-questions-not-working-bcb613d0c88543598c2249814e0e7dd4

### Context

0.14

**Comment by micahscopes** [comment]
@jtamiace tried reproducing this and could not.  Still waiting to hear if anyone else can reproduce it or has an idea that it's been fixed.

**Comment by indirectlylit** [comment]
closing - let's re-open if necessary
