### ISSUE TITLE
auto-generated facility names are not well-formatted

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7152]
### Observed behavior

it appears that we concatenate two strings together with a space:

![image](https://user-images.githubusercontent.com/2367265/85485590-e540f380-b57d-11ea-88e6-985829726653.png)

### Expected behavior

strings should be concatenated with a ` - ` or similar

### Steps to reproduce

create a facility using the basic flow

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
This can be fixed by updating the message here

https://github.com/learningequality/kolibri/blob/01d34382971f93aa1971c3987a1e91426ebe221b/kolibri/plugins/setup_wizard/assets/src/modules/pluginModule.js#L8-L14

**Comment by indirectlylit** [comment]
hm okay - need to push it for the next major release then

**Comment by indirectlylit** [comment]
flagging comment:

https://github.com/learningequality/kolibri/pull/7936#pullrequestreview-629562954
