### ISSUE TITLE
Device name was not saved during setup wizard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7158]
### Observed behavior

reported by @jamalex 

> Device name provided was not saved when clicking through the "Import facility" flow in the setup wizard (fell back to default of hostname)

Corroborated by @jonboiser 

> I also noticed that the device name that was saved is not being repopulated in the Device name form when you return to it, even though the name is still being saved in Vuex

### Expected behavior

Saved device name should be filled in properly

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
This should be fixed here 7638180395cbf338a035abd8e1861ce3fd53dfca

**Comment by indirectlylit** [comment]
thank you
