### ISSUE TITLE
cannot elevate user in another facility to super admin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7159]
### Observed behavior

reported by @jonboiser 

> Unable to change the permissions for an admin in a different facility from the one i'm logged in as as superuser
> 
> The super admin checkbox is disabled, and I can't save changes even after checking the "can manage..." box.
> 
> I think the crucial detail is that this "jb" user is an admin for a different facility than the one i'm logged into

![image](https://user-images.githubusercontent.com/2367265/85487942-584c6900-b582-11ea-8ad7-916b173e02a4.png)

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
The root cause actually looks like the same coincidence as #7130 (assuming that we can't have duplicate usernames on a Device) e.g. two "jb" usernames in two facilities
