### ISSUE TITLE
Error shows in the browser console during login.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7162]
### Observed behavior
Error shows in the browser's console during login.  It shows in these browsers: Firefox v76, Chrome v81, and IE11.

This is NOT shown during simplified login.
<img width="1016" alt="Screen Shot 2020-06-24 at 4 18 08 PM" src="https://user-images.githubusercontent.com/175580/85522361-1ed63500-b638-11ea-8122-91a1d29fb33e.png">

1. Here's the `.gif` for the login process in Firefox v76 showing the error.
![2020-06-24-wed--v0 14 0-b4--browser console errors during login 1](https://user-images.githubusercontent.com/175580/85522641-82f8f900-b638-11ea-9f63-61b2eceeeb91.gif)

2. If I intentionally use a wrong password, there's another error message shown 
> [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: "Request failed with status code 401"
<img width="1016" alt="Screen Shot 2020-06-24 at 5 18 25 PM" src="https://user-images.githubusercontent.com/175580/85528771-eede6000-b63e-11ea-9504-375cc2e23f9a.png">

3. In IE11 this shows an error when I press <Enter> in the username textbox, and I cannot proceed unless I click on the `Next` button.
![2020-06-24-wed--v0 14 0-b4--browser console errors during login 2 - ie11](https://user-images.githubusercontent.com/175580/85527085-221fef80-b63d-11ea-9d8b-1c6ce935ad2f.gif)

### Expected behavior
No errors must show in the browser console during login.

### User-facing consequences
The login process proceeds but don't know of other issues it may cause.

### Errors and logs
[127.0.0.1-1593041799974.log](https://github.com/learningequality/kolibri/files/4824121/127.0.0.1-1593041799974.log)
[daemon.txt](https://github.com/learningequality/kolibri/files/4824122/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4824124/kolibri.txt)

Browser console error
```
TypeError: "this.$refs.password is undefined"
    focusOnInvalidField SignInPage.vue:522
    signIn SignInPage.vue:517
    submit SignInPage.vue:18
    VueJS 3
        invokeWithErrorHandling
        invoker
        _wrapper
vue.runtime.esm.js:1888:12
```

### Steps to reproduce
1. Get the [Kolibri Windows installer for v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
1. Use a Windows 7 VM and setup 1 learner
1. Make sure to show the browser console to notice errors.
1. Login as that learner user and notice the error shown in the browser console.
1. However, when you input the learner password, the learner user is logged-in.

### Context
* Kolibri version: [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
* Operating system: Windows 7 VM
* Browser: Firefox v76, Chrome v81, and IE11
* Python: v3.6.8

**Comment by nucleogenesis** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/7306
