### ISSUE TITLE
Scrollbars show at the change password dialog in Firefox v76.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7163]
### Observed behavior
When trying to change a learner's password there are vertical and horizontal scrollbars shown in Firefox v76.  This doesn't show in IE11 and Chrome v81.  The user can still change password.

<img width="1016" alt="Screen Shot 2020-06-24 at 4 44 31 PM" src="https://user-images.githubusercontent.com/175580/85524949-3236cf80-b63b-11ea-9e20-c860a202d6f7.png">

### Expected behavior
These scrollbars shouldn't show because the content is not that big.

### User-facing consequences
Doesn't affect the change password functionality but it's an unusual behaviour.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4824223/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4824225/kolibri.txt)

No errors shown in the browser console.

### Steps to reproduce
1. Get the [Kolibri Windows installer for v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
1. Use a Windows 7 VM and setup 1 learner using Firefox (I tested using v76)
1. Login as that learner user and go to the profile page.
1. Click on the `Change password` link and notice the scrollbars shown.

### Context
* Kolibri version: [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
* Operating system: Windows 7 VM
* Browsers: Firefox v76, Chrome v81, and IE11
* Python: v3.6.8

**Comment by radinamatic** [comment]
Can replicate with Beta6 on Ubuntu 16.04, and even Chrome has an unnecessary vertical scrollbar:

![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_681](https://user-images.githubusercontent.com/1457929/86070442-070a1100-ba7d-11ea-9dba-71b2cf7236d0.png)

**Comment by MisRob** [comment]
This PR should fix this issue https://github.com/learningequality/kolibri-design-system/pull/56
