### ISSUE TITLE
Intermittent errors in IE11 console.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7165]
Intermittent errors in IE11 console.

### Observed behavior

This is an intermittent behavior and shows in the following as observed:
1. Errors after user login (at the learn page). 
2. When user visits the `Learn` page.
3. When user visits the `Profile` page.
4. The same errors also show when the `Recommended` tab is clicked twice or more.
5. It affects guest users too.
<img width="1016" alt="Screen Shot 2020-06-24 at 8 02 51 PM" src="https://user-images.githubusercontent.com/175580/85552684-d594de00-b655-11ea-8216-6c6f47c65754.png">
6. It also affects the superadmin user which shows a different page after login (device channels page).
<img width="1016" alt="Screen Shot 2020-06-24 at 7 07 35 PM" src="https://user-images.githubusercontent.com/175580/85545278-62d43480-b64e-11ea-9133-388e7a4291b0.png">

This does not manifest:

1.  in Chrome v81 or Firefox v76.
2. when the user is logged-in and I clicked on the Refresh button of IE11.

Here's the `.gif` of the pages visited by the learner user and the console error/s shown.
![2020-06-24-wed--v0 14 0-b4--4--error in ie11 console after learner login 1](https://user-images.githubusercontent.com/175580/85546611-aa0ef500-b64f-11ea-90e5-57d7967f1dbc.gif)

### Expected behavior
No errors must show in the IE11 console.

### User-facing consequences
Functionality of the page seems unaffected, so I don't know what else is affected by it.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4825036/daemon.txt)
[ie11-console-4.txt](https://github.com/learningequality/kolibri/files/4825038/ie11-console-4.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4825039/kolibri.txt)

IE11 console error/s
```
...
Kolibri Modules: kolibri.plugins.learn.app registered
TypeError: Unable to get property 'split' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'split' of undefined or null reference",
      message: "Unable to get property 'split' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'split' of undefined or null reference
   at createRouterError (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:431538)
   at Anonymous function (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:434747)
   at iterator (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:434716)
   at step (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:429373)
   at step (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:429418)
   at Anonymous function (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:429401)
   at Anonymous function (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b4.js:1:435449)
   at Router.prototype._hook (h"
   }
```

### Steps to reproduce
1. Get the [Kolibri Windows installer for v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
1. Use a Windows 7 VM and setup 1 learner using IE11 and show the console.
1. Import one or more channels. (This may be optional).
1. Login as that learner user and notice the error/s in the console.
1. Visit the `Learn`, `Recommended` pages that also shows the same error.

### Context
* Kolibri version: [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
* Operating system: Windows 7 VM
* Browsers: Firefox v76, Chrome v81, and IE11
* Python: v3.6.8

**Comment by mrpau-richard** [comment]
Maybe this is related to #7189 It has the same error I encountered in the IE11 coach page.

**Comment by radinamatic** [comment]
If there's no observable effect on users, I'll tag it `P2`

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
