### ISSUE TITLE
duplicate 'create account' links

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7174]
### Observed behavior

reported by @radinamatic and @kollivier, corroborated by @nucleogenesis 

![image](https://user-images.githubusercontent.com/2367265/85624801-4ff63b80-b61f-11ea-8096-419993b7f21b.png)

### Expected behavior

@riddhiavlani and @jtamiace can clarify but likely something like this:

![image](https://user-images.githubusercontent.com/2367265/85624955-8f248c80-b61f-11ea-9a37-7eb9a4f62f03.png)

### Steps to reproduce

go to https://kolibri-beta.learningequality.org/ in an incognito window

### Context

0.14.0 beta 3

**Comment by nucleogenesis** [comment]
fixed #7191
