### ISSUE TITLE
HTML5 download resource selection display issue

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7175]
### Observed behavior
HTML5 download resource selection display issue and unexpected `hi` text

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![c2](https://user-images.githubusercontent.com/8663934/85625738-7d35fe80-b69e-11ea-9e92-283e30fe3ee0.PNG)
![c1](https://user-images.githubusercontent.com/8663934/85625774-8626d000-b69e-11ea-98fb-837536640da8.PNG)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: release-v0.14.0b4
 * Operating system:  Windows 7
 * Browser:  Firefox 77

**Comment by kollivier** [comment]
The 'hi' text looks like another occurrence of #6986, but the popup displaying behind the slideshow caption bar seems like a separate issue.

**Comment by micahscopes** [comment]
This should be fixed in the next kolibri-design-system release.

**Comment by micahscopes** [comment]
The new KDS dependency was added in #7190.
