### ISSUE TITLE
Unknown MIME type error in IE11 console when playing a video.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7186]
The `Unknown MIME type.` error shows in IE11 console when playing videos.  This does not manifest in Firefox v76 or Chrome v83 under Windows 7 VM.

The video will eventually play.  But sometimes a browser refresh is needed when it doesn't.

This may be related to (affected by): https://github.com/learningequality/kolibri/issues/7165

### Observed behavior
Here's the error I noticed in IE11 console while testing [kolibri v0.14.0-beta5](https://buildkite.com/learningequality/kolibri-python-package/builds/1254):

> MEDIA12604: Text Track: Unknown MIME type. hr=8007000b.
<img width="1016" alt="Screen Shot 2020-06-25 at 6 42 25 PM" src="https://user-images.githubusercontent.com/175580/85705633-fde31200-b713-11ea-8855-933ff623229b.png">

Sometimes the video doesn't play but I just refresh IE11 and it will play - but the "unknown mime type" error above still shows.  This one I cannot reproduce consistently but it mostly shows when trying to play the **Kolibri QA Channel > Video > Intro to addition** video.
> VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. [object Object]

![2020-06-25-thu--v0 14 0-b5 testing--2--ie11 console error when playing videos - unknown mime type 1](https://user-images.githubusercontent.com/175580/85706501-d9d40080-b714-11ea-8320-886beda8d052.gif)

### Expected behavior
Users should be able to play videos without refreshing/reloading the page.

### User-facing consequences
This error may cause the "corruption" error above or other issues I haven't encountered yet.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4830786/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4830787/kolibri.txt)
[2020-06-25-thu--v0.14.0-b5--2--unknown mime type error - console log.txt](https://github.com/learningequality/kolibri/files/4830785/2020-06-25-thu--v0.14.0-b5--2--unknown.mime.type.error.-.console.log.txt)

Relevant lines of IE11 console log file above with the errors:
```
...
MEDIA12604: Text Track: Unknown MIME type. hr=8007000b.
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. [object Object]
   "VIDEOJS:"
   "ERROR:"
   "(CODE:3 MEDIA_ERR_DECODE)"
   "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
   {
      [functions]: ,
      __proto__: { },
      code: 3,
      MEDIA_ERR_ABORTED: 1,
      MEDIA_ERR_CUSTOM: 0,
      MEDIA_ERR_DECODE: 3,
      MEDIA_ERR_ENCRYPTED: 5,
      MEDIA_ERR_NETWORK: 2,
      MEDIA_ERR_SRC_NOT_SUPPORTED: 4,
      message: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support.",
      status: null
   }
...
```

### Steps to reproduce
1. Get the [Kolibri Windows installer for v0.14.0-beta5 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1254)
1. Use a Windows 7 VM and setup 1 learner using IE11.
1. Import channel using the token `nakav-mafak`.
1. Login as the learner user.
1. Navigate to **Learn > Channels > Kolibri QA Channel > Video > Intro to addition** video and play it.
1. Notice the "Unknown MIME type" error shown in IE11 console.
1. Navigate back to the **Learn > Channels** page then back to the same video to attempt to reproduce the "media playback was aborted due to a corruption problem" error as per above .gif.

### Context
* Kolibri version: [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
* Operating system: Windows 7 VM
* Browser: IE11
* Python: v3.6.8

**Comment by radinamatic** [comment]
@cpauya Can you please try to replicate in the latest beta (7 probably, by the time you start working :slightly_smiling_face:), and see if it happens in other browsers too? Thanks!

PS: I'd say the _expected behavior_ is being able to play videos without reloading, as users don't generally care about the errors in the console :wink:

**Comment by cpauya** [comment]
When I tested this (as of beta4) - this issue doesn't show in the other browsers @radinamatic.

> PS: I'd say the _expected behavior_ is being able to play videos without reloading, as users don't generally care about the errors in the console 😉

I agree, I already edited it. 😸

**Comment by cpauya** [comment]
Sadly, I still saw this issue in IE11 with v0.14.0-beta7.  Also doesn't manifest on other browsers (Firefox v77 and Chrome v83).

<img width="1016" alt="Screen Shot 2020-06-30 at 5 24 17 PM" src="https://user-images.githubusercontent.com/175580/86109337-d9fa4480-baf6-11ea-85aa-94aec71b7238.png">

**Comment by radinamatic** [comment]
> I still saw this issue in IE11 with v0.14.0-beta7

Thanks for confirming it @cpauya!
Would you edit the **Context** of your initial post to state only IE11 then, as that is where my confusion originated?
_Context_ should indicate **only** the browser where you encounter the error, not all that you used/tested :slightly_smiling_face:

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
