### ISSUE TITLE
SignInPage does not implement the "optional learner password" facility setting

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7199]
### Observed behavior

Screenshot 1: 

I try to login as a learner `l`, but am brought to this second "Create a password" page. (Also see other issues pointed out in screenshot)

![image](https://user-images.githubusercontent.com/10248067/85910455-c176eb00-b7d3-11ea-94b4-cf1386b5cd0d.png)

Screenshot 2:

I try to login as superuser `jb`. I get stuck at the sign-in page

![image](https://user-images.githubusercontent.com/10248067/85910489-00a53c00-b7d4-11ea-88b1-72ac90f11e9e.png)

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context
0.14 beta 6

**Comment by jredrejo** [comment]
I think this is related to #7115 as I could reproduce these same behaviour when using app mode, @jonboiser had you activated app mode when this happened to you?

**Comment by jonboiser** [comment]
I ran `kolibri plugin list` just now and the `app` plugin is disabled.

**Comment by jredrejo** [comment]
Closed with #7223
