### ISSUE TITLE
contentDB schema design limitations

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#720]
## Summary

I think committing to the "tree structure" [data model](http://kolibri.readthedocs.io/en/latest/dev/content/concepts_and_definitions.html) will lead to significant limitation for content reuse. The problem is discussed below, and an alternative is proposed.

## Scenario
Consider the following use case:

  - author creates content node `quadratic equation` which is a summary of how to use the quadratic equation, that consists of three subnodes:
    ```
    quadratic_eqns = ContentNode(title='Quadratic equations')
    intro = ContentNode(title='Intro paragraph', parent_id=quadratic_eqns.id)
    formulas = ContentNode(title='Quadratic formula', parent_id=quadratic_eqns.id)
    proof = ContentNode(title='Derivation of the q. eqn', parent_id=quadratic_eqns.id)
    extra = ContentNode(title='Extra explanations', parent_id=quadratic_eqns.id)
    ```
  - author creates two tutorials that include the `quadratic_eqns`
     - Basic math techniques
       - math topic 1
       - math topic 2
       - solving quadratic equations
       - math topic n
     - Solving kinematics problems
       - phys topic 1
       - phys topic 2
       - solving quadratic equations
       - phys topic n

Using the current data model (where each `ContentNode` has a unique `parent_id`) it would be impossible for the ContentNode `quadratic_eqns` to be used in both places.

Furthermore, if the current data model is somehow modified to allow `ContentNode`s  to be reused in multiple locations another problem would arise if the author chooses to customize the nodes that will be included as part of the two tutorials.

Assume the author wants to include different subsets of the `ContentNode`s from the `quadratic_eqns`. The author wants the first tutorial (Basic math techniques) to include the full contents: `[intro,formulas,proof,extra]`, whereas the second tutorial (Solving kinematics problems) should include just the summary `[intro,formulas]`.

The author will have to "fork" `quadratic_eqns` ContentNode and make two versions, one with the full contents and one with the reduced contents.

## Unnecessary coupling of concerns
It seems there is unnecessary coupling between the tree-like structure needed for presentation:

   - `parent_id`
   - `sort_order`
   - `lft`
   - `rght`
   - `tree_id` (not sure what this does)
   - `level`

And the content/metadata needs:

  - `license_id`/`license_owner`
  - `title`
  - `content_id`
  - `description`
  - `author`
  - `kind`
  - `available`
  - `stemmed_metaphone` ??
  - `has_prerequisite`
  - `related`
  - `tags`

## Alternative
Like with all things in software architecture, one possible solution would be to add a level of indirection between `ContentNode` objects and the actual contents.

For example a new model `ContentItem` could be build that focuses on the content/metadata concerns and each `ContentNode` can "point to" a `ContentItem`. This will allow for reuse of `ContentItem`s in multiple contexts.

A useful analogy for thinking about this proposed change is `ContentItems` as songs, and the (hierarchy of) `ContentNode`s as a playlist of pointers to songs.

I have been thinking about "data representation" for educational content for the past 10+ years so I'll be happy to discuss further.

**Comment by 66eli77** [comment]
Thank you for submitting the issue to us and sorry for the late reply. We have a compact team, but we are expanding it. Hope the response time will be much shorter in the near future.

With our current schema, to accomplish the task described in your scenario, one needs to copy the `quadratic_eqns` node to `Solving kinematics problems` because like you said it's a tree structure and every contentnode can only have one parent. But the duplicated node will have the same `content_id`, so our tracking system can mark the progress correctly. If you finished `quadratic_eqns` under `Basic math techniques`, you will see `quadratic_eqns` gets marked as completed too under `Solving kinematics problems`.

It's trickier to deal with modification. We need to change the `content_id` once the copied node gets modified. I like to know how would you deal with modification with your proposed solution.

**Comment by ivanistheone** [comment]
Hi Eli, sorry for my delay—it's really the first time since the new year that I had
the time to think about this and try to write something coherent. See below for
and outline of the proposed "separate structure and metadata" suggestion and 
a comment on the `content_id` field you mention.

## Proposed changes to data model
To facilitate content reuse and loose coupling between the tree-like structure
and the content/metadata needs of content items, I propose that we use two models
to educational content:
  - `ContentNode` objects that are used for presentation purposes
  - `ContentItem` objects that strore the metadata
  - Linked by ForeignKey field `content_item` from `ContentNode` to  `ContentItem`

```
class ContentNode(MPTTModel, ContentDatabaseModel):
    id = UUIDField(primary_key=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)
    sort_order = models.FloatField(blank=True, null=True)
    content_item = models.ForeignKey('ContentItem')  # <<<<<<<<<<<<< this is new
    
    # relational fields
    has_prerequisite = models.ManyToManyField('self', related_name='prerequisite_for', symmetrical=False, blank=True)
    related = models.ManyToManyField('self', symmetrical=True, blank=True)
    tags = models.ManyToManyField(ContentTag, symmetrical=False, related_name='tagged_content', blank=True)
```

```
class ContentItem(ContentDatabaseModel):
    id = UUIDField(primary_key=True)
    content_id = UUIDField()
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    description = models.CharField(max_length=400, blank=True, null=True)
    license = models.ForeignKey('License', null=True, blank=True)
    license_owner = models.CharField(max_length=200, blank=True)
    kind = models.CharField(max_length=200, choices=content_kinds.choices, blank=True)
    available = models.BooleanField(default=False)
    stemmed_metaphone = models.CharField(max_length=1800, blank=True)
```


### Usage example

Here is an example usage that shows the same `ContentItem` being used in two 
different content node trees:

```
citem = ContentItem(title="Quadratic equations")
citem.save()
cnode1 = ContentNode(parent=id_of_node('Basic math techniques'), content_item=citem)
cnode2 = ContentNode(parent=id_of_node('Solving kinematics problems'), content_item=citem)
```
By *symlinking* rather than copying the content item, we make sure that any changes
like improvements and edits to the content will appear in both places.


## Modification scenario

> It's trickier to deal with modification. We need to change the content_id once
> the copied node gets modified. I like to know how would you deal with modification
> with your proposed solution.

I'll be happy to provide a working scenario that shows how modification of nodes
would work, but not sure if this thread is the right place. I can start a google
doc and write the prototype code there? Or perhaps we can schedule a Skype call,
because I think there are bunch of things to discuss:

  - Separation of concerns for data model
  - Content reuse scenario 
  - Modification scenario
  - Representation of standards (e.g. how will the CCSSM be represented? as tags?)
  - Alignment between content standards and content items
  - Alignment/identity between content items from different channels

Maybe we can get @jamalex on the call, because I'm sure he's already thinking about these things too.


## Comments on `content_id`
I'm not sure I like this approach:

```
    # the content_id is used for tracking a user's interaction with a piece of
    # content, in the face of possibly many copies of that content. When a user
    # interacts with a piece of content, all substantially similar pieces of
    # content should be marked as such as well. We track these "substantially
    # similar" types of content by having them have the same content_id.
    content_id = UUIDField()
```

From what I understand, this field was added to keep "is identical to" information
for scenario where content nodes are copied when reused in different places.
If the `ContentNode` / `ContentItem` proposal is adopted, this field wouldn't be necessary.


## Comments on relational fields
The model fields `has_prerequisite` and  `related` seem like they would belong
better if attached to `ContentItem` objects rather than `ContentNode` objects,
and in fact perhaps prerequisites and relatedness of content items would be best
represented completely outside the content management system.

Consider the future scenario where a `kolibri` application serves content items
from two channels, say `KA` and `CK-12`. If `prerequisite` and `related` rel'ns
are represented on the `ContentNode` objects, then this will lead to lots of 
duplication since each channel will come with its own prerequisite structure.

Another aspect which I think is worth thinking about is the ability to attach
additional attributes to prerequisite relations. For and example of what that might
look like, consider the following examples of representation of prerequisites
from another project https://github.com/minireference/structure-api/tree/master/data 

I'm `ivanistheone` on Skype
