### ISSUE TITLE
No learner's progress in lessons and quizzies report page

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7200]
### Observed behavior

I cannot see the learner's lesson progress report although the learner's done his task in Class > Lesson that created.
Class home page
![image](https://user-images.githubusercontent.com/38421180/85913759-051c3400-b86a-11ea-83f3-801274bb93d4.png)

Lesson Report page
![image](https://user-images.githubusercontent.com/38421180/85913796-4876a280-b86a-11ea-8076-319ca0c1c283.png)

### Expected behavior

Can see the Learner's progress report
### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Create a lesson with at least one or more resources
2. Log in as learner
3. Start the lesson in Class
4. In another browser( for example IE11) Log in as coach
5. Check the learner's progress in Class home page and Lesson report page

### Context

 * Kolibri version: 0.14.0 beta 5
 * Operating system: Windows 10 pro
 * Browser: IE11 and Firefox v77.0.1

**Comment by mrpau-julius** [comment]
Also the quiz there's no learner's progress to show.
![image](https://user-images.githubusercontent.com/38421180/85914200-d3a56780-b86d-11ea-8d92-256e0e9fdba2.png)

![image](https://user-images.githubusercontent.com/38421180/85914214-f0da3600-b86d-11ea-85a8-062590b9960f.png)

**Comment by mrpau-julius** [comment]
this issue still exist in Kolibri version 0.14.0 beta 6
![image](https://user-images.githubusercontent.com/38421180/85983257-c331f000-ba19-11ea-9b94-913fa9e3aed6.png)

**Comment by mrpau-richard** [comment]
I also reproduced this issue on Windows 7 Kolibri 0.14.0 beta 6 released. I'm using Chrome 83 & Firefox 77

**Comment by radinamatic** [comment]
I can replicate this on Ubuntu 16.04, learner access/progress on lessons and quizzes does not display on Class home or Report subtabs.

<kbd> [db.zip](https://github.com/learningequality/kolibri/files/4847426/db.zip) </kbd> admin/pass, no passwords for learners

![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_680](https://user-images.githubusercontent.com/1457929/86043684-57677b80-ba49-11ea-8642-dff673dc5dbd.png)

**Comment by jonboiser** [comment]
@radinamatic I'm seeing something similar to your quizzes, where the progress says "0 of 0 started". Even though I try to assign a lesson to the whole class, it doesn't get updated as such, so also says "0 of 0 started" (it should say something like "0 of 20 started")

**Comment by radinamatic** [comment]
You might be onto something, the issue might be that it seems impossible to **assign** a task to recipient(s)

![recipients](https://user-images.githubusercontent.com/1457929/86052117-c0a1bb80-ba56-11ea-9ce5-5dd5a5922bbb.gif)

**Comment by jonboiser** [comment]
@rtibbles Could you look into this? When I've debugged this, I noticed that the code in `LessonViewset.consolidate` behaves differently in Python 2 + and Python 3. Here's the code with some `print` statement I added
```python
    def consolidate(self, items, queryset):
        assignment_ids = []
        for item in items:
            print("before")
            print(list(item["assignment_ids"]))
            assignment_ids.extend(item["assignment_ids"])
            print("after")
            print(list(item["assignment_ids"]))
        assignments = LessonAssignment.objects.filter(id__in=assignment_ids)
        assignments = annotate_array_aggregate(
            assignments, learner_ids="collection__membership__user__id"
        )
        assignments = {
            a["id"]: a
            for a in assignments.values(
                "id",
                "collection",
                "learner_ids",
                "assigned_by",
                collection_kind=F("collection__kind"),
            )
        }
        for item in items:
            print("second loop")
            print(list(item["assignment_ids"]))
            item_ids = item.pop("assignment_ids")
            item["lesson_assignments"] = [assignments[a] for a in item_ids]
            item["learner_ids"] = list(
                set(
                    chain.from_iterable(
                        a.pop("learner_ids") for a in item["lesson_assignments"]
                    )
                )
            )
        return items


```
Output
```
before
['9c1b671856420eea48e27ea6073cbc83']
after
[]
second loop
[]

before
['132e69078df16d64bcba28bbbc37baee']
after
[]
second loop
[]
```

So, I think the `map`s are getting wiped out in the first loop. I tried some similar code in a Python 2 REPL and didn't see that happen.

```
Python 2.7
>>> ids = []
>>> map1 = map(chr, [1,2,3,4])
>>> ids.extend(map1)
>>> list(map1)
['\x01', '\x02', '\x03', '\x04']

Python 3.7
>>> ids = []
>>> map1 = map(chr, [1,2,3,4])
>>> ids.extend(map1)
>>> list(map1)
[]
```

The overall result is that the serialized Lesson has an empty `lesson_assignments` array

```
{
  "id": "b74a014a5e3da02f54cdd0452b9deab2",
  "title": "Lesson 1-D",
  "description": "",
  "resources": [...]
  "lesson_assignments": [],
  "learner_ids": []
}
```

**Comment by mrpau-richard** [comment]
This issue fixed in beta7, learner progress now showing on coach page
![c1](https://user-images.githubusercontent.com/8663934/86121269-55182680-bb08-11ea-9913-6d7422e944e6.PNG)

**Comment by radinamatic** [comment]
Thanks for confirming @mrpau-richard, closing!
