### ISSUE TITLE
Cannot Login to Account after upgrading to 14.066 from 13.3

### ISSUE THREAD

**Issue by Rbuten** [learningequality/kolibri#7202]
### Observed behavior

…

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by Rbuten** [comment]
Account still present.  Tried to recreate new with same name.

**Comment by cyberorg** [comment]
Issue still exist on Beta 7, any hint on why this is closed?

Using the existing user the login does not move on to password, putting any random user allows to get to password input.

Login works fine in fresh install and setup, does not work only when upgrading with existing users.

Replacing kolibri/plugins/user/static/kolibri.plugins.user.app/kolibri.plugins.user.app-0.14.0b7.js with file from older version makes it possible to login.

in kolibri.txt log:

INFO 2020-07-01 16:32:28,301 cherrypy.access 127.0.0.1 - - "POST /api/auth/session/" 400 0 "http://localhost:8080/en/user/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"

In console log:
[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: "Request failed with status code 400"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
api-resource.js:167:24
    promise api-resource.js:167

May be related to : https://github.com/learningequality/kolibri/pull/7223
Duplicate of https://github.com/learningequality/kolibri/issues/7199

**Comment by Rbuten** [comment]
Maybe my posting error, I had just discovered it and posted and had nothing
to add.

**Comment by rtibbles** [comment]
Yes, this is definitely an extant issue and is being tracked in the issue and PR above, so fine for this to remain closed for now!
