### ISSUE TITLE
Issues with visual focus indicator on buttons on a single setup wizard step

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7203]
### Observed behavior

Setup wizard > Advanced > Create or import facility

Firefox on the left, Chrome on the right

![visual-focus](https://user-images.githubusercontent.com/1457929/85937286-6e4f8600-b902-11ea-91c4-0cfbb8f96543.gif)

The issue is present on this step only, all actionable UI elements on other setup wizard steps apparently display correctly.

### Expected behavior
Fully visible visual focus indicator.

### User-facing consequences
Confusion which button is in focus when navigating by keyboard.

### Errors and logs
…

### Steps to reproduce
Setup wizard > Advanced > Create or import facility

### Context
 * Kolibri version: 0.14.0b6, DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: both Firefox and Chrome

**Comment by jonboiser** [comment]
I'm guessing this might be because of an `overflow: hidden` rule of some sort on the KButtonGroup, since the green focus indicator appears when the form has a single button?

**Comment by radinamatic** [comment]
Same occurrence today during the mini bug bash, inside the 'Create new user' modal.

![Create new user - Kolibri - Mozilla Firefox_686](https://user-images.githubusercontent.com/1457929/86191842-5ec17e80-bb48-11ea-8d34-f38ca6952bd7.png)

**Comment by indirectlylit** [comment]
this should be fixed. please re-open if you see it again
