### ISSUE TITLE
Completed update channel task displays the 'in-progress' status until the page is reloaded

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7205]
### Observed behavior
I updated a few channels in the in-context translation server, and the most recent task always displays the _In-progress_ status, and the <kbd>Cancel</kbd> button, but the :heavy_check_mark: when completed. 

Once you refresh/reload the page, the task has the _Finished_ status, and the <kbd>Clear</kbd> button

![crwdns278692:0crwdns277678:0crwdne277678:0crwdne278692:0 - Mozilla Firefox_676](https://user-images.githubusercontent.com/1457929/85938305-4d8c2e00-b90c-11ea-991a-52692d2edd8a.png)

### Expected behavior
Status indicators and icons must be coherent and display the same state.

### User-facing consequences
Confusion by inconsistent UI message.

### Errors and logs
…

### Steps to reproduce
Not able to actually reproduce this locally (have to find some old channels on local USB drives), but check other channels in the in-context translation server.

### Context
 * Kolibri version: 0.14.0b6 at https://kolibri-translate.learningequality.org/
 * Operating system: Ubuntu...?
 * Browser: both Firefox & Chrome

**Comment by jonboiser** [comment]
@radinamatic Is this something you can reproduce on places other than the translation server? Hopefully this is just a quirk of that specific deployment...

**Comment by radinamatic** [comment]
Haven't been able to repro it locally, no. 
Going to close and reopen if I can reproduce!
