### ISSUE TITLE
'Create an account modal' displays the 'Explore without account' link

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7206]
### Observed behavior

Looks like a regression...? It's there on the step 2 too.

Step 1 | Step 2
------------ | -------------
![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_671](https://user-images.githubusercontent.com/1457929/85938674-a3160a00-b90f-11ea-86e5-1f8d743d7ebd.png) | ![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_672](https://user-images.githubusercontent.com/1457929/85938753-3d764d80-b910-11ea-9540-5df1a6f1d559.png)

Flagging the error in the console, but probably unrelated.

### Expected behavior
No 'Explore without account' link.

### User-facing consequences
Unnecessary option: if the user already decided to create an account, they probably don't need the CTA to explore without one...?

### Errors and logs
See the screenshot.

### Steps to reproduce
…

### Context
 * Kolibri version: 0.14.0b6, DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: both Firefox and Chrome

**Comment by nucleogenesis** [comment]
This was initially a part of the design as an "escape hatch" if I recall correctly - in any case I recall it coming up at some point during design or development.

@riddhiavlani has this been considered during your design updates?

**Comment by riddhiavlani** [comment]
It doesn't have 'Explore without account' but there is a 'sign in with an existing account' in the design. @jtamiace, the multi facility login figma file that you had shared has the 'sign in with an existing account' on the pages shared above. Should it be there? I'll update it otherwise!

**Comment by jtamiace** [comment]
Yeah 'Sign in with an existing account' is the intended design
