### ISSUE TITLE
The Options dropdown has a “hi” as title and extra padding.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7210]
### Observed behavior
All Options dropdowns in Kolibri has the "hi" as title with a bit more padding.

This shows in IE11, Firefox v77, and Chrome v83.

<img width="1016" alt="Screen Shot 2020-06-29 at 6 14 53 PM" src="https://user-images.githubusercontent.com/175580/85999499-c2f81b80-ba3e-11ea-87a8-900ef9592011.png">

### Expected behavior
Maybe remove the "hi" and replace with appropriate title?

### User-facing consequences
Nothing important.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4845143/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4845145/kolibri.txt)

### Steps to reproduce
1. Download and install [v0.14.0-beta6](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta6)
1. Do a quick setup of Kolibri.
1. Create a user and on the list of Users page click on the `Options` dropdown.
1. Notice the "hi" title of the dropdown and the extra space/padding of the window.

### Context
 * Kolibri version: [v0.14.0-beta6](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta6)
 * Operating system: Win7 on VM
 * Browser: IE11, Firefox v77, and Chrome v83

**Comment by radinamatic** [comment]
Apparently drop-down selects in many places are very eager to salute, see #7175 (among others).

**Comment by indirectlylit** [comment]
should be addressed by https://github.com/learningequality/kolibri-design-system/pull/52
