### ISSUE TITLE
Fix vue-test-utils deprecation errors

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7215]
`vue-test-utils` in changing their API again. The most common errors right now are these:

```
      [vue-test-utils]: finding components with `find` is deprecated and will be removed in the next major version. Use `findComponent` instead.
      [vue-test-utils]: contains is deprecated and will be removed in the next major version. Use `wrapper.find`, `wrapper.findComponent` or `wrapper.get` instead.
      [vue-test-utils]: isVueInstance is deprecated and will be removed in the next major version.
```

In the `spec.js` files, replace all calls to `wrapper.find` with `wrapper.findComponent` (and whatever other recommendations they make) and it should clear these up.

**Comment by jonboiser** [comment]
@MisRob Thanks for taking this on!

This might be ambitious, but I'm hoping we can even upgrade `vue-test-utils` to the latest version 1.0.0 (final) if you manage to take care of all the deprecated API. 

I just want to point out that some of the things we do in our tests might be hard to migrate. (And are not as simple as a find-replace, like I initially thought). For example, there is one thing that's done where we chain `.find` in ways that don't work anymore (I can't remember the exact place), like this

```
wrapper
    .find('.some_class') // <- returns DOM element
    .findComponent({ name: 'SomeComponent' }) <- can't `.findComponent` off a `.find` call since this is supposed to find Vue components
```

**Comment by MisRob** [comment]
Thank you @jonboiser for all the information, I've just started working on it. Will let you know if I run into some difficulties.
