### ISSUE TITLE
Reports and Plan tables alignment issue on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7220]
### Observed behavior
Reports and Plan tables alignment issue on IE11

### Expected behavior

…

### User-facing consequences
Reports and Plan tables display like this on IE11
![c1](https://user-images.githubusercontent.com/8663934/86118333-35caca80-bb03-11ea-835a-f6c5cc2f117f.PNG)

This is the display on Firefox and Chrome 
![c2](https://user-images.githubusercontent.com/8663934/86118639-af62b880-bb03-11ea-8017-e7433d816e27.PNG)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0 beta7
 * Operating system: Windows 7
 * Browser: IE11

**Comment by bjester** [comment]
I remember seeing this when I worked on printable coach reports. I don't recall if I fixed it. I have a feeling I didn't...

**Comment by blackboxo** [comment]
I would fix it. I think it is because "th" has a specified text-align: -internal-center; by Chrome default.
