### ISSUE TITLE
Question items are too big when viewing learner quiz activity in IE11.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7230]
The question items are too big (has extra padding) when viewing learner quiz activity (as coach) in IE11.

### Observed behavior
See pic.
<img width="1016" alt="Screen Shot 2020-07-01 at 7 42 36 PM" src="https://user-images.githubusercontent.com/175580/86241094-e94fbf80-bbd4-11ea-81af-d713f67fa499.png">

Here's a `gif.`:
![2020-07-01-wed--v0 14 0-b7--3--extra padding for questions at quiz report for learner 1](https://user-images.githubusercontent.com/175580/86241261-3469d280-bbd5-11ea-9668-9c5ce979677c.gif)

### Expected behavior
It should not have those extra padding.

### User-facing consequences
Only a UI thing, behavior of page is unaffected.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4857645/daemon.txt)
[ie11 console log.txt](https://github.com/learningequality/kolibri/files/4857646/ie11.console.log.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4857647/kolibri.txt)

### Steps to reproduce

1. Install [v0.14.0-beta7](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta7) in a Win7 VM.
1. Use IE11 as browser and follow this [coach-track-quiz-groups-notifications.feature - Gherkin story](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-track-quiz-groups-notifications.feature#L23).
1. Notice the Question item is too big (has extra padding).

### Context

* Kolibri version: [v0.14.0-beta7](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta7)
* Operating system: Win7 on VM
* Browser: IE11
* Python: v3.6.8

**Comment by jonboiser** [comment]
The height seems to be driven by the `a` tag here wanting to be 150px high

https://github.com/learningequality/kolibri/blob/13445ab3e443d381154b5cde44b644cf2bc5a0d1/kolibri/core/assets/src/views/AttemptLogList.vue#L27-L37

**Comment by indirectlylit** [comment]
@cpauya in your GIF, I'm also seeing some weird spacing here:

![image](https://user-images.githubusercontent.com/2367265/86502730-2cd43600-bd5b-11ea-92e1-e1f17da7bdf9.png)

Is this styling inconsistent between browsers?
