### ISSUE TITLE
Expand testing capabilities for app interface

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#7237]
### Observed behavior

Our first pass on the app interface has some limitations in terms of how we can test the API on both the frontend and backend. For the next pass, we should refactor the API to be more testable, especially as we add more platform support.

### User-facing consequences

None, but dev-facing consequence is the ability to more easily know that the Kolibri side of the app bridge is properly sending calls to the app and that these calls are properly formed.

### Context

0.14 beta 6

**Comment by rtibbles** [comment]
The addition of an app mode script by @nucleogenesis has addressee thistle about as best we can.
