### ISSUE TITLE
"Quiz" Icon Does not appear on Learn > Classes > Assignment Page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7241]
### Observed behavior

There's no icon inside the card
…
![image](https://user-images.githubusercontent.com/10248067/86409600-10a69b00-bc6e-11ea-9450-65f8b548c7ab.png)

### Expected behavior

There should be "Quiz" icon in the card

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by nucleogenesis** [comment]
Will be fixed in: https://github.com/learningequality/kolibri/pull/7190 and https://github.com/learningequality/kolibri-design-system/pull/55 together

**Comment by nucleogenesis** [comment]
Fixed in #7190
