### ISSUE TITLE
nest dependent device setting, similar to facility setting

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7247]
### Observed behavior

Settings are inter-dependent but not nested

> ![image](https://user-images.githubusercontent.com/2367265/86617573-46989780-bf6c-11ea-81f0-6dadb4a12291.png)

### Expected behavior

from @jtamiace  Proposal on the left and implications on the right, changes to the current text are in red to connect it more to the text on the sign in page.

the second nested option just puts into words what the implications are when both boxes are unchecked

If "Learn page" is selected, thinking that sign-in page and everything underneath should disable, nothing selected

<img width="1653" alt="Screen Shot 2020-07-09 at 4 35 16 PM" src="https://user-images.githubusercontent.com/6668144/87100814-326dc800-c202-11ea-8fb4-a1df8a4f11db.png">

### User-facing consequences

inconsistency

### Context

0.14.0 beta 5

**Comment by indirectlylit** [comment]
This issue is invalid because the interaction is more complex than one being dependent on the other:

![2020-07-09 12 09 50](https://user-images.githubusercontent.com/2367265/87080811-291e3480-c1dd-11ea-9da6-adca1616255d.gif)

**Comment by indirectlylit** [comment]
@jamalex FYI

**Comment by jtamiace** [comment]
I think it's possible to make this less complex by nesting. Proposal on the left and implications on the right, changes to the current text are in red to connect it more to the text on the sign in page.

the second nested option just puts into words what the implications are when both boxes are unchecked

If "Learn page" is selected, thinking that sign-in page and everything underneath should disable, nothing selected

<img width="1653" alt="Screen Shot 2020-07-09 at 4 35 16 PM" src="https://user-images.githubusercontent.com/6668144/87100814-326dc800-c202-11ea-8fb4-a1df8a4f11db.png">

**Comment by indirectlylit** [comment]
thanks! updated issue description with your proposal
