### ISSUE TITLE
Extra redirect during sign-in when pressing `<enter>` key to submit username

### ISSUE THREAD

**Issue by micahscopes** [learningequality/kolibri#7248]
### Observed behavior
If I press the `<enter>` key to submit my username on the Kolibri sign in screen, I'm redirected to the page I'm already on and have to type in my username again.

![weird login redirect](https://user-images.githubusercontent.com/389782/86630700-c76a8a00-bf92-11ea-877e-66b952c62134.gif)

### Expected behavior
Pressing the `<enter>` key should be equivalent to clicking "Next".  After pressing it, I should be prompted for my password.

### User-facing consequences
This could be confusing and distracting.

### Steps to reproduce
1. Navigate to a signed-out instance of Kolibri
2. Type in your username
3. Press `<enter>`

### Context
I am using Kolibri 0.14.x on Linux

**Comment by indirectlylit** [comment]
cc @nucleogenesis @jredrejo for your upcoming refactor work

**Comment by micahscopes** [comment]
@nucleogenesis seems like this is resolved now, would you agree?

**Comment by nucleogenesis** [comment]
@micahscopes Yep! Closed with #7306
