### ISSUE TITLE
Can't create New User

### ISSUE THREAD

**Issue by cjbamenda** [learningequality/kolibri#7249]
### Observed behavior

When creating a new user, the "Save" button is non responsive.

### Expected behavior

"Save" should result in creation of a new user account.

### User-facing consequences

Can't add new students, or users to the system.

### Errors and logs

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating ‘this$1.$refs.passwordTextbox.focus’)
	(anonymous function) (kolibri.plugins.facility.app-0.14.0b7.js:1:211088)
	promiseReactionJob
```

### Steps to reproduce

Facility > Users > New User > add user info then click "Save" No response.

### Context

 * Kolibri version 0.14-beta7
 * Operating system: Raspbian Stretch
 * Browser: Safari on Mac OS; Firefox 77.0.1 (64-bit) on MacOS 10.14.6

**Comment by jonboiser** [comment]
This should be fixed in #7238 and in the next beta (beta 8). To confirm, does your Facility have the "passwords not required for learners" setting turned on?

**Comment by cjbamenda** [comment]
@jonboiser Yes. Our Facility has "passwords not required for learners" setting turned on?

**Comment by cjbamenda** [comment]
Sorry, didn't mean to close the issue. Is there a way to unclose it?

**Comment by jonboiser** [comment]
Thanks @cjbamenda, I am fairly confident that this bug was fixed in the latest version of the code, and the "Create new user" form will work for facilities with the "password not required" setting in Beta 8.

I think we will release the new beta later today.

**Comment by cjbamenda** [comment]
After installing beta8, I confirm that the Add User function is working correctly.

**Comment by jonboiser** [comment]
Great to hear, thank you for testing this!
