### ISSUE TITLE
In Coach Notifications Feeds (Homepage + full activity feed), some icons are missing from notification

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7250]
@cpauya in your GIF, I'm also seeing some weird spacing here:

![image](https://user-images.githubusercontent.com/2367265/86502730-2cd43600-bd5b-11ea-92e1-e1f17da7bdf9.png)

_Originally posted by @indirectlylit in https://github.com/learningequality/kolibri/issues/7230#issuecomment-653705534_

This might be because the icon for the thing (quiz, resource, etc.) is missing. See screenshot in in second post.

And this is probably related to #7241 , and general changes to `KIcon` interface

**Comment by jonboiser** [comment]
Icons are missing for items 2, 5, 6.

![image](https://user-images.githubusercontent.com/10248067/86643229-60000a80-bf91-11ea-895a-67580238db25.png)

**Comment by indirectlylit** [comment]
thanks

**Comment by nucleogenesis** [comment]
Fixed in #7190
