### ISSUE TITLE
On "Select Network Address" modal, automatically select the address created in "Add new address" modal

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7252]
In `Device > Facilities` or `Device > Channels` page, we can improve the user experience by automatically selecting just-added "static addresses" on the Select Network Address modal immediately after the "add new address" modal is dismissed.

The current behavior might either have the previously-selected or first radio button selected. 

![image](https://user-images.githubusercontent.com/10248067/86654862-2502d480-bf9b-11ea-84c5-dd55a41707e8.png)

**Comment by radinamatic** [comment]
Yes, this would be an improved user experience! :+1:
