### ISSUE TITLE
Images from perseus exercises don't show in Lesson editor

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#7258]
Source: https://community.learningequality.org/t/khan-academy-human-biology-exercises-missing-images/1549/24

### Observed behavior

[This exercise](http://35.196.115.213/en/learn/#/topics/c/2a4defb24e0449ec8147cf21d4b92429) contains 12 questions, 6 of which have images in them. 

When this exercise is used inside a lesson, the images don't show up (screenshot from cjackson server; details below):
![8973dd7b0e44998b689c254f107466e7c7c15304](https://user-images.githubusercontent.com/163966/86851452-fd863780-c080-11ea-91a4-cc54925ee41d.png)

What is strange, is that the "missing images" are present on cjackson's device:

- http://kolibri.jv:8080/zipcontent/2e3bdf4a903ae6c4a69c60d3339feb18.perseus/images/59dd6c40aa2991bcc9a34ac50978ecb0.svg (the image from Question 8)  [see [this url](http://35.196.115.213/zipcontent/2e3bdf4a903ae6c4a69c60d3339feb18.perseus/images/59dd6c40aa2991bcc9a34ac50978ecb0.svg) on our demo server]

- http://kolibri.jv:8080/zipcontent/2e3bdf4a903ae6c4a69c60d3339feb18.perseus/images/af0e2a7a75154320f7aaa0fbe71fa74f.png  (the image from Question 9) [see [this url](http://35.196.115.213/zipcontent/2e3bdf4a903ae6c4a69c60d3339feb18.perseus/images/af0e2a7a75154320f7aaa0fbe71fa74f.png) on our demo server]

so the images are clearly there, just not showing up on the lesson editor.

### Expected behavior

Images show up (screenshot from an online demo server where it works):
<img width="690" alt="Screen Shot 2020-07-07 at 8 36 19 AM" src="https://user-images.githubusercontent.com/163966/86851271-b13af780-c080-11ea-9b1e-c04051371af7.png">

### User-facing consequences

Perseus rendering inside the lesson editor can get into broken state, for certain combinations of kolibri-server + kolibri setup.

### Steps to reproduce

I was not able to reproduce the bug on any of the Kolibri demo servers (tested in 0.13.3 and 0.14.0b8), so the problem must be something specific to cjackson's setup (details below).

#### Kolibri version
 - Version: 0.14.0b8
 - OS: Linux-4.19.69-v7±armv7l-with-debian-9.11
 - Python: 3.5.3
 - Installer: kolibri(apt) with **kolibri-server Version: 0.3.8~beta2-0ubuntu1**
 - Server: undefined
 - Database: /home/pi/.kolibri/db.sqlite3
 - Free disk space: 49 GB
 - Server time: Tue Jul 07 2020 19:40:38 GMT+0100 (WAT)
 - Server timezone: Africa/Douala

#### Clients
 - MacBook Pro: Mac OS 10.14.6, Safari Version 13.1.1 (14609.2.9.1.3), Firefox 78.0.1 (64-bit),
 - iPad2 iOS 9.3.5 (Safari), iOS 13 (Safari),
 - Galaxy Tab 8: Android 8.1.0 Chrome 69.0.3497.100

**Comment by ivanistheone** [comment]
[Followup debugging](https://community.learningequality.org/t/khan-academy-human-biology-exercises-missing-images/1549/32?u=ivan) by cjackson:

> QA. Try to access the exercise directly outside the lesson editor. I think the link for you should be:
http://kolibri.jv:8080/en/learn/#/topics/c/2a4defb24e0449ec8147cf21d4b92429 1 but if that doesn’t work navigate to the exercise manually from Learn > Channels > Form 3 Biology > Cells > Prokaryotic and Eukaryotic Cells. Answer a few questions until you hit one with an image. Does the image show?

Accessing it directly in the existing lessons. The images do not show.

____

> QB. Creating a new lesson for this exercise, the images still do not show. Nor do they show when access directly the exercise in the channel.

Creating a new lesson for this exercise, the images still do not show. Nor do they show when access directly the exercise in the channel.

____


> One last theory is that kolibri-server + nginx is somehow caching the wrong files, so restarting the server might clear the cache. I’m not 100% sure of the commands but try: sudo systemctl stop kolibri-server followed by sudo systemctl start kolibri-server.

I have restarted the entire RPi device, as well as the server, but that doesn’t change the situation with the missing images.

**Comment by rtibbles** [comment]
This should be resolved by the shift of perseus rendering away from the zipcontent endpoint. This should be reopened if a recurrence is reported.
