### ISSUE TITLE
Manage content / Generating channel listing page fails with errors

### ISSUE THREAD

**Issue by cjbamenda** [learningequality/kolibri#7265]
### Observed behavior

Attempting to manage channel content, or import new content from Studio, at the "Loading" "Generating channel listing..." page, only spinning wheel and lots of errors in Web Inspector. Then Kolibri seems to become overwhelmed and unresponsive for a number of minutes.

Sometimes, cancelling by clicking the "X" at the top left will result in the channel management page to appear.

Sometimes, results in Error page with message: 504 Gateway Time-out nginx/1.10.3 and unresponsive. Requires restart of Kolibri, or hardware reboot of device.

[Console.txt](https://github.com/learningequality/kolibri/files/4890746/Console.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4890751/kolibri.txt)

### Expected behavior

Should result in a channel listing page to select topics/content to import or delete.
### User-facing consequences

See attached files

### Steps to reproduce

Device > Channels > Manage

### Context
 * Kolibri version 0.14.0b8
 * Operating system: Raspbian Stretch / MacOS 10.14.6
 * Browser: Safari Version 13.1.1 (14609.2.9.1.3)

**Comment by jonboiser** [comment]
@rtibbles The logs for this issue coming out of `/api/tasks/task` show a similar traceback to the logs in #7267 , so these two might be related

```
  File "/usr/lib/python3/dist-packages/kolibri/dist/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/lib/python3/dist-packages/kolibri/dist/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python3/dist-packages/kolibri/dist/redis/connection.py", line 307, in read_response
    raise error
redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
```

**Comment by rtibbles** [comment]
Thanks - yeah, I think there are a couple of things happening differently with Redis that we might need to take into account.

**Comment by rtibbles** [comment]
@cjbamenda did this persist even after the Redis flush?

**Comment by cjbamenda** [comment]
@rtibbles Flushing Redis did not solve this problem. However, the beta9 update did. This problem seems to have been solved.

**Comment by indirectlylit** [comment]
great - please let us know if you encounter other issues
