### ISSUE TITLE
HTML5 books (African Storybook) progress bars and completion star not working

### ISSUE THREAD

**Issue by cjbamenda** [learningequality/kolibri#7266]
### Observed behavior

Reading progress bar (blue) not growing, yellow completion bar and yellow completion star not showing after finishing reading book and, thus, performance points not added. In the image below, the book "Body" was read before upgrading to 0.14beta8. It show the completion bar and star. The second book, "Yellow" has been completely read through AFTER upgrading to the beta and the bar is stuck at beginning point, blue.

![image](https://user-images.githubusercontent.com/44643658/86934595-cc1a7400-c133-11ea-9d4e-86ec643039c7.png)

### Expected behavior

Completion bar yellow, yellow star and points added to user performance points earned.

### User-facing consequences

Inaccurate indication of tasks completed, at least with HTML5 books.

### Errors and logs

[Console.txt](https://github.com/learningequality/kolibri/files/4891498/Console.txt)

### Steps to reproduce

open HTML5 resource/book, read through completely to the end. Note that progress bar has not advanced.

### Context
* Kolibri version: 0.14beta8
 * Operating system: Raspbian Stretch; Mac OS 10.14.6, iOS 9.3.5
 * Browser: Safari Version 13.1.1 (14609.2.9.1.3); Safari for iOS 9.3.5

**Comment by rtibbles** [comment]
This feels like it may be a result of an interaction with the new progress logging we added for SCORM content - will need to double check that it is not overriding our previous default behaviour here.

**Comment by nucleogenesis** [comment]
Seems to be related to time limit settings - 1 min vs 1.5 mins vs 5 mins? 

If we're doing time based, we could do a half-progress at half-time. Per @kollivier it's a setTimeout in JS so when it fires it reports progress.

**Comment by nucleogenesis** [comment]
@rtibbles @kollivier 

This is the offending code below:

https://github.com/learningequality/kolibri/blob/2c5e52bd7c64cd0a9ec4916b36865358ec624ccd/kolibri/plugins/html5_viewer/assets/src/views/Html5AppRendererIndex.vue#L148-L162

You'll see that we're checking `totalTime / 3,000,000 [aka 50 minutes]` so I made a PR changing that time to 300,000 [5 mins]. https://github.com/learningequality/kolibri/pull/7405

---

If we had some metadata that gave us a "time to mastery" then we could get to 100% completion at a different rate for different pieces of content - but it seems 5 mins is a fair amount of time with what we have.

We also don't seem to be doing anything that listens to events from the iframe that could let us know when it's "completed". If reaching the last page of ASB books triggered an event we could make use of that but I'm not clear on what can/cannot be done here. I'm just thinking about conversations I heard about SCORM iframes talking to the renderer (if I'm recalling that all correctly anyway).

**Comment by kollivier** [comment]
Oof, good catch, thanks! That would definitely cause a problem...!

Re: progress events / completion messages, for HTML5 apps I think the way forward would be to leverage SCORM and, for content we choose is worth the effort of adding progress tracking, we should just add a JS SCORM wrapper and send progress messages using that. Of course, someone has to go into the content source and make those modifications... ;-)

**Comment by nucleogenesis** [comment]
Fixed in #7405
