### ISSUE TITLE
Server errors on contentsummarylog

### ISSUE THREAD

**Issue by cjbamenda** [learningequality/kolibri#7267]
### Observed behavior

At irregular intervals, Kolibri crashes, or hangs for some time. Sometimes this requires restarting Kolibri. Sometimes, it requires restarting the RPi server completely.

Most recent error where this occurred was opening a KA English video on basic addition. The interface produced an error as shown below.
### Expected behavior

Not getting these errors, hangs, crashes.

### User-facing consequences
Users are disrupted in use of Kolibri, often have to log back in and relocate their work that was in progress.

### Errors and logs

```json
{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "connection": "keep-alive",
    "content-length": "27",
    "content-type": "text/html",
    "date": "Wed, 08 Jul 2020 16:47:30 GMT",
    "server": "nginx/1.10.3",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/logger/contentsessionlog/5be18eb70aba3cd72af35e5c65a6e974/",
    "method": "patch",
    "params": {},
    "data": "{\"start_timestamp\":\"2020-07-08T16:47:23.996Z\",\"end_timestamp\":\"2020-07-08T16:47:28.760Z\",\"time_spent\":1.98}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-CSRFToken": "RX0rAFhbrnG969cFWVr9VCRbdYazrRftlm2KlQtP5K1oT74SN7d7FR7ELWDqcden"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1
  },
  "request": {}
}

{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "connection": "keep-alive",
    "content-length": "27",
    "content-type": "text/html",
    "date": "Wed, 08 Jul 2020 16:52:21 GMT",
    "server": "nginx/1.10.3",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/logger/contentsummarylog/71bb4d352e4f469dc111438f62750c72/",
    "method": "patch",
    "params": {},
    "data": "{\"end_timestamp\":\"2020-07-08T16:52:20.274Z\",\"progress\":0.0033923770273437503,\"time_spent\":5.800000000000001,\"extra_fields\":{\"contentState\":{\"savedLocation\":217.35127272727271}}}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-CSRFToken": "RX0rAFhbrnG969cFWVr9VCRbdYazrRftlm2KlQtP5K1oT74SN7d7FR7ELWDqcden"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1
  },
  "request": {}
}
```

### Steps to reproduce

Open Khan Academy video. 
The following actions can cause the error: Start play. Stop play. Scrub back. Cancel video with "X" at top of screen.

### Context

Version:           0.14.0b8
OS:                Linux-4.19.69-v7+-armv7l-with-debian-9.11
Python:            3.5.3
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            undefined
Database:          /home/pi/.kolibri/db.sqlite3
Free disk space:   49 GB
Server time:       Wed Jul 08 2020 17:54:13 GMT+0100 (WAT)
Server timezone:   Africa/Douala

Client devices: MacOS 10.14.6 with Safari Version 13.1.1 (14609.2.9.1.3); iPad2 with iOS 9.3.5 with Safari browser; Galaxy Tab 8, Android 8.1.0, Chrome 69.0.3497.100

[kolibri.txt](https://github.com/learningequality/kolibri/files/4892134/kolibri.txt)
[Console.txt](https://github.com/learningequality/kolibri/files/4892161/Console.txt)

**Comment by rtibbles** [comment]
Thanks for the report @cjbamenda - looks like we have a weird interaction with our resource locking and redis. Will take a closer look at this.

**Comment by cjbamenda** [comment]
I don't know if this has a direct bearing, however with the mention of redis, that triggered a memory for me of something José suggested to use redis-cli/flushall. I was getting increasingly repetitive errors of the same type as shown above, used this command and things calmed down, though not 100%. I'm still not able to update channel content from Studio. Getting 

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (kolibri.plugins.coach.side_nav-0.14.0b8.js.map, line 0)

even though Studio is online and accessible.

**Comment by rtibbles** [comment]
Hrm, that particular error is about an optional static resource loading, so that wouldn't pinpoint the issue.

Do you have any log files from these more recent attempts? The Redis errors have hopefully been mostly fixed by the flush, but would be good to narrow down to see what is still happening.

**Comment by cjbamenda** [comment]
I have just upgraded to beta9 and tested for this problem. I am the only user on the system. It still resulted in the same error. Here is the content of the error report from Kolibri. This came about after viewing a video, scrubbing back and forth a few times, then allowing the video to complete. At the end, it went to the "Something went wrong..." page. I'm attaching the kolibri & daemon logs directly after this error.

[daemon.txt](https://github.com/learningequality/kolibri/files/4906493/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4906494/kolibri.txt)

```json
{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "connection": "keep-alive",
    "content-length": "27",
    "content-type": "text/html",
    "date": "Sat, 11 Jul 2020 08:17:50 GMT",
    "server": "nginx/1.10.3",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/logger/contentsummarylog/463509f1d351ffbda636d33802c8003c/",
    "method": "patch",
    "params": {},
    "data": "{\"start_timestamp\":\"2020-07-11T08:14:24.095Z\",\"end_timestamp\":\"2020-07-11T08:17:48.958Z\",\"progress\":0.5981691442835297,\"time_spent\":199.17200000000003,\"extra_fields\":{\"contentState\":{\"savedLocation\":327.448}}}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRFToken": "I7RtHEOzhGVgKUPAFHjbs3P2hWqv5C9Tqm56oKkSMXliEIPD2sOtQwPExEyaYhNI"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1
  },
  "request": {}
}
```

**Comment by cjbamenda** [comment]
@rtibbles I've installed beta10. I'm sure you have not yet addressed this server error issue, so just to confirm that it continues.

Log files are attached.

Kolibri system info:


```
Version:           0.14.0b10
OS:                Linux-4.19.69-v7+-armv7l-with-debian-9.11
Python:            3.5.3
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            undefined
Database:          /home/pi/.kolibri/db.sqlite3
Free disk space:   44 GB
Server time:       Tue Jul 14 2020 10:09:52 GMT+0100 (WAT)
Server timezone:   Africa/Douala
```

Below is the error w/in Kolibri. 

```json
{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "Internal Server Error",
  "headers": {
    "connection": "keep-alive",
    "content-length": "27",
    "content-type": "text/html",
    "date": "Tue, 14 Jul 2020 08:57:52 GMT",
    "server": "nginx/1.10.3",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/logger/contentsessionlog/50e76e807fa40c1fe55442bc627ba279/",
    "method": "patch",
    "params": {},
    "data": "{\"start_timestamp\":\"2020-07-14T08:57:39.428Z\",\"end_timestamp\":\"2020-07-14T08:57:51.456Z\",\"time_spent\":10.335999999999999,\"progress\":0.015946921467084634}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRFToken": "3x4lwLMAotwqQFRHhAqdqRe7v3QmBuCc67pcg8hUUh38pi8FWiQgwmfsEyl0BTyP"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1
  },
  "request": {}
}
```

[daemon.txt](https://github.com/learningequality/kolibri/files/4917702/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4917703/kolibri.txt)

**Comment by indirectlylit** [comment]
Thanks @cjbamenda 

FYI, your error messages are formatted more cleanly if you use a code block:

https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by rtibbles** [comment]
OK, this still seems to be Redis related - seems like a DB write lock is getting lost.

I think the simplest fix to this (and another issue that had a similar error) is to not do an assert during the release method of the RLock.

**Comment by cjbamenda** [comment]
@rtibbles 

I have updated to beta12. This server error continues and seems to have increased in some ways. I'm running the beta on my existing in-use server which is giving it a good test with the students coming to use it (I don't think I can go backwards to 0.13.3 at this point. This time (has happened before as well), the RPi became inaccessible and required a hard reboot.

[daemon.txt](https://github.com/learningequality/kolibri/files/4939280/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4939281/kolibri.txt)

Anyway, same error occurs as mentioned above. See attached log files. Let me know if there is something more you need.

**Comment by rtibbles** [comment]
Hi @cjbamenda - thanks. There is an open PR here: https://github.com/learningequality/kolibri/pull/7300 which we hope will fix the issues you are seeing. Will hopefully merge it soon and get it into beta 13.

**Comment by cjbamenda** [comment]
@rtibbles 

Want to report that thus far with beta14, it appears this problem has been solved. I discovered as well with @jredrejo that the redis cache was filled which was causing Kolibri to hang and become unresponsive. Clearing the redis db has solved that problem.

**Comment by rtibbles** [comment]
@jredrejo do we need a follow up issue to more gracefully handle the redis cache being full, or does @bjester's work handle that case better already?

**Comment by bjester** [comment]
@rtibbles My thoughts are that it does. I think we should greatly encourage setting the `maxmemory` and `maxmemory-policy` settings either through the Kolibri `options.ini` or through the redis configuration file, usually at `/etc/redis/redis.conf` or `/etc/redis.conf`. From an application perspective, I think errors arising from a full redis cache should be fatal in nature since the cache is only readable, if that.

**Comment by rtibbles** [comment]
OK, let's close this issue for now then, we can reopen if it becomes apparent we are not handling it gracefully enough!
