### ISSUE TITLE
Put more info in `api-resource.js` errors that can help with debugging

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7268]
I notice that a lot of bug reports will show console logs that point at some kind of HTTP error

From logs in #7263 
```
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
```

But, normally I need reproduce the error and look in the network tab to see _which_ endpoint actually returned an error. Then the debugging process then is normally:

1. Based on the endpoint, find the Resource class that wraps it
1. Find the call site for the request, which is straightforward if you have the full traceback that points to something like a component method. Much less straightforward if it was called inside a vuex action.

The ask:

1. More info in the these errors, like the name of the resource that failed, since it makes it easier to skip step 1 above and get a sense of what might be going just based on screenshot and logs (where the network tab isn't immediately available). Maybe even the parameters used in the request.
1. Providing more info to find the call site might be more tricky, but if `api-resource` is interacting with the vuex store somehow, it should have access to stuff like the `route` module, which could provide a URL or Route name (Useful if the screenshot or other info leaves that out)

**Comment by indirectlylit** [comment]
related: https://github.com/learningequality/kolibri/pull/7195/files

cc @MisRob
