### ISSUE TITLE
Unable to see lessons created after upgrading Kolibri with PostgreSQL

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#7271]
### Observed behavior

After upgrading Kolibri from 0.13.3 to 0.14.0b8, I'm unable to see the lessons, quizzes, class activities, and reports that I created before the upgrade on the Coach page. This issue only occurs when running Kolibri in PostgreSQL. In sqlite database, everything works fine.

### Expected behavior

Users should be able to see lessons/quizzes they created previously after the version upgrade 

### User-facing consequences

Users are unable to see the lessons and quizzes, although they exist in the database

### Errors and logs

Here's the error in the console:
<img width="1280" alt="Screen Shot 2020-07-08 at 2 08 15 PM" src="https://user-images.githubusercontent.com/19424916/86973443-6a550c80-c129-11ea-82ae-5a85c89802aa.png">

coach page after the upgrade:
<img width="1278" alt="Screen Shot 2020-07-08 at 2 27 29 PM" src="https://user-images.githubusercontent.com/19424916/86973539-9ec8c880-c129-11ea-9993-ba32efe90826.png">

### Steps to reproduce

1. start kolibri 0.13.3 in postgresql
2. create a class with a lesson and some class activity
3. upgrade kolibri to 0.14.0b8
4. check the coach page again

### Context

Kolibri version: 0.14.0b8

**Comment by jonboiser** [comment]
This might be related to #7200 and #7214, which is basically a serialization issue for `ValueViewsets` returning data from postgres. In those issues, it was a different array of IDs that was not being serialized properly. There might be something similar going on with the `member_ids` array, in a different place. A quick search of the code says this `member_ids` field comes from the ClassSummary API

**Comment by rtibbles** [comment]
Also means we need test coverage of more endpoints to catch this!

**Comment by cyberorg** [comment]
Rolling back to 0.13.3 using the same database makes everything visible again.

Could this be related? we get this running kolibri commands.

/usr/lib/python3/dist-packages/kolibri/dist/tzlocal/unix.py:108: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while start is not 0:
/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/utils/serializer_helpers.py:107: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if value is None or value is '':

**Comment by rtibbles** [comment]
Hrm, that seems like something slightly off inside some of our dependencies but is probably not the issue here - thanks for the extra context, @cyberorg!

**Comment by cyberorg** [comment]
Confirming that reports are now visible. after applying https://github.com/learningequality/kolibri/pull/7288

**Comment by cyberorg** [comment]
> Hrm, that seems like something slightly off inside some of our dependencies but is probably not the issue here 

Yes, https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/

**Comment by rtibbles** [comment]
Thanks - hopefully these warnings will disappear when we are able to update the dependencies (although explicit Python 3.8 support often involves dropping Python 2.7 support, so we may have to be judicious here!)

**Comment by lyw07** [comment]
Fixed in #7288
