### ISSUE TITLE
'undefined' value for server and database in Device - Info

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7277]
### Observed behavior

Database is postgres in both cases -

```
Version:           0.13.3
OS:                Linux-5.3.7-050307-generic-x86_64-with-Ubuntu-18.04-bionic
Python:            3.6.9
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            nginx/1.14.0 (Ubuntu)
Database:          undefined
Device name:       server
Free disk space:   454 GB
Server time:       Thu Jul 09 2020 07:30:41 GMT+0530 (India Standard Time)
Server timezone:   Asia/Kolkata
```
```
Version:           0.14.0b8
OS:                Linux-5.4.0-40-generic-x86_64-with-glibc2.29
Python:            3.8.2
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            undefined
Database:          undefined
Free disk space:   279 GB
Server time:       Thu Jul 09 2020 06:59:07 GMT+0530 (India Standard Time)
Server timezone:   Asia/Kolkata
```

### Expected behavior

Expected values : 
`Server:      nginx/1.14.0 (Ubuntu)`
`Database:    <postgres + version + database name>`

### User-facing consequences

Difficult to check accurate and convey technical information about the system environment.

### Errors and logs

None observed.

### Steps to reproduce

1. Start Kolibri with postgres as the database.
2. Login as admin user and navigate to `Device` -> `Info` -> `Advanced`

### Context

Kolibri 0.13.3 and 0.14b8
Postgres 12
Firefox
rest of the system information is given above

**Comment by jonboiser** [comment]
@lyw07 Do you have any thoughts on this? I'm noticing in the `DeviceInfoView` the `Database:` value doesn't get set if it's not a `sqlite3` database.

The comments in this code say that this `Database` field is supposed to be a path to a `.sqlite3`, file, but it seems that users might interpret the field in the Device Info Page as just the name of the db process or something else.

https://github.com/learningequality/kolibri/blob/44edffae0cceb4b254762040c432fdb9b55f1621/kolibri/core/device/api.py#L89-L92

**Comment by jonboiser** [comment]
Similarly, in that same view `info["server_type"]`, the (`Server: `) value doesn't get set at all. 

Instead, it gets set here in JS code (Line 29). I wonder if this is not a robust way of getting the `Server` (i.e. doesn't work on all web servers if they don't use the same headers)

https://github.com/learningequality/kolibri/blob/44edffae0cceb4b254762040c432fdb9b55f1621/kolibri/plugins/device/assets/src/modules/deviceInfo/handlers.js#L23-L32

**Comment by jonboiser** [comment]
So the missing `Server: undefined` seems to be because we should be extracting `infoResponse.headers.server` (lower-case 's'; the upper-case 'S' must be a holdover from the pre-axios days). I feel like this logic should be moved further back into the `DeviceInfoView` as well, though.

Now I think we just need to explicitly handle the missing branch for non-sqlite3 DBs in `DeviceInfoView`.

**Comment by lyw07** [comment]
For the `Database` field, I checked the code history and saw that it was written three years ago. I guess we put it as `Undefined` just because we didn't have postgresql support back then?

**Comment by jonboiser** [comment]
Yeah, that makes sense. Can you suggest something to put there for non-sqlite3 DBS?

In the tests for postgres settings, we have all this info

https://github.com/learningequality/kolibri/blob/44edffae0cceb4b254762040c432fdb9b55f1621/kolibri/deployment/default/settings/postgres_test.py#L19-L36

I think we might be able to do the same thing for both Sqlite and Postgres, which is return the `settings.DATABASES["default"]["NAME"]` value

**Comment by lyw07** [comment]
I see. When users use PostgreSQL for Kolibri, we ask them to set the option field `[Database][DATABASE_ENGINE]` to be `postgres` first: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/utils/options.py#L223
I think we can take advantage of that and check whether it's a postgresql database by checking `OPTIONS[Database][DATABASE_ENGINE] == postgres`

**Comment by jonboiser** [comment]
Is it possible to keep the same pattern of looking at `settings.DATABASES`? Does `OPTIONS["Database"]["DATABASE_ENGINE"]` get reflected in the `settings` object somehow?

Because I assume that this `OPTIONS` dictionary with `"sqlite"` first leads to the corresponding `settings.DATABASE["default"]["ENGINE"] = '.../sqlite3'`
```
    "Database": {
        "DATABASE_ENGINE": {
            "type": "option",
            "options": ("sqlite", "postgres"), <----- "sqlite" first
            "default": "sqlite",
            "envvars": ("KOLIBRI_DATABASE_ENGINE",),
        },
```

**Comment by lyw07** [comment]
oh yes you are right. it's set here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/deployment/default/settings/base.py#L159, so we can make something like `settings.DATABASES["default"]["ENGINE"].endswith("postgresql"): `

**Comment by jonboiser** [comment]
Yeah, I just saw that code too!

So, in this case would something like this on the Device Info Page look okay?


```
# For sqlite

Database:          /Users/jon/.kolibri/db.sqlite3

# For postgres

Database:          postgres

```

**Comment by lyw07** [comment]
yeah I think that will work well! 👍

**Comment by rtibbles** [comment]
Yeah, whatever is in the settings will be what Django is actually using - it's possible that someone might overwrite our options with their own custom settings file, so then the options would not be accurate.
