### ISSUE TITLE
Coach Report MVP UX Issues

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#728]
1. When clicking on a content item from the list on "Recent", the tab should switch to "Topics". Currently, it stays on "Recent" even though the breadcrumb updates to the filepath. 

2. How should UI update when clicking back to "All Learners" from a student profile? Currently it goes to the list of content in that topic but would it make more sense to go back to the list of learners for that topic?

**Comment by indirectlylit** [comment]
> How should UI update when clicking back to "All Learners" from a student profile? Currently it goes to the list of content in that topic but would it make more sense to go back to the list of learners for that topic?

Perhaps. If so, the content breadcrumbs should behave consistently and switch to content view even if you're not in learner view. I'll make both these changes.

(At some point I'd also like to demo/test a slight variation that's closer to the 'double-breadcrumb' idea we'd talked about a while ago, where they act more as filter updates than navigation)
