### ISSUE TITLE
setting doesn't get disabled in valid state

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7283]
### Observed behavior

The second checkbox is disabled in whatever state the user left it in:

![2020-07-09 12 05 06](https://user-images.githubusercontent.com/2367265/87086977-2c1e2280-c1e7-11ea-8754-2c7d36a3be3a.gif)

### Expected behavior

The checkbox should be disabled in the only state valid: learners cannot edit their password when they don't have a password

### Steps to reproduce

see facility settings

### Context

0.14.0 beta 8

**Comment by alexMet** [comment]
@jonboiser This issue has been resolved and it works in the "develop" branch, but not in the "release-v0.14.x".

**Comment by jonboiser** [comment]
Oh yeah, we should have closed this out! I think I'll have to cherry-pick this one to release-v0.14.x as well so it gets in the next release.

**Comment by jonboiser** [comment]
@alexMet Have you checked out some of the issues in the [0.14.4 milestone](https://github.com/learningequality/kolibri/milestone/60)? Most of them are frontend issues similar to the ones you've fixed recently.

**Comment by alexMet** [comment]
@jonboiser Oh sorry, i didn't see that you mentioned me. I was working on #7475 and i found the bug, but i don't know how to fix it. So i picked the other issues, that we are talking about.
