### ISSUE TITLE
`CoreMenu` dropdown should be slightly offset from the browser window's edge 

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7298]
See that the dropdown touches the edge of the browser window (the black content to the right is a different application).

I think that there should be a small gap between the right edge of the dropdown and the browser boundary, which is a common style choice on websites that have this kind of menu.

Similarly, in a RTL-locale, the dropdown should be offset from the left edge of the browser.

**Kolibri**

(From 0.14, but this is also the case in 0.13)

<img width="374" alt="CleanShot 2020-07-14 at 12 29 20@2x" src="https://user-images.githubusercontent.com/10248067/87468205-04a3cd00-c5ce-11ea-9f44-0319e77d49de.png">

**Other example:Github**
<img width="285" alt="CleanShot 2020-07-14 at 12 34 13@2x" src="https://user-images.githubusercontent.com/10248067/87468366-59474800-c5ce-11ea-8c1a-0ff42e6fd13a.png">

**Comment by indirectlylit** [comment]
+1
