### ISSUE TITLE
Setup Wizard -> Personal -- Creates the facility as "nonformal" - should be "informal"

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7303]
### Observed behavior

I created a new KOLIBRI_HOME and went through the setup wizard and selected "Personal" to test the Sign In Page work I'm doing for the Personal version.

When I got through with the Setup Wizard, it was created as `nonformal` rather than `informal`. I checked in Vuex and the database and it was created incorrectly.

### Expected behavior

In Setup Wizard:

Personal -> creates an `informal` facility
Advanced -> gives user the option to create a `formal` or `nonformal` facility

### User-facing consequences

Features we have for "Personal" devices/facilities will not be displayed properly.

### Context

0.14-beta9
Debian 10
Chrome

**Comment by jonboiser** [comment]
Did you see the `preset: nonformal` state in Vuex while doing a Quick Start? When I go immediately from "Pick Language" -> "Quick start", I do see the expected `preset: informal`.

It's happened before where if you go some steps into an "advanced" setup and move backwards, some of that state doesn't get reset when you take a different setup after backtracking. 

It's also possible that the correct `informal` preset is getting set on the client, but the `create` method on the ProvisionDeviceSerializer is doing something wrong, giving you a facility dataset with the wrong preset.

**Comment by nucleogenesis** [comment]
I didn't move throughout the options at all and went straight through the Personal flow because that's what I was trying to test.

I didn't look at Vuex until after I finished provisioning so I'd have to go back to try and replicate it. Can do tomorrow.

**Comment by jonboiser** [comment]
Yeah, I just reproduced this too.

Weirdly, the `preset` field on the `dataset` object in Vuex says `nonformal`, but the actual settings reflect the `informal` preset, specifically where two differ (`learner_can_sign_up: false` is correct for `informal` setups).

I also confirmed that the `facilitydataset` record has the wrong preset, so I think this might be happening at the DeviceProvisioning endpoint, where it's somehow getting the `preset` field wrong, but setting the correct default settings.

![CleanShot 2020-07-14 at 16 50 31@2x](https://user-images.githubusercontent.com/10248067/87487340-3e86ca80-c5f2-11ea-97c1-4ce7fcf0e345.png)

**Comment by jonboiser** [comment]
Yeah, I think what's happening is that we're not actually updating the `preset` field here

https://github.com/learningequality/kolibri/blob/efd4153decbc7663faed501260c76939ddffc764/kolibri/core/device/serializers.py#L81-L86

And the default preset is `nonformal`.

So we're getting the right settings for the preset, but the wrong name of the preset.

It looks like we do the same thing for the `provisiondevice` management command

https://github.com/learningequality/kolibri/blob/c0e59cc470921985a8fde87e7b0a2bcec02f2d6a/kolibri/core/device/management/commands/provisiondevice.py#L62-L68

**Comment by jonboiser** [comment]
An issue I just found is that this `preset` value is not used for resetting Facility settings to their defaults. It's just this default that we have here:

https://github.com/learningequality/kolibri/blob/efd4153decbc7663faed501260c76939ddffc764/kolibri/plugins/facility/assets/src/modules/facilityConfig/actions.js#L47-L59

I think this is the only place on the UI where having the correct `preset` field is actually important, since I believe the intention is that when we "reset to default", we want to reset to the defaults for the original preset.

**Comment by jonboiser** [comment]
This wrong `preset` field is also why we've been showing the Facility Name on the Sign In page for Personal Setups too (the code says to not show it for informal/personal facilities)
