### ISSUE TITLE
devicesettings 400 on upgraded instance

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7310]
### Observed behavior

I'm messing with settings to test Sign In refactor stuff and went to save my Device Settings.

`http://localhost:8000/api/device/devicesettings/` 400 with error message just: `allow_other_browsers_to_connect`.

I changed the "user password" settings. This is what it looked like after my changes before it failed to save:

![screenshot-localhost_8000-2020 07 15-05_55_04](https://user-images.githubusercontent.com/6356129/87547314-c8b94800-c65f-11ea-91e6-9b74d0210408.png)

Toggling and saving the "Allow others in the network..." setting fixed it.

Seems like it's got something to do with the upgrade path as this is an old KOLIBRI_HOME I've used for a while.

### Expected behavior

1. Settings save when I click Save
2. A meaningful error message appears if the error cannot be handled by the backend.

### User-facing consequences

Confusion when failing to save settings and frustration if the user doesn't mess with the settings and try again.

### Steps to Reproduce

- On a KOLIBRI_HOME you've used on an older version of Kolibri, run 0.14-* branch on it so it runs the migrations and so on.
- Change a Device Setting that is NOT the top-most ones about networking
- See 400 error (ideally, anyway... I hope this is easy to replicate).

### Context

0.14.x-beta9
Debian 10
Chrome

**Comment by indirectlylit** [comment]
> Allow others in the network...

One thing that's confusing: this setting I believe should be hidden/disabled unless you're in app mode

**Comment by rtibbles** [comment]
I observed this also - it's probably because at one point this setting was nullable, and is now not nullable. So it may be set to `NULL` in your db, but should be set to True or False (or 0 or 1, because SQLite uses integers for booleans).

**Comment by rtibbles** [comment]
(as a result, this should not affect users in production)

**Comment by nucleogenesis** [comment]
I'm closing this issue because there's no need to fix it given Richard's last comment - but I'm also glad it exists because I don't remember making this issue at all and just ran into it again.
