### ISSUE TITLE
Learn -> Recommended makes API call regardless of auth

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7314]
### Observed behavior

I went to make sure that my device settings prohibiting access to Learn for guests was working properly.

The "Channels" tab felt like it took longer to load and show the auth message than I expected. So I tried Recommended and I saw in my console that it was making this request on Channels and hitting `/api/content/contentnode/popular` on Recommended.

```
/api/content/contentnode/?ids=ec164fee25ee526296e68f7c10b1e169%2Cd824828e67b9472a9987a96870729178%2C91b4ce67480b51e699c52ae10b00c724%2Ca9b25ac9814742c883ce1b0579448337%2C878ec2e6f88c5c268b1be6f202833cd4%2Cfc47aee82e0153e2a30197d3fdee1128%2C1ceff53605e55bef987d88e0908658c5%2C1d8f6d84618153c18c695d85074952a7%2C913efe9f14c65cb1b23402f21f056e99%2C61b75af2bb2c4c0ea850d85dcf88d0fd%2C27bb0abc24d44dd9896be50d47b2357e%2C09ee940e106953a2b6716e1020a0ce3f%2C000409f81dbe5d1ba67101cb9fed4530%2C277ebe3f6d434b528e45bb8f0ab01607%2C0a3446937e3340fa86e6010ba80e16e1%2Cf2ed9568a9da4157b283f76406df472c%2C1c98e92b8c2f536796960bed8d137a25%2C95a52b386f2c485cb97dd60901674a98%2C2f3f836672a958ef92097b5e4a9b2ed3%2C737804b26629425284ef48fa1b1e1bde%2C9e1bb851d3f64c338113ec23809da56f%2Cc74b5be808354f318471ba46c68c0aae&user_kind=anonymous&contentCacheKey=1594330842 HTTP/1.1" 200 12001
```

No need to get content if we can't show it to anybody.

### Expected behavior

Avoid unnecessary API calls.

### User-facing consequences

Long loading time for auth message when accessing Learn without authorization.

Unnecessary API calls could affect the server negatively

### Steps to reproduce

Device -> Settings -> then set it so learners must log in to see content in Learn.

Go to `/en/learn` and `/en/learn#/recommended` and take a look at your network tab in Chrome

### Context

Debian 10
0.14.x-beta9
Chrome

**Comment by rtibbles** [comment]
Does this PR resolve this issue? https://github.com/learningequality/kolibri/pull/7305

**Comment by nucleogenesis** [comment]
@rtibbles unfortunately not but I think I got a solution in #7353
