### ISSUE TITLE
Sign In Page Improvements Needed (Follow up to #7306)

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7321]
### Observed behavior

This issue is to track and manage the fact that I am intentionally leaving some things for post-release in the Sign In refactor done on #7306 

- ~username/password don't need to be in Vuex~ Fixed in https://github.com/learningequality/kolibri/pull/7335
- SignInPage is monolithic and its parts ought to be broken out. Password create & sign in probably should be its own route.

### Expected behavior

Better code so the next person who dives into the SignIn part of user has less mental overhead.

### User-facing consequences

None.

**Comment by jredrejo** [comment]
I'd love to study the pertinence of using [xstate](https://xstate.js.org/) to manage the sign in procedures after the release

**Comment by nucleogenesis** [comment]
The remaining concerns for this issue were kind of indirectly addressed by @indirectlylit in #8443 - will close this as I don't think SignInPage is in bad shape at this point.

**Comment by rtibbles** [comment]
> indirectly addressed by @indirectlylit 

This seems oddly appropriate.
