### ISSUE TITLE
👻 Unavailable resources on Coach Page are properly displayed

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7325]
### Observed behavior

Some work related to missing content didn't get implemented in 0.14, but the strings for the functionality were added and have been translated.

Refs:

* https://www.figma.com/file/LM0YUkbWAOIerZ3EEg0FN6bS/0.14-P2P-Sync?node-id=547%3A11
* https://www.notion.so/learningequality/Data-syncing-and-facility-management-0-14-0-44a8d0e4a5674d35b2a18a440e967cea

![image](https://user-images.githubusercontent.com/2367265/87807608-4ff7ee80-c80d-11ea-99d0-569d0cac25d5.png)

### User-facing consequences

Users of data syncing could end up with very confusing user experiences

### Context

0.14.0

**Comment by cyberorg** [comment]
Automatically importing associated content when syncing facility would be much cleaner than showing error messages, this will also allow teachers to create lessons with content from multiple channels without students having to sync all of those channels.

**Comment by indirectlylit** [comment]
@cyberorg yes, we completely agree and we are definitely looking to allow content to be synced with data.

That said, there will always still be situations where we need to handle missing content so this update is required regardless.

**Comment by jamalex** [comment]
In 0.15.1b0, I observed the following in the coach notifications when the respective channel (and hence metadata) wasn't loaded onto the device:
![image](https://user-images.githubusercontent.com/618416/153102226-5ced82a0-6403-4d13-a671-0108b9b264b4.png)

(this usage data was generated on another device, and synced in here)

From @jtamiace:
> "started a resource in this lesson" sounds like a good way to handle that, along with flags/explanations like here https://www.figma.com/file/LM0YUkbWAOIerZ3EEg0FN6bS/0.14-P2P-Sync?node-id=1034%3A11

**Comment by marcellamaki** [comment]
Moving this to 0.16, as it seems like the design fix suggested will require new strings, and I do not see the referenced string

> "started a resource in this lesson" 

in Kolibri
