### ISSUE TITLE
Impossible to scroll table/grid horizontally on small Android screens

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7339]
### Observed behavior

Using Kolibri Android app, it is impossible to scroll horizontally the table/grid view in **Facility > Classes**, and therefore not possible to view the column where the **Remove class** button appears.

Might not be `P0` worthy, but the issue remains for all the information we display as table/grid (included the various coach views).

Android (Facility > Classes; German; vertical view) | Android (Facility > Classes; German; horizontal view) | Dev server with responsive view (Firefox in English left; Chrome in German right)
------------ | ------------- | ------------- 
![DevTools - localhost:8080-de-facility-_848](https://user-images.githubusercontent.com/1457929/88012515-6d350180-cb1a-11ea-8249-832cfb806d65.png) | ![DevTools - localhost:8080-en-facility---classes_850](https://user-images.githubusercontent.com/1457929/88012660-c309a980-cb1a-11ea-8455-2b709cc6d06a.png) | ![LEDev20 04 (start)  Running  - Oracle VM VirtualBox_875](https://user-images.githubusercontent.com/1457929/88012725-ef252a80-cb1a-11ea-8b84-d4de8a4ca20c.png)

Adding tentatively to 0.14 milestones as `P2`, pending other decisions.
cc @indirectlylit @jonboiser 

### Expected behavior
Coaches, admins and super admins need to be able to view and interact with the tabled info correctly.

### User-facing consequences
Unable to use the table/grid in app context.

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: Beta 12
 * Device: Moto G Play 6 
 * Operating system: Android 9

**Comment by pcenov** [comment]
@radinamatic this issue is no longer extant in 0.15.1

**Comment by rtibbles** [comment]
Closing as no longer extant.
