### ISSUE TITLE
Secondary button on top of the primary on small Android screens

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7340]
### Observed behavior

Not sure if this is according to specs, but seems unintuitive to me... :confused: 

So far I've encountered this only when switching language from German to others, not sure if it is present in other locales.

![DevTools - localhost:8080-de-facility---users_851](https://user-images.githubusercontent.com/1457929/88013137-f39e1300-cb1b-11ea-8656-34222205fff2.png)

It would seem logical to me that the secondary button (**Cancel**) is displayed below...?
cc @jtamiace @khangmach 

### Expected behavior
Secondary button below the primary?

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
…

### Context
 * Kolibri version: Beta 12
 * Device: Moto G Play 6 
 * Operating system: Android 9

**Comment by jtamiace** [comment]
Yeah, that's the expected behavior, I think at this point it's just on the dev to do list.

I've opened an issue for the design system to handle this exact situation https://github.com/learningequality/kolibri-design-system/issues/72

**Comment by pcenov** [comment]
@radinamatic this one is fixed in 0.15.1

**Comment by rtibbles** [comment]
Closing as fixed.
