### ISSUE TITLE
Channel description overlap on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7341]
### Observed behavior
Channel description overlap on IE11 when I resize the browser Windows.

This is the display on IE11
![Screen Shot 2020-07-21 at 8 14 42 PM](https://user-images.githubusercontent.com/8663934/88054298-aeb3c400-cb8f-11ea-854d-a74b85d345cd.png)

And this is on Chrome and Firefox
![Screen Shot 2020-07-21 at 8 15 37 PM](https://user-images.githubusercontent.com/8663934/88054395-d86ceb00-cb8f-11ea-91ed-64371b106a0a.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0 beta12
 * Operating system: WIndows 7
 * Browser: iE11

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
