### ISSUE TITLE
Setup Wizard needs to more strictly enforce "one-way" flow to avoid multiple Facilities being created before provisioning

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7343]
### Observed behavior
@nucleogenesis Found [some issues here](https://github.com/learningequality/kolibri/pull/7333#pullrequestreview-452754857) when you quit the Setup Wizard at the very last step of the Facility Import flow. At this point the device has imported a facility but has not been provisioned (meaning its possible to open up the Setup Wizard again in a different browser and create/import another facility, so long as the first setup process has been halted).

Note that this isn't unique to the other setup flows (e.g. this can happen when doing the personal + create new facility flows), but I did make a decision to bypass some "provision device immediately after import a facility" logic in the original import facility command to prevent issues with the device becoming provisioned in the middle of setup and messing with special API permissions.

@nucleogenesis Also made some suggestions that the current behavior where we try to enforce one-way navigation by hiding the back button and undo-ing backward navigation in the browser history can be replaced with other mechanisms.

### Expected behavior

The main requirement is that the Setup Wizard UI enforce a strict one-way flow whose current state is driven by the server, and not the browser (to prevent the edge case of running the setup wizard on two different browsers). Currently, there is a very crude guard that basically resets the entire process if you refresh in the middle of the Setup Wizard because we have little information to infer where the process was interrupted (except in the case of the import flow, we can _infer_ based on the existence of a Facility and/or Superuser where the user was).

The other minor requirement is to possible remove the disable-back-browsing hacks (which would be easier to implement if the browser could figure out the state of the Setup Wizard from the server).

### User-facing consequences

The consequences are minor. If a user does happen to encounter this edge case, their device will still work and they can remove the extra facility using the UI as of 0.14.0

### Context
0.14.0

**Comment by indirectlylit** [comment]
Previously, I believe we made an explicit UX decision that the _final_ step of the setup wizard would be the _first_ time that the server receives a command. This was decided so that it would be impossible for an end-user to have a "partially-provisioned" server.

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate importing more than one facility through the advanced setup in 0.15.1
However it is still possible to import a facility through the advanced setup, abandon the process at the last step and go through the quick start wizard in which case there will be two facilities:

https://user-images.githubusercontent.com/79847249/159675876-3b7094f4-f5ea-4141-acaa-fdbbe9ff2e9e.mp4

**Comment by marcellamaki** [comment]
@pcenov @radinamatic - this is not a new issue, but I think during the course of the new setup wizard work, these concerns should have been resolved. can we do some testing here to ensure that's the case? Then, we can close this out as resolved. Thanks!

**Comment by pcenov** [comment]
Hi @marcellamaki I am not able to replicate this issue in 0.16. The initial issue was for Kolibri 0.14 so I think we can close this one as resolved.

**Comment by radinamatic** [comment]
Closing as not extant anymore! 💥
