### ISSUE TITLE
"Restarting" a Task normally means deleting it and triggering a new one with same parameters -> UI consequences

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7348]
### Observed behavior

I don't believe there's a way to simply restart a Task once it's in the CANCELED/FAILED status. So to implement the "retry" feature for failed facility syncs/imports, we actually delete the original one and start a new one with data that is tacked on to the task metadata.

Having to do things this way has a couple of consequences for the UI code and actual UX:

1. "Restarting" a task with our standard "poll for tasks" framework means 1) delete it, 2) see it disappear, 3) start a new one, 4) see an identical-looking task reappear
1. The API calls to restart a task require the same full payload, as opposed to a more minimal one with just the TaskID. This is why we do not allow restarting Facility Import tasks, because this would require us tacking on plaintext credentials onto metadata to use the same approach

### Expected behavior

If it doesn't already exist, it would be nice to have a simpler interface to restart a Task and reduce the process from 2 steps (delete + create) to just 1 (restart).

And concretely, this would mean that the Facility Import/Sync Task Manager UIs in the Facility Page and Setup Wizard wouldn't have the disappear-then-reappear behavior it does now.

### Steps to reproduce

…

### Context

…

**Comment by ashmeet13** [comment]
Hi!
I was looking around to understand the TaskAPI. From what I understand the TaskAPI has a [BaseViewSet](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/tasks/api.py#L180) that handles the creation/deletion of tasks.

A way to implement the RestartTask functionality from the backend would be to add an endpoint to clear the CANCELED/FAILED status marked task and then enqueuing it again.

Would like your inputs and pick this up!

**Comment by jonboiser** [comment]
> A way to implement the RestartTask functionality from the backend would be to add an endpoint to clear the CANCELED/FAILED status marked task and then enqueuing it again.

I think that's basically the interface I would like. Where you can POST to something like

```
POST /api/task/restarttask/<task_id>
```

And the original job with be enqueued with the same exact parameters, _but the parameters do not need to be sent as part of the POST request_. That is, all the client needs to know to restart a task/job is the task ID.

I'm not sure if this is possible, by simply modifying the API layer. You might need to see if there is a way to restart jobs within the queue library we're using: "iceqube".

https://github.com/learningequality/iceqube 

Here is the interface for queues

https://github.com/learningequality/iceqube/blob/master/src/iceqube/queue.py

**Comment by ashmeet13** [comment]
A few questions. I cannot find exactly how [Iceqube](https://github.com/learningequality/iceqube) is being used in Kolibri?
Is it just a framework whose code is copied into the [Task Monolithic](https://github.com/learningequality/kolibri/tree/release-v0.14.x/kolibri/core/tasks)?

Cause I don't see it being added as pip requirement.

I'll have a look and understand the system better. I have created a simple explanatory design document for the TaskAPI (iceqube) which can be found here - [Dropbox Paper](https://paper.dropbox.com/doc/Kolibri-TaskAPI-Docs-WIP--BHO5slA8cTYMvnmnSD6mneGiAQ-y4TJykzXIwrUhwWo4rQSP)

**Comment by ashmeet13** [comment]
From what I have understood, [Queue](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/tasks/queue.py) is the interface for the [TaskAPI](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/tasks/api.py) to enqueue/schedule tasks.

To implement restart, a possible solution is defining a function in `Queue`as `restart_job(self, job_id)`

`restart_job(self, job_id)` would use `Storage.get_job(job_id)` to get the Job object that was saved by `Storage` after pickling. 

Then the `restart` function can delete the existing record using `Storage.clear(job_id)` if `Job.State in [State.FAILED, State.CANCELED]`

Then re queue the Job using `enqueue(func, *args, **kwargs):` Since we will be submitting the same Job Object that was used last time it should contain the same parameters.

**Comment by rtibbles** [comment]
@ashmeet13 - yes, that could definitely work, we could also just take the existing job object, clear any exceptions or results from it and then resave it.

However, I think your solution is cleaner, and means that we don't have to keep a running list of all things we need to clear, we just need to recreate the desired `enqueue` parameters. The one other thing that we should do is make a copy of the Job by passing the existing Job to the Job constructor: `new_job = Job(old_job)`

This should clear any extraneous information (see here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/tasks/job.py#L74), like any previous raised exceptions.

Please go ahead with your solution, with the additional proviso that I mention above ^

**Comment by ashmeet13** [comment]
Got it. Thank you for the help!

**Comment by rtibbles** [comment]
Fixed in #7905
