### ISSUE TITLE
another regression: breadcrumbs lost their underlines

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7355]
### Observed behavior

Breadcrumbs lost their underlines:

![image](https://user-images.githubusercontent.com/2367265/88216895-98028100-cc12-11ea-87c8-f4011d2bf57c.png)

### Expected behavior

Underlined:

![image](https://user-images.githubusercontent.com/2367265/88216938-abade780-cc12-11ea-81cb-59779623a262.png)

### User-facing consequences

inconsistent styling

### Context

It appears that this is due to `inline-block` being applied to a number of classes in these spans:

![image](https://user-images.githubusercontent.com/2367265/88217141-f62f6400-cc12-11ea-98be-9d5b8b93b56d.png)

possibly introduced in https://github.com/learningequality/kolibri-design-system/pull/41 ? (cc @bjester @nucleogenesis)

**Comment by bjester** [comment]
@indirectlylit Yep, looks like it was introduced there. I made the selector less specific, and that was overriding something removing the underline I guess.

**Comment by indirectlylit** [comment]
confirmed that https://github.com/learningequality/kolibri-design-system/pull/83 addresses this issue

I noticed a similar issue in the task manager, and it is not addressed by the PR above. Any chance they're related?

![image](https://user-images.githubusercontent.com/2367265/88304426-1ae01600-ccbd-11ea-8017-33c7614099f2.png)

**Comment by bjester** [comment]
@indirectlylit I would guess yes, as the selector change I was referencing has an `underline` style in the block https://github.com/learningequality/kolibri-design-system/pull/41/files#diff-b154ab58cb2ae36475fb0f933b130bd2

**Comment by nucleogenesis** [comment]
@bjester @indirectlylit that was just an inconsistent implementation of the same kind of thing, but not the same thing (not using `<KRouterLink>` since it's been updated.

See: https://github.com/learningequality/kolibri/pull/7383/commits/ea7154ac852e009484e0fd48b8736cd173d69e18
