### ISSUE TITLE
The "Update Your Profile" onboarding would ideally end back at the Learn Page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7362]
### Observed behavior

Currently, if you're a user whose account was created without birth year and gender info provided, you will see the `UpdateYourProfile` modal when viewing the Learn Page for the first time. If you decide to actually do it, this is the path

1. Go to profile page
1. Fill out info and click submit
1. End up on the user page

To get back where you started at the Learn Page, you would then need to open the side nav and click "Learn"

### Expected behavior

This Learn page onboarding ends back at the Learn page, e.g.

1. Go to profile page
1. Fill out info and click submit
1. End up back at Learn page

### Steps to reproduce

1. Create a user account and skip the birth year/ gender sections
1. Log in as that user and go to the Learn page
1. Go through the Update profile stuff and not get directed to Learn page as I suggest

### Context

…

**Comment by jonboiser** [comment]
I just noticed that this is the expected behavior according to this Gherkin story

https://github.com/learningequality/kolibri/blob/64f1439972b7d6994bfe37dbd81fa46298834449/integration_testing/features/learner/learner-profile-update-notification.feature#L22-L31

**Comment by jonboiser** [comment]
@metodimilevqa Would you mind testing #7778 to confirm that it fixes this bug?

**Comment by metodimilevqa** [comment]
@jonboiser I confirm the fix is successful. After the user is prompted to update profile info and after this is done, the user is redirected to the Learn page:

![Video-2021-02-08-133423](https://user-images.githubusercontent.com/72492554/107217526-f52b1c00-6a16-11eb-8752-356a45d948a6.gif)
