### ISSUE TITLE
scroll follow-up

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7367]
### Observed behavior

breadcrumb links still point to the top of the page:

![2020-07-23 08 53 07](https://user-images.githubusercontent.com/2367265/88308592-1538ff00-ccc2-11ea-8c1b-96711498c749.gif)

### Expected behavior

breadcrumb links should have the same anchor target as tree links, namely themselves

we should also add a gherkin story describing the new scroll behaviors

### User-facing consequences

scroll jumping

### Context

0.14.0 beta 13

**Comment by nucleogenesis** [comment]
I've tried a few channels and I'm not able to replicate on beta14. Tested on Firefox & Chrome on Debian.

![ezgif-7-2b1e8cf4c6ee](https://user-images.githubusercontent.com/6356129/88349491-235c3f00-cd05-11ea-9b19-74eb34ddf1c2.gif)
