### ISSUE TITLE
Use a more specific task-description label for Facility Import (one-way sync) tasks

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7370]
### Observed behavior

On the Device > Facilities > Task page, the header on the rows for facility import tasks says `Sync 'Facility name'`

This should be fixable in `syncTaskUtils.js` in one of the Task Metadata -> UI Message utilities, as well as in the `commonTaskStrings` mixin, where a new message would need to be added.

### Expected behavior

On the Device > Facilities > Task page, the header for the facility import tasks says something like `Import 'Facility name'`

### Steps to reproduce

1. Start a Facility _Import_ task
1. Go to the Task Manager
1. See the task you just made be described as "Sync Facility Name" on its row

### Context

…

**Comment by indirectlylit** [comment]
switched to 'upcoming major' because it requires new strings

**Comment by chrislun16** [comment]
Is this still open? And would this be achievable for a newcomer to this repository?

**Comment by nucleogenesis** [comment]
@chrislun16 I'd avoid this one - the string change will involve a little bit of complexity around our i18n system. I've removed the `beginner friendly` label here. 

My apologies for the confusion - I've done a pass of the [Beginner Friendly issues](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+beginner+friendly%22+) list and most items should be relatively easy to jump into.
