### ISSUE TITLE
Emphasize "Network address" to "Device" in copy for facility sync workflows

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7374]
### Observed behavior

Some background from @jamalex : "Devices" are Kolibri peer servers that have a permanent ID (`instance_id` in Morango and other places) and might have a more transient URL/protocol.

The current UIs emphasize the _address_ as the main entity, instead of the _device_

### Expected behavior

* UI copy for p2p-facility-sync flows emphasizes "Device" over "Address"
* (Bonus) the code implementing this stuff possibly be renamed for DX purposes

### Needs Clarification

* What headers and non-header copy needs to be changed?
* Do we still retain the original "Network address" copy for import/export flows?
* Does "Device" work as a unifying term for both Kolibri Peers + Studio/Content sources so it can be used for both facility-sync + content import/export flows?

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by jonboiser** [comment]
@indirectlylit 

All of the copy in the "Select Network Address" modal use the "address" terminology, so there's no way we can swap them out with messages from a different component.

https://github.com/learningequality/kolibri/blob/96ff5f3d00bb79cdefad139a67f33160f751d5db/kolibri/core/assets/src/views/sync/SelectAddressModalGroup/SelectAddressForm.vue#L334-L341

I would suggest maybe making these clarifications @jamalex was making regarding URL/address vs. Device in the user documentation.

**Comment by indirectlylit** [comment]
sounds good - pushed to next major milestone.

Opened a PR for a related but slightly different issue here: https://github.com/learningequality/kolibri/pull/7430
