### ISSUE TITLE
test preemptively merged PR

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7377]
merged https://github.com/learningequality/kolibri/pull/7371 without testing.

this is a note to test before final release

**Comment by jredrejo** [comment]
Tests and comments done in #7371 
@bjester did you create a PR to solve the small issue we commented?

**Comment by bjester** [comment]
@jredrejo Not yet, but it's super simple. I'm trying to wrap up something else today before I'm OOO Thursday and Friday
