### ISSUE TITLE
Upgrading between beta versions didn't update the static folder at KOLIBRI_HOME

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7384]
### Observed behavior

After upgrading from 0.14beta13 to 0.14beta14 all the clients lost the connection and began to show the kolibri loading screen.
After checking it, the static folder at KOLIBRI_HOME didn't have an update version of the js and css bundles.

To solve it, `.data_version` file and the previous `static` folder was deleted. After restarting kolibri , everything began to work again

### Expected behavior

When participants of the beta program update their systems, clients should continue working

### User-facing consequences
Nothing works

### Steps to reproduce
Install kolibri 0.14 beta 13
Use it normally
Install kolibri 0.14 beta14
Try to use it normally

### Context
Raspberry PI
Installation and upgrade done using the deb package

**Comment by jonboiser** [comment]
Has this always been a problem when upgrading on RPi? We could document that users need to

1. Delete `.data_version`
1. Delete `/static` 

From Kolibri home if they are having issues after an upgrade.

**Comment by rtibbles** [comment]
No - I think it's specific for beta versions (and not just for RPi) because we exclude beta versions from the upgrade logic.

We can probably triage this out if it still does run collectstatic if upgrading from a beta to the full version - or alternatively, we can modify the update logic to be sensitive to beta version changes too.

**Comment by jonboiser** [comment]
Okay, let's remove it from the milestone. I think for people in the beta program installing a new beta should ideally "just work" without running extra commands so we could try to change the update logic to handle non-major version upgrades as well.

And if that's not possible, we should have some documentation to troubleshoot upgrade issues like this on the Wiki or somewhere else.

**Comment by rtibbles** [comment]
This was fixed by #8023 - static files no longer need to be copied.
