### ISSUE TITLE
create a reusable 'New' badge component

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7386]
### Observed behavior

as of https://github.com/learningequality/kolibri/pull/7368 the 'New' label is used in 3 places, with duplicated styling and strings:

> ![image](https://user-images.githubusercontent.com/2367265/88438741-44349b00-cdbe-11ea-8a83-293d6b72583c.png)

### Expected behavior

badge should be be a re-usable core component

### Context

0.14.0

**Comment by YashJipkate** [comment]
Hi @indirectlylit @jonboiser I want to work on this and have made a [PR](https://github.com/learningequality/kolibri/pull/7865) regarding this. Please take a look.
Thanks!

**Comment by indirectlylit** [comment]
thanks @YashJipkate!
