### ISSUE TITLE
Vue2 Manage edit user error

### ISSUE THREAD

**Issue by 66eli77** [learningequality/kolibri#739]
## Summary

branch: vue2
browser: chrome

## How to reproduce

1. login as admin
1. go to manage page
1. click edit icon on one of the users

## Screenshots
![screen shot 2016-12-21 at 1 35 11 pm](https://cloud.githubusercontent.com/assets/5577205/21406878/9617c654-c782-11e6-8f61-478443054667.png)

**Comment by DXCanas** [comment]
This should be taken care of in my PR https://github.com/learningequality/kolibri/pull/721
