### ISSUE TITLE
EPUB content not properly displayed on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7390]
### Observed behavior
EPUB content not properly display on IE11 after I upgraded from Kolibri 0.12.9 to 0.14.0-beta12

This is the EPUB display on IE11
![Screen Shot 2020-07-27 at 8 20 30 PM](https://user-images.githubusercontent.com/8663934/88541642-b4098680-d047-11ea-92c2-bc7c9db34385.png)

and this is on Chrome
![Screen Shot 2020-07-27 at 8 22 05 PM](https://user-images.githubusercontent.com/8663934/88541701-cb487400-d047-11ea-8378-2ae653cf8fc3.png)

and this is on Firefox display
![Screen Shot 2020-07-27 at 8 16 30 PM](https://user-images.githubusercontent.com/8663934/88541800-f03ce700-d047-11ea-9e36-cdf7795017a2.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce
* Install the 0.12.9 and download an EPUB content (I'm using this channel token `nakav-mafak` to import the EPUB content)  
* Upgrade the installed Kolibri to 0.14.0-beta12 
* Load an EPUB content on IE11 browser
* Compare the same EPUB content on other browsers.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0-beta12
 * Operating system: Windows 7
 * Browser: IE11

**Comment by pcenov** [comment]
@radinamatic this one is not extant in 0.15.1:
![2022-03-15_13-59-41](https://user-images.githubusercontent.com/79847249/158373402-b88355d4-c16c-4d1f-bdb9-35d85eab0494.png)

**Comment by rtibbles** [comment]
Closing as fixed.
