### ISSUE TITLE
Can't play audio content on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7395]
### Observed behavior
Audio content not working on IE11. But I tested the same content on Chrome and FF the Audio file can play there properly.

This is the Audio content Display on IE11 that's not working
![Screen Shot 2020-07-28 at 8 13 11 PM](https://user-images.githubusercontent.com/8663934/88664560-d1098c80-d10f-11ea-8937-405d39d8f82c.png)

And this is on Chrome and Firefox the same Audio file is working.
![Screen Shot 2020-07-28 at 8 14 37 PM](https://user-images.githubusercontent.com/8663934/88664642-f39ba580-d10f-11ea-89a2-948f60726012.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce
* Assuming that kolibri 0.14.0-beta12 is installed and running
* Import Audio content in this channel token `nakav-mafak`
* Load an Audio file on IE11.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.0-beta12
 * Operating system: Windows 7
 * Browser: IE11

**Comment by bjester** [comment]
I wasn't able to reproduce this exactly, but I may have found the issue. When using the IE11-Windows7 [Windows Virtual Machine image](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/), the sound card isn't functional when imported into Virtualbox. In this case, opening the Device Manager, you would see:
![Screenshot from 2021-03-30 15-24-28](https://user-images.githubusercontent.com/819838/113065689-2221c280-916e-11eb-95af-fac1813de609.png)
Also, in the system tray, the sound control has a red X circle indicating an issue with the sound device. If you click it, it will launch troubleshooting which will fail to resolve the issue:
![Screenshot from 2021-03-30 15-23-57](https://user-images.githubusercontent.com/819838/113065854-601ee680-916e-11eb-8903-76f01ce0e2ba.png)
Noting that it is easy to confuse that with the audio being muted, which uses a different icon:
![Screenshot from 2021-03-30 15-42-24](https://user-images.githubusercontent.com/819838/113066003-9a888380-916e-11eb-93f9-844b886cf097.png)
To enable sound in the Windows VM, you must download the [Realtek AC97 driver](https://www.realtek.com/en/component/zoo/category/pc-audio-codecs-ac-97-audio-codecs-software) and install it. When downloading, while it says it will send an email with the download link, it will actually prompt to download it on the next step after a CAPTCHA. So simply enter a reasonable fake email address to continue through it. Once you have installed the driver and restarted the VM, you should see the following in the Device Manager:
![Screenshot from 2021-03-30 15-28-02](https://user-images.githubusercontent.com/819838/113066187-f6eba300-916e-11eb-8aa0-79b7ad086723.png)
Success! You should now have working audio to test media within IE11!

**Comment by radinamatic** [comment]
Issue reporter must have been eager to use their own VM, as the Windows 7 ready-made VM hard drive, available to use and regularly updated on our shared Google drive, already has the correct audio drivers necessary, and the IE11 plays sound without issues 🙂
