### ISSUE TITLE
Exit link at Select Content Page should be different if arriving from the New Channel Version Page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7397]
In #7387, we redirect users to the Select Content (from Studio) Page (SCP) after the user confirms they want to update a channel.

With this new navigation, the immersive toolbar's back button at the SCP (possibly unexpectedly) goes to Available Channels Page after use is redirected there.

Steps to reproduce:

1. click "update" button on new version page
1. get redirected to the "Select content page" for the channel
1. click immersive "<-" button 
1. get sent to do Kolibri Studio available channels page. (Expected behavior: ?)

Rel #6468

_Originally posted by @jonboiser in https://github.com/learningequality/kolibri/pull/7387#issuecomment-663755775_

**Comment by metodimilevqa** [comment]
What exactly is the expected behavior? The one described in pt. 4 above (original post) or something else? We need this in order to verify the fix.
