### ISSUE TITLE
Possible mismatch between "mastery criteria" for Learner and "completion requirement" in Coach Page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7400]
### Observed behavior

This is from a pretty standard lesson with a KA exercise. As a learner, I see that the "mastery criteria" is get 5 of 7 correct:

![image](https://user-images.githubusercontent.com/10248067/88715345-a816d680-d0d2-11ea-95df-0809da4a05c3.png)

But on the coach report for this page, I see something different in the "completion requirement"

![image](https://user-images.githubusercontent.com/10248067/88715579-b95fe300-d0d2-11ea-9eb3-522eef858735.png)

### Expected behavior

If "completion requirement" and "mastery criteria" are the same, I would expect the two too match on these two screens. If they're not, then some explanation of the difference would be helpful.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Create a lesson with a KA exercise
1. View it as a learner (see e.g. "4 of 5" requirement)
1. View it as a coach (see the "get one right" requirement)

### Context

Kolibri 0.14.0b13

**Comment by radinamatic** [comment]
Ugh, confusing... :disappointed:
