### ISSUE TITLE
500 error when trying to edit details or copy the lesson, a.k.a. 'adhoclearnersgroup' woes 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7404]
### Observed behavior

Seems impossible to edit lesson details or copy it elsewhere. All resources are present on the facility, and the lesson is assigned to entire class.

### Expected behavior
Ability to edit & copy the lesson.

### User-facing consequences
Troubled coach.

### Errors and logs

```
Uncaught (in promise) Error: Request failed with status code 500
    createError createError.js:16
    settle settle.js:17
    handleLoad xhr.js:61
```

![LEDev20 04 (start)  Running  - Oracle VM VirtualBox_894](https://user-images.githubusercontent.com/1457929/88753799-7dbe2b00-d15d-11ea-80c2-2ac11464f02a.png)

#### Logs

[debug-last-day.zip](https://github.com/learningequality/kolibri/files/4992420/debug-last-day.zip)
[kolibri.zip](https://github.com/learningequality/kolibri/files/4992421/kolibri.zip)

### Steps to reproduce

Same 500 error in both cases:

- Open an existing lesson in the Plan tab
- Click to open the *Options* and select *Edit details*

OR

- Select *Copy* and try to copy the lesson in another class

### Context
 * Kolibri version: current 0.14.x release branch 
 * Operating system: Ubuntu 18.04
 * Browser: Firefox

cc @rtibbles

**Comment by radinamatic** [comment]
Can't create a group either, dev env seems not to be a good place to grab the latest screenshots :disappointed: 

![Selection_896](https://user-images.githubusercontent.com/1457929/88755132-aeec2a80-d160-11ea-8073-78b93238faa7.png)

**Comment by rtibbles** [comment]
In examining the database that produced this error, what appears to have happened is that the `tree_id` value of the Facility object in question has been set to `3`, while the `tree_id` value of all its descendant collections is set to `1`.

I am not entirely sure what would have caused this, but this database has engaged in syncing, which seems like the likeliest candidate.

**Comment by jamalex** [comment]
I played with this database a bit and then tried to replicate this with a variety of syncing scenarios, and couldn't. I think it may have been the result of an earlier beta before some additional fixes went in on top of some morango changes. In order to repair this database for further use, you should be able to do:
```echo "from kolibri.core.auth.models import Collection; Collection.objects.rebuild()" | KOLIBRI_HOME=/home/jamalex/Downloads/test kolibri shell``` (or if on Windows, get into `kolibri shell` and then run that line of code inside the quotes)

**Comment by radinamatic** [comment]
@jamalex This was not the DB from an installed beta, but running on my own development server. I have several VMs used in testing between which I run import & sync scenarios, and this particular facility (_DistrictSchool16_) was most probably created from scratch on my dev machine, imported to several other VM devices, and later synced several times. 

Error was extant on the latest upstream from 0.14 branch all day today until Richard sent me the manually fixed DB.

**Comment by jamalex** [comment]
Right, what I meant was, I think the data corruption seems likely to have happened in an older beta. The new beta won't itself fix the data that's already corrupted, but hopefully this type of corruption wouldn't newly occur within the latest beta.

**Comment by radinamatic** [comment]
> what I meant was, I think the data corruption seems likely to have happened in an older beta.

Gotcha, thanks for clarifying! :crossed_fingers: 

I'll reopen if I manage to step into this mudhole again :stuck_out_tongue:
