### ISSUE TITLE
Import facility not working through setup wizard

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7410]
### Observed behavior

Tried importing facility from an existing one using the setup wizard on a new 0.14b14 setup.

Front end shows an invalid credentials error as below but that is not correct as have reverified the credentials and have tried both of super admin as well as facility admin.

![Screenshot_2020-07-29 Setup Wizard](https://user-images.githubusercontent.com/2577060/88769956-b9c3b100-d19a-11ea-882a-d55a4d4201ec.png)

Logs have this error -

```
INFO 2020-07-29 12:22:57,685 cherrypy.access 127.0.0.1 - - "GET /api/discovery/dynamicnetworklocation/" 200 0 "http://localhost:8080/en/setup_wizard/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
INFO 2020-07-29 12:22:57,712 kolibri.core.discovery.utils.network.client Attempting connection to: http://con.myscoolserver.in/
INFO 2020-07-29 12:22:58,365 kolibri.core.discovery.utils.network.client Success! We connected to: http://con.myscoolserver.in/api/public/info/
INFO 2020-07-29 12:22:58,379 cherrypy.access 127.0.0.1 - - "GET /api/discovery/staticnetworklocation/" 200 0 "http://localhost:8080/en/setup_wizard/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
INFO 2020-07-29 12:23:00,490 cherrypy.access 127.0.0.1 - - "GET /api/discovery/networklocation_facilities/82036dcd-a659-45b0-817d-913046512f95/" 200 0 "http://localhost:8080/en/setup_wizard/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
INFO 2020-07-29 12:23:25,314 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://con.myscoolserver.in/
INFO 2020-07-29 12:23:25,315 kolibri.core.discovery.utils.network.client Attempting connection to: http://con.myscoolserver.in:8080/
INFO 2020-07-29 12:23:30,681 kolibri.core.discovery.utils.network.client Unable to connect: HTTPConnectionPool(host='con.myscoolserver.in', port=8080): Max retries exceeded with url: /api/public/info/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3c89a62a30>, 'Connection to con.myscoolserver.in timed out. (connect timeout=5)'))
INFO 2020-07-29 12:23:30,683 kolibri.core.discovery.utils.network.client Attempting connection to: http://con.myscoolserver.in/
INFO 2020-07-29 12:23:31,383 kolibri.core.discovery.utils.network.client Success! We connected to: http://con.myscoolserver.in/api/public/info/
ERROR 2020-07-29 12:23:32,006 django.request Internal Server Error: /api/tasks/facilitytasks/startpeerfacilityimport/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Certificate' object has no attribute '_scope_definition_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3/dist-packages/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "./kolibri/core/tasks/api.py", line 882, in startpeerfacilityimport
    job_data = validate_and_prepare_peer_sync_job(
  File "./kolibri/core/tasks/api.py", line 1054, in validate_and_prepare_peer_sync_job
    get_client_and_server_certs(
  File "./kolibri/core/auth/management/utils.py", line 195, in get_client_and_server_certs
    client_cert = nc.certificate_signing_request(
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 258, in certificate_signing_request
    Certificate.save_certificate_chain(
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 227, in save_certificate_chain
    cert.check_certificate()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 168, in check_certificate
    scope = self.get_scope()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 244, in get_scope
    return self.scope_definition.get_scope(self.scope_params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 378, in get
    raise self.model.DoesNotExist(
morango.models.certificates.DoesNotExist: ScopeDefinition matching query does not exist.
INFO 2020-07-29 12:23:32,125 cherrypy.access 127.0.0.1 - - "POST /api/tasks/facilitytasks/startpeerfacilityimport/" 500 0 "http://localhost:8080/en/setup_wizard/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
```

However, importing another facility works once a new facility has been created via web or cli's `provisiondevice`

### Expected behavior

Import of chosen facility should have worked.

### User-facing consequences

Can't use Kolibri in an "Advanced", formal learning setup without creating a "native" facility in a device.

### Errors and logs

Error spotted in logs/kolibri.txt shared above.

### Steps to reproduce

1. Install kolibri 14.b14
2. Follow the Setup wizard and choose "Advanced.." facility option and thereafter try to import and facility instead of creating a new one.

### Context

Kolibri 0.14b14 deb
Kolibri server 0.3.8b2
Ubuntu 20.04
Firefox

**Comment by jonboiser** [comment]
@bjester Could you take a look at this? These lines in the logs stand out to me

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 178, in __get__
    rel_obj = getattr(instance, self.cache_name)
AttributeError: 'Certificate' object has no attribute '_scope_definition_cache'

...

  File "./kolibri/core/tasks/api.py", line 882, in startpeerfacilityimport
    job_data = validate_and_prepare_peer_sync_job(
  File "./kolibri/core/tasks/api.py", line 1054, in validate_and_prepare_peer_sync_job
    get_client_and_server_certs(
  File "./kolibri/core/auth/management/utils.py", line 195, in get_client_and_server_certs
    client_cert = nc.certificate_signing_request(
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 258, in certificate_signing_request
    Certificate.save_certificate_chain(
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 227, in save_certificate_chain
    cert.check_certificate()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 168, in check_certificate
    scope = self.get_scope()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models/certificates.py", line 244, in get_scope
    return self.scope_definition.get_scope(self.scope_params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 184, in __get__
    rel_obj = self.get_object(instance)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/fields/related_descriptors.py", line 159, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 378, in get
    raise self.model.DoesNotExist(
morango.models.certificates.DoesNotExist: ScopeDefinition matching query does not exist.
```

**Comment by jonboiser** [comment]
I also came across this issue, but my situation might have been a little different. I think what I did was first `kolibri manage deprovision` my server and try to re-import a facility I had before i deprovisioned. I assumed that the auth failure was because I had some residual data in my server, so deleted my `KOLIBRI_HOME` folder and was able to do the Setup Wizard without problems.

I don't think I saw the same errors in my terminal though. I think it was just a straightforward 40x response from the endpoint.

**Comment by jamalex** [comment]
- It looks as if the `ScopeDefinition` fixtures have not yet been loaded by this point.
- There are two places the loading of them gets triggered:
    1. [When the `sync` management command is run](https://github.com/learningequality/kolibri/blob/99058836c797184086596794497814e166499c9e/kolibri/core/auth/management/commands/sync.py#L108)
    2. When the [database is auto-migrated](https://github.com/learningequality/kolibri/blob/30885472fc35d4306791eb2ed896a08b7de73168/kolibri/utils/cli.py#L190), either on [first run](https://github.com/learningequality/kolibri/blob/30885472fc35d4306791eb2ed896a08b7de73168/kolibri/utils/cli.py#L400) or on an [update](https://github.com/learningequality/kolibri/blob/30885472fc35d4306791eb2ed896a08b7de73168/kolibri/utils/cli.py#L439)
- It appears the setupwizard doesn't call the `sync` command, and instead does its own thing (not sure why it couldn't just use the sync command)
- Hence, it relies on this happening during the migration. However, the "migrate on first run" is _only triggered if the database wasn't already migrated manually_ (when [`DatabaseNotMigrated` is raised](https://github.com/learningequality/kolibri/blob/30885472fc35d4306791eb2ed896a08b7de73168/kolibri/utils/cli.py#L398)).
- So, my guess is that in this case, something like `kolibri manage migrate` was run before starting the server. Actually, no, I just tested that, and it still passes through the "initialize" step and migrates the database through our internal function before even running the actual Django management command, so the fixtures still get loaded.
- My next thought was that maybe that table gets emptied when you run `deprovision`. But it doesn't.
- My only remaining idea is that all the data may have been manually dropped (using external tools) from the local database, and then the database was reused. Is something like that possible, @intelliant01? Or could you tell us more about the provenance of the database that the local server was being started with?

**Comment by jonboiser** [comment]
In the Setup Wizard, we do call the `sync` command via the `/api/tasks/startpeerfacilityimport` endpoint, but with an extra `--no-provision` flag to delay provisioning until the full setup is done.

https://github.com/learningequality/kolibri/blob/594f2f81cc67f1d79cc0480125b496a6265d5a2f/kolibri/core/tasks/api.py#L877-L893

**Comment by jamalex** [comment]
Ah, ok -- but the error is being raised in `validate_and_prepare_peer_sync_job`, which happens before that (but relies on the fixtures having been loaded). Perhaps, as an extra safeguard, we should run the fixture loading in `validate_and_prepare_peer_sync_job` as well.

**Comment by jonboiser** [comment]
So we do the authentication first because it a requirement for us because we wanted this endpoint to fail immediately with a 40x error instead of successfully create queue the `sync` call and wait for it to fail.

So yeah we should add whatever we need to `validate_and_prepare_peer_sync_job` to do the same preparation as we would by running `sync` on the terminal.

**Comment by jamalex** [comment]
Sounds good. Should be enough to add:
`call_command("loaddata", "scopedefinitions")`
at the start of that function, before you start calling morango APIs.

**Comment by intelliant01** [comment]
> My only remaining idea is that all the data may have been manually dropped (using external tools) from the local database, and then the database was reused.

@jamalex the client device into which the import is being attempted is a pristine Postgres db initialised using `kokibri manage migrate --skip-update`. 
The source server from which the facility is being imported has a Sqlite to Postgres migrated db.

**Comment by jamalex** [comment]
Ah, it's probably the --skip-update that prevented the fixtures from being
loaded during the run of the migrate command.

**Comment by intelliant01** [comment]
Verified. `--skip-update` is the problem. Works fine when it is not used.

Apologies as was not aware of its implications. Please guide me to some documentation about the same as it is not available via `kolibri manage help migrate`.

**Comment by jamalex** [comment]
This should be fixed by https://github.com/learningequality/kolibri/pull/7414 (which adds extra safeguards for handling special cases like this).

The `--skip-update` option isn't specific to `migrate`, it's a [Kolibri CLI option](https://github.com/learningequality/kolibri/blob/30885472fc35d4306791eb2ed896a08b7de73168/kolibri/utils/cli.py#L155). It's not documented because it wouldn't typically be relevant to end users.

**Comment by intelliant01** [comment]
Thanks @jamalex for the clarity.
