### ISSUE TITLE
Sync status as 'Never synced' on Linux

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7415]
### Observed behavior

The sync status is always `Never synced` on Linux systems whereas it shows the correct status on Windows.

![sync_status](https://user-images.githubusercontent.com/2577060/89064334-71b5b180-d387-11ea-9df9-75cbaa6c7775.gif)

### Expected behavior

Correct sync status should be visible as it is on Windows -

![image](https://user-images.githubusercontent.com/2577060/89064522-c48f6900-d387-11ea-8984-b875df9503c4.png)

### User-facing consequences

Confusion and misinformation.

### Errors and logs

No errors visible in logs.

However, I do notice this every time I start Kolibri -
```
Jul 31 23:51:24 myscoolserver kolibri-server[18533]: /usr/lib/python3/dist-packages/kolibri/dist/tzlocal/unix.py:108: SyntaxWarning: "is not" with a literal. Did you mean "!="?
Jul 31 23:51:24 myscoolserver kolibri-server[18533]:   while start is not 0:
Jul 31 23:51:25 myscoolserver kolibri-server[18533]: /usr/lib/python3/dist-packages/kolibri/dist/rest_framework/utils/serializer_helpers.py:107: SyntaxWarning: "is" with a literal. Did you mean "=="?
Jul 31 23:51:25 myscoolserver kolibri-server[18533]:   if value is None or value is '':
```

Not sure if this may be related.

Not sure if this could be related.

### Steps to reproduce

Initiate a sync from Linux based Kolibri installation.

### Context

Linux based installations :
```
Version:           0.14.0b15
OS:                Linux-5.4.0-42-generic-x86_64-with-glibc2.29
Python:            3.8.2
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            nginx/1.18.0 (Ubuntu)
Database:          postgresql
```

```
Version:           0.14.0b15
OS:                Linux-5.4.0-1015-raspi-aarch64-with-glibc2.29
Python:            3.8.2
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            nginx/1.18.0 (Ubuntu)
Database:          postgresql
```

Windows : 

```
Version:           0.14.0b15
OS:                Windows-10-10.0.18362-SP0
Python:            3.6.8
Installer:         Windows
Server:            Kolibri internal server
Database:          C:\Users\SHRENIK BHURA\.kolibri\db.sqlite3
```

**Comment by jonboiser** [comment]
This is a guess, but the errors in Linux related to the `tzlocal/unix.py` library might be related to the incorrect syncing information, since the `last_synced` field on `FacilityViewset` (which underlies the data on these screenshots) depends on interpreting and sorting by DateTimes

https://github.com/learningequality/kolibri/blob/5cd3b24230c6a360e96fd0faed19f108c9faf83e/kolibri/core/auth/api.py#L357-L365

**Comment by jredrejo** [comment]
Solved with #7428

**Comment by intelliant01** [comment]
@jredrejo Upgraded to 0.14.0b16 but the status displayed is still 'Never sycned'. 

What do I need to do different to test this reliably or what further information I may furnish to help replicate this at your end?

**Comment by jredrejo** [comment]
Can you give exact instructions to reproduce it?
i.e. what are the steps you doing in both servers and versions you have on them?

**Comment by intelliant01** [comment]
1. Login as superuser
2. Navigate to `Devices` -> `Facilities`
3. Execute `Sync` for any facility added therein
4. Sync completes and shows when clicked on `View Task Manager` but below the facility name it always shows as `Never synced` (as given in the gif above)

**Comment by intelliant01** [comment]
@jredrejo forgot to mention that kolibri version on both source and destination devices is now 0.14.0b16.

**Comment by intelliant01** [comment]
@jredrejo The status is working correctly for systems updated from 0.13.3 to 0.14.0 and now even to 0.14.1.

But it is still broken on 3 systems which had this upgrade path - 0.13.3 to 0.14.b{14,15,16,rc1} to 0.14.0 and 0.14.1.

What could we try to remove / change to get it working on the later systems?

**Comment by cyberorg** [comment]
This has nothing to do with upgrade path. This happens on fresh install using **postgres database**. Shows correct status when sqlite is used.

**Comment by jredrejo** [comment]
@intelliant01 I'm trying to reproduce this issue without success. I have tried the upgrade path you mentioned above and it works for me in Linux (I have even tested kolibri in one machine against kolibri-server in the other).
Could the problem be related to postgres as @cyberorg mentioned or are you still to reproduce it in sqlite?

**Comment by intelliant01** [comment]
It is related to a fresh install on Postgres. Sorry, Cyberorg is my teammate, hence I did not reconfirm on his comment.
