### ISSUE TITLE
unclear how to reset channel data cache

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7417]
### Observed behavior

I tried manually editing channel title.

Now I'm getting two different values, and can't get the new title to appear on the Learn page:

![2020-07-31 17 07 18](https://user-images.githubusercontent.com/2367265/89089270-59c33b00-d351-11ea-90ba-1aa90dcb5b64.gif)

As far as I can tell, the response from the `/contentnode/?ids=` is returning the old version of the data.

* tried resetting `contentCacheKey`
* tried restarting django

Also noticed that on the client-side `setChannelInfo` has the correct title but `setAndCheckChannels` does not.

### Expected behavior

Consistent data, or easier-to-understand behavior

### User-facing consequences

Not sure if there are any because I am modifying my own DB, but I am struggling over here on the dev side

### Steps to reproduce

* edit channel metadata manually
* reload

### Context

0.14.0 beta 14

**Comment by rtibbles** [comment]
Resetting the content cache key should do this, and now that it is using the disk cache, this should be sufficient.
