### ISSUE TITLE
facility user list: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7419]
### Observed behavior

facility page is stuck here:

![image](https://user-images.githubusercontent.com/2367265/89093285-cb10e700-d36d-11ea-9a2d-701439d957be.png)

### Errors and logs

```
UserType.js:12 Uncaught (in promise) TypeError: Cannot read property 'kind' of undefined
    at UserType (UserType.js:12)
    at _userState (mappers.js:16)
    at Array.map (<anonymous>)
    at handlers.js:17
    at conditionalPromise.js:36
```

### Steps to reproduce

Unknown but I can repro locally. See me for the details

### Context

0.14.0 beta 14

**Comment by jonboiser** [comment]
Did you import these users from somewhere via p2p-sync?

The code here makes a big assumption that if a `FacilityUser` is not a superuser or a learner, then they definitely have some kind of `Role` object for their facility (e.g. Admin or Coach role).

So it might be that the user has roles for a facility that is not the one they were created in (which should be impossible in a single-facility situation).

https://github.com/learningequality/kolibri/blob/4d5daad9ec22ec77cc7ad1a3a84e872c705c0688/kolibri/core/assets/src/utils/UserType.js#L11-L13

**Comment by rtibbles** [comment]
This could also happen if someone was assigned a coach role for a class, but did not have a 'assignable coach' role for the facility - not possible to make this through the UI, but the backend would allow this to happen.

**Comment by rtibbles** [comment]
> So it might be that the user has roles for a facility that is not the one they were created in (which should be impossible in a single-facility situation).

The backend *should* disallow this, but I'm also not entirely certain that the API would prevent it.

**Comment by jonboiser** [comment]
I'm not sure, but I think the only reason this code is run is to show the role "badge" on the Facility User page. So if we can just add some handling to prevent the unhandled `.kind is undefined` error on line 12, and also specifically handle the "coach in class, but not in facility" edge case, that would be enough to fix this issue.

If there are other smaller bugs that result from this, it's at least better than having the whole page crash.
