### ISSUE TITLE
Provide an alternative design for Assessments with very "high" mastery requirements

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7436]
### Observed behavior

Here's an assessment with a pretty high mastery requirement of 31 correct answers

![image](https://user-images.githubusercontent.com/10248067/89341379-0f460500-d656-11ea-8c19-6d435812c92a.png)

This comes from the "Baseline 2017 - 18" channel 

### Expected behavior

I think if the requirement is this high, we should use an alternative design because it's unlikely that all of these "___" placeholders will fit across the screen.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Note that this would also apply on narrower form factors.

**Comment by khangmach** [comment]
Addressed with upcoming 0.15 content renderer updates

**Comment by sairina** [comment]
The design is complete, and that design is listed under the first bullet point under **Core exercise (now 'practice') exclusive changes** [here](https://app.zenhub.com/workspaces/kolibri-ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/7873), which is also linked as having github issues created.
