### ISSUE TITLE
filters in lesson management have layout regressions

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7437]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/89346293-a793b800-d65d-11ea-8da6-533e2d007ab7.png)

![image](https://user-images.githubusercontent.com/2367265/89346756-6f40a980-d65e-11ea-828d-7259cea716b8.png)

### Context

0.14.0 beta 14

**Comment by jonboiser** [comment]
I'm not seeing the overflow with the magnifier class icon inside the SearchBox.

As for the KIcons next to the UiSelects, it should be enough to add 16px `margin-bottom` to match the margins of the UiSelect itself.

![image](https://user-images.githubusercontent.com/10248067/89349455-0e67a000-d663-11ea-8e35-0ec4520bcadc.png)

**Comment by indirectlylit** [comment]
will do

**Comment by jonboiser** [comment]
Things don't overflow for me in Chrome, but it does seem the sub-components of the searchbar are a little "cramped". The text input and "X (clear)" button actually overlap a little.

![image](https://user-images.githubusercontent.com/10248067/89350990-efb6d880-d665-11ea-953a-d28a67ea12a7.png)
