### ISSUE TITLE
searchTerm prop is undefined in lesson management search

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7439]
### Observed behavior

Seeing an error when searching. Occasionally this also seems to prevent the page from loading, but having trouble reproducing that.

![2020-08-04 15 23 47](https://user-images.githubusercontent.com/2367265/89352762-c304c000-d669-11ea-9804-d14db482fc52.gif)

### Expected behavior

No prop validation errors

### User-facing consequences

Occasionally might break search

### Errors and logs

![image](https://user-images.githubusercontent.com/2367265/89352801-e465ac00-d669-11ea-8bd8-662d349e7326.png)

### Steps to reproduce

search while creating a lesson or quiz

### Context

0.14.0 beta 15

**Comment by alexMet** [comment]
There is another bug, when you hit enter with the same search term. A redundant redirect happens.

![simplescreenrecorder](https://user-images.githubusercontent.com/3750511/95655664-95c50a00-0b11-11eb-9636-e73ae4b56cca.gif)

The above pull request fixes that also.
