### ISSUE TITLE
Tooltip gets clipped, causes flickering scroll behavior

### ISSUE THREAD

**Issue by micahscopes** [learningequality/kolibri#7441]
This is a followup issue on #7431.  The relevant code is [here](https://github.com/learningequality/kolibri/pull/7431/files#diff-c2f06cb7c0ab507378457858b8085daaR15-R40).

### Observed behavior
When editing a quiz ("coach --> plan --> quizzes --> <quiz>") with missing content in a narrow window, the missing content icon appears on a new line, causing a vertical scrollbar to appear.

The tooltip sometimes gets clipped, and hovering over the missing content icon results in strange flickering.

### Expected behavior
The missing content icon (":warning:") should not break to a new line;  The tooltip should not clip and there should be no scrollbar and no flickering.

### User-facing consequences
It's distracting and potentially jarring or worrisome (":warning:") for anyone trying to figure out what's going on.

![fluttering tooltip](https://user-images.githubusercontent.com/389782/89355325-b63f9680-d680-11ea-99b9-4fc78306f362.gif)

### Steps to reproduce
1. Import a facility with a classroom+quiz to a blank Kolibri instance with no content data.
2. Edit the quiz ("coach --> plan --> quizzes --> <quiz>")
3. Make the browser window narrow until one of the ":warning:" icons breaks to a new line
4. Hover over the icon

### Context
This happened with Kolibri 0.14beta15 with #7431 applied.  As soon as that PR is merged, you should be able to reproduce this on the `release-v0.14.x` branch

It happens both on Firefox and Chromium

**Comment by nucleogenesis** [comment]
The newline break may be either caused or fixed by using a KLabledIcon with the `iconAfter` prop. If the wrapping component has a width set on it, a KLabeledIcon would fill the space

https://github.com/learningequality/kolibri-design-system/blob/704fbb08002771856f64360164469267bf3405ed/lib/KLabeledIcon.vue#L21

**Comment by indirectlylit** [comment]
the clipping and scrollbar might be addressed by adding `overflow: visible` to the container

**Comment by micahscopes** [comment]
> The newline break may be either caused or fixed by using a KLabledIcon with the `iconAfter` prop. If the wrapping component has a width set on it, a KLabeledIcon would fill the space

Thanks for the tip!  Using `KLabeledIcon` does indeed help with the wrapping issue, but there's another issue when the width of the inner label text is larger than the width of the `KLabeledIcon` component's wrapper `span`:

![image](https://user-images.githubusercontent.com/389782/89586027-8de0a500-d804-11ea-9538-857e3e79a497.png)

I will make a fix for this in `kolibri-design-system`.

**Comment by micahscopes** [comment]
I didn't end up getting to this.  Letting it go for now!

**Comment by pcenov** [comment]
@radinamatic this one is not extant in 0.15.1. The tooltip is displayed correctly without causing any issues.

**Comment by rtibbles** [comment]
Super! Closing.
