### ISSUE TITLE
Adjust the double-click blocking time to make it a little less noticeable

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7444]
### Observed behavior

The fix for #3914 adds a perceivable delay on the Learn page between when the page loads (for fast connections at least) and when the user can interact with things.

While it was meant to prevent double-clicking the same space held by a content card in the the Channels navigation flow, this delay applies globally, e.g. clicking the navigation tabs and other links.

### Expected behavior

Personally, I would prefer to not have this delay at all, but if we need to keep it, I would like to have the double-click blocking last for a shorter duration and to be limited only to the area of the content cards.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by marcellamaki** [comment]
Closed with #11719
