### ISSUE TITLE
In `LearnerClassEnrollmentPage` and `CoachClassAssignmentPage`, place "Confirm" button in fixed bottom bar

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7456]
### Observed behavior

"Confirm" button in the learner/coach enrollment pages is at the bottom of the table.

![image](https://user-images.githubusercontent.com/10248067/89688503-29cae900-d8b7-11ea-9c44-167506db7d90.png)

### Expected behavior

See annotations in screenshot

To save users from having to scroll down for the confirm button, place the "Confirm" button in a fixed bottom bar. And also add a message like "5 selected" that is maintained even wile users page through the lists.

Example from channel management workflow:

![Screen Shot 2020-08-07 at 2 02 43 PM](https://user-images.githubusercontent.com/10248067/89688749-b4134d00-d8b7-11ea-8458-d2cf817afd0c.png)

### User-facing consequences

Saves users from having to scroll down for "Confirm" button

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
Yes, please! :100: :heavy_plus_sign:
