### ISSUE TITLE
App bar has no title when on Profile Edit page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7457]
### Observed behavior

There's nothing here in the top-left corner when viewing your own profile.

![image](https://user-images.githubusercontent.com/10248067/89689087-782cb780-d8b8-11ea-9eb2-dd42fd4814d4.png)

### Expected behavior

That there's a useful label in the top-left.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

0.14 (screenshot from kolibri-beta server)

**Comment by jonboiser** [comment]
@jtamiace Any suggestions for what should go there? Maybe just "Profile"?

**Comment by jtamiace** [comment]
Yeah, "Profile" seems right

**Comment by shivangtripathi** [comment]
@jonboiser I would like to work on this issue please assign it to me. Any guidance or tips are highly welcomed !
