### ISSUE TITLE
Classroom notifications are not imported/synced with Classroom via morango

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7458]
### Observed behavior

As reported in #7445, Classroom Activity (which is stored in a separate Database for Notifications) does not get synced along with Lessons and Quizzes, etc. using the 0.14.0 facility sync functionality.

### Expected behavior

That, with caveats for missing resources, that p2p sync also replicates Classroom activity on a device after it imports Facility data.

@jamalex Says that this would involve explicitly adding morango-specific fields to the notifications model.

### User-facing consequences

The expectation that Facility sync also replicates the Coach experience is broken if these notifications/activity are not also synced.

### Errors and logs

…

### Steps to reproduce

…

### Context
0.14

**Comment by intelliant01** [comment]
@jonboiser I don't see any great value and use of syncing real time classroom activity notifications. IMO, this may be considered for implementation only if real-world coaches express such a need in a p2p sync scenario.

**Comment by jamalex** [comment]
Once take-home tablets are used in a classroom environment (syncing to the classroom server every few minutes), this would become more important. An alternative (that would reduce the syncing bloat) would be to generate them post-sync based on data that is synced in.

**Comment by intelliant01** [comment]
In scenarios that we have i.e. a sync at most once a day, we don't see much utility of real time or near real time data as teachers are also not going to be online simultaneously. 
But yes analytics derived from the same could be very useful.
So as @jamalex states, deriving them post-sync, if possible, should be the way to go.
Additionally this could be governed by a configurable switch, once again, to limit the sync bloat. Those who see utility in the same, could turn it on.

**Comment by rtibbles** [comment]
Fixed in #8188
