### ISSUE TITLE
issue with latest windows installer v1.4.0

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7460]
### Observed behavior

observed by @jayoshih when trying to install any version from `0.14.0-beta3` onward:

> ![image](https://user-images.githubusercontent.com/2367265/89697480-19c00300-d8d1-11ea-8885-0f3c4b161648.png)

The main Windows change that happened between `0.14.0-beta2` and `0.14.0-beta3` was https://github.com/learningequality/kolibri/pull/7045, where we updated the Windows version from `v1.3.6` to `v1.4.0-beta1`.

The most significant change was: https://github.com/learningequality/kolibri-installer-windows/commit/c50d3ef93fc82f1f6568edd580cb723d8d55c62d

Here, Python was upgraded from `3.4.3` to `3.6.8`.

No one else besides @jayoshih has observed this behavior, so we're speculating but haven't proven that it's somehow due to existing Python environments on her system from development work. @kollivier also speculated that there could be conflicts due to 32- and 64-bit Python installations going to the same directory and having their installed packages thrash each other.

### Expected behavior

All users should be able to install Kolibri on Windows

### User-facing consequences

Some users cannot install Kolibri

### Steps to reproduce

We might attempt creating a Windows VM that matches @jayoshih's environment

### Context

…

**Comment by rtibbles** [comment]
No replication, closing as stale.
