### ISSUE TITLE
Content channel tiles appearing as 2 across at 100% zoom

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#7462]
### Observed behavior
I am using Chrome at 100% view and I see two content channel tiles across on the Learn page. It goes to 3 tiles across at 90% In talking to other colleagues similarly at 100% with what I assume to be similar size monitors, they see three or four tiles across at 100% so there seems to be an inconsistency. I am using a 12.3 inch monitor. 

### Expected behavior
My assumption was that the tiles would be three tiles across.

### User-facing consequences
Given that this feature change is a result of user testing and an interest in enhanced usability and discoverability of content, it seems to me that some consistency (or at least a 'guaranteed' three tile across experience on a laptop or desktop) is preferable.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.14.
* Operating system: Chrome OS
 * Browser: Chrome

**Comment by indirectlylit** [comment]
having trouble reproducing - screenshots or pixel resolution of the screen would be helpful
