### ISSUE TITLE
Circularity: kolibri.utils cannot depend on outside kolibri modules

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#747]
## Summary

https://github.com/learningequality/kolibri/commit/9770e883d2f5ae418900aafed65d5080f6812e6e introduces this line in `kolibri.utils.server`

     from kolibri.deployment.default.wsgi import application 

...then in `kolibri.utils.cli` we have this written twice:

     # import from server.py here to avoid circular imports caused by importing kolibri.deployment.default.wsgi
     from . import server

The actual problem is when `kolibri.utils.server` starts depending on an outside environment at load-time. This behavior should be reserved for very explicit use in runtime calls to `kolibri.utils.cli`.

At least the problem is solved by moving the wsgi import statement from loadtime to somewhere runtime.

@66eli77 assigning you because you're working on daemon mode right now :)

**Comment by 66eli77** [comment]
Isn't by placing `from . import server` inside a method of `cli.py` effectively it makes everything inside `server.py` executed at runtime(including `the wsgi import statement`)?

**Comment by 66eli77** [comment]
by load-time, do you mean compile time?

**Comment by benjaoming** [comment]
> Isn't by placing from . import server inside a method of cli.py effectively makes everything inside server.py executed at runtime(including the wsgi import statement)?

Yes, but when it can be avoided, it's not a nice pattern... it means "oops we have created a circular dependency in our modules" :)

compile-time is before load-time, but essentially it means the same... they're both before run-time. I think the (bytecode) compiler might be able to optimize things if it can resolve imports at module-level, but that's just some intuition.. I don't know the final answer to that.

**Comment by 66eli77** [comment]
looks like this anti-pattern is introduced by Cherrypy(http://docs.cherrypy.org/en/latest/advanced.html#id20). 
```
cherrypy.tree.graft(application, "/")
```
any ideas?

**Comment by benjaoming** [comment]
My idea: What you should do to fix this quickly is to move `from kolibri.deployment.default.wsgi import application` to the `run_server` scope. Thus, it won't be imported at load-time, which at least keeps the module structure, and then we don't have to put ` # import from server.py here to avoid circular imports caused by importing kolibri.deployment.default.wsgi` in files that have reverse dependencies.

**Comment by benjaoming** [comment]
Fixed in #895 :)
