### ISSUE TITLE
Links between SPA apps should not open a new tab

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7480]
### Observed behavior

| Navigate between facility and device settings pages | Explore without account |
|--|--|
| ![2020-08-17 17 45 32](https://user-images.githubusercontent.com/2367265/90458116-50a4ce80-e0b2-11ea-86d8-2aadc735e6df.gif) | ![2020-08-17 17 55 44](https://user-images.githubusercontent.com/2367265/90458321-f5271080-e0b2-11ea-9d9e-b00feec0b14e.gif) |

Related:

* https://kolibri-design-system.netlify.app/buttons/
* https://github.com/learningequality/kolibri-design-system/issues/82
* https://github.com/learningequality/kolibri-design-system/commit/29ba2b9781e37e8c10def63bcf84bff5a7244367

First noticed because in https://github.com/learningequality/kolibri-installer-gnome/issues/7 for the GTK/webkit Gnome app, special handling had to be added so that "external links" which were actually internal links would be opened in a webkit window.

### Expected behavior

From a user's perspective, the fact that different parts of Kolibri are implemented as separate SPAs is an implementation detail, not a feature. Navigating from one to the other should keep them in the same window.

* We should have a way of controlling whether or not links get opened in a new window
* Links that do get opened in a new window should include an icon, similar to that used in the design system: ![image](https://user-images.githubusercontent.com/2367265/90457379-3538c400-e0b0-11ea-9dd8-526833802052.png)
* We should audit use of `KExternalLink` and ensure that cross-SPA links do not open in a new window

### User-facing consequences

users are opening new tabs when they should be staying in the same tab 

### Steps to reproduce

Click 'explore without account'

### Context

0.14.1

**Comment by nucleogenesis** [comment]
> We should audit use of KExternalLink and ensure that cross-SPA links do not open in a new window

Bah I thought I did this :-(
