### ISSUE TITLE
Use of KExternalLink should never refer to Kolibri URLs, use KRouterLink

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7482]
### Observed behavior

The KDS `KExternalLink` component is supposed to be used for links outside of Kolibri. `KRouterLink` is supposed to link internally, even between SPAs.

Related to https://github.com/learningequality/kolibri/issues/7480 and the PRs/Issues that it refers to in the description.

### Expected behavior

`KExternalLink` opens in a new tab and never links within Kolibri and every time we want this in Kolibri, we use `KExternalLink`
`KRouterLink` opens in the same tab/window and always links within Kolibri and we use `KRouterLink` everywhere that we link to Kolibri.

**Comment by jonboiser** [comment]
So, to fix this we should look for anything like this in the code:

```
<template>
   <KExternalLink :href="someLink">Link</KExternalLink>
</template>
<script>
import urls from 'kolibri.urls'

// Some where in the module, we're referencing something in urls:

computed: {
    someLink() {
        return urls['some:key:for:something']();
    }}
}
</script>
```

And replace it the `KExternalLink` with a `KRouterLink` which also supports an `href` prop.

**Comment by jonboiser** [comment]
Here are some places I think this change needs to be made. These are all usages of `KExternalLink` that point from one Kolibri plugin SPA to another.

Sign in link on AuthMessage

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/core/assets/src/views/AuthMessage.vue#L13-L18

Link from Coach -> Facility if there are no classes

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/coach/assets/src/views/CoachClassListPage.vue#L27-L32

Link from Device Settings -> Facility Settings

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue#L10-L15

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/device/assets/src/views/DeviceSettingsPage/index.vue#L85-L98

Link from Facility Settings -> Device Settings

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/facility/assets/src/views/FacilityConfigPage/index.vue#L9-L14

Link to device permissions page

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/facility/assets/src/views/UserEditPage.vue#L39-L45

Link from Learn page to Content import page 

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue#L6

**Comment by nucleogenesis** [comment]
Closing in favor of a different approach, opening a separate issue.
