### ISSUE TITLE
Users are not being redirected to desired page after authenticating

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7488]
### Observed behavior

When trying to view a page like https://kolibri-beta.learningequality.org/en/device/#/permissions without being signed-in, you will see a page with a link to the sign-in page that also has this `redirect` parameter e.g.

https://kolibri-beta.learningequality.org/en/user/?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions#/signin

That `redirect` parameter is supposed to take you back to the page you wanted (e.g. the Permissions page). Instead it seems to take you to the default landing page for your user type (e.g. with a superuser account I end up on the Device > Channels page).

### Expected behavior

After signing in, I am taken to the page I wanted go to and see it (if I have permissions to see it).

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

0.14.3

**Comment by jonboiser** [comment]
I just noticed that the URL here is not formatted correctly:

❌ https://kolibri-beta.learningequality.org/en/user/?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions#/signin,

but this is after we land on the sign-in page. The URL provided in the AppError page is correct:

✅ https://kolibri-beta.learningequality.org/en/user/?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions

The URL that appears when you're on the sign in page has `/signin` at the end which seems to be a a mis-formatting of the URL. Maybe this is why the redirect behavior isn't working. I think what we actually want is this, where the `?redirect` parameter comes after the full URL up to `/signin/`

```diff
- https://kolibri-beta.learningequality.org/en/user/?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions#/signin
+ https://kolibri-beta.learningequality.org/en/user/#/signin?redirect=https%3A%2F%2Fkolibri-beta.learningequality.org%2Fen%2Fdevice%2F%23%2Fpermissions

```

**Comment by jonboiser** [comment]
@nucleogenesis Do you know why the post-`#` of the URL gets appended after the `?next` query parameter when one lands on the Sign In page?

**Comment by nucleogenesis** [comment]
The URL is being improperly formatted and can be fixed like so: https://github.com/learningequality/kolibri/commit/15c2fc6323099fb2b50cccd4bacfb1e473262c3b

But that doesn't seem to fix the issue. Will need more work to test thoroughly. We also don't account for the MFD flow in that a user might be redirected to signin, but they may change facilities or something and that would lose their query params - which could be annoying if they're trying to follow a link to a Class Home or reports, for example.
