### ISSUE TITLE
Sign-in page center container has unbalanced padding

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7491]
### Observed behavior

All sides of the container have 32px padding except for the bottom side which is more like 24px.

<img width="689" alt="CleanShot 2020-08-26 at 13 27 29@2x" src="https://user-images.githubusercontent.com/10248067/91353473-2a60ec00-e7a0-11ea-9d4b-21325b6a6f14.png">

### Expected behavior

To me, the unbalance is sort of noticeable, and think it would look a little better if all sides were even.

### Context

0.14.3

**Comment by indirectlylit** [comment]
very unsightly!

**Comment by jonboiser** [comment]
With the "password required" setting, the bottom padding looks more balanced, but is several pixels more than the sides.

![image](https://user-images.githubusercontent.com/10248067/91754124-c2cee600-eb7d-11ea-89ca-632572d61f17.png)
