### ISSUE TITLE
Double run when trying to Update Channel

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7492]
### Observed behavior

When a channel update is available and we try to execute `UPDATE CHANNEL`, it requires executing the entire cycle twice. See below gif capture of the update channel cycles and the task list screenshot. However, the second run seems a "blank" run though.

![double_channel_update_refresh](https://user-images.githubusercontent.com/2577060/91410667-dc61ec00-e864-11ea-83c0-6fb3be1c1ffc.gif)

![image](https://user-images.githubusercontent.com/2577060/91410673-e126a000-e864-11ea-8966-f1586e4e9aa2.png)

### Expected behavior

Should complete the update process in a single run.

### User-facing consequences

Confusion because it seems that the update is failing some where which isn't true.

### Errors and logs

N/A

### Steps to reproduce

1. Update a channel in studio if there isn't one eligible for update from your Device - Channels list.
2. Try to update the channel and follow the steps intuitively.

### Context

Kolibri 0.14.3 deb 
Ubuntu

**Comment by pcenov** [comment]
@radinamatic this one is fixed in 0.15.6:

https://user-images.githubusercontent.com/79847249/182151999-6bccfafb-4d95-4552-a282-52aa8191dc43.mp4

**Comment by rtibbles** [comment]
Seems like this must have been fixed at some point in 0.15.
