### ISSUE TITLE
manage provisiondevice accepts password with special characters but does not set it

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7495]
### Observed behavior

`kolibri manage provisiondevice` accepts a super user password with special characters but does not set it properly i.e. when using for authentication, the password is not acceptable and reports as incorrect.

Am aware that - " The 'provisiondevice' command is experimental, and the API and behavior will change in a future release"

### Expected behavior

Password with special characters should be allowed to be set via `provisiondevice`. If not, then it should be explicitly rejected while trying to set one in the first place.

### User-facing consequences

Confusion and inconvenience.

### Errors and logs

None

### Steps to reproduce

Execute `kolibri manage provisiondevice`
Try to set a super user password containing special characters.

### Context

Kolibri 0.14.3 deb

**Comment by rtibbles** [comment]
@intelliant01 what special characters are problematic here? All Unicode or more specific than that?

**Comment by intelliant01** [comment]
@rtibbles it's been a long time since. If I remember correctly, I had tried with the generally allowed special characters in a password like one or two of these along with a few alphabets - `%$^&!`.

**Comment by jredrejo** [comment]
I have tried all kind of combinations, including dirty ones and all of them have worked in the password, working with 0.15.
Some of the passwords that have worked are:
`año-%&$^C`
`añá&```)?¿`
I can't think of paswords more special than these

**Comment by intelliant01** [comment]
@jredrejo Did you try with `kolibri manage provisiondevice` ?

This is my experience even now with 0.15 -
```
mssadmin@server:~$ kolibri manage provisiondevice
WARNING  Option CHERRYPY_START in section [Server] is deprecated, please remove it from your options.ini file
INFO     Option DEBUG in section [Server] being overridden by environment variable KOLIBRI_DEBUG
INFO     Option DEBUG_LOG_DATABASE in section [Server] being overridden by environment variable KOLIBRI_DEBUG_LOG_DATABASE
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Importing 'tasks' module from django apps
INFO     Invoking command provisiondevice
WARNING  The 'provisiondevice' command is experimental, and the API and behavior will change in a future release
Do you wish to create a facility? [y/n] y
What do you wish to name your facility? Trialfacility
Which preset do you wish to use? [formal/nonformal/informal]: formal
Enter a default language code [ar,bg-bg,bn-bd,de,el,en,es-419,es-es,fa,ff-cm,fr-fr,gu-in,ha,hi-in,id,it,ka,km,ko,mr,my,nyn,pt-br,pt-mz,sw-tz,te,ur-pk,vi,yo,zh-hans]: en
Enter a username for the super user: trialadmin
Enter a password for the super user: Password$%123
Confirm password for the super user: Password$%123
INFO     Facility with name 'Trialfacility' created.
INFO     Facility preset changed to formal.
INFO     Device settings updated with {'language_id': 'en'}
INFO     Superuser created with username 'trialadmin' in facility 'Trialfacility'.
mssadmin@server:~$ dpkg --list |grep kolibri
ii  kolibri                                         0.15.0-0ubuntu1                                               all          The offline app for universal education
ii  kolibri-server                                  0.4.0-0ubuntu2                                                all          Improve Kolibri server network configuration
```

Authentication fails with Incorrect Password response when trying to login after the above steps.
