### ISSUE TITLE
Vue Devtools does not work for learningequality.org demo servers

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7499]
### Observed behavior

When I visit https://kolibribeta.learningequality.org (as well as the other subdomains `kolibri-dev`, `kolibri-demo`), Vue devtools don't work in Chrome/Firefox/etc probably because the library is in an optimized "production" mode.

### Expected behavior

Dev tools still work in these special environments because it is easier to debug things we're seeing specifically in these deployments and might be specific to the data, OS, or other things we can't easily replicate locally.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
I don't think this is something we can easily fix, closing as wontfix.
