### ISSUE TITLE
nav bar broken in vue2

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#750]
for profile mode:

![image](https://cloud.githubusercontent.com/assets/2367265/21662954/e6a2a9f8-d291-11e6-8823-f20a0a2af0d9.png)

**Comment by indirectlylit** [comment]
cc @eli @christianmemije

**Comment by 66eli77** [comment]
ha

**Comment by 66eli77** [comment]
fixed in PR #753
