### ISSUE TITLE
No "Create An Account" Button on the sign-in page in Android App.

### ISSUE THREAD

**Issue by MasakoOllivier** [learningequality/kolibri#7501]
### Observed behavior

On the sign-in page, there's no "Create an account" button. Right now, it shows only 1 user name.

### Expected behavior

There should be a "Create An Account" button on the sign-in page.

### User-facing consequences

No way to switch accounts/users.

### Errors and logs

…

### Steps to reproduce

Start the app after setting up an account.

### Context

Kolibri version: 0.14.3
Operating system: Android 5.1
Browser: Android App
Device: BLU Advance 5.0

**Comment by jonboiser** [comment]
Could you check the Facility settings to see if the "learner can sign up" setting is turned on or off?

The "create an account" button is shown only if that setting is on and this other `hideCreateAccount` prop is false (need to see if the App context might be affecting that).

https://github.com/learningequality/kolibri/blob/65c0d60a7b2507337f95b131492e47d0e62e2b47/kolibri/plugins/user/assets/src/views/AuthBase.vue#L73-L87

**Comment by MasakoOllivier** [comment]
It WAS turned off, so I turned it on and it works now.

 

Thanks so much!

Masako

**Comment by indirectlylit** [comment]
FYI @MasakoOllivier replying from email sometimes adds a lot of extra text to the response. recommend using the web UI when possible

**Comment by MasakoOllivier** [comment]
Thank you for your advice. Yes, I noticed it after I replied. ^^; Sorry for the extra stuff that came with my comment.

**Comment by jonboiser** [comment]
Kolibri will have the "learner can sign up" setting turned on only for the "non-formal" preset in the Setup Wizard (which is presented as using Kolibri in a library/ small/etc group setting).

For users seeing this issue, you will need to go into your Facility Settings and re-enable the feature to allow users to make their own accounts.

**Comment by kollivier** [comment]
@jonboiser I thought we decided at the Tuesday Kolibri tactical that the "informal" / "Quick Start" facility creation should also have the "learner can sign up" turned on, and that it being off by default was likely an oversight rather than a conscious design decision? (e.g. we want to support cases like family members sharing a tablet or computer but each having their own progress)

**Comment by jonboiser** [comment]
Ah, would you mind making an issue just for that then (making `learner can sign up: true` the default for `preset: informal`)? That should be an simple change.

**Comment by kollivier** [comment]
Okay, done! https://github.com/learningequality/kolibri/issues/7505
