### ISSUE TITLE
Crashes during viewing PDF on Android 5

### ISSUE THREAD

**Issue by MasakoOllivier** [learningequality/kolibri#7511]
### Observed behavior

Checking performance using Kolibri QA channel.

When trying to change font sides, doc orientation, etc. while viewing PDF, Kolibri crashes on Android 5 (device: BLU). (The "Sorry! Something went wrong!" message appears)  When using newer devices (Pixel C: Android 6; Nokia 1.3: Android 10), these crashes don't happen, at least I didn't see them.

![image](https://user-images.githubusercontent.com/70489926/93030463-27eff600-f5d8-11ea-932d-dc646312f8ed.png)

### Expected behavior

It should continue to let the user view the document without crashing.

### User-facing consequences

Users cannot view PDF content (if they're using old devices).

### Errors and logs

Files attached.

[0913_07_AppLog_crashed_while_viewing_PDF_Android5.txt](https://github.com/learningequality/kolibri/files/5219719/0913_07_AppLog_crashed_while_viewing_PDF_Android5.txt)
[0913_08_KolibriLog_crashed_while_viewing_PDF_Android5.txt](https://github.com/learningequality/kolibri/files/5219726/0913_08_KolibriLog_crashed_while_viewing_PDF_Android5.txt)

### Steps to reproduce

Use an old device and try to view PDF content. Adjust font sizes and change the doc orientation.

### Context

Kolibri version: 0.14.3
Operating system: Android 5.1
Browser: Android App
Device: BLU Advance 5.0

**Comment by radinamatic** [comment]
~@pcenov Could you grab the oldest Android device you have available and try to replicate with the most recent Kolibri? Thank you!~

Disregard, apparently a backend issue.

**Comment by rtibbles** [comment]
We are no longer able to support Android 5 with the App, so closing as wontfix.
