### ISSUE TITLE
HTML 5 viewing issues on Android

### ISSUE THREAD

**Issue by MasakoOllivier** [learningequality/kolibri#7513]
### Observed behavior

Devices:
Android 5.1 - BLU Advance 5.0 (cell phone)
Android 6.0.1 - Pixel C (tablet)
Android 10 - Nokia 1.3 (cell phone)

I'm using Kolibri QA Channel to check the performance.

Plix 
Contents do not show up on Android 5 (BLU). It works fine with the other two devices. 

![image](https://user-images.githubusercontent.com/70489926/93107248-2cfb8680-f666-11ea-9886-337fc731deaa.png)

Flexbook
Formulas don't seem to appear on Android 5 (BLU).  The 2nd pic is a capture from the desktop Kolibri. This is how it should appear. On the other two devices, they appeared okay first and then, after using Kolibri for a while, they stopped appearing.

![image](https://user-images.githubusercontent.com/70489926/93108039-33d6c900-f667-11ea-938f-d66c97a33f8f.png)

![image](https://user-images.githubusercontent.com/70489926/93108110-46e99900-f667-11ea-9ce7-e9f9e4f56d00.png)

Funza
The content didn't load on Android 5 (BLU)  at all. Android 10 (Nokia) started loading, got to 74% and crashed. It loaded okay on Android 6 (Pixel C)

![image](https://user-images.githubusercontent.com/70489926/93114118-0beb6380-f66f-11ea-9171-f8b04ce52c36.png)

Slides
On the last page of the slide, it doesn't show the entire text and the cat picture is missing as well.

![image](https://user-images.githubusercontent.com/70489926/93110583-60d8ab00-f66a-11ea-80a8-03beeb6812d7.png)

### Expected behavior

Content should load and appear without missing any part of the content.

### User-facing consequences

Users cannot view the content properly.

### Errors and logs

Log for the Funza crash on Android 10 (Nokia).
[0914_01_KolibriLog_Funza_crash_Nokia.txt](https://github.com/learningequality/kolibri/files/5219828/0914_01_KolibriLog_Funza_crash_Nokia.txt)

### Steps to reproduce

View the contents that had issues. Also, try to do it after using Kolibri for a while. (to make it run out of memory?)

### Context

Kolibri version: 0.14.3
Operating system: Android 5.1, 6.0.1, and 10
Browser: Android App
Device: 
Android 5.1 - BLU Advance 5.0 (cell phone)
Android 6.0.1 - Pixel C (tablet)
Android 10 - Nokia 1.3 (cell phone)

**Comment by pcenov** [comment]
@radinamatic we are no longer supporting Android 5. Tested with Android 8 and above and the HTML resources are being displayed identical to the web version so I wasn't able to reproduce the issues described above.

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
