### ISSUE TITLE
Viewing PDF: zoom in & out bar is hard to access - Android

### ISSUE THREAD

**Issue by MasakoOllivier** [learningequality/kolibri#7514]
### Observed behavior

Devices:
Android 6.0.1 - Pixel C (tablet)
Android 10 - Nokia 1.3 (smart phone)

When viewing PDF in the full screen mode, it's sometimes hard to access the zoom in & out bar. It's not that it never appears. It just doesn't appear when you expect, so you miss the timing to zoom in & out, or exit full screen. It seems that the longer you've been running Kolibri, the harder it gets.

### Expected behavior

The bar should appear in a more responsive manner.

### User-facing consequences

Users will have a hard time to zoom in & out or exiting the full screen mode.

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri version: 0.14.3
Operating system: Android 6.0.1 and 10
Browser: Android App
Device:
Android 6.0.1 - Pixel C (tablet)
Android 10 - Nokia 1.3 (smart phone)

**Comment by rtibbles** [comment]
@radinamatic @pcenov can we confirm if this is still extant after the recent updates to the PDF renderer?

**Comment by radinamatic** [comment]
Nope, we have a fixed PDF top toolbar now 🙂 


https://user-images.githubusercontent.com/1457929/232624632-17f84c1c-6693-46f8-aa98-b79c9f6b6f1d.mp4
