### ISSUE TITLE
Slow /api/auth/classroom endpoint

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#7518]
# Summary
We are experiencing 10+ latencies for the the `api/auth/classroom` endpoint on the Chile Kolibri Country server.

The full CURL request to emulate the slow endpoint can be found in [this slack message](https://learningequality.slack.com/archives/C920Q1LNS/p1600302430042400).

@rtibbles mentioned that the bottleneck is in our use of `HierarchicalRelationsFilter` [here](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/auth/api.py#L379).

# Impact

Every coach viewing the list of classrooms on all Cloud Kolibri servers will experience this slowdown.

Affects all Kolibri 0.12-0.14 users.

**Comment by rtibbles** [comment]
Note that this is specific to filtering by role:
```/api/auth/classroom/?role=coach```

**Comment by rtibbles** [comment]
Fixed in #7823
