### ISSUE TITLE
Learn: Rendering Content Page Before Promise is Resolved

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#752]
## Summary

`[Vue warn]: Error when rendering component <content-page> at /home/christian/repos/kolibri/kolibri/plugins/learn/assets/src/vue/content-page/index.vue: `
`TypeError: Cannot read property 'title' of undefined`

## How to reproduce
1. View a piece of content in Learn.
2. Navigate back.
3. Click on the same piece of content.
4. Check console.

## Possible Fixes
The issue is in `showLearnContent()` within Learn's actions.js. `CORE_SET_PAGE_LOADING` is set to false by the `recommendedPromise` before the `contentPromise` is resolved.  

There are a few possible fixes. 
1. Add the `recommendedPromise` into the `ConditionalPromise.all` (I believe the separation was to speed up load time.)
2. Let `CORE_SET_PAGE_LOADING` be set to false only by the `contentPromise` (Assumes the `contentPromise` will always resolve last.)
3. Have a counter so that only the promise that is resolved last can set the `CORE_SET_PAGE_LOADING` to false. 

Thoughts @indirectlylit?

**Comment by indirectlylit** [comment]
I think option 2 makes sense, and it's okay if they run in parallel because they don't clobber each others' subtrees of the state

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/759.

**Comment by DXCanas** [comment]
@christianmemije ok to close then?
