### ISSUE TITLE
Django tests should probably use `setUpClassData`(run once per TestCase class) more often than `setUp` (run every unit test)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7528]
A lot of our django tests use the `setUp()` method to run code that could should probably be only run once, e.g. for provisioning the device, making superusers, etc. As an optimization, this should be moved to a `setUpTestData(cls)` method. I tested this out on `kolibri/core/content/test/test_content_app.py::ContentNodeAPITestCase` and the whole test case took 100 seconds to run using the `setUp` method.

After renaming `setUp()` to `setUpTestData` and adding the `@classmethod` directive, the run time was reduced to 20 seconds and no failures.

On the looks of things, the `setUp` method is perfect for this optimization
```
    def setUpTestData(self):
        provision_device()
        self.facility = Facility.objects.create(name="facility")
        self.admin = FacilityUser.objects.create(
            username="admin", facility=self.facility
        )
        self.admin.set_password(DUMMY_PASSWORD)
        self.admin.save()
        self.facility.add_admin(self.admin)
```

Since these objects (Facility, superusers) are in principle re-usable and we're not mutating them as part of the test and the device provisioning is probably the slow point. There is a fixture file for contentnodes, but I'm not sure if they are actually reset by `provision_device`. If so, a more targeted cleanup or setup function should be used to undo any mutations caused by the actual test.

**Comment by rtibbles** [comment]
Note that even when we are mutating the data, if it is a regular DjangoTestCase, then it will roll back any changes after the test, so this should be safe in a lot of places.

**Comment by jonboiser** [comment]
I applied this refactor in a two test modules, and both took about 1/3 the time before the refactor, so we could get some good speedups if applied everywhere in the test suite.

https://github.com/learningequality/kolibri/compare/release-v0.14.x...jonboiser:faster-test-setup
