### ISSUE TITLE
Export Logs, User Import and Export missing after Facility Sync

### ISSUE THREAD

**Issue by pateljj04** [learningequality/kolibri#7538]
### Observed behavior

Under Facility Data, the option for Export usage Logs as well as Import and export users is missing once a facility has been sync. 
![Screen Shot 2020-09-30 at 2 19 53 PM](https://user-images.githubusercontent.com/404871/94724387-37857380-0328-11eb-85f0-ab341415c70c.png)

### Expected behavior

Expected behavior, I think it should still show Export Usage data and Import and Export users option even after a sync.

### User-facing consequences

For example, if Kolibri on a Pi is sent to students and when it comes back performs sync with a centralized instance of Kolibri, there still needs to be a way to import/export users as well as the ability to look at logs. I am able to generate the logs from cli, however, I am not sure about importing/exporting users using cli. 

### Steps to reproduce

Perform facility sync, once the sync has happened the option for exporting logs and users data management pieces are no longer there.  

### Context

Kolibri Version: 0.14.3

**Comment by jonboiser** [comment]
Hi @pateljj04, do you mean that the Import and Export functionality is missing from the page in the picture above?

In Kolibri, the ability to import users/export logs is not in the "Sync facility data" page, but a different part of the app, in the Facility > Data section. Here's how you would navigate to it:

![image](https://user-images.githubusercontent.com/10248067/94725534-c7b7be80-0310-11eb-8671-3bded7e4146a.png)

**Comment by jonboiser** [comment]
@pateljj04 Sorry for misinterpreting the screenshot above. Are you saying that the top two sections in the Facility > Data page disappear after you sync?

![image](https://user-images.githubusercontent.com/10248067/94726171-b4f1b980-0311-11eb-8494-bdc2eb253433.png)

This is unusual, because this is normal behavior for our Mac and Android versions of Kolibri, but those sections should always be shown even if Kolibri is running on a Rasberry Pi.

**Comment by pateljj04** [comment]
Hi @jonboiser yes sorry I should clarify, it's missing from the Data screen once its syncs with a facility.

**Comment by jonboiser** [comment]
@pateljj04 Do you have any Kolibri server logs or see any console errors inside your browser's development tools?

And are these import/export sections missing permanently now? They don't return after refreshing the page?

**Comment by pateljj04** [comment]
@jonboiser doing some more testing, it seems after the initial sync and subsequent reboots it tends to disappear. Rebooting bring it back but as soon as the sync is performed it disappears again. I will try to grab the logs.

**Comment by jonboiser** [comment]
Let us know if you are able to share any server logs that are recorded right when you sync a facility, plus any messages in the browser's console. Unfortunately, what you're seeing is very very unusual based on our understanding of how the facility-sync backend code and the facility data page frontend code work.

**Comment by pateljj04** [comment]
@jonboiser It's doing it again, what specific server logs should I pull? What I call our content server (local instance that Pi's sync with) it's running on Ubuntu 18.04.5.

**Comment by jonboiser** [comment]
In your `KOLIBRI_HOME` directory there should be a `/logs` directory with some text files (debug.txt and kolibri.txt). Could you maybe [create a gist](https://gist.github.com/) of them or email them to me at jonathan@learningequality?

I suspect this might be a frontend issue, so if you can take a screenshot or create a text file of any logs you see in, for example, the Chrome developer tools console that would help too.

**Comment by pateljj04** [comment]
Ok sounds good, I will email the debug and Kolibri log files. As well as the screenshot of the Safari, it looks like Safari is the culprit, it's showing fine in Chrome. Very weird.

**Comment by jonboiser** [comment]
Oh, okay. Could you post the console screenshot from Safari? That seems the most likely root cause right now! We'll see if we can reproduce this.

**Comment by pateljj04** [comment]
Here is Chrome: <img width="1916" alt="Screen Shot 2020-10-02 at 2 42 12 PM" src="https://user-images.githubusercontent.com/404871/95093441-ca425b80-06f6-11eb-9755-05dcc3c95df1.png">
Here is Safari: <img width="1920" alt="Screen Shot 2020-10-02 at 2 41 58 PM" src="https://user-images.githubusercontent.com/404871/95093456-ce6e7900-06f6-11eb-89cd-13895d22f85f.png">

**Comment by kollivier** [comment]
@pateljj04 In Safari, could you type `navigator.userAgent` into the JS console, and paste in what it shows?

**Comment by pateljj04** [comment]
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15" = $2

**Comment by jonboiser** [comment]
I was able to see this on the kolibri-beta server too with Safari. My user agent string is identical:

```
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15" 
```

**Comment by jonboiser** [comment]
@pateljj04 We just merged a patch that we think fixes this issue. Would you be interested in testing the fix with our next [Kolibri 0.14.4 weekly releases](https://github.com/learningequality/kolibri/releases)? The next release (`0.14.4-weekly3`) will have the fix and be released this Friday, October 9, around 12PM GMT-700 (California USA time). If you look in the "assets" section for our current releases, we include a RAsberry Pi image along with the other installers.

**Comment by pateljj04** [comment]
@jonboiser Sure, I will check it out and let you know! Thanks!

**Comment by jonboiser** [comment]
@pateljj04 We just released the weekly Kolibri release that hopefully fixes this issue for you on Safari. You can find the RPi image [at this link](https://github.com/learningequality/kolibri/releases/tag/v0.14.4-weekly3) under the "Assets" section on the button. Just a heads up that these are fairly large files (around 500 MB).
