### ISSUE TITLE
Kolibri version number defined via webpack doesn't recognize `-weekly` or other novel tags (shows as `-dev0`)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7540]
### Observed behavior

Currently, the git tag of Kolibri live on kolibri-beta.learningequality.org is `0.14.4-weekly2`, but the website shows this on the bottom of the Sign-In Page

![image](https://user-images.githubusercontent.com/10248067/94970104-c4f7cd80-04b8-11eb-9e81-3690b5f64a8f.png)

Similarly, the installers for Kolibri on the release page have the same `dev0` version in the file names.

### Expected behavior

1. An accurate version suffix on the website
1. An accurate version suffix on the installers

**Comment by rtibbles** [comment]
The allowed versions are defined in the Kolibri Python version code here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/utils/version.py#L112, so it might just be a matter of adding `weekly` as an option (but may also be more complex than that....)

**Comment by jonboiser** [comment]
Yeah, I'm looking at all this documentation stressing the semantic versioning, and realize `weekly` doesn't really fit into that story. But the intention is that the weekly release is a mostly internal thing and I don't plan on publishing any weekly versions anywhere.

So I think the plan will be just to add `weekly` as an allowable tag, and see if that works.

**Comment by jonboiser** [comment]
pre-releases will continue to use the `-alpha` suffix, so the versioning code doesn't need to support the `-weekly` suffix for now.
