### ISSUE TITLE
Same "sync" user credentials across facilities cause sync to fail

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7541]
### Observed behavior

Have two facilities with the same admin credentials on a server. Was attempting to import facilities on two different devices using `kolibri manage sync...`

The `sync` was always failing on the 2nd device with this error -

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://192.168.1.69:8080/api/morango/v1/certificates/`

After a lot of permutations and combinations realised that setting different passwords for each of the `admin` users allowed the sync to complete successfully on each device. 

### Expected behavior

The sync should have worked even with the same user credentials across facilities since the sync command differentiates the users with a `--facility <facilityid>`

### User-facing consequences

Confusion and anxiety as user has no way to know what is wrong and what is the cause of the error.

### Errors and logs

Error message following a large exception dump -

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://192.168.1.69:8080/api/morango/v1/certificates/`

### Steps to reproduce

1. Create two facilities.
2. Add a admin user in each of the facilities with exactly the same username and password - admin / password.
3. On another device try importing the two facilities using `kolibri manage sync --baseurl <source device ip/domain> --facility <facilityid[1,2]> --username admin --password password --no-push --noninteractive` command.
4. The import shall most likely fail for the second attempt.
5. Now change password of the admin user of the facility for which the sync is failing.
6. Stop Kolibri, remove the `KOLIBRI_HOME` folder and start Kolibri.
6. Reattempt the sync for both the facilities.
7. Now the sync shall work for both facilities.

### Context

Kolibi 0.14.3

**Comment by intelliant01** [comment]
Related https://github.com/learningequality/kolibri/pull/3011

**Comment by jonboiser** [comment]
@intelliant01 Is this only an issue when using the `importfacility` management command, or have you been able to reproduce this using the Import Facility workflow on the Device > Facilities page?

![image](https://user-images.githubusercontent.com/10248067/95391426-e50a0100-08ab-11eb-8139-673465764538.png)

**Comment by intelliant01** [comment]
Through `Device - FACILITIES`, upon attempting the import of the 2nd facility with the duplicate username and password of an admin user, the UI shows - `Incorrect username or password` and nothing in the logs.

**Comment by jonboiser** [comment]
Okay, so the result looks the same whether you use the management command or the UI.

**Comment by pateljj04** [comment]
I am also having this issue, wondering what the temporary workaround is? Wouldn't remove the KOLIBRI_DATA folder remove the channel content?

**Comment by jonboiser** [comment]
I believe the current workaround is to make sure that facility admins have unique usernames and/or passwords. 

I don't believe you need to remove the entire `KOLIBRI_DATA` folder, since this problem is most likely caused by specific tables in the `db.sqlite` file, namely these "morango_" tables

![image](https://user-images.githubusercontent.com/10248067/95638021-36e78e00-0a48-11eb-898d-79e85ad33974.png)

@pateljj04 , I haven't personally tried this workaround? Can you see if it works simply by changing the facility admin credentials, and _not_ having to delete or modify data in KOLIBRI_HOME?

@bjester, do you have any ideas on how to clear out any sync-related tables that might be affecting authenticating when doing facility syncing?

**Comment by intelliant01** [comment]
@jonboiser more than the need of clearing a morango table, to me it seems a case of acknowledging the fact that the 2nd sync attemtping admin user is a unique one based on its facility id and issue a new certificate. Once a certificate is issued, the credentials (username and password) will no longer matter.

**Comment by pateljj04** [comment]
@jonboiser That doesn't seem to work, my scenario might be a little different (Raspberry Pi), however, the behavior and the process described here is same. I have a 1st device (Pi) set up and synced with a facility. Then I deprovision the device to make copies of it, duplicating it so each Pi is different. When going thru the setup wizard on a duplicated image Importing facility fails and gives me the username and password incorrect on the  create facility admin screen.

**Comment by pateljj04** [comment]
I think this is replicating #7504  behavior but on the second device.

**Comment by pateljj04** [comment]
In addition, doing some more testing, if I set up the device as a new facility after deprovision, instead of doing an import facility, when I go to import a facility it doesn't import the new facility (hope that makes sense)
