### ISSUE TITLE
"Coach" label displays besides user name instead of "Class coach" label

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7568]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; trivial

Preconditions; user is logged in as super admin, *Facility > Users* page is opened

Steps to reproduce;

1. Create *Class coach* user
2. Pay attention to the label beside their name

Actual result; "Coach" label displays besides user name instead of "Class coach" label

Expected result; "Class coach" label should be displayed beside the user name

Attachment; https://take.ms/H5lSi

**Comment by jredrejo** [comment]
We call this role in the code "classroom assignable coach" , I think it could make sense to call it class coach, but it might be some kind of mess for our previous users who are familiar with the term just coach, as initially we didn't have the facility/class coach difference.
what do you think @radinamatic

**Comment by MindfulQA** [comment]
Able to replicate on the app.
OS: macOS Catalina version 10.15.6

**Comment by jredrejo** [comment]
> Able to replicate on the app.
> OS: macOS Catalina version 10.15.6

There's no need to check this. The question is deciding if "Class coach" is a correct naming here, to change the testing scenario @radinamatic

**Comment by radinamatic** [comment]
Thank you @jredrejo, we may explore the option to change the label/string, but only for the next major version upgrade.

For now I'll amend the Gherkin scenario :+1:

**Comment by rtibbles** [comment]
I don't think this needs to be fixed, they're a coach, so it says they're a coach.
