### ISSUE TITLE
[RPi] The edit user page closes automatically after saving the changes

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7569]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as super admin, *Facility > Users* page is opened

Steps to reproduce;

1. Click on the options button of any user
2. Click on the edit details button
3. Change the full name
4. Click on the Save button
5. Pay attention to closing the user details edit page, it will close automatically

Actual result: The edit user page closes automatically after saving the changes

Expected result; The edit user page closes by clicking on the "Close" button in the upper left corner 

Attachment; http://e.pc.cd/9XbotalK

**Comment by jonboiser** [comment]
This is the expected behavior of the User Editing page as of 0.14.3.

@radinamatic Is it possible the Gherkin story for this flow is outdated?
