### ISSUE TITLE
vue2 - issue with focus in modals

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#757]
console error regarding a `contains` check.

Steps to repro:

* open a modal
* put keyboard focus in a text input
* switch to another browser window and back

**Comment by DXCanas** [comment]
Seems like this could be because when you switch back, you're initially focusing on `window`. We might be able to add a listener and have it automatically focus on the modal?

**Comment by indirectlylit** [comment]
not sure offhand, but it might be related to the `$refs` API changes between vue1 and vue2: https://vuejs.org/v2/guide/migration.html#v-el-and-v-ref-replaced
