### ISSUE TITLE
[RPi] The list of learners includes all users not only learners

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7570]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as super admin, *Facility > Classes* page is opened

Steps to reproduce;

1. Click on the class
2. Click on the "enroll learners" button
3. Pay attention to the users which displayed in the list

Actual result: The list includes all users not only learners

Expected result; Only learners should be on the learners' list.
Also, note that in the coach list  admin users are displayed too https://take.ms/HAtD5p
Attachment; https://take.ms/gGWQL

**Comment by jonboiser** [comment]
This is expected behavior. Users of any role (learner, coach, admin, etc.) can be enrolled as a class as a learner.
