### ISSUE TITLE
[RPi] Confirmation message that the class was deleted is displayed

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7571]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as super admin, *Facility > Classes* page is opened

Steps to reproduce;

1. Click on the "delete class" button
2. Click on the "delete" button on the displayed modal
3. Pay attention to the displayed confirmation message

Actual result: Confirmation message that the class was deleted is displayed

Expected result; # no confirmation that the class has been deleted

Attachment; http://e.pc.cd/R0botalK

**Comment by jonboiser** [comment]
This is intentional behavior. Is there a reason why you expect that no notification would appear after the class is deleted, or is that a preference you have?
