### ISSUE TITLE
[RPi] It's possible to set the old password as a new

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7572]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as super admin, *User > Profile* page is opened

Steps to reproduce;

1. Click on the "Change password" button
2. Enter the old password to the password field
3. Re-enter the password to the second field
4. Click on the "Update" button
5. Pay attention to the success message about changing the password

Actual result: It's possible to set the old password as a new
Expected result; It shouldn't be possible to set the old password as a new

Attachment; http://e.pc.cd/jXbotalK

**Comment by jonboiser** [comment]
This is expected behavior, and it is not uncommon for websites to allow setting the current password as the new one. Is there a specific concern you had why we shouldn't allow that?
