### ISSUE TITLE
[RPi] Importing is failed after importing the selected full channel

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7573]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; blocker

Preconditions; user is logged in as super admin, *Channel* page is opened

Steps to reproduce;

1. Click on the "Import" button
2. Select the source of importing
3. Click on the "Select entire channels instead" link
4. Select any channel
5. Click on the import button
6. Pay attention to the importing progress 

Actual result: Importing is failed after importing the selected full channel
Expected result; Importing should be successful after importing the selected full channel

Attachment; http://e.pc.cd/JVbotalK

**Comment by ghost** [comment]
The "Multaqaddarain K-12 (العربيّة)" channel tried to import, but import didn't even start. In attachment I added the video, you can check it

**Comment by jredrejo** [comment]
> The "Multaqaddarain K-12 (العربيّة)" channel tried to import, but import didn't even start. In attachment I added the video, you can check it

Hi @Sasha801 thanks for your report, some questions to try to clarify/reproduce it:

- does this happen only with this channel or with any other channel?
- if you try it later, did it work? (Thinking it could be a network issue)

**Comment by ghost** [comment]
Hi, @jredrejo! This happens with all channels and if I try later it doesn't work.

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this one in 0.16.0b10

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
