### ISSUE TITLE
"N of resources selected" flag is missing, "All resources selected" text is visible instead

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7575]
### Observed behavior

When trying to import resources from a channel, after topics/sub-topics are selected the "N of resources selected" flag is missing or each imported resource. "All resources selected" text is visible instead (SEE IMAGE BELOW)
<img width="948" alt="2020-10-19_133337" src="https://user-images.githubusercontent.com/72492554/96440921-4c5f7380-1211-11eb-8ea6-e2c85cecd9a2.png">

### Expected behavior

"N of resources selected" flag is visible for each topic/sub-topic

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Login as super-admin
2. Go to Device -> Channels
3. Click Import button
4. Select Kolibri Studio
5. After the channels list loads select a channel which isn't imported to the device
6. Click Select resources
7. After the channel listing is generated click Select All

### Context

Kolibri version: 0.14.3
Device: Raspberry Pi 4, 4GB RAM
OS: Raspbian GNU/Linux 10
Browser: Chrome (Latest version) % Firefox (Latest version)

**Comment by davidgarg20** [comment]
@jonboiser I would like to work on this issue

**Comment by davidgarg20** [comment]
@jonboiser what should be the n in "n of resources"

**Comment by pcenov** [comment]
@radinamatic seems that this issue is no longer valid - a 'Some resources selected' text is displayed now in that case in 0.15.6:

![2022-08-01_15-33-46](https://user-images.githubusercontent.com/79847249/182149751-b1b4457d-b4f8-441d-a1ab-013c3bb6cf6b.png)

**Comment by rtibbles** [comment]
Great, closing!
