### ISSUE TITLE
(Gherkin needs update) "View all" button is missed on the "quizzes", "class activity", "lessons" blocks on the Class home page

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7578]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; major

Preconditions; user is logged in as a coach,  *Class home* page is opened; there are no created quizzes, lessons, and there has not been any learner engagement in the class

Steps to reproduce;

1. Pay attention to the "quizzes", "class activity", "Lessons" blocks

Actual result: "View all" button is missed on the "quizzes", "class activity", "lessons" blocks on the Class home page
Expected result: "View all" button should be displayed on the "quizzes", "class activity", "lessons" blocks on the Class home page
Attachment: http://e.pc.cd/LpbotalK

**Comment by jonboiser** [comment]
To me, this makes sense because at the moment there are no quizzes, lessons, etc. We only show those buttons when there is at least one in each category.

Is this possibly from an inaccurate Gherkin story?
