### ISSUE TITLE
"Individual learners" item is automatically unchecked on the "edit details" page after unchecking all groups

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7580]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as a coach, Class home page is opened; two groups are created and at least one lesson is created

Steps to reproduce;

1. Proceed to the Plan>Lessons page
2. Click on any lesson
3. Click on the edit details button from the "options" drop-down
4. Select all groups and individual learners
5. Uncheck all groups
6. Pay attention to the "individual learners" item  which was automatically unchecked

Actual result: "Individual learners" item is automatically unchecked on the "edit details" page after unchecking all groups
Expected result: "Individual learners" item shouldn't be automatically unchecked on the "edit details" page after unchecking all groups
Attachment: http://e.pc.cd/vHbotalK

**Comment by jredrejo** [comment]
Confirmed, applies to 0.14.3, no matter the installer
