### ISSUE TITLE
[RPi] It's impossible to come back to the list of resources from the preview page for the selected resource by clicking on the upper left button

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7583]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

Severity; critical

Preconditions; user is logged in as a coach, *Class home* page is opened; at least one lesson is created

Steps to reproduce;

1. Proceed to the Plan>Reports>Lessons page
2. Click on any lesson
3. Click on the "Options" dropdown
4. Click on the "Manage Resources" button
5. Proceed to the preview page for the selected resource
6. Click on the "left arrow" button in the upper left corner
7. Notice that nothing happens

Actual result: It's impossible to come back to the list of resources from the preview page for the selected resource by clicking on the upper left button
Expected result:  It should be possible to come back to the list of resources from the preview page for the selected resource by clicking on the upper left button

Attachment: http://e.pc.cd/OFbotalK

**Comment by jredrejo** [comment]
@Sasha801 I am not able to reproduce this issue.
If you can reproduce it, Please, can you:
1. Press F12 while in the browser to open Chrome dev tools
2. CLick on the Console tab
3. Copy and paste the errors you see in the tab when reproducing this problem

Thanks.

PS. I have been able to reproduce the problem going from the Coach>Reports>Lessons>Options>Manage resources
can you confirm this is where you can see the error and not in the Plan>Lessons page?

**Comment by jonboiser** [comment]
@jredrejo I can reproduce this. The reproduction steps are a little inaccurate. The way to get here is by managing lessons resources from the reports page (not the Plan page)

See [this URL](https://kolibri-beta.learningequality.org/en/coach/#/1b21fb43599f223b4885e95b61aa2ef3/plan/lessons/1f5a2b0091d62a0b05ff32ddea3cab27/selection/preview/d948a70f76995b19978b359d8ea3f7aa?last=ReportsLessonReportPage) as an example.

I believe the root cause is the same as https://github.com/learningequality/kolibri/issues/7584#issuecomment-712320421

**Comment by jredrejo** [comment]
> @jredrejo I can reproduce this. The reproduction steps are a little inaccurate. The way to get here is by managing lessons resources from the reports page (not the Plan page)
> 
> See [this URL](https://kolibri-beta.learningequality.org/en/coach/#/1b21fb43599f223b4885e95b61aa2ef3/plan/lessons/1f5a2b0091d62a0b05ff32ddea3cab27/selection/preview/d948a70f76995b19978b359d8ea3f7aa?last=ReportsLessonReportPage) as an example.
> 
> I believe the root cause is the same as [#7584 (comment)](https://github.com/learningequality/kolibri/issues/7584#issuecomment-712320421)

@jonboiser  :smile:  see the P.S section in my comment

**Comment by ghost** [comment]
@jredrejo Oh sorry,  I entered the wrong page in the description. You are exactly right, this problem reproduces from the Coach>Reports>Lessons>Options>Manage resources page
