### ISSUE TITLE
`CoreInfoIcon` button is not positioned correctly within Setup Wizard `KRadioButtons`

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7585]
### Observed behavior
The icon appears below the "details" slot

<img width="753" alt="CleanShot 2020-10-19 at 12 17 30@2x" src="https://user-images.githubusercontent.com/10248067/96501599-6a26db80-1205-11eb-93de-41730385393a.png">

### Expected behavior

The icon appears inline with the "details"

### Steps to reproduce

1. Setup wizard
1. Advanced setup
1. Layout issue should appear on some of the facility settings steps

### Context

…

**Comment by jonboiser** [comment]
This might be due to a new layout for the default slot in `KRadioButton`, see here:

https://github.com/learningequality/kolibri-design-system/blob/v0.2.x/lib/KRadioButton.vue#L51

I'm not sure if the layout I want is achievable with the current API, or might require some hacks

**Comment by jonboiser** [comment]
@jtamiace Can we just move the tooltip text to the "description" and do away with the tooltip altogether? Here's what it looks like:

![image](https://user-images.githubusercontent.com/10248067/96516941-de20ae00-121c-11eb-8bb5-91ca172ea236.png)

**Comment by jtamiace** [comment]
@jonboiser I think that's a great suggestion
