### ISSUE TITLE
The thumbnails of the videos are missed in the search page after searching from the manage resources page

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7586]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as a coach, *Coach - '<class>' > Report > Lessons > '<lesson>'* page is opened; 

Steps to reproduce;

1. Click on the "Options" dropdown
2. Click on the "Manage Resources" button
3. Enter <searchterm> in the *Search* field
4. Press the *Submit search* button
5. Pay attention to the preview images of the videos

Actual result: The thumbnails of the videos are missed on the search page after searching from the manage resources page

Expected result: The thumbnails of the videos should be displayed on the search page after searching from the manage resources page

Attachment: http://e.pc.cd/eHbotalK

**Comment by jonboiser** [comment]
It looks like maybe the URL to the thumbnail is not being returned in the search endpoint payload, while it _is_ for the regular browsing `contentnode` endpoint?
