### ISSUE TITLE
The "All" option from the filter dropdown doesn't work after selecting the channel from the filter dropdown

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7588]
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

Severity; major

Preconditions; user is logged in as a coach, *Coach - '<class>' > Report > Lessons > '<lesson>'* page is opened;

Steps to reproduce;

1. You are on the search results page
2. Enter in the Search field any character
3. Press the Submit search button
4. Select the "Khan Academy" option from the channel filter dropdown
5. Select the "Videos" option from the type filter dropdown
6. Select the "All" option from the type filter dropdown
7. Notice that the "All" option isn't applied 

Actual result: The "All" option from the filter dropdown doesn't work after selecting the channel from the filter dropdown
Expected result: The "All" option from the filter dropdown works after selecting the channel from the filter dropdown

Attachment: http://e.pc.cd/9JbotalK

**Comment by jonboiser** [comment]
This issue is related to #5882 and #6173

**Comment by MindfulQA** [comment]
Note: we also encountered this on macOS Catalina 12.15.7 - Kolibri version 0.14.

(We weren't attempting to reproduce this; we searched github issues after finding it to see if it had been reported yet. Even though it doesn't seem likely to be specific to just one Mac environment, adding this additional OS detail here just in case it's helpful!)
