### ISSUE TITLE
User account language reverts back to device default language after app is closed.

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7593]
### Observed behavior

After the user changes the language from the user menu and exits the app, the language reverts back to the 'device default language when reopened.

The only way to retain the user chosen language VS the admin chosen one is the 'browser default' option in the device language settings. This is not very intuitive.

### Expected behavior

The language should not revert to device settings. It should remain in the language that the user chose.

### User-facing consequences

Users will have to change the language every time the app is opened unless an admin has selected 'browser default'.

### Errors and logs

…

### Steps to reproduce

Preconditions: User must be signed in; check device default language in device>settings.

 1. Open the user profile menu in the top righthand corner
 2. Click Change language
 3. Select any language and click confirm.
 4. Verify that the different pages are in the same language that you chose.
 5. Logout then Exit the app.
 6. Reopen the app and login as a super admin
 7. Notice that the language has reverted to device default.
### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment]
I'm not able to reproduce this on kolibri-beta nor locally. Here's my sequence of steps, using the kolibri-beta server as a reference

1. Enter https://kolibri-beta.learningequality.org/ into my browser address bar
1. Get redirected to https://kolibri-beta.learningequality.org/en/user/#/signin (English)
1. Login with account, and switch language (Steps 1-3 in OP)
1. Get redirected to https://kolibri-beta.learningequality.org/de/device/#/content (German)
1. Logout, then close tab
1. Enter https://kolibri-beta.learningequality.org/ into my browser address bar
1. Get redirected to https://kolibri-beta.learningequality.org/de/user/#/signin

Could you provide some context on where you observed this bug and specifics like:

1. The languages you were switching between
1. The browser and where you were running Kolibri (e.g. locally or online)

**Comment by radinamatic** [comment]
@jonboiser Note that @MindfulQA is testing on the Mac app, not the browser.

**Comment by MindfulQA** [comment]
@jonboiser I discovered that when the admin selects 'browser default' in device settings the language does change without having to restart the app. This setting allows the user to choose their own language from the user menu and it will be retained. However, it's not very intuitive. If that 'browser default' setting is not applied, user account language will revert to whatever the admin chose for the 'device language' setting every time the app is opened. If the 'device language is changed to anything but 'browser default', the app will not automatically change to the selected language. It will only change after the app is restarted.

**Comment by rtibbles** [comment]
Note, most of the behaviour described here is intentional, due to difficulties with users changing the language, and the server language not having priority.
