### ISSUE TITLE
Not able to Import Facility through Advanced setup on Kolibri

### ISSUE THREAD

**Issue by JatinSharma12** [learningequality/kolibri#7595]
### Observed behavior
While configuring Kolibri app through Advanced setup, User is not able to import facility as the facilities available to be imported are not clickable/[selectable](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/super-admin/super-admin-imports-facility-in-device-setup.feature).
…

### Expected behavior
User should be able to import selected Facility through Advanced setup on Kolibri.
…

### User-facing consequences
User will not be able to proceed further and is blocked from using the application.

…

### Errors and logs

```

```

…

### Steps to reproduce
1. Double click on Kiolibri.exe file.
2. Application window will open asking to select a language.
3. Select a Language and proceed.
4. Select Advanced setup and proceed.
5. Select Import Facility Option and enter the network address on the next window.
6. User should be able to connect to the above provided network.
7. Try to import any of the facilities  available under that network.
8. Observe that user is not select any of the facility neither by mouse nor by keyboard.

PFA the video for reference.
[AdvancedSetup_issue.zip](https://github.com/learningequality/kolibri/files/5414227/AdvancedSetup_issue.zip)

…

### Context

Tell us about your environment, including:
 * Kolibri version 0.14.3
 * Operating system Windows 10
 * Browser: IE11

…

**Comment by jonboiser** [comment]
@JatinSharma12 Could you share which browser you're using, and if you see any errors in that browser's console? I'm not able to reproduce on my computer.

**Comment by jonboiser** [comment]
I was able to reproduce this on Windows 10 + IE11 on browserstack. There are no console error; the radio buttons just aren't clickable.

**Comment by jonboiser** [comment]
On IE11, the KRadioButton component does not seem to emit any events if its `currentValue` prop is an empty string. Simply changing this line here to initialize `selectedFacilityId` (which is passed to `KRadioButton.$props.currentValue` to something like `"none"` fixes the issue for me on IE11

https://github.com/learningequality/kolibri/blob/c8ff8d027ab2764df36bcc1d9671aa1f84ecb412/kolibri/plugins/setup_wizard/assets/src/views/importFacility/SelectFacilityForm.vue#L77
