### ISSUE TITLE
An input validation error doesn't appear after leaving the input field or attempt to continue or finish the quiz with an empty input field

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7596]
### Actual result: 
An input validation error doesn't appear after leaving the input field or attempt to continue or finish the quiz with an empty input field
### Expected result: 
An input validation error appears after leaving the input field or attempt to continue or finish the quiz with an empty input field

### Preconditions:
User is logged in as a coach;  *Coach - '<class>' > Plan > Quizzes* page is opened

### Steps to reproduce;
1. Click on the "New Quiz" button
2. Enter the title for a quiz and select exercises
3. Leave the "number of questions" field empty
4. Leave the input field or attempt to continue or finish the quiz
5. Notice that the errors are missed
Also please pay attention to the displayed error after proceeding to the preview quiz page with an empty number of questions field. (the error - "Resource not found on device"

### Video: 
http://e.pc.cd/eFbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by jonboiser** [comment]
What should happen is if there name or # of questions is missing, then when the user clicks continue, they are not taken to the quiz preview, but instead stay at the exercise selection step and see validation errors in the form.

**Comment by jonboiser** [comment]
I think this has been fixed in #7745, which dealt with the lack of validation in the "number of questions" field. In manual testing, I'm not able to finish a quiz at any point without providing a valid "number of questions" or title property for the quiz.
