### ISSUE TITLE
The number isn't cut out to 50 if entered value is >50 on the creating new quiz page

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7597]
### Actual result: 
The number isn't cut out to 50 if the entered value is >50 on the creating new quiz page
### Expected result: 
The number should be cut out to 50 if the entered value is >50 on the creating new quiz page
### Preconditions:
User is logged in as a coach;  *Coach - '<class>' > Plan > Quizzes* page is opened

### Steps to reproduce;
1. Click on the "New Quiz" button
2. Enter the title for a quiz and select exercises
3. Enter a number value greater than 50 to the "number of questions field"
4. Continue or finish the quiz
5. Notice that the number isn't cut to 50 (for example If I enter 250 then the number will be cut to 25 or If I enter 550 the number will be cut to 5)

### Video: 
http://e.pc.cd/jFbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by metodimilevqa** [comment]
I confirm the issue is no longer experienced with Kolibri version 0.14.6rc1. Tested with Windows 7 vm, on Chrome, Firefox and IE.
The value for N of questions is automatically cut down to 50 if the user enters >50 as an input.
