### ISSUE TITLE
The resource doesn't uncheck in the parent topic node after unchecking the resource from the list of resources with the selected "select all" parameter

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7599]
### Actual result: 
The resource doesn't uncheck in the parent topic node after unchecking the resource from the list of resources with the selected "select all" parameter
### Expected result: 
The resource should be unchecked in the parent topic node after unchecking the resource from the list of resources with the selected "select all" parameter
### Preconditions:
User is logged in as a coach;  *Coach - '<class>' > Plan > Quizzes* page is opened

### Steps to reproduce;
1. Click on the "New Quiz" button
2. Click on the channel to select the resources
3. Select the "select all" checkbox
4. Go to the list of all selected resources
5. You will see that all resources are checked with a checkbox
6. Uncheck one exercise
7. Go to the parent topic node
8. Notice that all resources are still selected

### Video: 
http://e.pc.cd/PpbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by jonboiser** [comment]
I believe this might be a duplicate or related to #7536. Could you check to see if you can reproduce this on https://kolibri-beta.learningequality.org/? (see the message on the sign in screen on how to sign in as a coach)
