### ISSUE TITLE
The *n of n selected* indicator doesn't apply the changes after adding or removing the resource from the search results page

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7600]
### Actual result: 
The *n of n selected* indicator doesn't apply the changes after adding or removing the resource from the search results page

### Expected result: 
The *n of n selected* indicator applies the changes after adding or removing the resource from the search results page

### Preconditions:
User is logged in as a coach;  *Coach - '<class>' > Plan > Quizzes* page is opened

### Steps to reproduce;
1. Click on the "New Quiz" button
2. Click on the channel to select the resources
3. Select the "select all" checkbox
4. Enter any character to the search field
5. Click the search button
6. Uncheck the exercise
7. Notice that *n of n selected* indicator doesn't change the number

### Video: 
http://e.pc.cd/XFbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by jonboiser** [comment]
I'm not able to reproduce this on Kolibri 0.14.5. When you toggle topics inside of the search window, the "n of n" selected indicator is updated as expected, and you also see the snackbar appear with each change.
