### ISSUE TITLE
Lessons > Manage Resources - Filter search results by type ALL is not working if the search results are previously filtered by a specific type (exercises or topics)

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7601]
### Observed behavior

Scenario: Filter search results by type - If the search results are already filtered by Type (exercises) and then if I select All from the Type drop-down, nothing happens - I still see only exercises type listed. Same with Topics type.

### Expected behavior

If the search results are already filtered by Type (exercises) and then if I select All from the Type drop-down, all types must be listed.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Preconditions: A class and a lesson must be created beforehand. Also there must be resources imported to the device
1. Login as a super-admin user
2. Go to Coach
3. Click a Class
4. Click Plan
5. Click the Lessons tab
6. Click a lesson
7. Click the Manage Resources button
8. Do a search
9. Filter by some specific type (exercises, topics, videos, etc)
10. Filter again by type ALL

### Context

Kolibri 0.14.3
OS: Raspbian GNU/Linux 10
Device: Raspberry Pi 4
Browsers: Chrome (Latest) + Firefox (Latest)

**Comment by jonboiser** [comment]
This looks related to #5882 and other similar issues.

After looking into it, it seems that the problem that changing the filter to "All" doesn't correctly updated the URL, and thus doesn't trigger a new search.

**Comment by jonboiser** [comment]
Closing as a duplicate
