### ISSUE TITLE
The same resource can be added twice to a lesson

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7605]
### Observed behavior

Scenario: Preview a resource from the search results and add/remove it to and from the lesson 
- I am on the preview page for exercise and I click ADD button, I'm returned to the previous screen with the search results. There I see the checkbox selected for the added resource but I can again go to the preview page for the exercise I already added and I can add it one more time. So I have the same resource added twice to the lesson. Then when I go back to the Lesson screen and click Remove for one of them, both are deleted.
<img width="915" alt="2020-10-23_115350" src="https://user-images.githubusercontent.com/72492554/96978039-98b6f600-1526-11eb-9cc0-4e8b608a71c2.png">

### Expected behavior

The user can't add a resource to the lesson if this resource is already added beforehand. Possible solution: Disable the ADD button of already added resources in the preview resource page.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

  Preconditions:
  I am signed in to Kolibri as a coach user
  I am on the *Coach > Class > Plan > Lessons* page
  There is a channel and topic on the device
  There is a Lesson already created

1. Click a Lesson
2. Click Manage Resources button
3. Browse down to a single topic
4. Click ADD
5. After returned to the topics list click again the card of the topic you just added
6. Click ADD - the topic is again added

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (Latest) + Firefox (Latest)

**Comment by pcenov** [comment]
Retested today on Kolibri v0.14.7-rc2 and this is no longer an issue because as soon as one clicks the Add button the page gets reloaded, the button changes to Remove and there's a text to the left of it stating that the resource has been 'Added':
![2021-04-07_16-05-00](https://user-images.githubusercontent.com/79847249/113871275-67bc3c00-97bb-11eb-8751-609949040897.png)

**Comment by apurva-modi** [comment]
no longer an issue
