### ISSUE TITLE
The "play" button is shifted to the center of page on the lesson page while the page is loading

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7609]
### Actual result:
The "play" button is shifted to the center of the page on the lesson page while the page is loading
Expected result:
The "play" button shouldn't be shifted to the center of the page on the lesson page while the page is loading

### Steps to reproduce:

1. You are at  *Learn > Classes > '<class>' > '<lesson>'* page
2. You see <exercise1> exercise and <video> video
3. Click on <exercise1> exercise content card
4. Pay attention to the "play" button which is shifted from the video player

### Video:
http://e.pc.cd/izbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by marcellamaki** [comment]
Addressed through changes from new 0.15 features
