### ISSUE TITLE
Missing metadata details on search results topic cards

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7617]
### Observed behavior

On Create New Quiz/Create New Lesson pages the search results are missing some metadata details information in the topic cards:
- Missing description
- Missing N of coach exercises/topics it contains
- Missing N of how many exercises inside are added to the quiz/lesson

### Expected behavior

Scenario: View metadata on topic cards in search results

On Create New Quiz/Create New Lesson pages the search results topic cards must contain the following information:
- Description
- N of coach exercises/topics it contains
- N of how many exercises inside are added to the quiz/lesson

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Preconditions: Resources imported, users created, classes created
1. Login as a coach user
2. Go to Coach > Classes > Class > Plan > Quiz/Lesson page
3. Click New Quiz/New Lesson button
4. Do a search
5. Filter by Type topic and see the search results cards

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (latest) + Firefox (latest)

**Comment by jonboiser** [comment]
Could you provide a screenshot of what you're seeing?

When I tried to reproduce it, search results for Quizzes and Lessons do show

1. The number of coach content resources. (We don't count coach topics in any special way, since coach-content is a resource-level concept).
1. The description
1. And " N of how many exercises inside are added to the quiz/lesson" was not shown on the search result item, but is only shown after the item is selected (in a notification)

Also, some topics do not have a description nor coach content, and so those would be missing from those topics.

**Comment by metodimilevqa** [comment]
> Could you provide a screenshot of what you're seeing?
> 
> When I tried to reproduce it, search results for Quizzes and Lessons do show
> 
> 1. The number of coach content resources. (We don't count coach topics in any special way, since coach-content is a resource-level concept).
> 2. The description
> 3. And " N of how many exercises inside are added to the quiz/lesson" was not shown on the search result item, but is only shown after the item is selected (in a notification)
> 
> Also, some topics do not have a description nor coach content, and so those would be missing from those topics.

Well, I think this is the case - the search results just returned such topics lacking description or coach content indicators. My understanding was that all these attributes are mandatory for each search result card. So I think we might close this one.

**Comment by jonboiser** [comment]
That's correct. Not all topics have coach content or descriptions, and the "N of how many..." message shouldn't appear _on the card_, but should appear as notification on the bottom of the screen after it is actually checked-off and added to the lesson or quiz.
