### ISSUE TITLE
Styling/Rendering Issue in Coach Reports Recent

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#762]
## Summary

Floating switch(?) element inside of coach report's recent students tab. I don't know if learners are even supposed to have exercises they haven't started on the list of "recent" lessons.

## How to reproduce

1. Navigate to Coach Reports
2. Set toggle switch to `Learner`
3. Click on a user
4. Click on the 'Recent' tab
5. Click on an excercise with 0% progress

## Screenshots

*If applicable*
![image](https://cloud.githubusercontent.com/assets/9877852/21734841/78b9642e-d41a-11e6-9f99-598ba16edb92.png)

**Comment by christianmemije** [comment]
@DXCanas Currently working on this.

**Comment by christianmemije** [comment]
Styling fixed in https://github.com/learningequality/kolibri/pull/763
