### ISSUE TITLE
(Gherkin needs update) Content download button missing

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7623]
### Observed behavior

User doesn't have the option to download channel content from the 'Learn' page, even if admin has enabled the 'show download button with content' option.

### Expected behavior

When the 'show download button with content' checkbox is marked in settings, the user should see the "Download" button next to the resource under Learn/Channels.

### User-facing consequences

Users are unable to download content for offline viewing. 

Given that one aspect of the software is about offering educational opportunities to those with limited internet connections, this could reduce usability for quite a few users.

### Errors and logs

…

### Steps to reproduce

[per comments section, this ended up being expected behavior for now on Mac - skipping steps to repro]
…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment]
@kollivier I believe we disable content download by default for the Mac App, right?

@radinamatic If this is the case, we need to make a more specific gherkin story for the platforms that don't allow downloads.
