### ISSUE TITLE
No way for user to lookup their username (after 16 members) or reset their password. 

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7624]
### Observed behavior

When a facility has more than 16 members, the sign in screen changes from a list to a single box asking for a username. 

If the user forgets their username, there's no way for them to find out what it is. 

If the user does remember their username, a password box will appear. But if the user forgets their password, they can't look it up. 

### Expected behavior
Would expect a way for users to look up their username or reset password even if the facility has more than 16 members.
…

### User-facing consequences

User will be unable to login if they forget either their password or username, especially since usernames aren't displayed after the facility has 16 members or more.

### Errors and logs

…

### Steps to reproduce
[in progress]

…

### Context
macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment]
@kollivier @nucleogenesis Is this 16 user limit something that is hardcoded into the App version of the sign on screen? Where is that in the code?

This "forgotten username" issues does seem like a general problem even in the non-app version of Kolibri. To me, the only workaround is for an admin to look up the user manually in the Facility tab.

**Comment by rtibbles** [comment]
The username field provides autocomplete, so the 'lookup' functionality is there already.

There is no secure way to reset the password without another factor available. Closing as wontfix.
