### ISSUE TITLE
Export to attached drive > Cancel task - on-click the Cancel button the *N of M resources (size)* exported text is missing under the task

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7625]
### Observed behavior

Export to attached drive > Cancel task - on-click the Cancel button the *N of M resources (size)* exported text is missing under the task.

<img width="942" alt="2020-10-26_154235" src="https://user-images.githubusercontent.com/72492554/97296161-f44fef00-1858-11eb-8a74-57459873f2f8.png">
<img width="941" alt="2020-10-26_154354" src="https://user-images.githubusercontent.com/72492554/97296169-f87c0c80-1858-11eb-9e56-4de3b749c3f8.png">

### Expected behavior

After clicking the Cancel button of an Export task the *N of M resources (size)* exported text must be visible under the task as it is with all the other tasks (Import, Delete, etc)

### User-facing consequences

…

### Errors and logs

<img width="768" alt="2020-10-27_132853" src="https://user-images.githubusercontent.com/72492554/97296415-4f81e180-1859-11eb-813f-e92c33b878f4.png">
<img width="768" alt="2020-10-27_132913" src="https://user-images.githubusercontent.com/72492554/97296424-51e43b80-1859-11eb-8ac7-1d4ec911a5fb.png">

### Steps to reproduce

Preconditions: Resources imported, attached drive to the device
1. Login as a super admin user
2. Go to Device > Channels
3. Click the Manage button of a channel
4. Select some resources
5. Click the Export button
6. Select the attached drive and click Export
7. After some resources are exported click the Cancel button
8. See the text below the task

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (latest) + Firefox (latest)

**Comment by jonboiser** [comment]
@rtibbles Is this difference between canceled import/export tasks due to a technical constraint?

My guess is that we never were able to display the "N of M" message for exports because we generally can't check whether a resource is "available" on an external hard drive. (Although intuitively, I feel like the exporting device could do that tallying on it's side: e.g. increment the counter every time a transfer succeeds).
