### ISSUE TITLE
Channel > Delete a single resource - "All Resources selected" flag text is visible next to the selected single resource

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7626]
### Observed behavior

There's some kind of discrepancy when the user tries to delete a single resource from a channel - the "All resources selected" flag text appears for the selected single resource which is not very relevant.

<img width="917" alt="2020-10-26_163721" src="https://user-images.githubusercontent.com/72492554/97298925-d2f10200-185c-11eb-90d0-c7f6c069ff21.png">

### Expected behavior

When the user selects a single resource the flag text must be relevant to that selection. For example: "1 resource selected" or "Resource selected".

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Preconditions: Resources imported
1. Login as a super admin user
2. Go to Device > Channels
3. Click the Manage button of a channel
4. Browse down to a page with single resources
5. Select a single resource
6. See the flag text next to the selected resource

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (latest) + Firefox (latest)

**Comment by jonboiser** [comment]
@jtamiace Do you have any suggestions for what that label should say? I was thinking something like just "Selected" (Context: "Label for a single resource that is selected for a quiz, lesson, or other collection") would work for single resources (this would require adding a new user string).

**Comment by khangmach** [comment]
Does not look like we have "Selected" alone anywhere as its own string. @metodimilevqa your suggestion of "Resource selected" seems fine to me

**Comment by jonboiser** [comment]
The main changes will need to be done in this module:

https://github.com/learningequality/kolibri/blob/42012dfb5423a09558758425ce3e1c97da8e379e/kolibri/plugins/device/assets/src/views/SelectContentPage/treeViewUtils.js#L7

The requirement is that

1. When selecting a single resource during an import or export workflow, the right hand annotation says "Resource selected"
1. When selecting a topic, the current behavior is the same, and the the annotation says "All resources selected"

**Comment by ayu023ban** [comment]
This issue is still not resolved. 
So I would like to work on this issue.

**Comment by kmrinal19** [comment]
> The main changes will need to be done in this module:
> 
> https://github.com/learningequality/kolibri/blob/42012dfb5423a09558758425ce3e1c97da8e379e/kolibri/plugins/device/assets/src/views/SelectContentPage/treeViewUtils.js#L7
> 
> The requirement is that
> 
> 1. When selecting a single resource during an import or export workflow, the right hand annotation says "Resource selected"
> 2. When selecting a topic, the current behavior is the same, and the the annotation says "All resources selected"

@jonboiser I think that we make use of existing strings by  displaying the right hand annotation as "1 resource selected" when selecting single resource. This can be achieved by modifying the `message` attribute in return object of `fullySelectedNode` function in [treeViewUtils.js](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/device/assets/src/views/SelectContentPage/treeViewUtils.js) module as:
`message: node.is_leaf ? translator.$tr('resourcesSelected', { total: 1 })  :  translator.$tr('allResourcesSelected')`

**Comment by jonboiser** [comment]
I think the designers want the message `"Resource selected"` (no "1" in the message). So you can simply add a new message 

```
resourceSelected: "Resource selected"
```

to that `translator` class, and then replace the annotation

```
message: node.is_leaf ? translator.$tr('resourceSelected') : translator.$tr('allResourcesSelected')
```
