### ISSUE TITLE
There are no password security rules in place

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7634]
### Observed behavior

When signing up, the password can be as short and insecure as a single letter.
…

### Expected behavior

Would expect the password to have some form of security rules in place, such as at least having a minimum of 6-8 characters.
…

### User-facing consequences

This increases the likelihood of an account and/or data breach being able to happen, and could put Learning Equality at higher legal risk if it did.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibri app (for example on Mac)
2. For SuperAdmin creation, enter a valid unregistered username
3. For the password, enter for example: l
4. Proceed, and observe how you're able to create the account 
…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jindal2209** [comment]
I would like to work on this issue
The rules that can be added are
- atleast one uppercase letter
- minimum 6-8 length of password
- atleast one number
- special character

**Comment by rtibbles** [comment]
Closing this as wontfix, as the risk of security breach is low, and the reset flows are arduous in an offline environment.
