### ISSUE TITLE
(Gherkin needs update) Topics in search results do not show a description

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7642]
### Observed behavior

The user is unable to read a description of the topic.

![Screen Shot 2020-10-28 at 9 01 50 PM](https://user-images.githubusercontent.com/73143721/97524000-dcfc2900-1960-11eb-9a1c-6c4adb70d236.png)

…

### Expected behavior

Would expect to be able to view the topic description in search results, as with common search result user experience.

…

### User-facing consequences

The user is unable to read a description of the topic, which makes it harder to quickly decide which to open.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. From the class home page, click on an existing lesson (or create a new one if there is not one already existing)
3. The lesson should open under the "Reports" tab. From the lesson title box, click the "options" drop-down menu and click "manage resources."
4. Enter a search term in the search bar and click the magnifying glass
6. Filter the serach results using the "Type" drop down by clicking "Topics"
7. Observe that the results show the title of the topic, but not a description. 

Note for testing - issue occurs in scenario in line 157:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-lesson.feature

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by MindfulQA** [comment]
Similar to https://github.com/learningequality/kolibri/issues/7641, but technically that one was created for Coach-specific issue.

**Comment by jonboiser** [comment]
Not all topics have description, which is an optional field.

@radinamatic We need to add that detail to the assumptions in the Gherkin scneario: A topic should only show a description _if_ it has a description.

**Comment by nucleogenesis** [comment]
We should find some examples in the testing channel that have descriptions and share their path in the Gherkin stories.

**Comment by radinamatic** [comment]
@metodimilevqa Could you work with @pcenov to add descriptions in some topics of the Kolibri QA channel, and than add that detail in the relevant Gherkin scenarios? Thanks!
