### ISSUE TITLE
When the user clicks the "go back" button while creating a quiz, it takes them back too far

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7647]
### Observed behavior

When the user clicks the "go back" button while creating a quiz, it does not take them to the previous screen, but instead takes them to the quizzes tab on the lessons page.

Screen recording:

https://drive.google.com/file/d/1JnKsjm7k36cpDcvAL2aHb7oYcj7vl5f0/view

…

### Expected behavior

When the user clicks the "go back" button, they will likely expect to be taken to the previous screen (following the breadcrumbs seen under the search bar.)

Note: This isn't in the gherkin scenarios, and I'm not sure if it's intentional or not. But it results in a frustrating user experience.

…

### User-facing consequences

A user may lose their work by clicking the "go back" button intending to see the previous page. 
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click on a topic. 
7. Click on a subtopic (if applicable). 
8. Click on an exercise (if applicable). 
9. Observe the breadcrumbs under the search bar indicating the channel, the chosen topic, subtopic(s), and exercise. 
10. Click the "go back" button.
11. Observe that the user is returned to the "Quizzes" tab on the "Plan" page.

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment]
Ah, so "Go back" might be interpreted as "go back (the the last page viewed within the workflow)", but it actually means "go back (to the Plan > Quiz)", i.e. exit the workflow entirely.

**Comment by khangmach** [comment]
Yeah the confusion is the wording. 'Go back' sounds like it'll take the user back to the previous "node" that they navigated from. To eliminate that expectation and emphasize the continuity of steps, we need to be more deliberate about naming.

![Screen Shot 2021-06-29 at 1.29.27 PM.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/7810ff0e-72b7-43e0-b53c-d68ccc9f421a)
There is no previous step here, so we take out the secondary button here to stress that this is the first step

![Screen Shot 2021-06-29 at 1.27.38 PM.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/f686de3e-79c4-4b58-bdf5-2d4a7f665cb1)
We need to rename "Go back" to something like "Previous step", as its far more informative...

cc @radinamatic to OK string changes
