### ISSUE TITLE
(Gherkin needs update) When a coach starts/ends a quiz, it doesn't display how long the quiz has been active/inactive on the same screen

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7649]
### Observed behavior

When a coach starts or ends a quiz, it does not display how long the quiz has been active or inactive on the screen the coach is on - they have to navigate away to the quiz page to see that info, and they may not realize that.

Screen recording:

https://drive.google.com/file/d/1EOqDny3dgKFocRP0lzg-ipAesoikgXOv/view

…

### Expected behavior

After a coach starts or ends a quiz, according to the Gherkin scenarios, it should indicate how much time has elapsed since the quiz was started or ended.

This issue occurs at lines 16 and 33:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-start-end-quiz.feature

Note: the seconds do show up, but only on the quiz page. The gherkin scenario doesn't specify this - to me, it sounded like the time should show immediately after starting/ending, rather than having to navigate to a different page.
…

### User-facing consequences

The user does not know how long the quiz has been active or inactive unless they navigate to a different area that they may not have thought they had to go to in order to see it right away.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. On an existing quiz that has not been started, click "Start Quiz"
5. Click "continue" 
6. Observe the snackbar notification stating that the quiz has been started. 
7. Observe that where the button previously said "start quiz" it now says "end quiz" 
8. Observe that it does not show the time elapsed since the quiz was started.
9. Click "end quiz"
10. Observe that it now says "quiz ended" but does not show the time elapsed since it ended
11. Navigate to the quiz page, and observe how it shows the time there -- but not prior to exiting the start/end section

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment]
This Gherkin story pertains to a different part of the App: the screen where you view the details of a single Quiz. I don't think these timestamps should appear on the list of all Quizzes, which is in the video. Here's where this feature lives. We should provide that detail in the Gherkin story (as well as a specific story for the quiz-list page, if that's useful).

![image](https://user-images.githubusercontent.com/10248067/98033119-e1459d80-1dc9-11eb-8600-bf189caa95c5.png)

**Comment by jonboiser** [comment]
@metodimilevqa @radinamatic To close this issue, we need to update the `feature` file in the first post to be more specific about where the "time elapsed" message should be. The misunderstanding was that the "time elapsed" message would appear in the list of all quizzes (as in the first post), when it is actually on this page: "Coach > Reports > Quizzes > Quiz Details" (see screenshot below)

![image](https://user-images.githubusercontent.com/10248067/103688604-e698a300-4f46-11eb-88ce-7b6bfcbd875a.png)
