### ISSUE TITLE
Arabic channel descriptions are text-align'd to the left on card and topic page (should be on the right, as RTL language)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7650]
### Observed behavior

Screenshot from https://kolibri-beta.learningequality.org/en/learn/#/topics/310ec19477d15cf7b9fed98551ba1e1f

![image](https://user-images.githubusercontent.com/10248067/97616730-2b014300-19da-11eb-84e6-d1a5924737a2.png)

Screenshot from https://kolibri-beta.learningequality.org/en/learn/#/topics (middle of the page)

![image](https://user-images.githubusercontent.com/10248067/97616423-c3e38e80-19d9-11eb-895b-909288b4abdf.png)

(This might be in other places too)

### Expected behavior

I think this is because the KGrid div has a `text-align: left` rule. (Screengrab of DOM explorer for the Channel card)

![image](https://user-images.githubusercontent.com/10248067/97616588-fd1bfe80-19d9-11eb-8fca-4732dc855113.png)

RTL text should be aligned to the right edge, since that's how readers are accustomed to reading it.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
can be addressed with updates to KDS linked above

**Comment by indirectlylit** [comment]
@rtibbles FYI this can be addressed now
