### ISSUE TITLE
When copying assignment to different class + assigning to individuals, the wrong group names are in the user table

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7652]
### Observed behavior
At [this Lesson for Grade 1](https://kolibri-beta.learningequality.org/en/coach/#/17f732bf12eca15a0cf6d846c3a1c8c4/plan/lessons/a4c7a371907d0bd99d8a20fb91c12798), if you want to copy a Lesson to a different class and assign it to individuals, the "Select individual learners" table will show the names of groups for the current class, but not the destination class) in the "Group" column. 

For example, in the screenshot below, the username `buster` is in "Class 1 Group" (current class), but in "Super Group" (destination class). The other learners are in "Super Group", but their Groups column is empty.

![image](https://user-images.githubusercontent.com/10248067/97643655-9280b800-1a05-11eb-9fbe-3afa02317a8b.png)

Fortunately, if the "Super group" checkbox is clicked, `buster` is recognized as a member of that group in the destination class and is made unselectable.

![image](https://user-images.githubusercontent.com/10248067/97643697-adebc300-1a05-11eb-8817-719b36fb3e73.png)

### Expected behavior

If a user is in different groups within the destination class, then those group names are shown in the "Groups" column.

### User-facing consequences

The wrong information is in the Individual Learner table when copying lessons or quizzes

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by radinamatic** [comment]
Looking good on the UNW Chile server (with 0.14.7a4 deployed)! 👍🏽

**Comment by metodimilevqa** [comment]
I confirm the fix is successful with #7820. Verified with Kolibri v0.14.7-alpha4, Windows 10, Chrome (latest).
