### ISSUE TITLE
On Coach > Class Home page, Lessons/Quizzes progress panels have no visual change on focus or hover

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7662]
### Observed behavior

Screenshot from https://kolibri-beta.learningequality.org/en/coach/#/17f732bf12eca15a0cf6d846c3a1c8c4/home

![image](https://user-images.githubusercontent.com/10248067/98152712-00eecb80-1e87-11eb-8103-576ae6773836.png)

When you hover over these items with a mouse or focus on them with a keyboard, there is no visual difference. (A related issue is #7651 where links in general don't get any visual indicator of keyboard focus).

### Expected behavior

On mouse-hover or keyboard-focus, there is some visual change to these items on the Coach > Class Home page.

**The actual visual change might need some decisions**, because the strategy used for flat, white buttons of changing the background from white to light grey will wash out other gray elements, like the progress bar and other text. 

I can't find the exact issue, but this is something that happened on the Individual Learner selector for assignments---with the wrong grey background, the grey text and disabled checkboxes would get completely obscured.

### User-facing consequences

The issue is less pronounced when using a mouse or touchpad, but for keyboard-only navigation, it's very difficult to know where you are without some visual assistance.

### Errors and logs

…

### Steps to reproduce

1. Go to a Coach > Class Home Page
1. mouse-hover or keyboard-focus one of these Quizzes/Lessons progress cards
1. The items do not change in appearance.

### Context

…

**Comment by nucleogenesis** [comment]
Likely good to use `palette.grey.v_100` for the background as the gray used above is likely the `textDisabled` token which is `palette.grey.v_300`.
