### ISSUE TITLE
A learner can appear twice in Lesson report if first assigned as an individual, then later via a group

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7667]
### Observed behavior

Screenshot from https://kolibri-beta.learningequality.org/en/coach/#/17f732bf12eca15a0cf6d846c3a1c8c4/reports/lessons/370c891ed77adb9d2fe7a0a14eaf5183/learners

![image](https://user-images.githubusercontent.com/10248067/98294984-a7110300-1f65-11eb-9696-c5d81ba63007.png)

In the example, a user can appear twice. When running locally, Vue will also give warnings about using duplicate keys when rendering the list.

This can happen if you do things in this sequence

1. Create a Lesson
1. Assign to an individual learner (and some others, just for fun)
1. Save the lesson
1. Edit the lesson and assign it to a group with that individual learner
1. Save the lesson

### Expected behavior

On the backend, I would expect redundant ad-hoc learner groups (i.e. the data object used to assign lessons to single users) to be cleaned and superseded by the group-level assignment. Or if that's not something we want, then to at least de-duplicate the users on these reports.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. Create a Lesson
1. Assign to an individual learner (and some others, just for fun)
1. Save the lesson
1. Edit the lesson and assign it to a group with that individual learner
1. Save the lesson

### Context

…

**Comment by rtibbles** [comment]
Fixed in #9728
