### ISSUE TITLE
Learn Page App Bar layout becomes crowded at around 600px, especially with long username or "Learn" label

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7670]
### Observed behavior

The Learn Page top bar can become cramped at around 600px, which is the breakpoint, where it shifts to a a smaller window layout (< 600px)

Example at 624px:

![image](https://user-images.githubusercontent.com/10248067/98304727-67521780-1f75-11eb-8d24-026e5e9b56f1.png)

Example at 600px in `nyn` locale

![image](https://user-images.githubusercontent.com/10248067/98304862-a3857800-1f75-11eb-84e6-133cfa151d0b.png)

### Expected behavior

Ideally, the layout of the Learn Top Bar would be responsive to different variables, like the length of the username or how "Learn" is localized.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by davidgarg20** [comment]
I would like to work on this issue

**Comment by pcenov** [comment]
Tested and verified as fixed as part of https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc1 testing.
