### ISSUE TITLE
When re-ordering lesson resources with mouse, the post-drop transforms cause the container to overflow

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7681]
### Observed behavior

GIF from https://kolibri-beta.learningequality.org/en/coach/#/eec4366a19f7df2d1da28606af175b7e/plan/lessons/f30d5609ebca7de3a34de7cb1bb02433 on Safari

![CleanShot 2020-11-09 at 14 06 30](https://user-images.githubusercontent.com/10248067/98602114-d0e36600-2294-11eb-949f-a05cf36ca7e1.gif)

Notice that after each time I drop a resource, the bottom of the container shows a horizontal scrollbar, which I think is because the drop animation magnifies the item, causing an overflow.

I won't show the GIF of the analogous UI on the Reports version of this workflow, but it can be observed at [this link](https://kolibri-beta.learningequality.org/en/coach/#/eec4366a19f7df2d1da28606af175b7e/plan/lessons/f30d5609ebca7de3a34de7cb1bb02433)

This doesn't happen when moving items with a keyboard, because the transform is different.

### Expected behavior

No transient scrollbar appears after dragging and dropping and item.

This fix needs to be implemented both on the the page here (Plan > Lesson) as well as the Report > Lesson version.

### User-facing consequences

Minor visual defect

### Errors and logs

…

### Steps to reproduce

1. Create a lesson with 2+ items
1. On the Plan > Lesson, or Report > Lesson UI for reordering lessons, move an item around with your mouse
1. You will see the scrollbar appear briefly after dropping them item

### Context

…

**Comment by ayu023ban** [comment]
Hey! I would like to work on this issue.

**Comment by sairina** [comment]
I can't seem to reproduce the presence of the scrollbar on the beta site (for either the Lesson or the Reports pages). Is it possible that this has already been fixed?

![2021-03-18 13 35 48](https://user-images.githubusercontent.com/13563002/111694312-f6f2b700-87ee-11eb-8619-70a4161f40f1.gif)

**Comment by jonboiser** [comment]
I haven't tried it on that UI,  but I see it consistently on the Lesson Summary Page (under coach > plan > lesson).

Here's a GIF of the area, with a potential solution (I just increased the padding a bit more so the "zoom" doesn't cause an overflow). So if we can shrink the cards, increase the padding, reduce the size of the zoom, etc. that might fix it.

![CleanShot 2021-03-19 at 13 29 22](https://user-images.githubusercontent.com/10248067/111839027-6633de00-88b7-11eb-8148-ee57f074a3c9.gif)

**Comment by jonboiser** [comment]
Here's a video of it

![CleanShot 2021-03-19 at 13 32 34](https://user-images.githubusercontent.com/10248067/111839176-9da28a80-88b7-11eb-8fe0-d81d63994247.gif)

**Comment by pcenov** [comment]
Tested and verified as fixed as part of https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc1 testing.
