### ISSUE TITLE
Copy on ContentUnavailablePage is not customized to different roles (and has minor English punctuation issue)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7694]
### Observed behavior

From http://localhost:8000/en/learn/#/content-unavailable (viewing with my super admin account)

![image](https://user-images.githubusercontent.com/10248067/99438746-0d344900-28c9-11eb-93d0-3c57ce8d2997.png)

Link to code: https://github.com/learningequality/kolibri/blob/68f33c3f429f55c60af23d6752ba389a6ac20a0d/kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue#L8

Issues:

1. There is no comma after the subordinate clause "As an administrator" in the English localization of the link
1. The "Please ask your coach or admin" is shown to users of all roles, when it should only be shown to learners.
1. The URL is `content-unavailable`, which might be a holdover when we used "Content" as the primary user-facing term for what is now called "resources"

### Expected behavior

1. In the English locale, there should comma after "As an administrator" (and if it changes the sense of any of the other localizations, those should be updated too)
1. The `learnerText` message ("Please ask your coach") is hidden unless the user has the Learner role (and does not have the "can manage content role")
1. The URL for this page is something like `resources-unavailable`

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by kmrinal19** [comment]
Hi! I would like to work on this issue.
