### ISSUE TITLE
Numerals are not localized in some places (and use 0-9 arabic numerals by default)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7696]
### Observed behavior

Here are places on https://kolibri-beta.learningequality.org/mr that I was able to find (annotations are within the screenshots)

**Version numbers on https://kolibri-beta.learningequality.org/mr/device/#/content**

![image](https://user-images.githubusercontent.com/10248067/99457214-76bf5200-28df-11eb-9e8e-0c3426eda9d3.png)

**Number of learners in class on https://kolibri-beta.learningequality.org/mr/facility/#/a3f606630690237bbe94fe2a1a850af4/classes**

![image](https://user-images.githubusercontent.com/10248067/99457476-e5041480-28df-11eb-97bc-f3cc70a20d1b.png)

**KTextbox maxlength validations**

![image](https://user-images.githubusercontent.com/10248067/99457568-0c5ae180-28e0-11eb-9785-ba937e20a094.png)

**Time elapsed messages on various Coach Pages**
https://kolibri-beta.learningequality.org/mr/coach/#/10c12cbfc4b67630511d67f7b7895f17/reports/quizzes/70a26038f8dddffcb93f05bcec8b2095/learners (same on lessons pages)
![image](https://user-images.githubusercontent.com/10248067/99457724-46c47e80-28e0-11eb-89b3-eebcac3bc93c.png)

**Birth years on profile page and other places**

![image](https://user-images.githubusercontent.com/10248067/99457922-973bdc00-28e0-11eb-8b9e-608b68bee564.png)

### Expected behavior

If appropriate, numerals should use the Intl API's number formatter, so numbers in e.g. the Marathi (mr) locale use those numerals consistently and so on.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by Kalovelo** [comment]
Hey @jonboiser, could I work on this? As I can see [here](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/locale/mr/LC_MESSAGES/kolibri.plugins.device.app-messages.json#L23), `{v}` should be replaced with `{v, number, float}`. If that seems like the right approach, I plan on updating the rest of those occurrences :smiley:

**Comment by jonboiser** [comment]
Sure @Kalovelo, thanks for offering to help. For most of the examples, we only expect integer values, so `{v, number}` should be fine, or `{v, number, integer}`.

I have seen another issue #7598 , where it seems we do want counting numbers like "3 learners" to be localized using Marathi numerals, but I'm not sure about the birth year example.

I'll ask around and see if we should also localize the birth year to numerals as well.

**Comment by jonboiser** [comment]
@Kalovelo , I just checked to see if the the [Intl API for datetimes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) localized calendar dates for Marathi, and they do. So please include the User Profile pages that display birth year. I believe the component is `BirthYearDisplayText.vue`

**Comment by Kalovelo** [comment]
A question @jonboiser, I see that `integer` string is in [`commonCoachStrings`](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/plugins/coach/assets/src/views/common/commonCoachStrings.js#L94), however, it may be used in core views such as facility views. Should I refactor the code and move the `integer` string instance from `commonCoachStrings` to `commonCoreStrings`? 

Importing `commonCoachStrings` doesn't seem like a good idea since there's no such importing under facility folder. 

A simpler way would be to add `integer` in `commonCoreStrings`, but I believe  this is not the best solution since there would be duplications :thinking:

**Comment by jonboiser** [comment]
I think this might depend on the situation. I really think that if a number is just by itself in the template, we should be using the `$formatNumber` method instead of using `$tr('integer', ...)`. Could you see if that approach works?

Here are the doc explaining how `$formatNumber` works. https://github.com/learningequality/vue-intl#instance-methods

It is like a wrapper around `Intl.NumberFormat`

**Comment by Kalovelo** [comment]
@jonboiser, I have fixed every instance except the `maxLength` occurrence in the KTextBox component, since it is imported from kolibri's design system and there's no corresponding prop assigning label values to current/max text of the textarea. Can a better solution be provided through the design system's repository?

**Comment by nucleogenesis** [comment]
@Kalovelo - if you are actively working on this issue, can you please assign yourself to it (or I'll assign you if you cannot assign yourself).

The issue w/ `KTextBox` in the design system can be fixed separately as it may require that we include `vue-intl` as a dependency in that package to allow for i18n on the numbers there.

Most numbers that will run through design system components would be passed as props and rendered directly to the user (aka, not used for mathematics).

Seems like we might need to `{{ $formatNumber(valueLength) + '/' + $formatNumber(maxLength) }}` in [KTextBox#113](https://github.com/learningequality/kolibri-design-system/blob/0621d5de5b9a6605b3f0d35ee166d123ca6681c3/lib/keen/UiTextbox.vue#L112-L114)


---

Feel free to create a PR with the work you've completed so far though and we can track that other requirement about the design system in a follow-up issue in the [Kolibri Design System repository](https://github.com/learningequality/kolibri-design-system/issues/new?assignees=&labels=&template=issue_template.md&title=%5BTitle%5D%3A+Brief+description)

**Comment by Kalovelo** [comment]
Thank you for your answer @nucleogenesis , I will proceed with a PR 🚀
