### ISSUE TITLE
Closing `SideNav` causes it to disappear immediately, with no animation

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7700]
### Observed behavior

`SideNav` simply disappears when you close it. Whereas, when you open it, it slides out from the left with an animation.
![CleanShot 2020-11-19 at 14 23 12](https://user-images.githubusercontent.com/10248067/99731521-dd28a980-2a72-11eb-8ab6-92a17bebc93f.gif)

### Expected behavior

The `SideNav` closes with an animation.

Also, the transition uses built-in motion curves like "ease-in-out". Maybe this should be changes to the material design curves to match other motions in Kolibri

https://github.com/learningequality/kolibri/blob/52e66abb9891e10b5c05e5250f544807ea9f594b/kolibri/core/assets/src/views/SideNav.vue#L298-L301

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by kmrinal19** [comment]
@jonboiser Hi, I would like to work on this issue.
