### ISSUE TITLE
import channel from studio error

### ISSUE THREAD

**Issue by MBKayro** [learningequality/kolibri#7706]
import channel from studio error

# first build the assets
yarn run build
# now, run the Django devserver
kolibri manage --debug runserver -- 0.0.0.0:8000

However it can import using CMD
kolibri manage importchannel network <Channel ID>
kolibri manage importcontent network <Channel ID>

![Capture d’écran de 2020-11-22 13-07-01](https://user-images.githubusercontent.com/328784/99903274-b7461380-2cc3-11eb-9e09-dd4c6f54e291.png)

**Comment by rtibbles** [comment]
hi @MBKayro  - the 404 you are seeing in the console here is expected behaviour, and is what prompts the channel listing import that you are seeing the task for. Does this task not complete?

**Comment by rtibbles** [comment]
Oh, sorry the issue here is the same as https://github.com/learningequality/kolibri/issues/7705#issuecomment-732286299 you are running the devserver without the task runner, so the tasks are not being executed.

**Comment by MBKayro** [comment]
Thank  you @rtibbles its works great. 

just a question, is it possible to import channels from a local studio connected in LAN ?

**Comment by rtibbles** [comment]
Yes, in the interface it will work the same way as importing from another Kolibri instance. Alternatively, you can use an option in the `options.ini` file to set the new Studio URL.
```
[Urls]
CENTRAL_CONTENT_BASE_URL = 
```
It is not well documented, but the details of these options are here: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/utils/options.py

**Comment by MBKayro** [comment]
Hi @rtibbles,

I'm trying and without success. i'm using tow VM (studio and kolibri). 

A) Kolibri:
![Capture d’écran de 2020-11-26 18-37-50](https://user-images.githubusercontent.com/328784/100383376-c3143b80-301d-11eb-810e-c260148e2c8c.png)
![Capture d’écran de 2020-11-26 19-22-17](https://user-images.githubusercontent.com/328784/100383395-cefffd80-301d-11eb-87ad-d47552b3d651.png)
![Capture d’écran de 2020-11-26 19-28-25](https://user-images.githubusercontent.com/328784/100383406-d45d4800-301d-11eb-918d-210dbdfc3531.png)

B) studio: yarn run localprodserver
![Capture d’écran de 2020-11-26 19-31-07](https://user-images.githubusercontent.com/328784/100383529-125a6c00-301e-11eb-95f7-c3f54efa6772.png)
![Capture d’écran de 2020-11-26 19-31-26](https://user-images.githubusercontent.com/328784/100383531-15555c80-301e-11eb-906c-c2192794a826.png)

Tank you for all your help

**Comment by radinamatic** [comment]
@MBKayro If I understand correctly your test case, my intuition is that none of the channels that you have on the _Madrassati_ Studio are **public**, and therefore your *Content Library* tab is empty. 

What I would expect was to see the `Import with token` button, so you could import the unlisted channels, not sure why it's not there...? @rtibbles Could there be some Studio setting for that?

![token](https://user-images.githubusercontent.com/1457929/100387711-09bb6300-3029-11eb-880d-c2c0681c7c1d.png)

**Comment by MBKayro** [comment]
thank you @radinamatic, i was asking the same question if is there no public channel, why i can't import at least one of channel created manually using token ?

when using CENTRAL_CONTENT_BASE_URL= "default": "https://studio.learningequality.org", is whork very well but not localy

Attempting connection to: http://192.168.1.5:8080/
INFO     Success! We connected to: http://192.168.1.5:8080/api/public/info/
INFO     192.168.1.3 - - "GET /api/discovery/networklocation/a4a7f5fe-bd7e-4013-858b-c325a77e2199/" 200 0 "http://192.168.1.3:8000/ar/device/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
INFO     "GET /api/discovery/networklocation/a4a7f5fe-bd7e-4013-858b-c325a77e2199/?1606422912739=1606422912739 HTTP/1.1" 200 326
INFO     192.168.1.3 - - "GET /api/content/remotechannel/" 200 0 "http://192.168.1.3:8000/ar/device/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
INFO     "GET /api/content/remotechannel/?baseurl=http%3A%2F%2F192.168.1.5%3A8080%2F&1606422912819=1606422912819 HTTP/1.1" 200 2

**Comment by MBKayro** [comment]
hi @radinamatic  and @rtibbles,

small update, even if there is a public channel the "Import with token" button does not appear 

        <p v-if="showUnlistedChannels">  /// so if there are no public channel, disable the button
          <KButton
            data-test="token-button"
            :text="$tr('channelTokenButtonLabel')"
            appearance="raised-button"
            name="showtokenmodal"
            @click="showTokenModal = true"
          />

however, even when i try to enable always, it need a way to connect to local channel created

![Capture d’écran de 2020-11-28 22-06-22](https://user-images.githubusercontent.com/328784/100526121-47a1be00-31c6-11eb-8560-e20aa6e7e47a.png)

**Comment by rtibbles** [comment]
We don't enable 'import with token' when importing from peers, because we assume peers are other Kolibri instances, and so do not need to allow import with token, as Kolibri has no knowledge of this.

In that case, setting `CENTRAL_CONTENT_BASE_URL` to the local address `http://192.168.1.5:8080` should allow for import with tokens.

**Comment by MBKayro** [comment]
Hi @rtibbles thanks for all your help,

just the last time, i have these 3 issue:

1) problems for kolibri does not recognize options.ini  (all my change as in  options.py) 

WARNING  Ignoring unknown option in options file /home/kayro/.kolibrimadrassati/options.ini under top level: CACHE_BACKEND.
WARNING  Ignoring unknown option in options file /home/kayro/.kolibrimadrassati/options.ini under top level: CACHE_TIMEOUT.
WARNING  Ignoring unknown option in options file /home/kayro/.kolibrimadrassati/options.ini under top level: CACHE_MAX_ENTRIES.
WARNING  Ignoring unknown option in options file /home/kayro/.kolibrimadrassati/options.ini under top level: CACHE_PASSWORD.
WARNING  Ignoring ............

2) even with change in options.py, when i try to import with token
    "Urls": {
        "CENTRAL_CONTENT_BASE_URL": {
            "type": "string",
            "default": "http://192.168.1.7:8080",

A) in kolibri
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.1.7:8080/content/databases/d0ce02d9f6f64c33bacd1dbef177ceef.sqlite3

B) in studio
pagination.py:198: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'contentcuration.models.Channel'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
Not Found: /content/databases/d0ce02d9f6f64c33bacd1dbef177ceef.sqlite3
WARNING:django.request:Not Found: /content/databases/d0ce02d9f6f64c33bacd1dbef177ceef.sqlite3

3) can i make a published channel created manually a public one ?

**Comment by rtibbles** [comment]
The options need to be under the appropriate top level e.g.:
```
[Cache]
CACHE_BACKEND = ....
```
etc.

In this case it seems like the channel has not been published, as the sqlite3 file is missing.

You can make it public, you will have to use the admin interface or change in in the shell interface.
