### ISSUE TITLE
Leverage new `openInNewTab` prop of `KExternalLink`

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7712]
### Observed behavior

We're adding a new prop which allows external links to set whether or not they open in a new tab: https://github.com/learningequality/kolibri-design-system/pull/137

`KExternalLink` is slightly misnamed: it really means "not a Vue router link". It is used for both "internal links" e.g. "Explore without account" on the sign-in page as well truly external links such as to _learningequality.org_ from the privacy policy.

### Expected behavior

We should audit our use of `KExternalLink` and set `openInNewTab=true` when appropriate.

### User-facing consequences

Internal links should stay on the same tab, and truly external links should open in a new tab.

### Context

0.14.4

**Comment by YashJipkate** [comment]
Hi! I would like to work on this issue and have opened a [working PR](https://github.com/learningequality/kolibri/pull/7848) towards this. Please take a look. 

Thanks.
