### ISSUE TITLE
When guest access is enabled, the AuthMessage redirect tries to redirect you back to content-unavailable, not the content you were looking for

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7722]
### Observed behavior
When guest access to learn is disabled, if you try to access some content (because your session got timed out) it takes you to the `content-unavailable` url, and prompts you to log back in. However, the redirect will redirect you back to the `content-unavailable` page after login.

### Expected behavior
It should return me to the page I was trying to access instead.

### User-facing consequences
Losing place after session timeout.

**Comment by metodimilevqa** [comment]
@rtibbles @jonboiser could you please provide precise steps to replicate this in order to be able to verify the fix. Me and Radina tried to replicate this with these steps but we couldn't get a clear idea if the issue is fixed.

**Comment by rtibbles** [comment]
1. Go to device settings and disable Guest Access
2. Go to a specific content item
3. Copy the URL for that content item
4. Logout
5. Go back to the URL for that content item
6. You should now be at a 'content unavailable' page
7. Click to login on the page
8. Login
9. Be redirected back to the content item after login

**Comment by metodimilevqa** [comment]
I confirm the fix with the above steps. Thanks @rtibbles
