### ISSUE TITLE
Options drop-down on Coach Plan & Coach Reports pages shows strange behavior on-click 

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7727]
### Observed behavior

The Options drop-down on Coach Plan & Coach Reports pages behaves pretty strange on-click and it is pretty hard for any of the options to be selected. See video below:
![issue2](https://user-images.githubusercontent.com/72492554/102505562-d2b9f980-408a-11eb-9f81-c1969731db02.gif)

### Expected behavior

The Options drop-down toggles and stays toggled until any of the options is selected. 

### User-facing consequences

Pretty hard to Delete Lessons
Pretty hard to Edit Lessons details
Pretty hard to Copy Lessons

### Errors and logs

…

### Steps to reproduce

Preconditions: Lessons created
1. Login to the system as an admin or a coach user
2. Go to Coach > Plan > Lessons > Lesson page
3. Click the Options drop-down

### Context

Kolibri 0.14.3
Windows 10 Version 18.0.9 - Virtual machine
Kolibri Windows Application

**Comment by jonboiser** [comment]
This is related to https://github.com/learningequality/kolibri/issues/7581. The behavior on the Windows App is different in that it seems to reposition the Menu after it is opened.

**Comment by radinamatic** [comment]
Not able to replicate this in neither the macOS app (same build based on 0.14.3, provided by @kollivier) nor the 3 browsers on macOS Mojave, seems to be issue only on Windows app :unamused:

**Comment by rtibbles** [comment]
The Windows app is not in active development, so I am closing this.
