### ISSUE TITLE
Define what data Kolibri should send about the app in telemetry pingbacks

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#7732]
### Observed behavior

Currently, we send update notifications based on the data sent by the telemetry pingbacks. However, now that we have applications, it's important that we be able to identify when an app is sending the pingback so we can know when to either not send the notification (e.g. when an app must be updated via an app store), or when we should send a custom notification on where and how to update. 

### Expected behavior

Kolibri sends app and/or browser client in telemetry pingback notifications.

### User-facing consequences

Users will not get incorrect or invalid notifications within the app, and we will know more about how important our apps are to our users by having more data on app usage.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
Primary needs:
* Which app is being used, and which version of that app?
* More accuracy for installation method - important to disambiguate kolibri debian package from kolibri + kolibri-server debian packages
* Details on how the app is being served: CherryPy, uWSGI, Apache, etc
* Be able to set a project specific flag for devices that we pre-provision.

**Comment by rtibbles** [comment]
> important to disambiguate kolibri debian package from kolibri + kolibri-server debian packages

It appears that our current method for sniffing whether we are running on kolibri or kolibri-server debian packages relies on checking whether the `installation_type` function has been invoked using `uwsgi`: https://github.com/learningequality/kolibri/blob/e68cfa265b7632b2c94a5b3301199f6383ebf1a2/kolibri/utils/server.py#L585

This means that when accessing from the device tab, this will indeed report correctly - however for ping backs, the task runner is never invoked using `uwsgi` so will ping back reports will always be inaccurate in this regard.

**Comment by jamalex** [comment]
Handled in https://github.com/learningequality/kolibri/issues/7960
