### ISSUE TITLE
When exiting search during quiz creation, you are not taken back to your last topic location

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7744]
### Observed behavior

When exiting search during quiz creation, you are not taken back to your last topic location. Instead, you are taken to the top-level list of all channels.

### Expected behavior

When exiting search during quiz creation, you **are** taken back to your last topic location. E.g. if you are at "algebra 1", then start a search, when you exit the search, you are back at "algebra 1".

This is accomplished in the Lessons workflow by saving a `last_id` param in the URL when going to the search page.

### User-facing consequences

It breaks the expectation that exiting search modal will return to the previous location.

### Errors and logs

…

### Steps to reproduce

1. Start creating a new quiz
2. Browse to a topic
3. Search for something with the search input
4. Exit the search
5. You are taken to the channel list

### Context

…

**Comment by rohitgeddam** [comment]
I would like to work on this!

**Comment by jonboiser** [comment]
Thanks @rohitgeddam! The first thing you should do is get Kolibri running locally using the instructions in the Readme. After getting set up, download some exercises from Khan Academy, since those are needed to make Quizzes.

[Check out the documentation](https://kolibri.readthedocs.io/en/latest/) here for some help on setting up your local Kolibri instance to reproduce this issue and test your solution.

**Comment by jonboiser** [comment]
Fixed in #7882
