### ISSUE TITLE
Search overlay is messed up on IE9

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#775]
## Summary

* Search overlay is messed up on IE9

## How to reproduce

1. Open search overlay on IE9.

## Screenshots

![bs_win7_ie_9 0 2](https://cloud.githubusercontent.com/assets/7193975/21831068/0837dade-d756-11e6-8cd9-aea20cb88f48.jpg)

**Comment by 66eli77** [comment]
what branch is this?

**Comment by christianmemije** [comment]
@66eli77 Vue2.

**Comment by 66eli77** [comment]
@christianmemije  I cannot replicate on browserstack ie9 
![screen shot 2017-01-11 at 12 26 53 pm](https://cloud.githubusercontent.com/assets/5577205/21865063/5099e6a2-d7f9-11e6-8f65-85ee2732fb4c.png)

**Comment by 66eli77** [comment]
and the fix has merged in this PR #760

**Comment by christianmemije** [comment]
Notice from the screenshot that I was testing the remote server from yesterday. @indirectlylit Are you sure it was from the latest Vue2 branch?

**Comment by indirectlylit** [comment]
No, unfortunately I'm not sure - that was the most chaotic server deployment in the history of server deployments. (note for future historians on the subject)

I can think of a couple possible explanations:

* the code was not vue2 at all (unlikely)
* the code was vue2 + develop with merge issues (more likely)

Tomorrow I'll finally figure out all these branch issues and keep an eye out for these regressions. Sorry for the confusion.

**Comment by indirectlylit** [comment]
FYI, I am reproducing this issue in the latest `develop`.

The changes from #760 are properly merged in.

**Comment by DXCanas** [comment]
#794 Seems to address this as well

**Comment by indirectlylit** [comment]
looks good!
