### ISSUE TITLE
Manage Lesson Resources > Search Results page - filter by channel drop-down is partially hidden when no results meet the criteria

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7752]
### Observed behavior

On the Manage Lesson Resources > Search Results page - there's an UI issue with filter by channel drop-down. It is partially hidden when no results meet the criteria.

![filterDDchannel](https://user-images.githubusercontent.com/72492554/105353258-b2380e80-5bf7-11eb-90c9-8b3fac7ec6d0.gif)

### Expected behavior

The drop-down must be fully visible in case of no results meeting the filter criteria.

### Steps to reproduce

Preconditions: A lesson created
1. Login to Kolibri as an admin or a couch user
2. Go to Coach > Plan > Lessons > Lesson page
3. Click Manage resources
4. Do a search ("English")
5. When the Search results page loads click the type filter drop-down and select Videos
6. Click the channel filter drop-down and select the different options one by one until no results are shown
7. See how the drop-down is hidden at the bottom and the container needs scroll to make it fully visible

### Context

Kolibri 0.14.6rc1
Windows 7 vm
Firefox, IE, Chrome

**Comment by rohitgeddam** [comment]
Is This fixed, I can't reproduce the same. 

- When we search for a resource, only the channels related to the search should be shown in the channel dropdown, but in the above GIF, in the channel dropdown, channel which is not related to the search is also shown, which should not be the case,
