### ISSUE TITLE
Create Lesson/Quiz > Search results - on-click the search field X icon the user is not redirected to the page with all channels

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7753]
### Observed behavior

When the user manages Lesson or Quiz resources and makes a search on-click the search field X icon the user is not redirected to the page with all channels but remains on the search results page. Related to #7638

![Video-2021-01-21-140507](https://user-images.githubusercontent.com/72492554/105460888-1b219400-5c95-11eb-9b3e-011808369518.gif)

### Expected behavior

On-click the search field X icon the user must be redirected to the all channels list page.

### Steps to reproduce

1. Login to Kolibri as an admin/coach
2. Go to Coach > Class > Plan > Lessons/Quizzes page
3. Click New Lesson
4. Fill in the lesson/quiz details and click Save Changes button
5. Click the newly created lesson/quiz
6. Click the Manage Resources button
7. Do a search
8. After the search results page loads click the X icon in the search field

### Context

Kolibri 0.14.6rc1
Windows 7 vm
Chrome, Firefox IE (latest versions)

**Comment by jonboiser** [comment]
I flagged this as possibly an inaccurate Gherkin story in #7587. I don't believe the "X" button should take you to a different page. It should only clear out the search bar so the user can do a new search.

If we want to go back to the Channels Page, this should be done through a link that explicitly says "Back to channels" or something like that.
