### ISSUE TITLE
Learn > Search > Search results page - Type and Channels filter drop-downs not working after the X icon in the search field is clicked

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7754]
### Observed behavior

On the Learn section when the user makes a search and the Search results page loads the Type and Channels filter drop-downs stop working after the X icon in the search field is clicked.

![Video-2021-01-22-103900](https://user-images.githubusercontent.com/72492554/105468147-51641100-5c9f-11eb-97a3-118f36e09373.gif)

### Expected behavior

The Type and Channels filtering is working after the X icon is clicked in the search field.

### Errors and logs

No console errors.

### Steps to reproduce

1. Login to Kolibri (no matter the access type)
2. Click the hamburger menu
3. Click Learn
4. Make a search in the top right corner field
5. Use the type and channels filtering to filter the results
6. Click the X icon in the search field
7. Use again the type and channels filters

### Context

Kolibri 0.14.6rc1
Windows 7 vm
Firefox, Chrome, IE (latest versions)

**Comment by jonboiser** [comment]
@metodimilevqa PR #7801 should fix this issue by re-inserting the search term if the user clears it, then changes a filter. Could you please QA the changes?

**Comment by metodimilevqa** [comment]
@jonboiser I confirm the fix is successful with Kolibri 0.14.7a1.dev0+git.6.ge1688aad

**Comment by metodimilevqa** [comment]
@jonboiser I again experience this issue with Kolibri 0.14.7a2; Chrome, FF, Edge.
