### ISSUE TITLE
Learn > Search > Search results page - resource multiple locations modal has UI issue under IE

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7755]
### Observed behavior

On the Learn > Search > Search results page the modal which toggles on-click the multiple locations link has UI issue under Internet Explorer. The modal is not fully displayed on first click the multiple locations link and when the browser window is resized then the modal gets displayed in its full scale. When the modal is closed and the N locations link is clicked again the modal is again not fully displayed making its content almost unreadable.

![searchLocationsModal](https://user-images.githubusercontent.com/72492554/105483808-1075f780-5cb3-11eb-88ae-0bd67d8b2333.gif)

### Expected behavior

The modal is fully displayed on each click the N Locations link no matter the browser windows size. 

### Steps to reproduce

1. Open IE 11 and login to Kolibri
2. Click the hamburger menu
3. Click Learn
4. Do a search in the top right corner field
5. On the search results page find a card with N Locations link (the resource is hosted in multiple locations)
6. See the modal and resize the browser window
7. Click the modal Close button
8. Click the N Locations link again

### Context

Kolibri 0.14.6rc1
Windows 7 vm
IE 11.0.9600

**Comment by pcenov** [comment]
@radinamatic this one is no longer extant in 0.15.1:

![2022-03-22_15-02-13](https://user-images.githubusercontent.com/79847249/159488085-ee1c7cc5-d6c2-4709-9a91-530670c655ef.png)

**Comment by rtibbles** [comment]
Fixed by 0.15 updates!
