### ISSUE TITLE
HTML5 Funza content isn't displayed correctly in Internet Explorer

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7756]
### Observed behavior

The HTML5 Funza content isn't displayed correctly in Internet Explorer. The app container remains black and no content is shown. An error is seen in the console. 

<img width="578" alt="funzaIssueIE3" src="https://user-images.githubusercontent.com/72492554/105493387-014a7600-5cc2-11eb-8952-1875d0f0a2d6.png">

### Expected behavior

The HTML5 Funza app is displayed correctly.
<img width="573" alt="2021-01-22_145452" src="https://user-images.githubusercontent.com/72492554/105493539-31921480-5cc2-11eb-913b-6e07ac365b4c.png">

### User-facing consequences

IE11 users are unable to interact with the HTML5 Funza content type. 

### Errors and logs

<img width="577" alt="funzaIssueIE1" src="https://user-images.githubusercontent.com/72492554/105493384-00194900-5cc2-11eb-8230-dc53a135d496.png">
<img width="580" alt="funzaIssueIE2" src="https://user-images.githubusercontent.com/72492554/105493385-00b1df80-5cc2-11eb-8829-808e9effa3e9.png">

### Steps to reproduce

Preconditions: Kolibri QA Channel (nakav-mafak) imported
1. Using IE11 login to Kolibri
2. Click the hamburger menu
3. Click Learn
4. Click the Channels tab
5. Click the Kolibri QA Channel
6. Click the HTML5 topic
7. Click the Funza topic
8. Click the Funza Chemistry item

### Context

Kolibri 0.14.6rc1
Windows 7 vm
IE 11.0.9600

**Comment by pcenov** [comment]
@radinamatic this one is still extant in 0.15.1

**Comment by rtibbles** [comment]
I strongly suspect that this is specific to the code used in Funza, but would have to dive a little deeper to be absolutely sure.

**Comment by rtibbles** [comment]
I have confirmed that this is because of Javascript code that is internal to the Funza application, it is throwing syntax errors. We cannot fix this.
