### ISSUE TITLE
Pages scrollbar on ASB (HTML5) books disappears after using side arrows for page navigation

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7757]
### Observed behavior
Scrollbar on African Story Books is there and usable upon entering the page, but disappears after user starts to navigate by arrows on each side. Happens on both Chrome & Firefox, scrollbar does not _reappear_ when the user navigates back to the beginning, but only if they reload the page.

![asb-scrollbar](https://user-images.githubusercontent.com/1457929/105497771-9861fe80-5cbf-11eb-9383-fec1bb69d2ae.gif)

### Expected behavior
Scrollbar should be visible all the time, and reflect the current page position.

### User-facing consequences
Less options for navigation through pages.

### Errors and logs
…

### Steps to reproduce
#. Open any book from the ASB channel (scrollbar is at the bottom).
#. Start moving through pages with the right and left arrow.
#. Observe that you don't see the scrollbar anymore.

### Context
 * Kolibri version: 0.14.6rc1
 * Operating system: Ubuntu 16.04
 * Browser: both Chrome & Firefox

**Comment by udithprabhu** [comment]
I would like to work on this

**Comment by udithprabhu** [comment]
This seems to be an issue with the HTML of the resource itself.

**Comment by rtibbles** [comment]
@radinamatic can you confirm this issue is still extant on develop? If so, we should move this to the ASB repo, as it appears to be an issue with how this was cheffed.

**Comment by radinamatic** [comment]
Sure, @pcenov & I will try to replicate on `develop`! 👍🏽

**Comment by pcenov** [comment]
@rtibbles and @radinamatic this issue is still extant in v0.14.7-rc3. I would also like to point out that the scroll bar does appear again if you click on the book page allowing to quickly navigate back or forward:

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/79847249/114577552-c3d40400-9c84-11eb-899c-ab852b803aac.gif)

**Comment by rtibbles** [comment]
Sorry - wanted to check whether it is extant on a 0.15 alpha!

**Comment by radinamatic** [comment]
Tota11y my bad, I told @pcenov to test on latest RC 🤦🏽‍♀️, we'll re-test on `develop`!

**Comment by pcenov** [comment]
@radinamatic I retested this on `develop` - still the same, the scrollbar disappears if you use the arrows. But are we sure that this is actually a bug because the user can click on the book page and the scrollbar will reappear?

**Comment by rtibbles** [comment]
As @pcenov says this seems like expected behaviour - the scroller is disappearing to show the full page. Going to close.
