### ISSUE TITLE
Videos don't play smoothly in IE 11

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7758]
### Observed behavior

All the videos in Internet Explorer 11 don't play smoothly and lag.

### Expected behavior

Videos in IE11 are played smoothly.

### Steps to reproduce

Preconditions: Video resources imported
1. Login to Kolibri using IE11
2. Click the Learn section in the hamburger menu
3. Click the Channels tab
4. Click a channel containing videos
5. Click a video to load its page
6. See how the playback behaves

### Context

Kolibri 0.14.6rc1
Windows 7 vm
IE 11.0.9600

**Comment by jonboiser** [comment]
@metodimilevqa Is the video performance more smooth on different browser (but on the same Win7 VM)?

**Comment by metodimilevqa** [comment]
@jonboiser Yes, videos are played more smoothly in Chrome and Firefox (the same Win7 VM).

**Comment by metodimilevqa** [comment]
Just a detail - the same issue is also experienced with the Kolibri App

**Comment by pcenov** [comment]
@radinamatic this is not extant in 0.15.1 - the videos performance is alright in IE11, tested on a real device.

**Comment by rtibbles** [comment]
Closing as seems not to be extant.
