### ISSUE TITLE
Exercises not rendering on IE9

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#776]
## Summary

Exercises not rendering on IE9.

## Error

```
ReferenceError: 'btoa' is undefined 
```

## How to reproduce

1. View an exercise on IE9.

## Screenshots

![bs_win7_ie_9 0 3](https://cloud.githubusercontent.com/assets/7193975/21831169/b41a3aae-d756-11e6-9333-eb19dd5996c9.jpg)

**Comment by rtibbles** [comment]
Looks like we need to polyfill `btoa` for IE9.

**Comment by 66eli77** [comment]
Perseus already polufill `btoa`.  https://github.com/Khan/perseus/blob/55e99dd019440ef72418fc74321111ddbadedf74/node/common.js#L32

**Comment by rtibbles** [comment]
Interesting. Wonder where it got to then?

**Comment by 66eli77** [comment]
fixed here https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/26#discussion_r95887897

**Comment by rtibbles** [comment]
@christianmemije please confirm fix and close.

**Comment by christianmemije** [comment]
Cannot confirm. @66eli77 There are lint errors in the perseus renderer.

**Comment by christianmemije** [comment]
Can confirm that is is fixed in kolibri-exercise-perseus-render 0.2.8.
