### ISSUE TITLE
Newly imported content doesn't show up in 'Learn' tab channel list

### ISSUE THREAD

**Issue by micahscopes** [learningequality/kolibri#7765]
### Observed behavior
I imported some topics from a local instance of Studio.  Importing appeared to complete, but the content isn't easily accessible in the 'Learn' tab.  Some of it appears to be accessible going through the search and recommended tabs, but isn't consistently available.

### Expected behavior
I expect newly imported content to show up immediately and to be accessible right away.

### User-facing consequences
Users won't be able to access content after importing it.

### Errors and logs
[debug.txt](https://github.com/learningequality/kolibri/files/5876213/debug.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/5876214/kolibri.txt)

### Steps to reproduce
![content import issue](https://user-images.githubusercontent.com/389782/105907514-a8911b00-5fea-11eb-8b6c-33b4d9195064.gif)

### Context
This was on the latest `release-v0.14.x` branch (0.14.7 alpha 0, commit 50205cc00120463a42c6b8d091d8504b67d30447)

I made the channel using the latest version of Studio, which was running locally and which I'd added as a network device.

**Comment by indirectlylit** [comment]
see also https://github.com/learningequality/kolibri/issues/6653
