### ISSUE TITLE
FilterTextBox component displays two clear icons on IE11

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7768]
### Observed behavior

Kolibri App > Device > Permissions page - two X icons are seen in the search bar

In Kolibri App there are 2 separate X icons to clear the search field queries on the Device > Permissions page. Both are active and functional. 

<img width="960" alt="doubleXbutton" src="https://user-images.githubusercontent.com/72492554/105996096-91b5fb80-60b2-11eb-9250-5ebf74755a9d.png">

### Expected behavior

Only one X icon is seen in the search field.

### Steps to reproduce

1. Login in Kolibri App as an admin
2. Click the hamburger menu
3. Click Device
4. Click the Permissions tab
5. Do a search in the search field
6. Observe the 2 X icons

### Context

Kolibri 0.14.3 - App
Windows 10 vm

**Comment by radinamatic** [comment]
Can you replicate this in the browsers?

**Comment by metodimilevqa** [comment]
@radinamatic, if you mean the host machine browsers - I only experience it under IE. Chrome, FF and Edge are fine

**Comment by rtibbles** [comment]
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.
