### ISSUE TITLE
Kolibri App - Navigation issue after Search on the Learn > Channels/Recommended pages

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7769]
### Observed behavior

Seems like there's a navigation issue in Kolibri App when the user makes a search from the Learn > Recommended > Most popular page or from the Learn > Channels page. For example, if I watch a video and then close it's page from the X icon and then I do a search, after I click the X icon to close the search results page I'm not brought back to Recommended > Most popular page but to the page of the video I initially watched. The same behavior is observed under Learn > Channels page.

![popularSearchNavIssue2](https://user-images.githubusercontent.com/72492554/106009363-e95b6380-60c0-11eb-9635-c9a239d6425f.gif)

### Expected behavior

When the user closes the search results page the Learn > Channels/Recommended page is loaded but not the page with the last viewed item (video, pdf, epub, etc)

### Steps to reproduce

Preconditions: Channels imported.
1. Login to Kolibri app
2. Click the hamburger menu
3. Click Learn
4. Click Recommended tab or stay on the Channels tab
5. Browse down to a single item and click it
6. Click the X icon in the upper left corner of the page.
7. Do a Search in the upper right corner of the page
8. Click the X icon in the upper left corner of the search results page
9. See how you're back to the previously viewed single item but not to the main list in Channels/Recommended tab

### Context

Kolibri 0.14.3
Windows 10 vm

**Comment by khangmach** [comment]
I'm not sure why we redirect the user to the previous content page and I imagine this would look even more buggy and confusing to a user. Good catch

**Comment by jonboiser** [comment]
@metodimilevqa I created a PR that should fix this issue here: https://github.com/learningequality/kolibri/pull/7777

Would you mind testing it?

**Comment by metodimilevqa** [comment]
@jonboiser I confirm the issue is fixed with version 0.14.7.
