### ISSUE TITLE
Improper Placement of Modals on IE9

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#778]
## Summary

Improper Placement of Modals on IE9

## How to reproduce

1. Click Login to open login modal.

## Screenshots

![bs_win7_ie_9 0 4](https://cloud.githubusercontent.com/assets/7193975/21831277/63648d7a-d757-11e6-884a-c41fc43a64c4.jpg)

**Comment by DXCanas** [comment]
Do you know if this also applies to other modals?

**Comment by christianmemije** [comment]
Yes. It appears to apply to the other modals as well.

![bs_win7_ie_9 0 5](https://cloud.githubusercontent.com/assets/7193975/21831494/0e9495ea-d759-11e6-81b2-69b433eea75b.jpg)

**Comment by DXCanas** [comment]
I'll look into it

**Comment by indirectlylit** [comment]
see also:

* https://github.com/learningequality/kolibri/pull/600#issuecomment-256278622
* https://trello.com/c/0hRMQkwP/645-layout-of-pages-on-ie9-is-askew

**Comment by DXCanas** [comment]
Seems like this bug doesn't exist in the latest branch of develop @christianmemije can you confirm?

**Comment by christianmemije** [comment]
Does not exist on the develop branch. **Does** exist on the vue2 branch. And it looks like develop's commits have been merged into the vue2 branch.

**Comment by DXCanas** [comment]
Looks like it's back in the most recent `develop` branch.

**Comment by christianmemije** [comment]
My comment was before the vue2 branch was merged into develop. But yes this is still an issue.

**Comment by DXCanas** [comment]
Looking into it

**Comment by DXCanas** [comment]
Addressed in #794
