### ISSUE TITLE
Many component props do not have a default value

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7794]
### Observed behavior

In an update to the design system, noticed that we have the [`vue/require-default-prop`](https://eslint.vuejs.org/rules/require-default-prop.html) linter rule disabled:

https://github.com/learningequality/kolibri/blob/ce8a5899b491b21827754fa91f0678ecd8fe3b05/packages/kolibri-tools/.eslintrc.js#L88

### Expected behavior

* The `vue/require-default-prop` linter rule should be enabled
* All props should either be `required: true`, provide a `default` value, or explicitly ignore the linting rule.

A quick change would be to simply replace `required: false` with `default: null` for components that don't already specify a default. This would leave existing behavior as-is while enabling the warning for future code. Note however that care needs to be take to look for code that actually checks for `=== undefined` or `!== undefined`.

### User-facing consequences

Potential for "`undefined` has no attribute..." type bugs.

### Errors and logs

Turning on the linting rule flags about 100 problems like these:

```
...

Kolibri Linter: 
Kolibri Linter: Linting errors for kolibri/core/assets/src/views/CoreLogo/index.vue
Kolibri Linter: 
kolibri/core/assets/src/views/CoreLogo/index.vue
  14:7  warning  Prop 'src' requires default value to be set  vue/require-default-prop

✖ 1 problem (0 errors, 1 warning)

Kolibri Linter: 
Kolibri Linter: Linting errors for kolibri/core/assets/src/views/ElapsedTime.vue
Kolibri Linter: 
kolibri/core/assets/src/views/ElapsedTime.vue
  18:7  warning  Prop 'date' requires default value to be set  vue/require-default-prop

✖ 1 problem (0 errors, 1 warning)

Kolibri Linter: 
Kolibri Linter: Linting errors for kolibri/core/assets/src/views/sync/RadioButtonGroup.vue
Kolibri Linter: 
kolibri/core/assets/src/views/sync/RadioButtonGroup.vue
  50:7  warning  Prop 'itemDescription' requires default value to be set  vue/require-default-prop

✖ 1 problem (0 errors, 1 warning)

...
```

### Context

0.14.5

**Comment by indirectlylit** [comment]
why was this closed?

Note that my PR addressed it for KDS but not Kolibri

**Comment by jonboiser** [comment]
#7811 fixed it in Kolibri, but wasn't linked to this issue

**Comment by indirectlylit** [comment]
awesome, thanks @apurva-modi!
