### ISSUE TITLE
Full NotoSansGujarati and NotoSansTelegu WOFF files are being downloaded for all locales except ko and zh-hans and km

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7799]
### Observed behavior

View Kolibri in English, French, Spanish, Russian, etc. These noto-full woff files for Gujarati and Telegu are downloaded. It's only in Khmer, Korean and Simplified Chinese that this doesn't happen.

Screenshots from kolibri-beta.learningequality.org. There are slight differences in how the two browsers here handle this. I'm finding that when refreshing multiple times, Firefox does different things (sometimes doesn't download the extra files, sometimes fails on the latin noto full files). Chrome tends to be more consistent.

Chrome:
<img width="947" alt="Screen Shot 2021-02-18 at 8 40 23 AM" src="https://user-images.githubusercontent.com/10248067/108390740-d28ec500-71c5-11eb-80c6-bf2ec260192a.png">

Firefox:
<img width="847" alt="Screen Shot 2021-02-18 at 8 41 45 AM" src="https://user-images.githubusercontent.com/10248067/108390834-e508fe80-71c5-11eb-8df9-04183ceadb9e.png">

This is similar to #5939, but not as extreme (i.e. IE11 downloads all font files regardless of locale)

### Expected behavior

NotoSansGujarati and NotoSansTelegu files are not downloaded for locales that do not need these files.

### User-facing consequences

Unneeded font files are downloaded

**Comment by jonboiser** [comment]
I'm noticing that the languages this does work correctly on are the ones we introduced just recently. So basically, it seems like the `noto-subset.css` files for those three languages are correct, whilst the other languages might not be, hence the browser is having to download the full font files for Gujarati and Telegu.

Maybe when we download the new messages and update these assets for #7779  , this will be resolved.

**Comment by indirectlylit** [comment]
no longer observing this behavior

**Comment by radinamatic** [comment]
I also did not encounter this with the asset from your most recent PR, but IE11 on Windows 7 still loads all non-Latin font families.
