### ISSUE TITLE
Move automatic device provisioning feature from apps into Kolibri

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#7803]
### Description

The Kolibri app has a feature where it can automatically provision a device if a file named `automatic_provision.json` exists in `KOLIBRI_HOME` and contains provisioning information. (This function exists in `src/kolibri_tools/utils.py` in the app repo.

It was decided that this functionality would be useful for non-app installations as well, and should be moved into Kolibri proper.

**Comment by rtibbles** [comment]
Fixed in #8198
