### ISSUE TITLE
Under specific scenario the "Passwords do not match" assertion is not working and learner user is still able to login 

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7810]
### Observed behavior

If a learner user is created in superadmin profile while the "Require password for learners" is unchecked in Facility > Settings, and after the learner creation is finished and the "Require password for learners" is checked, then this learner user is prompted for password in the first ever login and is able to login with different input in Password and Confirm password field. The input in Password field is recorded as a valid password and the Confirm password input seems to be ignored. The error message for "Passwords do not match" is displayed for a while before the learner is logged in.

![Video-2021-02-23-124539](https://user-images.githubusercontent.com/72492554/108834399-ce541480-75d6-11eb-93c4-8f74161ddb1d.gif)

### Expected behavior

"Passwords do not match" assertion is preventing the user to login unless the passwords match.

### Steps to reproduce

Preconditions: "Require password for learners" is unchecked in Facility > Settings
1. Login as a superadmin user
2. Click the hamburger menu
3. Click Facility
4. Click the Users tab
5. Click New user and fill the form to create a learner account
6. Go to Facility > Settings tab
7. Check the "Require password for learners" and click Save
8. Logout and login as the new learner account
9. On the Passwords screen fill 2 different inputs in Password and Confirm password fields
10. Click Login

### Context

Kolibri 0.14.7a2
Windows 10
Chrome

**Comment by jonboiser** [comment]
@metodimilevqa This is a good catch. Does this scenario have a gherkin story?

**Comment by metodimilevqa** [comment]
> @metodimilevqa This is a good catch. Does this scenario have a gherkin story?

Well, as there are many scenarios, I can't tell for sure but I can do a check

**Comment by metodimilevqa** [comment]
@jonboiser I conform the fix is successful with #7814, the issue is no longer experienced
