### ISSUE TITLE
After registering a facility in KDP the kdp server is not found 

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7824]
### Observed behavior
When registering a facility in KDP, there is a button to register and another to sync.
If the facility is registered, clicking on the sync button does not work because no kdp server is found in the network.
After refeshing the browser page, clicking in the button works fine.

### Expected behavior

I expect to be able to sync after registering without manually refreshing the page.

### User-facing consequences

At first sight it seems syncing does not work

### Steps to reproduce
1. Register a facility in KDP using the project token
2. In the same browser window click on the sync button

### Context
- local KDP installation
- kolibri 0.14.6

**Comment by marcellamaki** [comment]
@jredrejo - is this still a problem, or has this been addressed by some of the sync status and registration changes in other versions since last year?

**Comment by jredrejo** [comment]
Just tested it and it's working with current v0.15.x branch
