### ISSUE TITLE
Design render overlay to render just the content 'in context' of a custom navigation representation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7831]

**Comment by jtamiace** [comment]
https://www.figma.com/file/4QlF8kww5CDUhJIhoIwDrh/Custom-channel-representation?node-id=0%3A1

![custom channel](https://user-images.githubusercontent.com/6668144/112694352-7449a780-8e3f-11eb-8020-162170d883e2.png)

**Comment by rtibbles** [comment]
Design complete, and transferred to the implementation issue. Closing this one.
