### ISSUE TITLE
Add `themeRender` and `version` to Hashi `window.kolibri` object

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7833]
Implement the following API methods/getters and data flow from Kolibri:

- [x]  `version`
- [x]  `themeRenderer`
- [x]  `getContentById`

See https://github.com/learningequality/kolibri-ecosystem/issues/1 for the detailed API spec.

`themeRenderer` will allow setting of two properties:
* App bar colour - this will specify the colour of the render overlay app bar.
* Text/icon colour - this will specify the colour of the text and icon in the app bar overlay

We will not enforce this, but these colours ought to be AA contrast compliant.

**Comment by jonboiser** [comment]
`getContentId` has already been implemented in #7942 , and the `version` getter is simple to implement.

@jtamiace , regarding the `themeRenderer`, here are some behaviors I'm going to add:

1. In addition to app bar and text color, i am adding optional fields for setting the modal backdrop and modal background color to provide full customization of colors for #7832. 
2. If any of the colors are invalid (e.g. bogus CSS names, HEX values, etc), calling this method will still succeed, but set the values to `null` internally. It will then log warnings to the console of the form e.g.`value for appBarcolor (ghostlywhite) is not a valid color`. As a fallback, Kolibri-level theme's colors will be used in the content renderer.
3. If the app bar color + text color fall outside of AA contrast standards, the method will also log a warning and provide a suggestion for a better color. e.g. `the values of appBarColor and textColor have a contrast ratio below the AA standard levels. A textColor value of ... would provide better contrast`
