### ISSUE TITLE
Upgrade kolibri-exercise-perseus-plugin to 1.3.4

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7837]
Things to do:

- [x] Publish kolibri_exercise_perseus_plugin==1.3.4 to PyPi
- [x] Update dependency in `requirements/base.txt`
- [x] Apply this change to 0.14 branch https://github.com/rtibbles/kolibri/commit/b8fcd70084380d23af7182d5b80e4849a5d0b93c

**Comment by Cronus1007** [comment]
@jonboiser Shall I work upon this?

**Comment by jonboiser** [comment]
Thanks @Cronus1007 , but publishing to PyPi requires being a maintainer of the project.

**Comment by Cronus1007** [comment]
@jonboiser Yes I agree. No issues.
