### ISSUE TITLE
Remove HierarchyRelationsFilter and enforce explicit permissions model

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7842]
### Observed behavior
Our current role permissions and membership model allows for nested membership, and role permissions.

In practice, we require explicit membership of any collection. Each user is assigned to a specific Facility, and we only allow learners to be in LearnerGroups or AdHocGroups via the frontend interface if they are already a member of the relevant Classroom.

Through our user interface we only allow users to be Admins or Coaches at the Facility level, and at the Classroom level we only allow Coaches.

We do not allow assignment of role permissions to any other collections through the interface.

In order to support the more general permissions model, we use the HiearchyRelationsFilter to determine many permissions and membership checks. However, we have seen multiple cases where the HierarchyRelationsFilter causes significant performance issues in Facilities with a modestly (100+) sized collection tree (c.f. #6721, #7823).

### Expected behavior
Permissions and membership checks should only rely on the explicitly used membership and role assignment that we use.

We should enforce this pattern, rather than simply relying on it to be put in place by convention through the UI, so we should add validation to the serializers and the models where relevant.

We should remove HierarchyRelationsFilter in the process.

### User-facing consequences
Performance issues

**Comment by Aadi71** [comment]
I would love to work on this issue :)

**Comment by iharshit009** [comment]
Is @Aadi71  working on it? If not should I work on this one @rtibbles?

**Comment by rtibbles** [comment]
I am already assigned to this and am working on it.
