### ISSUE TITLE
error message on exercise should "refresh" if another error happens

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#785]
## How to reproduce

 1. Enter a weird answer into an exercise, and get the error message (screenshot below) to appear
2. Enter another weird one

System does not give feedback whether there is still an error, has impression that it's "frozen"

## Screenshots

<img width="767" alt="screen shot 2017-01-12 at 2 37 05 pm" src="https://cloud.githubusercontent.com/assets/6668144/21911241/c2d9ad0c-d8d4-11e6-8270-69c7783a806b.png">

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by indirectlylit** [comment]
What kind of feedback would be appropriate? Should the message maybe fade out and back in again?

**Comment by 66eli77** [comment]
I think Devon's solution would work. Any ideas @jtamiace ?

**Comment by khangmach** [comment]
Ideally, the error message alert should disappear the moment you start deleting your submitted answer. It would reappear once you hit "Check answer" once again.

I don't think it should fade out and back in the case that a user gets distracted and the error message disappears. Kind of confusing.

**Comment by 66eli77** [comment]
but what if the user not delete any but add on to the answer

**Comment by khangmach** [comment]
any kind of typing within the input field should make the error message disappear until they check their answer again.
