### ISSUE TITLE
Clicking breadcrumb from within Recent tab in Coach Reports returns an empty list of user icons

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#786]
## How to reproduce

1. Go to coach reports Recent tab
2. Click any content item title
3. Click a breadcrumb item
4. Should have an list of icons but no names, like below

## Screenshots

<img width="1241" alt="screen shot 2017-01-12 at 2 48 06 pm" src="https://cloud.githubusercontent.com/assets/6668144/21911618/5e6365aa-d8d6-11e6-828c-dc7036378a4f.png">

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by indirectlylit** [comment]
I think the main bug here is that breadcrumbs are displayed at all in the recent tab - that sounds like a regression.

At least according to the original design, Recent was supposed to be channel-wide all the time.

(cc @christianmemije )

**Comment by indirectlylit** [comment]
Whoops - I misunderstood the steps to repro. Please disregard the above.

**Comment by christianmemije** [comment]
**Steps to reproduce:**

1. Open coach reports.
2. Click on view by learners.
3. Click on a learner.
4. Click Recent tab.
5. Click on All Learners via breadcrumb.

**Comment by indirectlylit** [comment]
Hm I see. So this is now happening because I made clicking 'learners' always switch to the learner view as in #728
