### ISSUE TITLE
Design interface for a coach user to select a channel quiz and assign it like a regular quiz

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7861]
Coach users will be able to choose a channel quiz instead of choosing one or more exercises to add to the quiz.

Coach users will have the number of questions automatically set to the number of questions in the channel quiz.

Coach users will have the randomization set to the randomization of the channel quiz.

**Comment by khangmach** [comment]
Updated designs here:
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/?node-id=2070%3A90233

Full flow:
![channel-based quiz assignment.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/f02eecd2-c47a-4e24-871d-b7fa031aa642)

**Comment by rtibbles** [comment]
Designs finalized, handing off to dev.
