### ISSUE TITLE
Provide a way to read the full username for narrower windows (e.g. tablet and mobile)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7870]
### Observed behavior

#7867 Resolved some layout issues in the Learn Page, when the viewfinder is narrow, but now causes the username to be truncated in the other SPAs, even though there is enough room.

**When window is around 650px**

![CleanShot 2021-03-16 at 15 20 04](https://user-images.githubusercontent.com/10248067/111388309-452b7d00-866c-11eb-8daa-6e5ea7176f67.png)

However, in the other SPAs, the username will inevitably be truncated at mobile phone dimensions to accommodate the page labels on the left independent of the locale and the label used by the SPA.

**Using IPhone X simulator in chrome**

![image](https://user-images.githubusercontent.com/10248067/111388341-52486c00-866c-11eb-9be7-544b97220af6.png)

### Expected behavior

The username should be readable if there is enough room (e.g. on tablet or small laptop screens) in the non-Learn SPAs.

The username should be readable somewhere (maybe in the menu) on smaller screens (e.g. mobile phone).

For example in Twitter, it appears in a pop up by the menu

![image](https://user-images.githubusercontent.com/10248067/111388592-cdaa1d80-866c-11eb-97a1-56dc1ea7b616.png)

GitHub has a similar approach.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by Priyaraj17** [comment]
What if we make the font smaller? @jonboiser

**Comment by khangmach** [comment]
Addressed with new menu scoped in 0.15 single user syncing work

![new menu.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/48728eff-1aa9-4542-8d86-740b31a5f893)

**Comment by rtibbles** [comment]
Fixed.
