### ISSUE TITLE
New iconography for learning activities

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#7874]
- Watch
- Read
- Listen
- Reflect
- Practice
- Play/Interact/Experiment
- Create/Make

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on it?

**Comment by nucleogenesis** [comment]
Please provide the icon labels that you'd like to have for these as well as any colors (if any). @jtamiace (cc @radinamatic )

**Comment by nucleogenesis** [comment]
@khangmach can you please see https://github.com/learningequality/kolibri-design-system/issues/232 and provide the necessary information in a comment or directly edit the issue description if you'd like. 

That'll be everything we need to do the work on that issue from there and then this issue can be closed.
