### ISSUE TITLE
A dynamic flow through resource engagement that shifts focus from the resource to next step navigation as appropriate

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#7875]

**Comment by khangmach** [comment]
**Figma page:**
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=2469%3A99633

**Context:**
Right now after a learner completes a resource in a topic or lesson, they're awarded points and an option to move on to the next available resource in-topic/lesson. We're shaking this up a bit by giving them choice and directionality on where to focus their attention next:
- they can stay and practice more
- they can move on to the next resource in line
- they can move on to related resources from a related topic

**Core changes:**
-  Removing traditional points custom snackbar
-  Removing the "next item" custom snackbar
-  [Show one custom completion dialog component after the learner completes the resource. This dialog includes the information found in the points snackbar and some more options for engagement. ](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=542%3A47907)
- [Introduce different responsive form factors for this dialog component](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=2254%3A6)
- [Introduces a few new icons](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=2469%3A99636)
- Introduce an easy way to move on to the next topic/lesson when learner completes the current. Issue describing this [here](https://github.com/learningequality/clearinghouse/issues/595)

**Related design work**
- Uses the [new learning activity icons](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/?node-id=1192%3A0)
- Incorporates the new information sidebar (context [here](https://app.zenhub.com/workspaces/kolibri-ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/7873))

**Comment by marcellamaki** [comment]
Dev github issue created/handoff complete
