### ISSUE TITLE
Scrollbar suddenly appears and disappears in edit user modal

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#788]
## How to reproduce

1. Log in as admin
2. Go to Manage
3. Go to Users
4. Click pencil/edit user icon

## Screenshots

![scrollbar appear](https://cloud.githubusercontent.com/assets/6668144/21912042/7832610a-d8d8-11e6-9363-27341b4ec14f.gif)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by DXCanas** [comment]
Tested in #791, seems to work just fine.

**Comment by DXCanas** [comment]
#791 merged
