### ISSUE TITLE
Learn - Browse by categories and tags across all channels

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#7884]

**Comment by jtamiace** [comment]
Workspace 
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=19%3A13


[Interactive prototype](https://www.figma.com/proto/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?page-id=9%3A2&node-id=1475%3A14322&viewport=456%2C174%2C0.06612226366996765&scaling=min-zoom)

**Comment by rtibbles** [comment]
This issue is complete.
