### ISSUE TITLE
remove material-design-icons dependency from kolibri tools

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7890]
### Observed behavior

`material-design-icons` is [a dependency of `svg-icon-inline-loader`](https://github.com/learningequality/svg-icon-inline-loader/blob/9f137b273af978eda901c6f92b648be30322a15d/package.json#L35) which is [a dependency of `kolibri-tools`](https://github.com/learningequality/kolibri/blob/5df5f30aac0daf0ab97e5fb79e9a3555a9679618/packages/kolibri-tools/package.json#L74)

### Expected behavior

The design system should have pre-processed icons built-in, negating the need for any `material-design-icons` dependency.

### User-facing consequences

Many unnecessary MB of data downloaded, and occasional inscrutable errors

* https://github.com/learningequality/kolibri/pull/7881
* https://github.com/learningequality/studio/issues/2096
* https://github.com/learningequality/studio/#yarn-and-javascript-dependencies

### Errors and logs

```
There appears to be trouble with your network connection. Retrying...
```

### Context

0.14

**Comment by jonboiser** [comment]
I think @nucleogenesis is looking into this. We just need to remove any leftover `mat-svg`s in the Kolibri codebase and then we can safely remove this big dependency.

**Comment by indirectlylit** [comment]
awesome. Should be easy to hard-code those into components or local text files
