### ISSUE TITLE
Uncaught ReferenceError: kolibriGlobal is not defined - error while accessing server through LAN

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#790]
## Summary

Server started with `kolibri manage devserver --debug -- 0.0.0.0:8000 --webpack --qcluster`, working locally but gives `Uncaught ReferenceError: kolibriGlobal is not defined` when accessed from another device in the LAN.

## System information

 - Version: latest develop
 - Operating system: local server running on Chrome/Ubuntu 
 - client device: Chrome/OSX

## Traceback or relevant snippet from server.log or browser console

```
Uncaught ReferenceError: kolibriGlobal is not defined
```

## Screenshots

![kolibriglobal-not-defined](https://cloud.githubusercontent.com/assets/1457929/21912263/1f65bf98-d925-11e6-8cf4-a1c31726c282.png)

**Comment by rtibbles** [comment]
You can't access the dev server over LAN

You have to run it in production mode

Because the dev server serves its javascript from a webpack dev server at 127.0.0.1:3000, which is not accessible over LAN.

**Comment by radinamatic** [comment]
Darn, I knew there was a catch somewhere... :unamused: 

I was able to do in with KA Lite, but this one is cooked differently!

**Comment by jamalex** [comment]
We can probably find a way to set up the devserver to proxy through cherrypy to the webpack server.

**Comment by jamalex** [comment]
For now, if you run `npm run build` first and then leave `--webpack` off of the devserver command, should it work?

**Comment by rtibbles** [comment]
Should do.

**Comment by radinamatic** [comment]
LE magic: Kolibri dev server in IE on a VM of another LAN device! :tada: 

```
npm run build
kolibri manage devserver --debug -- 0.0.0.0:8000 --qcluster
```

![kolibri-lan-yes](https://cloud.githubusercontent.com/assets/1457929/21912731/fc3404e6-d927-11e6-91f5-f08b5d39ab60.png)

**Comment by radinamatic** [comment]
Solved, closing!

**Comment by indirectlylit** [comment]
:tada:

**Comment by radinamatic** [comment]
@radinamatic TODO  - document in RTD under developer docs.

**Comment by radinamatic** [comment]
Workaround documented in #802, closing!
