### ISSUE TITLE
Make a separate card component for non-ContentNodes (e.g. lessons, quizzes, classes)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7906]
Looking at the diff for https://github.com/learningequality/kolibri/pull/7883/files, I realized that we use the `ContentCard` for at least 4 non-contentnode objects (lessons, quizzes, channel metadata, and classrooms). This forces us to provide the `ContentCard` props like the new `is_leaf` field, when that doesn't make sense for e.g. a class.

We should have a separate card component(s) for non-content nodes to remove code bloat (to handle the idiosyncrasies of non-contentnodes) and keep the existing `ContentCard` focused on displaying resources (while we're at it, we should rename it to "ResourceCard" to reflect the new preferred usage of "resource" over "content").

**Comment by udithprabhu** [comment]
I would like to work on this.

**Comment by jonboiser** [comment]
@udithprabhu This issue isn't ready to work on yet. I need to do some refactoring of `ContentCard` and do technical design for the new components.

**Comment by udithprabhu** [comment]
Ok, thanks for letting me know

**Comment by MisRob** [comment]
Closing since we addressed this during 0.15 hybrid learning work - e.g some new cards can be found here https://github.com/learningequality/kolibri/tree/release-v0.15.x/kolibri/plugins/learn/assets/src/views/cards
