### ISSUE TITLE
Implement integrity check of job_storage database at startup and clear if broken

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7907]
### Observed behavior
If something like an unclean shutdown has caused the job_storage sqlite file to be in a bad state, then any subsequent queries to the Tasks database may result in errors.

### Expected behavior
We should attempt to read any extant jobs in the tasks database at startup, and if it results in an error and is using SQLite, clear the file.

### User-facing consequences
Unclean shutdowns that leave the job storage database in an unclean state could prevent the usual 'clear at startup' that we do, and then leave 500s coming from queries to the Task API.

**Comment by vkWeb** [comment]
@rtibbles the recent update of making jobs persistent across server restart might have some implications on this bug...? Do we still need to address this issue, since now, we don't clear jobs on startup?

**Comment by rtibbles** [comment]
Yes, it is still possible for this to get into this state, this is also in spite of us trying to do some integrity checking on the database at initial startup: https://github.com/learningequality/kolibri/blob/44bf1ed3591321f4b7ef7c4e5c6ceda8c01db7ae/kolibri/core/tasks/main.py#L72

**Comment by vkWeb** [comment]
@rtibbles umm, I will look into this deeply tomorrow and I'll report you on slack about a potential fix.
