### ISSUE TITLE
Context not transferred from Crowdin

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7916]
### Observed behavior

Initially noted by @radinamatic 

This [Vue SFC](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/plugins/learn/assets/src/views/classes/ClassAssignmentsPage.vue#L68) did not have the [context for its translation](https://crowdin.com/translate/kolibri/3798/en-es?filter=basic&value=0#275962) transferred into the code.

This issue should be fixed in the context of 0.15. This work may ultimately be blocked by some necessary work in  https://github.com/learningequality/kolibri/issues/7709 

### Expected behavior

`yarn transfercontext` should transfer all context from Crowdin into the components associated with the translation strings.

### User-facing consequences

Internal facing only - but context will not be available in the code, which can result in losing context when uploading the next round of translations. 

### Context

Kolibri 0.15

**Comment by comradekingu** [comment]
Is that supported in the format? https://docs.weblate.org/en/latest/formats.html?highlight=vue#translation-types-capabilities doesn't have it for JSON. Why use Crowdin though?

**Comment by nucleogenesis** [comment]
Apologies for the long delay @comradekingu

We use Crowdin as it provides our translators with an excellent interface for performing translations, seeing the context in which their translations are viewed and for our team to audit everything as we need.

We interface with Crowdin via their API and synchronize strings that provide context between the two while we perform our translations.
