### ISSUE TITLE
Swagger API Explorer does not work in Kolibri 0.15

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7917]
When going to http://localhost:8000/api_explorer/, the Swagger UI does not appear, and you see all of these 404 errors in the Network tab when trying to serve stuff from `/static`

![Broken Swagger Network Calls](https://user-images.githubusercontent.com/10248067/112386302-fa35e900-8cad-11eb-93ef-90034e0cd9d5.png)

This might have been caused by changes in https://github.com/learningequality/kolibri/pull/7254

The Swagger UI still works in 0.14

**Comment by jonboiser** [comment]
This is also affecting the UI for Django Rest framework. The HTML is more readable, but the missing JS seems to make the forms non-functional

![image](https://user-images.githubusercontent.com/10248067/112386976-af68a100-8cae-11eb-981d-32fe1119639a.png)

**Comment by rtibbles** [comment]
Yes, I think you've pin pointed the issue. I think the best solution to this would be to fix https://github.com/learningequality/kolibri/issues/7792, which would mean that we could always have static files available, without ever running collect static.

**Comment by rtibbles** [comment]
Fixed in #7920
