### ISSUE TITLE
On ContentPage, provide a way to view long, unbroken titles and descriptions that doesn't overflow rest of container

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7919]
### Observed behavior

From KA (km) channel

https://kolibri-beta.learningequality.org/en/learn/#/topics/c/33c22ff579d15a8fa856d149526b0d22

![Long Khmer Title](https://user-images.githubusercontent.com/10248067/112394994-d331e400-8cba-11eb-8ca9-c878bba90a52.png)

The title, which is a long sequence of Khmer glyph, causes the KPageContainer to overflow.

### Expected behavior

Because not all browser know how to handle word-breaks in SEA languages, it would be nice to have a more elegant way to show these longer-than-usual titles, but in a way that doesn't overflow the container.

Edit (5/14/21): Khmer Word-breaking seems to be improved on Firefox/Chrome/Safari. The same resource no longer renders as a single line on the current version of these browsers.

**For contributors: This issue is not ready to work on, since we need to figure out some designs for this**

* Maybe only the title should be scrollable? 
* Maybe the title should be truncated and handled like #7915 , where the full title can be read when hovering with a mouse?

**Comment by Priyaraj17** [comment]
I am not able to reproduce the error..

**Comment by jonboiser** [comment]
I'm not seeing this problem any more with the KA Khmer content (it's possible that browsers might have recently improved their handling of Khmer), but the problem is still there. Here is an example with a fake title

![image](https://user-images.githubusercontent.com/10248067/118331719-d2991b00-b4bd-11eb-80a1-28c8a90367bf.png)

**Comment by khangmach** [comment]
Addressed with 0.15 content renderer updates
