### ISSUE TITLE
Fix widgets that are using KLabeledIcon in the Facility Page + Device Page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7921]
Here are some breakages in layouts using `KLabeledIcon` after 
https://github.com/learningequality/kolibri-design-system/pull/195

I think these can probably be fixed by moving the misaligned elements into the `label` slot.

Screenshots in Safari

**http://localhost:8000/en/facility/#/data**

![Sync title alignment](https://user-images.githubusercontent.com/10248067/112403273-59562680-8ccb-11eb-9d9c-1ec7939778ca.png)

**http://localhost:8000/en/facility/#/users**

![Role label](https://user-images.githubusercontent.com/10248067/112403395-8f93a600-8ccb-11eb-9b7a-eb50a3b37ffc.png)

**http://localhost:8000/es-419/device/#/content/channels/95a52b386f2c485cb97dd60901674a98**

Coach labels

![image](https://user-images.githubusercontent.com/10248067/112519855-00809f80-8d58-11eb-8c82-fa9dc4bf4583.png)

**http://localhost:8000/es-419/device/#/content/manage_channel/a791922463b2587f9a8f3987efe8b7c9**

Unlisted channel (lock) icon

![image](https://user-images.githubusercontent.com/10248067/112521691-0bd4ca80-8d5a-11eb-85cf-2eae1dbcd152.png)

**Comment by Priyaraj17** [comment]
Is this issue open? May I work on it?

**Comment by jonboiser** [comment]
@Priyaraj17 Sure, thanks for offering to help!

**Comment by Priyaraj17** [comment]
I will set up the environment. I will start as soon as possible. Thanks

**Comment by Priyaraj17** [comment]
Sir, I am facing some issues in setting up the environment. Please allow me some more time. I am working on it.

**Comment by jonboiser** [comment]
@Priyaraj17 can you share a screenshot of what it looks like on your screen? Are you running the `develop` branch of the code?

**Comment by Priyaraj17** [comment]
@jonboiser Here are the screenshots:
![screencapture-localhost-8000-es-419-device-2021-04-02-22_26_34](https://user-images.githubusercontent.com/40101776/113437200-da1bcd80-9403-11eb-973a-ffc8364373d0.png)

![image](https://user-images.githubusercontent.com/40101776/113437182-cd977500-9403-11eb-8d48-a3a066d74d4c.png)

Yes, I am using the develop branch.
