### ISSUE TITLE
Display KLabeledIcon in Coach page BackLink as a full-width block element

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7922]
The BackLinks in the Coach Page are not displayed as block elements in Safari, so they look like this.

![Back links](https://user-images.githubusercontent.com/10248067/112403851-6fb0b200-8ccc-11eb-9cad-1130bd999263.png)

This can probably be fixed by copying what is done in the SignInPage and applying it here to BackLink component

SignInPage:

https://github.com/learningequality/kolibri/blob/8cec1c2b8579047b11ffc0564e6b5fb1e41f66d4/kolibri/plugins/user/assets/src/views/SignInPage/index.vue#L11-L13

Coach BackLink

https://github.com/learningequality/kolibri/blob/8cec1c2b8579047b11ffc0564e6b5fb1e41f66d4/kolibri/plugins/coach/assets/src/views/common/BackLink.vue#L4-L7

**Comment by Priyaraj17** [comment]
@jonboiser, May I work on this issue? I have been constantly looking to work on issues? Can you please help me a little?

**Comment by nucleogenesis** [comment]
@jonboiser pretty sure this is a Safari-only issue and was fixed in https://github.com/learningequality/kolibri-design-system/pull/195

@Priyaraj17 thank you for the interest here, I will be closing the issue. You could give https://github.com/learningequality/kolibri/issues/7455 a look for an issue that has clear expectations - but please to be sure to reach out if you have questions.

**Comment by jonboiser** [comment]
@nucleogenesis No, this is still extant, even after the PR. The BackLinks looks fixed on the Sign-Up page, because of the `display:block; width:100%` rule, but not on the coach pages because the BackLinks are lacking those rules. The screenshots come from after updating to kolibri-design-system with PR 195.

**Comment by Soren568** [comment]
I am unable to replicate this in Safari on macOS Sonoma 14.0 - I see the element is displayed using inline-block as well. Is this issue still occurring and is there a certain environment needed to reproduce it? If not it can likely be closed

**Comment by pcenov** [comment]
Hi @radinamatic I confirm that this issue is no longer extant in Kolibri 0.16 in Safari version 15.6.1.

**Comment by nucleogenesis** [comment]
@pcenov <3 thanks!
