### ISSUE TITLE
Update UI to eventually support H5P as a resource type

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7925]
The UI is missing some elements when H5P content is loaded into it:

## Missing Icons

![CleanShot 2021-03-25 at 11 09 15](https://user-images.githubusercontent.com/10248067/112522729-36735300-8d5b-11eb-9707-e92824bc2cc5.png)
![CleanShot 2021-03-25 at 11 08 35](https://user-images.githubusercontent.com/10248067/112522735-370be980-8d5b-11eb-90f8-4ac5cc27312c.png)
![H5P - no icon](https://user-images.githubusercontent.com/10248067/112522738-37a48000-8d5b-11eb-95b1-c2df67c1f6c3.png)

## Missing Metadata (?)

Here, the download button seems barebones (for other content type, the label has a more descriptive phrase + the filesize)

![CleanShot 2021-03-25 at 11 09 06](https://user-images.githubusercontent.com/10248067/112522834-5571e500-8d5b-11eb-8787-43b7bdd27877.png)

**Comment by Priyaraj17** [comment]
Hey, I am looking for issues to work on. Is this issue open?

**Comment by rtibbles** [comment]
There is not a clear path to resolution here yet, so I'd recommend looking at a different issue.

**Comment by MBKayro** [comment]
@jonboiser  is is possible to know where i wan find this content "H5P samples" ? there is no a guideline to how create a channel with h5p APP.

**Comment by rtibbles** [comment]
This issue should be redundant with changes upcoming in 0.15, where content kind will no longer be a primary thing displayed to end users. Learning Activities will be used instead.
