### ISSUE TITLE
design for updates to setup wizard to support individual learner syncing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7933]
https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#bb9db6abe670454286220b3df851980a

**Comment by jtamiace** [comment]
https://www.figma.com/file/w3raYcGRUhhaVm1Of8Dcvo/0.15-Device-setup?node-id=142%3A20

**Comment by rtibbles** [comment]
Closing - further hand off to happen in #8166
