### ISSUE TITLE
UI and UX design for automated syncing behaviors of individual learner syncing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7934]
https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#89392dfe200c4175aa45c1b89daef4c2

**Comment by khangmach** [comment]
designs updated on this zenhub issue:
https://app.zenhub.com/workspaces/kolibri-ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/7999

**Comment by khangmach** [comment]
Here are the current designs for learner syncing states. Full design figma documentation [**can be found here**](https://www.figma.com/file/MkIaNq2w3sx4Sh2uVOd35K/Coach-and-learner-notifications-SUS?node-id=11%3A643)

![sync statuses learner.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/cf5bf289-e322-46ec-abfd-c08141c7f8b5)

**Special case:**
When a device is set up as a limited device/individual learner device, we need to display a special indicator on the user menu and drawer briefly explaining the device is in learning mode and certain tabs are disabled.

![drawer.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/225cbe8e-60c4-4694-a968-6a3724fa311a)

**Comment by indirectlylit** [comment]
@khangmach in [this thread](https://learningequality.slack.com/archives/C0LKG14NL/p1623351233089500?thread_ts=1622834430.077100&cid=C0LKG14NL) @jamalex requested:

> Could we have a Google Doc with the full set of statuses and strings, to comment/iterate/finalize those?

Let's do that before iterating more on the wireframes. Let me know if I can help – we can cohack on it if you'd like to schedule a working meeting.

> Special case: When a device is set up as a limited device/individual learner device

For 0.15 this is not a special case – automated syncing will only work with limited devices. In a future release this might be relaxed.

See [Overview of "personal device" scenarios](https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#ae1a93e1daac440a9bd9d645e8a6e780) table:

![image](https://user-images.githubusercontent.com/2367265/122076813-30749780-cdc9-11eb-902a-2b85065a5a0b.png)

**Comment by khangmach** [comment]
>Could we have a Google Doc with the full set of statuses and strings, to comment/iterate/finalize those?

@indirectlylit @jamalex this sync status doc was submitted in that thread a couple of days ago. Feel free to add some comments
https://docs.google.com/document/d/1covX9is64XhN7ImzWORRBzUfl5yZhFUTViClvTAIq6s/edit?usp=sharing

**Comment by indirectlylit** [comment]
ah didn't see that - thanks!
