### ISSUE TITLE
Investigate: (UNW) Import failure messages appears but channel appears in Device tab

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#7945]
### Acceptance Criteria

- [ ] Find a way to regularly replicate this.
- [ ] If you can replicate this, describe the issue as completely as you can. If you cannot, then explain what you've tried in this issue in a comment.
- [ ] If this is a quick fix (~45mins from start to PR)- fix it, otherwise create a new issue following up on this with what you've learned.

### Observed behavior
Reported by UN Women:

> When updating the channel on the server, tasks often report as failed (as below), but on the Device tab the new version is shown.
 
![image](https://user-images.githubusercontent.com/22602993/113449139-2e568b80-93cb-11eb-93b3-0b10269bc9f0.png)

### Context
Tell us about your environment, including:
 * UN Women India server v0.14.6

**Comment by marcellamaki** [comment]
Closing as @lauradanforth says this has not been a continual issue. Can re-open as needed if it comes up again!
