### ISSUE TITLE
Exporting CSV file that contains Unicode text fails on Python 3 on Windows

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7946]
### Observed behavior
User reports of CSV file export failing prompted me to add a test for this in a Windows environment in https://github.com/learningequality/kolibri/pull/7899.

When Unicode text should be inserted into the exported CSV, such as a Unicode username or full_name, then an error occurs on windows.

```
Error trying to write csv file: 'charmap' codec can't encode characters in position 29-35: character maps to <undefined>
```

### Expected behavior
CSV Export should work on all platforms.

This is fixed by this commit: https://github.com/learningequality/kolibri/pull/7899/commits/c088d08b3e6c4a0f4194a17062457cbd7ae34816

### User-facing consequences
Windows users are unable to export CSV files.

**Comment by jonboiser** [comment]
Fixed in #7947
