### ISSUE TITLE
Update installation_type function to read from an environment variable

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7957]
## Observed behavior
Currently the `installation_type` function: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/server.py#L564 uses a series of sniffing steps to try to infer how the package in question was installed.

The reliance on the `sys.argv` sniffing in particular causes issues in disambiguating the `kolibri` debian package from invocations of Kolibri from within the `kolibri-server` debian package. In the device info page, this works, as the requests are being handled by a process launched by uwsgi - however, for analytics pingbacks, the worker process is not launched by uwsgi, so the wrong info is inferred.

## Expected behavior
We should instead set an environment variable `KOLIBRI_INSTALLATION_TYPE` inside the invocation scripts of each of our installers, and use that to infer the proper type.

**Comment by Priyaraj17** [comment]
Hey, May I work on this issue?

**Comment by rtibbles** [comment]
Yes, please do - this is just for the change in Kolibri, so should just be about reading the installation type from the environment variable.

**Comment by Priyaraj17** [comment]
Okay, thanks
