### ISSUE TITLE
Collect enhanced telemetry data

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7960]
Get more accurate and better reporting of user devices, including:
* Browser information of client devices
* Accurate installer information
* Information about apps and other 'launch' modes (e.g. cherrypy, uwsgi, gunicorn, apache)
* Project specific tagging so we can trace more information about projects we are working directly with

Installer information spec:
https://docs.google.com/spreadsheets/d/1EpN4yIO9H0qkP0pY6jiEtfQIdyrEPChs3aDZwOMupcI/edit#gid=0

*If the task runner has been invoked either with `CHERRYPY_START` set to `False` and/or has been invoked using `kolibri services`. Otherwise this will be `False`.

**Comment by jamalex** [comment]
@rtibbles Another piece of this is presumably including some aggregate stats about browsers, which we now track via the session endpoint? I'm not sure where we're tracking that.

**Comment by jamalex** [comment]
>Accurate installer information

I have copied and updated the table in the original issue description into this spreadsheet, and bolded the places where I am proposing something different than what was laid out there:
https://docs.google.com/spreadsheets/d/1EpN4yIO9H0qkP0pY6jiEtfQIdyrEPChs3aDZwOMupcI/edit#gid=0
(important notes have been added to the last column)

>Information about apps and other 'launch' modes (e.g. cherrypy, uwsgi, gunicorn, apache)

We're folding the "app" info into the installer field, as they're tightly coupled. Determining that gunicorn, apache, etc are being used doesn't seem feasible, given that in those scenarios the task runner would need to be run separately anyway, so it would be hard to pick it up from the context of the ping.

>Project specific tagging so we can trace more information about projects we are working directly with

It looks as if this is already in place on the Kolibri side, with:
`"project": conf.OPTIONS["Deployment"]["PROJECT"]`

>Browser information of client devices

It looks as if this is in place as well:
`"dis": usersess_devinf,`

**Comment by jredrejo** [comment]
I miss here installations done with `pex` and with `pip`.

**Comment by jamalex** [comment]
The table that was in the initial issue description was not the latest -- I updated the table (including adding pex/pip) in the spreadsheet linked in my last comment:
https://docs.google.com/spreadsheets/d/1EpN4yIO9H0qkP0pY6jiEtfQIdyrEPChs3aDZwOMupcI/edit#gid=0
(so that should be considered the canonical values)

**Comment by rtibbles** [comment]
This Epic was resolved with the release of 0.15.0.
