### ISSUE TITLE
Individual-user sync choice in setup wizard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7963]
Ref: https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#bb9db6abe670454286220b3df851980a

In Kolibri 0.14 during the setup wizard, admins have the option to select a facility on another device on the same network from which to initialize the new device.

In Kolibri 0.15, admins will additionally have the option to select one or more individual learner accounts from a facility on another device. This choice sets up a trusted relationship between the devices whereby they will automatically find each other and stay in sync when connected to the same local network.

A possible user flow would look like:

- Starting with a fresh Kolibri database, user launches the setup wizard
- User chooses to associate the fresh device with a facility on a device on the same network
- User can choose whether to sync the entire facility or individual users
- If 'individual users' is chosen:
    - User can decide whether to either enter the credentials of the user directly, or to authenticate with admin user credentials and get permission to select one or more other users

**Comment by indirectlylit** [comment]
In Kolibri 0.14 during the setup wizard, admins have the option to select a facility on another device on the same network from which to initialize the new device.

In Kolibri 0.15, admins will additionally have the option to select one or more individual learner accounts from a facility on another device. This choice sets up a trusted relationship between the devices whereby they will automatically find each other and stay in sync when connected to the same local network.

A possible user flow would look like:

- Starting with a fresh Kolibri database, user launches the setup wizard
- User chooses to associate the fresh device with a facility on a device on the same network
- User can choose whether to sync the entire facility or individual users
- If 'individual users' is chosen:
    - User can decide whether to either enter the credentials of the user directly, or to authenticate with admin user credentials and get permission to select one or more other users

**Comment by rtibbles** [comment]
This is now feature complete!
