### ISSUE TITLE
Automatic individual-user device syncing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7964]
Ref: https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#89392dfe200c4175aa45c1b89daef4c2

## Overview

Once a Kolibri device has been set up for individual-user syncing, it should automatically sync with any server device containing that user's full facility on its local network.

The most common scenario is that some individual-user devices will be on the same network as one server device during a class. That said, it is also possible that two or more facility servers might be available on the same local network simultaneously, and this situation should be handled.

The valuable time available when coaches and learners are colocated is best spent teaching and learning, and the participants should not be distracted by the technology. Kolibri should "do the right thing" in the background as much as possible, while also giving sufficient visibility of syncing status to both learners and coaches such that they can take proactive and well-informed actions when necessary. For example, coaches may ask learners to stay a few minutes after class while all devices get into a consistently-synced state.

When an individual-user device connects to the same network as the classroom server, the user should be able to see a sync state such as "queued to sync" (with last sync time) or "currently syncing" (with progress).

This information should be available from within the Kolibri UI somewhere and visible for all user types, so that Learners themselves can see the sync state. For the Android app we may additionally want to show this information in the OS notifications which help keep the app running in the background.

We should probably:

- Prioritize clients with the oldest last-sync times
- Rotate through known available devices to keep data recent after initial syncs

Note that currently, the models that store information related to coach notifications (such as that a learner 'needs help' or 'started' an item) are not synced with the rest of user interaction logs. We either need to sync them, or generate them on the server after a sync.

Open technical and UX question: what information can Kolibri get about syncs before they occur to help relate implications and progress to users?

## Colocated usage

When a learner is using their devices on the same network as a coach server, there is some question about which Kolibri server the learner ought to connect to. The learner can connect to either server, with some pros and cons:

**Connecting to their own device**

Pros

- May load resources faster
- Supports more simultaneous users

Cons

- Updates to coach reports and assigned resource will be slower

**Connecting to facility server**

Pros

- Updates to coach reports and assigned resource will be real-time

Cons

- May load resources slower

In both cases, given sufficient time on the same network, the two Kolibri instances will eventually converge to the same state.

The instance of Kolibri available within an app (e.g. Android or Mac) will always be their own device. If a user wishes to connect to a facility server on the same network instead, they can do so through a web browser.

These nuances should be documented so that people can choose the most appropriate recommended practice for their situation.

**Comment by indirectlylit** [comment]
## Overview

Once a Kolibri device has been set up for individual-user syncing, it should automatically sync with any server device containing that user's full facility on its local network.

The most common scenario is that some individual-user devices will be on the same network as one server device during a class. That said, it is also possible that two or more facility servers might be available on the same local network simultaneously, and this situation should be handled.

The valuable time available when coaches and learners are colocated is best spent teaching and learning, and the participants should not be distracted by the technology. Kolibri should "do the right thing" in the background as much as possible, while also giving sufficient visibility of syncing status to both learners and coaches such that they can take proactive and well-informed actions when necessary. For example, coaches may ask learners to stay a few minutes after class while all devices get into a consistently-synced state.

When an individual-user device connects to the same network as the classroom server, the user should be able to see a sync state such as "queued to sync" (with last sync time) or "currently syncing" (with progress).

This information should be available from within the Kolibri UI somewhere and visible for all user types, so that Learners themselves can see the sync state. For the Android app we may additionally want to show this information in the OS notifications which help keep the app running in the background.

We should probably:

- Prioritize clients with the oldest last-sync times
- Rotate through known available devices to keep data recent after initial syncs

Note that currently, the models that store information related to coach notifications (such as that a learner 'needs help' or 'started' an item) are not synced with the rest of user interaction logs. We either need to sync them, or generate them on the server after a sync.

Open technical and UX question: what information can Kolibri get about syncs before they occur to help relate implications and progress to users?



## Colocated usage

When a learner is using their devices on the same network as a coach server, there is some question about which Kolibri server the learner ought to connect to. The learner can connect to either server, with some pros and cons:

**Connecting to their own device**

Pros

- May load resources faster
- Supports more simultaneous users

Cons

- Updates to coach reports and assigned resource will be slower

**Connecting to facility server**

Pros

- Updates to coach reports and assigned resource will be real-time

Cons

- May load resources slower

In both cases, given sufficient time on the same network, the two Kolibri instances will eventually converge to the same state.

The instance of Kolibri available within an app (e.g. Android or Mac) will always be their own device. If a user wishes to connect to a facility server on the same network instead, they can do so through a web browser.

These nuances should be documented so that people can choose the most appropriate recommended practice for their situation.

**Comment by rtibbles** [comment]
In order to help prevent sync stampede, and also to ensure that there is not a multiplicity of calls between devices to see which should sync with which, the following syncing flow is envisaged:

SoUD - Subset of User Device (i.e. a device that does not have a whole facility's data on it)

* Whether or not a device is a SoUD is broadcast via zeroconf (https://github.com/learningequality/kolibri/issues/8077)
* A SoUD would then request to sync with any facility device on the network (https://github.com/learningequality/kolibri/issues/8060)
  * If it receives permission to sync, it syncs
  * If it receives a request to wait, it scheduled a task to check at the delay interval
  * If it is told that either:
    * This is not a facility device and it is mistaken
    * This endpoint was not found (404)
    * It should not sync with this device (for whatever reason - but may include the fact that their facility does not exist here)
  * Then it should ignore that device

**Comment by rtibbles** [comment]
This is now complete.
