### ISSUE TITLE
Scheduled syncs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7967]
ref: https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#af839b4b1f214ef9b585415e29580c9c

For computer lab servers and online servers, we should enable scheduled syncs of the latest data to the Kolibri Data Portal. We have existing designs for this, which might need to be pared down a little to an MVP which covers the most typical use cases.

**Comment by indirectlylit** [comment]
For computer lab servers and online servers, we should enable scheduled syncs of the latest data to the Kolibri Data Portal. We have existing designs for this, which might need to be pared down a little to an MVP which covers the most typical use cases.

**Comment by rtibbles** [comment]
This has now been implemented in work by @AllanOXDi, @vkWeb and @rtibbles.
