### ISSUE TITLE
Shifted Scrollbar In Learn in IE9

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#797]
## Summary

Might have to do with the way we're handling the overlay?

## How to reproduce

1. Open Learn
2. Direct eyes at right edge of window

## Screenshots

![bs_win7_ie_9 0 2](https://cloud.githubusercontent.com/assets/9877852/21915382/733eb804-d8ee-11e6-9d68-de3face7b161.jpg)

**Comment by indirectlylit** [comment]
I assume this is IE9-specific?

It might not be so much an 'extra' scrollbar as a misplaced scrollbar?

(Note that we have `scroll-y` always enabled so that things which are centered or right-aligned don't jump around as you navigate.)

**Comment by DXCanas** [comment]
@indirectlylit You're right. I mistook the gap for a second scrollbar.

**Comment by indirectlylit** [comment]
dropping support for IE9
