### ISSUE TITLE
Design optional 'I'm finished with this' interaction to allow learners to mark an item as 100% complete when the resource allows it

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7971]

**Comment by khangmach** [comment]
What're the usage cases and motivations for this? Is this meant to be a way to mark completion before fulfilling completion requirements? Or a "don't show me this again" marker?

**Comment by rtibbles** [comment]
In Studio a resource will be able to be flagged as 'user can mark as complete', so this would only show in the case that the resource was flagged as such.

**Comment by rtibbles** [comment]
More details on this here: https://github.com/learningequality/studio/issues/3077
