### ISSUE TITLE
In Kolibri CLI, don't show `INFO` level logs for every command (maybe just `kolibri start`)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7972]
## Observed behavior

When running something like `kolibri plugin list`, I see two `INFO`-level logs that distract from the list I wanted to see. 

```
INFO: No C extensions are available for this platform
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
Available plugins                   Status
kolibri.plugins.app                 DISABLED
kolibri.plugins.coach               ENABLED
kolibri.plugins.default_theme       ENABLED
kolibri.plugins.demo_server         ENABLED
kolibri.plugins.device              ENABLED
kolibri.plugins.epub_viewer         ENABLED
kolibri.plugins.facility            ENABLED
kolibri.plugins.html5_viewer        ENABLED
kolibri.plugins.learn               ENABLED
kolibri.plugins.media_player        ENABLED
kolibri.plugins.pdf_viewer          ENABLED
kolibri.plugins.setup_wizard        ENABLED
kolibri.plugins.slideshow_viewer    ENABLED
kolibri.plugins.user                ENABLED
kolibri_exercise_perseus_plugin     ENABLED
```

## Expected behavior

Especially for `kolibri plugin list`, just show the list of plugins. The other subcommands might benefit from this as well.

The two `INFO` logs above might be more relevant for `kolibri start`, so can be kept for that subcommand.

**Comment by chrislun16** [comment]
Where do we print the second INFO level log?

I found the first logging statement in kolibri/utils/env.py::prepend_cext_path()::38. Should I move the whole function to the kolibri start file or just the if else block in that function?

Also how is prepend_cext_path() being called in kolibri plugin list and kolibri start?

**Comment by jonboiser** [comment]
@chrislun16 I think it might be simpler than that. For now, I wouldn't recommend doing a big refactor like moving `prepend_cext_path`.

One thing you can try is raising the [logging level](https://docs.python.org/3/library/logging.html#logging.Logger.setLevel) to something higher than `INFO` when running `kolibri plugin` (perhaps at line 710 of `kolibri.utils.cli`.

**Comment by chrislun16** [comment]
I raised the logging level to warning there, but there is a different logging handler in env.py::prepend_cext_path(), so that logger's level isn't changed and it's printing out an INFO message. Is there a way I can change that logger's level when kolibri start is called?

**Comment by jonboiser** [comment]
I see. The `C extensions` log gets called because of this import statement, which happens before any of the CLI commands are invoked.

https://github.com/learningequality/kolibri/blob/a9d1f4b579804d587b90580a0a9eeaf1a7dee955/kolibri/utils/cli.py#L27-L28

See if there's a way to modify the logging level for the `logging.getLogger(kolibri.utils.env)` logger _before_ this import occurs.

**Comment by chrislun16** [comment]
We found that kolibri/kolibri/__init__.py / is the file that is calling env.set_env() which calls prepend_cext_path() which prints out the C extensions log. So we went inside init.py and called 

```
logging.getLogger(str(utils.env)).setLevel(logging.WARNING)
```

before env.set_env. It does change the level to warning, but it still prints out the c extensions log. We are confused by this. Do you know why? We found that the only time we are able to avoid printing out the c extensions log is when we change the logging level in env.py to warning.

If that worked, our next idea was to do this in cli.py:  

```
import kolibri except init.py
logging.getLogger(str(kolibri.utils.env)).setLevel(logging.WARNING)
import kolibri/init.py
```

**Comment by jonboiser** [comment]
I think you're targeting the wrong logger in `init.py`. You'll notice that in `env.py`, the _root_ logger is being used, not this one

```
logging.getLogger(str(kolibri.utils.env)).setLevel(logging.WARNING)
# key is something like "<module 'kolibri.utils.env' from '/Users/.../kolibri/utils/env.py'> (INFO)>
```

Also, the normal pattern to create a within-module logger is to do this:

```
logger = logging.getLogger(__name__)
# key is 'kolibri.utils.env'
```

which usually means the key for logger looks like something like `kolibri.utils.env`. So I think in the last thing you tried, you were setting the wrong logger to `logging.WARNING`

**Comment by chrislun16** [comment]
In init.py I added this `logging.basicConfig(level=logging.WARNING,force=True)` before env.set_env() and it didn't print the c extensions log but this won't print it for any kolibri command. Is this correct: When we import kolibri in cli.py, that's importing init.py which calls env.setenv() before the rest of cli.py is ran? 

If the command is kolibri start, we want to change the logging level back to info, but if the ordering I said above is correct then I think if we change the level back to info in cli.py, then that's too late because we already determined whether to print out the c extensions log or not.

I'm not sure if there's a more clean way to do it but I came up with this. I copied the prepend_cext_path() function to cli.py from env.py:
https://github.com/chrislun16/kolibri/commit/52c10dd53a261e5e4dd9804c3f66ea16c0eed3e1

**Comment by jonboiser** [comment]
Could you try something a little simpler? I think all I really want is that the logging be done differently during invocations like

`kolibri plugin list`, etc.

In python, you can get the invocation information like this (similar to using `process.env` in nodeJS)

```
import sys

print(sys.argv)

# ['.../kolibri', 'plugin', 'list']
```

so you can write conditional logic to adjust logging, not simply skip the logging unless you've called `kolibri start` etc.

**Comment by rtibbles** [comment]
Closing as a won't fix.
