### ISSUE TITLE
focus outline can appear around elements when hovering, even outside of keyboard modality

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7974]
## Observed behavior

These are some screenshots I made browsing https://kolibri-dev.learningequality.org, which is using kolibri-design-system 0.2.2b1.

These screenshots were created while using the mouse exclusively (i.e. never entering into keyboard modality, at least intentionally by tabbing into elements).

**On video player (hovering)**

![CleanShot 2021-04-07 at 12 09 52](https://user-images.githubusercontent.com/10248067/113938693-cb406c80-97af-11eb-9f8c-5e3fcac8b2f6.png)

**Learn search bar**

![CleanShot 2021-04-07 at 12 09 31](https://user-images.githubusercontent.com/10248067/113938735-d7c4c500-97af-11eb-9ee0-78bfd4d062c5.png)

**Under top nav while side nav is open**
![CleanShot 2021-04-07 at 12 06 22](https://user-images.githubusercontent.com/10248067/113938750-e0b59680-97af-11eb-9368-89f6ea8fbe37.png)

**Core menu while hovering**

![CleanShot 2021-04-07 at 12 05 27](https://user-images.githubusercontent.com/10248067/113938794-ef03b280-97af-11eb-9fa5-b30e89778a93.gif)

## Expected behavior

In all of these screenshots, there should not be any outline

## Steps to reproduce

Go to the various parts of the app in Chrome and you will see the outline when hovering with mouse (or sometimes without having to hover)

**Comment by Priyaraj17** [comment]
Hey, We just need to add 'outline: none' in the css files. I will get started ASAP.

**Comment by jonboiser** [comment]
> Hey, We just need to add 'outline: none' in the css files. I will get started ASAP.

@Priyaraj17 I don't think the solution is simple as that. We want the green outline to show when using the keyboard "tab" button to navigate the UI. Try navigating Kolibri right now with just the keyboard to see what I mean.

So any change to the CSS that will remove that is unacceptable (i.e. setting `outline: none` globally).

**Comment by Priyaraj17** [comment]
Hey, I have fixed a few issues and now I will be working on the core menu and top nav when side nav is open.

**Comment by Priyaraj17** [comment]
@jonboiser I was working on 2 issues simultaneously. I have solved the issues here. Shall I reference a pull request that I have made while solving a different issue? I believe it will resolve this issue too.

**Comment by Priyaraj17** [comment]
> > Hey, We just need to add 'outline: none' in the css files. I will get started ASAP.
> 
> @Priyaraj17 I don't think the solution is simple as that. We want the green outline to show when using the keyboard "tab" button to navigate the UI. Try navigating Kolibri right now with just the keyboard to see what I mean.
> 
> So any change to the CSS that will remove that is unacceptable (i.e. setting `outline: none` globally).

 I think we can use tabindex = -1 for this. I have attached a screenshot too
I am hovering on the menu and the outline is not showing.
![image](https://user-images.githubusercontent.com/40101776/114929595-9e482580-9e51-11eb-8daf-b12dbc672831.png)

**Comment by Priyaraj17** [comment]
Will this work? @jonboiser @rtibbles 

> > > Hey, We just need to add 'outline: none' in the css files. I will get started ASAP.
> > 
> > 
> > @Priyaraj17 I don't think the solution is simple as that. We want the green outline to show when using the keyboard "tab" button to navigate the UI. Try navigating Kolibri right now with just the keyboard to see what I mean.
> > So any change to the CSS that will remove that is unacceptable (i.e. setting `outline: none` globally).
> 
> I think we can use tabindex = -1 for this. I have attached a screenshot too
> I am hovering on the menu and the outline is not showing.
> ![image](https://user-images.githubusercontent.com/40101776/114929595-9e482580-9e51-11eb-8daf-b12dbc672831.png)

Will this work @rtibbles @jonboiser?
