### ISSUE TITLE
Strings not extracted and missing on Crowdin

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7976]
## Observed behavior
Reported on the [community forums](https://community.learningequality.org/t/add-button-in-spanish-version-is-not-translated/1960/2), strings for the button `Add` (resource to the lesson from a preview) and the label `Added`, still appear untranslated in the non-English UIs. 

`addButtonLabel` | `addedIndicator`
--- | ---
![crwdns278692:0Anatomia de la florcrwdne278692:0 — Mozilla Firefox_058](https://user-images.githubusercontent.com/1457929/113941404-4f6e1080-97ff-11eb-8b54-93c5f89ca774.png) | ![LEDev2104 (start)  Running  - Oracle VM VirtualBox_032](https://user-images.githubusercontent.com/1457929/113946694-4d10b400-9809-11eb-92d1-08c1521c81b0.png)

I think this is the [line where the first string is defined in the code](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/plugins/coach/assets/src/views/plan/LessonContentPreviewPage/index.vue#L227) (second is a line above), but maybe they did not get extracted properly...? 🤔 
Neither is present on Crowdin, nor editable on the in-context server (screenshot above left).

Weirdly enough, I see them in all 25 JSON files ([`addButtonLabel` string identifier](https://github.com/learningequality/kolibri/search?q=addButtonLabel)), associated with a [`SelectOptions` context that I cannot find anywhere in the code](https://github.com/learningequality/kolibri/search?q=SelectOptions)... 😕 
Either I'm misunderstanding, or there's something 🐟y there. 

## Errors and logs
Current 0.14.x branch in development:

![LEDev2104 (start)  Running  - Oracle VM VirtualBox_031](https://user-images.githubusercontent.com/1457929/113943665-6a428400-9803-11eb-815b-1337eb89e5b6.png)

## User-facing consequences
Inconsistently localized UI.

## Steps to reproduce
1. Switch to a non-English locale.
2. Go to *Coach > Plan > Lessons > Manage resources* and open a preview of any resource to see the button <kbd>Add</kbd> in English.

## Context
 * Kolibri version: 0.14.x 
 * Operating system: Ubuntu
 * Browser: all

cc @jonboiser @nucleogenesis

**Comment by rtibbles** [comment]
Seems like a component was renamed, maybe?
