### ISSUE TITLE
Allow setting different logging modes via environment variable

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7979]
## Observed behavior
We currently have a very fully specified logging configuration, which gets intellligently used both before the Django stack is started and after.

However, it always assumes that the log location should be to disk, which can cause problems for some deployment models.

## Expected behavior
Because logging is used by the options.ini parsing machinery in `options.py`, we can't use a configurable option in options.ini to configure logging. It therefore seems best to simply have an environment variable that can be specified to turn off file based logging here: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/logger.py#L195

So, all that would change is that the handler lists would be `['console']` in each case, rather than `['file', 'console', 'file_debug']`.

We should call the environment variable: `KOLIBRI_NO_FILE_BASED_LOGGING`.

## Context
This is most acutely needed for cloud deployments of Kolibri, where persistent file storage complicates deployment.

**Comment by aronasorman** [comment]
This hits a lot of birds with one stone especially with the hosted use-case.

- Avoids writing to potentially corrupt filesystems
- Stdout/err is much easier to manage on our side
- Removes one more need for a persistent filesystem
