### ISSUE TITLE
Development Server Unable to start when the "yarn run devserver" command is been ran

### ISSUE THREAD

**Issue by bernandez** [learningequality/kolibri#7986]
## Observed behavior

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

…

**Comment by nucleogenesis** [comment]
Hello @bernandez - please in the future provide as much information as you can about your issue.

Please take a look at our [developer documentation for Getting Started](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html) and let us know which step you're failing at and we may provide some assistance.
