### ISSUE TITLE
Pc gets hang after starting the server. 

### ISSUE THREAD

**Issue by Priyaraj17** [learningequality/kolibri#7988]
Whenever I start the server, the pc becomes very slow and since a couple of days it gets hanged and I have to turn it off. Its not a bug in the application but I am not able to work since 4-5 days now. Can someone suggest something to me?

OS: ubuntu

**Comment by radinamatic** [comment]
@Priyaraj17 Are you using a virtual machine for Kolibri development? 
How much RAM does your PC have available, and how much have you assigned to the VM?
Check the System Monitor application to see which processes are consuming the most resources.

**Comment by Priyaraj17** [comment]
No, I am not using a virtual machine. I have a 4 gb ram.

I will surely take a look in this. Thanks.

**Comment by Sourabh025** [comment]
@Priyaraj17 try to upgrade your RAM to 8GB (minimum) or more. I was facing the same issue but after upgrading RAM, It is working fine for me.

**Comment by Priyaraj17** [comment]
@Sourabh025 hey thanks. But I opened the repo in codespaces and things are working smoothly for me now.
