### ISSUE TITLE
Vertical green line in search box when active

### ISSUE THREAD

**Issue by muhammadalics** [learningequality/kolibri#7990]
## Observed behavior

Within the search box for Learn, as soon as mouse is hovered over the active search box, a vertical green line appears inside the box. See gif below:
 
![vertical_greenline_searchbox](https://user-images.githubusercontent.com/59783720/114249156-04671100-9957-11eb-9405-883e3fd305b8.gif)

## Expected behavior
There should not be any green line appearing inside search box.
See below:
![vertical_nogreenline_searchbox](https://user-images.githubusercontent.com/59783720/114249338-8f480b80-9957-11eb-965f-ebf48c089748.gif)

## User-facing consequences
The green vertical line is distracting and does not look good.

## Steps to reproduce
Log in and then click on Learn section. Once the page loads click on search box at the top right corner. Green line will appear.

## Context
 * Kolibri version: 0.15.0.dev0
 * Operating system: Ubuntu 20.04.2.0
 * Browser: Firefox and Chromium

**Comment by muhammadalics** [comment]
I have found out the fix for this issue and creating a pull request in few minutes.

**Comment by jonboiser** [comment]
This is a duplicate of #7974
