### ISSUE TITLE
Design coach view of user sync statuses

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7999]

**Comment by khangmach** [comment]
This design has four primary design components to it, seen below
- An overview page with all learners and their device sync statuses
- An updated coach home page with an entry point button that leads to the overview page mentioned above
- A new information modal
- A new hyperlink on the quiz report template that leads the coach to the overview page (e.g. a cross-link)

More details in this [**figma file**](https://www.figma.com/file/MkIaNq2w3sx4Sh2uVOd35K/Coach-and-learner-notifications-SUS?node-id=11%3A643)

![overview-1.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/7bdb00dd-8cf2-47b0-b5eb-9539202278c2)

![sortable column.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/543771ea-dd13-44e6-a781-3a5bc32a4ba9)

**Overview page with a table view of all learners registered in the current class** 
- the default ordering for learners is alphabetical order
- there is a hyperlink which triggers a modal with text on how to troubleshoot learner devices(WIP)
- Only the first two column are able to be sorted
- Similar to what a learner sees, there are five states of syncing

![info modal.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/512d741c-ba2a-488d-9b8c-a3b65459fd61)

**Informational modal** 
In lieu of official support documentation and given how complex these syncing states are, we provide some explanations in the form of a modal the user can quickly open.


![coach dashboard.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/93eb880d-60a3-4fe0-b4fc-fe6ba564a12a)

**Updated coach dashboard page** 
- One update is that we will be showing an indicator next to the current learner count that displays how many students have recently connected
- Coaches will have a button here that will take them to the sync overview page

![updated report template.png](https://images.zenhubusercontent.com/6042a21c8000460e5640191f/4e0175ec-92ea-4937-b954-4353391d2da9)

**Updated quiz report page template**
- There is a new hyperlink here that cross links to the sync overview page. If the coach uses this hyperlink to go to the sync overview page, then when they exit the overview page, they should be routed back to the reports page.

**Comment by khangmach** [comment]
Detailed specifications for the learner's side are also in the figma file

**Comment by jamalex** [comment]
This is looking great overall!

>Only the first column is able to be sorted

Wouldn't hurt to be able to sort by username, as well -- just not the sync status columns (which change dynamically).

>One update is that we will be showing an indicator next to the current learner count that displays how many students aren't connected

Note that the picture tells how many haven't synced (recently), not how many aren't connected. It would be good to think through when they would be looking at this page, and what indicator would be most useful in those moments. If they're looking at the report page outside class time, then seeing that students haven't synced "recently" isn't so meaningful either. Maybe this only shows up when at least one student device is connected to the server (indicating it's now during classtime)? And/or maybe it's a mini table indicating the counts of learners in each status?
