### ISSUE TITLE
root of coach reports displays incorrect header

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#801]
The coach reports should not display the text 'main root':

![image](https://cloud.githubusercontent.com/assets/2367265/21936854/9437579a-d967-11e6-9c65-51505e1ff39e.png)

Instead, just the channel name should be displayed.

**Comment by indirectlylit** [comment]
this should be addressed by https://github.com/fle-internal/content-curation/pull/139

**Comment by indirectlylit** [comment]
once the CC server is updated, let's test and confirm

**Comment by 66eli77** [comment]
this issue is gone on the latest develop branch
