### ISSUE TITLE
Put realtime percentage of tasks in the tab title

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#8011]
Because the loader animations used on the Device > Task Manager use a lot of CPU( https://github.com/learningequality/kolibri-design-system/issues/211) , I prefer to not have that tab active when I'm import/exporting large channels. (Or I just go do something else in a different tab).

So it would be nice if the total task percentage were displayed in the tab so I can keep an eye on it.

![image](https://user-images.githubusercontent.com/10248067/114953750-ec3b3a00-9e0d-11eb-979f-1ef444e94a16.png)

**Comment by GarvitSinghal47** [comment]
@marcellamaki @radinamatic i would like to work on this issue , if it is open for contribtion

**Comment by rtibbles** [comment]
Hi @GarvitSinghal47 - yes, this would be fine, please target the develop branch for any changes here, as it would require updates to the string used to display the title.

**Comment by rtibbles** [comment]
Fixed in #11696
