### ISSUE TITLE
Some exercises are not being displayed correctly in Safari browser

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8017]
## Observed behavior
When I attempt to go through exercises imported from the CK-12 channel using a Safari browser on Mac I see the following error message: Kolibri is unable to render this resource

## Expected behavior
The exercises should be displayed correctly.

## User-facing consequences
Learners are unable to read the question and select the correct answer.

## Steps to reproduce
1. Create a new lesson using exercises imported from CK-12 Elementary Math
2. Attempt to go through the exercises
3. An error message is displayed instead.

![error](https://user-images.githubusercontent.com/79847249/115270719-49ecc080-a145-11eb-90aa-147d79ad7697.jpg)

Here's the same exercise displayed correctly in the other supported browsers:

![2021-04-19_19-28-39](https://user-images.githubusercontent.com/79847249/115271108-a94ad080-a145-11eb-9431-b8f637228e35.png)

## Context

 * Kolibri version: https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc7
 * Operating system: MacOS Catalina 10.15.7
 * Browser: Safari 13.1.3 but also observed in latest (14)

**Comment by jonboiser** [comment]
Here's a SO article dealing with this issue, for reference: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group/51568859

**Comment by rtibbles** [comment]
Ooof, the most annoying thing is I am fairly sure we saw this issue during testing of this work initially.

**Comment by jonboiser** [comment]
Fixed in #8018

**Comment by radinamatic** [comment]
Tested this [Perseus exercise](https://kolibri-beta.learningequality.org/en/learn/#/topics/c/fc3e2505ecc5441caf22b0657c651340) from Kolibri beta on all the Safari versions available on Browserstack in Sierra, High Sierra, Mojave, Catalina & Big Sur, plus in IE11 on Windows 7, and the fix in #8018 seems to have nailed it! 💯
