### ISSUE TITLE
Consolidate wsgi configuration in `kolibri.deployment.default.wsgi`

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8020]
## Observed behavior
We currently set a lot of additional wsgi behaviour in `server.py` which  it would be useful for uwsgi (and other wsgi services) invoked versions of Kolibri. At present, the new static files handling, and alternate origin server are not exposed in a useful way for deployment.

## Expected behavior
The default Kolibri wsgi app should include all static file serving, including content and media files.
The default Kolibri alternate origin wsgi app should include all static file serving, and content serving.

This will require some extra subclassing of our `DjangoWhiteNoise` implementation, in order to allow the addition of lazily evaluated files from content or media files.

This needs to be done, bearing in mind the Whitenoise caveats about not adding global static file lazy handling - because if we were to do that, then for any request to the server we would end up checking the disk for the existence of a static file, before serving the request.

## User-facing consequences
Complexities for deployment.

**Comment by aronasorman** [comment]
It sounds like both origins should serve static files and content -- aside from the hostname, in what other ways should they differ?

**Comment by rtibbles** [comment]
The main origin also serves the Kolibri Django app, whereas the alternate origin only serves the zipcontent path handler.
