### ISSUE TITLE
Vue warning about missing required prop `tooltip` in `KIconButton`.

### ISSUE THREAD

**Issue by YashJipkate** [learningequality/kolibri#8027]
## Observed behavior

When the site is loaded, the console gets full of error messages complaining about a missing required prop `tooltip` in `KIconButton`.

## Errors and logs

```
[Vue warn]: Missing required prop: "tooltip"

found in

---> <KIconButton> at node_modules/kolibri-design-system/lib/buttons-and-links/KIconButton.vue
       <KeenUiToolbar> at kolibri/core/assets/src/views/KeenUiToolbar.vue
         <AppBar> at kolibri/core/assets/src/views/AppBar.vue
           <ScrollingHeader> at kolibri/core/assets/src/views/CoreBase/ScrollingHeader.vue
             <CoreBase> at kolibri/core/assets/src/views/CoreBase/index.vue
               <Root>
```

## Expected behavior

Console error shouldn't appear.

## User-facing consequences

None, it's a warning, so nothing is expected to break. 

## Steps to reproduce

Load the site, and see the logs.

## Context

Kolibri: `develop`
OS: Ubuntu 20.04
Browser: FF 87.0

**Comment by rtibbles** [comment]
This appears to have been fixed.
