### ISSUE TITLE
Prepare technical architecture for automated individual-user syncing 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8033]
https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#89392dfe200c4175aa45c1b89daef4c2

Terminology:
SoUD - Subset of Users Device, a device that has had one or more individual users synchronized to it, but not the full facility.

Primary needs:
* A SoUD for a facility should sync those users' data to a device that has the full facility
* This requires that:
  * The SoUDs are discoverable by or can discover the facility devices
  * This discovery should happen primarily via zeroconf, which may require additional metadata to flag that it is an SoUD and not a full facility device
  * 1) If the facility devices have primary responsibility for discovery:
    * There may need to be an endpoint available on the SoUDs which the facility device can use with certificate authentication to initiate the synchronization task, as side loading lessons, quizzes, and associated assignments may not happen within the sync task
    * This endpoint should initiate a sync task to the server requesting
    * This has the advantage that the facility device can take responsibility for queueing and scheduling synchronization tasks, based on the number of detected SoUDs on its local network, this can help to limit server load.
  * 2) If the SoUDs have primary responsibility for discovery:
    * They can initiate synchronization directly
    * No need for an additional endpoint for a remote server to initiate syncing
    * Potential for a sync stampede when a classroom all join the network at once
  * Overall (a) seems preferable to (b) but both are listed so as not to constrain approaches
  * Another scenario that tilts the scale in favour of (1) is if there are multiple 'eligible' full facility devices on the same network. If each device handles their own sync queue, then the onus is on each server to update itself, and insert itself into the queue of each of the SoUDs it wants to sync with it.
* In order to allow for notification of ongoing syncing add a `NOTIFICATION` capability to the Kolibri app plugin interface https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/app/utils.py#L9 - apps can then do dependency injection here to show native notifications when possible
* If this capability is enabled, we can suppress showing the notification inside the Kolibri UI itself, similarly to our selective display of the share functionality: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/ContentPage.vue#L152
* We should ensure the current sync status of each student is in someway queryable for verification in the UI if at all possible

**Comment by jamalex** [comment]
>If the facility devices have primary responsibility for discovery

My mental model of a server-initiated sync is that the server... just does the sync (acts as the client in the syncing relationship), rather than telling the SoUD to do a sync. The lesson/quiz syncing endpoint I was planning would support both GET and POST.

This should make the desired sequencing much easier -- as the server doesn't then need to be asynchronously checking, or adding callbacks, for when a sync completes, to start the next one -- it's just in a synchronous task loop, syncing one device after another.

**Comment by jamalex** [comment]
>Potential for a sync stampede when a classroom all join the network at once

Because we allow for held-open connections (for local servers, at least -- when not going through Cloudflare), in principle the server could still "queue" the incoming stampede using a lock of some sort. When it's already doing one sync, and another tries to initiate a session, it could hold the session creation request open until it's ready to continue with it.

**Comment by jamalex** [comment]
>We should ensure the current sync status of each student is in someway queryable for verification in the UI if at all possible

It's definitely possible, the main thing would be designing it -- where does it show up, on which device(s), and what metadata is included. I'm assuming one place it could live is on the full-facility device, with a list of students (by class, maybe?), showing the last time a SoUD for that user synced to this server. For the scenario described here, that could work fairly well, but it could start to get confusing in a roving-sync-device scenario, when aggregated data is brought back to a school and synced to the school server. What would we show in that case? Just the fact that a full-facility sync had happened? The last date of user activity for each user (noting that the timestamps on a SoUD may not be reliable...), or the fact that a full-facility sync happened that _included_ new data for a particular user (which is trickier technically, but we could add some sort of post-sync callback in Morango with a list of new/modified records, and Kolibri could loop over that and maintain a list of users whose data was included in a sync session).
