### ISSUE TITLE
Create technical specification for individual user syncing setup wizard backend

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8035]
https://www.notion.so/learningequality/Support-for-individual-user-syncing-and-S2S-RCT-73b84ed2d3df4899b5d0441126b96850#bb9db6abe670454286220b3df851980a

In addition to the current 'setup with existing facility' workflow in the setup wizard, the new single user syncing setup will necessitate a workflow that has the following requirements:

* Specify either:
  * a specific non-admin user's credentials (username and password) that will be used to authenticate and will also be the user synced
  * an admin user's credentials which will then require further selection of a user to sync
* In the admin user case will either need to communicate the list of possible users to the provisioning device, or allow a mechanism for verifying that the selected users do exist
* This should then initiate a single user sync for each of the selected users (in the non-admin case, this will only be a single user)

For now, no support is required for adding additional users after initial setup, although there may be a case for this.

It is assumed that any deprovisioning to reset to the setup wizard will happen through command line interfaces (or over ADB/SSH etc.)

**Comment by jamalex** [comment]
UX question to resolve: What should we have it do/say if someone puts in the credentials of a Coach? Sync them as a single-user account (in which case they can still act as a Learner, but not do coaching, on that device), or show an error?

**Comment by jamalex** [comment]
>For now, no support is required for adding additional users after initial setup, although there may be a case for this.

There's definitely a case for this, and the backend part (at least) wouldn't really be anything additional to what we're already building for this (just establishing the conditions/permissions piece for the endpoint, e.g. maybe it's "can add a single user from the same facility to a device" or just "can add a new single user from any facility, as long as the device is a SoUD"). For the frontend, could be as simple as having an additional unobtrusive "Import additional user" link at the bottom of the login page that takes you to the same flow as in the setup wizard. One consideration: if we are (as discussed) by default allowing learners on SoUDs to manage content, then this would be an avenue to gaining content management permissions on the SoUD. But we could have it only available if the device is app-only (not available over the network), in which case physical access to the app would be the layer preventing that.
