### ISSUE TITLE
Facility coach as a user type not apply

### ISSUE THREAD

**Issue by MBKayro** [learningequality/kolibri#8053]
When creating a new user as a Facility coach, it does not apply its permissions and not seen all classes.

A) In Admin interface:

In Device --> Permission:     User type | Facility coach

In Facility ---> Users:            User type | Facility coach

In profile :  Coach
-----------------------------------
B) In Facility coach (does not see any classes except if he is assigned by admin as a regular Coach)

In profile :   User type | Coach

## Observed behavior

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

…

**Comment by rtibbles** [comment]
What version of Kolibri is this happening on? I am not able to replicate this on 0.14.7.

Do you have any additional information to help us reproduce this?

**Comment by MBKayro** [comment]
the version is  0.15.0.dev0+git.20210429235644 

when i sign in with Facility coach account, i only view this but no classes that i was created:

Classes
View learner progress and class performance
Please consult your kolibri administrator

**Comment by rtibbles** [comment]
Thanks, have replicated on develop.
