### ISSUE TITLE
Add REST API for contentnode-bookmarks feature

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#8066]
## Use Cases

* Create/Delete bookmarks to ContentNodes
* View all bookmarked contentnodes as a list
* When a contentnode is bookmarked as a user, indicate that with a bookmark icon on its contentcard 
* When a contentnode is not bookmarked as a user, indicate that with an empty bookmark icon on its contentcard

There really isn't a use case for updating bookmarks or viewing an individual bookmark, so those abilities can be left out.

## Usage

Root URL

`/api/bookmarks`

### Create a bookmark

Request

```
POST /api/bookmarks/bookmarks
{
   "contentnode_id": "4d93d3e9-cd14-4d3f-8958-a7d24c3de807"
}
```

Response
```
{
   "contentnode_id": "4d93d3e9-cd14-4d3f-8958-a7d24c3de807",
   "is_bookmarked": true,
   "timestamp": "..."
}
```

### Delete a bookmark

Request
```
DELETE /api/bookmarks/bookmarks/4d93d3e9-cd14-4d3f-8958-a7d24c3de807
```

Response
```
{
   "contentnode_id": "4d93d3e9-cd14-4d3f-8958-a7d24c3de807",
   "is_bookmarked": false
}
```

### Retrieve all your bookmarks (get full ContentNode objects)

This is useful when the client needs to display full Content Cards for the bookmarks

```
GET /api/bookmarks/bookmarks
```

Response 
```
[
	{
		"contentnode_id": "4d93d3e9-cd14-4d3f-8958-a7d24c3de807",
		"title": "My bookmarked video",
		"description": "...",
		"thumbnail": "...",
		"is_leaf": false
	}
]
```

### Retrieve all your bookmarks (get full ContentNode objects)

This is a more minimal payload that can be used to annotate Content Nodes were from a different request. E.g., on the Learn Page, ContentNodes are requested separately. Then this list is used to mark the nodes that are already bookmarked.

The payload can be `Array<string>` or `Array<{contentnode_id}>` 

```
GET /api/bookmarks/bookmarks?ids_only=true
```

```
[
	"4d93d3e9-cd14-4d3f-8958-a7d24c3de807",
	"3f6a2357-9908-4ea4-a31d-c0f222d3cc8c",
	"5d4519ba-1b2a-47db-a530-bec11713d0b9",
	"38eb82d0-b5a1-4fe5-814e-67fb1aaf8828",
	"c97ba35f-57f7-4b12-9355-77b517dc143d",
	"af42d4fe-245e-476c-8511-b7e9914386cc",
	"07803f01-504a-42ee-b343-cf2189e66cc0",
	"f4dfdc9f-0509-484a-ac9e-971c4181c9e3"
]
```

**Comment by Priyaraj17** [comment]
Hey @jonboiser, can you please explain what do we have to work on here?

**Comment by rtibbles** [comment]
This issue will also require creating the model, and for the model to be syncable along with the user, so will need the appropriate morango partition for single user syncing.

Recommendation: create a new app in `core` called `bookmarks`.

**Comment by nucleogenesis** [comment]
@jonboiser @rtibbles 

I'm not sure we need the endpoint to return the content nodes themselves. There is one place where that will be relevant (Learn -> Bookmarks) and we will probably want more than a distilled little bit of metadata about the [content node to accommodate the designs](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=77%3A7116).

In any case - feels more reasonable that the Bookmarks resource return Bookmarks and we leave returning ContentNodes to the ContentNode endpoints?

**Comment by jonboiser** [comment]
I think that's fine. We can do a follow-up query on the frontend after getting the bookmarked contentnode IDs. I'm just worried if someone has a lot a bookmarks, since there can be limits when querying the Contentnode endpoint with a long list of  IDs.

**Comment by nucleogenesis** [comment]
That's important to note. That pagination can happen on the client and I'll include it in the spec.

**Comment by rtibbles** [comment]
Another thing that just occurred to me is that we should avoid using a direct Foreign Key for the bookmarks, and should probably add a 'fallback compatible' representation, so we should probably be storing the contentnode id, content_id, and channel_id.

We want to avoid the direct foreign key so that they can sync to devices that do not have that content metadata and still be properly deserialized.
