### ISSUE TITLE
Unreliable detection of Android app through zeroconf from Windows computer

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#8073]
## Observed behavior

Both Android tablet with Kolibri app and Windows computer running Kolibri are on the same wifi network. The tablet could "see" the computer, but the computer couldn't see the tablet.

## Expected behavior

Discovery should be symmetrical.

## User-facing consequences

For classroom syncing, we had discussed having the server initiate the syncing against the student devices. If the server can't find the tablets, this won't work reliably.

**Comment by radinamatic** [comment]
On Windows it's probably a firewall issue (see [related from prior testing](https://github.com/learningequality/kolibri/issues/6724)).

**Comment by jamalex** [comment]
I haven't been able to replicate this. Things are looking good now, so I'm going to close this.

I think it was because I was running previously within the Windows Subsystem for Linux (WSL), which has its own networking layer in between. I just installed the Windows installer and now Windows launcher, Android tablet, ODroid, and Ubuntu laptop are all finding each other happily and reliably.
