### ISSUE TITLE
Document `deletechannel` command

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#8074]
Add documentation [here](https://kolibri.readthedocs.io/en/latest/manage/command_line.html) for the `deletechannel` command to [avoid confusion like this](https://community.learningequality.org/t/kolibri-command-line/2018/2).

**Comment by Priyaraj17** [comment]
Hey, may I work on it?

**Comment by radinamatic** [comment]
Thank you @Priyaraj17, I'm already working on it! 👍🏽

**Comment by Priyaraj17** [comment]
@radinamatic okay,sure.

**Comment by radinamatic** [comment]
Fixed in https://github.com/learningequality/kolibri-docs/pull/221, closing.
