### ISSUE TITLE
Add facility device or SoUD flag to device info (for zeroconf broadcast)

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#8077]
For automatic background syncing (#7964), devices will need an efficient way to know what other devices and their associated datasets are on the local network. The most efficient way to facilitate this sharing of information is via the zeroconf broadcast itself, because it's multicast (i.e. many-to-many), rather than by requiring an additional HTTP request, which would lead to an n^2 barrage of 1:1 requests between every pair of devices on the network.

The simplest place to add this information is in the results of [`get_device_info()`](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/public/utils.py#L9), which is what's called to get the info that's included in the zeroconf broadcasts. This has the beneficial side effect of also including this info in the response to the `/api/public/info/` endpoint, which can be used as a fallback when devices are connecting outside of a local network context, or when an address was added manually.

The proposed new field to add would be:

~`"facilities": {"<facility_id_1>": "*", "<facility_id_2>": ["<single_user_id_1>", "<single_user_id_2>"]}`~

`"soud": <boolean>`

**Comment by rtibbles** [comment]
I thought we had just said we needed to flag if they were full facility or not - is there something that we need the user ids for?

**Comment by jamalex** [comment]
The main thing I was thinking was for scenarios where the syncs are initiated by the full-facility device (so it can prioritize students who haven't synced in a while), and so that it can show to the teacher which students in the class have devices that are currently connected to the network, in addition to showing the last time each student's data was synced.

In principle, that part could be done by pinging the Morango certificates endpoint and parsing some nested JSON data contained within the certificates, which at least would just be 1:n and not n:n, but is a bit awkward and still involves extra requests. We could cache for some duration the instance_id -> user_id mappings, though, which would help a bit.

Did we have a clear sense of the max payload size for the zeroconf packets?

**Comment by rtibbles** [comment]
It's limited to 255 bytes, so we need to be very strict about what we put in it, and this design seems like it would be very easy for some devices (either with lots of facilities, or multiple users in one facility) to push over that limit.

**Comment by rtibbles** [comment]
In conversation with @jamalex it seems like it will still be useful to encode some of this information in the base case of a single facility and a single user.

In the case where there are multiple facilities and multiple users, we can add special flags instead of the ids to indicate such.

e,g.

The 'single user, single facility' case:
```
"facility": "<facility_id>",
"user": "<user_id>"
```

The 'multiple individual user, single facility' case:
```
"facility": "<facility_id>",
"user": "MULTIPLE"
```

The 'multiple individual user, multiple facility' case:
```
"facility": "MULTIPLE",
"user": "MULTIPLE"
```

The 'facility synced, single facility' case:
```
"facility": "<facility_id>",
"user": "ALL"
```

The 'facility synced, multiple facility' case:
```
"facility": "MULTIPLE",
"user": "ALL"
```

**Comment by rtibbles** [comment]
From further conversations, it seems that we can probably simplify this to a simple flag - is this a facility device or not?
