### ISSUE TITLE
Device Settings Updates: Changes to "Allow guest access settings" are not immediately enforced on Sign-in page

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#8087]
## Observed behavior
This comes from https://kolibri-beta.learningequality.org/en/user/#/signin, but I am also able to reproduce this locally

I turned off guest access in Device Settings:

![image](https://user-images.githubusercontent.com/10248067/118328945-438b0380-b4bb-11eb-83ae-d4bdb718dedb.png)

But I still see the "Explore..." button

![image](https://user-images.githubusercontent.com/10248067/118329029-62899580-b4bb-11eb-9f8d-5a0796221c9f.png)

If you view the source for the UserPage, the `plugin_data` script is out of date

Line 364:

```
window['kolibriPluginDataGlobal'] = window['kolibriPluginDataGlobal'] \|\| {};
  | window['kolibriPluginDataGlobal']['kolibri.plugins.user.app'] = JSON.parse("
{\"oidcProviderEnabled\":false,\"allowGuestAccess\":true}");
 
```

This looks like a similar behavior that was fixed in https://github.com/learningequality/kolibri/pull/5601 (which removed bootstrapping code from the Django template that was also causing stale information to be sent to the browser).

## Expected behavior

The guest access setting is reflected immediately after an admin changes it.

## Steps to reproduce

1. Change the guest access setting in device settings
2. Go back to the sign-in page
3. You will see the "explore without an account" button

**Comment by marcellamaki** [comment]
Moving this to the Device Settings milestone, as it can be updated as part of that project.

**Comment by jredrejo** [comment]
Finished in #10025
