### ISSUE TITLE
Allow a facility to be dissolved and reconstituted

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#8091]
We've seen many cases of devices being cloned without first running the `deprovision` management command, hence duplicating the facility to each device, which leads to issues when it comes time to sync. Currently there is no way to recover from this situation and split the data out into separate facilities, so the only approach currently is to wipe one of the devices and start fresh, or never sync.

A possible flow for addressing this would be creating a management command, perhaps called `fork_facility`, that does the following:
- Creates a new facility B on the device, with the same metadata and settings as facility A
- One model at a time, starting from the root of the foreign-key chain, take chunks of records, update their `_morango_partition` and possibly also `_morango_source_id` (for those that include IDs of other records in them) and then recalculating and setting their `id`, then doing a bulk creation across the record batch.
- Remove the old facility once all that is done, including from the morango Store

Two specific places this could be leveraged, in addition to manually running the management command:
- When a user is renaming a facility, ask them if their intention is actually to make this into a new facility, or just correct the name. If they want it to be a new facility, trigger the forking.
- Automatically run this when a device is provisioned and then cloned! When a device starts up, if a) the instance_id has changed, and b) the device has never been synced (no records in the Store), and c) the facility doesn't have any/much user data.

**Comment by rtibbles** [comment]
Closed by #8742 - follow up filed here: https://github.com/learningequality/kolibri/issues/8824
