### ISSUE TITLE
Crowdin in-context server does not use localized messages for `document.title`

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#8094]
## Observed behavior

Most of the time you see this on the browser tab

![image](https://user-images.githubusercontent.com/10248067/118873309-7445b100-b89e-11eb-80ef-783736d5aacf.png)

https://kolibri-translate.learningequality.org/ach-ug/learn/#/topics/t/166880c6c61d4ef2a4e6adf5c8e968cf

Related to #7330

## Technical notes

The message keys only appear as an output of `$tr` if we are unable to resolve the message in the namespace. So there might be some broken link when going from the crowdin locale file to the real locale files.

**Comment by 0xV0YD** [comment]
is this issue open or closed @rtibbles @marcellamaki

**Comment by rtibbles** [comment]
Looking at this issue again, I actually think this is an issue with Crowdin's JIPT machinery and not something we can fix on our side. The thing being displayed in the document title is the special code that gets replaced by the JIPT code in an in place translation server, so I'm really not sure there's anything we can do about it.

**Comment by 0xV0YD** [comment]
@rtibbles   as i am very new to open source so can you please assign any issues to me for me to get started with open source

**Comment by MisRob** [comment]
Hello @yash1378, thanks for volunteering.

We currently have contributing opportunities in three repositories. You can see the contributing guidelines including links to issues suitable for contribution for each repository here:

Kolibri: https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md
Kolibri Design System: https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md
Studio: https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md
