### ISSUE TITLE
content does not load

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#810]
## Summary

Attempting to load content fails. git bisect seemed to narrow it down to one of these commits:

* c97b8d61d3f77211cf152caace43c0b6b2210943
* 736aa0aebb3eb641e93cd0d12f0a39bf1977e7fe

Seems to have occurred during https://github.com/learningequality/kolibri/pull/806

## System information

`develop` branch

## Traceback or relevant snippet from server.log or browser console

![image](https://cloud.githubusercontent.com/assets/2367265/22076586/9cda66d8-dd65-11e6-84f8-3969a4d46dec.png)

## How to reproduce

navigate to a video, e.g. http://localhost:8000/learn/#/explore/f6d2f857af2e304093648daf2d8cacec/content/dce69fb8ee605da59cbd9f2ac9da624c

## Screenshots

*If applicable*
![image](https://cloud.githubusercontent.com/assets/2367265/22076818/8d73b7a2-dd66-11e6-85ee-e08cffa9184a.png)

**Comment by rtibbles** [comment]
I think I missed a reference to `this.Kolibri` in one of the action invocations: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/vue/content-renderer/index.vue#L191
