### ISSUE TITLE
Create new informational side panel for hybrid learning view

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8107]
**Overview**:
The new side panel component is used to display resource information and lesson plan information. 

Done when:
- Side panel can be toggled open and closed (note: this can be a last `TODO` for when the menu bar is merged)
- Side panel has the appropriate new mobile-responsive breakpoints laid out in figma
- Side panel content is rendered either as information panel or as lesson/topic panel
- As an information panel: 
      1.  The resource title, description, subject, level, language, author, license holder,  and license details are visible and displayed in line with the figma design 
      2. Long descriptions should be truncated to fit within a "preview" 170px high, and have an option to toggle to read more (with scroll) and then read less
      3. The license details should default to being collapsed, and similarly have a toggle to display that metadata 
      4. There should be a button at the bottom of the panel to download resource, and this interaction should be implemented as part of the PR 
- As a topic/lesson panel:
   1. Each related (previous/next resource) should be listed in order 
   2. The current resource should be indicated as current with a shaded background (as indicated in design)
   3. Basic metadata of the title of the activity/resources and an icon should be displayed, with tooltips
   4. Empty topics should render with a "no more topics" message (see figma references)

**Beyond scope of this ticket**:
- Creating the "chips" seen at the top of the info panel
- Side panel implemented in other place in the code base
- Interactions to navigate between topics/resources in the side panel _(as this needs further clarification)_
- Display of metadata related to progress, completion and estimated time

**NOTE**: 
- Any metadata that is within the scope of this ticket but not available should be noted and raised for discussion to clarify the timeline of when it can be included. `TODOs` should be included in the code as well to keep track, and outstanding items should be referenced in the PR.

**Figma references**:
<img width="729" alt="Screen Shot 2021-05-25 at 10 36 11 AM" src="https://user-images.githubusercontent.com/17235236/119516778-09382680-bd45-11eb-8c18-d7c965d6c1df.png">
<img width="308" alt="Screen Shot 2021-05-25 at 10 31 36 AM" src="https://user-images.githubusercontent.com/17235236/119516509-cfffb680-bd44-11eb-818f-99513867d16c.png">
<img width="926" alt="Screen Shot 2021-05-25 at 10 31 28 AM" src="https://user-images.githubusercontent.com/17235236/119516510-cfffb680-bd44-11eb-80ff-87149e69ddb0.png">
<img width="703" alt="Screen Shot 2021-05-25 at 10 33 00 AM" src="https://user-images.githubusercontent.com/17235236/119516499-cece8980-bd44-11eb-807c-79b094b49130.png">
<img width="293" alt="Screen Shot 2021-05-25 at 10 32 09 AM" src="https://user-images.githubusercontent.com/17235236/119516503-cf672000-bd44-11eb-9049-51268f87f68a.png">
<img width="945" alt="Screen Shot 2021-05-25 at 10 32 50 AM" src="https://user-images.githubusercontent.com/17235236/119516502-cf672000-bd44-11eb-8161-656e7af0bfe0.png">
<img width="238" alt="Screen Shot 2021-05-25 at 10 33 52 AM" src="https://user-images.githubusercontent.com/17235236/119516496-cece8980-bd44-11eb-9c6a-bf9db28f67dc.png">
<img width="830" alt="Screen Shot 2021-05-25 at 10 33 48 AM" src="https://user-images.githubusercontent.com/17235236/119516497-cece8980-bd44-11eb-8ea5-7f21652b7173.png">
<img width="504" alt="Screen Shot 2021-05-25 at 10 34 00 AM" src="https://user-images.githubusercontent.com/17235236/119516495-cece8980-bd44-11eb-99a8-b6013eb6722b.png">

**Comment by marcellamaki** [comment]
Still to do: 
- make sure that all of the design use cases are covered by existing components and updated as necessary 
- responsiveness

**Comment by nucleogenesis** [comment]
Much of this is covered in #8466 but the metadata is not available, so this won't be finished until metadata is available.
