### ISSUE TITLE
Create new modal for learner engagement between resources

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8109]
**Overview**:
The new modal should replace the "points" and "next item" snackbars. Instead, the learner: can stay and practice more, move on to the next resource in line, or move on to related resources from a related topic. 

Done when:
- Modal displays when a learner completes a resources, in line with the new figma design
- Modal contains new iconography (or placeholder, but in the correct places, if the new icons are a bottleneck. Please add a `TODO` comment in the code and a note in the PR if the icons still need to be replaced)
- Modal is mobile responsive and correctly displays with the new breakpoints
- Dialog contains:
     1. the points associated with resource completion
     2. an option to stay on the current resource. **Note**: decision/clarification needed on whether or not there should be some type of mechanism that "resets" progress or place in the resource to the beginning
     3. option to move on to the next resource, if there is a next resource. For this resource, the title should display, along with resource type, and estimated time, if available
     4. related/helpful resources, if available. **Note**: decision/clarification needed on what exactly these resources should be, and where they should be fetched from. Regardless, the component should be built to render only if this data is available, as not all nodes will have related resources
- The following interactions are working: 
     1. Stay here
     2. Move on 
     3. Links to related resources

Outside the scope of this issue: 
- creating or modifying backend endpoints for related resources (if necessary)

[Figma references](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=2254%3A6):

<img width="831" alt="Screen Shot 2021-05-25 at 4 33 48 PM" src="https://user-images.githubusercontent.com/17235236/119564929-51703c80-bd77-11eb-81af-398dcd87e54c.png">

<img width="485" alt="Screen Shot 2021-05-25 at 4 34 36 PM" src="https://user-images.githubusercontent.com/17235236/119564932-5208d300-bd77-11eb-8496-83f8467f511b.png">

<img width="496" alt="Screen Shot 2021-05-25 at 4 34 46 PM" src="https://user-images.githubusercontent.com/17235236/119564933-5208d300-bd77-11eb-80ce-bcf3a4f2591b.png">

<img width="243" alt="Screen Shot 2021-05-25 at 4 34 53 PM" src="https://user-images.githubusercontent.com/17235236/119564934-5208d300-bd77-11eb-9dd5-20b08504b0c6.png">

<img width="350" alt="Screen Shot 2021-05-25 at 4 34 56 PM" src="https://user-images.githubusercontent.com/17235236/119564935-5208d300-bd77-11eb-9ed3-517c6ddea778.png">

<img width="696" alt="Screen Shot 2021-05-25 at 4 35 13 PM" src="https://user-images.githubusercontent.com/17235236/119564936-52a16980-bd77-11eb-8456-31453fa9735f.png">

<img width="531" alt="Screen Shot 2021-05-25 at 4 35 41 PM" src="https://user-images.githubusercontent.com/17235236/119564937-52a16980-bd77-11eb-946b-2ec7c7dc535a.png">

<img width="438" alt="Screen Shot 2021-05-25 at 4 35 56 PM" src="https://user-images.githubusercontent.com/17235236/119564938-52a16980-bd77-11eb-93bd-a6937fbb599e.png">

**Comment by marcellamaki** [comment]
@khangmach / @rtibbles - two points to clarify (mentioned above): 
1. If a learner choses to "stay here" - what do they see next? Do they get "sent back to the beginning" or something like that, or does the modal simply close? (Or, something else?) 
2. What is the status for "helpful resources" (related resources?) Does this need technical architecting and/or studio support still, or are we repurposing some existing metadata for this?

Please let me know if these questions make sense

**Comment by rtibbles** [comment]
> If a learner choses to "stay here" - what do they see next? Do they get "sent back to the beginning" or something like that, or does the modal simply close? (Or, something else?)

I think the modal simply closing would be the easiest to implement technically - and would mean we leave exactly what that engagement looks like entirely up to the learner.

We could implement a 'restart' public method for the different content types, but I am not sure that the technical effort to achieve that would be reflected in the improved user experience.

> What is the status for "helpful resources" (related resources?) Does this need technical architecting and/or studio support still, or are we repurposing some existing metadata for this?

I think for now we can repurpose the existing `recommendations_for` metadata for the node.

**Comment by khangmach** [comment]
@marcellamaki yup to echo what Richard said, if the Learner closes the side drawer or chooses to stay, the side drawer just closes and they're left to their own devices on the page. Of course, they can still move ahead to the next resource/topic via the 'lesson plan' icon seen below, which has a yellow dot appended on it to indicate there's more resources to check out!

<img width="194" alt="Screen Shot 2021-05-28 at 2 50 15 PM" src="https://user-images.githubusercontent.com/25045166/120045095-0bf47f00-bfc4-11eb-9642-21302aa27cc2.png">
