### ISSUE TITLE
Create new, manual "Mark As Complete" modal and interaction

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8110]
**Overview**:
There should be a new interaction "Mark as complete" that allows a learner to indicate they have finished engaging with a resource. The users access the interaction through the new top bar menu options and completes or cancels from a modal

**Done when**:

- Menu option "Mark resource as finished" opens a modal
- The modal contains the new strings as displayed in the figma designs 
- "Confiming" changes the status of the resource to complete
- When the status is changed to complete, the modal should close, the "complete" icon should also successfully display in the top nav, and a snack bar should render to indicate the status change

**[Figma references](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=517%3A46959)**:

<img width="710" alt="Screen Shot 2021-05-25 at 5 03 36 PM" src="https://user-images.githubusercontent.com/17235236/119568219-428b8900-bd7b-11eb-979e-eabdf7bb6d42.png">

<img width="708" alt="Screen Shot 2021-05-25 at 5 03 23 PM" src="https://user-images.githubusercontent.com/17235236/119568214-41f2f280-bd7b-11eb-9a46-68b069c3f3bb.png">

<img width="702" alt="Screen Shot 2021-05-25 at 5 03 29 PM" src="https://user-images.githubusercontent.com/17235236/119568218-428b8900-bd7b-11eb-96f1-e5b67d230afd.png">

**Comment by marcellamaki** [comment]
Since the `LearningActivityBar` component work is not yet integrated, in order to develop and test this interaction, please follow [the code diff in this commit](https://github.com/MisRob/kolibri/commit/1e9a411e2cdc109005fed5793dbf2b3311a7a3d2) that Misha used for testing the component to hack `CoreBase` locally. 

Note: since this work is still pending, it's possible there might need to be some refactoring after #8234 (Connect new hybrid learning bars to "Learn" pages) is completed and merged where the modal is moved to the new WIP `Layout` component that is based off of `CoreBase` for the new layout.

**Comment by nucleogenesis** [comment]
Note that #8324 being merged might close this (I can try to un-hook the automatic connection) - the follow up of making the component created in #8324 available in the resource LearningActivityBar will be needed.

**Comment by nucleogenesis** [comment]
@marcellamaki do you know how we will know whether a resource is allowed to be marked complete manually?

**Comment by rtibbles** [comment]
I had failed to make issues to cover the encoding of this in metadata, but @bjester is taking this on. We decided to encode it in the `options` JSON blob.
