### ISSUE TITLE
Add some additional documentation & comments about back-end peer device info/location gathering and caching

### ISSUE THREAD

**Issue by micahscopes** [learningequality/kolibri#8120]
There's some stuff related to p2p syncing that could use a little more developer documentation, especially around these files:
- https://github.com/learningequality/kolibri/blob/develop/kolibri/core/discovery/utils/network/connections.py
- https://github.com/learningequality/kolibri/blob/9761b070ac91ce68b45247cde8638a545e006552/kolibri/core/utils/nothing.py#L1
- https://github.com/learningequality/kolibri/blob/develop/kolibri/core/discovery/utils/network/client.py

**Comment by rtibbles** [comment]
Work by @bjester has significantly overhauled a lot of this functionality while also documenting it considerably, I think we can close this.
