### ISSUE TITLE
Top border of focused element on "Learn" in side nav is cut off

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8125]
## Observed behavior

When using the keyboard to tab through the side nav, the top border of the focus for the "Learn" option is slightly cut off (I realize that the left side also seems cut off, but that's due to my poor recording; the left side is fine).

![2021-05-24 14 46 34](https://user-images.githubusercontent.com/13563002/120056906-057dfb80-bff4-11eb-9223-9e130d5f98f0.gif)

## Errors and logs

…

## Expected behavior

The outline should behave the same as for any of the other options in the side nav.

## User-facing consequences

It just isn't as nice as it could be :)

## Steps to reproduce

1. Log in to Kolibri
2. Use the keyboard to tab to the icon on the top left to open up the side nav
3. Tab through the options

## Context

Kolibri 0.14
Mac OS
Chrome

**Comment by MisRob** [comment]
Resolved in https://github.com/learningequality/kolibri/pull/8973
