### ISSUE TITLE
Syntax error in IE11 on builds from 'develop' branch

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8131]
## Observed behavior
Syntax error impeding `develop` Kolibri to load in IE11.

## Errors and screenshot

![Win7 (start)  Running  - Oracle VM VirtualBox_024](https://user-images.githubusercontent.com/1457929/120368780-c8c34480-c312-11eb-8670-5f228d0c0aa1.png)

## Expected behavior
We still need to support IE11, so need to cater to its _idiosyntaxies_ 🤷🏽‍♀️ 

## Context

 * Kolibri version: `exe` asset built from the `develop` branch
 * Operating system: Windows 7
 * Browser: IE11

cc @rtibbles

**Comment by rtibbles** [comment]
This is almost certainly a regression from the babel upgrade. Will fix.

**Comment by rtibbles** [comment]
Looks like the specific syntax error is being caused by an untranspiled `class` definition.

**Comment by rtibbles** [comment]
There are two issues here, seemingly - one is that fuse.js by default exports a non-transpiled ES Module, which was being imported but not transpiled. The other is that our new core-js configuration was incorrect, so Object.assign and other vital polyfills were not being imported.
