### ISSUE TITLE
Text in HTML5 App does not appear for Windows 7 and 8

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#8135]
## Observed behavior

A user observed that HTML5 Apps are not consistently showing text on Windows 7 and 8, when it works on Windows 10.

This is being observed on both laptops and desktops with 3GB+ RAM on Intel Celeron.

## Expected behavior

One would expect that all of the Apps would appear with text as intended.

## User-facing consequences
Users cannot use the content.

## Steps to reproduce
Lauren can share the channel to reproduce this issue locally.

## Context
Kolibri version: 0.14.6
Browser: Occurs on Mozilla Firefox, Internet explorer, Microsoft Edge v42.17134.1 
OS: Windows 7 and 8

Examples:
Windows 7/8
![Screenshot 2021-06-02 10 49 08 AM](https://user-images.githubusercontent.com/25990164/120517302-513af700-c39e-11eb-9629-21e56d6e1868.png)

Windows 10
![Screenshot 2021-06-02 10 49 19 AM](https://user-images.githubusercontent.com/25990164/120517298-50a26080-c39e-11eb-919a-3bab7e4f1ad0.png)

Windows 7/8
![image](https://user-images.githubusercontent.com/25990164/120517466-7b8cb480-c39e-11eb-967b-94b6f977e1bf.png)

Windows 10
![image](https://user-images.githubusercontent.com/25990164/120517490-821b2c00-c39e-11eb-8862-f59761a94c8f.png)

**Comment by pcenov** [comment]
Hi @laurenlichtman and @radinamatic - I'm also not able to replicate this issue. Tested in Windows 7 with 0.14.6 in Firefox, Edge and Chrome and the text is displayed correctly:
![2021-06-08_14-51-42](https://user-images.githubusercontent.com/79847249/121186920-353cc700-c870-11eb-879d-82e98019631c.png)

**Comment by radinamatic** [comment]
@laurenlichtman We were unable to replicate this issue on Windows 7 with the most recent browsers, so my suspicion is that there's something an interplay between older browsers and the user OS. I'll try to find some potential tips and tweaks to reply, but the issue would most probably be resolved by upgrading the browsers.

**Comment by rtibbles** [comment]
Going to close this as unreproduceable.
