### ISSUE TITLE
Initiate auto-syncing from zeroconf listeners

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8157]
For a device that has a subset of users, when a new device joins the network, that is not a subset of users device, attempt to initiate an automatic sync with that device.

Could achieve this by adding behaviour directly in zeroconf, or potentially by adding signals to the DynamicNetworkLocation model.

**Comment by jredrejo** [comment]
@rtibbles in a SoUD, how can I know the user who must sync? in these devices, are they going to h ave only one user in the `FacilityUser` table, or one user + superuser and the user is the one to sync? or, in case more than user is found, should it try to sync them all, one by one?

**Comment by rtibbles** [comment]
> in case more than user is found, should it try to sync them all, one by one?

Yes - I think that's the only thing we can do! (in most cases, this should just be a single user)

**Comment by jredrejo** [comment]
Ok.
I'm looking forward to seeing how we're managing things like classrooms or teams having in one device just one user belonging to different collections in another device...

**Comment by rtibbles** [comment]
> I'm looking forward to seeing how we're managing things like classrooms or teams having in one device just one user belonging to different collections in another device...

A user's collection memberships are synced as part of their data, and the collection hierarchy is synced in a read only way. Not sure exactly what the scenario you're envisaging here is?

**Comment by jredrejo** [comment]
I was just thinking out loud  of possible database integrity problems in lessons assigned to individual users without those users in the db. I'm not sure if all the things we have in collections allow to work without all the users belonging to the collection created. I'm wondering if we can have that kind of problems with any of the different collections we're using. I.e. is it possible to sync a lesson assigned to a couple of individual users, syncing their collection with just one user and leaving the others out of the device db?

**Comment by rtibbles** [comment]
Assignments are on the collection level, and all collections are synchronized, so the assignment and the collection can be synchronized without including the other users.
