### ISSUE TITLE
Implement single user syncing flow in the setup wizard

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8166]
Implement designs/user flow described here:

https://www.figma.com/file/w3raYcGRUhhaVm1Of8Dcvo/0.15-Device-setup?node-id=142%3A20

as per https://github.com/learningequality/kolibri/issues/7933#issuecomment-865223151

**Comment by rtibbles** [comment]
Need to filter out three categories of devices:
* Kolibri < 0.15
* Non-local Kolibris
* SoUDs

**Comment by jtamiace** [comment]
0.15 Device setup gherkin stories 
https://www.notion.so/learningequality/Device-setup-gherkin-stories-0de35a71f63b4315b36243bc25aaf2b8
