### ISSUE TITLE
Create public facility user endpoint for single user syncing

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8170]
To support single user syncing setup, a public API endpoint is required that will:
* Return a user's information when that user has signed in as a learner
* Return a paginated list of users that can be selected for single user syncing when logged in as an admin
* Allow for search by username, fullname, classroom name, Identifier Number - check blackbox of facility admin searching

The form of the return data can be based on permissions based filtering - for ease, can always return paginated data, and simply return just the learner if a learner is logged in.

Authentication will be required for the endpoint, and should probably use HTTP Basic Auth in order to allow simple repeated queries without having to maintain a session.

**Comment by jredrejo** [comment]
The first two points of this issue have been implemented in in  #8185 in this commit: https://github.com/learningequality/kolibri/pull/8185/commits/47b486067fc25bf0748c326f9f07e1dd4e0c9b0a

As BasicAuth does not allow to add the facility and two users might have the same username & password in different facilities, this has be modified to include the facility_id as a realm when authenticating using BasicAuth:
https://github.com/learningequality/kolibri/blob/a56d04850e9c765b50a94ec0b25c0279ed197dfb/kolibri/core/auth/api.py#L82-L106
I.E: username@facility_id should be the user

**Comment by rtibbles** [comment]
Done!
