### ISSUE TITLE
Errors during syncing increase with the number of syncs in 0.14

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#8175]
## Observed behavior
Shared from Simon at Lewa, experienced on the Android App:

> Difficulty syncing facility data that increases with the number of syncs. At some point, you have to clear the app data before syncing. It gives an error that the last syncing has failed. When syncing quizzes some of the questions are lost during the process and you have to repeat more than one time for all of the questions to sync. This was experienced in all 25 devices.

## Context

Tell us about your environment, including:
![page2](https://user-images.githubusercontent.com/22602993/123313434-8814b080-d4f7-11eb-93ce-f115bdde95cc.jpeg)

**Comment by lauradanforth** [comment]
Additional information from Simon:

> Our Kolibri server is hosted on a Windows Laptop in a school. This is where teachers prepare lessons for the kids and the lessons include quizzes that children take home as assignments. A Kolibri Administrator In the school. Has to Daily sync the quizzes and lessons to the learners tablets installed with the Kolibri app before they carry them home. The first three days went well until a point where when you sync the quizzes in the Host Laptop to the learners tablet, after syncing some of the quizzes could not be found in the learners tablet  even if they still existed in the Host Tablet.  You had to sync more than once to have all the questions in the quiz fully synced on the tablet. At one point, the tablets failed to sync even after repeating and rebooting everything. many times. We resolved this by clearing the App data. This was the time I was filling in the form. We have not continued to experience this problem though since we cleared the app data in the tablets.  The total content size in the tablets is 5G and we have 25 students in the database for this pilot. All content is in HTML 5 and quizzes. The Tablet has an internal 32GB Storage size. Let me know if this helps!

**Comment by pcenov** [comment]
@radinamatic I cannot replicate this issue in 0.15.6 - tested on 2 Android devices without experiencing data loss or difficulty syncing.

**Comment by radinamatic** [comment]
@rtibbles This is a rather old issue, and even though on occasion we still may have some lags while syncing facilities among devices (or with KDP - recent tests in Greece for example), we cannot replicate with in-house manual QA with limited number of devices.

**Comment by rtibbles** [comment]
I think this is probably also ameliorated by the introduction of learner only device setup and syncing of subsets of facility data in 0.15 as well.
