### ISSUE TITLE
Prompt user to download to prevent user list CSV export popup being blocked silently in Chrome

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#8191]
## Observed behavior

The download popup for user CSV exports is blocked by the browser, without notifying the user.

## Expected behavior

After clicking the "EXPORT" button here:
![image](https://user-images.githubusercontent.com/618416/124833436-0713db00-df33-11eb-8022-b8bbf38e6c8e.png)
a spinner and status appears:
![image](https://user-images.githubusercontent.com/618416/124833502-21e64f80-df33-11eb-8e48-be0522d9200d.png)
but when it completes, the spinner disappears and button reactivates, but no file download is triggered.

Turns out the browser was blocking the popup automatically:
![image](https://user-images.githubusercontent.com/618416/124833633-5528de80-df33-11eb-9922-82f60ffed103.png)

This doesn't happen when downloading the logging CSVs, even though [they all use `window.open`](https://github.com/learningequality/kolibri/search?q=window.open&type=code). My assumption is that this is because those are initiated by a user action (click), whereas the user list CSV export popup is triggered internally (by a state change).

## User-facing consequences

We received a report from a user that the feature was broken, and it took a long time to realize that the cause was the blocked popup.

## Steps to reproduce

Not sure whether this happens locally, or only on a deployed server at a URL with a domain name in it.

## Context

Kolibri: 0.14.7
Local OS: Windows 10
Browser: Chrome

**Comment by rtibbles** [comment]
Seems like this should just be a matter of copying the interaction from the export logs page, where we have an explicit place to download once generation has completed.

**Comment by khangmach** [comment]
Handled in #6582. Work should be coupled with the designs found there

**Comment by rtibbles** [comment]
Fixed in #8419 - further work will be resolved in #6582.
