### ISSUE TITLE
Sync a facility - Hard to reproduce issue where syncing a facility fails

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8227]
## Observed behavior
When as an administrator I attempt to sync a single facility the radio button with the facility's URL is disabled, there's a loader spinning and I am unable to sync the facility unless I manually add a new address.

![2021-07-27_16-45-31](https://user-images.githubusercontent.com/79847249/127213495-1d06542f-351a-42a7-8240-891bed9143d4.png)

Note that when I changed the URL I was able to start the syncing process:
 
![2021-07-27_17-04-41](https://user-images.githubusercontent.com/79847249/127214503-234974ba-fc65-49e3-b2b8-da478adc803f.png)

Also note that after a while the initially disabled URL was successfully changed to the correct one. Not sure whether I disabled and then enabled the WiFi to achieve that:

![2021-07-27_17-13-00](https://user-images.githubusercontent.com/79847249/127215084-8bbb9bcc-a32d-40ba-99d5-e0090ac472e1.png)

## Steps to reproduce (Note: I don't have straightforward steps to replicate the issue at this moment, will follow up)
1. As an administrator create a single facility, set up all classes and user accounts on that facility and import the desired channels.
2. Install Kolibri on a individual learner device, import the facility from the central server by entering the super admin credentials and import the learner data and relevant channels in the learner device.
3. Simulate various real world scenarios with both admin and learner users on both devices and occasionally attempt to sync the facilities. This includes logging in and logging out, changing the WiFi networks, disabling the WiFi and so on.

## Errors and logs
I didn't observe any related errors in the browser console, will attempt to do so tomorrow.

## Expected behavior
An admin user should be able to sync successfully facilities when Kolibri is running on the devices and they are within the same network.

## Context
Tell us about your environment, including:
 * Kolibri version: 0.14.7
 * Operating system: Windows 10
 * Browser: Chrome

**Comment by radinamatic** [comment]
cc @rtibbles @jamalex @bjester 

Some findings while investigating the zeroconf issue.

**Comment by pcenov** [comment]
Adding the log files:
[Admin logs.zip](https://github.com/learningequality/kolibri/files/6890873/Admin.logs.zip)
[Learner Logs.zip](https://github.com/learningequality/kolibri/files/6890874/Learner.Logs.zip)

**Comment by pcenov** [comment]
Update:
I was able to successfully reproduce the issue. Here are the steps:

1. Stop both Kolibri instances on both devices.

2. As a Learner:
- Connect to a different WiFi network (I created a hotspot using my mobile phone)
- Launch Kolibri and start doing some exercises

3. As an Admin on the other laptop:
- Launch Kolibri and go to http://127.0.0.1:8080/en/device/#/facilities
- Select the Sync option for the facility - as expected no network address is displayed in the modal as the learner is on a different wi-fi network

4. As a Learner:
- Connect to the same WiFi network as the admin’s

5. As an Admin:
- Observe the Select network address modal window - the learner’s device is displayed now but with incorrect URL and the radio button is disabled

![2021-07-28_16-44-23](https://user-images.githubusercontent.com/79847249/127345666-1d1d9168-8980-4a37-b76a-cb98418927d4.png)

The sync issue gets fixed if I restart both Kolibri instances while being connected to the same network.

The logs from today:
[Admin logs.zip](https://github.com/learningequality/kolibri/files/6894105/Admin.logs.zip)
[Learner logs.zip](https://github.com/learningequality/kolibri/files/6894106/Learner.logs.zip)

**Comment by bjester** [comment]
Thanks for the great reproduce detail @pcenov! This is the issue that I hypothesized and also reproduced @jamalex

**Comment by rtibbles** [comment]
This will hopefully be fixed by #8231 - we have merged, but would be good to confirm the fix still on release-v0.15.x

**Comment by bjester** [comment]
I have observed this as fixed
