### ISSUE TITLE
Connect new hybrid learning bars to "Learn" pages

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#8234]
New top bars components - the primary bar (https://github.com/learningequality/kolibri/issues/8106) and the secondary sticky completion criteria bar (https://github.com/learningequality/kolibri/issues/8114) need to replace our current bar on the following pages of "Learn":

#### (1) A resource page in "Learn" → "Channels (the purple bar to be removed)

![Screenshot from 2021-07-28 16-40-05](https://user-images.githubusercontent.com/13509191/127347860-d5aab1d7-e050-49af-b23c-3f593899f1e8.png)

#### (2) A resource page in "Learn" → "Classes" → "Lessons" (the black bar to be removed)

![Screenshot from 2021-07-28 16-38-51](https://user-images.githubusercontent.com/13509191/127347780-d06b3c02-e5da-4aa7-ba13-13dfd360e252.png)

**Requirements**

- the primary bars is displayed on all pages above
- the primary bar is not sticky
- the secondary completion criteria bar is displayed only when practicing
- the secondary completion criteria bar is sticky

**Out of scope of this issue**

- bar controls (e.g. bookmarking functionality) don't need to work
- no updates to the quiz page and quiz report page - we will use different bars for those pages (see @jtamiace comments and designs below for more information)

**Comment by MisRob** [comment]
Not a requirement for the solution, only some suggestions from my recent observations:

As discussed [in this Slack thread ](https://learningequality.slack.com/archives/C023DNC5GCX/p1622725220014100), due to our current layout architecture, it's not possible to simply go to appropriate views and connect new bars there which adds some complexity to this task. As suggested in the thread, ideally we can use this issue to explore a more flexible layout structure which would be only introduced on these two pages even if it'd mean some temporary customized duplicates of our core layout component. If successful, we could then gradually move towards it in the whole app. However, if that shows to be way too complicated to finish in a reasonable time frame, it'd be okay to introduce more complexity to the current `CoreBase`. In that case, I'd suggest not forgetting to open a tech debt follow-up as our current layout makes simple things complicated, and we already discussed this several times in the past. An interesting article that describes similar problems https://michaelnthiessen.com/advanced-vue-controlling-parent-slots.

**Comment by MisRob** [comment]
@jtamiace Could you please confirm that I've referenced all pages where the new bars should be used in "Learn"?

**Comment by jtamiace** [comment]
It looks like there's also a purple bar in the quiz report under "Learn > Classes"

<img width="1102" alt="Screen Shot 2021-07-28 at 11 25 08 AM" src="https://user-images.githubusercontent.com/6668144/127376459-33f41dee-6837-49bc-af52-c9b5a0e873e4.png">

**Comment by MisRob** [comment]
@jtamiace Thanks, I've updated the description with both quiz and quiz report pages, and also updated requirements regarding the secondary completion criteria bar but now I realize that I am not sure how "displayed only when practicing" (designs say that it's "practice-exclusive") specifically refers to the pages referenced above. Is it something to be displayed also when taking a quiz? Feel free to update requirements to be more precise.

**Comment by jtamiace** [comment]
It looks like the "practice-exclusive" is referencing the secondary mastery bar only? 
<img width="620" alt="Screen Shot 2021-07-29 at 9 50 19 AM" src="https://user-images.githubusercontent.com/6668144/127532775-1a0c7121-777e-430f-b021-9102ff9fd614.png">

I've found this other Figma page that Khang worked on for the quiz renderer which uses the new top bar.
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=3845%3A90706

However, there are no design updates to the quiz report as far as I can see. I'm not sure what the original intention was here, but I do think it'd be good to use the new app bar on the report for consistency.

I'm going to drop in a draft now for how the top bar for the quiz report can appear.

**Comment by MisRob** [comment]
Yes, the question was meant to be about the secondary master bar.

Thanks for adding the draft. I am going to open another issue for implementing the bar for quizzes and quizzes reports because we don't have that one yet.

**Comment by MisRob** [comment]
Yes, the question was meant to be about the secondary master bar.

Thanks for adding the draft. ~I am going to open another issue for implementing the bar for quizzes and quizzes reports because we don't have that one yet.~ I realized that we don't have any issues open yet for updates to quiz renderer and that there is usually some planning happening before opening them. So for now, I will remove the requirement for connecting the quiz and quiz renderer bar to our views from this issue because we don't have this bar implemented yet.

**Comment by MisRob** [comment]
The description has been updated and should be precise now

**Comment by rtibbles** [comment]
Fixed in #8314
