### ISSUE TITLE
Need to requeue for sync after a successful automatic single user sync

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8236]
## Observed behavior
After a successful automatic single user sync, no syncs happen again until the server restarts or a new server joins the network.

## Expected behavior
Need to requeue for sync after the successful completion of the sync

**Comment by jredrejo** [comment]
@rtibbles I have looked at the specs and I haven't been able to find any decission related to this issue. i.e. how often a new sync should happen.
If there are not algorithm involved and just a time interval to be decided it could be as simple as adding a new
`scheduler.enqueue_in(dt, job)` being job a new `request_soud_sync` and dt the interval we decide: 10 minutes?, a random interval between 10-15 minutes?
inside this if, right after the sync command https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/public/utils.py#L190-L193

My first tend would be to do it with a random interval but I'd like to know if this has already been thought and/or decided

**Comment by rtibbles** [comment]
I don't think we made a decision - but I think if we are trying to achieve a near real time flow of data, we might want to reduce it further to 30 seconds? We are then relying on the server to queue us and let us know when to come back and ask.

**Comment by indirectlylit** [comment]
In the coach reports, @jredrejo you implemented a dynamic polling interval that was proportional to the number of active coach users. It's great because it is nearly real-time when demand is low, but doesn't overload things when demand is high. Would be great if there was a way to do something similar here.

**Comment by rtibbles** [comment]
The queueing mechanism already does that to some extent, as it serializes the syncs rather than letting them run in parallel. The question here is just about how often to requeue.

**Comment by indirectlylit** [comment]
what's the cost of re-queuing? if low, down to 5s would be great

**Comment by jredrejo** [comment]
@indirectlylit  the cost to re-queueing should be short, just one query in the server to check if there's a sync in progress.
As @rtibbles mentioned, if the queue in the server is long, the polling interval will be automatically increased. I think it should work but that's one of the cases I'd like to see it in practice :)

**Comment by indirectlylit** [comment]
Note for future readers: discussion moved to slack https://learningequality.slack.com/archives/CB37UM23A/p1628089247046100
