### ISSUE TITLE
Describe proper workflow for uploading and updating Perseus translations files

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8246]
## Observed behavior
Extracting Perseus translatable strings is a murk-ish _affaire_, as the desired workflow is not completely obvious. We should document it properly.

## Errors and logs
…

## Expected behavior
…

## User-facing consequences
…

## Steps to reproduce
…

## Context
…

**Comment by rtibbles** [comment]
Closed by #8254 - no need to have separate documentation, as it is now the same as the regular workflow.
