### ISSUE TITLE
Comments about Coach Reports API design

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8265]
## Observed behavior

This was reported by @jonboiser in early 2018. Transferring from https://github.com/learningequality/clearinghouse/issues/93

> 
> Doing analysis for the APIs to support Coach Lesson Reports, I've found some areas where the current reporting APIs can be improved
> 
> ### URLs are not resource-oriented and hard to understand
> 
> For example, the URL to get the Progress report for a piece of content in the context of Classroom or Group is:
> 
> is `coach/api/<channelId>/<contentNodeId>/<collectionKind>/<collectionId>/contentreport`
> 
> There might be a Resource-based interpretation of the URL, but it's not obvious.
> 
> If the relevant resource is the Content Progress Report, a more RESTful URL might be something like `coach/api/contentreport/...` where the `contentNodeId` could be used to uniquely determine the report. Additional context like Channel Id, Collection info could be provided as query parameters.
> 
> The absence of some of these parameters have a reasonable interpretation (e.g. no collection info provides aggregated progress over the entire facility, over all Learners under the Coach). Or omitting them results in an Error code.
> 
> ### Responses are polymorphic in a non-transparent way
> 
> For example, in the UserReportSErializer 
> 
> https://github.com/learningequality/kolibri/blob/34e99da58480e260062b590f467b8c25a061563f/kolibri/plugins/coach/serializers.py#L14,
> 
> The shape of response is different depending on whether the requested content node is a Topic/Channel or Leaf Node. This requires the client code to be pretty intelligent about what it gets back from the API.
> 
> It seems like this use case of the UserReport API is not used, too. To get a Learner's progress for a topic, the ContentReport API seems to be used instead, but with collectionKind set equal to "user", and content node id equal to the topic id e.g.
> 
> http://localhost:8000/coach/api/000409f81dbe5d1ba67101cb9fed4530/000409f81dbe5d1ba67101cb9fed4530/user/63216e3b88a8b650489ceef716518f26/contentreport/?1515623979850=1515623979850
> 
> The only use of the UserREport API in the JS code also seems to assume the response takes the Leaf Node version
> 
> https://github.com/learningequality/kolibri/blob/34e99da58480e260062b590f467b8c25a061563f/kolibri/plugins/coach/assets/src/state/actions/reports.js#L183

## Context

Reported Jan 10, 2018

**Comment by rtibbles** [comment]
The APIs in question no longer exist, so I am going to close this.
