### ISSUE TITLE
finalize copy for 0.15 update notification strings

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8270]
## Observed behavior

current copy is a placeholder:

https://github.com/learningequality/kolibri/blob/98bb185b73b247c0e774b229dd507fa6e74c4eaf/kolibri/core/assets/src/views/UpdateNotification.vue#L115-L116

## Expected behavior

string should provide information about highlights of new features

## User-facing consequences

Unhelpful upgrade notification

## Context

0.15

**Comment by marcellamaki** [comment]
Closed with updates for string freeze

**Comment by indirectlylit** [comment]
mind referencing the PR?

**Comment by radinamatic** [comment]
#8433

https://github.com/learningequality/kolibri/pull/8433/files#diff-3f5af7e3909e8a37e99d748407fe63e6db962b7a174899761d64a815c0cf276bR115
