### ISSUE TITLE
Brand new Setup Wizard infinitely redirects

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#8271]
## Observed behavior

On 0.15 branch, with a fresh KOLIBRI_HOME folder, going to the server causes infinite redirects and does not allow the user to proceed with the Setup Wizard (it doesn't load at all - tries to request the page like 10 times and then gives up).

## Context

Kolibri: release-v0.15.x branch
OS: Fedora
Browser: Chrome

**Comment by rtibbles** [comment]
@radinamatic have you seen this on testing of current release-v0.15.x (without https://github.com/learningequality/kolibri/pull/8185)?

**Comment by radinamatic** [comment]
Can't say that I have @rtibbles 🤔 

I just started the server on my dev VM from the `release-v0.15.x` branch without the `.kolibri` folder, and the setup wizard loads without issues.

![LEDev2104 (start)  Running  - Oracle VM VirtualBox_019](https://user-images.githubusercontent.com/1457929/129224775-39305f7d-664c-4a15-b737-85490c0efeca.png)

**Comment by radinamatic** [comment]
Both @pcenov and I have been doing periodic critical workflows tests on the assets built from the 0.15 branch, and we never had issues with the setup wizard.

**Comment by rtibbles** [comment]
@nucleogenesis anything specific about your dev setup that might be making this appear for you?
