### ISSUE TITLE
Feature request: make LISTEN_ADDRESS an option

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#8273]
At the moment, Kolibri's server always listens on all network interfaces, with the following code in [utils/server.py](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/utils/server.py#L64-L65):

```
# Currently non-configurable until we know how to properly handle this
LISTEN_ADDRESS = "0.0.0.0"
```

On Windows, listening on all interfaces requires a firewall exception, meaning a user is greeted with a scary firewall dialog when they first run Kolibri. This makes sense usually (we want Kolibri instances to talk to each other and firewall dialogs are not exactly uncommon in Windows), but it is problematic in an application where we are providing pre-installed Kolibri instances for _offline_ users who don't need that functionality. So, it would be nice if the listen address was configurable :)

**Comment by rtibbles** [comment]
@jamalex pointed out that having this be configurable as a list of interfaces (as opposed to just a single value) would also be helpful.

It may be that we would need to run separate WSGI servers to do this more specific binding (which would then also open the possibility for the port and zip_port options to be lists as well).

**Comment by marcellamaki** [comment]
Closed in error
