### ISSUE TITLE
Single User Syncing - A self created user's device status is always "Not connected to server"

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8274]
## Observed behavior
After importing a learn-only device I can create an account for another learner user which is never synced.

## Expected behavior
The expected behavior should be further discussed as either the option to create accounts for learn-only devices should be disabled or there should be an option to sync such users.

## Steps to reproduce the issue
1. Install this [build](https://buildkite.com/learningequality/kolibri-windows/builds/1586#97b40f19-5fb4-4cd7-888e-69531fedca75) and import a learn-only device.
2. Sign out with the imported learner
3. Create a new account by selecting the "Create an account" option
4. Click the username of the user to the top right corner to check the Device status

## Additional information
![2021-08-11_17-25-53](https://user-images.githubusercontent.com/79847249/129176925-749d053c-09f4-4284-a978-9637eadfe519.png)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by rtibbles** [comment]
I think the simplest short term fix here is to hide account sign up on learner only devices.
