### ISSUE TITLE
Single user syncing - Quiz results are not getting synced

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8275]
## Observed behavior
I have imported a learn-only device and have completed a couple of quizzes assigned to the learner user which never get synced to the admin device even after repeated restarts of the Kolibri instances. At the same time syncing is fully operational for lessons.

### Background
Exam related models `ExamLog` and `ExamAttemptLog` are only synced when syncing a full facility. This restriction was implemented as originally intended by customizing the [partition](https://github.com/learningequality/kolibri/pull/1712/files#diff-b867682c06c75c9355c277b585d1da401af2801a7a4d67ee6f7a6d968fd7f4e8R259) for the models.

## Expected behavior
The behavior is currently functioning as expected, but could be viewed as a bug by end users. Going forward, the models should be queued for sync similarly to other related records. Changing this behavior will also require compatibility enhancements to ensure backwards compatibility.

## User-facing consequences

For devices provisioned for a subset of users, admins/coaches will likely be confused by the absence of these records after syncing with learner devices, since all other related data is synced. It's likely this will be viewed as a bug.

## Steps to reproduce the issue
1. Install this [build](https://buildkite.com/learningequality/kolibri-windows/builds/1586#97b40f19-5fb4-4cd7-888e-69531fedca75) on 2 devices, set up an admin device and import a learn-only device.
2. As an admin create and assign quizzes for the learner to complete.
3. As a learner complete the quizzes.
4. As an admin go to Coach>Reports>Quizzes and attempt to see the learner's results. 

## Additional information
Admin:
![2021-08-12_15-08-41](https://user-images.githubusercontent.com/79847249/129194370-fbeaea58-4472-400c-8a01-114cec9044ec.png)
![2021-08-12_15-20-56](https://user-images.githubusercontent.com/79847249/129195701-eb8bb1ad-bff5-4efe-9466-86f8579bbdb6.png)

Learner with completed quizzes:
![2021-08-12_15-09-38](https://user-images.githubusercontent.com/79847249/129194443-808a09c0-5e6c-4a9c-b58e-717118ec0648.png)

## Logs
[logs.zip](https://github.com/learningequality/kolibri/files/6975404/logs.zip)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: Chrome

**Comment by radinamatic** [comment]
I also noticed this: progress on lessons and resources in them are synced from the learn-only device to the class server (granted, you need to restart the server to achieve the sync), but quizzes never seem to register as `In progress` or `Completed` on the server.

**Comment by rtibbles** [comment]
Thanks both - we're aware of this issue since the hack session. The current plan is to fix it in the scope of 0.15.x, but not for any prerelease. Good to have it tracked!

**Comment by rtibbles** [comment]
See also https://github.com/learningequality/kolibri/issues/8316

**Comment by bjester** [comment]
Follow up issues added for bugs, but single-user syncing of quiz and results is working
