### ISSUE TITLE
Single user syncing - Getting a 403 error when attempting to Sync with a learner-only device as a Super admin

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8276]
## Observed behavior
As a super admin I have the ability to manually sync facilities. However when I attempt to sync with a learner-only device I'm getting a 403 error without any explicit information what is going on.

## Expected behavior
The expected behavior is not clear and should be further discussed.

## Steps to reproduce the issue
1. Install this [build](https://buildkite.com/learningequality/kolibri-windows/builds/1586#97b40f19-5fb4-4cd7-888e-69531fedca75) on 2 devices, set up an admin device and import a learn-only device.
2. As a super admin go to Device>Facilities and click the Sync button next to your facility
3. Select the learner-only device and attempt to sync with it (note that syncing with a fully imported facility is functioning correctly)

## Additional information
![2021-08-12_16-45-05](https://user-images.githubusercontent.com/79847249/129207791-33bebf4a-2ab8-4fc2-bead-a5822f5106a3.png)

## Logs
[logs.zip](https://github.com/learningequality/kolibri/files/6975925/logs.zip)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: Chrome

**Comment by rtibbles** [comment]
Seems like we should filter out learner only devices from this list to prevent an admin even trying to do a full facility sync.
