### ISSUE TITLE
Clean up modal appearance and text in single user sync setup wizard flow

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8308]
> I find this screen a bit confusing, as 3 different terms (import, load, sync) seem to be used for what is essentially the same action.

 I'm not sure if the implementation in this PR is using the same components as the task manager in `Device > Channels`, but we can remove almost all the lines except `Finished` and `'learner' from 'ZukVillage' successfully loaded to this device` to be consistent with both the designs and the current 0.14 implementation of facility import. I'd argue all those other details aren't that useful to know at this stage in the setup process. That way we'd at least remove the word 'Sync'. I think there was a reason we went "Loaded/Loading" instead of import but I can't quite remember or find any notes on why...

![importuser](https://user-images.githubusercontent.com/6668144/128408954-3ff2f611-c4ae-49f7-b8fd-a442fa70b59a.png)

---

> Once the setup is completed, the first imported learner is automatically signed in, but on the Learn page, the phrase As an administrator, you can import channels looks out of place and confusing. Administrator on a learn-only-device?

> Actually, I'd like to suggest the change of the wording for this link to something more more straightforward, like Import channels on your device

Agree it should change, and also the action or statement here is conditional depending on who's logged in. Here's my suggestion, comparing what it is for super admins on 0.14 and proposal for learners on after this setup

<img width="1351" alt="Screen Shot 2021-08-05 at 12 47 08 PM" src="https://user-images.githubusercontent.com/6668144/128411908-aaa5bf91-642e-4aa3-9991-54174571d9c1.png">

**Comment by jredrejo** [comment]
@jtamiace  by accident I commited this into the release-v0.15.x branch so there's no PR to fix this issue.
This is the current behaviour:
![Peek 17-08-2021 18-57](https://user-images.githubusercontent.com/1008178/129768772-5669d83c-5dac-4d30-81cf-81f96d31043e.gif)

For the learn page, beware in a LOD the user can import content from the server, it does not have to be an admin.
Also, as you can see in the animated gif, after syncing there might be already classes so the Learn tab does not have to be empty.

Please, check it to confirm if we can close this issue or further work is needed.

**Comment by jtamiace** [comment]
Thanks @jredrejo, I think that addresses it.

One last minor thing - after clicking `FINISH`, the user should be directed to the Channels page, then be shown the "Welcome" modal, instead of seeing it while still in the wizard

<img width="1647" alt="Screen Shot 2021-08-18 at 9 26 55 AM" src="https://user-images.githubusercontent.com/6668144/129936077-d5d0e19b-ba35-4705-8ccb-ab29d6f75dc0.png">
