### ISSUE TITLE
allow SVG icons to be put in core and used across all apps

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#832]
Currently, we use a custom 'svg inliner' webpack loader to insert SVG into our vue templates. However, the loader is not leverage webpack's path resolution system, and so all SVG paths are relative to the current vue file.

This means that we have duplicated icons in every app; re-used icons should instead be available from core.

**Comment by christianmemije** [comment]
Maybe useful? https://github.com/google/material-design-icons/tree/master/sprites

**Comment by indirectlylit** [comment]
I don't think a sprite sheet would be compatible with using CSS selectors on the SVG: https://github.com/google/material-design-icons/tree/master/sprites#css-selectors-transformation-and-the-shadow-dom

Note that the 'svg inline' loader means that all icons are loaded at one time, so (like a sprite sheet) it prevents many small HTTP requests.

see also: https://css-tricks.com/inline-svg-best-svg/

**Comment by indirectlylit** [comment]
see also: https://github.com/learningequality/kolibri/issues/839

**Comment by indirectlylit** [comment]
this is done
