### ISSUE TITLE
Kolibri fails to start after installing the latest Buildkite builds

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8338]
## Observed behavior
After installing the Windows or Debrian build from:
https://buildkite.com/learningequality/kolibri-python-package/builds/3459 and https://buildkite.com/learningequality/kolibri-python-package/builds/3457 the app seems to be getting in an infinite boot loop with the following notification being displayed repeatedly: 'Kolibri is starting... Please wait' 

## Steps to reproduce the issue
1. Go to https://buildkite.com/learningequality/kolibri-python-package/builds/3459 or https://buildkite.com/learningequality/kolibri-python-package/builds/3457 and install the build.
2. Attempt to run Kolibri and go through the Setup Wizard.

## Logs
[UbuntuLogs.zip](https://github.com/learningequality/kolibri/files/7031830/UbuntuLogs.zip)
[WindowsLogs.zip](https://github.com/learningequality/kolibri/files/7031831/WindowsLogs.zip)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: Chrome

**Comment by rtibbles** [comment]
Looking at the logs, the same pattern emerges. Kolibri starts, and then as soon as it has started, Kolibri stops.

This text in the logs "Stopping server." is indicative that the `stop` command has been issued somehow, or at the very least that the `process_control.flag` file has `stop` in it.

**Comment by rtibbles** [comment]
On further investigation it seems likely that this is a manifestation of this: https://github.com/learningequality/kolibri/issues/8271
