### ISSUE TITLE
Provisioning learn-only device in setup wizard doesn't resync until restart

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#8344]
## Observed behavior

1. Start a fresh instance of Kolibri
2. Go through the Advanced setup wizard, selecting "learn-only" device
3. Authenticate with the remote server using the learner credentials
4. Finish setup
5. Observe the Kolibri instance does not resync with the server
6. Restart Kolibri
7. Observe the Kolibri instance does resync with the server

## Errors and logs

N/A

## Expected behavior

Kolibri always makes recurring requests to sync with the server when provisioned as a SoUD

## User-facing consequences

Broken expectation that SoUD make recurring syncs with the server

## Context

Latest Kolibri `release-v0.15.x`
Ubuntu 20.04
Chrome

**Comment by radinamatic** [comment]
Odd, I don't recall having to restart the learn-only VM yesterday when I was testing the #8341... 🤔

**Comment by bjester** [comment]
@rtibbles @jredrejo I believe the issue is that the hooks in the Zeroconf listeners that trigger the recurring sync requests are not triggered when a fresh Kolibri is setup as a SoUD because at the time they're invoked, the device isn't a SoUD yet. So it won't trigger requests for syncing because that detection logic needs re-run with the new SoUD status after completing the setup wizard.

**Comment by rtibbles** [comment]
Ahh - right. So when provisioning has finished for a SoUD/Learner only device, we should look at the `DynamicNetworkLocation` table, and run `begin_soud_sync` for every user!

**Comment by jredrejo** [comment]
yes, that's something the wizard could do, or restarting zeroconf would automatically do the same things, if that's possible from the python code. I'm speaking blindly (I haven't looked at the zereoconf code to see if that's possible yet)

**Comment by rtibbles** [comment]
I recently added this logic for reinitializing zeroconf if the recorded network addresses changed: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/discovery/utils/network/search.py#L281 we could definitely do something similar because its status has changed.

**Comment by jredrejo** [comment]
> I recently added this logic for reinitializing zeroconf if the recorded network addresses changed: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/discovery/utils/network/search.py#L281 we could definitely do something similar because its status has changed.

https://github.com/learningequality/kolibri/pull/8370/files#diff-35a619d54c106b0ec05d18ca338eaa77909ba1641f516826c54938dee1fa5017 is what #8370 does, so it seems we are in tune
