### ISSUE TITLE
Kolibri-beta - 404 Not Found error shown for all HTML5 resources 

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8356]
## Observed behavior
I'm getting a 404 Not Found error for each HTML5 resource from the Kolibri QA Channel at kolibri-beta. The resources are working correctly in any of the Kolibri 0.15.0a2 builds that I have installed locally.

## Expected behavior
The HTML5 resources should be displayed correctly.

## Steps to reproduce the issue
1. Go to https://kolibri-beta.learningequality.org/en/learn/#/topics/t/c98cdf0a207041398f50c52e8bfdd6b5
2. Attempt to view any of the available HTML5 resources.

## Additional information
![2021-08-30_16-47-06](https://user-images.githubusercontent.com/79847249/131349415-8429d283-572b-4509-894e-a11bf106a47d.png)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by rtibbles** [comment]
Note that this is a deployment issue with the kolibri demo server specifically, so is more of a dev ops issue.

**Comment by radinamatic** [comment]
> deployment issue with the kolibri demo server specifically

**Kolibri Beta**, not Kolibri Demo, where HTML resources on 0.14.7 are displayed correctly. 🙂

**Comment by rtibbles** [comment]
Kolibri Demo will have the same issue once upgraded to 0.15 though, unless the appropriate devops steps are taken!
