### ISSUE TITLE
issue with 'get a hint' function in RTL

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8363]
The 'use a hint' link should be left-aligned. If possible it should use the `KLabeledIcon` component:

![image](https://user-images.githubusercontent.com/2367265/59951658-9aab0980-9447-11e9-8b4b-3b3c46b1c02f.png)

**Comment by pcenov** [comment]
Fixed in 0.15.1 - the RTL text is left aligned.
@radinamatic

**Comment by rtibbles** [comment]
Excellent - seems like hint and content rendering updates in 0.15 fixed this.
