### ISSUE TITLE
Three small styling bugs in exercise renderer

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#8364]
### 1/ 
Font and styling text inside `<pre>` tag changes drastically between responsive breakpoints
![Screenshot_2020-03-17 Preguntas de Evaluación - Option 2 - CommonLit Test - Kolibri](https://user-images.githubusercontent.com/163966/77205750-def93200-6acb-11ea-8e8e-e24c3026310f.png)

----

### 2/ 
Horizontal line separators between answers stick out too far on smallest responsive brekpoint
![Screenshot_2020-03-17 Preguntas de Evaluación - Option 2 - CommonLit Test - Kolibri(2)](https://user-images.githubusercontent.com/163966/77205486-58445500-6acb-11ea-88bb-5279368ae36d.png)

for 1/ and 2/ see http://35.185.120.102/en/learn/#/topics/c/ba2b32b657104fe4b73748191693a725

----

### 3/ 
Hint numbering appears weird
<img width="365" alt="Screen Shot 2020-03-20 at 4 17 16 PM" src="https://user-images.githubusercontent.com/163966/77205245-d5bb9580-6aca-11ea-82e9-f49dd54c41d6.png">
see https://kolibridemo.learningequality.org/en/learn/#/topics/c/ba92f5cc02e7528abaf36108262f4772

Of these only 1/ is important because we'll be using it for CommonLit text passages and will get a lot of external visibility in coming weeks.

**Comment by pcenov** [comment]
@radinamatic I cannot replicate the above listed issues in 0.15.1

**Comment by rtibbles** [comment]
Closing - fixed by styling updates in 0.15.
