### ISSUE TITLE
No option to go 'back' on setup wizard individual user account import

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8377]
## Observed behavior

After reaching this screen, I wanted to go 'back':

![image](https://user-images.githubusercontent.com/2367265/131685897-62dcda8e-1332-489f-a242-1e6bf4dcc4ed.png)

There is no option so I had to refresh and start over

## Expected behavior

all screens should have back buttons if possible

## User-facing consequences

makes it harder for user to experiment and explore various setup options

## Context

latest 0.15

**Comment by indirectlylit** [comment]
this is actually a critical issue. If you click 'import another user' and decide you don't actually want to import another user, you're stuck here with no recourse

**Comment by jredrejo** [comment]
mmm, finish should be available but going back is not an option if you have already imported an user. It's not possible to change to a different setup.

**Comment by indirectlylit** [comment]
That makes sense.

In the original issue I hadn't yet imported a user and wanted to go back. I guess it was not clear to me as a user at what point I enter a "point of no return"

**Comment by indirectlylit** [comment]
cc @jtamiace

**Comment by jtamiace** [comment]
Yeah the back arrow should show and hide conditionally based on whether it's the first time importing a user during setup or not

Full flow:
https://www.figma.com/file/w3raYcGRUhhaVm1Of8Dcvo/0.15-Device-setup?node-id=142%3A247

![setup](https://user-images.githubusercontent.com/6668144/132378947-418ac363-2e02-419b-bb01-c26217024d4c.jpg)
