### ISSUE TITLE
confusing flow during individual user import

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8378]
## Observed behavior

| | |
|--|--|
| Initially there's a disabled 'finish' button | ![image](https://user-images.githubusercontent.com/2367265/131686780-3b88721f-8417-405b-8c28-fd2b4d106048.png) |
| Afterward, 'finish' is the only option even though there are no users to import | ![image](https://user-images.githubusercontent.com/2367265/131686804-039d8114-74d9-4caf-831b-fa3ca8d32bbf.png) |
| After clicking 'finish', unceremoniously ejected from setup wizard even though previous step was 2 of 4 | ![image](https://user-images.githubusercontent.com/2367265/131686907-32341ad1-dafe-45c9-a0c9-587687f16794.png) |

## Expected behavior

* During the 'import user' flow, I would expect the two options to be 'import' or 'cancel'. 'finish' doesn't make sense to me here.
* The 'import user' flow is an internal flow within the overall setup wizard. Clicking 'finish' during individual user import should not also finish the overall setup wizard

## User-facing consequences

confusing behavior during individual user import

## Context

latest 0.15

**Comment by rtibbles** [comment]
This has been updated in 0.16, and should be addressed.
