### ISSUE TITLE
Android App - Responsive design issues

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8380]
## Observed behavior
There are many screens with text or button layout issues when the app is viewed in a mobile phone.

## Expected behavior
All pages should be optimized for mobile devices.

## Steps to reproduce the issue
1. Install the Android [build](https://buildkite.com/learningequality/kolibri-android-installer/builds/2548#7d02075f-02ab-40ea-8f21-aa8bd75782f2) on a mobile device.
2. Interact with the app.

## Screenshots

1 | 2 | 3
--- | --- | ---
![Screenshot_20210901-103337_Kolibri](https://user-images.githubusercontent.com/79847249/131698043-42d4e2e6-ad3f-473e-8ac8-29c2da752dd1.jpg) | ![Screenshot_20210901-103350_Kolibri](https://user-images.githubusercontent.com/79847249/131698046-79e02342-d54c-4cef-b15e-57f626deaf85.jpg) | ![Screenshot_20210901-162205_Kolibri](https://user-images.githubusercontent.com/79847249/131698047-2ee8ec20-10dc-4d65-9384-34a23fee785f.jpg)

4 | 5 | 6
--- | --- | ---
![Screenshot_20210901-162225_Kolibri](https://user-images.githubusercontent.com/79847249/131698048-373fbf3a-c940-4fe3-936c-3dfb6b146446.jpg) | ![Screenshot_20210901-162727_Kolibri](https://user-images.githubusercontent.com/79847249/131698052-145dc281-0ef0-4447-ae15-4db6b85f5554.jpg) | ![Screenshot_20210901-162917_Kolibri](https://user-images.githubusercontent.com/79847249/131698053-6d8a1ccf-6d30-4b3c-a94c-be2abc423b19.jpg)

## Usage Details
 - OS: Android 11
 - Device: Samsung Galaxy Note 10 Lite

**Comment by MBKayro** [comment]
for a tablet 10' it look great with the latest 0.15.x git 
video and html5 are great

**Comment by marcellamaki** [comment]
Closed with #8802

ETA too many android issues -- this actually is separate

**Comment by radinamatic** [comment]
1 & 2 are still extant in the setup wizard when installing from APK on Android @marcellamaki, and you should  be able to replicate if you start without the home folder even on desktop, to trigger the setup wizard.

Android | Firefox on Ubuntu
--- | ---
![setup-wizard](https://user-images.githubusercontent.com/1457929/146447327-0379fdd8-9b75-4f23-9201-d3bbfd123c10.gif) | ![setup-wizard-browser](https://user-images.githubusercontent.com/1457929/146447718-5b85f98a-9796-4630-b96b-9744220e451e.gif)

**Comment by radinamatic** [comment]
Note that the **Select network address** modal is nice and responsive in the step to select the server device for channel import towards the end of the workflow: it should be that way even when selecting the device to import the learner account at the beginning.

**Comment by indirectlylit** [comment]
note to watch out for tab order, and try to ensure that the primary button comes first. 

For example:

![image](https://user-images.githubusercontent.com/2367265/146454598-e6c6c497-16b4-4217-a895-77173dd8456e.png)

This looks backwards.

Modals are supposed to actually have special logic so that 'cancel' displays on the left but comes second in tab order.
