### ISSUE TITLE
Android App - Constantly getting a "Disconnected from server error" in an Android 5.1 device

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8381]
## Observed behavior
I'm constantly getting a "Disconnected from server error" in an old Android 5.1 device. When I stop and then start again the app it gets stuck at the starting screen and I have to restart the device.

## Errors and logs
[logs.zip](https://github.com/learningequality/kolibri/files/7092456/logs.zip)

## Steps to reproduce
1. Install the Android build on an Android 5.1 mobile device.
2. Interact with the app.

## Screenshots
![Screenshot_2021-09-01-16-10-54](https://user-images.githubusercontent.com/79847249/131700379-92b5d5fd-fea6-4fd3-b97e-f1390b600577.png)

## Context
Device: Nexus 4
Android: 5.1.1

**Comment by rtibbles** [comment]
Hrm, this looks very much like the server is shutting down for some reason. Unfortunately getting good logs off the app is almost impossible at the moment.

**Comment by MBKayro** [comment]
the only way i test to keep sync is to change the port from 8080 to 8086.

many time it stop syncing to server at first, then it disconnect completely.

tested in the latest git 0.15.x

**Comment by rtibbles** [comment]
We are no longer able to publish versions of the app that support Android 5, so I am closing this issue as wontfix.
