### ISSUE TITLE
incorrect message shown to learner with import permission

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8392]
## Observed behavior

"As an administrator..." shown to learner

![image](https://user-images.githubusercontent.com/2367265/132049377-3da6b257-8233-45d4-8e6f-59f83cde3a2e.png)

## Expected behavior

messaging appropriate for any user with content management permission

## User-facing consequences

confusing messaging

## Steps to reproduce

import a single learner on a SOUD

## Context

latest `develop`

**Comment by radinamatic** [comment]
This has been reported previously (after our first SoD hack session), should have been fixed in 0.15...? 

https://github.com/learningequality/kolibri/issues/8308#issue-972785185

**Comment by indirectlylit** [comment]
it's possible that the changes haven't been merged from 0.15 to develop yet, but I don't see the updated string in the PR that closed that issue: https://github.com/learningequality/kolibri/pull/8367/files

**Comment by rtibbles** [comment]
I think there had been a string edit, but it seems to have gone walkabout.

**Comment by jredrejo** [comment]
> it's possible that the changes haven't been merged from 0.15 to develop yet, but I don't see the updated string in the PR that closed that issue: https://github.com/learningequality/kolibri/pull/8367/files

Nope, the mentioned PR ensures the user is sent to the device screen, where he's told to import channels, after the setup finishes, but he's free to move to the Learn page and nothing was changed there.

**Comment by radinamatic** [comment]
Is the `kolibri/plugins/learn/assets/src/views/ContentUnavailablePage.vue` page different depending on the device type (Full vs. SOUD)? I assumed that just changing these 2 strings would be enough, but if I do that, go through the setup wizard for full device but NOT import anything, and visit as a learner afterwards, admin side looks good, but on learner side, the phrase would look better as just `Ask your coach or administrator for assistance`.

![LEDev2104 (start)  Running  - Oracle VM VirtualBox_028](https://user-images.githubusercontent.com/1457929/132259574-bd7332cb-ceca-4fb5-8ca9-eb8046bdb698.png)

Question becomes if these 2 strings will appear together (as proposed in #8308) when the user goes through the setup wizard on the SOUD device? 

![soud](https://user-images.githubusercontent.com/1457929/132260091-8d749259-2c76-491a-a3f1-1f5e1136eabc.png)


I can't really test manually unless I open the PR and grab the asset from Buildkite, right?
