### ISSUE TITLE
sync tasks are affecting channel import UI

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8393]
## Observed behavior

background syncing is causing the channel UI to display incorrect information:

![2021-09-03 14 13 38](https://user-images.githubusercontent.com/2367265/132049636-5bd91d55-a3a2-4488-a632-3136c528dcab.gif)

## Expected behavior

sync tasks should not affect channel UI

## User-facing consequences

confusing / incorrect behavior

## Context

latest `develop`

**Comment by rtibbles** [comment]
@vkWeb this is where better filtering of tasks would be very helpful, to just return the content related tasks here!

**Comment by vkWeb** [comment]
Yesss! I love when our work solves issues like these :tada: 

@rtibbles You can assign this issue to me. Will be resolved after shifting tasks to their respective django apps and updating the client. I'll handle both the work - shifting as well as the frontend.
