### ISSUE TITLE
noisy syncing logs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8394]
## Observed behavior

when devices are auto-syncing, both the source and target device get a lot of repetitive information written to the logs:

![image](https://user-images.githubusercontent.com/2367265/132049933-3a3897c5-e783-4699-95be-25c09ca04f5e.png)

## Expected behavior

If possible, these should be made quieter - maybe one line for each attempted sync?

## User-facing consequences

This could make it more difficult for users (and us) to find important information like errors in the logs, and could also cause log file sizes to grow very large

## Context

latest `develop`

**Comment by rtibbles** [comment]
I think it would make sense to move a lot of the intermediary stages to debugging logs?
