### ISSUE TITLE
Remove the obsolete user strings with 'active/inactive'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8420]
## Observed behavior
[Prior discussion on Slack](https://learningequality.slack.com/archives/CB37UM23A/p1631222446061300)
We currently use naming strategy of **Open/Closed** exam and **Visible to learners** for lessons. 

[Full list of the strings in question](https://www.notion.so/learningequality/833e2a916545468295b2b2933a8f0290?v=3e22809b9b374830a9ad5505c1b81021)

## Errors and logs
…

## Expected behavior
…

## User-facing consequences
…

## Steps to reproduce
…

## Context
…

**Comment by rtibbles** [comment]
Fixed in #8421
