### ISSUE TITLE
Importing channel gets stuck

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#847]
## Summary

First channel I installed was OK, but the second got stuck in the Manage tab, even though the content seems available. `Importing from Curation Server... Please wait...` is present even after restarting the VM.

## System information

 - Version: `pip install` `kolibri-0.1.1rc3`
 - Operating system: Ubuntu 16.10
 - Browser: Firefox 50

## Screenshots

The first install gets stuck: 
![ubuntu 16 10 start running - oracle vm virtualbox_001](https://cloud.githubusercontent.com/assets/1457929/22380613/f4ba10fe-e4b5-11e6-865a-04a067b10796.png)

After the VM restart:
![ubuntu 16 10 start running - oracle vm virtualbox_002](https://cloud.githubusercontent.com/assets/1457929/22380624/0030dc38-e4b6-11e6-832a-9ad7a73a1f15.png)

Content is there:
![ubuntu 16 10 start running - oracle vm virtualbox_003](https://cloud.githubusercontent.com/assets/1457929/22380717/53fb141e-e4b6-11e6-903b-8aa5cc6020c0.png)

**Comment by DXCanas** [comment]
Confirming. Blocks #769. My behaviour is a bit different, though. The bar doesn't fill at all, won't go away with refresh, and the only thing I have to show for the UI import is a blip in the console for a `POST`
![image](https://cloud.githubusercontent.com/assets/9877852/25877377/0b292498-34d8-11e7-8913-386780d285aa.png)

The UI:
![behavior](https://cloud.githubusercontent.com/assets/9877852/25877381/15b8820a-34d8-11e7-92dd-ac8025b1c316.png)

**Comment by radinamatic** [comment]
> My behaviour is a bit different, though. 

Well, you did dig this up from the dead... :joy:

**Comment by DXCanas** [comment]
The dead don't manifest into issues :smirk:

**Comment by radinamatic** [comment]
David will not suffer the Dead to pass!!! :crossed_swords:

**Comment by indirectlylit** [comment]
let's hold off working on import/export issues. Will be addressed during work by @jonboiser and @aronasorman on the UI and BBQ.

**Comment by jonboiser** [comment]
@aronasorman I've experienced similar behavior as in @DXCanas screenshot up there, where a command (i.e. `startremoteimport`) is sent but there is no effect.

Do you know why that fails, and whether we can send an appropriate response (instead of 200 OK) back?

**Comment by radinamatic** [comment]
Not able to reproduce this error on latest 0.5.0 build.

## System information

 - Version: [`0.5.0-beta1-dev22`](https://buildkite.com/learningequality/kolibri/builds/1673)
 - Operating system: Windows 7 & 10, Ubuntu 16.10
 - Browser: Chrome & Firefox

The original issue is 6 months old, not extant anymore, and there are several other, more recent content import issues, so I'm closing this.
