### ISSUE TITLE
'View learner devices' link present only on 'Reports > Quizzes'

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8475]
## Observed behavior
Probably just an oversight, see the [Slack convo](https://learningequality.slack.com/archives/CB37UM23A/p1633023528287000).

![view-learner-devices](https://user-images.githubusercontent.com/1457929/135510600-81117b8d-8f99-4d2d-8821-461fb82691a3.gif)

## Errors and logs
…

## Expected behavior
Coaches able to access the list of learner devices from all 4 subtabs in Reports: Lessons, Quizzes, Groups and Learners.

## User-facing consequences
Unclear and inconsistent UI for coaches.

## Steps to reproduce
…

## Context
 * Kolibri version: 0.15, `develop` branch
 * Operating system: all
 * Browser: all

**Comment by rtibbles** [comment]
Fixed in #8715
