### ISSUE TITLE
Not possible to change username and password at the same time

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#848]
## Summary

Not really a bug, but a bit misleading for a user, as the changes in username are not recorded IF they change the value in the `Username` field and then press the `Reset password` button. With this workflow only the password change is recorded in the DB. The ideal would be to add and alert if the after any change in the `Username` field admin does not press the `Confirm` button. Not sure if this is possible... :thinking: 

## System information

 - Version: `pip install` `kolibri-0.1.1rc3`
 - Operating system: Ubuntu 16.10
 - Browser: Firefox 50

![peek 2017-01-27 19-11](https://cloud.githubusercontent.com/assets/1457929/22382247/c0aaeca0-e4bc-11e6-99b5-a77374cbdebc.gif)

**Comment by 66eli77** [comment]
It seems a legit UX issue, @jtamiace @@khangmach any ideas?

**Comment by jtamiace** [comment]
I've been under the impression that clicking "save" on the change password screen would take the user back to the main edit account info page. That way, the username could remain there.

Might also be good to rename "save" to "save new password" so that the user is clear what data is going to be altered (if they had edited either the "full name" or "username" field previously

**Comment by khangmach** [comment]
I think this is fine the way it is. Two separate processes. We want the user to focus on one process at a time, no need for confirmation/error messages. The ONLY way to change and save a username is to hit "confirm".

To make this more clear, we should NOT have the process for resetting password be titled "Edit Account Info", but change it to "Reset Password". 

Would also suggest removing "Username: techsavvy" entirely from the update password modal to avoid confusion. It's irrelevant to the password changing process.

**Comment by 66eli77** [comment]
just tested this, under `reset password` click `save` will leave the editing mode and actually save the password change.

**Comment by radinamatic** [comment]
The behavior is still as described by @66eli77: clicking `Save` on `Reset password` will close the `Edit account info` modal completely, and if admin changed the username too, that change is not registered. I would favor the scenario mentioned by @jtamiace: clicking `Save` on `Reset password`  should commit that change to db, and *not* close the `Edit account info` modal, but allow the user to finish editing the rest of the fields if necessary, and then confirm and close the modal completely.



## System information

 - Version: [`0.4.0-446-gd1737c5`](https://github.com/learningequality/kolibri/pull/1805)
 - Operating system: Windows 7
 - Browser: Chrome

**Comment by christianmemije** [comment]
Fixed #2154
