### ISSUE TITLE
Import individual user accounts - Wizard is stuck on the 'Loading user' step

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8489]
## Observed behavior
The setup wizard gets stuck at the 'Loading user' screen when I attempt to import a learner user.
I then have to go back to http://127.0.0.1:8080/en/auth/#/signin to sign in as the imported learner user.

## Expected behavior
It should be possible to import one or several learners and automatically get logged in with the last one.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-python-package/builds/3842) on at least 2 devices.
2. Create a server device.
3. Start the wizard on the client device and attempt to import a learner.

## Additional information
![2021-10-11_18-24-42](https://user-images.githubusercontent.com/79847249/136818114-c5b0aa80-686c-4519-83cd-37aac9fbf88e.gif)

## Logs
https://drive.google.com/drive/folders/1zKyWrtJOFuOBLoDPhbsFM_ITME4Hg2zR?usp=sharing

## Usage Details
 - OS: Windows 10 (client) and Ubuntu (as a server)
 - Browser: Chrome

**Comment by rtibbles** [comment]
Fixed in #8569
