### ISSUE TITLE
ZIP and PNG labeled as "Unknown Format"

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#849]
## Summary

Happens in the dropdown element for downloading content (CK-12 channel).

## System information

 - Version: `pip install` `kolibri-0.1.1rc3`
 - Operating system: Ubuntu 16.10
 - Browser: Firefox 50

## Screenshots

![peek 2017-01-27 19-44](https://cloud.githubusercontent.com/assets/1457929/22383341/4ff2cf46-e4c1-11e6-933b-71483622f1a1.gif)

**Comment by 66eli77** [comment]
seems fixed 
![screen shot 2017-02-15 at 11 53 02 am](https://cloud.githubusercontent.com/assets/5577205/22992701/583128e8-f375-11e6-9d31-041fefb51569.png)
