### ISSUE TITLE
category filter text is Title Case

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8490]
## Observed behavior

Category filter text Title Case:

> ![image](https://user-images.githubusercontent.com/2367265/136828808-3e987171-d4de-4e2d-b3af-e8cce8b6d356.png)

## Expected behavior

Sentence-style caps: https://design-system.learningequality.org/writing/#punctuation

## User-facing consequences

Phrases like "For Teachers" and "None Of The Above" look a bit strange when written using Title Case.

## Context

0.15

**Comment by AbhijithGanesh** [comment]
@rtibbles can I be assigned this issue? I would like to contribute to this repo and it'd be my first contribution

**Comment by marcellamaki** [comment]
Closing as resolved

<img width="1423" alt="Screen Shot 2022-12-20 at 9 39 14 AM" src="https://user-images.githubusercontent.com/17235236/208692538-a01d24b2-1b80-4067-99f1-b7f6f4bcb2c2.png">

**Comment by indirectlylit** [comment]
yay! :)
