### ISSUE TITLE
learner home page layout might not fully use available screen real estate

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8491]
## Observed behavior

It's hard to see multiple sections "at a glance" even when there is space available:

![image](https://user-images.githubusercontent.com/2367265/136829724-0a537661-debe-4a1d-bff9-9daf1158e35a.png)

## Expected behavior

The coach home page seems to make slightly better use of screen real estate on larger screens using two columns

## User-facing consequences

More scrolling than necessary, and learners might not see bottom sections

## Context

current 0.15 development

**Comment by indirectlylit** [comment]
cc @jtamiace

**Comment by rtibbles** [comment]
The home page has changed significantly since this report was filed, so I am going to close this.
