### ISSUE TITLE
remove references to `learn` plugin from `user_profile` plugin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8494]
## Observed behavior

Logic in the profile editor page has some hard-coded references to Learn plugin:

https://github.com/learningequality/kolibri/blob/2f12791e9d974b3c7dc417f2aefb1c0a041ab20a/kolibri/plugins/user/assets/src/views/ProfileEditPage.vue#L158-L164

## Expected behavior

Plugins should be as independent of one another as possible. In this case, can probably just redirect to the 'next' query param if it is set.

## User-facing consequences

Could cause breakage in a case where a custom plugin was also using `learn` as its URL. For example, this could happen if someone forked our learn plugin.

## Context

0.15

**Comment by AbhijithGanesh** [comment]
Is this issue relevant? Is there something I can do?

**Comment by indirectlylit** [comment]
this has already been addressed in https://github.com/learningequality/kolibri/pull/8575
