### ISSUE TITLE
Use SWC instead of Babel for faster ES5 transpilation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8499]
One of the bottlenecks for our build pipeline is the use of Babel for transpilation. [SWC](https://swc.rs/) is reported to be significantly faster than Babel, and to do functionally equivalent transpilation and polyfilling.

Looking at the configuration it seems to aim to be as similar to babel in configuration as possible, down to the inclusion of a `preset-env` option.

It also has a loader for integration into Webpack, so we should be able to do a drop in replacement: https://github.com/swc-project/swc-loader

Note that this is preferred to using a next generation build system like ESBuild, Parcel, or Vite, because of the continued support for ES5 transpilation that is needed for our browser targets.

**Comment by nucleogenesis** [comment]
I spent some time getting SWC working in place of Babel in our Webpack config per this [LogRocket blog](https://blog.logrocket.com/migrating-swc-webpack-babel-overview/) and it was slower by ~5-10% or so.

SWC is supposed to be suited for a full-on webpack replacement, so I'll come back and see what that might look like and update here based on what I find but the simplest potential change didn't pan out as we hoped ( at least not on my machine :-D )

**Comment by rtibbles** [comment]
Damn, I guess there's no free lunch after all!
