### ISSUE TITLE
Admin view: independent practice quizzes can be imported, managed, and deleted from the device

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8507]
### User stories for this issue:
| User story | Design |
| -- | -- |
|1. As an **admin user**, I want to be able to see all the available independent practice quizzes show up along with all the other resources in the topic folders of channels that contain independent practice quizzes so that I can **select them for import**. | ![Screen Shot 2021-10-20 at 12 15 24 PM](https://user-images.githubusercontent.com/13563002/138158008-9534bad4-6f75-47a8-ac5e-52b69743944e.png)|
| 2. As an **admin user**, I want to be able to see all the available independent practice quizzes show up along with all the other resources in the topic folders of channels that contain independent practice quizzes so that I can **select them for deletion or export**. | ![Screen Shot 2021-10-20 at 12 15 05 PM](https://user-images.githubusercontent.com/13563002/138158245-8dc6e5c5-b409-4aff-80ef-2af67b562bde.png) |

### Notes and changes to current designs:
- [Figma file for admin view](https://www.figma.com/file/TfaSTT9gs6fPKhGdNUjffU/Channel-quizzes?node-id=17%3A463)
- import/export/deletion behavior should be the same as current behavior, but with the correct icon to indicate that it is an independent practice quiz.
- All strings required should already be in `commonCoreStrings`, `commonCoachStrings`, or `commonLearnStrings`
- this differs from how we currently categorize content for lessons and quizzes in that it is content that can both be used as content in a lesson or channel AND assigned as a quiz, so for this issue, the icon should reflect that, and behaviorally, it should behave as if an admin were to import/export/manage it onto the device.

### Criteria for success:
**Please copy these into your PR for "Steps for Testing"!**
_This issue is done when the **3 Gherkin stories** below work._
- [x] Independent practice quizzes are able to be imported onto your device
```
Feature: Independent practice quizzes are able to be imported onto your device
	Independent practice quizzes show up as selectable content during content import

	Scenario: I am browsing a channel's content and decide to select independent practice quizzes
		Given that I am on the content selection screen for a particular content channel
		When I scroll down to the content selection tree
		Then I can see independent practice quizzes
			And those independent practice quizzes should be selectable
		When I select an independent practice quiz
		Then I see the space it'll take up on my device
			And I see the checkbox state changed from empty to a checked state
```
- [x] Independent practice quizzes are able to be exported from your device
```
Feature: Independent practice quizzes are able to be exported from your device
	Independent practice quizzes show up as selectable content during content management

	Scenario: I am editing (managing) a channel and decide to export independent learning quizzes
		Given that I am managing a channel in the 'Channels' tab in 'Device'
		When I have one or more independent practice quizzes selected
			And I press the 'export' button in the bottom bar
		Then I see a dialog appear prompting me for an export destination
```
- [x] Independent practice quizzes are able to be deleted from your device
```
Feature: Independent practice quizzes are able to be deleted from your device
	Independent practice quizzes show up as selectable content to be deleted
		
	Scenario: I am editing (managing) a channel and decide to delete independent practice quizzes	
		Given that I am managing a channel in the 'Channels' tab in 'Device'
		When I have one or more independent practice quiz selected
			And I press the 'delete' button in the bottom bar
		Then I see a dialog appear confirming my delete action
```

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8507?planning-poker) with ZenHub @jredrejo @marcellamaki @sairina @rtibbles @MisRob @nucleogenesis @jamalex

**Comment by sairina** [comment]
This works! Closing the issue.
