### ISSUE TITLE
Coach view: update Gherkin stories for independent practice quizzes as normal quizzes

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8519]
## Observed behavior

We have to update the Gherkin story that checks that the workflow for when a coach assigns an independent practice quiz as a regular quiz is the same as when a coach assigns an exercise as a regular quiz. It is currently in `coach-create-quiz.feature` as a `channel-based quiz`

See [link to `coach-create-quiz.feature` for current stories](https://github.com/learningequality/kolibri/blob/release-v0.15.x/integration_testing/features/coach/coach-create-quiz.feature#L226)

## Expected behavior

We'll need to create or update this Gherkin story to reflect the following two user stories (with the correct terminology of "independent practice quiz" or "practice quiz" instead of "channel-based quiz":
1. As a coach, when I select an independent practice quiz as a regular quiz to be assigned to learners in my classes, I want this to follow the same current user story as if it were assigned as a regular quiz so that there is no difference in user experience for the coach.
2. As a coach, when I view a quiz report from an independent practice quiz that was assigned as a regular quiz, I want this to follow the same, current user story as if I were viewing a quiz report from an exercise so that there is no difference in user experience for the coach.

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8519?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles
