### ISSUE TITLE
Learner view new component: `<PracticeQuizRenderer>`

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8520]
### Summary
Currently, we have a normal quiz rendering experience. This is from `KContentRenderer`, `AssessmentWrapper`, and in the workflow, is primarily found in two components, `<ExamPage>` and `<ContentPage>`. 

- We will want to include the new `<PracticeQuizTimer>`.
- [In `<ContentPage>`](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/ContentPage.vue), we will want to add the `<PracticeQuizRenderer>` as another option for display. 
- [In `<ExamPage>`](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/ExamPage/index.vue), we will want to add the `<PracticeQuizRenderer>` as another option along with the current `KContentRenderer`
- Note: the renderer will have to have very similar props signatures as `KContentRenderer` and `AssessmentWrapper` in order to slot it in easily to `<ExamPage>` and `<ContentPage>`
- This issue also includes adding in mobile and tablet responsiveness.

|Frame|Explanation|
|--|--|
|![Screen Shot 2021-10-25 at 11 36 12 PM](https://user-images.githubusercontent.com/13563002/138821743-53eb3dff-c7ce-4efa-b255-fccc7b95f6cd.png)|**NEW** Independent practice quiz rendered|
|![Screen Shot 2021-10-25 at 11 36 51 PM](https://user-images.githubusercontent.com/13563002/138821828-6d3753ca-cab7-41de-8b26-4a367d6f55e9.png)|Tablet rendered|
|![Screen Shot 2021-10-25 at 11 37 12 PM](https://user-images.githubusercontent.com/13563002/138821900-0b753284-061e-44a1-8a77-b7e483615ca3.png)|Mobile rendered|
|![Screen Shot 2021-10-25 at 11 33 52 PM](https://user-images.githubusercontent.com/13563002/138821453-46fcb80b-b903-47b9-ade1-07419bcb4d08.png)|Regular quiz (for comparison)|

### Notes and changes to current designs:
- [Figma for the independent practice quiz base and responsiveness](https://www.figma.com/file/TfaSTT9gs6fPKhGdNUjffU/Channel-quizzes?node-id=76%3A130)
- All strings required for this component should already be in `commonCoreStrings`, `commonCoachStrings`, or `commonLearnStrings`
- If a learner exits a practice quiz before they have submitted (not all of these may be important for this issue):
   - the timer resets
   - user will be returned to the page where they found the independent practice quiz (channel or lesson)
   - the "Completion status" at the bottom of the card should reset to "in progress"

### Criteria for success:
**Please copy these into your PR for "Steps for Testing"!**
_This issue is done when the checkboxes below work_

- [ ] Practice quiz renders correctly for learner through `<ExamPage>` and `<ContentPage>`
- [ ] Practice quiz renders correctly in different screens
- [ ] If there additional scenarios, please include them in your PR

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8520?planning-poker) with ZenHub @jredrejo @marcellamaki @sairina @rtibbles @MisRob @nucleogenesis @jamalex

**Comment by rtibbles** [comment]
May require additional testing of existing coach assigned workflows in order to ensure that no regressions have occurred.

**Comment by rtibbles** [comment]
Fixed in #8645 - implemented as `QuizRenderer`
