### ISSUE TITLE
Coach view: Create routes for independent practice quiz workflows

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8521]
Creating routes creates a skeleton for other devs to implement their component and state work within, so this should smooth the path for further development on the overall feature.

This will comprise of the four main routes for a coach:
- [x] Checking the route for putting a practice quiz inside a lesson
- [x] Checking the route for making a practice quiz a quiz
- [x] Checking the route for displaying practice quiz reports that were assigned in a lesson
- [x] Checking the route for displaying practice quiz reports from a quiz (should be the exact same functionality as viewing a quiz report from a regular quiz)
- [x] Checking route for displaying difficult questions for a practice quiz

**It seems that the only one that needs modification will be the route for displaying practice quiz reports when a practice quiz was assigned in a lesson.**

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8521?planning-poker) with ZenHub @jredrejo @marcellamaki @sairina @rtibbles @MisRob @nucleogenesis @jamalex

**Comment by rtibbles** [comment]
Fixed in #8521
