### ISSUE TITLE
missing content is not gracefully handled

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#853]
migrated from trello tasks:
* https://trello.com/c/hBQu1UzZ/567-import-export-missing-content-is-not-gracefully-handled
* https://trello.com/c/3YGyf0v0/569-learn-app-missing-content-is-not-gracefully-handled

When content is referenced by a DB but missing the content folder, this is handled poorly in during import/export, when viewing in the Learn app, and potentially other situations. We should ensure:

* the server has proper checks and error handling to deal with content referenced by the DB but not available on disk
* the client has proper checks and error handling to show the user an indication that content is missing

Shown below: an example of errors while importing a set of channels where 3 large videos were deleted from the content:

![image](https://cloud.githubusercontent.com/assets/2367265/22432159/d33abbf8-e6c8-11e6-9bc3-7dfbbd8cb8f6.png)

**Comment by rtibbles** [comment]
This is fixed by the annotation that happens in #1947

**Comment by rtibbles** [comment]
Fixed in #1947
