### ISSUE TITLE
Coach view: naming - change current instances of "channel quiz" to "practice quiz"

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8530]
## Observed behavior
Currently in the codebase, we use "channel quiz" to describe the functionality we want for "independent practice quiz." We want to make sure we are using the same name to refer to the functionality we want, so we need to update all mentions of a "channel quiz" into "practice quiz" or "independent practice quiz."

Additionally, we will need to make sure the report for practice quizzes for the coach is now using the newly created shared `ReportsPracticeQuizLearnersPage` component.

Notes: 
1. strings that include "channel quiz" do NOT need to be edited, as that is covered by this pull request: #8529 
2. see PR #8212 to see what needs to be changed.

## Expected behavior
All instances in the codebase of "channel quiz" are changed to "practice quiz."

## User-facing consequences
Consequences are for ease of maintenance and upkeep of the codebase by devs.

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8530?planning-poker) with ZenHub @jredrejo @marcellamaki @sairina @rtibbles @MisRob @nucleogenesis @jamalex
