### ISSUE TITLE
Incorrect frontend state management for collection-based content import flows

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#8536]
## Observed behavior

Two related issues when importing content through Kolibri Studio Collection tokens:
1. When you add a collection token through "IMPORT WITH TOKEN", it filters the list down to just the channels from that collection. But if you then toggle the view with "Select entire channels instead", the token seems to be getting cleared and it shows the full list of channels again.
2. When you're viewing the "entire channels" import interface, and select some channels, and then add a collection token, it filters the list down to the collection channels, but still thinks the other channels are selected, and includes them in what's going to be imported (and they can't be unselected):

![image](https://user-images.githubusercontent.com/618416/138760885-087353ad-adfa-407c-a95f-888d73718944.png)

(note the "117 channels selected" -- this blocks me from importing, too, as I don't have space for that)

## Expected behavior

1. Switching views should maintain the current token context.
2. Putting in a token should clear the currently channel selections.

## Context

Chrome in latest 0.15.x.

**Comment by rtibbles** [comment]
Fixed in #9729
