### ISSUE TITLE
Learner view: create Gherkin story for practice quizzes to be accessible from completion modal

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8539]
## Observed behavior
We have to create the Gherkin story for the workflow for when a learner finds a quiz from the completion modal.

## Expected behavior

- The[ FIgma design for this is here](https://www.figma.com/file/TfaSTT9gs6fPKhGdNUjffU/Channel-quizzes?node-id=1315%3A12505)
- The user story for this is: As a learner, I want to be able to access an independent practice quiz from the completion modal.

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8539?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles
