### ISSUE TITLE
Learner view new component: `<PracticeQuizTimer>`

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8540]
### Summary
A new timer component will be added on top of the answer log component in independent practice quizzes.

**Why?** Practice quizzes are for learners to practice with content in a "test-like" condition with regards to time, so this component will provide much-needed functionality for the independent practice quiz feature in our past papers project.

#### Background (optional information)
Currently, when a learner takes a quiz that was assigned by their coach, there are two main things to be aware of (on the UI level): they can only take it once, and the learner does not see a timer. If an independent practice quiz is assigned as a regular quiz, it will follow this same flow.

When a learner takes an independent practice quiz that was found in a channel or assigned in a _lesson_ by their coach, however, they can take it multiple times and, and there is a timer.

|Frame|Explanation|
|--|--|
|![Screen Shot 2021-10-25 at 11 25 19 PM](https://user-images.githubusercontent.com/13563002/138820445-d2fe630c-94c3-4717-9924-d0933e95dc34.png)|The timer is on the top left portion of the `PracticeQuizRenderer` Details for its functionality are below|
_
### Notes and changes to current designs:
- [Figma for the practice quiz timer](https://www.figma.com/file/TfaSTT9gs6fPKhGdNUjffU/Channel-quizzes?node-id=999%3A7166)
- All strings required should already be in `commonCoreStrings`, `commonCoachStrings`, or `commonLearnStrings`
- `<PracticeQuizTimer>` should live in the `<PracticeQuizRenderer>`
- Quiz duration (a.k.a. "Suggested time") is optional and is hidden if not provided. This information is from metadata that comes in from Studio
- Timer starts when learner enters the quiz page
- Timer pauses when the learner leaves the quiz or browser tab (please note that this may not be testable for this component, but that it is something to be mindful of when planning the component)
   - Storybook could be used to prepare a PR with styles and a props driven timer component and reference it as part of this issue
- Time spent will be shown in quiz reports
- Learner’s timer will increment by minutes, not seconds
- Time spent will be used in other components, like the `<ReportsPracticeQuizLearnerPage>`

### Criteria for success:
**Please copy these into your PR for "Steps for Testing"!**

_This issue is done when the checkboxes below work_

- [ ] Quiz duration (a.k.a. "Suggested time") is optional and is hidden if not provided.
- [ ] Timer starts when learner enters the quiz page
- [ ] Time spent is shown in quiz reports
- [ ] Learner’s timer increments by minutes, not seconds
- [ ] "Time spent" is saved for use in other components, like the `<ReportsPracticeQuizLearnerPage>`

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8540?planning-poker) with ZenHub @jamalex @jredrejo @marcellamaki @MisRob @nucleogenesis @rtibbles @sairina

**Comment by rtibbles** [comment]
Noting that three of the action items should be handled outside the scope of this component:

> Timer starts when learner enters the quiz page
> Time spent is shown in quiz reports
> "Time spent" is saved for use in other components, like the <ReportsPracticeQuizLearnerPage>

These three should all be handled by using the `startTrackingProgress` action and `stopTrackingProgress` action from the core actions. https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/state/modules/core/actions.js#L563

**Comment by rtibbles** [comment]
Fixed in #8645
