### ISSUE TITLE
Add Storybook to Kolibri dev environment

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8542]
## Observed behavior
Currently in our dev environment, creating small, props-based components can be challenging, as it requires a view in order to be tested and created. We would like to introduce Storybook to help make the process of developing new components easier.

## Expected behavior
We would like Storybook to be accessible in the dev environment for Kolibri.

## User-facing consequences
This is a dev-facing update

- [ ] Local environment to develop components in isolation
- [ ] Integrating webpack configuration into storybook configuration
- [ ] Documentation to describe how to use for local development

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8542?planning-poker) with ZenHub @jamalex @jredrejo @marcellamaki @MisRob @nucleogenesis @rtibbles @sairina

**Comment by rtibbles** [comment]
Closing as wontfix - we can continue to look at ways to enable similar developer experiences.
