### ISSUE TITLE
Provide API for practice quiz report

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#8543]
Due to the updates in the examlogging API, we will need new functionality to take advantage of the exam attempts to return the following data for use in the components below:

### Component: `PracticeQuizReport`
**Summary information in header:**
- Status (in progress or completed, though, tbh, it would never _not_ be completed, right?)
- Best score out of all attempts
- For the best attempt (the one with the highest score), how many answers were answered correctly
- For the best attempt (the one with the highest score), what was the time?

**Information in the main content area (per attempt from the dropdown - the 5 most recent attempts are shown in the dropdown):**
- Score for that attempt
- Total questions answered correctly
- Total questions answered correctly from previous attempt
- Individual question answered this attempt and the previous attempt
- Time spent for that attempt
- Time spent for the previous attempt
- Last attempted

See Figma below for details.
![Screen Shot 2021-10-28 at 9 53 29 PM](https://user-images.githubusercontent.com/13563002/139377905-a7a113f4-9f7e-45f1-b317-c085f06d5fc0.png)

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8543?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles

**Comment by rtibbles** [comment]
Fixed in #8740
