### ISSUE TITLE
login is broken in IE10

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#855]
migrated from https://trello.com/c/iMtVyXKv/667-broken-in-ie-10-can-t-log-in

![image](https://cloud.githubusercontent.com/assets/2367265/22433471/50fafbe4-e6cd-11e6-95a3-41bb55cedfdb.png)

**Comment by 66eli77** [comment]
the login in latest develop branch works on IE10 now
![screen shot 2017-02-14 at 1 42 59 pm](https://cloud.githubusercontent.com/assets/5577205/22950784/a488e2fe-f2bb-11e6-834c-c5d22b78c6fd.png)

**Comment by indirectlylit** [comment]
nice
