### ISSUE TITLE
Update API for difficult questions in practice quizzes

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8554]
## Observed behavior
Currently, to access a difficult questions report, there are only two options for viewsets - one for an exercise and one for a quiz. However, for practice quizzes, we need some new functionality that is not present in either viewset.

|Frame|Notes|
|--|--|
|![Screen Shot 2021-10-28 at 9 29 13 PM](https://user-images.githubusercontent.com/13563002/139375806-e9814259-7fea-4650-b4f6-4733bb6723d4.png)|the practice quiz difficult questions report|
|![Screen Shot 2021-10-28 at 9 32 52 PM](https://user-images.githubusercontent.com/13563002/139376120-33d376da-c9ba-41a2-8046-afb07d01a3d3.png)|the possible responses that show up as a result of comparing the question with the learner's previous attempt|

## Expected behavior
We need additional functionality in our viewsets to address the ability to add:
- [x] restrict the returned attempts to only attempts for the most recently completed try for a user
- [x] comparatively, how the learner did on the question this time compared to their previous attempt - this could either be achieved by annotation on the attempt, or by fetching the other attemptlog from the penultimate attempt

## User-facing consequences
Without this, coaches will not be able to utilize the full functionality and purpose for having a student take a practice quiz several times.

## Steps to reproduce
1. Sign in as a coach
2. Click on the reports tab
3. Click on the lessons subtab. It should open lesson list page
4. Making sure you are in the report subtab here, click on the title for a resource that is an independent practice quiz
5. Click on the difficult questions subtab
6. Click on the question - this should take you to the difficult question report view.

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8554?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles

**Comment by bjester** [comment]
Intersects a bit with API for reporting on practice quizzes which also has question diff

**Comment by rtibbles** [comment]
Both requirements here were fulfilled by a combination of #8740 and #8645
