### ISSUE TITLE
Learner-only setup wizard broken at importing a user

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#8561]
## Observed behavior

When importing a single user while setting up a device as a learner-only device, the setup wizard appears to get stuck at the task processing screen even though the task response is completed. No other errors or API requests are observed after task endpoints responds with completion

![Screenshot from 2021-10-29 11-11-17](https://user-images.githubusercontent.com/819838/139482770-cddd34cc-fb95-4e62-b263-41e509e42a50.png)

## Errors and logs

```
Request URL: http://localhost:8080/setup/api/soudtasks/
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin

[{"status":"COMPLETED","exception":"None","traceback":"None","percentage":0,"id":"0","cancellable":false,"clearable":true}]
```

## Expected behavior

Upon completion it should allow the user to import more users or complete setup.

## Steps to reproduce

Set up a learner-only device by syncing a single user from another 0.15 instance (like VPN server) without the need for a password

**Comment by pcenov** [comment]
This one is reported here as well: https://github.com/learningequality/kolibri/issues/8489
