### ISSUE TITLE
When running the Python devserver, watch the plugins.json to autorestart when plugins are updated

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8603]
## Observed behavior
Currently the Python devserver watches source files to autorestart - if we also watched plugins.json, we could autorestart when enabling or disabling plugins during development

**Comment by abhimnc** [comment]
I like to contribute to this issue. I already got one pull request merged #8720 . I have some experience with python and django. Can you clarify more about it ?

**Comment by rtibbles** [comment]
Yes, please do take this on!

At the moment, when running the development server, we use this magicbus plugin: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/utils/server.py#L657 to autoreload the server when any imported Python source files have changed.

In addition, it would be useful to autoreload when the `options.ini` and `plugins.json` files in the `KOLIBRI_HOME` (defined here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/utils/conf.py#L31) change too.

The `AutoReloader` class has a `files` attribute which is a set, you should be able to add new files to this after the object is initialized in order to achieve this (see the magicbus source here: https://github.com/cherrypy/magicbus/blob/main/magicbus/plugins/tasks.py#L184).

**Comment by abhimnc** [comment]
@rtibbles  created pull request #8782  . Kindly review.

**Comment by rtibbles** [comment]
Fixed in #8782
