### ISSUE TITLE
incorrect available space reported by drive enumeration

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#862]
(Python 2.7, OSX)

Reported my hard drive's free space as 30984954183680 bytes (28.18 TB). Nice if true, but unfortunately not.

Likely relates to this function in `posix.py`:

```python
def _get_drive_usage(path):
    """
    Use Python libraries to get drive space/usage statistics. Prior to v3.3, use `os.statvfs`;
    on v3.3+, use the more accurate `shutil.disk_usage`.
    """
    if sys.version_info >= (3, 3):
        usage = shutil.disk_usage(path)
        return {
            "total": usage.total,
            "used": usage.used,
            "free": usage.free,
        }
    else:
        # with os.statvfs, we need to multiple block sizes by block counts to get bytes
        stats = os.statvfs(path)
        total = stats.f_bsize * stats.f_blocks
        free = stats.f_bsize * stats.f_bavail
        return {
            "total": total,
            "free": free,
            "used": total - free,
        }
```

**Comment by 66eli77** [comment]
Try to reproduce the issue, but it doesn't show the space of my machine, instead it said `not writable`, is this the correct behavior?
![screen shot 2017-02-14 at 2 06 19 pm](https://cloud.githubusercontent.com/assets/5577205/22951682/eccd2ab8-f2be-11e6-977e-df504e8dde23.png)

**Comment by 66eli77** [comment]
ok, confirm the issue, I sticked in a 32G flash drive but see it display 238G available.
