### ISSUE TITLE
Accessibility follow up issues

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8620]
- [x] improve tab focus on dropdowns
 <img width="344" alt="Screen Shot 2021-11-05 at 4 50 20 PM" src="https://user-images.githubusercontent.com/17235236/140576845-8f2c5ff0-149f-4469-9e42-e5c0fdebe0ed.png">

- [x] fix card focus bug on hybrid learning content cards on lessons page, library page (channel cards working)
- [ ] Mac App: there is no way to use a keyboard to tab to "check" my answers in a quiz or go to the "next" button

**Comment by radinamatic** [comment]
@marcellamaki 
> Mac App: there is no way to use a keyboard to tab to "check" my answers in a quiz or go to the "next" button

No idea why on Earth this is the default setting, but check if this helps:
https://www.a11yproject.com/posts/2017-12-29-macos-browser-keyboard-navigation/

**Comment by marcellamaki** [comment]
Breaking out the Mac app issue to address separately in #8752 8752, will close this for the other two tasks resolved in #8648
