### ISSUE TITLE
Use negative mastery_level for independent practice quizzes

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8622]
## Observed behavior
Currently the progress tracking endpoint uses negative mastery_levels for MasteryLogs for coach assigned quizzes (ones encoded with Exam models in the database).

We had originally devised this strategy in order to prevent these MasteryLogs syncing to older Kolibri versions and causing breakage.

However, in the case of independent practice quizzes, the `content_id` that identifies the practice quiz to the ContentSummaryLog to which the MasteryLogs are attached will no longer be universally unique, as they could be shared across an independent practice quiz and an exercise in this scenario:

If an exercise is copied in Studio, and then converted into an independent practice quiz, the exercise and the independent practice quiz will then share a content_id, as content_ids are preserved by duplication operations.

If both of these are then imported into a Kolibri instance, the same MasteryLog will be used to track the first try at an exercise as the first try at the practice quiz (as they will both use a mastery_level of 1, and the UUID of a MasteryLog is determined by the mastery_level and the id of its associated ContentSummaryLog - the id of a ContentSummaryLog is determined by the user id and the content_id).

There are two problems here:
1. The MasteryLogs will collide.
2. The ContentSummaryLogs will collide, so setting progress on an exercise will set the progress for a Practice Quiz and vice versa.

## Expected behavior
Interaction with a Practice Quiz should have no effect on the logged data for an exercise and vice versa.

A simple change would be to use negative mastery_levels for independent practice quizzes - this would have a slightly ameliorating effect of not letting the MasteryLogs collide, but the progress on ContentSummaryLog would still be an issue.

The only way to solve the logged progress issue would be either:
* Change how we calculate the uniqueness of ContentSummaryLogs to add contextual information, to allow separate progress to be tracked for different contexts. This is a solution that might be useful for longer term consideration as it would have benefits and fit with reported user expectations about progress. However, it would be technically difficult to implement.
* A shorter term change would be how we calculate progress (basically providing a read time shim of the above, to allow us to calculate a different progress for an exercise and an independent practice quiz that share a content_id) - this has the distinct disadvantage of making our DB reads significantly more complex for what have hitherto been fairly simple queries.

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8622?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles

**Comment by rtibbles** [comment]
We should also update mastery log filtering in the progress tracking endpoint to only look for negative mastery_level mastery logs when accessing a practice quiz.

**Comment by rtibbles** [comment]
Fixed in #8645 - will do further follow up for the longer term resolution.
