### ISSUE TITLE
unhandled client-side router error in Learn when no resources are loaded

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8625]
## Observed behavior

When viewing `/en/learn/` when there are no resources loaded, the router throws an unhandled error.

This might be because `next` is called multiple times. [According to the docs](https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards):

> Make sure that the `next` function is called exactly once in any given pass through the navigation guard. It can appear more than once, but only if the logical paths have no overlap, otherwise the hook will never be resolved or produce errors

## Errors and logs

```
Uncaught (in promise) Error: Navigation cancelled from "/" to "/home" with a new navigation.
```

## Expected behavior

There should be no unhandled errors.

One possible fix: rather than redirecting to a page at `/en/learn/#/resources-unavailable`, instead the 'unavailable' message should be shown at `/en/learn/` without redirecting. This has the added benefit of allowing a 'refresh' to show new content when it becomes available.

## User-facing consequences

Probably minimal.

* Possibility of broken behavior due to unhandled exception
* 'refresh' might not behave as expected

## Steps to reproduce

* start a server with no content on it
* navigate to `/learn/`

## Context

latest 0.15

**Comment by pcenov** [comment]
@radinamatic this one is not valid in 0.16.0b10 as the we go directly to /learn/#library there.

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
