### ISSUE TITLE
'view learners' button in Coach  has incorrect styling

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8629]
## Observed behavior

The 'view learners' button is styled as a raised secondary button:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/2367265/140665374-4f98571f-a758-4819-a2dc-521e1a366354.png">

## Expected behavior

Button should probable be a 'basic link' and inline with number, not on next line

## User-facing consequences

* button has more prominence on the page than appropriate
* too much space is taken up for functionality

## Steps to reproduce

view a class home page in Coach

## Context

0.15.0-beta1

**Comment by sharifmaryam** [comment]
Hi, I would like to contribute but I am unsure on how to reproduce this.

**Comment by abhimnc** [comment]
hi @indirectlylit , first time user, like to contribute. I am not able to get what you want to convey. Here is screenshot I am getting. What changes do you want to make?
![image](https://user-images.githubusercontent.com/10187395/141995858-dfb5b57e-5f68-4d27-b333-18c927b4ec8c.png)

**Comment by indirectlylit** [comment]
Hello, thanks for offering to contribute!

The design system defines terminology related to button styling that's used in the description:

https://design-system.learningequality.org/buttons/#visualstyles

Take a look at that and let us know if you still have questions

**Comment by abhimnc** [comment]
is this change you want to make? (Just want to confirm I am going in right direction.) 
![image](https://user-images.githubusercontent.com/10187395/142040805-eefa683c-9a16-4f9b-8188-ba7a5f32797f.png)

what do you mean by "inline with number, not on next line"?

**Comment by indirectlylit** [comment]
Yes, that's right.

> what do you mean by "inline with number, not on next line"?

Something like this:

> ![image](https://user-images.githubusercontent.com/2367265/142044911-fadac734-f423-4a54-9976-094549797c38.png)

Would you mind also double-checking that if we have a 'View coaches' button we apply the same styling? I don't know offhand if we have that implemented.

thank you!

**Comment by abhimnc** [comment]
Thanks for clarification.
Finally I got this. Here is the screenshot.
![image](https://user-images.githubusercontent.com/10187395/142147185-a0ae30f1-6f7e-406c-8545-5105712cdd42.png)

I checked 'View coaches' button but I haven't found it. Would you like to create one? I would happy to work on it also.
Also, should I create pull request for the issue I am working on currently.

**Comment by abhimnc** [comment]
hi @indirectlylit . i have created a pull request.Let me know the feedback.
it is #8720
