### ISSUE TITLE
issues with library top-nav

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8630]
## Observed behavior

The top-nav of the library is not styled consistently with existing analogous navigation in Coach. In particular:

* purple bottom-bar styling has rounded radius
* 'UPPER CASE' vs 'Sentence case'
* non-enabled text color 
* hover states
* spacing

| coach | learn |
|--|--|
| ![2021-11-07 18 16 10](https://user-images.githubusercontent.com/2367265/140665711-2163a204-bfa3-4aaa-bbd6-7f69460b83f6.gif) | ![2021-11-07 18 18 40](https://user-images.githubusercontent.com/2367265/140665709-8f2354f7-0634-400c-903a-0eba20b4e823.gif) |

A few more observed issues:

| issue | screenshot |
|--|--|
| nav overlapping with other content | ![2021-11-07 18 24 28](https://user-images.githubusercontent.com/2367265/140665880-6ca4abfc-cda9-4d67-ac12-d394e7849516.gif) |
| shifting hover state  | ![2021-11-07 18 25 10](https://user-images.githubusercontent.com/2367265/140665906-be5a37dd-3e95-4039-87d0-6acfe0b41906.gif) |
| missing header and description on smaller screens | ![2021-11-07 18 28 36](https://user-images.githubusercontent.com/2367265/140665948-a3899ab2-d94e-4b28-9ced-5144ebb76340.gif) |
| icon can overlap tabs (note: in some languages text could be much longer) | ![2021-11-07 18 34 18](https://user-images.githubusercontent.com/2367265/140666104-2d721e1d-6230-4306-b938-ce0ed8c113bd.gif) |

## Expected behavior

* consistent styling with coach tabs
* grid-based layout to prevent broken layouts
* responsively handle both small window sizes and long label text lengths
* Important information such as the main header and description should not completely disappear because window got smaller

## User-facing consequences

* Users may struggle to navigate properly on small windows
* Inconsistent styling with other parts of app
* Users of smaller screens lack critical information 

## Steps to reproduce

* Compare to Coach
* Try with longer label text 
* Try with smaller window sizes

## Context

0.15.0-beta1

**Comment by marcellamaki** [comment]
@jtamiace -- I will likely start working on this tomorrow, but just want to get a 👍 / 👎 on the items that Devon notes so I know which feedback I should move forward with. If you have a chance today to leave some comments, that would be really helpful! Thanks!

**Comment by indirectlylit** [comment]
let me know if you'd like me to break any items out into independent issues so they can be deprioritized

**Comment by jtamiace** [comment]
Everything is a 👍🏼 except

> missing header and description on smaller screens

This was intentional. I was hoping that the breadcrumb + thumb would be enough to avoid duplicating the current folder title and take up a lot of screen space with a large header.

**Comment by indirectlylit** [comment]
if the breadcrumb alignment issue turns out to be KDS-specific, recommend opening a separate issue there

**Comment by marcellamaki** [comment]
KDS issue for breadcrumb alignment here: https://github.com/learningequality/kolibri-design-system/issues/284

**Comment by indirectlylit** [comment]
> KDS issue for breadcrumb alignment here: learningequality/kolibri-design-system#284

removed from issue description
