### ISSUE TITLE
Do not allow users to navigate to channel quiz selection page when there are none on their device 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8632]
<img width="1421" alt="Screen Shot 2021-11-04 at 8 09 55 PM" src="https://user-images.githubusercontent.com/17235236/140776228-8d071b23-6a14-45ec-a16a-6bcf8b8daa54.png">

This screen should not appear, so need to conditionalize the option to "Select channel quiz" from dropdown

**Comment by bjester** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Kolibri-Ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/8632?planning-poker) with ZenHub @marcellamaki @sairina @jredrejo @rtibbles

**Comment by bjester** [comment]
We should hide the dropdown option if there are no channel quizzes available

**Comment by bjester** [comment]
Query for detecting availability of practice quizzes could be complicated and expensive

**Comment by rtibbles** [comment]
Fixed in #8684
