### ISSUE TITLE
Widen the language modal to avoid truncation

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8636]
## Observed behavior
The new `Portuguese (Mozambique)` locale name gets truncated in the **Change language** modal, we should widen it to avoid truncation.

![2021-11-08_23-10-54](https://user-images.githubusercontent.com/1457929/140828293-e80c7f6a-8b6c-4b32-b453-c6560c33acea.png)

## Errors and logs
…

## Expected behavior
Locale names not truncated in the **Change language** modal.

## User-facing consequences
…

## Steps to reproduce
…

## Context
 * Kolibri version: 0.15
 * Operating system
 * Browser

**Comment by indirectlylit** [comment]
Noting that this will require an update to KDS because the current `KModal` has a limited set of pre-defined items

**Comment by radinamatic** [comment]
Should I open a corresponding issue on KDS repo?

**Comment by indirectlylit** [comment]
that's okay – I can do that
