### ISSUE TITLE
Order resume content node requests by last interaction

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8649]
## Observed behavior
The resume fetches for contentnodes are not ordered by the interaction.

## Expected behavior
The most recently interacted content node should be returned first!

**Comment by qrossCS** [comment]
I would like to contribute! Do you mind pointing me in a good starting direction?

**Comment by abhimnc** [comment]
@rtibbles please assign me this issue. I like to contribute. I already got two pull request merged #8782 and #8720.

**Comment by rtibbles** [comment]
Fixed in #9666
