### ISSUE TITLE
Visual focus for content cards missing on Chrome

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#866]
## Summary

Outline style for content cards in focus is lost in Chrome and not exactly "fit" in Firefox. So cards are technically accessible by keyboard, only the sighted users do not know that since they cannot see which one is in focus.

## System information

 - Version: develop
 - Operating system: Ubuntu 16.10
 - Browser: Chrome 56 / FF 51

#### Chrome

![dividing fractions word problems - khan academy en - kolibri - google chrome_010](https://cloud.githubusercontent.com/assets/1457929/22669738/4fb90056-ecc6-11e6-8d0b-b6ef4593fcf9.png)

#### Firefox

![dividing fractions word problems - khan academy en - kolibri - mozilla firefox_011](https://cloud.githubusercontent.com/assets/1457929/22670060/cdd6e2b8-ecc7-11e6-8dfc-903cf2b4f3f5.png)

**Comment by rtibbles** [comment]
Fixed in #1133
