### ISSUE TITLE
text does not wrap in cards

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8667]
## Observed behavior

Text in content cards is not wrapping. For example:

![image](https://user-images.githubusercontent.com/2367265/141382080-c9b6d0da-4e86-424a-b3d1-580f9b56f075.png)

## Expected behavior

Text should wrap and fill all available vertical space and only truncate at the end if there still isn't room.

## User-facing consequences

Cannot read titles even when space is available

## Steps to reproduce

Browse library content

## Context

0.15.0-beta1

**Comment by marcellamaki** [comment]
This is addressed (to wrap up to 5 lines of text) in #8637

**Comment by indirectlylit** [comment]
hm I checked that branch and I'm still seeing this behavior

**Comment by marcellamaki** [comment]
Thanks -- I'll double check it!!

**Comment by MisRob** [comment]
Tested on the latest 0.15.0 (`Kolibri 0.15.0b2.dev0+git.112.gb0eba58b`) and it's looking good:

| Firefox | Chrome | IE 11 |
| --------- | ----------- | ------ |
| ![firefox](https://user-images.githubusercontent.com/13509191/142827527-2bba2a1a-ed7e-4d7f-b4bd-08f7e26fc7ec.png) | ![chrome](https://user-images.githubusercontent.com/13509191/142827519-b978f8bb-90c1-4dbf-8f76-069333b0e0eb.png) | ![ie11](https://user-images.githubusercontent.com/13509191/142827529-61800014-2e47-4693-b0f4-1bc1f06cf3ad.png) |

**Comment by indirectlylit** [comment]
thank you!

**Comment by MisRob** [comment]
Reopening since under another circumstance, this is still indeed a problem, see https://github.com/learningequality/kolibri/pull/8766

**Comment by MisRob** [comment]
Might be some kind of layout problem related to whether and how the progress bar is displayed.
