### ISSUE TITLE
search filter chips are too closely spaced

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8668]
## Observed behavior

The chips are very cramped with each other and their surrounding elements:

![image](https://user-images.githubusercontent.com/2367265/141382515-2daff77d-5642-4d5a-8004-4b987a14ce1a.png)

## Expected behavior

The [design system specifies](https://design-system.learningequality.org/layout/#spacing) an 8px baseline grid

## User-facing consequences

Search interface becomes slightly harder to read and visually inconsistent

## Context

0.15.0 beta1

**Comment by sharifmaryam** [comment]
I would like to contribute but I am unsure where these chips are in the codebase.

**Comment by indirectlylit** [comment]
One way to find code is to search the codebase for user-facing strings. Here for example if you search for `Clear all`, case-sensitive, in *.vue files you'll find:

* https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/LibraryPage.vue
* https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/SearchChips.vue

**Comment by abhimnc** [comment]
If no one is working, can I take this issue ? I already got one pull request merged in #8720 .

**Comment by sharifmaryam** [comment]
I am working on this ticket.

**Comment by sharifmaryam** [comment]
> * https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/SearchChips.vue

I think I understand how to implement a solution but I am having trouble recreating this page locally so I can test to see if the change works. Do you have any suggestions on how to go about that?

**Comment by indirectlylit** [comment]
@sharifmaryam see https://kolibri-dev.readthedocs.io/en/develop/getting_started.html for instructions on setting up your development environment

**Comment by rtibbles** [comment]
Once you have got it set up, you would need to import some content into the device locally (using the Device tab), and then go to `Learn` --> `Library` and use the search functionality in the side panel. Once you have started filtering, it should start to display these search chips.
