### ISSUE TITLE
view-as-grid and -as-list buttons do not convey currently active state

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8669]
## Observed behavior

Both buttons are enabled, regardless of which display mode is currently active, resulting in one button doing nothing:

![2021-11-11 18 23 36](https://user-images.githubusercontent.com/2367265/141383145-04fb18d4-2cf2-4aae-a42e-b2f6d56b539e.gif)

## Expected behavior

The button corresponding to the currently active state should be disabled

## User-facing consequences

The UI is harder to learn and understand because it doesn't convey the "toggle" action visually.

## Context

0.15.0-beta1

**Comment by akash5100** [comment]
I would like to contribute

**Comment by indirectlylit** [comment]
Thanks @akash5100 – these buttons are here:

https://github.com/learningequality/kolibri/blob/d9b4864a8e93205923c388b4387efc539ae82ec1/kolibri/plugins/learn/assets/src/views/LibraryPage.vue#L26-L39

**Comment by akash5100** [comment]
Thank you @indirectlylit , I will open a PR give me sometime.

**Comment by akash5100** [comment]
@indirectlylit I run `yarn run devserver` and tried to look issue before solving and I found this

![Screenshot from 2021-11-13 11-01-57](https://user-images.githubusercontent.com/53405133/141607060-471f3a92-cb03-4a9d-824e-da0945e382cb.png)

![Screenshot from 2021-11-13 11-02-10](https://user-images.githubusercontent.com/53405133/141607061-cb4e49e9-27e5-44c5-bf1f-62b90e40660e.png)
 can you help me how to reach this test case, it would be helpful.

**Comment by indirectlylit** [comment]
Sorry, I don't quite understand your question.

To disable the buttons, you can probably do something like


```
:disabled="currentViewStyle !== 'list'"
```

and 

```
:disabled="currentViewStyle !== 'card'"
```

for the list and grid views, respectively.

**Comment by akash5100** [comment]
> Sorry, I don't quite understand your question.
> 
> To disable the buttons, you can probably do something like
> 
> ```
> :disabled="currentViewStyle !== 'list'"
> ```
> 
> and
> 
> ```
> :disabled="currentViewStyle !== 'card'"
> ```
> 
> for the list and grid views, respectively.

No this is not, what I asked, leaving that aside
can you explain, what are `$tr`, `$themeTokens` and `toggleCardView` ?

**Comment by indirectlylit** [comment]
* `$tr` - see https://kolibri-dev.readthedocs.io/en/develop/i18n.html
* `$themeTokens` - see https://design-system.learningequality.org/colors/

`toggleCardView` is defined below in the same file:

https://github.com/learningequality/kolibri/blob/d9b4864a8e93205923c388b4387efc539ae82ec1/kolibri/plugins/learn/assets/src/views/LibraryPage.vue#L350-L352

**Comment by akash5100** [comment]
Thank You for helping me @indirectlylit 

![screenrecording](https://user-images.githubusercontent.com/53405133/141670414-7d378251-8f8b-46ad-8a39-80b79f931e90.gif)
```
 <KIconButton
      icon="menu"
      :ariaLabel="$tr('viewAsList')"
      :color="$themeTokens.text"
      :tooltip="$tr('viewAsList')"
      @click="toggleCardView('list')"
      :disabled="currentViewStyle === 'list' && true"
/>
<KIconButton
      icon="channel"
      :ariaLabel="$tr('viewAsGrid')"
      :color="$themeTokens.text"
      :tooltip="$tr('viewAsGrid')"
      @click="toggleCardView('card')"
      :disabled="currentViewStyle === 'card' && true"
/>
```
does this seem correct?
