### ISSUE TITLE
string is missing for 'all categories' search filter chip

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8670]
## Observed behavior

when selecting 'all categories', the chip does not display correctly:

![image](https://user-images.githubusercontent.com/2367265/141383401-96dd0f65-d50e-4864-9e74-d55f7690f774.png)

## Errors and logs

```
[Vue Intl] Missing message: "CommonCoreStrings.all_categories" for locale: "en"
[Vue Intl] Cannot format message: "CommonCoreStrings.all_categories", using message id as fallback.
```

## Context

0.15.0-beta1

**Comment by rtibbles** [comment]
Needs to be added to the `nonConformingKeys` object here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/mixins/commonCoreStrings.js#L1048

Using the constant here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/constants.js#L56

Possible `NoCategories` needs to be done similarly?

**Comment by rtibbles** [comment]
The string for this only exists in the `EmbeddedSidePanel` component, so it needs to be imported using a crossComponentTranslator.

Special casing for `NoCategories` has already been implemented.
