### ISSUE TITLE
IE11 - Truncated and misaligned resource title

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8678]
## Observed behavior
When viewing a resource in IE11 the title of the resource is truncated and misaligned.

## Expected behavior
The labels should not overlap.

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Click on a resource and observe the title area.

## Additional information
IE11:
![2021-11-12_18-41-17](https://user-images.githubusercontent.com/79847249/141503235-99430be3-7072-4f54-a88e-e5913f4e04b3.png)
Firefox:
![2021-11-12_18-40-54](https://user-images.githubusercontent.com/79847249/141503311-e67fdc2e-3787-42ab-b4cd-950af3cf1b20.png)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: IE11, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Not only IE11, Chrome too... 

![Win7 (0 15b2)  Running  - Oracle VM VirtualBox_006](https://user-images.githubusercontent.com/1457929/141891774-48276d49-a231-4eaa-9d3c-b210a601763c.png)

(Chrome on top, Firefox on bottom, Windows 7)
