### ISSUE TITLE
Learner - Cannot set a password for a learner created without a password

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8687]
## Observed behavior
When I attempt to sign in as a Learner created without a password I cannot set just a password instead I see an option to create a new account. (Note that I'm not able to use the existing username)

## Expected behavior
It should be possible to create a new password as specified in the following feature file: https://github.com/learningequality/kolibri/blob/release-v0.15.x/integration_testing/features/learner/learner-sign-in.feature

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Create a facility with the option for 'Require password for learners' disabled
3. Create a Learner user
4. Enable the 'Require password for learners' option
5. Attempt to sign in with the Learner

## Additional information
![2021-11-15_18-19-51](https://user-images.githubusercontent.com/79847249/141818433-b0e73949-83f5-4d21-997d-b89fda6b173f.png)

![2021-11-15_15-05-41](https://user-images.githubusercontent.com/79847249/141818449-a649348f-d42f-4017-8fa9-7c3f583d9a73.png)

Logs: 
[logs.zip](https://github.com/learningequality/kolibri/files/7540298/logs.zip)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Issue confirmed on Windows 7.

1 | 2
--- | ---
![Win7 (0 15b2)  Running  - Oracle VM VirtualBox_002](https://user-images.githubusercontent.com/1457929/141875827-abf8b948-567a-40e0-baf1-802cb4d9b669.png) | ![Win7 (0 15b2)  Running  - Oracle VM VirtualBox_003](https://user-images.githubusercontent.com/1457929/141875837-d45daf45-11f3-4387-a072-bd8c67b2a933.png)

If I understand correctly this scenario should trigger the [`NewPasswordPage`](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/user_auth/assets/src/views/SignInPage/NewPasswordPage.vue), correct?

**Comment by rtibbles** [comment]
Yes - it seems that there was an error when this was separated out into a separate page. Fixing now.
