### ISSUE TITLE
'incorrect username' reported for 'username not found'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8693]
## Observed behavior

when trying to log in on a server with a username that doesn't exist, kolibri reports "incorrect username":

![image](https://user-images.githubusercontent.com/2367265/141841390-bc4c90c9-0962-4aab-8e98-777732da18ab.png)

## Expected behavior

Kolibri should report "username not found"

## User-facing consequences

Error may be misleading. For example, it could have been that the server URL was wrong but the username was correct.

## Steps to reproduce

* go to https://bck-develop.internal.learningequality.org/en/auth/
* try to log in with a random string as the username

## Context

0.15

**Comment by somesh202** [comment]
Hey @indirectlylit ! Can I work on this issue?

**Comment by indirectlylit** [comment]
Sure! If you do, please target the `develop` branch.
