### ISSUE TITLE
'categories' filter should probably not have the highest prominence for 0.15

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8694]
## Observed behavior

The 'categories' filter has the most prime real estate:

![image](https://user-images.githubusercontent.com/2367265/141842344-5c4e9c22-ce7d-449a-aaa2-018c0e8b577c.png)

However, it is also currently the least useful filter because so little content has been categorized yet.

## Suggested behavior

Recommend moving the categories filter lower and giving more prominence to filters that will work more effectively out-of-the-gate. Then in a subsequent patch release we may choose to raise it higher again when we can tell from our telemetry data that people have generally upgraded their channels.

cc @jtamiace thoughts?

## User-facing consequences

Using the categories filter is currently fairly frustrating when no content has been categorized.

## Context

0.15.0-beta2

**Comment by rtibbles** [comment]
This will not display until there are categories available - this is shown currently only in development mode for developer convenience.
