### ISSUE TITLE
category filters are active even when no resources apply

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8695]
## Observed behavior

Selecting a category takes two clicks and leads to 0 results:

![2021-11-15 14 37 33](https://user-images.githubusercontent.com/2367265/141843349-18f879fd-dc47-469e-a4a3-1402abb95fa8.gif)

## Expected behavior

categories should be hidden or disabled when no content applies

## User-facing consequences

user would need to slowly click through every possible category to see if any have results

## Steps to reproduce

Go to http://localhost:8000/en/learn/#/library and select categories

## Context

0.15.0-beta2

**Comment by rtibbles** [comment]
This is specifically enabled in development mode but does not happen in production.
