### ISSUE TITLE
Home page Learn and 'Library > Recent' are displaying duplicates of the same resources in different languages (KA channels)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8700]
## Observed behavior
When device has, for example, various KA channels available, the homepage and  **Library > Recent** section are displaying the same resource in all the languages, and not just the one the learner has engaged with. 

Learner engaged with videos only on the Kolibri QA channel, but since device has KA EN, KA ES and KA BG channels imported, the same resource in all those languages is pulled in and displayed in the **Recent** section.

Homepage | Library
--- | ---
![Win7 (0 15b2)  Running  - Oracle VM VirtualBox_005](https://user-images.githubusercontent.com/1457929/141891567-0dd607db-cdb0-45c7-91e9-d13a49af78b3.png) | ![Win7 (0 15b2)  Running  - Oracle VM VirtualBox_004](https://user-images.githubusercontent.com/1457929/141890385-712b0a0e-19fc-4edd-ba8f-572a7b926158.png)

## Errors and logs
…

## Expected behavior
**Library > Recent** should display only the specific resource user has engaged with, and not the copies from other channels

## User-facing consequences
User confusion, too many resources in the **Recent** section.

## Steps to reproduce
1. Import the same topic from various KA channels.
2. Engage with one resource that is present on more than one channel.
3. Check the **Library > Recent** section

## Context
 * Kolibri version: 0.15b2
 * Operating system: Windows 7
 * Browser: Firefox

**Comment by rtibbles** [comment]
Note that we can't actually tell which one that user most recently engaged with - so without a radical change to our data structures we cannot fix this as stated.

What we can do is deduplicated these things in the same way that we should be doing for search results as in here (https://github.com/learningequality/kolibri/issues/8498)
