### ISSUE TITLE
Android App - Learn UI responsive design issues

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8722]
## Observed behavior
When I am using the android app in a mobile phone with a smaller screen size I'm observing a number of Learn UI responsive design issues. Note that when the search filters are opened in a smaller mobile device the user has no way of closing the filter view as there's no outside area to tap on.

## Expected behavior
All pages should be optimized for mobile devices.

## Steps to reproduce the issue
1. Install the Android [build](https://buildkite.com/learningequality/kolibri-android-installer/builds/3163) on a mobile device.
2. Interact with the app.

## Screenshots

1 | 2 | 3
--- | --- | ---
![2021-11-17_18-18-23](https://user-images.githubusercontent.com/79847249/142242355-90495776-7dae-401c-b7da-ce491c2070a7.png) | ![2021-11-17_18-20-48](https://user-images.githubusercontent.com/79847249/142242366-cdceebd5-ed98-4e60-aa3b-8fe657f14a60.png) | ![2021-11-17_18-27-18](https://user-images.githubusercontent.com/79847249/142242370-e85c95f7-1e12-4430-a8b9-b5ae7f84ba6d.png)

## Usage Details
 - OS: Android 11
 - Device: Samsung Galaxy Note 10 Lite

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
To recap and add more examples, excluding Perseus issues, tracked in #8714: 

nº | Screenshot | Comment |
--- | --- | ---
1 | ![card-height](https://user-images.githubusercontent.com/1457929/142362585-9e4801a9-a9d7-4178-b425-f7ade4d8a066.png) | Card height misuses space
2 | ![crowded-topbar](https://user-images.githubusercontent.com/1457929/142362677-067221f5-c742-465b-8eac-64488f7703d5.png) | Crowded icons and elements in the topbar
3 | ![search-sidebar-width](https://user-images.githubusercontent.com/1457929/142362914-8121e065-2c6f-473b-b890-632f6b37d703.png) | Width of the *Search* sidebar
4 | ![folders-sidebar-width](https://user-images.githubusercontent.com/1457929/142362879-30369b3f-30d7-4bab-87fa-37604f7888c4.png) | Width of the *Folders* sidebar
5 | ![quiz-report](https://user-images.githubusercontent.com/1457929/142363239-b8176da8-4cb4-4cde-b96e-ad2b431f62d0.png) | Quiz report
6 | ![Selection_107](https://user-images.githubusercontent.com/1457929/142363490-2321f123-c309-433e-9fd4-745f69eec0c2.png) | No breadcrumbs links
7 | ![DevTools - localhost:8080-en-learn---home_001](https://user-images.githubusercontent.com/1457929/142363648-25fd3ffa-ee85-4aab-8697-70a537e8ba83.png) | Completion modal

**Comment by StarTrooper08** [comment]
Is it a Flutter Android App or a normal XML and Java/Kotlin based Android App?

**Comment by rtibbles** [comment]
Neither - it uses [Python For Android](https://python-for-android.readthedocs.io/en/latest/) to run the Kolibri Python server on an Android device and serve up the VueJS interface via a webview.

Most of these responsiveness issues should be extant in a regular web browser context on the same Android device also.

**Comment by rtibbles** [comment]
(noting that @marcellamaki is fixing this issue, so we are not looking for contributions here at this time)
