### ISSUE TITLE
Unstuck bottom bar in the Perseus renderer on small mobile screens

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8727]
## Observed behavior
Bottom bar in the Perseus renderer (where the <kbd>Check</kbd> button is located) is supposed to be sticky, and not scroll up and down with the exercise when the height of the resource is bigger than the available screen space

(disregard the icons of the screencasting apps)

### Android app
https://user-images.githubusercontent.com/1457929/142364399-72aaa4b3-fc1d-4d0f-9c7b-af775a2435c1.mp4

### Browser on Android client
https://user-images.githubusercontent.com/1457929/142364602-a435826a-dc45-4921-947a-c4e4b2980c06.mp4

## Errors and logs
…

## Expected behavior
Bottom bar should stick to the edge and not scroll with the content.

## User-facing consequences
…

## Steps to reproduce
…

## Context
Tell us about your environment, including:
 * Kolibri version: 0.15b2
 * Operating system Android
 * Browser all

**Comment by MisRob** [comment]
@radinamatic:
> I believe the server was running on Windows 7 and I used Firefox on my Android phone (version 9) as a client to access

**Comment by radinamatic** [comment]
I just re-tested the second scenario, and the issue is extant on both Firefox and Chrome browser clients on Android when accessing the server on Windows 7, but it does depend on the exercise resource that you load: if the problem area is large enough, the bottom bar starts in the correct position, but gets pushed down once the problem area gets loaded on top.

You can use the `Recognize fractions` exercise in the **Kolibri QA channel > Exercises > Channel based quizzes** folder to replicate.

**Comment by MisRob** [comment]
Thank you @radinamatic. I was testing it on the `Recognize fractions` exercise. Wondering if the screen resolution may play a role here too. Could you post what was the screen resolution of your test device, please?

**Comment by MisRob** [comment]
I think the exercise was higher than the available screen space since I could scroll but maybe devices I checked so far weren't small enough for this to happen. An approximate number should be sufficient, just to have direction.

**Comment by radinamatic** [comment]
Actually, I had no idea and needed to google that 😛 
https://www.gsmarena.com/motorola_moto_g6-9000.php

**Comment by MisRob** [comment]
Ah, that's perfect :) Thanks for testing it one more time and for all information.

**Comment by MisRob** [comment]
Regarding testing this issue in a **browser on Android client** I've still had no luck with finding a test device where I could reproduce and debug.

For the record, I tested `Kolibri 0.15.0b2.dev0+git.158.g5de9da33` and the bottom bar behaved fine on the following devices:

- my Samsung Galaxy A40, Android 11, both Firefox and Chrome (recording 1)
- BrowserStack Real Devices:
  - Sony Xperia Z5, Android 5.1, Chrome
  - Xiaomi Redmi Note 7, Android 9, Firefox
  - Motorola Moto G7 Play, Android 9, Firefox
  - Motorola Moto G 2nd Gen, Android 5, Chrome (recording 2) - has the smallest screen I've discovered on BrowserStack so far, @radinamatic's testing device looks to be still smaller though
- Chrome Mobile Emulation for a very small screen  (recording 3)

| Samsung Galaxy A40, Android 11, Firefox | Motorola Moto G 2nd Gen, Android 5, Chrome | Chrome Mobile Emulation |
| ------------------------------------------------------- | -------------------------------------------------------------- | ----------------------------------- |
| ![samsung](https://user-images.githubusercontent.com/13509191/143226940-a7e1e188-96f6-42de-80ae-4fb5d664f33f.gif) | ![motorola-moto-g-2nd-gen-android5-chrome](https://user-images.githubusercontent.com/13509191/143226976-6664b316-a376-42f7-8920-b1fb78cdeebe.gif) | ![browser](https://user-images.githubusercontent.com/13509191/143229054-7291ac8a-55fd-479f-a880-47234d11d07b.gif) |

**Comment by MisRob** [comment]
:tada:  @bjester was able to reproduce:

> Looking at the videos, it seems that it's likely caused by x-axis overflow. I was able to reproduce the issue by switching to Spanish which causes the "Get 5 correct", which is lengthier in Spanish, to push the hints anchor off the end of the header and cause viewport panning. The same also happens if you use a hint, and the hint status gets added to the bottom bar causing different overflow issues

> Seems like we need some design for how to handle the hints call-to-action in a responsive manner. There's just not enough space!

**Comment by MisRob** [comment]
Confirming that I am able to reproduce this on my phone after switching to Spanish as @bjester's advised
