### ISSUE TITLE
PDF documents in Kolibri are not 100% viewable due to the "go to full screen" bar.

### ISSUE THREAD

**Issue by SerchMX** [learningequality/kolibri#8745]
## Observed behavior

If you add any channel that uses PDFs, you will see a banner that allows you to 'enter full screen', at the top of the PDF document. This banner will not hide unless you scroll down the PDF document, so the PDF title will remain behind this banner. 

![baktun](https://user-images.githubusercontent.com/9337397/142517808-f6b78264-01a0-4492-b420-52bbc4cb20e9.png)

…

## Expected behavior

Would it be possible to hide the banner if you stop moving the mouse pointer or move the pointer outside of the PDF document, or any other method?

## User-facing consequences

It was reported by a deployment in Yucatán Mexico, although this behavior is agnostic to specific users.

## Steps to reproduce

1. Open Kolibri
2. Add any channel that has a PDF doc
3. You will see an "Enter Full Screen" gray banner at the top of the document, which prevents the PDF to show its title.
If you scroll down the PDF document, the banner dissapears, but if you go to the very top, it will appear again.

## Context

 * Kolibri version: 1.0 from Flathub
 * Operating system: Endless OS 3.9.5
 * Browser: Chromium/Chrome

**Comment by pcenov** [comment]
@radinamatic this one is still valid in 0.15.1

**Comment by rtibbles** [comment]
I think the best solution for this is to just push the PDF rendering area below the toolbar.

**Comment by rtibbles** [comment]
Fixed in #9439
