### ISSUE TITLE
When finishing a resource in a lesson, the completion modal does not move you on to the next item in the lesson

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8749]
## Observed behavior
When finishing a resource in a lesson, the completion modal does not move you on to the next item in the lesson.

First it doesn't render the content, but when I refresh, it does.

## Expected behavior
Should just move the learner on to the next resource in the lesson.

**Comment by rtibbles** [comment]
This seems to have been resolved, never mind!

**Comment by radinamatic** [comment]
Initially thought to be only in the past-papers project, but actually extant in the general 0.15 branch.

Clicking the <kbd>Move on</kbd> button in the lesson completion modal _moves on_ (displays) to the next resource in the same folder as the completed resource, and NOT to the next resource in the lesson as set by the coach.

Moving on to _Intro to addition_ (next in the Kolibri QA channel, after the _Welcome_) | Moving on to _Where the babies come from_ (next in the Kolibri QA channel, after the _Seven rivers..._)
--- | ---
![move-on-skipps-ppp](https://user-images.githubusercontent.com/1457929/142703380-a451109f-fe1d-4093-bf0c-f58393e98e5b.gif) | ![move-on-next in folder](https://user-images.githubusercontent.com/1457929/142703375-e4c53f0e-cdae-4290-9c04-f4d96a3d947b.gif)
