### ISSUE TITLE
Bookmarks - The bookmark icon is displayed for a non signed-in user

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8750]
## Observed behavior
As a user who hasn't signed in I'm still able to see and click the bookmark icon for a resource which results only in an error in the console.

## Expected behavior
Not sure whether this is being tracked somewhere else but my guess would be that the icon should not be displayed in that case.

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2) and setup a facility
2. As a learner who hasn't signed in open a resource and attempt to bookmark it.

## Additional information

![2021-11-19_17-45-10](https://user-images.githubusercontent.com/79847249/142651107-da5cc6a2-79d8-4b90-bf59-0949384d00bf.png)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Tagging it P2 for now, maybe the easiest solution would be to not display the bookmark button.

In case we wanted to implement the workflow to use this as an incentive for the guest to create an account, it would need some UX decisions and maybe additional user strings which cannot be added for now.

**Comment by pranay101** [comment]
I am new to open source and I'd like to contribute to this issue.

**Comment by rtibbles** [comment]
Great, please base your work off the release-v0.15.x branch.

It should just be a matter of conditionalising the display of the bookmark action on the user being logged in. The code for the action is here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/LearningActivityBar.vue#L221

It is worth noting that for ease of testing the above component has been implemented with just props and no reference to vuex state or getters (which you will need to use to determine if the user is logged in). To maintain this, I would recommend adding a new prop to the component that determines whether the bookmark is shown.

Where this component is used you can then set this new prop with reference to the isUserLoggedIn getter (search the code for examples).

**Comment by pranay101** [comment]
Hey there, so I created a new prop isUserLoggedIn. what should be the conditions and how can I check if the user is logged in or not.

**Comment by rtibbles** [comment]
There is a vuex getter defined in the core store called `isUserLoggedIn` too, the LearningActivityBar is used only in this component, which already accesses a getter from the core here: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/LearnImmersiveLayout.vue#L190 you can add the `isUserLoggedIn` getter, which you could then use to pass to the `isUserLoggedIn` prop.

If you want to be specific about the function of passing this boolean to the LearningActivityBar - you could consider naming the prop `showBookmark` or somesuch, as that will better describe to a future developer why this prop is needed.
