### ISSUE TITLE
Mac App Keyboard navigation

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8752]
Mac App: there is no way to use a keyboard to tab to "check" my answers in a quiz or go to the "next" button

Reported by Sairina in 0.15 bug bash. Investigation so far would suggest that this is mac app specific, and this is not a problem on mac in the browser.

**Comment by radinamatic** [comment]
It's not even an issue per-se, more of Apple's 🤦🏽‍♀️ decision NOT to enable the keyboard access to all actionable UI elements on macOS by default, but to force the user to look for the respective setting and enable it manually... 😒

**Comment by marcellamaki** [comment]
Yes -- I saw what you shared in the other issue that this was originally in. So, do you think this is even a "bug" and something we can fix, @radinamatic? I just wasn't sure if there was some extra code or configuration we would need to add proactively for the mac app specifically

**Comment by rtibbles** [comment]
This is a configuration issue on MacOS, and not something we can fix.
