### ISSUE TITLE
Update learning activity label metadata to correctly display reference and duration

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8767]
Now that we have the backend set up, we will need to make some adjustments to duration/reference displays that are used on the Learning Activity Label (which is on some of the cards). 

Specifically my guess is that '`durationEstimate()` in `LearningActivityLabel.vue` in the place that needs to be updated to fix the data mismatch.

**Comment by rtibbles** [comment]
Full spec for how this will be encoded in content node options is here: https://github.com/learningequality/studio/issues/3281
