### ISSUE TITLE
intermittent lint failure

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8772]
## Observed behavior

see https://github.com/learningequality/kolibri/pull/8500#pullrequestreview-813868553

It appears that some invalid code slipped in without triggering a lint failure. At a later point, this caused a lint failure in my personal fork during unrelated work.

## Errors and logs

This block:

https://github.com/learningequality/kolibri/blob/80fe54f6ace6ed3146099984a928c11e58c8bc0a/kolibri/utils/server.py#L925-L929

triggered this linting error in my personal branch:

```
kolibri/utils/server.py:929:40: F812 list comprehension redefines 'output' from line 927
```

## Expected behavior

* The linter should have flagged this in the PR
* ~The code in question should not redefine `output`~ fixed in #8773 

## User-facing consequences

Possible that bugs would slip through

## Steps to reproduce

uncertain

## Context

0.15.0-beta2

**Comment by indirectlylit** [comment]
re-opening to reflect the first part of this issue ('the linter should have flagged this in the PR')

**Comment by rtibbles** [comment]
Oh - it appears the path match check for this is incorrect - `kolibri/**.py` is not the same as `**.py` in terms of expansiveness (as I think we've discussed before).
