### ISSUE TITLE
Unable to load channel based quiz report from Home/Classes tabs on 0.15 (Beta Site)

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#8785]
## Observed behavior
When clicking onto a report for a channel based Quiz, the page is unable to load.
![image](https://user-images.githubusercontent.com/22602993/143913778-525ac5ea-7586-40f5-b28d-e44058f65d66.png)

## Steps to reproduce
Log-into Kolibri as a Learner on the beta site, navigate to Home page and click on the report of a channel based quiz. I navigated to this page while being logged in as 'admin' on the beta site: [](https://kolibri-beta.learningequality.org/en/learn/#/classes/f6e7f562bb0ea654340c726e1f81bbe9/examReport/aa66ddb61689c5ebebd00660ab25e4d2/0/0)

…

## Context

Tell us about your environment, including:
 * Kolibri version 0.15
 * Operating system MacOS on kolibri-beta.learneq.org
 * Browser Chrome

…

**Comment by rtibbles** [comment]
I _think_ this is an artifact of a previously fixed issue to do with migration of JSON fields from ExamAttemptLog to AttemptLog.
