### ISSUE TITLE
'keyboard navigation' mode is being incorrectly enabled in login screen

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8786]
## Observed behavior

Enter a username and press 'enter'. Note that the keyboard focus outline shows up:

| interaction | annotated |
|--|--|
| ![2021-11-29 13 08 57](https://user-images.githubusercontent.com/2367265/143922633-e5d4384e-aace-4aa6-9e44-392850284db3.gif) | ![image](https://user-images.githubusercontent.com/2367265/143922527-e9001c92-2652-4c41-b9c6-94188d367259.png) |

This might be related to one of these changes:

* https://github.com/learningequality/kolibri-design-system/pull/200
* https://github.com/learningequality/kolibri-design-system/pull/227

## Expected behavior

The "input modality" should only be set to "keyboard" if and when the user uses 'tab' to move between UI elements.

## User-facing consequences

* Extra visual noise
* May be indicative of a more general problem with how we track input modality

## Steps to reproduce

Enter username from login screen 

## Context

0.15.0-beta2

**Comment by MisRob** [comment]
Re-opened since this will be fixed after we install the new version of KDS which hasn't happened yet
