### ISSUE TITLE
improvement on channel deletion

### ISSUE THREAD

**Issue by vahidmas** [learningequality/kolibri#8797]
## Observed behavior
As i am trying to delete a (large 50GB+) channel, the screen for deletion seems to idle for a good 8 minutes, and then starts showing progress in the green percentage bar, with the corresponding % being displayed. 

Proposed solution: Create a message such as "Deletion is being prepared" until the actual % bar starts making progress. 

## Expected behavior
Indication of some sort of progress would be great, even if it doesn't count towards the percentage bar. Also, logging (at level INFO) should indicate that the deletion has completed successfully. As it is, the log reads `INFO     Deleting all channel metadata` and never indicates that the process finishes.

## User-facing consequences
It is not helpful to the user to be left wondering whether the deletion has started or is doing anything. 

## Steps to reproduce
Import a large channel, delete it, and tail the log generated by the iceqube/task/job worker.

…

## Context
 * Kolibri version 0.15.0b2
 * Operating system Windows 11
 * Browser Chrome

…

**Comment by radinamatic** [comment]
Targeting to a new version because it requires a new UI string.

**Comment by nucleogenesis** [comment]
I think that this issue has been resolved by https://github.com/learningequality/kolibri/pull/9461 (and maybe others) where the entire deletion workflow was moved to the task workflow, so it is no longer a blocking UI at all cc @rtibbles

**Comment by rtibbles** [comment]
This was always a backend task - so there's no change here. This is just about giving more meaningful status messages while the backend task is in progress.

One thing to note is that I think we have made the very long stage that was not being reported on a bit less long - would still be good to add this messaging though.

**Comment by nucleogenesis** [comment]
That's good to know - I think that guidance on precisely where that messaging should go would be helpful to get this unblocked.

Additionally, does this issue also affect any other tasks? Do we need messages for all tasks, a generic message for all of them or just one for the deletion task?

Once we know where the messages should go and what they should be this should be good to go I think

**Comment by rtibbles** [comment]
I don't think we've had any reports of other tasks where this is an issue - for some tasks (like syncing and facility/single user import) we even have distinct messaging for different stages of the task being in progress, which seems to match up with the desired behaviour here.
