### ISSUE TITLE
card thumbnail area could be shrunk vertically at some screen sizes

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8800]
## Observed behavior

There is extra space above and below the thumbnail at some screen resolutions

<img width="590" alt="image" src="https://user-images.githubusercontent.com/2367265/144529191-c833bbe5-c9b5-44b2-a742-d6e7b0aa92a3.png">

## Expected behavior

The cards could simply become shorter:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/2367265/144529754-2e18adf5-2d3a-4b57-b3e9-041eae1ee93f.png">

## User-facing consequences

More content displayed

## Steps to reproduce

view library at smaller screen sizes

## Context

0.15.0-beta2

**Comment by marcellamaki** [comment]
Fixed in #8945
