### ISSUE TITLE
Facility>Data - No indication that a facility has been registered correctly

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8801]
## Observed behavior
The page is not refreshed after successfully registering a facility to the KDP portal and it seems that nothing has happened. One has to manually refresh the page to see that the facility has been registered successfully.

## Expected behavior
The page should be refreshed to indicate that the registration was successful.

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Go to Facility>Data
3. At 'Sync facility data' click the Register button.
4. Enter a valid project token such as 'pijitgotal' and click Continue
5. Confirm that you want to register the facility and observe that the modal gets closed without any visual indication that something has changed

## Additional information

![2021-12-03_18-19-30](https://user-images.githubusercontent.com/79847249/144637701-8e47ace3-40c8-43c5-ae86-0d0b6cf921f0.png)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
At least a snackbar confirmation should appear at this point... Thoughts, @jtamiace?

At first I thought to slide this to 0.16, but we actually have a string [`Registered to 'Kolibri Data Portal'](https://github.com/learningequality/kolibri/blob/a64471e954eb64344697bb13492c2aaaf19489e2/kolibri/core/assets/src/views/sync/FacilityNameAndSyncStatus.vue#L93) that could fit here without issues.
