### ISSUE TITLE
Labels for radio buttons are truncated

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8808]
## Observed behavior
Labels for radio buttons should wrap and extend to the second line (like labels for checkbox options), and not be truncated.

app | browser
--- | ---
![DevTools - localhost:8080-en-device---settings_003](https://user-images.githubusercontent.com/1457929/144920894-cfe9d809-da55-4502-9db4-25eda2c6bed7.png) | ![Configuración del dispositivo - Kolibri — Mozilla Firefox_001](https://user-images.githubusercontent.com/1457929/144921934-99c2e639-ed6f-47fa-bc77-a08653219ceb.png)

Luckily we don't have radio buttons in the Learn app, so we might fix this in the upcoming patch. cc @marcellamaki @rtibbles 

## Errors and logs
…

## Expected behavior
Labels should be fully visible.

## User-facing consequences
Impossible to understand the options.

## Steps to reproduce
Go to Device > Configuration on a small mobile screen (app), or with responsive view in the browser.

## Context
 * Kolibri version: 0.15
 * Operating system: Android app
 * Browser: all

**Comment by marcellamaki** [comment]
Moved to: https://github.com/learningequality/kolibri-design-system/issues/302 since this is a changed that needs to be discussed and implemented in KDS
