### ISSUE TITLE
Content cards with folders shorter than other content cards

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8809]
## Observed behavior
In the learner's library, content cards with folders are slightly shorter in height than the rest.
|without hover shadow|with hover shadow|
|--|--|
|<img width="674" alt="Screen Shot 2021-12-06 at 1 33 10 PM" src="https://user-images.githubusercontent.com/13563002/144926066-9b3bcfd3-5e58-4cce-a621-2c73b5131e00.png">|<img width="674" alt="Screen Shot 2021-12-06 at 1 29 59 PM" src="https://user-images.githubusercontent.com/13563002/144925828-653c2f38-0d26-4323-a328-00fad2fd54a8.png">|

## Errors and logs
None

## Expected behavior
The cards should be the same height.

## User-facing consequences
Just a bit off.

## Steps to reproduce
1. Log in as a learner
2. Click on "Library" tab
3. On left sidebar, go to Category > "None of the above" to view everything (including folders)
4. See that cards with folders are slightly shorter

## Context
- Kolibri v0.15
- Chrome

**Comment by rtibbles** [comment]
Fixed in #8856
