### ISSUE TITLE
Invalid prop warning in Learner > Library > Category

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8810]
## Observed behavior
When in Learner > Library, and I click on "Categories" in the side panel, there is a warning in the console that pops up for anything that is not "All categories" or "None of the above":
```Invalid prop: type check failed for prop "span". Expected String with value "4", got Number with value 4.``` for 

## Errors and logs
<img width="1508" alt="Screen Shot 2021-12-06 at 12 33 13 PM" src="https://user-images.githubusercontent.com/13563002/144927203-46bd72b4-20f0-4f93-9879-71fb6e93f249.png">

## Expected behavior
No errors would show up in console.

## User-facing consequences
Cluttered console

## Steps to reproduce
1. Sign in as learner
2. Click on Library
3. Open the console in browser
4. Under "Category," click on anything other than "All categories" or "None of the above"

## Context
- Kolibri v0.15.x
- Chrome

**Comment by rtibbles** [comment]
Note that this is likely `:span="4"` being passed instead of `span="4"` to a `KGridItem` component.
