### ISSUE TITLE
Completion modal only shows right half of modal on Android

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8816]
![DevTools - localhost:8080-en-learn---home_001](https://user-images.githubusercontent.com/1457929/142363648-25fd3ffa-ee85-4aab-8697-70a537e8ba83.png)

_Originally posted by @radinamatic in https://github.com/learningequality/kolibri/issues/8722#issuecomment-972576249_

**Comment by radinamatic** [comment]
Seems to be gone with @marcellamaki wind! 👍🏽 


Same Android device, server on Windows 7 as in the original issue:

![DevTools - localhost:8080-es-es-learn---topics-c-d753aaf3ac794cf59b0169df72964dbe?lessonId=b44f7ef78626b7041476861b64f1c7f1 classId=1b21fb43599f223b4885e95b61aa2ef3 last=LESSON_PLAYLIST_001](https://user-images.githubusercontent.com/1457929/145118787-54ea474c-844c-4dbd-b616-90da45627180.png)
