### ISSUE TITLE
'import more' flow is interrupted by channel upgrade

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8826]
## Observed behavior

After clicking 'import more' on a channel, if the channel has updates available, the flow is interrupted:

1. the bottom section showing known resources is completely hidden
2. after upgrading the channel, the user is kicked out of the import flow

## Expected behavior

The user should remain in the 'import more' flow regardless of whether upgrades are available or if they choose to complete an available upgrade

## User-facing consequences

* The user is forced to upgrade even if they don't want to in order to import more
* If the user does want to upgrade, they lose their place in the task and need to start over

## Steps to reproduce

* Import items from a channel
* Upgrade the channel
* Go to 'import more' from the channel

## Context

0.15.0 beta 3

**Comment by rtibbles** [comment]
Fixed in #9252
