### ISSUE TITLE
[Regression] Side panel alignment updates have not be applied in all cases

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8827]
Double check all places where the sidepanel is used: 
- ensure spacing is accurate on large medium and small screens
- ensure alignment is correct for both LTR and RTL languages
- ensure "X" is visible in all cases 
- focus trap is working in all cases 

https://www.notion.so/learningequality/REGRESSION-Learn-Viewing-Content-Workflow-29-a828497ca3354a3aa497f2b6aed8a5af
https://www.notion.so/learningequality/REGRESSION-Learn-Content-renderer-search-browse-29-Broken-fba0b651cd1c4260a1d3dea6d20310eb
https://www.notion.so/learningequality/REGRESSION-29-Learn-Content-Renderer-8e336fabdc564369be509254c9005e2e
https://www.notion.so/learningequality/FEATURE-BUG-folder-resources-side-bar-issues-a501b5d425714e548da183719bbb1c51

**Comment by radinamatic** [comment]
cc @rtibbles and @sairina as #8874 is extant on 0.16 too, and should be fixed for the practice quiz release.

Should I reopen #8874 and add the 0.16 milestone?


![DevTools - localhost:8080-en-learn---topics-c-a1b7e748daa34232b12022017fbb9b59?lessonId=4f1a41ccfc7fb400eb3b0e86cab29c5c classId=c1863477e405753f9e208c8ddd7f3644 last=LESSON_PLAYLIST_001](https://user-images.githubusercontent.com/1457929/145254288-c7cc7934-4489-4c44-b6f9-9173f226de2b.png)

**Comment by rtibbles** [comment]
No, I think we can assume any bugs extant on 0.15 are extant on 0.16 as well, no need to double track.
