### ISSUE TITLE
Resources not showing up in lessons, coach quiz planning page on Mac - app and Pex

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8828]
When navigating to a lesson within the class tab, no lesson resources display. Similarly, 

Not a problem when running a dev server/chrome on Mac, but pex/Chrome and mac app both have this issue
https://www.notion.so/learningequality/REGRESSION-Learn-Lessons-page-6-Broken-86d6a790568b429ca01e5ea9d0fde4c0
https://www.notion.so/learningequality/REGRESSION-Coach-Quiz-Planning-page-b63ccf5cbd304122b2412279445b0462

**Comment by jredrejo** [comment]
FYI: using the same KOLIBRI_HOME, and just switching from pex to deb, it works. Going back to pex it does not

**Comment by rtibbles** [comment]
Fixed in #8858 - sorry @jredrejo, @marcellamaki had a brain wave!
