### ISSUE TITLE
View more link at top of library page (displaying search results) should be removed

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8832]
https://www.notion.so/learningequality/Feedback-13-Learn-Library-Page-aa394a3cddaf49c6a26c0ab584de2659
https://www.notion.so/learningequality/SUGGESTION-Library-13-4930ffc2a42b401f86fb4a6bb3627d50
(has also been noted in other feedback, but perhaps gotten lost in the shuffle)

**Comment by jtamiace** [comment]
This was the original layout for results text and filter chips

<img width="496" alt="Screen Shot 2021-12-07 at 11 05 50 AM" src="https://user-images.githubusercontent.com/6668144/145090717-d2c23719-4e5b-48ad-bcf0-ba8a8718c5fd.png">
