### ISSUE TITLE
Kolibri upgrade on windows installer breaks when you haven't uninstalled previous version

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8841]
Please see logs in: 
https://www.notion.so/learningequality/Kolibri-did-not-shut-down-before-upgrade-on-Windows-cb87b3805a5049af981ca5b3ea943573

**Comment by rtibbles** [comment]
This may well be a duplicate of #8853

**Comment by rtibbles** [comment]
Should be fixed by #8883
