### ISSUE TITLE
ux issues with 'search' tab in Library

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8847]
## Observed behavior

| observation | illustration |
|--|--|
| At smaller sizes the 'Search' tab launches the side panel which seems incorrect |  ![2021-12-13 21 44 28](https://user-images.githubusercontent.com/2367265/145923793-dcd8ec06-cc88-42e7-aacc-a8a056ee5d87.gif) |
| The tabs also initially start out with neither selected | ![2021-12-13 21 41 16](https://user-images.githubusercontent.com/2367265/145923786-ea1ade58-f82b-4efa-a8e8-5377d3d21666.gif)| 
| Additionally, on mid-size responsive views when there are no folders there is a only single tab. At this point, it should probably be replaced with just a header or a label rather than being clickable. | ![image](https://user-images.githubusercontent.com/2367265/146063678-e7667c4e-f2d3-46e2-918d-3dc48c0f5a66.png) |

## Expected behavior

* Make sure there is always one tab selected
* Do not overload the 'search' tab to launch filter side view
* Display as header instead of tab when there is only one tab

## User-facing consequences

confusing navigation and interaction

**Comment by rtibbles** [comment]
Also on large views when there are no folders, the 'Folders' header still appears and is still selectable:

![uselessheaders](https://user-images.githubusercontent.com/1680573/146077056-9ca2ead0-7cb8-4d91-8ac9-7018950b785d.gif)
