### ISSUE TITLE
Kolibri locked up on Windows and then unable to restart

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8851]
https://www.notion.so/learningequality/BUG-Kolibri-locked-up-on-Windows-and-then-unable-to-restart-5562f3d8da4e40dcb6559b206768aff8

From @jamalex bug bash notes: At first, it worked. And I imported content, then set up an Android device with a single user, autosyncing. Then, after a few minutes, the server stopped responding (browser load hanging). Then I exited Kolibri and tried to restart, and the port was still locked: 

<img width="1110" alt="Untitled (3)" src="https://user-images.githubusercontent.com/17235236/145109982-8aff380a-1934-4b1c-acb6-3771ce6e10aa.png">

**Comment by jamalex** [comment]
Turns out the reason the port was still locked was that VS Code was doing some port forwarding that claimed it. When VS Code was closed, starting up still failed, but this time due to https://github.com/learningequality/kolibri/issues/8853

**Comment by jredrejo** [comment]
Closing it as it seems the remaining problem is being managed in #8853
