### ISSUE TITLE
Continual re-initialization of zeroconf every 5 seconds

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8852]
https://www.notion.so/learningequality/BUG-Continual-re-initialization-of-zeroconf-every-5-seconds-9d6917de73024f00b106b50251eff2be

The log files on my Windows machine show "New addresses detected since zeroconf was initialized, updating now" messages every 5 seconds. I added additional logging to the following code:

```
logger.info(
    "New addresses detected since zeroconf was initialized, updating now"
)
logger.info("Old list: " + str(self.broadcast.addresses))
logger.info("New list: " + str(set(get_all_addresses())))
```

which shows that the zeroconf-internal list has stripped out the link-local addresses and so the comparison is never true:

```
INFO 2021-12-07 11:07:22,701 kolibri.utils.server New addresses detected since zeroconf was initialized, updating now
INFO 2021-12-07 11:07:22,702 kolibri.utils.server Old list: {'172.24.32.1', '192.168.137.1', '6.5.75.243', '172.22.48.1', '127.0.0.1'}
INFO 2021-12-07 11:07:22,709 kolibri.utils.server New list: {'172.24.32.1', '169.254.148.11', '169.254.117.77', '169.254.203.37', '192.168.137.1', '10.0.85.2', '169.254.181.43', '6.5.75.243', '127.0.0.1', '169.254.173.0', '169.254.226.233', '172.22.48.1', '169.254.22.56', '169.254.14.241'}
```

Proposed solution:

- Update get_all_addresses to exclude link-local addresses
- Use a local cache of the address list on the ZeroConfPlugin as an additional less brittle way of detecting changes

**Comment by rtibbles** [comment]
Seems likely that this is causing global issues on the windows installer.
