### ISSUE TITLE
404 error in console on device/#/content/channels

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8855]
https://www.notion.so/learningequality/BUG-Device-Import-7f01fc98a2744599959fe3bff75b88a9

bug bash feedback note from @DXCanas: 
404 for channels that haven't been opened before - still loads fine after a while

**Comment by rtibbles** [comment]
This is not an error. It specifically says so in the console: https://github.com/learningequality/kolibri/blob/02fc882b827a1c822d9d5863d37c0a9e1cd5ab61/kolibri/plugins/device/assets/src/modules/wizard/handlers.js#L174
