### ISSUE TITLE
Impossible to scroll the 'Change language' modal in app context on Android devices

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8867]
## Observed behavior
More acute on small phone screens, but replicable on tablet in landscape mode.
Not replicable in browser responsive view, only when installed on physical device.

phone | tablet
--- | ---
![change-language-modal-does-not-scroll](https://user-images.githubusercontent.com/1457929/145160989-691ed1ad-7302-44f2-b12b-8c7a4d168eec.gif) | ![change-language-modal-does-not-scroll-tablet](https://user-images.githubusercontent.com/1457929/145161009-9ed7a78a-e50b-43c9-914d-a12b59fdd4f7.gif)

## Errors and logs
…

## Expected behavior
Ability to scroll the list of languages.

## User-facing consequences
Impossible to select the desired language if off screen.

## Steps to reproduce
...

## Context

 * Kolibri version: 0.15.0b3
 * Operating system: Android 9.0
 * Browser: -

cc @marcellamaki @rtibbles

**Comment by akash5100** [comment]
Why is this happening? I want to help.

**Comment by radinamatic** [comment]
And apparently this has something to do with having the Android device USB-connected and **inspected** for debugging... 😒 

As soon as the Dev tools inspect window is closed, modal becomes scrollable, go figure 🤷🏽‍♀️
