### ISSUE TITLE
Reports - Missing answered question data after upgrade from 0.14.7 to 0.15

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8869]
## Observed behavior
This issue is a follow-up of https://github.com/learningequality/kolibri/pull/8818
When I'm logged in as a Coach and I go to the reports immediately after I've upgraded Kolibri from 0.14.7 to 0.15 and I attempt to go through the completed lessons or quizzes I'm not able to see the actual questions, instead I see the following text: No attempts made on this question.

## Expected behavior
All the completion details should be displayed.

## Steps to reproduce the issue
1. Install the a 0.14.7 version of Kolibri from [here](https://learningequality.org/r/kolibri-windows-setup-latest).
2. Setup a facility, create classes, users, lesson etc and complete a lesson and a quiz using exercises such as CK12's 'Make 10 (grids and number bonds)'.
3. Upgrade to the 0.15 version by Installing the following [build.](https://buildkite.com/learningequality/kolibri-python-package/builds/4467).
4. Go to Coach>Reports and observe the reports for the completed lesson and quiz. (Note that after restart of Kolibri the issue is observed only for the completed lesson while the quiz data is displayed correctly)

## Additional information

![2021-12-07_16-19-30](https://user-images.githubusercontent.com/79847249/145059555-47a4535f-9f9c-4118-b059-05487be78d51.png)

## Logs and DB files: 
[UbuntuDBlogs.zip](https://github.com/learningequality/kolibri/files/7669547/UbuntuDBlogs.zip)
[WindowsDBLogs.zip](https://github.com/learningequality/kolibri/files/7669548/WindowsDBLogs.zip)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by pcenov** [comment]
Retested today using the most recent [0.15 build](https://buildkite.com/learningequality/kolibri-python-package/builds/4548) and this issues is still extant.

**Comment by radinamatic** [comment]
cc @rtibbles @marcellamaki

**Comment by rtibbles** [comment]
Hrm a key to thing I notice here is that the URL is incorrect, so I think there's a frontend issue here. I can look at replicating locally with the supplied DB.

**Comment by rtibbles** [comment]
Replicated locally with your DB.
