### ISSUE TITLE
Beta 3 - All lesson resources are not displayed

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8870]
## Observed behavior
No lesson resources are displayed in Class>Lesson so a Learner cannot view and complete them. The quiz resources are displayed correctly.

## Expected behavior
All lesson resources should be displayed correctly

## Steps to reproduce the issue
1. Install the the 0.15 beta 3 version of Kolibri from [here](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta3).
2. Setup a facility, create classes, users, lesson etc
3. Login as a Learner and attempt to complete an assigned Lesson

## Additional information
![2021-12-08_14-33-28](https://user-images.githubusercontent.com/79847249/145210783-44e8ccea-8f06-424d-9ca0-a37834ba0501.png)

## Logs and DB files: 
[Logs.zip](https://github.com/learningequality/kolibri/files/7676090/Logs.zip)

## Usage Details
 - OS: Windows 10, Ubuntu, MacOS
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
This is a duplicate (albeit more detailed) of https://github.com/learningequality/kolibri/issues/8828 which has been fixed in release-v0.15.x. Closing!
