### ISSUE TITLE
change "None of the above" string in category filter

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8872]
## Observed behavior

The "None of the above" string slipped in to 0.15.0 by mistake. The intent was "Other", or possibly "Uncategorized"

## Expected behavior

The intent is to communicate that when the option is selected, all resources that are not tagged with a category are shown.

## User-facing consequences

confusing terminology

## Context

0.15.0

**Comment by akash5100** [comment]
If I am not wrong, files are right here
https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L81

I will try to solve this issue.
And I will follow #8871 and try to solve it too.

**Comment by akash5100** [comment]
Hello @indirectlylit, I think the "Title Case" issue is already solved.
please check [here](https://github.com/learningequality/kolibri/pull/8793/commits/7c7efafd19e56f0af93bddc3ad570fb73c0d9102#diff-be519ac938881b9857a564e6f29554f4ae630c17161865022783f023e4de10ceL266) and [latest](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L268) file.

**Comment by indirectlylit** [comment]
Thanks – I've updated the issue to reflect that. We still need to decide what the final string should be.

Once decided, this work should be done in `develop` for 0.16 and involve removing this:

https://github.com/learningequality/kolibri/blob/4bff6ab93b642a6665812dacfb42e915d30e07f1/kolibri/core/assets/src/mixins/commonCoreStrings.js#L1048-L1053

**Comment by indirectlylit** [comment]
> And I will follow #8871 and try to solve it too.

Please coordinate with @rtibbles on that

**Comment by rtibbles** [comment]
Decision here: use 'Uncategorized'.
