### ISSUE TITLE
Incorrectly displayed 'View information' overlay

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8874]
## Observed behavior
The "View information' overlay is not displayed correctly - it's positioned to the left side of the page while it should be at the right.

## Steps to reproduce the issue
1. Install the the 0.15 beta 3 version of Kolibri from [here](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta3).
2. Go to Library and select a resource to preview
3. Click the info icon

## Screenshot

![2021-12-08_18-43-41](https://user-images.githubusercontent.com/79847249/145248378-52a7a086-6f3a-4326-bb57-49653b271b98.png)

## Usage Details
 - OS: Windows 10, Ubuntu, MacOS
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
I encountered this while testing the app on Android tablet, probably related...

![DevTools - localhost:8080-en-learn---topics-c-a1b7e748daa34232b12022017fbb9b59?lessonId=4f1a41ccfc7fb400eb3b0e86cab29c5c classId=c1863477e405753f9e208c8ddd7f3644 last=LESSON_PLAYLIST_001](https://user-images.githubusercontent.com/1457929/145254288-c7cc7934-4489-4c44-b6f9-9173f226de2b.png)

cc @marcellamaki

**Comment by marcellamaki** [comment]
Closing as these issues are covered in #8827
