### ISSUE TITLE
Completion modal after the practice quiz in a lesson is too short

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8893]
## Observed behavior
Currently flashes for just a fraction of the second before the practice quiz report appears. Tested on learn-only Android app, while server is on Ubuntu 18.04.

![completion-modal-flash](https://user-images.githubusercontent.com/1457929/145635425-4b441cec-8c7d-42f0-a5af-252f52018ba7.gif)

## Errors and logs
…

## Expected behavior
Completion modal should remain opened, until learner decides to either move on with the lesson or view the report.

[Slack discussion around the need for `Move on` button](https://learningequality.slack.com/archives/C02JTHE8EV9/p1639160750037300) in the practice quiz report.

## User-facing consequences
Inconsistent flow between resources in a lesson.

## Steps to reproduce
Complete a practice quiz in a lesson that has other resources lined up after the quiz.

## Context
 * Kolibri version: 0.16 `develop`
 * Operating system: Ubuntu 18.04, Android 8.0
 * Browser: - 

cc @rtibbles @sairina

**Comment by sairina** [comment]
Can confirm that this bug also exists for the browser. But, not sure if the completion modal is too short, or if the "Submit" modal is persisting too long?

![2021-12-14 12 54 06](https://user-images.githubusercontent.com/13563002/146094613-dda7c085-0ad1-450f-af60-0923273af649.gif)

**Comment by rtibbles** [comment]
I think this might be caused by optimistic updating of `complete` to `true` - if we rolled that back, then it would show the submit modal until submission had completed, then pop up the completion modal.

**Comment by rtibbles** [comment]
But we might want to add some loading state to the submission modal to indicate when it is being submitted?
