### ISSUE TITLE
Disappearing timer in practice quizzes on learn-only device

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8896]
## Observed behavior
Practice quiz inside lessons have the timer icon in the top bar that briefly appears on the learn-only Android app, but stays and counts when learner connects through the browser.

app | browser
--- | ---
![time-counter2](https://user-images.githubusercontent.com/1457929/145643382-697c1d42-e6b2-4e41-9b4b-9472bc952f73.gif) | ![time-counter-browser](https://user-images.githubusercontent.com/1457929/145643414-881304f2-fb8a-41e2-8bdc-43f09ea4c0d6.gif)

## Errors and logs
…

## Expected behavior
Working counter in the app context.

## User-facing consequences
User unable to keep track of the time spent in the quiz.

## Steps to reproduce
Start the practice quiz in the app on learn-only device.

## Context
 * Kolibri version: 0.16 (latest APK and DEB assets from the `develop` branch)
 * Operating system: Ubuntu 18.04, Android 8.0
 * Browser: -

cc @sairina @marcellamaki @rtibbles

**Comment by marcellamaki** [comment]
@radinamatic -- on the android app view you have screenshot, you're in the report, not actively taking the quiz. Do you experience the same problem if you hit the "try again" button and re-start the quiz?

**Comment by radinamatic** [comment]
Argh, you are correct... 🤦🏽‍♀️ 

What got me confused is that a brief flash of the counter is seen on the quiz report, **but only on the real device**, not if I record the Chrome dev tools inspect window. Here's what I see IRL:


https://user-images.githubusercontent.com/1457929/145853121-d07ddb63-4031-4479-9808-3abd46bf3b60.mp4

**Comment by marcellamaki** [comment]
Thanks for clarifying @radinamatic -- that's helpful. I can take a look at this, although I'm not sure given the new context that it's a P0 (but I defer to @sairina 😄). I can prioritize if there's nothing more critical that needs to be finished or reviewed before the release today!

**Comment by radinamatic** [comment]
Yeah, not sure if it warrants the P0 status either...

**Comment by pcenov** [comment]
Hi @radinamatic - I'm not able to replicate the issue with the disappearing timer - currently when going through a practice quiz the timer is constantly visible both in the Android device and a desktop browser.

**Comment by radinamatic** [comment]
Closing as not extant on 0.17! 💥
