### ISSUE TITLE
some UI elements are not themed correctly and have hardcoded colors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8899]
## Observed behavior

Some non-theme colors are hard-coded into the styling which prevents them from being overwritten by the theme system.

![image](https://user-images.githubusercontent.com/2367265/145693480-19bdc021-7d54-4e02-b2b5-865759945270.png)

### Brand colors (most important)

I've found the following instances of hard-coded brand colors which will look bad under themes. Items below should all draw from [brand colors](https://design-system.learningequality.org/colors/#brand):

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L272

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L391

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L393

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/ActivityButtonsGroup.vue#L94

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/ActivityButtonsGroup.vue#L105

### UI colors

This one should use our standard [`error` color](https://design-system.learningequality.org/colors/#tokens-error)

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/device/assets/src/views/FacilitiesPage/RemoveFacilityModal.vue#L142

### Grayscale (least important)

These items are grayscale. They should also be referenced using our standard scales, but the consequences are less significant.

Where appropriate it's best to use the following specialized grayscale tokens because this will help us eventually make dark and high-contrast themes.:

* [`surface`](https://design-system.learningequality.org/colors/#tokens-surface)
* [`text`](https://design-system.learningequality.org/colors/#tokens-text)
* [`annotation`](https://design-system.learningequality.org/colors/#tokens-annotation)
* [`textDisabled`](https://design-system.learningequality.org/colors/#tokens-textDisabled)
* [`textInverted`](https://design-system.learningequality.org/colors/#tokens-textInverted)
* [`fineLine`](https://design-system.learningequality.org/colors/#tokens-fineLine)

When none is appropriate, use one of the standard [grey values from our palette](https://design-system.learningequality.org/colors/#palette) unless alpha transparency is required.

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/core/assets/src/views/FullScreenSidePanel/SidePanelContentItem.vue#L127

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/SelectGroup.vue#L238

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/AlsoInThis.vue#L202

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/LearningActivityChip.vue#L51

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/LearningActivityChip.vue#L51

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/SearchChips.vue#L130

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/media_player/assets/src/views/MediaPlayerTranscript/index.vue#L249

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/slideshow_viewer/assets/src/views/SlideshowRendererComponent.vue#L358

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/slideshow_viewer/assets/src/views/SlideshowRendererComponent.vue#L366

## Expected behavior

All colors should be referenced using theme tokens:

https://design-system.learningequality.org/colors/

## User-facing consequences

inconsistent styling in themed versions of Kolibri

## Steps to reproduce

Try adjusting colors in the default theme or applying a theme plugin

## Context

0.15.0-beta3

**Comment by pranay101** [comment]
I am new to open-source. and I would like to work on this issue.

**Comment by indirectlylit** [comment]
Thank you @pranay101! If you work on this, please target the [`theme-updates`](https://github.com/learningequality/kolibri/tree/theme-updates) branch which will be released in the 0.15.1 patch.

**Comment by vkWeb** [comment]
@pranay101 how's the progress on this? if you need any help feel free to ping me brother.

**Comment by pranay101** [comment]
@vkWeb yeah brother, it seems Kolibri is getting way too heavy for my system. any idea on how to run it in a light mode or something.

**Comment by MisRob** [comment]
@pranay101 

You can run `yarn run build` to build all plugins once and then only rebuild those plugins that your work is affecting like `yarn exec kolibri-tools build dev -- --plugins kolibri.core,kolibri.plugins.learn` together with `yarn run python-devserver`

**Comment by MisRob** [comment]
@pranay101 Are you still planning to work on this?

**Comment by pranay101** [comment]
@MisRob I tried running it on my system and it had me force shutdown my PC. I don't think I could work on this UI part of Kolibri. looking for some backend issue where I can put my contribution.

**Comment by MisRob** [comment]
Thank you for the information, I'll assign myself to this one then
