### ISSUE TITLE
Perseus drag & drop offset in release-v0.15.x

### ISSUE THREAD

**Issue by danigm** [learningequality/kolibri#8905]
## Observed behavior

Practice content with drag & drop, like the ones in Khan Academy, for example, "Count with small numbers" is not being rendered correctly when dragging. The drag object is not positioned in the right place, it's always positioned at (top: 0, left: 13) relative to the `#perseus` div.

![kolibri](https://user-images.githubusercontent.com/50350/145807277-1b0cf13a-e827-4bba-9fbd-55f27166c88f.png)

I've detected that  the problem is in the [perseus code](https://github.com/learningequality/perseus/blob/master/src/widgets/orderer.jsx#L434).

## Expected behavior

The transparent object should be placed on top of the selected one.

## Context
 * Kolibri version: release-v0.15.x (4c1eca4e4e68945a4733382100013c07baaebb9f)
 * Operating system: ubuntu 21.10
 * Firefox

**Comment by rtibbles** [comment]
Hrm, I am wondering if this is a regression caused by wrapping the perseus renderer in our KGrid component.

**Comment by rtibbles** [comment]
Removing KGrid does not resolve this, so that does not seem to be the cause here.
