### ISSUE TITLE
remove unnecessary uses of $computedClass

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8910]
## Observed behavior

`$computedClass` is available for specifying colors in pseudo-elements such as `:hover` or `:focus`. For example, this is a necessary use:

```vue
<input :class="$computedClass({ '::placeholder': { color: $themeTokens.annotation } })" />
```

## Expected behavior

For most styles it is not necessary to use `$computedClass` and elements can be styled directly:

```vue
<div :style="{ color: $themeTokens.error }">This is an error</div>
```

In situations where the style gets complex, computed props can be used:

```vue
<div :style="labelStyle">This is an error</div>
```

```js
computed {
  labelStyle() {
    return { color: $themeTokens.textInverted, backgroundColor: $themeTokens.primaryDark };
  }
}
```

## User-facing consequences

For developers, code is more complex than it needs to be

## Steps to reproduce

Search codebase for `$computedClass` and identify unnecessary usages. For example:

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/user_auth/assets/src/views/AuthBase.vue#L23

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/user_auth/assets/src/views/AuthBase.vue#L45

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L83-L88

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/SearchTools/LessonsSearchBox.vue#L73-L77

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/cards/BaseCard.vue#L116-L123

https://github.com/learningequality/kolibri/blob/4c1eca4e4e68945a4733382100013c07baaebb9f/kolibri/plugins/learn/assets/src/views/thumbnails/Thumbnail.vue#L51-L60

## Context

0.15.0

**Comment by MisRob** [comment]
Resolved in #8965
