### ISSUE TITLE
Kolibri Android App - Incorrect quiz completion messages

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8922]
## Observed behavior
While testing the Android app today I noticed a weird behavior after completing a quiz which I was subsequently unable to replicate. Filing an issue in case the logs/screenshots will have some info for the devs.

## Steps to reproduce the issue
1. Install the following Android build: https://buildkite.com/learningequality/kolibri-android-installer/builds/3613
2. Launch the app and login as a Learner
3. Complete a quiz and observe the messages about the number of answered questions.

## Additional information
![2021-12-14_15-18-24](https://user-images.githubusercontent.com/79847249/146027852-9ea2bb99-2b68-45c5-a242-0e4974cf4e00.png)
![2021-12-14_15-19-22](https://user-images.githubusercontent.com/79847249/146027858-a8ca1da9-62d8-43dc-af21-da1da0f358a6.png)

## Logs and DB files: 
[AndroidLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7712473/AndroidLogsAndDB.zip)

## Usage Details
 - OS: Android 7, Samsung S7

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Encountered the same last week 🙂 

![DevTools - localhost 8080-en-learn---topics-c-9f121944a93942fc999c96fa21ba6281 lessonId=63c71d9c40d80d82921104dda1785898 classId=dd2541e39fa77dbf5f39a3ffc346149f last=LESSON_PLAYLIST_001](https://user-images.githubusercontent.com/1457929/146028615-11db2b74-43dd-40be-b05a-5b5c26c0b217.png)

@rtibbles , given that neither @pcenov nor I were able to replicate it consistently, leaving it as P1 for now.

**Comment by rtibbles** [comment]
I can backport the fix I had worked up for practice quizzes in develop to address this as well.
