### ISSUE TITLE
Why is the new release tagged v.0.15.0 instead of v0.15.0 ?

### ISSUE THREAD

**Issue by holta** [learningequality/kolibri#8963]
Was the additional dot (period, to the right of the letter 'v') added by accident...or for a reason?

https://github.com/learningequality/kolibri/releases/tag/v.0.15.0

**Comment by nucleogenesis** [comment]
Ah that was a mistake - thanks for catching that

**Comment by radinamatic** [comment]
Thank you @holta, it's a privilege to have such an attentive community! 🥇 💯
