### ISSUE TITLE
Refactor library page using a reusable/props-driven component for main content/content grid(s)

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8978]
These sections can be turned into a "main view" component. This component could either be used twice within the page (one for the default view and once for results) or could be used once and have the contents changed based on whether or not search results are displayed. As a follow up issue, the same changes can be applied in the Topics Page.

**Writing unit tests for this new component is part of this issue being done**

![Screen Shot 2022-01-07 at 10.58.48 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/00e8b34d-3569-4e2e-81e6-0db248ee9ecc)

![Screen Shot 2022-01-07 at 10.58.58 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/f46d061c-159b-4f5b-9842-c5f4e7d0f528)

**Comment by abhimnc** [comment]
hi @marcellamaki. I would like to contribute to this issue. I have contributed to #8782 and #8720 till now. Can you give me some heads up for this issue which might be useful ?
I have also interacted with you over mail regarding contribution. Hope you  remember me :).
