### ISSUE TITLE
Refactor: adding optional/required props in `FullScreenSidePanel`

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#8989]
## Observed behavior
Currently, there are two places where the `close` button that appears in mobile can be rendered from: `FullScreenSidePanel` and `LibraryPage`. As it currently stands in the code, the `close` button in `FullScreenSidePanel` is always hidden when a user is in the Library page and in a Topic page, and that button is rendered instead by the `LibraryPage` and `TopicsPage` parent components. 

Two decisions to be made:
- [ ] Which component should be rendering the `close` button - the `FullScreenSidePanel` or the parents (`LibraryPage`/`TopicsPage`)?
- [ ] Should the `closeButtonHidden` prop be required, and if so, should we refactor all instances of `FullScreenSidePanel` with that required prop?

<img width="570" alt="Screen Shot 2022-01-12 at 2 13 50 PM" src="https://user-images.githubusercontent.com/13563002/149231365-324477c5-9673-47d2-9147-81d1c5e602fc.png">

## Errors and logs
No errors.

## Expected behavior
See decisions above.

## User-facing consequences
No user-facing consequences, but for good for cleaning up our code.

## Steps to reproduce
1. Log in as Learner and on mobile
2. Go to library page and click on the "Filter" button
3. This is in the `LibraryPage` and `FullScreenSidePanel` components

**Comment by nucleogenesis** [comment]
I think that a feature of the FullScreenSidePanel  (FSSP) should be that it always provides a way to close itself. It puts an absolutely positioned button in place, and should be top-aligned with the `header` slot's contents - or just above it perhaps?

It is then incumbent on LibraryPage / TopicsPage to handle the `closePanel` event, which is emitted whenever the close button is clicked only - simplifying how other components make use of FSSP.

It looks like there are two specific states for the icon that we'd want that would jive with our designs - a back arrow vs a close X.

I think FSSP being opinionated about those being the only options would be okay and aligns with our typical design patterns I think - so having just a prop `iconType: 'back' | 'close'` where the `back` renders a left-aligned arrow and the `close` renders a right-aligned X (in LTR languages, vice versa in RTL) could be a fairly simple solution

I guess the main thing I'm thinking is that the parent component shouldn't be injecting its own icon and having to style/position it. That should all be handled within the FSSP component as one of its features IMO.
