### ISSUE TITLE
REMOTE_CONTENT option does not affect required storage at content import

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8994]
## Observed behavior
When using the `REMOTE_CONTENT` option, the device plugin is not aware that this means that no local storage space is required in order to import content.

This means that on devices using this option, the amount of content that can be imported at one time will be artificially restricted.

## Expected behavior
Should be able to import any amount of content when `REMOTE_CONTENT` is set.

## User-facing consequences
Not able to provision servers effectively.

**Comment by socketbox** [comment]
Just to clarify, does this issue also encompass or affect the "Free disk space" label show here?
![image](https://user-images.githubusercontent.com/1593835/153968525-244e0d80-99e8-40b7-96bb-9817d746a1b6.png)

**Comment by rtibbles** [comment]
Fixed in #9246
