### ISSUE TITLE
Browse channel - The Folders and Search section are not fully displayed when there are 0 results

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9010]
## Observed behavior
When I go to Learn>Library and apply a filter for which there are 0 results and navigate to the Browse channel page I see the Folders and Search section shrunk.
See the attached screenshot

## Steps to reproduce the issue
1. Install the official 0.15 build of Kolibri
2. Import the QA Channel (nakav-mafak) and go to Learn>Library
3. Filter by language - Espanol - and click the Spanish folder in the Search results

## Additional information
![2022-01-19_17-38-49](https://user-images.githubusercontent.com/79847249/150164663-65d0e0e3-b70f-4e6a-bb8d-cd02d865f3f2.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Replicated in Firefox on Windows 7.

![filter-0-results](https://user-images.githubusercontent.com/1457929/150188584-44c8b318-f6bb-4490-9067-273865cb2270.gif)
