### ISSUE TITLE
Survey modality - Answer history is displayed in reverse order

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9020]
## Observed behavior
The answer history is displayed in reverse order with the last question being displayed on top of the list.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/4813
2. Import the Colors of Kindness (gutuf-potuv) channel and go to Learn>Library
3.  Complete any of the available surveys

## Additional information
![2022-01-21_14-51-38](https://user-images.githubusercontent.com/79847249/150543395-f665e408-47ff-4bdf-8f33-5c34666c9dbc.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by nucleogenesis** [comment]
Fixed in #9000
