### ISSUE TITLE
Survey modality - Getting 500 points for a completed survey in both desktop and mobile view

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9021]
## Observed behavior
Currently I'm getting 500 points for a completed survey while there should be no points awarded for a survey.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/4813
2. Import the Colors of Kindness (gutuf-potuv) channel and go to Learn>Library
3.  Complete any of the available surveys

## Additional information
![2022-01-21_15-31-07](https://user-images.githubusercontent.com/79847249/150544121-d659cd6b-03dd-4b49-a0cc-67951d1b1081.png)
![2022-01-21_15-28-49](https://user-images.githubusercontent.com/79847249/150544129-eadcd53e-133f-4e87-899c-24a2f56124f1.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by rtibbles** [comment]
Why should no points be awarded for a survey? This is intended behaviour at the moment.

**Comment by pcenov** [comment]
I might have got carried away here 😅 - indeed there is no requirement against getting reward points for just completing a survey.
