### ISSUE TITLE
Set SECURE_CONTENT_TYPE_NOSNIFF setting to True

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9033]
## Observed behavior
Currently clients can MIME sniff content rather than deferring to the declared MIME type.

## Expected behavior
Clients should not be able to MIME sniff content, can set this response header with this setting: https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SECURE_CONTENT_TYPE_NOSNIFF

**Comment by sakshampathak1508** [comment]
Hi i would like to work on this issue and make it my first contribution in the world of open source

**Comment by rtibbles** [comment]
Hi @sakshampathak1508 - we'd be happy to get your contribution. The place to make this change would be in the `base.py` module in `kolibri/deployment/default/settings`.

Please branch from the release-v0.15.x branch and target that branch with the pull request.

**Comment by rtibbles** [comment]
Fixed in #9195
