### ISSUE TITLE
Remove all instances of the `crossComponentTranslator` before the next string freeze

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9037]
## Observed behavior

After the string freeze for the `0.15` release, we couldn't modify strings and their namespaces anymore. That also means that we couldn't move strings between components. We have the `crossComponentTranslator` utility which allowed us to access translation strings in a component from another component so that we could temporarily work around this. Before the next string freeze, we should clean up all places where the `crossComponentTranslator` is used, move strings to components from where they are really used or to common string files, and remove all components that are not used but needed to be left in the codebase because they contain some translations.

### Example

Translations strings from the `OverallStatus` component

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/AssessmentWrapper/OverallStatus.vue#L16-L23

should be moved to the `LessonMasteryBar` component

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/AssessmentWrapper/LessonMasteryBar.vue#L30

and used directly instead of using the `crossComponentTranslator`

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/AssessmentWrapper/LessonMasteryBar.vue#L28

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/AssessmentWrapper/LessonMasteryBar.vue#L8

`OverallStatus` component should then be removed.

Note that removing a component might not be desired at all places that need to be cleaned up since sometimes we share strings between components that are all used. In such cases, the `crossComponentTranslator` should still be removed and strings can be duplicated in both components, alternatively, they could be moved to shared string files like for example `commonCoreStrings`, `commonLearnStrings`, etc. depending on what location is appropriate.

Search codebase for the `crossComponentTranslator` term to find more.

**Comment by photon0205** [comment]
Hi!!, Is this issue still valid?

**Comment by MisRob** [comment]
Hello @photon0205, yes it is still valid, are you asking because you'd like to work on it?

**Comment by photon0205** [comment]
Yes, I would like to work on this

**Comment by MisRob** [comment]
Thank you, we appreciate that. I'll assign you. Feel free to start and let me know if you encountered any issues. Depending on how many instances of `crossComponentTranslator` are currently in the codebase, you may open one pull request or split work into more pull requests if that'd be easier.

**Comment by sahej-hira** [comment]
I would like to would on this issue. If its still valid, please assign it to me.

**Comment by photon0205** [comment]
@shark-lamp I am working on it

**Comment by radinamatic** [comment]
>  the crossComponentTranslator should still be removed and strings can be duplicated in both components, alternatively, they could be moved to shared string files like for example `commonCoreStrings`, `commonLearnStrings`, etc. depending on what location is appropriate.

I did not review the code, but noting that  moving the identical strings used in different components into  `commonCoreStrings` or `commonLearnStrings` is almost always the preferred solution, as duplicating them just inflates our translation word count and needlessly increases the i18n budget.

**Comment by akila-i** [comment]
Hi @MisRob @marcellamaki ,
Is this issue still open? If so, I would love to take and work on it.
I have done working on the issue #9867 and the PR #10130 is about to get merged. So I would be free to work on another issue.

**Comment by MisRob** [comment]
Thank you, @Akila-I, we appreciate your interest. This particular issue is currently time-sensitive so it's been already been assigned to @marcellamaki, who will start working on it soon. I saw that you've already posted a comment of interest to one another issue, so I'd recommend focusing on that.
