### ISSUE TITLE
Slideshow resource cards don't indicate a learning activity in title and thumbnail areas

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9042]
## Observed behavior

There is no "Read" learning activity label and icon in the card title area and the generic thumbnail (displayed when a resource has no thumbnail) is empty instead of showing a dimmed "Read" learning activity icon. This was first observed on cards in the library (compare with other cards):

![slideshow](https://user-images.githubusercontent.com/13509191/151121446-fed01495-09eb-42d5-bca7-337a0e07eb43.png)

This is likely related to the invalid property Vue warning showing in the browser console `[Vue warn]: Invalid prop: custom validator check failed for prop "kind"`

## Errors and logs

![console](https://user-images.githubusercontent.com/13509191/151121745-e8806e36-1b27-4e6b-af52-a1cc79537f26.png)

## Expected behavior

- there is "Read" learning activity icon and label in the title area
- there is "Read" learning activity icon in the generic thumbnail area
- no Vue warning in the browser console

## User-facing consequences

Users can't determine learning activities associated with slideshow resources, but note [@radina's message](https://github.com/learningequality/kolibri/issues/9042#issuecomment-1022435536):

> For the context, the `slideshow` type of resource was a prototype developed by @nucleogenesis a few years ago, but it did not go further from that _prototype_ stage. As far as I know, slideshow resource can only be made with Ricecooker, and that item in the QA channel is the only instance of a slideshow resource that exists on Studio.

## Steps to reproduce

1. Import the Kolibri QA Channel by using `nakav-mafak` token
2. Navigate to "Learn" -> "Library" -> "Kolibri QA Channel"
3. Go to "HTML5" sub-folder in the "Folders" tab in the side panel
4. Scroll down to see the "Slides Slides Slides!" resource card

## Context

 * Kolibri version: Kolibri 0.15.1.dev0+git.20220125194959
 * Operating system: Ubuntu 20.04.3 LTS
 * Browser: Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by MisRob** [comment]
@jtamiace What learning activity should be associated with slideshow resources? "Read" I assume?

**Comment by MisRob** [comment]
Most likely related to #9044

**Comment by jtamiace** [comment]
Yes, original intent for slides was to have Read as the default activity

**Comment by radinamatic** [comment]
For the context, the `slideshow` type of resource was a prototype developed by @nucleogenesis a few years ago, but it did not go further from that _prototype_ stage. As far as I know, slideshow resource can only be made with Ricecooker, and that item in the QA channel is the only instance of a slideshow resource that exists on Studio.

**Comment by MisRob** [comment]
@jtamiace Thank you, I'm updating the issue description with this information
@radinamatic Thank you, I think it'd make sense to lower priority then

**Comment by MisRob** [comment]
@radinamatic I also added your comment to "User-facing consequences" sections of this issue as well as to #9044

**Comment by Akila-I** [comment]
Hey @MisRob , since #9044 is related this, is this issue no longer open to work?
I noticed one has expressed hi interest on that issue. If this one can be worked separately, I'd love to take this on.

**Comment by rtibbles** [comment]
As it seems that the only known instance of a Slideshow resource now has the learning activity properly applied, and any newly created nodes on Studio are required to have a learning activity before they are published, I think this issue is now resolved.
