### ISSUE TITLE
The top bar on a slideshow resource page doesn't indicate a learning activity

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9044]
## Observed behavior

"Read" learning activity icon is missing at the top bar on a slideshow resource page

![slide](https://user-images.githubusercontent.com/13509191/151149987-40a43077-8dc9-41db-a93c-de650585aac9.png)

This is likely related to the invalid property Vue warning showing in the browser console `[Vue warn]: Invalid prop: custom validator check failed for prop "learningActivities".`

## Errors and logs

![error](https://user-images.githubusercontent.com/13509191/151150026-a4477271-903a-44b9-b213-ee06a7490424.png)

## Expected behavior

- there is "Read" learning activity icon next to a resource title at the top bar
- no Vue warning in the browser console

## User-facing consequences

Users can't determine learning activities associated with a slideshow resource, but note [@radina's message](https://github.com/learningequality/kolibri/issues/9042#issuecomment-1022435536):

> For the context, the `slideshow` type of resource was a prototype developed by @nucleogenesis a few years ago, but it did not go further from that _prototype_ stage. As far as I know, slideshow resource can only be made with Ricecooker, and that item in the QA channel is the only instance of a slideshow resource that exists on Studio.

## Steps to reproduce

1. Import the Kolibri QA Channel by using `nakav-mafak` token
2. Navigate to "Learn" -> "Library" -> "Kolibri QA Channel"
3. Go to "HTML5" sub-folder in the "Folders" tab in the side panel
4. Scroll down and click the "Slides Slides Slides!" resource card
5. See the slideshow resource page

## Context

 * Kolibri version: Kolibri 0.15.1.dev0+git.20220125194959
 * Operating system: Ubuntu 20.04.3 LTS
 * Browser: Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by MisRob** [comment]
Most likely related to #9042

**Comment by MisRob** [comment]
Regarding the "needs decisions" label, see this comment https://github.com/learningequality/kolibri/issues/9042#issuecomment-1021952515

**Comment by MisRob** [comment]
Lowering priority https://github.com/learningequality/kolibri/issues/9042#issuecomment-1022435536 and updating the expected behavior - we should show "Read" learning activity https://github.com/learningequality/kolibri/issues/9042#issuecomment-1022422745

**Comment by ykabusalah** [comment]
@MisRob Can I claim and address this issue?

**Comment by MisRob** [comment]
Hi @ykabusalah, I'm sorry for the late reply, I've just returned today after taking some time off. Yes, you're welcome to assign yourself and work on this issue.

**Comment by akila-i** [comment]
Hi @MisRob , I believe @ykabusalah is no longer working on this issue, If thats the case, can I address this issue?
It'd be great if you could assign me.

**Comment by MisRob** [comment]
Hi @Akila-I, yes this issue is not assigned. You're welcome to take it on, thank you

**Comment by akila-i** [comment]
I figured the followings when I try to reproduce the error.
1. "Slides Slides Slides!" resource is not in the HTML5 folder anymore. It is in the "Experiments" folder.
2. There is "Read" learning activity icon next to a resource title at the top bar
3. There is no Vue warning in the browser console
4. Also the observed behavior in #9042 is also not there anymore.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80597937/232978672-7a2fa2e6-f3ba-4aee-8929-7d607303e70b.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/80597937/232979043-392b4d7b-fe26-4cb6-90a5-7fad5daa5182.png">

  - Kolibri verison : Kolibri 0.16.0a12.dev0+git.173.gf4fd6e25
  - Kolibri QA Channel version : Version 112
  - Browser : Brave Browser Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (x86_64)
  - OS : MacOS Monterey 12.6.5

@MisRob  I believe with this we can close both this and #9042 issues isnt it?

**Comment by rtibbles** [comment]
It seems this has been resolved.
