### ISSUE TITLE
There is not enough space for the focus ring at the EPUB viewer toolbar

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9051]
## Observed behavior

When navigating an EPUB resource toolbar with the keyboard, the focus ring is clipped:

![focus-1](https://user-images.githubusercontent.com/13509191/151398487-4631df8d-7645-4372-ae42-4f979094e666.png)
![focus-2](https://user-images.githubusercontent.com/13509191/151398490-db64660a-0008-4467-a373-975309d46bff.png)

## Expected behavior

There is enough space for the whole focus ring in the toolbar

## User-facing consequences

Minor visual issue

## Steps to reproduce

1. Import *Kolibri QA Channel* by using `nakav-mafak` token
2. Go to _Library --> Kolibri QA Channel --> ePUB_ and select an EPUB resource
3. Navigate the EPUB toolbar controls with your keyboard

## Context

- Kolibri version: Kolibri 0.15.1.dev0+git.20220127085643
- Operating system: Ubuntu 20.04.3 LTS
- Browser: Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by ConConRob** [comment]
Hello, I'd like to take a crack at this.
 I've had a dig into this and it appears the icons are not centered vertically in the toolbar and the icons on the sides need some  horizontal positioning. The main issue with just putting in a couple px of padding is that there are popups that are positioned absolutely that expect these buttons to be positioned  at top: 0. 

I'm new to this code base so please let me know if you  think  centering the toolbar buttons and repositioning the pop up buttons sounds like a good enough solution?

Also note that one of the popups is already out of position. Considering I'll have to reposition this anyways, is it alright if I fix this also?
![image](https://user-images.githubusercontent.com/28680288/156706373-f6e1eaec-0b10-4571-bfe8-65890800db0f.png)

**Comment by MisRob** [comment]
Hello @ConConRob,

thank you for looking into this. Since you've already opened a PR, I think it'd make sense to check the code and discuss questions raised here in the PR. Thank you for your contribution :)

**Comment by MisRob** [comment]
Resolved in https://github.com/learningequality/kolibri/pull/9165
