### ISSUE TITLE
Previous/Next icon buttons are hard to notice on small screens when taking a quiz as a learner 

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9053]
## Observed behavior

Although Previous/Next icon buttons pass contrast checks, on one of my screens, I had difficulties noticing them when taking a quiz as a learner since they're pretty small and thin.

![340px](https://user-images.githubusercontent.com/13509191/151408107-a9e8d1d5-cfd0-43f0-974f-bdc6d6d86eb6.png)

(note that the issue with buttons being misaligned is already reported in #9052)

## Expected behavior

These buttons are important navigation elements so I'd expect them higher in the visual hierarchy.

## User-facing consequences

Difficulties with navigating a quiz

## Steps to reproduce

1. As a coach, create and start a quiz
2. As a learner, take the quiz for page width < 480px

## Context

- Kolibri version: Kolibri 0.15.1.dev0+git.20220127085643
- Operating system: Ubuntu 20.04.3 LTS
- Browser: Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by MisRob** [comment]
@jtamiace I think we could use buttons from [this design](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=3861%3A92031) to improve buttons visibility, is that right?


![Screenshot from 2022-01-27 18-18-49](https://user-images.githubusercontent.com/13509191/151410202-44be92dd-c3fa-4a64-b775-ebd0f497b571.png)

**Comment by radinamatic** [comment]
Yes X 💯 !!!

I love this suggestion, let's please implement! 🙏🏽

**Comment by jtamiace** [comment]
Yes! Let's go with this.
