### ISSUE TITLE
Wrong focus behavior in the main side navigation panel

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9069]
## Observed behavior

When I navigate the main side navigation with the TAB key, there are the following problems:

- The close button gets focused first
- As I circle between focusable elements over and over, the close button never gets focused again
- When I arrive to "Usage and privacy" link and press TAB, the focus ring disappears. I need to click TAB one more time to see the focus ring move to the following option.

![focus](https://user-images.githubusercontent.com/13509191/151787290-96aa6bd5-9509-4567-b923-14bf0d1ff8b9.gif)

## Expected behavior

Assuming that the main side navigation is open, the expected focus order is as follows as I'm pressing the TAB key:
"Learn" --> "Coach" --> "Facility" --> .... --> "Profile" --> "Sign out" --> "Usage and privacy" --> "Close button" --> "Learn" --> "Coach" --> ...

The focus ring never disappears when navigating through options.

## User-facing consequences

Difficulties with navigating one of the major elements of the application with keyboard

## Steps to reproduce

Navigate the main side navigation with your keyboard

## Context

- Kolibri 0.15.1.dev0+git.20220127215827
- Ubuntu 20.04.3 LTS
- Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by marcellamaki** [comment]
This seems to have been fixed with the recent patch release. Although the outline does not initially appear right on open, the focus is not lost during tab nav, and correctly cycles through the menu options, including all items, the usage and privacy link, and the close button
