### ISSUE TITLE
Android app designs

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#9071]
This project will be updated with more detail as the quarter goes on

## Background, documentation, resources
https://www.notion.so/learningequality/Scope-the-technical-and-design-foundations-to-publicly-release-a-great-first-time-experience-on-the--df8f88d17af743b098c4bf93f46c3a8e

## Figma 
https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=0%3A1

**Comment by rtibbles** [comment]
These have been completed.
