### ISSUE TITLE
Enhanced onboarding and device configuration

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#9072]
## User stories

Full list: https://www.notion.so/learningequality/Android-app-user-stories-4d1d27356de04d6095226903001bdcbb

### As an admin, I want to...

- Allow students to join the facility without losing their progress and data
- Automatically install all content associated with a learner’s account to their device
- Make sure the devices I’m setting up don’t use metered data

### As a learner, I want to...

- Learn how to use Kolibri and what’s possible
- Control how much mobile data Kolibri uses on my phone & tablet
- Reset my password

## Design goals

- Use clear, plain language to introduce value of Kolibri
- Help someone learn how to use Kolibri successfully on their own
- Settings - good defaults, context, offer choice to change
- Tutorials - empty states, CTAs 
- Consistent loading states
- “More native” experience on smallest screens

## Figma 
https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=0%3A1

**Comment by rtibbles** [comment]
This design work has been completed, and has been described in #9284
