### ISSUE TITLE
Uncaught errors in the content modal in a channel with custom navigation

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9074]
## Observed behavior

There is a Vue warning and uncaught errors in the browser console after opening the content modal in a channel with custom navigation:

![custom-content-modal](https://user-images.githubusercontent.com/13509191/151972657-a545f8f1-2d1e-4a12-80df-b48e60dbb370.png)

## Errors and logs

```
vue.runtime.esm.js:619 [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read properties of undefined (reading 'content_id')"

found in

---> <ContentItem> at kolibri/plugins/learn/assets/src/views/ChannelRenderer/ContentItem.vue
       <Backdrop> at kolibri/core/assets/src/views/Backdrop.vue
         <ContentModal> at kolibri/plugins/learn/assets/src/views/ChannelRenderer/ContentModal.vue
           <CustomContentRenderer> at kolibri/plugins/learn/assets/src/views/ChannelRenderer/CustomContentRenderer.vue
             <TopicsPage> at kolibri/plugins/learn/assets/src/views/TopicsPage.vue
               <CoreBase> at kolibri/core/assets/src/views/CoreBase/index.vue
                 <Root>
```

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of undefined (reading 'content_id')
    at VueComponent.cacheProgress (ContentItem.vue:167:1)
    at ContentItem.vue:154:1
```

Wait a couple of seconds to see:

```
ContentItem.vue:167 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'content_id')
    at VueComponent.cacheProgress (ContentItem.vue:167:1)
```

## Expected behavior

There are no Vue warnings and uncaught errors in the browser console.

## User-facing consequences

I haven't observed any user-facing problems in the channel and the modal.

## Steps to reproduce

1. Enable custom channel navigation in the _options.ini_ file (in the Kolibri home folder, typically _~/.kolibri_):

```
[Learn]
# Whether to enable custom channel navigation applications
ENABLE_CUSTOM_CHANNEL_NAV = True
```

2. Import a custom channel by using the `bovir-dubov` token to Kolibri
3. Navigate to *Learn* → *Library → Custom Nav Channel*
4. Click on *the Interlinking Content Test* link
5. See Vue warnings and uncaught errors in the browser console

## Context

- Kolibri 0.15.1.dev0+git.20220131152842
- Ubuntu 20.04.3 LTS
- Chrome 97.0.4692.99 (Official Build) (64-bit)

**Comment by himanshuc3** [comment]
@MisRob I am able to reproduce the error. I'll check what's the issue and see if it needs a stop-gap fix or otherwise.

**Comment by bjester** [comment]
@himanshuc3 Thank you for taking a look at it. I'll assign you the issue, but if at any point you're unable to complete it, please let us know!

**Comment by himanshuc3** [comment]
@bjester  Is there a quick way to clear cache of courses progress or do I have to kill the env and create another one?
I need it for debugging purpose since everytime I import, delete and again import a custom channel it seems to remember it.

**Comment by bjester** [comment]
> clear cache of courses progress

@himanshuc3 I'm not sure I understand your motivation for this. You shouldn't need to re-import the channel

**Comment by himanshuc3** [comment]
@bjester Got around the issue. Now the problem is `setContentNodeProgress`  is triggered and it requires `content_id` which is apparently not set. I am not sure how we generate a unique id for a custom channel or even if there is one generated?

**Comment by himanshuc3** [comment]
Another visual bug I found and I am not sure if this is also considered in here or reported as under another issue. Bug: When routing to library, and clicking on the custom channel, the header goes missing.
![Screenshot from 2024-03-15 19-42-21](https://github.com/learningequality/kolibri/assets/19166045/6fe50fa7-10bc-4b9b-8306-25f80dcc955d)

**Comment by bjester** [comment]
The `content_id` should be available on the `contentNode`. As for the other issue, it would be best to file a separate issue
