### ISSUE TITLE
Error when clicking on an exercise in the coach notifications feed when the user didn't generate any attempts

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#9088]
## Observed behavior

In the coach dashboard, I clicked on the purple text in this notification, but nothing happened:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/618416/153102509-b067a320-db11-4b98-9a3f-57d56bc918a5.png">

## Errors and logs

In the console, I got this traceback:
<img width="435" alt="image" src="https://user-images.githubusercontent.com/618416/153102552-659cd240-680d-4948-9c44-29366444961c.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/618416/153102627-3b4f84f8-47ff-4929-83d3-f33810d94e0b.png">

It looks as if the user didn't actually have any AttemptLogs for that exercise, and progress was still at 0.

## Expected behavior

I would expect that either:
- The user could still be taken somewhere meaningful when clicking on that link, OR
- The notification text shouldn't be a link, if it's not actionable

## Context

Kolibri 0.15.1b0

**Comment by aditi428** [comment]
How can I get help to solve this bug

**Comment by nucleogenesis** [comment]
@akolson and I made some progress on this but were not able to replicate it without artificially forcing the app to think there are no attempt logs.

We cannot get the notification to pop up at all without actually interacting with the lesson exercise.

In any case, we will return to this next week to wrap it up by trying to add a condition that will not link to a broken Report page.

**Comment by rtibbles** [comment]
Fixed in #9682
