### ISSUE TITLE
current state of github 'releases' page is hard to scan

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#9104]
## Observed behavior

Hi folks, hope you're all well!

I'd gone to look for the most recent releases and what's changed, and found the page a bit hard to use:

* there are many alpha and beta pre-releases shown which are no longer relevant, and make it hard to find "what's latest?"
* the release notes are not in sync with what's in the [changelog](https://github.com/learningequality/kolibri/blob/release-v0.15.x/CHANGELOG.md)

## Recommendations

* delete old pre-releases to remove clutter
* keep the release notes in sync with the changelog

## User-facing consequences

Harder to find the latest stable releases and know what's changed in them

## Steps to reproduce

see https://github.com/learningequality/kolibri/releases

## Additional thoughts

I believe the high-level summaries are more useful than the lists of PRs. However I completely understand that these are time-consuming to maintain and the audience is relatively small.

**Comment by rtibbles** [comment]
Should be cleaned up now!

**Comment by indirectlylit** [comment]
thanks looks cleaner!
