### ISSUE TITLE
missing padding on channel import screen

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#9105]
## Observed behavior

The 'select resources' buttons touch the adjacent text at medium screen sizes:

> ![image](https://user-images.githubusercontent.com/2367265/153918934-aec6fa3c-41c3-42d0-8ffc-308833f89bdb.png)

## Expected behavior

padding should probably be equal to the space between the thumbnail and text

## User-facing consequences

slightly harder to read text

## Steps to reproduce

http://localhost:8080/en/device/#/content/channels

## Context

0.15.0

**Comment by amitpanwar789** [comment]
Can i work on this issue ?
