### ISSUE TITLE
Answer history section for a practice quiz is not displayed correctly

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#9116]
## Observed behavior
[Reported by @pcenov](https://learningequality.slack.com/archives/C02JTHE8EV9/p1644857494478009?thread_ts=1643744227.404699&cid=C02JTHE8EV9) while doing the critical workflows testing on the [EXE and DEB assets](https://buildkite.com/learningequality/kolibri-python-package/builds/4892) from #9078 (0.16.x branch).

![2022-02-14_18-34-04](https://user-images.githubusercontent.com/1457929/154107831-6dc01b17-4589-4a2e-8865-55bcd8f3821a.png)

## Errors and logs
…

## Expected behavior
...

## User-facing consequences
…

## Steps to reproduce
Make several attempts on a practice quiz and try to review past answers.

## Context
* Kolibri version: asset from #9078 (0.16.x branch)
 * Operating system: Windows & Linux
 * Browser: Chrome

**Comment by rtibbles** [comment]
Fixed in #9122
