### ISSUE TITLE
Create new quiz - Misaligned 'Previous step' and 'Finish' buttons

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9118]
## Observed behavior
The 'Previous step' and 'Finish' buttons are slightly misaligned in Chrome and Firefox browsers and much more so in IE11

## Steps to reproduce the issue
1. Install the latest [0.15.1 build](https://github.com/learningequality/kolibri/releases/tag/v0.15.1-beta1)
2. As a Coach go to Class>Plan>Quizzes
3. Click the 'New quiz' > 'Create new quiz' option
4. Enter a quiz title, select resources and click 'Continue'
5. Observe the position of the 'Previous step' button

## Screenshots
| Issue | Screenshot |
:-------------------------:|:-------------------------:
| Chrome, Firefox |![2022-02-16_16-58-33](https://user-images.githubusercontent.com/79847249/154295195-1dad7eba-7be7-42d1-8f72-4ac09480d655.png)|
| IE 11 |![2022-02-16_17-10-30](https://user-images.githubusercontent.com/79847249/154295199-2556601a-eb4b-4a9d-b5a8-bcddfdce122d.png)|

## Usage Details
Windows 10 - Chrome, Firefox, IE11, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/9881

**Comment by bjester** [comment]
This is still extant as of 0.16.1rc3

**Comment by rtibbles** [comment]
These buttons have been removed in 0.17 so closing this as resolved!
