### ISSUE TITLE
exercise buttons are broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#912]
in current develop branch

![image](https://cloud.githubusercontent.com/assets/2367265/23003529/308145b8-f3a6-11e6-83c3-8422fc89da88.png)

**Comment by rtibbles** [comment]
Might need an update of the perseus renderer.

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/commit/90ca5c7a1f4ea8b9a6862c24e8335bfccfbe0e24
