### ISSUE TITLE
Delayed appearance of completion icon on Lesson

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#9121]
## Observed behavior
Identified on the demo site: After completing the resources in a Lesson, the completion icon did not appear on the "Home" page until 10 or so minutes later. However, clicking into the Lesson showed a completion icon on each of the resources.

…
## Context

Tell us about your environment, including:
 * Kolibri version: 0.15.1b0.dev0+git.43.ge0d85dac
 * Operating system: Kolibri Demo site
 * Browser: Chrome

…

**Comment by pcenov** [comment]
@radinamatic I am not able to replicate the issue with the official 0.15.6 build. The competition icon is displayed immediately after finishing a lesson:
![2022-08-01_14-02-13](https://user-images.githubusercontent.com/79847249/182135112-bdbcb4a2-67b9-4dd7-9539-69325fe0e41f.png)

**Comment by rtibbles** [comment]
Super, let's close this - can reopen if it gets reported again.
