### ISSUE TITLE
Misaligned Previous and Next button in Practice quizzes and Surveys

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9123]
## Observed behavior
This issue is similar to https://github.com/learningequality/kolibri/pull/9085 which was fixed by @MisRob but in this case applies to Practice quizzes and Surveys

## Expected behavior
Same as https://github.com/learningequality/kolibri/pull/9085

## Steps to reproduce the issue
1. Install the following [0.16 build](https://buildkite.com/learningequality/kolibri-debian/builds/3799)
2. Import the QA Channel and as a Coach assign a Survey and a Practice quiz to a Learner
3. Sign in as a Learner using a mobile device and attempt to complete the Survey and/or Practice quiz

## Screenshots
![2022-02-17_15-56-55](https://user-images.githubusercontent.com/79847249/154498760-bfbebd55-c9fc-4b39-b203-d2bfef9c610c.png)

## Usage Details
Windows 10 - Chrome, Firefox, IE11, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@marcellamaki @sairina I'd say this has higher impact, not just visually, but again - not a blocker or regression. 
Would it be possible to apply the same fix as @MisRob previously?
