### ISSUE TITLE
Lesson - Incorrectly positioned resource type labels in Greek

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9124]
## Observed behavior
See the attached screenshots. Note that I am able to replicate this every time I switch to Greek or Bulgarian while it's hardly noticeable in the other supported languages. Valid in both desktop and mobile view.

## Expected behavior
Correctly positioned labels.

## Steps to reproduce the issue
1. Install the following [0.16 build](https://buildkite.com/learningequality/kolibri-debian/builds/3799)
2. Import the QA Channel and as a Coach assign a Lesson with resources to a Learner
3. Sign in as a Learner change the language to Greek and go to Classes>Lesson
4. Observe the position of the resource type labels

## Screenshots
| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Desktop | ![2022-02-17_10-04-22](https://user-images.githubusercontent.com/79847249/154500744-4ab28d0f-10c9-4f8e-92a7-92b26ed7d352.png)| 
| Mobile| ![2022-02-17_16-22-45](https://user-images.githubusercontent.com/79847249/154501828-588850c5-dcc4-48e9-8d37-17f4e3eb1f9a.png)| 

## Usage Details
Windows 10 - Chrome, Firefox, IE11, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@marcellamaki @sairina Visually this looks unappealing, but it's not a blocker. 
If fixing it requires more time, feel free to retarget to a future patch.
