### ISSUE TITLE
Regression - Switching to a RTL language breaks the entire UI

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9131]
## Observed behavior
Switching to a RTL language breaks the entire UI in all supported browsers. This issue is probably a result of the changes made in https://github.com/learningequality/kolibri/pull/9014

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5005
2. Change the language to Arabic, Farsi or Urdu

## Screenshots
![2022-02-22_15-10-22](https://user-images.githubusercontent.com/79847249/155139446-94126613-bd44-4d29-9f9e-ad740346031a.png)

## Usage Details
Windows 10 - Chrome, Firefox, IE11, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@pcenov also tested the asset from the PR that was merged immediately before the https://github.com/learningequality/kolibri/pull/9014, and there were no issues with the UI in RTL languages.

**Comment by rtibbles** [comment]
Sigh... I did test this, but apparently something else went awry.
