### ISSUE TITLE
Regression - Kolibri won't start in IE11

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9132]
## Observed behavior
When I attempt to launch Kolibri in a real IE11 browser I  see a bunch of errors in the console and Kolibri won't start. Again, this seems caused by the changes made in https://github.com/learningequality/kolibri/pull/9014

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5005
2. Attempt to load Kolibri using an IE11 browser.

## Screenshots
![2022-02-22_17-17-10](https://user-images.githubusercontent.com/79847249/155163335-dbc32f6d-4474-4f8a-849f-085cef2fff06.png)
## Logs
[logs.zip](https://github.com/learningequality/kolibri/files/8117980/logs.zip)

## Usage Details
Windows 10, IE11

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
I was also able to replicate this on IE11 on Windows 10, [with this build](https://buildkite.com/learningequality/kolibri-windows/builds/3211). 
Probably connected to changes that are also causing #9131. 

![Win10 (start)  Running  - Oracle VM VirtualBox_001](https://user-images.githubusercontent.com/1457929/155351161-1ec1c9f6-2d6f-45be-87a4-fd8140d36346.png)
