### ISSUE TITLE
Kolibri Logs Are Always Classified as ERROR in Google Cloud Logging

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#9162]
## Observed behavior

[Discussed on Slack.
](https://learningequality.slack.com/archives/C02AW6J5ZNC/p1641952761041900?thread_ts=1641657482.030500&cid=C02AW6J5ZNC)
The [GCloud Logging docs indicate](https://cloud.google.com/stackdriver/docs/solutions/gke/managing-logs#best_practices
) that this is happening because the application write to STDERR instead of STDOUT:

> Severities: By default, logs written to the standard output are on the INFO level and logs written to the standard error are on the ERROR level.

Some maybe-helpful notes from that chat:
@rtibbles:
Hrm not seeing a prima facie reason why it would be going to stderr not stdout, our console handler is following the example here https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
Oh, except we don't specify the stream. Can try tweaking it for 0.15.1
I think, looking at the way that the Python StreamHandler class works, it sends everything to the same stream, but I'll double check.
We might need to define separate handlers in order to split the streams

## Expected behavior

That we have INFO and ERROR distinctions, at the very least.

## User-facing consequences

Makes debugging cloud instances more of a sift than a hunt. 

## Context

Run in Ubuntu LTS 18 containers on the containerd runtime inside Kubernetes.

**Comment by rtibbles** [comment]
Yes, the stream defaults to stderr. We would need to have two different console handlers, one that outputs to stdout, one to stderr.

**Comment by socketbox** [comment]
This is incredibly annoying because it produces logs in GCP Log Explorer that look like this (minus the pixelation):

![image](https://user-images.githubusercontent.com/1593835/157296071-51fc760e-c546-4ed3-b845-e59605ae247e.png)


These are responses to simple `/status/` calls that result in an HTTP 200, yet they're flagged as errors in the UI because they come over `stderr` and not `stdout`.

**Comment by rtibbles** [comment]
Fixed in #9240
