### ISSUE TITLE
Focus is still in main content when folder resources panel opens in an exercise in Learn

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#9178]
## Observed behavior
Focus ring does not immediate jump to the side panel (`FullScreenSidePanel`) when the side panel is opened by keyboard navigation.
![2022-03-14 08 50 39](https://user-images.githubusercontent.com/13563002/158210204-b0056c77-20eb-402e-85d0-7adeaf5ca6da.gif)

## Errors and logs
None

## Expected behavior
Whenever a side panel opens by keyboard navigation, the focus should immediately be directed to that side panel, and not remain with the main content.

## User-facing consequences
Confusing for users who are navigating with keyboard.

## Steps to reproduce
1. Sign in as Learner
2. Open an exercise
3. Use the keyboard to navigate to the first icon the right-hand side (the one furthest to the left), called "View folder resources"
4. Notice that when you click `Enter`, and use `Tab` to navigate, the focus remains on the main content

## Context
Kolibri 0.15
MacOS
Chrome

…

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/9408
