### ISSUE TITLE
When there is more content in an exercise's folder resources, there is a console error for a missing prop

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#9179]
## Observed behavior
When in an exercise and if I click on the "View folder resources" icon, if there are resources, there is an error for the `nextContent` prop.

## Errors and logs
![Screen Shot 2022-03-14 at 9 27 08 AM](https://user-images.githubusercontent.com/13563002/158217009-e7377568-82be-4d7b-9ac1-c129473ac4d5.png)

## Expected behavior
No errors in console

## User-facing consequences
Doesn't seem to have any user-specific consequences outside of the console.

## Steps to reproduce
1. Login as a learner
2. Click on an exercise/pdf/etc. that has additional resources (e.g. "pH Scale: Basics")
3. Click on the "view resources" icon (icon furthest left on the right-hand side)
4. Note the prop error

## Context
Kolibri 0.15
MacOS
Chrome

**Comment by marcellamaki** [comment]
This also need to be confirmed as still reproducible, but I think could easily be done without the QA team by a dev who takes on the issue
