### ISSUE TITLE
Focus ring around "Check" button in exercises is cut off on left side

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#9181]
## Observed behavior
Focus ring is cut off:
<img width="1210" alt="Screen Shot 2022-03-11 at 3 59 51 PM" src="https://user-images.githubusercontent.com/13563002/158239940-6bc9fa2a-e2ad-4920-8af1-7d5d03ad8568.png">

## Errors and logs
None

## Expected behavior
Focus ring should not be cut off

## User-facing consequences
Stylistic issue

## Steps to reproduce
1. Login as learner
2. Go to an exercise
3. Use the keyboard to navigate to the "Check" button at the bottom

## Context
Kolibri 0.15
MacOS
Chrome

**Comment by rtibbles** [comment]
Fixed in #9478
