### ISSUE TITLE
VF Installer - The phone number validation message is initially not being displayed

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9201]
## Observed behavior
When creating a new account the phone number validation message is initially not being displayed and the user has to click the 'Finish' button again in order to see it.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Go to the 'Create an account' page.
3. Fill in all required fields and use a phone number which is already used by another account.
4. Click the 'Finish' button.

## Expected result
The validation message should be displayed immediately

## Screenshots
| Issue | Screenshot |
:-------------------------:|:-------------------------:
| Initial Result |![2022-03-16_18-23-46](https://user-images.githubusercontent.com/79847249/158641407-4688d93b-0cc3-4718-8321-4bec98fe86ec.png)|
| Subsequent click on Finish |![2022-03-16_18-24-26](https://user-images.githubusercontent.com/79847249/158641523-3bc5dcad-7e3b-4fbb-b3c2-8f8c802b93d1.png)|

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by rskbansal** [comment]
I think I can give this a try, will get you updated soon

**Comment by radinamatic** [comment]
Thank you @pcenov 👍🏽 

cc @nucleogenesis

**Comment by rtibbles** [comment]
Hi @rskbansal - sorry this issue is specifically about a custom build of Kolibri, so not something you could take on! We'll try to keep these issues out of the open tracker in the future!

**Comment by pcenov** [comment]
Tested and verified as fixed in the latest build - the validation for existing phone number is displayed correctly now.
@radinamatic
