### ISSUE TITLE
VF installer - Modal window buttons are glued together

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9202]
## Observed behavior
See the attached screenshots

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Observe the buttons in any of the modal windows.

## Expected result
Correctly positioned buttons with enough space between them

## Screenshots
| Issue | Screenshot |
:-------------------------:|:-------------------------:
| Reset Password |![2022-03-16_17-18-44](https://user-images.githubusercontent.com/79847249/158642995-1f5b309a-b286-4ef1-b8fd-acd816674cca.png)|
| New Profile |![2022-03-16_17-23-05](https://user-images.githubusercontent.com/79847249/158643017-0dab7525-6de7-4808-8adc-291302785f2e.png)|

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
Verified as fixed in the latest build. @radinamatic

**Comment by pcenov** [comment]
After some additional testing - this issue is still valid for the Reset password form which is accessible from the sign-in page:
![2022-05-09_11-56-56](https://user-images.githubusercontent.com/79847249/167376364-7bc8f617-9772-4cc0-b6cf-4e421feb93b0.png)
@nucleogenesis

**Comment by nucleogenesis** [comment]
This issue has been resolved here: https://github.com/learningequality/kolibri-instant-schools-plugin/pull/180
