### ISSUE TITLE
VF - Cannot navigate to the 'Account' page

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9203]
## Observed behavior
The 'Account' link appears to be broken and clicking it results only in page reload.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Open the sidebar and click the Account option. Alternatively open the profile menu and again click the Account option.

## Expected result
The user is able to see the contents of the Account page

## Video
https://user-images.githubusercontent.com/79847249/158645827-b78ca8ff-8d98-42b1-b22a-5249f9b72e49.mp4

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by radinamatic** [comment]
Thank you @pcenov!

cc @nucleogenesis

**Comment by pcenov** [comment]
The Account link is completely removed in the latest build - @nucleogenesis is this fixing the reported issue?

**Comment by nucleogenesis** [comment]
@pcenov the account button is now called "profile" after the latest update to make it in line with the latest Kolibri
