### ISSUE TITLE
Kolibri VF - Cannot import and see exercises

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9204]
## Observed behavior
When as an admin I attempt to import a channel containing exercises such as Khan Academy I don't see the exercises and cannot import them.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Sign in as an Admin an go to Channels>Import
3. Select a source e.g. Kolibri Studio (online) and proceed with selecting a source for import

## Expected result
An Admin should be able to import exercises

## Screenshot
![2022-03-17_15-35-15](https://user-images.githubusercontent.com/79847249/158820156-b9fa3453-8795-4e36-bdbe-e98ec4506d17.png)

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by nucleogenesis** [comment]
I have not been able to replicate this issue - perhaps there was some other cause?

**Comment by rtibbles** [comment]
I assume this has been resolved? Closing.
