### ISSUE TITLE
Kolibri VF - Getting constantly signed out of .kolibri when using the Server URL

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9205]
## Observed behavior
If I am accessing Kolibri through the Server URL as provided in Device>Info I am getting signed out immediately after I select a Profile.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Sign in as an Admin an go to Device>Info to see the Server URL.
3. Load the Server URL in an external device and sign in as a Learner.
4. Choose a Profile.

## Expected result
The user should remain signed in.

## Video
https://user-images.githubusercontent.com/79847249/158826851-733fba80-282a-4f3d-b895-b29aaf92bec0.mp4

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by nucleogenesis** [comment]
@rtibbles - can you think of why this would be the case? You just cannot log in when accessing over the server URL, but it works fine on localhost

**Comment by rtibbles** [comment]
If you've initially signed in via localhost, the session cookie is on the localhost origin, not the server origin, so you are not signed in as far as Kolibri is concerned.

**Comment by nucleogenesis** [comment]
That was what I thought at first - but I cleared my application data and just tried logging in on my 192.168.*.* IP and it won't log me in - whenever it finishes hitting the session endpoint, it just redirects me back to auth :-/

**Comment by nucleogenesis** [comment]
I've dug into this and somewhere around the Middleware there is never a user set, so by the time it hits the redirect view, it has no user.

Why this only happens on the network IP addresses is beyond me, but I tracked it down until it went into the guts of Django where I prodded a bit but in the end I think that, realistically, this isn't worth much more time unless it would complicate some aspect of proxying on BCK - which given the test servers already spun up by @socketbox doesn't seem to be the case - but perhaps I'm wrong there.

I'll move along and let this be for a bit unless it becomes a problem for our use case as it is an issue that seems only to apply to the Instant Schools plugin

**Comment by nucleogenesis** [comment]
I'm going to close this as a `wontfix` for now as it is specific to the VF IS configuartion but doesn't impact the intended use of the software
