### ISSUE TITLE
Kolibri VF - Missing icons for the About and Account menu items

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9207]
## Observed behavior
See the attached screenshot.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-vf/builds/347).
2. Sign in as a Learner and open the sidebar or the user menu.

## Expected result
All menu items should have icons

## Screenshot
![ddf](https://user-images.githubusercontent.com/79847249/158839296-47d2219f-e51a-49d4-a9de-d4d06e4ff9bc.png)

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by ratika-12** [comment]
Can I work on this issue? @nucleogenesis @pcenov ? I am new to this project and looking to start contributing :)

**Comment by radinamatic** [comment]
Hi @ratika-12, this issue is specifically about a custom build of Kolibri, and it's something we'll take on internally.

You can check out other [beginner-friendly](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+beginner+friendly%22) issues on GitHub.

**Comment by pcenov** [comment]
Verified as fixed: 
![2022-05-09_11-21-42](https://user-images.githubusercontent.com/79847249/167370120-6e7fb3bb-78f0-4578-89a9-9ed3d97e4630.png)
