### ISSUE TITLE
Impossible to run jest tests on kolibri plugins

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#9214]
## Observed behavior
Trying to test a Vue component in a Kolibri plugin (KDP) it has become impossible with the current npm packaging of both `kolibri` and `kolibri-tools`.
Some of the core components used by the tested component are not found. Specifically `KSelect` is missing.

## Errors and logs
```
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Unknown custom element: <KSelect> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

## Expected behavior
Running 
`kolibri-tools test --config ./jest.conf.js`
should make jest be able to find Kolibri core components

## User-facing consequences
No way to run frontend tests on Kolibri plugins

## Hack to make it work
In the `node_modules` directory:
1. Edited [kolibri-tools setup.js file](https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-tools/jest.conf/setup.js#L16) to remove the first `../` in the path
2. Manually copied the [KSelect source code](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/KSelect/) directory to `node_modules/kolibri/core/assets/src/views/`

With these two modifications and a simple jest.conf.js file:
```
const baseConfig = require('kolibri-tools/jest.conf');
module.exports = Object.assign(baseConfig, {
  // Make sure we transpile any raw vue or ES6 files
  transformIgnorePatterns: [
    '/node_modules/(?!(keen-ui|epubjs|kolibri-tools|kolibri|kolibri-design-system)/).*/',
  ],
  collectCoverageFrom: [
    'kolibri_data_portal/**/assets/src/**/*.{js,vue}',
    '!**/node_modules/**',
  ],
});
```
`kolibri-tools test --config ./jest.conf.js` runs fine frontend tests

However, 
`kolibri-tools test --config ./jest.conf.js --watch `does not work. It can't find `CoreBase`:
```
 ● Test suite failed to run

    Configuration error:
    
    Could not locate module kolibri.coreVue.components.CoreBase mapped as:
    kolibri/coreVue/components/CoreBase.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/^kolibri.coreVue.components.CoreBase$/": "kolibri/coreVue/components/CoreBase"
      },
      "resolver": null
    }

      at createNoMappedModuleFoundError (node_modules/jest-resolve/build/index.js:501:17)
          at Array.reduce (<anonymous>)
      at SearchSource.findRelatedTests (node_modules/@jest/core/build/SearchSource.js:280:30)
      at SearchSource.findTestRelatedToChangedFiles (node_modules/@jest/core/build/SearchSource.js:363:14)

```

**Comment by nucleogenesis** [comment]
This looks like it was related to some of the CoreBase refactor - seems like this is probably okay to close now?

**Comment by rtibbles** [comment]
Should have been fixed by moving KSelect into KDS.
