### ISSUE TITLE
ImportError on running migrate while using Python 3.10.0

### ISSUE THREAD

**Issue by nitheezkant** [learningequality/kolibri#9224]
## Observed behavior

On running  `kolibri manage migrate` command while using Python version 3.10.0, ImportError is observed.
Complete screenshot of Terminal is attached:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/85250569/160286893-58f1e248-a0e8-4d07-b60e-d5ee0db87edb.png">

## Errors and logs

```
ImportError: cannot import name 'Iterator' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

## Expected behavior

Migration is successful when lower versions of python is used.

## Steps to reproduce

Make sure you are using Python 3.10.0 inside the virtual environment and then run `kolibri manage migrate`.

## Context

OS:macOS, M1

**Comment by rtibbles** [comment]
Kolibri does not support Python 3.10.0 or later, and cannot until we drop Python 2.7 support and upgrade our Django version.

However, this could be better specified in our setup.py with a `python_requires` kwarg.
