### ISSUE TITLE
SCORM not working

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9226]
## Observed behavior
From 15.2-a0 bug bash 

Tested with the PEX file. Imported from our QA-Testing channel, none of the three samples work, they all show this kind of error http://localhost:37765/zipcontent/cee209b7b03a1da1858343f5c0bdf6cf.zip/index.html 404 Not found

https://www.notion.so/learningequality/HTML5-SCORM-materials-don-t-work-2cda79443ff14b6dac0484fd0358355b

## Expected behavior
SCORM materials should work

## Steps to reproduce
 
On 15.x, navigate to the Kolibri QA channel and access any SCORM materials under HTML5

## Context

 * Kolibri version: 15.x
 * Operating system: Linux (Marcella also reproduced on MacOS)
 * Browser: Chrome, Firefox

**Comment by radinamatic** [comment]
Kolibri QA channel has been updated and SCORM resources removed for now, closing!
