### ISSUE TITLE
Scrolling on Library and Topics page does not work on Firefox

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9227]
## Observed behavior
From bug bash 

Scrolling the page down does not work on Library Page or Topics Page with mouse or keyboard in Firefox

https://www.notion.so/learningequality/Scrolling-the-page-down-does-not-work-on-Library-Page-or-Topics-Page-with-mouse-or-keyboard-in-Firef-f56d2d2e94294d4d8d07ecd98fa607b3

## Context
 * Kolibri version 15.x
 * Operating system MacOS
 * Browser Firefox

**Comment by nucleogenesis** [comment]
@sairina I've tested this on Firefox 88 and 98 on Linux, using scroll wheel, arrow keys and my laptop's trackpad and I can scroll without issue. Would you mind testing this through again on 0.15 to see if it remains on your end?

**Comment by sairina** [comment]
It seems to be working! Thank you for testing this again. Not sure why it wasn't working before? 😌
