### ISSUE TITLE
Add additional metadata strings for "what learners need" and make available in search and filter

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9245]
There are missing strings associated with the following constants in “What resources learners need” in le-utils: 

PEERS
PRIOR_KNOWLEDGE
SPECIAL_SOFTWARE
TEACHER
OTHER_SUPPLIES

These will be used in the studio edit modal work, and in order for this data to be displayable in Kolibri, the strings will need to be added, and we will have to confirm that once they are added, that the metadata will display in the appropriate places in the search/filter options. Users should be able to see these additional selections, and searching/filtering by them should work, once the metadata is in place.

**Comment by rtibbles** [comment]
Note that I am not entirely sure that we need a user facing string for `prior knowledge` as 'for beginners' is the user displayed label within that category.

**Comment by radinamatic** [comment]
I think that was one of the reasons why we decided to refactor these categories in the user-facing search UI: it made no sense for the learner to **search** for resources that would require ``prior knowledge`` or ``other software`` (which software...? 🤔).

These make more sense on Studio from the content curator point of view, correct?

**Comment by marcellamaki** [comment]
Hmm -- that definitely does make sense to me @radinamatic. It seems not useful, and possibly confusing, for learners.

Would there be case where a _coach_ might be using those things to search? Although, maybe more to _not_ choose a particular resource than to pick it? i.e. "I don't want to add a resource to a lesson that requires X which we don't have. And in that case... would the coach do it from the library? (I'm honestly not sure... I know the actually adding resources to a lesson flow is not like this, but trying to think of how that kind of browsing possible content to add to a lesson might happen)
