### ISSUE TITLE
wrong average score in the coach reports after the first learner of a quiz submits it

### ISSUE THREAD

**Issue by abdelrahman725** [learningequality/kolibri#9255]
## Observed behavior

when the first quiz taker submits a quiz , the quiz score showing to the quiz taker (learner) after quiz submission is correct  but the initial average score (reports view in coach account) of that quiz for the whole class is Wrong .

### what i exactly  did is the following :  

- created a quiz from the coach account with 5 quesions
- (in another session eg.Incognito mode ) took that quiz  as a learner and answered all the 5 questions correct
- ( learner account ) the result score for that quiz is 100% (5/5) as expected 
- (coach account ) without reloading the page, the average score for that quiz in the coach reports is 20% ! whic is wrong  but  refreshing  the page it shows 100% as expected .

### what does that mean ?
It means an important thing (to lead the person working on this issue in the right direction)
The quiz answers  got saved in the database normally and  correctly as expected that's why when you refresh the page you see the expected average score , so i think it has something to do with the notifications pushed to the coach.

### related files 
/kolibri/core/notifications/api.py  line 553
examine (quiz_completed_notification) function 

## Expected behavior

coah should sees correct average score (initially the same as the score showed to the learner) after the first learner who took the quiz  submits the quiz

## Steps to reproduce

1. login as a coach, make a quiz and start it (try a simple one where you can answer correctly)
2. from another window (Incognito mode) login as a learner , take this quiz
3. answer the questions and then submit
4. look at  the other window (logged in as a coach) without refreshing the page
5. observe the expected avg score for that quiz  in the reports view (again without loading the page)   

### noticed the same issue on both environments :
 
Production evironment)( following  kolibri user guide )
Kolibri 0.15.1
Windows 10
Chrome 99.0.4844.74
___________________
Developemnt environment (following Kolibri developer documentation )
Kolibri 0.16.0a4.dev0+git.88.g98506819
Ubuntu 20.04
Chrome 100.0.4896.60

**Comment by radinamatic** [comment]
I can replicate this with 0.15.6 on Ubuntu 18.04:

![quiz-0 15 6](https://user-images.githubusercontent.com/1457929/181648176-06461f5a-8f46-45db-8d06-b41abcf6ad4a.gif)

**Comment by abdelrahman725** [comment]
so this behaviour is not related to the environment used.

also i referenced a function above that me be relevant

**Comment by rtibbles** [comment]
Fixed in #9721 - thanks for the report @abdelrahman725 !
