### ISSUE TITLE
Update layout and spacing of nav elements on browser App Bar

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9274]
This issue is part of the app bar refresh work. The scope of this issue is just updating the spacing and alignment of existing items on a browser view.

### Scope
- [ ]  Update the between-element spacing for navigation and display elements on the app bar
- [ ]  Conditionally displaying the number of points, based on screen size
- [ ]  Spacing on smaller screens, where links drop below the main heading

#### Out of scope 
- Implementing the overflow menu
- Updating the points icon and updating from tooltip to button on small screens
- Removing the profile dropdown menu

### Specs 
**For large screens** (as defined by `responsiveWindowMixin`)
![Screen Shot 2022-04-11 at 9.29.52 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/2303aaae-109d-4ba0-b5c8-06659c9177dd)

**For medium and small screens** (as defined by `responsiveWindowMixin`)
![Screen Shot 2022-04-11 at 9.32.51 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/451acf51-3e6f-4841-8817-25a51606902e)

**Between-element spacing**
![Screen Shot 2022-04-11 at 9.30.19 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/f13347c4-9572-4a58-b634-9a15eb812906)

### Acceptance Criteria
- [ ] Layout should be pixel-perfect match to Figma specifications 
- [ ] Main menu should continue to be tab-navigable and tab order should be persisted
- [ ] Update any tests in `app-bar.spec.js` as needed based on your changes

**Comment by arishmaurya** [comment]
@marcellamaki please assign this issue to me i want to work on it

**Comment by marcellamaki** [comment]
Hi @arishmaurya -- why don't you go ahead and get started on the other issue that you requested to contribute on. If you finish that and this hasn't been assigned to a member of our team by then, I will assign you. Thanks again for your interest in Kolibri!
