### ISSUE TITLE
Turn points icon into an button on small breakpoints

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9277]
This change improves the accessibility and functionality of the points display, by using a button rather than a tooltip.

### Scope
- [ ]  On small screens, as defined by `responsiveWindowMixin`, points should not be displayed
- [ ]  The existing tooltip feature for this use case should be removed, replaced with a button and popover. The string can be reused.
- [ ]  Username truncation should remain in its current version

#### Out of scope
- Adding the new icon to KDS to be available for KIconButton. Instead, use any placeholder icon.

### Specs
![Screen Shot 2022-04-11 at 9.50.39 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/c7f62470-ad3d-461e-8023-b5d8c5f840bf)

### Acceptance Criteria
- [ ]  Button should be keyboard navigable: accessed through tab order. When in focus, it should open the popover on `Enter` and close it on `Esc`
- [ ]  Tests should be added to `app-bar.spec.js` for conditions of when points are displayed, when the icon is a button, and the opening of the popover.

**Comment by arishmaurya** [comment]
hey, @marcellamaki i want to work on this issue I have done a personal project similar where button issue was quite similar so can you assign it to me and what will be your suggestions i'm new contributor in this organization

**Comment by marcellamaki** [comment]
Hi @arishmaurya -- thank you for your interest in contributing to Kolibri! 

Get started by reading the [developer documentation for Kolibri](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html) and for the [Kolibri Design System](https://kolibri-design-system.netlify.app/). Make sure you read [the section about internationalizing strings](https://kolibri-dev.readthedocs.io/en/develop/i18n.html?highlight=strings#) since you with be reusing some text in this issue.

Once you get Kolibri running in your dev environment, use the components from the design system where possible, for example, use [`<KIconButton />`](https://kolibri-design-system.netlify.app/kiconbutton/) rather than the HTML `<button>` tag.

Use the checklist items to ensure that your work matches the scope of the issue and the acceptance criteria. If you have clarifying questions, you can ask in a comment on this issue.

**Comment by arishmaurya** [comment]
@marcellamaki mam i'm having problem with installation of virtual environment of python 

pipenv : The term 'pipenv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling 
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pipenv --python 3
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (pipenv:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

I'm following developer docs line by line i have installed pipenv(https://pipenv.pypa.io/en/latest/install/#installing-pipenv) but don't know why i'm getting this error please help me

**Comment by marcellamaki** [comment]
Hi @arishmaurya -- what operating system are you using?

**Comment by arishmaurya** [comment]
windows

**Comment by marcellamaki** [comment]
Hi @arishmaurya 

As noted in the getting started section of the developer docs, unfortunately our [dev docs are not written to support developing on Windows](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#prerequisites), and you might run into some challenges. 

I would suggest either using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) or [VirtualBox with Ubuntu](https://ubuntu.com/tutorials/how-to-run-ubuntu-desktop-on-a-virtual-machine-using-virtualbox#1-overview), as related to your question in the gsoc channel. Once you have decided which option you prefer, you should be able to set up the project, and you should not have to use docker to do so.

**Comment by arishmaurya** [comment]
/home/rahul/Pictures/Screenshot from 2022-05-08 18-12-28.png

mam I tried <KIconButton> to make this icon a button but when i'm doing this the leaf icon disappers and then i tried <button> it is now navigable by tab bar but it is not showing points on clicking by keyboard can you help me and the screenshot that i'm sharing with you it is current situation of icon button

**Comment by arishmaurya** [comment]
![Screenshot from 2022-05-08 18-12-28](https://user-images.githubusercontent.com/75907342/167296864-80839cac-2d61-4d85-b401-2091346edb23.png)


mam I tried to make this icon a button but when i'm doing this the leaf icon disappers and then i tried it is now navigable by tab bar but it is not showing points on clicking by keyboard can you help me and the screenshot that i'm sharing with you it is current situation of icon button

**Comment by arishmaurya** [comment]
![Screenshot from 2022-05-08 18-12-28](https://user-images.githubusercontent.com/75907342/167296941-d6fccc3c-9254-45aa-9015-782eb6b6cc5e.png)

 I made this  icon a button using <button> tag because when i'm using <KIconButton> tag  the leaf icon disappers  now this button is  navigable by tab bar but it is not showing points on clicking by keyboard can you help me and the screenshot that i'm sharing with you it is current situation of icon button

**Comment by arishmaurya** [comment]
![Screenshot from 2022-05-08 18-12-28](https://user-images.githubusercontent.com/75907342/167297118-3e141459-964e-4107-859b-ad83ceefb5f6.png)
@marcellamaki  mam ,I made this icon a button using html button tag because when i'm using KIconButton tag the leaf icon disappers now this button is navigable by tab bar but it is not showing points on clicking by keyboard can you help me and the screenshot that i'm sharing with you it is current situation of icon button

**Comment by marcellamaki** [comment]
@arishmaurya -- it's no problem that the leaf icon disappears. There is a new icon that will be created by our design team for this new work, and it is not ready to be added to the repository. So, please use the `KIconButton` component, not the html button. You can use any icon as a placeholder, as noted in the scope of the issue, which will allow for testing. To find a placeholder icon to use, you can search for `KIconButton` or `IconButton` anywhere in the repository and look for the "icon" prop. Then, just use that for now and pass that into your component. Add a comment to the code to note that this is a placeholder and should be replaced. Please [include `TODO:` at the beginning of your comment like this](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/sync/SelectSyncSourceModal.vue#L56)

You can look at `DownloadButton.vue` to get an idea of how to add a dropdown element (`KDropdownMenu`) to a button, which you can use to display the points.
