### ISSUE TITLE
Add bottom bar as Android navigation bar

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9278]
This issue is part of the app bar refresh work. The scope of this issue is to begin implementation of an Android app specific navigation bar, following common design patterns of bottom navigation.

### Scope
- [ ] Create a bottom menu that will display only on the Android app
- [ ] The menu options area always the Learn plugin main pages -- home, library, and bookmarks -- and a menu option for additional navigation
- [ ] The top bar should only have the plugin name on the left. The existing points display and username can be left as-is.

#### Out of scope 
- Creating the menu. The button should be added to the bottom bar, but no interaction with it is needed for this issue
- Removing the existing user profile dropdown menu

### Specs 
![Screen Shot 2022-04-11 at 11.07.06 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/fae02b09-2e49-4b17-b1c7-c2d0221160b5)

![Screen Shot 2022-04-11 at 11.07.53 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/898f4502-10dd-48b2-927c-4ddc463ced9d)

![Screen Shot 2022-04-11 at 11.07.41 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/43a2dc0a-d05d-4090-ad06-5b64794a9732)

![Screen Shot 2022-04-11 at 11.07.11 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/5b0bec36-9f43-49c1-8929-5ca9927649a6)

### Acceptance Criteria
- [ ] Layout should be pixel-perfect match to Figma specifications 
- [ ] Navigation between home, library, and bookmarks should work
- [ ] Bars should hide on scroll
- [ ] Update any tests in `app-bar.spec.js` as needed based on your changes

**Comment by marcellamaki** [comment]
This issue is part of the app bar refresh work. The scope of this issue is to begin implementation of an Android app specific navigation bar, following common design patterns of bottom navigation.

### Scope
- [ ] Create a bottom menu that will display only on the Android app
- [ ] The menu options area always the Learn plugin main pages -- home, library, and bookmarks -- and a menu option for additional navigation
- [ ] The top bar should only have the plugin name, points display, and username

#### Out of scope 
- Creating the menu. The button should be added to the bottom bar, but no interaction with it is needed for this issue

### Specs 

![Screen Shot 2022-04-11 at 11.07.06 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/a3503fcc-5f89-48c3-b3dc-ef96ac680dc7)

### Acceptance Criteria
- [ ] Layout should be pixel-perfect match to Figma specifications 
- [ ] Navigation between home, library, and bookmarks should work
- [ ] Bars should hide on scroll
- [ ] Update any tests in `app-bar.spec.js` as needed based on your changes

**Comment by rtibbles** [comment]
Fixed in #9984
