### ISSUE TITLE
Add overlay menu for Android navigation

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9279]
This issue is part of the app bar refresh work. The scope of this issue is to add a navigation menu for the Android app for navigation to plugins and pages beyond the core Learn plugin pages that will be the main bottom navigation

### Scope
- [ ] Create an overlay navigation menu the conditionally displays navigation options based on the user type (admin, coach, etc.)
- [ ] Add the content that was previous in the user profile dropdown
- [ ] Navigation happens on tap for each sub page link under the plugin. For example, with the "Coach" menu open, when a user taps "Class home", they are redirected and the menu closes. 
- [ ] The "X" button closes the overlay modal

#### Out of scope 
- [ ] Add the sync status for Learn-only devices to the profile section of the menu

### Specs 

![Screen Shot 2022-04-11 at 11.16.41 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/3f755042-ca4c-45cd-bc8a-bd95ede608b2)
![Screen Shot 2022-04-11 at 11.17.10 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/edeffced-94f0-4ebb-ba7f-64caa92fabd7)
![Screen Shot 2022-04-11 at 11.17.25 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/03f17d05-7354-4fa7-b004-dea0ec3dc265)
![Screen Shot 2022-04-11 at 11.17.31 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/552c47a9-899a-42aa-8342-57cefcd938b9)

### Acceptance Criteria
- [ ] Layout should be pixel-perfect match to Figma specifications 
- [ ] Navigation should work when navigating between any part of the app
- [ ] Update any tests in `app-bar.spec.js` as needed based on your changes

**Comment by rtibbles** [comment]
Fixed in #9984
