### ISSUE TITLE
Concurrent import of several channels fails after restart of the server

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9280]
## Observed behavior
This issue was first spotted by @radinamatic at the Bugbash when the concurrent import of 4 channels seemed to go on without issues, but then the VM restarted, and the import of those channels was supposed to restart automatically but the import of the original 4 channels remained stalled and never progressed further than where is was before the restart. 

I was able to replicate this issue on both Windows and Ubuntu after restarting the server while the import is still in progress.

## Expected behavior
The import of the channels should proceed after a restart of the server.

## Steps to reproduce the issue
1. Install the following [0.15.2a1](https://buildkite.com/learningequality/kolibri-python-package/builds/5227#job-c03da187-c9a1-483a-9d5f-e75b5c36f97d) build
2. Attempt to import several channels simultaneously
3. Stop the server while the import of some or all of the channels is still and progress
4. Start again the server and observe the progress of the import

## Screenshots
![2022-04-11_17-12-23](https://user-images.githubusercontent.com/79847249/162772664-c76f7e65-6406-4ab7-8a0e-22a05b7ebd7c.png)

## Ubuntu logs and DB
[Logs.zip](https://github.com/learningequality/kolibri/files/8465509/Logs.zip)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by rtibbles** [comment]
Note that this is not currently expected behaviour (in terms of the implementation that is currently in place), but I certainly agree that this behaviour is desirable.
