### ISSUE TITLE
Add sync information to Android overlay menu 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9282]
This issue is part of the app bar refresh work. The scope of this issue is to add sync status for Learn-only devices to the new overlay menu on the Android app

### Scope
- [ ] Use existing `<SyncStatusDisplay>` component for display on learn only devices
- [ ] Display "Learn only" message (can reuse existing strings/text)

### Acceptance Criteria
- [ ] Layout should be pixel-perfect match to Figma specifications 
- [ ] Sync information on Learn-only devices should display accurately based on the current users syncing status or connection
- [ ] Update any tests in `app-bar.spec.js` as needed based on your changes

### Specs
![Screen Shot 2022-04-11 at 2.37.06 PM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/59f181ca-ae64-41f5-83fc-cd47c2c3eb21)

**Comment by rtibbles** [comment]
This was fixed in #9404 due to the sharing of common code between the Android side nav and the main side nav.
