### ISSUE TITLE
Enhanced Onboarding Flow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9284]
## Overview 

This epic is to create an enhanced user experience for the first time the user is interacting with Kolibri -- the onboarding. 

The improved onboarding experience has been created to:
1. help a user understand the product's value 
2. help them use the core product _successfully_ on their own
3. reduce the chances of a bad first impression, and potential abandonment of the product 

An additional goal for this work is making user's choices easier to understand.

We will know this feature is successful if we have a low bounce rates for Kolibri downloads.

### Impact and Timeline 
This feature will impact all of our users, but the most significant changes will be for users who are downloading the Android app from the Play store and using Kolibri independently. 

This is a Q2 and Q3 project, which will be released in 0.16.

### Assumptions and Risks
When designing this work, the assumption was that the existing workflows work well enough, and there are not significant changes to these. We also are assuming that people who are following the Quickstart workflow may want to change their minds later, and have an option for them to do so, whereas this option does not exist for other setup paths.

One related risk is that we might lock a user into a particular path during onboarding. The only option would be for the user to uninstall. In the future, we could add a reset option. 

Assumption that syncing works as expected, as this work is dependent on that. Any undiscovered bugs there could present delays or complications. 

### Approach
This work should build on the pre-exisiting xState development, as it has been well-tested. 

For beginning splash screen in Android app (before unpacking, during installation), this will likely need to be implemented in pure HTML. This must be localized and accessible.

#### Out of scope
Implementing initial screens using lottie (even though Android supports this)

### Acceptance Criteria
Since most technical complexity has already been resolved, and the feature workflows are all necessary for 0.16, the acceptance criteria for this epic is the full implementation of the existing specs. 

#### MVP
- Given the limited technical implementation and long lead time, full compliance to both visual elements and accessibility criteria is the baseline for our MVP.
- Full mobile responsiveness for all pages 
- Any concerns with implementing the designs according to Figma or Gherkin should be reviewed with Jessica and Radina. Decisions should not be made while coding and then asked "is this an okay change?"

### Resources
[Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1040%3A20342)
Gherkin Scenarios 
Ditto

**Comment by nucleogenesis** [comment]
#10126 #10243 #10240 #10239 and others are made as follow-ups to this, setup wizard is feature complete, just some follow-up issues to smooth things out
