### ISSUE TITLE
Kolibri not starting

### ISSUE THREAD

**Issue by nemoece** [learningequality/kolibri#9295]
## Observed behavior

Installed kolibri using "sudo pip install kolibri" on my new manjaro kde installation. When i started kolibri using "kolibri start", it throws the following error. I tried to decode the error. But i couldn't resolve this. Please have a look at it.

…

## Errors and logs

```
    ~  kolibri start                                                                                      1 ✘ 
INFO: No C extensions are available for this platform
Traceback (most recent call last):
  File "/usr/bin/kolibri", line 5, in <module>
    from kolibri.utils.cli import main
  File "/usr/lib/python3.10/site-packages/kolibri/utils/cli.py", line 12, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/core/management/__init__.py", line 13, in <module>
    from django.core.management.base import (
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/core/management/base.py", line 17, in <module>
    from django.db.migrations.exceptions import MigrationSchemaMissing
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/migrations/__init__.py", line 2, in <module>
    from .operations import *  # NOQA
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/migrations/operations/__init__.py", line 1, in <module>
    from .fields import AddField, AlterField, RemoveField, RenameField
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/migrations/operations/fields.py", line 4, in <module>
    from django.db.models.fields import NOT_PROVIDED
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.deletion import (
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/models/deletion.py", line 5, in <module>
    from django.db.models import signals, sql
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/models/sql/__init__.py", line 2, in <module>
    from django.db.models.sql.query import *  # NOQA
  File "/usr/lib/python3.10/site-packages/kolibri/dist/django/db/models/sql/query.py", line 11, in <module>
    from collections import Counter, Iterator, Mapping, OrderedDict
ImportError: cannot import name 'Iterator' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

```

…

## Expected behavior

Kolibri just starts.

…

## User-facing consequences

I already have around 60gb worth of kolibri downloaded files. I just copied .kolibri folder from my old installations and paste it in new installation. This was working like a charm in the past. Now I don't know what is happening. It didn't even start. In ubuntu, It still works. So the problem is not with database. It is with Manjaro and kolibri combinations. It just misses some dependencies or something like that. I tried to search kolibri website to look for any dependencies list. But i couldn't find it. So please help me.

…

## Steps to reproduce

Install kolibri on Fresh installation of manjaro OS and start kolibri. It won't start.

…

## Context

 Kolibri version - 0.15
 Operating system - Manjaro KDE Plasma 21.2.5

…

**Comment by rtibbles** [comment]
Hi @nemoece - apologies, we should update this prior to the next patch release of 0.15, but Kolibri is not compatible with Python 3.10 yet. I recommend running it using Python 3.9 instead.

**Comment by rtibbles** [comment]
I've opened a pull request to make sure that from 0.15.2 onwards, Kolibri will properly show it is incompatible with Python 3.10.

**Comment by nemoece** [comment]
> Hi @nemoece - apologies, we should update this prior to the next patch release of 0.15, but Kolibri is not compatible with Python 3.10 yet. I recommend running it using Python 3.9 instead.

Thanks for the info @rtibbles . Is there any specific command i can give so that kolibri run on python 3.9
Thanks for your help.

**Comment by rtibbles** [comment]
Make sure you have Python 3.9 installed on your system, then make a Python virtual environment using that version of Python.

For more information about virtual environments, see here: https://realpython.com/python-virtual-environments-a-primer/

**Comment by nemoece** [comment]
> Make sure you have Python 3.9 installed on your system, then make a Python virtual environment using that version of Python.
> 
> For more information about virtual environments, see here: https://realpython.com/python-virtual-environments-a-primer/

Thanks for your help @rtibbles. I am closing this issue for now.
