### ISSUE TITLE
Consolidate documentation regarding asset hooks

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#93]
After some final amendments on #66, we went for a model where asset definitions and building takes place in one `WebpackBundleHook` and the inclusion itself is done through means of hooks for each location where hooks are loaded or with a template tag taking the asset's slug as a parameter.

**Comment by indirectlylit** [comment]
This issue is very old and documentation/code has evolved a lot. Let's file new issues specific to the current state of the docs & code if necessary.
