### ISSUE TITLE
Design Update: All steps in Import individual users on LoD flow (existing flow)

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#9311]
# Overview

The existing LoD import users flow has visual updates

# Acceptance Criteria

- [ ] Apply designs from Figma

Import individual user accounts (Figma - [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A683) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1602))
Import multiple accounts (Figma - [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=450%3A5775) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1641) ) )
Loading user  (Figma - [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A777) [Desktop 2](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A766) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1633) [Mobile 2](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1672)

- Note that the loading user page, after successfully importing completes, allows the user to return and import another individual account.

**Comment by rtibbles** [comment]
The visual changes have been implemented, further behaviour tweaks are logged in other issues.
