### ISSUE TITLE
Create new state machine for User plugin to manage facility change flow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9318]
# Overview

The facility change workflow will be supported through an xState machine similar to the `wizardMachine.js` file in the Setup Wizard flows. The machine defines a state machine through which the Setup Wizard flows as the user interacts with the wizard. This pattern should be followed and translated into the possible flows for changing a facility. 

The state machine should be created, and each state should be defined with alignment to the titles of the slides that the user sees. 

## Acceptance Criteria

- [ ] Create a state machine file for the facility change
- [ ] Each possible state for the flow has been identified and added to the state machine
- [ ] Each possible state has a 'continue' and 'back' associated with it, when appropriate
- [ ] Each possible state has a route

**Comment by rtibbles** [comment]
Why is this targeted for the facility plugin? Most users who will be changing facilities will not have access to the facility plugin. I think this should be targeted at the User Profile plugin instead.

**Comment by jredrejo** [comment]
@marcellamaki I'm adding a dependency for this issue to  be able to fulfil the latest point of the Acceptance Criterias
