### ISSUE TITLE
Create "Confirm Account" page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9325]
# Overview 

Adds a confirmation page when a user is changing facility, explaining that they will use their current account to join the new facility.

## Figma 
![Screen Shot 2022-04-20 at 11.17.03 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/eb258084-bd5c-46ef-a1ce-791fcb0fe1d9)

### Accessibility notes
Tab order: 
1) "Continue" primary button 
2) "Back" secondary button 
3) "X" close out flow 

### Out of scope 

Adding the route itself is not part of this issue

### Acceptance criteria

- [ ] Page is created with correct strings 
- [ ] UI layout to spec with correct tab order and spacing

**Comment by jredrejo** [comment]
Closed with #9512
