### ISSUE TITLE
Create task status page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9327]
# Overview 

Adds a page that can be used to show the task progress of the facility change or account merge

## Figma 
|  Description  |  In progress  |  Done  |
|---|---|---|
| When changing facility  |  ![Screen Shot 2022-04-20 at 11.04.35 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/8f27461d-3bdc-4e78-9b06-ccf4558cbc1c) | ![Screen Shot 2022-04-20 at 11.04.42 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/6f3e3300-6825-478e-85ae-ee4374a57e5f) |
|  When merging accounts | ![Screen Shot 2022-04-20 at 11.04.09 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/34f749cd-50bc-40ca-afd9-0f500ddc3971) | ![Screen Shot 2022-04-20 at 11.04.18 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/d3724e4f-8eff-4a37-ba3c-6615e0b2810f) |

### Out of scope 

Adding the routes are not part of this issue

### Acceptance criteria
- [ ] Page created and reuses existing task display components
- [ ] UI layout to spec
- [ ] Finish button and bottom bar not visible until task is finished

**Comment by photon0205** [comment]
Is the task to just create the frontend (the page)? If yes, I would like to work on this issue if its still valid

**Comment by rtibbles** [comment]
This has all been implemented.
