### ISSUE TITLE
Create "Create Account" / "Edit Account" page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9329]
# Overview 

Adds a page for a learner account creation or editing an existing account. `CreateLearnerAccountForm.vue` in the Setup Wizard could be used for reference

## Figma 
| No Existing Account |  Edit Existing Account |
|---|---|
| ![Screen Shot 2022-04-20 at 9.43.12 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/2940373d-2db3-433f-b4c7-12950945f875) | ![Screen Shot 2022-04-20 at 9.42.40 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/67c84f5b-9411-4edb-89bd-bca209c46f76)| 

### Accessibility notes
Tab order: 
1) Text fields (top to bottom)
2) "Continue" (or "Save") primary button 
3) "Back" secondary button 
4) "X" close out flow 

### Out of scope 

Adding the route itself is not part of this issue

### Acceptance criteria

- [ ] Page is created with correct strings 
- [ ] UI layout to spec with correct tab order and spacing
- [ ] If the account exists, the fields are populated with existing details
- [ ] Fields are editable and displayed according to facility settings

**Comment by MisRob** [comment]
Closing as "Create Account" has been already implemented and "Edit account" doesn't need to be implemented because we removed this step from the flow.
