### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#933]
## Summary

Just a console error noticed in #930, not aware of any functionality problems (yet).
Happens on both login state as learner or device admin, and when not logged in.

## System information

 - Version: latest develop
 - Operating system: Linux
 - Browser: Chrome & FF

## Traceback or relevant snippet from server.log or browser console

```
Uncaught (in promise) Object {request: Object, error: "mime-serialization"}
default_frontend-0.1.1rc1.dev653.js:2 Uncaught (in promise) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at p (default_frontend-0.1.1rc1.dev653.js:2)
    at default_frontend-0.1.1rc1.dev653.js:2
p @ default_frontend-0.1.1rc1.dev653.js:2
(anonymous) @ default_frontend-0.1.1rc1.dev653.js:2
```

## Screenshots

![divide fractions and whole numbers word problems - khan academy en - kolibri - google chrome_055](https://cloud.githubusercontent.com/assets/1457929/23075317/3f494c16-f53c-11e6-8b7f-3b3494ce1bfc.png)

**Comment by 66eli77** [comment]
@radinamatic don't see this error in the latest develop branch. Can you reproduce it again? any specific procedure to reproduce?

**Comment by 66eli77** [comment]
ok, I know how to reproduce now, you have to correctly answer an exercise, then see the error on dev console.
