### ISSUE TITLE
Create "Confirm Account Details" page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9330]
# Overview 

Adds a page to account details to flows when a user has an existing account. 

## Figma 
![Screen Shot 2022-04-20 at 9.35.44 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/b60e9a6e-d9c2-4445-8032-efed0b276ca3)

### Accessibility notes
Tab order: 
1) Text fields (top to bottom)
2) "Continue" primary button 
3) "Back" secondary button 
4) "X" close out flow 

### Out of scope 

Adding the route itself is not part of this issue

### Acceptance criteria

- [ ] Page is created with correct strings 
- [ ] UI layout to spec with correct tab order and spacing

**Comment by jredrejo** [comment]
@marcellamaki I can't find this screen in the figma design, could it be it was removed after you created the epic? 
I suppose the right design is this one:
![image](https://user-images.githubusercontent.com/1008178/171041924-7d15e2ab-3dd1-40ac-84e0-ffe9e8caf036.png)

**Comment by marcellamaki** [comment]
@jredrejo -- it is [this screen  (04d.1) in the "username exists" flow](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=611%3A10119). If it is easier to combine this with the option you refer to above, and just have different content based on the state, I think that would be fine too

**Comment by jredrejo** [comment]
ah, thanks! I hadn't seen that one previously. No, it's not something to combine. This is farther in the flow. 
Sorry for the noise

**Comment by jredrejo** [comment]
This screen has been removed after the changes done in the design in the discussion of #9328
