### ISSUE TITLE
Controls overlapping content in folder resources panel

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#9345]
## Observed behavior

In the "folder resources" panel for some resources, both the close button and the arrow icon overlap with text:

![Screenshot 2022-04-22 at 15-53-19 Watch Me - TED-Ed Lessons - Kolibri](https://user-images.githubusercontent.com/132063/164814797-8db910e4-fb27-44ab-a836-6278659f7d74.png)

## User-facing consequences

This does not block interaction, but it makes text difficult to read and it looks ugly.

## Steps to reproduce

This occurs using Ted Ed content at https://kolibri-demo.learningequality.org/en/learn/#/topics/c/5900e6eab432596d88ab8cf455a77995?last=TOPICS_TOPIC_SEARCH&topicId=68ad96dcf36f54db9367e76ee7afc015.

## Context

The screenshot was created using Firefox with a 1366×768 resolution.

The same issue was also seen using the Kolibri desktop app for GNOME: https://flathub.org/apps/details/org.learningequality.Kolibri.

Kolibri version: 0.15.1.

**Comment by rtibbles** [comment]
Could you specify the Kolibri version? I assume 0.15.1, but want to double check.

**Comment by nucleogenesis** [comment]
I tested this on `develop` and 0.15 and see the issue in both. I figure a fix for this should probably both:

- Address the text width to avoid overlapping with the icons
- Use the TextTruncatorCSS component on the content title there to avoid overflow of longer titles

**Comment by dylanmccall** [comment]
Yep, looks like you got it, but just to confirm this was with Kolibri 0.15.1.

**Comment by rtibbles** [comment]
Fixed in #9699.
