### ISSUE TITLE
View Resource button makes everything tiny

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#9347]
## Observed behavior

After a particular series of steps, Kolibri's interface is constrained to a tiny frame and it becomes impossible to scroll.

## Steps to reproduce

Navigate to a channel in the Learn / Library interface, and then to a particular folder:

https://kolibri-demo.learningequality.org/en/learn/#/topics/t/ba195f33c4e65057a324b223d6b35f97/folders

For a particular resource, click the "i" button to view information about that resource:

![Screenshot 2022-04-22 at 16-04-29 01 Think Like A Coder - TED-Ed Lessons - Kolibri](https://user-images.githubusercontent.com/132063/164815536-1575e10b-3dfa-4401-8771-9fd27f27250e.png)

Click the "View resource" button:

![Screenshot 2022-04-22 at 16-04-52 Watch Me - TED-Ed Lessons - Kolibri](https://user-images.githubusercontent.com/132063/164817140-905a1ec5-5212-4a0e-a9cd-889095193126.png)

Note that Kolibri's interface has been constrained to a tiny (280×251 px) frame.

After pressing the Back button (either the browser Back button or in Kolibri's UI), it is no longer possible to scroll.

## Context

The screenshot was created using Firefox with a 1366×768 resolution. We originally encountered this issue using the Kolibri desktop app for GNOME (https://flathub.org/apps/details/org.learningequality.Kolibri).

Kolibri version: 0.15.1.

**Comment by marcellamaki** [comment]
Fixed in #9449
