### ISSUE TITLE
Update perseus renderer to better manage exam errors

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9402]
As previously reported in #3853, the perseus renderer was displaying exam errors to the user. The fix in #4365 dismisses these errors when moving between items. 

Included in the update was a comment that this was a bit of a hacky work around. The perseus renderer should be updated to handle this issue properly, rather than having this in the Exam Page.

**Comment by rtibbles** [comment]
Fixed in #9403
