### ISSUE TITLE
Add availability checking that we do in the lesson display page when we pass nodes to the AlsoInThis panel

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9412]
From 0.15.3-a0 bug bash

Opening the ‘Next in lesson’ sidebar gives inconsistent results, sometimes just the green spinner is visible
Happened in a single user syncing context 

**Expected behavior**
Next in lesson sidebar should always load the files, or have the blank state if none

Tested by @radinamatic 
[logs.zip](https://github.com/learningequality/kolibri/files/8642943/logs.zip)
<img width="960" alt="2022-05-06_19-21-43 (1)" src="https://user-images.githubusercontent.com/17235236/167197627-eb2524f2-3429-49bf-b854-424b85e9f218.png">

Firefox | Windows 10

**Comment by rtibbles** [comment]
Possible that this could be related to missing content for some of these issues?

There is definitely an error in the logs about the database being locked.

Also, I see that our Windows installer is still absolutely spamming the hell out of the Kolibri server for no good reason.

**Comment by radinamatic** [comment]
@rtibbles nailed it:

>  If you create a lesson, then selectively delete one resource that is in the lesson from the device (but don't delete it from the lesson), then I think the error will replicate. We're not doing any kind of availability checking that we do in the lesson display page when we pass nodes to the AlsoInThis panel: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/LearnImmersiveLayout.vue#L332

![Win10 (start)  Running  - Oracle VM VirtualBox_003](https://user-images.githubusercontent.com/1457929/185708403-ca07bed9-8820-4201-8bb2-9d4d9e1d561a.png)

**Comment by marcellamaki** [comment]
Thanks @radinamatic - I've removed you as the assignee and updated the title to better describe the bug so we can assign this in the next iteration 🎉

**Comment by rtibbles** [comment]
Fixed in #9700
