### ISSUE TITLE
Don't send unnecessary empty query parameters to the facility user endpoint

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9414]
## Observed behavior
There are instances where there are empty query params being sent to the facility user endpoint

e.g. http://127.0.0.1:8080/api/auth/facilityuser/?member_of=4839d1a0688cc1e8f01fac813f5b1da8&page_size=30&page=3&search=65&exclude_member_of=&user_type=&exclude_user_type=&1651856395778=1651856395778

## Expected behavior
Should not send empty query params

**Comment by rtibbles** [comment]
Fixed in #9422
