### ISSUE TITLE
Confusing UI when importing content over a network

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9415]
## Observed behavior
When importing from someone over the network, if they have a lower version of the same channel, some items may show up with a “New” flag on resources that are actually old. This occurred an QA channel versions 95 → 90.

## Errors and logs
None

## Expected behavior
Older versions of the channel should not be flagged as "new"

## User-facing consequences
Confusion!

## Steps to reproduce
Import from someone over the network, when the person you are importing from has an older version of the channel than you currently have on your device

## Context
Single-user-sync context 
Jamie	Ubuntu 20.04	Chrome
Jacob	Fedora 34	Chrome

**Comment by rtibbles** [comment]
This should be relatively simple to solve - presumably we are looking for a difference to display 'new' rather than only showing newer versions.

**Comment by rtibbles** [comment]
Fixed in #11695
