### ISSUE TITLE
Error when trying to import content from a peer

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9416]
From 0.15.3.a0 bug bash 

## Observed behavior
Local request to:

[http://6.5.75.95:1234/api/content/remotechannel/95a52b386f2c485cb97dd60901674a98/?baseurl=http%3A%2F%2F192.168.191.113%3A8080%2F&1651855796864=1651855796864](http://6.5.75.95:1234/api/content/remotechannel/95a52b386f2c485cb97dd60901674a98/?baseurl=http%3A%2F%2F192.168.191.113%3A8080%2F&1651855796864=1651855796864)

returns a 404 with body:

[{"id":"NOT_FOUND","metadata":{"view":"Remote Channel Instance"}}]

After a hard refresh, it worked for Jacob, but not for Jamie (same error showing).
## Errors and logs
404 with body: 
[{"id":"NOT_FOUND","metadata":{"view":"Remote Channel Instance"}}]

User-facing error message
<img width="367" alt="Untitled (5)" src="https://user-images.githubusercontent.com/17235236/167200573-d70ffb04-4232-4e1c-993d-bff4ed3c0d43.png">

## Steps to reproduce
Set up a sync scenario. Attempt to import content

## Context
Jamie	Ubuntu 20.04	Chrome
Jacob	Fedora 34	Chrome

**Comment by bjester** [comment]
Experienced something like this running the 0.15.3a0 pex, and attempting to import from an 0.15.2 pex that I had just imported a channel into. It said there were 0 channels on the peer instance

**Comment by marcellamaki** [comment]
@radinamatic - can this get QA re-review please? Thank you!

**Comment by pcenov** [comment]
Hi @marcellamaki I'm not able to replicate this issue in Kolibri 0.16.0a13 - no issues observed while importing content from a peer device.

**Comment by radinamatic** [comment]
Closing as not extant on 0.16.
