### ISSUE TITLE
Remove SidePanelModal from core api

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#9442]
The SidePanelModal is only used in Learn - not sure why I put it in the Core API spec but maybe I was a bit optimistic about how widely used this feature might be!

It should be moved to Learn, all references to it updated, and then remove it from the API spec.

**Comment by amitpanwar789** [comment]
Hi, I am new to open source and willing to contribute to Kolibri, can I work on this issue. ?
