### ISSUE TITLE
Khan Academy exercises - Missing x-axis labels

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9443]
## Observed behavior
This issue was initially reported here: https://community.learningequality.org/t/display-issues-with-khan-academy-exercises/2425/1
Note that I am currently able to replicate only the issue with the missing x-axis labels, the numeric input is functioning correctly.

## Steps to reproduce the issue
1. Install Kolibri 0.15.2
2. Import [Khan Academy's](https://www.khanacademy.org/math/cc-third-grade-math/represent-and-interpret-data/imp-picture-graphs/e/reading_pictographs_2) (English - US curriculum) > Math by grade > 3rd grade > Represent and interpret data > Picture graphs 
3. Create a quiz for 'Read picture graphs (multi-step problems)'
4. Interact with the quiz

## Expected result
Fully visible x-axis labels

## Screenshots

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Khan Academy's site | ![2022-05-17_12-58-16](https://user-images.githubusercontent.com/79847249/168813009-cb9e1f3b-c4cc-4517-9add-3344dbc456ba.png) |
:-------------------------:|:-------------------------:
| Coach view | ![2022-05-17_12-59-25](https://user-images.githubusercontent.com/79847249/168813116-ad5734c2-63e3-4aaa-bb95-7a618ed5884e.png) |
:-------------------------:|:-------------------------:
| Learner view | ![2022-05-17_13-01-32](https://user-images.githubusercontent.com/79847249/168813224-580bbb1b-e8c9-4103-a196-052aff9ece11.png) |
:-------------------------:|:-------------------------:

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #9446
