### ISSUE TITLE
Learners not available to enroll in the class

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#9448]
## Observed behavior
Encountered while testing #9446, according to @rtibbles most probably a regression from the recent pagination work.

Facility has 3 new learners, but none seem available to be enrolled in the class:

![enroll-issue](https://user-images.githubusercontent.com/1457929/168927631-eec829b1-abe5-4ae8-8904-f216dc979f2b.gif)

## Errors and logs
…

## Expected behavior
Visible list of learners to enroll.

## User-facing consequences
…

## Steps to reproduce
Create learner(s) and try to enroll them in a class.

## Context
 * Kolibri version: 0.15.x branch, EXE asset from #9446  
 * Operating system: Windows 10
 * Browser: all

**Comment by marcellamaki** [comment]
Fixed with #9450
