### ISSUE TITLE
PhET Interactive Simulations interactive resources loading on non-standard ports 

### ISSUE THREAD

**Issue by eapdso** [learningequality/kolibri#9451]
## Observed behavior

Resources that are interactive fail to load in the PhET Interactive Simulations channels on v0.15.3-alpha0 even after reinstalling channel. 

Background resources are attempting to load on various random ports, rather than using the standard https port which is likely being blocked by our load balancer / security groups.

It's possible that we could open up these ports, but they appear to be randomized. The preference would be to revert back to loading content on https standard ports which is how this worked in previous builds. 

## Errors and logs

For example, the html resource fails to load and sits as "pending" when trying to load any interactive (non-video) content within PhET. 

For example, this page fails to load: 
https://[website]/en/learn/#/topics/c/1872377961a65fb2bf67edff4cec2666?last=TOPICS_TOPIC&topicId=1036aaceb2935676a224831edeb4369b

And we see this resource loading in the
e.g. https://[website]:44813/content/static/hashi/hashi-cea3be36e609aeba234a13b27afd33b8.html fails to load and sits as "pending" 

Or this one: 
https://[website]:60155/content/static/hashi/hashi-cea3be36e609aeba234a13b27afd33b8.html

## Expected behavior

Resource loads on https and the end user can interact with the interactive javascript function

## User-facing consequences
Test environment only, currently

## Steps to reproduce
1. Load 0.15.3 version
2. Add PhET Interactive Simulations Channel with all content
3. Navigate to PhET channel
4. Load interactive simulaiton (not video content) like Physics -> "Balancing Act"
5. View in developer tools the resources loading on non-standard ports

## Context
Tell us about your environment, including:
 * Kolibri version - 0.15.3
 * Operating system - AWS linux
 * Browser - Chrome (Mac) 

…

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/25356567/169369652-3646954f-c1c4-4662-8f1a-745314bbf6c3.png">

**Comment by rtibbles** [comment]
Hi @eapdso - this is by design, if you would like to set a fixed port for zip content to be served over, please use the `ZIP_CONTENT_PORT` option, as described here: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/options.py#L488

This can either be set in an `options.ini` file under the `[Deployment]` section header, or as an environment variable `KOLIBRI_ZIP_CONTENT_PORT`.

Note that this was changed due to ongoing issues with running HTML5 apps inside a sandboxed iframe context - this caused many apps to fail to run properly. In order to address this, we instead switched to serving the apps from an alternate port, which allowed us to reduce the sandboxing on the iframe. Serving the zip content from the same origin as the main Kolibri server poses a security risk and is not recommended.

**Comment by eapdso** [comment]
hey @rtibbles thanks, I didn't realize that change had been made!
I've tried setting the ZIP_CONTENT_PORT in the options.ini file but after reboot, regardless of the port I select, the entire site fails to load with a 502. This isn't just the content failing to load, it's the entire site, so it's like the ZIP_CONTENT_PORT is affecting general site hosting settings as well, weirdly. See attached images. 

I've tried port 80, 8443 (our default port for the site itself) and others but with no luck -- the main site fails to load in every circumstance. 

Is this expected in any way? For example, do I need to be setting other settings in the Deployment section of the options.ini in order to use the ZIP_CONTENT_PORT setting? 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/25356567/170075376-d567da4a-f8af-4f81-bb5f-8714edff3321.png">

<img width="997" alt="image" src="https://user-images.githubusercontent.com/25356567/170075588-1485c50d-2fab-4b7e-9983-53aff1be6f0a.png">

**Comment by rtibbles** [comment]
It seems like you are serving Kolibri behind nginx? If you are trying to serve on https, then you will probably need one domain serving to the main Kolibri WSGI server (defined by `HTTP_PORT`) and another domain or subdomain that serves to the ZIP_CONTENT_PORT.

If you need to define the specific origin that you are serving the zip content from, you can use the `ZIP_CONTENT_ORIGIN` option to set the specific origin that is being used for that so Kolibri knows where to access it from.

For complete details of these different settings and how they interact, see here: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/options.py#L566

It's important to note that `ZIP_CONTENT_PORT` is an internal setting to tell the Kolibri process where to serve, and `ZIP_CONTENT_ORIGIN` is needed to point the frontend of Kolibri to look for zip content on a specific origin. A complete description is given in the link above. However, if you are serving via https, only one server can be served on port 443 per origin. The above settings should allow you to customize the setup once you've configured nginx to handle things as you need.

For further guidance, also see our https://github.com/learningequality/kolibri-server repository which uses nginx to serve the different WSGI apps using UWSGI.
