### ISSUE TITLE
Keyboard-only navigation - Tab focus outline is not fully encircling the buttons

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9464]
## Observed behavior
While testing the keyboard navigation and focus outline improvements I noticed that the buttons in the footer don't get fully encircled by the tab focus outline.

## Steps to reproduce the issue
1. Install Kolibri v0.15.3-beta1
2. Go through some workflows such as importing a channel or completing a lesson/quiz

## Screenshots
![2022-05-27_18-05-32](https://user-images.githubusercontent.com/79847249/170732744-a157c1b8-c556-4e67-abe4-189de0b51541.png)
![2022-05-27_18-06-54](https://user-images.githubusercontent.com/79847249/170732746-44fd6a4b-1354-4eee-9550-9f95355c3d4e.png)
![2022-05-27_18-08-32](https://user-images.githubusercontent.com/79847249/170732747-6505509f-3b0c-49b0-adf5-751e64994133.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
@marcellamaki This is a regression, but not necessarily a result of the changes in the most current patch PRs, not sure if the fix is related to the design system or can be dealt in Kolibri.

It's not a blocker not it has high impact, but would be a bonus to see if we could fix it... 😉

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/9478
