### ISSUE TITLE
Create "Change Facility" Informational screen

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9469]
# Overview 

Presents a user with information about what changing their facility means, the new facility they are joining, and what will happen to their data 

## [Figma](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=473%3A6412) 
![Screen Shot 2022-06-01 at 9.03.28 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/41761267-e768-4c97-bf11-566368394fc7)

### Acceptance criteria

- [ ] Page is created with correct strings 
- [ ] UI layout to spec with correct tab order and spacing
- [ ] "Your user account type will change from ‘[non-learner-role] to ‘learner’. You will need another admin to change your account type to ‘[non-learner-role]’ again. " only is included for non-learner accounts.

**Comment by jredrejo** [comment]
Closed with #9512
