### ISSUE TITLE
Disable 'continue' button during quiz creation unless a selection is made

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9472]
## Observed behavior
During the Uganda training, while creating a quiz, many participants clicked on ‘continue’ after entering the title and the number of questions instead of clicking on the channel first

<img width="1438" alt="Screen Shot 2022-06-01 at 11 26 20 AM" src="https://user-images.githubusercontent.com/17235236/171441469-3309738f-5883-4f56-803c-f805d58fb795.png">

## Expected behavior
A user should not have the option to click the "continue" button unless they have selected content needed. It could perhaps be disabled, or the bottom bar could only show up when the content has been selected

## User-facing consequences
Confusion about how to follow the workflow. 

## Steps to reproduce
Add a title and selected number of questions. Click the "continue" button before selecting any content.

**Comment by rtibbles** [comment]
Fixed in #9515
