### ISSUE TITLE
Update "Manage Lesson Resources" saving actions with clearer language

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9473]
## Observed behavior
During the Uganda training, coaches reported confusion about clicking the "close" button during the Manage Lesson Resources flow. Not always super intuitive to click on "Close" after desired exercises are selected. It seemed a little intimidating to hit close instead of something like “Save” or “Next.”

<img width="1434" alt="Screen Shot 2022-06-01 at 11 39 21 AM" src="https://user-images.githubusercontent.com/17235236/171444802-26a68930-e4ff-462b-b3dd-87d6df98658d.png">

## Expected Behavior 

Replacing the "Close" button with something like "Save" or "Continue" (available in commonCoreStrings) might make the workflow clearer, even though the resource is technically saved as part of the checkbox action.

## User-facing consequences
Users being unsure of the next step of the workflow

**Comment by rtibbles** [comment]
Fixed in #9516
