### ISSUE TITLE
Channel import API issues

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9479]
## Observed behavior
@rtibbles I found a couple of more issues for the channel import/update workflows
I noticed that when attempting to import only a single resource or a folder then the entire channel will get imported instead.
Also when I attempt to import a recently updated channel I see a "Something went wrong" error page.

## Steps to reproduce the issue
1. Install the latest [build](https://buildkite.com/learningequality/kolibri-python-package/builds/5614) from https://github.com/learningequality/kolibri/pull/9461
2. Attempt to import only a single resource or a folder
3. Attempt to update a channel

## Logs
[logs.zip](https://github.com/learningequality/kolibri/files/8825129/logs.zip)

## Videos
https://user-images.githubusercontent.com/79847249/171659702-b5d541f5-5681-4a00-a9c7-01ec4cac6b8a.mp4
https://user-images.githubusercontent.com/79847249/171658668-2a6061d8-0725-4ea7-969a-a181bffbd31b.mp4

## Usage Details
Windows 10 and Ubuntu 20 - Chrome

**Comment by rtibbles** [comment]
Thanks for the follow up @pcenov - I had definitely seen issues with whole channels being imported instead of a subselection, but thought I had resolved it. It appears not.

**Comment by rtibbles** [comment]
The first issue of the subselection of resources should have been fixed by #9567.

**Comment by rtibbles** [comment]
The second and final part of this was resolved in #9732
