### ISSUE TITLE
Keyboard navigation - Minor cosmetic issues with the visible focus outline

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9484]
## Observed behavior
See the attached screenshots.

## Steps to reproduce the issue
1. Install Kolibri v0.15.3-beta2
2. Observe the visible focus outline when importing a channel, changing the permissions or browsing the library

## Screenshots
Device > Permissions:
![2022-06-06_11-55-56](https://user-images.githubusercontent.com/79847249/172184079-ca9721e2-b925-4bbc-aaf8-fcd29acfbb68.png)

Device > Facilities > Import facility:
![2022-06-06_11-57-57](https://user-images.githubusercontent.com/79847249/172184083-3da06c93-3c71-4980-a4fc-ad84cc97b3a3.png)

Learn > Library and Learn > Library > Browse channel
![2022-06-06_17-21-35](https://user-images.githubusercontent.com/79847249/172184085-449eaa31-62d9-4f2c-a509-709528f3d3e5.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
This is not a blocker for the release tomorrow, can be slated to the next patch!

**Comment by AllanOXDi** [comment]
fixed in  #9897
