### ISSUE TITLE
Missing facility name when importing (sync) a facility

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9494]
## Observed behavior

When you import a facility, the name is missing from the task details

![Screenshot from 2022-06-07 15-37-10](https://user-images.githubusercontent.com/819838/172494678-1a694ea5-c44b-4e4d-8775-ad801518ed51.png)

## Expected behavior

It should say `Import '<facility name>'`

## Steps to reproduce

1) Go to Device > Facilities
2) Click <kbd>Import Facility</kbd>
3) Choose a peer instance, facility, and provide credentials to trigger the import
4) Observe the task's details are missing the facility name

## Context

Kolibri 0.16.0
Ubuntu
Google Chrome

**Comment by rtibbles** [comment]
Noting that this is probably an issue in the frontend not setting the name in the task payload.
