### ISSUE TITLE
Library page - Missing "Keywords" section

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9497]
## Observed behavior
The Keywords section of the filters on the Library page is not being displayed in all supported browsers.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library page

## Screenshots
![2022-06-08_14-35-52](https://user-images.githubusercontent.com/79847249/172638830-1ca082e3-1aa3-497a-814f-241c7d6dbdfd.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by marcellamaki** [comment]
Hi @pcenov - I think with some other updates we've made, this has been resolved on the 0.16 build. Can you confirm also working on Windows and Ubuntu (this is not urgent)? It is fine for me on Mac but want to be sure there's not a bug I'm unaware of. Thank you!

**Comment by pcenov** [comment]
Hi @marcellamaki yes, I've just checked and confirm that this is no longer extant.
