### ISSUE TITLE
Browse channel > View resource - The video player is displayed in the left corner of the screen

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9499]
## Observed behavior
When I go to Library > Browse channel  and I click the info icon of a video resource and then click the View resource button the video player gets displayed in the left corner of the screen. When I go back to Browse channel the page is not displayed correctly as well.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library > Browse channel
3. Click the info icon of a video resource and then click 'View resource'

## Screenshots
![2022-06-08_11-46-18](https://user-images.githubusercontent.com/79847249/172641762-bc7629d1-a9c1-4126-a601-44ad2073823a.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by akolson** [comment]
@pcenov After a couple of tests, this doesn't seem to be an issue anymore in `develop` so proceeding to close this. Please see screenshots showing the current state of the UI in `develop`.

<img width="1798" alt="Screenshot 2022-12-28 at 20 36 51" src="https://user-images.githubusercontent.com/5203639/209851089-a9a1a646-e1ce-4739-84b7-0efdc0c23ead.png">

On Click **View Resource**
<img width="1798" alt="Screenshot 2022-12-28 at 20 37 19" src="https://user-images.githubusercontent.com/5203639/209851169-51c13e56-2e88-4613-beb2-98be74ca96a6.png">

cc @radinamatic
