### ISSUE TITLE
Allow plugins to be built standalone

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#950]
## Summary

Right now, looks like we need to clone both a Kolibri repository and the specific plugin we need to build, and then run the devserver to have it serve the assets. It's hard on a devops and CI perspective to start building the plugins:

- Which version of Kolibri do I need to clone to get a plugin building? We'll like to pin a plugin to a version of Kolibri in the long term.
- I'm basically just replicating the Kolibri build pipeline, but with one small change. This consumes both devops and computing resources.
- What specific steps should I take to get a plugin building and releasable? Right now, the plugin build process is very dev-focused. Hence I'm having a hard time to figure out what steps I need to do on a continuous integration perspective. `yarn install && yarn run build`, `pip install -e && make assets` all are no dice. Running `make dist` inside the plugin itself doesn't work too.

## Possible solutions

The goal is to have `make dist` produce a working `whl` file that's ready to be uploaded to PyPI.

1. When `make dist` is run, clone Kolibri on Git based on a certain tag, and then run `yarn run build` or some other magic using the cloned Kolibri dir. `make clean` should remove said directory.
1. Similar to the one above, but only fetch the exact files that are needed to build. So maybe only the vue files and the frontend build dependencies?
1. Make the plugin fully standalone (has all the dependencies needed to build its assets). Not sure what this would involve, but is the cleanest solution.

**Comment by rtibbles** [comment]
1 would be easiest to transition to.

2 would require internal knowledge about what is going on inside Kolibri, so would be fragile to changes in Kolibri's structure and API - another alternative would be for Kolibri versions to publish a versioned npm package that plugins could then depend on for build related information. Again, this seems brittle and just a mediated form of 1.

3 This would be ideal, however, all Kolibri frontend modules have a direct dependency on Kolibri, and I can't see how we would break this dependency (unless we published some sort of external npm module as in 2).

**Comment by indirectlylit** [comment]
Another long-term possibility: decouple the build front-end system from the Kolibri application. Make the build system a stand-alone set of utilities which, when run, gets pointed at a particular version of Kolibri and some set of plugins.

Shorter-term, I would be very hesitant to advocate this because so many pieces of the infrastructure are still in flux, so adding yet another repo could introduce a lot of friction.

**Comment by indirectlylit** [comment]
> We'll like to pin a plugin to a version of Kolibri in the long term.

Longer-term, this really relates to designing a stable (semantically versioned?) plugin API and specifying that version. We are not yet ready to do that though, and I agree that for now pinning to a particular tagged release of Kolibri is the best strategy.

**Comment by indirectlylit** [comment]
This issue is a bit higher-level and requires design/planning.

migrating to https://github.com/learningequality/kolibri/issues/950

**Comment by rtibbles** [comment]
You migrated it to itself?

**Comment by indirectlylit** [comment]
whoops - typo.

Migrated to https://trello.com/c/wMFbSiuR/791-allow-plugins-to-be-built-standalone

**Comment by indirectlylit** [comment]
re-opening this as we migrate _back_ from trello :)

**Comment by indirectlylit** [comment]
my comments from Trello:

* This might involve either cloning the kolibri repo as part of the plugin build process, or potentially decoupling the kolibri build tools from the application itself.
* This also relates to the idea of Kolibri having a well-defined API that plugins can build against, rather than the application itself
