### ISSUE TITLE
Mobile view - Too much empty space

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9500]
## Observed behavior
See the attached screenshot. Tested in real devices as well as using Chrome's dev tools emulator.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library > Browse channel

## Screenshots
![2022-06-08_16-48-18](https://user-images.githubusercontent.com/79847249/172643361-63dd6fa9-141d-4557-babb-87c465e9fe74.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by marcellamaki** [comment]
Closing this issue, as it has been redefined in #9962
