### ISSUE TITLE
Learn - Unnecessary top navigation when there are no channels/resources on the device

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9506]
## Observed behavior
In 0.15.3 if there are no channels on the device the user is not able to see the Home, Library and Bookmarks tabs. In the latest develop build I can see and access all 3 tabs.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5692
2. Delete any channels if there are such
3. Go to Learn

## Screenshots
![2022-06-10_16-33-32](https://user-images.githubusercontent.com/79847249/173082351-47d3d600-11c8-41f1-851b-e3fc42ad0eab.png)

## Expected behavior
When I go to Learn I should see only the following:
![2022-06-10_17-02-28](https://user-images.githubusercontent.com/79847249/173083132-9b7cbc36-556c-4620-8909-ff1a3a09b996.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by nucleogenesis** [comment]
@thanksameeelian and I walked through this and tried to replicate on 0.15.x but could not. We tried downloading a channel and deleting it but that did not cause the reported error. Closing unless replicated.
