### ISSUE TITLE
Create new quiz - The Search is not functioning

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9520]
## Observed behavior
The search bar at Coach > Plan > Create new quiz is not functioning - no results are being returned regardless of the entered search term. There are no errors in the console.

## Steps to reproduce the issue
1. Install the official 0.15.3 Kolibri build
2. Go to Coach > Plan > Create new quiz
3. Attempt to search for an exercise by typing a keyword an pressing Enter or the search icon.

## Screenshots
https://user-images.githubusercontent.com/79847249/173845477-e89bfb38-174e-4bec-837d-b1817dd0a5ba.mp4

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
One more detail: the same search while managing resources for lessons seems to be working without problems.

**Comment by rtibbles** [comment]
Fixed in #9522
