### ISSUE TITLE
Update defaultState in UserManagement 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9528]
## Observed behavior

In the UserManagement module, the `defaultState` only contains `facilityUsers: []`

In the ClassAssignMembers, this default state caused some problems with the page state not being updated properly. It does not seem to be an issue in UserManagement so far in causing an apparent UI bug, but the default state should be consistent across these two modules.

## User-facing consequences
Things might be more brittle than we are expecting; potential problems with pagination or state updates yet to be discovered!

## Context
v0.15.x

**Comment by rtibbles** [comment]
If the state is not reset due to the `preparePage` action the same brittleness arises. Setting some default state fixes the issue also.

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/9535
