### ISSUE TITLE
nav-bar UX

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#953]
We currently use a ['persistent' navigation drawer](https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-behavior) for tablet and desktop sizes.

However the guidelines say:

> Persistent navigation drawers are not recommended for apps with multiple levels of hierarchy that require using an up arrow for navigation.

Violating this advice gives rise to confusion like this bug report:

![image](https://cloud.githubusercontent.com/assets/2367265/23177658/6ff269f0-f81c-11e6-943e-ccc4cb462cc8.png)

**Comment by khangmach** [comment]
I'm not sure what they're confused by. Is the user new to drawer functionality? There is no "going in circles" here, just two views of one page. Will look at different ways to style the drawer so it looks like a standard drawer

**Comment by indirectlylit** [comment]
The initial confusion is that the `<` button (which closes the drawer) was confused with 'back' or 'up' functionality. That's why Material recommends avoiding that style drawer on sites with hierarchical content.

Then second issue about "going in circles" relates more to this issue: https://github.com/learningequality/kolibri/issues/956

(They should be able to click either sub-nav item to go to the root of Recommended or Topics)

**Comment by christianmemije** [comment]
A few different things we can do. 
1. Change the icon to be the same menu icon. 
2. Keep the drawer temporary at all screen sizes. 
3. Or the recommended by Material, to have a Permanent drawer on desktop view, which by definition, cannot be closed.

**Comment by khangmach** [comment]
Or we can swap out the < icon for an X to indicate closing action. Youtube recently made their menu  (on large screen sizes) a disappearing/appearing menu overlayed on the content below. I think that could be a good trick to use given how little content we have in our menu. youtube.com

**Comment by indirectlylit** [comment]
Interesting, they use the hamburger icon for both states.

![image](https://cloud.githubusercontent.com/assets/2367265/23196789/a1b7eed4-f870-11e6-8225-b910424c26c8.png)

![image](https://cloud.githubusercontent.com/assets/2367265/23196792/a83e6cf6-f870-11e6-84b8-9dcbab47e812.png)

**Comment by christianmemije** [comment]
Check this out @indirectlylit https://thenextweb.com/google/2016/05/02/youtube-getting-googles-material-design-heres-enable-now/#.tnw_ZpK0Z6TN

**Comment by DXCanas** [comment]
I'm with @christianmemije on the icon change - I keep clicking it to go back despite knowing that it doesn't actually go back. I've been primed.

**Comment by indirectlylit** [comment]
fixed by icon change
