### ISSUE TITLE
Update the validation to manage changes from the new themeing updates

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9531]
## Observed behavior
When starting kolibri, there are several validation errors that are a result of the changes to the theme validation. Either the default theme or the validation should be updated so there are not these errors (since, it's actually fine!)

## Errors and logs
![image](https://user-images.githubusercontent.com/17235236/175339967-b4e952d4-9955-4f1f-a330-9c78534cb51d.png)

## Expected behavior
There should not be validation errors by default 😊 

## Steps to reproduce
Start Kolibri

## Context
Currently occurring on `develop` and on `15.x`

**Comment by rtibbles** [comment]
Fixed in #9558
