### ISSUE TITLE
Quizzes - Cannot view quizzes as a non-admin user

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9544]
## Observed behavior
I'm seeing a "Resource not found" page each time I attempt to view a quiz as a learner or a coach. However the quiz can be viewed if it is assigned to an admin.

## Steps to reproduce the issue
1. Install 0.15.4 and import the QA channel
2. As a Coach create and assign a quiz to a class of learners, coaches and admins
3. Sign in as a learner/coach and attempt to view and complete the quiz

## Screenshots
![2022-06-30_18-37-16](https://user-images.githubusercontent.com/79847249/176720980-c1b22fa7-66dd-4e44-93f7-518a7708a04a.png)

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Ouch - this is a nasty regression - fairly sure this is a result of the security fixes in 0.15.4.

**Comment by rtibbles** [comment]
Fixed in #9545
