### ISSUE TITLE
Fix missing "show more" in resources not in folders 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9553]
## Observed behavior
`show more` is completely missing from the top level resources in the Folder/TopicsContent view of kolibri. Therefore, a maximum of 4 resources are displayed (the "preview" amount), no matter how many there are

## Expected behavior
user should be able to access all resources 

## User-facing consequences
Confusing, and users are unable to access content

## Steps to reproduce
Navigate to a folder where there are more than 4 resources at the top level (not nested within other folders)

## Context
Kolibri develop

**Comment by rtibbles** [comment]
Fixed in #9555

**Comment by rtibbles** [comment]
Reopening for develop as merge from 0.15 into develop does not resolve this issue due to refactor.
