### ISSUE TITLE
consistently styled sub-navs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#956]
Current unstyled links:

![image](https://cloud.githubusercontent.com/assets/2367265/23178443/478f9cfa-f81f-11e6-91ef-ae5c0f2e0842.png)

Intended design: 

![image](https://cloud.githubusercontent.com/assets/2367265/23178496/7c3f2be6-f81f-11e6-9a34-b6c5d51b749c.png)

(see https://projects.invisionapp.com/share/S7A3FGVW9#/screens/215056232)

Additionally, links should always be active and go back to the "root" item, even on the current section.

**Comment by christianmemije** [comment]
Will come in handy: https://josephuspaye.github.io/Keen-UI/#/ui-tabs

**Comment by indirectlylit** [comment]
still needs a couple updates:

* remove background colors
* make them consistent widths

**Comment by indirectlylit** [comment]
also noticing that issue where resizing the window is causing the underline to change shape length inappropriately. Might be something that needs a PR upstream?

Looks like keen's got it's own version of the responsive mixin! https://github.com/JosephusPaye/Keen-UI/blob/master/src/mixins/RespondsToWindowResize.js

**Comment by indirectlylit** [comment]
we should style sub-navs in all plugins using the same core widget. Likely, this will need to be a new, custom widget given that none of our existing options are free of issues.

**Comment by christianmemije** [comment]
Addressed in #1475 :champagne:
