### ISSUE TITLE
Closing and opening of side nav bar does not resize content

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#957]
this happens specifically on larger (desktop) views.

likely relates to this code in _core-base.vue_:

```javascript
      paddingForNav() {
        if (this.mobile || (this.tablet && !this.navShown)) {
          return 32;
        }
        return this.navWidth + 32;
      },
```

**Comment by rtibbles** [comment]
I think this might also be fixed by using some element query code inside the content renderer wrapper and the content renderers themselves (which would be freakin' awesome!)

**Comment by indirectlylit** [comment]
I think it's simpler than that:

```javascript
 if (this.mobile || !this.navShown) 
```

(note, @christianmemije  removed some of the special-case tablet vs desktop behaviors.
