### ISSUE TITLE
Research benefits & LOE of moving common code to package

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#9589]
## Observed behavior

[Follow-up on this comment](https://github.com/learningequality/kolibri/pull/9534#discussion_r908967139) - overall, it may be worthwhile to consider moving some common (although not core) code out of our default front-end bundle.

The idea being that if we expose this code in a package, then when a plugin uses common code, it will be bundled with that plugin's bundle. Conversely, a plugin that does not use some common code will have it shaken out of their builds. 

So - we should see a significant reduction in the size of the default frontend build which is loaded on every page along with a relatively small increase to each plugin's build size.

### Thoughts on differentiating between "core" and "common"

@rtibbles said:

> "What do we think we need to expose, and are prepared to support for people outside Learning Equality building frontend plugins for Kolibri?"

If you take this on and don't feel comfortable deciding on what to move and what not do, prepare and schedule a meeting with the likes of @marcellamaki @rtibbles and @nucleogenesis to walk through the core API spec and to decide on what should go where.

## Acceptance Criteria

- [x] A new package is created in Kolibri called `kolibri-common`
- [ ] The core API spec is reduced in size
- [ ] Provide before & after outcomes for the production and dev build sizes

**Comment by rtibbles** [comment]
Closing in favour of #5488
