### ISSUE TITLE
Importing and syncing facilities in Kolibri is not working across my devices even if we are both connected on the same network

### ISSUE THREAD

**Issue by Absoft002** [learningequality/kolibri#9594]
## Observed behavior
 If I try to import a facility, it does not work. This is what it shows me on the screenshot below.
![image](https://user-images.githubusercontent.com/91900905/183657108-189cb541-e068-42fa-af0a-c09cc18f4b7e.png)

…

## Errors and logs

…

## Expected behavior
That is should have imported the facilities and also sync the facility on the server with other facilities

…

## User-facing consequences

…

## Steps to reproduce

…

## Context

…
![sync-import screenshot](https://user-images.githubusercontent.com/91900905/183658822-8155b3cf-67cd-4fff-96b3-9fe96a3e5a4b.jpg)

**Comment by Absoft002** [comment]
Sorry I forgot to add that I also use the Raspberry Pi with the internet-in-a-box to provide local network

**Comment by holta** [comment]
Some Context:

- @Absoft002 is trying to "IMPORT FACILITY" into Kolibri 0.15.6 running on [Internet-in-a-Box](https://internet-in-a-box.org) (that's a Raspberry Pi 4, running Raspberry Pi OS).
- The Kolibri facility (that he's trying to import) is on a Windows laptop (that is also running Kolibri 0.15.6).
- He suspects "IMPORT CHANNEL" might work.  But he wants "IMPORT FACILITY" to also work, in preparation for an important Kolibri training they're hoping to teach next week.
- He is concerned that Kolibri's port 8080 on the Windows laptop might possibly be related to the problem, as Internet-in-a-Box / Raspberry Pi's Kolibri is running on port 8009.  I don't know if that's related.
- He is in Cameroon, where electrical issues are very challenging.
- Internet connectivity is also very challenging, but he can allow me to connect remotely over `ssh` to this Internet-in-a-Box if more diagnostics are needed?  (And/or if any workarounds need to be attempted?)

Are they any log files or diagnostics @Absoft002 and I can provide to Kolibri to help understand &mdash; what's appears to be going wrong and why?  Many Thanks !!

**Comment by holta** [comment]
I've tried to clarify the [above troubleshooting context](https://github.com/learningequality/kolibri/issues/9594#issuecomment-1209410801) with a bit more detail.

Thanks also to @Absoft002 who tightened up the subject line (he meant "Kolibri" not "Kolibri Studio" !)

**Comment by holta** [comment]
Question:

Is it possible that "IMPORT FACILITY" functionality might need additional work, similar to but above-and-beyond the recent improvements[*] below?

- #9455
- PR #9533

[*] The above recent improvement is now part of Kolibri 0.15.6

**Comment by bjester** [comment]
> He is concerned that Kolibri's port 8080 on the Windows laptop might possibly be related to the problem

Is the device with IP address 192.168.137.87 shown in the screenshot the Windows laptop?

**Comment by Absoft002** [comment]
> > He is concerned that Kolibri's port 8080 on the Windows laptop might possibly be related to the problem
> 
> Is the device with IP address 192.168.137.87 shown in the screenshot the Windows laptop?

Yes Sir, it is.

**Comment by rtibbles** [comment]
> He suspects "IMPORT CHANNEL" might work. But he wants "IMPORT FACILITY" to also work, in preparation for an important Kolibri training they're hoping to teach next week.

It would be useful to confirm or disprove this suspicion - when we made the fixes in #9533 we did not restrict ourselves to content import flows only, so it was meant to fix all peer to peer interactions when servers are prefixed, however, it's possible that this flow might have slipped through.

One thing is that it seems that the addresses have been manually added, so if they are grayed out it means that Kolibri is not able to access them via the network - if this is different between content import and facility import this would point to an issue similar to the one that has arisen before. If not, then it seems there is probably some sort of network issue that is to blame.

**Comment by holta** [comment]
> > He suspects "IMPORT CHANNEL" might work. But he wants "IMPORT FACILITY" to also work, in preparation for an important Kolibri training they're hoping to teach next week.
> 
> It would be useful to confirm or disprove this suspicion - when we made the fixes in #9533 we did not restrict ourselves to content import flows only, so it was meant to fix all peer to peer interactions when servers are prefixed, however, it's possible that this flow might have slipped through.

@rtibbles (and @bjester) thanks for explaining!

@Absoft002 please respond to @rtibbles's question above &mdash; fully verifying that "CHANNEL IMPORT" does-or-does-not work (importing any channel into Internet-in-a-Box, from your Windows laptop).

> One thing is that it seems that the addresses have been manually added,

No.  Addresses were not manually added.  Kolibri scans for these addresses, but they remain forever grayed out.

> so if they are grayed out it means that Kolibri is not able to access them via the network - if this is different between content import and facility import this would point to an issue similar to the one that has arisen before. If not, then it seems there is probably some sort of network issue that is to blame.

Could this be a firewall issue of some kind ??

**Comment by holta** [comment]
I connected remotely to his Internet-in-a-Box, and the "Gray Spinning Forever" syndrome applies to all my attempts to import a CHANNEL _as well as_ all attempts to import a FACILTY.

@Absoft002 will hopefully reconfirm.  So it appears that a local/LAN import of a Kolibri Channel is also not working.

Regardless whether the Windows laptop is connected to the Internet-in-a-Box over Ethernet, or even more directly via the Internet-in-a-box's WiFi hotspot, the "Gray Spinning Forever" syndrome persists.

Anything else we should try?

**Comment by Absoft002** [comment]
> > He suspects "IMPORT CHANNEL" might work. But he wants "IMPORT FACILITY" to also work, in preparation for an important Kolibri training they're hoping to teach next week.
> 
> It would be useful to confirm or disprove this suspicion - when we made the fixes in #9533 we did not restrict ourselves to content import flows only, so it was meant to fix all peer to peer interactions when servers are prefixed, however, it's possible that this flow might have slipped through.
> 
> One thing is that it seems that the addresses have been manually added, so if they are grayed out it means that Kolibri is not able to access them via the network - if this is different between content import and facility import this would point to an issue similar to the one that has arisen before. If not, then it seems there is probably some sort of network issue that is to blame.

"IMPORT CHANNELS" work well with 'Kolibri Studio (Online)' and 'Attached drive or memory Card'. But does not work well with 'Local Network or internet'.

**Comment by rtibbles** [comment]
> Could this be a firewall issue of some kind ??

It's a possibility - we use PyZeroConf to detect other Kolibri devices on the network, and then verify that we can create a network connection to them by connecting to the `api/public/info/` endpoint on the Kolibri device - this is why previously there were issues with prefixed servers, because we were failing to properly include the prefix in the information broadcast over PyZeroConf, and then include that in the URL.

One other thing to just double check - are all the Kolibri devices being used here updated to 0.15.6? The updates released there require all devices to be upgraded, not just the initiating one.

**Comment by holta** [comment]
> are all the Kolibri devices being used here updated to 0.15.6?

Yes.  All machines (Internet-in-a-Box on Raspberry Pi OS, and also the Windows laptop) are running Kolibri 0.15.6

**Comment by bjester** [comment]
To rule out firewall issues on the Windows laptop side, testing the connection from the Raspberry Pi to the Windows laptop would be great. Since we already determined the IP of the Windows laptop, running this on the Pi should return some JSON:
```
curl "http://192.168.137.87:8080/api/public/info/"
```

**Comment by holta** [comment]
> curl "http://192.168.137.87:8080/api/public/info/"

The above command hangs.

This command also hangs:

```
curl "http://192.168.1.120:8080/api/public/info/"
```

I tried both IP addresses, as it appears @Absoft002 changed to a different DHCP in his building in Cameroon.  Screenshot to confirm the "Gray Spinning Forever" problem is identical, no matter the networking cables or WiFi connection direct to Internet-in-a-Box:

![image](https://user-images.githubusercontent.com/2458907/183703092-fc3fb7b1-7edd-4d41-9195-11dddd146167.png)

**Comment by bjester** [comment]
Okay! So that sounds like a firewall issue on the Windows laptop to me. I'm not a Windows expert, but Windows itself and some anti-virus programs have firewalls. Our Kolibri documentation has a [few comments](https://kolibri.readthedocs.io/en/latest/manage/get_support.html?highlight=firewall#firewalls) regarding firewalls

**Comment by holta** [comment]
> sounds like a firewall issue on the Windows laptop

Bingo, Thank you!

> It's a possibility - we use PyZeroConf to detect other Kolibri devices on the network, and then verify that we can create a network connection to them by connecting to the `api/public/info/` endpoint on the Kolibri device - this is why previously there were issues with prefixed servers, because we were failing to properly include the prefix in the information broadcast over PyZeroConf, and then include that in the URL.

QUESTION:

Several people spent many hours (days might be most honest ;) getting to the bottom of this.

Would Kolibri consider improving its user interface below perhaps &mdash; so that in future people don't again waste hours/days every time &mdash; fighting this same battle?

![image](https://user-images.githubusercontent.com/2458907/183738670-4a78f005-4f3b-4441-99e6-634e76ea9eb1.png)

- e.g. a simple reminder that "You may need to **turn the firewall off** on the _other_ [source] machine" might save people days (or weeks) of headaches.  If you want to get fancy, with a link to the long-form documentation that @bjester mentioned?

- e.g. a deluxe warning would entail Kolibri auto-detecting that it's getting stuck (the "Gray Spinning Forever" syndrome is a clear pattern, with the source machine being partially detected, but staying grayed out, "spinning forever").  In any case, the UI/UX could very much use an explanation of what's happening (right there in the pop-up) if Kolibri might consider this in a future version!

**Comment by bjester** [comment]
Thank you @holta, I added a [followup issue](https://github.com/learningequality/kolibri/issues/9598). I definitely think we can add more visibility in that address selection modal.

**Comment by holta** [comment]
Many Thanks Blaine & Richard for all your help!

If peer sync'ing becomes practical + understandable for regular people (not just networking/firewall gurus like yourselves!) that would be *incredible* as part of Kolibri 0.16+ ✅

**Comment by holta** [comment]
@bjester & @rtibbles

FYI this ongoing work in Cameroon appears to be really going places — though people don't yet understand this rural/indigenous linguistics survey that Internet-in-a-Box is helping them to make happen — more about that later if you or Learning Equality are interested:

https://twitter.com/internet_in_box/status/1558055160273944576
