### ISSUE TITLE
Use translated string for user kind in the user table

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9600]
## Observed behavior

In the user table component, we render visually hidden user kind for assistive technologies:

https://github.com/learningequality/kolibri/blob/82ae0b3997943d6d349080b0df80c10c8bb8c1fe/kolibri/plugins/facility/assets/src/views/UserTable.vue#L89-L91 

It is supposed to convey the same information as `aria-hidden` badge (e.g. _Super admin_):

![Screenshot from 2022-08-11 13-04-47](https://user-images.githubusercontent.com/13509191/184119999-c3a5332e-a33e-4187-b098-fcbc939e5513.png)

https://github.com/learningequality/kolibri/blob/82ae0b3997943d6d349080b0df80c10c8bb8c1fe/kolibri/plugins/facility/assets/src/views/UserTable.vue#L78-L87

However, the visually hidden `<td>` only shows an untranslated constant (e.g. _superuser_):

![Screenshot from 2022-08-11 13-13-07](https://user-images.githubusercontent.com/13509191/184121141-d2a9ae43-dc79-449b-b8d6-7b2d1c5e8622.png)

## Expected behavior

Instead of rendering `user.kind` constant, we need to render translation corresponding to it (the same one as the text shown in badges)

## Comments

There is already a translation map implemented in `UserTypeDisplay`

https://github.com/learningequality/kolibri/blob/82ae0b3997943d6d349080b0df80c10c8bb8c1fe/kolibri/core/assets/src/views/UserTypeDisplay.vue#L39-L48

Ideally, it'd be extracted to common utilities or constants and then imported to all places that need to use it.

## User-facing consequences

Worse user experience for people using screenreaders who will hear raw constant value instead of user-friendly and properly translated text.

## Steps to reproduce

This can be seen at more places where `UserTable` is used. One of them is the facility users page. To see the table, sign-in as admin and go to _/facility/#/users_. Preview markup.

## Context

- Kolibri version: Kolibri 0.16.0.dev0+git.20220811104159
- Operating system: Ubuntu 20.04.3 LTS
- Browser: Chrome Version 104.0.5112.79 (Official Build) (64-bit)

**Comment by radinamatic** [comment]
Thank you @MisRob, great catch and a good reminder for me to turn NVDA on while I do i18n testing! 😅

**Comment by nucleogenesis** [comment]
Just checked and this is the case in 0.15 - so I've added it to the planned patch 6 milestone

**Comment by rtibbles** [comment]
Fixed in #9664
