### ISSUE TITLE
Immersive back button does not return to search results

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9622]
## Observed behavior
After filtering resources down using a search, if you click into a specific resource, then exit using the 'Go back' button in the immersive toolbar, it returns you to main Library page, rather than back to the context of your search.

This appears to be because the link to the resource itself is not encoding the search parameters.

## Expected behavior
Navigation should preserve the search parameters so that you are returned back into the context of the search.

## User-facing consequences
Confusion, losing place in search.

## Steps to reproduce
Use any search filter.
Click on a resource.
Press the immersive back button.
Get returned to the main Library page.

## Context
 * Kolibri version: Develop branch

**Comment by pcenov** [comment]
Hi @rtibbles using the Back button is now functioning correctly as described. I'll just make a couple of notes for related issues which perhaps should also be considered:

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Closing a folder accessed via the search results doesn't bring the user back to the search results. This is valid for both the main search and the search from within a folder and is also quite confusing | https://user-images.githubusercontent.com/79847249/207330134-52e7499e-bfec-4d5f-936a-81d88486dbf5.mp4 |
:-------------------------:|:-------------------------:
| The 'View as list' setting is not preserved after coming back | https://user-images.githubusercontent.com/79847249/207332482-7d193c63-a4ab-4c29-9b28-6e6c4805272a.mp4 |
:-------------------------:|:-------------------------:

**Comment by rtibbles** [comment]
Have addressed both these issues in the referenced PR.
