### ISSUE TITLE
Mobile view - Not truncated texts and missing header section

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9624]
## Observed behavior
See the attached screenshots. Tested in real devices as well as using Chrome's dev tools emulator.

## Steps to reproduce the issue
1. Install the latest develop (0.16) build
2. Go to the Library > Browse channel

## Screenshots
Longer resource titles are not truncated:

![2022-08-15_15-08-42](https://user-images.githubusercontent.com/79847249/184643196-bc246d80-9f86-4fdb-8b1e-d4d06a3f8d0e.png)

Missing channel header and channel/folder title not being truncated:
![2022-08-15_15-02-23](https://user-images.githubusercontent.com/79847249/184643638-0a4857ff-7fc6-4e8c-a650-20116f85c1e4.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by Cvanshulll** [comment]
@pcenov I want to work on this issue. Can you assign this to me?

**Comment by MisRob** [comment]
Hello @Cvanshulll, you're welcome to take this on. Please let me know as soon as you start working on it and I will assign you the issue. If you haven't done so already, please have a look [at our developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html).
