### ISSUE TITLE
Add guard to /library when no resources are added.

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9625]
## Observed behavior
Currently on a partner instance, there are no loaded resources, but `/library` does not redirect correctly, although `/home` does. 

## Errors and logs
Perpetual loader

## Expected behavior
When there are no resources added to a Kolibri instance, redirect to "No resources available page" (see home page guard for reference).

## User-facing consequences
Confusion, concern that something is broken

## Steps to reproduce
This can be reproduced by going to the /library page on a Kolibri facility with no resources added to the library

## Context
Kolibri 0.15

**Comment by rtibbles** [comment]
Fixed in #9635
