### ISSUE TITLE
Check 0.16 onboarding strings

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#9626]
Follow up issue from https://github.com/learningequality/kolibri/pull/9534.

## Observed behavior
In the 0.16 setup wizard we changed almost all the instances of the word ``facility`` into ``learning facility`` to give better context for localization, but [there may be some that were not changed in #9534](https://github.com/learningequality/kolibri/pull/9534#issuecomment-1211322082). This change is applicable only to the setup wizard pages where we have no screen space concerns, while in the actionable elements like buttons in the rest of the UI the string will remain just ``facility``. 

![183448291-45ddb12c-edf1-408d-8987-d8e5c7b03d7a](https://user-images.githubusercontent.com/1457929/184961085-814287e7-89e3-48f9-ab24-c74e7a22a2b9.png)

### Figma designs

Import facility: [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A672) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1833)
Loading Facility: [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A793) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1842) [Mobile 2](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1851)
Select super admin: [Desktop](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A809) | [Mobile](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1%3A1815)

## Errors and logs
…

## Expected behavior
All onboarding (setup wizard) pages use ``learning facility`` instead of just ``facility``.

## User-facing consequences
…

## Steps to reproduce
…

## Context
 * Kolibri version: 0.16

**Comment by camperjett** [comment]
@radinamatic I would like to take up this issue

**Comment by rtibbles** [comment]
Hi @camperjett - you are welcome to take a look at this - this would be on the develop branch, confirming that we have not missed any instances of this. Please search for all instances of `facility` in user facing strings *in the setup wizard* and ensure that we have updated to `learning facility`.

**Comment by 10kartik** [comment]
Hello @camperjett, are you working on this issue? else I'm interested to contribute for the same.

**Comment by MisRob** [comment]
Hi @10kartik, thank you for your interest. As we haven't heard from @camperjett for some time, and we will need to have this ready before the next major release, if you're interested, you're welcome to tackle this issue. If you could let me know as soon as you start working, that'd be helpful so we know that it's in progress. Otherwise, we will assign this to one of the core team members in the next couple of weeks.

**Comment by 10kartik** [comment]
Yeah @MisRob, I'd like to give it a try! I'll try to explore more around and fix this issue. Thanks!

**Comment by MisRob** [comment]
Great, thanks

**Comment by MisRob** [comment]
@10kartik We realized that this might be hard to test and preview due to some work in progress on `develop` and also because of design access. It's not that it would be impossible, though if you haven't started working on this yet, I'd recommend choosing another issue.

**Comment by 10kartik** [comment]
Cool @MisRob, I'll search for another issue.. Thanks!
