### ISSUE TITLE
Decrease syncing chunk size to reduce memory load in Morango's buffer API

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9677]
## Observed behavior

@nucleogenesis's testing on migrating a large database to our cloud Kolibri infrastructure (BCK) encountered increased memory usage when transferring data. This occurred on the server side of a push sync, where Morango POSTs buffers to the API. It resulted in Kolibri getting OOM killed and a 502 error on the client side.

## Expected behavior

Reducing the chunk size a little bit should keep the memory load more stable and should decrease the likelihood our Kolibri application gets OOM killed.

## User-facing consequences

Sync clients may encounter 502 errors or requests that "hang" forever.

## Steps to reproduce

1. Sync a large dataset
2. Monitor memory usage on the server side of the sync

## Context

0.15+

**Comment by bjester** [comment]
I will also integrate https://github.com/learningequality/morango/pull/174 with this change

**Comment by rtibbles** [comment]
Fixed in #9714
