### ISSUE TITLE
Scope & Design: Handling of missing resources in Lessons in the Syncing Era of Kolibri

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#9697]
## Observed behavior

While @akolson and I investigated #9412 we found a quick solution on the front-end but then considered how we may resolve the issue that caused it on the back-end.

The issue there being that a Lesson is on the device, but it points to a resource that is no longer on the device. This broke the side panel in one instance, but Samson and I discussed how the fact that we were getting back a "Resource" that pointed to nothing is probably undesirable.

**However** -- in discussion with Richard we came to the thought that perhaps this data _should_ be available to the front-end as we may want to prompt users directly that the content is not available, but it _is indeed_ in their lesson. We then should tell the user if they can acquire the content now or - if not - how they might be able to acquire the content (ie, "You may need to connect to the same network as your facility administrator, or another peer in your class, to acquire this content" if they're not currently finding any peers).

## Next Steps (Open for discussion)

I think that this breaks down into three separate but related problems that can be addressed individually:

1) Should the user, in any case, be shown unavailable resources that are in their lessons? If so, how should they appear and what messaging should we include? Note that their "appearance" may necessarily span across the various "content cards" we have -- perhaps this behavior would be useful in other situations (ie, I've bookmarked something I no longer have on my device).

2) Should the user be given a way to quickly start downloading the content to their device if it is available? (ie, a little download icon on the card?)

3) What should we do in the case that the missing content is not currently available? How can we provide great UX to users on their best next steps in this case?

---

## Timeline

I hesitantly hope we can get this into 0.16 in full. Much of the upfront work will need to be done ideally by mid October 2022 - at which point we may then be able to get the strings and designs in well enough in time to get the feature done, if not in full, then within some patch releases.

Alternatively, if we're squeezed as we approach an imminent release data, it appears that this is handled already on the frontend gracefully (except in the one case #9412, which will be fixed in a patch to 0.15) -- so we could just release 0.16 without any of this implemented if needed, and can include it in 0.17. :crossed_fingers:

**Comment by rtibbles** [comment]
This was fixed for coaches and learners in #8677
