### ISSUE TITLE
Change facility: Set a new super admin

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#9725]
In https://github.com/learningequality/kolibri/pull/9715, _Choose a new super admin_ page and related state machine updates have been implemented. When a user chooses a new super admin on that page, we decided that we will only save the new super admin's ID to the machine's context `newSuperAdminId` attribute but won't actually set the new super admin yet on the source facility. That should rather happen together with all other updates related to changing facility during the syncing step (`syncChangeFacilityState`). This issue is here so that we don't forget this needs to be implemented in `syncChangeFacilityState`.

**Background**
This is a general approach we have adopted for all updates to be done when changing facilities for the sake of simplicity since we will know that all updates will happen during a single step, and also to prevent unnecessary actions or inconsistencies when a user changes their mind, go back in the flow, etc.

**Comment by jredrejo** [comment]
This was fixed in #9760
