### ISSUE TITLE
Previewing resource shows Level metadata as alphanumeric IDs instead of their string names

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9731]
Extracted from https://github.com/learningequality/studio/issues/3664

## Observed behavior
Incorrectly displayed metadata names for Levels in Kolibri-- alphanumeric metadata IDs are shown instead:

![2022-09-21_17-06-35](https://user-images.githubusercontent.com/79847249/191549491-875bcae3-9e8d-4292-8c63-46354b55da09.png)

## Steps to reproduce the issue
1. Go to https://hotfixes.studio.learningequality.org/en/accounts/#/ and sign in
2. Go to the channel editor for a public channel and fill in the Level metadata for a resource
3. Publish the channel
4. Import the channel into Kolibri (you'll have to use the URL flow with https://hotfixes.studio.learningequality.org)
5. View the resource in Kolibri
6. Observe Level metadata shows incorrectly

## Usage Details
 - OS: Windows 10
 - Browser: Chrome
 - URL: https://hotfixes.studio.learningequality.org/
 - Kolibri: 0.15.6

**Comment by rtibbles** [comment]
Fixed in #9736
