### ISSUE TITLE
Create "Sync Schedules" Page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9772]
### Overview 

Add a new page, "Sync Schedules", that lists all scheduled syncs and their corresponding devices, and provides a way to add, edit or delete these syncs. The table should also display the sync status. It should also add the dropdown menu option on the Facility and Device pages, to add "manage sync schedules" 

_Note_: This page will be shared between the facility and device plugins

### Figma
[Link to Specs](https://www.figma.com/file/XHO5zXznOD3WXcxcA6d6Zv/Scheduled-sync-2022?node-id=0%3A1)
<img width="611" alt="Screen Shot 2022-10-14 at 11 59 57 AM" src="https://user-images.githubusercontent.com/17235236/195890522-d5db5494-5577-42dd-a007-4826add9a228.png">
<img width="826" alt="Screen Shot 2022-10-14 at 11 59 34 AM" src="https://user-images.githubusercontent.com/17235236/195890527-7ab36aa0-b351-4d2a-9072-a3cd57484a30.png">

<img width="830" alt="Screen Shot 2022-10-14 at 11 22 18 AM" src="https://user-images.githubusercontent.com/17235236/195883099-43dc63c1-5139-4b7b-8d83-1a8a6e660903.png">

### Data
The data from the backend that is passed to create this page should be: 
* loading all existing scheduled syncs for this facility from the backend
  * Currently all task fetching on the frontend is concerned with getting currently queued, running, or completed tasks. (One example here for getting the tasks for a specific queue: https://github.com/learningequality/kolibri/blob/87f12da247caf366be7df2b1ee7cfda063926024/kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js#L24).
  * We would need to enhance the tasks list endpoint to filter down to:
    1. Only scheduled tasks
    2. Only tasks for a specific facility 
* loading the connection status of KDP and all peer devices  
  * There is already frontend code for handling fetching the peer devices: https://github.com/learningequality/kolibri/blob/87f12da247caf366be7df2b1ee7cfda063926024/kolibri/core/assets/src/views/sync/SelectAddressModalGroup/api.js#L114 - unfortunately, three is not currently any code for checking if we are able to connect to KDP

### Accessibility 
Use existing KComponents (i.e. `KButton`) or Kolibri components as relevant for table, which will ensure page is navigable by keyboard.

### Out of Scope
Adding interactions (i.e. creating the modals that open, or creating the page for editing each sync) is not part of this issue, and will be addressed in follow up issues. The buttons for "Add Device" and "Edit" should be present but disabled, so that this work can be merged in and not be broken (even if the functionality is not built yet).

**Comment by AllanOXDi** [comment]
Fixed in #9786
