### ISSUE TITLE
Device Settings Updates: Auto Download

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9781]
## Overview 

This issue is a full-stack issue that updates the Device Settings page to include a setting where the user can determine whether or not to automatically download new materials such as lessons and quizzes. **The default behavior is to download automatically**. The setting should be set to true by default, and then the user can change it. There is an additional setting which determines a maximum amount of space that Kolibri can use for auto-downloaded content.

To avoid having to create a new migration for each field, we will be using a feature branch for this project `update-device-settings`. Please make PRs to this branch, which will later be merged into develop when the feature is complete.

### Figma 

Please see [complete figma spec ](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773) for full specs of various states.

➡️ Accessibility notes: 
* The title for this section ('Auto-download') is an `<h2>`
* Please use `KComponents` to ensure that the content is properly passed on to screen readers, and that focus outlining works. 

### API changes 

The changes to the API should be made within the existing API file in the `/device` plugin: `kolibri/plugins/device/assets/src/views/DeviceSettingsPage/api.js` unless it is discovered that there would be some blocker to use this setting. As an alternative, `options.ini` could be considered.

Backend changes should include updating the model `kolibri/core/device/models.py` and related serializer `kolibri/core/device/serializers.py`

## Acceptance Criteria
- [ ]  Frontend is updated with correct strings, using existing components
- [ ]  On saving, the setting is updated on both the frontend and the backend, and a *Settings have been updated* message displays. (This snackbar should already exists and it should appear by default on a successful update to the device settings).
- [ ]  The `DeviceSettingsPage.spec.js` should be updated so that existing tests still pass (as necessary) and there should be at least one test written to cover this scenario

## References 
- [Notion project page](https://www.notion.so/learningequality/Updates-to-Device-Settings-45529cbcc4f74aeb9b19559228c97579)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#1959b753421648308fb467e21bdaa125)

**Comment by rtibbles** [comment]
Fixed in #9833
