### ISSUE TITLE
When the root folders of channels appear in search results, they appear as unadorned folder cards rather than channels

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9784]
## Observed behavior
Search can result in folders being displayed in search results. When a folder is the root folder of a channel, it does correctly link to the channel root in Kolibri, but does not display the additional channel metadata that is already available in the client side.

See the first folder here, when clicked, links to the root of the channel

![image](https://user-images.githubusercontent.com/1680573/196498119-c22a40bb-2cb7-46d1-ae00-17e9c5132c8b.png)

https://kolibri-catalog-en.learningequality.org/en/learn/#/library?channels=1e378725d3924b47aa5e1260628820b5

## Expected behavior
Root folders should display channel thumbnails etc.

**Comment by photon0205** [comment]
Hi! I would like to take up this issue

**Comment by rtibbles** [comment]
Sure! You should look at the  current implementation of Channel display in order to see how to display the channels here:
https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/views/ChannelCard.vue

(I would recommend just using this component directly as a first pass and seeing how it looks).

**Comment by photon0205** [comment]
@rtibbles if i use the ChannelCard component, then this is how it looks:
<img width="1433" alt="Screenshot 2023-03-11 at 12 33 59 PM" src="https://user-images.githubusercontent.com/99784265/224470589-90993083-1b17-4add-a3e8-0f6776866846.png">
Ans if i just use channel_thumbnails for the content not having anything in their thumbnails, then it looks like this:
<img width="1433" alt="Screenshot 2023-03-11 at 12 35 04 PM" src="https://user-images.githubusercontent.com/99784265/224470632-638f8d59-8b74-4675-8b4b-54ace25f7147.png">
Now you suggest which one should i go for

**Comment by rtibbles** [comment]
Fixed in #10231
