### ISSUE TITLE
Merge accounts - Incorrect message and behavior when changing facility

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9790]
## Observed behavior
When I attempt to change my facility as a learner I see an incorrect message that my user exists in the target facility and I am prompted to choose a different username.

## Expected behavior
The learner should be able to change the facility.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/organizations/learningequality/pipelines/kolibri-debian/builds/5203/jobs/0183fbda-239d-4c8c-8201-420d48d92d2c/artifacts/0184090a-8e30-43f9-af55-d55929fe454a
2. Modify the DB as specified in https://github.com/learningequality/kolibri/pull/9760
3. Create a learner account and sign in as the learner
4. Go to Profile and click the Change button
5. Select the target learning facility and press Continue
6. Keep pressing the Continue button at the next screens.

## Video
https://user-images.githubusercontent.com/79847249/197557533-d983ccd6-43a4-419b-b07f-5126c52f7d53.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@jredrejo @radinamatic

**Comment by jredrejo** [comment]
Blocked by #10133

**Comment by jredrejo** [comment]
Fixed with #10206
