### ISSUE TITLE
'Allow learner to mark as complete' not working in Kolibri

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#9795]
## Observed behavior
Scratch all below, my longer-term memory must be off today... 🤦🏽‍♀️ 

Not sure if it's a Studio or Kolibri issue: marking a resource as available to check as completed by learner is not working in Kolibri (tested on 0.15 and 0.16), with ``Error in v-on handler: "TypeError: this.$store.dispatch`` in the console.

0.15 | 0.16
-- | --
![make-completed](https://user-images.githubusercontent.com/1457929/197620842-9d92191a-651f-430d-9d1f-97382d708734.gif) | ![LEDev (start)  Running  - Oracle VM VirtualBox_024](https://user-images.githubusercontent.com/1457929/197597749-3b3f0d90-c892-46e4-a309-ec1c913408d2.png)

~I don't recall what was the reasoning to already include in this release the **Allow learner to mark as complete** feature in the edit modal, when no learner in Kolibri will be able to use it for at least a few months...? I'm assuming here that feature will be included in Kolibri 0.16, and if that is the case, this early inclusion is just generating a (contributing to) cognitive overload for Studio users on the edit modal that is already bursting with features and options~

~We should have though better around the UX implications, and at least include additional information string saying the feature is not yet available in Kolibri. In that case we would again have to remove it once 0.16 Kolibri is released.~

~Last but not least, there's no way we can test the feature at this time, and if I understand correctly, it can have [ramifications and cause conflicts in delicate parts of the code around completion and duration](https://github.com/learningequality/studio/issues/3758).~

## Expected behavior
Learners able to mark resource in Kolibri.

cc @bjester @rtibbles

**Comment by rtibbles** [comment]
Fixed in #9808
