### ISSUE TITLE
Facility Settings Updates: PIN usage on Learn-only Devices

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9796]
## Overview 

This issue is a full-stack issue that updates allows the Device page to be accessed on learn-only devices by entering a PIN.

We will be using a feature branch for this project `update-facility-settings`. Please make PRs to this branch, which will later be merged into develop when the feature is complete.

### Figma 

When the user picks "Device" on the menu, the modal opens and prompts for the PIN to be entered. If the correct PIN is entered, the user should be authorized to access the device page. 

<img width="830" alt="Screen Shot 2022-10-24 at 11 53 02 AM" src="https://user-images.githubusercontent.com/17235236/197570382-10f9761e-e257-440e-bce6-500c49321842.png">

**Please see [complete figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1473%3A16838) for details on states for PIN modal**

➡️ Accessibility notes: 
* Please use `KComponents` for wherever possible to ensure that the content is properly passed on to screen readers, and that focus outlining and focus shift works. (See [KDS docs](https://kolibri-design-system.netlify.app/) for more information)

### API changes 

Authentication will need to be updated to support a PIN granting access as an admin. A user should not be able to navigate directly via a URL without being prompted to authenticate, but should not have to enter the PIN twice, once when pressing "Device" in the navigation, and then again when redirected. One approach would be to save something in the session to say that it is authenticated, i.e. a 15 second cookie that can be used if the PIN has already been entered, and can be checked during navigation to the Device plugin.

Access should expire on return to Learn plugin and/or with a timeout.

## Acceptance Criteria
- [ ]  Frontend is updated with correct strings, using `KComponents`
- [ ] PIN authentication is implemented as described above
- [ ]  The `FacilitySettingsPage.spec.js` should be updated so that existing tests still pass (as necessary) and there should be at least one test written to cover this scenario

## References 
- [Notion project page](https://www.notion.so/learningequality/Updates-to-Facility-Settings-f35f3be6e5fb45fb8de0abc0d898c017)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=969%3A16669)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#1959b753421648308fb467e21bdaa125)

**Comment by rtibbles** [comment]
Fixed in #10110
