### ISSUE TITLE
Library page - An empty category modal is displayed for a category without child nodes

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9820]
## Observed behavior
If I have imported a channel from Studio in which for the Category field of a resource I have selected only the main node of a certain category e.g. 'For teachers' then in Kolibri that results in seeing an empty modal window when attempting to filter by the mentioned category.

## Expected behavior
My guess is that in that case it should be possible to filter directly by the selected category by skipping the empty modal.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/6562
2. Import a channel from https://hotfixes.studio.learningequality.org/ containing a resource with only the main node of a category selected as a Category value.
3. Go to the Library page and attempt to filter by selecting that category value.

## Screenshot

![2022-11-09_18-15-42](https://user-images.githubusercontent.com/79847249/200883033-87664072-500d-4083-86b3-87239396cea2.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by rtibbles** [comment]
This was fixed in #9839
