### ISSUE TITLE
The completion modal keeps reappearing when viewing already completed resources

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9824]
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/9814 I noticed that the completion modal keeps reappearing when viewing already completed resources. for some resources such as PDF once the completion is displayed it seemingly cannot be closed as hitting the x icon or 'Stay here' results in the modal being immediately displayed again. Valid in all supported browsers.
For resources of type exercise the completion modal is correctly displayed only once.
This issue is not being observed in the beta build without the KDS updates.

## Expected behavior
The completion modal should be displayed only once after having completed a resource.

## Steps to reproduce the issue
1. Install the the latest [beta build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta1) with the KDS updates
2. Complete a resource and then attempt to view the resource again.

## Videos
PDF:

https://user-images.githubusercontent.com/79847249/201088498-9b73fad9-9592-4ea0-afff-dd42cab956b3.mp4

Video:

https://user-images.githubusercontent.com/79847249/201088536-4851fe73-ab33-4fe2-b1c3-4ce4ff2630b1.mp4

EPUB:

https://user-images.githubusercontent.com/79847249/201088676-456f4ac6-5d2a-43e7-b19d-eb5c6bbd3849.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by marcellamaki** [comment]
Resolved with https://github.com/learningequality/kolibri/pull/9830
