### ISSUE TITLE
The completion modal doesn't appear when I mark a resource as complete

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9825]
## Observed behavior
The completion modal doesn't appear in the latest [beta build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta1)  with the KDS updates after I mark a resource as complete. This is functioning correctly in the 0.15.9-beta build without the KDS updates.

## Expected behavior
The completion modal should be displayed.

## Steps to reproduce the issue
1. Install the the latest [beta build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta1) with the KDS updates
2. Mark a resource as completed.

## Video

https://user-images.githubusercontent.com/79847249/201097353-96a7fa7d-a596-4888-8085-09f48b3e2073.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by marcellamaki** [comment]
Resolved with https://github.com/learningequality/kolibri/pull/9830
