### ISSUE TITLE
Home > Lesson - Incorrectly displayed duration labels

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9826]
## Observed behavior
The duration labels are almost entirely covering the thumbnails of the resources and are also displayed to the right side of the cards.
The issue is valid for both v0.15.9-beta and v0.15.9-beta1

## Expected behavior
To be further specified.

## Steps to reproduce the issue
1. Install the the latest [beta build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta1)
2. As a coach assign resources with set duration values.
3. As a learner go to Home > Lesson and observe the cards.

## Screenshot

![2022-11-10_14-51-58](https://user-images.githubusercontent.com/79847249/201142482-17c9bc46-ce97-4679-b426-eea71904f627.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@marcellamaki @radinamatic

**Comment by marcellamaki** [comment]
Resolve in https://github.com/learningequality/kolibri/pull/9838
