### ISSUE TITLE
Class > Lesson - Icons return to their default state after having selected 'Mark as complete'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9840]
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/9830 I noticed that if I click the 'Mark as complete' option while interacting with an assigned resource in Class > Lesson and after that I click the 'Next steps' button, then after closing the modal the icons return to their default state.
The issue can be replicated also by clicking the 'View lesson resources' icon. Sometimes the 'Bookmarks' icon also becomes disabled after such interaction.
Note that this is not replicable on the Library page.

## Expected behavior
The 'Mark as complete' option should not be displayed after having completed a resource. The 'Bookmarks' icon should not get disabled after interaction with any of the other available icons.

## Steps to reproduce the issue
1. Install the the following [build ](https://buildkite.com/learningequality/kolibri-python-package/builds/6620) 
2. While at Class > Lesson complete a resource by selecting the 'Mark as complete' option
3. Click the 'Next steps' button and then after closing the modal observe that the icons are changed back to their default state.

## Video

https://user-images.githubusercontent.com/79847249/202731081-b51facd4-79a4-4d7a-b278-d4a837739556.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Resolved in https://github.com/learningequality/kolibri/pull/9830
