### ISSUE TITLE
Content card layout overlaps

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9842]
## Observed behavior
Narrower content cards in the grid (in in-between display sizes) show overlapping content.

## Errors and logs

**Card with overlap**
<img width="200" alt="Screen Shot 2022-11-18 at 2 54 46 PM" src="https://user-images.githubusercontent.com/17235236/202791039-4075f83c-01b1-44a9-af72-5aa38a7dc1b5.png">

**Slightly wider card, title only takes up 2 lines, not 3 - no overlap**
<img width="217" alt="Screen Shot 2022-11-18 at 2 54 35 PM" src="https://user-images.githubusercontent.com/17235236/202791024-1c4405f6-d7dd-415e-91a3-946fb5f27e94.png">

## Expected behavior
Title overflow should be truncated to reduce layout conflicts, so that relevant content can be displayed without overlaps

## User-facing consequences
May be difficult to read information

## Steps to reproduce
1. Ensure you have the "Kolibri QA Channel" imported
2. Open up "Make 10, grids and number bonds"
3. Shrink the browser window enough that the cards become narrower, but not so much that the side-bar disappears. 
4. Observe the title runs into 3 lines and content begins overlapping 

## Context
0.15.x, Chrome

**Comment by JJJ62** [comment]
I am going to attempt resolving this issue

**Comment by marcellamaki** [comment]
Closed with #9868
