### ISSUE TITLE
Automatic Syncing Updates: Learners using the Android App should receive native app notifications for library syncing updates

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9843]
## Overview 

This issue is a full-stack issue that updates the Android app for learn only devices to include a native app notifications about library sync status. **Notifications for: updates in progress, updates completed, and update errors**. 

This syncing state is already reflected in the learner's sidebar and in other places throughout the app. The data and how it is accessed should be able to be easily repurposed.

### Figma 

Please see [complete figma spec ](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=bVNzyZsQkYnGNOPe-0) for full specs of various states.
<img width="874" alt="Screen Shot 2022-11-18 at 4 28 57 PM" src="https://user-images.githubusercontent.com/17235236/202806872-861d7ff9-7a60-4718-9898-8cc42a62383d.png">

## Acceptance Criteria
- [ ]  Android app is updated so that push notifications display, using the native app settings, during library content syncing

### Out of scope
Implementing banner or other push-style notifications for browser learn-only devices is not part of this issue.

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Automatic-syncing-d0a28f150b324d4da019790228117068)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=bVNzyZsQkYnGNOPe-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#8d768ab75449478783adb84732968e18)

**Comment by rtibbles** [comment]
This was released in 0.16.0.
