### ISSUE TITLE
Remote Content Browsing: Update Library Page to display other available libraries

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9852]
## Overview 

This issue is a front-end issue to update the library page to display additional network libraries. The backend for this work was set up by Richard in https://github.com/learningequality/kolibri/pull/9474. Please refer to this PR for context and instructions for testing to better understand the functionality that is in place.

### Figma 

Please see [complete figma spec ](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=CrKIgrjUb27SiVJA-0) for full specs of various states, as there are variations based on pinned/unpinned libraries, and the number of libraries available on the network.

<img width="363" alt="Screen Shot 2022-11-28 at 9 58 12 AM" src="https://user-images.githubusercontent.com/17235236/204309631-2badf5e0-c470-4c6c-9abd-cc2ecb775fc4.png">

## Acceptance Criteria
- [ ]  Library page displays on-network libraries in accordance with Figma spec

### Out of scope
Please note that searching is scoped to a user's library ONLY. The search feature of the main library page does _not_ need to be updated and should not be updated as part of this work. Only allow search of another library when they go into that library (which is covered in a separate issue). 

Connection state display is covered in https://github.com/learningequality/kolibri/issues/9859

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Browse-Libraries-dab6e6d520d642bb80ed68f3b37e93fa)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=CrKIgrjUb27SiVJA-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#0a205e75b2ea49a9be07acf15bf13b7a)

**Comment by akolson** [comment]
@AllanOXDi, Please note this is the specific task that should used to track progress on the current work you have done under remote content browsing.

**Comment by AllanOXDi** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/10111 and https://github.com/learningequality/kolibri/pull/10420
