### ISSUE TITLE
Remote Content Browsing: Explore a library

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9854]
## Overview 

This issue is a front-end issue to ensure that viewing an external library's channels works. The backend for this remote content browsing work was set up by Richard in https://github.com/learningequality/kolibri/pull/9474. Please refer to this PR for context and instructions for testing to better understand the functionality that is in place.

Theoretically, adding the `baseUrl` param should be sufficient for this to work within our existing architecture. However, this issue is to "stitch together" any missing pieces that are needed for this to work. 
* Searching and filtering should be scoped to only this library
* There are also some minor UI tweaks on the figma that will be specific to this page

### Figma 

Please see [complete figma spec ](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=zDk6ybjN91p5hH6m-0) for full specs based on the library type.
<img width="434" alt="Screen Shot 2022-11-28 at 10 45 26 AM" src="https://user-images.githubusercontent.com/17235236/204320648-e5552753-dd1e-4181-8a5a-b3d918e5ddb1.png">

## Acceptance Criteria
- [ ]  User can open any library type page from the main library page, including online server (Kolibri studio super-admin only), local server, other learn-only devices, or external storage

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Browse-Libraries-dab6e6d520d642bb80ed68f3b37e93fa)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=zDk6ybjN91p5hH6m-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#0a205e75b2ea49a9be07acf15bf13b7a)

**Comment by akolson** [comment]
Hi @marcellamaki. There are existing `SidePanelModal` and `SideFiltersModal` components and my impression is that we should reuse these for the side panel in this issue. Is this a correct assumption?

**Comment by marcellamaki** [comment]
Yes, @akolson, that's correct! The filtering panel that is present on the Library page can be reused here, as well as the channel cards. 

Then, once the user clicks into a channel, they can really see the existing Channel (aka Topics) Page. Can you confirm @rtibbles and @jtamiace? I've included the broader screenshot of the flow below in case it's helpful :) 

<img width="749" alt="Screenshot 2023-03-07 at 9 38 24 AM" src="https://user-images.githubusercontent.com/17235236/223454477-87030b55-5cc3-41ae-86ee-b58bee41e633.png">

**Comment by rtibbles** [comment]
I think the current `LibraryPage/index.vue` component can probably be reused for simplicity here. It might make the component a little more complex than might be ideal, but we can sort that out later in refactor to factor out the more complex parts.
