### ISSUE TITLE
Remote Content Browsing: Update Content Renderer for downloading and streaming

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9856]
## Overview 

This issue is a front-end issue to ensure that the content renderer correctly manages download and streaming states. The backend for this remote content browsing work is managed separately. 

This implementation depends on both the `DownloadRequests` model, which indicates the downloads on the user's device as well as the `useDevices` composable which supports remote content browsing.

### Figma 
<img width="576" alt="Screenshot 2023-02-13 at 5 11 44 PM" src="https://user-images.githubusercontent.com/17235236/218586181-3e2d5457-8bd1-481e-b3df-2c80bade754b.png">

## Acceptance Criteria
- [ ]  If a user is browsing remote content, just "watching" the content, this should display a streaming status and the 'bookmark action' should be replaced with a 'download' action
- [ ] if the user has downloaded the content to their device, they should see that it is downloaded, and still be able to bookmark the content

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Browse-Libraries-dab6e6d520d642bb80ed68f3b37e93fa)
- [Spec doc](https://www.notion.so/learningequality/Remote-Content-Browsing-Reference-Spec-s-500ab68669cb4b1fb2e752314d21f6cb)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=UZhtEmvHSEWEKomz-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#0a205e75b2ea49a9be07acf15bf13b7a)

**Comment by MisRob** [comment]
Related PR https://github.com/learningequality/kolibri/pull/10558. Some logic is mocked there though. This issue can be closed after https://github.com/learningequality/kolibri/issues/10564 is resolved.

**Comment by marcellamaki** [comment]
Confirming that after manual QA including the team session on Friday, the download icon is replaced by the bookmark icon, once the download has completed!
