### ISSUE TITLE
Remote Content Browsing: Add resource's downloadable/removable state to content card

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9857]
## Overview 

This issue is a front-end and API resource layer issue to ensure that content cards correctly display the state of content that can be downloaded to or removed from a device.

This implementation depends on both the `DownloadRequests` model, which indicates the downloads on the user's device as well as the `useDevices` composable which supports remote content browsing.

### Figma 

[Download states spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=UZhtEmvHSEWEKomz-0)

<img width="862" alt="Screenshot 2023-02-13 at 5 17 05 PM" src="https://user-images.githubusercontent.com/17235236/218587121-91ae45ec-96bf-46fb-96db-5df3e6d61b84.png">

## Acceptance Criteria
- [ ]  If a user is browsing remote content, content cards in the library should display the "download" icon
- [ ] if the user has downloaded the content to their device, they should see the menu, which opens to display an option to remove the content from the device 
- [ ] When the user removes the content from their device, they should be prompted 
- [ ] content downloaded by an admin or assigned/synced by a coach cannot be removed by a learner

## References 
- [Notion project page](https://www.notion.so/learningequality/Remote-Content-Syncing-Browse-Libraries-dab6e6d520d642bb80ed68f3b37e93fa)
- [Spec doc](https://www.notion.so/learningequality/Remote-Content-Browsing-Reference-Spec-s-500ab68669cb4b1fb2e752314d21f6cb)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922&t=UZhtEmvHSEWEKomz-0)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#0a205e75b2ea49a9be07acf15bf13b7a)

**Comment by rtibbles** [comment]
Clarification from discussion with @jtamiace - to keep the number of states simple, we will flag either 'download' or 'requested by learner', or hide things completely in the case of an admin import.

Other learner's download requests and import due to lessons and quizzes will not impact the reported status.
