### ISSUE TITLE
Class > Lesson - The 'Save to bookmarks' option gets temporary disabled

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9864]
## Observed behavior
The 'Save to bookmarks' option gets disabled after viewing an assigned resource. Valid in all supported browser. After refreshing the page the option gets enabled again.

## Expected behavior
The 'Save to bookmarks' option should not get disabled.

## Steps to reproduce the issue
1. Install the the following [build ](https://buildkite.com/learningequality/kolibri-python-package/builds/66290) 
2. While at Class > Lesson bookmark a resource by selecting the 'Save to bookmarks' option (or don't bookmark it, just viewing the resource is also enough)
3. Click the Back arrow to go back to the lesson resources page
4. Reopen the same resource and observe that the 'Save to bookmarks' option is disabled

## Video

https://user-images.githubusercontent.com/79847249/203336224-f1302a55-abf0-4ae2-a652-34d9858914ee.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki

**Comment by marcellamaki** [comment]
Thanks @pcenov! We'll take a look at this!

**Comment by rtibbles** [comment]
Fixed in #9865
