### ISSUE TITLE
Add prefer-const linting rule to kolibri-tools

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9867]
## Observed behavior
I quite frequently see uses of `let` in cases where the variable will never be reassigned. In this case `const` should be preferred for the variable declaration.

ESLint has a `prefer-const` rule https://eslint.org/docs/latest/rules/prefer-const that has some autofixing capability, so this could be added and any existing usages fixed.

Note it would be best to wait until #9698 has been merged to do this.

**Comment by AbrahamOsmondE** [comment]
Hi! :)

I understand that this issue is still waiting for #9698 to be merged first, but would it be possible for me to take this up? I don't mind having to redo some stuff once the #9698 has been merged

**Comment by rtibbles** [comment]
I think it may be possible to add this rule even without #9698 being merged, so please do go ahead and give this a go!

**Comment by rahulhumie** [comment]
i wanted to work on the issue please assign me the issue

**Comment by AbrahamOsmondE** [comment]
> I think it may be possible to add this rule even without #9698 being merged, so please do go ahead and give this a go!

Thank you! Any advice on how I might be able to get the issue assigned?

**Comment by MAYANKpandey14** [comment]
Hey, is someone working on this issue ?

**Comment by rahulhumie** [comment]
No

**Comment by MAYANKpandey14** [comment]
Should I wait for https://github.com/learningequality/kolibri/pull/9698 to get approved ?
One of the test it has failed is this .
`Linting of JS, Vue, SCSS and CSS files...................................Failed  `

**Comment by MisRob** [comment]
> Thank you! Any advice on how I might be able to get the issue assigned?

@AbrahamOsmondE I think some of the core team members need to assign you. So I just did it as you were the first one to show interest. Please let us know in case you aren't working on it.

@MAYANKpandey14 @rahulhumie Thank you for your interest. As just mentioned, I assigned the issue to @AbrahamOsmondE for now. We are always grateful for contributions and if you'd like to work on Kolibri, there are many other issues open. It may be helpful to filter them by "help wanted", "good first issue", or "beginner friendly" tags.

**Comment by AbrahamOsmondE** [comment]
> > Thank you! Any advice on how I might be able to get the issue assigned?
> 
> @AbrahamOsmondE I think some of the core team members need to assign you. So I just did it as you were the first one to show interest. Please let us know in case you aren't working on it.
> 
> @MAYANKpandey14 @rahulhumie Thank you for your interest. As just mentioned, I assigned the issue to @AbrahamOsmondE for now. We are always grateful for contributions and if you'd like to work on Kolibri, there are many other issues open. It may be helpful to filter them by "help wanted", "good first issue", or "beginner friendly" tags.

Hi @MisRob , I'm currently trying to setup the development environment and I'm facing issues on the following [section](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#install-node-js-yarn-and-other-dependencies) when trying to setup nodeenv on the virtual environment. I've tried looking for my error on google but can't seem to find it. May I know where might be a good place to ask?

**Comment by MisRob** [comment]
@AbrahamOsmondE Thank you for asking, it'd be fine to post the error here and we'll do our best to figure it out with you

**Comment by AbrahamOsmondE** [comment]
> @AbrahamOsmondE Thank you for asking, it'd be fine to post the error here and we'll do our best to figure it out with you

@MisRob I've been getting the following error when doing `nodeenv -p --node=10.17.0` while having the kolibri pyenv up and running.
<img width="1046" alt="Screenshot 2023-01-25 at 9 38 31 AM" src="https://user-images.githubusercontent.com/82792334/214468728-55e422de-3960-4733-92f9-01f498c48a47.png">

I used homebrew to install a node with version 16.x as mentioned in the document. Do let me know if any other detail is required from me. Thank you!

**Comment by MisRob** [comment]
@AbrahamOsmondE, is this problem specific to Node v10 only? Are you able to proceed with the setup using Node v16?

**Comment by AbrahamOsmondE** [comment]
> @AbrahamOsmondE, is this problem specific to Node v10 only? Are you able to proceed with the setup using Node v16?

@MisRob no the problem persists even when trying to use Node v16. Also tried using Node v19 and it didn't work too

**Comment by MisRob** [comment]
I'm sorry to hear that. Unfortunately, I have no idea what's causing this problem, and I haven't heard yet from anyone who'd experienced this error.

The only idea I've gotten so far is that perhaps playing around with different virtual environment tools may be helpful? For example, I use `venv` and `nvm` and not `nodeenv`. I don't know if this could help, and I don't have Mac myself.

**Comment by MisRob** [comment]
@AbrahamOsmondE ^

**Comment by MisRob** [comment]
@AbrahamOsmondE Not related to that particular error, but if you get further in the setup process, one of my colleagues shared that instead of this step https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#checkout-release-v0-15-x (which also requires switching to Node v10 temporarily), it should be simpler to run `kolibri manage provisiondevice`. That way, we only need to make sure that Node v16 works.

**Comment by Gauravjadhav22** [comment]
i wanted to work on the issue please assign me the issue

**Comment by MisRob** [comment]
Taking into account that we didn't hear back from @AbrahamOsmondE for some time, I'm removing the assignment. If someone wants to work on it, please let me know as soon as you start coding and I will make a new assignment.

**Comment by akila-i** [comment]
Hi @MisRob , I have been in contact with Learning Equality for about last 2 weeks and I have successfully got setup Kolibri on my local computer. I land on this good-first-issue and I'd love to work on this if you could assign this issue to me.
Thanks in advance.

**Comment by MisRob** [comment]
Hello @Akila-I, thank you for your interest. You're welcome to take this on.

**Comment by akila-i** [comment]
Hi @MisRob , Thanks for assigning the issue to me.
I have imposed the prefer-const ESLint rule and made the necessary changes in the code.
Now running `npm run lint-frontend` exits without an error or warning.
Is there any other test do I need to run before make a PR.

**Comment by akila-i** [comment]
@rtibbles , @MisRob  I have made a PR #10130 . Maybe we can review there. Please do correct me if anything is not in the order.

**Comment by MisRob** [comment]
Thank you for your contribution, @Akila-I. Yes, we will review changes in the PR.
