### ISSUE TITLE
Class > Lesson - Resources get displayed as bookmarked while they are not

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9869]
## Observed behavior
After I bookmark a resource and I click on another resource in the lesson and then go back and forth then eventually the other resource is also displayed incorrectly as bookmarked. 

## Expected behavior
The 'Save to bookmarks' option should not get incorrectly enabled.

## Steps to reproduce the issue
1. Install the the following [build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta3) 
2. While at Class > Lesson bookmark a resource by selecting the 'Save to bookmarks' option.
3. Click the Back arrow to go back to the lesson resources page.
4. Open another resource which has not been bookmarked.
5. Go back and open the bookmarked one.
6. Go back to the other resource and observe that it gets bookmarked.

## Video

https://user-images.githubusercontent.com/79847249/203820482-de451a28-c35e-42d8-a38c-8f956ea3abfd.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@marcellamaki @radinamatic

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/9874
