### ISSUE TITLE
Library > Channel > Folder - Categories returning 0 results should not be available as filtering options

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9872]
## Observed behavior
When I open a specific folder and then I apply a filter by Category I am seeing 0 results returned for the applied filter.

## Expected behavior
Categories returning 0 results should not be available as filtering options

## Steps to reproduce the issue
1. Install the the following [build ](https://github.com/learningequality/kolibri/releases/tag/v0.15.9-beta3)
2. Import the following channel from Hotfixes: koluv-zuvol
3. Go to Library > Channel > Audio folder and filter by School visual art

## Video

https://user-images.githubusercontent.com/79847249/204321649-dcc48683-7532-44ff-971a-765e98eb59c9.mp4

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@marcellamaki this one was noticed last week by @radinamatic and I was able to reliably replicate it today.

**Comment by marcellamaki** [comment]
@radinamatic @pcenov corresponding PR is ready for testing: https://github.com/learningequality/kolibri/pull/9875

**Comment by rtibbles** [comment]
Fixed in #9875
