### ISSUE TITLE
Channel import generates update query that affects the entire contentnode table

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9873]
## Observed behavior

On Kolibri Data Portal (KDP), we've observed lengthy database update queries that set learning activities based on the kind of a content node. On KDP, there are many channels, and those along with new channels are imported automatically, which causes recurring and lengthy query times (on average 7 minutes, but upwards of 30 minutes has been observed)

![Screenshot from 2022-11-28 09-05-05](https://user-images.githubusercontent.com/819838/204338306-d0db486e-b3af-482a-90af-a53411aced93.png)

## Expected behavior

Importing a channel only generates updates to the channel that was imported, and avoids blanket update queries

## User-facing consequences

As a sysadmin, the frequency of these may cause significant database churn that can lead to database bloat. Other enterprise users of Kolibri may face similar issues if they import a significant number of channels on a regular basis.

## Context

Kolibri 0.15+ with postgresql
Google Cloud

**Comment by rtibbles** [comment]
Fixed in #9876
