### ISSUE TITLE
Learn page styling defaults to non-large window size view on page load

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9890]
## Observed behavior
On first load of the Library page, if full screen on a laptop or monitor, the Library page displays a large version of the "middle sized screen" layout. 

<img width="1438" alt="Screen Shot 2022-12-02 at 12 20 56 PM" src="https://user-images.githubusercontent.com/17235236/205349323-40b014d9-d28b-4759-96cf-b1125e23eb07.png">

…

## Errors and logs
No errors apparent in the console

…

## Expected behavior
Desktop should have embedded sidebar display

## Steps to reproduce
Navigate to Library page on full screen desktop (don't have the console open)

## Context
`develop`
Mac OS/Chrome

**Comment by nucleogenesis** [comment]
I'm not able to replicate this issue on develop right now

https://user-images.githubusercontent.com/6356129/206319420-7c5a0b55-8003-4681-83ab-67388dc31a0b.mp4

**Comment by pcenov** [comment]
Hi @marcellamaki I'm also not able to replicate this one on the latest develop. Tried in both Ubuntu Chrome/Firefox and Mac Safari/Chrome.

**Comment by marcellamaki** [comment]
Thank you @pcenov and @nucleogenesis - let's close this as resolved and we can reopen as needed.
