### ISSUE TITLE
Device Setting Updates: Ensure new Device Settings update the user's experience

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9960]
## Overview 

This issue is a full-stack issue that makes sure all of the new device settings that have been implemented actually are used within the UI and are correctly updating the user's experience. It should be completed after the earlier device settings issues are finished, or at the same time as the remaining issues. 

## Acceptance Criteria
- [ ]  On the new device settings page, each of the new settings, when selected, not only updates that UI, but the saved values actually change the user's experience in accordance with that change 

## References 
- [Notion project page](https://www.notion.so/learningequality/Updates-to-Device-Settings-45529cbcc4f74aeb9b19559228c97579)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#1959b753421648308fb467e21bdaa125)

**Comment by DivyanshSingh12** [comment]
Hi! I would like to contribute can you explain it

**Comment by jredrejo** [comment]
@marcellamaki I've been adding some of the missing parts, but when beginning to work on the auto-download and its properties I don't have enough context. There's almost no info in the notion pages. Is there any documentation you can link to know how these settings should work?

**Comment by marcellamaki** [comment]
Hi @jredrejo - I think @rtibbles would be much better equipped to help here, as I suspect he might have something in mind :)  Let's remember to mention this during the planning meeting.
