### ISSUE TITLE
The completion modal for a .pdf resource get's displayed prematurely when using the bookmarks 

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9983]
## Observed behavior
The completion modal for a .pdf resource get's displayed prematurely when using the bookmarks and this happens every time I open the .pdf file until it actually gets completed.

## Expected behavior
The .pdf resource should be marked as completed only after it actually is completed. 

## Steps to reproduce the issue
1. Install the the following [build ](https://buildkite.com/learningequality/kolibri-python-package/builds/6937) 
2. While viewing a .pdf file (for example one from the QA Channel) first click a bookmark bringing you to the end of the document and then scroll down to complete the pdf.

## Video

https://user-images.githubusercontent.com/79847249/211343071-2c9ad481-2708-44f4-b572-1cfbf447c5c9.mp4

## Usage Details
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Fixed in #9985
