### ISSUE TITLE
Allow PIN creation from the facility settings page

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#9992]
## Observed behaviour
As a device admin, I should be able to create a PIN from the facility page so that I can manage my facility settings.

## Expected behaviour

The user should be prompted to enter a four-digit PIN 
After clicking the create a PIN button

## Steps to reproduce
Navigate to the facility settings page

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/10074
